### ISSUE TITLE
missing data with cf =1 when creating new ks and table and inserting data during bootstrap

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1000]
Start a 3 node cluster. Bootstrap a new node, node4, when "Beginning stream session" is seen on node 4, start insert a new kesypace and table (ks1.cf1) and insert data (1000 rows), with cf=1. When node4 completes bootstrapping, we should see all the 1000 rows of data in kd1.cf1.

This issue exists both on c* and scylla. 

```
FAIL: add_new_node_while_add_new_table_during_bootstrapping_test (update_cluster_layout_tests.TestUpdateClusterLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asias/src/cloudius-systems/scylla-dtest/update_cluster_layout_tests.py", line 1031, in add_new_node_while
_add_new_table_during_bootstrapping_test
    self._add_new_node_while_add_new_table("during");
  File "/home/asias/src/cloudius-systems/scylla-dtest/update_cluster_layout_tests.py", line 1025, in _add_new_node_whil
e_add_new_table
    self.assertEqual(len(result), 1000, len(result))
AssertionError: 933
-------------------- >> begin captured logging << --------------------
```

**Comment by asias** [comment]
Patch is on the list.
