### ISSUE TITLE
Cassandra Stress exits with java.lang.RuntimeException: Encountered exception creating schema

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla#10035]
## Installation details

Kernel Version: 5.11.0-1022-aws

Scylla version (or git commit hash): `4.6~rc4-20220203.34d470967a0` with build-id `bf9a6fccf70cbe9f5c482869342c931fadd4c0b2`

Cluster size: 6 nodes (i3.8xlarge)

Scylla running with shards number (live nodes):
- longevity-1000-keyspaces-4-6-db-node-de655ac8-1 (3.236.75.84 | 10.0.2.190) (shards: 32)
- longevity-1000-keyspaces-4-6-db-node-de655ac8-2 (18.204.44.88 | 10.0.2.193) (shards: 32)
- longevity-1000-keyspaces-4-6-db-node-de655ac8-3 (54.147.100.244 | 10.0.3.91) (shards: 32)
- longevity-1000-keyspaces-4-6-db-node-de655ac8-4 (3.221.127.193 | 10.0.1.123) (shards: 30)
- longevity-1000-keyspaces-4-6-db-node-de655ac8-5 (35.175.110.1 | 10.0.3.120) (shards: 30)
- longevity-1000-keyspaces-4-6-db-node-de655ac8-6 (54.237.164.206 | 10.0.2.92) (shards: 30)

OS / Image: `ami-06d4532db67cc0577` (aws: us-east-1)

Test: `longevity-multi-keyspaces-60h-test`

Test id: `de655ac8-f125-4097-b957-4e2443ea7a4d`

Test name: `longevity_test/longevity-multi-keyspaces-60h-test`

Test config file(s):

- [longevity-multi-keyspaces.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/91e422f87473efdad90333955dbd09cb8a494fc3/test-cases/longevity/longevity-multi-keyspaces.yaml)

## Issue description
```
< t:2022-02-03 23:49:37,042 f:base.py         l:146  c:RemoteCmdRunner      p:ERROR > Error executing command: "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=RKC24VZK6C836KEMXBT9; cassandra-stress write no-warmup cl=QUORUM n=4000000 -schema keyspace=keyspace460 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=20 -pop seq=1..4000000 -log interval=30 -node 10.0.2.190 -errors skip-unsupported-columns"; Exit status: 1
< t:2022-02-03 23:49:37,043 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > STDOUT: 10.0.2.193:9042; Rack: 1a
< t:2022-02-03 23:49:37,043 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > Datacenter: us-east; Host: /10.0.3.120:9042; Rack: 1a
< t:2022-02-03 23:49:37,043 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > Datacenter: us-east; Host: /10.0.1.123:9042; Rack: 1a
< t:2022-02-03 23:49:37,043 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > Datacenter: us-east; Host: /10.0.3.91:9042; Rack: 1a
< t:2022-02-03 23:49:37,043 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > Datacenter: us-east; Host: /10.0.2.92:9042; Rack: 1a
< t:2022-02-03 23:49:37,043 f:base.py         l:150  c:RemoteCmdRunner      p:DEBUG > STDERR: java.lang.RuntimeException: Encountered exception creating schema
< t:2022-02-03 23:49:37,043 f:base.py         l:150  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:88)
< t:2022-02-03 23:49:37,043 f:base.py         l:150  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:156)
< t:2022-02-03 23:49:37,043 f:base.py         l:150  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.StressAction.run(StressAction.java:57)
< t:2022-02-03 23:49:37,043 f:base.py         l:150  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.Stress.run(Stress.java:143)
< t:2022-02-03 23:49:37,043 f:base.py         l:150  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.Stress.main(Stress.java:62)
< t:2022-02-03 23:49:37,043 f:base.py         l:150  c:RemoteCmdRunner      p:DEBUG > Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.1.123:9042] Timed out waiting for server response
```

```
Feb 03 23:49:36 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 0] schema_tables - Schema version changed to c1499898-1ddc-3f7f-a4ac-b599b5116c56
Feb 03 23:49:36 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 0] migration_manager - Schema merge with 10.0.3.91:0 completed
Feb 03 23:49:36 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 20] schema_tables - Creating keyspace460.counter1 id=ea930db0-854b-11ec-b390-dc3d873ad37f version=84dfb7ad-fc38-3c48-b238-eb1d0dec6759
Feb 03 23:49:36 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 20] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 03 23:49:37 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 20] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 03 23:49:37 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 03 23:49:37 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 03 23:49:38 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 20] schema_tables - Schema version changed to f4e1cfc2-c0cf-3a6e-a50a-fc01104b1494
Feb 03 23:49:38 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 7] schema_tables - Creating keyspace461.counter1 id=f078c210-854b-11ec-99ce-dc4b873ad37f version=d138fbe6-bb33-380e-877c-fb520af12407
Feb 03 23:49:38 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 7] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 03 23:49:39 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 7] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 03 23:49:40 longevity-1000-keyspaces-4-6-db-node-de655ac8-4 scylla[16004]:  [shard 7] schema_tables - Schema version changed to 71bdb948-ccda-3d20-bc71-44374db3f099
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor de655ac8-f125-4097-b957-4e2443ea7a4d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=de655ac8-f125-4097-b957-4e2443ea7a4d)
- Show all stored logs command: `$ hydra investigate show-logs de655ac8-f125-4097-b957-4e2443ea7a4d`

## Logs:
- **db-cluster-de655ac8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/de655ac8-f125-4097-b957-4e2443ea7a4d/20220205_014304/db-cluster-de655ac8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/de655ac8-f125-4097-b957-4e2443ea7a4d/20220205_014304/db-cluster-de655ac8.tar.gz)
- **monitor-set-de655ac8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/de655ac8-f125-4097-b957-4e2443ea7a4d/20220205_014304/monitor-set-de655ac8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/de655ac8-f125-4097-b957-4e2443ea7a4d/20220205_014304/monitor-set-de655ac8.tar.gz)
- **loader-set-de655ac8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/de655ac8-f125-4097-b957-4e2443ea7a4d/20220205_014304/loader-set-de655ac8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/de655ac8-f125-4097-b957-4e2443ea7a4d/20220205_014304/loader-set-de655ac8.tar.gz)
- **sct-runner-de655ac8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/de655ac8-f125-4097-b957-4e2443ea7a4d/20220205_014304/sct-runner-de655ac8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/de655ac8-f125-4097-b957-4e2443ea7a4d/20220205_014304/sct-runner-de655ac8.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.6/job/longevity/job/longevity-multi-keyspaces-60h-test/5/)

**Comment by fgelcer** [comment]
i'm seeing similar java error (coming from the loader):
```
20:12:04.021 [main] DEBUG c.d.driver.core.GuavaCompatibility - Error while checking existence of method Futures.transformAsync
java.lang.NoSuchMethodException: com.google.common.util.concurrent.Futures.transformAsync(com.google.common.util.concurrent.ListenableFuture, com.google.common.util.concurrent.AsyncFunction, java.util.concurrent.Executor)

  at java.base/java.lang.Class.getMethod(Class.java:2108) ~[na:na]
  at com.datastax.driver.core.GuavaCompatibility.methodExists(GuavaCompatibility.java:330) ~[scylla-driver-core-3.10.2-scylla-1-shaded.jar:na]
  at com.datastax.driver.core.GuavaCompatibility.isGuava_19_0_OrHigher(GuavaCompatibility.java:295) ~[scylla-driver-core-3.10.2-scylla-1-shaded.jar:na]
  at com.datastax.driver.core.GuavaCompatibility.selectImplementation(GuavaCompatibility.java:184) ~[scylla-driver-core-3.10.2-scylla-1-shaded.jar:na]
  at com.datastax.driver.core.GuavaCompatibility.<clinit>(GuavaCompatibility.java:58) ~[scylla-driver-core-3.10.2-scylla-1-shaded.jar:na]
  at com.datastax.driver.core.PoolingOptions.<clinit>(PoolingOptions.java:137) ~[scylla-driver-core-3.10.2-scylla-1-shaded.jar:na]
  at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:124) ~[stress.jar:na]
  at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:211) ~[stress.jar:na]
  at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79) ~[stress.jar:na]
  at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69) ~[stress.jar:na]
  at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:228) ~[stress.jar:na]
  at org.apache.cassandra.stress.StressAction.run(StressAction.java:58) ~[stress.jar:na]
  at org.apache.cassandra.stress.Stress.run(Stress.java:143) ~[stress.jar:na]
  at org.apache.cassandra.stress.Stress.main(Stress.java:62) ~[stress.jar:na]
20:12:04.039 [main] INFO  c.d.driver.core.GuavaCompatibility - Detected Guava < 19 in the classpath, using legacy compatibility layer

```

job is rolling upgrade, from 4.5 to 4.6.rc4, but this error is happening before we upgrade a node (so happening for `4.5.3-0.20211223.c8f14886d with build-id 9a5b504c51cbe8feb1217517d6977f7793b2971e`)
