### ISSUE TITLE
backup_restore: test snapshot_test.TestSnapshot.test_basic_snapshot_and_restore_with_refresh failes with smp=2

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1004]
running the test with scylla using smp=1 passes

running the test with scylla using smp=2 fails

using latest ccm and latest dtest
```
export SCYLLA_EXT_OPTS="--smp 2"
shlomi@localhost~/urchin-dtest (master)$ export CASSANDRA_DIR=~/scylla/build/release; pkill -9 scylla; pkill -9 java; rm -Rf core.*; KEEP_TEST_DIR=true REUSE_CLUSTER=false DEBUG=true PRINT_DEBUG=true nosetests -v -s snapshot_test.py:TestSnapshot.test_basic_snapshot_and_restore_with_refresh
test_basic_snapshot_and_restore_with_refresh (snapshot_test.TestSnapshot) ... cluster ccm directory: /home/shlomi/.dtest/dtest-oHlIO1
Making snapshot....
Running snapshot cmd: snapshot ks -cf cf -t basic
snapshot_dir is : /home/shlomi/.dtest/dtest-oHlIO1/test/node1/data/ks/cf-e95c77b0e56f11e5b349000000000001/snapshots/basic
snapshot copy is : /tmp/tmp8_t4QE
Restoring snapshot....
Copying from /tmp/tmp8_t4QE/ks/cf to /home/shlomi/.dtest/dtest-oHlIO1/test/node1/data/ks/cf-ec43e030e56f11e5b349000000000001/
ERROR

======================================================================
ERROR: test_basic_snapshot_and_restore_with_refresh (snapshot_test.TestSnapshot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/snapshot_test.py", line 96, in test_basic_snapshot_and_restore_with_refresh
    self.basic_snapshot_and_restore(use_sstableloader=False)
  File "/home/shlomi/urchin-dtest/snapshot_test.py", line 143, in basic_snapshot_and_restore
    node1.nodetool('refresh ks cf')
  File "/home/shlomi/urchin-ccm/ccmlib/node.py", line 693, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
NodetoolError: Nodetool command '/home/shlomi/scylla/resources/cassandra/bin/nodetool -h localhost -p 7100 refresh ks cf' failed; exit status: 2; stderr: error: /home/shlomi/.dtest/dtest-oHlIO1/test/node1/data/ks/cf-ec43e030e56f11e5b349000000000001/ks-cf-ka-1-Filter.db: file not found
-- StackTrace --
java.lang.RuntimeException: /home/shlomi/.dtest/dtest-oHlIO1/test/node1/data/ks/cf-ec43e030e56f11e5b349000000000001/ks-cf-ka-1-Filter.db: file not found
	at com.scylladb.jmx.api.APIClient.getException(APIClient.java:115)
	at com.scylladb.jmx.api.APIClient.post(APIClient.java:102)
	at org.apache.cassandra.service.StorageService.loadNewSSTables(StorageService.java:1123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-oHlIO1
dtest: DEBUG: Making snapshot....
dtest: DEBUG: Running snapshot cmd: snapshot ks -cf cf -t basic
dtest: DEBUG: snapshot_dir is : /home/shlomi/.dtest/dtest-oHlIO1/test/node1/data/ks/cf-e95c77b0e56f11e5b349000000000001/snapshots/basic
dtest: DEBUG: snapshot copy is : /tmp/tmp8_t4QE
dtest: DEBUG: Restoring snapshot....
dtest: DEBUG: Copying from /tmp/tmp8_t4QE/ks/cf to /home/shlomi/.dtest/dtest-oHlIO1/test/node1/data/ks/cf-ec43e030e56f11e5b349000000000001/
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 16.159s

FAILED (errors=1)
```

checking the snapshot backup directory

```
ls /tmp/tmp8_t4QE/ks/cf/
ks-cf-ka-2-CompressionInfo.db  ks-cf-ka-2-Filter.db      ks-cf-ka-2-Summary.db          ks-cf-ka-3-Data.db      ks-cf-ka-3-Index.db       ks-cf-ka-3-TOC.txt
ks-cf-ka-2-Data.db             ks-cf-ka-2-Index.db       ks-cf-ka-2-TOC.txt             ks-cf-ka-3-Digest.sha1  ks-cf-ka-3-Statistics.db  manifest.json
ks-cf-ka-2-Digest.sha1         ks-cf-ka-2-Statistics.db  ks-cf-ka-3-CompressionInfo.db  ks-cf-ka-3-Filter.db    ks-cf-ka-3-Summary.db
```

there is not ks-cf-ka-1-*

**Comment by slivne** [comment]
marking as showstopper as its not clear if we have a general issue with refresh in smp

**Comment by slivne** [comment]
It seems this is also failing backup_restore_tests.py:TestBackupRestore.replay_restore_no_additional_data_test 

```
shlomi@localhost~/urchin-dtest (master)$ export CASSANDRA_DIR=~/scylla/build/release; pkill -9 scylla; pkill -9 java; rm -Rf core.*; KEEP_TEST_DIR=true REUSE_CLUSTER=false DEBUG=true PRINT_DEBUG=true nosetests -v -s backup_restore_tests.py:TestBackupRestore.replay_restore_no_additional_data_test
replay_restore_no_additional_data_test (backup_restore_tests.TestBackupRestore) ... cluster ccm directory: /home/shlomi/.dtest/dtest-Lu6X1c
Starting a cluster of one node...
Creating a CQL connection...
Creating a keyspace 'ks'...
Creating a column family 'cf'...
Inserting concurrently 1000 keys...
Creating a snapshot...
Snapshot dir is /home/shlomi/.dtest/dtest-Lu6X1c/test/node1/data/ks/cf-7cb431b0e57011e59511000000000001/snapshots/testsnapshot
Dropping a keyspace...
Creating the same keyspace.table...
Flushing a keyspace...
Column family directory is /home/shlomi/.dtest/dtest-Lu6X1c/test/node1/data/ks/cf-7e9d8b20e57011e59511000000000001
Removing sstables...
Copy sstables from the snapshot...
Running 'nodetool refresh -- ks cf' - first take...
Checking rows on node1...
Running 'nodetool refresh -- ks cf' - second take...
ERROR

======================================================================
ERROR: replay_restore_no_additional_data_test (backup_restore_tests.TestBackupRestore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/backup_restore_tests.py", line 240, in replay_restore_no_additional_data_test
    node1.nodetool("refresh -- ks cf")
  File "/home/shlomi/urchin-ccm/ccmlib/node.py", line 693, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
NodetoolError: Nodetool command '/home/shlomi/scylla/resources/cassandra/bin/nodetool -h localhost -p 7100 refresh -- ks cf' failed; exit status: 2; stderr: error: /home/shlomi/.dtest/dtest-Lu6X1c/test/node1/data/ks/cf-7e9d8b20e57011e59511000000000001/ks-cf-ka-1-TOC.txt: file not found
-- StackTrace --
java.lang.RuntimeException: /home/shlomi/.dtest/dtest-Lu6X1c/test/node1/data/ks/cf-7e9d8b20e57011e59511000000000001/ks-cf-ka-1-TOC.txt: file not found
	at com.scylladb.jmx.api.APIClient.getException(APIClient.java:115)
	at com.scylladb.jmx.api.APIClient.post(APIClient.java:102)
	at org.apache.cassandra.service.StorageService.loadNewSSTables(StorageService.java:1123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-Lu6X1c
dtest: DEBUG: Starting a cluster of one node...
dtest: DEBUG: Creating a CQL connection...
dtest: DEBUG: Creating a keyspace 'ks'...
dtest: DEBUG: Creating a column family 'cf'...
dtest: DEBUG: Inserting concurrently 1000 keys...
dtest: DEBUG: Creating a snapshot...
dtest: DEBUG: Snapshot dir is /home/shlomi/.dtest/dtest-Lu6X1c/test/node1/data/ks/cf-7cb431b0e57011e59511000000000001/snapshots/testsnapshot
dtest: DEBUG: Dropping a keyspace...
dtest: DEBUG: Creating the same keyspace.table...
dtest: DEBUG: Flushing a keyspace...
dtest: DEBUG: Column family directory is /home/shlomi/.dtest/dtest-Lu6X1c/test/node1/data/ks/cf-7e9d8b20e57011e59511000000000001
dtest: DEBUG: Removing sstables...
dtest: DEBUG: Copy sstables from the snapshot...
dtest: DEBUG: Running 'nodetool refresh -- ks cf' - first take...
dtest: DEBUG: Checking rows on node1...
dtest: DEBUG: Running 'nodetool refresh -- ks cf' - second take...
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 16.180s

FAILED (errors=1)
```

**Comment by vladzcloudius** [comment]
@slivne `backup_restore_tests.py:TestBackupRestore.replay_restore_no_additional_data_test` works just fine for me with the HEAD 8575f1391fd1e80d8e19cb8bc27e60dfae6b435a

```
pkill -9 java ;rm -Rf ~/.dtest/*;  pkill -9 scylla; KEEP_TEST_DIR=true DEBUG=true PRINT_DEBUG=true nosetests -v -s backup_restore_tests.py:TestBackupRestore.replay_restore_no_additional_data_test 
replay_restore_no_additional_data_test (backup_restore_tests.TestBackupRestore) ... cluster ccm directory: /home/vladz/.dtest/dtest-_HBPD8
Starting a cluster of one node...
Creating a CQL connection...
Creating a keyspace 'ks'...
Creating a column family 'cf'...
Inserting concurrently 1000 keys...
Creating a snapshot...
Snapshot dir is /home/vladz/.dtest/dtest-_HBPD8/test/node1/data/ks/cf-fce7aec0e5ed11e5bea8000000000000/snapshots/testsnapshot
Dropping a keyspace...
Creating the same keyspace.table...
Flushing a keyspace...
Column family directory is /home/vladz/.dtest/dtest-_HBPD8/test/node1/data/ks/cf-fea90dd0e5ed11e5bea8000000000000
Removing sstables...
Copy sstables from the snapshot...
Running 'nodetool refresh -- ks cf' - first take...
Checking rows on node1...
Running 'nodetool refresh -- ks cf' - second take...
Checking rows on node1...
ok

----------------------------------------------------------------------
Ran 1 test in 16.019s

OK
```

**Comment by slivne** [comment]
@vladzcloudius any update ?

**Comment by vladzcloudius** [comment]
On 03/10/2016 02:08 PM, slivne wrote:
>
> @vladzcloudius <https://github.com/vladzcloudius> any update ?
>

Still trying to understand why a second refresh causes the failure and 
deletes all SStables. According to logs both refreshes have successfully 
completed.

**Comment by vladzcloudius** [comment]
@slivne is it a must to have ks-cf-ka-1-*? I see that there isn't this SStable even after I simply create a CF and flush it.

**Comment by slivne** [comment]
I am not the expert on this @glommer / @raphaelsc should probably have an
answer

**Comment by glommer** [comment]
It's okay not to have an SSTable with the generation number 1.
As a matter of fact we're not expecting to see one, since the code that creates generations do _gen * smp_count + shard_id

_gen starts with 1, so for SMP 2, your first two SSTables will be 1 * 2 + 0 = 2, and 1 * 2 + 1 = 3.

If gen started with 0, we'd have an SSTable with generation number 0 (0 * 0 + 0). That's not the end of the world, but we are not sure Cassandra could handle it, since they always use positive numbers. So we start _gen from 1.

**Comment by vladzcloudius** [comment]
On 03/10/2016 03:36 PM, Glauber Costa wrote:
>
> It's okay not to have an SSTable with the generation number 1.
> As a matter of fact we're not expecting to see one, since the code 
> that creates generations do _gen * smp_count + shard_id
>
> _gen starts with 1, so for SMP 2, your first two SSTables will be 1 * 
> 2 + 0 = 2, and 1 * 2 + 1 = 3.
>

This is exactly what I see:

ll /home/vladz/.dtest/dtest-4IF8ms/test/node1/data/ks/cf-26c9bca0e6c111e592c9000000000001/
total 172K
drwx------. 2 vladz vladz 4.0K Mar 10 15:08 .
drwx------. 3 vladz vladz 4.0K Mar 10 15:08 ..
-rwx------. 1 vladz vladz    8 Mar 10 15:08 ks-cf-ka-2-CRC.db
-rwx------. 1 vladz vladz  44K Mar 10 15:08 ks-cf-ka-2-Data.db
-rwx------. 1 vladz vladz   10 Mar 10 15:08 ks-cf-ka-2-Digest.sha1
-rwx------. 1 vladz vladz  664 Mar 10 15:08 ks-cf-ka-2-Filter.db
-rwx------. 1 vladz vladz 9.2K Mar 10 15:08 ks-cf-ka-2-Index.db
-rwx------. 1 vladz vladz 4.4K Mar 10 15:08 ks-cf-ka-2-Statistics.db
-rwx------. 1 vladz vladz  118 Mar 10 15:08 ks-cf-ka-2-Summary.db
-rwx------. 1 vladz vladz   79 Mar 10 15:08 ks-cf-ka-2-TOC.txt
-rwx------. 1 vladz vladz    8 Mar 10 15:08 ks-cf-ka-3-CRC.db
-rwx------. 1 vladz vladz  40K Mar 10 15:08 ks-cf-ka-3-Data.db
-rwx------. 1 vladz vladz   10 Mar 10 15:08 ks-cf-ka-3-Digest.sha1
-rwx------. 1 vladz vladz  608 Mar 10 15:08 ks-cf-ka-3-Filter.db
-rwx------. 1 vladz vladz 8.4K Mar 10 15:08 ks-cf-ka-3-Index.db
-rwx------. 1 vladz vladz 4.4K Mar 10 15:08 ks-cf-ka-3-Statistics.db
-rwx------. 1 vladz vladz  104 Mar 10 15:08 ks-cf-ka-3-Summary.db
-rwx------. 1 vladz vladz   79 Mar 10 15:08 ks-cf-ka-3-TOC.txt

However due to some bug (I'm still looking for it) the second /refresh/ 
fails and in the error message we see the following:

NodetoolError: Nodetool command '/home/vladz/work/urchin/resources/cassandra/bin/nodetool -h localhost -p 7100 refresh -- ks cf' failed; exit status: 2; stderr: error: /home/vladz/.dtest/dtest-iR7rXj/test/node1/data/ks/cf-3d1f4570e6ca11e5b0ed000000000001/ks-cf-ka-1-Filter.db: file not found
-- StackTrace --
java.lang.RuntimeException: /home/vladz/.dtest/dtest-iR7rXj/test/node1/data/ks/cf-3d1f4570e6ca11e5b0ed000000000001/ks-cf-ka-1-Filter.db: file not found
         at com.scylladb.jmx.api.APIClient.getException(APIClient.java:115)
         at com.scylladb.jmx.api.APIClient.post(APIClient.java:102)


(note that the two listings above are from different test runs).

**Comment by vladzcloudius** [comment]
@slivne According to logs during the second _refresh_ shard 1 succeeds to read `Filter.db` while shard 0 fails to do so right after it (in the original error report it was TOC.db):
```
INFO  2016-03-13 12:31:17,263 [shard 1] storage_service - Loading new SSTables for ks.cf...
DEBUG 2016-03-13 12:31:17,266 [shard 1] storage_service - Loading new sstables with generation numbers larger or equal than 1
DEBUG 2016-03-13 12:31:17,285 [shard 1] sstable - Reading TOC file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-TOC.txt
DEBUG 2016-03-13 12:31:17,296 [shard 1] sstable - Reading TOC file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-2-TOC.txt
DEBUG 2016-03-13 12:31:17,297 [shard 1] storage_service - Now accepting writes for sstables with generation larger or equal than 2
INFO  2016-03-13 12:31:17,297 [shard 1] storage_service - CF ks.cf at shard 1 had SSTables writes disabled for 33126 usec
INFO  2016-03-13 12:31:17,305 [shard 0] storage_service - CF ks.cf at shard 0 had SSTables writes disabled for 41836 usec
DEBUG 2016-03-13 12:31:17,306 [shard 1] sstable - Reading TOC file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-TOC.txt
DEBUG 2016-03-13 12:31:17,306 [shard 1] sstable - Reading TOC file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-2-TOC.txt
DEBUG 2016-03-13 12:31:17,306 [shard 0] sstable - Reading TOC file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-TOC.txt
DEBUG 2016-03-13 12:31:17,306 [shard 0] sstable - Reading TOC file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-2-TOC.txt
DEBUG 2016-03-13 12:31:17,307 [shard 1] sstable - Reading Statistics.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-2-Statistics.db
DEBUG 2016-03-13 12:31:17,307 [shard 1] sstable - Reading Statistics.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-Statistics.db
DEBUG 2016-03-13 12:31:17,314 [shard 1] sstable - Reading Filter.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-2-Filter.db
DEBUG 2016-03-13 12:31:17,314 [shard 1] sstable - Reading Filter.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-Filter.db
DEBUG 2016-03-13 12:31:17,315 [shard 1] sstable - Reading Summary.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-2-Summary.db
DEBUG 2016-03-13 12:31:17,315 [shard 1] sstable - Reading Summary.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-Summary.db
INFO  2016-03-13 12:31:17,315 [shard 1] storage_service - Done loading new SSTables for ks.cf
DEBUG 2016-03-13 12:31:17,324 [shard 0] sstable - Reading Statistics.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-2-Statistics.db
DEBUG 2016-03-13 12:31:17,324 [shard 0] sstable - Reading Statistics.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-Statistics.db
DEBUG 2016-03-13 12:31:17,342 [shard 0] sstable - Reading Filter.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-2-Filter.db
DEBUG 2016-03-13 12:31:17,342 [shard 0] sstable - Reading Filter.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-Filter.db
DEBUG 2016-03-13 12:31:17,348 [shard 0] sstable - Reading Summary.db file /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-2-Summary.db
```

and the test fails as follows:
```
Flushing a keyspace...
Running 'nodetool refresh -- ks cf' - second take...
ERROR

======================================================================
ERROR: replay_restore_no_additional_data_test (backup_restore_tests.TestBackupRestore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vladz/work/scylla-dtest/backup_restore_tests.py", line 243, in replay_restore_no_additional_data_test
    node1.nodetool("refresh -- ks cf")
  File "/home/vladz/work/scylla-ccm/ccmlib/node.py", line 693, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
NodetoolError: Nodetool command '/home/vladz/work/urchin/resources/cassandra/bin/nodetool -h localhost -p 7100 refresh -- ks cf' failed; exit status: 2; stderr: error: /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-Filter.db: file not found
-- StackTrace --
java.lang.RuntimeException: /home/vladz/.dtest/dtest-pe5qm8/test/node1/data/ks/cf-b5493ea0e90611e599b9000000000001/ks-cf-ka-1-Filter.db: file not found
        at com.scylladb.jmx.api.APIClient.getException(APIClient.java:115)
        at com.scylladb.jmx.api.APIClient.post(APIClient.java:102)
        at org.apache.cassandra.service.StorageService.loadNewSSTables(StorageService.java:1123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)

```

**Comment by vladzcloudius** [comment]
I've printed the content of the SStable directory right before the second `nodetool refresh` call:
```
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-2-Filter.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-2-Summary.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-1-Digest.sha1
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-1-Statistics.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-1-Summary.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-1-CRC.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-1-TOC.txt
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-1-Index.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-1-Data.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-2-Data.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-2-Index.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-2-Statistics.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-1-Filter.db
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-2-Digest.sha1
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-2-TOC.txt
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/manifest.json
/home/vladz/.dtest/dtest-nTPvJP/test/node1/data/ks/cf-3961ac90e90c11e59da8000000000001/ks-cf-ka-2-CRC.db
```
No .tmp files or something like that as in #1014 
After the failure the above directory has only `manifest.json` file. All other files above are gone.
