### ISSUE TITLE
scylla image setup fails with ValueError

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla#10082]
_Installation details_ 
Kernel version: `5.11.0-1028-aws` 
Scylla version (or git commit hash): `5.1.dev-0.20220207.c020ed738 with build-id 9e5a8c9f13250e7c84efa1ed1d2e61f82eec0e4a` 
Cluster size: 3 nodes (i3.4xlarge) 
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-059369771bc43bf3e` (aws: eu-east-1)

Scylla running with shards number (live nodes): 
perf-regression-latency-perf-v8-db-node-dbfa9cac-1 (3.85.142.219 | 172.30.0.19)
perf-regression-latency-perf-v8-db-node-dbfa9cac-2 (18.212.9.121 | 172.30.0.73)
perf-regression-latency-perf-v8-db-node-dbfa9cac-3 (54.144.113.235 | 172.30.0.169)

Test: `scylla-master-perf-regression-aws-test-latency` Test name: `performance_regression_test.PerformanceRegressionTest.test_latency` Test config file(s):

* [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/911515140d749e19692c701b197c1a56de0eb05f/test-cases/performance/perf-regression-latency-500gb-30min.yaml)

**Issue description** 

Scylla machine image setup fails with the following error:

```
2022-02-15T09:46:32+00:00  perf-regression-latency-perf-v8-db-node-dbfa9cac-1 !NOTICE  | sudo: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/rm -rf /var/lib/scylla/data
...
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11275]: 2022-02-15 09:46:32,563 - [scylla_configure] - INFO - Disabling Scylla start on first boot
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11275]: 2022-02-15 09:46:32,563 - [scylla_configure] - INFO - Disabling Scylla start on first boot
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11275]: Disabling Scylla start on first boot
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11275]: 2022-02-15 09:46:32,563 - [scylla_configure] - INFO - Create scylla data devices as auto
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11275]: Create scylla data devices as auto
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11275]: Disabling Scylla start on first boot
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11275]: 2022-02-15 09:46:32,563 - [scylla_configure] - INFO - Create scylla data devices as auto
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11275]: Create scylla data devices as auto
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11305]: Devices: ['/dev/nvme1n1', '/dev/nvme0n1']
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11305]: Devices: ['/dev/nvme1n1', '/dev/nvme0n1']
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11305]: /var/lib/scylla is already mounted. Will not run 'scylla_raid_setup'!
2022-02-15T09:46:32+00:00 ... !INFO    | scylla_image_setup[11305]: /var/lib/scylla is already mounted. Will not run 'scylla_raid_setup'!
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]: Traceback (most recent call last):
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]:   File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 75, in <module>
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]:     cpuset = hex2list(rps_cpus) 
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]:   File "/opt/scylladb/scripts/scylla_util.py", line 135, in hex2list
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]: Traceback (most recent call last):
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]:   File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 75, in <module>
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]:     cpuset = hex2list(rps_cpus) 
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]:   File "/opt/scylladb/scripts/scylla_util.py", line 135, in hex2list
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]:     hex_int = int(hex_str2, 16) 
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]: ValueError: invalid literal for int() with base 16: "/var/lib/scylla/data doesn't exist - skipping\n0000fefe"
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]:     hex_int = int(hex_str2, 16) 
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11316]: ValueError: invalid literal for int() with base 16: "/var/lib/scylla/data doesn't exist - skipping\n0000fefe"
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]: Traceback (most recent call last):
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]: Traceback (most recent call last):
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 32, in <module>
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]:     run('/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami', shell=True, check=True)
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 32, in <module>
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]:     run('/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami', shell=True, check=True)
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]:     raise CalledProcessError(retcode, process.args, 
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]:     raise CalledProcessError(retcode, process.args, 
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]: subprocess.CalledProcessError: Command '/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami' returned non-zero exit status 1.
2022-02-15T09:46:33+00:00 ... !INFO    | scylla_image_setup[11265]: subprocess.CalledProcessError: Command '/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami' returned non-zero exit status 1.
```

Restore Monitor Stack command: `$ hydra investigate show-monitor dbfa9cac-3a26-4ee1-b399-39780828a0fb` 
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=dbfa9cac-3a26-4ee1-b399-39780828a0fb) 
Show all stored logs command: `$ hydra investigate show-logs dbfa9cac-3a26-4ee1-b399-39780828a0fb`

Test id: `dbfa9cac-3a26-4ee1-b399-39780828a0fb`

Logs: 
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/dbfa9cac-3a26-4ee1-b399-39780828a0fb/20220215_094651/db-cluster-dbfa9cac.zip
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/dbfa9cac-3a26-4ee1-b399-39780828a0fb/20220215_094651/loader-set-dbfa9cac.zip 
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/dbfa9cac-3a26-4ee1-b399-39780828a0fb/20220215_094651/monitor-set-dbfa9cac.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/dbfa9cac-3a26-4ee1-b399-39780828a0fb/20220215_094651/sct-runner-dbfa9cac.zip

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-latency/168)

**Comment by nyh** [comment]
I think you opened this issue in the wrong repository. Should probably open it in https://github.com/scylladb/scylla-machine-image ?

**Comment by nyh** [comment]
I hope I didn't mislead you. The script "scylla_sysconfig_setup" is actually in the Scylla repository... :-( I don't know if the problem is in this script or something in the image... 
You can re-open this issue if you realize that this was the right repository all along... Sorry.

**Comment by syuu1228** [comment]
Reopened the issue, since I think scylla_sysconfig_setup has a bug, even it looks like caused because the nightly machine image is broken.

I found that scylla_sysconfig_setup retrieves following output from perftune.py, and failed to convert from HEX string to int:
```
/var/lib/scylla/data doesn't exist - skipping
0000fefe
```

This warning message is caused because the machine-image is failed to configure /var/lib/scylla properly, won't be able to happen on correctly configure environment.
But I think scylla_sysconfig_setup should be able to parse this.
Because perftune.py is not causing error (it exits with 0), and still returning CPU mask.

**Comment by avikivity** [comment]
Backported to 5.0.
