### ISSUE TITLE
scylla_raid_setup failed (Scylla 4.3 on CentOS8) with error - Command '['systemctl', 'start', 'var-lib-scylla.mount']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#10110]
during rolling upgrade test for 2021.1, we have started a test from `4.3.6` and it failed just after installing it from https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-4.3.repo with error:

```
< t:2022-02-16 10:57:05,117 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3 --no-io-setup  --swap-directory / "; Exit status: 1
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/tester.py", line 121, in wrapper
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 110, in inner
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/tester.py", line 490, in setUp
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     self.init_nodes(db_cluster=self.db_cluster)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/tester.py", line 441, in init_nodes
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     db_cluster.wait_for_init(node_list=db_cluster.nodes)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/cluster.py", line 3562, in wrapper
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     verify_node_setup(start_time)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/cluster.py", line 3536, in verify_node_setup
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     raise NodeSetupFailed(node=node, error_msg=setup_exception[0], traceback_str=setup_exception[1])
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > sdcm.cluster.NodeSetupFailed: [Node rolling-upgrade-2021-1-centos-db-node-84c9bfda-0-1 [34.139.28.42 | 10.142.0.112] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3 --no-io-setup  --swap-directory / '
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Exit code: 1
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Stdout:
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > data     =                       bsize=4096   blocks=294812928, imaxpct=5
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >          =                       sunit=256    swidth=768 blks
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > log      =internal log           bsize=4096   blocks=143951, version=2
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >          =                       sectsz=4096  sunit=1 blks, lazy-count=1
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > realtime =none                   extsz=4096   blocks=0, rtextents=0
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > /dev/md0 will be used to setup a RAID
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Creating RAID0 for scylla using 3 disk(s): /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > You current Scylla release is 4.3.6 the latest minor release is 4.5.3 go to http://www.scylladb.com for upgrade instructions
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > RAID setup failed.
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Stderr:
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 186, in <module>
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     mount.start()
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/opt/scylladb/scripts/scylla_util.py", line 765, in start
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return run('systemctl {} start {}'.format(self.ctlparam, self._unit))
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/opt/scylladb/scripts/scylla_util.py", line 513, in run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return subprocess.run(cmd, stdout=stdout, stderr=stderr, shell=shell, check=exception, env=scylla_env).returncode
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 512, in run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     raise CalledProcessError(retcode, process.args,
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > subprocess.CalledProcessError: Command '['systemctl', 'start', 'var-lib-scylla.mount']' returned non-zero exit status 1.
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/cluster.py", line 3525, in node_setup
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     cl_inst.node_setup(_node, **setup_kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/cluster.py", line 4216, in node_setup
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     self._scylla_post_install(node, install_scylla, devname)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/cluster.py", line 4288, in _scylla_post_install
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     node.scylla_setup(disks, devname)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 110, in inner
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/cluster.py", line 2364, in scylla_setup
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --no-io-setup {}'
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     result = _run()
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return func(*args, **kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/enterprise-2021.1/rolling-upgrade/rolling-upgrade-centos8-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     result = connection.run(**command_kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "<decorator-gen-3>", line 2, in run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return method(self, *args, **kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return self._run(self._remote_runner(), command, **kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return runner.run(command, **kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return self._run_body(command, **kwargs)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     raise UnexpectedExit(result)
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3 --no-io-setup  --swap-directory / '
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Exit code: 1
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Stdout:
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > data     =                       bsize=4096   blocks=294812928, imaxpct=5
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >          =                       sunit=256    swidth=768 blks
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > log      =internal log           bsize=4096   blocks=143951, version=2
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >          =                       sectsz=4096  sunit=1 blks, lazy-count=1
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > realtime =none                   extsz=4096   blocks=0, rtextents=0
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > /dev/md0 will be used to setup a RAID
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Creating RAID0 for scylla using 3 disk(s): /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > You current Scylla release is 4.3.6 the latest minor release is 4.5.3 go to http://www.scylladb.com for upgrade instructions
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > RAID setup failed.
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Stderr:
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 186, in <module>
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     mount.start()
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/opt/scylladb/scripts/scylla_util.py", line 765, in start
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return run('systemctl {} start {}'.format(self.ctlparam, self._unit))
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/opt/scylladb/scripts/scylla_util.py", line 513, in run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return subprocess.run(cmd, stdout=stdout, stderr=stderr, shell=shell, check=exception, env=scylla_env).returncode
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 512, in run
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     raise CalledProcessError(retcode, process.args,
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > subprocess.CalledProcessError: Command '['systemctl', 'start', 'var-lib-scylla.mount']' returned non-zero exit status 1.
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,142 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
< t:2022-02-16 10:57:05,146 f:tester.py       l:2022 c:UpgradeTest          p:INFO  > TearDown is starting...
```

`kernel version: 4.18.0-358.el8.x86_64`

[db logs](https://cloudius-jenkins-test.s3.amazonaws.com/84c9bfda-7402-4c43-a36e-71b0108de683/20220216_105746/db-cluster-84c9bfda.tar.gz)
[sct logs](https://cloudius-jenkins-test.s3.amazonaws.com/84c9bfda-7402-4c43-a36e-71b0108de683/20220216_105746/sct-runner-84c9bfda.tar.gz)

**Comment by roydahan** [comment]
It was decided that since 4.3 is EOL, the test of 4.3 upgrade to 2021.1 will be disabled.
@fgelcer please take care of it.
