### ISSUE TITLE
[scylla 4.6] disable_tombstone_removal_during_reshard_test regression

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10182]
The disable_tombstone_removal_during_reshard_test dtest started failing in https://jenkins.scylladb.com/job/scylla-4.6/job/dtest-release/41/testReport/junit/resharding_test/ReshardingTombstones_with_TimeWindowCompactionStrategy/disable_tombstone_removal_during_reshard_test/
scylla version f85cd289bcfca774e34794cd751a68af711f25fa
scylladb/scylla-dtest@a3e9f3ee92dad634adebcefc705288a1217e4121
scylladb/scylla-ccm@7939d07c1588016fa9a6f8e9f1f9792980a9f706
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-4.6/dtest-release/scylla-dtest/resharding_test.py", line 274, in disable_tombstone_removal_during_reshard_test
    node1.wait_for_compactions()
  File "/jenkins/workspace/scylla-4.6/dtest-release/scylla-ccm/ccmlib/node.py", line 761, in wait_for_compactions
    raise TimeoutError(f"Waiting for compactions timed out after {idle_timeout} seconds with {pending_tasks} pending tasks remaining.")
ccmlib.node.TimeoutError: Waiting for compactions timed out after 300 seconds with 1 pending tasks remaining.
```

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/job/scylla-4.6/job/dtest-release/41/artifact/logs-all.release.2/dtest.log
```
2022-01-21 09:35:42,030 1277426 dtest                          DEBUG    | resharding_test.py:ReshardingTombstones_with_TimeWindowCompactionStrategy.disable_tombstone_removal_during_reshard_test - Inserting data and waiting for new compaction

2022-01-21 09:40:47,893 1277426 dtest                          DEBUG    | resharding_test.py:ReshardingTombstones_with_TimeWindowCompactionStrategy.disable_tombstone_removal_during_reshard_test - Test failed with errors: [(<resharding_test.ReshardingTombstones_with_TimeWindowCompactionStrategy testMethod=disable_tombstone_removal_during_reshard_test>, (<class 'ccmlib.node.TimeoutError'>, TimeoutError('Waiting for compactions timed out after 300 seconds with 1 pending tasks remaining.'), <traceback object at 0x7f6e114ec190>))]
```

https://jenkins.scylladb.com/job/scylla-4.6/job/dtest-release/41/artifact/logs-all.release.2/1642758050901_resharding_test.ReshardingTombstones_with_TimeWindowCompactionStrategy.disable_tombstone_removal_during_reshard_test/node1.log
```
INFO  2022-01-21 09:35:44,721 [shard 1] compaction - [Compact ks1.cf1 81c41c10-7a9d-11ec-ae39-1497238c5363] Compacting [/jenkins/workspace/scylla-4.6/dtest-release/scylla/.dtest/dtest-4z4u4mlq/test/node1/data/ks1/cf1-76de7f707a9d11ecae391497238c5363/md-9-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-4.6/dtest-release/scylla/.dtest/dtest-4z4u4mlq/test/node1/data/ks1/cf1-76de7f707a9d11ecae391497238c5363/md-7-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-4.6/dtest-release/scylla/.dtest/dtest-4z4u4mlq/test/node1/data/ks1/cf1-76de7f707a9d11ecae391497238c5363/md-5-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-4.6/dtest-release/scylla/.dtest/dtest-4z4u4mlq/test/node1/data/ks1/cf1-76de7f707a9d11ecae391497238c5363/md-3-big-Data.db:level=0:origin=memtable]
INFO  2022-01-21 09:35:44,726 [shard 1] compaction - [Compact ks1.cf1 81c41c10-7a9d-11ec-ae39-1497238c5363] Compacted 4 sstables to [/jenkins/workspace/scylla-4.6/dtest-release/scylla/.dtest/dtest-4z4u4mlq/test/node1/data/ks1/cf1-76de7f707a9d11ecae391497238c5363/md-11-big-Data.db:level=0]. 199kB to 5kB (~2% of original) in 3ms = 1MB/s. ~512 total partitions merged to 1.
INFO  2022-01-21 09:40:47,893 [shard 0] compaction_manager - Asked to stop
```

It looks like the node did run compaction, but there's still 1 pending based on the api estimation.
Could be an accounting issue.

@raphaelsc please look into this.

**Comment by bhalevy** [comment]
Likely caused by scylladb/seastar#1012.
Closing...
