### ISSUE TITLE
CQL Syntax error when creating a Service Level with workload_type attribute

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla#10235]
*Installation details*
Kernel version: `5.11.0-1028-aws`
Scylla version (or git commit hash): `5.1.dev-0.20220303.0544973b15dd with build-id 3b69cb8b4d61d8190175613119fcc982a0b5eddb`
Cluster size: 3 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   system-sla-sla-work-db-node-a90844ac-1 (13.40.4.87 | 10.0.2.5): 8 shards
   system-sla-sla-work-db-node-a90844ac-2 (35.177.28.67 | 10.0.1.205): 8 shards
   system-sla-sla-work-db-node-a90844ac-3 (35.178.64.9 | 10.0.0.127): 8 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0286e6a18e17e2595` (aws: eu-west-2)

Test: `mc-sla-test`
Test name: `sla_per_user_system_test.SlaPerUserTest.test_workload_type`
Test config file(s):
- [system-sla-test.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/86c130602e72783bb5ab87d9631ac20e4be36ac5/test-cases/features/system-sla-test.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/86c130602e72783bb5ab87d9631ac20e4be36ac5/test-cases/features/system-sla-test.yaml&source=gmail-html&ust=1647614470494000&usg=AOvVaw2NONZkUoC90slvwLrB9643))

**Issue description**

====================================

During a test run for working on an SCT test for the Service Levels `workload_type` feature we received the following error:

```
2022-03-17 13:04:34.071: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=d23218f3-efc5-4a34-b82c-5d527d4c1cd8, source=SlaPerUserTest.test_workload_type (sla_per_user_system_test.SlaPerUserTest)() message=Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sla_per_user_system_test.py", line 594, in test_workload_type
    batch_role.attach_service_level(batch_sla)
  File "/home/ubuntu/scylla-cluster-tests/test_lib/sla.py", line 236, in attach_service_level
    self.session.execute(query)
  File "cassandra/cluster.py", line 2627, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4893, in cassandra.cluster.ResponseFuture.result
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:32 no viable alternative at input 'batch'">
```

This happens when we're attempting to create 2 Service Levels:

```
< t:2022-03-17 13:03:59,263 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress write cl=QUORUM n=100000 -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native user=cassandra password=cassandra -rate threads=250
< t:2022-03-17 13:03:59,269 f:connectionpool.py l:228  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 10.0.3.227:3000
< t:2022-03-17 13:03:59,276 f:sla.py          l:326  c:test_lib.sla         p:INFO  > Role "interactive" has been created
< t:2022-03-17 13:03:59,276 f:sla.py          l:324  c:test_lib.sla         p:INFO  > CREATE role query: CREATE ROLE 'batch' WITH password = 'batch' AND login = True
< t:2022-03-17 13:03:59,277 f:connectionpool.py l:456  c:urllib3.connectionpool p:DEBUG > http://10.0.3.227:3000 "POST /api/annotations HTTP/1.1" 200 38
< t:2022-03-17 13:03:59,284 f:sla.py          l:326  c:test_lib.sla         p:INFO  > Role "batch" has been created
< t:2022-03-17 13:03:59,285 f:sla.py          l:139  c:test_lib.sla         p:INFO  > Create service level query: CREATE SERVICE_LEVEL IF NOT EXISTS 'interactive' WITH workload_type = 'interactive'
< t:2022-03-17 13:03:59,291 f:sla.py          l:141  c:test_lib.sla         p:INFO  > Service level "'interactive'" has been created
< t:2022-03-17 13:03:59,291 f:sla.py          l:139  c:test_lib.sla         p:INFO  > Create service level query: CREATE SERVICE_LEVEL IF NOT EXISTS 'batch' WITH workload_type = 'batch'
< t:2022-03-17 13:03:59,297 f:sla.py          l:141  c:test_lib.sla         p:INFO  > Service level "'batch'" has been created
< t:2022-03-17 13:03:59,297 f:sla.py          l:235  c:test_lib.sla         p:DEBUG > Attach service level query: ATTACH SERVICE_LEVEL 'interactive' TO interactive
< t:2022-03-17 13:03:59,298 f:sla.py          l:237  c:test_lib.sla         p:DEBUG > Service level "'interactive'" has been attached to interactive role
< t:2022-03-17 13:03:59,298 f:sla.py          l:235  c:test_lib.sla         p:DEBUG > Attach service level query: ATTACH SERVICE_LEVEL 'batch' TO batch
< t:2022-03-17 13:03:59,304 f:events_processes.py l:146  c:sdcm.sct_events.events_processes p:DEBUG > Get process `MainDevice' from EventsProcessesRegistry[lod_dir=/home/ubuntu/sct-results/20220317-123507-242865,id=0x7fbe79cdf5e0,default=True]
< t:2022-03-17 13:03:59,304 f:tester.py       l:195  c:silence              p:DEBUG > Finished 'Sending test end event'. No errors were silenced.
< t:2022-03-17 13:03:59,304 f:tester.py       l:2332 c:SlaPerUserTest       p:INFO  > TearDown is starting...
```

The db logs show the Service Level as created:
```
Mar 17 13:02:59 system-sla-sla-work-db-node-a90844ac-1 scylla[10262]:  [shard 0] compaction - [Compact system_schema.scylla_tables 927061b0-a5f2-11ec-9122-c2f93482a107] Compacting [/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/me-136-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/me-128-big-Data.db:level=0:origin=compaction]
Mar 17 13:02:59 system-sla-sla-work-db-node-a90844ac-1 scylla[10262]:  [shard 0] compaction - [Compact system_schema.scylla_tables 927061b0-a5f2-11ec-9122-c2f93482a107] Compacted 2 sstables to [/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/me-144-big-Data.db:level=0]. 27kB to 14kB (~51% of original) in 12ms = 1MB/s. ~256 total partitions merged to 7.
Mar 17 13:02:59 system-sla-sla-work-db-node-a90844ac-1 scylla[10262]:  [shard 0] compaction - [Compact system_schema.keyspaces 9272aba0-a5f2-11ec-9122-c2f93482a107] Compacting [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/me-232-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/me-224-big-Data.db:level=0:origin=compaction]
Mar 17 13:02:59 system-sla-sla-work-db-node-a90844ac-1 scylla[10262]:  [shard 0] compaction - [Compact system_schema.keyspaces 9272aba0-a5f2-11ec-9122-c2f93482a107] Compacted 2 sstables to [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/me-240-big-Data.db:level=0]. 26kB to 13kB (~50% of original) in 13ms = 1MB/s. ~256 total partitions merged to 7.
Mar 17 13:04:05 system-sla-sla-work-db-node-a90844ac-1 scylla[10262]:  [shard 0] service_level_controller - service level "batch" was added.
Mar 17 13:04:05 system-sla-sla-work-db-node-a90844ac-1 scylla[10262]:  [shard 0] service_level_controller - service level "interactive" was added.
```

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor a90844ac-597b-43f9-a469-9b9d39d65514`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=sla-workload-tests&test_id=a90844ac-597b-43f9-a469-9b9d39d65514](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dsla-workload-tests%26test_id%3Da90844ac-597b-43f9-a469-9b9d39d65514&source=gmail-html&ust=1647614470494000&usg=AOvVaw0Bc4NBHgJPJgJ7q9b9M0Lk))
Show all stored logs command: `$ hydra investigate show-logs a90844ac-597b-43f9-a469-9b9d39d65514`

Test id: `a90844ac-597b-43f9-a469-9b9d39d65514`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_130437/grafana-screenshot-mc-sla-test-scylla-per-server-metrics-nemesis-20220317_130551-system-sla-sla-work-monitor-node-a90844ac-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_130437/grafana-screenshot-mc-sla-test-scylla-per-server-metrics-nemesis-20220317_130551-system-sla-sla-work-monitor-node-a90844ac-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_130437/grafana-screenshot-mc-sla-test-scylla-per-server-metrics-nemesis-20220317_130551-system-sla-sla-work-monitor-node-a90844ac-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_130437/grafana-screenshot-mc-sla-test-scylla-per-server-metrics-nemesis-20220317_130551-system-sla-sla-work-monitor-node-a90844ac-1.png)&source=gmail-html&ust=1647614470494000&usg=AOvVaw27Q8oVx-4r510F2tLbgtd_)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_130437/grafana-screenshot-overview-20220317_130437-system-sla-sla-work-monitor-node-a90844ac-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_130437/grafana-screenshot-overview-20220317_130437-system-sla-sla-work-monitor-node-a90844ac-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_130437/grafana-screenshot-overview-20220317_130437-system-sla-sla-work-monitor-node-a90844ac-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_130437/grafana-screenshot-overview-20220317_130437-system-sla-sla-work-monitor-node-a90844ac-1.png)&source=gmail-html&ust=1647614470494000&usg=AOvVaw1Jm3qihT3CZty3KGdV-AWr)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/db-cluster-a90844ac.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/db-cluster-a90844ac.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/db-cluster-a90844ac.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/db-cluster-a90844ac.tar.gz)&source=gmail-html&ust=1647614470494000&usg=AOvVaw0Sr70wpv4Jype4SdF0_asa)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/loader-set-a90844ac.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/loader-set-a90844ac.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/loader-set-a90844ac.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/loader-set-a90844ac.tar.gz)&source=gmail-html&ust=1647614470494000&usg=AOvVaw3kPQfToZ0sBf2YVeZFhgH_)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/monitor-set-a90844ac.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/monitor-set-a90844ac.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/monitor-set-a90844ac.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/monitor-set-a90844ac.tar.gz)&source=gmail-html&ust=1647614470494000&usg=AOvVaw37pUMF5AZlzg_Ak9RFIuip)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/sct-runner-a90844ac.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/sct-runner-a90844ac.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/sct-runner-a90844ac.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/a90844ac-597b-43f9-a469-9b9d39d65514/20220317_131331/sct-runner-a90844ac.tar.gz)&source=gmail-html&ust=1647614470494000&usg=AOvVaw2pfhp6tnKezTrPbSNEUxHk)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-sla-test/24/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-sla-test/24/&source=gmail-html&ust=1647614470494000&usg=AOvVaw2SIIhw2ytQbaqXvE98ujhu))

**Comment by KnifeyMoloko** [comment]
@slivne Couldn't reproduce the issue while running locally. Looks like the issue was with my test. I'm closing this issue.
