### ISSUE TITLE
Docker commands are not working

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylla#10237]
https://github.com/scylladb/scylla-doc-issues/issues/843

A Scylla user tried running the commands described at https://docs.scylladb.com/operating-scylla/procedures/tips/best-practices-scylla-on-docker/ but failed. See https://github.com/scylladb/scylla-doc-issues/issues/843.

This doesn't seem to be a documentation issue. Could you look into it and help?

PopOS 21.10 (Ubuntu 21.10-based) 64-bit
Linux pop2104 5.16.11-76051611-generic #202202230823164624826121.10~2b22243 SMP PREEMPT Wed Mar 2 20: x86_64 x86_64 x86_64 GNU/Linux

`# testing with latest
» docker exec -it some-scylla nodetool status
nodetool: Scylla API server HTTP GET to URL '/storage_service/ownership/' failed: runtime_exception (runtime error: No nodes present in the cluster. Has this node finished starting up?)
See 'nodetool help' or 'nodetool help <command>'.

» docker exec -it some-scylla cqlsh                                         1 ↵
Connection error: ('Unable to connect to any servers', {'172.17.0.2': error(111, "Tried connecting to [('172.17.0.2', 9042)]. Last error: Connection refused")})

# testing with 4.5
» docker exec -it scylla45 nodetool status
nodetool: Scylla API server HTTP GET to URL '/storage_service/ownership/' failed: runtime_exception (runtime error: No nodes present in the cluster. Has this node finished starting up?)
See 'nodetool help' or 'nodetool help <command>'.

# even tested with docker compose also didn't work
version: '3.3'
services:
  testscylla:
    image: scylladb/scylla # latest
    command: --smp 2 --memory 1G --overprovisioned 1 --developer-mode 1
    ports:
      #- "7000-7001:7000-7001"
      - "19042:9042"
      #- "9160:9160"
      #- "10000:10000"
      #- "7199:7199"

testscylla_1  | 2022-03-16 18:23:31,493 INFO exited: scylla-server (exit status 1; not expected)
testscylla_1  | 2022-03-16 18:23:33,503 INFO spawned: 'scylla-server' with pid 100
testscylla_1  | Scylla version 4.6.0-0.20220306.2f2d22a86 with build-id d487cdea729e95d8caebe2e9e2ae8698f35f19ee starting ...
testscylla_1  | command used: "/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --developer-mode=1 --memory 1G --smp 2 --overprovisioned --listen-address 172.21.0.2 --rpc-address 172.21.0.2 --seed-provider-parameters seeds=172.21.0.2 --alternator-address 172.21.0.2 --blocked-reactor-notify-ms 999999999"
testscylla_1  | parsed command line options: [log-to-syslog, (positional) 1, log-to-stdout, (positional) 0, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, memory, (positional) 1G, smp, (positional) 2, overprovisioned, listen-address: 172.21.0.2, rpc-address: 172.21.0.2, seed-provider-parameters: seeds=172.21.0.2, alternator-address: 172.21.0.2, blocked-reactor-notify-ms, (positional) 999999999]
testscylla_1  | 2022-03-16 18:23:33,865 INFO exited: scylla-server (exit status 1; not expected)
testscylla_1  | Traceback (most recent call last):
testscylla_1  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 209, in <module>
testscylla_1  |     args.func(args)
testscylla_1  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 135, in check_version
testscylla_1  |     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
testscylla_1  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 93, in get_api
testscylla_1  |     return get_json_from_url("http://" + api_address + path)
testscylla_1  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 88, in get_json_from_url
testscylla_1  |     raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
testscylla_1  | RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
testscylla_1  | 2022-03-16 18:23:36,892 INFO spawned: 'scylla-server' with pid 127
testscylla_1  | Scylla version 4.6.0-0.20220306.2f2d22a86 with build-id d487cdea729e95d8caebe2e9e2ae8698f35f19ee starting ...
testscylla_1  | command used: "/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --developer-mode=1 --memory 1G --smp 2 --overprovisioned --listen-address 172.21.0.2 --rpc-address 172.21.0.2 --seed-provider-parameters seeds=172.21.0.2 --alternator-address 172.21.0.2 --blocked-reactor-notify-ms 999999999"
testscylla_1  | parsed command line options: [log-to-syslog, (positional) 1, log-to-stdout, (positional) 0, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, memory, (positional) 1G, smp, (positional) 2, overprovisioned, listen-address: 172.21.0.2, rpc-address: 172.21.0.2, seed-provider-parameters: seeds=172.21.0.2, alternator-address: 172.21.0.2, blocked-reactor-notify-ms, (positional) 999999999]
testscylla_1  | 2022-03-16 18:23:37,205 INFO exited: scylla-server (exit status 1; not expected)
testscylla_1  | 2022-03-16 18:23:38,210 INFO gave up: scylla-server entered FATAL state, too many start retries too quickly`

**Comment by syuu1228** [comment]
Not able to reproduce:
```
[syuu@monster ~]$ docker run --name some-scylla -d scylladb/scylla
Unable to find image 'scylladb/scylla:latest' locally
latest: Pulling from scylladb/scylla
7c3b88808835: Pull complete 
8e33056e129a: Pull complete 
Digest: sha256:b0a9a72d61734c26d0167f61b920964de639e4a9142d854fa973f1c2ca8f6ec3
Status: Downloaded newer image for scylladb/scylla:latest
af32630ab64eab674e9aeb58cd2849cdd7d4036e487720e16e23d2d356f0dcf2
[syuu@monster ~]$ docker exec -it some-scylla nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.2  231.89 KB  256          ?       487267b1-08b3-49c7-a909-46a7a68db5a9  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
[syuu@monster ~]$ docker exec -it some-scylla cqlsh
Connected to  at 172.17.0.2:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> SELECT cluster_name FROM system.local;

 cluster_name
--------------
             

(1 rows)
cqlsh> 
```

**Comment by nyh** [comment]
Works for me:
```
$ docker pull scylladb/scylla
$ docker run --name some-scylla -d scylladb/scylla
$ docker exec -it some-scylla cqlsh 
Connected to  at 172.17.0.2:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh>
```

@kokizzu maybe the host's operating system somehow makes a difference (I'm using Fedora 34 myself) but I don't know how or why. It looks like the Scylla server itself failed to start in your container, and the question is why. Can you find anything interesting in "docker logs some-scylla" - written by the Scylla server itself (the logs which you pasted only say that Scylla exited, and various auxiliary processes failed to connect to it - but I didn't see any line coming from Scylla itself saying why it is exiting). Maybe you can attach here the entire log?

**Comment by colin-grapl** [comment]
I'm having this issue on multiple versions. The last one I tried was 4.2.1, but I've tried multiple others (4.5, 4.6).

I'm on a debian distro (via ChromeOS), docker version 20.10.13. I've also tried adding port mappings to the command,

```
docker run -it --name some-scylla \
  -p 9042:9042 -p 7000:7000 -p 7001:7001 -p 7199:7199 \
  -p 9160:9160 -p 9180:9180 -p 10000:10000 \
  -d scylladb/scylla --overprovisioned 1
```

Output log `docker logs some-scylla`
https://gist.github.com/colin-grapl/513a5c898dd2f02f097f4fc4ad43697a

Here's the output of running cqlsh
```
docker exec -it some-scylla cqlsh 
Connection error: ('Unable to connect to any servers', {'172.17.0.2': error(111, "Tried connecting to [('172.17.0.2', 9042)]. Last error: Connection refused")})
```

**Comment by kokizzu** [comment]
only got this error on 4.6, 
using 4.5 is fine, just need to wait for a moment until it's up

**Comment by kokizzu** [comment]
the docker log for 4.6
https://gist.github.com/kokizzu/8c84457ccf32f824a2684b764ea70de8

**Comment by kokizzu** [comment]
hmm... if I run with that argument it works fine..
```shell
$ docker run --name some-scylla2 -d scylladb/scylla
$ docker exec -it some-scylla2 scylla --version
4.6.0-0.20220306.2f2d22a86
$ docker exec -it some-scylla2 cqlsh
Connected to  at 172.17.0.2:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> 
```
so one of the parameter on my docker-compose is causing the error?

**Comment by kokizzu** [comment]
yes it's the `--overprovisioning` flag that caused that
```
Could not initialize seastar: std::runtime_error (Could not setup Async I/O: Not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)

cat /proc/sys/fs/aio-max-nr
4194304
```
so 4 million not enough for 32 core when overprovisioned flag on?

**Comment by nyh** [comment]
This may be the same problem as issue #9096.
@syuu1228 - do you know how aio-max-nr is handled inside docker? also, Do you know if the fix in issue #9096 works inside docker?

**Comment by syuu1228** [comment]
I thought why I couldn't reproduce the bug last time is because I missed `--overprovisioning` option.
But I retired reproduce the bug with `--overprovisioning` option, I still not able to reproduce this.

I tested this on Azure Standard D32ads v5 instance with 32vCPUs, with CentOS7.9 image + docker-ce 20.10.14:
```
[azureuser@takuya-centos7-test1 ~]$  docker run -d -p 9042:9042 -p 7000:7000 -p 7001:7001 -p 7199:7199   -p 9160:9160 -p 9180:9180 -p 10000:10000 scylladb/scylla:latest --overprovisioned 1

[azureuser@takuya-centos7-test1 ~]$ docker exec -ti 2642b06b5ff5 /bin/bash

root@2642b06b5ff5:/# ps ax|grep /usr/bin/scylla
   32 pts/0    S      0:00 sudo -u scylla -g scylla /usr/bin/env SCYLLA_HOME=/var/lib/scylla SCYLLA_CONF=/etc/scylla /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --alternator-address 172.17.0.2 --blocked-reactor-notify-ms 999999999
   73 pts/0    Sl     0:21 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --alternator-address 172.17.0.2 --blocked-reactor-notify-ms 999999999
  198 pts/1    R+     0:00 grep --color=auto /usr/bin/scylla
root@2642b06b5ff5:/# cat /proc/sys/fs/aio-max-nr 
65536
root@79ac742cfd04:/# cat /sys/devices/system/cpu/present 
0-31
```

```
[azureuser@takuya-centos7-test1 ~]$  docker run -d -p 9042:9042 -p 7000:7000 -p 7001:7001 -p 7199:7199 -p 9160:9160 -p 9180:9180 -p 10000:10000 scylladb/scylla:4.5.0 --overprovisioned 1

[azureuser@takuya-centos7-test1 ~]$ docker exec -ti a8f3a2cebaf7 /bin/bash

[root@a8f3a2cebaf7 /]# ps ax|grep /usr/bin/scylla
   29 ?        Sl     0:23 /usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --blocked-reactor-notify-ms 999999999
  204 pts/0    S+     0:00 grep --color=auto /usr/bin/scylla
[root@a8f3a2cebaf7 /]# cat /proc/sys/fs/aio-max-nr
65536
[root@a8f3a2cebaf7 /]# cat /sys/devices/system/cpu/present 
0-31
```

I guess there are two possibilities:
 - Failed docker image is old, and hitting the issue #9096
   The issue caused at 2cfc517874e98c5780c1b1b4c38440a8123f86f6 and fixed at c0afdf3f150b09bb425f30b1a7d12f2ecd578c29, so docker image revision is between them.
- It is the environment specific issue such as specific container, or distro, or machine

**Comment by kokizzu** [comment]
yeah, weirdly with your command above it all ok '__') and i retried the docker-compose command i've used previously it's ok now no longer broken

**Comment by RoDmitry** [comment]
Don't know if it's the same, but I also use Docker on my dev machine:
```
  scylla:
    image: scylladb/scylla
    container_name: scylla
    restart: unless-stopped
    command: --smp 1 --memory 512M --overprovisioned 1 --api-address 0.0.0.0 --authenticator PasswordAuthenticator --authorizer CassandraAuthorizer
```

And it gives me same error on starting an image:
`Connection error: ('Unable to connect to any servers', {'172.18.0.2:9042': error(111, "Tried connecting to [('172.18.0.2', 9042)]. Last error: Connection refused")})`

And after about a minute it's gone. Maybe because I use it on hdd, which might be slower than what you tested on.
My system is Windows -> Centos 9 in VirtualBox -> Docker. Last docker image. And for the first time I also thought that something is wrong :)
