### ISSUE TITLE
nodetool cfstats dtest failure with smp > 1

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#1024]
The test case passes with ``--smp 1``:

```
[penberg@nero scylla-dtest]$ export SCYLLA_EXT_OPTS="--smp 1"
[penberg@nero scylla-dtest]$ nosetests -s -v nodetool_additional_test.py:TestNodetool.cfstats_test
cfstats_test (nodetool_additional_test.TestNodetool) ... ok

----------------------------------------------------------------------
Ran 1 test in 179.445s

OK
```

but fails with ``--smp 2``:

```
[penberg@nero scylla-dtest]$ export SCYLLA_EXT_OPTS="--smp 2"
[penberg@nero scylla-dtest]$ nosetests -s -v nodetool_additional_test.py:TestNodetool.cfstats_test
cfstats_test (nodetool_additional_test.TestNodetool) ... FAIL

======================================================================
FAIL: cfstats_test (nodetool_additional_test.TestNodetool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/penberg/scylla-dtest/nodetool_additional_test.py", line 205, in cfstats_test
    self.assertMapEqual(table, "SSTable count", 1)
  File "/home/penberg/scylla-dtest/nodetool_additional_test.py", line 84, in assertMapEqual
    self.assertEqual(val, float(container[key]), m)
  File "/home/penberg/scylla-dtest/nodetool_additional_test.py", line 48, in assertEqual
    super(TestNodetool, self).assertEqual(expect, second, msg + " (Expecting " + str(expect) + " got " + str(second) + ")")
AssertionError: SSTable count (Expecting 1 got 2.0)
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/penberg/.dtest/dtest-OUCJb0
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 28.365s

FAILED (failures=1)
```

**Comment by penberg** [comment]
@amnonh @raphaelsc Faulty test or faulty API?

**Comment by amnonh** [comment]
On Fri, Mar 11, 2016 at 11:29 AM, Pekka Enberg <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> @raphaelsc
> <https://github.com/raphaelsc> Faulty test or faulty API?
>
It could be a fault API.
From the test failure message I get that we expect a single sstable, but we
get two.
So maybe we count the number of sstable twice.

**Comment by penberg** [comment]
@amnonh There's two sstables because of sharing. I am not sure what's the right way to fix it.

Ping @raphaelsc @glommer

**Comment by glommer** [comment]
We can't really guarantee that a single SSTable will be created for anything with more than one partition key in smp > 2.

The only way to do so is to make the test token-aware, so that it only introduces partition keys that would fall into the same shard.

**Comment by penberg** [comment]
Perhaps we should relax the test case then?

@slivne @lmr

**Comment by slivne** [comment]
@amnonh is the owner of this tests ....
