### ISSUE TITLE
Nodetool toppartitions fails with NotSerializableException 

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#10256]
*Installation details*
Scylla version (or git commit hash): 5.0.rc2-0.20220316.839d9ef41 with build-id 1319e7e64335b7e5c7531f773e92ef997b6c51ba
Cluster size: 5 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-088d9111d729684f8 (eu-north-1)

Test: longevity-mv-si-4days-test

New node that was created as replacement for another node but wasn't added to the cluster ring.

Nodetool toppartitions fails (as in issue https://github.com/scylladb/scylla/issues/4893) on the node longevity-mv-si-4d-5-0-db-node-1bb24db5-2:
```
< t:2022-03-18 10:53:53,786 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-18 10:53:53.784: (NodetoolEvent Severity.ERROR) period_type=end event_id=6f47c924-aa50-4a21-871c-bcff0f514d72 duration=25s: nodetool_command=toppartitions node=longevity-mv-si-4d-5-0-db-node-1bb24db5-2
< t:2022-03-18 10:53:53,784 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "/usr/bin/nodetool  toppartitions --ks-filters system,system_distributed,system_schema,mview,sec_i
ndex --cf-filters system:repair_history,system_schema:scylla_tables,system:token_ring,system:snapshots,sec_index:users,system:versions,mview:users_by_email,sec_index:users_last_name_ind_index,mview:users,system:
scylla_local,system:runtime_info,mview:users_by_last_name,system:versions,system:protocol_servers,system_distributed:cdc_streams_descriptions_v2,system:protocol_servers -s 275 -k 6 -a reads -d 1830"; Exit status
: 2
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: error: org.glassfish.json.JsonLocationImpl
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > -- StackTrace --
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > java.io.NotSerializableException: org.glassfish.json.JsonLocationImpl
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:396)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at sun.rmi.transport.Transport$1.run(Transport.java:200)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at sun.rmi.transport.Transport$1.run(Transport.java:197)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.security.AccessController.doPrivileged(Native Method)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.security.AccessController.doPrivileged(Native Method)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
< t:2022-03-18 10:53:53,784 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at java.lang.Thread.run(Thread.java:748)
```

Logs here:
https://s3.console.aws.amazon.com/s3/object/cloudius-jenkins-test?region=us-east-1&prefix=1bb24db5-ff03-42fb-b3c5-595d885b91f2

[Jenkins job](https://jenkins.scylladb.com/view/scylla-5.0/job/scylla-5.0/job/longevity/job/longevity-mv-si-4days-test/2/)

**Comment by slivne** [comment]
it maybe this https://github.com/scylladb/scylla/issues/9061

**Comment by slivne** [comment]
this was backported only 4 days ago - so we did not have this fix - closing this issue hoping its fixed by #9061 backport (the stack does have an issue with json formatting that 9061 fixed)

**Comment by slivne** [comment]
Lets verify on 5.0.rc3

**Comment by juliayakovlev** [comment]
This issue was not reproduced with `5.0~rc8-20220612.f28542a71` version (https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-mv-si-4days-test/3/)
