### ISSUE TITLE
Scylla crashes if stream does not end properly

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1025]
I have a cluster with 3 nodes running.

Node3 is the repair master, and some of the streams it sends to Node1 never get acknowledged. That's fine, and we should be able to handle that. But after a timeout occurs (10 minutes, but can be reduced in messaging_service.cc to make this quicker to happen), Node3 crashes instead of gracefully handling this.

Backtrace is as follows:

```
#0  0x00007ffff3910a98 in raise () from /lib64/libc.so.6
#1  0x00007ffff391269a in abort () from /lib64/libc.so.6
#2  0x00007ffff7257aed in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007ffff7255936 in ?? () from /lib64/libstdc++.so.6
#4  0x00007ffff7255981 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007ffff7255be9 in __cxa_rethrow () from /lib64/libstdc++.so.6
#6  0x0000000000f45cee in streaming::stream_transfer_task::<lambda()>::<lambda(auto:44)>::operator()<std::__exception_ptr::exception_ptr> (ep=..., __closure=0x7fffffffcce0)
    at streaming/stream_transfer_task.cc:157
#7  do_void_futurize_apply<const streaming::stream_transfer_task::start()::<lambda()>::<lambda(auto:44)>&, std::__exception_ptr::exception_ptr> (func=...)
    at /home/glauber/scylla/seastar/core/future.hh:1142
#8  futurize<void>::apply<const streaming::stream_transfer_task::start()::<lambda()>::<lambda(auto:44)>&, std::__exception_ptr::exception_ptr> (func=...)
    at /home/glauber/scylla/seastar/core/future.hh:1190
#9  future<>::<lambda(auto:7&&)>::operator()<future<> > (fut=fut@entry=<unknown type in /home/glauber/scylla/build/release/scylla, CU 0xef38e39, DIE 0xf0d9e27>, 
    __closure=__closure@entry=0x7fffffffcce0) at /home/glauber/scylla/seastar/core/future.hh:1014
#10 futurize<future<> >::apply<future<T>::handle_exception(Func&&) [with Func = streaming::stream_transfer_task::start()::<lambda()>::<lambda(auto:44)>; T = {}]::<lambda(auto:7&&)>, future<> >(<unknown type in /home/glauber/scylla/build/release/scylla, CU 0xef38e39, DIE 0xf0d9f5f>) (
    func=func@entry=<unknown type in /home/glauber/scylla/build/release/scylla, CU 0xef38e39, DIE 0xf0d9f5f>) at /home/glauber/scylla/seastar/core/future.hh:1207
#11 0x0000000000f47e26 in future<>::<lambda(auto:4&&)>::operator()<future_state<> > (state=<unknown type in /home/glauber/scylla/build/release/scylla, CU 0xef38e39, DIE 0xf0cb935>, 
    __closure=0x6000840bc850) at /home/glauber/scylla/seastar/core/future.hh:885
#12 continuation<future<T>::then_wrapped(Func&&) [with Func = future<T>::handle_exception(Func&&) [with Func = streaming::stream_transfer_task::start()::<lambda()>::<lambda(auto:44)>; T = {}]::<lambda(auto:7&&)>; Result = future<>; T = {}]::<lambda(auto:4&&)> >::run(void) (this=0x6000840bc840) at /home/glauber/scylla/seastar/core/future.hh:400
#13 0x000000000047131d in reactor::run_tasks (this=this@entry=0x60000032b000, tasks=...) at core/reactor.cc:1444
#14 0x000000000049cb0b in reactor::run (this=0x60000032b000) at core/reactor.cc:1748
#15 0x000000000051342e in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffd6a0, ac=ac@entry=37, av=av@entry=0x7fffffffd918, 
    func=func@entry=<unknown type in /home/glauber/scylla/build/release/scylla, CU 0x6744da, DIE 0x731655>) at core/app-template.cc:127
#16 0x0000000000417dcb in main (ac=37, av=0x7fffffffd918) at main.cc:526
```

**Comment by penberg** [comment]
Fixed by commit https://github.com/scylladb/scylla/commit/f747df2aff2b3a39bacfc0c8e21c13074e3ab70d, no?

**Comment by glommer** [comment]
I don't have this commit in my tree. Will retest.

**Comment by glommer** [comment]
Yes. The cluster is still alive after the timeout when I apply that change.
