### ISSUE TITLE
[rolling upgrade] truncate query failed: OperationTimedOut

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#10283]
## Installation details

Kernel Version: 3.10.0-1160.59.1.el7.x86_64

Scylla version (or git commit hash): `5.0.rc1-20220206.891990ec0` with build-id `20d9fa2c6020017f4afdc4941c0cca9c9a29d94a`

Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-master-centos-db-node-2bef8693-0-4 (34.138.65.50 | 10.142.0.166) (shards: 8)
- rolling-upgrade-master-centos-db-node-2bef8693-0-3 (35.196.221.23 | 10.142.0.162) (shards: 8)
- rolling-upgrade-master-centos-db-node-2bef8693-0-2 (34.148.172.136 | 10.142.0.139) (shards: 8)
- rolling-upgrade-master-centos-db-node-2bef8693-0-1 (34.139.245.42 | 10.142.0.120) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: eu-west-1)

Test: `rolling-upgrade-centos7-test`

Test id: `2bef8693-38f9-443c-906d-0e663358bfa6`

Test name: `rolling-upgrade/rolling-upgrade-centos7-test`

Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1cf1a7533b0af12a4484921aa18db289b82b4f94/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

At first, node 3 was upgraded to the latest master. This upgrade went without a hitch, and ended at `2022-03-26 06:14:40.086`. After the upgrade procedure has ended, we started a cassandra stress read thread:
`cassandra-stress read no-warmup cl=QUORUM n=10100200 -schema 'replication(factor=3) compression=DeflateCompressor' -port jmx=6868 -mode cql3 native compression=none -rate threads=1000 -pop seq=1..10100200 -log interval=5`
And soon afterwards, node 2 started to experience a heavy load:
```
2022-03-26T06:16:20+00:00 rolling-upgrade-master-centos-db-node-2bef8693-0-2 !    INFO |  [shard 0] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 100/100 count and 2225982/127171297 memory resources: timed out, dumping permit diagnostics:
2022-03-26T06:16:20+00:00 rolling-upgrade-master-centos-db-node-2bef8693-0-2 !  NOTICE | 
2022-03-26T06:16:20+00:00 rolling-upgrade-master-centos-db-node-2bef8693-0-2 !  NOTICE | 
2022-03-26T06:16:20+00:00 rolling-upgrade-master-centos-db-node-2bef8693-0-2 !  NOTICE | 
2022-03-26T06:16:20+00:00 rolling-upgrade-master-centos-db-node-2bef8693-0-2 !  NOTICE | 
2022-03-26T06:16:20+00:00 rolling-upgrade-master-centos-db-node-2bef8693-0-2 !  NOTICE | 
2022-03-26T06:16:20+00:00 rolling-upgrade-master-centos-db-node-2bef8693-0-2 !  NOTICE | 1463 permits with 100 count and 2174K memory resources
```
At `2022-03-26 06:47:16.634`, the upgrade precedure of node 4 has started. As part of the upgrade process, we perform a truncate query on a few specifically created tables. The truncate, however failed due to node 2 timing out:
```
< t:2022-03-26 06:48:36,283 f:common.py       l:1324 c:utils                p:DEBUG > Executing CQL 'TRUNCATE TABLE truncate_table0' ...
...
2022-03-26 06:49:48.107: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=a563c75e-105f-416b-878b-e4f0b4882d75, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 603, in test_rolling_upgrade
    self.upgrade_node(self.db_cluster.node_to_upgrade)
  File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 48, in inner
    self.cql_truncate_simple_tables(session=session, rows=self.insert_rows)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3057, in cql_truncate_simple_tables
    session.execute(truncate_query % i)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1325, in execute_verbose
    return execute_orig(*args, **kwargs)
  File "cassandra/cluster.py", line 2627, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4893, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={<Host: 10.142.0.139:9042 datacenter1>: ConnectionException('Host has been marked down or removed')}, last_host=10.142.0.120:9042
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2bef8693-38f9-443c-906d-0e663358bfa6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2bef8693-38f9-443c-906d-0e663358bfa6)
- Show all stored logs command: `$ hydra investigate show-logs 2bef8693-38f9-443c-906d-0e663358bfa6`

## Logs:
- **db-cluster-2bef8693.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2bef8693-38f9-443c-906d-0e663358bfa6/20220326_065552/db-cluster-2bef8693.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2bef8693-38f9-443c-906d-0e663358bfa6/20220326_065552/db-cluster-2bef8693.tar.gz)
- **monitor-set-2bef8693.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2bef8693-38f9-443c-906d-0e663358bfa6/20220326_065552/monitor-set-2bef8693.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2bef8693-38f9-443c-906d-0e663358bfa6/20220326_065552/monitor-set-2bef8693.tar.gz)
- **loader-set-2bef8693.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2bef8693-38f9-443c-906d-0e663358bfa6/20220326_065552/loader-set-2bef8693.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2bef8693-38f9-443c-906d-0e663358bfa6/20220326_065552/loader-set-2bef8693.tar.gz)
- **sct-runner-2bef8693.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2bef8693-38f9-443c-906d-0e663358bfa6/20220326_065552/sct-runner-2bef8693.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2bef8693-38f9-443c-906d-0e663358bfa6/20220326_065552/sct-runner-2bef8693.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/224/)

**Comment by roydahan** [comment]
@fgelcer / @soyacz does it still happen on 5.0 / 2022.1?

**Comment by fgelcer** [comment]
> @fgelcer / @soyacz does it still happen on 5.0 / 2022.1?

last CentOS 7 upgrade ran on May 10th and it passed...
if this issue was consistent, it did not happen on the latest run, but if it happens sporadically we should run few times to confirm it (also, waiting for RC5, that shall trigger it again).

**Comment by soyacz** [comment]
After fixing Gemini seed we don't see timeout errors anymore (including this truncate error).

**Comment by roydahan** [comment]
Because we don't run the nemesis anymore?
