### ISSUE TITLE
added keyspace storage options break java tools

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10376]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1175/testReport/offline_tools_test/TestOfflineTools/test_sstablelevelreset/
```
Stacktrace
self = <offline_tools_test.TestOfflineTools object at 0x7f17ed2f9220>

    @pytest.mark.single_node
    def test_sstablelevelreset(self):
        """
        Insert data and call sstablelevelreset on a series of
        tables. Confirm level is reset to 0 using its output.
        Test a variety of possible errors and ensure response is resonable.
        @since 2.1.5
        @jira_ticket CASSANDRA-7614
        """
        cluster = self.cluster
        cluster.populate(1).start(wait_for_binary_proto=True)
        node1 = cluster.nodelist()[0]
    
        # test by trying to run on nonexistent keyspace
        cluster.stop(gently=False)
        (output, error, rc) = node1.run_sstablelevelreset("keyspace1", "standard1", output=True)
        assert "ColumnFamily not found: keyspace1/standard1" in error, "Message was not found in stderr"
        # this should return exit code 1
        assert rc == 1, f"Invalid exit code: {str(rc)}"
    
        # now test by generating keyspace but not flushing sstables
        cluster.start(wait_for_binary_proto=True)
        node1.stress(['write', 'n=100', '-schema', 'replication(factor=1)'])
        cluster.stop(gently=False)
    
        (output, error, rc) = node1.run_sstablelevelreset("keyspace1", "standard1", output=True)
>       self.verify_nodetool_stderr(error)

offline_tools_test.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <offline_tools_test.TestOfflineTools object at 0x7f17ed2f9220>
error = 'ERROR 12:36:37,671 Error in ThreadPoolExecutor\njava.lang.RuntimeException: Unknown column storage during deserializa...NamedThreadFactory.java:84)\n\tat java.lang.Thread.run(Thread.java:748)\nColumnFamily not found: keyspace1/standard1\n'

    def verify_nodetool_stderr(self, error):
>       assert not self._nodetool_stderr_has_error(error), f"Unexpected nodetool stderr: {error}"
E       AssertionError: Unexpected nodetool stderr: ERROR 12:36:37,671 Error in ThreadPoolExecutor
E         java.lang.RuntimeException: Unknown column storage during deserialization
E         	at org.apache.cassandra.db.SerializationHeader$Component.toHeader(SerializationHeader.java:338)
E         	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:522)
E         	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:385)
E         	at org.apache.cassandra.io.sstable.format.SSTableReader$3.run(SSTableReader.java:570)
E         	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
E         	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
E         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
E         	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:84)
E         	at java.lang.Thread.run(Thread.java:748)
E         ColumnFamily not found: keyspace1/standard1
E         
E       assert not True
E        +  where True = <bound method TestOfflineTools._nodetool_stderr_has_error of <offline_tools_test.TestOfflineTools object at 0x7f17ed2f9220>>('ERROR 12:36:37,671 Error in ThreadPoolExecutor\njava.lang.RuntimeException: Unknown column storage during deserializa...NamedThreadFactory.java:84)\n\tat java.lang.Thread.run(Thread.java:748)\nColumnFamily not found: keyspace1/standard1\n')
E        +    where <bound method TestOfflineTools._nodetool_stderr_has_error of <offline_tools_test.TestOfflineTools object at 0x7f17ed2f9220>> = <offline_tools_test.TestOfflineTools object at 0x7f17ed2f9220>._nodetool_stderr_has_error

offline_tools_test.py:49: AssertionError
```

Test test passes at 379892142d0b656bb9535edd372a9c2a9cd46925
and fails as above starting 59d56a3fd7ab22a3184de2ebfb3df67580316ff9

**Comment by psarna** [comment]
Oh, the series contained a terrible non-backward-compatible leftover, it added an unused "storage" column to `system_schema.keyspaces`.... I'll push a patch that fixes it in a minute.
