### ISSUE TITLE
nodetool info is not working properly

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1041]
The following AMI is used:
scylla_2016-03-10T05-43-00Z (ami-7c545016)

Error happens when simply issuing the command, look:
```
$ nodetool info
ID                     : b4f4ce96-6864-47f2-b171-97d1d525a51c
Gossip active          : true
Thrift active          : false
Native Transport active: true
Load                   : 16.84 KB
Generation No          : 1457994079
Uptime (seconds)       : 562
Heap Memory (MB)       : 134.79 / 247.50
Off Heap Memory (MB)   : 1.75
error: Index: 0, Size: 0
-- StackTrace --
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.apache.cassandra.tools.NodeProbe.getEndpoint(NodeProbe.java:812)
	at org.apache.cassandra.tools.NodeProbe.getDataCenter(NodeProbe.java:830)
	at org.apache.cassandra.tools.NodeTool$Info.execute(NodeTool.java:425)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:288)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:202)
```

After that, Scylla is still up and log doesn't show anything strange:
```
$ journalctl | grep scylla | tail -n 10
Mar 14 22:21:19 ip-172-30-0-197 scylla[2624]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-16-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-31-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-46-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-61-Data.db:level=0, ]
Mar 14 22:21:19 ip-172-30-0-197 scylla[2624]:  [shard 0] storage_service - Node 172.30.0.197 state jump to normal
Mar 14 22:21:19 ip-172-30-0-197 scylla[2624]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-76-Data.db:level=0, ]. 12739 bytes to 12574 (~98% of original) in 39ms = 0.307474MB/s. ~1024 total partitions merged to 1.
Mar 14 22:21:19 ip-172-30-0-197 scylla[2624]:  [shard 0] storage_service - NORMAL: node is now in normal status
Mar 14 22:21:19 ip-172-30-0-197 scylla[2624]:  [shard 0] gossip - Waiting for gossip to settle before accepting client requests...
Mar 14 22:21:27 ip-172-30-0-197 scylla[2624]:  [shard 0] gossip - No gossip backlog; proceeding
Mar 14 22:21:27 ip-172-30-0-197 scylla[2624]:  [shard 0] storage_service - Starting listening for CQL clients on 0.0.0.0:9042...
Mar 14 22:21:33 ip-172-30-0-197 scylla-jmx[2656]: Using config file: /etc/scylla/scylla.yaml
Mar 14 22:21:33 ip-172-30-0-197 scylla-jmx[2656]: Connecting to http://127.0.0.1:10000
Mar 14 22:21:33 ip-172-30-0-197 scylla-jmx[2656]: Starting the JMX server
```

**Comment by amnonh** [comment]
Already covered by #1027
Please close

On Tue, Mar 15, 2016 at 12:32 AM, Raphael Carvalho <notifications@github.com

**Comment by raphaelsc** [comment]
@amnonh  thx
