### ISSUE TITLE
(ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded) after nodetool cleanup

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#10435]
## Installation details

Kernel Version: 5.11.0-1022-aws
Scylla version (or git commit hash): `4.7.dev-20220407.3e21fea2b` with build-id `d7c55eaaa9df57f9f445c73c5e983cae6ea272c3`
Cluster size: 6 nodes (r5b.2xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-master-db-node-96eef9fb-7 (52.16.169.40 | 10.0.3.10) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-6 (3.250.173.56 | 10.0.0.140) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-5 (54.217.58.255 | 10.0.0.157) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-4 (54.217.60.147 | 10.0.1.33) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-3 (34.244.177.10 | 10.0.3.28) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-2 (52.31.100.243 | 10.0.0.24) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-1 (54.171.209.155 | 10.0.0.69) (shards: 8)

OS / Image: `ami-06940ae9efa1017bb` (aws: eu-west-1)

Test: `longevity-100gb-4h-ebs-gp3-test`
Test id: `96eef9fb-a79f-40b9-9df7-5a17c6899185`
Test name: `scylla-master/longevity/longevity-100gb-4h-ebs-gp3-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f3bc0a8d076b3829fdfb3178ba6203ee0c44ed34/test-cases/longevity/longevity-100gb-4h.yaml)

## Issue description

**>>>>>>>**
SCT started a nodetool-cleanup nemesis at 6.00. then at 6.45 c-s failed with a read-timeout error.

c-s exception on loader (./cassandra-stress-l1-c0-k1-339cdfbf-12be-44c6-b0f5-e7f4af2a96cc.log):
```
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [4e4c4b37343431363130]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)

com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
total,       1759265,       0,       0,       0, 50012.9, 50029.7, 50029.7, 50029.7, 50029.7, 50029.7, 6254.0,  0.79020,      1,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)


```
c-s error on sct log:
```
< t:2022-04-10 06:00:09,757 f:nemesis.py      l:1364 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_cleanup
< t:2022-04-10 06:00:09,758 f:nemesis.py      l:313  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Current Target: Node longevity-100gb-4h-master-db-node-96eef9fb-7 [52.16.169.40 | 10.0.3.10] (seed: False) with running nemesis: CorruptThenScrub Node longevity-100gb-4h-master-db-node-96eef9fb-7 [52.16.169.40 | 10.0.3.10] (seed: False)
< t:2022-04-10 06:00:36,420 f:nemesis.py      l:3282 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Start disruption at `2022-04-10 06:00:36.420115`
< t:2022-04-10 06:00:36,420 f:nemesis.py      l:804  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> NodetoolCleanup Node longevity-100gb-4h-master-db-node-96eef9fb-7 [52.16.169.40 | 10.0.3.10] (seed: False)
< t:2022-04-10 06:00:36,422 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-10 06:00:36.420: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=423b8180-8753-4824-a806-150ce52adf71: nemesis_name=NodetoolCleanup target_node=Node longevity-100gb-4h-master-db-node-96eef9fb-7 [52.16.169.40 | 10.0.3.10] (seed: False)
< t:2022-04-10 06:46:43,998 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > java.io.IOException: Operation x10 on key(s) [4e4c4b37343431363130]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2022-04-10 06:46:44,023 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-10 06:46:44.022: (CassandraStressLogEvent Severity.CRITICAL) period_type=one-time event_id=1909d3e8-5ee4-4b3b-85f6-df8d48de43f9: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=3043 node=Node longevity-100gb-4h-master-loader-node-96eef9fb-2 [54.195.179.242 | 10.0.2.214] (seed: False)
< t:2022-04-10 06:46:44,023 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > java.io.IOException: Operation x10 on key(s) [4e4c4b37343431363130]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 96eef9fb-a79f-40b9-9df7-5a17c6899185`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=96eef9fb-a79f-40b9-9df7-5a17c6899185)
- Show all stored logs command: `$ hydra investigate show-logs 96eef9fb-a79f-40b9-9df7-5a17c6899185`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-ebs-gp3-test/42/)

**Comment by fgelcer** [comment]
> This is a very old image 4.7.dev-20220407.3e21fea2b with build-id d7c55eaaa9df57f9f445c73c5e983cae6ea272c3
> 
> @yarongilor / @fgelcer If we are clearing some backlog lets make sure that the images are "new"

@yarongilor must pay more attention to the version being used, and this was related to an issue with scylla-pkg...
i'm not sure this issue was already addressed, but IMHO we can close it, and if seen again, we will report a new one, or re-open this one.

**Comment by slivne** [comment]
closing this issue
