### ISSUE TITLE
cqlsh describe-keyspace command fails with ReadTimeout while adding a new node

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#10436]
## Installation details

Kernel Version: 5.11.0-1022-aws
Scylla version (or git commit hash): `4.7.dev-20220407.3e21fea2b` with build-id `d7c55eaaa9df57f9f445c73c5e983cae6ea272c3`
Cluster size: 6 nodes (r5b.2xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-master-db-node-96eef9fb-7 (52.16.169.40 | 10.0.3.10) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-6 (3.250.173.56 | 10.0.0.140) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-5 (54.217.58.255 | 10.0.0.157) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-4 (54.217.60.147 | 10.0.1.33) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-3 (34.244.177.10 | 10.0.3.28) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-2 (52.31.100.243 | 10.0.0.24) (shards: 8)
- longevity-100gb-4h-master-db-node-96eef9fb-1 (54.171.209.155 | 10.0.0.69) (shards: 8)

OS / Image: `ami-06940ae9efa1017bb` (aws: eu-west-1)

Test: `longevity-100gb-4h-ebs-gp3-test`
Test id: `96eef9fb-a79f-40b9-9df7-5a17c6899185`
Test name: `scylla-master/longevity/longevity-100gb-4h-ebs-gp3-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f3bc0a8d076b3829fdfb3178ba6203ee0c44ed34/test-cases/longevity/longevity-100gb-4h.yaml)

## Issue description

**>>>>>>>**

node-4 is decommissioned:
```
NodetoolDecommission Node longevity-100gb-4h-master-db-node-96eef9fb-4 [54.217.60.147 | 10.0.1.33]
```

Added a new node - node-7:
``` < t:2022-04-10 04:59:33,308 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-04-10T04:59:33+00:00 longevity-100gb-4h-master-db-node-96eef9fb-7 !    INFO |  [shard 0] init - starting system distributed keyspace ```

decommission completed successfully for node-4, then Started adding a new node:
```
< t:2022-04-10 04:53:24,534 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  decommission " finished with status 0
< t:2022-04-10 04:53:24,535 f:cluster.py      l:2628 c:sdcm.cluster_aws     p:DEBUG > Node longevity-100gb-4h-master-db-node-96eef9fb-4 [54.217.60.147 | 10.0.1.33] (seed: False): Command '/usr/bin/nodetool  decommission ' duration -> 2102.400983832 s
< t:2022-04-10 04:53:24,536 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-10 04:53:24.535: (NodetoolEvent Severity.NORMAL) period_type=end event_id=80ced5ac-5a8c-411d-9ada-58648d917660 duration=35m2s: nodetool_command=decommission node=longevity-100gb-4h-master-db-node-96eef9fb-4
< t:2022-04-10 04:53:24,723 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-04-10T04:53:24+00:00 longevity-100gb-4h-master-db-node-96eef9fb-4 !    INFO |  [shard 0] storage_service - DECOMMISSIONING: set_bootstrap_state done
< t:2022-04-10 04:53:24,723 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-04-10T04:53:24+00:00 longevity-100gb-4h-master-db-node-96eef9fb-4 !    INFO |  [shard 0] storage_service - DECOMMISSIONED:
< t:2022-04-10 04:53:24,723 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-04-10T04:53:24+00:00 longevity-100gb-4h-master-db-node-96eef9fb-4 !    INFO |  [shard 0] storage_service - DECOMMISSIONING: done
< t:2022-04-10 04:53:26,304 f:cluster.py      l:4432 c:sdcm.cluster         p:INFO  > Decommission Node longevity-100gb-4h-master-db-node-96eef9fb-4 [54.217.60.147 | 10.0.1.33] (seed: False) PASS
< t:2022-04-10 04:53:34,691 f:nemesis.py      l:899  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Adding new node to cluster...
< t:2022-04-10 04:57:03,643 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   --override-decommission arg           Set true to force a decommissioned node
< t:2022-04-10 04:57:03,643 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >                                         removenode, decommission and rebuild

```

Then cqlsh describe-keyspace cmd failed for node-1:
(Node longevity-100gb-4h-master-db-node-96eef9fb-1 [54.171.209.155 | 10.0.0.69])
```
< t:2022-04-10 05:21:13,198 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "describe keyspaces" 10.0.0.69 9042"...
< t:2022-04-10 05:21:23,705 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "describe keyspaces" 10.0.0.69 9042"; Exit status: 1
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <function Nemesis.disrupt_nodetool_decommission at 0x7f450e4937f0> < t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <function Nemesis.disrupt_nodetool_decommission at 0x7f450e4937f0>
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3307, in wrapper
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 945, in disrupt_nodetool_decommission
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     test_keyspaces = self.cluster.get_test_keyspaces()
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4037, in get_test_keyspaces
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     keyspaces = self.nodes[0].run_cqlsh("describe keyspaces").stdout.split()
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2811, in run_cqlsh
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     cqlsh_out = self.remoter.run(cmd, timeout=timeout + 30,  # we give 30 seconds to cqlsh timeout mechanism to work
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     result = _run()
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     return func(*args, **kwargs)
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     result = connection.run(**command_kwargs)
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR >     raise UnexpectedExit(result)
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > 
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "describe keyspaces" 10.0.0.69 9042'
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > 
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > Exit code: 1
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > 
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > 
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > 
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > 
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > 
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > Connection error: ('Unable to connect to any servers', {'10.0.0.69': ReadTimeout('Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\' responses] message="Operation timed out for system.peers - received only 0 responses from 1 CL=ONE." info={\'received_responses\': 0, \'required_responses\': 1, \'consistency\': \'ONE\'}',)})
< t:2022-04-10 05:21:23,708 f:nemesis.py      l:3317 c:sdcm.nemesis         p:ERROR > 
< t:2022-04-10 05:21:23,710 f:nemesis.py      l:3329 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: NodetoolDecommission Node longevity-100gb-4h-master-db-node-96eef9fb-4 [54.217.60.147 | 10.0.1.33] (seed: False) duration -> 3782 s
```

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 96eef9fb-a79f-40b9-9df7-5a17c6899185`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=96eef9fb-a79f-40b9-9df7-5a17c6899185)
- Show all stored logs command: `$ hydra investigate show-logs 96eef9fb-a79f-40b9-9df7-5a17c6899185`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-ebs-gp3-test/42/)

**Comment by slivne** [comment]
@yarongilor / @fgelcer - why an old image (Scylla version (or git commit hash): 4.7.dev-20220407.3e21fea2b with build-id d7c55eaaa9df57f9f445c73c5e983cae6ea272c3
) 

?

If we are still clearing some backlog please double check the images are "new"

**Comment by slivne** [comment]
closing this issue
