### ISSUE TITLE
Gemini test fails on warmup phase with Validation failed: row count differ

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla#10453]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.1.dev-20220421.cc40685c288f` with build-id `fde9a351743afef6ce27c7787712211d9ee8f41f`
Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- gemini-1tb-10h-master-oracle-db-node-ed9b280b-1 (54.77.240.103 | 10.0.0.96) (shards: 14)
- gemini-1tb-10h-master-db-node-ed9b280b-3 (34.240.55.239 | 10.0.1.229) (shards: 14)
- gemini-1tb-10h-master-db-node-ed9b280b-2 (34.242.223.136 | 10.0.1.206) (shards: 14)
- gemini-1tb-10h-master-db-node-ed9b280b-1 (34.240.88.56 | 10.0.2.30) (shards: 14)

OS / Image: `ami-07d353a9e8649b3a1` (aws: eu-west-1)

Test: `gemini-1tb-10h`
Test id: `ed9b280b-0925-40ae-be69-c2f49503a415`
Test name: `scylla-master/gemini-/gemini-1tb-10h`
Test config file(s):

- [gemini-1tb-10h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f485155a9f8b359c8e8da8d07cd3d4396aa5ca27/test-cases/gemini/gemini-1tb-10h.yaml)

## Issue description

**>>>>>>>**
Gemini test failed after it's warmup phase:
```
2022-04-22 06:03:01.919: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=257dd076-8417-4923-9b25-4686ff8bd8b9, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 68, in test_load_random_with_nemesis
self.verify_results()
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results
self.fail(self.gemini_results['results'])
AssertionError: [{'write_ops': 40194216, 'write_errors': 0, 'read_ops': 0, 'read_errors': 1, 'errors': [{'timestamp': '2022-04-22T05:34:53.804173244Z', 'message': 'Validation failed: row count differ (test has 634 rows, oracle has 0 rows, test is missing rows: [], oracle is missing rows: [pk0=-15, \tpk1=845512951, \tck0=8224272148495114023, \tck1=2771902910911737.118, \tck2=SzCiqNwRMiEyW2NQD1EyEripdck4Rpnwj472QoBWl+aLInyge6jlC+THizOPfiqfD3G+Z4gjJDFFV9IZ9joc3UfOs7e7XgJpaV1CaMzPG2S10aeUeGdoK22Ms6Iem0VFjYxo7SVtJtyEaNbBmsmoGB6Ch0813c5VI0goNyONG0gTA+TcNgJ12TFPs3gdtvPlTWKTxpEgep9hYvOq1o3QHOV8DLFJpRJsVz0BymR8KEapmEUIogBniv2Xd17HrXfhaQxS0NcxdRBA9kXNSe4puBpZVTX1OeFXstQsJpovmPYXavNrmLjqb+qqkuc6D9O0ObOdXYI/o3O9qo7d1FOLrsuG8E7PToDjuzom2lIugNGOxA9mveLpmayJLbHp9lK8FbKeByfXLcNwmPuZOAe6wzOBZNZ7KOccrGkR8Bhvg0BNGZvsH0IWwOS1x6M926ZTcU pk0=-51, \tpk1=43178825, \tck0=3868316782544142933, \tck1=575044646194022.284, \tck2=ZVgRMi36O6jhwCjEEw8JkrjyIx6orbwb0e2PoWQvX/7eP1Fa1DoUAfS7yBgtF8K5yPxioR4+RnfgHjbeW+W1LL7bPFINU1C6GOeV3cdCD4KgFWb3OhSz0qiI4ThgiD2zCnAGCSwXxrGgyi3HDwmjNLq0+psEbGDf93JxpYMSpGDGAtaoDAN50ANjWpBJkpPgyLTj1nsurWqk96VBJHpW2ZAABr5p5YHnbNBI7bPvuCq3Lmu87vdNIL4IOHN8Zv34GdAD4eU1SaeSI0KDvhvDGn54AJMv6W0kwK+buo3kbHs+KmZjKvutW7YyjbluDPzy+2htBrsWA/Q8ORSDEzvs//ITkb8yw5Nlsh6aeZ0njaeE34kI9cPwnLQjaPrDmHAVnXkMaj9gZMxikw5uhNfxQU6B3obqwZT8uJcdKqAuqYwZNoNxvCBa1vIni21aq9DEdqX5TfxmSZm2H5cnB/fDMXWeTssQ3DupHo5qufSV7oPK8A3AiZyU/zAD41WhySKHOK6w6IGFqqV6BNZ477BKH9gjdCrvf1qgZtEn5R7A0C5xRV9ysVOpX4u+TNBXAta+WiJuilXTo4tzTUrs9jvdih4gPhqcnsIrT4FcF+5a3EYtBfY73Y8bSF20F6SNh1/PC+oIn6iU1eIyHMMtW+jRYqguuBUSpaNCJaet8Xze9aXKtg8kgRKFP5cA6U/NYW/Yv3oU2cmYP9nUV7QvMTBa6vulnPJ1zfmV+DTwl3xaREE2FPARSfLlGmHXwzzMhpo8Dx8uWY4ZJfCPkZIoT032F8Y3B9vVWVYaJ6GMadnY3HuVxn1qnDzFSOFYloVNSEUd4qX41Cx1LOGtEFTZa0ZgCSjXU8jIbEXPB7/59SNgXQhScLZnGECRTnqshsuY+9Ovq2ybThmj9iiNkri3zSHl2gPMLeLrn7AwHjy+jGaWxJ+Rlbv pk0=-122, \tpk1=1366441931, \tck0=1514351017571084399, \tck1=5172012619356554.151, \tck2=V6WczEhfaHYPCfvG2SOWt3EO0oiBTvhC3aH3szPxaw6d7yKNXCXiOvV40fFVQDncjYh41ZgJKNhNJROaDEzJ2k/Hh2n6QGs39WTzXqqvdqr5NJicePOBp+8EoTbbH8iWEDbrmgMPtpu/08an5/rHtDAk0iTesa0oLyfTq+U9NtXKSV53Uu5kxF99JIDO/xTQaA68jxXQB+fCduFfHNsyUFO6jVY/KCe4k207D2CTasGJopL8D3WRf421YpMPVtq/gykmpMS16VqH71zCLt03X/Di+hwRtHj9hT/yShBPTrYjs9q+0K5FDgU+IeXtUJvJWPwcy0wlx91XmvM7iUjh034mvzhqjdstm5DMdOLukSH1U7qgzv/2VbjvEsLfbziwULkH2f/iqqIultcwAELVDGDWTawn+WG/+BCEnDRDfKO6BaaSY9egs0GSPyVUUvCaeNAk5Z/x7ZGuD3/tX/z6ZvB9GrBdCv8c41JrxZKdhyJE/dp8O/XvHUxMTIijMOFwPgQRiJ0qTYOR2l5PIk/eVR19BEnqXlkkGlaFKh3WjNkKjlU4 pk0=-51, \tpk1=1197429689, \tck0=1760885574115848297, \tck1=3335762327889102.546, \tck2=ZXhCDzNohjNsq7rilImZF9dx3aAHz4KpqFHXFQXSoEW5qCIqCTY4PzGOPKVjxgoMsod8+FUkLIQfOfcc0geuj/FD1A9D6c4kcwX6ty4qEgSpIRQH4WartYqBREbIAMzZCt5gIJIOo46Yq2l+DZ/kfs32uSBuIPMXJpXmwnJB pk0=-36, \tpk1=648916598, \tck0=7038942994308168306, \tck1=9158249922512408.692, 
...
...
[long list of missing rows]
...
...
, 'query': 'SELECT * FROM ks1.table1 WHERE col0=25714 '}]}]
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor ed9b280b-0925-40ae-be69-c2f49503a415`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ed9b280b-0925-40ae-be69-c2f49503a415)
- Show all stored logs command: `$ hydra investigate show-logs ed9b280b-0925-40ae-be69-c2f49503a415`

## Logs:
- **db-cluster-ed9b280b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed9b280b-0925-40ae-be69-c2f49503a415/20220422_060917/db-cluster-ed9b280b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed9b280b-0925-40ae-be69-c2f49503a415/20220422_060917/db-cluster-ed9b280b.tar.gz)
- **monitor-set-ed9b280b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed9b280b-0925-40ae-be69-c2f49503a415/20220422_060917/monitor-set-ed9b280b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed9b280b-0925-40ae-be69-c2f49503a415/20220422_060917/monitor-set-ed9b280b.tar.gz)
- **loader-set-ed9b280b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed9b280b-0925-40ae-be69-c2f49503a415/20220422_060917/loader-set-ed9b280b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed9b280b-0925-40ae-be69-c2f49503a415/20220422_060917/loader-set-ed9b280b.tar.gz)
- **sct-runner-ed9b280b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed9b280b-0925-40ae-be69-c2f49503a415/20220422_060917/sct-runner-ed9b280b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed9b280b-0925-40ae-be69-c2f49503a415/20220422_060917/sct-runner-ed9b280b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/154/)

**Comment by slivne** [comment]
Does this reproduce - easily,  if you start again with the same seed ? how long does it take to reproduce ?

If this reproduces - @kostja I'll assign to your team

**Comment by vponomaryov** [comment]
One more occurrence of this bug.
@slivne `gemini` jobs use `GeminiChaosMonkey` kind of nemesis in SCT which is not compatible with `nemesis_seed` feature (just fact).
I would also assume that 2 other following bugs (a bit older than this one) are about the same problem:
- https://github.com/scylladb/scylla/issues/10301
- https://github.com/scylladb/scylla/issues/10343

## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`
Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- ics-cdc-gemini-basic-3h-2022-1-oracle-db-node-9c197537-1 (52.214.87.7 | 10.0.1.243) (shards: 2)
- ics-cdc-gemini-basic-3h-2022-1-db-node-9c197537-5 (54.77.90.193 | 10.0.3.27) (shards: 2)
- ics-cdc-gemini-basic-3h-2022-1-db-node-9c197537-4 (3.250.156.63 | 10.0.0.153) (shards: 2)
- ics-cdc-gemini-basic-3h-2022-1-db-node-9c197537-3 (54.195.175.142 | 10.0.1.254) (shards: 2)
- ics-cdc-gemini-basic-3h-2022-1-db-node-9c197537-2 (54.195.154.237 | 10.0.0.28) (shards: 2)
- ics-cdc-gemini-basic-3h-2022-1-db-node-9c197537-1 (34.240.7.204 | 10.0.3.126) (shards: 2)


OS / Image: `ami-071c70d20f0fdbb2c` (aws: eu-west-1)

Test: `gemini-3h-ics-cdc-with-nemesis-test`
Test id: `9c197537-4f6d-44bc-b0ed-89e0045f04ad`
Test name: `enterprise-2022.1/SCT_Enterprise_Features/ICS/gemini-3h-ics-cdc-with-nemesis-test`
Test config file(s):

- [gemini-3h-ics-cdc-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/24fff36f7f430283a9dbd1286bb6e7415f6bf12c/test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml)

## Issue description

Gemini test failed during the disruptive "disrupt_remove_node_then_add_node" nemesis with following error message:

```
> 2022-04-28 17:18:30.886: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=eae67a6e-f4dc-43c9-80de-3e199c1cef95, source=GeminiTest.test_load_random_with_nemesis_cdc_reader (gemini_test.GeminiTest)() message=Traceback (most recent call last):
>   File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 100, in test_load_random_with_nemesis_cdc_reader
>     self.verify_results()                                                                            
>   File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results               
>     self.fail(self.gemini_results['results'])                                                        
> AssertionError: [{                                                                                
        'write_ops': 2649516,                                                                       
        'write_errors': 0,                                                                          
        'read_ops': 100913,                                                                         
        'read_errors': 1,                                                                           
        'errors': [{                                                                                
            'timestamp': '2022-04-28T15:12:21.306743345Z',                                          
            'message': 'Validation failed: row count differ (                                       
                test has 0 rows, oracle has 1 rows,                                                 
                test is missing rows: [                                                             
                    pk0=3658845429774183712,                                                        
                    pk1=27460328,                                                                   
                    ck0=QbGK4OV0WXKfSnBG8sAwKbj6HSkPjzW3N2yXXpIsrbZfHl9cAJ4P6d5L8klW7bEhsNf45Mw+hxxQuvEIbVbFhXAW3RJspttLT/afBXVufU0vFdyIb1TmqO/DxjuHWbBhoxEHM+wtlX+4DnxPfvtfRiKCwv9xBRTTQxZ/N/utTOUBytfkt4D0aNj4nUZ+OHP1v+lhOmdbSEONt5JBDIT87YUbvVpojQqS1+XuDHtaXf9vAdG39mv4zkwaXqaRLUw3GXzYRYqwbevCEF9kaRjrLna5oczv5sVl5tLlrhs/hGOie,          
                    ck1=-116                                                                        
                ],                                                                                  
                oracle is missing rows: []                                                          
            )',                                                                                     
            'query': 'SELECT * FROM ks1.table1 WHERE pk0=3658845429774183712 AND pk1=27460328 '     
        }]                                                                                          
}]
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9c197537-4f6d-44bc-b0ed-89e0045f04ad`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9c197537-4f6d-44bc-b0ed-89e0045f04ad)
- Show all stored logs command: `$ hydra investigate show-logs 9c197537-4f6d-44bc-b0ed-89e0045f04ad`

## Logs:
- **db-cluster-9c197537.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9c197537-4f6d-44bc-b0ed-89e0045f04ad/20220428_173017/db-cluster-9c197537.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9c197537-4f6d-44bc-b0ed-89e0045f04ad/20220428_173017/db-cluster-9c197537.tar.gz)
- **monitor-set-9c197537.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9c197537-4f6d-44bc-b0ed-89e0045f04ad/20220428_173017/monitor-set-9c197537.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9c197537-4f6d-44bc-b0ed-89e0045f04ad/20220428_173017/monitor-set-9c197537.tar.gz)
- **loader-set-9c197537.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9c197537-4f6d-44bc-b0ed-89e0045f04ad/20220428_173017/loader-set-9c197537.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9c197537-4f6d-44bc-b0ed-89e0045f04ad/20220428_173017/loader-set-9c197537.tar.gz)
- **sct-runner-9c197537.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9c197537-4f6d-44bc-b0ed-89e0045f04ad/20220428_173017/sct-runner-9c197537.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9c197537-4f6d-44bc-b0ed-89e0045f04ad/20220428_173017/sct-runner-9c197537.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/SCT_Enterprise_Features/job/ICS/job/gemini-3h-ics-cdc-with-nemesis-test/5/)
