### ISSUE TITLE
Scylla setup script fails at NTP setup

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla#10475]
## Installation details

Cluster size: 5 nodes (n1-standard-4)

Scylla Nodes used in this run:
- jepsen-ubuntu-db-node-2d685449-0-5 (34.148.0.36 | 10.142.0.96) (shards: -1)
- jepsen-ubuntu-db-node-2d685449-0-4 (34.73.216.183 | 10.142.0.95) (shards: -1)
- jepsen-ubuntu-db-node-2d685449-0-3 (35.196.208.79 | 10.142.0.94) (shards: -1)
- jepsen-ubuntu-db-node-2d685449-0-2 (34.139.172.21 | 10.142.0.93) (shards: -1)
- jepsen-ubuntu-db-node-2d685449-0-1 (35.196.235.128 | 10.142.0.92) (shards: -1)

OS / Image: `https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10` (gce: us-east1)

Test: `jepsen-test-all`
Test id: `2d685449-b2bb-4f5b-be4a-d0074dd0ec0c`
Test name: `scylla-master/jepsen/jepsen-test-all`
Test config file(s):

- [jepsen.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3615a6c5d451a30d2929dd1593784ba7c643783f/test-cases/jepsen/jepsen.yaml)

## Issue description

**>>>>>>>**
The initial setup for one of the Scylla nodes setup failed with:

```
2022-04-29 03:17:33.248: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=fa5c987c-bd0d-4e19-be10-c80c1326794b, source=JepsenTest.SetUp()
exception=[Node jepsen-ubuntu-db-node-2d685449-0-1 [35.196.235.128 | 10.142.0.92] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
Processing triggers for initramfs-tools (0.133+deb10u1) ...
update-initramfs: Generating /boot/initrd.img-4.19.0-20-cloud-amd64
This is a supported kernel version.
Command 'systemctl  is-active systemd-timesyncd' returned non-zero exit status: 3
----------  stdout  ----------
inactive
------------------------------
----------  stderr  ----------
------------------------------
NTP setup failed.
Stderr:
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_ntp_setup", line 56, in <module>
if systemd_unit('systemd-timesyncd').is_active() == 'active':
File "/opt/scylladb/scripts/scylla_util.py", line 381, in is_active
return out('systemctl {} is-active {}'.format(self.ctlparam, self._unit))
File "/opt/scylladb/scripts/scylla_util.py", line 34, in out
res.check_returncode()
File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 460, in check_returncode
raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command 'systemctl  is-active systemd-timesyncd' returned non-zero exit status 3.
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3523, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4211, in node_setup
self._scylla_post_install(node, install_scylla, nic_devname)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4287, in _scylla_post_install
node.scylla_setup(disks, devname)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 113, in inner
res = func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2261, in scylla_setup
self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --setup-nic-and-disks {}'
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
Processing triggers for initramfs-tools (0.133+deb10u1) ...
update-initramfs: Generating /boot/initrd.img-4.19.0-20-cloud-amd64
This is a supported kernel version.
Command 'systemctl  is-active systemd-timesyncd' returned non-zero exit status: 3
----------  stdout  ----------
inactive
------------------------------
----------  stderr  ----------
------------------------------
NTP setup failed.
Stderr:
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_ntp_setup", line 56, in <module>
if systemd_unit('systemd-timesyncd').is_active() == 'active':
File "/opt/scylladb/scripts/scylla_util.py", line 381, in is_active
return out('systemctl {} is-active {}'.format(self.ctlparam, self._unit))
File "/opt/scylladb/scripts/scylla_util.py", line 34, in out
res.check_returncode()
File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 460, in check_returncode
raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command 'systemctl  is-active systemd-timesyncd' returned non-zero exit status 3.
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2d685449-b2bb-4f5b-be4a-d0074dd0ec0c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2d685449-b2bb-4f5b-be4a-d0074dd0ec0c)
- Show all stored logs command: `$ hydra investigate show-logs 2d685449-b2bb-4f5b-be4a-d0074dd0ec0c`

## Logs:
- **db-cluster-2d685449.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2d685449-b2bb-4f5b-be4a-d0074dd0ec0c/20220429_032038/db-cluster-2d685449.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2d685449-b2bb-4f5b-be4a-d0074dd0ec0c/20220429_032038/db-cluster-2d685449.tar.gz)
- **monitor-set-2d685449.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2d685449-b2bb-4f5b-be4a-d0074dd0ec0c/20220429_032038/monitor-set-2d685449.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2d685449-b2bb-4f5b-be4a-d0074dd0ec0c/20220429_032038/monitor-set-2d685449.tar.gz)
- **loader-set-2d685449.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2d685449-b2bb-4f5b-be4a-d0074dd0ec0c/20220429_032038/loader-set-2d685449.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2d685449-b2bb-4f5b-be4a-d0074dd0ec0c/20220429_032038/loader-set-2d685449.tar.gz)
- **sct-runner-2d685449.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2d685449-b2bb-4f5b-be4a-d0074dd0ec0c/20220429_032038/sct-runner-2d685449.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2d685449-b2bb-4f5b-be4a-d0074dd0ec0c/20220429_032038/sct-runner-2d685449.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/jepsen/job/jepsen-test-all/102/)

**Comment by rayakurl** [comment]
Seems similar to https://github.com/scylladb/scylla/issues/10455

**Comment by syuu1228** [comment]
It is duplicated with #10455, and fix is at #10467 but it's not merged yet.

**Comment by yaronkaikov** [comment]
Closed with https://github.com/scylladb/scylladb/pull/10467
