### ISSUE TITLE
[ubuntu20] Rolling upgrade - with mixed cluster we have no access to any node, for few times until test times out

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#10530]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): from `4.5.5-0.20220328.c789a1819 with build-id 6bbf890a14b748856fae07c74d820afdd8bf3afe` to `4.5.6-0.20220424.85d3fe744 with build-id 7e9c62599667193cbfdd8eaa9305b90d7512aac2` (and also from `4.4.8-0.20211215.9af2e5ead with build-id e7f02d14170955cb7989a0b0c3eeaea0e3eb5950` with the same result)
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04 `VERSION="20.04.4 LTS (Focal Fossa)"`

steps in prior to the failure:

1. upgrade 1st node
2. upgrade 2nd node
3. downgrade 2nd node back to previous version
4. start upgrade of the 2nd node, again

at this point, we see many times the following message:
```
2022-04-25T22:39:46+00:00  rolling-upgrade-4-5-ubuntu-focal-db-node-d6097fd3-0-3 !WARNING | scylla:  [shard 5] io - (rate limiting dropped 151 similar messages) oversized request (length 131072) submitted. dazed and confuzed, trimming its weight from 53760 down to 44877
```

and we end up with the following error (that happens few times, most likely because of retries, until it fails the test):
```
[control connection] Error connecting to 10.142.0.78:9042: < t:2022-04-25 22:41:05,444 f:cluster.py      l:3392 c:cassandra.cluster    p:WARNING > [control connection] Error connecting to 10.142.0.78:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3504, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3561, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 3558, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 3660, in cassandra.cluster.ControlConnection._refresh_schema
  File "cassandra/metadata.py", line 142, in cassandra.metadata.Metadata.refresh
  File "cassandra/metadata.py", line 165, in cassandra.metadata.Metadata._rebuild_all
  File "cassandra/metadata.py", line 2443, in get_all_keyspaces
  File "cassandra/metadata.py", line 1952, in get_all_keyspaces
  File "cassandra/metadata.py", line 2640, in cassandra.metadata.SchemaParserV3._query_all
  File "cassandra/connection.py", line 981, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 979, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 1431, in cassandra.connection.ResponseWaiter.deliver
cassandra.OperationTimedOut: errors=None, last_host=None
```

we thought it could be an issue with the driver, and because SCT `branch-4.5` uses old C* driver, we changed it to use the latest Scylla driver, but we failed exactly the same.

logs (job that upgrades from 4.4):
[db logs](https://cloudius-jenkins-test.s3.amazonaws.com/d6097fd3-5fba-44be-98f8-a62818233741/20220425_233138/db-cluster-d6097fd3.tar.gz)
[loader logs](https://cloudius-jenkins-test.s3.amazonaws.com/d6097fd3-5fba-44be-98f8-a62818233741/20220425_233138/loader-set-d6097fd3.tar.gz)
[sct logs](https://cloudius-jenkins-test.s3.amazonaws.com/d6097fd3-5fba-44be-98f8-a62818233741/20220425_233138/sct-runner-d6097fd3.tar.gz)

logs (job that upgrades from 4.5):
[db logs](https://cloudius-jenkins-test.s3.amazonaws.com/0173ac2a-e448-4027-bf19-bda8543da197/20220425_231634/db-cluster-0173ac2a.tar.gz)
[loader logs](https://cloudius-jenkins-test.s3.amazonaws.com/0173ac2a-e448-4027-bf19-bda8543da197/20220425_231634/loader-set-0173ac2a.tar.gz)
[sct logs](https://cloudius-jenkins-test.s3.amazonaws.com/0173ac2a-e448-4027-bf19-bda8543da197/20220425_231634/sct-runner-0173ac2a.tar.gz)

**Comment by fgelcer** [comment]
there is a live monitor (it will live for 48h from now) [here](http://44.204.93.242:3000/d/c71ltw_nk/rolling-upgrade-ubuntu20-04-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1650919265882&to=1650929816282):

**Comment by avikivity** [comment]
Why are you keeping machines alive for 48h?

**Comment by fgelcer** [comment]
> Why are you keeping machines alive for 48h?

it is a monitor instance (it will cost around 4 dollars for the entire period) and it will avoid many people creating many monitor stacks, while we are trying to understand where this failure is coming from.

**Comment by roydahan** [comment]
The issue isn't relevant only to ubuntu20, it happened on all distros (occasionally).

**Comment by roydahan** [comment]
Few insights I collected so far:

Few insights I have till now on 10530:
1. It started happening on master "Tue, Jun 8, 2021, 6:33 PM" with 4.5.rc2.
2. The code for that connection exist there year before that.
3. It stopped happening on master on "Fri, Nov 26, 2021, 12:12 PM" (last time I see it in emails of runs) with ScyllaDB version: 4.5.1-0.20211024.4c0eac049.
4. No one really investigated it during all that period of master duty, some reported it, but didn't do anything with it, some ignored.
5. We switched using to cassandra-driver 3.22.0 from 3.13 on "Mar 11 16:04:53 2020"
6. We changed master to use scylla-driver 3.24.5 instead of cassandra-driver at "October 11th 2021".
7. We changed to 3.24.7 at  Wed Oct 20 11:34:15 2021
8. We changed to 3.24.8 at Fri Jan 14 14:04:41 2022.
9. @fgelcer tested with latest scylla-driver but issue still reproduced.

@fgelcer to test with SCT master branch and 4.5.6 to check if there was something else affecting this on SCT side.

**Comment by fgelcer** [comment]
builds # 2 and 3 passed, without any problem:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/4.5/job/rolling-upgrade-ubuntu20.04-test-4.5-from-sct-master/

**Comment by fgelcer** [comment]
> Few insights I collected so far:
> 
> Few insights I have till now on 10530:
> 
> 1. It started happening on master "Tue, Jun 8, 2021, 6:33 PM" with 4.5.rc2.
> 2. The code for that connection exist there year before that.
> 3. It stopped happening on master on "Fri, Nov 26, 2021, 12:12 PM" (last time I see it in emails of runs) with ScyllaDB version: 4.5.1-0.20211024.4c0eac049.
> 4. No one really investigated it during all that period of master duty, some reported it, but didn't do anything with it, some ignored.
> 5. We switched using to cassandra-driver 3.22.0 from 3.13 on "Mar 11 16:04:53 2020"
> 6. We changed master to use scylla-driver 3.24.5 instead of cassandra-driver at "October 11th 2021".
> 7. We changed to 3.24.7 at  Wed Oct 20 11:34:15 2021
> 8. We changed to 3.24.8 at Fri Jan 14 14:04:41 2022.
> 9. @fgelcer tested with latest scylla-driver but issue still reproduced.
> 
> @fgelcer to test with SCT master branch and 4.5.6 to check if there was something else affecting this on SCT side.

@roydahan , seems like switching to Scylla driver was the key to solve this issue (as as my previous comment), and running from master didn't reproduce this issue, so we can conclude this is related to SCT and close this issue.
