### ISSUE TITLE
offline-install: Failed to get D-Bus connection: No such file or directory on oel76

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#10574]
## Installation details

Cluster size: 1 nodes (i3.large)

Scylla Nodes used in this run:
- artifacts-oel76-jenkins-db-node-c7cb9978-1 (34.247.189.25 | 10.0.0.149) (shards: -1)

OS / Image: `ami-0d6a24fe35fdf5dc4` (aws: eu-west-1)

Test: `artifacts-oel76-nonroot-test`
Test id: `c7cb9978-3eed-4b0e-85fa-7a44cd2e6d18`
Test name: `enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test`
Test config file(s):

- [oel76.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/36fe5f381efbb6e84265a80610312dc0aa78921d/test-cases/artifacts/oel76.yaml)

## Issue description

**>>>>>>>**
artifacts-offline-install/artifacts-oel76-nonroot-test fails with an error of:
```
2022-05-16 01:21:31.873: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=8ee46fe1-81f5-4cc3-b146-3d9ea07a870c, source=ArtifactsTest.SetUp()
exception=[Node artifacts-oel76-jenkins-db-node-c7cb9978-1 [34.247.189.25 | 10.0.0.149] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'systemctl --user stop scylla-server.service'
Exit code: 1
Stdout:
Stderr:
Failed to get D-Bus connection: No such file or directory
Traceback (most recent call last):
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 3506, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4201, in node_setup
self.scylla_configure_non_root_installation(node=node, devname=nic_devname,
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4143, in scylla_configure_non_root_installation
node.stop_scylla_server(verify_down=False)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 2455, in stop_scylla_server
self.stop_service(service_name='scylla-server', timeout=timeout, ignore_status=ignore_status)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 2425, in stop_service
self._service_cmd(service_name=service_name, cmd='stop', timeout=timeout, ignore_status=ignore_status)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 2416, in _service_cmd
return self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/jenkins/slave/workspace/enterprise-2022.1/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'systemctl --user stop scylla-server.service'
Exit code: 1
Stdout:
Stderr:
Failed to get D-Bus connection: No such file or directory
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor c7cb9978-3eed-4b0e-85fa-7a44cd2e6d18`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c7cb9978-3eed-4b0e-85fa-7a44cd2e6d18)
- Show all stored logs command: `$ hydra investigate show-logs c7cb9978-3eed-4b0e-85fa-7a44cd2e6d18`

## Logs:
- **db-cluster-c7cb9978.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c7cb9978-3eed-4b0e-85fa-7a44cd2e6d18/20220516_012240/db-cluster-c7cb9978.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c7cb9978-3eed-4b0e-85fa-7a44cd2e6d18/20220516_012240/db-cluster-c7cb9978.tar.gz)
- **sct-runner-c7cb9978.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c7cb9978-3eed-4b0e-85fa-7a44cd2e6d18/20220516_012240/sct-runner-c7cb9978.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c7cb9978-3eed-4b0e-85fa-7a44cd2e6d18/20220516_012240/sct-runner-c7cb9978.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/artifacts-offline-install/job/artifacts-oel76-nonroot-test/2/)

**Comment by yarongilor** [comment]
Reproduced in 5.0 as well:

Might be reproduced in 5.0.
scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test got an error of:
```
2022-05-10 14:23:58.073: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=0acdf745-d525-459b-a3ed-a565fd29ad4c, source=ArtifactsTest.SetUp()
exception=[Node artifacts-oel76-jenkins-db-node-6721022c-1 [34.242.83.50 | 10.0.1.78] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'systemctl --user stop scylla-server.service'
Exit code: 1
Stdout:
Stderr:
Failed to get D-Bus connection: No such file or directory
Traceback (most recent call last):
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 3506, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4201, in node_setup
self.scylla_configure_non_root_installation(node=node, devname=nic_devname,
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4143, in scylla_configure_non_root_installation
node.stop_scylla_server(verify_down=False)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 2455, in stop_scylla_server
self.stop_service(service_name='scylla-server', timeout=timeout, ignore_status=ignore_status)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 2425, in stop_service
self._service_cmd(service_name=service_name, cmd='stop', timeout=timeout, ignore_status=ignore_status)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 2416, in _service_cmd
return self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'systemctl --user stop scylla-server.service'
Exit code: 1
Stdout:
Stderr:
Failed to get D-Bus connection: No such file or directory
```


## Installation details



Cluster size: 1 nodes (i3.large)

Scylla Nodes used in this run:
- artifacts-oel76-jenkins-db-node-6721022c-1 (34.242.83.50 | 10.0.1.78) (shards: -1)


OS / Image: `ami-0d6a24fe35fdf5dc4` (aws: eu-west-1)

Test: `artifacts-oel76-nonroot-test`
Test id: `6721022c-34ca-4d28-93a0-f9f1904e43e0`
Test name: `scylla-5.0/artifacts-offline-install/artifacts-oel76-nonroot-test`
Test config file(s):

- [oel76.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/93f03dd9be3b54c3266af62cc4db65c5bdb2c13a/test-cases/artifacts/oel76.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 6721022c-34ca-4d28-93a0-f9f1904e43e0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=6721022c-34ca-4d28-93a0-f9f1904e43e0)
- Show all stored logs command: `$ hydra investigate show-logs 6721022c-34ca-4d28-93a0-f9f1904e43e0`

## Logs:
- **db-cluster-6721022c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6721022c-34ca-4d28-93a0-f9f1904e43e0/20220510_142500/db-cluster-6721022c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6721022c-34ca-4d28-93a0-f9f1904e43e0/20220510_142500/db-cluster-6721022c.tar.gz)
- **sct-runner-6721022c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6721022c-34ca-4d28-93a0-f9f1904e43e0/20220510_142500/sct-runner-6721022c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6721022c-34ca-4d28-93a0-f9f1904e43e0/20220510_142500/sct-runner-6721022c.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/artifacts-offline-install/job/artifacts-oel76-nonroot-test/2/)

**Comment by syuu1228** [comment]
@yarongilor non-root mode is currently not supported on CentOS7 and RHEL7 variants (I think we dicided not to support it, support it from CentOS8).

In such distro, we still have supervisord mode (--supervisor):
https://github.com/scylladb/scylla/blob/master/unified/install.sh#L28
But we never documented it, unofficial feature.

**Comment by roydahan** [comment]
Ok, non-root offline installer isn't supported on OEL 76 (same as CentOS7).
