### ISSUE TITLE
Failed to stop messaging_service with smp 2

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1059]
With simple_kill_streaming_node_while_bootstrapping_test

export SCYLLA_EXT_OPTS="--smp 2 --memory 1G"

I found we have issue stop messaging_service.

```
total gc time (s)         : 0
avg gc time(ms)           : 47
stdev gc time(ms)         : 3
Total operation time      : 00:00:17
END
Flush cluster...
Start node 4...
Stop node 2...
ERROR

======================================================================
ERROR: simple_kill_streaming_node_while_bootstrapping_test (update_cluster_layout_tests.TestUpdateClusterLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asias/src/cloudius-systems/scylla-dtest/update_cluster_layout_tests.py", line 274, in simple_kill_stream$
ng_node_while_bootstrapping_test
    node2.stop()
  File "/home/asias/src/cloudius-systems/scylla-ccm/ccmlib/node.py", line 654, in stop
    raise NodeError("Problem stopping node %s" % self.name)
NodeError: Problem stopping node node2
-------------------- >> begin captured logging << --------------------


$ cat node2/logs/system.log |grep Drain
INFO  2016-03-18 16:32:45,688 [shard 0] storage_service - Drain on shutdown: starts
INFO  2016-03-18 16:32:48,167 [shard 0] storage_service - Drain on shutdown: stop_gossiping done
INFO  2016-03-18 16:32:48,182 [shard 0] storage_service - Drain on shutdown: shutdown rpc and cql server done

suggests we hang stopping messaging_service. 

```

With following debug code:

```
--- a/message/messaging_service.cc
+++ b/message/messaging_service.cc
@@ -280,7 +280,10 @@ future<> messaging_service::stop() {
         _server->stop(),
         parallel_for_each(_clients, [] (auto& m) {
             return parallel_for_each(m, [] (std::pair<const msg_addr, shard_info>& c) {
-                return c.second.rpc_client->stop();
+                logger.info("HJ: stopping addr={} beg", c.first);
+                return c.second.rpc_client->stop().then([addr = c.first] {
+                    logger.info("HJ: stopping addr={} end", addr);
+                });
             });
         })
     ).discard_result();

$ cat node2/logs/system.log|egrep  'beg|end'|grep stop
INFO  2016-03-18 16:32:48,182 [shard 0] messaging_service - HJ: stopping addr=127.0.0.4:0 beg
INFO  2016-03-18 16:32:48,182 [shard 0] messaging_service - HJ: stopping addr=127.0.0.3:0 beg
INFO  2016-03-18 16:32:48,182 [shard 0] messaging_service - HJ: stopping addr=127.0.0.1:0 beg
INFO  2016-03-18 16:32:48,182 [shard 0] messaging_service - HJ: stopping addr=127.0.0.4:0 beg
INFO  2016-03-18 16:32:48,182 [shard 0] messaging_service - HJ: stopping addr=127.0.0.3:0 beg
INFO  2016-03-18 16:32:48,182 [shard 0] messaging_service - HJ: stopping addr=127.0.0.1:0 beg
INFO  2016-03-18 16:32:48,182 [shard 0] messaging_service - HJ: stopping addr=127.0.0.4:0 beg
INFO  2016-03-18 16:32:48,183 [shard 0] messaging_service - HJ: stopping addr=127.0.0.4:0 end
INFO  2016-03-18 16:32:48,183 [shard 0] messaging_service - HJ: stopping addr=127.0.0.3:0 end
INFO  2016-03-18 16:32:48,183 [shard 0] messaging_service - HJ: stopping addr=127.0.0.1:0 end
INFO  2016-03-18 16:32:48,183 [shard 0] messaging_service - HJ: stopping addr=127.0.0.4:0 end
INFO  2016-03-18 16:32:48,183 [shard 0] messaging_service - HJ: stopping addr=127.0.0.3:0 end
INFO  2016-03-18 16:32:48,183 [shard 0] messaging_service - HJ: stopping addr=127.0.0.1:0 end
INFO  2016-03-18 16:32:48,188 [shard 1] messaging_service - HJ: stopping addr=127.0.0.1:0 beg
INFO  2016-03-18 16:32:48,188 [shard 1] messaging_service - HJ: stopping addr=127.0.0.3:0 beg
INFO  2016-03-18 16:32:48,188 [shard 1] messaging_service - HJ: stopping addr=127.0.0.4:0 beg
INFO  2016-03-18 16:32:48,189 [shard 1] messaging_service - HJ: stopping addr=127.0.0.1:0 end
INFO  2016-03-18 16:32:48,189 [shard 1] messaging_service - HJ: stopping addr=127.0.0.3:0 end

[asias@localhost test]$ cat node2/logs/system.log|egrep  'beg'|grep stop|wc -l
10
[asias@localhost test]$ cat node2/logs/system.log|egrep  'end'|grep stop|wc -l
8

We failed to stop 2 clients
```

**Comment by asias** [comment]
@slivne it turns out it is a rpc connection closing issue in seastar. @gleb-cloudius Can you take a look?
