### ISSUE TITLE
[centos8-arm offline install] Install house-keeping fails with: "libreloc/ld.so: cannot execute binary file: Exec format error"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#10605]
## Installation details

Cluster size: 1 nodes (r6gd.large)

Scylla Nodes used in this run:
- artifacts-centos8-jenkins-db-node-4eddf583-1 (34.248.139.67 | 10.0.2.203) (shards: -1)

OS / Image: `ami-07d54ca4e98347364` (aws: eu-west-1)

Test: `artifacts-centos8-arm-test`
Test id: `4eddf583-7dfd-478a-93c1-e42a50c00cc4`
Test name: `scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test`
Test config file(s):

- [centos8.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/598a6dc92f57e9f386a4280d92e73128151cafb5/test-cases/artifacts/centos8.yaml)

## Issue description

**>>>>>>>**
Install housekeeping script for centos-8 arm failed with:
```
2022-05-17 20:48:45.043: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=aebdbe83-72e2-43df-878f-b1f8405725e5, source=ArtifactsTest.SetUp()
exception=[Node artifacts-centos8-jenkins-db-node-4eddf583-1 [34.248.139.67 | 10.0.2.203] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\ntar xvfz ./unified_package.tar.gz\n./install.sh --housekeeping\nrm -f /tmp/scylla.yaml\n"'
Exit code: 126
Stdout:
scylla-tools/debian/control
scylla-tools/debian/copyright
scylla-tools/debian/rules
scylla-tools/debian/scylla-tools-core.install
scylla-tools/debian/scylla-tools.install
scylla-tools/debian/source/
scylla-tools/debian/source/format
scylla-tools/debian/source/options
uninstall.sh
.relocatable_package_version
Stderr:
+ tar xvfz ./unified_package.tar.gz
+ ./install.sh --housekeeping
./install.sh: line 128: libreloc/ld.so: cannot execute binary file: Exec format error
Traceback (most recent call last):
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 3506, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 4193, in node_setup
self._scylla_install(node)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 4272, in _scylla_install
node.offline_install_scylla(unified_package=self.params.get('unified_package'),
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 2090, in offline_install_scylla
self.remoter.run('sudo bash -cxe "%s"' % install_cmds)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\ntar xvfz ./unified_package.tar.gz\n./install.sh --housekeeping\nrm -f /tmp/scylla.yaml\n"'
Exit code: 126
Stdout:
scylla-tools/debian/control
scylla-tools/debian/copyright
scylla-tools/debian/rules
scylla-tools/debian/scylla-tools-core.install
scylla-tools/debian/scylla-tools.install
scylla-tools/debian/source/
scylla-tools/debian/source/format
scylla-tools/debian/source/options
uninstall.sh
.relocatable_package_version
Stderr:
+ tar xvfz ./unified_package.tar.gz
+ ./install.sh --housekeeping
./install.sh: line 128: libreloc/ld.so: cannot execute binary file: Exec format error
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4eddf583-7dfd-478a-93c1-e42a50c00cc4`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4eddf583-7dfd-478a-93c1-e42a50c00cc4)
- Show all stored logs command: `$ hydra investigate show-logs 4eddf583-7dfd-478a-93c1-e42a50c00cc4`

## Logs:
- **db-cluster-4eddf583.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4eddf583-7dfd-478a-93c1-e42a50c00cc4/20220517_204922/db-cluster-4eddf583.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4eddf583-7dfd-478a-93c1-e42a50c00cc4/20220517_204922/db-cluster-4eddf583.tar.gz)
- **sct-runner-4eddf583.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4eddf583-7dfd-478a-93c1-e42a50c00cc4/20220517_204922/sct-runner-4eddf583.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4eddf583-7dfd-478a-93c1-e42a50c00cc4/20220517_204922/sct-runner-4eddf583.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/artifacts-offline-install/job/artifacts-centos8-arm-test/4/)

**Comment by slivne** [comment]
The package that is passed

```
http://downloads.scylladb.com/unstable/scylla/branch-5.0/relocatable/2022-05-15T22:15:37Z/scylla-x86_64-unified-package-5.0.rc5.0.20220515.9da666e77.tar.gz
```

does not seem correct - can you please verify this is used

**Comment by yarongilor** [comment]
@slivne , it is similarly reproduced for Debian10-arm:
```

2022-05-19 13:13:56.364: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=936c5d04-26b3-4033-8801-050074852dbf, source=ArtifactsTest.SetUp()
exception=[Node artifacts-debian10-jenkins-db-node-a60ea2a3-1 [54.76.179.61 | 10.0.1.150] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\ntar xvfz ./unified_package.tar.gz\n./install.sh --housekeeping\nrm -f /tmp/scylla.yaml\n"'
Exit code: 126
Stdout:
scylla-tools/debian/control
scylla-tools/debian/copyright
scylla-tools/debian/rules
scylla-tools/debian/scylla-tools-core.install
scylla-tools/debian/scylla-tools.install
scylla-tools/debian/source/
scylla-tools/debian/source/format
scylla-tools/debian/source/options
uninstall.sh
.relocatable_package_version
Stderr:
+ tar xvfz ./unified_package.tar.gz
+ ./install.sh --housekeeping
./install.sh: line 128: libreloc/ld.so: cannot execute binary file: Exec format error
Traceback (most recent call last):
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 3506, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 4193, in node_setup
self._scylla_install(node)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 4272, in _scylla_install
node.offline_install_scylla(unified_package=self.params.get('unified_package'),
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 2090, in offline_install_scylla
self.remoter.run('sudo bash -cxe "%s"' % install_cmds)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/jenkins/slave/workspace/scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\ntar xvfz ./unified_package.tar.gz\n./install.sh --housekeeping\nrm -f /tmp/scylla.yaml\n"'
Exit code: 126
Stdout:
scylla-tools/debian/control
scylla-tools/debian/copyright
scylla-tools/debian/rules
scylla-tools/debian/scylla-tools-core.install
scylla-tools/debian/scylla-tools.install
scylla-tools/debian/source/
scylla-tools/debian/source/format
scylla-tools/debian/source/options
uninstall.sh
.relocatable_package_version
Stderr:
+ tar xvfz ./unified_package.tar.gz
+ ./install.sh --housekeeping
./install.sh: line 128: libreloc/ld.so: cannot execute binary file: Exec format error
```


## Installation details



Cluster size: 1 nodes (r6gd.large)

Scylla Nodes used in this run:
- artifacts-debian10-jenkins-db-node-a60ea2a3-1 (54.76.179.61 | 10.0.1.150) (shards: -1)


OS / Image: `ami-03505f4be3ad4f07b` (aws: eu-west-1)

Test: `artifacts-debian10-arm-test`
Test id: `a60ea2a3-187c-44b4-9acc-db6165173332`
Test name: `scylla-5.0/artifacts-offline-install/artifacts-debian10-arm-test`
Test config file(s):

- [debian10.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c1f2d6dae5e9a9193d25f464ee31cdd621f52e76/test-cases/artifacts/debian10.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor a60ea2a3-187c-44b4-9acc-db6165173332`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a60ea2a3-187c-44b4-9acc-db6165173332)
- Show all stored logs command: `$ hydra investigate show-logs a60ea2a3-187c-44b4-9acc-db6165173332`

## Logs:
- **db-cluster-a60ea2a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a60ea2a3-187c-44b4-9acc-db6165173332/20220519_131437/db-cluster-a60ea2a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a60ea2a3-187c-44b4-9acc-db6165173332/20220519_131437/db-cluster-a60ea2a3.tar.gz)
- **sct-runner-a60ea2a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a60ea2a3-187c-44b4-9acc-db6165173332/20220519_131437/sct-runner-a60ea2a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a60ea2a3-187c-44b4-9acc-db6165173332/20220519_131437/sct-runner-a60ea2a3.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/artifacts-offline-install/job/artifacts-debian10-arm-test/2/)
