### ISSUE TITLE
Segfault on shutdown in test_simple_kill_streaming_node_while_bootstrapping

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10668]
This is being hit frequently in CI and is pretty hard to reproduce locally.
I managed to get a coredump with scylladb/scylla@1f8b529e08bc613ca250314b51bbd41f728c1d7a
When bisecting https://github.com/scylladb/scylla/issues/10664.

node4.log:
```
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down service_memory_limiter
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down service_memory_limiter was successful
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down sst_dir_semaphore
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down sst_dir_semaphore was successful
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down storage_service
DEBUG 2022-05-26 14:06:21,096 [shard 0] storage_service - node_ops_singal_abort: ops_uuid={}
DEBUG 2022-05-26 14:06:21,096 [shard 0] storage_service - Awoke node_ops_abort_thread: node_ops_abort_queue=[{}]
DEBUG 2022-05-26 14:06:21,096 [shard 1] storage_service - node_ops_singal_abort: ops_uuid={}
DEBUG 2022-05-26 14:06:21,096 [shard 1] storage_service - Awoke node_ops_abort_thread: node_ops_abort_queue=[{}]
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down storage_service was successful
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down Raft
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down Raft was successful
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down direct_failure_detector
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down direct_failure_detector was successful
INFO  2022-05-26 14:06:21,096 [shard 0] init - Shutting down gossiper
INFO  2022-05-26 14:06:21,096 [shard 0] gossip - My status = BOOT
WARN  2022-05-26 14:06:21,096 [shard 0] gossip - No local state or state is in silent shutdown, not announcing shutdown
INFO  2022-05-26 14:06:21,096 [shard 0] gossip - Disable and wait for gossip loop started
Segmentation fault on shard 0.
Backtrace:
  0x4d5ebb8
  0x4d8f546
  0x4748d71
  0x7fb302c02a1f
  0x10cb4de
  0x10cc5fe
  0x10cb60a
  0x4fccc0f
  0x4fccb9f
  0x10ccaa5
  0x4dad7b9
  0x4d8ec28
  0x4d70f51
  0x4d7015c
  0x4d171f8
  0x4d166d1
  0x105dfef
  0x105b81a
  /lib64/libc.so.6+0x27b74
  0x105a7ad
```

Backtrace:
```
#0  0x00000000010cb4df in boost::intrusive::list_node_traits<void*>::set_previous (n=0x10cb420 <seastar::abort_source::request_abort()>, prev=0x0) at /usr/include/boost/intrusive/detail/list_node.hpp:57
#1  boost::intrusive::circular_list_algorithms<boost::intrusive::list_node_traits<void*> >::init (this_node=0x10cb420 <seastar::abort_source::request_abort()>) at /usr/include/boost/intrusive/circular_list_algorithms.hpp:74
#2  boost::intrusive::list_impl<boost::intrusive::bhtraits<seastar::abort_source::subscription, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)2, boost::intrusive::dft_tag, 1u>, unsigned long, false, void>::clear_and_dispose<seastar::abort_source::request_abort()::{lambda(seastar::abort_source::subscription*)#1}>(seastar::abort_source::request_abort()::{lambda(seastar::abort_source::subscription*)#1}) (this=0x7fffc5aa4480, disposer=...) at /usr/include/boost/intrusive/list.hpp:753
#3  seastar::abort_source::request_abort (this=<optimized out>) at ./seastar/include/seastar/core/abort_source.hh:116
#4  0x00000000010cc5ff in std::__invoke_impl<void, void (seastar::abort_source::*&)() noexcept, seastar::abort_source&>(std::__invoke_memfun_ref, void (seastar::abort_source::*&)() noexcept, seastar::abort_source&) (__f=<optimized out>, __t=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:67
#5  std::__invoke<void (seastar::abort_source::*&)() noexcept, seastar::abort_source&>(void (seastar::abort_source::*&)() noexcept, seastar::abort_source&) (__fn=<optimized out>, __args=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
#6  std::__apply_impl<void (seastar::abort_source::*&)() noexcept, std::tuple<seastar::abort_source&>, 0ul>(void (seastar::abort_source::*&)() noexcept, std::tuple<seastar::abort_source&>&&, std::integer_sequence<unsigned long, 0ul>) (__f=<optimized out>, __t=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1858
#7  std::apply<void (seastar::abort_source::*&)() noexcept, std::tuple<seastar::abort_source&> >(void (seastar::abort_source::*&)() noexcept, std::tuple<seastar::abort_source&>&&) (__f=<optimized out>, __t=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1869
#8  seastar::futurize<void>::apply<void (seastar::abort_source::*&)() noexcept, seastar::abort_source&>(void (seastar::abort_source::*&)() noexcept, std::tuple<seastar::abort_source&>&&) (func=<optimized out>, args=...) at ./seastar/include/seastar/core/future.hh:2105
#9  seastar::futurize_apply<void (seastar::abort_source::*&)() noexcept, seastar::abort_source&>(void (seastar::abort_source::*&)() noexcept, std::tuple<seastar::abort_source&>&&) (func=<optimized out>, args=...) at ./seastar/include/seastar/core/future.hh:2184
#10 seastar::sharded<seastar::abort_source>::invoke_on_all<void (seastar::abort_source::*)() noexcept>(seastar::smp_submit_to_options, void (seastar::abort_source::*)() noexcept)::{lambda(seastar::abort_source&)#1}::operator()(seastar::abort_source&) (this=<optimized out>, service=...) at ./seastar/include/seastar/core/sharded.hh:768
#11 std::__invoke_impl<seastar::future<void>, seastar::sharded<seastar::abort_source>::invoke_on_all<void (seastar::abort_source::*)() noexcept>(seastar::smp_submit_to_options, void (seastar::abort_source::*)() noexcept)::{lambda(seastar::abort_source&)#1}&, seastar::abort_source&>(std::__invoke_other, seastar::sharded<seastar::abort_source>::invoke_on_all<void (seastar::abort_source::*)() noexcept>(seastar::smp_submit_to_options, void (seastar::abort_source::*)() noexcept)::{lambda(seastar::abort_source&)#1}&, seastar::abort_source&) (__f=..., __args=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#12 std::__invoke_r<seastar::future<void>, seastar::sharded<seastar::abort_source>::invoke_on_all<void (seastar::abort_source::*)() noexcept>(seastar::smp_submit_to_options, void (seastar::abort_source::*)() noexcept)::{lambda(seastar::abort_source&)#1}&, seastar::abort_source&>(seastar::sharded<seastar::abort_source>::invoke_on_all<void (seastar::abort_source::*)() noexcept>(seastar::smp_submit_to_options, void (seastar::abort_source::*)() noexcept)::{lambda(seastar::abort_source&)#1}&, seastar::abort_source&) (__fn=..., __args=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:114
#13 std::_Function_handler<seastar::future<void> (seastar::abort_source&), seastar::sharded<seastar::abort_source>::invoke_on_all<void (seastar::abort_source::*)() noexcept>(seastar::smp_submit_to_options, void (seastar::abort_source::*)() noexcept)::{lambda(seastar::abort_source&)#1}>::_M_invoke(std::_Any_data const&, seastar::abort_source&) (__functor=..., __args=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
#14 0x00000000010cb60b in std::function<seastar::future<void> (seastar::abort_source&)>::operator()(seastar::abort_source&) const (this=0x6000001fef98, __args=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
#15 seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}::operator()() const (this=0x6000001fef90) at ./seastar/include/seastar/core/sharded.hh:750
#16 seastar::futurize<seastar::future<void> >::invoke<seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&>(seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&) (func=...) at ./seastar/include/seastar/core/future.hh:2141
#17 seastar::smp::submit_to<seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::smp_submit_to_options, seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&) (t=<optimized out>, options=..., func=...) at ./seastar/include/seastar/core/smp.hh:349
#18 seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const (this=<optimized out>, c=<optimized out>) at ./seastar/include/seastar/core/sharded.hh:749
#19 std::__invoke_impl<seastar::future<void>, seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}&, unsigned int>(std::__invoke_other, seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}&, unsigned int&&) (__f=..., __args=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#20 std::__invoke_r<seastar::future<void>, seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}&, unsigned int>(seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}&, unsigned int&&) (__fn=..., __args=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:114
#21 std::_Function_handler<seastar::future<void> (unsigned int), seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>)::{lambda(unsigned int)#1}>::_M_invoke(std::_Any_data const&, unsigned int&&) (__functor=..., __args=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
#22 0x0000000004fccc10 in std::function<seastar::future<void> (unsigned int)>::operator()(unsigned int) const (this=0x7fffc5aa45f0, __args=0) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
#23 seastar::futurize<seastar::future<void> >::invoke<std::function<seastar::future<void> (unsigned int)>, unsigned int>(std::function<seastar::future<void> (unsigned int)>&&, unsigned int&&) (func=..., args=<optimized out>) at ./seastar/include/seastar/core/future.hh:2141
#24 seastar::futurize_invoke<std::function<seastar::future<void> (unsigned int)>, unsigned int>(std::function<seastar::future<void> (unsigned int)>&&, unsigned int&&) (func=..., args=<optimized out>) at ./seastar/include/seastar/core/future.hh:2172
#25 seastar::parallel_for_each<boost::range_detail::integer_iterator<unsigned int>, boost::range_detail::integer_iterator<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(boost::range_detail::integer_iterator<unsigned int>, boost::range_detail::integer_iterator<unsigned int>, std::function<seastar::future<void> (unsigned int)>&&) (begin=begin@entry=..., end=..., func=...) at ./seastar/include/seastar/core/loop.hh:566
#26 0x0000000004fccba0 in seastar::internal::parallel_for_each_impl<boost::integer_range<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&) (range=..., func=...) at ./seastar/include/seastar/core/loop.hh:616
#27 seastar::futurize<seastar::future<void> >::invoke<seastar::future<void> (*&)(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&), boost::integer_range<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(seastar::future<void> (*&)(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&), boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&) (func=<optimized out>, args=..., args=...) at ./seastar/include/seastar/core/future.hh:2141
#28 seastar::futurize_invoke<seastar::future<void> (*&)(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&), boost::integer_range<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(seastar::future<void> (*&)(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&), boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&) (func=<optimized out>, args=..., args=...) at ./seastar/include/seastar/core/future.hh:2172
#29 seastar::parallel_for_each<boost::integer_range<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&) (range=..., func=...) at ./seastar/include/seastar/core/loop.hh:631
#30 seastar::internal::sharded_parallel_for_each(unsigned int, std::function<seastar::future<void> (unsigned int)>) (nr_shards=1751168, on_each_shard=<error reading variable: Cannot access memory at address 0xd68948088b480847>) at ./seastar/src/core/sharded.cc:33
#31 0x00000000010ccaa6 in seastar::sharded<seastar::abort_source>::sharded_parallel_for_each(std::function<seastar::future<void> (unsigned int)>) (this=<optimized out>, func=...) at ./seastar/include/seastar/core/sharded.hh:160
#32 seastar::sharded<seastar::abort_source>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (seastar::abort_source&)>) (this=<optimized out>, options=..., func=...) at ./seastar/include/seastar/core/sharded.hh:748
#33 seastar::sharded<seastar::abort_source>::invoke_on_all<void (seastar::abort_source::*)() noexcept>(seastar::smp_submit_to_options, void (seastar::abort_source::*)() noexcept) (this=<optimized out>, options=..., func=<optimized out>) at ./seastar/include/seastar/core/sharded.hh:767
#34 seastar::sharded<seastar::abort_source>::invoke_on_all<void (seastar::abort_source::*)() noexcept>(void (seastar::abort_source::*)() noexcept) (this=<optimized out>, func=<optimized out>) at ./seastar/include/seastar/core/sharded.hh:249
#35 stop_signal::signaled()::{lambda()#1}::operator()() const (this=<optimized out>) at main.cc:117
#36 seastar::futurize<seastar::future<void> >::invoke<stop_signal::signaled()::{lambda()#1}>(stop_signal::signaled()::{lambda()#1}&&) (func=...) at ./seastar/include/seastar/core/future.hh:2141
#37 seastar::futurize<seastar::future<void> >::invoke<stop_signal::signaled()::{lambda()#1}>(stop_signal::signaled()::{lambda()#1}&&, seastar::internal::monostate) (func=...) at ./seastar/include/seastar/core/future.hh:1985
#38 seastar::future<void>::then_impl<stop_signal::signaled()::{lambda()#1}, seastar::future<void> >(stop_signal::signaled()::{lambda()#1}&&) (this=0x60000035fc78, func=...) at ./seastar/include/seastar/core/future.hh:1607
#39 seastar::internal::call_then_impl<seastar::future<void> >::run<stop_signal::signaled()::{lambda()#1}>(seastar::future<void>&, stop_signal::signaled()::{lambda()#1}&&) (fut=..., func=...) at ./seastar/include/seastar/core/future.hh:1240
#40 seastar::future<void>::then<stop_signal::signaled()::{lambda()#1}, seastar::future<void> >(stop_signal::signaled()::{lambda()#1}&&) (this=0x60000035fc78, func=...) at ./seastar/include/seastar/core/future.hh:1526
#41 stop_signal::signaled (this=0x60000035fc38) at main.cc:116
#42 stop_signal::stop_signal()::{lambda()#2}::operator()() const (this=<optimized out>) at main.cc:124
#43 seastar::noncopyable_function<void ()>::direct_vtable_for<stop_signal::stop_signal()::{lambda()#2}>::call(seastar::noncopyable_function<void ()> const*) (func=<optimized out>) at ./seastar/include/seastar/util/noncopyable_function.hh:124
#44 0x0000000004dad7ba in seastar::noncopyable_function<void ()>::operator()() const (this=0x6000001ab880) at ./seastar/include/seastar/util/noncopyable_function.hh:209
#45 seastar::reactor::signals::poll_signal (this=0x600000077a10) at ./seastar/src/core/reactor.cc:664
#46 seastar::reactor::signal_pollfn::poll (this=<optimized out>) at ./seastar/src/core/reactor.cc:2452
#47 0x0000000004d8ec29 in seastar::reactor::poll_once (this=0x600000076000) at ./seastar/src/core/reactor.cc:3023
#48 seastar::reactor::do_run()::$_43::operator()() const (this=<optimized out>) at ./seastar/src/core/reactor.cc:2920
#49 std::__invoke_impl<bool, seastar::reactor::do_run()::$_43&>(std::__invoke_other, seastar::reactor::do_run()::$_43&) (__f=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#50 std::__invoke_r<bool, seastar::reactor::do_run()::$_43&>(seastar::reactor::do_run()::$_43&) (__fn=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:114
#51 std::_Function_handler<bool (), seastar::reactor::do_run()::$_43>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
#52 0x0000000004d70f52 in std::function<bool ()>::operator()() const (this=0x7fffc5aa47c0) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
#53 seastar::reactor::do_run (this=0x600000076000) at ./seastar/src/core/reactor.cc:2947
#54 0x0000000004d7015d in seastar::reactor::run (this=0x6000001ab880) at ./seastar/src/core/reactor.cc:2809
#55 0x0000000004d171f9 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffc5aa7298, ac=<optimized out>, ac@entry=30, av=<optimized out>, av@entry=0x7fffc5aa91f8, func=...) at ./seastar/src/core/app-template.cc:265
#56 0x0000000004d166d2 in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) (this=0x7fffc5aa7298, ac=30, av=0x7fffc5aa91f8, func=...) at ./seastar/src/core/app-template.cc:156
#57 0x000000000105dff0 in scylla_main (ac=30, av=0x7fffc5aa91f8) at main.cc:535
#58 0x000000000105b81b in std::function<int (int, char**)>::operator()(int, char**) const (this=0x7fffc5aa9020, __args=0x7fffc5aa91f8, __args=0x7fffc5aa91f8) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
#59 main (ac=30, av=0x7fffc5aa91f8) at main.cc:1575
(gdb) up
#46 seastar::reactor::signal_pollfn::poll (this=<optimized out>) at ./seastar/src/core/reactor.cc:2452
2452            return _r._signals.poll_signal();
(gdb) fr 1
#1  boost::intrusive::circular_list_algorithms<boost::intrusive::list_node_traits<void*> >::init (this_node=0x10cb420 <seastar::abort_source::request_abort()>) at /usr/include/boost/intrusive/circular_list_algorithms.hpp:74
74            NodeTraits::set_previous(this_node, null_node);
(gdb) p this_node
$1 = (boost::intrusive::circular_list_algorithms<boost::intrusive::list_node_traits<void*> >::node_ptr) 0x10cb420 <seastar::abort_source::request_abort()>
(gdb) p *this_node
$2 = {
  next_ = 0xc618ec8348535641,
  prev_ = 0x107f8000102444
}
```

**Comment by asias** [comment]
The backtrace does not show the real place we get the abort ;(

**Comment by asias** [comment]
@bhalevy I think this https://github.com/scylladb/scylla/commit/1f8b529e08bc613ca250314b51bbd41f728c1d7a simply revealed a bug during shutdown.

**Comment by asias** [comment]
I could not reproduce so far locally.

**Comment by asias** [comment]
The patch https://github.com/scylladb/scylla/commit/1f8b529e08bc613ca250314b51bbd41f728c1d7a makes node4 fails with streaming faster. During shutdown we had the abort.

The abort is unlikely related to the 1f8b529e08bc613ca250314b51bbd41f728c1d7a.

**Comment by bhalevy** [comment]
What happens here is that raft_group0 calls `request_abort` on the "global" stop_signal abort source that was passed down it from the storage_service, racing with the stop signal.
When `stop_signal.signaled` is called from the signal handler the abort_source on shard 0 was already aborted and calling request_abort twice dereferences a disengaged optional.

Here's the log with some additional instrumentations:
```
INFO  2022-05-26 20:43:04,641 [shard 0] init - Shutting down storage_service
DEBUG 2022-05-26 20:43:04,641 [shard 0] storage_service - node_ops_singal_abort: ops_uuid={}
INFO  2022-05-26 20:43:04,642 [shard 0] storage_service - raft_group0: abort 0x6000001ab880: requested=false
DEBUG 2022-05-26 20:43:04,642 [shard 0] seastar - compaction_manager aborting
DEBUG 2022-05-26 20:43:04,642 [shard 0] seastar - compaction_manager aborted
...
INFO  2022-05-26 20:43:04,642 [shard 0] gossip - My status = BOOT
WARN  2022-05-26 20:43:04,642 [shard 0] gossip - No local state or state is in silent shutdown, not announcing shutdown
INFO  2022-05-26 20:43:04,642 [shard 0] gossip - Disable and wait for gossip loop started
stop_signal: signaled on shard 0: abort_source=0x6000001ab880
terminate called after throwing an instance of 'std::bad_optional_access'
  what():  bad optional access
Aborting on shard 0.
```

https://github.com/scylladb/scylla/blob/19316dee94bf9cef6bcf2ae5f82078da9d78434a/service/raft/raft_group0.hh#L95-L100
and
https://github.com/scylladb/scylla/blob/19316dee94bf9cef6bcf2ae5f82078da9d78434a/service/storage_service.cc#L1484

were added in c22f945f11696068b28a54a59509183d16916e2a

@kostja why does raft group0 request abort on the abort source it was provided with?
Usually abort is requested top-down, not bottom-up.
I.e. raft_group0 doesn't know who's subscribed on the abort_source, and in this particular case
it shouldn't just request abort on shard 0.
The stop_signal abort_source is sharded and was designed to broadcast the stop signal abort to all shards.

**Comment by bhalevy** [comment]
Note: 5.0.rc5 is vulnerable.

**Comment by kostja** [comment]
@kbr- please take a look

**Comment by bhalevy** [comment]
I think that we should have a service that encapsulates the stop_signal that should be used by other services to change the server state, for e.g. isolate(), which we want to add to the table class when failing to flush the memtable, or force shutdown as in this case.

So instead of a reference to an abort_source, the storage service and raft group0 can get a reference to a sharded<system_control> service and can get the local abort_source from it, as well as call isolate() or shutdown() methods to yank the distributed abort source top-down.

Cc @xemul @avikivity

**Comment by kbr-** [comment]
I think that the objects which today get an `abort_source&` in order to subscribe to the source, should instead get a reference to something else, say `read_abort_source&`, which does not have a `request_abort` method, only a `subscribe` method. This would be an easy way to prevent this mistake in the future. There is only one "owner" of the abort source who is responsible for calling `request_abort`. Everyone else should only subscribe/check for abort and not have access to requesting.

**Comment by kostja** [comment]
@bhalevy answering your question, it's just a wrong assumption onwhether it's safe to call request_abort() twice on my side. I'd just make it safe, but @kbr- fix is also OK.

**Comment by bhalevy** [comment]
> @bhalevy answering your question, it's just a wrong assumption onwhether it's safe to call request_abort() twice on my side. I'd just make it safe, but @kbr- fix is also OK.

@kostja I think there's a design issue here, not only an implementation issue, that's easily solvable in the short term.

raft_group0 calling request_abort exemplifies a need for a way to trigger system-wide state changes like going into service mode (https://github.com/scylladb/scylla/issues/5489 which is similar to today's `storage_service::isolate`), or triggering shutdown.  This needs to be done on all shards and requesting abort on shard 0's top-level abort_source is just not the right way to do it and we need to expose a higher level mechanism that can be used to propagate such events to all shards.

**Comment by avikivity** [comment]
Backported to 5.0. This is raft, so not backporting further.
