### ISSUE TITLE
Many Scylla tests fail with new Seastar

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10689]
Trying to update to the latest Seastar, many tests fail in debug mode, apparently on an ASAN violation. See details in https://github.com/scylladb/scylla/pull/10688.
We need to figure out if it's a Scylla bug, or a Seastar bug, and fix it.

**Comment by nyh** [comment]
One of the failures can be reproduced locally by updating Seastar and:
```
ninja build/debug/scylla
test/alternator/run test_system_tables.py::test_fetch_from_system_tables
```
The backtrace I get locally is more informative:
```
 at pc 0x000013793438 bp 0x7f0245a523f0 sp 0x7f0245a523e8
READ of size 1 at 0x7f0245a524b7 thread T1 (reactor-1)
INFO  2022-05-30 02:09:02,589 [shard 0] alternator_ttl - sleeping 1 seconds until 
next period
    #0 0x13793437 in seastar::basic_sstring<char, unsigned int, 15u, true>::is_int
ernal() const ./seastar/include/seastar/core/sstring.hh:78:27
    #1 0x13796d20 in seastar::basic_sstring<char, unsigned int, 15u, true>::size()
 const ./seastar/include/seastar/core/sstring.hh:223:16
    #2 0x137d29f2 in seastar::basic_sstring<char, unsigned int, 15u, true>::operator==(seastar::basic_sstring<char, unsigned int, 15u, true> const&) const ./seastar/include/seastar/core/sstring.hh:550:28
    #3 0x1380946c in seastar::basic_sstring<char, unsigned int, 15u, true>::operator!=(seastar::basic_sstring<char, unsigned int, 15u, true> const&) const ./seastar/include/seastar/core/sstring.hh:553:17
    #4 0x1675b314 in db::snapshots_table::execute(reader_permit, db::result_collector&, db::virtual_table::query_restrictions const&)::'lambda'(replica::database&)::operator()(replica::database&) const (.resume) db/system_keyspace.cc:2035:52
    #5 0x16810d4d in std::experimental::coroutine_handle<seastar::internal::coroutine_traits_base<std::map<seastar::basic_sstring<char, unsigned int, 15u, true>, std::map<seastar::basic_sstring<char, unsigned int, 15u, true>, replica::table::snapshot_details, std::less<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, replica::table::snapshot_details> > >, std::less<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, std::map<seastar::basic_sstring<char, unsigned int, 15u, true>, replica::table::snapshot_details, std::less<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, replica::table::snapshot_details> > > > > > >::promise_type>::resume() const ./seastar/include/seastar/core/std-coroutine.hh:70:36
    #6 0x16810a78 in seastar::internal::coroutine_traits_base<std::map<seastar::basic_sstring<char, unsigned int, 15u, true>, std::map<seastar::basic_sstring<char, unsigned int, 15u, true>, replica::table::snapshot_details, std::less<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, replica::table::snapshot_details> > >, std::less<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, std::map<seastar::basic_sstring<char, unsigned int, 15u, true>, replica::table::snapshot_details, std::less<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, replica::table::snapshot_details> > > > > > >::promise_type::run_and_dispose() ./seastar/include/seastar/core/coroutine.hh:78:20
    #7 0x1a924e6e in seastar::reactor::run_tasks(seastar::reactor::task_queue&) build/debug/seastar/./seastar/src/core/reactor.cc:2356:14
    #8 0x1a92b4e6 in seastar::reactor::run_some_tasks() build/debug/seastar/./seastar/src/core/reactor.cc:2769:9

....

Address 0x7f0245a524b7 is located in stack of thread T1 (reactor-1) at offset 87 in frame
    #0 0x1675af9f in db::snapshots_table::execute(reader_permit, db::result_collector&, db::virtual_table::query_restrictions const&)::'lambda'(replica::database&)::operator()(replica::database&) const (.resume) db/system_keyspace.cc:2032

  This frame has 2 object(s):
    [32, 80) 'ref.tmp174' <== Memory access at offset 87 overflows this variable
    [112, 160) 'ref.tmp121'

...

SUMMARY: AddressSanitizer: stack-buffer-overflow ./seastar/include/seastar/core/sstring.hh:78:27 in seastar::basic_sstring<char, unsigned int, 15u, true>::is_internal() const
```

**Comment by nyh** [comment]
I can't figure out what's wrong in the line pointed by ASAN, or why the seemingly-benign Seastar changes changed anything, so now I started bisecting the Seastar changes. It's going to take quite some time because I need to compile Scylla to test each version :-(

**Comment by slivne** [comment]
@avikivity / @nyh maybe we should first revert the update and then bisect

**Comment by nyh** [comment]
> @avikivity / @nyh maybe we should first revert the update and then bisect

There's nothing to revert in Scylla because I didn't commit the Seastar-update because of this failure.
I'm now finishing the Seastar bisection, and then will be able to tell whether a broken Seastar patch needs to be reverted there, or maybe it's a real Scylla bug that got exposed by an innocent change. I'll hopefully report back in a few minutes (my bisecting nearly ended).

**Comment by xemul** [comment]
I did it already, please apply `[PATCH v2] system_keyspace: Save coroutine's captured variable on stack` from the ML

**Comment by xemul** [comment]
@nyh , :point_up:

**Comment by nyh** [comment]
Wow, what a colossal waste of time on my part :-( Sorry, I'll mix your patch with the Seastar update.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
