### ISSUE TITLE
2.3% chance of flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order failing in release mode

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#10720]
This is next (0abbd93b53830873922f8da8d817246cdb141a78), may not apply to master.

```
# ninja release-build && ./test.py --mode release --repeat 1000 flat_mutation_reader
[1/201] NINJA build/release/seastar/libseastar.a
ninja: Entering directory `build/release/seastar'
ninja: no work to do.
[2/200] NINJA build/release/seastar/libseastar_testing.a
ninja: Entering directory `build/release/seastar'
ninja: no work to do.
Found 105000 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[90689/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_abandoned_flat_mutation_reader_from_mutation.90698                                      
[90690/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.90703
[90733/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_mutation_reader_from_fragments_v2_as_mutation_source.90701             
[90734/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.90748
[92218/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_fragmenting_and_freezing.92223                                         
[92219/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.92233
[92745/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_abandoned_flat_mutation_reader_from_mutation.92753                     
[92746/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.92758
[94721/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_reverse_reader_v2_is_mutation_source.94694                             
[94722/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.94738
[94798/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_reverse_reader_memory_limit.94812                                      
[94799/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.94813
[94872/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_reverse_reader_memory_limit.94887                                      
[94873/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.94888
[95495/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_flat_mutation_reader_consume_two_partitions.95507                      
[95496/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.95503
[96756/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_flat_mutation_reader_consume_two_partitions.96767                      
[96757/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.96763
[97276/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_allow_reader_early_destruction.97290                                   
[97277/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.97288
[97664/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_reverse_reader_memory_limit.97677                                      
[97665/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.97678
[98730/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_fragmenting_and_freezing.98733                                         
[98731/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.98743
[99435/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_abandoned_flat_mutation_reader_from_mutation.99443                     
[99436/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.99448
[99583/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_fragmenting_and_freezing.99588                                         
[99584/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.99598
[100227/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_abandoned_flat_mutation_reader_from_mutation.100238                     
[100228/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.100243
[100321/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_allow_reader_early_destruction.100335                                   
[100322/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.100333
[102073/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_reverse_reader_memory_limit.102087                                      
[102074/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.102088
[102178/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_abandoned_flat_mutation_reader_from_mutation.102188                     
[102179/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.102193
[102301/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_flat_mutation_reader_consume_single_partition.102301                    
[102302/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.102313
[102928/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_abandoned_flat_mutation_reader_from_mutation.102938                     
[102929/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.102943
[103304/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_reverse_reader_memory_limit.103317                                      
[103305/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.103318
[103465/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_multi_range_reader.103475                                               
[103466/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.103483
[104474/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_abandoned_flat_mutation_reader_from_mutation.104483                     
[104475/105000]  boost   release [ FAIL ] flat_mutation_reader_test.test_reverse_reader_reads_in_native_reverse_order.104488
[105000/105000]  boost   release [ PASS ] flat_mutation_reader_test.test_reverse_reader_v2_is_mutation_source.104999                             
------------------------------------------------------------------------------
The following test(s) have failed: boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test boost/flat_mutation_reader_test
Summary: 23 of the total 105000 tests failed
Traceback (most recent call last):
  File "/home/avi/scylla-maint/./test.py", line 1139, in workaround_python26789
    code = await main()
  File "/home/avi/scylla-maint/./test.py", line 1120, in main
    write_consolidated_boost_junit_xml(options.tmpdir, mode)
  File "/home/avi/scylla-maint/./test.py", line 1071, in write_consolidated_boost_junit_xml
    test_xml = test.get_junit_etree()
  File "/home/avi/scylla-maint/./test.py", line 493, in get_junit_etree
    self.__junit_etree = ET.parse(self.xmlout)
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 3, column 27
```

**Comment by avikivity** [comment]
It was, in fact, 0abbd93b53830873922f8da8d817246cdb141a78, so master is okay.

**Comment by avikivity** [comment]
Not on master, so closing.
