### ISSUE TITLE
Cancelled tests in debug mode with CI on latest master

### ISSUE THREAD

**Issue by alecco** [scylladb/scylla#10852]
CI run had multiple test failures in debug mode unrelated to the change (in pytests).

https://jenkins.scylladb.com/job/releng/job/Scylla-CI/988/artifact/testlog/x86_64_debug/

bptree_stress_test, index_with_paging_test.test_index_with_paging, lwt_test, memtable_test, test_secondary_index, test_storage_service, test_tools.

`Test was cancelled
`

**Comment by alecco** [comment]
Found the problem

```
dictionary changed size during iteration
Traceback (most recent call last):
  File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 181, in run
    await test.run(options)
  File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 710, in run
    cluster.before_test(self.uname)
  File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 401, in before_test
    raise self.start_exception
  File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 181, in run
    await test.run(options)
  File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 710, in run
    cluster.before_test(self.uname)
  File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 401, in before_test
    raise self.start_exception
  File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 376, in install_and_start
    await server.install_and_start()
  File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 130, in install_and_start
    await self.start()
  File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 284, in start
    raise RuntimeError("""Failed to start server at host {}.
RuntimeError: Failed to start server at host 127.204.108.10.
Check the log files:
/jenkins/workspace/releng/Scylla-CI/scylla/testlog/test.py.log
/jenkins/workspace/releng/Scylla-CI/scylla/testlog/debug/scylla-10.log

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1208, in workaround_python26789
    code = await main()
  File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1175, in main
    await run_all_tests(signaled, options)
  File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1052, in run_all_tests
    await TestSuite.artifacts.cleanup_before_exit()
  File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/artifact_registry.py", line 39, in cleanup_before_exit
    for artifacts in self.exit_artifacts.values():
RuntimeError: dictionary changed size during iteration
```
