### ISSUE TITLE
Improvements to the test.py harness

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#10871]
The harness was recently updated to run CQL pytests on a pool of regular Scylla nodes. Previously, they would run using a special separate `cql_repl` binary.

It's quite hard right now to find the reason of a test failure. You need to look into multiple files and gather scattered pieces of information to see the whole picture.
Here's a list of potential improvements for simplifying the process.
The file "x86_64_test.py.log" is of little use.

Example: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/1036/artifact/testlog/x86_64_test.py.log
Potential improvements:

1.
```
Starting test #2: ...
Test #2 succeeded
...
Test #3 failed
```
Instead of printing only the test's unique ID (here, `2`), print the tests name as well: `logalloc_test.2` or something.

2.
```
starting server at host 127.153.173.10...
stopping server at host 127.153.173.2
stopped server at host 127.153.173.8
```
print the server's "name" in those log messages, like `scylla-10`. This will help find the log file which I should look into in case the server startup fails.

When concurrently running tests, if one of them fails, the others are cancelled. Example: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/1036/artifact/testlog/x86_64_debug/memtable_test.3.log
at the end:
```
=== TEST.PY SUMMARY START ===
Test was cancelled
=== TEST.PY SUMMARY END ===
```
why was it cancelled?

3.
It would be great if we saw the reason, e.g.:
```
Test was cancelled due to concurrent test failure: test X.123 has failed concurrently
```
or
```
Test was cancelled due to failure of Scylla startup for a concurrent test: scylla-10 (127.153.173.10) failed to start
```

When a node setup fails, the Jenkins console shows the error. Example: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/1036/consoleText
```
[2022-06-24T12:30:49.572Z] [2332/2336]   cql     debug  [ PASS ] lwt_test.2083 53.57s
[2022-06-24T12:30:55.454Z] [2333/2336]  boost    debug  [ PASS ] index_with_paging_test.test_index_with_paging.138 770.29s
[2022-06-24T12:31:01.343Z] [2334/2336]  boost    debug  [ PASS ] schema_changes_test.196 753.54s
[2022-06-24T12:31:18.028Z] errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.153.173.9:9042
[2022-06-24T12:31:18.029Z] Traceback (most recent call last):
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1208, in workaround_python26789
[2022-06-24T12:31:18.029Z]     code = await main()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1175, in main
[2022-06-24T12:31:18.029Z]     await run_all_tests(signaled, options)
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1047, in run_all_tests
[2022-06-24T12:31:18.029Z]     await reap(done, pending, signaled)
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1029, in reap
[2022-06-24T12:31:18.029Z]     result = coro.result()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 181, in run
[2022-06-24T12:31:18.029Z]     await test.run(options)
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 707, in run
[2022-06-24T12:31:18.029Z]     async with self.suite.clusters.instance() as cluster:
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/pool.py", line 52, in __aenter__
[2022-06-24T12:31:18.029Z]     self.obj = await self.pool.get()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/pool.py", line 36, in get
[2022-06-24T12:31:18.029Z]     await self.pool.put(await self.build())
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 358, in create_cluster
[2022-06-24T12:31:18.029Z]     await cluster.install_and_start()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 376, in install_and_start
[2022-06-24T12:31:18.029Z]     await server.install_and_start()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 130, in install_and_start
[2022-06-24T12:31:18.029Z]     await self.start()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 290, in start
[2022-06-24T12:31:18.029Z]     if await self.cql_is_up():
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 230, in cql_is_up
[2022-06-24T12:31:18.029Z]     session.execute("CREATE KEYSPACE k WITH REPLICATION = {" +
[2022-06-24T12:31:18.029Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/cluster.py", line 2668, in execute
[2022-06-24T12:31:18.029Z]     return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state, host, execute_as).result()
[2022-06-24T12:31:18.029Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/cluster.py", line 4953, in result
[2022-06-24T12:31:18.029Z]     raise self._final_exception
[2022-06-24T12:31:18.029Z] cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.153.173.9:9042
[2022-06-24T12:31:21.584Z] [Pipeline] echo
[2022-06-24T12:31:22.308Z] Error: test debug failed, error: |hudson.AbortException: script returned exit code 255|.
```

This is a stack trace from an exception which was unhandled in the test harness, if I understand correctly.  The harness or part of it crashed.

4.
Failures during node setup should be catched and the details printed here but also in the `x86_64_test.py.log` file. Here, part of node/cluster setup involves performing schema changes, and one of these failed; we should expect this, catch it, and print the details in a digestible form. Note that this happened because we were setting up server X, but at the same performing a schema change at server Y as part of the setup process of X (I know, weird). The message should say that the failure occurred during the setup of X, because a schema change at Y failed, as part of the setup process.

For example, this is how the above error could look like in `x86_64_test.py.log` (and also in the main Jenkins output):
```
starting server at host 127.153.173.10 (scylla-10)...
ERROR: Setting up server 127.153.173.10 (scylla-10) failed: while setting up the server, we tried to execute "CREATE KEYSPACE ..." on server <ip-of-second-server> (<name-of-second-server>), but it failed due to error: <blah blah blah driver failed to connect>
```

5. For CQL tests, print the set of nodes which are used to execute it:
```
Starting CQL test #2: ...; Executing it on nodes scylla-10 (127.153.173.10), NAME2 (IP2), ...
```

**Comment by avikivity** [comment]
Not a regression, not backporting.

**Comment by avikivity** [comment]
Or rather, not a bug.
