### ISSUE TITLE
test_twcs_multiple_sstables_during_decommission struck during nodetool flush

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#10897]
Test was running ~2.5 hours, and timeout of the whole run killed it in middle of `nodetool flush`

```
INFO  2022-06-27 11:25:28,331 [shard 0] init - Scylla version 5.1.dev-0.20220627.9c231ad0ce58 with build-id 13692a7ecdd3902878788d8c6249eef476e24b7f starting ...
```

```
03:45:46,977 390     cassandra.cluster              INFO     dtest_setup.py      :399  | test_twcs_multiple_sstables_during_decommission: New Cassandra host <Host: 127.0.97.2:9042 datacenter1> discovered
06:33:09,594 390     errors                         ERROR    conftest.py         :199  | test_twcs_multiple_sstables_during_decommission: test failed: 
self = <compaction_additional_test.TestTimeWindowDataSegregation object at 0x7f58a0dd28e0>

    def test_twcs_multiple_sstables_during_decommission(self):
        synthetic_minutes = 20
        [node1, node2], session = self.prepare(2)
        self._create_ks_cl_with_twcs(session, rf=2)
    
        insert_statement = session.prepare("INSERT INTO {}.{} (pk, ck, v) VALUES (?, ?, ?)"
                                           "USING TIMESTAMP ?".format(self.keyspace_name, self.table_name))
        rand_pks = set()
        while len(rand_pks) < 100:
            rand_pks.add(random.randint(-2147483647, 2147483647))
    
>       self.run_prepared_statement(node1, session, insert_statement, rand_pks, 0, synthetic_minutes)

compaction_additional_test.py:1522: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
compaction_additional_test.py:1461: in run_prepared_statement
    node.flush()
../scylla/.local/lib/python3.9/site-packages/ccmlib/scylla_node.py:1234: in flush
    super(ScyllaNode, self).flush(ks, table)
../scylla/.local/lib/python3.9/site-packages/ccmlib/node.py:1328: in flush
    self.nodetool(cmd)
../scylla/.local/lib/python3.9/site-packages/ccmlib/scylla_node.py:684: in nodetool
    return super().nodetool(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ccmlib.scylla_node.ScyllaNode object at 0x7f58a10af430>, cmd = 'flush'
capture_output = True, wait = True, timeout = None

    def nodetool(self, cmd, capture_output=True, wait=True, timeout=None):
        """
        Setting wait=False makes it impossible to detect errors,
        if capture_output is also False. wait=False allows us to return
        while nodetool is still running.
        When wait=True, timeout may be set to a number, in seconds,
        to limit how long the function will wait for nodetool to complete.
        """
        if capture_output and not wait:
            raise common.ArgumentError("Cannot set capture_output while wait is False.")
        env = self.get_env()
        if self.is_scylla() and not self.is_docker():
            host = self.address()
        else:
            host = 'localhost'
        nodetool = self.get_tool('nodetool')
    
        if not isinstance(nodetool, list):
            nodetool = [nodetool]
        # see https://www.oracle.com/java/technologies/javase/8u331-relnotes.html#JDK-8278972
        nodetool.extend(['-h', host, '-p', str(self.jmx_port), '-Dcom.sun.jndi.rmiURLParsing=legacy'])
        nodetool.extend(cmd.split())
        if capture_output:
            p = subprocess.Popen(nodetool, universal_newlines=True, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = p.communicate(timeout=timeout)
        else:
            p = subprocess.Popen(nodetool, env=env, universal_newlines=True)
            stdout, stderr = None, None
    
        if wait:
            exit_status = p.wait(timeout=timeout)
            if exit_status != 0:
>               raise NodetoolError(" ".join(nodetool), exit_status, stdout, stderr)
E               ccmlib.node.NodetoolError: Nodetool command '/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/f2bb676d279ff6551c5cf718b8a9a6b01fbd4d4e/scylla-tools-java/bin/nodetool -h 127.0.97.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy flush' failed; exit status: 2; stdout: Cassandra has shutdown.
E               ; stderr: error: null
E               -- StackTrace --
E               java.io.EOFException
E               	at java.io.DataInputStream.readByte(DataInputStream.java:267)
E               	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:240)
E               	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
E               	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
E               	at javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
E               	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1020)
E               	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:298)
E               	at com.sun.proxy.$Proxy7.forceKeyspaceFlush(Unknown Source)
E               	at org.apache.cassandra.tools.NodeProbe.forceKeyspaceFlush(NodeProbe.java:464)
E               	at org.apache.cassandra.tools.nodetool.Flush.execute(Flush.java:45)
E               	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.runInternal(NodeTool.java:309)
E               	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:294)
E               	at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:196)
E               	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:62)

../scylla/.local/lib/python3.9/site-packages/ccmlib/node.py:795: NodetoolError
```

https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/42/artifact/logs-full.release.021/dtest-gw1.log
https://jenkins.scylladb.com/blue/organizations/jenkins/scylla-master%2Fdtest-daily-release/detail/dtest-daily-release/42/pipeline/

Reproduced locally, and the third time the refresh is called stuck forever

**Comment by fruch** [comment]
I can confim `5.1.dev-0.20220707.6cdd5b9ff543` didn't get stuck on the flush anymore

**Comment by bhalevy** [comment]
Confined to master. no backport needed.

**Comment by slivne** [comment]
issues closed please check #10878 prior to sending the next iteration
