### ISSUE TITLE
Compaction metadata differs in format between Cassandra 2.1.8 and Scylla

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#109]
When importing sstables from Origin to Scylla, an exception occur:

```
WARN  15:03:03 Cardinality merge failed.
com.clearspring.analytics.stream.cardinality.HyperLogLogPlus$HyperLogLogPlusMergeException: Cannot merge estimators of different sizes
    at com.clearspring.analytics.stream.cardinality.HyperLogLogPlus.addAll(HyperLogLogPlus.java:893) ~[stream-2.5.2.jar:na]
    at com.clearspring.analytics.stream.cardinality.HyperLogLogPlus.merge(HyperLogLogPlus.java:962) ~[stream-2.5.2.jar:na]
    at org.apache.cassandra.io.sstable.SSTableReader.getApproximateKeyCount(SSTableReader.java:278) ~[main/:na]
    at org.apache.cassandra.db.compaction.CompactionTask.runMayThrow(CompactionTask.java:151) [main/:na]
    at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) [main/:na]
    at org.apache.cassandra.db.compaction.CompactionTask.executeInternal(CompactionTask.java:73) [main/:na]
    at org.apache.cassandra.db.compaction.AbstractCompactionTask.execute(AbstractCompactionTask.java:59) [main/:na]
    at org.apache.cassandra.db.compaction.CompactionManager$BackgroundCompactionTask.run(CompactionManager.java:244) [main/:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```

This seems to happen because the HyperLogLog function we use is different from the one that Java provides.

This exception is benign, because when failing to use cardinality for estimations, Cassandra will fall back to using Index Summary.

**Comment by glommer** [comment]
@raphaelsc didn't we fix this ?

**Comment by glommer** [comment]
Benign at best, and not sure if it reproduces for MC.
tagging Wontfix

**Comment by avikivity** [comment]
Probably will reproduce for mc, compaction metadata has not changed
