### ISSUE TITLE
testIndexOnKeyWithReverseClustering failure on next

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10918]
When I run on Scylla next

> test/cql-pytest/run cassandra_tests/validation/entities/secondary_index_test.py::testIndexOnKeyWithReverseClustering

I get a failure:
```
    def testIndexOnKeyWithReverseClustering(cql, test_keyspace):
        with create_table(cql, test_keyspace, "(k1 int, k2 int, v int, PRIMARY K
EY ((k1, k2), v)) WITH CLUSTERING ORDER BY (v DESC)") as table:
            execute(cql, table, "CREATE INDEX ON %s (k2)")
    
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (0, 0, 1)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (0, 1, 2)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (0, 0, 3)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (1, 0, 4)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (1, 1, 5)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (2, 0, 7)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (2, 1, 8)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (3, 0, 1)")
    
            for _ in before_and_after_flush(cql, table):
>               assert_rows(execute(cql, table, "SELECT * FROM %s WHERE k2 = 0 A
ND v >= 2 ALLOW FILTERING"),
                           [2, 0, 7],
                           [0, 0, 3],
                           [1, 0, 4])
cassandra_tests/validation/entities/secondary_index_test.py:390: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

result = <cassandra.cluster.ResultSet object at 0x7f025bf28730>
expected = ([2, 0, 7], [0, 0, 3], [1, 0, 4]), allresults = [], @py_assert2 = 0
@py_assert7 = 3

    def assert_rows(result, *expected):
        allresults = list(result)
>       assert len(allresults) == len(expected)
E       assert 0 == 3
E        +  where 0 = len([])
E        +  and   3 = len(([2, 0, 7], [0, 0, 3], [1, 0, 4]))

cassandra_tests/porting.py:166: AssertionError
```

On my machine it happens every time so it doesn't appear to be a fluke. If this is a regression, how was it not caught by CI? Maybe it's somehow specific to my build machine (clang 14.0.0)?

None of the other cql-pytest tests appear to fail - just this one.

**Comment by nyh** [comment]
It turns out that this is a recent regression, I bisected it to:

```
6d943e6cd024eb36a6ff2b8779d2760d3a74fa22 is the first bad commit
commit 6d943e6cd024eb36a6ff2b8779d2760d3a74fa22
Author: Avi Kivity <avi@scylladb.com>
Date:   Sun Jun 12 19:19:37 2022 +0300

    cql3: expr: drop column_maybe_subscripted
    
    column_maybe_subscripted is a variant<column_value*, subscript*> that
    existed for two reasons:
      1. evaluation of subscripts and of columns took different paths.
      2. calculation of the type of column or column[sub] took different paths.
    
    Now that all evaluations go through evaluate(), and the types are
    present in the expression itself, there is no need for column_maybe_subscripted
    and it is replaced with plain expressions.

 cql3/expr/expression.cc | 105 +++++++++++-------------------------------------
 1 file changed, 23 insertions(+), 82 deletions(-)
```

@avikivity any thoughts?

Two surprising things:
1. I can easily and with 100% consistency reproduce this test failure when building and running on Fedora 36 but it appears that the CI never reproduced with dbuild.
2. The test doesn't have subscripts which the commit was supposedly about - but still broke something it does (it uses an index plus filtering).

FYI @psarna @cvybhu

**Comment by avikivity** [comment]
Very strange. Maybe it's a miscompile with the newer compiler.

**Comment by avikivity** [comment]
Practically everything fails for me on Fedora 35 with

```
___________________________________ test_cql ___________________________________

request = <FixtureRequest for <Function test_cql>>
cql = <cassandra.cluster.Session object at 0x7fd3b6003f40>
keyspace = <async_generator object keyspace at 0x7fd3b4e54ac0>

    def test_cql(request, cql, keyspace):
        # Comments allowed by CQL - -- and //
        comment_re = re.compile(r"^\s*((--|//).*)?$")
        # A comment is not a delimiter even if ends with one
        delimiter_re = re.compile(r"^(?!\s*(--|//)).*;\s*$")
        with open(request.config.getoption("--input"), "r") as ifile, \
                open(request.config.getoption("--output"), "a") as ofile:
>           cql.set_keyspace(keyspace)

test/pylib/cql_repl/cql_repl.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib64/python3.10/site-packages/cassandra/cluster.py:3331: in set_keyspace
    self.execute('USE %s' % (protect_name(keyspace),))
/usr/local/lib64/python3.10/site-packages/cassandra/metadata.py:1573: in protect_name
    return maybe_escape_name(name)
/usr/local/lib64/python3.10/site-packages/cassandra/metadata.py:1600: in maybe_escape_name
    if is_valid_name(name):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = <async_generator object keyspace at 0x7fd3b4e54ac0>

    def is_valid_name(name):
        if name is None:
            return False
>       if name.lower() in cql_keywords_reserved:
E       AttributeError: 'async_generator' object has no attribute 'lower'
```

It's some driver mismatch, but I can't tell what.

**Comment by nyh** [comment]
@avikivity this is a different issue, in test code that @alecco just added recently. @alecco / @kostja can you please take a look? But it deserves a separate issue.

**Comment by alecco** [comment]
Checking

**Comment by alecco** [comment]
> @avikivity this is a different issue, in test code that @alecco just added recently. @alecco / @kostja can you please take a look? But it deserves a separate issue.

https://github.com/scylladb/scylla/issues/10925

**Comment by nyh** [comment]
I get two other cql-pytest tests failing for me on Fedora 36, both from `cassandra_tests/validation/operations/select_test.py`:
`testContainsOnPartitionKey` and `testContainsOnPartitionKeyPart`. Both of these failures are because of an error message that changed - so I suspect they should fail on any system, not just Fedora 36. 

@kostja @alecco could we have had a test.py regression recently which might have cause it to not run cql-pytest or not run some of its tests, specifically all the tests in the cassandra_tests/ subdirectory (these are the translated Cassandra unit tests?)

**Comment by nyh** [comment]
@avikivity it turns out that the reason why we didn't see these test failures in Jenkins wasn't my different compiler but more simply - `test.py` stopped running these tests when it switched away from using my `test/cql-pytest/run` script to different in-test.py code.

So this is most likely a real regression caused by your https://github.com/scylladb/scylla/commit/6d943e6cd024eb36a6ff2b8779d2760d3a74fa22, not a miscompilation. Can you please try to run yourself:

```
test/cql-pytest/run cassandra_tests/validation/entities/secondary_index_test.py::testIndexOnKeyWithReverseClustering
```

and see if it fails for you too? Thanks.

**Comment by psarna** [comment]
@nyh I can confirm that it fails on my Fedora 35:
```
[sarna@localhost scylla]$ pytest -vvv -s test/cql-pytest/cassandra_tests/validation/entities/secondary_index_test.py::testIndexOnKeyWithReverseClustering
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.10.4, pytest-6.2.4, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/sarna/repo/scylla/test/cql-pytest, configfile: pytest.ini
plugins: asyncio-0.14.0
collected 1 item                                                                                                                                                                         

test/cql-pytest/cassandra_tests/validation/entities/secondary_index_test.py::testIndexOnKeyWithReverseClustering FAILED

======================================================================================== FAILURES ========================================================================================
__________________________________________________________________________ testIndexOnKeyWithReverseClustering ___________________________________________________________________________

cql = <cassandra.cluster.Session object at 0x7f302486f340>, test_keyspace = 'cql_test_1657006209979'

    def testIndexOnKeyWithReverseClustering(cql, test_keyspace):
        with create_table(cql, test_keyspace, "(k1 int, k2 int, v int, PRIMARY KEY ((k1, k2), v)) WITH CLUSTERING ORDER BY (v DESC)") as table:
            execute(cql, table, "CREATE INDEX ON %s (k2)")
    
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (0, 0, 1)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (0, 1, 2)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (0, 0, 3)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (1, 0, 4)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (1, 1, 5)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (2, 0, 7)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (2, 1, 8)")
            execute(cql, table, "INSERT INTO %s (k1, k2, v) VALUES (3, 0, 1)")
    
            for _ in before_and_after_flush(cql, table):
>               assert_rows(execute(cql, table, "SELECT * FROM %s WHERE k2 = 0 AND v >= 2 ALLOW FILTERING"),
                           [2, 0, 7],
                           [0, 0, 3],
                           [1, 0, 4])

test/cql-pytest/cassandra_tests/validation/entities/secondary_index_test.py:390: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

result = <cassandra.cluster.ResultSet object at 0x7f302486cf70>, expected = ([2, 0, 7], [0, 0, 3], [1, 0, 4]), allresults = [], @py_assert2 = 0, @py_assert7 = 3

    def assert_rows(result, *expected):
        allresults = list(result)
>       assert len(allresults) == len(expected)
E       assert 0 == 3
E         +0
E         -3

test/cql-pytest/cassandra_tests/porting.py:166: AssertionError
----------------------------------------------------------------------------------- Captured log setup -----------------------------------------------------------------------------------
WARNING  cassandra.cluster:conftest.py:66 [control connection] Error connecting to ::1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3522, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3544, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1620, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 831, in cassandra.connection.Connection.factory
  File "/home/sarna/.local/lib/python3.10/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 898, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('::1', 9042, 0, 0)]. Last error: Connection refused
WARNING  cassandra.connection:libevreactor.py:370 An authentication challenge was not sent, this is suspicious because the driver expects authentication (configured authenticator = PlainTextAuthenticator)
WARNING  cassandra.connection:libevreactor.py:370 An authentication challenge was not sent, this is suspicious because the driver expects authentication (configured authenticator = PlainTextAuthenticator)
================================================================================ short test summary info =================================================================================
FAILED test/cql-pytest/cassandra_tests/validation/entities/secondary_index_test.py::testIndexOnKeyWithReverseClustering - assert 0 == 3
=================================================================================== 1 failed in 0.40s ====================================================================================

```

**Comment by psarna** [comment]
@nyh what I also find very disturbing is that locally running `./test.py -- mode dev` does **not** seem to run these test cases indeed. I can only see the failures after I run pytest manually with specific parameters, asking for `cassandra_tests` to be covered. So we definitely have a regression in the test suite.

**Comment by psarna** [comment]
oh, you already created https://github.com/scylladb/scylla/issues/10962 for that, never mind

**Comment by nyh** [comment]
> @nyh what I also find very disturbing is that locally running `./test.py -- mode dev` does **not** seem to run these test cases indeed. I can only see the failures after I run pytest manually with specific parameters, asking for `cassandra_tests` to be covered.

You can also run the good old `test/cql-pytest/run`, which still works well. Just like it always did, it runs Scylla for you, and runs pytest for you - which runs all the tests, including everything in `cassandra_tests/`, unless you choose to run only specific tests. Only `test.py` is broken - because unlike test/cql/pytest/run it tries to run each test file _separately_, and gets the list of test files wrong (it doesn't go into subdirectories like pytest does). Indeed I opened an issue about it #10962.

**Comment by cvybhu** [comment]
I can try debugging `testIndexOnKeyWithReverseClustering`, I'm familiar with the code that the bisected commit modified.
This looks more urgent than the rewrite that I'm working on right now.
@avikivity do you want to do this, or do you have other stuff to do?
