### ISSUE TITLE
nodetool repair command failed with exit code 2  while tables were dropped in parallel.

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#10936]
## Installation details

Kernel Version: 5.13.0-1029-aws
Scylla version (or git commit hash): `2022.1~rc8-20220612.16fe5fba7` with build-id `65d0f21ffc7b178a9ea2d7f6184acd357201209f`
Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-2022-1-db-node-94df267a-9 (18.184.111.49 | 10.0.3.151) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-8 (52.59.212.197 | 10.0.3.42) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-7 (18.158.60.226 | 10.0.0.211) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-6 (3.67.133.112 | 10.0.3.4) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-5 (52.28.59.24 | 10.0.0.223) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-4 (18.197.20.77 | 10.0.1.41) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-3 (3.71.184.203 | 10.0.1.71) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-2 (3.70.223.152 | 10.0.3.23) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-16 (3.121.185.221 | 10.0.3.25) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-15 (35.159.15.31 | 10.0.0.99) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-14 (18.195.141.176 | 10.0.0.21) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-13 (3.71.199.77 | 10.0.2.65) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-12 (3.71.44.48 | 10.0.3.48) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-11 (3.125.50.0 | 10.0.1.19) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-10 (18.184.15.51 | 10.0.3.5) (shards: 8)
- longevity-twcs-48h-2022-1-db-node-94df267a-1 (3.121.110.66 | 10.0.1.224) (shards: 8)

OS / Image: `ami-0b6f5064822903b9a` (aws: eu-central-1)

Test: `longevity-twcs-48h-test`
Test id: `94df267a-f1ee-4f55-b7bb-8bdd59933a28`
Test name: `enterprise-2022.1/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/31980805f3c66f99000c577cde15c50b6adfe97f/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

During job which is running TWCS,  Nemesis NoCorrupt repair executed 3 times. The nemesis prepare several tables and then execute nodetool repair and while command has been running, drop created tables. The repair command failed 2 times with next error:
first time on node 15:
```
Command: '/usr/bin/nodetool  repair '

Exit code: 2

Stdout:

[2022-06-23 05:22:52,288] Starting repair command #308, repairing 1 ranges for keyspace drop_table_during_repair_ks_5 (parallelism=SEQUENTIAL, full=true)
[2022-06-23 05:28:02,424] Repair session 308 
[2022-06-23 05:28:02,424] Repair session 308 finished
[2022-06-23 05:28:02,430] Starting repair command #309, repairing 1 ranges for keyspace drop_table_during_repair_ks_7 (parallelism=SEQUENTIAL, full=true)
[2022-06-23 05:33:07,554] Repair session 309 
[2022-06-23 05:33:07,555] Repair session 309 finished
[2022-06-23 05:33:07,561] Starting repair command #310, repairing 1 ranges for keyspace drop_table_during_repair_ks_6 (parallelism=SEQUENTIAL, full=true)
[2022-06-23 05:38:07,700] Repair session 310 failed
[2022-06-23 05:38:07,700] Repair session 310 finished

Stderr:

error: Repair job has failed with the error message: [2022-06-23 05:38:07,700] Repair session 310 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2022-06-23 05:38:07,700] Repair session 310 failed
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)


```
Second time on node 10
```
Command: '/usr/bin/nodetool  repair '

Exit code: 2

Stdout:

[2022-06-23 09:21:50,212] Repair session 1 finished
[2022-06-23 09:21:50,219] Starting repair command #2, repairing 1 ranges for keyspace drop_table_during_repair_ks_3 (parallelism=SEQUENTIAL, full=true)
[2022-06-23 09:26:52,344] Repair session 2 
[2022-06-23 09:26:52,344] Repair session 2 finished
[2022-06-23 09:26:52,352] Starting repair command #3, repairing 1 ranges for keyspace drop_table_during_repair_ks_8 (parallelism=SEQUENTIAL, full=true)
[2022-06-23 09:31:56,474] Repair session 3 
[2022-06-23 09:31:56,474] Repair session 3 finished
[2022-06-23 09:31:56,478] Starting repair command #4, repairing 1 ranges for keyspace drop_table_during_repair_ks_5 (parallelism=SEQUENTIAL, full=true)
[2022-06-23 09:36:56,596] Repair session 4 failed
[2022-06-23 09:36:56,597] Repair session 4 finished

Stderr:

error: Repair job has failed with the error message: [2022-06-23 09:36:56,596] Repair session 4 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2022-06-23 09:36:56,596] Repair session 4 failed
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)

```

According to log, repair stop compaction for dropped table, and after command failed.

```
md-1992-big-Data.db:level=0:origin=compaction]
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 0] compaction - [Compact system_schema.keyspaces 09503840-f2d9-11ec-96bb-21973e9028b2] Compacted 2 sstables to [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-2008-big-Data.db:level=0]. 26kB to 13kB (~50% of original) in 64ms = 207kB/s. ~256 total partitions merged to 20.
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 2] compaction - [Compact system.truncated 097e9b40-f2d9-11ec-b760-21983e9028b2] Compacting [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-642-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-634-big-Data.db:level=0:origin=compaction]
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 2] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table drop_table_during_repair_ks_9.standard1 due to table removal
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 0] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table drop_table_during_repair_ks_9.standard1 due to table removal
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 6] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table drop_table_during_repair_ks_9.standard1 due to table removal
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 3] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table drop_table_during_repair_ks_9.standard1 due to table removal
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 5] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table drop_table_during_repair_ks_9.standard1 due to table removal
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 4] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table drop_table_during_repair_ks_9.standard1 due to table removal
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 7] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table drop_table_during_repair_ks_9.standard1 due to table removal
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 1] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table drop_table_during_repair_ks_9.standard1 due to table removal
2022-06-23T09:44:12+00:00 longevity-twcs-48h-2022-1-db-node-94df267a-10 !    INFO |  [shard 0] schema_tables - Schema version changed to 4b3c3d9c-0796-304f-85a9-735e8b91ae57
```

could be related to https://github.com/scylladb/scylla/issues/9237

- Restore Monitor Stack command: `$ hydra investigate show-monitor 94df267a-f1ee-4f55-b7bb-8bdd59933a28`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=94df267a-f1ee-4f55-b7bb-8bdd59933a28)
- Show all stored logs command: `$ hydra investigate show-logs 94df267a-f1ee-4f55-b7bb-8bdd59933a28`

## Logs:
- **db-cluster-94df267a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/94df267a-f1ee-4f55-b7bb-8bdd59933a28/20220623_120332/db-cluster-94df267a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/94df267a-f1ee-4f55-b7bb-8bdd59933a28/20220623_120332/db-cluster-94df267a.tar.gz)
- **monitor-set-94df267a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/94df267a-f1ee-4f55-b7bb-8bdd59933a28/20220623_120332/monitor-set-94df267a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/94df267a-f1ee-4f55-b7bb-8bdd59933a28/20220623_120332/monitor-set-94df267a.tar.gz)
- **loader-set-94df267a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/94df267a-f1ee-4f55-b7bb-8bdd59933a28/20220623_120332/loader-set-94df267a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/94df267a-f1ee-4f55-b7bb-8bdd59933a28/20220623_120332/loader-set-94df267a.tar.gz)
- **sct-runner-94df267a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/94df267a-f1ee-4f55-b7bb-8bdd59933a28/20220623_120332/sct-runner-94df267a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/94df267a-f1ee-4f55-b7bb-8bdd59933a28/20220623_120332/sct-runner-94df267a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-twcs-48h-test/4/)

**Comment by bhalevy** [comment]
@asias it looks like repair didn't tolerate the table removal as it used to

**Comment by asias** [comment]
This is 2022.1 branch. 

We need to backport https://github.com/scylladb/scylla/pull/10124.

**Comment by avikivity** [comment]
Is it a regression? Since which commit?

**Comment by avikivity** [comment]
And is this issue a duplicate?

**Comment by asias** [comment]
> Is it a regression? Since which commit?

It is a regression for 2022.1 and 5.0 branch and master branch.

It was since a8ad385ecd3e2b372db3c354492dbe57d9d91760.

**Comment by roydahan** [comment]
@slivne don't we need it in 2022.1 and 5.0?

**Comment by slivne** [comment]
@avikivity lets backport to 5.0

**Comment by mykaul** [comment]
> @avikivity lets backport to 5.0

ping @avikivity

**Comment by mykaul** [comment]
ping @avikivity - do we need this still in 2022.1?

**Comment by denesb** [comment]
@Deexie fixed repair+table drop last year, closing.
