### ISSUE TITLE
test/cql-pytest/run-cassandra doesn't work with Java 17

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10946]
The script `test/cql-pytest/run-cassandra` (to run cql-pytest tests against Cassandra) does not seem to work out-of-the-box on Fedora 36, where "java" points by default to Java 17.

I see many errors coming from netty, but the Cassandra startup continues, until one final error:
```
Exception (java.lang.AssertionError) encountered during startup: java.lang.reflect.InaccessibleObjectException: Unable to make field private int java.io.
FileDescriptor.fd accessible: module java.base does not "opens java.io" to unnamed module @161b062a
java.lang.AssertionError: java.lang.reflect.InaccessibleObjectException: Unable to make field private int java.io.FileDescriptor.fd accessible: module ja
va.base does not "opens java.io" to unnamed module @161b062a
        at org.apache.cassandra.utils.FBUtilities.getProtectedField(FBUtilities.java:824)
        at org.apache.cassandra.utils.NativeLibrary.<clinit>(NativeLibrary.java:83)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:258)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:765)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:889)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private int java.io.FileDescriptor.fd accessible: module java.base does no
t "opens java.io" to unnamed module @161b062a
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.apache.cassandra.utils.FBUtilities.getProtectedField(FBUtilities.java:819)
        ... 4 more

```

**Comment by nyh** [comment]
Unfortunately, it appears that Cassandra itself is not ready for Java 17 - see https://issues.apache.org/jira/browse/CASSANDRA-16895. It might be possible to work around this (e.g., by running Cassandra compiled on Java 11 on Java 17, and using additional security-circumventing options on startup such as listed https://lists.apache.org/thread/hny49r5vlg4nn9d53n3fksxvjg71joqz) but let's not worry about that until Cassandra itself is ready for Java 17.
Until then, the run-cassandra script should focus about using a Java 11 or even Java 8 JRE, if installed on the system (Fedora 36 has the java-11-openjdk-headless and java-1.8.0-openjdk-headless packages, and our install-dependencies.sh even installs the latter by default!),

**Comment by avikivity** [comment]
Test only, not backporting.
