### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Liao-JianHao** [scylladb/scylla#10992]
DEBUG: Get a provider from the provider queue: ProxylistsProvider

/app/scylla/scheduler.py:36: RuntimeWarning: coroutine 'Browser.new_page' was never awaited

  continue

RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Process Process-1:

Traceback (most recent call last):

  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap

    self.run()

  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/app/scylla/scheduler.py", line 31, in fetch_ips

    for url in provider.urls():

  File "/app/scylla/providers/proxylists_provider.py", line 39, in urls

    ret.update(self.gen_url_for_country(self.country_patten.findall(relative_path)[0]))

  File "/app/scylla/providers/proxylists_provider.py", line 47, in gen_url_for_country

    ret.append('http://www.proxylists.net/{}'.format(a.attrs['href']))

AttributeError: 'HtmlElement' object has no attribute 'attrs'

**Comment by avikivity** [comment]
Wrong project, this is a different scylla.
