### ISSUE TITLE
ami: nodetool status prints lots of log if it fails to write to directory cassandra.logdir_IS_UNDEFINED

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1113]
We should set the log directory properly instead of writing to the current directory.

```
cd /etc/scylla/
[centos@ip-172-31-34-22 scylla]$ nodetool status
02:26:54,009 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-tools.xml]
02:26:54,009 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
02:26:54,009 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
02:26:54,009 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/tmp/tmp.m4JZ6KQbXF/logback.xml]
02:26:54,111 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
02:26:54,116 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/tmp/tmp.m4JZ6KQbXF/logback.xml]] every 60 seconds.
02:26:54,116 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
02:26:54,123 |-INFO in ch.qos.logback.classic.joran.action.JMXConfiguratorAction - begin
02:26:54,204 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
02:26:54,210 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
02:26:54,259 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@43738a82 - Will use zip compression
02:26:54,296 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
02:26:54,328 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: cassandra.logdir_IS_UNDEFINED/system.log
02:26:54,328 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [cassandra.logdir_IS_UNDEFINED/system.log]
02:26:54,329 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Failed to create parent directories for [/etc/scylla/cassandra.logdir_IS_UNDEFINED/system.log]
02:26:54,329 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(cassandra.logdir_IS_UNDEFINED/system.log,true) call failed. java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
        at java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
        at      at java.io.FileOutputStream.open0(Native Method)
        at      at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at      at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at      at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
        at      at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:150)
        at      at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
        at      at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
        at      at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
        at      at org.apache.cassandra.utils.FBUtilities.<clinit>(FBUtilities.java:67)
        at      at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:233)
        at      at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:201)
02:26:54,329 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
02:26:54,331 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
02:26:54,333 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
02:26:54,334 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
02:26:54,334 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
02:26:54,335 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
02:26:54,335 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.thinkaurelius.thrift] to ERROR
02:26:54,335 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
02:26:54,335 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@75881071 - Registering current configuration as safe fallback point

Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns    Host ID                               Rack
UN  54.200.244.184  54.57 KB   256     ?       cf2d0150-3c53-4a53-aad5-641f97f62fa8  2b
UN  54.213.19.116   54.57 KB   256     ?       690003d5-c9cb-4649-92ff-f0f6423a8284  2b
UN  54.187.174.143  50.04 KB   256     ?       661cd93d-4d54-4ae1-abd5-dcc2514f336d  2b

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

```
[centos@ip-172-31-34-22 scylla]$ cd /tmp
[centos@ip-172-31-34-22 tmp]$ ls
hsperfdata_centos  hsperfdata_root  hsperfdata_scylla  ssh-m3Wm3QJuh5  systemd-private-16aec24914d448198a070ef46dba866c-ntpd.service-N7ylxB
[centos@ip-172-31-34-22 tmp]$ nodetool status
Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns    Host ID                               Rack
UN  54.200.244.184  54.57 KB   256     ?       cf2d0150-3c53-4a53-aad5-641f97f62fa8  2b
UN  54.213.19.116   54.57 KB   256     ?       690003d5-c9cb-4649-92ff-f0f6423a8284  2b
UN  54.187.174.143  50.04 KB   256     ?       661cd93d-4d54-4ae1-abd5-dcc2514f336d  2b

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
[centos@ip-172-31-34-22 tmp]$ ls
cassandra.logdir_IS_UNDEFINED  hsperfdata_centos  hsperfdata_root  hsperfdata_scylla  ssh-m3Wm3QJuh5  systemd-private-16aec24914d448198a070ef46dba866c-ntpd.service-N7ylxB
```

**Comment by slivne** [comment]
Its related to permissions - I'll collect some data from users I think they have a workaround - a better option is probably to disable the logging all together by default

**Comment by asias** [comment]
Running nodetool generates a  cassandra.logdir_IS_UNDEFINED directory in $pwd looks ugly. I am for disabling the log.

**Comment by penberg** [comment]
@asias @slivne AFAICT, this is fixed by https://github.com/scylladb/scylla-tools-java/commit/133571bb104fcce8500294837ff1ae514a06fa08

**Comment by asias** [comment]
@penberg I am closing it.

**Comment by avikivity** [comment]
Backport candidate label applied by mistake, removing.
