### ISSUE TITLE
Missing api-doc files result in silent failure

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#11499]
If scylla fails to open the `json` files for the api-doc (swagger), requests to api endpoints result in silent failure and the connection being abruptly closed. Some clients (e.g. python's urllib) don't handle this well: the rest api uses chunked encoding and abruptly closing the connection -- while correct per protocol in case of errors -- results in the last 0 chunk not being sent, which results in large errors in some clients. Example:
```
# scylla-api-client  -lm
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 696, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 763, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 700, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 792, in read_chunked
    self._original_response.close()
  File "/usr/lib64/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scylla-api-client", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/cli.py", line 95, in main
    scylla_api = load_api(node_address=node_address, port=port)
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/cli.py", line 59, in load_api
    scylla_api.load()
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/api.py", line 390, in load
    module_json = self.client.get_raw_api_json(f"{module_def['path']}/")
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/rest/scylla_rest_client.py", line 11, in get_raw_api_json
    if api := self.get(f"/api-doc{resource_path}"):
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/rest/scylla_rest_client.py", line 16, in get
    return super().get(resource_path=resource_path, query_params=query_params)
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/rest/__init__.py", line 69, in get
    return requests.get(url=url, params=query_params, headers=headers)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 756, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by nyh** [comment]
I opened a Seastar issue https://github.com/scylladb/seastar/issues/1209 on something we could have done to make the error clearer in this case, but I think there is also the question of why Scylla (or Seastar?) didn't log the error from the response body writer (@denesb said he saw nothing in the log). The error message should have mentioned what file was missing, and bonus points for mentioning the "api_doc_dir" configuration option which can configure the location of that file.
