### ISSUE TITLE
Nodetool complains about logging configuration

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#1150]
## Installation details

Scylla version (or git commit hash): 1.0-rc2
Cluster size: 1
OS: Ubuntu/Docker

## Problem

When I run `nodetool` in our Ubuntu-based Docker container, I'm greeted with this error message because `nodetool` wants `logback-tools.xml` but it's not part of our packages:

```
scylla@cc9444ec6154:/$ nodetool 
07:16:14,023 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-tools.xml]
07:16:14,023 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
07:16:14,023 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
07:16:14,023 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/tmp/tmp.x23eViP1tW/logback.xml]
07:16:14,066 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
07:16:14,069 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/tmp/tmp.x23eViP1tW/logback.xml]] every 60 seconds. 
07:16:14,069 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
07:16:14,072 |-INFO in ch.qos.logback.classic.joran.action.JMXConfiguratorAction - begin
07:16:14,108 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
07:16:14,110 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
07:16:14,136 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@6457cbd9 - Will use zip compression
07:16:14,152 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
07:16:14,167 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: cassandra.logdir_IS_UNDEFINED/system.log
07:16:14,167 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [cassandra.logdir_IS_UNDEFINED/system.log]
07:16:14,167 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Failed to create parent directories for [/cassandra.logdir_IS_UNDEFINED/system.log]
07:16:14,168 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(cassandra.logdir_IS_UNDEFINED/system.log,true) call failed. java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
	at java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
	at 	at java.io.FileOutputStream.open(Native Method)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:150)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at 	at org.apache.cassandra.utils.FBUtilities.<clinit>(FBUtilities.java:67)
	at 	at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:233)
	at 	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:201)
07:16:14,168 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
07:16:14,169 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
07:16:14,170 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
07:16:14,171 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
07:16:14,171 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
07:16:14,172 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
07:16:14,172 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.thinkaurelius.thrift] to ERROR
07:16:14,172 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
07:16:14,172 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2ccf8c7f - Registering current configuration as safe fallback point

usage: nodetool [(-h <host> | --host <host>)]
        [(-pw <password> | --password <password>)]
        [(-pwf <passwordFilePath> | --password-file <passwordFilePath>)]
        [(-u <username> | --username <username>)] [(-p <port> | --port <port>)]
        <command> [<args>]

The most commonly used nodetool commands are:
    cfhistograms        Print statistic histograms for a given column family
    cfstats             Print statistics on column families
    cleanup             Triggers the immediate cleanup of keys no longer belonging to a node. By default, clean all keyspaces
    clearsnapshot       Remove the snapshot with the given name from the given keyspaces. If no snapshotName is specified we will remove all snapshots
    compact             Force a (major) compaction on one or more column families
    compactionhistory   Print history of compaction
    compactionstats     Print statistics on compactions
    decommission        Decommission the *node I am connecting to*
    describecluster     Print the name, snitch, partitioner and schema version of a cluster
    describering        Shows the token ranges info of a given keyspace
    disablegossip       Disable gossip (effectively marking the node down)
    drain               Drain the node (stop accepting writes and flush all column families)
    enablegossip        Reenable gossip
    flush               Flush one or more column families
    getendpoints        Print the end points that owns the key
    getlogginglevels    Get the runtime logging levels
    gossipinfo          Shows the gossip information for the cluster
    help                Display help information
    info                Print node information (uptime, load, ...)
    listsnapshots       Lists all the snapshots along with the size on disk and true size.
    move                Move node on the token ring to a new token
    netstats            Print network information on provided host (connecting node by default)
    proxyhistograms     Print statistic histograms for network operations
    rebuild             Rebuild data by streaming from other nodes (similarly to bootstrap)
    refresh             Load newly placed SSTables to the system without restart
    removenode          Show status of current node removal, force completion of pending removal or remove provided ID
    repair              Repair one or more column families
    ring                Print information about the token ring
    scrub               Scrub (rebuild sstables for) one or more column families
    setlogginglevel     Set the log level threshold for a given class. If both class and level are empty/null, it will reset to the initial configuration
    snapshot            Take a snapshot of specified keyspaces or a snapshot of the specified column family
    status              Print cluster information (state, load, IDs, ...)
    statusgossip        Status of gossip
    stop                Stop compaction
    version             Print cassandra version

See 'nodetool help <command>' for more information on a specific command.
```

**Comment by penberg** [comment]
@syuu1228, @slivne ping

**Comment by syuu1228** [comment]
@penberg We can add, but I don't understand why other environments does not causes this error, we don't have logback-tools.xml both on .rpm / .deb.
Even my Ubuntu VM with 1.0-rc2 does not causes the error.
I'll check what's happening in docker instance..

**Comment by syuu1228** [comment]
I still don't find a root of the problem because upstream's script is complicated, but it seems it only happens following condition:
- You are in /
- You have logback.xml on current directory

And it happens both on Docker Ubuntu instance and normal Ubuntu, likely scylla-tools implementation problem not related to Docker image.

I guess /etc/scylla/cassandra/logback.xml is loaded correctly only when we see the error message.
It just too verbose since log level is INFO, and also fails to write log file because "${cassandra.logdir}" is not exists (see "ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE]").
And when we don't see the error, probably logging is disabled.

**Comment by slivne** [comment]
permissions is the issue you are running the tool in a directory you do not
have write permissions

**Comment by syuu1228** [comment]
Now I understand. As @slivne says it is permission error, logback always tries to write log file to ./cassandra.logdir_IS_UNDEFINED/system.log, and when PWD=/ you don't have a permission to create the directory. So we need to fix path on ${cassandra.logdir}

**Comment by penberg** [comment]
@syuu1228 @slivne The root cause of the error is that we don't include the right logback configuration file for ``nodetool`` to pick up. The permission error is a secondary failure.

**Comment by slivne** [comment]
I think we do have the logback config file included in the packaging of
sctlla-tools

https://github.com/scylladb/scylla-tools-java/blob/master/dist/redhat/scylla-tools.spec.in#L37
