### ISSUE TITLE
nodetool gossipinfo: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1164]
When adding gms::application_state::SUPPORTED_FEATURES to the cluster, I got the following error. We need to modify nodetool to allow more gossip application_state.

```
$ nodetool gossipinfo                                                                    
error: 24
-- StackTrace --
java.lang.ArrayIndexOutOfBoundsException: 24
        at org.apache.cassandra.gms.EndpointState.addApplicationState(EndpointState.java:76)
        at org.apache.cassandra.gms.FailureDetector.getEndpointStateMap(FailureDetector.java:113)
        at org.apache.cassandra.gms.FailureDetector.getAllEndpointStates(FailureDetector.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
        at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
```

**Comment by amnonh** [comment]
Cassandra implementation uses a close set of enum, you should probably use one of the Xs that they added for future expensions.

Alternatively we can add states to ApplicationState.java

**Comment by asias** [comment]
if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but still the name
is still incorrect in the output.

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but the name
is still incorrect in the output (X1:FEATURE1,FEATURE2).

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but the name
is still incorrect in the output (X1:FEATURE1,FEATURE2).

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but the name
is still incorrect in the output (X1:FEATURE1,FEATURE2).

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but the name
is still incorrect in the output (X1:FEATURE1,FEATURE2).

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but the name
is still incorrect in the output (X1:FEATURE1,FEATURE2).

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but the name
is still incorrect in the output (X1:FEATURE1,FEATURE2).

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but the name
is still incorrect in the output (X1:FEATURE1,FEATURE2).

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

**Comment by asias** [comment]
Yes, if I use X1 for SUPPORTED_FEATURES, nodetool survived, but the name
is still incorrect in the output (X1:FEATURE1,FEATURE2).

```
$ nodetool gossipinfo

/127.0.0.1
  generation:1459844451
  heartbeat:55
  RELEASE_VERSION:2.1.8
  INTERNAL_IP:127.0.0.1
  X1:FEATURE1,FEATURE2
  RACK:rack1
  STATUS:NORMAL,978250183477372971
  LOAD:56204
  NET_VERSION:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  DC:dc1
  RPC_ADDRESS:127.0.0.1
  HOST_ID:3fad3104-5552-4959-9f3e-baa604ec4bfb
```

On Tue, Apr 5, 2016 at 3:48 PM, Amnon Heiman <notifications@github.com>
wrote:

> Cassandra implementation uses a close set of enum, you should probably use
> one of the Xs that they added for future expensions.
>
> Alternatively we can add states to ApplicationState.java
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/1164#issuecomment-205706232>
>



-- 
Asias
