### ISSUE TITLE
scylla_io_setup ignores data_file_directories

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1167]
## Installation details
Scylla version (or git commit hash): 1.0-rc2

scylla_io_setup unconditionally tests /var/lib/scylla, but the user may have configured a different directory.

**Comment by tzach** [comment]
@syuu1228 any updates?

**Comment by eyalgutkind** [comment]
Can scylla_io_setup read /etc/scylla/scylla.yaml and acquire/test the data and commitlog directories from the yaml file?
This way it will target the working directories to test.

**Comment by syuu1228** [comment]
sent v2 for this issue.

**Comment by dyasny** [comment]
I just installed Scylla 3.0.5 on CentOS7, and ran into this issue. 

`/sbin/scylla_io_setup` had /var/lib/scylla hardcoded (link: https://github.com/scylladb/scylla/blob/b19792405faee91ed9410357dc41b7cda648690f/dist/common/scripts/scylla_io_setup#L45)

Changing it to my datadir's mountpoint made scylla_io_setup and scylla_setup work.

**Comment by glommer** [comment]
That however only happens in AMI mode.
In AMI mode, I don't think we're supposed to expect those dirs somewhere else.
I am not opposed to a patch to make this more robust, but I don't see a real need either.

**Comment by dyasny** [comment]
This happened today on a Clean Centos7 install using the yum repo. No AMI

**Comment by dyasny** [comment]
```[root@ip-10-0-0-79 ~]# scylla_setup 
Skip any of the following steps by answering 'no'
Do you want to run Amazon EC2 configuration check?
Yes - runs a script to verify that this instance is optimized for running Scylla. No - skips the configuration check.
[YES/no]no
Do you want to run check your kernel version?
Yes - runs a  script to verify that the kernel for this instance qualifies to run Scylla. No - skips the kernel check.
[YES/no]
INFO  2019-04-24 15:54:15,797 [shard 0] iotune - /var/tmp/mnt passed sanity checks
This is a supported kernel version.
Do you want to verify the ScyllaDB packages are installed?
Yes - runs a script to confirm that ScyllaDB is installed. No - skips the installation check.
[YES/no]
Do you want the Scylla server service to automatically start when the Scylla node boots?
Yes - Scylla server service automatically starts on Scylla node boot. No - skips this step. Note you will have to start the Scylla Server service manually.
[YES/no]
Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /usr/lib/systemd/system/scylla-server.service.
Do you want to disable SELinux?
Yes - disables SELinux. Choosing Yes greatly improves performance. No - keeps SELinux activated.
[YES/no]
Do you want to setup Network Time Protocol(NTP) to auto-synchronize the current time on the node?
Yes - enables time-synchronization. This keeps the correct time on the node. No - skips this step.
[YES/no]
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repos-va.psychz.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: repos-va.psychz.net
 * updates: repos-va.psychz.net
Resolving Dependencies
--> Running transaction check
---> Package ntp.x86_64 0:4.2.6p5-28.el7.centos will be installed
--> Processing Dependency: libopts.so.25()(64bit) for package: ntp-4.2.6p5-28.el7.centos.x86_64
---> Package ntpdate.x86_64 0:4.2.6p5-28.el7.centos will be installed
--> Running transaction check
---> Package autogen-libopts.x86_64 0:5.18-5.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================
 Package                  Arch            Version                         Repository     Size
==============================================================================================
Installing:
 ntp                      x86_64          4.2.6p5-28.el7.centos           base          549 k
 ntpdate                  x86_64          4.2.6p5-28.el7.centos           base           86 k
Installing for dependencies:
 autogen-libopts          x86_64          5.18-5.el7                      base           66 k

Transaction Summary
==============================================================================================
Install  2 Packages (+1 Dependent package)

Total download size: 701 k
Installed size: 1.6 M
Downloading packages:
(1/3): autogen-libopts-5.18-5.el7.x86_64.rpm                           |  66 kB  00:00:00     
(2/3): ntpdate-4.2.6p5-28.el7.centos.x86_64.rpm                        |  86 kB  00:00:00     
(3/3): ntp-4.2.6p5-28.el7.centos.x86_64.rpm                            | 549 kB  00:00:00     
----------------------------------------------------------------------------------------------
Total                                                         3.8 MB/s | 701 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : autogen-libopts-5.18-5.el7.x86_64                                          1/3 
  Installing : ntpdate-4.2.6p5-28.el7.centos.x86_64                                       2/3 
  Installing : ntp-4.2.6p5-28.el7.centos.x86_64                                           3/3 
  Verifying  : ntpdate-4.2.6p5-28.el7.centos.x86_64                                       1/3 
  Verifying  : autogen-libopts-5.18-5.el7.x86_64                                          2/3 
  Verifying  : ntp-4.2.6p5-28.el7.centos.x86_64                                           3/3 

Installed:
  ntp.x86_64 0:4.2.6p5-28.el7.centos          ntpdate.x86_64 0:4.2.6p5-28.el7.centos         

Dependency Installed:
  autogen-libopts.x86_64 0:5.18-5.el7                                                         

Complete!
24 Apr 15:54:47 ntpdate[26807]: adjust time server 216.218.254.202 offset -0.000563 sec
Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
Do you want to setup RAID0 and XFS?
It is recommended to use RAID0 and XFS for Scylla data. If you select yes, you will be prompted to choose the unmounted disks to use for Scylla data. Selected disks are formatted as part of the process.
Yes - choose a disk/disks to format and setup for RAID0 and XFS. No - skip this step.
[YES/no]
Are you sure you want to setup RAID0 and XFS?
If you choose Yes, the selected drive will be reformated, erasing all existing data in the process.
[YES/no]
Please select unmounted disks from the following list: ['/dev/nvme1n1']
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: []
> /dev/nvme1n1
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: ['/dev/nvme1n1']
> done
Creating XFS volume for scylla using 1 disk(s): /dev/nvme1n1
meta-data=/dev/nvme1n1           isize=512    agcount=4, agsize=6553600 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=0, sparse=0
data     =                       bsize=4096   blocks=26214400, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=12800, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
Do you want to enable coredumps?
Yes - sets up coredump to allow a post-mortem analysis of the Scylla state just prior to a crash. No - skips this step.
[YES/no]
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e"
Do you want to setup a system-wide customized configuration for Scylla?
Yes - setup the sysconfig file. No - skips this step.
[YES/no]
Do you want to enable Network Interface Card (NIC) and disk(s) optimization?
Yes - optimize the NIC queue and disks settings. Selecting Yes greatly improves performance. No - skip this step.
[YES/no]
ERROR: 'disks' tuning was requested but no disks were found. Your system can't be tuned until the issue is fixed.
Traceback (most recent call last):
  File "/usr/lib/scylla/scylla_sysconfig_setup", line 75, in <module>
    rps_cpus = out('{} --tune net --nic {} --get-cpu-mask'.format(perftune_base_command(), ifname))
  File "/usr/lib/scylla/scylla_util.py", line 280, in out
    return subprocess.check_output(cmd, shell=shell).strip().decode('utf-8')
  File "/usr/lib64/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/scylla/perftune.py', '--tune', 'disks', '--dir', '/mnt/scylla/data', '--dir', '/mnt/scylla/commitlog', '--tune', 'net', '--nic', 'ens5', '--get-cpu-mask']' returned non-zero exit status 1.
NIC queue setup failed. Press any key to continue...

Do you want iotune to study your disks IO profile and adapt Scylla to it?
Yes - let iotune study my disk(s). Note that this action will take a few minutes. No - skip this step.
[YES/no]
ERROR:root:/mnt/scylla/data is not found. please check the configuration and run scylla_io_setup again.

IO configuration setup failed. Press any key to continue...

Do you want to install node exporter to export Prometheus data from the node? Note that the Scylla monitoring stack uses this data
Yes - install node exporter. No - skip this  step.
[YES/no]
Created symlink from /etc/systemd/system/multi-user.target.wants/node-exporter.service to /usr/lib/systemd/system/node-exporter.service.
node_exporter successfully installed
Do you want to set the CPU scaling governor to Performance level on boot?
Yes - sets the CPU scaling governor to performance level. No - skip this step.
[YES/no]
This computer doesn't supported CPU scaling configuration.
Do you want to enable fstrim service?
Yes - runs fstrim on your SSD. No - skip this step.
[YES/no]
ScyllaDB setup finished.
```

**Comment by glommer** [comment]
That is, then, unrelated to the line you singled out. That line is only relevant in ami mode.

**Comment by avikivity** [comment]
Backport candidate label applied by mistake, removing.
