### ISSUE TITLE
SIGSEGV when systemctl stop scylla-server

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#118]
systemctl stop scylla-server causes SIGSEGV.
This is 100% reproducible, also happen with "killall scylla".
According to backtrace, it seems memory manager referencing bad pointer when freeing memory.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  deallocate (object=0x6000000beef0, this=<optimized out>)
    at core/memory.cc:731
731	    o->next = _free;
Missing separate debuginfos, use: dnf debuginfo-install boost-filesystem-1.57.0-6.fc22.x86_64 boost-program-options-1.57.0-6.fc22.x86_64 boost-system-1.57.0-6.fc22.x86_64 boost-test-1.57.0-6.fc22.x86_64 boost-thread-1.57.0-6.fc22.x86_64 bzip2-libs-1.0.6-14.fc22.x86_64 cryptopp-5.6.2-9.fc22.x86_64 elfutils-libelf-0.163-1.fc22.x86_64 elfutils-libs-0.163-1.fc22.x86_64 glibc-2.21-7.fc22.x86_64 hwloc-libs-1.10.1-2.fc22.x86_64 jsoncpp-0.6.0-0.14.rc2.fc22.x86_64 keyutils-libs-1.5.9-4.fc22.x86_64 krb5-libs-1.13.2-5.fc22.x86_64 libaio-0.3.110-4.fc22.x86_64 libattr-2.4.47-9.fc22.x86_64 libcap-2.24-7.fc22.x86_64 libcom_err-1.42.12-4.fc22.x86_64 libgcc-5.1.1-4.fc22.x86_64 libgcrypt-1.6.3-4.fc22.x86_64 libgpg-error-1.17-2.fc22.x86_64 libpciaccess-0.13.3-0.3.fc22.x86_64 libselinux-2.3-10.fc22.x86_64 libstdc++-5.1.1-4.fc22.x86_64 libtool-ltdl-2.4.2-34.fc22.x86_64 libxml2-2.9.2-3.fc22.x86_64 lz4-r131-1.fc22.x86_64 numactl-libs-2.0.10-2.fc22.x86_64 openssl-libs-1.0.1k-11.fc22.x86_64 pcre-8.37-2.fc22.x86_64 snappy-1.1.1-3.fc22.x86_64 systemd-libs-219-19.fc22.x86_64 thrift-0.9.1-13.fc22.3.x86_64 xen-libs-4.5.1-2.fc22.x86_64 xz-libs-5.2.0-2.fc22.x86_64 yaml-cpp-0.5.1-6.fc22.x86_64 zlib-1.2.8-7.fc22.x86_64
(gdb) bt
#0  deallocate (object=0x6000000beef0, this=<optimized out>)
    at core/memory.cc:731
#1  memory::cpu_pages::free (this=0x7ff8c2935980, ptr=0x6000000beef0, 
    size=<optimized out>) at core/memory.cc:518
#2  0x0000000000c7ad9d in operator() (__closure=<optimized out>)
    at /usr/src/debug/scylla-server-0.00/seastar/core/sharded.hh:316
#3  apply (args=<optimized out>, func=<optimized out>)
    at /usr/src/debug/scylla-server-0.00/seastar/core/apply.hh:34
#4  apply<seastar::sharded<Service>::stop()::<lambda(Service*&)> mutable::<lambda()> mutable [with Service = streaming::stream_session::handler]::<lambda()> >
    (args=<optimized out>, func=<optimized out>)
    at /usr/src/debug/scylla-server-0.00/seastar/core/apply.hh:42
#5  apply<seastar::sharded<Service>::stop()::<lambda(Service*&)> mutable::<lambda()> mutable [with Service = streaming::stream_session::handler]::<lambda()> >
    (args=<optimized out>, func=<optimized out>)
    at /usr/src/debug/scylla-server-0.00/seastar/core/future.hh:972
#6  then<void, seastar::sharded<Service>::stop()::<lambda(Service*&)> mutable::<lambda()> mutable [with Service = streaming::stream_session::handler]::<lambda()>, future<T>::then(Func&&) [with Func = seastar::sharded<Service>::stop()::<lambda(Service*&)> mutable::<lambda()> mutable [with Service = streaming::stream_session::handler]::<lambda()>; Result = future<>; T = {}]::<lambda(future_state<>&&)> > (param=<optimized out>, func=<optimized out>, this=0x7ffc65a09f60)
    at /usr/src/debug/scylla-server-0.00/seastar/core/future.hh:625
---Type <return> to continue, or q <return> to quit---
#7  then<seastar::sharded<Service>::stop()::<lambda(Service*&)> mutable::<lambda()> mutable [with Service = streaming::stream_session::handler]::<lambda()>, future<> > (func=<optimized out>, this=0x7ffc65a09f60)
    at /usr/src/debug/scylla-server-0.00/seastar/core/future.hh:758
#8  operator() (__closure=0x6000000bedb0)
    at /usr/src/debug/scylla-server-0.00/seastar/core/sharded.hh:317
#9  apply<seastar::sharded<Service>::stop()::<lambda(Service*&)> mutable [with Service = streaming::stream_session::handler]::<lambda()>&> (func=...)
    at /usr/src/debug/scylla-server-0.00/seastar/core/future.hh:1003
#10 submit_to<seastar::sharded<Service>::stop()::<lambda(Service*&)> mutable [with Service = streaming::stream_session::handler]::<lambda()> > (
    func=<optimized out>, t=<optimized out>)
    at /usr/src/debug/scylla-server-0.00/seastar/core/reactor.hh:972
#11 operator() (inst=<optimized out>, __closure=<optimized out>)
    at /usr/src/debug/scylla-server-0.00/seastar/core/sharded.hh:319
#12 operator() (state=..., __closure=<optimized out>)
    at /usr/src/debug/scylla-server-0.00/seastar/core/future-util.hh:88
#13 do_with<parallel_for_each_state, parallel_for_each(Iterator, Iterator, Func&&) [with Iterator = __gnu_cxx::__normal_iterator<streaming::stream_session::handler**, std::vector<streaming::stream_session::handler*, std::allocator<streaming::stream_session::handler*> > >; Func = seastar::sharded<Service>::stop() [with Service = streaming::stream_session::handler]::<lambda(streaming::stream_session::handler*&)>]::<lambda(parallel_for_each_state&)> > (f=<optimized out>, 
---Type <return> to continue, or q <return> to quit---
    rvalue=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x6068f1b, DIE 0x6292354>) at /usr/src/debug/scylla-server-0.00/seastar/core/do_with.hh:55
#14 parallel_for_each<__gnu_cxx::__normal_iterator<streaming::stream_session::handler**, std::vector<streaming::stream_session::handler*, std::allocator<streaming::stream_session::handler*> > >, seastar::sharded<Service>::stop() [with Service = streaming::stream_session::handler]::<lambda(streaming::stream_session::handler*&)> > (func=<optimized out>, end=..., begin=...)
    at /usr/src/debug/scylla-server-0.00/seastar/core/future-util.hh:103
#15 seastar::sharded<streaming::stream_session::handler>::stop (
    this=this@entry=0x1583f00 <streaming::stream_session::_handlers>)
    at /usr/src/debug/scylla-server-0.00/seastar/core/sharded.hh:322
#16 0x0000000000c65873 in operator() (__closure=<optimized out>)
    at streaming/stream_session.cc:178
#17 std::_Function_handler<future<>(), streaming::stream_session::init_streaming_service(distributed<database>&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/5.1.1/functional:1857
#18 0x0000000000452061 in do_for_each<std::reverse_iterator<__gnu_cxx::__normal_iterator<std::function<future<>()>*, std::vector<std::function<future<>()> > > >, reactor::run_exit_tasks()::<lambda(auto:20&)> >(std::reverse_iterator<__gnu_cxx::__normal_iterator<std::function<future<>()>*, std::vector<std::function<future<>()>, std::allocator<std::function<future<>()> > > > >, std::reverse_iterator<__gnu_cxx::__normal_iterator<std::function<future<>()>*, std::vector<std::function<future<>()>, std::allocator<std::function<future<>()> > > > >, <unknown type ---Type <return> to continue, or q <return> to quit---
in /usr/lib/debug/usr/bin/scylla.debug, CU 0x4a54b1, DIE 0x5b5cc3>) (
    begin=..., end=..., action=<optimized out>)
    at /usr/include/c++/5.1.1/functional:2271
#19 0x00000000004526e3 in continuation<future<T>::then(Func&&, Param&&) [with Ret = future<>; Func = do_for_each(Iterator, Iterator, AsyncAction&&) [with Iterator = std::reverse_iterator<__gnu_cxx::__normal_iterator<std::function<future<>()>*, std::vector<std::function<future<>()> > > >; AsyncAction = reactor::run_exit_tasks()::<lambda(auto:20&)>]::<lambda()>; Param = future<T>::then(Func&&) [with Func = do_for_each(Iterator, Iterator, AsyncAction&&) [with Iterator = std::reverse_iterator<__gnu_cxx::__normal_iterator<std::function<future<>()>*, std::vector<std::function<future<>()> > > >; AsyncAction = reactor::run_exit_tasks()::<lambda(auto:20&)>]::<lambda()>; Result = future<>; T = {}]::<lambda(future_state<>&&)>; T = {}; futurize_t<Ret> = future<>]::<lambda(auto:1&&)> >::run(void) (
    this=0x600000033e70) at core/future-util.hh:279
#20 0x000000000044153a in reactor::run_tasks (this=this@entry=0x6000001eb000, 
    tasks=..., quota=<optimized out>) at core/reactor.cc:1054
#21 0x0000000000468af2 in reactor::run (this=0x6000001eb000)
    at core/reactor.cc:1151
#22 0x00000000004b7396 in app_template::run(int, char**, std::function<void ()>&&) (this=this@entry=0x7ffc65a0a970, ac=ac@entry=5, av=av@entry=0x7ffc65a0abb8, 
    func=func@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x52fd8, DIE 0x53984>) at core/app-template.cc:104
#23 0x00000000004180d3 in main (ac=5, av=0x7ffc65a0abb8) at main.cc:208
```

**Comment by slivne** [comment]
@syuu1228 is this reproducible on latest head ?

**Comment by syuu1228** [comment]
This is fixed.
