### ISSUE TITLE
TestUpdateClusterLayout.simple_kill_new_node_while_bootstrapping_with_parallel_writes_test fails with "--smp 2"

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#1201]
## Installation details
Scylla version (or git commit hash): 45527fcffa6cf7aee80da3e37d3713ff3ce5f72f
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora

## Problem

The test case passes with "--smp 1":

```
$ export SCYLLA_EXT_OPTS="--smp 1 --memory 1G"
$ nosetests -v update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_kill_new_node_while_bootstrapping_with_parallel_writes_test
----------------------------------------------------------------------
Ran 1 test in 119.452s

OK
```

but fails with "--smp 2":

```
$ export SCYLLA_EXT_OPTS="--smp 2 --memory 1G"
$ nosetests -v update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_kill_new_node_while_bootstrapping_with_parallel_writes_test

======================================================================
ERROR: simple_kill_new_node_while_bootstrapping_with_parallel_writes_test (update_cluster_layout_tests.TestUpdateClusterLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/penberg/scylla-dtest/update_cluster_layout_tests.py", line 441, in simple_kill_new_node_while_bootstrapping_with_parallel_writes_test
    session.execute("SELECT * FROM cf")
  File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:26565)
    result = future.result()
  File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:62845)
    raise self._final_exception
Unavailable: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl ONE. Requires 1, alive 0" info={'required_replicas': 1, 'alive_replicas': 0, 'consistency': 'ONE'}
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/penberg/.dtest/dtest-MqrKbV
dtest: DEBUG: Inserting more data to make streaming process longer...
dtest: DEBUG: Start Node 4
dtest: DEBUG: start write
dtest: DEBUG: Stop Node 4
dtest: DEBUG: exception thrown WriteTimeout code=1100 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out - received only 1 responses." info={'received_responses': 1, 'required_responses': 2, 'consistency': 'ONE'}
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
dtest: DEBUG: Retrying read after timeout. Attempt #0
dtest: DEBUG: Retrying request after UE. Attempt #1
dtest: DEBUG: Retrying request after UE. Attempt #2
dtest: DEBUG: Retrying request after UE. Attempt #3
dtest: DEBUG: Retrying request after UE. Attempt #4
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 133.617s

FAILED (errors=1)
```

**Comment by penberg** [comment]
Ping @asias @gleb-cloudius

**Comment by asias** [comment]
@penberg I can not reproduce it with latest scylla master (e7f438eeae860531396979e687daf0a06ee0399e) + dtest master (e6aa4240cb69f25b6c5115e2510a08a33bd0bfed)with --smp 2. 

20 out of 20 runs passed here.

**Comment by penberg** [comment]
Right. I suspect this Seastar commit fixes the issue: https://github.com/scylladb/seastar/commit/15a92cfe7aa43748c9afb88878bbe7eeac5e229c

Let's see what Jenkins has to say about it before we close this.

**Comment by penberg** [comment]
Jenkins agrees. Closing!
