### ISSUE TITLE
Cannot decommission node.

### ISSUE THREAD

**Issue by Freeaqingme** [scylladb/scylla#1242]
## Installation details
Scylla version (or git commit hash): 666.development-20160504.f1cd52f-ubuntu1
Cluster size: 4, or 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): Linux node2 4.4.0-21-generic #37~14.04.1-Ubuntu SMP Wed Apr 20 16:33:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I've got a node on which everything is okay:
```
# nodetool status
Datacenter: Yes
================================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address          Load       Tokens  Owns    Host ID                               Rack
UN  149.X.Y.136  508.03 MB  256     ?       ea82c60b-5ef7-43ca-b8e8-a5dae6b90fea  16
UL  149.X.Y.117  325.97 MB  256     ?       2e5de3ab-f773-4f3b-844f-359a0931857a  16
UN  149.X.Y.115  742.98 MB  256     ?       5698433b-7af7-4b3d-be21-dc299781d2d8  16
UN  149.X.Y.132  568.31 MB  256     ?       e4f5762d-ac35-4158-b7cb-50d8e7400832  16
UN  149.X.Y.135  569.18 MB  256     ?       baee8572-d933-4878-a905-3cc788faee88  16

# ip a s | grep inet
    inet 149.X.Y.132/24
```

Then I've got another node which I was restarting while I was performing some other node operations. Current state:
```
nodetool status
Datacenter: Yes
================================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address          Load       Tokens  Owns    Host ID                               Rack
UN  149.X.Y.136  508.03 MB  256     ?       ea82c60b-5ef7-43ca-b8e8-a5dae6b90fea  16
UL  149.X.Y.117  325.97 MB  256     ?       2e5de3ab-f773-4f3b-844f-359a0931857a  16
UN  149.X.Y.115  742.98 MB  256     ?       5698433b-7af7-4b3d-be21-dc299781d2d8  16
DN  149.X.Y.130  ?          256     ?       d557c3be-bb0a-4e05-a545-515a53791bc0  16
UN  149.X.Y.132  568.31 MB  256     ?       e4f5762d-ac35-4158-b7cb-50d8e7400832  16
UN  149.X.Y.135  569.18 MB  256     ?       baee8572-d933-4878-a905-3cc788faee88  16
```

Because my data is not yet stored redundantly (#1241), I'm trying to properly decommission it (node 149.X.Y.117). When I run '''nodetool decommission''' the command takes several minutes, while not exchanging any data (according to 'iftop'). Finally it ends:
```
sudo nodetool decommission
nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: stream_ranges failed
See 'nodetool help' or 'nodetool help <command>'.
```

Meanwhile the logs show:
```
May  9 00:30:46 node2.nl scylla[5045]:  [shard 0] rpc - client 149.X.Y.130: fail to connect: Connection refused
May  9 00:30:52 node2.nl scylla[5045]:  [shard 0] rpc - client 149.X.Y.130: fail to connect: Connection refused
May  9 00:30:55 node2.nl scylla[5045]:  [shard 0] messaging_service - Retry verb=15 to 149.X.Y.130:0, retry=10: rpc::closed_error (connection is closed)
May  9 00:30:55 node2.nl scylla[5045]:  [shard 0] stream_session - [Stream #220648e0-156b-11e6-be5f-000000000000] The session 0x600000a38600 is idle for 600 seconds, the peer 149.X.Y.130 is probably gone, close it
May  9 00:30:55 node2.nl scylla[5045]:  [shard 0] stream_session - [Stream #220648e0-156b-11e6-be5f-000000000000] Streaming error occurred
May  9 00:30:55 node2.nl scylla[5045]:  [shard 0] stream_session - [Stream #220648e0-156b-11e6-be5f-000000000000] Session with 149.X.Y.130 is complete, state=FAILED
May  9 00:30:55 node2.nl scylla[5045]:  [shard 0] stream_session - [Stream #220648e0-156b-11e6-be5f-000000000000] bytes_sent = 1118653692, bytes_received = 0
May  9 00:30:55 node2.nl scylla[5045]:  [shard 0] stream_session - [Stream #220648e0-156b-11e6-be5f-000000000000] Stream failed, peers={149.X.Y.115, 149.X.Y.130, 149.X.Y.132, 149.X.Y.135, 149.X.Y.136}
May  9 00:30:55 node2.nl scylla[5045]:  [shard 0] storage_service - stream_ranges failed: streaming::stream_exception (Stream failed)
May  9 00:30:55 node2.nl scylla[5045]:  [shard 0] storage_service - unbootstrap fails to stream : std::runtime_error (stream_ranges failed)
May  9 00:30:57 node2.nl scylla[5045]:  [shard 0] rpc - client 149.X.Y.130: fail to connect: Connection refused
May  9 00:30:58 node2.nl scylla[5045]:  [shard 0] rpc - client 149.X.Y.130: fail to connect: Connection refused
May  9 00:31:12 node2.nl scylla[5045]:  [shard 0] rpc - client 149.X.Y.130: fail to connect: Connection refused
```

I figured I might need to manually remove that .130 node first, but I consistently get this:
```
nodetool removenode 149.X.Y.130
nodetool: Scylla API server H210.149TTP POST to URL '/storage_service/remove_node' failed: marshalling error
See 'nodetool help' or 'nodetool help <command>'.
```

**Comment by penberg** [comment]
Ping @asias

**Comment by asias** [comment]
I noticed the nightly version is used (666.development-20160504.f1cd52f-ubuntu1). The commit f1cd52f includes dc69999 (rpc: introduce outgoing packet queue #1236 ) which might probably break decommission. 

@Freeaqingme why is node 149.X.Y.130 not shown in the first nodetool status output. What happened to 149.X.Y.130, it is in DOWN state?

"Then I've got another node which I was restarting while I was performing some other node operations."

Can you explain what did you do exactly? Did you add another node while you are decommissioning a node? What node is restarted and what is "other node operations"?

**Comment by Freeaqingme** [comment]
@asias I'm indeed using a nightly version. This was because of #1231, where I couldn't add a new node.

I'm not entirely sure about the order of events, everything appeared to go smoothly and I was just playing around. As such, I did not keep meticulous logs of what I did, until I realized an hour later that my changes might not have been as trivial as they initially appeared.

However, it comes down to something like:
```
# I began with a 7 node cluster, all nodes were UN.
db0 (.132) # nodetool removenode <host id node1 (.116) >
node1 (.130) # nodetool decommission
db0 (.132) # nodetool removenode 2e5de3ab-f773-4f3b-844f-359a0931857a (node2 .117)
db0 (.132) # nodetool removenode 2e5de3ab-f773-4f3b-844f-359a0931857a (node2 .117)
node2 (.117) # nodetool decommission^C
node2 (.117) # reboot
node2 (.117) # nodetool decommission
```

I did not add any new nodes.

**Comment by asias** [comment]
decommission and removenode is a heavy operation, it involves a lot of data being streamed between nodes. When a node is alive, use decommission to remove a node from the cluster, and it is the recommended way. Only when a node is down and can not be started, as a last resort, use removenode to remove it.

It is complex to cancel and undo a removenode or decommission operations, both scylla and cassandra do not support, so wait for it to complete instead of trying ctrl-c to abort the operation, and there operations one by one. 

@amnonh Do you have any idea why we get "marshalling error" here?
'''
nodetool removenode 149.X.Y.130
nodetool: Scylla API server H210.149TTP POST to URL '/storage_service/remove_node' failed: marshalling error
See 'nodetool help' or 'nodetool help <command>'.
'''

**Comment by amnonh** [comment]
It's hard to tell, my guess is that the UUID constructor throws the exception.
You put the ip address instead of the id

**Comment by slivne** [comment]
@asias I think amnon is correct

I had a 2 node cluster

```
shlomi@localhost~/urchin-ccm (branch-1.2)$ ccm node1 nodetool status

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns (effective)  Host ID                               Rack
UN  127.0.0.1  230.01 KB  256     100.0%            428bf84c-b4a2-4982-a667-219c370431bc  rack1
UN  127.0.0.2  220.7 KB   256     100.0%            19775a80-fbd7-4bbb-b911-fc436428a9f7  rack1

```

I then did the following

```
shlomi@localhost~/urchin-ccm (branch-1.2)$ ccm node2 stop
shlomi@localhost~/urchin-ccm (branch-1.2)$ ccm node1 nodetool removenode 127.0.0.1
Traceback (most recent call last):
  File "/home/shlomi/urchin-ccm/ccm", line 74, in <module>
    cmd.run()
  File "/home/shlomi/urchin-ccm/ccmlib/cmds/node_cmds.py", line 262, in run
    stdout, stderr = self.node.nodetool(" ".join(self.args[1:]))
  File "/home/shlomi/urchin-ccm/ccmlib/node.py", line 693, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/home/shlomi/scylla/resources/cassandra/bin/nodetool -h localhost -p 7100 removenode 127.0.0.1' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/remove_node' failed: marshalling error
See 'nodetool help' or 'nodetool help <command>'.
```
which reproduces the issue

I then did 
```
shlomi@localhost~/urchin-ccm (branch-1.2)$ ccm node1 nodetool removenode 19775a80-fbd7-4bbb-b911-fc436428a9f7
shlomi@localhost~/urchin-ccm (branch-1.2)$ ccm node1 nodetool status

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns (effective)  Host ID                               Rack
UN  127.0.0.1  207.58 KB  256     100.0%            428bf84c-b4a2-4982-a667-219c370431bc  rack1


```

which worked

is there anything left todo with this issue - can we close it ?

```

**Comment by tzach** [comment]
@slivne , as decommission do works, suggest to close this issue. 

@amnonh if the error is coming from Scylla, please open an issue for a clearer error response, like "Error in parsing API parameters"

**Comment by amnonh** [comment]
I have opened #1526

**Comment by tzach** [comment]
closing this issue as decommission do work.
The error message should be improved #1526
