### ISSUE TITLE
Can't connect to scylla housekeeper

### ISSUE THREAD

**Issue by lapisz1** [scylladb/scylla#12822]
Everything works fine except I got an error when I deployed scylladb 5.X.Y.
Scylladb version: 5.1.3 
Instance family: r6g (ARM64)
Image: Amazon linux 2
Volume: ebs
Deployment: kubernetes statefulset
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
BTW scylladb version 4.6.11 doesn't appear this error message and housekeeper is working properly.

**Comment by fruch** [comment]
@lapisz1 can you supply a bit more full log of the problematic pod in question ?

also is something else isn't working ? beside this backtrace print ? i.e. the housekeeping failure shouldn't be blocking anything.

also are you using scylla-operator here ?

**Comment by mykaul** [comment]
I'm surprised it tries with HTTP, but I'm not sure if it's even related. @amnonh - thoughts?

**Comment by amnonh** [comment]
I just did a test with https and saw that I got a correct reply, maybe it's
a network issue?
