### ISSUE TITLE
fail to run Scylla AMI 1.2 cluster on EC2

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1381]
* Scylla version (or git commit hash): 1.2
* Cluster size: 3
* OS (RHEL/CentOS/Ubuntu/AWS AMI): scylla 1.2 (ami-31b97c51) Oregon,  i2.xlarge

I see 3 issues in the log below:
* Reflector does not response (maybe its is down?)
* wallawalla ftp issue at the start
* should AMI skeep the RAID0 step when there is only one disk?

Look like the first is the problem

```
$ journalctl | grep -i scylla
Jun 23 07:31:11 ip-172-30-0-52.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.service:12] Not an absolute path, ignoring: $SCYLLA_HOME
Jun 23 07:31:31 ip-172-30-0-52.ec2.internal systemd[1]: Starting Scylla AMI Setup...
Jun 23 07:31:31 ip-172-30-0-52.ec2.internal scylla_ami_setup[746]: RAID does not constructed, going to initialize...
Jun 23 07:31:31 ip-172-30-0-52.ec2.internal scylla_ami_setup[746]: Found disk /dev/xvdb
Jun 23 07:31:31 ip-172-30-0-52.ec2.internal scylla_ami_setup[746]: Creating RAID0 for scylla using 1 disk(s): /dev/xvdb
Jun 23 07:31:39 ip-172-31-34-249 scylla_ami_setup[746]: Loaded plugins: fastestmirror, langpacks
Jun 23 07:31:51 ip-172-31-34-249 scylla_ami_setup[746]: ftp://ftp.wallawalla.edu/pub/mirrors/centos/7.2.1511/updates/x86_64/repodata/2b463e49fd055957a49de31ef98c1e1c5668d2fe79eed7685c634d614dab9258-primary.sqlite.bz2: [Errno 12] Timeout on ftp://ftp.wallawalla.edu/pub/mirrors/centos/7.2.1511/updates/x86_64/repodata/2b463e49fd055957a49de31ef98c1e1c5668d2fe79eed7685c634d614dab9258-primary.sqlite.bz2: (28, '')
Jun 23 07:31:51 ip-172-31-34-249 scylla_ami_setup[746]: Trying other mirror.
Jun 23 07:31:54 ip-172-31-34-249 scylla_ami_setup[746]: Loading mirror speeds from cached hostfile
Jun 23 07:31:55 ip-172-31-34-249 scylla_ami_setup[746]: * base: mirror.unl.edu
Jun 23 07:31:55 ip-172-31-34-249 scylla_ami_setup[746]: * epel: mirror.cs.pitt.edu
Jun 23 07:31:55 ip-172-31-34-249 scylla_ami_setup[746]: * extras: mirror.beyondhosting.net
Jun 23 07:31:55 ip-172-31-34-249 scylla_ami_setup[746]: * updates: mirror.cs.pitt.edu
Jun 23 07:32:13 ip-172-31-34-249 scylla_ami_setup[746]: Package mdadm-3.3.2-7.el7.x86_64 already installed and latest version
Jun 23 07:32:14 ip-172-31-34-249 scylla_ami_setup[746]: Package xfsprogs-3.2.2-2.el7.x86_64 already installed and latest version
Jun 23 07:32:14 ip-172-31-34-249 scylla_ami_setup[746]: Nothing to do
Jun 23 07:32:14 ip-172-31-34-249 scylla_ami_setup[746]: mdadm: Defaulting to version 1.2 metadata
Jun 23 07:32:14 ip-172-31-34-249 scylla_ami_setup[746]: mdadm: array /dev/md0 started.
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: meta-data=/dev/md0               isize=256    agcount=32, agsize=6103744 blks
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: =                       sectsz=4096  attr=2, projid32bit=1
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: =                       crc=0        finobt=0
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: data     =                       bsize=4096   blocks=195319808, imaxpct=25
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: =                       sunit=64     swidth=64 blks
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: naming   =version 2              bsize=4096   ascii-ci=0 ftype=0
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: log      =internal log           bsize=4096   blocks=95371, version=2
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: =                       sectsz=4096  sunit=1 blks, lazy-count=1
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: realtime =none                   extsz=4096   blocks=0, rtextents=0
Jun 23 07:32:16 ip-172-31-34-249 scylla_ami_setup[746]: Setting parameters on /etc/sysconfig/scylla-server
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: Waiting for cloud-init to finish...
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] Started with user data set to:
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] --clustername CassandraCluster --totalnodes 3 --version=community --release=2.1.8
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] Using user data:
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] --clustername CassandraCluster --totalnodes 3 --version=community --release=2.1.8
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] Using instance type: i2.xlarge
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] meta-data:instance-type: i2.xlarge
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] meta-data:local-ipv4: 172.31.34.249
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] meta-data:public-hostname: ec2-54-191-41-176.us-west-2.compute.amazonaws.com
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] meta-data:ami-launch-index: 1
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] meta-data:reservation-id: r-c0912504
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] Using cluster name: CassandraCluster
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] Using cluster size: 3
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] Using seed indexes: [0, 3, 3]
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] Reflector loop...
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] 06/23/16-07:32:28 Reflector: Received 0 of 1 responses from: []
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] 06/23/16-07:32:31 Reflector: Received 0 of 1 responses from: []
Jun 23 07:34:34 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] 06/23/16-07:32:33 Reflector: Received 0 of 1 responses from: []
```
....
```
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: [INFO] 06/23/16-07:42:25 Reflector: Received 0 of 1 responses from: []
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: [ERROR] EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: Aborting the clustering of this reservation. Please try again.
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: Traceback (most recent call last):
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 485, in <module>
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: get_seed_list()
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 312, in get_seed_list
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: exit_path('EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.', '\n\nAborting the clustering of this reservation. Please try again.')
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 55, in exit_path
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: raise AttributeError(errorMsg)
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: AttributeError: EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.
Jun 23 07:42:28 ip-172-31-34-249 scylla_ami_setup[746]: Aborting the clustering of this reservation. Please try again.
Jun 23 07:42:28 ip-172-31-34-249 systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
Jun 23 07:42:28 ip-172-31-34-249 systemd[1]: Failed to start Scylla AMI Setup.
Jun 23 07:42:28 ip-172-31-34-249 systemd[1]: Dependency failed for Scylla Server.
Jun 23 07:42:28 ip-172-31-34-249 systemd[1]: Dependency failed for Scylla JMX.
Jun 23 07:42:28 ip-172-31-34-249 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Jun 23 07:42:28 ip-172-31-34-249 systemd[1]: Job scylla-server.service/start failed with result 'dependency'.
Jun 23 07:42:28 ip-172-31-34-249 systemd[1]: Unit scylla-ami-setup.service entered failed state.
Jun 23 07:42:28 ip-172-31-34-249 systemd[1]: scylla-ami-setup.service failed.
```

**Comment by slivne** [comment]
I started a 3 node cluster on n virginia and it worked

scylla 1.2 (ami-928a4dff)

user data
```
--totalnodes 3
--clustername sl-12-3
```

```
[centos@ip-10-147-10-121 ~]$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  10.95.133.42   54.74 KB   256     ?       1f185c0b-a39d-4483-8ea8-c8f2a42bc50c  rack1
UN  10.167.96.48   50.2 KB    256     ?       7e36d9fd-4aa4-4123-ad81-f2cb20a45c11  rack1
UN  10.147.10.121  54.74 KB   256     ?       6a374006-42a0-4ec1-9bd7-382d0988d495  rack1

```

what is clear that reflector is working (at least in the n-virginia) and I did not get the issue with ftp

**Comment by slivne** [comment]
I did the same in oregon

scylla 1.2 (ami-31b97c51)

3 node cluster on i2.x

```
--totalnodes 3
--clustername sl-o-12-3
```

```
[centos@ip-172-31-9-197 ~]$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens  Owns    Host ID                               Rack
UN  172.31.9.199  16.85 KB   256     ?       a1c47a79-dcac-43fa-88ed-057647cb5a24  rack1
UN  172.31.9.198  ?          256     ?       2c220dd1-4ffc-4d98-873f-91457ea52f90  rack1
UN  172.31.9.197  33.37 KB   256     ?       9300ec15-2e4f-45f3-8d7f-a7ea503b71a7  rack1

```

maybe it was a temp networking issue in AWS

**Comment by tzach** [comment]
I can't reproduce it either. I will assume its an EC2 network glitch till proven otherwise.
