### ISSUE TITLE
bad_alloc during normal operation when refilling lsa reserve

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1394]
*Installation details*
Scylla version (or git commit hash): a439a6b8d3ff19523e7fc26c4b20051e3bb8c828

Everything is working normally, but exceptions are thrown internally and caught.  No effect on the user.

```
(gdb) bt
#0  0x00007f83eb903b3d in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x00000000007c3e4c in logalloc::segment_zone::segment_zone (this=0x60002273d180) at utils/logalloc.cc:434
#2  0x00000000007c963d in logalloc::segment_pool::allocate_segment (this=this@entry=0x7f83ec5e1bb8) at utils/logalloc.cc:660
#3  0x00000000007c9848 in logalloc::segment_pool::refill_emergency_reserve (this=0x7f83ec5e1bb8) at utils/logalloc.cc:691
#4  0x00000000007ce483 in logalloc::allocating_section::guard::enter (this=this@entry=0x7ffe2b699690, self=...) at utils/logalloc.cc:2104
#5  0x0000000000797814 in logalloc::allocating_section::operator()<row_cache::populate(const mutation&)::<lambda()>::<lambda()> > (func=<optimized out>, r=..., this=0x6000003a79d8) at utils/logalloc.hh:643
#6  row_cache::<lambda()>::operator() (__closure=<optimized out>) at row_cache.cc:694
#7  with_allocator<row_cache::populate(const mutation&)::<lambda()> > (func=<optimized out>, alloc=...) at ./utils/allocation_strategy.hh:222
#8  row_cache::populate (this=0x6000003a7790, m=...) at row_cache.cc:695
#9  0x00000000007a274d in single_partition_populating_reader::operator()()::{lambda(optimized_optional<mutation>&&)#2}::operator()(optimized_optional<mutation>&&) const (mo=<optimized out>, __closure=<optimized out>) at row_cache.cc:212
#10 apply_helper<single_partition_populating_reader::operator()()::{lambda(optimized_optional<mutation>&&)#2}, std::tuple<optimized_optional<mutation> >&&, std::integer_sequence<unsigned long, 0ul> >::apply({lambda(optimized_optional<mutation>&&)#2}&&, std::tuple<optimized_optional<mutation> >) (args=<optimized out>, func=<optimized out>) at ./seastar/core/apply.hh:34
#11 apply<single_partition_populating_reader::operator()()::{lambda(optimized_optional<mutation>&&)#2}, optimized_optional<mutation> >(single_partition_populating_reader::operator()()::{lambda(optimized_optional<mutation>&&)#2}&&, std::tuple<optimized_optional<mutation> >&&) (args=<optimized out>, func=<optimized out>) at ./seastar/core/apply.hh:42
#12 futurize<optimized_optional<streamed_mutation> >::apply<single_partition_populating_reader::operator()()::{lambda(optimized_optional<mutation>&&)#2}, optimized_optional<mutation> >(single_partition_populating_reader::operator()()::{lambda(optimized_optional<mutation>&&)#2}&&, std::tuple<optimized_optional<mutation> >&&) (func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x2ca2a5e, DIE 0x2e2cb2b>, 
    args=args@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x2ca2a5e, DIE 0x2e2d34f>) at ./seastar/core/future.hh:1158
#13 0x00000000007a6686 in _ZZN6futureIJ18optimized_optionalI8mutationEEE4thenIZN34single_partition_populating_readerclEvEUlOS2_E0_S_IJS0_I17streamed_mutationEEEEET0_OT_ENUlSD_E_clI12future_stateIJS2_EEEEDaSD_ (
    state=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x2ca2a5e, DIE 0x2deab80>, __closure=0x6000214a06a8) at ./seastar/core/future.hh:870
#14 _ZN12continuationIZN6futureIJ18optimized_optionalI8mutationEEE4thenIZN34single_partition_populating_readerclEvEUlOS3_E0_S0_IJS1_I17streamed_mutationEEEEET0_OT_EUlSE_E_JS3_EE3runEv (this=0x6000214a0690) at ./seastar/core/future.hh:402
#15 0x0000000000478dee in reactor::run_tasks (this=this@entry=0x60000023d000, tasks=...) at core/reactor.cc:1501
#16 0x00000000004a45bb in reactor::run (this=0x60000023d000) at core/reactor.cc:1854
#17 0x00000000005175cc in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7ffe2b69a3f0, ac=ac@entry=5, av=av@entry=0x7ffe2b69a668, 
    func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x65738c, DIE 0x714b81>) at core/app-template.cc:127
#18 0x000000000041958d in main (ac=5, av=0x7ffe2b69a668) at main.cc:636
```

This is bad because:

1. exceptions are slow

2. it prevents debugging via gdb's `catch throw`

We should remove exceptions from normal operation.

**Comment by avikivity** [comment]
lsa should also talk a little to the system allocator to figure out whether allocation is worthwhile.

**Comment by avikivity** [comment]
Another issue is that the exception implementation in the gcc C++ support library takes a lock, and this can easily cause lock contention if it happens in multiple shards concurrently.

**Comment by avikivity** [comment]
@pdziepak, @tgrabiec
