### ISSUE TITLE
cassandra-stress / cqlsh connection fails on native mode

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1407]
*Installation details*
Scylla version (or git commit hash): 2c4501f3172634692c83cfe42ee4ea0e4abacf9b
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora23

On native-mode, cassandra-stress and cqlsh causes connection error as follows:
```
[syuu@devil scylla]$ taskset -c 0 cassandra-stress write cl=QUORUM duration=10m -mode cql3 native -rate threads=10 -pop seq=1..10000000 -node 192.168.122.30
INFO  06:37:20 Found Netty's native epoll transport in the classpath, using it
Exception in thread "main" java.lang.RuntimeException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.122.30:9042 (com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on /192.168.122.30:9042: IPv6 socket addresses are not supported.))
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:198)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:205)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:55)
	at org.apache.cassandra.stress.Stress.main(Stress.java:109)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.122.30:9042 (com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on /192.168.122.30:9042: IPv6 socket addresses are not supported.))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:240)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1429)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:402)
	at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:121)
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:189)
	... 5 more
```

```
[syuu@devil scylla]$ CQLSH_HOST=192.168.122.30 cqlsh 
Connection error: ('Unable to connect to any servers', {'192.168.122.30': ProtocolError("cql_version '3.2.0' is not supported by remote (w/ native protocol). Supported versions: [u'3.2.1']",)})
[syuu@devil scylla]$ CQLSH_HOST=192.168.122.30 cqlsh --cqlversion=3.2.1
Connection error: ('Unable to connect to any servers', {'192.168.122.30': <ErrorMessage code=0000 [Server error] message="IPv6 socket addresses are not supported.">})
```

While clients getting error, scylla-server shows following error:
```
Keepalive is not supported by native stack
Keepalive is not supported by native stack
Keepalive is not supported by native stack
Keepalive is not supported by native stack
Keepalive is not supported by native stack
Keepalive is not supported by native stack
Keepalive is not supported by native stack
Keepalive is not supported by native stack
Keepalive is not supported by native stack
```

The error from seastar/net/native-stack-impl.hh, because we haven't implemented keepalive on socket for native-mode.

**Comment by penberg** [comment]
@syuu1228 This just means your ``cqlsh`` is not up-to-date and doesn't have commit https://github.com/scylladb/scylla-tools-java/commit/287262b55fd0bbe5767975c76e33c64b58a57d5d:

```
Connection error: ('Unable to connect to any servers', {'192.168.122.30': ProtocolError("cql_version '3.2.0' is not supported by remote (w/ native protocol). Supported versions: [u'3.2.1']",)})
```

It's not related to the IPv6 issue, though.

**Comment by syuu1228** [comment]
@penberg Just tested latest build of scylla-tools-java.
Version error was disappeared, but same 'Unable to connect' error.

```
$ CQLSH_HOST=192.168.122.30 cqlsh 
Connection error: ('Unable to connect to any servers', {'192.168.122.30': <ErrorMessage code=0000 [Server error] message="IPv6 socket addresses are not supported.">})
```

**Comment by syuu1228** [comment]
Looks like native-stack returns 0-filled client address on accept().
In the result, gms::inet_address::inet_address() throws "IPv6 socket addresses are not supported." exception, then client received such error message.
```
(gdb) f 1
#1  0x0000000000a39dcf in gms::inet_address::inet_address (sa=..., 
    this=<optimized out>) at gms/inet_address.hh:50
50	            throw std::invalid_argument("IPv6 socket addresses are not supported.");
(gdb) print sa
$1 = (const socket_address &) @0x602000250c48: {u = {sas = {ss_family = 0, 
      __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}, sa = {
      sa_family = 0, sa_data = '\000' <repeats 13 times>}, in = {
      sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, 
      sin_zero = "\000\000\000\000\000\000\000"}}}
(gdb) f 3 
#3  transport::cql_server::connection::process_query (this=0x602000129690, 
    stream=<optimized out>, buf="\000\001", client_state=...)
    at transport/server.cc:757
757	    query_state.begin_tracing(query.to_string(), query_state.get_client_state().get_client_address(), {});
(gdb) print client_state
$2 = {_keyspace = {u = {external = {str = 0x60200053d400 "\001", size = 8, 
        pad = 0 '\000'}, internal = {
        str = "\000\324S\000 `\000\000\b\000\000\000\000\000", 
        size = 0 '\000'}}, static npos = 4294967295}, _trace_state_ptr = {
    _p = 0x0}, _tracing_session_id = {_p = 0x0}, _user = {_b = 0x60204183ab68, 
    _p = 0x60204183ab78}, _is_internal = false, _is_thrift = false, 
  _last_timestamp_micros = 0, _dirty = false, _remote_address = {u = {sas = {
        ss_family = 0, __ss_padding = '\000' <repeats 117 times>, 
        __ss_align = 0}, sa = {sa_family = 0, 
        sa_data = '\000' <repeats 13 times>}, in = {sin_family = 0, 
        sin_port = 0, sin_addr = {s_addr = 0}, 
        sin_zero = "\000\000\000\000\000\000\000"}}}}
```

Root of the problem is seems like this one:
https://github.com/scylladb/seastar/blob/aed893e5daa21ae1ed4a7310c63d29e44a077083/net/native-stack-impl.hh#L61
It does not receive client address from native-stack, just returns empty socket_address().

**Comment by tzach** [comment]
@slivne @penberg  c-s not working is a showstopper issue, why did we push it to 1.4?

**Comment by slivne** [comment]
its related to native stack (dpdk)

**Comment by tzach** [comment]
Aha. 
In cassandra-stress, `native` mean CQL. Maybe we should call it "DPDK stack"

**Comment by penberg** [comment]
@tzach Or "kernel by-pass" stack. Ping @avikivity

**Comment by syuu1228** [comment]
Fixed at https://github.com/scylladb/seastar/commit/0da8423abfcebda1f164733f23ad42d25eb01b20
