### ISSUE TITLE
`Read` and `write` queries fail after adding a new node using different `DC` suffix

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla#14114]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

Queries fail by getting timeouts.

## How frequently does it reproduce?

2/2 using the Scylla build from here.

## Installation details

Kernel Version: 5.15.0-1036-aws
Scylla version (or git commit hash): `5.2.2-20230530.9dd70a58c3f9` with build-id `d3997884004abbd7d6f60bf507b63050c88c4cf3`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-7 (63.32.46.100 | 10.4.2.217) (shards: 14) (Datatacenter: eu-west_nemesis_dc)
- longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-6 (52.18.247.156 | 10.4.8.254) (shards: 14) (Datatacenter: eu-west)
- longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5 (52.209.219.93 | 10.4.10.198) (shards: 14) (Datatacenter: eu-west)
- longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-4 (3.253.107.85 | 10.4.7.112) (shards: 14) (Datatacenter: eu-west)
- longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-3 (34.253.52.29 | 10.4.5.191) (shards: 14) (Datatacenter: eu-west)
- longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-2 (54.154.69.14 | 10.4.0.138) (shards: 14) (Datatacenter: eu-west)
- longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-1 (3.252.250.146 | 10.4.3.52) (shards: 14) (Datatacenter: eu-west)

OS / Image: `ami-04684e54dd2d82c19` (aws: eu-west-1)

Test: `longevity-cdc-100gb-4h-test`
Test id: `13e8ebce-c837-4886-b566-f3d7657be413`
Test name: `scylla-5.2/longevity/longevity-cdc-100gb-4h-test`
Test config file(s):

- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/729b19a44daf479b16ee6cda962d6c79794ed255/test-cases/longevity/longevity-cdc-100gb-4h.yaml)

## Details:
In this setup we ran the `add_remove_dc` nemesis which has following steps:
- Create new `keyspace_new_dc` keyspace
- Create new node in the same real `region`
- Update new node's config -> `echo dc_suffix=_nemesis_dc >> /etc/scylla/cassandra-rackdc.properties`
- Run `nodetool rebuild -- eu-west` on the new node
- Run `nodetool repair -pr` on each of the nodes
- Run `write` and `read` load
  - `Query failures occur here`
- Decommission the new node
- Drop the newly added keyspace

On the step where we run `read` and `write` load we get failures for both.
SCT-runner logs:
```
2023-05-31 19:07:56,771 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-05-31 19:07:56.769: (InfoEvent Severity.NORMAL) period_type=not-set event_id=b8fab0eb-3deb-4765-8af2-6818e9da6781: message=execute rebuild on new datacenter
...
2023-05-31 19:08:00,790 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-05-31 19:08:00.778: (InfoEvent Severity.NORMAL) period_type=not-set event_id=4e88a493-68b7-4756-b0d3-d65f401c8c63: message=Running full cluster repair on each node
...
2023-05-31 19:44:02,285 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-05-31 19:44:02.284: (InfoEvent Severity.NORMAL) period_type=not-set event_id=3779ee27-8a9d-49c4-bdb4-ea1c3dc14bf7: message=Writing and reading data with new dc
...
2023-05-31 19:44:08,204 f:stress_thread.py l:287  c:sdcm.stress_thread   p:INFO  > cassandra-stress write no-warmup cl=ALL n=10000 -schema 'keyspace=keyspace_new_dc replication(strategy=NetworkTopologyStrategy,eu-west=3,eu-west_nemesis_dc=1) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 native compression=lz4 -rate threads=5 -pop seq=1..10000 -log interval=5 -node 10.4.3.52,10.4.0.138,10.4.5.191,10.4.7.112,10.4.10.198,10.4.8.254,10.4.2.217 -errors skip-unsupported-columns
2023-05-31 19:44:08,229 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-05-31 19:44:08.227: (CassandraStressEvent Severity.NORMAL) period_type=begin event_id=595728c7-95fc-4061-8431-6ebc54296f70: node=Node longevity-cdc-100gb-4h-5-2-loader-node-13e8ebce-1 [34.253.123.203 | 10.4.1.91] (seed: False)
2023-05-31 19:44:08,229 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress write no-warmup cl=ALL n=10000 -schema 'keyspace=keyspace_new_dc replication(strategy=NetworkTopologyStrategy,eu-west=3,eu-west_nemesis_dc=1) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 native compression=lz4 -rate threads=5 -pop seq=1..10000 -log interval=5
2023-05-31 19:44:12,840 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-05-31 19:44:12.839: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=595728c7-95fc-4061-8431-6ebc54296f70: type=ShardAwareDriver regex=Using optimized driver line_number=83 node=Node longevity-cdc-100gb-4h-5-2-loader-node-13e8ebce-1 [34.253.123.203 | 10.4.1.91] (seed: False)
2023-05-31 19:44:12,840 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > ===== Using optimized driver!!! =====
2023-05-31 19:44:54,296 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:CRITICAL > 2023-05-31 19:44:54.294: (CassandraStressLogEvent Severity.CRITICAL) period_type=one-time event_id=595728c7-95fc-4061-8431-6ebc54296f70 during_nemesis=AddRemoveDc: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=142 node=Node longevity-cdc-100gb-4h-5-2-loader-node-13e8ebce-1 [34.253.123.203 | 10.4.1.91] (seed: False)
2023-05-31 19:44:54,296 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:CRITICAL > java.io.IOException: Operation x10 on key(s) [30503337373039503231]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
2023-05-31 19:44:54,303 f:tester.py       l:2778 c:LongevityTest        p:INFO  > TearDown is starting...
```

`Read` loader:
```
Sleeping 2s...
Running READ with 5 threads for 10000 iteration
===== Using optimized driver!!! =====
Connected to cluster: longevity-cdc-100gb-4h-5-2-db-cluster-13e8ebce, max pending requests per connection null, max connections per host 8
Datatacenter: eu-west; Host: /10.4.3.52; Rack: 1a
Datatacenter: eu-west; Host: /10.4.8.254; Rack: 1c
Datatacenter: eu-west; Host: /10.4.5.191; Rack: 1b
Datatacenter: eu-west; Host: /10.4.7.112; Rack: 1b
Datatacenter: eu-west; Host: /10.4.0.138; Rack: 1a
Datatacenter: eu-west; Host: /10.4.10.198; Rack: 1c
type       total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
Failed to connect over JMX; not collecting these stats
java.io.IOException: Operation x0 on key(s) [4f32364b4f3938323031]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
java.io.IOException: Operation x0 on key(s) [4d4e38303432504d4c30]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
java.io.IOException: Operation x0 on key(s) [383138373434344c3331]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
java.io.IOException: Operation x0 on key(s) [4b373034344c314d5030]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
total,            48,     457,     428,     428,     3.8,     2.6,     7.6,     9.8,     9.8,     9.8,    0.1,  0.00000,      3,      0,       0,       0,       0,       0
FAILURE
java.lang.RuntimeException: Failed to execute stress action
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:101)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

monitoring screenshot:
![Screenshot from 2023-06-01 17-12-47](https://github.com/scylladb/scylladb/assets/3796058/c297c30e-f8d2-44a4-805e-1eca4d97784d)

We see that `node-5 (10.4.10.198)` node has lots of failed reads and writes in short period of time.

Here is a previously passed CI job (`5.2.2-0.20230521.9dd70a58c3f9 with build-id d692f21f4fc0ee40fac88d4bdef5d4f0999127ba`) for comparison ([Argus](https://argus.scylladb.com/test/fa88d2c7-3d74-4e7b-b0b2-229a5d49b5b1/runs?additionalRuns[]=ccff5df9-e262-4365-8be5-02edf0e75acb), [CI job](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-cdc-100gb-4h-test/19/)):
![Screenshot from 2023-06-01 17-13-55](https://github.com/scylladb/scylladb/assets/3796058/af5bab23-fe1a-41c3-9945-2d47190293d2)

So, in the `5.2.2-0.20230521.9dd70a58c3f9 with build-id d692f21f4fc0ee40fac88d4bdef5d4f0999127ba` this problem was absent.

The `node-5` logs:
```
2023-05-31T19:43:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5     !INFO | scylla[5703]:  [shard  4] compaction_manager - Starting off-strategy compaction for cdc_test.test_table, 693 candidates were found
2023-05-31T19:47:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: I/O error occurred while writing; fd='16', error='Broken pipe (32)'
2023-05-31T19:47:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection broken; fd='16', server='AF_INET(10.4.0.73:32768)', time_reopen='60'
2023-05-31T19:50:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5     !INFO | scylla[5703]:  [shard  5] compaction - [Compact cdc_test.test_table_preimage_postimage_scylla_cdc_log 62f82360-ffeb-11ed-b70c-ced150864085] Compacted 2 sstables to []. 17MB to 0 bytes (~0% of original) in 0ms = 0 bytes/s. ~1536 total partitions merged to 0.
...
2023-05-31T19:51:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: Destination reliable queue full, dropping message; filename='/tmp/syslog-ng-00000.rqf', queue_len='87', mem_buf_size='100000', disk_buf_size='2000000', persist_name='afsocket_dd_qfile(stream,10.4.0.73:32768)'
2023-05-31T19:51:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: I/O error occurred while writing; fd='20', error='Broken pipe (32)'
2023-05-31T19:51:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection broken; fd='20', server='AF_INET(10.4.0.73:32768)', time_reopen='60'
2023-05-31T19:51:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5     !INFO | scylla[5703]:  [shard  3] compaction_manager - Done with off-strategy compaction for cdc_test.test_table_preimage_postimage_scylla_cdc_log
...
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5     !INFO | scylla[5703]:  [shard  4] compaction - [Compact cdc_test.test_table_preimage_scylla_cdc_log f8a12060-ffeb-11ed-9a81-cec750864085] Compacting [/var/lib/scylla/data/cdc_test/test_table_preimage_scylla_cdc_log-fd28e182ffe211ed9a1919e5947e8523/me-5184-big-Data.db:level=0:origin=compaction]
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5     !INFO | scylla[5703]:  [shard 12] compaction_manager - Done with off-strategy compaction for cdc_test.test_table_preimage_scylla_cdc_log
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: Destination reliable queue full, dropping message; filename='/tmp/syslog-ng-00000.rqf', queue_len='298', mem_buf_size='100000', disk_buf_size='2000000', persist_name='afsocket_dd_qfile(stream,10.4.0.73:32768)'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: Destination reliable queue full, dropping message; filename='/tmp/syslog-ng-00000.rqf', queue_len='298', mem_buf_size='100000', disk_buf_size='2000000', persist_name='afsocket_dd_qfile(stream,10.4.0.73:32768)'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: Destination reliable queue full, dropping message; filename='/tmp/syslog-ng-00000.rqf', queue_len='299', mem_buf_size='100000', disk_buf_size='2000000', persist_name='afsocket_dd_qfile(stream,10.4.0.73:32768)'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection established; fd='20', server='AF_INET(10.4.0.73:32768)', local='AF_INET(0.0.0.0:0)'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: EOF occurred while idle; fd='20'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection closed; fd='20', server='AF_INET(10.4.0.73:32768)', time_reopen='60'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection established; fd='20', server='AF_INET(10.4.0.73:32768)', local='AF_INET(0.0.0.0:0)'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: EOF occurred while idle; fd='20'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection closed; fd='20', server='AF_INET(10.4.0.73:32768)', time_reopen='60'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection established; fd='20', server='AF_INET(10.4.0.73:32768)', local='AF_INET(0.0.0.0:0)'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: I/O error occurred while writing; fd='20', error='Broken pipe (32)'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection broken; fd='20', server='AF_INET(10.4.0.73:32768)', time_reopen='60'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection established; fd='20', server='AF_INET(10.4.0.73:32768)', local='AF_INET(0.0.0.0:0)'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5      !ERR | syslog-ng[4818]: I/O error occurred while writing; fd='20', error='Broken pipe (32)'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection broken; fd='20', server='AF_INET(10.4.0.73:32768)', time_reopen='60'
2023-05-31T19:52:16+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | syslog-ng[4818]: Syslog connection established; fd='20', server='AF_INET(10.4.0.73:32768)', local='AF_INET(0.0.0.0:0)'
2023-05-31T19:55:50+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5   !NOTICE | sudo[14192]: scyllaadm : PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/grep ^SCYLLA_ARGS= /etc/default/scylla-server
2023-05-31T19:55:50+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-5     !INFO | sudo[14192]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
```

The error `I/O error occurred while writing; fd='16', error='Broken pipe (32)'` is special for the `node-5`.

## Monitoring:

- Restore Monitor Stack command: `$ hydra investigate show-monitor 13e8ebce-c837-4886-b566-f3d7657be413`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=13e8ebce-c837-4886-b566-f3d7657be413)
- Show all stored logs command: `$ hydra investigate show-logs 13e8ebce-c837-4886-b566-f3d7657be413`

## Logs:
- **db-cluster-13e8ebce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/db-cluster-13e8ebce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/db-cluster-13e8ebce.tar.gz)
- **sct-runner-events-13e8ebce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/sct-runner-events-13e8ebce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/sct-runner-events-13e8ebce.tar.gz)
- **sct-13e8ebce.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/sct-13e8ebce.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/sct-13e8ebce.log.tar.gz)
- **monitor-set-13e8ebce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/monitor-set-13e8ebce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/monitor-set-13e8ebce.tar.gz)
- **loader-set-13e8ebce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/loader-set-13e8ebce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/loader-set-13e8ebce.tar.gz)
- **parallel-timelines-report-13e8ebce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/parallel-timelines-report-13e8ebce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/13e8ebce-c837-4886-b566-f3d7657be413/20230531_200501/parallel-timelines-report-13e8ebce.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-cdc-100gb-4h-test/26/)
[Argus](https://argus.scylladb.com/test/fa88d2c7-3d74-4e7b-b0b2-229a5d49b5b1/runs?additionalRuns[]=13e8ebce-c837-4886-b566-f3d7657be413)

**Comment by mykaul** [comment]
@vponomaryov - did you look at the cluster logs? Anything interesting there?

**Comment by mykaul** [comment]
Are you sure the IO errors are not when you are decommissioning?
```
2023-05-31T19:45:22+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-7     !INFO | scylla[5520]:  [shard  0] api - decommission
2023-05-31T19:45:22+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-7     !INFO | scylla[5520]:  [shard  0] storage_service - DECOMMISSIONING: starts
2023-05-31T19:45:22+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-7     !INFO | scylla[5520]:  [shard  0] storage_service - decommission[f68ccd2a-ebd7-4669-bfd1-7c112a7f578e]: Started decommission operation: node=9dc22ec1-a2fe-48f6-a842-2e593f12e05d/10.4.2.217, sync_nodes={10.4.2.217, 10.4.3.52, 10.4.8.254, 10.4.7.112, 10.4.10.198, 10.4.5.191, 10.4.0.138}, ignore_nodes={}
```

(From node-7 log - 19:44 seems to be when you have the timeouts?)

**Comment by vponomaryov** [comment]
> @vponomaryov - did you look at the cluster logs? Anything interesting there?

Fixed. Actually, I prepared it and didn't add for some unintentional reason...

> Are you sure the IO errors are not when you are decommissioning?
> 
> ```
> 2023-05-31T19:45:22+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-7     !INFO | scylla[5520]:  [shard  0] api - decommission
> 2023-05-31T19:45:22+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-7     !INFO | scylla[5520]:  [shard  0] storage_service - DECOMMISSIONING: starts
> 2023-05-31T19:45:22+00:00 longevity-cdc-100gb-4h-5-2-db-node-13e8ebce-7     !INFO | scylla[5520]:  [shard  0] storage_service - decommission[f68ccd2a-ebd7-4669-bfd1-7c112a7f578e]: Started decommission operation: node=9dc22ec1-a2fe-48f6-a842-2e593f12e05d/10.4.2.217, sync_nodes={10.4.2.217, 10.4.3.52, 10.4.8.254, 10.4.7.112, 10.4.10.198, 10.4.5.191, 10.4.0.138}, ignore_nodes={}
> ```
> 
> (From node-7 log - 19:44 seems to be when you have the timeouts?)

I am sure. It is not `when`, it is `after` as a `finalizer` step for any nemesis result.

**Comment by mykaul** [comment]
From the above (initial description) I see:
```
2023-05-31 19:44:54,296 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:CRITICAL > 2023-05-31 19:44:54.294: (CassandraStressLogEvent Severity.CRITICAL) period_type=one-time event_id=595728c7-95fc-4061-8431-6ebc54296f70 during_nemesis=AddRemoveDc: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=142 node=Node longevity-cdc-100gb-4h-5-2-loader-node-13e8ebce-1 [34.253.123.203 | 10.4.1.91] (seed: False)
2023-05-31 19:44:54,296 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:CRITICAL > java.io.IOException: Operation x10 on key(s) [30503337373039503231]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
```

Were there any previous IO errors? I'm not sure I understand where (when) I need to look for errors. https://github.com/scylladb/scylla-cluster-tests/issues/6088 might have helped here.

**Comment by vponomaryov** [comment]
> From the above (initial description) I see:
> 
> ```
> 2023-05-31 19:44:54,296 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:CRITICAL > 2023-05-31 19:44:54.294: (CassandraStressLogEvent Severity.CRITICAL) period_type=one-time event_id=595728c7-95fc-4061-8431-6ebc54296f70 during_nemesis=AddRemoveDc: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=142 node=Node longevity-cdc-100gb-4h-5-2-loader-node-13e8ebce-1 [34.253.123.203 | 10.4.1.91] (seed: False)
> 2023-05-31 19:44:54,296 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:CRITICAL > java.io.IOException: Operation x10 on key(s) [30503337373039503231]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
> ```
> 
> Were there any previous IO errors? I'm not sure I understand where (when) I need to look for errors. [scylladb/scylla-cluster-tests#6088](https://github.com/scylladb/scylla-cluster-tests/issues/6088) might have helped here.

This the message of the SCT events handler which follows lots of various places.
In current case it is based on the `write` load from one of the loaders:

```
===== Using optimized driver!!! =====
Connected to cluster: longevity-cdc-100gb-4h-5-2-db-cluster-ccff5df9, max pending requests per connection null, max connections per host 8
WARN  16:21:18,592 Some contact points don't match local data center. Local DC = eu-west. Non-conforming contact points: /10.4.2.251:9042 (eu-west_nemesis_dc)
Datatacenter: eu-west; Host: /10.4.9.83; Rack: 1c
Datatacenter: eu-west; Host: /10.4.2.133; Rack: 1a
Datatacenter: eu-west; Host: /10.4.6.218; Rack: 1b
Datatacenter: eu-west_nemesis_dc; Host: /10.4.2.251; Rack: 1a
Datatacenter: eu-west; Host: /10.4.11.157; Rack: 1c
Datatacenter: eu-west; Host: /10.4.7.166; Rack: 1b
Datatacenter: eu-west; Host: /10.4.1.217; Rack: 1a
WARN  16:21:31,079 No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes.
Created keyspaces. Sleeping 7s for propagation.
Sleeping 2s...
Running WRITE with 5 threads for 10000 iteration
type       total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
Failed to connect over JMX; not collecting these stats
total,           169,      34,      34,      34,   110.3,     6.2,   274.5,  2124.4,  2847.9,  2847.9,    5.0,  0.00000,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
total,           865,     139,     139,     139,    34.5,     4.0,    21.7,   497.0,  3447.7,  3447.7,   10.0,  0.49633,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
total,          2215,     270,     270,     270,    19.3,     3.2,    14.2,    82.8,  2938.1,  2982.2,   15.0,  0.35283,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
total,          3054,     168,     168,     168,    26.6,     3.5,    13.5,   395.6,  3240.1,  3240.1,   20.0,  0.25549,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (4 replica were required but only 3 acknowledged the write)
total,          3289,      47,      47,      47,   121.7,     3.5,     9.9,  5536.5,  5620.4,  5620.4,   25.0,  0.64236,      0,      0,       0,       0,       0,       0
total,          7228,     788,     788,     788,     6.3,     3.7,    18.5,    32.2,    99.3,   103.5,   30.0,  0.46179,      0,      0,       0,       0,       0,       0
total,         10000,     575,     575,     575,     8.5,     3.5,    17.5,    26.0,  1691.4,  1740.6,   34.8,  0.36511,      0,      0,       0,       0,       0,       0


Results:
Op rate                   :      287 op/s  [WRITE: 287 op/s]
Partition rate            :      287 pk/s  [WRITE: 287 pk/s]
Row rate                  :      287 row/s [WRITE: 287 row/s]
Latency mean              :   16.8 ms [WRITE: 16.8 ms]
Latency median            :    3.5 ms [WRITE: 3.5 ms]
Latency 95th percentile   :   18.6 ms [WRITE: 18.6 ms]
Latency 99th percentile   :  110.9 ms [WRITE: 110.9 ms]
Latency 99.9th percentile : 3231.7 ms [WRITE: 3,231.7 ms]
Latency max               : 5620.4 ms [WRITE: 5,620.4 ms]
Total partitions          :     10,000 [WRITE: 10,000]
Total errors              :          0 [WRITE: 0]
Total GC count            : 0
Total GC memory           : 0.000 KiB
Total GC time             :    0.0 seconds
Avg GC time               :    NaN ms
StdDev GC time            :    0.0 ms
Total operation time      : 00:00:34

END
```
