### ISSUE TITLE
nodetool print a warning about filter_cassandra_attributes.py

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1425]
_Installation details_
Scylla version (or git commit hash): 1.2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2

After the warning nodetool return the right response

```
> nodetool status
Traceback (most recent call last):
  File "/usr/bin/filter_cassandra_attributes.py", line 14, in <module>
    main()
  File "/usr/bin/filter_cassandra_attributes.py", line 10, in main
    attributes.update(load(open(sys.argv[i], 'r')))
TypeError: 'NoneType' object is not iterable
Datacenter: TELECITY
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  185.94.84.232  336.2 MB   256     ?       84e1a0f9-6c6a-46ce-9263-8401189d9bff  Z2C2
UN  185.94.84.231  336.26 MB  256     ?       6bdf873c-6b36-4575-bde5-e25e4c1ffb10  Z2C2

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

**Comment by tzach** [comment]
@amnonh can you take a look?

**Comment by slivne** [comment]
@tzach is this still happening -  have you been able to reproduce this 

to me it seems as if there are no permissions or something in those lines

**Comment by tzach** [comment]
This is from a user system, so I cant reproduce.

**Comment by slivne** [comment]
if this happens again please add info - closing
