### ISSUE TITLE
nodetool repair -dcpar flag is not supported

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1462]
*Installation details*
Scylla version (or git commit hash): 666.development-20160713.b5bef73

```
shlomi@localhost~/urchin-ccm (master)$ ~/cassandra/bin/nodetool repair --port 7100 -dcpar 
error: Scylla API server HTTP POST to URL '/storage_service/repair_async/keyspace1' failed: unsupported repair parallelism: 2
-- StackTrace --
java.lang.IllegalStateException: Scylla API server HTTP POST to URL '/storage_service/repair_async/keyspace1' failed: unsupported repair parallelism: 2
	at com.scylladb.jmx.api.APIClient.getException(APIClient.java:124)
	at com.scylladb.jmx.api.APIClient.post(APIClient.java:111)
	at com.scylladb.jmx.api.APIClient.postGetVal(APIClient.java:128)
	at com.scylladb.jmx.api.APIClient.postInt(APIClient.java:132)
	at org.apache.cassandra.service.StorageService.repairAsync(StorageService.java:731)
	at org.apache.cassandra.service.StorageService.forceRepairAsync(StorageService.java:1423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mx4j.server.ReflectionMBeanInvoker.invokeImpl(ReflectionMBeanInvoker.java:156)
	at mx4j.server.ReflectionMBeanInvoker.doInvoke(ReflectionMBeanInvoker.java:117)
	at mx4j.server.ReflectionMBeanInvoker.invoke(ReflectionMBeanInvoker.java:52)
	at mx4j.server.interceptor.InvokerMBeanServerInterceptor.invoke(InvokerMBeanServerInterceptor.java:238)
	at mx4j.server.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:120)
	at mx4j.server.interceptor.SecurityMBeanServerInterceptor.invoke(SecurityMBeanServerInterceptor.java:84)
	at mx4j.server.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:120)
	at mx4j.server.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:120)
	at mx4j.server.interceptor.ContextClassLoaderMBeanServerInterceptor.invoke(ContextClassLoaderMBeanServerInterceptor.java:203)
	at mx4j.server.MX4JMBeanServer.invoke(MX4JMBeanServer.java:1043)
	at mx4j.server.ChainedMBeanServer.invoke(ChainedMBeanServer.java:196)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by denesb** [comment]
I don't think we will ever implement this. Currently, repair parallelism can be controlled by scylla-manager, which repairs ranges in parallel.
Tablet repairs are scheduled in parallel internally already.

We have no plans to allow the user to control this via nodetool.
