### ISSUE TITLE
sstableloader - check what happens if a table was altered

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1470]
sstables may be altered over the course of time - scylla is able to read persisted data using older schemas. 

sstableloader translates stored data into cql commands - since it is using the last schema (and does not have schema history information) it can only read data that is in synch with the last available schema.

need to create a test to verify that in case we can not synch the persisted data with the schema we will fail with informative information 

example sequence:
1. create table (A INT,B INT ,C INT)
2. insert data
3. flush data
4. alter table rename C to D, drop column B
5. insert data (not overwriting step 2)
6. flush data 
7. snapshot - copy data 
8. stop node
9. clear data
10. try to load snapshot using sstableloader

**Comment by tzach** [comment]
@elcallio ping

**Comment by slivne** [comment]
@roydahan - I assigned this to you - and we can change if you relay this 

The goal is to have this in regression testing.

**Comment by larisau** [comment]
the test worked for cassandra2.2.6, but failed for cassandra3.3.0
for scylla(dev) sstableloader fails which the following error:

CQL: 'INSERT INTO ks.cf (a,key,d) values (?,?,?) USING TIMESTAMP ?;' [4, 234, 5, 1486638222419607]
java.lang.AssertionError: Unknown column b in table ks.cf
	at org.apache.cassandra.db.LegacyLayout.readLegacyAtom(LegacyLayout.java:1026)
	at org.apache.cassandra.db.UnfilteredDeserializer$OldFormatDeserializer$AtomIterator.readAtom(UnfilteredDeserializer.java:518)
	at org.apache.cassandra.db.UnfilteredDeserializer$OldFormatDeserializer$AtomIterator.hasNext(UnfilteredDeserializer.java:504)
	at org.apache.cassandra.db.UnfilteredDeserializer$OldFormatDeserializer$UnfilteredIterator.readRow(UnfilteredDeserializer.java:447)
	at org.apache.cassandra.db.UnfilteredDeserializer$OldFormatDeserializer$UnfilteredIterator.hasNext(UnfilteredDeserializer.java:423)
	at org.apache.cassandra.db.UnfilteredDeserializer$OldFormatDeserializer.hasNext(UnfilteredDeserializer.java:289)
	at org.apache.cassandra.io.sstable.SSTableSimpleIterator$OldFormatIterator.readStaticRow(SSTableSimpleIterator.java:133)
	at org.apache.cassandra.io.sstable.SSTableIdentityIterator.<init>(SSTableIdentityIterator.java:57)
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner$KeyScanningIterator$1.initializeIterator(BigTableScanner.java:334)
	at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.maybeInit(LazilyInitializedUnfilteredRowIterator.java:48)
	at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.metadata(LazilyInitializedUnfilteredRowIterator.java:53)
	at com.scylladb.tools.SSTableToCQL$RowBuilder.process(SSTableToCQL.java:634)
	at com.scylladb.tools.SSTableToCQL$RowBuilder.access$200(SSTableToCQL.java:116)
	at com.scylladb.tools.SSTableToCQL.process(SSTableToCQL.java:850)
	at com.scylladb.tools.SSTableToCQL.stream(SSTableToCQL.java:881)
	at com.scylladb.tools.BulkLoader.main(BulkLoader.java:840)

**Comment by elcallio** [comment]
What does "worked with cassandra2.2.6, but failed for cassandra3.3.0" 
mean here?

If the table was written by cassandra 3.x, we should not be running the 
LegacyLayout scanner, so which sstable was actually being read here?

In any case, the AssertionError, contrary to its message is not actually 
about the column being gone, the scanner is fine with that. It is 
actually complaining about the fact that there is no record of the 
column being dropped (and thus existing at some point). This is of 
course not surprising, since we generate the CF metadata based on CQL 
driver info, not on actual system tables (if we do keep track of this).

**Comment by slivne** [comment]
"worked with cassandra2.2.6, but failed for cassandra3.3.0"
if you run the test - trying to upload sstabled that have been altered with cassandra 2.2.6 - data is loaded 
if you run the test with cassandra 3.3.0 it fails - sstableloader is not able to load the files 
@larisau - please try this with cassandra 3.0.9 / 3.9 - they had some bug fixes go into sstableloader (https://issues.apache.org/jira/browse/CASSANDRA-10990)

@elcallio the sstables have been created by scylla - so they are 2.1 - how hard would it be to fix sstableloader to support loading in case of altering.

**Comment by slivne** [comment]
I checked alter table

https://docs.datastax.com/en/cql/3.1/cql/cql_reference/alter_table_r.html#reference_ds_xqq_hpc_xj__renaming-a-column

it seems this should work for us as it does for cassandra as the sstable content does not include the clustering key name (https://github.com/scylladb/scylla/wiki/SSTables-Data-File#rows) and I also played with sstable2json (AKA sstabledump) and checked that we get out of that.

So @larisau can you create a test that only renames a clustering key and lets check that this works, if not we need to understand why.

**Comment by larisau** [comment]
tested this with cassandra 3.0.9 / 3.9, failed in both with the same error(about the column that was dropped):
java.lang.RuntimeException: Unknown column b during deserialization
.....

**Comment by slivne** [comment]
Lets open a bug for them ... with the reproducer info :)

**Comment by slivne** [comment]
A possible workaround:

- Run sstablescrub / force major compaction - prior to sstableloader - lets validate if any of those works

**Comment by amoskong** [comment]
I can't reproduce this problem if I restore the snapshot by `/usr/bin/sstableloader`, which is installed by `scylla-tools-666.development-20180205.8f1fa6436.el7.centos.noarch`

This problem can't be reproduced in dtest [1] with latest `scylladb/scylla-tools-java.git` [2]

[1] snapshot_test.py:TestSnapshot.restore_snapshot_with_alter_table_drop_column_test
[2] 8f1fa64368ef2fddb52b19f32d78fde7767a9c67


It can be reproduced with old scylla-tools-java.git, I try to run sstablescrub / nodetool compact before sstableloader, but problem still exists.

**Comment by roydahan** [comment]
I think we can mark as fixed according to @amoskong testing.

**Comment by tzach** [comment]
@roydahan do we have a dtest to check this?

**Comment by roydahan** [comment]
migrate_sstable_with_schema_change_test
