### ISSUE TITLE
Failed DTEST :  consistency_test.py:TestAccuracy.test_simple_strategy_users

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#149]
On jenkins we get the following

On my laptop I am not able to reproduce this - but on jenkins its consistent - will try to analyze and find the root cause

PATH=`pwd`/urchin-ccm:$PATH
export PATH
export PERL5LIB=`pwd`/urchin-ccm
export PYTHONPATH=`pwd`/urchin-ccm
export CASSANDRA_DIR=`pwd`/urchin
cd urchin-dtest
export HOME=/home/jenkins
REUSE_CLUSTER=false KEEP_TEST_DIR=true PRINT_DEBUG=true DEBUG=true nosetests -v -s consistency_test.py:TestAccuracy.test_simple_strategy_users

```
REUSE_CLUSTER=false KEEP_TEST_DIR=true PRINT_DEBUG=true DEBUG=true nosetests -v -s consistency_test.py:TestAccuracy.test_simple_strategy_users
/usr/lib64/python2.7/site-packages/cassandra/util.py:486: UserWarning: The blist library is not available, so a pure python list-based set will be used in place of blist.sortedset for set collection values. You can find the blist library here: https://pypi.python.org/pypi/blist/
  "The blist library is not available, so a pure python list-based set will "
test_simple_strategy_users (consistency_test.TestAccuracy) ... cluster ccm directory: /home/jenkins/.dtest/dtest-cboVZV
Testing single dc, users
Testing accuracy for ALL/ALL/- (keys : 0 to 50)
Testing accuracy for QUORUM/QUORUM/- (keys : 50 to 100)
Testing accuracy for ALL/ONE/- (keys : 100 to 150)
Testing accuracy for ONE/ALL/- (keys : 150 to 200)
Testing accuracy for QUORUM/ONE/- (keys : 200 to 250)
Testing accuracy for ONE/QUORUM/- (keys : 250 to 300)
Testing accuracy for TWO/TWO/- (keys : 300 to 350)
Testing accuracy for ONE/THREE/- (keys : 350 to 400)
Waiting for workers to complete
Testing accuracy for THREE/ONE/- (keys : 400 to 450)
Testing accuracy for ANY/ONE/- (keys : 450 to 500)
Testing accuracy for ONE/ONE/- (keys : 500 to 550)
Testing accuracy for ONE/TWO/- (keys : 550 to 600)
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/urchin-dtest/workspace/label/master/urchin-dtest/consistency_test.py", line 448, in run
    valid_fcn(v)
  File "/var/lib/jenkins/jobs/urchin-dtest/workspace/label/master/urchin-dtest/consistency_test.py", line 391, in validate_users
    outer.insert_user(sessions[s], n, age, write_cl, serial_cl)
  File "/var/lib/jenkins/jobs/urchin-dtest/workspace/label/master/urchin-dtest/consistency_test.py", line 126, in insert_user
    session.execute(statement)
  File "/usr/lib64/python2.7/site-packages/cassandra/cluster.py", line 1405, in execute
    result = future.result(timeout)
  File "/usr/lib64/python2.7/site-packages/cassandra/cluster.py", line 2976, in result
    raise self._final_exception
WriteTimeout: code=1100 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out - received only 0 responses." info={'received_responses': 0, 'required_responses': 2, 'consistency': 'TWO'}
FAIL
Testing accuracy for TWO/ONE/- (keys : 600 to 650)

======================================================================
FAIL: test_simple_strategy_users (consistency_test.TestAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/urchin-dtest/workspace/label/master/urchin-dtest/consistency_test.py", line 503, in test_simple_strategy_users
    self._run_test_function_in_parallel(TestAccuracy.Validation.validate_users, [self.nodes], [self.rf], combinations)
  File "/var/lib/jenkins/jobs/urchin-dtest/workspace/label/master/urchin-dtest/consistency_test.py", line 475, in _run_test_function_in_parallel
    assert False, "Look for an exception above"
AssertionError: Look for an exception above
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/jenkins/.dtest/dtest-cboVZV
dtest: DEBUG: Testing single dc, users
cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: {UUID('b2e1ad15-a1bd-3f4b-8bc9-fe773ec57344'): ['127.0.0.3', '127.0.0.1'], UUID('244c8201-a6ef-3816-bfa5-e849bdc980c2'): ['127.0.0.2'], UUID('bee9c387-4034-3313-b8bb-b624562feb20'): ['127.0.0.5', '127.0.0.4']}
cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: {UUID('b2e1ad15-a1bd-3f4b-8bc9-fe773ec57344'): ['127.0.0.4', '127.0.0.3', '127.0.0.2', '127.0.0.1'], UUID('e9964332-40f3-3d19-98e9-281569938128'): ['127.0.0.5']}
cassandra.cluster: WARNING: Node 127.0.0.2 is reporting a schema disagreement: {UUID('b2e1ad15-a1bd-3f4b-8bc9-fe773ec57344'): ['127.0.0.3', '127.0.0.2', '127.0.0.1'], UUID('9986362a-186a-3495-b4a4-94fe06bee953'): ['127.0.0.5'], UUID('54a7b5fe-193b-35b3-8686-d1db96f25ac8'): ['127.0.0.4']}
cassandra.cluster: WARNING: [control connection] No schema built on connect; retrying without wait for schema agreement
dtest: DEBUG: Testing accuracy for ALL/ALL/- (keys : 0 to 50)
dtest: DEBUG: Testing accuracy for QUORUM/QUORUM/- (keys : 50 to 100)
dtest: DEBUG: Testing accuracy for ALL/ONE/- (keys : 100 to 150)
dtest: DEBUG: Testing accuracy for ONE/ALL/- (keys : 150 to 200)
dtest: DEBUG: Testing accuracy for QUORUM/ONE/- (keys : 200 to 250)
dtest: DEBUG: Testing accuracy for ONE/QUORUM/- (keys : 250 to 300)
dtest: DEBUG: Testing accuracy for TWO/TWO/- (keys : 300 to 350)
dtest: DEBUG: Testing accuracy for ONE/THREE/- (keys : 350 to 400)
dtest: DEBUG: Waiting for workers to complete
dtest: DEBUG: Testing accuracy for THREE/ONE/- (keys : 400 to 450)
dtest: DEBUG: Testing accuracy for ANY/ONE/- (keys : 450 to 500)
dtest: DEBUG: Testing accuracy for ONE/ONE/- (keys : 500 to 550)
dtest: DEBUG: Testing accuracy for ONE/TWO/- (keys : 550 to 600)
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 84.091s

FAILED (failures=1)
```

**Comment by slivne** [comment]
schema migration issue the same as #357 that has been fixed - closing
