### ISSUE TITLE
prepared statements on v1 cql protocol do not work

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1676]
*Installation details*
Scylla version (or git commit hash): 1.3

update cql_prepared_test.py

```
diff --git a/cql_prepared_test.py b/cql_prepared_test.py
index 210477c..dc48a05 100644
--- a/cql_prepared_test.py
+++ b/cql_prepared_test.py
@@ -14,7 +14,7 @@ class TestCQL(Tester):
         node1 = cluster.nodelist()[0]
         time.sleep(0.2)
 
-        session = self.patient_cql_connection(node1)
+        session = self.patient_cql_connection(node1,protocol_version=1)
         self.create_ks(session, 'ks', 1)
         return session
```

running this toward scylla will fail

running this toward cassandra passes

```
batch_preparation_test (cql_prepared_test.TestCQL) ... cluster ccm directory: /home/shlomi/.dtest/dtest-ANGddc
ERROR

======================================================================
ERROR: batch_preparation_test (cql_prepared_test.TestCQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/cql_prepared_test.py", line 35, in batch_preparation_test
    session.execute(pq, ['foo', 4])
  File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:27334)
    result = future.result()
  File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:65206)
    raise self._final_exception
InvalidRequest: code=2200 [Invalid query] message="Invalid amount of bind variables"
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-ANGddc
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 9.561s

FAILED (errors=1)
```

fails java_driver_test
  ProtocolV1Test.should_execute_prepared_statement_with_no_variables  ProtocolV1Test.should_execute_prepared_statement_with_variables

**Comment by penberg** [comment]
@slivne Is this scheduled for 1.3 and not on 1.4 on purpose?
