### ISSUE TITLE
Error parsing schema options

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1705]
Installation details
Scylla version (or git commit hash): 1.2.3-20160731
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS Linux version 3.10.0-327.10.1.el7.x86_64

We got an error from java client
Could you check this?
We use datastax java driver 2.1.7.1

[ERROR] 2016-09-26 01:28:46 Error parsing schema options for table spatch.raw_data: Cluster.getMetadata().getKeyspace("spatch").getTable("raw_data").getOptions() will return null
java.lang.IllegalArgumentException: Multiple entries with same key: class=SizeTieredCompactionStrategy and class=SizeTieredCompactionStrategy
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
        at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
        at com.datastax.driver.core.TableOptionsMetadata.<init>(TableOptionsMetadata.java:138)
        at com.datastax.driver.core.TableMetadata.build(TableMetadata.java:137)
        at com.datastax.driver.core.SchemaParser.buildTables(SchemaParser.java:176)
        at com.datastax.driver.core.SchemaParser.buildKeyspaces(SchemaParser.java:128)
        at com.datastax.driver.core.SchemaParser.refresh(SchemaParser.java:64)
        at com.datastax.driver.core.ControlConnection.refreshSchema(ControlConnection.java:341)
        at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:271)
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:199)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:77)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1420)
        at com.datastax.driver.core.Cluster.init(Cluster.java:162)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:333)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:283)
        at com.sds.medical.wellness.smartpatch.database.ScyllaConnector.connect(ScyllaConnector.java:256)
        at com.sds.medical.wellness.smartpatch.EdfToEcgConverter.main(EdfToEcgConverter.java:40)

**Comment by gleb-cloudius** [comment]
On Tue, Sep 27, 2016 at 03:39:03AM -0700, Junghyun Park wrote:
> Installation details
> Scylla version (or git commit hash): 1.2.3-20160731
> Cluster size: 3
> OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS Linux version 3.10.0-327.10.1.el7.x86_64
> 
> We got an error from java client
> Could you check this?
> 
What have you tried to do when you've got this error?

> 
> [ERROR] 2016-09-26 01:28:46 Error parsing schema options for table spatch.raw_data: Cluster.getMetadata().getKeyspace("spatch").getTable("raw_data").getOptions() will return null
> java.lang.IllegalArgumentException: Multiple entries with same key: class=SizeTieredCompactionStrategy and class=SizeTieredCompactionStrategy
Looks like it complains about class=SizeTieredCompactionStrategy been
present twice.
 
>         at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
>         at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
>         at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
>         at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
>         at com.datastax.driver.core.TableOptionsMetadata.<init>(TableOptionsMetadata.java:138)
>         at com.datastax.driver.core.TableMetadata.build(TableMetadata.java:137)
>         at com.datastax.driver.core.SchemaParser.buildTables(SchemaParser.java:176)
>         at com.datastax.driver.core.SchemaParser.buildKeyspaces(SchemaParser.java:128)
>         at com.datastax.driver.core.SchemaParser.refresh(SchemaParser.java:64)
>         at com.datastax.driver.core.ControlConnection.refreshSchema(ControlConnection.java:341)
>         at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:271)
>         at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:199)
>         at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:77)
>         at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1420)
>         at com.datastax.driver.core.Cluster.init(Cluster.java:162)
>         at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:333)
>         at com.datastax.driver.core.Cluster.connect(Cluster.java:283)
>         at com.sds.medical.wellness.smartpatch.database.ScyllaConnector.connect(ScyllaConnector.java:256)
>         at com.sds.medical.wellness.smartpatch.EdfToEcgConverter.main(EdfToEcgConverter.java:40)
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/1705

--
			Gleb.

**Comment by slivne** [comment]
you may be hitting https://github.com/scylladb/scylla/issues/1538 that was
fixed and is part of the 1.3 release

to verify that you can connect with cqlsh and run

cqlsh:> SELECT compaction_strategy_class, compaction_strategy_options
FROM system.schema_columnfamilies WHERE keyspace_name = 'spatch';

and check the output.

**Comment by infordb** [comment]
@slivne 


cqlsh> SELECT columnfamily_name,compaction_strategy_class, compaction_strategy_options
   ... FROM system.schema_columnfamilies WHERE keyspace_name = 'spatch';

 columnfamily_name | compaction_strategy_class    | compaction_strategy_options
-------------------+------------------------------+------------------------------------------
   beat_annotation | SizeTieredCompactionStrategy |                                       {}
          raw_data | SizeTieredCompactionStrategy | {"class":"SizeTieredCompactionStrategy"}
 rhythm_annotation | SizeTieredCompactionStrategy |                                       {}
          sampling | SizeTieredCompactionStrategy |                                       {}
         trenddata | SizeTieredCompactionStrategy |                                       {}

(5 rows)

**Comment by slivne** [comment]
@infordb you are hitting #1538 - to resolve this please upgrade to 1.3.1
