### ISSUE TITLE
cassandra-stress with snappy compression is not working with scylla

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1711]
*Installation details*
Scylla version (or git commit hash):  master (3057ca05bc80ef3e3795c9a4b26af36bc8129745)
Cluster size: 1

to reproduce

```
ccm create scylla-1 --scylla --vnodes -n 1 --install-dir=
ccm node1 stress write n=1000 -mode cql3 native compression=snappy
```

does not work 

```
INFO  14:50:56 Found Netty's native epoll transport in the classpath, using it
Exception in thread "main" java.lang.RuntimeException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.OperationTimedOutException: [/127.0.0.1:9042] Operation timed out))
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:198)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:205)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:55)
	at org.apache.cassandra.stress.Stress.main(Stress.java:109)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.OperationTimedOutException: [/127.0.0.1:9042] Operation timed out))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:240)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1429)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:402)
	at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:121)
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:189)
	... 5 more

```

trying the same with cassandra it work

trying the same with lz4 works

lets add a regression test to check that snappy and ;z4 are working using cassandra-stress - it should be simple.

**Comment by penberg** [comment]
We need to fix it for 1.4 or disable snappy support.
