### ISSUE TITLE
SIGSEGV inside size estimates recorder

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1804]
*Installation details*
Scylla version (or git commit hash): a35136533d9fb080979f4cdacfde02935d63aad2 (master)
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): F23

Easy to reproduce. Scenario:

```
cassandra-stress read -pop dist=uniform\(1..1000000\) &
kill -SIGSTOP $scylla_pid
sleep 10
kill -SIGCONT $scylla_pid
```

```
(gdb) bt
#0  0x000000000079b794 in managed_bytes::size (this=0x600008f972d0) at ./utils/managed_bytes.hh:333
#1  managed_bytes::managed_bytes (this=0x600008f70a70, o=...) at ./utils/managed_bytes.hh:211
#2  0x00000000012f857e in dht::token::token (this=0x600008f70a68) at ./dht/i_partitioner.hh:74
#3  db::estimates_for (cf=..., local_ranges=...) at db/size_estimates_recorder.cc:85
#4  0x00000000012fa593 in db::size_estimates_recorder::record_size_estimates()::{lambda()#2}::operator()() const::{lambda()#1}::operator()() const [clone .isra.798] () at db/size_estimates_recorder.cc:127
#5  0x00000000012fc552 in apply_helper<db::size_estimates_recorder::record_size_estimates()::<lambda()>::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (func=<optimized out>, args=<optimized out>) at ./seastar/core/apply.hh:34
#6  apply<db::size_estimates_recorder::record_size_estimates()::<lambda()>::<lambda()> > (func=<optimized out>, 
    args=<optimized out>) at ./seastar/core/apply.hh:42
#7  do_void_futurize_apply_tuple<db::size_estimates_recorder::record_size_estimates()::<lambda()>::<lambda()> > (
    func=<optimized out>, args=<optimized out>) at ./seastar/core/future.hh:1235
#8  futurize<void>::apply<db::size_estimates_recorder::record_size_estimates()::<lambda()>::<lambda()> > (func=<optimized out>, 
    args=<optimized out>) at ./seastar/core/future.hh:1255
#9  seastar::<lambda(seastar::async(seastar::thread_attributes, Func&&, Args&& ...) [with Func = db::size_estimates_recorder::record_size_estimates()::<lambda()>::<lambda()>; Args = {}; futurize_t<typename std::result_of<typename std::decay<_Tp>::type(std::decay_t<Args>...)>::type> = future<>]::work&)>::<lambda()>::operator() (__closure=<optimized out>)
    at /home/tgrabiec/src/scylla/seastar/core/thread.hh:308
#10 std::_Function_handler<void(), seastar::async(seastar::thread_attributes, Func&&, Args&& ...)::<lambda(seastar::async(seastar::thread_attributes, Func&&, Args&& ...)::work&)> mutable [with Func = db::size_estimates_recorder::record_size_estimates()::<lambda()>::<lambda()>; Args = {}]::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/5.3.1/functional:1871
#11 0x000000000041bd3e in std::function<void ()>::operator()() const (this=0x600008c60810)
    at /usr/include/c++/5.3.1/functional:2271
#12 seastar::thread_context::main (this=0x600008c60800) at core/thread.cc:198
#13 0x0000000000552362 in seastar::thread_context::s_main (lo=<optimized out>, hi=<optimized out>) at core/thread.cc:189
#14 0x00007f2fbff4df20 in ?? () from /lib64/libc.so.6
#15 0x0000000000000000 in ?? ()

```

**Comment by avikivity** [comment]
checking
