### ISSUE TITLE
CL=1 reads fail even though there is one node alive

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1828]
*Installation details*
Scylla version (or git commit hash): 0f1ba1a3bb566904378d65f83a4670d30aedaf20
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI):

1 node alive, 1 node down.

```
cqlsh> select * from keyspace1.standard1 ;
Traceback (most recent call last):
  File "/usr/bin/cqlsh", line 1078, in perform_simple_statement
    rows = self.session.execute(statement, trace=self.tracing_enabled)
  File "/usr/share/scylla/cassandra/lib/cassandra-driver-internal-only-2.6.0c2.post.zip/cassandra-driver-2.6.0c2.post/cassandra/cluster.py", line 1594, in execute
    result = future.result(timeout)
  File "/usr/share/scylla/cassandra/lib/cassandra-driver-internal-only-2.6.0c2.post.zip/cassandra-driver-2.6.0c2.post/cassandra/cluster.py", line 3296, in result
    raise self._final_exception
Unavailable: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl ONE. Requires 1, alive 0" info={'required_replicas': 1, 'alive_replicas': 0, 'consistency': 'ONE'}

```

```
TRACE 2016-11-09 15:57:31,713 [shard 1] storage_proxy - query keyspace1.standard1 cmd=read_command{cf_id=ce842e80-a598-11e6-9b6b-000000000001, version=9d8c6479-7378-3892-b1b5-4abe630bfed6, slice={regular_cols=[0, 1, 2, 3, 4], static_cols=[], rows=[(-inf, +inf)], options=2, cql_format=3, partition_row_limit=4294967295}, limit=100, timestamp=1478703451}, partition_limit=4294967295}, ranges={(-inf, +inf)}, id=15
DEBUG 2016-11-09 15:57:31,713 [shard 1] storage_proxy - Estimated result rows per range: 0.9; requested rows: 100, ranges.size(): 513; concurrent range requests: 112
TRACE 2016-11-09 15:57:31,713 [shard 1] storage_proxy - creating range read executor with targets {127.0.0.1}
TRACE 2016-11-09 15:57:31,713 [shard 1] storage_proxy - creating range read executor with targets {}
DEBUG 2016-11-09 15:57:31,713 [shard 1] consistency - Live nodes 0 do not satisfy ConsistencyLevel (1 required, 0 pending)
```

**Comment by tgrabiec** [comment]
False alarm
