### ISSUE TITLE
Scylla core dump with AMI 1.4.1

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1835]
*Installation details*
Scylla version (or git commit hash): 1.4.1
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI, c3.xlarge

Reproduce
* Launching 2 node cluster
* Launching 6 loaders (also c3.xlarge)
* run `cassandra-stress write` from each loader

logs, coredump uploaded to s3 `scylladb-users-upload.s3.amazonaws.com/a72cb5c1-37e5-4ecf-82b3-bb5c9be4ed9d/`

relevant part of the log below
```
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka
-7-Data.db:level=0, /var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-11-Data.db:level=0, /var/lib/scylla/data/system/schema_keysp
aces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-15-Data.db:level=0, /var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspace
s-ka-19-Data.db:level=0, ]
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema
_keyspaces-ka-23-Data.db:level=0, ]. 752 bytes to 188 (~25% of original) in 123ms = 0.00145765MB/s. ~1024 total partitions merged to 1.
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 0] schema_tables - Creating system_traces.node_slow_log id=78822410-a73c-11e6-8ebd-000000000000 version=8b3f1828-1cac-3f70-abf4-2fa6
48991039
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 0] database - Setting compaction strategy of system_traces.node_slow_log to SizeTieredCompactionStrategy
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 3] database - Setting compaction strategy of system_traces.node_slow_log to SizeTieredCompactionStrategy
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 1] database - Setting compaction strategy of system_traces.node_slow_log to SizeTieredCompactionStrategy
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 2] database - Setting compaction strategy of system_traces.node_slow_log to SizeTieredCompactionStrategy
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 0] database - Schema version changed to 1e1119ce-bccf-3fc9-9640-7ae38b97a087
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 0] storage_service - Starting listening for CQL clients on 0.0.0.0:9042...
Nov 10 11:54:44 ip-172-31-41-0 scylla[2133]:  [shard 0] storage_service - Thrift server listening on 0.0.0.0:9160 ...
Nov 10 11:54:44 ip-172-31-41-0 scylla-jmx[2142]: service:jmx:rmi://localhost/jndi/rmi://localhost:7199/jmxrmi
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: scylla-jmx.service: main process exited, code=exited, status=143/n/a
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: Unit scylla-jmx.service entered failed state.
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: scylla-jmx.service failed.
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 0] compaction_manager - Asked to stop
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 0] compaction_manager - Stopped
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 1] compaction_manager - Asked to stop
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 1] compaction_manager - Stopped
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 2] compaction_manager - Asked to stop
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 2] compaction_manager - Stopped
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 3] compaction_manager - Asked to stop
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 3] compaction_manager - Stopped
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 0] storage_service - Drain on shutdown: starts
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 0] storage_service - Stop transport: starts
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 0] gossip - My status = NORMAL
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 0] gossip - Announcing shutdown
Nov 10 12:10:14 ip-172-31-41-0 scylla[2133]:  [shard 0] storage_service - Node 172.31.41.0 state jump to normal
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: Segmentation fault on shard 0.
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: Backtrace:
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x00000000004e2e6a
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x00000000004e2f13
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x00007f770fa110ff
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x00000000005929ff
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x000000000067da41
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x000000000067f45f
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x000000000051a5cf
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x000000000051b147
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x00000000004e18d4
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x000000000052f89d
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x000000000059b26c
Nov 10 12:10:16 ip-172-31-41-0 scylla[2133]: 0x000000000047637c
Nov 10 12:10:17 ip-172-31-41-0 scylla[2133]: 0x00007f770f661b14
Nov 10 12:10:17 ip-172-31-41-0 scylla[2133]: 0x00000000004dffa0
Nov 10 12:10:17 ip-172-31-41-0 scylla[2133]: 0xffffffffffffffff
Nov 10 12:10:17 ip-172-31-41-0 kernel: scylla[2133]: segfault at 8 ip 0000000000592a00 sp 00007ffc534a0c60 error 4 in scylla[400000+1d16000]
Nov 10 12:10:39 ip-172-31-41-0 systemd[1]: scylla-server.service: main process exited, code=dumped, status=11/SEGV
Nov 10 12:10:39 ip-172-31-41-0 systemd[1]: Unit scylla-server.service entered failed state.
Nov 10 12:10:39 ip-172-31-41-0 systemd[1]: scylla-server.service failed.
Nov 10 12:11:15 ip-172-31-41-0 systemd-coredump[2609]: Process 2133 (scylla) of user 994 dumped core.
                                                       #0  0x0000000000592a00 _ZN9scollectd13get_value_mapEv (scylla)
                                                       #1  0x000000000067da42 operator() (scylla)
                                                       #2  0x000000000067f460 process (scylla)
                                                       #3  0x000000000051a5d0 operator() (scylla)
                                                       #4  0x000000000051b148 _ZN17smp_message_queue16process_incomingEv (scylla)
                                                       #5  0x00000000004e18d5 _ZN7reactor9poll_onceEv (scylla)
                                                       #6  0x000000000052f89e _ZNKSt8functionIFbvEEclEv (scylla)
                                                       #7  0x000000000059b26d _ZN12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
                                                       #8  0x000000000047637d main (scylla)
                                                       #10 0x00000000004dffa1 _start (scylla)
                                                       #1  0x00000000004e5376 _ZN11thread_pool4workEv (scylla)
                                                       #2  0x000000000056f6de _ZNKSt8functionIFvvEEclEv (scylla)
                                                       #1  0x00000000004e5376 _ZN11thread_pool4workEv (scylla)
                                                       #2  0x000000000056f6de _ZNKSt8functionIFvvEEclEv (scylla)
                                                       #1  0x00000000004e5376 _ZN11thread_pool4workEv (scylla)
                                                       #2  0x000000000056f6de _ZNKSt8functionIFvvEEclEv (scylla)
                                                       #1  0x00000000004e5376 _ZN11thread_pool4workEv (scylla)
                                                       #2  0x000000000056f6de _ZNKSt8functionIFvvEEclEv (scylla)
                                                       #1  0x00000000004f106b _ZN21reactor_backend_epoll16wait_and_processEiPK10__sigset_t (scylla)
                                                       #2  0x00000000004f11e1 _ZN7reactor16wait_and_processEiPK10__sigset_t (scylla)
                                                       #3  0x000000000052fcf1 _ZN7reactor3runEv (scylla)
                                                       #4  0x000000000053b879 _ZZN3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv.constprop.3327 (scylla)
                                                       #5  0x000000000056f6de _ZNKSt8functionIFvvEEclEv (scylla)
                                                       #1  0x00000000004f106b _ZN21reactor_backend_epoll16wait_and_processEiPK10__sigset_t (scylla)
                                                       #2  0x00000000004f11e1 _ZN7reactor16wait_and_processEiPK10__sigset_t (scylla)
                                                       #3  0x000000000052fcf1 _ZN7reactor3runEv (scylla)
                                                       #4  0x000000000053b879 _ZZN3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv.constprop.3327 (scylla)
                                                       #5  0x000000000056f6de _ZNKSt8functionIFvvEEclEv (scylla)
                                                       #1  0x00000000004f106b _ZN21reactor_backend_epoll16wait_and_processEiPK10__sigset_t (scylla)
                                                       #2  0x00000000004f11e1 _ZN7reactor16wait_and_processEiPK10__sigset_t (scylla)
                                                       #3  0x000000000052fcf1 _ZN7reactor3runEv (scylla)
                                                       #4  0x000000000053b879 _ZZN3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv.constprop.3327 (scylla)
                                                       #5  0x000000000056f6de _ZNKSt8functionIFvvEEclEv (scylla)
```

**Comment by slivne** [comment]
It seems that scylla-jmx failed/stopped and only then did scylla tried to
shutdown and crashed - did you do any jmx operation ?

**Comment by tzach** [comment]
As part of cleaning up a node between tests I did:

1. stop scylla service-server
2. clean data dir
3. restart scylla service-server
4. restart scylla-jmx

**Comment by slivne** [comment]
if we had the complete log of the node we may be able to understand at what
point this happened

**Comment by tzach** [comment]
@slivne I upload it to s3, see above

**Comment by slivne** [comment]
looking at the log it seems this happens when you try to clean the data

the first line is an ansible command
```
Nov 10 12:10:14 ip-172-31-41-0 sudo[2588]:   centos : TTY=pts/0 ; PWD=/home/centos ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kgjiutlhxopzhnnfpzauqtytiwrtbvkt; LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/py
thon /home/centos/.ansible/tmp/ansible-tmp-1478779810.79-71341194442052/service; rm -rf "/home/centos/.ansible/tmp/ansible-tmp-1478779810.79-71341194442052/" > /dev/null 2>&1
```

following it there is a stop of hourkeeping + jmx 

```
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: Stopped Run Scylla Housekeeping daily.
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: Stopping Run Scylla Housekeeping daily.
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: Stopping Scylla JMX...
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: scylla-jmx.service: main process exited, code=exited, status=143/n/a
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: Stopped Scylla JMX.
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: Unit scylla-jmx.service entered failed state.
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: scylla-jmx.service failed.
Nov 10 12:10:14 ip-172-31-41-0 systemd[1]: Stopping Scylla Server...
```

I downloaded the complete log and in it I could not find a reference to a created keyspace / table - so I think this aligns with the case that this happens when you clean the old data.


I tried also to open the coredumps you have uploaded and failed

```
[centos@ip-10-149-175-123 ~]$ /opt/scylladb/bin/gdb /usr/bin/scylla core.scylla.994
GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...../../gdb/cp-support.c:1595: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE5_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
Attempting to dump core.
../../gdb/cp-support.c:1608: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE5_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) n

This is a bug, please report it.  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.

done.
done.
"/home/centos/core.scylla.994" is not a core dump: File format not recognized
```

**Comment by tzach** [comment]
there are two files, core.scylla.994, core.scylla.994.xz
both are compressed with xz

**Comment by tzach** [comment]
> looking at the log it seems this happens when you try to clean the data

Yes. The sequence is:
1. Stop Scylla
2. Clean the data
3. Restart Scylla
4. Restart JMX

Maybe 2 started before 1 was completed?

**Comment by slivne** [comment]
ok that did the trick :)

```
#0  scollectd::get_value_map () at core/scollectd.cc:905
#1  0x000000000067da42 in prometheus::<lambda(httpd::routes&)>::<lambda(std::unique_ptr<httpd::request, std::default_delete<httpd::request> >, std::unique_ptr<httpd::reply, std::default_delete<httpd::reply> >)>::<lambda(auto:30&)>::<lambda(auto:31)>::<lambda()>::operator() (__closure=<optimized out>) at core/prometheus.cc:122
#2  futurize<std::map<scollectd::type_instance_id, std::vector<scollectd::collectd_value, std::allocator<scollectd::collectd_value> >, std::less<scollectd::type_instance_id>, std::allocator<std::pair<scollectd::type_instance_id const, std::vector<scollectd::collectd_value, std::allocator<scollectd::collectd_value> > > > > >::apply<prometheus::start(httpd::http_server_control&, const prometheus::config&)::<lambda(httpd::routes&)>::<lambda(std::unique_ptr<httpd::request>, std::unique_ptr<httpd::reply>)>::<lambda(auto:30&)> mutable::<lambda(auto:31)> [with auto:31 = unsigned int; auto:30 = std::vector<std::map<scollectd::type_instance_id, std::vector<scollectd::collectd_value> > >]::<lambda()>&>(prometheus::<lambda(httpd::routes&)>::<lambda(std::unique_ptr<httpd::request, std::default_delete<httpd::request> >, std::unique_ptr<httpd::reply, std::default_delete<httpd::reply> >)>::<lambda(auto:30&)>::<lambda(auto:31)>::<lambda()> &) (func=...) at core/future.hh:1172
#3  0x000000000067f460 in smp_message_queue::async_work_item<prometheus::start(httpd::http_server_control&, const prometheus::config&)::<lambda(httpd::routes&)>::<lambda(std::unique_ptr<httpd::request>, std::unique_ptr<httpd::reply>)>::<lambda(auto:30&)> mutable::<lambda(auto:31)> [with auto:31 = unsigned int; auto:30 = std::vector<std::map<scollectd::type_instance_id, std::vector<scollectd::collectd_value> > >]::<lambda()> >::process(void) (this=<optimized out>) at core/reactor.hh:376
#4  0x000000000051a5d0 in smp_message_queue::<lambda(smp_message_queue::work_item*)>::operator() (wi=0x601000198ea0, __closure=<synthetic pointer>) at core/reactor.cc:2730
#5  smp_message_queue::process_queue<2ul, smp_message_queue::process_incoming()::<lambda(smp_message_queue::work_item*)> >(smp_message_queue::lf_queue &, smp_message_queue::<lambda(smp_message_queue::work_item*)>) (q=..., process=..., process@entry=..., this=0x60000034ca00) at core/reactor.cc:2703
#6  0x000000000051b148 in smp_message_queue::process_incoming (this=0x60000034ca00) at core/reactor.cc:2733
#7  smp::poll_queues () at core/reactor.cc:3322
#8  0x00000000004e18d5 in reactor::poll_once (this=<optimized out>) at core/reactor.cc:2445
#9  reactor::<lambda()>::operator() (__closure=0x7ffc534a15d0) at core/reactor.cc:2350
#10 std::_Function_handler<bool(), reactor::run()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /opt/scylladb/include/c++/5.3.1/functional:1857
#11 0x000000000052f89e in std::function<bool ()>::operator()() const (this=0x7ffc534a15d0) at /opt/scylladb/include/c++/5.3.1/functional:2271
#12 reactor::run (this=0x60000024d000) at core/reactor.cc:2373
#13 0x000000000059b26d in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7ffc534a1ea0, ac=ac@entry=17, av=av@entry=0x7ffc534a20e8, 
    func=func@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x761609, DIE 0x82bfba>) at core/app-template.cc:131
#14 0x000000000047637d in main (ac=17, av=0x7ffc534a20e8) at main.cc:663
```

**Comment by slivne** [comment]
@amnonh if this is closed please provide a reference to a commit

**Comment by slivne** [comment]
@amnonh can we close this

**Comment by penberg** [comment]
Yes, it's fixed by commit https://github.com/scylladb/seastar/commit/83549367df6936fe844c8a6635baeeac0505a427 in master, and by https://github.com/scylladb/scylla-seastar/commit/6fd4534d1598fb879b8fe17944dbf02ffb0a906c and https://github.com/scylladb/scylla-seastar/commit/c50a30142af707424125b79af1a008fd75e13b37 in 1.5 and 1.4.
