### ISSUE TITLE
scylla-ami-setup failed to join nodes to a cluster

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#1914]
Installation details
Scylla version (or git commit hash): 1.5.rc1-20161123.d58af7d
Cluster size: 3 nodes (i2.2xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS, ami-38c2f22f

*Description*
Create 3 nodes in AWS [1], assign `Number of instances` to 3,
but the 3 nodes can't join in same cluster all the time (100%).
Sometimes, two nodes join in a cluster, and one node fails.

I also try to re-run `sudo systemctl restart scylla-ami-setup`, it can join the failed node to a single cluster, sometimes it will fail again.

*Expected result*
scylla-ami-setup service can always setup/join 3 nodes to same cluster.

[1] https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1

```
@10.164.80.33, node1

● scylla-ami-setup.service - Scylla AMI Setup
   Loaded: loaded (/usr/lib/systemd/system/scylla-ami-setup.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-12-01 15:18:19 UTC; 57s ago
  Process: 791 ExecStart=/usr/lib/scylla/scylla-ami/scylla_ami_setup (code=exited, status=1/FAILURE)
 Main PID: 791 (code=exited, status=1/FAILURE)

Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: [INFO] 12/01/16-15:18:15 Reflector: Received 2 of 1 responses from: [u'10.113.219.220', u'10.97.217.200']
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: [INFO] 12/01/16-15:18:17 Reflector: Received 2 of 1 responses from: [u'10.113.219.220', u'10.97.217.200']
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: [ERROR] EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: Aborting the clustering of this reservation. Please try again.
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: Traceback (most recent call last):
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 485, in <module>
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: get_seed_list()
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 312, in get_seed_list
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: exit_path('EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.', '\n\nAborting the clustering of this reservation. Please try again.')
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 55, in exit_path
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: raise AttributeError(errorMsg)
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: AttributeError: EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.
Dec 01 15:18:19 ip-10-164-80-33 scylla_ami_setup[791]: Aborting the clustering of this reservation. Please try again.
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: Failed to start Scylla AMI Setup.
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: Dependency failed for Scylla Server.
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: Dependency failed for Scylla JMX.
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: Dependency failed for Run Scylla Housekeeping daily.
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: Job scylla-housekeeping.timer/start failed with result 'dependency'.
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: Job scylla-server.service/start failed with result 'dependency'.
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: Unit scylla-ami-setup.service entered failed state.
Dec 01 15:18:19 ip-10-164-80-33 systemd[1]: scylla-ami-setup.service failed.
```

```
@10.97.217.200, node2

● scylla-ami-setup.service - Scylla AMI Setup
   Loaded: loaded (/usr/lib/systemd/system/scylla-ami-setup.service; enabled; vendor preset: disabled)
   Active: active (exited) since Thu 2016-12-01 15:08:18 UTC; 11min ago
 Main PID: 791 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/scylla-ami-setup.service

Dec 01 15:08:18 ip-10-97-217-200 scylla_ami_setup[791]: [INFO] 12/01/16-15:08:18 Reflector: Received 1 of 1 responses from: [u'10.97.217.200']
Dec 01 15:08:18 ip-10-97-217-200 scylla_ami_setup[791]: [INFO] scylla.yaml configured.
Dec 01 15:08:18 ip-10-97-217-200 scylla_ami_setup[791]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dec 01 15:08:18 ip-10-97-217-200 scylla_ami_setup[791]: Dload  Upload   Total   Spent    Left  Speed
Dec 01 15:08:18 ip-10-97-217-200 scylla_ami_setup[791]: [155B blob data]
Dec 01 15:08:18 ip-10-97-217-200 scylla_ami_setup[791]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dec 01 15:08:18 ip-10-97-217-200 scylla_ami_setup[791]: Dload  Upload   Total   Spent    Left  Speed
Dec 01 15:08:18 ip-10-97-217-200 scylla_ami_setup[791]: [155B blob data]
Dec 01 15:08:18 ip-10-97-217-200 scylla_ami_setup[791]: kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e
Dec 01 15:08:18 ip-10-97-217-200 systemd[1]: Started Scylla AMI Setup.
```

```
@ 10.97.217.220 node3

● scylla-ami-setup.service - Scylla AMI Setup
   Loaded: loaded (/usr/lib/systemd/system/scylla-ami-setup.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-12-01 15:18:19 UTC; 1min 5s ago
  Process: 790 ExecStart=/usr/lib/scylla/scylla-ami/scylla_ami_setup (code=exited, status=1/FAILURE)
 Main PID: 790 (code=exited, status=1/FAILURE)

Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: [INFO] 12/01/16-15:18:14 Reflector: Received 2 of 1 responses from: [u'10.113.219.220', u'10.97.217.200']
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: [INFO] 12/01/16-15:18:16 Reflector: Received 2 of 1 responses from: [u'10.113.219.220', u'10.97.217.200']
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: [ERROR] EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: Aborting the clustering of this reservation. Please try again.
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: Traceback (most recent call last):
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 485, in <module>
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: get_seed_list()
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 312, in get_seed_list
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: exit_path('EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.', '\n\nAborting the clustering of this reservation. Please try again.')
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 55, in exit_path
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: raise AttributeError(errorMsg)
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: AttributeError: EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.
Dec 01 15:18:19 ip-10-113-219-220 scylla_ami_setup[790]: Aborting the clustering of this reservation. Please try again.
Dec 01 15:18:19 ip-10-113-219-220 systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
Dec 01 15:18:19 ip-10-113-219-220 systemd[1]: Failed to start Scylla AMI Setup.
Dec 01 15:18:19 ip-10-113-219-220 systemd[1]: Unit scylla-ami-setup.service entered failed state.
Dec 01 15:18:19 ip-10-113-219-220 systemd[1]: scylla-ami-setup.service failed.
```

**Comment by kongove** [comment]
You can search 'setup-test-amos' in us-east to find the 3 instances, if you want to access them, please contact with me.

**Comment by slivne** [comment]
@kongove hat is the user data you specified for the instance

https://github.com/scylladb/scylla/wiki/Using-AWS-AMI

**Comment by kongove** [comment]
I re-tested with right `user-data`, the cluster can be setup correctly.
So let's close this issue.

And the `user-data` is lacked in SCT, I will send a patch to add it.

**Comment by slivne** [comment]
I think the user-data is in SCT.

Can you also check the docs and ssee that we have the user data covered in
the AMI section.

On Tue, Dec 6, 2016 at 12:21 PM, Amos Jianjun Kong <notifications@github.com

**Comment by kongove** [comment]
```
--clustername scylla
--totalnodes 3
```

Above two parameters existed in SCT, '--reflector http://reflector.scylladb.com/reflector.php' is missing.
