### ISSUE TITLE
Scylla exits during population phase due to std::out_of_range (unable to reverse map)

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1922]
*Installation details*
Scylla version (or git commit hash): master

I guess that the problem is when starting Scylla with sstables without the new Scylla.db component.

@avikivity please confirm or refute.

```
(gdb) bt
#0  0x00007ffff7255b3d in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x00000000008c3121 in sstables::reverse_map<std::unordered_map<sstables::sstable::component_type, basic_sstring<char, unsigned int, 15u>, enum_hash<sstables::sstable::component_type> > > (value=..., map=std::unordered_map with 11 elements = {...})
    at sstables/sstables.cc:182
#2  0x000000000092f5a1 in sstables::sstable::component_from_sstring (s=...) at sstables/sstables.cc:2089
#3  sstables::entry_descriptor::make_descriptor (fname=...) at sstables/sstables.cc:2077
#4  0x000000000075a4d6 in column_family::probe_file (this=0x600000487808, sstdir=..., fname=...) at database.cc:812
#5  0x000000000075bac9 in column_family::<lambda(std::vector<future<>, std::allocator<future<> > >&)>::<lambda(directory_entry)>::operator() (de=<error reading variable: access outside bounds of object referenced via synthetic pointer>, __closure=0x6000007876f0)
    at database.cc:1533
#6  std::_Function_handler<future<>(directory_entry), column_family::populate(sstring)::<lambda(std::vector<future<> >&)>::<lambda(directory_entry)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/tgrabiec/src/scylla/build/release/scylla, CU 0x26c74f4, DIE 0x2ec09f2>) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/5.3.1/functional:1857
#7  0x00000000007b559e in std::function<future<> (directory_entry)>::operator()(directory_entry) const (
    __args#0=<error reading variable: access outside bounds of object referenced via synthetic pointer>, this=<optimized out>)
    at /usr/include/c++/5.3.1/functional:2267
#8  lister::_visit(directory_entry)::{lambda(directory_entry)#1}::operator()(directory_entry) const (de=..., __closure=<optimized out>)
    at database.cc:719
#9  apply_helper<lister::_visit(directory_entry)::{lambda(directory_entry)#1}, std::tuple<directory_entry>&&, std::integer_sequence<unsigned long, 0ul> >::apply({lambda(directory_entry)#1}&&, std::tuple<directory_entry>) (
    args=<unknown type in /home/tgrabiec/src/scylla/build/release/scylla, CU 0x26c74f4, DIE 0x2c999d9>, func=<optimized out>)
    at /home/tgrabiec/src/scylla/seastar/core/apply.hh:34
#10 apply<lister::_visit(directory_entry)::{lambda(directory_entry)#1}, directory_entry>(lister::_visit(directory_entry)::{lambda(directory_entry)#1}&&, std::tuple<directory_entry>&&) (args=<optimized out>, func=<optimized out>)
    at /home/tgrabiec/src/scylla/seastar/core/apply.hh:42
#11 futurize<future<> >::apply<lister::_visit(directory_entry)::{lambda(directory_entry)#1}, directory_entry>(lister::_visit(directory_entry)::{lambda(directory_entry)#1}&&, std::tuple<directory_entry>&&) (
    args=<unknown type in /home/tgrabiec/src/scylla/build/release/scylla, CU 0x26c74f4, DIE 0x2c999a7>, func=<optimized out>)
    at /home/tgrabiec/src/scylla/seastar/core/future.hh:1267
#12 _ZZN6futureIJ15directory_entryEE4thenIZN6lister6_visitES0_EUlS0_E_S_IJEEEET0_OT_ENUlS8_E_clI12future_stateIJS0_EEEEDaS8_ (
    state=<unknown type in /home/tgrabiec/src/scylla/build/release/scylla, CU 0x26c74f4, DIE 0x2be3f5e>, __closure=0x600000791848)
    at /home/tgrabiec/src/scylla/seastar/core/future.hh:872
#13 _ZN12continuationIZN6futureIJ15directory_entryEE4thenIZN6lister6_visitES1_EUlS1_E_S0_IJEEEET0_OT_EUlS9_E_JS1_EE3runEv (
    this=0x600000791820) at /home/tgrabiec/src/scylla/seastar/core/future.hh:390
#14 0x000000000048bc00 in reactor::run_tasks (this=this@entry=0x600000413000, tasks=...) at core/reactor.cc:1998
#15 0x00000000004d3afb in reactor::run (this=0x600000413000) at core/reactor.cc:2453
#16 0x0000000000553e7c in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffdbd0, 
    ac=ac@entry=11, av=av@entry=0x7fffffffde48, 
    func=func@entry=<unknown type in /home/tgrabiec/src/scylla/build/release/scylla, CU 0x91c06f, DIE 0xa0c52d>)
    at core/app-template.cc:131
#17 0x000000000041d461 in main (ac=11, av=0x7fffffffde48) at main.cc:667
```

```
(gdb) p value
$1 = (const std::unordered_map<sstables::sstable::component_type, basic_sstring<char, unsigned int, 15u>, enum_hash<sstables::sstable::component_type>, std::equal_to<sstables::sstable::component_type>, std::allocator<std::pair<sstables::sstable::component_type const, basic_sstring<char, unsigned int, 15u> > > >::mapped_type &) @0x7fffffffc6f0: {u = {external = {
      str = 0x642e616c6c796353 <error: Cannot access memory at address 0x642e616c6c796353>, size = 720994, pad = 0 '\000'}, 
    internal = {str = "Scylla.db\000\v\000\000`", size = 9 '\t'}}, static npos = 4294967295}

(gdb) p map
$2 = std::unordered_map with 11 elements = {[sstables::sstable::component_type::TemporaryStatistics] = {u = {external = {
        str = 0x600000058b40 "Statistics.db.tmp", size = 17, pad = 0 '\000'}, internal = {
        str = "@\213\005\000\000`\000\000\021\000\000\000\000\000", size = -1 '\377'}}, static npos = 4294967295}, 
  [sstables::sstable::component_type::Index] = {u = {external = {
        str = 0x62642e7865646e49 <error: Cannot access memory at address 0x62642e7865646e49>, size = 4294958592, pad = -1 '\377'}, 
      internal = {str = "Index.db\000\336\377\377\377\177", size = 8 '\b'}}, static npos = 4294967295}, 
  [sstables::sstable::component_type::CompressionInfo] = {u = {external = {str = 0x600000058b54 "CompressionInfo.db", size = 18, 
        pad = 0 '\000'}, internal = {str = "T\213\005\000\000`\000\000\022\000\000\000\000\000", size = -1 '\377'}}, 
    static npos = 4294967295}, [sstables::sstable::component_type::Data] = {u = {external = {
        str = 0x62642e61746144 <error: Cannot access memory at address 0x62642e61746144>, size = 29, pad = 0 '\000'}, internal = {
        str = "Data.db\000\035\000\000\000\000\000", size = 7 '\a'}}, static npos = 4294967295}, 
  [sstables::sstable::component_type::TOC] = {u = {external = {
        str = 0x7478742e434f54 <error: Cannot access memory at address 0x7478742e434f54>, size = 0, pad = 0 '\000'}, internal = {
        str = "TOC.txt\000\000\000\000\000\000\000", size = 7 '\a'}}, static npos = 4294967295}, 
  [sstables::sstable::component_type::Summary] = {u = {external = {
        str = 0x2e7972616d6d7553 <error: Cannot access memory at address 0x2e7972616d6d7553>, size = 25188, pad = 0 '\000'}, 
      internal = {str = "Summary.db\000\000\000\000", size = 10 '\n'}}, static npos = 4294967295}, 
  [sstables::sstable::component_type::Digest] = {u = {external = {
        str = 0x732e747365676944 <error: Cannot access memory at address 0x732e747365676944>, size = 3236200, pad = 0 '\000'}, 
      internal = {str = "Digest.sha1\000\000\000", size = 11 '\v'}}, static npos = 4294967295}, 
  [sstables::sstable::component_type::CRC] = {u = {external = {str = 0x62642e435243 "", size = 4085184024, pad = -1 '\377'}, 
      internal = {str = "CRC.db\000\000\030\366~\363\377\177", size = 6 '\006'}}, static npos = 4294967295}, 
  [sstables::sstable::component_type::Filter] = {u = {external = {
        str = 0x642e7265746c6946 <error: Cannot access memory at address 0x642e7265746c6946>, size = 5439586, pad = 0 '\000'}, 
      internal = {str = "Filter.db\000S\000\000\000", size = 9 '\t'}}, static npos = 4294967295}, 
  [sstables::sstable::component_type::Statistics] = {u = {external = {
        str = 0x6974736974617453 <error: Cannot access memory at address 0x6974736974617453>, size = 1680765795, pad = 98 'b'}, 
      internal = {str = "Statistics.db\000", size = 13 '\r'}}, static npos = 4294967295}, 
  [sstables::sstable::component_type::TemporaryTOC] = {u = {external = {
        str = 0x2e7478742e434f54 <error: Cannot access memory at address 0x2e7478742e434f54>, size = 7368052, pad = 0 '\000'}, 
      internal = {str = "TOC.txt.tmp\000\000\000", size = 11 '\v'}}, static npos = 4294967295}}

```

```
WARN  2016-12-08 13:05:31,976 [shard 0] seastar - Exceptional future ignored: std::out_of_range (unable to reverse map)
WARN  2016-12-08 13:05:31,976 [shard 0] seastar - Exceptional future ignored: std::out_of_range (unable to reverse map)
ERROR 2016-12-08 13:05:31,977 [shard 0] database - Exception while populating keyspace 'system' with column family 'compaction_history' from file '/home/tgrabiec/.ccm/scylla-2/node1/data//system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca': std::out_of_range (unable to reverse map)
ERROR 2016-12-08 13:05:31,977 [shard 0] database - Exception while populating keyspace 'system' with column family 'local' from file '/home/tgrabiec/.ccm/scylla-2/node1/data//system/local-7ad54392bcdd35a684174e047860b377': std::out_of_range (unable to reverse map)
INFO  2016-12-08 13:05:31,977 [shard 0] sstable - Unrecognized TOC component was found: Scylla.db in sstable /home/tgrabiec/.ccm/scylla-2/node1/data//system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-161-TOC.txt
WARN  2016-12-08 13:05:31,977 [shard 0] seastar - Exceptional future ignored: std::out_of_range (unable to reverse map)
ERROR 2016-12-08 13:05:31,977 [shard 0] database - Exception while populating keyspace 'system' with column family 'schema_columnfamilies' from file '/home/tgrabiec/.ccm/scylla-2/node1/data//system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697': std::out_of_range (unable to reverse map)
WARN  2016-12-08 13:05:31,979 [shard 0] seastar - Exceptional future ignored: std::out_of_range (unable to reverse map)
ERROR 2016-12-08 13:05:31,979 [shard 0] database - Exception while populating keyspace 'system' with column family 'schema_columns' from file '/home/tgrabiec/.ccm/scylla-2/node1/data//system/schema_columns-296e9c049bec3085827dc17d3df2122a': std::out_of_range (unable to reverse map)
INFO  2016-12-08 13:05:31,981 [shard 0] sstable - Unrecognized TOC component was found: Scylla.db in sstable /home/tgrabiec/.ccm/scylla-2/node1/data//system/schema_usertypes-3aa752254f82350b8d5c430fa221fa0a/system-schema_usertypes-ka-141-TOC.txt
WARN  2016-12-08 13:05:31,981 [shard 0] seastar - Exceptional future ignored: std::out_of_range (unable to reverse map)
ERROR 2016-12-08 13:05:31,981 [shard 0] database - Exception while populating keyspace 'system' with column family 'peers' from file '/home/tgrabiec/.ccm/scylla-2/node1/data//system/peers-37f71aca7dc2383ba70672528af04d4f': std::out_of_range (unable to reverse map)
WARN  2016-12-08 13:05:31,982 [shard 0] seastar - Exceptional future ignored: std::out_of_range (unable to reverse map)
ERROR 2016-12-08 13:05:31,982 [shard 0] database - Exception while populating keyspace 'system' with column family 'schema_triggers' from file '/home/tgrabiec/.ccm/scylla-2/node1/data//system/schema_triggers-0359bc7171233ee19a4ab9dfb11fc125': std::out_of_range (unable to reverse map)
WARN  2016-12-08 13:05:31,985 [shard 0] seastar - Exceptional future ignored: std::out_of_range (unable to reverse map)
ERROR 2016-12-08 13:05:31,985 [shard 0] database - Exception while populating keyspace 'system' with column family 'schema_usertypes' from file '/home/tgrabiec/.ccm/scylla-2/node1/data//system/schema_usertypes-3aa752254f82350b8d5c430fa221fa0a': std::out_of_range (unable to reverse map)
WARN  2016-12-08 13:05:31,986 [shard 0] seastar - Exceptional future ignored: std::out_of_range (unable to reverse map)
ERROR 2016-12-08 13:05:31,986 [shard 0] database - Exception while populating keyspace 'system' with column family 'schema_keyspaces' from file '/home/tgrabiec/.ccm/scylla-2/node1/data//system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676': std::out_of_range (unable to reverse map)
ERROR 2016-12-08 13:05:31,996 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Exception while populating keyspace 'system' with column family 'compaction_history' from file '/home/tgrabiec/.ccm/scylla-2/node1/data//system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca': std::out_of_range (unable to reverse map))
INFO  2016-12-08 13:05:31,996 [shard 0] compaction_manager - Asked to stop
INFO  2016-12-08 13:05:31,996 [shard 0] compaction_manager - Stopped
```

**Comment by avikivity** [comment]
Most likely, taking a look.

**Comment by avikivity** [comment]
@tgrabiec, can't reproduce; maybe it's due to a missing component in Statistics.db, from the previous implementation?

**Comment by avikivity** [comment]
@tgrabiec you'd expect that exception when running old Scylla with a new component, but not to exit.  I'll try to get it to crash like that.

**Comment by avikivity** [comment]
yup

/cc @raphaelsc

**Comment by avikivity** [comment]
patch posted
