### ISSUE TITLE
cqlsh is unable to parse tracing data

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#2079]
*Installation details*
Scylla version (or git commit hash): 8b1d34f39dc3296186470081eb90ce4c8ff18706

When executing a query with tracing enabled cqlsh fails to parse the received response.
```
cqlsh> tracing on;
Now Tracing is enabled
cqlsh> select * from ks.cf;
Traceback (most recent call last):
  File "./bin/cqlsh", line 1078, in perform_simple_statement
    rows = self.session.execute(statement, trace=self.tracing_enabled)
  File "/home/pdziepak/scylla-tools-java/bin/../lib/cassandra-driver-internal-only-2.7.2-2fc8a2b.zip/cassandra-driver-2.7.2-2fc8a2b/cassandra/cluster.py", line 1602, in execute
    result = future.result()
  File "/home/pdziepak/scylla-tools-java/bin/../lib/cassandra-driver-internal-only-2.7.2-2fc8a2b.zip/cassandra-driver-2.7.2-2fc8a2b/cassandra/cluster.py", line 3347, in result
    raise self._final_exception
ValueError: invalid size in header: 0xca783dc0

Statement trace did not complete within 10 seconds
```

This happens both with cqlsh from an old version of scylla-tools-java (before the build was broken) as well as upstream.

Tracing events are written to `system_traces.events`.

**Comment by tzach** [comment]
@vladzcloudius ?

**Comment by vladzcloudius** [comment]
@pdziepak Could you provide the exact stepts to reproduce the issue?

**Comment by pdziepak** [comment]
Looks like my setup is horribly broken and cqlsh is doing something weird. No idea what exactly it is yet, but it is not scylla or scylla-tools-java problem, so closing the issue.
