### ISSUE TITLE
datastax is mention in our errors/exceptions

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#2092]
*Installation details*
Version: 1.6
Cluster size: 3 nodes on GCE (4 vCPU, 15GB RAM)
OS: RHEL (manually installed, not via AMI)
2 Standard persistent disk, 20 GB each disk = 40GB per node

Ran Cassandra stress test and filled-up the cluster's capacity, over 90%. 2 nodes went into DN (Down-Normal) state. Tried to initiate reads and got the following error - why do we mention datastax in our errors?

[root@tomer-2cpu-8gb-centos7-loader ~]# cassandra-stress read n=5 -node 10.240.0.26,10.240.0.27,10.240.0.28
Sleeping 2s...
Running with 4 threadCount
Running READ with 4 threads for 5 iteration
INFO  13:46:53 Found Netty's native epoll transport in the classpath, using it
Failed to connect over JMX; not collecting these stats
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
INFO  13:46:53 Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO  13:46:53 New Cassandra host /10.240.0.26:9042 added
INFO  13:46:53 New Cassandra host /10.240.0.27:9042 added
INFO  13:46:53 New Cassandra host /10.240.0.28:9042 added
Connected to cluster: Tomer Cluster
Datatacenter: datacenter1; Host: /10.240.0.26; Rack: rack1
Datatacenter: datacenter1; Host: /10.240.0.27; Rack: rack1
Datatacenter: datacenter1; Host: /10.240.0.28; Rack: rack1
WARN  13:46:54 Error creating pool to /10.240.0.28:9042
com.**_datastax_**.driver.core.ConnectionException: [/10.240.0.28:9042] Pool was closed during initialization
        at com.datastax.driver.core.HostConnectionPool$2.onSuccess(HostConnectionPool.java:147) [cassandra-driver-core-2.1.9.jar:na]
        at com.datastax.driver.core.HostConnectionPool$2.onSuccess(HostConnectionPool.java:133) [cassandra-driver-core-2.1.9.jar:na]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1181) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture.setOneValue(Futures.java:1626) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture.access$400(Futures.java:1470) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture$2.run(Futures.java:1548) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$FallbackFuture$1$1.onSuccess(Futures.java:475) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1181) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:102) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1184) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:472) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1172) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$FallbackFuture$1$1.onFailure(Futures.java:483) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1172) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.add(ExecutionList.java:101) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:170) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1184) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:472) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1172) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:857) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202) [guava-16.0.jar:na]
        at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68) [guava-16.0.jar:na]
        at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:162) [cassandra-driver-core-2.1.9.jar:na]
        at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:145) [cassandra-driver-core-2.1.9.jar:na]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.fulfillConnectPromise(EpollSocketChannel.java:579) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.finishConnect(EpollSocketChannel.java:604) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:621) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.23.Final.jar:4.0.23.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.240.0.27:9042 (com.**datastax**.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_ONE (1 required but only 0 alive)))
.
.
.
java.io.IOException: Operation x10 on key(s) [4f384c4b37394c4f3631]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (tried: /10.240.0.27:9042 (com.**_datastax_**.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_ONE (1 required but only 0 alive)))

**Comment by manigandham** [comment]
Datastax makes many of the official client drivers for Cassandra, and since Scylla is wire-compatible with Cassandra, using the datastax drivers makes sense. Is ScyllaDB planning on creating new client drivers?

This particular issue is shown at the end -  there were no replicas found, so the driver threw an error that bubbled up.

**Comment by avikivity** [comment]
@manigandham there are no plans for new drivers at present, though I'm itching to write a seastar-based driver

**Comment by avikivity** [comment]
Not a bug, the Java driver was written by DataStax and has their name in the code.
