### ISSUE TITLE
ubuntu: scylla_setup  - No module named 'pyudev'

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2315]
*Installation details*
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/f3609fc8134eb6a73392f2f8bcc399647bf8995f
OS : Ubuntu16

pyudev is not default library in python3

when I run scylla_setup
```
> eth0
Do you want to optimize NIC queue settings?
Answer yes to enable network card optimization and improve performance. Answer no to skip this optimization.
[YES/no]yes
Setting parameters on /etc/default/scylla-server
Traceback (most recent call last):
  File "/usr/lib/scylla/perftune.py", line 11, in <module>
    import pyudev
ImportError: No module named 'pyudev'
NIC queue setup failed. press any key to continue...
```
could we take this dependency into account for installation packages?

or all logs:
```
andrei@abv:~/scylladb_src$ sudo scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run kernel version check?
Answer yes to have this script verify that the currently installed kernel is qualified to run Scylla; answer no to skip this check.
[YES/no]yes
This is a supported kernel version.
Do you want to verify ScyllaDB packages installed?
Answer yes to have this script check that ScyllaDB is already installed; answer no to skip this check.
[YES/no]yes
Do you want to enable ScyllaDB services?
Answer yes to automatically start Scylla when the node boots; answer no to skip this step.
[YES/no]yes
Synchronizing state of collectd.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable collectd
Do you want to enable ScyllaDB version check?
Answer yes to automatically start Scylla-housekeeping service that checks for a newer version periodically; answer no to skip this step.
[YES/no]yes
Do you want to setup NTP?
Answer yes to enable time synchronization at boot time. This keeps time right on the node. Answer no to do nothing.
[YES/no]yes
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ntp is already the newest version (1:4.2.8p4+dfsg-3ubuntu5.4).
ntpdate is already the newest version (1:4.2.8p4+dfsg-3ubuntu5.4).
The following packages were automatically installed and are no longer required:
  libpciaccess-dev libprotoc9v5 libsctp-dev libunwind-dev linux-headers-4.4.0-71 linux-headers-4.4.0-71-generic linux-image-4.4.0-71-generic linux-image-extra-4.4.0-71-generic protobuf-compiler ragel
  systemtap-sdt-dev thrift-compiler uuid-dev xfslibs-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
25 Apr 19:26:01 ntpdate[25430]: step time server 91.189.89.198 offset -0.555297 sec
Do you want to setup RAID and XFS?
It is recommended to use RAID0 and XFS for Scylla data. If you select yes, you will be prompt to choose which unmounted disks to use for Scylla data. Selected disks will be formatted in the process.
[YES/no]yes
Are you sure you want to setup RAID and XFS?
If you choose Yes, selected drive will be reformated, erasing existing data in the process.
[YES/no]no
Do you want to setup coredump?
Answer yes to enable core dumps; this allows to do post-mortem analysis of Scylla state after a crash. Answer no to do nothing.
[YES/no]yes
Reading package lists... Done
Building dependency tree       
Reading state information... Done
systemd-coredump is already the newest version (229-4ubuntu16).
The following packages were automatically installed and are no longer required:
  libpciaccess-dev libprotoc9v5 libsctp-dev libunwind-dev linux-headers-4.4.0-71 linux-headers-4.4.0-71-generic linux-image-4.4.0-71-generic linux-image-extra-4.4.0-71-generic protobuf-compiler ragel
  systemtap-sdt-dev thrift-compiler uuid-dev xfslibs-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
kernel.core_pattern = |/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %e
Do you want to setup sysconfig?
Answer yes to do system wide configuration customized for Scylla. Answer no to do nothing.
[YES/no]yes
Please select NIC from following list: 
docker0 eth0 virbr0 virbr0-nic
> eth0
Do you want to optimize NIC queue settings?
Answer yes to enable network card optimization and improve performance. Answer no to skip this optimization.
[YES/no]yes
Setting parameters on /etc/default/scylla-server
Traceback (most recent call last):
  File "/usr/lib/scylla/perftune.py", line 11, in <module>
    import pyudev
ImportError: No module named 'pyudev'
NIC queue setup failed. press any key to continue...

andrei@abv:~/scylladb_src$ dpkg --list | grep scylla
ii  scylla                                               666.development-0.20170425.92dba05-0ubuntu1   amd64        Scylla database metapackage
ii  scylla-conf                                          666.development-0.20170425.92dba05-0ubuntu1   amd64        Scylla database main configuration file
ii  scylla-jmx                                           666.development-20170424.8176d57-0ubuntu1     all          Scylla JMX server binaries
ii  scylla-kernel-conf                                   666.development-0.20170425.92dba05-0ubuntu1   amd64        Scylla kernel tuning configuration
ii  scylla-server                                        666.development-0.20170425.92dba05-0ubuntu1   amd64        Scylla database server binaries
ii  scylla-server-dbg                                    666.development-0.20170425.92dba05-0ubuntu1   amd64        debugging symbols for scylla-server
ii  scylla-tools                                         666.development-20170425.33f64f3-0ubuntu1     all          Scylla database tools
```

**Comment by tzach** [comment]
@syuu1228 can you please take a look?

**Comment by syuu1228** [comment]
@tzach sure, will handle in today
