### ISSUE TITLE
Nodetool cfstats do not provide correct information  after dropping a table from a keyspace

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#2340]
*Installation details*
Scylla version (or git commit hash): scylla --version
1.6.2-20170310.d41ba3b
Cluster size:3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos7.2

Platform (physical/VM/cloud instance type/docker): GCE
Hardware: sockets= cores= hyperthreading= memory= n1-standard-8

executing nodetool cfstats <CF> do not provide information after dropping a table from a keyspace. 
Created 2 tables in a keysapce and dropped on of them, after the drop nodetool cfstats no longer provide data on any of the tables in the keyspace

The process of creating the issue:
cqlsh> CREATE KEYSPACE test123 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};
cqlsh> CREATE TABLE test123.test1 (col1 text PRIMARY KEY, col2 text, col3 text);
cqlsh> CREATE TABLE test123.test2 (col11 text PRIMARY KEY, col21 text, col31 text);
cqlsh> INSERT INTO test123.test1 ( col1, col2, col3) VALUES ( '123', '234', '456');
cqlsh> INSERT INTO test123.test1 ( col1, col2, col3) VALUES ( '12', '23', '45');
cqlsh> INSERT INTO test123.test1 ( col1, col2, col3) VALUES ( '1', '2', '4');
cqlsh> INSERT INTO test123.test2 (col11, col21, col31) VALUES ( '123', '234', '456');
cqlsh> INSERT INTO test123.test2 (col11, col21, col31) VALUES ( '12', '23', '45');
cqlsh> INSERT INTO test123.test2 (col11, col21, col31) VALUES ( '2', '3', '5');

from a shell:
nodetool cfstats test123
Keyspace: test123
	Read Count: 0
	Read Latency: NaN ms.
	Write Count: 6
	Write Latency: 0.0 ms.
	Pending Flushes: 0
		Table: test1
		SSTable count: 0
		Space used (live): 0
		Space used (total): 0
		Space used by snapshots (total): 0
		Off heap memory used (total): 786432
		SSTable Compression Ratio: 0.0
		Number of keys (estimate): 0
		Memtable cell count: 3
		Memtable data size: 1752
		Memtable off heap memory used: 786432
		Memtable switch count: 0
		Local read count: 0
		Local read latency: NaN ms
		Local write count: 3
		Local write latency: 0.000 ms
		Pending flushes: 0
		Bloom filter false positives: 0
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 0
		Bloom filter off heap memory used: 0
		Index summary off heap memory used: 0
		Compression metadata off heap memory used: 0
		Compacted partition minimum bytes: 0
		Compacted partition maximum bytes: 0
		Compacted partition mean bytes: 0
		Average live cells per slice (last five minutes): 0.0
		Maximum live cells per slice (last five minutes): 0.0
		Average tombstones per slice (last five minutes): 0.0
		Maximum tombstones per slice (last five minutes): 0.0

		Table: test2
		SSTable count: 0
		Space used (live): 0
		Space used (total): 0
		Space used by snapshots (total): 0
		Off heap memory used (total): 524288
		SSTable Compression Ratio: 0.0
		Number of keys (estimate): 0
		Memtable cell count: 3
		Memtable data size: 1752
		Memtable off heap memory used: 524288
		Memtable switch count: 0
		Local read count: 0
		Local read latency: NaN ms
		Local write count: 3
		Local write latency: 0.000 ms
		Pending flushes: 0
		Bloom filter false positives: 0
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 0
		Bloom filter off heap memory used: 0
		Index summary off heap memory used: 0
		Compression metadata off heap memory used: 0
		Compacted partition minimum bytes: 0
		Compacted partition maximum bytes: 0
		Compacted partition mean bytes: 0
		Average live cells per slice (last five minutes): 0.0
		Maximum live cells per slice (last five minutes): 0.0
		Average tombstones per slice (last five minutes): 0.0
		Maximum tombstones per slice (last five minutes): 0.0

Dropping the test2 table.
cqlsh> DROP TABLE test123.test2;

nodetool cfstats test123
Keyspace: test123
nodetool: Scylla API server HTTP GET to URL '/column_family/metrics/write_latency/moving_average_histogram/test123:test2' failed: Column family 'test123:test2' not found
See 'nodetool help' or 'nodetool help <command>'.

The nodetool cfstats should report the test1 table information.

**Comment by tomer-sandler** [comment]
Did the same exact scenario described by Eyal on the following version:
[tomer@tomer-4cpu-15gb-centos7-loader7 ~]$ scylla --version
1.6.1-20170218.2ea4da2

I got an exception and few seconds later, the same error as Eyal got.  Maybe it would be of some use:

[tomer@tomer-4cpu-15gb-centos7-loader7 ~]$ nodetool cfstats test123
error: null
-- StackTrace --
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at org.apache.cassandra.db.ColumnFamilyStore.checkRegistration(ColumnFamilyStore.java:123)
        at com.scylladb.jmx.utils.APIMBeanServer.queryNames(APIMBeanServer.java:87)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1487)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.queryNames(RMIConnectionImpl.java:572)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
        at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
        at javax.management.remote.rmi.RMIConnectionImpl_Stub.queryNames(Unknown Source)
        at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.queryNames(RMIConnector.java:847)
        at org.apache.cassandra.tools.ColumnFamilyStoreMBeanIterator.getCFSMBeans(NodeProbe.java:1346)
        at org.apache.cassandra.tools.ColumnFamilyStoreMBeanIterator.<init>(NodeProbe.java:1306)
        at org.apache.cassandra.tools.NodeProbe.getColumnFamilyStoreMBeanProxies(NodeProbe.java:464)
        at org.apache.cassandra.tools.NodeTool$CfStats.execute(NodeTool.java:743)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:288)
        at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:202)

[tomer@tomer-4cpu-15gb-centos7-loader7 ~]$ nodetool cfstats test123
Keyspace: test123
nodetool: Scylla API server HTTP GET to URL '/column_family/metrics/write_latency/moving_average_histogram/test123:test2' failed: Column family 'test123:test2' not found
See 'nodetool help' or 'nodetool help <command>'.

**Comment by amnonh** [comment]
I've checked it on Master and it works as expected, I'll try to see the problem on 1.6 and see where it comes from

**Comment by amnonh** [comment]
@elcallio can you take a look at MetricsMbean.postDeregister from the stack it seems that it tries to register an mbean instead of unregistering it

**Comment by elcallio** [comment]
1.6 branch is before the grand v3-rewrite, so this is your code actually. That being said, the code in question is:
```
for (String n : cf.keySet()) {
    if (!all_cf.contains(n)) {
        cf.remove(n);
    }
}
```

which is illegal. Modifying the HashMap invalidates any existing iterators. To iterate-and-remove you need to use an explicit iterator + remove, thus:

```
Iterator<String> i = cf.keySet().iterator();
while (i.hasNext()) {
    String n = i.next();
    if (!all_cf.contains(n)) {
        i.remove();
    }
}
```

**Comment by amnonh** [comment]
you are right about 1.6, my comment was about the code in master, if you
can take a look

**Comment by amnonh** [comment]
On Wed, May 10, 2017 at 2:37 PM, Calle Wilund <notifications@github.com>
wrote:

> Ah, right, sorry. Eyals problem is probably because we don't do a purge of
> bound names until we get something like a wildcard lookup (for performance
> reasons). I will run and verify this.
> The best solution is probably to wrap catching the exception and
> purge+retry iff we get a "missing object".
>
I think eyal's problem is actually the one you mentioned (he reported it in
1.6) and I think that your fix works, still verifying.

**Comment by elcallio** [comment]
In trunk at least I got a slightly different problem: Unregistration happened as expected (I think nodetool always does a lookup - great!), but a bug in the unregistration path (missing proxy call) caused us to both throw exceptions and retain some beans that should be removed. Note that the nodetool call itself worked for me though, so I'm a little confused. 
I'd love to be able to repro the original error...

**Comment by elcallio** [comment]
But he ran another 1.6, right, so maybe to unregistration check is only broken there... :-)

**Comment by amnonh** [comment]
On Wed, May 10, 2017 at 3:03 PM, Calle Wilund <notifications@github.com>
wrote:

> In trunk at least I got a slightly different problem: Unregistration
> happened as expected (I think nodetool always does a lookup - great!), but
> a bug in the unregistration path (missing proxy call) caused us to both
> throw exceptions and retain some beans that should be removed. Note that
> the nodetool call itself worked for me though, so I'm a little confused.
> I'd love to be able to repro the original error...
>
That what got me confused on my first reponse, it seems to work on the
nodetool side, but it does through an error on the jmx side.

I end up explicitly unregister the mbean to fix the issue on 1.6

**Comment by elcallio** [comment]
Well, I verified that nodetool will indeed to a general lookup before (most?) ops, so for that purpose the unregistration in trunk should be fine. I am reluctant to add more complexity to the code unless we find a tangible error-case so until then the patch I sent should suffice.

**Comment by slivne** [comment]
@amnonh / @elcallio - did we resolve this ?

**Comment by amnonh** [comment]
I sent a patch, it didn't get reviewed

**Comment by slivne** [comment]
so please ping

**Comment by penberg** [comment]
@amnonh The patch was applied, can we close this?

**Comment by amnonh** [comment]
Yes please
