### ISSUE TITLE
scylla has an old version of cqlshlib

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2393]
clqsh tests working with cqlshlib are broken

some example from dtest:
======================================================================
ERROR: test_all_datatypes_write (cqlsh_tests.cqlsh_copy_tests.CqlshCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larisau/dev/scylla-dtest/cqlsh_tests/cqlsh_copy_tests.py", line 964, in test_all_datatypes_write
    self.assertCsvResultEqual(self.tempfile.name, results)
  File "/home/larisau/dev/scylla-dtest/cqlsh_tests/cqlsh_copy_tests.py", line 237, in assertCsvResultEqual
    result_list = list(self.result_to_csv_rows(results))
  File "/home/larisau/dev/scylla-dtest/cqlsh_tests/cqlsh_copy_tests.py", line 298, in result_to_csv_rows
    return [[self.format_for_csv(v) for v in row] for row in result]
  File "/home/larisau/dev/scylla-dtest/cqlsh_tests/cqlsh_copy_tests.py", line 288, in format_for_csv
    nullval=None).strval
  File "/home/larisau/dev/scylla/../scylla-tools-java/pylib/cqlshlib/formatting.py", line 133, in format_value
    return formatter(val, **kwargs)
TypeError: format_value_list() takes exactly 9 arguments (6 given)

**Comment by slivne** [comment]
We are supposed to have something that aligns with the commit that
@elcallio used to repase scylla-tools-java.

It should be 3.0.X - @elcallio should have the exact commit.

If the features/tests are not on that version they will not work and in my
view we should retain them on the same version as the other tools.

**Comment by elcallio** [comment]
If you refer to the "pylib/cqlshlib" folder in scylla-tools-java, I 
don't have much more idea of exactly which "version" that is. It is 
updated to whatever was in cassandra-3.0 branch on merge (which we 
should probably do again to collect fixes updates), but git history does 
not say much about "version", though by definition I guess it is 3.x.

Most recent change we have there from origin is 
99e2add18da2fe24c25f94b4e0647a2c266374df

/C

**Comment by slivne** [comment]
@roydahan is this working with cassandra 3.0.X or with later versions ?

**Comment by larisau** [comment]
No, it does not work, fails with the same error.

**Comment by slivne** [comment]
so lets disable the tests and close the issue - we are compatible with cassandra 3.0.X

**Comment by duarten** [comment]
There are a bunch of fixes related with this, namely apache/cassandra@bdca25e. It appears to only be merged into 3.10.
