### ISSUE TITLE
unable to migrate 2_1_x/with_old_format_counter

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2458]
*Installation details*
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/de70d942a914e2f8c846604124c160ca1e385dd5

test: migration_test.py:TestMigration.migrate_sstable_with_old_format_counter_test https://github.com/scylladb/scylla-dtest/pull/502

when we query 'SELECT * FROM ks.cf' after migration:

ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for ks.cf - received only 0 responses from 1 CL=ONE." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}

server logs:
```
INFO  2017-06-08 11:28:45,258 [shard 0] storage_service - Loading new SSTables for ks.cf...
INFO  2017-06-08 11:28:45,448 [shard 0] storage_service - CF ks.cf at shard 0 had SSTables writes disabled for 189615 usec
INFO  2017-06-08 11:28:45,491 [shard 0] storage_service - Done loading new SSTables for ks.cf for all shards
ERROR 2017-06-08 11:29:00,474 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: marshaling error: encountered a local shard in a counter cell
ERROR 2017-06-08 11:29:10,496 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: marshaling error: encountered a local shard in a counter cell
ERROR 2017-06-08 11:29:20,481 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: marshaling error: encountered a local shard in a counter cell
ERROR 2017-06-08 11:29:30,484 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: marshaling error: encountered a local shard in a counter cell
ERROR 2017-06-08 11:29:40,491 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: marshaling error: encountered a local shard in a counter cell
ERROR 2017-06-08 11:29:50,492 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: marshaling error: encountered a local shard in a counter cell
```

test logs:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/andrei/scylladb_fork/scylla-dtest/migration_test.py", line 477, in migrate_sstable_with_old_format_counter_test
    rows = self.get_all_rows_for_check(node1)
  File "/home/andrei/scylladb_fork/scylla-dtest/migration_test.py", line 278, in get_all_rows_for_check
    return list(s.execute(statement))
  File "cassandra/cluster.py", line 2018, in cassandra.cluster.Session.execute (cassandra/cluster.c:35502)
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 3822, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:74332)
    raise self._final_exception
ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for ks.cf - received only 0 responses from 1 CL=ONE." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}
-------------------- >> begin captured stdout << ---------------------
cluster ccm directory: /home/andrei/.dtest/dtest-Yoc9_7
Starting a cluster of one node...
Creating a CQL connection...
Creating a keyspace 'ks'...
Creating a column family 'cf'...
Flushing a keyspace...
cassandra sstable dir is /home/andrei/scylladb_fork/scylla-dtest/cassandra-sstables/migration/2_1_x/with_old_format_counter
Column family directory is /home/andrei/.dtest/dtest-Yoc9_7/test/node1/data/ks/cf-4f073c104c2311e7badd000000000000
Copying sstables created by Cassandra...
Running 'nodetool refresh -- ks cf' to load migrated sstables
Checking counters data...
Checking rows content on node1...
Retrying read after timeout. Attempt #0
Retrying read after timeout. Attempt #1
Retrying read after timeout. Attempt #2
Retrying read after timeout. Attempt #3
Retrying read after timeout. Attempt #4
```

**Comment by pdziepak** [comment]
Looks correct. We do not support the old counters format.
