### ISSUE TITLE
Cannot create table with non-alphnum UDT

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2491]
Connected to scylla-1 at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> 
cqlsh> CREATE KEYSPACE udttests WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
cqlsh> USE udttests;
cqlsh:udttests> CREATE TYPE "test.field@#$%@%#!" ("test.field@#$%@%#!" text);
cqlsh:udttests> CREATE TYPE type2 ("test.field@#$%@%#!" text);
cqlsh:udttests> DESC SCHEMA 

CREATE KEYSPACE udttests WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TYPE udttests."test.field@#$%@%#!" (
    "test.field@#$%@%#!" text
);

CREATE TYPE udttests.type2 (
    "test.field@#$%@%#!" text
);

cqlsh:udttests> CREATE TABLE tbl (k int PRIMARY KEY, non_alphanum_type_map map<frozen<"test.field@#$%@%#!">, int>,alphanum_type_map map<frozen<type2>, int>);
SyntaxException: line 1:21 no viable alternative at input ''

**Comment by duarten** [comment]
I think the problem is at `alphanum_type_map map<frozen, int>`; this is not valid syntax as frozen expects a parameter. Changing this to 

```
CREATE TABLE udttests.tbl (k int PRIMARY KEY, non_alphanum_type_map map<frozen<"test.field@#$%@%#!">, int>,alphanum_type_map map<frozen<type2>, int>);
```

works for me.

**Comment by larisau** [comment]
I just reproduced the failing python-driver test:
Traceback (most recent call last):
  File "/home/larisau/dev/python-driver/tests/integration/standard/test_udts.py", line 680, in test_non_alphanum_identifiers
    s.execute('CREATE TABLE %s (k int PRIMARY KEY, non_alphanum_type_map map<frozen<"%s">, int>, alphanum_type_map map<frozen<%s>, int>)' % (self.table_name, non_alphanum_name, type_name))
  File "/home/larisau/dev/python-driver/cassandra/cluster.py", line 2018, in execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "/home/larisau/dev/python-driver/cassandra/cluster.py", line 3822, in result
    raise self._final_exception
SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:21 no viable alternative at input ''">

here is the right query that is still failing:
cqlsh:udttests> CREATE TABLE tbl (k int PRIMARY KEY, non_alphanum_type_map map<frozen<"test.field@#$%@%#!">, int>,alphanum_type_map map<frozen<type2>, int>);
SyntaxException: line 1:21 no viable alternative at input ''

Executed on master scylla built today.

**Comment by duarten** [comment]
That still contains `alphanum_type_map map<frozen, int>`, which isn't valid. Fixing that makes the statement work for me with scylladb/scylla-tools-java@6d11529.

**Comment by larisau** [comment]
duarte, it's github markdown, when I copy my query, it removes some part of it

**Comment by duarten** [comment]
Ah! :) Works fine for me with Scylla 1.7:

```
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.2.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> CREATE KEYSPACE udttests WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true;
cqlsh>
cqlsh> CREATE TYPE udttests."test.field@#$%@%#!" (
   ... "test.field@#$%@%#!" text
   ... );
cqlsh>
cqlsh> CREATE TYPE udttests.type2 (
   ... "test.field@#$%@%#!" text
   ... );
cqlsh> CREATE TABLE tbl (k int PRIMARY KEY, non_alphanum_type_map map<frozen<"test.field@#$%@%#!">, int>,alphanum_type_map map<frozen<type2>, int>);
InvalidRequest: Error from server: code=2200 [Invalid query] message="No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename"
cqlsh> use udttests;
cqlsh:udttests> CREATE TABLE tbl (k int PRIMARY KEY, non_alphanum_type_map map<frozen<"test.field@#$%@%#!">, int>,alphanum_type_map map<frozen<type2>, int>);
cqlsh:udttests>
```
But indeed not with master:

```
cqlsh:udttests> CREATE TABLE tbl (k int PRIMARY KEY, non_alphanum_type_map map<frozen<"test.field@#$%@%#!">, int>,alphanum_type_map map<frozen<type2>, int>);
SyntaxException: line 1:21 no viable alternative at input ''
```

This is the relevant backtrace:

```
#0  __cxxabiv1::__cxa_throw (obj=0x60e00005cb00, tinfo=0xaebf778 <_ZTIN10exceptions16syntax_exceptionE>, dest=0x368d5ac <_ZN10exceptions16syntax_exceptionD2Ev>)
    at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:63
#1  0x000000000370aae0 in _ZN4cql315error_collectorIN11cql3_parser8CqlLexerEhN6antlr36TraitsIS2_NS1_9CqlParserENS3_16CustomTraitsBaseENS3_5EmptyEE17ExceptionBaseTypeINS3_11InputStreamINS3_10TraitsBaseIS6_EEEEEEE24throw_first_syntax_errorEv (this=0x7fffde264de0) at ./cql3/error_collector.hh:107
#2  0x0000000004d2f480 in _ZN4cql34util14do_with_parserISt7_Mem_fnIMN11cql3_parser9CqlParserEFN7seastar10shared_ptrINS_9cql3_type3rawEEEvEES9_EET0_RKNSt12experimental15fundamentals_v117basic_string_viewIcSt11char_traitsIcEEEOT_ (cql="map<frozen<test.field@#$%@%#!>, int>",
    f=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xec44b60, DIE 0xee29159>) at ./cql3/util.hh:54
#3  0x0000000004d29e2f in parse_raw (str=...) at db/cql_type_parser.cc:52
#4  0x0000000004d2a829 in _ZN2db15cql_type_parser5parseERKN7seastar13basic_sstringIcjLj15EEES5_NS1_13lw_shared_ptrI19user_types_metadataEE (keyspace=..., str=..., user_types=...)
    at db/cql_type_parser.cc:81
#5  0x0000000004a862c8 in db::schema_tables::create_columns_from_column_rows (rows=..., keyspace=..., table=..., is_super=false) at db/schema_tables.cc:2025
#6  0x0000000004a818d0 in _ZN2db13schema_tables27create_table_from_mutationsE16schema_mutationsNSt12experimental15fundamentals_v18optionalIN5utils4UUIDEEE (sm=...,
    version=std::experimental::optional<utils::UUID> [no contained value]) at db/schema_tables.cc:1864
#7  0x0000000004ac07db in db::schema_tables::<lambda(auto:129&&)>::operator()<schema_mutations>(<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeaad670>) const (__closure=0x7fffde26634f, sm=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeaad670>) at db/schema_tables.cc:899
#8  0x0000000004ac155f in db::schema_tables::diff_table_or_view<db::schema_tables::merge_tables_and_views(seastar::distributed<service::storage_proxy>&, std::map<db::schema_tables::qualified_name, schema_mutations>&&, std::map<db::schema_tables::qualified_name, schema_mutations>&&, std::map<db::schema_tables::qualified_name, schema_mutations>&&, std::map<db::schema_tables::qualified_name, schema_mutations>&&)::<lambda(auto:129&&)> >(seastar::distributed &, <unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>, <unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>, <unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xec03bcb>) (proxy=..., before=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>,
    after=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>,
    create_schema=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xec03bcb>) at db/schema_tables.cc:879
#9  0x0000000004a61fc9 in db::schema_tables::merge_tables_and_views(seastar::distributed &, <unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>, <unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>, <unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>, <unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>) (proxy=...,
    tables_before=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>,
    tables_after=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>,
    views_before=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>,
    views_after=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeab3df4>) at db/schema_tables.cc:899
#10 0x0000000004a569bb in db::schema_tables::<lambda()>::operator()(void) (__closure=0x608000289da8) at db/schema_tables.cc:777
#11 0x0000000004baffb6 in seastar::apply_helper<db::schema_tables::do_merge_schema(seastar::distributed<service::storage_proxy>&, std::vector<mutation>, bool)::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply(<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeb66b49>, <unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xea730e0>) (func=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeb66b49>,
    args=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xea730e0>) at /home/fedora/code/scylla/seastar/core/apply.hh:36
#12 0x0000000004bb003c in seastar::apply<db::schema_tables::do_merge_schema(seastar::distributed<service::storage_proxy>&, std::vector<mutation>, bool)::<lambda()> >(<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeb66b09>, <unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xea730e0>) (
    func=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xeb66b09>,
    args=<unknown type in /home/fedora/code/scylla/build/debug/scylla, CU 0xe80e4f6, DIE 0xea730e0>) at /home/fedora/code/scylla/seastar/core/apply.hh:44
```

In 6c8b5fc09d5e01782acd3ef175113935f2ce9db4, we started to read a column type by doing `cql_type_parser::parse(keyspace, type_str)`, instead of `db::marshal::type_parser::parse(type_str);` as before.

`cql_type_parser::parse(keyspace, type_str)` will eventually use the cql3 grammar to parse the type, which fails because the quotes around the type are missing, i.e., the type we try to parse internally is `map<frozen<test.field@#$%@%#!>, int>` instead of `map<frozen<"test.field@#$%@%#!">, int>`.

This means that `test.` will match a user type prefixed by a keyspace named `test`.

The fix should be to understand why the quotes are removed and preserve the quoted name.
