### ISSUE TITLE
Exception when trying to run "nodetool tabelhistograms" on Schema created by scylla_bench tool

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#2521]
**Installation details**
Scylla version (or git commit hash): 1.7
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos7

```
Enabled counters by adding 'experimental: true' to the scylla.yaml
Run the scylla_bench from 3 loaders for ~20 min
Stop the loaders and then executed the below commands

Known bug?

 cqlsh> DESCRIBE SCHEMA ;

CREATE KEYSPACE scylla_bench WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE scylla_bench.test (
    pk bigint,
    ck bigint,
    v blob,
    PRIMARY KEY (pk, ck)
) WITH CLUSTERING ORDER BY (ck ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE scylla_bench.test_counters (
    pk bigint,
    ck bigint,
    c1 counter,
    c2 counter,
    c3 counter,
    c4 counter,
    c5 counter,
    PRIMARY KEY (pk, ck)
) WITH CLUSTERING ORDER BY (ck ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh> exit


[root@optane37 ~]# nodetool tablehistograms scylla_bench scylla_bench.test
error: org.apache.cassandra.metrics:type=IndexTable,keyspace=scylla_bench,scope=scylla_bench.test,name=EstimatedPartitionSizeHistogram
-- StackTrace --
javax.management.InstanceNotFoundException: org.apache.cassandra.metrics:type=IndexTable,keyspace=scylla_bench,scope=scylla_bench.test,name=EstimatedPartitionSizeHistogram
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at com.scylladb.jmx.utils.APIMBeanServer.getAttribute(APIMBeanServer.java:120)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
        at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
        at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
        at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
        at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:273)
        at com.sun.proxy.$Proxy21.getValue(Unknown Source)
        at org.apache.cassandra.tools.NodeProbe.getColumnFamilyMetric(NodeProbe.java:1150)
        at org.apache.cassandra.tools.nodetool.TableHistograms.execute(TableHistograms.java:49)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:265)
        at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:174)
```

**Comment by slivne** [comment]
I don;t think this is a bug the syntax is incorrect - the same error is returned from cassandra

instead of

```
nodetool tablehistograms scylla_bench scylla_bench.test
```

run

```
nodetool tablehistograms scylla_bench test
```

with cassandra we get the exat same behaviour
