### ISSUE TITLE
Running Scylla AMI with t2.micro instance failed without a clear error message

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2540]
*Installation details*
Scylla version (or git commit hash): 1.7.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ScyllaDB 1.7.1 (ami-a8e3edd1) Oregon region

Two ways to handle small instance:
- Do not allow Scylla AMI to run on small instances, showing a detailed error message (for example - please run in dev mode) 
- Run Scylla in develoer-mode on small instances (see https://github.com/scylladb/scylla/issues/1829)

Currently, Scylla do neither 

The prompt does not pass 
```
Constructing RAID volume...
```

```
$ systemctl status scylla-ami-setup
● scylla-ami-setup.service - Scylla AMI Setup
   Loaded: loaded (/usr/lib/systemd/system/scylla-ami-setup.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2017-07-02 13:45:47 UTC; 9min ago
  Process: 722 ExecStart=/usr/lib/scylla/scylla-ami/scylla_ami_setup (code=exited, status=1/FAILURE)
 Main PID: 722 (code=exited, status=1/FAILURE)

Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: Traceback (most recent call last):
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 162, in <module>
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: get_disk_bundles()
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 139, in get_disk_bundles
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: raise Exception("No disks found")
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: Exception: No disks found
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: Failed to start Scylla AMI Setup.
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: Unit scylla-ami-setup.service entered failed state.
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: scylla-ami-setup.service failed.
```

logs
```
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: [INFO] scylla.yaml configured.
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: Traceback (most recent call last):
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 162, in <module>
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: get_disk_bundles()
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 139, in get_disk_bundles
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: raise Exception("No disks found")
Jul 02 13:45:47 ip-172-31-10-161 scylla_ami_setup[722]: Exception: No disks found
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: Job scylla-server.service/start failed with result 'dependency'.
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: Unit scylla-ami-setup.service entered failed state.
Jul 02 13:45:47 ip-172-31-10-161 systemd[1]: scylla-ami-setup.service failed.
```

**Comment by syuu1228** [comment]
Patch is on the list: "[PATCH scylla-ami] scylla_create_devices: don't raise error when no disks found"
