### ISSUE TITLE
Row Cache continuity information is not used for queries of partitions that do not exist (bloom filters are still checked)

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2544]
*Installation details*
Scylla version (or git commit hash): 6895f6e60373bd66ae7b991aba8dae892fda5b6b

I changed the code to be able to breakpoint on sstables::sstable::filter_has_key

I used the following
```
ccm create scylla-1 --scylla --vnodes -n 1 --install-dir=/data2/shlomi/scylla-ccm/../scylla
ccm start
ccm node1 cqlsh
ccm node1 stress write n=100;
ccm node1 flush
ccm node1 stop
ccm node1 start
ccm node1 cqlsh -e "select * from keyspace1.standard1;"
```

I then attached to the process

a query to an existing key is returned from the cache (and does not hit the filter_has_key)

a query to a non existing key hits the filter_has_key - it shouldn't we know the information is not in the disk

backtrace

(please note I moved the filter_has_key to cc and added some logging as well) - but the rest is aligned.
```
#0  sstables::sstable::filter_has_key (this=0x6000001f0000, key=...) at sstables/sstables.cc:2753
#1  0x000000000088f255 in <lambda(const shared_sstable&)>::operator() (sst=..., __closure=<synthetic pointer>) at database.cc:317
#2  __gnu_cxx::__ops::_Iter_pred<filter_sstable_for_reader(std::vector<seastar::lw_shared_ptr<sstables::sstable> >&&, column_family&, const schema_ptr&, const sstables::key&, const query::partition_slice&)::<lambda(const shared_sstable&)> >::operator()<__gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable>*, std::vector<seastar::lw_shared_ptr<sstables::sstable> > > > (__it=..., 
    this=<synthetic pointer>) at /usr/include/c++/6.3.1/bits/predefined_ops.h:234
#3  std::__find_if<__gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable>*, std::vector<seastar::lw_shared_ptr<sstables::sstable> > >, __gnu_cxx::__ops::_Iter_pred<filter_sstable_for_reader(std::vector<seastar::lw_shared_ptr<sstables::sstable> >&&, column_family&, const schema_ptr&, const sstables::key&, const query::partition_slice&)::<lambda(const shared_sstable&)> > > (__pred=..., __last=..., 
    __first=...) at /usr/include/c++/6.3.1/bits/stl_algo.h:148
#4  std::__find_if<__gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable>*, std::vector<seastar::lw_shared_ptr<sstables::sstable> > >, __gnu_cxx::__ops::_Iter_pred<filter_sstable_for_reader(std::vector<seastar::lw_shared_ptr<sstables::sstable> >&&, column_family&, const schema_ptr&, const sstables::key&, const query::partition_slice&)::<lambda(const shared_sstable&)> > > (__pred=..., __last=..., 
    __first=...) at /usr/include/c++/6.3.1/bits/stl_algo.h:162
#5  std::__remove_if<__gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable>*, std::vector<seastar::lw_shared_ptr<sstables::sstable> > >, __gnu_cxx::__ops::_Iter_pred<filter_sstable_for_reader(std::vector<seastar::lw_shared_ptr<sstables::sstable> >&&, column_family&, const schema_ptr&, const sstables::key&, const query::partition_slice&)::<lambda(const shared_sstable&)> > > (__pred=..., __last=..., 
    __first=...) at /usr/include/c++/6.3.1/bits/stl_algo.h:860
#6  std::remove_if<__gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable>*, std::vector<seastar::lw_shared_ptr<sstables::sstable> > >, filter_sstable_for_reader(std::vector<seastar::lw_shared_ptr<sstables::sstable> >&&, column_family&, const schema_ptr&, const sstables::key&, const query::partition_slice&)::<lambda(const shared_sstable&)> > (__pred=..., __last=..., __first=...)
    at /usr/include/c++/6.3.1/bits/stl_algo.h:937
#7  boost::range::remove_if<std::vector<seastar::lw_shared_ptr<sstables::sstable> >, filter_sstable_for_reader(std::vector<seastar::lw_shared_ptr<sstables::sstable> >&&, column_family&, const schema_ptr&, const sstables::key&, const query::partition_slice&)::<lambda(const shared_sstable&)> > (pred=..., rng=std::vector of length 1, capacity 1 = {...}) at /usr/include/boost/range/algorithm/remove_if.hpp:35
#8  filter_sstable_for_reader (slice=..., key=..., schema=..., cf=..., sstables=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x30a733f>) at database.cc:319
#9  single_key_sstable_reader::operator() (this=0x6000049d6220) at database.cc:527
#10 0x00000000009a0cd3 in mutation_reader::operator() (this=<optimized out>) at mutation_reader.hh:89
#11 restricting_mutation_reader::operator()()::{lambda()#1}::operator()() const (__closure=<optimized out>) at mutation_reader.cc:260
#12 seastar::apply_helper<restricting_mutation_reader::operator()()::{lambda()#1}, std::tuple<>&&, std::integer_sequence<unsigned long> >::apply({lambda()#1}&&, std::tuple<>) (args=<optimized out>, 
    func=<optimized out>) at ./seastar/core/apply.hh:36
#13 seastar::apply<restricting_mutation_reader::operator()()::{lambda()#1}>(restricting_mutation_reader::operator()()::{lambda()#1}&&, std::tuple<>&&) (args=<optimized out>, func=<optimized out>)
    at ./seastar/core/apply.hh:44
#14 seastar::futurize<seastar::future<optimized_optional<streamed_mutation> > >::apply<restricting_mutation_reader::operator()()::{lambda()#1}>(restricting_mutation_reader::operator()()::{lambda()#1}&&, std::tuple<>&&) (args=<optimized out>, func=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x5831258, DIE 0x59743d7>) at ./seastar/core/future.hh:1302
#15 seastar::future<>::then<restricting_mutation_reader::operator()()::{lambda()#1}, seastar::future<optimized_optional<streamed_mutation> > >(restricting_mutation_reader::operator()()::{lambda()#1}&&) (
    this=this@entry=0x7ffd2007dc10, func=func@entry=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x5831258, DIE 0x598a39b>) at ./seastar/core/future.hh:890
#16 0x00000000009a48f8 in restricting_mutation_reader::operator() (this=0x600005268980) at mutation_reader.cc:261
#17 0x000000000090feb2 in mutation_reader::operator() (this=0x600005268d30) at mutation_reader.hh:89
#18 single_partition_populating_reader::operator() (this=0x600005268d20) at row_cache.cc:329
#19 0x00000000009971b2 in mutation_reader::operator() (this=0x600005060b98) at mutation_reader.hh:89
#20 combined_mutation_reader::<lambda(mutation_reader*)>::operator() (mr=0x600005060b98, __closure=<optimized out>) at mutation_reader.cc:40
#21 seastar::<lambda(seastar::parallel_for_each_state&)>::operator() (state=..., __closure=<optimized out>) at /data2/shlomi/scylla/seastar/core/future-util.hh:98
#22 seastar::do_with<seastar::parallel_for_each_state, seastar::parallel_for_each(Iterator, Iterator, Func&&) [with Iterator = __gnu_cxx::__normal_iterator<mutation_reader**, std::vector<mutation_reader*> >; Func = combined_mutation_reader::prepare_next()::<lambda(mutation_reader*)>]::<lambda(seastar::parallel_for_each_state&)> > (f=<optimized out>, 
    rvalue=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x5831258, DIE 0x5963162>) at /data2/shlomi/scylla/seastar/core/do_with.hh:57
#23 seastar::parallel_for_each<__gnu_cxx::__normal_iterator<mutation_reader**, std::vector<mutation_reader*> >, combined_mutation_reader::prepare_next()::<lambda(mutation_reader*)> > (func=<optimized out>, 
    end=..., begin=...) at /data2/shlomi/scylla/seastar/core/future-util.hh:119
#24 seastar::parallel_for_each<std::vector<mutation_reader*>&, combined_mutation_reader::prepare_next()::<lambda(mutation_reader*)> > (func=<optimized out>, range=std::vector of length 2, capacity 2 = {...})
    at /data2/shlomi/scylla/seastar/core/future-util.hh:142
#25 combined_mutation_reader::prepare_next (this=this@entry=0x6000001f1100) at mutation_reader.cc:39
#26 0x000000000099ad90 in combined_mutation_reader::next (this=0x6000001f1100) at mutation_reader.cc:53
#27 0x000000000099b359 in combined_mutation_reader::operator() (this=<optimized out>) at mutation_reader.cc:123
#28 0x000000000097f151 in mutation_reader::operator() (this=<optimized out>) at mutation_reader.hh:89
#29 _ZZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bENKUlRS7_RT0_RT1_E_clIS6_S5_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaS9_SB_SD_ENKUlvE_clEv (__closure=0x7ffd2007e0e0) at mutation_reader.hh:428
#30 _ZN7seastar8futurizeINS_6futureIJNS_10bool_classINS_18stop_iteration_tagEEEEEEE5applyIRZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bENKUlRSG_RT0_RT1_E_clISF_SE_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaSI_SK_SM_EUlvE_JEEES5_SH_DpOT0_ (func=...) at ./seastar/core/future.hh:1312
#31 _ZN7seastar6repeatIZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bENKUlRS9_RT0_RT1_E_clIS8_S7_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaSB_SD_SF_EUlvE_EENS_6futureIJEEESA_ (action=action@entry=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x5175321, DIE 0x538ecf9>)
    at /data2/shlomi/scylla/seastar/core/future-util.hh:203
#32 0x000000000097f81d in _ZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bENKUlRS7_RT0_RT1_E_clIS6_S5_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaS9_SB_SD_ (sm=std::experimental::optional<streamed_mutation> [no contained value], c=..., mr=..., __closure=<optimized out>)
    at mutation_reader.hh:431
#33 _ZN7seastar12apply_helperIRZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bEUlRS9_RT0_RT1_E_RSt5tupleIJS8_S7_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEESt16integer_sequenceImJLm0ELm1ELm2EEEE5applyESH_SP_ (args=..., func=...) at ./seastar/core/apply.hh:36
#34 _ZN7seastar5applyIRZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bEUlRS9_RT0_RT1_E_JS8_S7_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEEDaSA_RSt5tupleIJDpT0_EE (args=..., func=...) at ./seastar/core/apply.hh:51
#35 _ZN7seastar7do_withI15mutation_reader35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEENSt12experimental15fundamentals_v18optionalI17streamed_mutationEEJZ17consume_flattenedIS7_EDaS1_OT_bEUlRSE_RT0_RT1_E_EEEDaSF_OSH_OSJ_DpOT2_ (rv3=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x5175321, DIE 0x52cdc87>, 
    rv2=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x5175321, DIE 0x52d0d13>, rv1=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x5175321, DIE 0x52cdc3d>)
    at /data2/shlomi/scylla/seastar/core/do_with.hh:110
#36 consume_flattened<stable_flattened_mutations_consumer<compact_for_query<(emit_only_live_rows)1, query_result_builder> > >(mutation_reader, stable_flattened_mutations_consumer<compact_for_query<(emit_only_live_rows)1, query_result_builder> >&&, bool) (mr=..., c=c@entry=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x5175321, DIE 0x52d0d13>, reverse_mutations=reverse_mutations@entry=false)
    at mutation_reader.hh:431
#37 0x00000000009676f5 in data_query (s=..., source=..., range=..., slice=..., row_limit=row_limit@entry=100, partition_limit=4294967295, query_time=..., builder=..., trace_ptr=...)
    at mutation_partition.cc:1962
#38 0x000000000072a88d in column_family::<lambda(query::result_memory_accounter)>::<lambda()>::operator()(void) const (__closure=__closure@entry=0x7ffd2007e8e0) at database.cc:2793
#39 0x000000000078e3a2 in seastar::do_until_continued<column_family::query(schema_ptr, const query::read_command&, query::result_request, const partition_range_vector&, tracing::trace_state_ptr, query::result_memory_limiter&, uint64_t)::<lambda(query::result_memory_accounter)> mutable::<lambda()>, std::_Bind<std::_Mem_fn<bool (query_state::*)() const>(query_state*)> > (
    p=<error reading variable: access outside bounds of object referenced via synthetic pointer>, action=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x355089d>, 
    stop_cond=<optimized out>) at /data2/shlomi/scylla/seastar/core/future-util.hh:155
#40 seastar::do_until<column_family::query(schema_ptr, const query::read_command&, query::result_request, const partition_range_vector&, tracing::trace_state_ptr, query::result_memory_limiter&, uint64_t)::<lambda(query::result_memory_accounter)> mutable::<lambda()>, std::_Bind<std::_Mem_fn<bool (query_state::*)() const>(query_state*)> > (
    action=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x3626ccf>, stop_cond=<optimized out>, this=<optimized out>) at /data2/shlomi/scylla/seastar/core/future-util.hh:330
#41 column_family::<lambda(query::result_memory_accounter)>::operator() (accounter=..., __closure=0x7ffd2007e980) at database.cc:2790
#42 seastar::apply_helper<column_family::query(schema_ptr, const query::read_command&, query::result_request, const partition_range_vector&, tracing::trace_state_ptr, query::result_memory_limiter&, uint64_t)::<lambda(query::result_memory_accounter)>, std::tuple<query::result_memory_accounter>&&, std::integer_sequence<long unsigned int, 0ul> >::apply (
    args=args@entry=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x3094a1d>, 
    func=func@entry=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x354fd0c>) at ./seastar/core/apply.hh:36
#43 seastar::apply<column_family::query(schema_ptr, const query::read_command&, query::result_request, const partition_range_vector&, tracing::trace_state_ptr, query::result_memory_limiter&, uint64_t)::<lambda(query::result_memory_accounter)>, query::result_memory_accounter> (args=<optimized out>, func=<optimized out>) at ./seastar/core/apply.hh:44
#44 seastar::futurize<seastar::future<seastar::lw_shared_ptr<query::result> > >::apply<column_family::query(schema_ptr, const query::read_command&, query::result_request, const partition_range_vector&, tracing::trace_state_ptr, query::result_memory_limiter&, uint64_t)::<lambda(query::result_memory_accounter)>, query::result_memory_accounter>(<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x3549ac9>, <unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x3094a1d>) (
    func=func@entry=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x3549ac9>, 
    args=args@entry=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x3094a1d>) at ./seastar/core/future.hh:1302
#45 0x000000000079d046 in seastar::future<query::result_memory_accounter>::then<column_family::query(schema_ptr, const query::read_command&, query::result_request, const partition_range_vector&, tracing::trace_state_ptr, query::result_memory_limiter&, uint64_t)::<lambda(query::result_memory_accounter)> > (func=<unknown type in /data2/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x2bbb080, DIE 0x36262a3>, 
    this=0x7ffd2007eaf0) at ./seastar/core/future.hh:890
#46 column_family::query (this=<optimized out>, s=..., cmd=..., request=query::result_request::only_result, partition_ranges=std::vector of length 1, capacity 1 = {...}, trace_state=..., memory_limiter=..., 
    max_size=1048576) at database.cc:2803
.
.
```

**Comment by tgrabiec** [comment]
Looks like it's never been implemented.

**Comment by haaawk** [comment]
I'm on it.

**Comment by haaawk** [comment]
I've sent the fix here: https://groups.google.com/forum/#!topic/scylladb-dev/_BfXec3_dzI

**Comment by haaawk** [comment]
The fix for this issue was merged into master so probably we can close it now.

**Comment by tgrabiec** [comment]
Fixed by a4b6cfe8f099829260e46bad2b117624a58250ad

**Comment by avikivity** [comment]
2.0 backport needed?

**Comment by tgrabiec** [comment]
@avikivity Not strictly needed, we've been forever missing this functionality. I think it's safe to backport though.

**Comment by haaawk** [comment]
Pekka was already asking whether to backport it. Not sure if he did though.

**Comment by avikivity** [comment]
Let's not backport it then, so 2.0 can stabilize.

If further backports are needed and the lack of this patch gets in the way, then we can backport it.

**Comment by penberg** [comment]
@haaawk I didn't backport the commit.
