### ISSUE TITLE
Migration to v3 schema tables changes layout of compact tables in an incompatible way

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2555]
*Installation details*
Scylla version (or git commit hash): master, 2.0

This affects so called "static compact" tables, which are compact tables with non-compound cell name. For instance:

```
CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    c0 blob,
    c1 blob) with COMPACT STORAGE;
```

`legacy_schema_migrator` will change the layout so that columns are static instead of regular, and cells will now be stored in the static row instead of a regular row.

This causes problems in a mixed cluster, since old nodes are using and expecting the old layout.

The following errors can be found during mutation replication:

On new node:
```
WARN  2017-07-07 18:40:42,931 [shard 0] storage_proxy - Failed to apply mutation from 127.0.0.2#0: std::out_of_range (regular column id 1 >= 1)
```

On old node:
```
WARN  2017-07-07 18:40:42,910 [shard 0] storage_proxy - Failed to apply mutation from 127.0.0.1#0: std::out_of_range (static column id 0 >= 0)
```

**Comment by tgrabiec** [comment]
Not doing the layout conversion results in the following error from Cassandra tools:

```
Exception in thread "main" java.lang.AssertionError: For table keyspace1.standard1, isDense=false, isCompound=false, clustering=[]
	at org.apache.cassandra.config.CFMetaData.<init>(CFMetaData.java:281)
	at org.apache.cassandra.config.CFMetaData.create(CFMetaData.java:366)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchTable(SchemaKeyspace.java:954)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchTables(SchemaKeyspace.java:928)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspace(SchemaKeyspace.java:891)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspacesWithout(SchemaKeyspace.java:868)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchNonSystemKeyspaces(SchemaKeyspace.java:856)
	at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:136)
	at org.apache.cassandra.config.Schema.loadFromDiskForTool(Schema.java:145)
	at com.scylladb.tools.SSTableExport.metadataFromSSTable(SSTableExport.java:26)
	at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:192)
	at com.scylladb.tools.SSTableExport.main(SSTableExport.java:37)

```

**Comment by tgrabiec** [comment]
The new layout moves old regular columns to the static row and adds the synthetic clustering and regular columns in order to support thrift tables with column_metadata (thrift static tables). Such tables should support insertions of columns whose names are not defined in the column_metadata clause, but any names which match the comparator. Such insertions are translated into CQL insertion with the clustering key derived from the cell name and with the only regular column set to insertion's value.

It wasn't a problem for us because we don't support such insertions: https://github.com/scylladb/scylla/issues/1474

We can keep the old layout in memory as long as we don't support #1474. Once we do, we will have to make a similar layout change.

**Comment by tgrabiec** [comment]
One reason embracing C* model for #1474 would be problematic is that "static" columns (from column_metadata) could occur at any position in an sstable, while our readers are required to emit the static row before all clustered rows.
