### ISSUE TITLE
Updating column family schema through thrift by adding column metadata causes abort

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2588]
*Installation details*
Scylla version: tested with 1.7.2

Relates to https://issues.apache.org/jira/browse/CASSANDRA-11502.

```
scylla-1.7.2: schema.cc:800: sstring cell_comparator::to_sstring(const schema&): Assertion `s.is_dense()' failed.
```

test case:

```python
        cf = CfDef(ks_name, 'test_table2',
                   key_validation_class='UTF8Type',
                   comparator_type='LongType',
                   default_validation_class='UTF8Type')
        thrift_client.system_add_column_family(cf)
        cf.column_metadata = [
            ColumnDef(_i64(4), 'Int32Type')
        ]
        thrift_client.system_update_column_family(cf)
```

```
(gdb) bt
#0  0x00007ffff32ab64b in raise () from /lib64/libc.so.6
#1  0x00007ffff32ad450 in abort () from /lib64/libc.so.6
#2  0x00007ffff32a3d1a in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff32a3d92 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000840548 in cell_comparator::to_sstring (s=...) at schema.cc:800
#5  0x0000000000e3be25 in db::schema_tables::make_table_mutations (table=..., timestamp=1499872435827547, 
    with_columns_and_triggers=<optimized out>) at db/schema_tables.cc:1225
#6  0x0000000000e3db16 in db::schema_tables::make_schema_mutations (s=..., timestamp=<optimized out>, with_columns=with_columns@entry=true)
    at db/schema_tables.cc:1879
#7  0x0000000000849b4b in frozen_schema::<lambda()>::operator() (__closure=<optimized out>) at frozen_schema.cc:35
#8  frozen_schema::frozen_schema (this=0x7fffffffcce0, s=...) at frozen_schema.cc:42
#9  0x000000000084ea53 in schema_registry::learn (this=0x7ffff7fb5cc8, s=...) at schema_registry.cc:63
#10 0x000000000077ce4b in database::add_column_family (this=this@entry=0x600000557c10, ks=..., schema=..., cfg=...) at database.cc:2120
#11 0x00000000007c1473 in database::add_column_family_and_make_directory (this=this@entry=0x600000557c10, schema=...) at database.cc:2149
#12 0x00000000007c6c28 in database::<lambda()>::<lambda(db::schema_tables::schema_result_value_type&)>::<lambda(std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > >)>::<lambda(auto:132&)>::operator()<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > (t=..., __closure=<optimized out>) at database.cc:2005
#13 <lambda(parallel_for_each_state&)>::operator() (state=..., __closure=<optimized out>)
    at /home/tgrabiec/src/scylla2/seastar/core/future-util.hh:95
#14 do_with<parallel_for_each_state, parallel_for_each(Iterator, Iterator, Func&&) [with Iterator = std::_Rb_tree_iterator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > >; Func = database::parse_system_tables(distributed<service::storage_proxy>&)::<lambda()>::<lambda(db::schema_tables::schema_result_value_type&)>::<lambda(std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> >)>::<lambda(auto:132&)>]::<lambda(parallel_for_each_state&)> > (f=..., rvalue=...)
    at /home/tgrabiec/src/scylla2/seastar/core/do_with.hh:55
#15 parallel_for_each<std::_Rb_tree_iterator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > >, database::parse_system_tables(distributed<service::storage_proxy>&)::<lambda()>::<lambda(db::schema_tables::schema_result_value_type&)>::<lambda(std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> >)>::<lambda(auto:132&)> > (func=..., end=..., begin=...)
    at /home/tgrabiec/src/scylla2/seastar/core/future-util.hh:116
#16 database::<lambda()>::<lambda(db::schema_tables::schema_result_value_type&)>::<lambda(std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > >)>::operator() (
    tables=std::map with 7237412644498207843 elements<error reading variable: Cannot access memory at address 0x129>, 
    __closure=0x7fffffffd130) at database.cc:2006
#17 apply_helper<database::parse_system_tables(distributed<service::storage_proxy>&)::<lambda()>::<lambda(db::schema_tables::schema_result_value_type&)>::<lambda(std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > >)>, std::tuple<std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > > >&&, std::integer_sequence<long unsigned int, 0> >::apply (
    args=..., func=...) at /home/tgrabiec/src/scylla2/seastar/core/apply.hh:34
#18 apply<database::parse_system_tables(distributed<service::storage_proxy>&)::<lambda()>::<lambda(db::schema_tables::schema_result_value_typ---Type <return> to continue, or q <return> to quit---
e&)>::<lambda(std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> >)>, std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > > > (args=..., func=...) at /home/tgrabiec/src/scylla2/seastar/core/apply.hh:42
#19 futurize<future<> >::apply<database::parse_system_tables(distributed<service::storage_proxy>&)::<lambda()>::<lambda(db::schema_tables::schema_result_value_type&)>::<lambda(std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> >)>, std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > > >(database::<lambda()>::<lambda(db::schema_tables::schema_result_value_type&)>::<lambda(std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > >)> &&, std::tuple<std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<schema const>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<basic_sstring<char, unsigned int, 15> const, lw_shared_ptr<schema const> > > > > &&) (func=..., args=...)
    at /home/tgrabiec/src/scylla2/seastar/core/future.hh:1267
#20 0x00000000007cc17e in future<std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<schema const>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<basic_sstring<char, unsigned int, 15> const, lw_shared_ptr<schema const> > > > >::<lambda(auto:4&&)>::operator()<future_state<std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > > > > (state=..., 
    __closure=0x600005428820) at /home/tgrabiec/src/scylla2/seastar/core/future.hh:872

#21 continuation<future<T>::then(Func&&) [with Func = database::parse_system_tables(distributed<service::storage_proxy>&)::<lambda()>::<lambda(db::schema_tables::schema_result_value_type&)>::<lambda(std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> >)>; Result = future<>; T = {std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > >}]::<lambda(auto:4&&)>, std::map<basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema>, std::less<basic_sstring<char, unsigned int, 15> >, std::allocator<std::pair<const basic_sstring<char, unsigned int, 15>, lw_shared_ptr<const schema> > > > >::run(void) (this=0x6000054287e0)
    at /home/tgrabiec/src/scylla2/seastar/core/future.hh:390
#22 0x0000000000493cda in reactor::run_tasks (this=this@entry=0x600000420000, tasks=...) at core/reactor.cc:2025
#23 0x00000000004e1863 in reactor::run (this=0x600000420000) at core/reactor.cc:2467
#24 0x000000000055fb7e in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffdb20, 
    ac=ac@entry=4, av=av@entry=0x7fffffffdd98, func=...) at core/app-template.cc:131
#25 0x0000000000424f68 in main (ac=4, av=0x7fffffffdd98) at main.cc:659
```

Works fine with C* 2.1.17.

**Comment by duarten** [comment]
We should reject the update in thrift, because that will create a mixed CF. Adding the CF will add a clustering key, but updating it will mark the schema as not dense, so that assert will fail down the line.

**Comment by tgrabiec** [comment]
Right. Refs #1474
