### ISSUE TITLE
Scylla crashes on "select *" CL=QUORUM queries 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2593]
*Installation details*
Scylla version (or git commit hash): 2.0
Cluster size: 6

```
  ccm create scylla-6 --scylla --vnodes -n 6 --install-dir=/home/shlomi/scylla-ccm/../scylla
  ccm start
  ccm node1 stress write n=1000
  ccm node1 cqlsh
    select * from keyspace1.standard1;
    alter KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : '4'};
    consistency quorum;
    select * from keyspace1.standard1;  
```

backtrace

```
#0  std::unique_ptr<bytes_ostream::chunk, std::default_delete<bytes_ostream::chunk> >::get (this=this@entry=0x8) at /usr/include/c++/5.3.1/bits/unique_ptr.h:305
#1  std::unique_ptr<bytes_ostream::chunk, std::default_delete<bytes_ostream::chunk> >::operator bool (this=this@entry=0x8) at /usr/include/c++/5.3.1/bits/unique_ptr.h:319
#2  bytes_ostream::is_linearized (this=this@entry=0x8) at ./bytes_ostream.hh:231
#3  ser::as_input_stream (b=...) at serializer_impl.hh:476
#4  frozen_mutation::mutation_view (this=this@entry=0x8) at frozen_mutation.cc:51
#5  0x0000000000928671 in frozen_mutation::partition (this=this@entry=0x8) at frozen_mutation.cc:121
#6  0x0000000000de9620 in service::data_read_resolver::get_last_row (s=..., p=..., is_reversed=<optimized out>) at service/storage_proxy.cc:2060
#7  0x0000000000df4e8f in service::data_read_resolver::get_last_row (replica=1, versions=std::vector of length 6, capacity 8 = {...}, is_reversed=false, s=...) at service/storage_proxy.cc:2078
#8  service::data_read_resolver::got_incomplete_information_across_partitions (this=this@entry=0x6000050c3f50, s=..., cmd=..., last_reconciled_row=..., rp=std::vector of length 6, capacity 6 = {...}, 
    versions=std::vector of length 6, capacity 8 = {...}, is_reversed=false) at service/storage_proxy.cc:2123
#9  0x0000000000e1c54c in service::data_read_resolver::got_incomplete_information (versions=std::vector of length 6, capacity 8 = {...}, rp=std::vector of length 6, capacity 6 = {...}, 
    original_partition_limit=4294967197, original_per_partition_limit=4294967295, original_row_limit=2, cmd=..., s=..., this=0x6000050c3f50) at service/storage_proxy.cc:2200
#10 service::data_read_resolver::resolve (this=0x6000050c3f50, schema=..., cmd=..., original_row_limit=2, original_per_partition_limit=4294967295, original_partition_limit=4294967197)
    at service/storage_proxy.cc:2355
#11 0x0000000000e20aab in service::abstract_read_executor::reconcile(db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, seastar::lw_shared_ptr<query::read_command>)::{lambda(seastar::future<>)#2}::operator()(seastar::future<>) const (__closure=__closure@entry=0x6000052463b0, f=...) at service/storage_proxy.cc:2544
#12 0x0000000000e21672 in seastar::do_void_futurize_apply<service::abstract_read_executor::reconcile(db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, seastar::lw_shared_ptr<query::read_command>)::{lambda(seastar::future<>)#2}, seastar::future<> >(std::result_of&&, seastar::future<>&&) (
    func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x10440854, DIE 0x10ba646f>) at ./seastar/core/future.hh:1247
#13 0x0000000000e21b84 in seastar::futurize<void>::apply<service::abstract_read_executor::reconcile(db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, seastar::lw_shared_ptr<query::read_command>)::{lambda(seastar::future<>)#2}, seastar::future<> >(service::abstract_read_executor::reconcile(db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, seastar::lw_shared_ptr<query::read_command>)::{lambda(seastar::future<>)#2}&&, seastar::future<>&&) (func=<optimized out>)
    at ./seastar/core/future.hh:1295
#14 _ZZN7seastar6futureIJEE12then_wrappedIZN7service22abstract_read_executor9reconcileEN2db17consistency_levelENSt6chrono10time_pointINS_12lowres_clockENS7_8durationIlSt5ratioILl1ELl1000EEEEEENS_13lw_shared_ptrIN5query12read_commandEEEEUlS1_E0_S1_EET0_OT_ENUlSM_E_clINS_12future_stateIJEEEEEDaSM_ (state=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x10440854, DIE 0x10ba7364>, __closure=0x600005246390)
    at ./seastar/core/future.hh:940
#15 _ZN7seastar12continuationIZNS_6futureIJEE12then_wrappedIZN7service22abstract_read_executor9reconcileEN2db17consistency_levelENSt6chrono10time_pointINS_12lowres_clockENS8_8durationIlSt5ratioILl1ELl1000EEEEEENS_13lw_shared_ptrIN5query12read_commandEEEEUlS2_E0_S2_EET0_OT_EUlSN_E_JEE3runEv (this=0x600005246380) at ./seastar/core/future.hh:395
#16 0x0000000000495d50 in seastar::reactor::run_tasks (this=this@entry=0x60000078e000, tasks=...) at core/reactor.cc:2316
#17 0x00000000004e932b in seastar::reactor::run (this=0x60000078e000) at core/reactor.cc:2774
#18 0x000000000056d123 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7ffff151d3a0, ac=ac@entry=23, av=av@entry=0x7ffff151d638, 
    func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0xa25dd3, DIE 0xb27a66>) at core/app-template.cc:142
#19 0x000000000041e553 in main (ac=23, av=0x7ffff151d638) at main.cc:682
```

**Comment by avikivity** [comment]
Please try to provide more detail in the subject line so that queries that return just the subject line have some information in them.
