### ISSUE TITLE
Cannot allocate memory in checking version

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2619]
*Installation details*
Scylla version (or git commit hash):  scylla-1.7.1-0.20170607.dbbf99d.el7.centos.x86_64
Cluster size: 3 dcs, 5 + 5 + 3 db nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

*description*
Scylla-server was running, host still has 1+ G memory.
scylla failed to allocate memory in checking version info.

The version/help message don't need to really run scylla service. Can we reduce the memory allocation in this situation?

*more info*

```
[scylla-test@sct-mdcdev-scylla-db-node-f3f1aa85-1-15 ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          52171       49671        1383         368        1116        1619
Swap:             0           0           0
[scylla-test@sct-mdcdev-scylla-db-node-f3f1aa85-1-15 ~]$ scylla --version
FATAL: Exception during startup, aborting: std::system_error (error system:12, Cannot allocate memory
```

**Comment by asias** [comment]
Can you run `strace -fF -o t.log scylla --version` to see which system call is failling to allocate?

**Comment by amoskong** [comment]
Attached the strace log: [github-issue-2619-strace.txt](https://github.com/scylladb/scylla/files/1165693/github-issue-2619-strace.txt)

**Comment by amoskong** [comment]
This can be reproduced with scylla-1.7.3-0.20170719.41b4055.el7.centos.x86_64.
And it blocked current (multi-dc) longevity test. I will try to workaround it.

**Comment by asias** [comment]
It failed to allocate 1.6GB of ram. 

Does the following work?

scylla -m 1G  --version
scylla -m 8G  --version
scylla -m 16G  --version
scylla -m 32G  --version

**Comment by asias** [comment]
Amos, can you run:

$ gdb --args scylla --version

and get the backtrace?

**Comment by amoskong** [comment]
It's failed to attach the process, the output is very similar as this:
```
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...../../gdb/cp-support.c:1595: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE6_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
Attempting to dump core.
../../gdb/cp-support.c:1608: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE6_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) n
```

**Comment by tgrabiec** [comment]
This message is supposed to be benign. After you type n it should let you into the session. Though symbol reading may take a while

**Comment by asias** [comment]
Btw, we need Scylla-gdb.

**Comment by amoskong** [comment]
```
[root@sct-mdcdev-scylla-db-node-b5daea3f-2-60 scylla-test]# free 
              total        used        free      shared  buff/cache   available
Mem:       53423364    50672664      424836     1655080     2325864      590964
Swap:             0           0           0

[root@sct-mdcdev-scylla-db-node-b5daea3f-2-60 scylla-test]# scylla -m 1G --version
1.7.3-0.20170719.41b4055
[root@sct-mdcdev-scylla-db-node-b5daea3f-2-60 scylla-test]# scylla -m 8G --version
1.7.3-0.20170719.41b4055
[root@sct-mdcdev-scylla-db-node-b5daea3f-2-60 scylla-test]# scylla -m 16G --version
FATAL: Exception during startup, aborting: std::system_error (error system:12, Cannot allocate memory)
```

**Comment by asias** [comment]
Interesting, it failed with more memory assigned.

**Comment by amoskong** [comment]
I got a coredump when I execute `scylla -m 4G --version` on that machine.

```
[root@sct-mdcdev-scylla-db-node-b5daea3f-2-60 coredump]# gdb /usr/bin/scylla core.scylla.1003.02f289a56e91401e83a
...
Core was generated by `scylla -m 4G --version'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f521483e1d7 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56        return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
[Current thread is 1 (Thread 0x7f52101ff700 (LWP 28284))]
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.166-2.el7.x86_64 elfutils-libs-0.166-2.el7.x86_64 gmp-6.0.0-1
2.el7_1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-8.el7.x86_64 libcom_err-1.42.9-9.el7.x86
_64 libffi-3.0.13-18.el7.x86_64 libgcrypt-1.5.3-13.el7_3.1.x86_64 libgpg-error-1.12-3.el7.x86_64 libselinux-2.5-6.el7.x86_64 libtasn1-3.8-3.el7.x86_64 libtool-ltd
l-2.4.2-22.el7_3.x86_64 nettle-2.7.1-8.el7.x86_64 nss-softokn-freebl-3.16.2.3-14.4.el7.x86_64 openssl-libs-1.0.1e-60.el7_3.1.x86_64 p11-kit-0.20.7-3.el7.x86_64 pc
re-8.32-15.el7_2.1.x86_64 trousers-0.3.13-1.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64
(gdb) bt
#0  0x00007f521483e1d7 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f521483fa08 in __GI_abort () at abort.c:119
#2  0x0000000001a5330d in __gnu_cxx::__verbose_terminate_handler() ()
#3  0x00000000019bb276 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x0000000001a530c9 in __cxa_call_terminate ()
#5  0x00000000019babc5 in __gxx_personality_v0 ()
#6  0x00007f5216a80903 in _Unwind_RaiseException_Phase2 (
    exc=exc@entry=0x603000004fa0, context=context@entry=0x7f52101f6e40)
    at ../../../libgcc/unwind.inc:62
#7  0x00007f5216a80e37 in _Unwind_Resume (exc=exc@entry=0x603000004fa0)
    at ../../../libgcc/unwind.inc:230
#8  0x000000000053367d in __gnu_cxx::new_allocator<unsigned int>::deallocate (
    this=<optimized out>, __p=<optimized out>)
    at /opt/scylladb/include/c++/5.3.1/ext/new_allocator.h:110
#9  std::allocator_traits<std::allocator<unsigned int> >::deallocate (__a=...,
    __n=<optimized out>, __p=<optimized out>)
    at /opt/scylladb/include/c++/5.3.1/bits/alloc_traits.h:386
#10 std::_Vector_base<unsigned int, std::allocator<unsigned int> >::_M_deallocate (this=<optimized out>, __n=<optimized out>, __p=<optimized out>)
    at /opt/scylladb/include/c++/5.3.1/bits/stl_vector.h:178
#11 std::_Vector_base<unsigned int, std::allocator<unsigned int> >::~_Vector_base (this=<optimized out>, __in_chrg=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at /opt/scylladb/include/c++/5.3.1/bits/stl_vector.h:160
#12 std::vector<unsigned int, std::allocator<unsigned int> >::~vector (
    this=<optimized out>, __in_chrg=<optimized out>)
    at /opt/scylladb/include/c++/5.3.1/bits/stl_vector.h:425
#13 smp::<lambda(unsigned int)>::operator() (shard=<optimized out>,
    __closure=<optimized out>) at core/reactor.cc:3353
#14 smp::<lambda()>::operator()(void) const (__closure=0x6000000cc680)
    at core/reactor.cc:3389
#15 0x000000000058ed9e in std::function<void ()>::operator()() const (
    this=<optimized out>) at /opt/scylladb/include/c++/5.3.1/functional:2271
#16 posix_thread::start_routine (arg=<optimized out>) at core/posix.cc:50
#17 0x00007f5214bd1dc5 in start_thread (arg=0x7f52101ff700)
    at pthread_create.c:308
#18 0x00007f521490076d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```
