### ISSUE TITLE
connect error: unconfigured table schema_keyspaces

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2703]
*Installation details*
Scylla version (or git commit hash): 2.0.rc2-0.20170815.8370e1b.el7.centos
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7
Cassandra-driver: 2.7.2

Connect script:
```
[amos@amos-centos7 ~]$ cat c.py
from cassandra.cluster import Cluster

cluster = Cluster()
session = cluster.connect()
rows = session.execute('select * from kb1009.standard1 limit 10;')
for row in rows:
    print row[0]
```
cqlsh works well:
```
[amos@amos-centos7 ~]$ cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> 
```
error to connect cluster by cassandra-driver:
```
[amos@amos-centos7 ~]$ python c.py
Traceback (most recent call last):
  File "c.py", line 4, in <module>
    session = cluster.connect()
  File "cassandra/cluster.py", line 820, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 846, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 840, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 2088, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 2123, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1': InvalidRequest(u'code=2200 [Invalid query] message="unconfigured table schema_keyspaces"',)})
```

driver info:
```
[amos@amos-centos7 ~]$ pip show cassandra-driver
Name: cassandra-driver
Version: 2.7.2
Summary: Python driver for Cassandra
Home-page: http://github.com/datastax/python-driver
Author: Tyler Hobbs
Author-email: tyler@datastax.com
License: UNKNOWN
Location: /usr/lib64/python2.7/site-packages
Requires: six, futures
```

**Comment by amoskong** [comment]
Upgrade the cassandra-driver from `2.7.2` to `3.10`, then the problem disappears.

```
[amos@amos-centos7 ~]$ sudo pip install cassandra-driver==3.10
Collecting cassandra-driver==3.10
  Downloading cassandra-driver-3.10.tar.gz (217kB)
    100% |████████████████████████████████| 225kB 3.6MB/s 
Requirement already satisfied: six>=1.9 in /usr/lib/python2.7/site-packages (from cassandra-driver==3.10)
Requirement already satisfied: futures in /usr/lib/python2.7/site-packages (from cassandra-driver==3.10)
Installing collected packages: cassandra-driver
  Found existing installation: cassandra-driver 2.7.2
    Uninstalling cassandra-driver-2.7.2:
      Successfully uninstalled cassandra-driver-2.7.2
  Running setup.py install for cassandra-driver ... /

done
Successfully installed cassandra-driver-3.10
[amos@amos-centos7 ~]$ python c.py
LNP20N43M0
411PK8P261
9733781010
P29L2298P0
9815N7P411
M126M08KP0
36835LN8N0
3O5L187PO0
87150P3K21
223O779L40
```

**Comment by penberg** [comment]
Why are you testing with older driver versions? Scylla 2.0 requires Python driver 3.5 or later. See the "system impacts" section in the release notes:

https://groups.google.com/forum/#!topic/scylladb-users/TQwSgcAYJeU/discussion

**Comment by amoskong** [comment]
Ok, we are using 3.10 casandra-driver for testing. Let's close this issue. Thanks.
