### ISSUE TITLE
MATERIALIZED VIEW C-S: [Control connection] Unexpected error while refreshing schema / node list and token map

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2704]
*Installation details*
Scylla version (or git commit hash): scylla-2.0.rc1-0.20170811.ea933b4
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Error info:
There are two kinds of control connection error from cassandra-stress (`MATERIALIZED VIEW`). and the c-s client exits. But other `two (non-MV)` workload are fine.

Workload info:
Two loaders
each load has 3 kinds of workloade
- cassandra-stress write cl=QUORUM duration=1m -schema 'replication(factor=1) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=10 -pop seq=1..  100000000
- cassandra-stress counter_write cl=QUORUM duration=5760m -schema 'replication(factor=3) compaction(strategy=DateTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1000 -pop seq=1..1000000
- cassandra-stress user profile=/tmp/cs_mv_profile.yaml ops'(insert=3,read1=1,read2=1,read3=1)' cl=QUORUM duration=1m -port jmx=6868 -mode cql3 native -rate threads=10 -node 127.0.0.1

[cs_mv_profile.yaml.txt](https://github.com/scylladb/scylla/files/1232952/cs_mv_profile.yaml.txt)

Error 1:
[Control connection] Unexpected error while refreshing schema
This error occurs after `MATERIALIZED VIEW` workload start.

Error 2:
[Control connection] Unexpected error while refreshing node list and token map
This error occurs during decommission testing.

**Comment by amoskong** [comment]
One loader error during previous Drain testing:
```
08-17 17:25:21,874 | [10.240.0.103] [stdout] Aug 17 17:25:20 err    |  [shard 14] view - Error applying view update to 10.240.0.106: exceptions::mutation_writ
e_timeout_exception (Operation timed out for mview.users_by_last_name - received only 0 responses from 1 CL=ONE.)
...
08-17 17:28:09,202 |  insert,      2705003,    3519,    3519,    3519,    11.4,     3.6,    53.0,   137.7,   370.3,   421.2,  706.1,  0.01348,      0,      0,       0,       0,       0,       0
08-17 17:28:09,203 |  read1,        901981,    1217,    1188,    1188,    16.5,     4.2,    61.2,   160.1,  2507.5,  2523.9,  706.1,  0.01348,      0,      0,       0,       0,       0,       0
08-17 17:28:09,203 |  read2,        903584,    1199,    1167,    1167,    18.6,     4.1,    56.3,   157.9,  2552.7,  5008.2,  706.1,  0.01348,      0,      0,       0,       0,       0,       0
08-17 17:28:09,204 |  read3,        900783,    1259,    1225,    1225,    16.1,     4.4,    54.9,   160.1,  2508.9,  2657.9,  706.1,  0.01348,      0,      0,       0,       0,       0,       0
08-17 17:28:15,273 |  com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (3 responses were required but only 2 replica responded)
08-17 17:28:15,273 |  java.util.NoSuchElementException
08-17 17:28:15,274 |  java.util.NoSuchElementException
08-17 17:28:15,274 |  java.util.NoSuchElementException
08-17 17:28:15,275 |  java.util.NoSuchElementException
08-17 17:28:15,275 |  java.util.NoSuchElementException
08-17 17:28:15,275 |  java.util.NoSuchElementException
08-17 17:28:15,276 |  java.util.NoSuchElementException
08-17 17:28:15,277 |  java.util.NoSuchElementException
08-17 17:28:15,277 |  java.util.NoSuchElementException
08-17 17:28:15,277 |  java.io.IOException: Operation x10 on key(s) [}#A=JXD4]: Error executing: (NoSuchElementException)
08-17 17:28:15,278 |  
08-17 17:28:15,278 |  	at org.apache.cassandra.stress.Operation.error(Operation.java:135)
08-17 17:28:15,279 |  	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
08-17 17:28:15,279 |  	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.run(SchemaQuery.java:156)
08-17 17:28:15,279 |  	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
08-17 17:28:15,821 |  com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (3 responses were required but only 2 replica responded)
08-17 17:28:15,822 |  java.util.NoSuchElementException
08-17 17:28:15,822 |  java.util.NoSuchElementException
08-17 17:28:15,822 |  java.util.NoSuchElementException
08-17 17:28:15,823 |  java.util.NoSuchElementException
08-17 17:28:15,823 |  java.util.NoSuchElementException
08-17 17:28:15,823 |  java.util.NoSuchElementException
08-17 17:28:15,824 |  java.util.NoSuchElementException
08-17 17:28:15,824 |  java.util.NoSuchElementException
08-17 17:28:15,824 |  java.util.NoSuchElementException
08-17 17:28:15,824 |  java.io.IOException: Operation x10 on key(s) [GW[Rk.VCg//fqu:/mKhJ]: Error executing: (NoSuchElementException)
08-17 17:28:15,825 |  
08-17 17:28:15,825 |  	at org.apache.cassandra.stress.Operation.error(Operation.java:135)
08-17 17:28:15,825 |  	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
08-17 17:28:15,826 |  	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.run(SchemaQuery.java:156)
08-17 17:28:15,826 |  	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
08-17 17:28:16,026 |  com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (3 responses were required but only 2 replica responded)
08-17 17:28:16,026 |  java.util.NoSuchElementException
08-17 17:28:16,026 |  java.util.NoSuchElementException
08-17 17:28:16,027 |  java.util.NoSuchElementException
08-17 17:28:16,027 |  java.util.NoSuchElementException
08-17 17:28:16,027 |  java.util.NoSuchElementException
08-17 17:28:16,028 |  java.util.NoSuchElementException
08-17 17:28:16,028 |  java.util.NoSuchElementException
08-17 17:28:16,028 |  java.util.NoSuchElementException
08-17 17:28:16,029 |  java.util.NoSuchElementException
08-17 17:28:16,029 |  java.io.IOException: Operation x10 on key(s) [o}P	IE27N
                                                                             XC I4la}$2n]: Error executing: (NoSuchElementException)
08-17 17:28:16,029 |  
08-17 17:28:16,030 |  	at org.apache.cassandra.stress.Operation.error(Operation.java:135)
08-17 17:28:16,030 |  	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
08-17 17:28:16,030 |  	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.run(SchemaQuery.java:156)
08-17 17:28:16,030 |  	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
```

The loader error during decommission testing:
```
08-17 17:39:40,561 | sdcm.nemesis.ChaosMonkey: Decommission Node amostmp-longevity-50gb-4d-db-node-0f260910-0-5 [35.196.143.231 | 10.240.0.107] (seed: False) 

08-17 17:39:41,602 | [10.240.0.102] [stdout] Aug 17 17:39:41 info   |  [shard 0] gossip - InetAddress 10.240.0.107 is now DOWN, status = LEFT
08-17 17:39:43,046 | [10.240.0.106] [stdout] Aug 17 17:39:42 info   |  [shard 0] gossip - InetAddress 10.240.0.107 is now DOWN, status = LEFT
08-17 17:39:44,129 | [10.240.0.104] [stdout] Aug 17 17:39:44 info   |  [shard 0] gossip - InetAddress 10.240.0.107 is now DOWN, status = LEFT
08-17 17:39:44,286 | [10.240.0.103] [stdout] Aug 17 17:39:44 info   |  [shard 0] gossip - InetAddress 10.240.0.107 is now DOWN, status = LEFT
08-17 17:39:44,286 | Message pushed from server: <EventMessage(event_type=u'STATUS_CHANGE', trace_id=None, event_args={'change_type': u'DOWN', 'address': ('10
0.107', 9042)}, str
08-17 17:39:49,737 | [10.240.0.107] [stderr] Connection to 10.240.0.107 closed by remote host.
08-17 17:39:49,737 | [10.240.0.107] [stderr] Connection to 10.240.0.107 closed.
08-17 17:40:02,356 | Sending options message heartbeat on idle connection (77978960) 35.190.137.79
08-17 17:40:02,519 | Received options response on connection (77978960) from 35.190.137.79

08-17 17:40:14,097 |  ERROR 17:40:14 [Control connection] Unexpected error while refreshing node list and token map
08-17 17:40:14,097 |  java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.OperationTimedOutException: [amostmp-longevity-50gb-4d-db-node-0f260910-0-1.c.skilled-adapter-452.internal/10.240.0.103] Operation timed out
08-17 17:40:14,098 |  	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[guava-18.0.jar:na]
08-17 17:40:14,098 |  	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[guava-18.0.jar:na]
08-17 17:40:14,099 |  	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[guava-18.0.jar:na]
08-17 17:40:14,099 |  	at com.datastax.driver.core.ControlConnection.refreshNodeListAndTokenMap(ControlConnection.java:549) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
08-17 17:40:14,099 |  	at com.datastax.driver.core.ControlConnection.refreshNodeListAndTokenMap(ControlConnection.java:355) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
08-17 17:40:14,099 |  	at com.datastax.driver.core.Cluster$Manager$NodeListRefreshRequestDeliveryCallback$1.runMayThrow(Cluster.java:2771) [cassandra-driver-core-3.0.1-shaded.jar:na]
08-17 17:40:14,100 |  	at com.datastax.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32) [cassandra-driver-core-3.0.1-shaded.jar:na]
08-17 17:40:14,100 |  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_141]
08-17 17:40:14,101 |  	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_141]
08-17 17:40:14,101 |  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
08-17 17:40:14,101 |  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
08-17 17:40:14,102 |  	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
08-17 17:40:14,102 |  Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [amostmp-longevity-50gb-4d-db-node-0f260910-0-1.c.skilled-adapter-452.internal/10.240.0.103] Operation timed out
08-17 17:40:14,102 |  	at com.datastax.driver.core.DefaultResultSetFuture.onTimeout(DefaultResultSetFuture.java:209) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
08-17 17:40:14,102 |  	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1268) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
08-17 17:40:14,103 |  	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
08-17 17:40:14,103 |  	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
08-17 17:40:14,103 |  	at com.datastax.shaded.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[cassandra-driver-core-3.0.1-shaded.jar:na]
08-17 17:40:14,104 |  	... 1 common frames omitted
```

**Comment by amoskong** [comment]
Snapshot included both drain and decommission tests
![fireshot capture 90 - grafana - scylla per server metrics ma_ - http___35 196 102 61_3000_dashboar](https://user-images.githubusercontent.com/309708/29439342-a789b800-83ef-11e7-8936-7588ea05071f.png)

**Comment by duarten** [comment]
I don't know what I'm supposed to do here.

I see one write timed out when a node was being drained, and maybe that entry was missing when reading? The write timed out because the node was overloaded, and since we don't retry these updates, it was lost.

This happened when reading, and one replica was down (because we were decommissioning it?). The only thing I don't understand is why a read at QUORUM for a RF of 3 requires 3 responses instead of just 2? /cc @gleb-cloudius 

I ran this workload locally without nemesis and everything went fine.

**Comment by duarten** [comment]
Closing in favour of #3080.
