### ISSUE TITLE
reactor stalled for for 4513 ms during major compaction

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla#2846]
*Installation details*
Scylla version (or git commit hash): 2.0.rc5-0.20170925.6e2858a
Cluster size: 4 nodes 1TB
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
might be related to : [https://github.com/scylladb/scylla/issues/2843](https://github.com/scylladb/scylla/issues/2843
)
full log: [scylladb-users-upload.s3.amazonaws.com/2843/log.tar.gz](scylladb-users-upload.s3.amazonaws.com/2843/log.tar.gz)
prometheus data [scylladb-users-upload.s3.amazonaws.com/2843/prometheus-data.tar.gz](scylladb-users-upload.s3.amazonaws.com/2843/prometheus-data.tar.gz)
### event sequence
1.  MajorCompaction nemeiss began on Node 3:
```
2017-09-27 08:38:35,125 nemesis          L0187 DEBUG| sdcm.nemesis.ChaosMonkey: Set current_disruption -> MajorCompaction Node longevity-1tb-7d-2-0-db-node-6280c635-0-3 [35.196.74.152 | 10.240.0.24] (seed: False)
2017-09-27 08:38:35,125 nemesis          L0189 INFO | sdcm.nemesis.ChaosMonkey: MajorCompaction Node longevity-1tb-7d-2-0-db-node-6280c635-0-3 [35.196.74.152 | 10.240.0.24] (seed: False)
2017-09-27 08:38:35,125 remote           L0894 DEBUG| Remote [scylla-test@35.196.74.152]: Running 'nodetool -h localhost compact'
2017-09-27 08:38:35,125 remote           L0097 INFO | [35.196.74.152] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp7X2xwQ -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 35.196.74.152 "nodetool -h localhost compact"'
2017-09-27 08:38:35,487 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:38:35 info   |  [shard 8] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-32be1520a29e11e785d7000000000003/keyspace1-standard1-ka-144472-Data.db:level=2, /var/lib/scylla/data/keyspace1/standard1-32be1520a29e11e785d7000000000003/keyspace1-standard1-ka-144488-Data.db:level=2, ]. 343517728 bytes to 333923943 (~97% of original) in 6943ms = 45.87MB/s. ~314880 total partitions merged to 305755.
```
2. Reactor stalled for 4513 ms:

```
2017-09-27 08:59:51,612 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | Reactor stalled for 2511 ms on shard 8.
2017-09-27 08:59:51,613 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | Backtrace:
2017-09-27 08:59:51,613 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00000000004eef98
2017-09-27 08:59:51,614 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00000000004ef279
2017-09-27 08:59:51,614 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00007fe2de5e95df
2017-09-27 08:59:51,615 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00000000004e99ef
2017-09-27 08:59:51,615 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00007fe2de5e95df
2017-09-27 08:59:51,616 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00007fe2e1c38696
2017-09-27 08:59:51,616 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00000000004fad63
2017-09-27 08:59:51,617 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00000000004e9e94
2017-09-27 08:59:51,617 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00000000005408b7
2017-09-27 08:59:51,617 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x0000000000542120
2017-09-27 08:59:51,618 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x000000000059a58d
2017-09-27 08:59:51,618 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00007fe2de5e1e24
2017-09-27 08:59:51,618 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:51 info   | 0x00007fe2de30f34c
2017-09-27 08:59:58,599 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | Reactor stalled for 4513 ms on shard 2.
2017-09-27 08:59:58,599 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | Backtrace:
2017-09-27 08:59:58,600 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004eef98
2017-09-27 08:59:58,600 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004ef279
2017-09-27 08:59:58,600 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2de5e95df
2017-09-27 08:59:58,600 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004e99ef
2017-09-27 08:59:58,601 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2de5e95df
2017-09-27 08:59:58,601 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2e1c38696
2017-09-27 08:59:58,602 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004fad63
2017-09-27 08:59:58,602 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004e9e94
2017-09-27 08:59:58,602 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000005408b7
2017-09-27 08:59:58,603 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x0000000000542120
2017-09-27 08:59:58,603 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x000000000059a58d
2017-09-27 08:59:58,603 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2de5e1e24
2017-09-27 08:59:58,603 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2de30f34c
2017-09-27 08:59:58,604 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | Reactor stalled for 4513 ms on shard 2.
2017-09-27 08:59:58,604 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | Backtrace:
2017-09-27 08:59:58,604 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004eef98
2017-09-27 08:59:58,604 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004ef279
2017-09-27 08:59:58,605 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2de5e95df
2017-09-27 08:59:58,605 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004e99ef
2017-09-27 08:59:58,605 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2de5e95df
2017-09-27 08:59:58,605 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2e1c38696
2017-09-27 08:59:58,606 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004fad63
2017-09-27 08:59:58,606 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000004e9e94
2017-09-27 08:59:58,606 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00000000005408b7
2017-09-27 08:59:58,606 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x0000000000542120
2017-09-27 08:59:58,607 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x000000000059a58d
2017-09-27 08:59:58,607 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2de5e1e24
2017-09-27 08:59:58,607 remote           L0197 DEBUG| [35.196.74.152] [stdout] Sep 27 08:59:58 info   | 0x00007fe2de30f34c
...
```
decoded backtrace:
```
[harel@longevity-1tb-7d-2-0-db-node-6280c635-0-3 ~]$ addr2line -Cpife /usr/lib/debug/.build-id/e1/50a7ce6189ef13530e65e2bff63bfeb3296990.debug 
0x00000000004eef98
0x00000000004ef279
0x00007fe2de5e95df
0x00000000004e99ef
0x00007fe2de5e95df
0x00007fe2e1c38696
0x00000000004fad63
0x00000000004e9e94
0x00000000005408b7
0x0000000000542120
0x000000000059a58d
0x00007fe2de5e1e24
0x00007fe2de30f34c
seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-2.0.rc5/seastar/core/reactor.cc:277
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-2.0.rc5/seastar/core/reactor.cc:288
seastar::reactor::block_notifier(int) at /usr/src/debug/scylla-2.0.rc5/seastar/core/reactor.cc:514
?? ??:0
std::_Function_handler<seastar::metrics::impl::metric_value (), std::function<seastar::metrics::impl::metric_value ()> seastar::metrics::impl::make_function<seastar::reactor::register_metrics()::{lambda()#2}, void>(seastar::reactor::register_metrics()::{lambda()#2}, seastar::metrics::impl::data_type)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /opt/scylladb/include/c++/5.3.1/functional:1858
?? ??:0
?? ??:0
seastar::reactor::flush_pending_aio() at /usr/src/debug/scylla-2.0.rc5/seastar/core/reactor.cc:809
seastar::reactor::poll_once() at /usr/src/debug/scylla-2.0.rc5/seastar/core/reactor.cc:2871
 (inlined by) operator() at /usr/src/debug/scylla-2.0.rc5/seastar/core/reactor.cc:2768
 (inlined by) _M_invoke at /opt/scylladb/include/c++/5.3.1/functional:1857
std::function<bool ()>::operator()() const at /opt/scylladb/include/c++/5.3.1/functional:2271
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-2.0.rc5/seastar/core/reactor.cc:2793
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const [clone .constprop.4264] at /usr/src/debug/scylla-2.0.rc5/seastar/core/reactor.cc:3707
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/5.3.1/functional:2271
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-2.0.rc5/seastar/core/posix.cc:52
?? ??:0
?? ??:0
```
3. timeouts with reactor stalled:
```
2017-09-27 10:16:13,915 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-09-27 10:16:13,966 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-09-27 10:16:13,966 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-09-27 10:16:13,966 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
...
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,314 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00000000004eef98
2017-09-27 10:16:14,314 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00000000004ef279
2017-09-27 10:16:14,314 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00007f087cc9b5df
2017-09-27 10:16:14,315 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00000000004e99ef
2017-09-27 10:16:14,316 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00007f087cc9b5df
2017-09-27 10:16:14,317 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00007f08802ea696
2017-09-27 10:16:14,317 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00000000004fad63
2017-09-27 10:16:14,318 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00000000004e9e94
2017-09-27 10:16:14,319 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,319 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,319 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,319 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,319 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00000000005408b7
2017-09-27 10:16:14,320 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,320 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x0000000000542120
2017-09-27 10:16:14,321 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,321 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x000000000059a58d
2017-09-27 10:16:14,322 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,323 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00007f087cc93e24
2017-09-27 10:16:14,323 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,324 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | 0x00007f087c9c134c
2017-09-27 10:16:14,324 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were
 required but only 1 acknowledged the write)
2017-09-27 10:16:14,325 remote           L0197 DEBUG| [35.185.42.131] [stdout] Sep 27 10:16:14 info   | Reactor stalled for 2412 ms on shard 11.

```
4. a stop and start nemesis started in node 8:
```
2017-09-27 12:20:05,154 nemesis          L0418 INFO | sdcm.nemesis.ChaosMonkey: Status for target Node longevity-1tb-7d-2-0-db-node-6280c635-0-8 [35.185.42.131 | 10.240.0.22] (seed: False): None
2017-09-27 12:20:06,869 nemesis          L0429 DEBUG| sdcm.nemesis.ChaosMonkey: Start disruption at `2017-09-27 12:20:06.869323`
2017-09-27 12:20:06,870 nemesis          L0374 INFO | sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method <bound method ChaosMonkey.disrupt_stop_start_scylla_server of <sdcm.nemesis.ChaosMonkey 
object at 0x4588610>>
2017-09-27 12:20:07,466 threading        L0811 DEBUG| Sending options message heartbeat on idle connection (72917392) 104.196.117.12
2017-09-27 12:20:07,467 threading        L0811 DEBUG| Sending options message heartbeat on idle connection (72920912) 104.196.117.12
2017-09-27 12:20:07,469 asyncorereactor  L0383 DEBUG| Received options response on connection (72917392) from 104.196.117.12
2017-09-27 12:20:07,469 asyncorereactor  L0383 DEBUG| Received options response on connection (72920912) from 104.196.117.12
2017-09-27 12:20:07,547 nemesis          L0187 DEBUG| sdcm.nemesis.ChaosMonkey: Set current_disruption -> StopStartService Node longevity-1tb-7d-2-0-db-node-6280c635-0-8 [35.185.42.131 | 10.240.0.22] (seed: Fals
e)
```
5. Not enough replicas available for query at consistency quorum (the nemsis took one out):
```
2017-09-27 12:20:16,058 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2017-09-27 12:20:16,058 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2017-09-27 12:20:16,059 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2017-09-27 12:20:16,059 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
```
6. loader crashed:
```
2017-09-27 12:20:19,323 remote           L0197 DEBUG| [35.196.54.57] [stdout] 
2017-09-27 12:20:19,324 remote           L0197 DEBUG| [35.196.54.57] [stdout]   at org.apache.cassandra.stress.Operation.error(Operation.java:135)
2017-09-27 12:20:19,324 remote           L0197 DEBUG| [35.196.54.57] [stdout]   at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
2017-09-27 12:20:19,324 remote           L0197 DEBUG| [35.196.54.57] [stdout]   at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:98)
2017-09-27 12:20:19,324 remote           L0197 DEBUG| [35.196.54.57] [stdout]   at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
2017-09-27 12:20:19,324 remote           L0197 DEBUG| [35.196.54.57] [stdout]   at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:258)
2017-09-27 12:20:19,325 remote           L0197 DEBUG| [35.196.54.57] [stdout]   at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
2017-09-27 12:20:19,325 remote           L0197 DEBUG| [35.196.54.57] [stdout] java.io.IOException: Operation x10 on key(s) [4f4f4b4e4d384f503631]: Error executing: (UnavailableException): Not enough replicas ava
ilable for query at consistency QUORUM (2 required but only 1 alive)

```

**Comment by avikivity** [comment]
@harelassayag did disk space come close to 100% utilization during this test?

**Comment by harelassayag** [comment]
@avikivity yes, the blue one is the node in question and around that time.
![freespace](https://user-images.githubusercontent.com/15847218/31054073-5b61b2c0-a6b3-11e7-8bef-cca56bc095f5.png)

**Comment by avikivity** [comment]
This is a known problem in xfs.

**Comment by harelassayag** [comment]
a similar issue has reproduced multipule time on another longevity run. the test was running 4 nodes 1TB with version 2.0.0-0.20170929.e265c91. this time the nodes were not close to utilizing 100% disk space.
1. major compaction:
```
2017-10-04 02:17:38,370 nemesis          L0429 DEBUG| sdcm.nemesis.ChaosMonkey: Start disruption at `2017-10-04 02:17:38.370624`
2017-10-04 02:17:38,371 nemesis          L0374 INFO | sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method <bound method ChaosMonkey.disrupt_major_compaction of
 <sdcm.nemesis.ChaosMonkey object at 0x541fc50>>
2017-10-04 02:17:38,929 nemesis          L0187 DEBUG| sdcm.nemesis.ChaosMonkey: Set current_disruption -> MajorCompaction Node longevity-1tb-7d-2-0-db-node-bafcb5bc-0-8 [104.196.117.12 | 10.240.0.27] (seed: False)
2017-10-04 02:17:38,929 nemesis          L0189 INFO | sdcm.nemesis.ChaosMonkey: MajorCompaction Node longevity-1tb-7d-2-0-db-node-bafcb5bc-0-8 [104.196.117.12 | 10.240.0.27] (seed: False)
2017-10-04 02:17:38,929 remote           L0894 DEBUG| Remote [scylla-test@104.196.117.12]: Running 'nodetool -h localhost compact'
2017-10-04 02:17:38,929 remote           L0097 INFO | [104.196.117.12] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpdOtdnA -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 104.196.117.12 "nodetool -h localhost compact"'
```
2. reactor stall:
```
2017-10-04 02:27:33,434 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | Reactor stalled for 2002 ms on shard 7.
2017-10-04 02:27:33,434 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | Backtrace:
2017-10-04 02:27:33,435 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00000000004eef58
2017-10-04 02:27:33,435 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00000000004ef239
2017-10-04 02:27:33,437 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00007f031c4e35df
2017-10-04 02:27:33,437 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00000000004e99af
2017-10-04 02:27:33,439 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00007f031c4e35df
2017-10-04 02:27:33,440 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00007f031fb32696
2017-10-04 02:27:33,440 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00000000004fad23
2017-10-04 02:27:33,440 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00000000004e9e54
2017-10-04 02:27:33,441 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x0000000000540877
2017-10-04 02:27:33,441 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00000000005420e0
2017-10-04 02:27:33,443 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x000000000059a54d
2017-10-04 02:27:33,443 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00007f031c4dbe24
2017-10-04 02:27:33,444 remote           L0197 DEBUG| [104.196.117.12] [stdout] Oct 04 02:27:33 info   | 0x00007f031c20934c
```
decoded:
```
[harel@longevity-1tb-7d-2-0-db-node-bafcb5bc-0-8 ~]$ addr2line -Cpife /usr/lib/debug/.build-id/98/fd496d6976cc8e7fb00ae7cad5e473fbeb82de.debug 
0x00000000004eef58
0x00000000004ef239
0x00007f031c4e35df
0x00000000004e99af
0x00007f031c4e35df
0x00007f031fb32696
0x00000000004fad23
0x00000000004e9e54
0x0000000000540877
0x00000000005420e0
0x000000000059a54d
0x00007f031c4dbe24
0x00007f031c20934c
seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-2.0.0/seastar/core/reactor.cc:277
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-2.0.0/seastar/core/reactor.cc:288
seastar::reactor::block_notifier(int) at /usr/src/debug/scylla-2.0.0/seastar/core/reactor.cc:514
?? ??:0
std::_Function_handler<seastar::metrics::impl::metric_value (), std::function<seastar::metrics::impl::metric_value ()> seastar::metrics::impl::make_function<seastar::reactor::register_metrics()::{lambda()#2}, void>(seastar::reactor::register_metrics()::{lambda()#2}, seastar::metrics::impl::data_type)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /opt/scylladb/include/c++/5.3.1/functional:1858
?? ??:0
?? ??:0
seastar::reactor::flush_pending_aio() at /usr/src/debug/scylla-2.0.0/seastar/core/reactor.cc:809
seastar::reactor::poll_once() at /usr/src/debug/scylla-2.0.0/seastar/core/reactor.cc:2871
 (inlined by) operator() at /usr/src/debug/scylla-2.0.0/seastar/core/reactor.cc:2768
 (inlined by) _M_invoke at /opt/scylladb/include/c++/5.3.1/functional:1857
std::function<bool ()>::operator()() const at /opt/scylladb/include/c++/5.3.1/functional:2271
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-2.0.0/seastar/core/reactor.cc:2793
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const [clone .constprop.4264] at /usr/src/debug/scylla-2.0.0/seastar/core/reactor.cc:3707
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/5.3.1/functional:2271
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-2.0.0/seastar/core/posix.cc:52
?? ??:0
?? ??:0

```
3. timeouts:
```
2017-10-04 02:27:35,349 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-10-04 02:27:35,349 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-10-04 02:27:35,349 remote           L0197 DEBUG| [35.196.54.57] [stdout] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```
disk space:
![diskspace](https://user-images.githubusercontent.com/15847218/31171890-16d200de-a90a-11e7-94cb-9ab4ce4aba08.png)

**Comment by slivne** [comment]
@harelassayag since this is a major compaction the FS may be "close" to full and we are not seeing it because there are many deleted files - need to check if there is an alternate metric we should look at / verift this metric covers deleted but held files.

**Comment by slivne** [comment]
@harelassayag ping - did you check if there is another OS metrics that shows the used space of deleted and held files - that may show that we are out of diskspace ?

**Comment by harelassayag** [comment]
@slivne the issue has reproduced last week but in a manner that was closer to the first instance (free space was actually close to 0).at the second instance. I might have been looking at the wrong metric.

**Comment by slivne** [comment]
@avikivity
- can you please refer to the known issue in XFS - it seemed the disk was almost full.
- is there a mean in which we can try to avoid  XFS from running into this issue (make sure we have enough disk space / not do certain operations in certain order - we already have some items like this in our code).

**Comment by slivne** [comment]
We have found that in XFS submitting a write to a file while there is an ongoing fsync can cause stalls 

scylladb/seastar@0fb334b9f1f0d624e256436d2c1e4839d7eff2dd
