### ISSUE TITLE
Failed to install scylla for dependency issue (3rdparty repo)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2941]
*Installation details*
Scylla version (or git commit hash): development-0.20171107.cb9daec.el7.centos
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

[scylla-master-centos-rpm-test/262 log:](http://jenkins.cloudius-systems.com:8080/job/scylla-master-centos-rpm-test/label=muninn/262/artifact/latest/job.log)

```
2017-11-07 22:57:29,659 process          L0420 DEBUG| [stdout] ---> Package scylla.x86_64 0:666.development-0.20171107.cb9daec.el7.centos will be installed
2017-11-07 22:57:29,659 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-libstdc++72 for package: scylla-666.development-0.20171107.cb9daec.el7.centos.x86_64
2017-11-07 22:57:29,659 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-libgcc72 for package: scylla-666.development-0.20171107.cb9daec.el7.centos.x86_64
2017-11-07 22:57:29,659 process          L0420 DEBUG| [stdout] ---> Package scylla-server.x86_64 0:666.development-0.20171107.cb9daec.el7.centos will be installed
2017-11-07 22:57:29,660 process          L0420 DEBUG| [stdout] --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.22)(64bit) for package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64
2017-11-07 22:57:29,660 process          L0420 DEBUG| [stdout] --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.21)(64bit) for package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64
2017-11-07 22:57:29,660 process          L0420 DEBUG| [stdout] --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.20)(64bit) for package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64
2017-11-07 22:57:29,660 process          L0420 DEBUG| [stdout] --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.9)(64bit) for package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64
2017-11-07 22:57:29,660 process          L0420 DEBUG| [stdout] --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.8)(64bit) for package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64
2017-11-07 22:57:29,660 process          L0420 DEBUG| [stdout] --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.11)(64bit) for package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64
2017-11-07 22:57:30,042 process          L0420 DEBUG| [stdout] --> Finished Dependency Resolution
2017-11-07 22:57:30,053 process          L0420 DEBUG| [stderr] Error: Package: scylla-666.development-0.20171107.cb9daec.el7.centos.x86_64 (scylla)
2017-11-07 22:57:30,053 process          L0420 DEBUG| [stderr]            Requires: scylla-libstdc++72
2017-11-07 22:57:30,053 process          L0420 DEBUG| [stderr] Error: Package: scylla-666.development-0.20171107.cb9daec.el7.centos.x86_64 (scylla)
2017-11-07 22:57:30,053 process          L0420 DEBUG| [stderr]            Requires: scylla-libgcc72
2017-11-07 22:57:30,053 process          L0420 DEBUG| [stderr] Error: Package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64 (scylla)
2017-11-07 22:57:30,053 process          L0420 DEBUG| [stderr]            Requires: libstdc++.so.6(GLIBCXX_3.4.22)(64bit)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr] Error: Package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64 (scylla)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr]            Requires: libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr] Error: Package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64 (scylla)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr]            Requires: libstdc++.so.6(CXXABI_1.3.11)(64bit)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr] Error: Package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64 (scylla)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr]            Requires: libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr] Error: Package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64 (scylla)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr]            Requires: libstdc++.so.6(CXXABI_1.3.8)(64bit)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr] Error: Package: scylla-server-666.development-0.20171107.cb9daec.el7.centos.x86_64 (scylla)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stderr]            Requires: libstdc++.so.6(CXXABI_1.3.9)(64bit)
2017-11-07 22:57:30,054 process          L0420 DEBUG| [stdout]  You could try using --skip-broken to work around the problem
2017-11-07 22:57:30,394 process          L0420 DEBUG| [stdout]  You could try running: rpm -Va --nofiles --nodigest
2017-11-07 22:57:30,424 stacktrace       L0036 ERROR| 
2017-11-07 22:57:30,424 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
2017-11-07 22:57:30,424 stacktrace       L0042 ERROR| Traceback (most recent call last):
2017-11-07 22:57:30,424 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-centos-rpm-test/label/muninn/scylla-artifacts.py", line 635, in setUp
2017-11-07 22:57:30,424 stacktrace       L0042 ERROR|     self.scylla_setup()
2017-11-07 22:57:30,424 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-centos-rpm-test/label/muninn/scylla-artifacts.py", line 630, in scylla_setup
2017-11-07 22:57:30,424 stacktrace       L0042 ERROR|     installer.run()
2017-11-07 22:57:30,424 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-centos-rpm-test/label/muninn/scylla-artifacts.py", line 281, in run
2017-11-07 22:57:30,425 stacktrace       L0042 ERROR|     raise InstallPackageError(e_msg)
2017-11-07 22:57:30,425 stacktrace       L0042 ERROR| InstallPackageError: Package scylla could not be installed (see logs for details)
```

@syuu1228 
What's the expected 3rdparty repo?  copr-be.cloud.fedoraproject.org or downloads.scylladb.com?

[543/scylla.reop](http://downloads.scylladb.com.s3.amazonaws.com/rpm/unstable/centos/master/543/scylla.repo)

```
[scylla]
name=Scylla for Centos $releasever - $basearch
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/master/543/scylla/\7/$basearch/
enabled=1
gpgcheck=0

[scylla-generic]
name=Scylla for centos $releasever
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/master/543/scylla/\7/noarch/
enabled=1
gpgcheck=0

[scylla-3rdparty]
name=Scylla 3rdParty for Centos $releasever - $basearch
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/master/543/3rdparty/\7/$basearch/
enabled=1
gpgcheck=0

[scylla-3rdparty-generic]
name=Scylla 3rdParty for Centos $releasever
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/master/543/3rdparty/\7/noarch/
enabled=1
gpgcheck=0
```

**Comment by amoskong** [comment]
I tried try to manually replace `3rdparty repos` in [543/scylla.repo](http://downloads.scylladb.com.s3.amazonaws.com/rpm/unstable/centos/master/543/scylla.repo) with `copr-be.cloud.fedoraproject.org`, then scylla packages (scylla.*666.development-0.20171107.cb9daec.el7.centos) can be installed successfully.

```
[scylla]
name=Scylla for Centos $releasever - $basearch
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/master/543/scylla/\7/$basearch/
enabled=1
gpgcheck=0

[scylla-generic]
name=Scylla for centos $releasever
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/master/543/scylla/\7/noarch/
enabled=1
gpgcheck=0

[scylladb-scylla-3rdparty]
name=Copr repo for scylla-3rdparty owned by scylladb
baseurl=https://copr-be.cloud.fedoraproject.org/results/scylladb/scylla-3rdparty/epel-7-x86_64/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/scylladb/scylla-3rdparty/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

```
===============================================================================================================================
 Package                 Arch        Version                                               Repository                     Size
===============================================================================================================================
Installing:
 scylla                  x86_64      666.development-0.20171107.cb9daec.el7.centos         scylla                        2.2 k
Installing for dependencies:
 scylla-conf             x86_64      666.development-0.20171107.cb9daec.el7.centos         scylla                         17 k
 scylla-env              noarch      1.0-1.el7.centos                                      scylladb-scylla-3rdparty      3.1 k
 scylla-jmx              noarch      666.development-20171107.e80a5e3.el7.centos           scylla-generic                5.6 M
 scylla-kernel-conf      x86_64      666.development-0.20171107.cb9daec.el7.centos         scylla                        3.6 k
 scylla-libgcc72         x86_64      7.2.1-1.el7.centos                                    scylladb-scylla-3rdparty       85 k
 scylla-libstdc++72      x86_64      7.2.1-1.el7.centos                                    scylladb-scylla-3rdparty      452 k
 scylla-server           x86_64      666.development-0.20171107.cb9daec.el7.centos         scylla                         10 M
 scylla-tools            noarch      666.development-20171107.c4ba9fc.el7.centos           scylla-generic                142 k
 scylla-tools-core       noarch      666.development-20171107.c4ba9fc.el7.centos           scylla-generic                 22 M

Transaction Summary
===============================================================================================================================
Install  1 Package (+9 Dependent packages)
...
```

**Comment by slivne** [comment]
I modified the jenkins job to align with that - lets see if it works
tomorrow morning.

**Comment by amoskong** [comment]
@slivne Which job did you change to change the 3rdparty repo？      I saw [scylla-t-centos-rpm](http://jenkins.cloudius-systems.com:8080/job/scylla-t-centos-rpm/configure) still use `downloads.scylladb.com` 3rdparty repos.

**Comment by slivne** [comment]
there is a scylla-t-centos-rpm-v2 now that uses the fedora copr

The scylla-master-centos-rpm was moved to use this template instead of the
previous one (we are leaving that one for all the 2.0 and previous jobs)

**Comment by syuu1228** [comment]
@slivne @amoskong All dependency libraries provided by 3rdparty repo should be statically linked on package building time, which means users doesn't need scylladb-scylla-3rdparty repo.
We have configure.py options for that, but we haven't specified it correctly. I'll send a patch to fix it.
We also have similar problem on Ubuntu, will fix it too.

**Comment by gleb-cloudius** [comment]
@syuu1228 we have to link libgcc dynamically since we override symbols
from there. And our static linkage never worked anyway since there are
other dynamic libraries that are linked with libgcc dynamically and they
pull dynamic dependency on libgcc with them. So what happens now is that
we compile with our own compiler, but use libgcc that happens to be
installed on the system, which works only because libgcc rarely changes
in incompatible way.

--
			Gleb.

**Comment by syuu1228** [comment]
@gleb-cloudius okay.. so we should not link libgcc statically, how about other libraries, is it safe to link boost statically?
(Maybe we can just stop static linking, since we have to provide 3rdparty packages to user anyway)

And I suppose it's not just on CentOS, we probably do same way on Ubuntu too?
We statically linking libgcc/libstdc++ on Ubuntu/Debian, looks like it should be drop ( --static-stdc++):
https://github.com/scylladb/scylla/blob/master/dist/debian/rules.in#L4

**Comment by gleb-cloudius** [comment]
On Wed, Nov 08, 2017 at 10:02:22AM +0000, Takuya ASADA wrote:
> @gleb-cloudius okay.. so we should not link libgcc statically, how about other libraries, is it safe to link boost statically?
> (Maybe we can just stop static linking, since we have to provide 3rdparty packages to user anyway)
> 
libgcc and libstdc++ dynamically the reset can be static.

> And I suppose it's not just on CentOS, we probably do same way on Ubuntu too?
> We statically linking libgcc/libstdc++ on Ubuntu/Debian, looks like it should be drop ( --static-stdc++):
> https://github.com/scylladb/scylla/blob/master/dist/debian/rules.in#L4
> 
Yes, it should be. I dropped the one in CentOS because it disables some
of our optimizations, but leaves libgcc dynamically linked anyway.

--
			Gleb.

**Comment by syuu1228** [comment]
On Wed, Nov 8, 2017 at 7:34 PM, Gleb Natapov <notifications@github.com>
wrote:

> On Wed, Nov 08, 2017 at 10:02:22AM +0000, Takuya ASADA wrote:
> > @gleb-cloudius okay.. so we should not link libgcc statically, how about
> other libraries, is it safe to link boost statically?
> > (Maybe we can just stop static linking, since we have to provide
> 3rdparty packages to user anyway)
> >
> libgcc and libstdc++ dynamically the reset can be static.
>
> > And I suppose it's not just on CentOS, we probably do same way on Ubuntu
> too?
> > We statically linking libgcc/libstdc++ on Ubuntu/Debian, looks like it
> should be drop ( --static-stdc++):
> > https://github.com/scylladb/scylla/blob/master/dist/debian/rules.in#L4
> >
> Yes, it should be. I dropped the one in CentOS because it disables some
> of our optimizations, but leaves libgcc dynamically linked anyway.


Umm, but adding our PPA apt line to scylla.list doesn't solve the problem,
because unlike CentOS, we are using gcc-7 from ppa:ubuntu-toolchain-r/test
not on our PPA.
And libgcc is part of that.
The apt line to access ppa:ubuntu-toolchain-r/test can be include our
scylla.list, but I'm not sure we should provide such .list for users.
Maybe better to copy gcc-7 related packages from the PPA to our PPA?
@avikivity @slivne What do you think?

**Comment by syuu1228** [comment]
Ah, it looks like not good to install ppa:ubuntu-toolchain-r/test, since it tries to upgrade libc6/libgcc1:
```
# apt install gcc-7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  binutils cpp-7 gcc-7-base libasan4 libatomic1 libc-dev-bin libc6 libc6-dev
  libcc1-0 libcilkrts5 libgcc-7-dev libgcc1 libgomp1 libisl15 libitm1 liblsan0
  libmpc3 libmpfr4 libmpx2 libquadmath0 libtsan0 libubsan0 linux-libc-dev
  manpages manpages-dev
Suggested packages:
  binutils-doc gcc-7-locales gcc-7-multilib gcc-7-doc libgcc1-dbg libgomp1-dbg
  libitm1-dbg libatomic1-dbg libasan4-dbg liblsan0-dbg libtsan0-dbg
  libubsan0-dbg libcilkrts5-dbg libmpx2-dbg libquadmath0-dbg glibc-doc
  man-browser
The following NEW packages will be installed:
  binutils cpp-7 gcc-7 gcc-7-base libasan4 libatomic1 libc-dev-bin libc6-dev
  libcc1-0 libcilkrts5 libgcc-7-dev libgomp1 libisl15 libitm1 liblsan0 libmpc3
  libmpfr4 libmpx2 libquadmath0 libtsan0 libubsan0 linux-libc-dev manpages
  manpages-dev
The following packages will be upgraded:
  libc6 libgcc1
2 upgraded, 24 newly installed, 0 to remove and 33 not upgraded.
Need to get 81.1 MB of archives.
After this operation, 368 MB of additional disk space will be used.
```

So I suppose we have to provide our own scylla-gcc72 / scylla-libgcc72 on our PPA.
