### ISSUE TITLE
Range tombstones are incorrectly serialized for compact storage tables with a single clustering column

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2986]
```cql
create table x (pk int, ck int, v int, primary key(pk, ck)) with compact storage;
insert into x (pk, ck, v) values (1, 1, 1);
DELETE from x where pk = 1 and ck = 1;
```

sstabledump:
```
[
  {
    "partition" : {
      "key" : [ "1" ],
      "position" : 0
    },
    "rows" : [
      {
        "type" : "range_tombstone_bound",
        "start" : {
          "type" : "inclusive",
          "clustering" : [ ] } } ] } ]Exception in thread "main" org.apache.cassandra.serializers.MarshalException: Expected 4 or 0 byte int (7)
	at org.apache.cassandra.serializers.Int32Serializer.validate(Int32Serializer.java:42)
	at org.apache.cassandra.db.marshal.AbstractType.getString(AbstractType.java:128)
	at org.apache.cassandra.tools.JsonTransformer.serializeClustering(JsonTransformer.java:352)
	at org.apache.cassandra.tools.JsonTransformer.serializeBound(JsonTransformer.java:329)
	at org.apache.cassandra.tools.JsonTransformer.serializeTombstone(JsonTransformer.java:304)
	at org.apache.cassandra.tools.JsonTransformer.serializePartition(JsonTransformer.java:221)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.apache.cassandra.tools.JsonTransformer.toJson(JsonTransformer.java:102)
	at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:251)
	at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)

```

For compact tables with a single clustering column, cell names in sstables are not compound, but sstable serialization and deserialization is always assuming that cell names are compound. The cell name will therefore have an unexpected length and EOC parts.

This will cause compatibility problems with Cassandra. Cassandra won't be able to read sstables containing such tombstones, and Scylla would not read sstables with such tombstones generated by Cassandra correctly.

**Comment by duarten** [comment]
There's some additional complexity with range tombstones because of C* 3.0 ranged deletes, which we partially support, and require range tombstone cell names to always have an EOC somehow, even if the schema is non-compound.

In C* 3.0, serializing a row tombstone is different:

```java
out.writeByte(bound.kind().ordinal());
out.writeShort(bound.size());
ClusteringPrefix.serializer.serializeValuesWithoutSize(bound, out, version, types);
```

I'm not sure what we can do here to be fully correct. We could disallow ranged deletes on compact schemas, the same way that in thrift, if the schema is non-compound, we don't expect an EOC to have been specified:

```cpp
static query::clustering_range::bound make_clustering_bound(const schema& s, bytes_view v, composite::eoc exclusiveness_marker) {
        auto composite = composite_view(v, s.thrift().has_compound_comparator());
        auto last = composite::eoc::none;
        auto&& ck = clustering_key_prefix::from_exploded(composite.components() | boost::adaptors::transformed([&](auto&& c) {
            last = c.second;
            return c.first;
        }));
        return query::clustering_range::bound(std::move(ck), last != exclusiveness_marker);
    }
```

What do you think?

**Comment by tgrabiec** [comment]
Disallowing range deletes on compact storage tables seems the right approach to do now. We could lift that off when move to a new storage format.
