### ISSUE TITLE
cassandra-stress fails with "no viable alternative at input '<EOF>'" error on Power

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#2998]
*Installation details*
Scylla version (or git commit hash): b515cca5e2f3f1d3ccff563fc6b72cb9a6314687
Cluster size: 1
Shards count: 80
OS: Fedora 26

*Description*
When we cassandra-stress on many shards it fails with the following error:
```
cassandra-stress user profile=/home/user1/size_based_load.yaml ops\(insert=1\) no-warmup n=600000  -rate threads=200 -mode native cql3 -pop seq=1..100
WARN  00:14:07 You listed localhost/0:0:0:0:0:0:0:1:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
Connected to cluster: scylla-1, max pending requests per connection 128, max connections per host 8
Datatacenter: datacenter1; Host: localhost/127.0.0.1; Rack: rack1
Created schema. Sleeping 1s for propagation.
Sleeping 2s...
Running [insert] with 200 threads for 600000 iteration
Failed to connect over JMX; not collecting these stats
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
Generating batches with [1..1] partitions and [1..1] rows (of [1..1] total rows in the partitions)
com.datastax.driver.core.exceptions.SyntaxError: line 1:0 no viable alternative at input '<EOF>'
        at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
        at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:98)
        at org.apache.cassandra.stress.util.JavaDriverClient.prepare(JavaDriverClient.java:101)
        at org.apache.cassandra.stress.StressProfile.getInsert(StressProfile.java:473)
        at org.apache.cassandra.stress.settings.SettingsCommandUser$1.get(SettingsCommandUser.java:83)
        at org.apache.cassandra.stress.settings.SettingsCommandUser$1.get(SettingsCommandUser.java:79)
        at org.apache.cassandra.stress.operations.SampledOpDistributionFactory.get(SampledOpDistributionFactory.java:56)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:213)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:74)
        at org.apache.cassandra.stress.Stress.main(Stress.java:117)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:0 no viable alternative at input '<EOF>'
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:132)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
        at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```
The problem doesn't reproduces with the default schema. It only reproduces with the attached user profile using the following command:
```
cassandra-stress user profile=/home/user1/size_based_load.yaml ops\(insert=1\) no-warmup n=600000  -rate threads=200 -mode native cql3 -pop seq=1..100
```

[size_based_load.yaml.txt](https://github.com/scylladb/scylla/files/1489577/size_based_load.yaml.txt)

**Comment by vladzcloudius** [comment]
The issue was introduced by the following commit: 66568be96960e870cde4c1f3b128c296aa7e0e63
