### ISSUE TITLE
failed to create user by super session of the node (trans-auth already enabled)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3025]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20171121.c1b97d1
Cluster size: 2 
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Test steps:
1. start a cluster (2 nodes) with PasswordAuthenticator/CassandraAuthorizer
2. enable trans-auth of node0
3. get a super session with node0
4. try to create a normal user by the session

Expected result: `the normal user can be created`

Real result: failed to create user in step4, error: 
```
Error from server: code=2200 [Invalid query] message="org.apache.cassandra.auth.AllowAllAuthenticator doesn't support PASSWORD option
```

Testcase:
```
    def transitional_auth_2nodes_from_default_test(self):
        self.prepare(nodes=2, enable_auth=False)
        nodes = self.cluster.nodelist()

        #########################################
        config = {'authenticator': 'com.scylladb.auth.TransitionalAuthenticator',
                   'authorizer': 'com.scylladb.auth.TransitionalAuthorizer'}
        self.cluster.set_configuration_options(values=config)

        debug('STEP: restart node0 to enable Transitional Auth')
        nodes[0].stop(wait_other_notice=True, gently=True)
        nodes[0].start(wait_for_binary_proto=True)

        print self.wait_for_any_log(self.cluster.nodelist(), 'Created default superuser', 10)
        session = self.get_session(node_idx=0, user='cassandra', password='cassandra')
        try:
            session.execute("CREATE USER normal WITH PASSWORD '123456' NOSUPERUSER")
        except InvalidRequest as e:
            debug(e.message)
```

@elcallio

**Comment by slivne** [comment]
@elcallio can you please provide your feedback on this

**Comment by slivne** [comment]
@amoskong - can you provide full details to reproduce (repo , test file, test name) - even better command line

**Comment by elcallio** [comment]
Please rerun this, as from what I can see the auth code has been changed, and no such error message exists currently.

**Comment by amoskong** [comment]
Ok, I will rerun and provide the test & log.

**Comment by amoskong** [comment]
### Test Details:

The tests can be found in scylladb/scylla-dtest#545
The test name: transitional_auth_2nodes_from_default_test

PRINT_DEBUG=true KEEP_TEST_DIR=true REUSE_CLUSTER=false nosetests --logging-filter=none -s auth_test.py:TestAuth.transitional_auth_2nodes_from_default_test

dtest full log: [dtest-J5LSnR.tar.gz](https://github.com/scylladb/scylla/files/1577834/dtest-J5LSnR.tar.gz)


```
cluster ccm directory: /home/amos/.dtest/dtest-J5LSnR
STEP: restart node0 to enable Transitional Auth
<ccmlib.scylla_node.ScyllaNode object at 0x4236c10>
Error from server: code=2200 [Invalid query] message="org.apache.cassandra.auth.AllowAllAuthenticator doesn't support PASSWORD option"
can't get session of node0 with normal user/password
STEP: restart node1 to enable Transitional Auth
E
======================================================================
ERROR: transitional_auth_2nodes_from_default_test (auth_test.TestAuth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amos/space/scylla-dtest/auth_test.py", line 1763, in transitional_auth_2nodes_from_default_test
    session = self.get_session(node_idx=0, user='normal', password='123456')
  File "/home/amos/space/scylla-dtest/auth_test.py", line 1824, in get_session
    conn = self.patient_cql_connection(node, user=user, password=password)
  File "/home/amos/space/scylla-dtest/dtest.py", line 579, in patient_cql_connection
    **kwargs
  File "/home/amos/space/scylla-dtest/dtest.py", line 112, in retry_till_success
    return fun(*args, **kwargs)
  File "/home/amos/space/scylla-dtest/dtest.py", line 502, in cql_connection
    protocol_version, port=port, ssl_opts=ssl_opts, **kwargs)
  File "/home/amos/space/scylla-dtest/dtest.py", line 540, in _create_session
    session = cluster.connect()
  File "cassandra/cluster.py", line 1237, in cassandra.cluster.Cluster.connect
    with self._lock:
  File "cassandra/cluster.py", line 1273, in cassandra.cluster.Cluster.connect
    raise
  File "cassandra/cluster.py", line 1260, in cassandra.cluster.Cluster.connect
    self.control_connection.connect()
  File "cassandra/cluster.py", line 2749, in cassandra.cluster.ControlConnection.connect
    self._set_new_connection(self._reconnect_internal())
  File "cassandra/cluster.py", line 2792, in cassandra.cluster.ControlConnection._reconnect_internal
    raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="authentication failed"',)})

----------------------------------------------------------------------
Ran 1 test in 176.080s

FAILED (errors=1)
```

**Comment by amoskong** [comment]
It's a problem of scylla-dtest, scylla works well. Let's close this issue as NOTABUG.

auth_test.py: get_session() calls self.patient_cql_connection(), queries will be balanced to all nodes.

We contact with node1 (TransitionalAuth), but execute query on node2 (AllowAllAuth) because of load balance.

We can fix the test by calling `self.patient_exclusive_cql_connection()`.

Sorry for the noise. I will fix get_session(), or add a get_exclusive_session(), or add a parameter for get_session (exclusive=True).
