### ISSUE TITLE
regression on ability to recreate sstable summary

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#3057]
*Installation details*
Scylla version (or git commit hash): 57a6ed5aaa346a3ed7c88a172b738e228b957341

how to reproduce: deletes summary of any table and reboot

INFO  2017-12-09 21:46:21,623 [shard 0] database - Populating Keyspace ks
INFO  2017-12-09 21:46:21,623 [shard 0] database - Keyspace ks: Reading CF users 
WARN  2017-12-09 21:46:21,624 [shard 0] sstable - Couldn't read summary file ./data/data/ks/users-b8f63830dc5e11e7b5ae000000000000/ks-users-ka-1-Summary.db: sstables::malformed_sstable_exception (./data/data/ks/users-b8f63830dc5e11e7b5ae000000000000/ks-users-ka-1-Summary.db: file not found). Recreating it.
INFO  2017-12-09 21:46:21,624 [shard 0] sstable - Summary file ./data/data/ks/users-b8f63830dc5e11e7b5ae000000000000/ks-users-ka-1-Summary.db not found. Generating Summary...

ERROR 2017-12-09 21:46:21,625 [shard 0] database - Unrecognized error while processing ks-users-ka-1-TOC.txt: std::system_error (error system:2, No such file or directory). Refusing to boot
ERROR 2017-12-09 21:46:21,625 [shard 0] database - Exception while populating keyspace 'ks' with column family 'users' from file './data/data/ks/users-b8f63830dc5e11e7b5ae000000000000': std::system_error (error system:2, No such file or directory)
WARN  2017-12-09 21:46:21,625 [shard 0] seastar - Exceptional future ignored: std::runtime_error (Exception while populating keyspace 'ks' with column family 'users' from file './data/data/ks/users-b8f63830dc5e11e7b5ae000000000000': std::system_error (error system:2, No such file or directory)), backtrace:   0x49ca04
  0x50b14a
  0x4a3128
  0x49b81c
  0x49ba96
  0x4ec12c
  0x57f354
  0x424bdb
  /lib64/libc.so.6+0x20400
  0x4975c9

ERROR 2017-12-09 21:46:21,625 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Exception while populating keyspace 'ks' with column family 'users' from file './data/data/ks/users-b8f63830dc5e11e7b5ae000000000000': std::system_error (error system:2, No such file or directory))

**Comment by raphaelsc** [comment]
follow backtrace. looks like we're trying to read from a deleted file, and that would be summary. Maybe some functionality used by summary generation now relies on summary, which creates a egg-and-chicken problem.

```
(gdb) bt
#0  0x00007ffff724e4dd in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x00000000004a6375 in seastar::throw_kernel_error<long> (r=-22) at core/posix.hh:420
#2  seastar::posix_file_impl::<lambda(io_event)>::operator() (__closure=<optimized out>, ev=...) at core/reactor.cc:1178
#3  seastar::apply_helper<seastar::posix_file_impl::read_dma(uint64_t, std::vector<iovec>, const seastar::io_priority_class&)::<lambda(io_event)>, std::tuple<io_event>&&, std::integer_sequence<long unsigned int, 0ul> >::apply (func=<optimized out>, args=<optimized out>) at core/apply.hh:36
#4  seastar::apply<seastar::posix_file_impl::read_dma(uint64_t, std::vector<iovec>, const seastar::io_priority_class&)::<lambda(io_event)>, io_event> (func=<optimized out>, 
    args=<optimized out>) at core/apply.hh:44
#5  seastar::futurize<seastar::future<unsigned long> >::apply<seastar::posix_file_impl::read_dma(uint64_t, std::vector<iovec>, const seastar::io_priority_class&)::<lambda(io_event)>, io_event>(<unknown type in /home/utroz/scylla/build/release/scylla, CU 0x0, DIE 0x1dadf1>, <unknown type in /home/utroz/scylla/build/release/scylla, CU 0x0, DIE 0x3c7aa1>) (args=<optimized out>, func=<optimized out>) at core/future.hh:1308
#6  0x00000000004e6795 in seastar::future<io_event>::<lambda(auto:1&&)>::operator()<seastar::future_state<io_event> > (
    state=<unknown type in /home/utroz/scylla/build/release/scylla, CU 0x0, DIE 0x1dae21>, __closure=0x600000106818) at core/future.hh:905
#7  seastar::continuation<seastar::future<T>::then(Func&&) [with Func = seastar::posix_file_impl::read_dma(uint64_t, void*, size_t, const seastar::io_priority_class&)::<lambda(io_event)>; Result = seastar::future<long unsigned int>; T = {io_event}]::<lambda(auto:1&&)>, io_event>::run(void) (this=warning: can't find linker symbol for virtual table for `seastar::continuation<seastar::future<T>::then(Func&&) [with Func = seastar::posix_file_impl::read_dma(uint64_t, void*, size_t, const seastar::io_priority_class&)::<lambda(io_event)>; Result = seastar::future<long unsigned int>; T = {io_event}]::<lambda(auto:1&&)>, io_event>' value
warning: can't find linker symbol for virtual table for `seastar::continuation<seastar::future<T>::then(Func&&) [with Func = seastar::posix_file_impl::read_dma(uint64_t, void*, size_t, const seastar::io_priority_class&)::<lambda(io_event)>; Result = seastar::future<long unsigned int>; T = {io_event}]::<lambda(auto:1&&)>, io_event>' value
0x6000001067e0) at core/future.hh:396
#8  0x000000000049b813 in seastar::reactor::run_tasks (this=this@entry=0x600000402000, tq=...) at core/reactor.cc:2431
#9  0x000000000049ba97 in seastar::reactor::run_some_tasks (this=this@entry=0x600000402000, t_run_completed=...) at core/reactor.cc:2841
#10 0x00000000004ec12d in seastar::reactor::run_some_tasks (t_run_completed=..., this=0x600000402000) at core/future.hh:912
#11 seastar::reactor::run (this=0x600000402000) at core/reactor.cc:2985
#12 0x000000000057f355 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffdba0, ac=ac@entry=13, 
    av=av@entry=0x7fffffffde38, func=func@entry=<unknown type in /home/utroz/scylla/build/release/scylla, CU 0xaaf2d5, DIE 0xb3e72c>) at core/app-template.cc:162
#13 0x0000000000424bdc in main (ac=13, av=0x7fffffffde38) at main.cc:681
```

**Comment by raphaelsc** [comment]
turns out we don't ignore missing summary, which is recreated from index if necessary, when calculating bytes on disk for sstable fail with ENOENT. I'll send patch soon

```
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-Filter.db", {st_mode=S_IFREG|0644, st_size=136, ...}) = 0
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-Index.db", {st_mode=S_IFREG|0644, st_size=1890, ...}) = 0
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-Scylla.db", {st_mode=S_IFREG|0644, st_size=54, ...}) = 0
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-Digest.sha1", {st_mode=S_IFREG|0644, st_size=10, ...}) = 0
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-Statistics.db", {st_mode=S_IFREG|0644, st_size=4446, ...}) = 0
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-TOC.txt", {st_mode=S_IFREG|0644, st_size=89, ...}) = 0
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-CRC.db", {st_mode=S_IFREG|0644, st_size=12, ...}) = 0
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-Filter.db", {st_mode=S_IFREG|0644, st_size=136, ...}) = 0
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-Data.db", {st_mode=S_IFREG|0644, st_size=106790, ...}) = 0
[pid 16382] stat("/tmp/tmpdir_7DlFF7/la-1-big-Summary.db", 0x7f2f2a9d4bb0) = -1 ENOENT (No such file or directory)
```

**Comment by glommer** [comment]
Thanks Raphael

Please also include an unit test.
