### ISSUE TITLE
it takes a long time to propagate schema when creating new table

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#3059]
100 nodes cluster

When running c-s write for the first time, it creates the table and gets timeout till all nodes are synced with the schema.

2017-12-10 20:50:37,040 remote           L0197 DEBUG| [54.89.42.30] [stdout] Dec 10 20:50:37 info   |  [shard 0] database - Schema version changed to 479652a0-868e-3435-ba96-0fc585175361
2017-12-10 20:50:37,058 remote           L0197 DEBUG| [54.157.36.61] [stdout] Dec 10 20:50:37 info   |  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/system_schema-keyspaces-ka-1045-Data.db:level=0, ]. 
21292 bytes to 6391 (~30% of original) in 237ms = 0.03MB/s. ~1024 total partitions merged to 3.
2017-12-10 20:50:37,083 remote           L0197 DEBUG| [54.234.13.244] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-12-10 20:50:37,109 remote           L0197 DEBUG| [54.157.36.61] [stdout] Dec 10 20:50:37 info   |  [shard 0] database - Schema version changed to 479652a0-868e-3435-ba96-0fc585175361
2017-12-10 20:50:37,153 remote           L0197 DEBUG| [54.234.13.244] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-12-10 20:50:37,193 remote           L0197 DEBUG| [54.234.13.244] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-12-10 20:50:37,244 remote           L0197 DEBUG| [54.157.36.61] [stdout] Dec 10 20:50:37 info   |  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/system_schema-tables-ka-1045-Data.db:level=0, ]. 36042 
bytes to 15331 (~42% of original) in 218ms = 0.07MB/s. ~1024 total partitions merged to 3.
2017-12-10 20:50:37,415 remote           L0197 DEBUG| [54.234.13.244] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-12-10 20:50:37,417 remote           L0197 DEBUG| [54.234.13.244] [stdout] java.io.IOException: Operation x10 on key(s) [4b384b4f4e3932503530]: Error executing: (WriteTimeoutException): Cassandra timeout during write query at consistency QUORUM (2 replica were required but only
 1 acknowledged the write)
2017-12-10 20:50:37,417 remote           L0197 DEBUG| [54.234.13.244] [stdout] 
2017-12-10 20:50:37,418 remote           L0197 DEBUG| [54.234.13.244] [stdout]  at org.apache.cassandra.stress.Operation.error(Operation.java:135)
2017-12-10 20:50:37,418 remote           L0197 DEBUG| [54.234.13.244] [stdout]  at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
2017-12-10 20:50:37,418 remote           L0197 DEBUG| [54.234.13.244] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:98)
2017-12-10 20:50:37,418 remote           L0197 DEBUG| [54.234.13.244] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
2017-12-10 20:50:37,418 remote           L0197 DEBUG| [54.234.13.244] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:258)
2017-12-10 20:50:37,418 remote           L0197 DEBUG| [54.234.13.244] [stdout]  at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
2017-12-10 20:50:37,533 remote           L0197 DEBUG| [54.234.13.244] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-12-10 20:50:37,737 remote           L0197 DEBUG| [54.234.13.244] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-12-10 20:50:37,785 remote           L0197 DEBUG| [54.157.36.61] [stdout] Dec 10 20:50:37 info   |  [shard 0] database - Schema version changed to 479652a0-868e-3435-ba96-0fc585175361
2017-12-10 20:50:37,793 remote           L0197 DEBUG| [54.234.13.244] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2017-12-10 20:50:37,793 remote           L0197 DEBUG| [54.234.13.244] [stdout] java.io.IOException: Operation x10 on key(s) [50353235314c39373830]: Error executing: (WriteTimeoutException): Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

**Comment by larisau** [comment]
job log:
[Uploading job_log.tar.gz…]()

**Comment by asias** [comment]
which scylla version is used exactly ?

**Comment by slivne** [comment]
@larisau the link is incorrect - it points to the issue

**Comment by slivne** [comment]
@larisau ping

**Comment by slivne** [comment]
@larisau ping

**Comment by larisau** [comment]
Unfortunately I don't have this log anymore. But we can workaround the problem by creating the schema before running cassandra stress(we already have it in longevity test). So we can close this issue.

**Comment by slivne** [comment]
starting from 2.2 we will not have timeouts for system tables - so scylla will not generate the timeout (or not supposed to).

client side timeout may still occur - we can retest this on 2.2 and see if the issue still exists.

Its fine we have a solution for out workloads - we need to understand what will happen for users that have a large cluster and are trying to create a schema.

**Comment by roydahan** [comment]
@amoskong is retesting with "precreate-schema:false"
