### ISSUE TITLE
regression: execution timeout with session of new created user

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3175]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20180116.93076d25b
Cluster size: ·2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

666.development-0.20180116.93076d25b  （`Bad` most of time)
666.development-0.20171223.dfb6296d0     (always `Good`)

Test Code:
```
+    def simple_list_test(self):
+        self.prepare(nodes=2)
+
+        session = self.get_session(user='cassandra', password='cassandra')
+        debug('STEP: create normal user (normal) by super cassandra')
+        session.execute("CREATE USER normal WITH PASSWORD '123456' NOSUPERUSER")
+
+        session = self.get_session(user='normal', password='123456')
+        print list(session.execute("LIST USERS"))
```

```
cluster ccm directory: /home/amos/.dtest/dtest-eJO2CM
Default role created by node1
STEP: create normal user (normal) by super cassandra
E
======================================================================
ERROR: simple_list_test (auth_test.TestAuth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amos/space/scylla-dtest/auth_test.py", line 1795, in simple_list_test
    print list(session.execute("LIST USERS"))
  File "cassandra/cluster.py", line 2122, in cassandra.cluster.Session.execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 3982, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
OperationTimedOut: errors={'127.0.0.2': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.0.2

----------------------------------------------------------------------
Ran 1 test in 47.690s
```

@elcallio @roydahan

**Comment by slivne** [comment]
@hakuch can it be related to your changes for roles ... (I did not check the commit list)

**Comment by hakuch** [comment]
Sorry, I missed this earlier. Nothing obvious jumps out at me as to why any change I have made would have caused this.

I can't find `simple_list_test` in the `dtest` repository, @amoskong. How can I try to reproduce this locally?

**Comment by amoskong** [comment]
Hi @hakuch ,

Just added the simple_list_test code to auth_test.py in the personal branch:
https://github.com/amoskong/scylla-dtest/tree/simple-test

**Comment by hakuch** [comment]
@amoskong, I think this has been fixed now. Please verify, and if so, close this issue.

**Comment by amoskong** [comment]
Absolutely fixed, I checked recent dtest results, and tested in my localhost.
