### ISSUE TITLE
connect AMI instance timeout afte booting

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3234]
*Installation details*
Scylla version (or git commit hash): ami-3ead4243 (latest master ami)
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI
Instance type: tested with c3.large and i2.xlarge

*Description*
Recent [scylla-master-ami-test jobs](http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/) failed for the network issue at the beginning.

[ami-systemlog.txt](https://github.com/scylladb/scylla/files/1757730/ami-systemlog.txt), got from AWS page:
```
CentOS Linux 7 (Core)
Kernel 3.10.0-514.10.2.el7.x86_64 on an x86_64

ip-172-30-0-107 login: [   20.665562] ISOFS: Unable to identify CD-ROM format.
[   20.952178] cloud-init[1900]: Cloud-init v. 0.7.5 running 'init' at Mon, 26 Feb 2018 08:31:04 +0000. Up 20.91 seconds.
[   20.977262] cloud-init[1900]: ci-info: +++++++++++++++++++++++Net device info++++++++++++++++++++++++
[   20.977488] cloud-init[1900]: ci-info: +--------+-------+-----------+-----------+-------------------+
[   20.977995] cloud-init[1900]: ci-info: | Device |   Up  |  Address  |    Mask   |     Hw-Address    |
[   20.979817] cloud-init[1900]: ci-info: +--------+-------+-----------+-----------+-------------------+
[   20.981441] cloud-init[1900]: ci-info: |  lo:   |  True | 127.0.0.1 | 255.0.0.0 |         .         |
[   20.981942] cloud-init[1900]: ci-info: | ens3:  | False |     .     |     .     | 12:81:20:96:a7:98 |
[   20.983550] cloud-init[1900]: ci-info: +--------+-------+-----------+-----------+-------------------+
[   20.985077] cloud-init[1900]: ci-info: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Route info failed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[   21.143710] ISOFS: Unable to identify CD-ROM format.
[   21.174320] cloud-init[1900]: 2018-02-26 08:31:04,256 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [0/120s]: unexpected error ['NoneType' object has no attribute 'status_code']
....
[  147.361379] cloud-init[1900]: 2018-02-26 08:33:10,444 - DataSourceEc2.py[CRITICAL]: Giving up on md from ['http://169.254.169.254/   2009-04-04/meta-data/instance-id'] after 126 seconds
...
```

```
$ ssh -i ~/.ssh/amos-ec2-key.pem  centos@34.226.138.131
ssh: connect to host 34.226.138.131 port 22: Operation timed out
```

http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/label=muninn/190/artifact/latest/remote.log
```
10:33:54 output     L0642 DEBUG| [34.226.138.131] Executing task 'run'
10:33:54 output     L0642 DEBUG| [34.226.138.131] run: rm .bashrc .bash_profile; sudo yum install -y gcc openssl-devel python-devel python2-pip libvirt libvirt-devel pkgconfig gdb-gdbserver git && sudo pip install -r https://raw.githubusercontent.com/avocado-framework/avocado/36lts/requirements.txt && sudo pip install avocado-framework==36.4
10:38:54 output     L0642 DEBUG| 
10:38:54 output     L0642 DEBUG| Fatal error: Timed out trying to connect to 34.226.138.131 (tried 10 times)
10:38:54 output     L0642 DEBUG| 
10:38:54 output     L0642 DEBUG| Underlying exception:
10:38:54 output     L0642 DEBUG|     timed out
10:38:54 output     L0642 DEBUG| 
10:38:54 output     L0642 DEBUG| Aborting.
```

avocado ec2 plugins log:
http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/label=muninn/190/artifact/latest/job.log
```
2018-02-26 10:38:56,116 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/remote/runner.py:228
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR| Traceback (most recent call last):
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_ec2/plugins/ec2.py", line 140, in setup
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|     self._install_avocado(distro_type=self.job.args.ec2_ami_distro_type)
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_ec2/plugins/ec2.py", line 119, in _install_avocado
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|     self.remote.run(install_cmd, timeout=600, quiet=False)
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/remoter.py", line 160, in wrapper
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|     return method(*args, **kwargs)
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/remoter.py", line 230, in run
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|     hosts=[self.hostname])
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 394, in execute
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|     error(e.message, func=func, exception=e.wrapped)
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/fabric/utils.py", line 358, in error
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|     return func(message)
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/fabric/utils.py", line 54, in abort
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|     raise env.abort_exception(msg)
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR| ConnectionError: Timed out trying to connect to 34.226.138.131 (tried 10 times)
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR| 
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR| Underlying exception:
2018-02-26 10:38:56,117 stacktrace       L0042 ERROR|     timed out
```

@syuu1228

**Comment by amoskong** [comment]
This is a regression bug.

last working ami:
- ami-id: ami-64226f1e
- http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/175/
- Dec 28, 2017 1:27 AM
- rebuild result: I resubmit [a job](http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/191/ 
) with `ami-64226f1e`, result is good

**Comment by tzach** [comment]
@amoskong is this the public AMI? which version?

**Comment by roydahan** [comment]
it's master AMI

**Comment by syuu1228** [comment]
Maybe this is same bug with "[PATCH scylla-ami v2 0/3] AMI bootup fix on master" witch is pending patchset.

**Comment by amoskong** [comment]
I just built an ami with Takuya's fix:
https://github.com/syuu1228/scylla-ami/tree/ami-enhanced-networking-fix-v2

```
./dist/ami/build_ami.sh --repo https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/master/647/scylla.repo --target centos
...
==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

us-east-1: ami-8b31daf6
```

Test job: [job/scylla-master-ami-test/label=muninn/193](http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/label=muninn/193/console)
Job doesn't finish, but the network seems good.

**Comment by amoskong** [comment]
[Job](http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/label=muninn/193/console) result is good, added a `Tested-by` in maillist.
[PATCH scylla-ami v2 0/3] AMI bootup fix on master
