### ISSUE TITLE
debian9: stretch repo is invalid

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3241]
*Installation details*
Scylla version (or git commit hash):  scylla_666.development-0.20171202.7f7bf8f-1~stretch_amd64.deb
http://downloads.scylladb.com/deb/unstable/stretch/master/4/scylla.list
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): debian9

Test job: http://jenkins.cloudius-systems.com:8080/job/scylla-2.1-debian9-deb-test/label=huginn/3/artifact/latest/job.log
Repo: http://downloads.scylladb.com/deb/unstable/stretch/master/4/scylla.list

Problem:
1. fail to apt update with a old master repo (20171202)
2. we have [job/scylla-2.1-debian9-deb-test](http://jenkins.cloudius-systems.com:8080/job/scylla-2.1-debian9-deb-test/), but we don't have debian9 repo for scylla branch-2.1
3. we should add a job/scylla-master-debian9-deb-test, even recent [job/scylla-master-debian-deb-9](http://jenkins.cloudius-systems.com:8080/job/scylla-master-debian-deb-9/) are all failed.

```
2018-02-27 20:52:16,048 process          L0333 INFO | Running 'sudo curl http://downloads.scylladb.com/deb/unstable/stretch/master/4/scylla.list -o /etc/apt/sources.list.d/scylla.list'
2018-02-27 20:52:16,070 process          L0420 DEBUG| [stderr]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2018-02-27 20:52:16,071 process          L0420 DEBUG| [stderr]                                  Dload  Upload   Total   Spent    Left  Speed
2018-02-27 20:52:16,511 process          L0420 DEBUG| [stderr] 
2018-02-27 20:52:16,511 process          L0420 DEBUG| [stderr]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2018-02-27 20:52:16,511 process          L0420 DEBUG| [stderr] 100    95  100    95    0     0    215      0 --:--:-- --:--:-- --:--:--   215
2018-02-27 20:52:16,512 process          L0333 INFO | Running 'sudo apt-get update'
2018-02-27 20:52:16,852 process          L0420 DEBUG| [stdout] Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
2018-02-27 20:52:16,862 process          L0420 DEBUG| [stdout] Ign:2 http://mirror.isoc.org.il/pub/debian stretch InRelease
2018-02-27 20:52:16,864 process          L0420 DEBUG| [stdout] Hit:3 http://mirror.isoc.org.il/pub/debian stretch-updates InRelease
2018-02-27 20:52:16,867 process          L0420 DEBUG| [stdout] Hit:4 http://mirror.isoc.org.il/pub/debian stretch Release
2018-02-27 20:52:16,970 process          L0420 DEBUG| [stdout] Ign:5 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch InRelease
2018-02-27 20:52:17,120 process          L0420 DEBUG| [stdout] Ign:7 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch Release
2018-02-27 20:52:17,271 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free all Packages
2018-02-27 20:52:17,421 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free amd64 Packages
2018-02-27 20:52:17,573 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en
2018-02-27 20:52:17,752 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en_IL
2018-02-27 20:52:17,908 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free all Packages
2018-02-27 20:52:18,105 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free amd64 Packages
2018-02-27 20:52:18,274 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en
2018-02-27 20:52:18,426 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en_IL
2018-02-27 20:52:18,581 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free all Packages
2018-02-27 20:52:18,783 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free amd64 Packages
2018-02-27 20:52:18,936 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en
2018-02-27 20:52:19,082 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en_IL
2018-02-27 20:52:19,254 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free all Packages
2018-02-27 20:52:19,402 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free amd64 Packages
2018-02-27 20:52:19,556 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en
2018-02-27 20:52:19,708 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en_IL
2018-02-27 20:52:19,859 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free all Packages
2018-02-27 20:52:20,006 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free amd64 Packages
2018-02-27 20:52:20,155 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en
2018-02-27 20:52:20,475 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en_IL
2018-02-27 20:52:20,624 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free all Packages
2018-02-27 20:52:20,790 process          L0420 DEBUG| [stdout] Err:9 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free amd64 Packages
2018-02-27 20:52:20,790 process          L0420 DEBUG| [stdout]   404  Not Found
2018-02-27 20:52:20,947 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en
2018-02-27 20:52:21,195 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch//non-free Translation-en_IL
2018-02-27 20:52:21,830 process          L0420 DEBUG| [stdout] Reading package lists...
2018-02-27 20:52:21,858 process          L0420 DEBUG| [stderr] W: The repository 'http://downloads.scylladb.com/deb/unstable/stretch/master/4 stretch Release' does not have a Release file.
2018-02-27 20:52:21,858 process          L0420 DEBUG| [stderr] E: Failed to fetch http://downloads.scylladb.com/deb/unstable/stretch/master/4/dists/stretch//non-free/binary-amd64/Packages  404  Not Found
2018-02-27 20:52:21,859 process          L0420 DEBUG| [stderr] E: Some index files failed to download. They have been ignored, or old ones used instead.
```

@syuu1228 @roydahan @slivne

**Comment by amoskong** [comment]
We already have http://jenkins.cloudius-systems.com:8080/job/scylla-master-debian-deb-9-test/

**Comment by amoskong** [comment]
Hi @slivne , error in 
http://jenkins.cloudius-systems.com:8080/job/scylla-master-debian-deb-9-test/configure

```
Template Project:  scylla-t-debian-deb-9-test
No such project ‘scylla-t-debian-deb-9-test’. Did you mean ‘scylla-t-debian8-deb-test’?
```

**Comment by syuu1228** [comment]
@amoskong Since we have decided not to release Debian9 package for 2.1, I think we can drop scylla-2.1-debian9-deb-test. But need it for master.

**Comment by amoskong** [comment]
On Wed, Feb 28, 2018 at 11:41 AM, Takuya ASADA <notifications@github.com>
wrote:

> @amoskong <https://github.com/amoskong> Since we have decided not to
> release Debian9 package for 2.1, I think we can drop
> scylla-2.1-debian9-deb-test. But need it for master.
>

I just disabled job scylla-2.1-debian9-deb-test

**Comment by slivne** [comment]
@amoskong - is this working for master ?

**Comment by amoskong** [comment]
We didn't build available packages for debian9, [Job scylla-master-debian-deb-9](http://jenkins.cloudius-systems.com:8080/job/scylla-master-debian-deb-9/) are always failed.

**Comment by syuu1228** [comment]
We need to merge “[PATCH scylla v2 0/2] Debian/Ubuntu fixes on master” patchset to get fix the error, also need to fix sign-compare/uninitialized compilation error, discussed on “[PATCH scylla 2/3] configure.py: add -Wno-sign-compare to prevent compilation error on antlr3 header” and “[PATCH scylla 3/3] configure.py: add -Wno-uninitialized to prevent compilation error on Boost.Intrusive”.

I’m working on them now.

**Comment by amoskong** [comment]
I saw we successfully build repo for debian9 (stretch) after failed for long time.
But the repo is still invalid.

```
2018-04-01 12:47:20,312 process          L0333 INFO | Running 'sudo curl https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/stretch/master/124/scylla.list -o /etc/apt/sources.list.d/scylla.list -L'
2018-04-01 12:47:20,388 process          L0420 DEBUG| [stderr]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2018-04-01 12:47:20,389 process          L0420 DEBUG| [stderr]                                  Dload  Upload   Total   Spent    Left  Speed
2018-04-01 12:47:21,134 process          L0420 DEBUG| [stderr] 
2018-04-01 12:47:21,134 process          L0420 DEBUG| [stderr]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2018-04-01 12:47:21,134 process          L0420 DEBUG| [stderr]   0    97    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2018-04-01 12:47:21,134 process          L0420 DEBUG| [stderr] 100    97  100    97    0     0    130      0 --:--:-- --:--:-- --:--:--   130
2018-04-01 12:47:21,137 process          L0333 INFO | Running 'sudo apt-get update'
2018-04-01 12:47:21,339 process          L0420 DEBUG| [stdout] Ign:1 http://mirror.isoc.org.il/pub/debian stretch InRelease
2018-04-01 12:47:21,346 process          L0420 DEBUG| [stdout] Hit:2 http://mirror.isoc.org.il/pub/debian stretch-updates InRelease
2018-04-01 12:47:21,349 process          L0420 DEBUG| [stdout] Hit:3 http://mirror.isoc.org.il/pub/debian stretch Release
2018-04-01 12:47:21,479 process          L0420 DEBUG| [stdout] Hit:5 http://security.debian.org/debian-security stretch/updates InRelease
2018-04-01 12:47:21,748 process          L0420 DEBUG| [stdout] Ign:6 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch InRelease
2018-04-01 12:47:21,922 process          L0420 DEBUG| [stdout] Ign:7 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch Release
2018-04-01 12:47:22,115 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free all Packages
2018-04-01 12:47:22,315 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free amd64 Packages
2018-04-01 12:47:22,467 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en_IL
2018-04-01 12:47:22,619 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en
2018-04-01 12:47:22,769 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free all Packages
2018-04-01 12:47:22,922 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free amd64 Packages
2018-04-01 12:47:23,075 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en_IL
2018-04-01 12:47:23,226 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en
2018-04-01 12:47:23,379 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free all Packages
2018-04-01 12:47:23,531 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free amd64 Packages
2018-04-01 12:47:23,684 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en_IL
2018-04-01 12:47:23,834 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en
2018-04-01 12:47:23,985 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free all Packages
2018-04-01 12:47:24,135 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free amd64 Packages
2018-04-01 12:47:24,283 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en_IL
2018-04-01 12:47:24,433 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en
2018-04-01 12:47:24,585 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free all Packages
2018-04-01 12:47:24,745 process          L0420 DEBUG| [stdout] Ign:9 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free amd64 Packages
2018-04-01 12:47:24,898 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en_IL
2018-04-01 12:47:25,222 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en
2018-04-01 12:47:25,371 process          L0420 DEBUG| [stdout] Ign:8 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free all Packages
2018-04-01 12:47:25,559 process          L0420 DEBUG| [stdout] Err:9 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free amd64 Packages
2018-04-01 12:47:25,559 process          L0420 DEBUG| [stdout]   404  Not Found
2018-04-01 12:47:25,709 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en_IL
2018-04-01 12:47:25,863 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch//non-free Translation-en
2018-04-01 12:47:26,497 process          L0420 DEBUG| [stdout] Reading package lists...
2018-04-01 12:47:26,524 process          L0420 DEBUG| [stderr] W: The repository 'http://downloads.scylladb.com/deb/unstable/stretch/master/124 stretch Release' does not have a Release file.
2018-04-01 12:47:26,525 process          L0420 DEBUG| [stderr] E: Failed to fetch http://downloads.scylladb.com/deb/unstable/stretch/master/124/dists/stretch//non-free/binary-amd64/Packages  404  Not Found
2018-04-01 12:47:26,525 process          L0420 DEBUG| [stderr] E: Some index files failed to download. They have been ignored, or old ones used instead.
2018-04-01 12:47:26,527 stacktrace       L0036 ERROR| 
2018-04-01 12:47:26,527 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:436
2018-04-01 12:47:26,528 stacktrace       L0042 ERROR| Traceback (most recent call last):
2018-04-01 12:47:26,528 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-debian-deb-9-test/label/huginn/scylla-artifacts.py", line 707, in setUp
2018-04-01 12:47:26,528 stacktrace       L0042 ERROR|     self.scylla_setup()
2018-04-01 12:47:26,528 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-debian-deb-9-test/label/huginn/scylla-artifacts.py", line 693, in scylla_setup
2018-04-01 12:47:26,528 stacktrace       L0042 ERROR|     installer.run()
2018-04-01 12:47:26,528 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-debian-deb-9-test/label/huginn/scylla-artifacts.py", line 303, in run
2018-04-01 12:47:26,528 stacktrace       L0042 ERROR|     pkgs = self.env_setup()
2018-04-01 12:47:26,528 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-debian-deb-9-test/label/huginn/scylla-artifacts.py", line 476, in env_setup
2018-04-01 12:47:26,529 stacktrace       L0042 ERROR|     process.run('sudo apt-get update')
2018-04-01 12:47:26,529 stacktrace       L0042 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 1031, in run
2018-04-01 12:47:26,529 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
2018-04-01 12:47:26,529 stacktrace       L0042 ERROR| CmdError: Command 'sudo apt-get update' failed (rc=100)
2018-04-01 12:47:26,529 stacktrace       L0043 ERROR| 
2018-04-01 12:47:26,538 test             L0581 ERROR| ERROR 1-/root/avocado/tests/jenkins/slave/workspace/scylla-master-debian-deb-9-test/label/huginn/scylla-artifacts.py:ScyllaArtifactSanity.test_after_install -> TestSetupFail: Command 'sudo apt-get update' failed (rc=100)
```

**Comment by amoskong** [comment]
Manually tested latest Debian9 repo, the basic test is fine.
- repo: [deb/unstable/stretch/master/134/scylladb/scylla.list](http://downloads.scylladb.com.s3.amazonaws.com/deb/unstable/stretch/master/134/scylladb/scylla.list)
- scylla version:  666.development-0.20180409.80651e6dc-1~stretch 

The artifact-test job is running with the repo:
[job/scylla-staging-debian-deb-9-test-amos-clone/1](http://jenkins.cloudius-systems.com:8080/job/scylla-staging-debian-deb-9-test-amos-clone/1)

---

*Jenkins Config Problem*: [scylla-master-debian-deb-9 job](http://jenkins.cloudius-systems.com:8080/job/scylla-master-debian-deb-9/) still passes wrong repo url to [scylla-master-debian-deb-9-test job](http://jenkins.cloudius-systems.com:8080/job/scylla-master-debian-deb-9-test/11/parameters/)
- passed scylla_repo_file_url: https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/stretch/master/134/scylla.list
- right scylla_repo_file_url: https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/stretch/master/134/scylladb/scylla.list

**Comment by topilski** [comment]
Hi, how can i install scylla on Debian 9 from repo?

**Comment by amoskong** [comment]
Debian9 isn't officially supported, there is not repo for Debian9 right now.

@tzach Can you help to confirm this?

**Comment by slivne** [comment]
Debina9 is part of 2.3 - Done
