### ISSUE TITLE
Cluster with multi seed via ccm does not work with python driver 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#330]
Most of our testing is done via cassandra-stress, cqlsh, dtest

We have a failing dtest on head

```
pkill -9 java; pkill -9 scylla; rm -Rf ~/.dtest/*; KEEP_TEST_DIR=true PRINT_DEBUG=true DEBUG=true nosetests -v -s  simple_cluster_driver_test.py:TestSimpleCluster.simple_rf_3_consistency_level_tests
```

head

commit b96ad54cbff0d85d15fc5a0cb774595d923ef297
Author: Gleb Natapov <gleb@cloudius-systems.com>
Date:   Wed Sep 9 14:42:32 2015 +0300

    do not leak write response handler in logged batch.
    
    If exception is thrown during creation of a write response handler those
    that are already created need to be removed explicitly.

I have tried to check if I can remove dtest and work directly with the python driver to see if it simple to create the issue.

It seems we have more serious problems - working directly with the driver simply does not work ... I am not sure why

here is the mimized program

```
#!/usr/bin/python
from cassandra.cluster import Cluster
import subprocess, tempfile, os, shutil
import time
from cassandra.query import SimpleStatement
from cassandra import Unavailable,ConsistencyLevel

def debug(msg):
    print msg

class TestSimpleCluster:

#    __urchin_args__=['--smp', '1','--default-log-level','trace']
#
#    def __init__(self, *args, **kwargs):
#        Tester.__init__(self, *args, **kwargs)

#    def prepare(self):
#        """
#        Sets up cluster to test against.
#        """
#        cluster = self.cluster
#        return cluster



    def clname(self,cl):
        map = {
            ConsistencyLevel.ANY : 'ANY',
            ConsistencyLevel.ONE : 'ONE',
            ConsistencyLevel.TWO : 'TWO',
            ConsistencyLevel.THREE : 'THREE',
            ConsistencyLevel.QUORUM : 'QUORUM',
            ConsistencyLevel.ALL : 'ALL'
        }
        return map[cl]


    def simple_consistency_level_validate(self,session,node,read_keys,read_cls_pass,read_cls_fail,read_cls_pass_all,write_keys,write_cls_pass,write_cls_fail,write_cls_pass_all):
        for cl in read_cls_pass:
            debug("read %s cl %s" % (node,self.clname(cl)))
            read_pass=0
            read_fail=0
            for key in read_keys:
                try:
                   query1 = SimpleStatement("SELECT * FROM ks.test1 WHERE k=%s" % key,consistency_level=cl)
                   res = session.execute(query1)
                   assert len(res) == 1, res
                   read_pass=read_pass+1
                except Exception as ex:
                   read_fail=read_fail+1
            assert (read_fail == 0 or read_cls_pass_all == False), "Expected all reads to pass, pass %s, fail %s" % (read_pass,read_fail)
            assert (read_fail > 0 or read_cls_pass_all == True), "Expected some reads to fail, pass %s, fail %s" % (read_pass,read_fail)

        for cl in read_cls_fail:
            query1 = SimpleStatement("SELECT * FROM ks.test1 WHERE k=1",consistency_level=cl)
            try:
                res = sessionexecute(query1)
                assert("Consistency level %s is not possible" % self.clname(cl))
            except Unavailable as ex:
                assert(True)
            except Exception as ex:
                assert("Expected cassandra.Unavilable exception received %s" %ex)

        for cl in write_cls_pass:
            debug("write %s cl %s" % (node,self.clname(cl)))
            write_pass=0
            write_fail=0
            for key in write_keys:
                try:
                   insert = SimpleStatement("insert into ks.test1  (k,c) values (%s,%s)" % (key,key),consistency_level=cl)
                   res = session.execute(insert)
                   write_pass=write_pass+1
                except Exception as ex:
                   write_fail=write_fail+1
            assert (write_fail == 0 or write_cls_pass_all == False), "Expected all writes to pass, pass %s, fail %s" % (write_pass,write_fail)
            assert (write_fail > 0 or write_cls_pass_all == True), "Expected some writes to fail, pass %s, fail %s" % (write_pass,write_fail)

        for cl in write_cls_fail:
            insert = SimpleStatement("insert into ks.test1 (k,c) values (101,101)",consistency_level=cl)
            try:
                res = sessionexecute(insert)
                assert("Consistency level %s is not possible" % self.clname(cl))
            except Unavailable as ex:
                assert(True)
            except Exception as ex:
                assert("Expected cassandra.Unavilable exception received %s" %ex)

    def prepare_cluster(self):
        cluster = Cluster(['127.0.0.1', '127.0.0.2','127.0.0.3'])
        session = cluster.connect()
        session.execute("CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'} ;")
        session.execute("CREATE TABLE ks.test1 ( k int PRIMARY KEY, c int);")
        return session;

    def simple_rf_3_consistency_level_tests(self):
        session = self.prepare_cluster()

        keys = range(1,100)
        for val in keys:
            insert = SimpleStatement("insert into ks.test1  (k,c) values (%s,%s)" % (val,val), consistency_level=ConsistencyLevel.ALL)
            session.execute(insert)


        debug("3 nodes, node1,node2,node3 are running")
        # FIXME - used to make sure write has completed
        time.sleep(10)
        read_cls_pass = [ConsistencyLevel.ONE, ConsistencyLevel.TWO, ConsistencyLevel.THREE, ConsistencyLevel.QUORUM, ConsistencyLevel.ALL]
        write_cls_pass = [ConsistencyLevel.ANY, ConsistencyLevel.ONE, ConsistencyLevel.TWO, ConsistencyLevel.THREE, ConsistencyLevel.QUORUM, ConsistencyLevel.ALL]
        self.simple_consistency_level_validate(session,"node 1",keys,read_cls_pass,[],True,range(101,200),write_cls_pass,[],True)


x =  TestSimpleCluster()
x.simple_rf_3_consistency_level_tests()
```

it starts by creating a keyspace and table and that already has issues

starting a cluster with ccm 
1. ccm create urchin --urchin --vnodes -n 3 --install-dir=/home/shlomi/urchin
2. ccm start
3. running the program 

I get
```
shlomi@localhost~/urchin-dtest (master)$ ./simple_rf_3_consistency_level_tests_stand_alone.py 
Traceback (most recent call last):
  File "./simple_rf_3_consistency_level_tests_stand_alone.py", line 114, in <module>
    x.simple_rf_3_consistency_level_tests()
  File "./simple_rf_3_consistency_level_tests_stand_alone.py", line 97, in simple_rf_3_consistency_level_tests
    session = self.prepare_cluster()
  File "./simple_rf_3_consistency_level_tests_stand_alone.py", line 92, in prepare_cluster
    session.execute("CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'} ;")
  File "/usr/lib64/python2.7/site-packages/cassandra/cluster.py", line 1405, in execute
    result = future.result(timeout)
  File "/usr/lib64/python2.7/site-packages/cassandra/cluster.py", line 2978, in result
    raise OperationTimedOut(errors=self._errors, last_host=self._current_host)
cassandra.OperationTimedOut: errors={}, last_host=127.0.0.3
```

entering the nodes (all three) with cqlsh shows the keyspace exists

cqlsh> select * from system.schema_keyspaces;

 keyspace_name | durable_writes | strategy_class                             | strategy_options
---------------+----------------+--------------------------------------------+----------------------------
        system |           True | org.apache.cassandra.locator.LocalStrategy |                         {}
            ks |           True |                             SimpleStrategy | {"replication_factor":"3"}

(2 rows)
cqlsh> 

marking out the create keyspace and allowing the create table has a similar issue

```
shlomi@localhost~/urchin-dtest (master)$ ./simple_rf_3_consistency_level_tests_stand_alone.py 
Traceback (most recent call last):
  File "./simple_rf_3_consistency_level_tests_stand_alone.py", line 114, in <module>
    x.simple_rf_3_consistency_level_tests()
  File "./simple_rf_3_consistency_level_tests_stand_alone.py", line 97, in simple_rf_3_consistency_level_tests
    session = self.prepare_cluster()
  File "./simple_rf_3_consistency_level_tests_stand_alone.py", line 93, in prepare_cluster
    session.execute("CREATE TABLE ks.test1 ( k int PRIMARY KEY, c int);")
  File "/usr/lib64/python2.7/site-packages/cassandra/cluster.py", line 1405, in execute
    result = future.result(timeout)
  File "/usr/lib64/python2.7/site-packages/cassandra/cluster.py", line 2978, in result
    raise OperationTimedOut(errors=self._errors, last_host=self._current_host)
cassandra.OperationTimedOut: errors={}, last_host=127.0.0.2
```

again the table is created

then I need to mark out the create table

This test program works with Origin without any issue that is

starting a cluster with ccm 
1. ccm create orig --vnodes -n 3 --install-dir=/home/shlomi/cassandra
2. ccm start
3. running the program 

it ends ok - no issues

I am not sure if there is an issue with timing or starvation as all instances run on the same cpu  .... yet this works ok in other cluster dtests -

**Comment by slivne** [comment]
retested this with 

commit b2630db514d595d3a19c542af713e18b867d7994
Author: Takuya ASADA <syuu@cloudius-systems.com>
Date:   Thu Sep 24 09:18:06 2015 +0000

    dist: remove rpm dependency to libvirt
    
    This is for testing virtio mode, since we don't officially recommend to use virtio mode we should drop it.
    
    Signed-off-by: Takuya ASADA <syuu@cloudius-systems.com>

it runs into #418

**Comment by slivne** [comment]
with 

commit 2998b891f35346cc4d62bf779ab901ae841a7a1c
Author: Gleb Natapov <gleb@scylladb.com>
Date:   Wed Sep 30 13:31:13 2015 +0300

    storage_proxy: fix crash during background read repair
    
    Lazy digest calculation code introduced a bug in background read repair.
    The problem is that digest_read_resolver::resolve() destroys one data
    result (it is moved to a caller to be sent as a reply), so during
    background digest match there is no value to calculate a digest from.
    Copying data to the caller would be most elegant solution, but also
    slowest one, so lets just treat the case where there is only one
    target queried and skip digest calculation in this case since we know
    digest_match() will do nothing.

it passes
