### ISSUE TITLE
cassandra-stress: fails with RF = 2 and CL = TWO

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#333]
On aws, there are 2 nodes in the cluster.

```
cassandra-stress  mixed ratio\(write=95,read=5\) n=10000 cl=TWO  -rate threads=8  -mode cql3 native -schema replication\(strategy=org.apache.cassandra.locator.SimpleStrategy,factor=2\) -node 172.31.14.220
\Sleeping 2s...
Running [READ, WRITE] with 8 threads for 10000 iteration
INFO  09:22:21 Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO  09:22:21 New Cassandra host /172.31.14.220:9042 added
INFO  09:22:21 New Cassandra host /172.31.15.223:9042 added
Connected to cluster: Test Cluster
Datatacenter: datacenter1; Host: /172.31.14.220; Rack: rack1
Datatacenter: datacenter1; Host: /172.31.15.223; Rack: rack1
Failed to connect over JMX; not collecting these stats
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
java.io.IOException: Operation x10 on key(s) [4f34383236504e333330]: Error executing: (UnavailableException): Not enough replica available for query at consistency TWO (2 required but only 1 alive)

        at org.apache.cassandra.stress.Operation.error(Operation.java:216)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)java.io.IOException: Operation x10 on key(s) [334c3635384b32303930]: Error execu
ting: (UnavailableException): Not enough replica available for query at consistency TWO (2 required but only 1 alive)


        at org.apache.cassandra.stress.Operation.error(Operation.java:216)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)
java.io.IOException: Operation x10 on key(s) [305036304b4c4f343330]: Error executing: (UnavailableException): Not enough replica available for query at consistency TWO (2 required but only 1 alive)

        at org.apache.cassandra.stress.Operation.error(Operation.java:216)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
java.io.IOException: Operation x10 on key(s) [4e5031384d4c38313530]: Error executing: (UnavailableException): Not enough replica available for query at consistency TWO (2 required but only 1 alive)

        at org.apache.cassandra.stress.Operation.error(Operation.java:216)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency TWO (2 required but only 1 alive)
java.io.IOException: Operation x10 on key(s) [4f303435383438313830]: Error executing: (UnavailableException): Not enough replica available for query at consistency TWO (2 required but only 1 alive)
```

**Comment by slivne** [comment]
for anglerfish we have a solution for large servers on aws in which cpu0 handles all networking interrupts and the rest of the cpus run scylla 

for next milestone we may (probably) have a better solution

**Comment by slivne** [comment]
@asias  please close this
