### ISSUE TITLE
nodetool gossipinfo fails with NullPointerException

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#3330]
start node 1 2 3
shutdown node2
shutdown node1 and node3
start node1 and node3
run nodetool gossipinfo on node1 fails

```
$ nodetool gossipinfo
error: null
-- StackTrace --
java.lang.NullPointerException
        at org.apache.cassandra.gms.FailureDetector.getEndpointStateMap(FailureDetector.java:108)
        at org.apache.cassandra.gms.FailureDetector.getAllEndpointStates(FailureDetector.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
        at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

Run curl, there is no "application_state" for node2. This is expected since node is not up yet, it only has the basic gossip info by added during boot up with gossiper::add_saved_endpoint. 

```
curl -X GET --header "Accept: application/json" "http://127.0.0.1:10000/failure_detector/endpoints/" | python -mjson.tool
   {
   "addrs": "127.0.0.2",
   "generation": 0,
   "is_alive": false,
   "update_time": 1521778757334,
   "version": 0
   },
```

The code for the above http api is:

```
fd::get_all_endpoint_states.set(r, [](std::unique_ptr<request> req) {
    std::vector<fd::endpoint_state> res;
    for (auto i : gms::get_local_gossiper().endpoint_state_map) {
        fd::endpoint_state val;
        val.addrs = boost::lexical_cast<std::string>(i.first);
        val.is_alive = i.second.is_alive();
        val.generation = i.second.get_heart_beat_state().get_generation();
        val.version = i.second.get_heart_beat_state().get_heart_beat_version();
        val.update_time = i.second.get_update_timestamp().time_since_epoch().count();
        for (auto a : i.second.get_application_state_map()) {
            fd::version_value version_val;
            // We return the enum index and not it's name to stay compatible to origin
            // method that the state index are static but the name can be changed.
            version_val.application_state = static_cast<std::underlying_type<gms::application_state>::type>(a.first);
            version_val.value = a.second.value;
            version_val.version = a.second.version;
            val.application_state.push(version_val);
        }
        res.push_back(val);
    }
    return make_ready_future<json::json_return_type>(res);
});
```

Can we return an empty list in this case for application_state?

**Comment by asias** [comment]
@amnonh

**Comment by slivne** [comment]
@avikivity can I close this ?
