### ISSUE TITLE
ASAN complains in unit tests (debug mode) on PPC64

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3345]
Installation details
Scylla version (or git commit hash): 58e47fa0b358d8690e174dfffbe35aa6a8dc2dee
Cluster size: 1
OS: CentOS 7.4.1708
Arch: ppc64le

Description
Some tests are failing with the following ASAN error:
```
$ build/debug/tests/types_test -- -c1 -m4G --collectd 0
WARNING: debug mode. Not for benchmarking or production
Running 48 test cases...
WARN  2018-04-04 21:52:33,387 seastar - Seastar compiled with default allocator, heap profiler not supported
WARN  2018-04-04 21:52:33,414 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
WARN  2018-04-04 21:52:34,521 [shard 0] org.apache.cassandra.db.marshal.TimestampType - Changing from DateType to TimestampType is allowed, but be wary that they sort differently for pre-unix-epoch timestamps (negative timestamp values) and thus this change will corrupt your data if you have such negative timestamp. So unless you know that you don't have *any* pre-unix-epoch timestamp you should change back to DateType
WARN  2018-04-04 21:52:34,521 [shard 0] org.apache.cassandra.db.marshal.DateType - Changing from TimestampType to DateType is allowed, but be wary that they sort differently for pre-unix-epoch timestamps (negative timestamp values) and thus this change will corrupt your data if you have such negative timestamp. There is no reason to switch from DateType to TimestampType except if you were using DateType in the first place and switched to TimestampType by mistake.

*** No errors detected
ASAN:DEADLYSIGNAL
=================================================================
==101672==ERROR: AddressSanitizer: SEGV on unknown address 0x3fffa6fd53b0 (pc 0x00001006f614 bp 0x3fffa6a83cd0 sp 0x3fffa6a83cd0 T2)
==101672==The signal is caused by a UNKNOWN memory access.
    #0 0x1006f610  (/home/user1/scylla/build/debug/tests/types_test+0x1006f610)
    #1 0x1057d48c  (/home/user1/scylla/build/debug/tests/types_test+0x1057d48c)
    #2 0x104f4d14  (/home/user1/scylla/build/debug/tests/types_test+0x104f4d14)
    #3 0x108d53e4  (/home/user1/scylla/build/debug/tests/types_test+0x108d53e4)
    #4 0x108c287c  (/home/user1/scylla/build/debug/tests/types_test+0x108c287c)
    #5 0x108a91e0  (/home/user1/scylla/build/debug/tests/types_test+0x108a91e0)
    #6 0x3fffb0453630  (/opt/scylladb/lib64/libstdc++.so.6+0x103630)
    #7 0x3fffb123d7d0  (/opt/scylladb/lib64/libasan.so.4+0x12d7d0)
    #8 0x3fffb1154818  (/opt/scylladb/lib64/libasan.so.4+0x44818)
    #9 0x3fffaf1a8af0 in start_thread (/lib64/libpthread.so.0+0x8af0)
    #10 0x3fffaf0d4ef0 in __clone (/lib64/libc.so.6+0x124ef0)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/user1/scylla/build/debug/tests/types_test+0x1006f610)
Thread T2 (timer-0) created by T1 here:
    #0 0x3fffb11545a8 in pthread_create (/opt/scylladb/lib64/libasan.so.4+0x445a8)
    #1 0x3fffb0453b9c in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/opt/scylladb/lib64/libstdc++.so.6+0x103b9c)
    #2 0x104f50c4  (/home/user1/scylla/build/debug/tests/types_test+0x104f50c4)
    #3 0x1006a2ec  (/home/user1/scylla/build/debug/tests/types_test+0x1006a2ec)
    #4 0x10100fd0  (/home/user1/scylla/build/debug/tests/types_test+0x10100fd0)
    #5 0x10107998  (/home/user1/scylla/build/debug/tests/types_test+0x10107998)
    #6 0x10beeca0  (/home/user1/scylla/build/debug/tests/types_test+0x10beeca0)
    #7 0x1dd2fd60  (/home/user1/scylla/build/debug/tests/types_test+0x1dd2fd60)
    #8 0x1dd3beec  (/home/user1/scylla/build/debug/tests/types_test+0x1dd3beec)
    #9 0x104ee078  (/home/user1/scylla/build/debug/tests/types_test+0x104ee078)
    #10 0x10a446dc  (/home/user1/scylla/build/debug/tests/types_test+0x10a446dc)
    #11 0x3fffb123d7d0  (/opt/scylladb/lib64/libasan.so.4+0x12d7d0)
    #12 0x3fffb1154818  (/opt/scylladb/lib64/libasan.so.4+0x44818)
    #13 0x3fffaf1a8af0 in start_thread (/lib64/libpthread.so.0+0x8af0)
    #14 0x3fffaf0d4ef0 in __clone (/lib64/libc.so.6+0x124ef0)

Thread T1 created by T0 here:
    #0 0x3fffb11545a8 in pthread_create (/opt/scylladb/lib64/libasan.so.4+0x445a8)
    #1 0x10a45090  (/home/user1/scylla/build/debug/tests/types_test+0x10a45090)
    #2 0x10a44928  (/home/user1/scylla/build/debug/tests/types_test+0x10a44928)
    #3 0x1dd35298  (/home/user1/scylla/build/debug/tests/types_test+0x1dd35298)
    #4 0x1dd30230  (/home/user1/scylla/build/debug/tests/types_test+0x1dd30230)
    #5 0x1db1bad4  (/home/user1/scylla/build/debug/tests/types_test+0x1db1bad4)
    #6 0x1da966d0  (/home/user1/scylla/build/debug/tests/types_test+0x1da966d0)
    #7 0x1dcd6f78  (/home/user1/scylla/build/debug/tests/types_test+0x1dcd6f78)
    #8 0x1dcc1b0c  (/home/user1/scylla/build/debug/tests/types_test+0x1dcc1b0c)
    #9 0x1dc9fc34  (/home/user1/scylla/build/debug/tests/types_test+0x1dc9fc34)
    #10 0x147ae8dc  (/home/user1/scylla/build/debug/tests/types_test+0x147ae8dc)
    #11 0x1db98570  (/home/user1/scylla/build/debug/tests/types_test+0x1db98570)
    #12 0x1dca61dc  (/home/user1/scylla/build/debug/tests/types_test+0x1dca61dc)
    #13 0x1dc2c708  (/home/user1/scylla/build/debug/tests/types_test+0x1dc2c708)
    #14 0x1dbe2630  (/home/user1/scylla/build/debug/tests/types_test+0x1dbe2630)
    #15 0x1daae784  (/home/user1/scylla/build/debug/tests/types_test+0x1daae784)
    #16 0x1daaee44  (/home/user1/scylla/build/debug/tests/types_test+0x1daaee44)
    #17 0x1dab1e38  (/home/user1/scylla/build/debug/tests/types_test+0x1dab1e38)
    #18 0x1da9f87c  (/home/user1/scylla/build/debug/tests/types_test+0x1da9f87c)
    #19 0x1dae8f64  (/home/user1/scylla/build/debug/tests/types_test+0x1dae8f64)
    #20 0x1db1bd20  (/home/user1/scylla/build/debug/tests/types_test+0x1db1bd20)
    #21 0x3fffaefd497c in generic_start_main.isra.0 (/lib64/libc.so.6+0x2497c)
    #22 0x3fffaefd4b70 in __libc_start_main (/lib64/libc.so.6+0x24b70)

==101672==ABORTING
```

This is the same issue as in https://github.com/scylladb/scylla-enterprise/issues/508

**Comment by denesb** [comment]
Can you build and run the `_g` version of the test so we can see resolved backtraces?

**Comment by vladzcloudius** [comment]
When I compiled the same test with the in-box tool chain on Fedora 27 the test failed as follows:

```
$ build/debug/tests/types_test_g -- -c1 -m4G --collectd 0
==56179==AddressSanitizer CHECK failed: ../../../../libsanitizer/asan/asan_poisoning.cc:35 "((AddrIsInMem(addr))) != (0)" (0x0, 0x0)
    <empty stack>
$
```

which resembles the issue described here: https://github.com/google/sanitizers/issues/682,
which is supposed to be fixed by https://reviews.llvm.org/rL269633. I guess this either didn't make to ppc64le branch or this doesn't fix the issue on Power.

**Comment by James-A-Clark** [comment]
I'm also having a similar issue. I found this issue by searching for "asan_poisoning.cc:35".

Any program I build with asan enabled causes the program to crash with this error:
``` -> ./test
==1196==AddressSanitizer CHECK failed: ../../../../libsanitizer/asan/asan_poisoning.cc:35 "((AddrIsInMem(addr))) != (0)" (0x0, 0x0)
    <empty stack>
```

The source code for this program is:
`int main() { 
   return 0;
}`

Compilation command:
`g++  -fsanitize=address -o test test.c`

Platform: ppc64le
OS: Redhat 7
Compiler: GCC 7.3.0
ASAN Version: I'm not sure, whichever comes from GCC 7.3.0 by default.

**Comment by avikivity** [comment]
ppc64 anf gcc 7.3 are no longer supported, closing.
