### ISSUE TITLE
types_test unit test crashes in a debug mode

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3356]
Installation details
Scylla version (or git commit hash): 1a9aaece3e38e0418d30a632140b3062e8d37bce
OS: CentOS 7.4.1708
Tool chain: ScyllaDB's 7.2 or 7.3 toolchain (I used 7.3 toolchain)

Hardware details
Platform: GCE n1-standard-32 instance

Description

1. Clone the sources.
2. `python3.4 ./configure.py --static-boost --compiler=g++-7.3 --python python3.4 --ldflag=-Wl,-rpath=/opt/scylladb/lib64`
3. `ninja-build ./build/debug/tests/types_test_g`
4. `build/debug/tests/types_test_g -- -c1 -m4G --collectd 0`

The result is going to be as follows:
```
$ build/debug/tests/types_test_g -- -c1 -m4G --collectd 0
Running 48 test cases...
WARNING: debug mode. Not for benchmarking or production
WARN  2018-04-12 15:42:30,956 seastar - Seastar compiled with default allocator, heap profiler not supported
WARN  2018-04-12 15:42:30,963 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
WARN  2018-04-12 15:42:31,671 [shard 0] org.apache.cassandra.db.marshal.TimestampType - Changing from DateType to TimestampType is allowed, but be wary that they sort differently for pre-unix-epoch timestamps (negative timestamp values) and thus this change will corrupt your data if you have such negative timestamp. So unless you know that you don't have *any* pre-unix-epoch timestamp you should change back to DateType
WARN  2018-04-12 15:42:31,671 [shard 0] org.apache.cassandra.db.marshal.DateType - Changing from TimestampType to DateType is allowed, but be wary that they sort differently for pre-unix-epoch timestamps (negative timestamp values) and thus this change will corrupt your data if you have such negative timestamp. There is no reason to switch from DateType to TimestampType except if you were using DateType in the first place and switched to TimestampType by mistake.

*** No errors detected
ASAN:DEADLYSIGNAL
=================================================================
==13473==ERROR: AddressSanitizer: SEGV on unknown address 0x7f113bbd5538 (pc 0x0000004240fe bp 0x7f113b84b9d0 sp 0x7f113b84b6a0 T2)
==13473==The signal is caused by a WRITE memory access.
    #0 0x4240fd in seastar::reactor::task_quota_timer_thread_fn() core/reactor.cc:580
    #1 0x7a7056 in void std::__invoke_impl<void, void (seastar::reactor::*)(), seastar::reactor*>(std::__invoke_memfun_deref, void (seastar::reactor::*&&)(), seastar::reactor*&&) (/home/vladz/scylla/build/debug/tests/types_test_g+0x7a7056)
    #2 0x74ccd7 in std::__invoke_result<void (seastar::reactor::*)(), seastar::reactor*>::type std::__invoke<void (seastar::reactor::*)(), seastar::reactor*>(void (seastar::reactor::*&&)(), seastar::reactor*&&) (/home/vladz/scylla/build/debug/tests/types_test_g+0x74ccd7)
    #3 0x9d5671 in decltype (__invoke((_S_declval<0ul>)(), (_S_declval<1ul>)())) std::thread::_Invoker<std::tuple<void (seastar::reactor::*)(), seastar::reactor*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (/home/vladz/scylla/build/debug/tests/types_test_g+0x9d5671)
    #4 0x9c8570 in std::thread::_Invoker<std::tuple<void (seastar::reactor::*)(), seastar::reactor*> >::operator()() (/home/vladz/scylla/build/debug/tests/types_test_g+0x9c8570)
    #5 0x9b648a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (seastar::reactor::*)(), seastar::reactor*> > >::_M_run() (/home/vladz/scylla/build/debug/tests/types_test_g+0x9b648a)
    #6 0x7f114a919c9e  (/opt/scylladb/lib64/libstdc++.so.6+0xbcc9e)
    #7 0x7f1147206e24 in start_thread (/lib64/libpthread.so.0+0x7e24)
    #8 0x7f1146f3434c in __clone (/lib64/libc.so.6+0xf834c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV core/reactor.cc:580 in seastar::reactor::task_quota_timer_thread_fn()
Thread T2 (timer-0) created by T1 here:
    #0 0x7f114b93f09f in pthread_create (/opt/scylladb/lib64/libasan.so.4+0x3809f)
    #1 0x7f114a919fd4 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/opt/scylladb/lib64/libstdc++.so.6+0xbcfd4)
    #2 0x4201ed in seastar::reactor::reactor(unsigned int) core/reactor.cc:437
    #3 0x48f1ff in seastar::smp::allocate_reactor(unsigned int) core/reactor.cc:3744
    #4 0x49411d in seastar::smp::configure(boost::program_options::variables_map) core/reactor.cc:4006
    #5 0xbf8fa7 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) core/app-template.cc:162
    #6 0x9f5e0e9 in operator() seastar/tests/test_runner.cc:63
    #7 0x9f67199 in _M_invoke /opt/scylladb/include/c++/7/bits/std_function.h:316
    #8 0x7484d3 in std::function<void ()>::operator()() const /opt/scylladb/include/c++/7/bits/std_function.h:706
    #9 0xad5c90 in seastar::posix_thread::start_routine(void*) core/posix.cc:52
    #10 0x7f1147206e24 in start_thread (/lib64/libpthread.so.0+0x7e24)

Thread T1 created by T0 here:
    #0 0x7f114b93f09f in pthread_create (/opt/scylladb/lib64/libasan.so.4+0x3809f)
    #1 0xad644a in seastar::posix_thread::posix_thread(seastar::posix_thread::attr, std::function<void ()>) core/posix.cc:83
    #2 0xad5e40 in seastar::posix_thread::posix_thread(std::function<void ()>) core/posix.cc:57
    #3 0x9f622ec in make_unique<seastar::posix_thread, seastar::test_runner::start(int, char**)::<lambda()> > /opt/scylladb/include/c++/7/bits/unique_ptr.h:825
    #4 0x9f5e4b0 in seastar::test_runner::start(int, char**) seastar/tests/test_runner.cc:49
    #5 0x9df39a8 in seastar::init_unit_test_suite() seastar/tests/test-utils.cc:77
    #6 0x9d90cc4 in invoke_init_func /opt/scylladb/include/boost/test/impl/framework.ipp:176
    #7 0x9f241af in void boost::_bi::list1<boost::_bi::value<bool (*)()> >::operator()<void (*)(bool (*)()), boost::_bi::list0>(boost::_bi::type<void>, void (*&)(bool (*)()), boost::_bi::list0&, int) /opt/scylladb/include/boost/bind/bind.hpp:259
    #8 0x9f16c95 in boost::_bi::bind_t<void, void (*)(bool (*)()), boost::_bi::list1<boost::_bi::value<bool (*)()> > >::operator()() /opt/scylladb/include/boost/bind/bind.hpp:1294
    #9 0x9f009ed in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<void, void (*)(bool (*)()), boost::_bi::list1<boost::_bi::value<bool (*)()> > >, void>::invoke(boost::detail::function::function_buffer&) /opt/scylladb/include/boost/function/function_template.hpp:159
    #10 0x36b2e6d in boost::function0<void>::operator()() const /opt/scylladb/include/boost/function/function_template.hpp:770
    #11 0x9e49fa3 in boost::detail::forward::operator()() /opt/scylladb/include/boost/test/impl/execution_monitor.ipp:1300
    #12 0x9f04d2e in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) /opt/scylladb/include/boost/function/function_template.hpp:138
    #13 0x9eb11c1 in boost::function0<int>::operator()() const /opt/scylladb/include/boost/function/function_template.hpp:771
    #14 0x9e7cb37 in int boost::detail::do_invoke<boost::shared_ptr<boost::detail::translator_holder_base>, boost::function<int ()> >(boost::shared_ptr<boost::detail::translator_holder_base> const&, boost::function<int ()> const&) /opt/scylladb/include/boost/test/impl/execution_monitor.ipp:281
    #15 0x9da26d3 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) /opt/scylladb/include/boost/test/impl/execution_monitor.ipp:864
    #16 0x9da2bfa in boost::execution_monitor::execute(boost::function<int ()> const&) /opt/scylladb/include/boost/test/impl/execution_monitor.ipp:1203
    #17 0x9da5088 in boost::execution_monitor::vexecute(boost::function<void ()> const&) /opt/scylladb/include/boost/test/impl/execution_monitor.ipp:1309
    #18 0x9d977c5 in boost::unit_test::framework::init(bool (*)(), int, char**) /opt/scylladb/include/boost/test/impl/framework.ipp:1065
    #19 0x9dce178 in boost::unit_test::unit_test_main(bool (*)(), int, char**) /opt/scylladb/include/boost/test/impl/unit_test_main.ipp:189
    #20 0x9df3b2b in main seastar/tests/test-utils.cc:84
    #21 0x7f1146e5dc04 in __libc_start_main (/lib64/libc.so.6+0x21c04)

==13473==ABORTING
```

If we use the gdb we'll see that the crash comes due to exactly the same reasons as in #3345 

```
$ /opt/scylladb/bin/gdb --args build/debug/tests/types_test_g -- -c1 -m4G --collectd 0
GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/debug/tests/types_test_g...../../gdb/cp-support.c:1595: demangler-warning: unable to demangle '_ZSt7forwardIRZN7seastar7reactor14run_exit_tasksEvEUlRT_E_EOS2_RNSt16remove_referenceIS2_E4typeE' (demangler failed with signal 11)
Unable to dump core, use `ulimit -c unlimited' before executing GDB next time.
../../gdb/cp-support.c:1608: demangler-warning: unable to demangle '_ZSt7forwardIRZN7seastar7reactor14run_exit_tasksEvEUlRT_E_EOS2_RNSt16remove_referenceIS2_E4typeE' (demangler failed with signal 11)
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) n

This is a bug, please report it.  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.

done.
(gdb) handle SIG33 pass noprint
Signal        Stop      Print   Pass to program Description
SIG33         No        No      Yes             Real-time event 33
(gdb) handle SIG34 pass noprint
Signal        Stop      Print   Pass to program Description
SIG34         No        No      Yes             Real-time event 34
(gdb) handle SIGUSR1 pass noprint
Signal        Stop      Print   Pass to program Description
SIGUSR1       No        No      Yes             User defined signal 1
(gdb) break reactor.cc: 475 <--- second line in the ~reactor()
Breakpoint 1 at 0x4221ae: file core/reactor.cc, line 475.
(gdb) r
Starting program: /home/vladz/scylla/build/debug/tests/types_test_g -- -c1 -m4G --collectd 0
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7f20737ff700 (LWP 13607)]
Running 48 test cases...
WARNING: debug mode. Not for benchmarking or production
WARN  2018-04-12 15:57:25,476 seastar - Seastar compiled with default allocator, heap profiler not supported
[New Thread 0x7f20734de700 (LWP 13608)]
[New Thread 0x7f20729ff700 (LWP 13609)]
WARN  2018-04-12 15:57:25,485 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
WARN  2018-04-12 15:57:26,254 [shard 0] org.apache.cassandra.db.marshal.TimestampType - Changing from DateType to TimestampType is allowed, but be wary that they sort differently for pre-unix-epoch timestamps (negative timestamp values) and thus this change will corrupt your data if you have such negative timestamp. So unless you know that you don't have *any* pre-unix-epoch timestamp you should change back to DateType
WARN  2018-04-12 15:57:26,254 [shard 0] org.apache.cassandra.db.marshal.DateType - Changing from TimestampType to DateType is allowed, but be wary that they sort differently for pre-unix-epoch timestamps (negative timestamp values) and thus this change will corrupt your data if you have such negative timestamp. There is no reason to switch from DateType to TimestampType except if you were using DateType in the first place and switched to TimestampType by mistake.

*** No errors detected
[Thread 0x7f20737ff700 (LWP 13607) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f20734de700 (LWP 13608)]
0x00000000004240fe in seastar::reactor::task_quota_timer_thread_fn (this=0x629000000200) at core/reactor.cc:580
580             _local_need_preempt = true;
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 cryptopp-5.6.2-10.el7.x86_64 elfutils-libelf-0.168-8.el7.x86_64 elfutils-libs-0.168-8.el7.x86_64 gmp-6.0.0-15.el7.x86_64 gnutls-3.3.26-9.el7.x86_64 gnutls-c++-3.3.26-9.el7.x86_64 hwloc-libs-1.11.2-2.el7.x86_64 jsoncpp-0.10.5-2.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-9.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libffi-3.0.13-18.el7.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libpciaccess-0.13.4-3.1.el7_4.x86_64 libselinux-2.5-11.el7.x86_64 libtasn1-4.10-1.el7.x86_64 libtool-ltdl-2.4.2-22.el7_3.x86_64 libunwind-1.2-2.el7.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 lz4-1.7.3-1.el7.x86_64 nettle-2.7.1-8.el7.x86_64 nss-softokn-freebl-3.28.3-8.el7_4.x86_64 numactl-libs-2.0.9-6.el7_2.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 p11-kit-0.23.5-3.el7.x86_64 pcre-8.32-17.el7.x86_64 protobuf-2.5.0-8.el7.x86_64 scylla-libasan73-7.3.1-1.el7.centos.x86_64 scylla-libgcc73-7.3.1-1.el7.centos.x86_64 scylla-libstdc++73-7.3.1-1.el7.centos.x86_64 scylla-libubsan73-7.3.1-1.el7.centos.x86_64 snappy-1.1.0-3.el7.x86_64 systemd-libs-219-42.el7_4.10.x86_64 thrift-0.9.1-15.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 yaml-cpp-0.5.1-1.el7.2.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) info thread
  Id   Target Id         Frame
  4    Thread 0x7f20729ff700 (LWP 13609) "syscall-0" 0x00007f207ee5570d in read () from /lib64/libpthread.so.0
* 3    Thread 0x7f20734de700 (LWP 13608) "timer-0" 0x00000000004240fe in seastar::reactor::task_quota_timer_thread_fn (this=0x629000000200) at core/reactor.cc:580
  1    Thread 0x7f20846d9b40 (LWP 13603) "types_test_g" 0x00007f2083652b61 in ?? () from /opt/scylladb/lib64/libasan.so.4
(gdb) q

```

**Comment by vladzcloudius** [comment]
@slivne I tested the same test on a Fedora 26 with the in-box gcc 7.3.1 and boost 1.63 (with and without static boost) and the test passed. This means that this failure clearly has something to do with our toolchain.
