### ISSUE TITLE
storage_proxy - Exception when communicating with 10.240.0.128: sstable inactive read queue overloaded

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3487]
*Installation details*
Scylla version (or git commit hash):
- src version: 2.1.3-0.20180501.8e33e80ad
- dest version: 2.2.rc1-0.20180516.eb646c61e

Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Test job link: [job/scylla-staging-rolling-upgrade-gce/37
](http://jenkins.cloudius-systems.com:8080/job/scylla-staging-rolling-upgrade-gce/base_version=2.1,label=gce3-qavpc/37/artifact/latest/)

1. create and setup a cluster, which has 4 db nodes
2. start a write workload: `cassandra-stress write no-warmup cl=QUORUM n=10000000 -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=100 -pop seq=1..10000000 -log interval=5)`
3. upgrade the first node in random list(`rolling-upgrade-ak-2-2-db-node-ae9b95ed-0-4`, 10.240.0.128) during the write workload
4. wait the write workload finishes 
5. start the read workload: `cassandra-stress read no-warmup cl=QUORUM duration=10m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=100 -pop seq=1..10000000 -log interval=5`
6. upgrade the second node in random list(`rolling-upgrade-ak-2-2-db-node-ae9b95ed-0-3`, 10.240.0.127) during the read workload
7. wait the read workload finishes

The exception was raised during step 5  (before step 6), when the second node was upgraded, the c-s read workload failed.

```
2018-06-04 06:28:55,058 upgrade_test     L0237 INFO | Sleeping for 60s to let cassandra-stress start before the upgrade...
2018-06-04 06:28:59,890 remote           L0197 DEBUG| [35.237.77.104] [stdout] total,        721259,   29335,   29335,   29335,     3.4,     2.4,    10.0,    15.6,    27.3,    50.8,   30.6,  0.11929,      0,      0,       0,       0,       0,       0
2018-06-04 06:29:04,925 remote           L0197 DEBUG| [35.237.77.104] [stdout] total,        877876,   31078,   31078,   31078,     3.2,     2.4,     8.6,    13.1,    19.5,    30.7,   35.6,  0.10586,      0,      0,       0,       0,       0,       0
2018-06-04 06:29:09,965 remote           L0197 DEBUG| [35.237.77.104] [stdout] total,       1032862,   30783,   30783,   30783,     3.2,     2.3,     9.3,    15.0,    21.9,    33.8,   40.7,  0.09421,      0,      0,       0,       0,       0,       0
2018-06-04 06:29:15,024 remote           L0197 DEBUG| [35.237.77.104] [stdout] total,       1187505,   30582,   30582,   30582,     3.3,     2.5,     8.7,    13.5,    21.4,    30.4,   45.7,  0.08452,      0,      0,       0,       0,       0,       0
2018-06-04 06:29:20,068 remote           L0197 DEBUG| [35.237.77.104] [stdout] total,       1342322,   30653,   30653,   30653,     3.2,     2.5,     8.4,    12.7,    19.9,    32.7,   50.8,  0.07660,      0,      0,       0,       0,       0,       0
2018-06-04 06:29:25,118 remote           L0197 DEBUG| [35.237.77.104] [stdout] total,       1497733,   30806,   30806,   30806,     3.2,     2.3,     8.9,    13.9,    21.5,    30.0,   55.8,  0.07005,      0,      0,       0,       0,       0,       0
2018-06-04 06:29:29,081 remote           L0197 DEBUG| [35.231.45.221] [stdout] Jun 04 06:29:29 err    |  [shard 5] storage_proxy - Exception when communicating with 10.240.0.128: sstable inactive read queue overloaded
2018-06-04 06:29:29,081 remote           L0197 DEBUG| [35.231.100.130] [stdout] Jun 04 06:29:29 err    |  [shard 2] storage_proxy - Exception when communicating with 10.240.0.128: sstable inactive read queue overloaded
2018-06-04 06:29:29,083 remote           L0197 DEBUG| [35.227.16.193] [stdout] Jun 04 06:29:29 err    |  [shard 0] storage_proxy - Exception when communicating with 10.240.0.128: sstable inactive read queue overloaded
2018-06-04 06:29:29,087 remote           L0197 DEBUG| [35.231.177.83] [stdout] Jun 04 06:29:29 err    |  [shard 7] storage_proxy - Exception when communicating with 10.240.0.128: sstable inactive read queue overloaded
```

```
...
2018-06-04 06:30:30,462 remote           L0197 DEBUG| [35.237.77.104] [stdout] com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
2018-06-04 06:30:30,463 remote           L0197 DEBUG| [35.237.77.104] [stdout] java.io.IOException: Operation x10 on key(s) [364e3732303531383431]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
2018-06-04 06:30:30,463 remote           L0197 DEBUG| [35.237.77.104] [stdout]
2018-06-04 06:30:30,463 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.Operation.error(Operation.java:135)
2018-06-04 06:30:30,463 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
2018-06-04 06:30:30,463 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:98)
2018-06-04 06:30:30,464 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
2018-06-04 06:30:30,464 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:261)
2018-06-04 06:30:30,464 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
...
2018-06-04 06:30:30,531 remote           L0197 DEBUG| [35.237.77.104] [stdout] com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
2018-06-04 06:30:30,532 remote           L0197 DEBUG| [35.237.77.104] [stdout] java.io.IOException: Operation x10 on key(s) [3835384b353936363830]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
2018-06-04 06:30:30,532 remote           L0197 DEBUG| [35.237.77.104] [stdout]
2018-06-04 06:30:30,532 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.Operation.error(Operation.java:135)
2018-06-04 06:30:30,532 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
2018-06-04 06:30:30,532 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:98)
2018-06-04 06:30:30,533 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
2018-06-04 06:30:30,533 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:261)
2018-06-04 06:30:30,533 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)/F
...
2018-06-04 06:30:50,590 remote           L0197 DEBUG| [35.237.77.104] [stdout] java.io.IOException: Operation x10 on key(s) [36365037353133354f30]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (3 responses were required but only 2 replica responded)
2018-06-04 06:30:50,591 remote           L0197 DEBUG| [35.237.77.104] [stdout]
2018-06-04 06:30:50,591 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.Operation.error(Operation.java:135)
2018-06-04 06:30:50,591 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
2018-06-04 06:30:50,591 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:98)
2018-06-04 06:30:50,592 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
2018-06-04 06:30:50,592 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:261)
2018-06-04 06:30:50,592 remote           L0197 DEBUG| [35.237.77.104] [stdout]  at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
2018-06-04 06:30:53,280 remote           L0197 DEBUG| [35.231.100.130] [stdout] Jun 04 06:30:53 info   |  [shard 0] gossip - No gossip backlog; proceeding
2018-06-04 06:30:53,281 remote           L0197 DEBUG| [35.231.100.130] [stdout] Jun 04 06:30:53 info   |  [shard 0] storage_service - Starting listening for CQL clients on 10.240.0.126:9042 (unencrypted)
2018-06-04 06:30:53,283 remote           L0197 DEBUG| [35.231.100.130] [stdout] Jun 04 06:30:53 info   |  [shard 0] storage_service - Thrift server listening on 10.240.0.126:9160 ...
2018-06-04 06:31:41,723 wait             L0026 DEBUG| Node rolling-upgrade-ak-2-2-db-node-ae9b95ed-0-2 [35.231.100.130 | 10.240.0.126] (seed: False): Waiting for DB services to be up (60.113853 secs)
2018-06-04 06:31:41,845 remote           L0901 DEBUG| Remote [scylla-test@35.231.100.130]: Running 'scylla --version'
2018-06-04 06:31:41,845 remote           L0097 INFO | [35.231.100.130] Running '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterHoiAPY/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVnLdSu -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 35.231.100.130 "scylla --version"'
2018-06-04 06:31:41,894 remote           L0197 DEBUG| [35.231.100.130] [stdout] 2.2.rc1-0.20180516.eb646c61e
2018-06-04 06:31:41,895 remote           L0197 DEBUG| [35.231.100.130] [stderr] Shared connection to 35.231.100.130 closed.
2018-06-04 06:31:41,896 upgrade_test     L0244 INFO | Upgrade Node rolling-upgrade-ak-2-2-db-node-ae9b95ed-0-2 ended
2018-06-04 06:31:41,897 remote           L0901 DEBUG| Remote [scylla-test@35.231.100.130]: Running 'nodetool status'
2018-06-04 06:31:41,897 remote           L0097 INFO | [35.231.100.130] Running '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterHoiAPY/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVnLdSu -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 35.231.100.130 "nodetool status"'
2018-06-04 06:31:43,288 remote           L0197 DEBUG| [35.231.100.130] [stdout] Datacenter: datacenter1
2018-06-04 06:31:43,288 remote           L0197 DEBUG| [35.231.100.130] [stdout] =======================
2018-06-04 06:31:43,289 remote           L0197 DEBUG| [35.231.100.130] [stdout] Status=Up/Down
2018-06-04 06:31:43,289 remote           L0197 DEBUG| [35.231.100.130] [stdout] |/ State=Normal/Leaving/Joining/Moving
2018-06-04 06:31:43,289 remote           L0197 DEBUG| [35.231.100.130] [stdout] --  Address       Load       Tokens       Owns    Host ID                               Rack
2018-06-04 06:31:43,298 remote           L0197 DEBUG| [35.231.100.130] [stdout] UN  10.240.0.128  517.18 MB  256          ?       a7f1c577-17f8-4ae0-851c-76131a7f2fd3  rack1
2018-06-04 06:31:43,305 remote           L0197 DEBUG| [35.231.100.130] [stdout] UN  10.240.0.122  1.76 GB    256          ?       bdc94dce-75d3-4bfb-992a-bca53aa879fb  rack1
2018-06-04 06:31:43,313 remote           L0197 DEBUG| [35.231.100.130] [stdout] UN  10.240.0.126  2.16 GB    256          ?       4ccd36ee-eacf-4aff-869a-af3495b3c5d9  rack1
2018-06-04 06:31:43,321 remote           L0197 DEBUG| [35.231.100.130] [stdout] UN  10.240.0.127  1.76 GB    256          ?       02da4f66-c9c1-497f-89bf-a39959aa6a37  rack1
2018-06-04 06:31:43,321 remote           L0197 DEBUG| [35.231.100.130] [stdout] 
2018-06-04 06:31:43,321 remote           L0197 DEBUG| [35.231.100.130] [stdout] Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
2018-06-04 06:31:43,339 remote           L0197 DEBUG| [35.231.100.130] [stderr] Shared connection to 35.231.100.130 closed.
2018-06-04 06:31:43,340 cluster          L2176 DEBUG| GCE Cluster rolling-upgrade-ak-2-2-loader-set-da3f6bc4 | Image: centos-7 | Root Disk: pd-standard 50 GB | Type: n1-standard-2: Wait for 1 stress threads to verify
2018-06-04 06:38:29,187 remote           L0197 DEBUG| [35.237.77.104] [stdout] FAILURE
<c-s read workload failed>
```

![image](https://user-images.githubusercontent.com/309708/40904582-c3e5a97a-680d-11e8-8737-26dfb4f59569.png)

**Comment by slivne** [comment]
![grafana-snapshot-0](https://user-images.githubusercontent.com/3465480/40907479-a90de8ea-67ec-11e8-8fe3-47de74c8acd1.png)

@tgrabiec - can you please look at this ...

**Comment by tgrabiec** [comment]
Is this a regression, that is, did you perform the same test before without problems?

**Comment by amoskong** [comment]
I didn't perform the same test (fixed scenario & workload) before.
I saw the error was added by Botond on March 5 in
commit 1259031af3db2fbd2103fe6be84b4fc779f4405a.

**Comment by tgrabiec** [comment]
@amoskong Dropping readers when the sstable read queue is overloaded is something we had for a while, since bea7d7ee94b2e0014f675002b546c46c0680c1f3 (scylla-1.3).

The situation here is that the node which was upgraded and restarted has a cold cache and unlike other nodes is serving reads from sstables. It seems that the sstables cannot sustain the concurrency within the timeout.

There are just a few coordinator-side timeouts per second, but lots of background reads (10k). My explanation is that high replica-side concurrency is generated by probabilistic background read-repair, which probabilistically adds more requests to the slow node. Since we have high foreground read rate, we end up with a substantial amount of background concurrency, which overflows the slow node.

What's making things worse is that the sstable reads accumulate due to https://github.com/scylladb/scylla/issues/2927, which makes timeouts even more likely, eventually inevitable, and finally the sstable read queue is overflown affecting all foreground reads which go to that node.

I think HWLB makes this effect more pronounced because the slow replica is rarely in the foreground set, so we don't get as much backpressure from the slow node, until the coordinator-side memory-based limit would kick in, but that woudl already allow for too large concurrency.

**Comment by tgrabiec** [comment]
For one, perhaps background reads should be given separate scheduling priority on replica side, so that they don't affect foreground reads as much.

**Comment by gleb-cloudius** [comment]
On Mon, Jun 04, 2018 at 04:06:50AM -0700, Tomasz Grabiec wrote:
> For one, perhaps background reads should be given separate scheduling priority on replica side, so that they don't affect foreground reads as much.
> 
All reads are started as foreground and become background when enough
replies for CL are received.

--
			Gleb.

**Comment by slivne** [comment]
@amoskong - can you please disable ```cache_hit_rate_read_balancing``` and lets try this as well.

One option that may exist is that there is a difference in computation between releases and that is forcing more traffic to the restarted node than what would happen if all nodes were in the same version.

(We can also check that by running a cluster of 2.2 and restarting one node under the same workload).

**Comment by slivne** [comment]
another option is to look at the metrics - @gleb-cloudius do we have metrics for the stats that are used by cache_hit_rate_read_balancing we can check the values of the old nodes vs the upgraded node and see if we are forcing to much traffic toward that node

**Comment by gleb-cloudius** [comment]
On Mon, Jun 04, 2018 at 03:08:45PM +0000, Shlomi Livne wrote:
> another option is to look at the metrics - @gleb-cloudius do we have metrics for the stats that are used by cache_hit_rate_read_balancing we can check the values of the old nodes vs the upgraded node and see if we are forcing to much traffic toward that node
> 
cache_hit_rate_read_balancing has its own metric but it is per CF and
hence is disabled by default.

--
			Gleb.

**Comment by tgrabiec** [comment]
2018-06-04 17:07 GMT+02:00 Shlomi Livne <notifications@github.com>:

> @amoskong <https://github.com/amoskong> - can you please disable
> cache_hit_rate_read_balancing and lets try this as well.
>
> One option that may exist is that there is a difference in computation
> between releases and that is forcing more traffic to the restarted node
> than what would happen if all nodes were in the same version.
>

I don't think that explains the overload, the client concurrency is only
100, whereas the node has tens of thousands requests sitting in the queue.
Even if there was such a bias, its efect would be limited to the client's
concurrency (100), and wouldn't explain overload.

**Comment by tgrabiec** [comment]
We can also disable probabilistic read repair to confirm this.

**Comment by slivne** [comment]
@gleb-cloudius
 - so how do we disable heat-weighted-load-balancing ?

@tgrabiec 
- do you meand alter the table and set dclocal_read_repair_chance = 0.0 , read_repair_chance =0.0 or something else

**Comment by tgrabiec** [comment]
@slivne To be sure, both. Probably zeroing just `dclocal_read_repair_chance` is enough due to defaults.

**Comment by slivne** [comment]
so @amoskong lets disable everything heat-eaighted-load-balancing and also read repair chance and lets see what we get.

If it turns out that the upgrade works with these disabled we will need to check which of these causes the issue. but lets get the data of what happens when both are disabled.

**Comment by amoskong** [comment]
When I disabled both `heat-weighted-load-balancing` and `read_repair_chance`, the exception and c-s fail disappeared.

----

Then I tried to test with latest unstable 2.1.x (without disable `heat-weighted-load-balancing` and `read_repair_chance`), the whole upgrade & rollback test can pass.

Test job link: [job/scylla-staging-rolling-upgrade-gce/base_version=2.1,label=gce3-qavpc/43/](http://jenkins.cloudius-systems.com:8080/job/scylla-staging-rolling-upgrade-gce/base_version=2.1,label=gce3-qavpc/43/)

- 2.1.3-0.20180528.f6c4d558e  (unstable repo, not release)
- 2.2.rc2-0.20180531.c3187093a

**Comment by gleb-cloudius** [comment]
Now run with read_repair_chance not 0 since without it all reads a
synchronous.

--
			Gleb.

**Comment by amoskong** [comment]
src version: 2.1.3-0.20180501.8e33e80ad  (released 2.1.3)
dest version: 2.2.rc1-0.20180516.eb646c61e

Note: only disabled heat-weighted-load-balancing, read_repair_chance isn't set to 0

Result: didn't see `sstable inactive read queue overloaded`, but c-s keep raising ReadTimeoutException, it still raised the error [1] when the node upgrade finished.
The read throughput is very slow (it might be caused by #3437 , second disk isn't mounted rightly), but c-s finished successfully.

error [1] in first read workload (`cl=QUORUM` duration=10m -schema 'replication(factor=3)'):
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (3 responses were required but only 2 replica responded)

error [2] in second read workload (`cl=ALL` n=10000000 -schema 'replication(factor=3)'):
07:56:16 [35.196.27.64] [stdout] com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency ALL (3 responses were required but only 2 replica responded)

![fireshot capture 16 - grafana - scylla per server metrics ne_ - http___35 196 178 31_3000_dashboar](https://user-images.githubusercontent.com/309708/41009048-37e274bc-6961-11e8-8386-1db0ff2db5f3.png)

**Comment by tgrabiec** [comment]
@amoskong @slivne Where can I get the prometheus database for this run from?

**Comment by tgrabiec** [comment]
@amoskong I cannot analyze this without prometheus data. Please re-run with metrics attached. If possible, use scrape period of 1 second.

**Comment by amoskong** [comment]
Test result with different configuration:

  | read_repair_chance | heat-weighted-load-balancing | STL (server-server) | avi workaround: raid0.devices_discard_performance issue | RESULT
-- | -- | -- | -- | -- | --
2.1.3-0.20180501.8e33e80ad (released 2.1.3) | set it to 0.0 | disable | disable | workaround | Good
  | unset | disable | disable | workaround | Fail (read workload: Data returned was not validated)
  | unset | disable | enable | workaround | Good
  | unset | enable | disable | don't workaround | Fail (read workload: Data returned was not validated)
  | set it to 0.0 | disable | disable | don't workaround | Good
  | unset | disable | disable | don't workaround | Fail (read workload: Data returned was not validated)
  |   |   |   |   |  
  |   |   |   |   |  
  | read_repair_chance | heat-weighted-load-balancing | STL (server-server) | avi workaround: raid0.devices_discard_performance issue | RESULT
2.1.3-0.20180528.f6c4d558e | unset | enable | enable | workaround isn't requested | Good

**Comment by amoskong** [comment]
I will rerun and provide you the prometheus data.

**Comment by roydahan** [comment]
Assuming the summary above is correct and the "running" line is the same test repeating the line above and it'll result in "Good", it seems like the issue is false alarm and it originally caused by the slow disk (boot disk) that scylla was using due to the raid0 issue.

So, the actual factor is "with" / "without" the workaround or IOW with slow disk or fast disk.

**Comment by amoskong** [comment]
Retest result with archived job result (final color result, prometheus data, conf(heat-wighted-load-balancing, read_repair_chance, slt) detail):

2.1.3-0.20180501.8e33e80ad (released 2.1.3) |   |   |   |  
-- | -- | -- | -- | --
read_repair_chance | heat-weighted-load-balancing | avi workaround: raid0.devices_discard_performance issue | RESULT |  
default | enable | workaround | Good | http://jenkins.cloudius-systems.com:8080/job/scylla-staging-rolling-upgrade-gce/label=gce3-qavpc/54/
default | disable | workaround | Good | http://jenkins.cloudius-systems.com:8080/job/scylla-staging-rolling-upgrade-gce/label=gce3-qavpc/57/
disable | disable | workaround | Good | http://jenkins.cloudius-systems.com:8080/job/scylla-staging-rolling-upgrade-gce/label=gce3-qavpc/58/
disable | enable | workaround | Running, but key part is good | http://jenkins.cloudius-systems.com:8080/job/scylla-staging-rolling-upgrade-gce/label=gce3-qavpc/59/

**Comment by tzach** [comment]
@amoskong can you reproduce with 2.1.4 to 2.2?
fixing #3437 should have solved this

**Comment by slivne** [comment]
@amoskong  / @roydahan ping

**Comment by amoskong** [comment]
I tested 2.1.3-0.20180528.f6c4d558e, it's good.

I just submitted a [job](http://jenkins.cloudius-systems.com:8080/job/scylla-staging-rolling-upgrade-gce/60/) for official release 2.1.4, will update you result soon.

**Comment by amoskong** [comment]
I can't reproduce this issue in upgrading from `2.1.4-0.20180614.6615c2a6a` to `2.2.rc2-0.20180621.c11bd3e1c`. So this issue had been fixed.

Test job:  [job/scylla-staging-rolling-upgrade-gce/60/](http://jenkins.cloudius-systems.com:8080/job/scylla-staging-rolling-upgrade-gce/60/)
Result: PASS
