### ISSUE TITLE
Apparent lsa binomial heap corruption

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#351]
```
#0  0x00000000006771c0 in siftup<boost::heap::binomial_heap<logalloc::segment*, boost::heap::compare<logalloc::segment_occupancy_descending_less_compare> > > (cmp=..., n=0x600004c38100, this=0x6000000cac30) at /usr/include/boost/heap/binomial_heap.hpp:761
#1  increase (handle=..., this=0x6000000cac30) at /usr/include/boost/heap/binomial_heap.hpp:473
#2  logalloc::region_impl::free (this=0x6000000cac10, obj=<optimized out>) at utils/logalloc.cc:808
#3  0x000000000067a002 in destroy<blob_storage> (obj=<optimized out>, this=<optimized out>) at ./utils/allocation_strategy.hh:88
#4  ~managed_bytes (this=<optimized out>, __in_chrg=<optimized out>) at ./utils/managed_bytes.hh:78
#5  ~atomic_cell_or_collection (this=<optimized out>, __in_chrg=<optimized out>) at ./atomic_cell.hh:248
#6  pop_back (this=<optimized out>, this=<optimized out>) at utils/managed_vector.hh:196
#7  clear (this=<optimized out>) at utils/managed_vector.hh:153
#8  clear_and_release (this=<optimized out>) at utils/managed_vector.hh:60
#9  ~managed_vector (this=<optimized out>, __in_chrg=<optimized out>) at utils/managed_vector.hh:110
#10 row::~row (this=this@entry=0x60003ed87fa0, __in_chrg=<optimized out>) at mutation_partition.cc:734
#11 0x000000000067a145 in ~deletable_row (this=0x60003ed87f80, __in_chrg=<optimized out>) at mutation_partition.hh:329
#12 ~rows_entry (this=0x60003ed87f50, __in_chrg=<optimized out>) at mutation_partition.hh:417
#13 destroy<rows_entry> (obj=0x60003ed87f50, this=0x6000000cac10) at ./utils/allocation_strategy.hh:87
#14 operator() (obj=0x60003ed87f50, __closure=<synthetic pointer>) at ./utils/allocation_strategy.hh:131
#15 operator() (p=<synthetic pointer>, this=<synthetic pointer>) at /usr/include/boost/intrusive/detail/utilities.hpp:287
#16 dispose_subtree<boost::intrusive::detail::node_disposer<current_deleter() [with T = rows_entry]::<lambda(rows_entry*)>, boost::intrusive::mhtraits<rows_entry, boost::intrusive::set_member_hook<>, &rows_entry::_link>, (boost::intrusive::algo_types)4u> > (disposer=..., x=0x60003ed87f50) at /usr/include/boost/intrusive/bstree_algorithms.hpp:1842
#17 clear_and_dispose<boost::intrusive::detail::node_disposer<current_deleter() [with T = rows_entry]::<lambda(rows_entry*)>, boost::intrusive::mhtraits<rows_entry, boost::intrusive::set_member_hook<>, &rows_entry::_link>, (boost::intrusive::algo_types)4u> > (disposer=..., header=<optimized out>) at /usr/include/boost/intrusive/bstree_algorithms.hpp:628
#18 clear_and_dispose<current_deleter() [with T = rows_entry]::<lambda(rows_entry*)> > (disposer=..., this=0x600033b3f778) at /usr/include/boost/intrusive/bstree.hpp:1353
#19 mutation_partition::~mutation_partition (this=0x600033b3f700, __in_chrg=<optimized out>) at mutation_partition.cc:27
#20 0x0000000000666f88 in cache_entry::~cache_entry (this=0x600033b3f6d8, __in_chrg=<optimized out>) at row_cache.hh:28
#21 0x00000000006640f5 in destroy<cache_entry> (obj=0x600033b3f6d8, this=0x6000000cac10) at ./utils/allocation_strategy.hh:87
#22 operator() (obj=0x600033b3f6d8, __closure=<synthetic pointer>) at ./utils/allocation_strategy.hh:131
#23 pop_back_and_dispose<current_deleter() [with T = cache_entry]::<lambda(cache_entry*)> > (disposer=..., this=0x7f95d04018d0) at /usr/include/boost/intrusive/list.hpp:312
#24 operator() (__closure=<optimized out>) at row_cache.cc:34
#25 with_allocator<cache_tracker::cache_tracker()::<lambda()>::<lambda()> > (func=<optimized out>, alloc=...) at ./utils/allocation_strategy.hh:187
#26 operator() (__closure=<optimized out>) at row_cache.cc:38
#27 std::_Function_handler<memory::reclaiming_result(), cache_tracker::cache_tracker()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/4.9.2/functional:2025
#28 0x00000000006738c6 in operator() (this=0x6000000cac80) at /usr/include/c++/4.9.2/functional:2439
#29 evict_some (this=0x6000000cac10) at utils/logalloc.cc:911
#30 reclaim_from_evictable (target_segments_in_use=<optimized out>, r=...) at utils/logalloc.cc:1025
#31 logalloc::tracker::impl::reclaim (this=0x60000029b280, bytes=bytes@entry=10485760) at utils/logalloc.cc:1145
#32 0x0000000000673f37 in reclaim (bytes=10485760, this=<optimized out>) at utils/logalloc.cc:80
#33 operator() (__closure=<optimized out>) at utils/logalloc.cc:70
#34 std::_Function_handler<memory::reclaiming_result(), logalloc::tracker::tracker()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/4.9.2/functional:2025
#35 0x00000000004d2ca7 in operator() (this=<optimized out>) at /usr/include/c++/4.9.2/functional:2439
#36 do_reclaim (this=<optimized out>) at core/memory.hh:100
#37 memory::cpu_pages::run_reclaimers (this=this@entry=0x7f95d04008c0, scope=scope@entry=memory::reclaimer_scope::sync) at core/memory.cc:757
#38 0x00000000004d2d6d in memory::cpu_pages::find_and_unlink_span_reclaiming (this=this@entry=0x7f95d04008c0, n_pages=n_pages@entry=64) at core/memory.cc:438
#39 0x00000000004d3a63 in memory::cpu_pages::allocate_large_and_trim<memory::cpu_pages::allocate_large(unsigned int)::<lambda(unsigned int, unsigned int)> >(unsigned int, memory::cpu_pages::<lambda(unsigned int, unsigned int)>) (this=0x7f95d04008c0, this@entry=<error reading variable: Asked for position 0 of stack, stack only has 0 elements on it.>, n_pages=n_pages@entry=64, trimmer=..., trimmer@entry=...) at core/memory.cc:447
#40 0x00000000004d408a in allocate_large (n_pages=<optimized out>, this=<optimized out>) at core/memory.cc:484
#41 memory::allocate_large (size=<optimized out>) at core/memory.cc:917
#42 0x00000000004d4265 in operator new (size=size@entry=262144) at core/memory.cc:1222
#43 0x00000000006700de in logalloc::segment_pool::allocate_or_fallback_to_reserve (this=this@entry=0x7f95d0401928) at utils/logalloc.cc:281
#44 0x0000000000670149 in logalloc::segment_pool::new_segment (this=this@entry=0x7f95d0401928) at utils/logalloc.cc:301
#45 0x00000000006759dc in new_segment (this=<optimized out>) at utils/logalloc.cc:667
#46 close_and_open (this=0x6000000cc0b0) at utils/logalloc.cc:686
#47 logalloc::region_impl::alloc_small (this=0x6000000cc0b0, migrator=0x66ca60 <standard_migrator<partition_entry>(void*, void*, unsigned long)>, size=288, alignment=8) at utils/logalloc.cc:609
#48 0x0000000000675e35 in logalloc::region_impl::alloc (this=0x6000000cc0b0, migrator=<optimized out>, size=<optimized out>, alignment=<optimized out>) at utils/logalloc.cc:778
#49 0x000000000066b6eb in construct<partition_entry, dht::decorated_key, mutation_partition> (this=0x6000000cc0b0) at ./utils/allocation_strategy.hh:74
#50 memtable::find_or_create_partition (this=this@entry=0x600009e24880, key=...) at memtable.cc:49
#51 0x000000000066bff3 in operator() (__closure=<optimized out>) at memtable.cc:36
#52 with_allocator<memtable::find_or_create_partition_slow(partition_key_view)::<lambda()>::<lambda()> > (func=<optimized out>, alloc=...) at ./utils/allocation_strategy.hh:187
#53 operator() (__closure=<optimized out>) at memtable.cc:37
#54 with_allocator<memtable::find_or_create_partition_slow(partition_key_view)::<lambda()> > (func=<optimized out>, alloc=...) at ./utils/allocation_strategy.hh:187
#55 memtable::find_or_create_partition_slow (this=0x600009e24880, key=...) at memtable.cc:38
#56 0x000000000066c3a5 in operator() (__closure=<optimized out>) at memtable.cc:197
#57 with_allocator<memtable::apply(const frozen_mutation&, const db::replay_position&)::<lambda()> > (func=<optimized out>, alloc=...) at ./utils/allocation_strategy.hh:187
#58 memtable::apply (this=0x600009e24880, m=..., rp=...) at memtable.cc:199
#59 0x0000000000626543 in apply (rp=..., m=..., this=0x60000004b708) at database.hh:540
#60 database::apply_in_memory (this=this@entry=0x600000052390, m=..., rp=...) at database.cc:1328
#61 0x0000000000626e1d in database::do_apply (this=0x600000052390, m=...) at database.cc:1364
#62 0x0000000000627064 in operator() (__closure=__closure@entry=0x7fffeaf3d8c0) at database.cc:1401
#63 apply (args=<optimized out>, func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x188c53a, DIE 0x1b23eae>) at /home/avi/urchin/seastar/core/apply.hh:34
#64 apply<database::apply(const frozen_mutation&)::<lambda()> > (args=<optimized out>, func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x188c53a, DIE 0x1b23f1c>) at /home/avi/urchin/seastar/core/apply.hh:42
#65 futurize<future<> >::apply<database::apply(const frozen_mutation&)::<lambda()> >(<unknown type in /home/avi/urchin/build/release/scylla, CU 0x188c53a, DIE 0x1b23f5c>, <unknown type in /home/avi/urchin/build/release/scylla, CU 0x188c53a, DIE 0x1b23f6f>) (func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x188c53a, DIE 0x1b23f5c>, args=<optimized out>) at /home/avi/urchin/seastar/core/future.hh:1119
#66 0x000000000062735b in then<database::apply(const frozen_mutation&)::<lambda()>, future<> > (func=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x188c53a, DIE 0x1c7f3d1>, this=0x7fffeaf3d980) at /home/avi/urchin/seastar/core/future.hh:769
#67 database::apply (this=<optimized out>, m=...) at database.cc:1401
#68 0x000000000087224f in operator() (db=..., __closure=0x6000049d5048) at service/storage_proxy.cc:658
#69 operator() (__closure=0x6000049d5040) at /home/avi/urchin/seastar/core/sharded.hh:284
#70 apply<seastar::sharded<Service>::invoke_on(unsigned int, Func&&) [with Func = service::storage_proxy::mutate_locally(const frozen_mutation&)::<lambda(database&)>; Ret = future<>; Service = database]::<lambda()>&> (func=...) at /home/avi/urchin/seastar/core/future.hh:1129
#71 submit_to<seastar::sharded<Service>::invoke_on(unsigned int, Func&&) [with Func = service::storage_proxy::mutate_locally(const frozen_mutation&)::<lambda(database&)>; Ret = future<>; Service = database]::<lambda()> > (func=<optimized out>, t=<optimized out>) at /home/avi/urchin/seastar/core/reactor.hh:991
#72 invoke_on<service::storage_proxy::mutate_locally(const frozen_mutation&)::<lambda(database&)>, future<> > (func=<optimized out>, id=<optimized out>, this=0x7fffeaf3f2f0) at /home/avi/urchin/seastar/core/sharded.hh:285
#73 service::storage_proxy::mutate_locally (this=this@entry=0x60000004c880, m=...) at service/storage_proxy.cc:659
#74 0x0000000000889eea in operator() (dc_targets=..., __closure=0x7fffeaf3dbf0) at service/storage_proxy.cc:988
#75 operator() (state=..., __closure=<optimized out>) at /home/avi/urchin/seastar/core/future-util.hh:89
#76 do_with<parallel_for_each_state, parallel_for_each(Iterator, Iterator, Func&&) [with Iterator = boost::range_detail::join_iterator<__gnu_cxx::__normal_iterator<std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >*, std::vector<std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> > > >, std::__detail::_Node_iterator<std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >, false, true>, std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >, std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >&, boost::forward_traversal_tag>; Func = service::storage_proxy::send_to_live_endpoints(service::storage_proxy::response_id_type, sstring)::<lambda(std::unordered_map<basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >::value_type&)>]::<lambda(parallel_for_each_state&)> > (f=<optimized out>, rvalue=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x5b92777, DIE 0x5eb76ce>) at /home/avi/urchin/seastar/core/do_with.hh:55
#77 parallel_for_each<boost::range_detail::join_iterator<__gnu_cxx::__normal_iterator<std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >*, std::vector<std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> > > >, std::__detail::_Node_iterator<std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >, false, true>, std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >, std::pair<const basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >&, boost::forward_traversal_tag>, service::storage_proxy::send_to_live_endpoints(service::storage_proxy::response_id_type, sstring)::<lambda(std::unordered_map<basic_sstring<char, unsigned int, 15u>, std::vector<gms::inet_address> >::value_type&)> > (func=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x5b92777, DIE 0x5eb771a>, end=..., begin=...) at /home/avi/urchin/seastar/core/future-util.hh:110
#78 service::storage_proxy::send_to_live_endpoints (this=this@entry=0x60000004c880, response_id=response_id@entry=32996005, local_dc=...) at service/storage_proxy.cc:997
#79 0x0000000000894775 in operator() (m=..., __closure=0x7fffeaf3de50) at service/storage_proxy.cc:749
#80 operator() (state=..., __closure=<optimized out>) at /home/avi/urchin/seastar/core/future-util.hh:89
#81 do_with<parallel_for_each_state, parallel_for_each(Iterator, Iterator, Func&&) [with Iterator = __gnu_cxx::__normal_iterator<mutation*, std::vector<mutation> >; Func = service::storage_proxy::mutate(std::vector<mutation>, db::consistency_level)::<lambda(mutation&)>]::<lambda(parallel_for_each_state&)> > (f=<optimized out>, rvalue=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x5b92777, DIE 0x5eb7956>) at /home/avi/urchin/seastar/core/do_with.hh:55
#82 parallel_for_each<__gnu_cxx::__normal_iterator<mutation*, std::vector<mutation> >, service::storage_proxy::mutate(std::vector<mutation>, db::consistency_level)::<lambda(mutation&)> > (func=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x5b92777, DIE 0x6028202>, end=..., begin=...) at /home/avi/urchin/seastar/core/future-util.hh:110
#83 parallel_for_each<std::vector<mutation>&, service::storage_proxy::mutate(std::vector<mutation>, db::consistency_level)::<lambda(mutation&)> > (func=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x5b92777, DIE 0x5ead54e>, range=...) at /home/avi/urchin/seastar/core/future-util.hh:132
#84 service::storage_proxy::mutate (this=<optimized out>, mutations=..., cl=<optimized out>) at service/storage_proxy.cc:777
#85 0x0000000000897c15 in service::storage_proxy::mutate_with_triggers (this=0x60000004c880, mutations=std::vector of length 0, capacity 0, cl=cl@entry=db::consistency_level::ONE, should_mutate_atomically=should_mutate_atomically@entry=false) at service/storage_proxy.cc:793
#86 0x00000000007c8971 in operator()<std::vector<mutation> > (mutations=<error reading variable: access outside bounds of object referenced via synthetic pointer>, __closure=<optimized out>) at cql3/statements/modification_statement.cc:362
#87 apply (args=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x4542584, DIE 0x4700d4c>, func=<optimized out>) at /home/avi/urchin/seastar/core/apply.hh:34
#88 apply<cql3::statements::modification_statement::execute_without_condition(distributed<service::storage_proxy>&, service::query_state&, const cql3::query_options&)::<lambda(auto:34)>, std::vector<mutation, std::allocator<mutation> > > (args=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x4542584, DIE 0x46977bd>, func=<optimized out>) at /home/avi/urchin/seastar/core/apply.hh:42
#89 apply<cql3::statements::modification_statement::execute_without_condition(distributed<service::storage_proxy>&, service::query_state&, const cql3::query_options&)::<lambda(auto:34)>, std::vector<mutation, std::allocator<mutation> > > (args=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x4542584, DIE 0x4700d1a>, func=<optimized out>) at /home/avi/urchin/seastar/core/future.hh:1119
#90 then<cql3::statements::modification_statement::execute_without_condition(distributed<service::storage_proxy>&, service::query_state&, const cql3::query_options&)::<lambda(auto:34)>, future<> > (func=<optimized out>, this=0x7fffeaf3e070) at /home/avi/urchin/seastar/core/future.hh:769
#91 cql3::statements::modification_statement::execute_without_condition (this=this@entry=0x6000006b6a10, proxy=..., qs=..., options=...) at cql3/statements/modification_statement.cc:363
#92 0x00000000007c8dc4 in cql3::statements::modification_statement::execute (this=0x6000006b6a10, proxy=..., qs=..., options=...) at cql3/statements/modification_statement.cc:346
#93 0x00000000008d2747 in cql3::query_processor::process_statement (this=0x6000000c9390, statement=..., query_state=..., options=...) at cql3/query_processor.cc:113
#94 0x0000000000760083 in transport::cql_server::connection::process_execute (this=0x60000028f350, stream=<optimized out>, buf=...) at transport/server.cc:531
#95 0x0000000000760c57 in operator() (__closure=__closure@entry=0x7fffeaf3e480) at transport/server.cc:339
#96 apply (args=<optimized out>, func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34643ca>) at /home/avi/urchin/seastar/core/apply.hh:34
#97 apply<transport::cql_server::connection::process_request_one(temporary_buffer<char>, uint8_t, uint16_t)::<lambda()> > (args=<optimized out>, func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x3464438>) at /home/avi/urchin/seastar/core/apply.hh:42
#98 futurize<future<> >::apply<transport::cql_server::connection::process_request_one(temporary_buffer<char>, uint8_t, uint16_t)::<lambda()> >(<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x3464478>, <unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x346448b>) (func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x3464478>, args=<optimized out>) at /home/avi/urchin/seastar/core/future.hh:1119
#99 0x0000000000761017 in then<transport::cql_server::connection::process_request_one(temporary_buffer<char>, uint8_t, uint16_t)::<lambda()>, future<> > (func=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x346968f>, this=0x7fffeaf3e560) at /home/avi/urchin/seastar/core/future.hh:769
#100 transport::cql_server::connection::process_request_one (this=this@entry=0x60000028f350, buf=..., op=<optimized out>, stream=<optimized out>) at transport/server.cc:366
#101 0x00000000007619a9 in operator() (__closure=0x7fffeaf3e700) at transport/server.cc:435
#102 with_gate<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>::<lambda()> > (func=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e3a0e>, g=...) at /home/avi/urchin/seastar/core/gate.hh:100
#103 operator() (buf=<error reading variable: access outside bounds of object referenced via synthetic pointer>, __closure=0x7fffeaf3e6c0) at transport/server.cc:438
#104 apply (args=args@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e39df>, func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e39cd>) at /home/avi/urchin/seastar/core/apply.hh:34
#105 apply<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>, temporary_buffer<char> > (args=args@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x346468d>, func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x3464679>) at /home/avi/urchin/seastar/core/apply.hh:42
#106 futurize<future<> >::apply<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>, temporary_buffer<char> >(<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e3e9a>, <unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e61cd>) (func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e3e9a>, args=args@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e61cd>) at /home/avi/urchin/seastar/core/future.hh:1119
#107 0x00000000007627bc in then<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>, future<> > (func=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e6322>, this=0x7fffeaf3e7f0) at /home/avi/urchin/seastar/core/future.hh:769
#108 operator() (v=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e61d2>, __closure=0x7fffeaf3e890) at transport/server.cc:441
#109 futurize<future<> >::apply<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>, future<std::experimental::optional<transport::cql_binary_frame_v3> > >(<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e65b5>) (func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34e65b5>) at /home/avi/urchin/seastar/core/future.hh:1129
#110 0x0000000000764ac9 in then_wrapped<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>, future<> > (func=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34eeccf>, this=0x7fffeaf3e8c0) at /home/avi/urchin/seastar/core/future.hh:810
#111 transport::cql_server::connection::process_request (this=<optimized out>) at transport/server.cc:442
#112 0x0000000000764d52 in operator() (__closure=0x7fffeaf3e9c0) at transport/server.cc:389
#113 seastar::with_gate<transport::cql_server::connection::process()::<lambda()>::<lambda()> >(seastar::gate &, <unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34f03c6>) (g=..., func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34f03c6>) at /home/avi/urchin/seastar/core/gate.hh:100
#114 0x00000000007651c5 in operator() (__closure=0x600033e45650) at transport/server.cc:390
#115 do_until_continued<transport::cql_server::connection::process()::<lambda()>, transport::cql_server::connection::process()::<lambda()>&>(transport::cql_server::connection::<lambda()> &, <unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34f1546>, promise<>) (stop_cond=..., action=action@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34f1546>, p=...) at /home/avi/urchin/seastar/core/future-util.hh:145
#116 0x0000000000765b68 in operator() (fut=..., __closure=0x600033e45650) at /home/avi/urchin/seastar/core/future-util.hh:151
#117 do_void_futurize_apply<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = transport::cql_server::connection::process()::<lambda()>; StopCondition = transport::cql_server::connection::process()::<lambda()>&]::<lambda(std::result_of_t<transport::cql_server::connection::process()::<lambda()>()>)>, future<> >(<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34f319d>) (func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34f319d>) at /home/avi/urchin/seastar/core/future.hh:1064
#118 0x0000000000765d16 in apply<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = transport::cql_server::connection::process()::<lambda()>; StopCondition = transport::cql_server::connection::process()::<lambda()>&]::<lambda(std::result_of_t<transport::cql_server::connection::process()::<lambda()>()>)>, future<> > (func=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x3464f78>) at /home/avi/urchin/seastar/core/future.hh:1112
#119 operator()<future_state<> > (state=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x3281365, DIE 0x34f3663>, __closure=0x600033e45630) at /home/avi/urchin/seastar/core/future.hh:816
#120 continuation<future<T>::then_wrapped(Func&&) [with Func = do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = transport::cql_server::connection::process()::<lambda()>; StopCondition = transport::cql_server::connection::process()::<lambda()>&]::<lambda(std::result_of_t<transport::cql_server::connection::process()::<lambda()>()>)>; Result = future<>; T = {}]::<lambda(auto:2&&)> >::run(void) (this=0x600033e45620) at /home/avi/urchin/seastar/core/future.hh:359
#121 0x000000000046813f in reactor::run_tasks (this=this@entry=0x6000001de000, tasks=...) at core/reactor.cc:1112
#122 0x000000000048f153 in reactor::run (this=0x6000001de000) at core/reactor.cc:1229
#123 0x00000000004e193f in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffeaf3f3b0, ac=ac@entry=6, av=av@entry=0x7fffeaf3f5f8, func=func@entry=<unknown type in /home/avi/urchin/build/release/scylla, CU 0x515a9a, DIE 0x5be16a>) at core/app-template.cc:122
#124 0x000000000041d382 in main (ac=6, av=0x7fffeaf3f5f8) at main.cc:279
```

```
(gdb) fr
#0  0x00000000006771c0 in siftup<boost::heap::binomial_heap<logalloc::segment*, boost::heap::compare<logalloc::segment_occupancy_descending_less_compare> > > (cmp=..., n=0x600004c38100, this=0x6000000cac30) at /usr/include/boost/heap/binomial_heap.hpp:761
761	        while (n->parent) {
(gdb) list
756	    };
757	
758	    template <typename Compare>
759	    void siftup(node_pointer n, Compare const & cmp)
760	    {
761	        while (n->parent) {
762	            node_pointer parent = n->parent;
763	            node_pointer grand_parent = parent->parent;
764	            if (cmp(n->value, parent->value))
765	                return;
```

```
(gdb) p *n
$21 = {
  <boost::heap::detail::heap_node<logalloc::segment*, true>> = {
    <boost::heap::detail::heap_node_base<false>> = {
      <boost::intrusive::list_base_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)1>, void, void>> = {
        <boost::intrusive::generic_hook<boost::intrusive::get_list_node_algo<void*>, boost::intrusive::default_tag, (boost::intrusive::link_mode_type)1, (boost::intrusive::base_hook_type)1>> = {
          <boost::intrusive::node_holder<boost::intrusive::list_node<void*>, boost::intrusive::default_tag, 1u>> = {
            <boost::intrusive::list_node<void*>> = {
              next_ = 0xf62650 <_ZTV12continuationIZN6futureIIEE12then_wrappedIZNS1_16handle_exceptionIZZZN9transport10cql_server10connection15process_requestEvENKUlOS0_IINSt12experimental8optionalINS4_19cql_binary_frame_v3EEEEEE_clESC_ENKUl16temporary_bufferIcEE_clESF_EUlNSt15__exception_ptr13exception_ptrEE0_EES1_OT_EUlOT_E_S1_EET0_SL_EUlSN_E_IEE+16>, 
              prev_ = 0x1
            }, <No data fields>}, 
          <boost::intrusive::hook_tags_definer<boost::intrusive::generic_hook<boost::intrusive::get_list_node_algo<void*>, boost::intrusive::default_tag, (boost::intrusive::link_mode_type)1, (boost::intrusive::base_hook_type)1>, 1u>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, 
    members of boost::heap::detail::heap_node<logalloc::segment*, true>: 
    value = 0x0, 
    children = {
      <boost::intrusive::list_impl<boost::intrusive::bhtraits<boost::heap::detail::heap_node_base<false>, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1, boost::intrusive::default_tag, 1u>, unsigned long, true>> = {
        <boost::intrusive::detail::clear_on_destructor_base<boost::intrusive::list_impl<boost::intrusive::bhtraits<boost::heap::detail::heap_node_base<false>, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1, boost::intrusive::default_tag, 1u>, unsigned long, true>, true>> = {<No data fields>}, 
        members of boost::intrusive::list_impl<boost::intrusive::bhtraits<boost::heap::detail::heap_node_base<false>, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1, boost::intrusive::default_tag, 1u>, unsigned long, true>: 
        static external_value_traits = <optimized out>, 
        static constant_time_size = true, 
        static stateful_value_traits = <optimized out>, 
        static safemode_or_autounlink = <optimized out>, 
        data_ = {
          <boost::intrusive::bhtraits<boost::heap::detail::heap_node_base<false>, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1, boost::intrusive::default_tag, 1u>> = {
            <boost::intrusive::bhtraits_base<boost::heap::detail::heap_node_base<false>, boost::intrusive::list_node<void*>*, boost::intrusive::default_tag, 1u>> = {<No data fields>}, 
            members of boost::intrusive::bhtraits<boost::heap::detail::heap_node_base<false>, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1, boost::intrusive::default_tag, 1u>: 
            static link_mode = <optimized out>
          }, 
          members of boost::intrusive::list_impl<boost::intrusive::bhtraits<boost::heap::detail::heap_node_base<false>, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1, boost::intrusive::default_tag, 1u>, unsigned long, true>::data_t: 
          root_plus_size_ = {
            <boost::intrusive::detail::size_holder<true, unsigned long, void>> = {
              static constant_time_size = <optimized out>, 
              size_ = 1
            }, 
            members of boost::intrusive::list_impl<boost::intrusive::bhtraits<boost::heap::detail::heap_node_base<false>, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1, boost::intrusive::default_tag, 1u>, unsigned long, true>::root_plus_size: 
            root_ = {
              next_ = 0x600004c38118, 
              prev_ = 0x0
            }
          }
        }
      }, <No data fields>}
  }, 
  members of boost::heap::detail::parent_pointing_heap_node<logalloc::segment*>: 
  parent = 0x3f74c347a6fde5
}
```

`parent` is bad.

**Comment by slivne** [comment]
@avikivity whats the status of this ?

**Comment by avikivity** [comment]
Looks like @asias / @gleb-cloudius managed to replicate it, so still active.

**Comment by slivne** [comment]
Related to #403

**Comment by tgrabiec** [comment]
#403 is closed, so closing this
