### ISSUE TITLE
Scylla aborts with std::bad_function_call when it fails to bind to a port

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#353]
Tested with 977f2ff0a765c1b81d5f12a6024244e78ac09045 and with a seastar patch which disables SO_REUSEPORT.

The triggering exception:
```
(gdb) bt
#0  0x00007ffff7469b9d in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x00000000004981e3 in throw_system_error_on (condition=<optimized out>)
    at core/posix.hh:349
#2  0x000000000045f869 in bind (sl=128, sa=..., this=<synthetic pointer>)
    at core/posix.hh:233
#3  reactor::posix_listen (this=0x600000262000, sa=..., opts=...)
    at core/reactor.cc:392
#4  0x00000000004ec825 in net::posix_network_stack::listen (this=<optimized out>, 
    sa=..., opt=...) at net/posix-stack.cc:181
#5  0x000000000045f9f1 in reactor::listen (this=<optimized out>, sa=..., opt=..., 
    opt@entry=...) at core/reactor.cc:426
#6  0x0000000000c0de6a in rpc::protocol<net::serializer, net::messaging_verb>::server::server (this=this@entry=0x600001619080, proto=..., addr=..., addr@entry=...)
    at /home/tgrabiec/src/urchin/seastar/rpc/rpc_impl.hh:518
#7  0x0000000000b73400 in rpc_protocol_server_wrapper (this=0x600001619080)
    at message/messaging_service.cc:167
#8  net::messaging_service::messaging_service (this=0x60000160ba80, ip=...)
    at message/messaging_service.cc:237
#9  0x0000000000cbbcb1 in make<gms::inet_address const&> ()
    at /home/tgrabiec/src/urchin/seastar/core/shared_ptr.hh:491
#10 make_shared<net::messaging_service, gms::inet_address const&> ()
    at /home/tgrabiec/src/urchin/seastar/core/shared_ptr.hh:501
#11 create_local_service<gms::inet_address const&> (
    this=0x16be1e0 <net::_the_messaging_service>) at ./seastar/core/sharded.hh:309
#12 operator() (args#0=..., __closure=<optimized out>)
    at ./seastar/core/sharded.hh:338
#13 apply (args=<optimized out>, func=<optimized out>) at ./seastar/core/apply.hh:34
#14 apply<seastar::sharded<Service>::start(Args&& ...)::<lambda(unsigned int)> mutable::<lambda()> mutable [with Args = {const gms::inet_address&}; Service = net::messaging_service]::<lambda(const gms::inet_address&)>, gms::inet_address> (
    args=<optimized out>, func=<optimized out>) at ./seastar/core/apply.hh:42
#15 operator() (__closure=0x7fffffffd5e0, __closure@entry=0x60000160ba80)
    at ./seastar/core/sharded.hh:336
#16 futurize<void>::apply<future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&>(future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&) (func=...) at ./seastar/core/future.hh:1072
#17 0x0000000000cc6648 in submit_to<seastar::sharded<Service>::start(Args&& ...)::<lambda(unsigned int)> mutable [with Args = {const gms::inet_address&}; Service = net::messaging_service]::<lambda()> > (
    func=<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0xbaaee9c, DIE 0xbceb6e4>, t=<optimized out>) at ./seastar/core/reactor.hh:980
#18 operator() (c=<optimized out>, __closure=<optimized out>)
```

What causes abort:
```
(gdb) bt
#0  0x00007ffff7469b9d in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x00007ffff7492f92 in std::__throw_bad_function_call() ()
   from /lib64/libstdc++.so.6
#2  0x0000000000b74ecc in operator() (this=0x60000160ba90)
    at /usr/include/c++/5.1.1/functional:2270
#3  seastar::async_sharded_service<net::messaging_service>::~async_sharded_service (
    this=<optimized out>, __in_chrg=<optimized out>)
    at /home/tgrabiec/src/urchin/seastar/core/sharded.hh:42
#4  0x0000000000b73460 in net::messaging_service::messaging_service (
    this=0x60000160ba80, ip=...) at message/messaging_service.cc:237
#5  0x0000000000cbbcb1 in make<gms::inet_address const&> ()
    at /home/tgrabiec/src/urchin/seastar/core/shared_ptr.hh:491
#6  make_shared<net::messaging_service, gms::inet_address const&> ()
    at /home/tgrabiec/src/urchin/seastar/core/shared_ptr.hh:501
#7  create_local_service<gms::inet_address const&> (
    this=0x16be1e0 <net::_the_messaging_service>) at ./seastar/core/sharded.hh:309
#8  operator() (args#0=..., __closure=<optimized out>)
    at ./seastar/core/sharded.hh:338
#9  apply (args=<optimized out>, func=<optimized out>) at ./seastar/core/apply.hh:34
#10 apply<seastar::sharded<Service>::start(Args&& ...)::<lambda(unsigned int)> mutable::<lambda()> mutable [with Args = {const gms::inet_address&}; Service = net::messaging_service]::<lambda(const gms::inet_address&)>, gms::inet_address> (
    args=<optimized out>, func=<optimized out>) at ./seastar/core/apply.hh:42
#11 operator() (__closure=0x7fffffffd5e0, __closure@entry=0x60000160ba80)
    at ./seastar/core/sharded.hh:336
#12 futurize<void>::apply<future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&>(future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&) (func=...) at ./seastar/core/future.hh:1072
#13 0x0000000000cc6648 in submit_to<seastar::sharded<Service>::start(Args&& ...)::<lambda(unsigned int)> mutable [with Args = {const gms::inet_address&}; Service = net::messaging_service]::<lambda()> > (
    func=<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0xbaaee9c, DIE 0xbceb6e4>, t=<optimized out>) at ./seastar/core/reactor.hh:980
#14 operator() (c=<optimized out>, __closure=<optimized out>)
    at ./seastar/core/sharded.hh:340
#15 future<> parallel_for_each<boost::range_detail::integer_iterator<unsigned int>, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}>(boost::range_detail::integer_iterator<unsigned int>, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}&&)::{lambda(parallel_for_each_state&)#1}::operator()(parallel_for_each_state) const (__closure=0x7fffffffd6c0, __closure@entry=0x7fffffffd5b0, 
    state=...) at /home/tgrabiec/src/urchin/seastar/core/future-util.hh:89
#16 0x0000000000cc6648 in parallel_for_each<boost::integer_range<unsigned int>, seastar::sharded<Service>::start(Args&& ...) [with Args = {const gms::inet_address&}; Service ---Type <return> to continue, or q <return> to quit---
= net::messaging_service]::<lambda(unsigned int)> > (func=<optimized out>, 
    range=<optimized out>)
#17 seastar::sharded<net::messaging_service>::start<gms::inet_address const&> (
    this=<optimized out>) at ./seastar/core/sharded.hh:349
#18 0x0000000000cd44c5 in do_with<parallel_for_each_state, parallel_for_each(Iterator, Iterator, Func&&) [with Iterator = boost::range_detail::integer_iterator<unsigned int>; Func = seastar::sharded<Service>::start(Args&& ...) [with Args = {const gms::inet_address&}; Service = net::messaging_service]::<lambda(unsigned int)>]::<lambda(parallel_for_each_state&)> > (
    f=<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0xbaaee9c, DIE 0xbd2233f>, 
    rvalue=<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0xbaaee9c, DIE 0xbd2240e>) at /home/tgrabiec/src/urchin/seastar/core/do_with.hh:55
#19 parallel_for_each<boost::range_detail::integer_iterator<unsigned int>, seastar::sharded<Service>::start(Args&& ...) [with Args = {const gms::inet_address&}; Service = net::messaging_service]::<lambda(unsigned int)> > (
    func=<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0xbaaee9c, DIE 0xbd20397>, end=..., begin=...)
    at /home/tgrabiec/src/urchin/seastar/core/future-util.hh:110
#20 parallel_for_each<boost::integer_range<unsigned int>, seastar::sharded<Service>::start(Args&& ...) [with Args = {const gms::inet_address&}; Service = net::messaging_service]::<lambda(unsigned int)> > (
    func=<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0xbaaee9c, DIE 0xbc9e8c1>, range=<optimized out>)
    at /home/tgrabiec/src/urchin/seastar/core/future-util.hh:132
#21 seastar::sharded<net::messaging_service>::start<gms::inet_address const&> (
    this=0x16be1e0 <net::_the_messaging_service>) at ./seastar/core/sharded.hh:349
#22 0x0000000000cb5094 in init_ms_fd_gossiper (listen_address=..., seed_provider=..., 
    cluster_name=...) at init.cc:26
#23 0x00000000005735a1 in operator() (__closure=0x6000000e8ed0, 
    __closure@entry=0x6000000e8ef0) at main.cc:183
#24 apply (args=<optimized out>, func=<optimized out>)
    at /home/tgrabiec/src/urchin/seastar/core/apply.hh:34
#25 apply<main(int, char**)::<lambda()>::<lambda()>::<lambda()> > (
    args=<optimized out>, func=<optimized out>)
    at /home/tgrabiec/src/urchin/seastar/core/apply.hh:42
#26 futurize<future<> >::apply<main(int, char**)::<lambda()>::<lambda()>::<lambda()> >(<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0x1277953, DIE 0x15f3a0e>, <unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0x1277953, DIE 0x15f3a21>) (
    func=func@entry=<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0x1277953, DIE 0x15f3a0e>, args=<optimized out>)
    at /home/tgrabiec/src/urchin/seastar/core/future.hh:1083
#27 0x0000000000576c0c in operator()<future_state<> > (
    state=<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0x1277953, DIE 0x1659d9b>, __closure=0x6000000e8eb0)
    at /home/tgrabiec/src/urchin/seastar/core/future.hh:779
#28 continuation<future<T>::then(Func&&) [with Func = main(int, char**)::<lambda()>::<l---Type <return> to continue, or q <return> to quit---
ambda()>::<lambda()>; Result = future<>; T = {}]::<lambda(auto:3&&)> >::run(void) (
    this=0x6000000e8ea0) at /home/tgrabiec/src/urchin/seastar/core/future.hh:359
#29 0x000000000046022a in reactor::run_tasks (this=this@entry=0x600000262000, 
    tasks=..., quota=<optimized out>) at core/reactor.cc:1093
#30 0x000000000048508b in reactor::run (this=0x600000262000) at core/reactor.cc:1190
#31 0x00000000004dde90 in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffe130, ac=ac@entry=14, av=av@entry=0x7fffffffe378, 
    func=func@entry=<unknown type in /home/tgrabiec/src/urchin/build/release/scylla, CU 0x52da5c, DIE 0x5dc94e>) at core/app-template.cc:122
#32 0x0000000000414e8b in main (ac=14, av=0x7fffffffe378) at main.cc:283

```

**Comment by tgrabiec** [comment]
Fixed by 5abdc4323a4f47b1b8c7a1107f4799bc16600134
