### ISSUE TITLE
Scylla_setup: OSError: Cannot call rmtree on a symbolic link

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3544]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20180624.828497ad1
Cluster size: 1 
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

* Description:
I tried to execute scylla_setup in non - interactive mode, and got this error.

```
[scylla-test@amos-centos7-test2 ~]$ sudo scylla_setup --nic eth0 --disks /dev/sdb --no-cpuscaling-setup
Skip any of the following steps by answering 'no'
Reactor stalled for 0 ms on shard 0.
Backtrace:
  0x00000000005ba592
  0x00000000004d9a4c
  0x00000000004d9f06
  /lib64/libpthread.so.0+0x000000000000f6cf
  /lib64/libc.so.6+0x00000000000f8ec8
  0x00000000006b2794
  0x00000000006b2028
  0x000000000042d079
  0x000000000042f9ca
  0x000000000041fb95
INFO  2018-06-25 12:04:25,695 [shard 0] iotune - /var/tmp/mnt passed sanity checks
This is a supported kernel version.
Unable to retrieve version information
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repo1.ash.innoscale.net
 * epel: mirror.us.leaseweb.net
 * extras: repos-va.psychz.net
 * updates: ftpmirror.your.org
Package ntp-4.2.6p5-28.el7.centos.x86_64 already installed and latest version
Package ntpdate-4.2.6p5-28.el7.centos.x86_64 already installed and latest version
Nothing to do
25 Jun 12:04:34 ntpdate[1998]: adjust time server 169.254.169.254 offset -0.000740 sec
Creating RAID0 for scylla using 1 disk(s): /dev/sdb
mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
meta-data=/dev/md0               isize=512    agcount=16, agsize=818688 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=0, sparse=0
data     =                       bsize=4096   blocks=13098752, imaxpct=25
         =                       sunit=256    swidth=256 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=6395, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
Traceback (most recent call last):
  File "/usr/lib/scylla/scylla_coredump_setup", line 65, in <module>
    shutil.rmtree('/var/lib/systemd/coredump')
  File "/usr/lib64/python3.4/shutil.py", line 478, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib64/python3.4/shutil.py", line 476, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
coredump setup failed.
[scylla-test@amos-centos7-test2 ~]$ ls -l /var/lib/systemd/coredump
lrwxrwxrwx 1 root root 24 Jun 25 12:02 /var/lib/systemd/coredump -> /var/lib/scylla/coredump
```

@syuu1228

**Comment by tzach** [comment]
@amoskong is it a regression?

**Comment by syuu1228** [comment]
@tzach it's not regression, since it caused by python3 conversion patchset.

**Comment by amoskong** [comment]
666.development-0.20180623.2d4177355  (PASS)
666.development-0.20180624.828497ad1  (FAILED)
