### ISSUE TITLE
ami: master AMI trying to create RAID device on unsupported instance type, and it's failing

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3547]
When I started ScyllaDB 2.2-rc1 (ami-385dc647) on c5.2xlarge, I got
```
AMI initial configuration failed!
```
And I found journal says scylla_ami_setup failed to create RAID volume.
The error is happening because the script think nvme0n1 is secondary disk, but actually it used for root volume and mounted.
We should fix the error, but shouldn't we skip creating RAID volume when we don't supported the instance type, anyway?

```
Jun 25 12:37:06 ip-172-30-0-104.ec2.internal scylla_ami_setup[1040]: Setting parameters on /etc/sysconfig/scylla-server
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: Waiting for cloud-init to finish...
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] No userdata found. Starting 1 node clusters, by default.
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] Using instance type: c5.2xlarge
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] meta-data:instance-type: c5.2xlarge
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] meta-data:local-ipv4: 172.16.99.41
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] meta-data:public-hostname: ec2-34-207-223-78.compute-1.amazonaws.com
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] meta-data:ami-launch-index: 0
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] meta-data:reservation-id: r-05283eb41e7affa50
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] Using cluster name: Test Cluster - No AMI Parameters
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] Using cluster size: 1
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] Using seed indexes: [0, 1, 1]
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] Reflector loop...
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] 06/25/18-12:37:20 Reflector: Received 1 of 1 responses from: [u'172.16.99.41']
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] scylla.yaml configured.
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: Creating RAID0 for scylla using 1 disk(s): /dev/nvme0n1
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: /dev/nvme0n1 does not supported TRIM, skipping blkdiscard...
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: mdadm: super1.x cannot open /dev/nvme0n1: Device or resource busy
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: mdadm: ddf: Cannot use /dev/nvme0n1: Device or resource busy
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: mdadm: Cannot use /dev/nvme0n1: It is busy
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: mdadm: cannot open /dev/nvme0n1: Device or resource busy
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: [INFO] RAID Array containing ['nvme0n1'] not found. Creating...
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: Traceback (most recent call last):
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 164, in <module>
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: get_disk_bundles()
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 160, in get_disk_bundles
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: config_array(t, typemap[t], role[t], mdidx)
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 59, in config_array
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: "--volume-role", role ])
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: raise CalledProcessError(retcode, cmd)
Jun 25 12:37:20 ip-172-16-99-41.ec2.internal scylla_ami_setup[1040]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla_raid_setup', '--raiddev', '/dev/md0', '--disks', '/dev/nvme0n1', '--root', '/var/lib/scylla', '--volume-role', 'all']' returned non-zero exit status 2
```

**Comment by syuu1228** [comment]
Looks like I wrote wrong title when I created issue, it's causes on 2.2 AMI instead of master AMI.
Also verified on 'ScyllaDB 2.2.0 (ami-3ceac343)'.

**Comment by syuu1228** [comment]
Add note: very likely happens on 2.3 and master AMI too, since we have same logic on scylla_ami_setup.
