### ISSUE TITLE
Scylla_setup on ubuntu 14 failed with "swapon: unrecognized option '--show=NAME'" error.

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3596]
*Installation details*
Scylla version (or git commit hash): 2.3
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu 14
Scylla_repo_file_url: https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/f6a2bafae2958622704b2e1ad8bb59bcc438311e-d6c408445e597e8bd531f3d9472e5d95335d9ecb-d20ea1bac351d396c5768f8ecbd001d469b05245/2/scylladb-2.3/scylla.list

Jenkins job: http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/scylla-2.3-ubuntu-deb-test/label=huginn/lastBuild/console

Logs folder on hugnin: /jenkins/slave/workspace/scylla-2.3/scylla-2.3-ubuntu-deb-test/label/huginn/latest/job.log

Scylla setup failed because of "swapon: unrecognized option '--show=NAME'" error.

{code}
2018-07-10 17:00:49,934 process          L0420 DEBUG| [stderr] swapon: unrecognized option '--show=NAME'
2018-07-10 17:00:49,935 process          L0420 DEBUG| [stderr] 
2018-07-10 17:00:49,935 process          L0420 DEBUG| [stderr] Usage:
2018-07-10 17:00:49,935 process          L0420 DEBUG| [stderr]  swapon [options] [<spec>]
2018-07-10 17:00:49,935 process          L0420 DEBUG| [stderr] 
2018-07-10 17:00:49,935 process          L0420 DEBUG| [stderr] Options:
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr]  -a, --all              enable all swaps from /etc/fstab
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr]  -d, --discard          discard freed pages before they are reused
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr]  -e, --ifexists         silently skip devices that do not exis
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr]  -f, --fixpgsz          reinitialize the swap space if necessary
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr]  -h, --help             display help and exit
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr]  -p, --priority <prio>  specify the priority of the swap device.
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr]  -s, --summary          display summary about used swap devices and exit
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr]  -v, --verbose          verbose mode
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr]  -V, --version          display version and exit
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr] 
2018-07-10 17:00:49,936 process          L0420 DEBUG| [stderr] The <spec> parameter:
2018-07-10 17:00:49,937 process          L0420 DEBUG| [stderr]  -L <label>             LABEL of device to be used
2018-07-10 17:00:49,937 process          L0420 DEBUG| [stderr]  -U <uuid>              UUID of device to be used
2018-07-10 17:00:49,937 process          L0420 DEBUG| [stderr]  LABEL=<label>          LABEL of device to be used
2018-07-10 17:00:49,937 process          L0420 DEBUG| [stderr]  UUID=<uuid>            UUID of device to be used
2018-07-10 17:00:49,937 process          L0420 DEBUG| [stderr]  <device>               name of device to be used
2018-07-10 17:00:49,937 process          L0420 DEBUG| [stderr]  <file>                 name of file to be used
2018-07-10 17:00:49,937 process          L0420 DEBUG| [stderr] 
2018-07-10 17:00:50,060 process          L0420 DEBUG| [stderr] Traceback (most recent call last):
2018-07-10 17:00:50,060 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_raid_setup", line 70, in <module>
2018-07-10 17:00:50,060 process          L0420 DEBUG| [stderr]     if not is_unused_disk(disk):
2018-07-10 17:00:50,060 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_util.py", line 337, in is_unused_disk
2018-07-10 17:00:50,060 process          L0420 DEBUG| [stderr]     s = out('swapon --show=NAME --noheadings')
2018-07-10 17:00:50,060 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_util.py", line 253, in out
2018-07-10 17:00:50,061 process          L0420 DEBUG| [stderr]     return subprocess.check_output(shlex.split(cmd)).strip().decode('utf-8')
2018-07-10 17:00:50,061 process          L0420 DEBUG| [stderr]   File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
2018-07-10 17:00:50,061 process          L0420 DEBUG| [stderr]     raise CalledProcessError(retcode, process.args, output=output)
2018-07-10 17:00:50,061 process          L0420 DEBUG| [stderr] subprocess.CalledProcessError: Command '['swapon', '--show=NAME', '--noheadings']' returned non-zero exit status 1
2018-07-10 17:00:50,075 process          L0420 DEBUG| [stdout] ESC[0;32mSkip any of the following steps by answering 'no'ESC[0m
2018-07-10 17:00:50,075 process          L0420 DEBUG| [stdout] Unable to retrieve version information
2018-07-10 17:00:50,075 process          L0420 DEBUG| [stdout] RAID setup failed.
2018-07-10 17:00:50,083 stacktrace       L0036 ERROR| 
2018-07-10 17:00:50,083 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:436
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR| Traceback (most recent call last):
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-2.3/scylla-2.3-ubuntu-deb-test/label/huginn/scylla-artifacts.py", line 735, in setUp
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR|     self.scylla_setup()
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-2.3/scylla-2.3-ubuntu-deb-test/label/huginn/scylla-artifacts.py", line 721, in scylla_setup
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR|     installer.run()
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-2.3/scylla-2.3-ubuntu-deb-test/label/huginn/scylla-artifacts.py", line 345, in run
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR|     process.run(setup_cmd, shell=True, verbose=True, timeout=600)
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 1031, in run
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
2018-07-10 17:00:50,097 stacktrace       L0042 ERROR| CmdError: Command '/usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/vdb --no-cpuscaling-setup' failed (rc=1)
2018-07-10 17:00:50,097 stacktrace       L0043 ERROR| 
2018-07-10 17:00:50,124 test             L0581 ERROR| ERROR 1-/root/avocado/tests/jenkins/slave/workspace/scylla-2.3/scylla-2.3-ubuntu-deb-test/label/huginn/scylla-artifacts.py:ScyllaArtifactSanity.test_after_install -> TestSetupFail: Command '/usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/vdb --no-cpuscaling-setup' failed (rc=1)
{code}

**Comment by syuu1228** [comment]
@juliayakovlev it fixed at 1a5a40e5f61273d5e958780c36725319401dd485 but only merged on master, needs to be backported to branch-2.3.

**Comment by syuu1228** [comment]
@juliayakovlev sorry I was wrong, it already merged to branch-2.3 2hrs ago.

**Comment by juliayakovlev** [comment]
@syuu1228  Thank you. So I'll re-check in the nightly run
@roydahan

**Comment by slivne** [comment]
@juliayakovlev ?

**Comment by juliayakovlev** [comment]
@slivne  this job wasn't run again.

**Comment by tzach** [comment]
@juliayakovlev ping
