### ISSUE TITLE
scylla_setup: ntp setup failed and error was ignored

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3629]
*Installation details*
Scylla version (or git commit hash): 2.1.6-0.20180701.7d2150a-1~jessie
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian8

* Test job: http://jenkins.cloudius-systems.com:8080/job/scylla-2.1-debian8-deb-test/label=huginn/213/artifact/latest/job.log

* Issue Description:
During NTP setup, the server is temporarily unavailable, it failed to sync the date by `ntpdate`.
ntp setup will break off without start NTP service.

* Suggestion:  CC @syuu1228 
- break scylla_setup for err in subtest, related with issue #3433
- ignore error ntpdate, and start NTP service (we still have chance to sync the date in future?)

* Reproduce method:
comment original server, and add an invalid server to /etc/ntp.conf
`server google.com iburst`  to /etc/ntp.conf

* Error for scylla_ntp_setup:
```
2018-07-25 04:37:31,265 process          L0420 DEBUG| [stdout] Setting up ntpdate (1:4.2.6.p5+dfsg-7+deb8u2) ...
2018-07-25 04:37:31,435 process          L0420 DEBUG| [stdout] Setting up lockfile-progs (0.1.17) ...
2018-07-25 04:37:43,189 process          L0420 DEBUG| [stderr] 25 Jul 04:37:43 ntpdate[18242]: no server suitable for synchronization found
```

* Status of NTP service:
```
2018-07-25 04:45:00,706 process          L0333 INFO | Running 'service ntp status'
2018-07-25 04:45:00,711 process          L0420 DEBUG| [stdout] â— ntp.service - LSB: Start NTP daemon
2018-07-25 04:45:00,711 process          L0420 DEBUG| [stdout]    Loaded: loaded (/etc/init.d/ntp)
2018-07-25 04:45:00,711 process          L0420 DEBUG| [stdout]    Active: inactive (dead) since Wed 2018-07-25 04:37:35 IDT; 7min ago
2018-07-25 04:45:00,711 process          L0420 DEBUG| [stdout] 
2018-07-25 04:45:00,711 process          L0420 DEBUG| [stdout] Jul 25 04:29:13 debian ntpd[472]: Listen normally on 2 lo 127.0.0.1 UDP 123
2018-07-25 04:45:00,712 process          L0420 DEBUG| [stdout] Jul 25 04:29:13 debian ntpd[472]: Listen normally on 3 eth0 192.168.122.7 UDP 123
2018-07-25 04:45:00,712 process          L0420 DEBUG| [stdout] Jul 25 04:29:13 debian ntpd[472]: Listen normally on 4 lo ::1 UDP 123
2018-07-25 04:45:00,712 process          L0420 DEBUG| [stdout] Jul 25 04:29:13 debian ntpd[472]: peers refreshed
2018-07-25 04:45:00,712 process          L0420 DEBUG| [stdout] Jul 25 04:29:13 debian ntpd[472]: Listening on routing socket on fd #21 for interface updates
2018-07-25 04:45:00,712 process          L0420 DEBUG| [stdout] Jul 25 04:29:16 debian ntpd[472]: Listen normally on 5 eth0 fe80::5054:ff:feb4:2226 UDP 123
2018-07-25 04:45:00,713 process          L0420 DEBUG| [stdout] Jul 25 04:29:16 debian ntpd[472]: peers refreshed
2018-07-25 04:45:00,713 process          L0420 DEBUG| [stdout] Jul 25 04:37:34 debian systemd[1]: Stopping LSB: Start NTP daemon...
2018-07-25 04:45:00,713 process          L0420 DEBUG| [stdout] Jul 25 04:37:34 debian ntp[18224]: Stopping NTP server: ntpd.
2018-07-25 04:45:00,713 process          L0420 DEBUG| [stdout] Jul 25 04:37:35 debian systemd[1]: Stopped LSB: Start NTP daemon.
```

**Comment by amoskong** [comment]
scylla 2.1 : dist/common/scripts/scylla_ntp_setup
```
if is_debian_variant; then
    apt-get install -y ntp ntpdate
    service ntp stop
    count=$(egrep '^server' /etc/ntp.conf|wc -l)
    if [ $count -eq 0 ]; then
        cp /etc/ntp.conf /etc/ntp.conf_orig
        grep -v "pool" /etc/ntp.conf > /etc/ntp.conf_new
        cp /etc/ntp.conf_new /etc/ntp.conf
        rm -rf /etc/ntp.conf_new
        echo "server ntp.ubuntu.com iburst" >> /etc/ntp.conf
    fi
    ntpdate `cat /etc/ntp.conf |egrep "^server"|head -n1|awk '{print $2}'`
    service ntp start
elif is_gentoo_variant; then
   ...
```

**Comment by tzach** [comment]
Can we make the ntpdate a dependency for Scylla (or statically linked) instead of downloading it in scylla_setup?
The current state is error prune, not friendly for offline install. Same case for node_exporter #2190

**Comment by syuu1228** [comment]
Even if we add ntp, ntpdate on dependency, we still have download such as
scylla_raid_setup.
And adding mdadm on dependency causes previously closed issue:
https://github.com/scylladb/scylla/issues/741

I think we can download all packages on offline installer that scripts
depends on.

2018年7月25日(水) 15:05 Tzach Livyatan <notifications@github.com>:

**Comment by amoskong** [comment]
@syuu1228 

Commit 8e4d135 introduced a SyntaxError in python script.

```
2018-07-28 23:45:38,629 process          L0333 INFO | Running '/usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/vdb --no-cpuscaling-setup'
2018-07-28 23:45:40,066 process          L0420 DEBUG| [stdout] INFO  2018-07-28 23:45:40,066 [shard 0] iotune - /var/tmp/mnt passed sanity checks
2018-07-28 23:45:40,149 process          L0420 DEBUG| [stdout] This is a supported kernel version.
2018-07-28 23:45:41,365 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_ntp_setup", line 52
2018-07-28 23:45:41,365 process          L0420 DEBUG| [stderr]     // ignore error, ntpd may able to adjust clock later
2018-07-28 23:45:41,365 process          L0420 DEBUG| [stderr]      ^
2018-07-28 23:45:41,365 process          L0420 DEBUG| [stderr] SyntaxError: invalid syntax
2018-07-28 23:45:41,368 process          L0420 DEBUG| [stdout] [1;32mSkip any of the following steps by answering 'no'[0m
2018-07-28 23:45:41,368 process          L0420 DEBUG| [stdout] Unable to retrieve version information
2018-07-28 23:45:41,368 process          L0420 DEBUG| [stdout] NTP setup failed.
```

@slivne re-open this issue?

**Comment by amoskong** [comment]
```
2018-07-30 23:44:43,348 process          L0420 DEBUG| [stderr] Traceback (most recent call last):
2018-07-30 23:44:43,348 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_ntp_setup", line 93, in <module>
2018-07-30 23:44:43,348 process          L0420 DEBUG| [stderr]     run('ntpdate {}'.format(server), Exception=False)
2018-07-30 23:44:43,348 process          L0420 DEBUG| [stderr] TypeError: run() got an unexpected keyword argument 'Exception'
```

New typo.  @syuu1228

**Comment by avikivity** [comment]
@syuu1228 please verify the fix before sending it.

**Comment by syuu1228** [comment]
@avikivity sorry about that. New patch sent on ml: [PATCH scylla] dist/common/scripts/scylla_ntp_setup: fix typo

**Comment by slivne** [comment]
so is this fixed ?

I think the patch is in 4bfa0ae2472ad4060b8b6a21f1552177515e51f1

**Comment by amoskong** [comment]
It's fixed. Latest job ([job/scylla-master-centos-rpm-test/469/](http://jenkins.cloudius-systems.com:8080/job/scylla-master-centos-rpm-test/469/)) is PASS.
