### ISSUE TITLE
jmx crash

### ISSUE THREAD

**Issue by avnerbarr** [scylladb/scylla#3646]
```
[root@scylladb-cluster-1-work-99f7e05.use avner]# rpm -q scylla-jmx
scylla-jmx-2.3.rc1-20180730.1dc4338.el7.noarch
```

```
Starting the JMX server
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at java.util.HashMap.resize(HashMap.java:704)
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at java.util.HashMap.putVal(HashMap.java:663)
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at java.util.HashMap.put(HashMap.java:612)
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at java.util.HashSet.add(HashSet.java:220)
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.objectNamesFromFilteredNamedObject
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNamesImpl(DefaultMBeanServerI
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(DefaultMBeanServerInter
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(JmxMBeanServer.java:619)
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at com.scylladb.jmx.utils.APIMBeanServer.queryNames(APIMBeanServer.java:106)
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at com.scylladb.jmx.main.Main.main(Main.java:49)
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: scylla-jmx.service: main process exited, code=exited, status=1/FAILURE
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: Unit scylla-jmx.service entered failed state.
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: scylla-jmx.service failed.
```

**Comment by avikivity** [comment]
/cc @haaawk 

@avnerbarr how many  tables/MVs are on that cluster?

**Comment by avnerbarr** [comment]
several hundred

**Comment by haaawk** [comment]
@avnerbarr Could you please paste a full log? The one you pasted above has some lines cropped. For example "Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.objectNamesFromFilteredNamedObject". There should be a file name and line number at the end of this line.

**Comment by avnerbarr** [comment]
```journalctl --since=today -u scylla-jmx
-- Logs begin at Tue 2018-07-24 14:32:44 UTC, end at Thu 2018-08-02 13:33:02 UTC. --
Aug 02 09:17:06 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: Started Scylla JMX.
Aug 02 09:17:06 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: Starting Scylla JMX...
Aug 02 09:17:06 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: Using config file: /etc/scylla/scylla.yaml
Aug 02 09:17:06 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: Connecting to http://172.30.1.35:10000
Aug 02 09:17:06 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: Starting the JMX server
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: Exception in thread "main" javax.management.RuntimeErrorException: Error thrown in preRegister method
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.throwMBeanRegistrationException(DefaultMBeanServerInterceptor.java:988)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.preRegister(DefaultMBeanServerInterceptor.java:1009)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:919)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.scylladb.jmx.metrics.APIMBean.checkRegistration(APIMBean.java:78)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at org.apache.cassandra.db.ColumnFamilyStore.checkRegistration(ColumnFamilyStore.java:112)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.scylladb.jmx.utils.APIMBeanServer.checkRegistrations(APIMBeanServer.java:280)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.scylladb.jmx.utils.APIMBeanServer.queryNames(APIMBeanServer.java:95)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.scylladb.jmx.main.Main.main(Main.java:49)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: Caused by: java.lang.OutOfMemoryError: Java heap space
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at java.util.Arrays.copyOfRange(Arrays.java:3664)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at java.lang.String.<init>(String.java:207)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at java.lang.String.substring(String.java:1969)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at javax.management.ObjectName.getDomain(ObjectName.java:1566)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.scylladb.jmx.metrics.MetricsMBean.lambda$getTypePredicate$0(MetricsMBean.java:46)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.scylladb.jmx.metrics.MetricsMBean$$Lambda$5/2054798982.test(Unknown Source)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.scylladb.jmx.metrics.APIMBean$1.apply(APIMBean.java:105)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.objectNamesFromFilteredNamedObjects(DefaultMBeanServerInterceptor.java:1521)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNamesImpl(DefaultMBeanServerInterceptor.java:564)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(DefaultMBeanServerInterceptor.java:554)
Aug 02 09:55:09 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3869]: at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(JmxMBeanServer.java:619)
...skipping...
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at com.scylladb.jmx.utils.APIMBeanServer.queryNames(APIMBeanServer.java:106)
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[32166]: at com.scylladb.jmx.main.Main.main(Main.java:49)
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: scylla-jmx.service: main process exited, code=exited, status=1/FAILURE
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: Unit scylla-jmx.service entered failed state.
Aug 02 12:00:41 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: scylla-jmx.service failed.
Aug 02 12:04:34 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: Started Scylla JMX.
Aug 02 12:04:34 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: Starting Scylla JMX...
Aug 02 12:04:34 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: Using config file: /etc/scylla/scylla.yaml
Aug 02 12:04:34 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: Connecting to http://172.30.1.35:10000
Aug 02 12:04:34 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: Starting the JMX server
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at java.util.HashMap.resize(HashMap.java:704)
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at java.util.HashMap.putVal(HashMap.java:663)
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at java.util.HashMap.put(HashMap.java:612)
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at java.util.HashSet.add(HashSet.java:220)
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.objectNamesFromFilteredNamedObjects(DefaultMBeanServerInterceptor.java:1511)
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNamesImpl(DefaultMBeanServerInterceptor.java:564)
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(DefaultMBeanServerInterceptor.java:554)
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(JmxMBeanServer.java:619)
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at com.scylladb.jmx.utils.APIMBeanServer.queryNames(APIMBeanServer.java:106)
Aug 02 12:06:35 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[1868]: at com.scylladb.jmx.main.Main.main(Main.java:49)
Aug 02 12:06:36 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: scylla-jmx.service: main process exited, code=exited, status=1/FAILURE
Aug 02 12:06:36 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: Unit scylla-jmx.service entered failed state.
Aug 02 12:06:36 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: scylla-jmx.service failed.
Aug 02 12:12:44 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: Started Scylla JMX.
Aug 02 12:12:44 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com systemd[1]: Starting Scylla JMX...
Aug 02 12:12:44 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3411]: Using config file: /etc/scylla/scylla.yaml
Aug 02 12:12:44 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3411]: Connecting to http://172.30.1.35:10000
Aug 02 12:12:44 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3411]: Starting the JMX server
Aug 02 12:12:50 scylladb-cluster-1-work-99f7e05.use.dynamicyield.com scylla-jmx[3411]: JMX is enabled to receive remote connections on port: 7199```

**Comment by haaawk** [comment]
Thanks @avnerbarr. 

Would it be possible for you to run scylla-jmx with the script I'm attaching?
[scylla-jmx.txt](https://github.com/scylladb/scylla/files/2257627/scylla-jmx.txt)
The only difference is that I added -XX:+HeapDumpOnOutOfMemoryError to dump a heap dump on OOM error.

Another option would be to find a way for me to reproduce your problem locally.

The easiest but also least helpful option is to run jcmd <scylla-jmx process id> GC.class_histogram to create a class histogram.

**Comment by avnerbarr** [comment]
How should I run it? 

Currently jmx is running as a service, i.e.

`service scylla-jmx start`

**Comment by tzach** [comment]
@avnerbarr did you have a chance to try @haaawk suggestion?

**Comment by avnerbarr** [comment]
not yet. I'll try to catch it when it happens

**Comment by slivne** [comment]
we have fixed the memory usage of scylla-jms scylladb/scylla-jmx@71f857b1de2d4cdaacc517402ba39a8275b5e52e
