### ISSUE TITLE
Fail to run Scylla docker 2.3-rc1 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3647]
*Installation details*
Scylla version (or git commit hash): 2.3-rc1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

```
> docker run --name some-scylla -d scylladb/scylla:2.3-rc1 --smp 1 --memory 1G --overprovisioned 1
> docker logs some-scylla
ERROR 2018-08-02 12:14:05,602 [shard 0] seastar - Exiting on unhandled exception: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)
2018-08-02 12:14:05,668 INFO exited: scylla (exit status 1; not expected)
Traceback (most recent call last):
  File "/usr/lib/scylla/scylla-housekeeping", line 174, in <module>
    args.func(args)
  File "/usr/lib/scylla/scylla-housekeeping", line 101, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/usr/lib/scylla/scylla-housekeeping", line 65, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/usr/lib/scylla/scylla-housekeeping", line 62, in get_json_from_url
    return json.loads(data)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2018-08-02 12:14:08,670 INFO spawned: 'scylla' with pid 87
/usr/lib/scylla/scylla_prepare: line 22: import: command not found
/usr/lib/scylla/scylla_prepare: line 23: import: command not found
/usr/lib/scylla/scylla_prepare: line 24: import: command not found
/usr/lib/scylla/scylla_prepare: line 25: from: command not found
/usr/lib/scylla/scylla_prepare: line 28: syntax error near unexpected token `>'
/usr/lib/scylla/scylla_prepare: line 28: `    if os.getuid() > 0:'
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARN  2018-08-02 12:14:09,030 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
Scylla version 2.3.rc1-0.20180726.adad12ddc starting ...
ERROR 2018-08-02 12:14:09,031 [shard 0] init - Could not read configuration file conf/scylla.yaml: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)
ERROR 2018-08-02 12:14:09,031 [shard 0] seastar - Exiting on unhandled exception: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)
2018-08-02 12:14:09,088 INFO exited: scylla (exit status 1; not expected)
2018-08-02 12:14:12,095 INFO spawned: 'scylla' with pid 103
/usr/lib/scylla/scylla_prepare: line 22: import: command not found
/usr/lib/scylla/scylla_prepare: line 23: import: command not found
/usr/lib/scylla/scylla_prepare: line 24: import: command not found
/usr/lib/scylla/scylla_prepare: line 25: from: command not found
/usr/lib/scylla/scylla_prepare: line 28: syntax error near unexpected token `>'
/usr/lib/scylla/scylla_prepare: line 28: `    if os.getuid() > 0:'
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARN  2018-08-02 12:14:12,228 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
Scylla version 2.3.rc1-0.20180726.adad12ddc starting ...
ERROR 2018-08-02 12:14:12,229 [shard 0] init - Could not read configuration file conf/scylla.yaml: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)
ERROR 2018-08-02 12:14:12,229 [shard 0] seastar - Exiting on unhandled exception: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)
2018-08-02 12:14:12,294 INFO exited: scylla (exit status 1; not expected)
2018-08-02 12:14:13,295 INFO gave up: scylla entered FATAL state, too many start retries too quickly
```

**Comment by avikivity** [comment]
```
 git show HEAD:dist/docker/redhat/scylla-service.sh
#!/bin/bash

. /usr/lib/scylla/scylla_prepare

export SCYLLA_HOME SCYLLA_CONF

exec /usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE $CPUSET $SCYLLA_DOCKER_ARGS
```
running a python script as shell, and exporting variables that (now) don't exist

**Comment by industral** [comment]
confirm. same here

**Comment by industral** [comment]
Quick and dirty fix:

```bash
docker exec -it scylla bash

vi /scylla-service.sh
```

Change to that:

```bash
python3 /usr/lib/scylla/scylla_prepare
exec /usr/bin/scylla --smp=1 --memory=256M --developer-mode=1
```

```bash
mkdir /conf
cp /etc/scylla/scylla.yaml /conf

docker restart scylla
```

I wonder did anybody test before upload new RC-1 to docker hub? Looks like alpha-1. Anyway, I get some other errors from DB..
