### ISSUE TITLE
dtest err: Operation failed for system_auth.roles - received 0 responses and 1 failures from 2 CL=QUORUM

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3671]
*Installation details*
Scylla version (or git commit hash): 2.3.rc1-0.20180806.ae71ffdcf
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Test job (kill_one_of_the_nodes_with_the_auth_info_test): http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/scylla-2.3-dtest/label=scylla-dtest,mode=release,smp=2/22/testReport/junit/auth_test/TestAuth/kill_one_of_the_nodes_with_the_auth_info_test/

* Description
system_auth.users and system_auth.roles has same `3` endpoints, we kill one endpoint in the test, there are still two available endpoints. But we got `ReadFailure` in executing `LIST USERS`.

```
Error 1:
Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed for system_auth.roles - received 0 responses and 1 failures from 2 CL=QUORUM." info={'failures': 1, 'received_responses': 0, 'required_responses': 2, 'consistency': 'QUORUM'}

Error 2:
Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed for system_auth.roles - received 1 responses and 1 failures from 2 CL=QUORUM." info={'failures': 1, 'received_responses': 1, 'required_responses': 2, 'consistency': 'QUORUM'}
```

This test is PASS for scylla 2.2, [job link](http://jenkins.cloudius-systems.com:8080/job/scylla-2.2-dtest/label=scylla-dtest,mode=release,smp=2/53/testReport/auth_test/TestAuth/kill_one_of_the_nodes_with_the_auth_info_test/)

* Dtest log:
```
2018-08-08 07:31:37.308606 going to run tests sequentially
2018-08-08 07:31:37.318930 cluster ccm directory: /home/amos/.dtest/dtest-vlYwP2
2018-08-08 07:32:08.109027 Default role created by node1
2018-08-08 07:32:08.109374 Cluster with 4 nodes started
2018-08-08 07:32:08.172682 Successfully get the session from node1
2018-08-08 07:32:08.210556 Debug users list: [Row(name=u'cassandra', super=True)]
2018-08-08 07:32:08.210640 Good: session is available as expected
2018-08-08 07:32:36.755773 Current RF of system_auth is 3
2018-08-08 07:32:38.571831 Endpoints of system_auth.roles:cassandra : ['127.0.0.4', '127.0.0.2', '127.0.0.1']
2018-08-08 07:32:40.294423 Endpoints of system_auth.users:cassandra : ['127.0.0.4', '127.0.0.2', '127.0.0.1']
2018-08-08 07:32:40.354539 Kill rf node2(node2: 127.0.0.2) to break Auth info
2018-08-08 07:32:40.457071 Try to re-get session from first rf endpoint(node4: 127.0.0.4)
2018-08-08 07:32:40.527023 Check if the new session works
2018-08-08 07:32:40.533719 Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed for system_auth.roles - received 1 responses and 1 failures from 2 CL=QUORUM." info={'failures': 1, 'received_responses': 1, 'required_responses': 2, 'consistency': 'QUORUM'}
2018-08-08 07:32:40.533793 xxx: session isn't available (read failure)

2018-08-08 07:32:40.533870 Check if the first session still works
2018-08-08 07:32:40.543026 Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed for system_auth.roles - received 0 responses and 1 failures from 2 CL=QUORUM." info={'failures': 1, 'received_responses': 0, 'required_responses': 2, 'consistency': 'QUORUM'}
2018-08-08 07:32:40.543103 xxx: session isn't available (read failure) 
```

```
ERROR: kill_one_of_the_nodes_with_the_auth_info_test (auth_test.TestAuth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amos/space/scylla-dtest/auth_test.py", line 1146, in kill_one_of_the_nodes_with_the_auth_info_test
    self._check_session_available(new_session)
  File "/home/amos/space/scylla-dtest/auth_test.py", line 1006, in _check_session_available
    rows = list(session.execute('LIST USERS'))
  File "cassandra/cluster.py", line 2016, in cassandra.cluster.Session.execute (cassandra/cluster.c:35491)
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result(
)
  File "cassandra/cluster.py", line 3826, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:74365)
    raise self._final_exception
ReadFailure: Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed for system_auth.r
oles - received 1 responses and 1 failures from 2 CL=QUORUM." info={'failures': 1, 'received_responses': 1, 'required_res
ponses': 2, 'consistency': 'QUORUM'}

```

@hakuch can you help to check it?

**Comment by tzach** [comment]
@hakuch ping

**Comment by hakuch** [comment]
@amoskong 

I believe that 13f1d067bf2e38bd237a64dd449c3ac181e563f4 fixes the issue.

I tried to reproduce the failure locally in the way that you described, and I cannot.

With `scylla` and `scylla-dtest` at `branch-2.2`:

```
CASSANDRA_DIR=$HOME/src/scylla_ref/build/release nosetests -s -v auth_test.py:TestAuth.kill_one_of_the_nodes_with_the_auth_info_test
```

```
$ CASSANDRA_DIR=$HOME/src/scylla_ref/build/release nosetests -s -v auth_test.py:TestAuth.kill_one_of_the_nodes_with_the_auth_info_test                                              
kill_one_of_the_nodes_with_the_auth_info_test (auth_test.TestAuth) ... ERROR                                                                                                                                         

======================================================================                                                                                                                                               
ERROR: kill_one_of_the_nodes_with_the_auth_info_test (auth_test.TestAuth)                                                                                                                                            
----------------------------------------------------------------------                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                   
  File "/home/jhaberku/src/scylla-dtest_ref/auth_test.py", line 1129, in kill_one_of_the_nodes_with_the_auth_info_test                                                                                               
    self._check_session_available(new_session)                                                                                                                                                                       
  File "/home/jhaberku/src/scylla-dtest_ref/auth_test.py", line 992, in _check_session_available                                                                                                                     
    rows = list(session.execute('LIST USERS'))                                                                                                                                                                       
  File "/usr/lib64/python2.7/site-packages/cassandra/cluster.py", line 1998, in execute                                                                                                                              
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()                                                                                           
  File "/usr/lib64/python2.7/site-packages/cassandra/cluster.py", line 3781, in result                                                                                                                               
    raise self._final_exception                                                                                                                                                                                      
Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1" info={'required_replicas': 2, 'alive_replicas': 1, 'consistency': 'QUORUM'}
```

Note that this fails in the way that you describe.

With `scylla` and `scylla-dtest` at 2.3:

```
$ CASSANDRA_DIR=$HOME/src/scylla_ref_2/build/release nosetests -s -v auth_test.py:TestAuth.kill_one_of_the_nodes_with_the_auth_info_test
kill_one_of_the_nodes_with_the_auth_info_test (auth_test.TestAuth) ... ok

----------------------------------------------------------------------
Ran 1 test in 68.491s

OK
```

With `scylla` and `scylla-dtest` at `HEAD` (6f1c3e69451b62c0d665ff953cddc18d8020c33c for `scylla`):

```
$ CASSANDRA_DIR=$HOME/src/scylla/build/release nosetests -s -v auth_test.py:TestAuth.kill_one_of_the_nodes_with_the_auth_info_test
kill_one_of_the_nodes_with_the_auth_info_test (auth_test.TestAuth) ... ok

----------------------------------------------------------------------
Ran 1 test in 69.794s

OK
```

Since 13f1d067bf2e38bd237a64dd449c3ac181e563f4 exists in `branch-2.3` and `HEAD` and does not exist in `branch-2.2`, I think this commit is the one that is necessary and that this explains the test failure.

Maybe the version of the dtest suite running in CI is different. Check to see if that commit is present or not.

**Comment by amoskong** [comment]
Thanks @hakuch 

The subtest is pass in latest [dtest-2.3](http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/scylla-2.3-dtest/37/label=scylla-dtest,mode=release,smp=2/testReport/auth_test/TestAuth/kill_one_of_the_nodes_with_the_auth_info_test/) result.

Close this issue, it's not a real bug.
