### ISSUE TITLE
scylla_setup (deb/systemd): unit scylla-server.service not found

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3675]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20180809.ad7bc313f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04 Ubuntu 18.04, Debian 9

* Description:
It seems `scylla-server.service` isn't packed correctly.

```
2018-08-09 02:23:27,259 process          L0333 INFO | Running '/usr/lib/scylla/scylla_setup --nic ens2 --disks /dev/sdb --no-cpuscaling-setup'
....
2018-08-09 02:23:45,247 process          L0420 DEBUG| [stdout] INFO  2018-08-09 02:23:45,226 [shard 0] iotune - /var/tmp/mnt passed sanity checks
2018-08-09 02:23:45,359 process          L0420 DEBUG| [stdout] This is a supported kernel version.
2018-08-09 02:23:45,401 process          L0420 DEBUG| [stdout] [1;32mSkip any of the following steps by answering 'no'[0m
2018-08-09 02:23:45,411 process          L0420 DEBUG| [stderr] Traceback (most recent call last):
2018-08-09 02:23:45,411 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_util.py", line 402, in __init__
2018-08-09 02:23:45,411 process          L0420 DEBUG| [stderr]     run('systemctl cat {}'.format(unit), silent=True)
2018-08-09 02:23:45,411 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_util.py", line 263, in run
2018-08-09 02:23:45,412 process          L0420 DEBUG| [stderr]     return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
2018-08-09 02:23:45,414 process          L0420 DEBUG| [stderr]   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
2018-08-09 02:23:45,415 process          L0420 DEBUG| [stderr]     raise CalledProcessError(retcode, cmd)
2018-08-09 02:23:45,415 process          L0420 DEBUG| [stderr] subprocess.CalledProcessError: Command '['systemctl', 'cat', 'scylla-server.service']' returned non-zero exit status 1.
2018-08-09 02:23:45,415 process          L0420 DEBUG| [stderr] 
2018-08-09 02:23:45,415 process          L0420 DEBUG| [stderr] During handling of the above exception, another exception occurred:
2018-08-09 02:23:45,415 process          L0420 DEBUG| [stderr] 
2018-08-09 02:23:45,415 process          L0420 DEBUG| [stderr] Traceback (most recent call last):
2018-08-09 02:23:45,415 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_setup", line 220, in <module>
2018-08-09 02:23:45,416 process          L0420 DEBUG| [stderr]     systemd_unit('scylla-server.service').enable()
2018-08-09 02:23:45,416 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_util.py", line 404, in __init__
2018-08-09 02:23:45,416 process          L0420 DEBUG| [stderr]     raise SystemdException('unit {} not found'.format(unit))
2018-08-09 02:23:45,416 process          L0420 DEBUG| [stderr] scylla_util.SystemdException: unit scylla-server.service not found
```

```
scylla-test@amos-ubuntu18:~$ sudo systemctl cat scylla-server.service
No files found for scylla-server.service.
scylla-test@amos-ubuntu18:~$ echo $?
1
```

@syuu1228

**Comment by amoskong** [comment]
On debian8 `systemctl cat scylla-server.service` didn't failed (result is empty), but `systemctl enable scylla-server.service` failed for same reason.

Test job: [job/scylla-master-debian-deb-8-test/215/](http://jenkins.cloudius-systems.com:8080/job/scylla-master-debian-deb-8-test/215/label=huginn/artifact/latest/job.log)

```
scylla-test@amos-debian8:~$ sudo systemctl cat scylla-server.service
scylla-test@amos-debian8:~$ echo $?
0
scylla-test@amos-debian8:~$ sudo systemctl status scylla-server.service
● scylla-server.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead) since Thu 2018-08-09 01:08:35 UTC; 13s ago
 Main PID: 861 (code=exited, status=0/SUCCESS)
   Status: "serving"

Aug 09 01:08:34 amos-debian8 scylla[861]: [shard 0] storage_service - Drain on shutdown: stop_transport done
Aug 09 01:08:34 amos-debian8 scylla[861]: [shard 0] tracing - Asked to shut down
Aug 09 01:08:34 amos-debian8 scylla[861]: [shard 0] tracing - Tracing is down
Aug 09 01:08:34 amos-debian8 scylla[861]: [shard 0] storage_service - Drain on shutdown: tracing is stopped
Aug 09 01:08:35 amos-debian8 scylla[861]: [shard 0] storage_service - Drain on shutdown: flush column_families done
Aug 09 01:08:35 amos-debian8 scylla[861]: [shard 0] storage_service - Drain on shutdown: shutdown commitlog done
Aug 09 01:08:35 amos-debian8 scylla[861]: [shard 0] storage_service - Drain on shutdown: done
Aug 09 01:08:35 amos-debian8 scylla[861]: [shard 0] repair - Starting shutdown of repair
Aug 09 01:08:35 amos-debian8 scylla[861]: [shard 0] repair - Completed shutdown of repair
Aug 09 01:08:35 amos-debian8 scylla[861]: [shard 0] compaction_manager - Asked to stop
Aug 09 01:08:35 amos-debian8 systemd[1]: Stopped scylla-server.service.
scylla-test@amos-debian8:~$ sudo systemctl enable scylla-server.service
Failed to execute operation: No such file or directory
scylla-test@amos-debian8:~$ echo $?
1
```

**Comment by syuu1228** [comment]
@amoskong Hmm, maybe we did something wrong on .deb packaging, will check
