### ISSUE TITLE
AWS AMI: nodetool info throws an exception

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#375]
Using latest AMI : ami-a5b5c6c0

Applying the patch "[PATCH scylla-jmx] dist: fix jvm option mistake in run script"

[root@ip-10-229-89-147 fedora]# nodetool -h 10.229.89.147 -p 7199 info
ID                     : 6bb05820-25db-4a89-8545-cd0e8b206e9d
Gossip active          : false
Thrift active          : true
Native Transport active: true
Load                   : 24807.0
Generation No          : 0
Uptime (seconds)       : 1548
Heap Memory (MB)       : 41.42 / 3342.50
Off Heap Memory (MB)   : 1.50
error: com.sun.jersey.api.client.ClientHandlerException (no security manager: RMI class loader disabled)
-- StackTrace --
java.lang.ClassNotFoundException: com.sun.jersey.api.client.ClientHandlerException (no security manager: RMI class loader disabled)
	at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:396)
	at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:186)
	at java.rmi.server.RMIClassLoader$2.loadClass(RMIClassLoader.java:637)
	at java.rmi.server.RMIClassLoader.loadClass(RMIClassLoader.java:264)
	at sun.rmi.server.MarshalInputStream.resolveClass(MarshalInputStream.java:214)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:245)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1022)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:298)
	at com.sun.proxy.$Proxy20.getDatacenter(Unknown Source)
	at org.apache.cassandra.tools.NodeProbe.getDataCenter(NodeProbe.java:818)
	at org.apache.cassandra.tools.NodeTool$Info.execute(NodeTool.java:425)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:288)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:202)

**Comment by slivne** [comment]
we are based on 2.1.8 for anglerfish - closing the issue
