### ISSUE TITLE
Indexes of columns in Scylla-generated SSTables 3.x files don't match those from Cassandra

### ISSUE THREAD

**Issue by argenet** [scylladb/scylla#3853]
The problem revolves around the serialization header and how static/regular columns are stored and accessed.

In Scylla, we serialize and deserialize them to utils::chunked_vector to preserve the natural order.

Cassandra does the same when reading/writing them (See deserialize() method:
https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/db/SerializationHeader.java#L453).

But, when translating into a SerializationHeader, Cassandra puts all those ColumnDefinitions into a BTree that breaks the ordering - see toHeader() method:
https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/db/SerializationHeader.java#L294).

The order used by Cassandra is determined by org.apache.cassandra.config.ColumnDefinition#comparisonOrder, which doesn't take the data type into account, but it takes isComplex() (our !is_atomic()?) into account before the name.

We need to use the same order of columns when writing indices of present/missing columns to SSTables 3.x as well as when we read those columns back.

Repro steps:

Using Scylla with enable_sstables_mc_format: true, generate the following table:
```
cqlsh> CREATE KEYSPACE sst3 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> use sst3 ;
cqlsh:sst3> CREATE TABLE atomic_and_collection1 ( pk int, ck int, rc1 text, rc2 list<text>, rc3 text, rc4 list<text>, rc5 text, rc6 list<text>, PRIMARY KEY (pk, ck)) WITH compression = {'sstable_compression': ''};
cqlsh:sst3> INSERT INTO atomic_and_collection1 (pk, ck, rc1, rc4, rc5) VALUES (0, 0, 'hello', ['beautiful','world'], 'here');

<< flush >>
```
Now try to dump it with `sstabledump`:

```
sstabledump -t -d ~/sstables/testcase/mc-1-big-Data.db
Exception in thread "main" org.apache.cassandra.io.sstable.CorruptSSTableException: Corrupted: /home/argenet/sstables/testcase/mc-1-big-Data.db
	at org.apache.cassandra.io.sstable.SSTableIdentityIterator.hasNext(SSTableIdentityIterator.java:134)
	at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.computeNext(LazilyInitializedUnfilteredRowIterator.java:100)
	at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.computeNext(LazilyInitializedUnfilteredRowIterator.java:32)
	at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at org.apache.cassandra.tools.SSTableExport.lambda$main$6(SSTableExport.java:229)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.apache.cassandra.tools.SSTableExport.main(SSTableExport.java:215)
Caused by: java.io.EOFException: EOF after -1 bytes out of 1
	at org.apache.cassandra.io.util.RebufferingInputStream.readFully(RebufferingInputStream.java:68)
	at org.apache.cassandra.io.util.RebufferingInputStream.readFully(RebufferingInputStream.java:60)
	at org.apache.cassandra.utils.ByteBufferUtil.read(ByteBufferUtil.java:402)
	at org.apache.cassandra.utils.ByteBufferUtil.readWithVIntLength(ByteBufferUtil.java:340)
	at org.apache.cassandra.db.marshal.CollectionType$CollectionPathSerializer.deserialize(CollectionType.java:248)
	at org.apache.cassandra.db.rows.Cell$Serializer.deserialize(Cell.java:241)
	at org.apache.cassandra.db.rows.UnfilteredSerializer.readComplexColumn(UnfilteredSerializer.java:694)
	at org.apache.cassandra.db.rows.UnfilteredSerializer.lambda$deserializeRowBody$1(UnfilteredSerializer.java:631)
	at org.apache.cassandra.utils.btree.BTree.applyForwards(BTree.java:1221)
	at org.apache.cassandra.utils.btree.BTree.apply(BTree.java:1176)
	at org.apache.cassandra.db.Columns.apply(Columns.java:398)
	at org.apache.cassandra.db.rows.UnfilteredSerializer.deserializeRowBody(UnfilteredSerializer.java:625)
	at org.apache.cassandra.db.rows.UnfilteredSerializer.deserializeOne(UnfilteredSerializer.java:495)
	at org.apache.cassandra.db.rows.UnfilteredSerializer.deserialize(UnfilteredSerializer.java:442)
	at org.apache.cassandra.io.sstable.SSTableSimpleIterator$CurrentFormatIterator.computeNext(SSTableSimpleIterator.java:95)
	at org.apache.cassandra.io.sstable.SSTableSimpleIterator$CurrentFormatIterator.computeNext(SSTableSimpleIterator.java:73)
	at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47)
	at org.apache.cassandra.io.sstable.SSTableIdentityIterator.hasNext(SSTableIdentityIterator.java:122)
	... 16 more
```

In the case above, Cassandra (`sstabledump`) re-orders columns so that the indices written by Scylla correspond to [rc1 rc2 rc4] rather than [rc1, rc4, rc5] which causes errors on parsing.

**Comment by argenet** [comment]
Re-opening for a while as the merged fix does not cover static columns that are also affected.
