### ISSUE TITLE
ubuntu 18: scylla-jmx crash in start

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3858]
*Installation details*
Scylla version (or git commit hash): 3.0.rc0-0.20181016.202913406
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI):  ubuntu 18.04

* Description:

Test job: http://jenkins.cloudius-systems.com:8080/view/scylla-3.0/job/scylla-3.0/job/3.0-test/job/scylla-ubuntu-deb-18.04-test/label=huginn/4/

Test log: http://jenkins.cloudius-systems.com:8080/view/scylla-3.0/job/scylla-3.0/job/3.0-test/job/scylla-ubuntu-deb-18.04-test/label=huginn/4/artifact/latest/job.log

* Scylla-jmx error in start
[ubuntu18-jmx-full-err.txt](https://github.com/scylladb/scylla/files/2485759/ubuntu18-jmx-full-err.txt)

```
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]: Oct 16, 2018 3:22:58 PM org.glassfish.jersey.internal.Errors logErrors
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]: WARNING: The following warnings have been detected: WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]: MultiException stack 1 of 2
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]: java.lang.NoClassDefFoundError: javax/activation/DataSource
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3090)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2316)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1311)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1307)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at java.base/java.security.AccessController.doPrivileged(Native Method)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1307)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1250)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at org.glassfish.jersey.internal.inject.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:144)
15:22:59 DEBUG| [stdout] Oct 16 15:22:59 ubuntu18 scylla-jmx[18130]:         at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:179)
```

* Scylla-jmx service status

```
2018-10-16 15:23:37,276 process          L0333 INFO | Running 'systemctl status scylla-jmx.service'
2018-10-16 15:23:37,283 process          L0420 DEBUG| [stdout] ● scylla-jmx.service - Scylla JMX
2018-10-16 15:23:37,284 process          L0420 DEBUG| [stdout]    Loaded: loaded (/lib/systemd/system/scylla-jmx.service; disabled; vendor preset: enabled)
2018-10-16 15:23:37,284 process          L0420 DEBUG| [stdout]    Active: active (running) since Tue 2018-10-16 15:23:22 IDT; 15s ago
2018-10-16 15:23:37,284 process          L0420 DEBUG| [stdout]  Main PID: 18338 (scylla-jmx)
2018-10-16 15:23:37,284 process          L0420 DEBUG| [stdout]     Tasks: 15 (limit: 4667)
2018-10-16 15:23:37,284 process          L0420 DEBUG| [stdout]    CGroup: /system.slice/scylla-jmx.service
2018-10-16 15:23:37,285 process          L0420 DEBUG| [stdout]            └─18338 /usr/lib/scylla/jmx/symlinks/scylla-jmx -Xmx256m -XX:+UseSerialGC -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.    management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.host=localhost -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Djava.rmi.server.hostname=localhost -Dcom.sun.management.     jmxremote.rmi.port=7199 -Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder -jar /usr/lib/scylla/jmx/scylla-jmx-1.0.jar
2018-10-16 15:23:37,285 process          L0420 DEBUG| [stdout]
2018-10-16 15:23:37,285 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:774)
2018-10-16 15:23:37,285 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
2018-10-16 15:23:37,285 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.glassfish.jersey.client.RequestProcessingInitializationStage.                             apply(RequestProcessingInitializationStage.java:97)
2018-10-16 15:23:37,285 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.glassfish.jersey.client.RequestProcessingInitializationStage.                             apply(RequestProcessingInitializationStage.java:67)
2018-10-16 15:23:37,286 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:308)
2018-10-16 15:23:37,286 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
2018-10-16 15:23:37,286 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
2018-10-16 15:23:37,286 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700)
2018-10-16 15:23:37,286 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
2018-10-16 15:23:37,287 process          L0420 DEBUG| [stdout] Oct 16 15:23:24 ubuntu18 scylla-jmx[18338]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
```

* Failed to execute 'nodetool status'
```
2018-10-16 15:23:37,287 process          L0333 INFO | Running '/usr/bin/nodetool status'
2018-10-16 15:23:38,929 process          L0420 DEBUG| [stderr] error: null
2018-10-16 15:23:38,930 process          L0420 DEBUG| [stderr] -- StackTrace --
2018-10-16 15:23:38,931 process          L0420 DEBUG| [stderr] java.lang.NullPointerException
2018-10-16 15:23:38,931 process          L0420 DEBUG| [stderr]  at org.apache.cassandra.config.DatabaseDescriptor.getDiskFailurePolicy(DatabaseDescriptor.java:1881)
2018-10-16 15:23:38,931 process          L0420 DEBUG| [stderr]  at org.apache.cassandra.utils.JVMStabilityInspector.inspectThrowable(JVMStabilityInspector.java:82)
2018-10-16 15:23:38,931 process          L0420 DEBUG| [stderr]  at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:79)
2018-10-16 15:23:38,931 process          L0420 DEBUG| [stderr]  at org.apache.cassandra.utils.FBUtilities.getToolsOutputDirectory(FBUtilities.java:824)
2018-10-16 15:23:38,932 process          L0420 DEBUG| [stderr]  at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:204)
2018-10-16 15:23:38,932 process          L0420 DEBUG| [stderr]  at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:170)
2018-10-16 15:23:38,932 process          L0420 DEBUG| [stderr]
```

* Scylla-server status (Looks good)

```
2018-10-16 15:23:57,653 process          L0333 INFO | Running 'systemctl status scylla-server.service'
2018-10-16 15:23:57,662 process          L0420 DEBUG| [stdout] ● scylla-server.service - Scylla Server
2018-10-16 15:23:57,662 process          L0420 DEBUG| [stdout]    Loaded: loaded (/lib/systemd/system/scylla-server.service; enabled; vendor preset: enabled)
2018-10-16 15:23:57,662 process          L0420 DEBUG| [stdout]   Drop-In: /etc/systemd/system/scylla-server.service.d
2018-10-16 15:23:57,663 process          L0420 DEBUG| [stdout]            └─mounts.conf
2018-10-16 15:23:57,663 process          L0420 DEBUG| [stdout]    Active: active (running) since Tue 2018-10-16 15:23:42 IDT; 15s ago
2018-10-16 15:23:57,663 process          L0420 DEBUG| [stdout]   Process: 18489 ExecStopPost=/usr/lib/scylla/scylla_stop (code=exited, status=0/SUCCESS)
2018-10-16 15:23:57,663 process          L0420 DEBUG| [stdout]   Process: 18490 ExecStartPre=/usr/lib/scylla/scylla_prepare (code=exited, status=0/SUCCESS)
2018-10-16 15:23:57,664 process          L0420 DEBUG| [stdout]  Main PID: 18492 (scylla)
2018-10-16 15:23:57,664 process          L0420 DEBUG| [stdout]    Status: "serving"
2018-10-16 15:23:57,664 process          L0420 DEBUG| [stdout]     Tasks: 3 (limit: 4667)
2018-10-16 15:23:57,664 process          L0420 DEBUG| [stdout]    CGroup: /system.slice/scylla-server.service
2018-10-16 15:23:57,664 process          L0420 DEBUG| [stdout]            └─18492 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --num-io-queues=1 --io-        properties-file=/etc/scylla.d/io_properties.yaml
2018-10-16 15:23:57,664 process          L0420 DEBUG| [stdout]
2018-10-16 15:23:57,664 process          L0420 DEBUG| [stdout] Oct 16 15:23:43 ubuntu18 scylla[18492]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/la-30-big-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/la-31-big-Data.db:level=0, ]
2018-10-16 15:23:57,665 process          L0420 DEBUG| [stdout] Oct 16 15:23:43 ubuntu18 scylla[18492]:  [shard 0] storage_service - NORMAL: node is now in normal status
2018-10-16 15:23:57,665 process          L0420 DEBUG| [stdout] Oct 16 15:23:43 ubuntu18 scylla[18492]:  [shard 0] storage_service - SSTable data integrity checker is disabled.
2018-10-16 15:23:57,665 process          L0420 DEBUG| [stdout] Oct 16 15:23:43 ubuntu18 scylla[18492]:  [shard 0] gossip - Waiting for gossip to settle before accepting client requests...
2018-10-16 15:23:57,665 process          L0420 DEBUG| [stdout] Oct 16 15:23:43 ubuntu18 scylla[18492]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/la-8- big-Data.db:level=0, /var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-7-Data.db:level=0, ]
2018-10-16 15:23:57,665 process          L0420 DEBUG| [stdout] Oct 16 15:23:43 ubuntu18 scylla[18492]:  [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/local-                          7ad54392bcdd35a684174e047860b377/la-32-big-Data.db:level=0, ]. 35273 bytes to 18602 (~52% of original) in 141ms = 0.13MB/s. ~256 total partitions merged to 1.
2018-10-16 15:23:57,665 process          L0420 DEBUG| [stdout] Oct 16 15:23:43 ubuntu18 scylla[18492]:  [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/peers-                          37f71aca7dc2383ba70672528af04d4f/la-9-big-Data.db:level=0, ]. 9792 bytes to 5060 (~51% of original) in 69ms = 0.07MB/s. ~256 total partitions merged to 1.
2018-10-16 15:23:57,665 process          L0420 DEBUG| [stdout] Oct 16 15:23:55 ubuntu18 scylla[18492]:  [shard 0] gossip - No gossip backlog; proceeding
2018-10-16 15:23:57,666 process          L0420 DEBUG| [stdout] Oct 16 15:23:55 ubuntu18 scylla[18492]:  [shard 0] storage_service - Starting listening for CQL clients on 127.0.0.1:9042 (unencrypted)
2018-10-16 15:23:57,666 process          L0420 DEBUG| [stdout] Oct 16 15:23:55 ubuntu18 scylla[18492]:  [shard 0] storage_service - Thrift server listening on localhost:9160 ...
```

**Comment by elcallio** [comment]
The first error at least looks like you are running java 9 or higher. In JDK 9 they made a bunch of javax.* packages optional, so running without special options and whatnot will cause CNFE. 
Can you try with JDK8 and verify it works then? We can modify our scylla-jmx maven build to include these packages in the fat jar, but it would be nice to know this is the culprit.

**Comment by amoskong** [comment]
That's java 10 (openjdk-11). It works well after swith to java 1.8

```
scylla-test@amos-ubuntu18:~$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)

scylla-test@amos-ubuntu18:~$ dpkg -l |grep openjdk
ii  openjdk-11-jre-headless:amd64  10.0.2+13-1ubuntu0.18.04.2                   amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-8-jre-headless:amd64   8u181-b13-0ubuntu0.18.04.1                   amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```

```
scylla-test@amos-ubuntu18:~$ sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
update-alternatives: error: no alternatives for appletviewer
update-alternatives: error: no alternatives for extcheck
update-alternatives: error: no alternatives for idlj
update-alternatives: error: no alternatives for jaotc
update-alternatives: error: no alternatives for jar
update-alternatives: error: no alternatives for jarsigner
update-alternatives: error: no alternatives for javac
update-alternatives: error: no alternatives for javadoc
update-alternatives: error: no alternatives for javah
update-alternatives: error: no alternatives for javap
update-alternatives: error: no alternatives for jcmd
update-alternatives: error: no alternatives for jconsole
update-alternatives: error: no alternatives for jdb
update-alternatives: error: no alternatives for jdeprscan
update-alternatives: error: no alternatives for jdeps
update-alternatives: error: no alternatives for jhat
update-alternatives: error: no alternatives for jhsdb
update-alternatives: error: no alternatives for jimage
update-alternatives: error: no alternatives for jinfo
update-alternatives: error: no alternatives for jlink
update-alternatives: error: no alternatives for jmap
update-alternatives: error: no alternatives for jmod
update-alternatives: error: no alternatives for jps
update-alternatives: error: no alternatives for jrunscript
update-alternatives: error: no alternatives for jsadebugd
update-alternatives: error: no alternatives for jshell
update-alternatives: error: no alternatives for jstack
update-alternatives: error: no alternatives for jstat
update-alternatives: error: no alternatives for jstatd
update-alternatives: error: no alternatives for mozilla-javaplugin.so
update-alternatives: error: no alternatives for native2ascii
update-alternatives: error: no alternatives for policytool
update-alternatives: error: no alternatives for rmic
update-alternatives: error: no alternatives for schemagen
update-alternatives: error: no alternatives for serialver
update-alternatives: error: no alternatives for wsgen
update-alternatives: error: no alternatives for wsimport
update-alternatives: error: no alternatives for xjc
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-8-openjdk-amd64/bin/appletviewer
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-8-openjdk-amd64/bin/jconsole
update-alternatives: error: no alternatives for extcheck
update-alternatives: error: no alternatives for idlj
update-alternatives: error: no alternatives for jar
update-alternatives: error: no alternatives for jarsigner
update-alternatives: error: no alternatives for javac
update-alternatives: error: no alternatives for javadoc
update-alternatives: error: no alternatives for javah
update-alternatives: error: no alternatives for javap
update-alternatives: error: no alternatives for jcmd
update-alternatives: error: no alternatives for jdb
update-alternatives: error: no alternatives for jdeps
update-alternatives: error: no alternatives for jhat
update-alternatives: error: no alternatives for jinfo
update-alternatives: error: no alternatives for jmap
update-alternatives: error: no alternatives for jps
update-alternatives: error: no alternatives for jrunscript
update-alternatives: error: no alternatives for jsadebugd
update-alternatives: error: no alternatives for jstack
update-alternatives: error: no alternatives for jstat
update-alternatives: error: no alternatives for jstatd
update-alternatives: error: no alternatives for native2ascii
update-alternatives: error: no alternatives for rmic
update-alternatives: error: no alternatives for schemagen
update-alternatives: error: no alternatives for serialver
update-alternatives: error: no alternatives for wsgen
update-alternatives: error: no alternatives for wsimport
update-alternatives: error: no alternatives for xjc
update-alternatives: error: no alternatives for policytool
update-java-alternatives: plugin alternative does not exist: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/IcedTeaPlugin.so
scylla-test@amos-ubuntu18:~$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

scylla-test@amos-ubuntu18:~$ sudo systemctl restart scylla-server

oscylla-test@amos-ubuntu18:~$ journalctl  -u scylla-jmx -f
-- Logs begin at Mon 2018-06-04 13:00:52 UTC. --
Oct 24 01:02:46 amos-ubuntu18 scylla-jmx[12394]: JMX is enabled to receive remote connections on port: 7199
Oct 24 01:05:21 amos-ubuntu18 systemd[1]: Stopping Scylla JMX...
Oct 24 01:05:22 amos-ubuntu18 systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=143/n/a
Oct 24 01:05:22 amos-ubuntu18 systemd[1]: scylla-jmx.service: Failed with result 'exit-code'.
Oct 24 01:05:22 amos-ubuntu18 systemd[1]: Stopped Scylla JMX.
Oct 24 01:05:25 amos-ubuntu18 systemd[1]: Started Scylla JMX.
Oct 24 01:05:26 amos-ubuntu18 scylla-jmx[12748]: Using config file: /etc/scylla/scylla.yaml
Oct 24 01:05:26 amos-ubuntu18 scylla-jmx[12748]: Connecting to http://127.0.0.1:10000
Oct 24 01:05:26 amos-ubuntu18 scylla-jmx[12748]: Starting the JMX server
Oct 24 01:05:27 amos-ubuntu18 scylla-jmx[12748]: JMX is enabled to receive remote connections on port: 7199

scylla-test@amos-ubuntu18:~$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  216.25 KB  256          ?       f89a7b09-5a29-48bc-96a2-4220d9c32626  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

**Comment by amoskong** [comment]
TODO mentioned by @elcallio:
We can modify our scylla-jmx maven build to include these packages in the fat jar, but it would be nice to know this is the culprit.

Will we officially support 18.04 from scylla 3.0? release the 18.04 packages/repo?
Then we need to mention user to switch to old java.

**Comment by slivne** [comment]
We support Ubuntu18.04 from 2.3

If we are missing something in the docs lets fix it.

We can work on allowing non 1.8 support - but we need it complete for tools
and jmx - not only for jmx. I am not sure thats feasible for scylla-tools.
in any case its not part of 3.0


On Thu, Oct 25, 2018 at 11:32 AM, Amos Kong <notifications@github.com>
wrote:

> TODO mentioned by @elcallio <https://github.com/elcallio>:
> We can modify our scylla-jmx maven build to include these packages in the
> fat jar, but it would be nice to know this is the culprit.
>
> Will we officially support 18.04 from scylla 3.0? release the 18.04
> packages/repo?
>


> Then we need to mention user to switch to old java.
>

we support 18.04 from 2.3

**Comment by Solvik** [comment]
On a freshly installed Ubuntu 18.04 I had the same problem with multiple java exceptions regarding JMX in my syslog.
I had to switch the Java version using `update-alternatives`

Example below:

```
# update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number:
```

It fixed all my issues.
I would have saved time by reading this in the doc though, hope it get added soon.

**Comment by breign** [comment]
on ubuntu 16.04 I had too choose java-8-openjdk-amd64 for scylla-jmx.service to work too
