### ISSUE TITLE
c-s issue when more than one loads stressing scylla

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#386]
```
1) When one c3.8xlarge node stressing scylla (one node cluster with c3.8xlarge)

Load1
=================================  node status: 172.31.40.176
["172.31.40.176"]
=================================  perf status
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
==> bigperf.172.31.40.176.cpu0 <==
total,       1101272,   41592,   41592,   41592,    21.6,    10.0,    63.5,   217.6,   246.6,   260.0,   23.6,  0.01665,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu12 <==
total,       1616125,   68403,   68403,   68403,    13.1,    12.1,    24.5,    32.0,    42.0,    56.0,   25.1,  0.01858,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu16 <==
total,       1639122,   70839,   70839,   70839,    12.7,    11.9,    22.6,    29.5,    57.1,    61.5,   25.3,  0.01911,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu20 <==
total,       1535610,   61369,   61369,   61369,    14.7,    11.1,    36.7,   103.4,   145.8,   153.2,   25.2,  0.02071,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu24 <==
total,       1646334,   70220,   70220,   70220,    12.8,    11.9,    22.8,    30.3,    40.8,    51.0,   24.9,  0.01689,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu28 <==
total,       1649124,   69268,   69268,   69268,    13.0,    12.2,    23.6,    30.6,    40.1,    49.1,   25.2,  0.02197,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu4 <==
total,       1545795,   57157,   57157,   57157,    15.7,    12.5,    30.6,   132.3,   150.7,   164.9,   24.3,  0.02133,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu8 <==
total,       1620277,   67496,   67496,   67496,    13.3,    12.1,    24.8,    36.4,    64.9,    81.8,   25.5,  0.01311,      0,      0,       0,       0,       0,       0


2) When two c3.8xlarge nodes stressing scylla 

Some of the c-s processes starts to timeout and fails to proceed.

Load1
=================================  node status: 172.31.40.176
["172.31.40.176"]
=================================  perf status
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
==> bigperf.172.31.40.176.cpu0 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

==> bigperf.172.31.40.176.cpu12 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

==> bigperf.172.31.40.176.cpu16 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

==> bigperf.172.31.40.176.cpu20 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

==> bigperf.172.31.40.176.cpu24 <==
total,      63259651,  111089,  111089,  111089,     8.1,     7.8,    13.3,    16.3,    19.5,    25.5,  883.2,  0.00602,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu28 <==
total,      64614021,  112040,  112040,  112040,     8.0,     7.7,    13.2,    19.5,    36.5,    42.2,  883.0,  0.00621,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu4 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

==> bigperf.172.31.40.176.cpu8 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

Load2
["172.31.40.176"]
=================================  perf status
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
==> bigperf.172.31.40.176.cpu0 <==
total,        167989,    5368,    5368,    5368,    63.7,     1.0,    19.1,  1586.8,  7570.7, 20067.1,   24.3,  0.54966,      1,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu12 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

==> bigperf.172.31.40.176.cpu16 <==
total,      21230657,  103902,  103902,  103902,     8.6,     8.1,    14.7,    25.4,    44.6,    52.8,  223.3,  0.00776,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu20 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

==> bigperf.172.31.40.176.cpu24 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

==> bigperf.172.31.40.176.cpu28 <==
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

==> bigperf.172.31.40.176.cpu4 <==
total,      21721823,  109965,  109965,  109965,     8.2,     8.0,    13.3,    16.2,    20.5,    27.8,  222.3,  0.00706,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu8 <==


I saw

        at org.apache.cassandra.stress.Operation.error(Operation.java:216)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)
java.io.IOException: Operation x10 on key(s) [4f4c3337354f4c324b30]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (no host was tried)

        at org.apache.cassandra.stress.Operation.error(Operation.java:216)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)
java.io.IOException: Operation x10 on key(s) [34333633313432503030]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (no host was tried)

        at org.apache.cassandra.stress.Operation.error(Operation.java:216)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)
java.io.IOException: Operation x10 on key(s) [3139364b3436374e3031]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (no host was tried)

        at org.apache.cassandra.stress.Operation.error(Operation.java:216)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)


3) Kill both Load 1 and Load 2, and start Load 1 again. Everything goes back to normal.

=================================  node status: 172.31.40.176
["172.31.40.176"]
=================================  perf status
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
==> bigperf.172.31.40.176.cpu0 <==
total,        326529,   48230,   48230,   48230,    18.1,     7.7,   107.9,   176.7,   324.6,   364.7,    7.1,  0.04333,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu12 <==
total,        580136,   68414,   68414,   68414,    13.2,    10.3,    29.6,    70.7,   102.7,   117.2,    8.9,  0.03623,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu16 <==
total,        540997,   73328,   73328,   73328,    12.2,     9.2,    29.6,    59.0,    85.5,    97.4,    7.8,  0.05849,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu20 <==
total,        500553,   72742,   72742,   72742,    12.3,    10.6,    25.7,    34.7,    75.4,    90.3,    8.4,  0.06993,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu24 <==
total,        484517,   68376,   68376,   68376,    13.2,    10.2,    29.4,    65.3,   181.2,   204.3,    7.7,  0.02235,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu28 <==
total,        490128,   67345,   67345,   67345,    13.6,     9.9,    35.2,    71.8,   187.5,   230.5,    8.0,  0.03993,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu4 <==
total,        510337,   68925,   68925,   68925,    13.0,     9.7,    30.6,    93.9,   117.8,   131.4,    7.9,  0.03388,      0,      0,       0,       0,       0,       0

==> bigperf.172.31.40.176.cpu8 <==
total,        499051,   68545,   68545,   68545,    13.2,    11.4,    26.7,    45.2,    88.8,    95.6,    8.0,  0.03645,      0,      0,       0,       0,       0,       0



for IP in $IP1;do
    echo === start cassandra-stress against $IP ===
    for CPU in `seq 0 4 31`; do
        CPULIST="$CPU,$((CPU+1)),$((CPU+2)),$((CPU+3))"
        echo Start cassandra-stress on $CPULIST
        logfile=bigperf.$IP.cpu$CPU
        taskset -c $CPULIST cassandra-stress write duration=90m $CL "keyspace=$KS" -mode native cql3 -rate threads=900 -node $IP -log file=$logfile >err.${logfile} 2>&1 &
    done
    sleep 2
done
```

**Comment by slivne** [comment]
@gleb-cloudius , @asias did we resolve this

**Comment by gleb-cloudius** [comment]
On Tue, Dec 15, 2015 at 05:25:26AM -0800, slivne wrote:
> @gleb-cloudius , @asias did we resolve this
> 
Hard to say, but this is likely what Glauber is fixing.

--
			Gleb.

**Comment by glommer** [comment]
Let's just keep in mind that one c3.x8large client is probably able to generate around 250k ops/sec or more for that C*-S command line. I have been using half the CPUs for loaders (m4), and could do 200k ops/sec. The first thing that strikes me as odd here is that the first client seem to be generating less than half of that. Something fishy on the client side, maybe?

The c3.x8large as a server will be able to handle between 400 and 600k ops/sec depending on the mood of its disks. So this might very well be a case in which the server really isn't able, simply put, to handle the load. (only hole here is that in the first loader seem to be generating a lot less than it would normally)

In any case, I will take a closer look.

**Comment by glommer** [comment]
Ok.

I had some issues running our latest AMI, but then I remembered I had an old c3 VM around. It is still running Fedora, but I believe it shouldn't be an issue.

Also, I am configuring the I/O queues manually, but I am doing so with the recommended parameters for c3. So we may still have some lingering bugs if the AMI is, for any reason not set properly.

I have been running this for some 20 minutes, and I don't see any issue.

From what I understood, that seemed to happened right after the second loader would start. So I guess we're good here.

**Comment by glommer** [comment]
After one hour, everything is fine.

Since this bug dates back to September and a lot of work has been done in areas that were expected to fix this behavior, I would say this is fixed.

@asias please close this.
