### ISSUE TITLE
SSTables 3.x files with empty static row can't be output by sstabledump

### ISSUE THREAD

**Issue by argenet** [scylladb/scylla#3900]
Scylla version (or git commit hash): 2ebab69ce783b5693f7c0fe945179225b1c75841

Create the following SSTables in 'mc' format using Scylla:
```
CREATE TABLE empty_static_row (pk int, ck int, st int static, rc int, PRIMARY KEY (pk, ck)) WITH compression = {'sstable_compression': ''};
INSERT INTO empty_static_row (pk, ck, rc) VALUES ( 0, 1, 2);
<<flush>>

```

And then try to output the resulting file using `sstabledump`. It will fail with:
```
[
  {
    "partition" : {
      "key" : [ "0" ],
      "position" : 0
    }
  }
]Exception in thread "main" java.lang.AssertionError: 36
	at org.apache.cassandra.db.rows.UnfilteredSerializer.deserializeStaticRow(UnfilteredSerializer.java:560)
	at org.apache.cassandra.io.sstable.SSTableSimpleIterator$CurrentFormatIterator.readStaticRow(SSTableSimpleIterator.java:88)
	at org.apache.cassandra.io.sstable.SSTableIdentityIterator.<init>(SSTableIdentityIterator.java:49)
	at org.apache.cassandra.io.sstable.SSTableIdentityIterator.create(SSTableIdentityIterator.java:59)
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner$KeyScanningIterator$1.initializeIterator(BigTableScanner.java:384)
	at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.maybeInit(LazilyInitializedUnfilteredRowIterator.java:48)
	at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.partitionLevelDeletion(LazilyInitializedUnfilteredRowIterator.java:81)
	at org.apache.cassandra.tools.JsonTransformer.serializePartition(JsonTransformer.java:191)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.apache.cassandra.tools.JsonTransformer.toJson(JsonTransformer.java:101)
	at org.apache.cassandra.tools.SSTableExport.main(SSTableExport.java:240)
```

This happens because Scylla doesn't track filled columns like Cassandra does.

In Cassandra's memtable, all updates are tracked so that updated columns are known and the set of updated columns (which can be a subset of all columns in schema) is stored in serialization header. 
Refer to https://github.com/scylladb/scylla/wiki/SSTables-3.0-Data-File-Format#row for more details.
In particular, that means that if there are static columns in schema but they are not filled in memtable mutations, Cassandra will not write the static column to the serialization header but Scylla will.

When reading SSTables, Cassandra (and `sstabledump` in particular) check the serialization header to see if it has static columns and based on that decides whether it should expect a static row to be present or not. That means Scylla's SSTables are confusing because break this logic.

We need to track the inserted/updated columns inside a memtable too and use the resulting set to write the serialization header.
Besides resolving the issue above, this will also somewhat reduce the size of data files because the information on missing columns will be now written based on actually filled ones, not on the entire set declared in schema, so `HAS_ALL_COLUMNS` flag will be used more often and indicate additional encoding is not needed.

**Comment by tgrabiec** [comment]
I don't understand this part:
```
Cassandra check the serialization header to see if it has static columns and based on that decides whether it should expect a static row to be present or not. 
```
If there is at least one partition with a static cell set, we need to add this column to the serialization header. But it doesn't mean that all partitions have static columns set. There still could be partitions with no static columns set. So how can Cassandra always expect it based on that?

**Comment by argenet** [comment]
Good question. It turns out Cassandra will write empty static rows for every partition in case if some partition has a non-empty one.

Here is the example:
```
cqlsh:sst3> CREATE TABLE empty_static_row2 (pk int, ck int, st int static, rc int, PRIMARY KEY (pk, ck)) WITH compression = {'sstable_compression': ''};
cqlsh:sst3> INSERT INTO empty_static_row2 (pk, ck, rc) VALUES ( 0, 1, 2);
cqlsh:sst3> INSERT INTO empty_static_row2 (pk, ck, st, rc) VALUES ( 1, 1, 2, 3);
cqlsh:sst3> quit
osboxes@osboxes:~$ nodetool flush
osboxes@osboxes:~$ sstabledump /var/lib/cassandra/data/sst3/empty_static_row2-47108b60dedf11e89f0475601744495f/mc-1-big-Data.db 
[
  {
    "partition" : {
      "key" : [ "1" ],
      "position" : 0
    },
    "rows" : [
      {
        "type" : "static_block",
        "position" : 48,
        "cells" : [
          { "name" : "st", "value" : 2, "tstamp" : "2018-11-02T20:39:06.835336Z" }
        ]
      },
      {
        "type" : "row",
        "position" : 48,
        "clustering" : [ 1 ],
        "liveness_info" : { "tstamp" : "2018-11-02T20:39:06.835336Z" },
        "cells" : [
          { "name" : "rc", "value" : 3 }
        ]
      }
    ]
  },
  {
    "partition" : {
      "key" : [ "0" ],
      "position" : 49
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 86,
        "clustering" : [ 1 ],
        "liveness_info" : { "tstamp" : "2018-11-02T20:38:51.000652Z" },
        "cells" : [
          { "name" : "rc", "value" : 2 }
        ]
      }
    ]
  }
]osboxes@osboxes:~$ hexdump -C /var/lib/cassandra/data/sst3/empty_static_row2-47108b60dedf11e89f0475601744495f/mc-1-big-Data.db 
00000000  00 04 00 00 00 01 7f ff  ff ff 80 00 00 00 00 00  |................|
00000010  00 00 a0 01 0a 00 00 e0  f1 9e 3c 00 00 00 02 24  |..........<....$|
00000020  00 00 00 00 01 0a 1f e0  f1 9e 3c 08 00 00 00 03  |..........<.....|
00000030  01 00 04 00 00 00 00 7f  ff ff ff 80 00 00 00 00  |................|
00000040  00 00 00 80 01 02 00 01  24 00 00 00 00 01 07 17  |........$.......|
00000050  00 08 00 00 00 02 01                              |.......|
00000057
```

**Comment by argenet** [comment]
The following bytes at position 0x00000044 are an empty static row:
`80 01 02 00 01`
The bytes mean:
`80` - flags (extended_flag set)
`01` - extended flags (is_static set)
`02` - the length of the current row
`00` - the length of the previous row (always set to zero for static rows for obvious reason)
`01` - the missing columns encoded

Notice that `sstabledump` silently ignores those empty static rows.
