### ISSUE TITLE
c-s error: ArrayIndexOutOfBoundsException / AssertionError

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3934]
*Installation details*
Scylla version (or git commit hash): 3.0.rc0-0.20181024.76ff2e5c3
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Problem occurred when enable_sstables_mc_format is both True and False.

```
cassandra-stress user profile=data_dir/sst3_schema.yaml  ops'(insert=3,read1=1,read2=1,update_static=1,update_ttl=1,update_diff1_ts=1,update_diff2_ts=1,update_same1_ts=1,update_same2_ts=1,alter_table=1,delete_row=0.1)' cl=QUORUM duration=10m
```

[sst3_schema.yaml.txt](https://github.com/scylladb/scylla/files/2606970/sst3_schema.yaml.txt)

```
******************** Stress Settings ********************
Command:
  Type: user
  Count: -1
  Duration: 10 MINUTES
  No Warmup: false
  Consistency Level: QUORUM
  Target Uncertainty: not applicable
  Command Ratios: {insert=3.0, read1=1.0, read2=1.0, update_static=1.0, update_ttl=1.0, update_diff1_ts=1.0, update_diff2_ts=1.0, update_same1_ts=1.0, update_same2_ts=1.0, alter_table=1.0, delete_row=0.1}
  Command Clustering Distribution: clustering=gaussian(1..10)
  Profile File: data_dir/sst3_schema.yaml
Rate:
  Auto: true
  Min Threads: 4
  Max Threads: 1000
Population:
  Distribution: Gaussian:  min=1,max=1000000,mean=500000.500000,stdev=166666.500000
  Order: ARBITRARY
  Wrap: false
Insert:
  Revisits: Uniform:  min=1,max=1000000
  Visits: Fixed:  key=1
  Row Population Ratio: Ratio: divisor=1.000000;delegate=Fixed:  key=1
  Batch Type: not batching
Errors:
  Ignore: false
  Tries: 10
Log:
  No Summary: false
  No Settings: false
  File: null
  Interval Millis: 1000
  Level: NORMAL
Mode:
  API: JAVA_DRIVER_NATIVE
  Connection Style: CQL_PREPARED
  CQL Version: CQL3
  Protocol Version: V4
  Username: null
  Password: null
  Auth Provide Class: null
  Max Pending Per Connection: 128
  Connections Per Host: 8
  Compression: NONE
Node:
  Nodes: [localhost]
  Is White List: false
  Datacenter: null
Schema:
  Keyspace: keyspace_sst3
  Replication Strategy: org.apache.cassandra.locator.SimpleStrategy
  Replication Strategy Pptions: {replication_factor=1}
  Table Compression: null
  Table Compaction Strategy: null
  Table Compaction Strategy Options: {}
Transport:
  factory=org.apache.cassandra.thrift.TFramedTransportFactory; truststore=null; truststore-password=null; keystore=null; keystore-password=null; ssl-protocol=TLS; ssl-alg=SunX509; store-type=JKS; ssl-ciphers=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA; 
Port:
  Native Port: 9042
  Thrift Port: 9160
  JMX Port: 7199
Send To Daemon:
  *not set*
Graph:
  File: null
  Revision: unknown
  Title: null
  Operation: USER
TokenRange:
  Wrap: false
  Split Factor: 1

******************** Profile ********************
  Keyspace Name: keyspace_sst3
  Keyspace CQL: 
***
CREATE KEYSPACE IF NOT EXISTS keyspace_sst3 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
***

  Table Name: user_with_ck
  Table CQL: 
***
CREATE TABLE IF NOT EXISTS user_with_ck (
  key blob,
  // Case sensitive column names
  //Md5 text,
  md5 text,
  email text,
  static_int int static,
  //short non-PK column names
  a blob,
  b text,
  c ascii,
  d varchar,
  e boolean,
  f inet,
  g int,
  // Case sensitive column names
  h bigint,
  //H bigint,
  char ascii,
  vchar varchar,
  finished boolean,
  osirisjson blob,
  ip inet,
  size int,
  imagebase bigint,
  small_num smallint,
  tiny_num tinyint,
  // todo: verify size of varint
  vint varint,
  decimal_num decimal,
  double_num double,
  float_num float,
  start_date date,
  start_time time,
  check_date timestamp,
  pass_date timestamp,
  upload_time timeuuid,
  user_uid uuid,
  //// name_tuple tuple<text>,
  name_set set<text>,
  name_list list<text>,
  //// map1 map<text,text>,
  //// map2 map<int,text>,
  //home_addr address,
  //// frozen_office_addr frozen<address>,
  //hash_bashname hash_and_basename,
  ////frozen_hash_bashname frozen<hash_and_basename>,
  //num counter,
  //PRIMARY KEY (key, md5, upload_time)
  PRIMARY KEY (key, md5)
  //PRIMARY KEY (key)
);
***

  Extra Schema Definitions: [CREATE TYPE IF NOT EXISTS hash_and_basename (md5 text, basename text);, CREATE TYPE IF NOT EXISTS address (street text, city text, zip_code int, phones set<text>, map1 map<text,text>, map2 map<int,text>);]
  Generator Configs:
    key: Size: Fixed:  key=10;
  Query Definitions:
    read1: CQL:select * from user_with_ck where key = ? LIMIT 1;Fields:null;
    read2: CQL:select * from user_with_ck where key = ? and md5 = ? LIMIT 1;Fields:null;
    update_static: CQL:update user_with_ck USING TTL 5 set static_int = ? where key = ?;Fields:null;
    update_ttl: CQL:update user_with_ck USING TTL 5 set check_date = ? where key = ? and md5 = ?;Fields:null;
    update_diff1_ts: CQL:update user_with_ck USING TIMESTAMP 10 set check_date = ? where key = ? and md5 = ?;Fields:null;
    update_diff2_ts: CQL:update user_with_ck USING TIMESTAMP 5 set pass_date = ? where key = ? and md5 = ?;Fields:null;
    update_same1_ts: CQL:update user_with_ck USING TIMESTAMP 10 set check_date = '2018-01-01T11:21:59.001+0000' where key = ? and md5 = ?;Fields:null;
    update_same2_ts: CQL:update user_with_ck USING TIMESTAMP 10 set pass_date = '2018-01-01T11:21:59.001+0000' where key = ? and md5 = ?;Fields:null;
    alter_table: CQL:ALTER TABLE user_with_ck WITH comment = 'updated';Fields:null;
    delete_row: CQL:delete from user_with_ck where key = ? and md5 = ?;Fields:null;
  Token Range Queries:
  Insert Settings:
    partitions: fixed(1)
    select: fixed(1)/1000
    batchtype: UNLOGGED
WARN  07:43:08,447 You listed localhost/0:0:0:0:0:0:0:1:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
Connected to cluster: , max pending requests per connection 128, max connections per host 8
Datatacenter: datacenter1; Host: localhost/127.0.0.1; Rack: rack1
Created schema. Sleeping 1s for propagation.
Created extra schema. Sleeping 1s for propagation.
Generating batches with [1..1] partitions and [0..0] rows (of [1..1] total rows in the partitions)

Sleeping 2s...
Warming up insert with 0 iterations...
Warming up read1 with 0 iterations...
Warming up read2 with 0 iterations...
Warming up update_static with 0 iterations...
Warming up update_ttl with 0 iterations...
Warming up update_diff1_ts with 0 iterations...
Warming up update_diff2_ts with 0 iterations...
Warming up update_same1_ts with 0 iterations...
Warming up update_same2_ts with 0 iterations...
Warming up alter_table with 0 iterations...
Warming up delete_row with 0 iterations...
Thread count was not specified

Running with 4 threadCount
Running [insert, read1, read2, update_static, update_ttl, update_diff1_ts, update_diff2_ts, update_same1_ts, update_same2_ts, alter_table, delete_row] with 4 threads 10 minutes
type       total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
java.lang.ArrayIndexOutOfBoundsException: 0
Exception in thread "Thread-1116" java.lang.AssertionError
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.fillRandom(SchemaQuery.java:112)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.bindArgs(SchemaQuery.java:121)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery$JavaDriverRun.run(SchemaQuery.java:74)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:85)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.run(SchemaQuery.java:158)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:468)
java.lang.ArrayIndexOutOfBoundsException: 0
Exception in thread "Thread-1117" java.lang.AssertionError
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.fillRandom(SchemaQuery.java:112)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.bindArgs(SchemaQuery.java:121)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery$JavaDriverRun.run(SchemaQuery.java:74)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:85)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.run(SchemaQuery.java:158)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:468)
java.lang.ArrayIndexOutOfBoundsException: 0
Exception in thread "Thread-1114" java.lang.AssertionError
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.fillRandom(SchemaQuery.java:112)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.bindArgs(SchemaQuery.java:121)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery$JavaDriverRun.run(SchemaQuery.java:74)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:85)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.run(SchemaQuery.java:158)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:468)
java.lang.ArrayIndexOutOfBoundsException: 0
Exception in thread "Thread-1115" java.lang.AssertionError
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.fillRandom(SchemaQuery.java:112)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.bindArgs(SchemaQuery.java:121)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery$JavaDriverRun.run(SchemaQuery.java:74)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:85)
	at org.apache.cassandra.stress.operations.userdefined.SchemaQuery.run(SchemaQuery.java:158)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:468)
insert,           40,      40,      40,      40,    11.3,     4.5,    89.9,    98.8,    98.8,    98.8,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
read1,             9,       9,       0,       0,     1.9,     2.1,     2.8,     2.8,     2.8,     2.8,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
read2,            26,      26,       0,       0,     6.8,     4.0,    10.2,    79.0,    79.0,    79.0,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
update_diff1_ts,         4,       4,       0,       0,     2.6,     2.1,     3.9,     3.9,     3.9,     3.9,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
update_diff2_ts,        20,      20,       0,       0,     2.4,     1.7,     5.6,     6.0,     6.0,     6.0,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
update_same1_ts,        19,      19,       0,       0,     2.0,     1.5,     3.9,     4.1,     4.1,     4.1,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
update_same2_ts,        22,      22,       0,       0,     1.9,     1.3,     4.5,     4.9,     4.9,     4.9,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
update_static,        25,      25,       0,       0,     2.7,     1.9,     6.0,     7.2,     7.2,     7.2,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
update_ttl,         8,       8,       0,       0,     1.5,     1.2,     2.6,     2.6,     2.6,     2.6,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
total,           173,     173,      40,      40,     5.0,     2.3,     8.2,    89.9,    98.8,    98.8,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
<c-s is stuck>
```

**Comment by slivne** [comment]
@amoskong - why 3.0.rc0 ?

can you please share some more info - if I run this on docker 3.0-rc1 will it reproduce ?

**Comment by amoskong** [comment]
Both c-s cmdline and profile were there, it can always be reproduced.
I did not try with docker, it will reproduce.

**Comment by amoskong** [comment]
I can reproduce this issue with 3.0.rc1-0.20181203.1953c5fa6

**Comment by elcallio** [comment]
fwiw, the assert means that somehow you are doing a query without any partition keys. Which should not be possible as far as I can read the code, but...

**Comment by slivne** [comment]
@amoskong the part that is causing the issue at least on docker for me is the alter_table part. if you drop that statement everything seems to work (afgain for me on 3.0 on docker)

alter_table - is the only one that is not using any info from a partition/row.

If I change the yaml and do the following

```
queries:
  read1:
    cql: select * from user_with_ck where key = ? LIMIT 1
    fields: samerow
  read2:
    cql: select * from user_with_ck where key = ? and md5 = ? LIMIT 1
    fields: samerow
  update_static:
    cql: update user_with_ck USING TTL 5 set static_int = ? where key = ?
    fields: samerow
  update_ttl:
    cql: update user_with_ck USING TTL 5 set check_date = ? where key = ? and md5 = ?
    fields: samerow
  update_diff1_ts:
    cql: update user_with_ck USING TIMESTAMP 10 set check_date = ? where key = ? and md5 = ?
    fields: samerow
  update_diff2_ts:
    cql: update user_with_ck USING TIMESTAMP 5 set pass_date = ? where key = ? and md5 = ?
    fields: samerow
  update_same1_ts:
    cql: update user_with_ck USING TIMESTAMP 10 set check_date = '2018-01-01T11:21:59.001+0000' where key = ? and md5 = ?
    fields: samerow
  update_same2_ts:
    cql: update user_with_ck USING TIMESTAMP 10 set pass_date = '2018-01-01T11:21:59.001+0000' where key = ? and md5 = ?
    fields: samerow
  alter_table:
    cql: ALTER TABLE user_with_ck WITH comment = 'updated'
    fields: samerow
  delete_row:
    cql: delete from user_with_ck where key = ? and md5 = ?
    fields: samerow
```

(adding ```fiels: samerow```)  everything works ok - please double check and close if this fixes your issue.

**Comment by amoskong** [comment]
The c-s error is solved by added `filelds: samerow` in schema file. Close this issue.
