### ISSUE TITLE
building from source on ubuntu fails with error in configure.py about missing jsoncpp.pc

### ISSUE THREAD

**Issue by ChrisCoxArt** [scylladb/scylla#3946]
*Installation details*
Scylla version (or git commit hash): downloaded head from git
Ubuntu currently under VirtualBox (will migrate once build and testing are successful)
following build directions from https://www.scylladb.com/download/#source

ccox@ccox-VirtualBox:~/scylla$ ./configure.py --mode=release
666.development-0.20181128.de17150cb
Notice: -fsanitize=vptr is broken, disabling; some debug mode tests are bypassed.
ninja: no work to do.
Package jsoncpp was not found in the pkg-config search path.
Perhaps you should add the directory containing `jsoncpp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'jsoncpp' found
Traceback (most recent call last):
  File "./configure.py", line 1043, in <module>
    args.user_cflags += " " + pkg_config("--cflags", "jsoncpp")
  File "./configure.py", line 99, in pkg_config
    output = subprocess.check_output(['pkg-config', option, package])
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pkg-config', '--cflags', 'jsoncpp']' returned non-zero exit status 1.

**Comment by tzach** [comment]
Hi @ChrisCoxArt what Ubuntu version are you using? if its Ubuntu 14 you might hitting https://github.com/scylladb/scylla/issues/3471

**Comment by ChrisCoxArt** [comment]
I'm on 18.0.4.1  (can't get 18.0.10 to upgrade yet).

**Comment by tzach** [comment]
@syuu1228 can you please take a look?

**Comment by ChrisCoxArt** [comment]
libjsoncpp 1.7..4-3 is installed

**Comment by tzach** [comment]
@ChrisCoxArt notes that you have ready packages for Ubuntu 18 here
https://www.scylladb.com/download/ubuntu-18-04/

**Comment by ChrisCoxArt** [comment]
Prebuilt packages make it difficult to profile the software (and near impossible to test fixes/performance tweaks).
Since Ubuntu is listed as a supported platform, I assumed the build was tested and would work on Ubuntu - but that does not appear to be the case at this time.

Please let me know when you have fixed and tested your build process.

**Comment by avikivity** [comment]
Try installing libjsoncpp-dev

**Comment by syuu1228** [comment]
@ChrisCoxArt If you are okay to build with 3.0 source code,  please try this:
```
git checkout branch-3.0
git submodule sync
git submodule update --init --recursive -f
./dist/debian/build_deb.sh --target xenial --dist
```
It will build scylla and generate .deb.
If you don't want use .deb, you'll need to refer dist/debian/build_deb.sh and files under dist/debian/.
There is no automate script to build without generating .deb package.

Build time requirement is basically listed on dist/debian/control.mustache, but it's templated in mustache format since dependency is different for each distribution.
Also we use ppa:scylladb/ppa to provide 3rdparty dependencies that is missing on Ubuntu repository.
But basically if you satisfied all dependencies and passed correct parameters to ./configure.py, it should able to build just launch "ninja" command.

On HEAD it's more complicated, we are trying to use one binary built on Fedora for all distributions, and providing a Docker image to build on other distributions: 
https://github.com/scylladb/scylla/commit/fd8eae50db1b273fc1cddc9c4897ab78eb1d107c
https://github.com/scylladb/scylla/commit/224c4c0b81f6956e09cfb0f49137bb743657d62a
But, again, it should able to build if you satisfied all dependencies, then should able to build with ./configure.py and ninja.

**Comment by ChrisCoxArt** [comment]
It sounds like you really need to update your documentation and compatibility lists to include the current status of your code (runs on many, only builds on one).

**Comment by syuu1228** [comment]
Since we switched our official way to build Scylla to [frozen toolchain](https://github.com/scylladb/scylladb/blob/master/HACKING.md#dependencies), we don't have this kind of dependency error because all dependencies and build toolchains are provided in the container.
Closing.
