### ISSUE TITLE
Crash in rpc streaming

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#4000]
*Installation details*
Scylla version (or git commit hash): 3.0-rc2

Segmentation fault with the trace:

```
#0  0x0000000000000000 in ?? ()
#1  0x0000000000882e1d in seastar::rpc::connection::stop_send_loop (this=0x60100dfc3c10) at rpc/rpc.cc:133
#2  0x0000000000884ee4 in seastar::rpc::client::<lambda(seastar::future<>)>::operator() (f=<error reading variable: access outside bounds of object referenced via synthetic pointer>, __closure=0x60100dc868b8) at rpc/rpc.cc:681
#3  seastar::futurize<seastar::future<> >::apply<seastar::rpc::client::client(const seastar::rpc::logger&, void*, seastar::rpc::client_options, seastar::socket, seastar::ipv4_addr, seastar::ipv4_addr)::<lambda(seastar::future<>)>, seastar::future<> >(<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x1e6fca5, DIE 0x23274c7>, <unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x1e6fca5, DIE 0x23274e7>) (
    func=func@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x1e6fca5, DIE 0x23274c7>, args#0=args#0@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x1e6fca5, DIE 0x23274e7>)
    at /usr/src/debug/scylla-3.0.rc2/seastar/core/future.hh:1399
#4  0x0000000000886e7a in seastar::future<>::<lambda(auto:2&&)>::operator()<seastar::future_state<> > (state=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x1e6fca5, DIE 0x2070e0f>, __closure=0x60100dc86898)
    at /usr/src/debug/scylla-3.0.rc2/seastar/core/future.hh:1004
#5  seastar::continuation<seastar::future<T>::then_wrapped(Func&&) [with Func = seastar::rpc::client::client(const seastar::rpc::logger&, void*, seastar::rpc::client_options, seastar::socket, seastar::ipv4_addr, seastar::ipv4_addr)::<lambda(seastar::future<>)>; Result = seastar::future<>; T = {}]::<lambda(auto:2&&)> >::run_and_dispose(void) (this=0x60100dc86880) at /usr/src/debug/scylla-3.0.rc2/seastar/core/future.hh:414
#6  0x00000000005a040f in seastar::reactor::run_tasks (this=this@entry=0x601000020000, tq=...) at core/reactor.cc:2694
#7  0x00000000005a05d2 in seastar::reactor::run_some_tasks (this=this@entry=0x601000020000) at core/reactor.cc:3117
#8  0x000000000066ec68 in seastar::reactor::run_some_tasks (this=0x601000020000) at /usr/src/debug/scylla-3.0.rc2/seastar/util/log.hh:313
#9  seastar::reactor::run (this=0x601000020000) at core/reactor.cc:3264
#10 0x00000000006733db in seastar::smp::<lambda()>::operator()(void) const (__closure=0x6000000ed2c0) at core/reactor.cc:4333
#11 0x000000000075646e in std::function<void ()>::operator()() const (this=<optimized out>) at /opt/scylladb/include/c++/7/bits/std_function.h:706
#12 seastar::posix_thread::start_routine (arg=<optimized out>) at core/posix.cc:52
#13 0x00007f8df6adddd5 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f8df6806ead in clone () from /lib64/libc.so.6

```

Connection seams to be a stream:

```
(gdb) print _is_stream
$25 = true
```

Code that fails is at line 133:

```
129       future<> connection::stop_send_loop() {
130           _error = true;
131           if (_connected) {
132               _outgoing_queue_cond.broken();
133               _fd.shutdown_output();
134           }
```
But _fd object is not null!:

```
(gdb) print _fd
$26 = {
  _csi = std::unique_ptr<seastar::net::connected_socket_impl> containing 0x601009e3a3f0
}
```

**Comment by gleb-cloudius** [comment]
dup of #4004
