### ISSUE TITLE
coredump in restart_then_repair_node & enospc nemesis

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4004]
*Installation details*
Scylla version (or git commit hash): 3.0.rc2-0.20181213.6b011fbe0
Cluster size: 6 db_nodes, 2 loaders
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0441d73b099ec2c23

* Jenkins job:
http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-test/label=aws-scylla-qa-builder1/14/

* Backtraces:
I found two kinds of backtrace in jobs, different error but same backtrace.

1. Backtrace in first restart_then_repair_node (nemesis finished without error)

```
2018-12-13 09:37:02,504 remote           L0194 DEBUG| [54.89.105.104] [stdout] Dec 13 09:37:01 warning|  [shard 12] sstable - Unable to delete /var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/la-208-big-TOC.txt because it
 doesn't exist.
2018-12-13 09:37:02,504 remote           L0194 DEBUG| [54.89.105.104] [stdout] Dec 13 09:37:01 err    |  [shard 8] sstable - Could not create SSTable component /var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/la-176-big-Data.db
. Found exception: std::experimental::filesystem::v1::filesystem_error (error system:2, No such file or directory)
2018-12-13 09:37:02,504 remote           L0194 DEBUG| [54.89.105.104] [stdout] Dec 13 09:37:01 err    |  [shard 8] sstable - Could not create SSTable component /var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/la-176-big-Index.d
b. Found exception: std::experimental::filesystem::v1::filesystem_error (error system:2, No such file or directory)
2018-12-13 09:37:02,504 remote           L0194 DEBUG| [54.89.105.104] [stdout] Dec 13 09:37:01 warning|  [shard 8] seastar - Exceptional future ignored: std::experimental::filesystem::v1::filesystem_error (error system:2, No such file or directory), backtrace:   0x7cc428
2018-12-13 09:37:02,505 remote           L0194 DEBUG| [54.89.105.104] [stdout]   0x5a1874
2018-12-13 09:37:02,505 remote           L0194 DEBUG| [54.89.105.104] [stdout]   0x1985df3
2018-12-13 09:37:02,505 remote           L0194 DEBUG| [54.89.105.104] [stdout]   0x18b7e9c
2018-12-13 09:37:02,505 remote           L0194 DEBUG| [54.89.105.104] [stdout]   0x5a016e
2018-12-13 09:37:02,505 remote           L0194 DEBUG| [54.89.105.104] [stdout]   0x5a0331
2018-12-13 09:37:02,505 remote           L0194 DEBUG| [54.89.105.104] [stdout]   0x66e9c7
2018-12-13 09:37:02,505 remote           L0194 DEBUG| [54.89.105.104] [stdout]   0x67313a
2018-12-13 09:37:02,505 remote           L0194 DEBUG| [54.89.105.104] [stdout]   0x7561cd
2018-12-13 09:37:02,506 remote           L0194 DEBUG| [54.89.105.104] [stdout]   /lib64/libpthread.so.0+0x7dd4
2018-12-13 09:37:02,506 remote           L0194 DEBUG| [54.89.105.104] [stdout]   /lib64/libc.so.6+0xfdeac                                                                                                        
```

2. Backtrace in ENOSPC nemesis:

```
2018-12-13 11:28:04,913 remote           L0194 DEBUG| [18.212.57.62] [stdout] Dec 13 11:28:04 err    |  [shard 12] commitlog - Failed to flush commits to disk: storage_io_error (Storage I/O error: 28: No space left on device)
2018-12-13 11:28:04,917 remote           L0194 DEBUG| [18.212.57.62] [stdout] Dec 13 11:28:04 err    |  [shard 1] commitlog - Failed to persist commits to disk for CommitLog-1-18014398514448982.log: storage_io_error (Storage I/O error: 28: No space left 
on device)
2018-12-13 11:28:04,921 remote           L0194 DEBUG| [18.212.57.62] [stdout] Dec 13 11:28:04 warning|  [shard 1] seastar - Exceptional future ignored: storage_io_error (Storage I/O error: 28: No space left on device), backtrace:   0x7cc428
2018-12-13 11:28:04,921 remote           L0194 DEBUG| [18.212.57.62] [stdout]   0x5a1874
2018-12-13 11:28:04,922 remote           L0194 DEBUG| [18.212.57.62] [stdout]   0x2aef530
2018-12-13 11:28:04,922 remote           L0194 DEBUG| [18.212.57.62] [stdout]   0x5a016e
2018-12-13 11:28:04,922 remote           L0194 DEBUG| [18.212.57.62] [stdout]   0x5a0331
2018-12-13 11:28:04,922 remote           L0194 DEBUG| [18.212.57.62] [stdout]   0x66e9c7
2018-12-13 11:28:04,922 remote           L0194 DEBUG| [18.212.57.62] [stdout]   0x67313a
2018-12-13 11:28:04,922 remote           L0194 DEBUG| [18.212.57.62] [stdout]   0x7561cd
2018-12-13 11:28:04,922 remote           L0194 DEBUG| [18.212.57.62] [stdout]   /lib64/libpthread.so.0+0x7dd4
2018-12-13 11:28:04,923 remote           L0194 DEBUG| [18.212.57.62] [stdout]   /lib64/libc.so.6+0xfdeac
```

* Uploaded Coredump files: (scylla employee only)
https://console.cloud.google.com/storage/browser/upload.scylladb.com/core.scylla.996.7b024e1419424f10bc2afc1c2dd13c5f.32916.1544701613000000.gz/?project=upload-179716&authuser=0

```
2018-12-13 11:49:49,983 cluster          L0593 DEBUG| Node longevity-10gb-3h-2.3-db-node-f26a703b-5 [18.212.57.62 | 172.30.0.95] (seed: None): Found coredump file: /var/lib/systemd/coredump/core.scylla.996.7b024e1419424f10bc2afc1c2dd13c5f.32916.154470161
3000000
2018-12-13 11:53:19,242 cluster          L0545 INFO | Node longevity-10gb-3h-2.3-db-node-f26a703b-5 [18.212.57.62 | 172.30.0.95] (seed: None): You can download it by https://storage.cloud.google.com/upload.scylladb.com/core.scylla.996.7b024e1419424f10bc2afc1c2dd13c5f.32916.1544701613000000.gz/core.scylla.996.7b024e1419424f10bc2afc1c2dd13c5f.32916.1544701613000000.gz.ab (available for ScyllaDB employee)
2018-12-13 11:53:19,242 cluster          L0601 INFO | Node longevity-10gb-3h-2.3-db-node-f26a703b-5 [18.212.57.62 | 172.30.0.95] (seed: None): To join coredump pieces, you may use: 'cat core.scylla.996.7b024e1419424f10bc2afc1c2dd13c5f.32916.1544701613000000.gz.* > core.scylla.996.7b024e1419424f10bc2afc1c2dd13c5f.32916.1544701613000000.gz'
:            PID: 32916 (scylla)
:            UID: 996 (scylla)
:            GID: 1001 (scylla)
:         Signal: 6 (ABRT)
:      Timestamp: Thu 2018-12-13 11:46:53 UTC (2min 56s ago)
:   Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15
:     Executable: /usr/bin/scylla
:  Control Group: /
:        Boot ID: 7b024e1419424f10bc2afc1c2dd13c5f
:     Machine ID: df877a200226bc47d06f26dae0736ec9
:       Hostname: ip-172-30-0-95.ec2.internal
:       Coredump: /var/lib/systemd/coredump/core.scylla.996.7b024e1419424f10bc2afc1c2dd13c5f.32916.1544701613000000
:        Message: Process 32916 (scylla) of user 996 dumped core.
:                 
:                 Stack trace of thread 32923:
:                 #0  0x00007fb6f444f207 raise (libc.so.6)
:                 #1  0x00007fb6f4450a38 abort (libc.so.6)
:                 #2  0x00007fb6f4448026 __assert_fail_base (libc.so.6)
:                 #3  0x00007fb6f44480d2 __assert_fail (libc.so.6)
:                 #4  0x00000000008dcdae _ZN7seastar13output_streamIcED4Ev (scylla)
:                 #5  0x00000000032798ca _ZN7seastar3rpc6clientD4Ev (scylla)
:                 #6  0x00000000031ed247 _ZN7seastar10shared_ptrINS_3rpc10connectionEED4Ev (scylla)
:                 #7  0x0000000003868b41 _ZN7seastar10shared_ptrINS_3rpc4sinkIJ24frozen_mutation_fragmentEE4implEED4Ev (scylla)
:                 #8  0x00000000005a016f _ZN7seastar7reactor9run_tasksERNS0_10task_queueE (scylla)
:                 #9  0x00000000005a0332 _ZN7seastar7reactor14run_some_tasksEv (scylla)
:                 #10 0x000000000066e9c8 _ZN7seastar7reactor14run_some_tasksEv (scylla)
:                 #11 0x000000000067313b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
:                 #12 0x00000000007561ce _ZNKSt8functionIFvvEEclEv (scylla)
:                 #13 0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #14 0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32933:
:                 #0  0x00007fb6f47f46fd read (libpthread.so.0)
:                 #1  0x00000000006369e5 _ZN7seastar9file_desc4readEPvm (scylla)
:                 #2  0x00007fb6f7c98c9f n/a (libstdc++.so.6)
:                 #3  0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #4  0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32945:
:                 #0  0x00007fb6f47f46fd read (libpthread.so.0)
:                 #1  0x00000000006369e5 _ZN7seastar9file_desc4readEPvm (scylla)
:                 #2  0x00007fb6f7c98c9f n/a (libstdc++.so.6)
:                 #3  0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #4  0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32939:
:                 #0  0x00007fb6f47f46fd read (libpthread.so.0)
:                 #1  0x00000000006369e5 _ZN7seastar9file_desc4readEPvm (scylla)
:                 #2  0x00007fb6f7c98c9f n/a (libstdc++.so.6)
:                 #3  0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #4  0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32934:
:                 #0  0x00007fb6f47f46fd read (libpthread.so.0)
:                 #1  0x00000000005a126d _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
:                 #2  0x00000000005be712 operator() (scylla)
:                 #3  0x00000000007561ce _ZNKSt8functionIFvvEEclEv (scylla)
:                 #4  0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #5  0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32949:
:                 #0  0x00007fb6f47f46fd read (libpthread.so.0)
:                 #1  0x00000000006369e5 _ZN7seastar9file_desc4readEPvm (scylla)
:                 #2  0x00007fb6f7c98c9f n/a (libstdc++.so.6)
:                 #3  0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #4  0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32941:
:                 #0  0x00007fb6f47f46fd read (libpthread.so.0)
:                 #1  0x00000000006369e5 _ZN7seastar9file_desc4readEPvm (scylla)
:                 #2  0x00007fb6f7c98c9f n/a (libstdc++.so.6)
:                 #3  0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #4  0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32918:
:                 #0  0x00007fb6f45170e7 epoll_pwait (libc.so.6)
:                 #1  0x00000000005c89ae _ZN7seastar21reactor_backend_epoll16wait_and_processEiPK10__sigset_t (scylla)
:                 #2  0x000000000059b9a5 _ZN7seastar7reactor9poll_onceEv (scylla)
:                 #3  0x000000000066e8f7 _ZNKSt8functionIFbvEEclEv (scylla)
:                 #4  0x000000000067313b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
:                 #5  0x00000000007561ce _ZNKSt8functionIFvvEEclEv (scylla)
:                 #6  0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #7  0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32942:
:                 #0  0x00007fb6f47f46fd read (libpthread.so.0)
:                 #1  0x00000000006369e5 _ZN7seastar9file_desc4readEPvm (scylla)
:                 #2  0x00007fb6f7c98c9f n/a (libstdc++.so.6)
:                 #3  0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #4  0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32951:
:                 #0  0x00007fb6f47f46fd read (libpthread.so.0)
:                 #1  0x00000000006369e5 _ZN7seastar9file_desc4readEPvm (scylla)
:                 #2  0x00007fb6f7c98c9f n/a (libstdc++.so.6)
:                 #3  0x00007fb6f47eddd5 start_thread (libpthread.so.0)
:                 #4  0x00007fb6f4516ead __clone (libc.so.6)
:                 
:                 Stack trace of thread 32931:
:                 #0  0x00007fb6f47f46fd read (libpthread.so.0)
:                 #1  0x00000000006369e5 _ZN7seastar9file_desc4r
```

**Comment by amoskong** [comment]
Comment from @roydahan in email:
```
Amos, I think I see the same issue in longevity-200GB-48h…
It seems like durinHardReboot Nemesis on "2018-12-15 10:25” when the node starts after reboot there is streamind (I'm not sure why).
Then, at somepoint we get FS error on one node (although we should have plenty of space), and the segmentation fault (on another node!) with the gollowing backtrace:

 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 warning|  [shard 12] storage_service - Shutting down communications due to I/O errors until operator intervention
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 warning|  [shard 12] storage_service - Disk error: std::system_error (error system:28, No space left on device)
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] storage_service - Stop transport: starts
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] gossip - My status = hibernate
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 warning|  [shard 0] gossip - No local state or state is in silent shutdown, not announcing shutdown
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] storage_service - Stop transport: stop_gossiping done
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] storage_service - messaging_service stopped
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] storage_service - Stop transport: shutdown messaging_service done
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 warning|  [shard 0] stream_session - [Stream #ede675e1-0053-11e9-8f6c-000000000008] Streaming plan for Bootstrap-keyspace1-index-0 failed, peers={172.16.99.250}, tx=0 KiB, 0.0

 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 warning|  [shard 0] stream_session - [Stream #ede675e0-0053-11e9-8f6c-000000000008] Streaming plan for Bootstrap-keyspace1-index-0 failed, peers={172.16.99.173}, tx=0 KiB, 0.0

 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] storage_service - stream_manager stopped
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] storage_service - Stop transport: shutdown stream_manager done
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 warning|  [shard 0] range_streamer - Bootstrap with 172.16.99.250 for keyspace=keyspace1 failed, took 40.111 seconds: streaming::stream_exception (Stream failed)
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 warning|  [shard 0] range_streamer - Bootstrap with 172.16.99.173 for keyspace=keyspace1 failed, took 40.111 seconds: streaming::stream_exception (Stream failed)
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 warning|  [shard 0] range_streamer - Bootstrap failed, took 45 seconds, nr_ranges_remaining=777
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 warning|  [shard 0] range_streamer - Bootstrap failed to stream. Will retry in 60 seconds ...
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] storage_service - Stop transport: auth shutdown
 L0194 DEBUG| [172.16.99.234] [stdout] Dec 15 10:27:28 info   |  [shard 0] storage_service - Stop transport: done
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | Segmentation fault on shard 11.
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | Backtrace:
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x00000000006a7692
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x00000000005bedbc
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x00000000005bf065
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x00000000005bf0b3
 L0194 DEBUG| [172.16.99.137] [stdout] java.io.IOException: Operation x0 on key(s) [323738504b3531304c30]: Data returned was not validated
 L0194 DEBUG| [172.16.99.137] [stdout]
 L0194 DEBUG| [172.16.99.137] [stdout]  at org.apache.cassandra.stress.Operation.error(Operation.java:136)
 L0194 DEBUG| [172.16.99.137] [stdout]  at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:114)
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | /lib64/libpthread.so.0+0x000000000000f5cf
 L0194 DEBUG| [172.16.99.137] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x0000000000884b20
 L0194 DEBUG| [172.16.99.137] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
 L0194 DEBUG| [172.16.99.137] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x0000000000886bd9
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x00000000005a016e
 L0194 DEBUG| [172.16.99.137] [stdout]  at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:468)
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x00000000005a0331
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x000000000066e9c7
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x000000000067313a
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | 0x00000000007561cd
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | /lib64/libpthread.so.0+0x0000000000007dd4
 L0194 DEBUG| [172.16.99.250] [stdout] Dec 15 10:27:28 info   | /lib64/libc.so.6+0x00000000000fdeac
```

**Comment by amoskong** [comment]
It occurred after instance restart. When RAID setup finished, try to restart the scylla-server service, then the error occurred.

```
## start nemesis
2018-12-13 09:34:49,866 nemesis          L0213 INFO | sdcm.nemesis.ChaosMonkey: RestartThenRepairNode Node longevity-10gb-3h-2.3-db-node-f26a703b-2 [3.80.208.24 | 172.30.0.216] (seed: False)

## stop, start instance

## c-s error?
2018-12-13 09:34:54,464 remote           L0194 DEBUG| [34.238.235.149] [stderr] ERROR 09:34:54,459 Unexpected error while querying ip-172-30-0-216.ec2.internal/172.30.0.216
2018-12-13 09:34:54,465 remote           L0194 DEBUG| [34.238.235.149] [stderr] com.datastax.driver.core.exceptions.TransportException: [ip-172-30-0-216.ec2.internal/172.30.0.216:9042] Connection has been closed
2018-12-13 09:34:54,466 remote           L0194 DEBUG| [34.238.235.149] [stderr]         at com.datastax.driver.core.Connection$ConnectionCloeFuture.force(Connection.java:1227) [cassandra-driver-core-3.5.1-shaded.jar:na]

## instance got new IP
2018-12-13 09:35:52,901 cluster_aws      L0348 DEBUG| Node longevity-10gb-3h-2.3-db-node-f26a703b-2 [3.80.208.24 | 172.30.0.216] (seed: None): Got new public IP 54.89.105.104
2018-12-13 09:35:52,901 remote           L0895 DEBUG| Remote [centos@3.80.208.24]: Running 'sudo /usr/lib/scylla/scylla-ami/scylla_create_devices'
....
2018-12-13 09:37:02,443 remote           L0194 DEBUG| [54.89.105.104] [stdout] Dec 13 09:36:50 info   | Writing '4096' to /proc/sys/net/ipv4/tcp_max_syn_backlog

## stop, start scylla-server
2018-12-13 09:37:02,443 remote           L0194 DEBUG| [54.89.105.104] [stdout] Dec 13 09:36:52 info   | Scylla version 3.0.rc2-0.20181213.6b011fbe0 starting ..

## target node raised error, and backtrace
2018-12-13 09:37:02,504 remote           L0194 DEBUG| [54.89.105.104] [stdout] Dec 13 09:37:01 warning|  [shard 8] seastar - Exceptional future ignored: std::experimental::filesystem::v1::filesystem_error (error system:2, No such file or directory), backtrace:   0x7cc428

## wait db up

## repair
```

**Comment by amoskong** [comment]
The two backtraces occurred in 3.0-rc4 longevity testing.

- 3.0.rc4-0.20190105.5a178ff63
- AMI: ami-0e1140edadd0fd57a

http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-mv-si-4days/label=aws-scylla-qa-builder3/15/  (jenkins job failed, but the job is still running in builder3)

Test dir: /home/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-mv-si-4days/label/aws-scylla-qa-builder3

Living monitor: http://184.73.0.179:3000/dashboard/db/scylla-per-server-metrics-nemesis-master?orgId=1&from=1546732234401&to=now&var-by=instance&var-dc=All&var-node=All&var-shard=All&refresh=30s

```
In decommission nemesis:
2019-01-06 21:16:47 [172.30.0.19]  Jan 06 21:16:47 warning|  [shard 12] seastar - Exceptional future ignored: std::experimental::filesystem::v1::filesystem_error (error system:2, No such file or directory),      backtrace:   0x7cc418
2019-01-06 21:16:47 [172.30.0.19]    0x5a1864
2019-01-06 21:16:47 [172.30.0.19]    0x60fc82
2019-01-06 21:16:47 [172.30.0.19]    0x5a015e
2019-01-06 21:16:47 [172.30.0.19]    0x5a0321
2019-01-06 21:16:47 [172.30.0.19]    0x66e9b7
2019-01-06 21:16:47 [172.30.0.19]    0x67312a
2019-01-06 21:16:47 [172.30.0.19]    0x7561bd
2019-01-06 21:16:47 [172.30.0.19]    /lib64/libpthread.so.0+0x7dd4
2019-01-06 21:16:47 [172.30.0.19]    /lib64/libc.so.6+0xfdeac


In enospc nemesis: (is backtrace acceptable?)
2019-01-08 09:38:28 [172.30.0.32]  Jan 08 09:38:28 warning|  [shard 4] seastar - Exceptional future ignored: storage_io_error (Storage I/O error: 28: No space left on device), backtrace:   0x7cc418
2019-01-08 09:38:28 [172.30.0.32]    0x5a1864
2019-01-08 09:38:28 [172.30.0.32]    0x2b0ea40
2019-01-08 09:38:28 [172.30.0.32]    0x5a015e
2019-01-08 09:38:28 [172.30.0.32]    0x5a0321
2019-01-08 09:38:28 [172.30.0.32]    0x66e9b7
2019-01-08 09:38:28 [172.30.0.32]    0x67312a
2019-01-08 09:38:28 [172.30.0.32]    0x7561bd
2019-01-08 09:38:28 [172.30.0.32]    /lib64/libpthread.so.0+0x7dd4
2019-01-08 09:38:28 [172.30.0.32]    /lib64/libc.so.6+0xfdeac

In another decommission nemesis:
2019-01-08 10:18:15 [172.30.0.76]  Jan 08 10:18:15 warning|  [shard 3] seastar - Exceptional future ignored: std::experimental::filesystem::v1::filesystem_error (error system:2, No such file or directory),       backtrace:   0x7cc418
2019-01-08 10:18:15 [172.30.0.76]    0x5a1864
2019-01-08 10:18:15 [172.30.0.76]    0x60fc82
2019-01-08 10:18:15 [172.30.0.76]    0x5a015e
2019-01-08 10:18:15 [172.30.0.76]    0x5a0321
2019-01-08 10:18:15 [172.30.0.76]    0x66e9b7
2019-01-08 10:18:15 [172.30.0.76]    0x67312a
2019-01-08 10:18:15 [172.30.0.76]    0x7561bd
2019-01-08 10:18:15 [172.30.0.76]    /lib64/libpthread.so.0+0x7dd4
2019-01-08 10:18:15 [172.30.0.76]    /lib64/libc.so.6+0xfdeac
```

**Comment by roydahan** [comment]
@amoskong, please decode the backtraces and open them in a new issue.
You can mention it may be related to this issue.

@slivne FYI what I mentioned in the meeting (I thought the issue is still open).
