### ISSUE TITLE
Failure in changes_while_node_down_test

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#4013]
```
RUN TEST: concurrent_schema_changes_test.py:TestConcurrentSchemaChanges.changes_while_node_down_test
2018-12-21 09:15:23.838359 going to run tests sequentially
changes_while_node_down_test (concurrent_schema_changes_test.TestConcurrentSchemaChanges) ... 2018-12-21 09:15:23.839653 cluster ccm directory: /home/asias/.dtest/dtest-fEaTdG
2018-12-21 09:15:23.869139 changes_while_node_down_test()
2018-12-21 09:15:58.170701 Calling prepare_for_changes
2018-12-21 09:15:58.170817 prepare_for_changes() ns2
2018-12-21 09:16:03.543186 Calling node1.Stop strated
2018-12-21 09:16:06.649448 Calling node1.stop done
2018-12-21 09:16:08.651694 Calling make_schema_changes
2018-12-21 09:16:08.651819 make_schema_changes() ns2
ERROR

======================================================================
ERROR: changes_while_node_down_test (concurrent_schema_changes_test.TestConcurrentSchemaChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asias/src/cloudius-systems/scylla-dtest/concurrent_schema_changes_test.py", line 432, in changes_while_node_down_test
    self.make_schema_changes(session, namespace='ns2')
  File "/home/asias/src/cloudius-systems/scylla-dtest/concurrent_schema_changes_test.py", line 86, in make_schema_changes
    session.execute('USE ks_%s' % namespace)
  File "cassandra/cluster.py", line 2141, in cassandra.cluster.Session.execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
ConnectionShutdown: Connection to 127.0.0.1 is closed
-------------------- >> begin captured logging << --------------------
dtest: DEBUG:  - going to run tests sequentially
dtest: DEBUG: concurrent_schema_changes_test.TestConcurrentSchemaChanges.changes_while_node_down_testchanges_while_node_down_test - cluster ccm directory: /home/asias/.dtest/dtest-fEaTdG
dtest: DEBUG: concurrent_schema_changes_test.TestConcurrentSchemaChanges.changes_while_node_down_testchanges_while_node_down_test - changes_while_node_down_test()
cassandra.cluster: WARNING: Cluster.__init__ called with contact_points specified, but load-balancing policies are not specified in some ExecutionProfiles. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['127.0.0.2'], EPs without explicit LBPs = ('EXEC_PROFILE_DEFAULT',))
cassandra.cluster: DEBUG: Connecting to cluster, contact points: ['127.0.0.2']; protocol version: 4
cassandra.pool: DEBUG: Host 127.0.0.2 is now marked up
cassandra.cluster: DEBUG: [control connection] Opening new connection to 127.0.0.2
cassandra.connection: DEBUG: Not sending options message for new connection(139662017744656) to 127.0.0.2 because compression is disabled and a cql version was not specified
cassandra.connection: DEBUG: Sending StartupMessage on <LibevConnection(139662017744656) 127.0.0.2:9042>
cassandra.connection: DEBUG: Sent StartupMessage on <LibevConnection(139662017744656) 127.0.0.2:9042>
cassandra.io.libevreactor: DEBUG: Starting libev event loop
cassandra.connection: DEBUG: Got ReadyMessage on new connection (139662017744656) from 127.0.0.2
cassandra.cluster: DEBUG: [control connection] Established new connection <LibevConnection(139662017744656) 127.0.0.2:9042>, registering watchers and refreshing schema and topology
cassandra.cluster: DEBUG: [control connection] Refreshing node list and token map using preloaded results
cassandra.policies: INFO: Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host '127.0.0.2'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
cassandra.cluster: DEBUG: [control connection] Found new host to connect to: 127.0.0.1
cassandra.cluster: INFO: New Cassandra host <Host: 127.0.0.1 datacenter1> discovered
cassandra.cluster: DEBUG: Handling new host <Host: 127.0.0.1 datacenter1> and notifying listeners
cassandra.cluster: DEBUG: Done preparing queries for new host <Host: 127.0.0.1 datacenter1>
cassandra.pool: DEBUG: Host 127.0.0.1 is now marked up
cassandra.cluster: DEBUG: [control connection] Finished fetching ring info
cassandra.cluster: DEBUG: [control connection] Rebuilding token map due to topology changes
cassandra.cluster: DEBUG: Control connection created
cassandra.pool: DEBUG: Initializing connection for host 127.0.0.2
cassandra.pool: DEBUG: Initializing connection for host 127.0.0.1
cassandra.connection: DEBUG: Not sending options message for new connection(139661143599440) to 127.0.0.2 because compression is disabled and a cql version was not specified
cassandra.connection: DEBUG: Sending StartupMessage on <LibevConnection(139661143599440) 127.0.0.2:9042>
cassandra.connection: DEBUG: Sent StartupMessage on <LibevConnection(139661143599440) 127.0.0.2:9042>
cassandra.connection: DEBUG: Not sending options message for new connection(139661795030800) to 127.0.0.1 because compression is disabled and a cql version was not specified
cassandra.connection: DEBUG: Sending StartupMessage on <LibevConnection(139661795030800) 127.0.0.1:9042>
cassandra.connection: DEBUG: Sent StartupMessage on <LibevConnection(139661795030800) 127.0.0.1:9042>
cassandra.connection: DEBUG: Got ReadyMessage on new connection (139661143599440) from 127.0.0.2
cassandra.connection: DEBUG: Got ReadyMessage on new connection (139661795030800) from 127.0.0.1
cassandra.pool: DEBUG: Finished initializing connection for host 127.0.0.2
cassandra.cluster: DEBUG: Added pool for host 127.0.0.2 to session
dtest: DEBUG: concurrent_schema_changes_test.TestConcurrentSchemaChanges.changes_while_node_down_testchanges_while_node_down_test - Calling prepare_for_changes
dtest: DEBUG: concurrent_schema_changes_test.TestConcurrentSchemaChanges.changes_while_node_down_testchanges_while_node_down_test - prepare_for_changes() ns2
cassandra.pool: DEBUG: Finished initializing connection for host 127.0.0.1
cassandra.cluster: DEBUG: Added pool for host 127.0.0.1 to session
cassandra.connection: DEBUG: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'ks_ns2', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}, stream_id=-1)>
cassandra.cluster: DEBUG: Refreshing schema in response to schema change. {'keyspace': u'ks_ns2', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.connection: DEBUG: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'ks_ns2', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'cf_ns2'}, stream_id=-1)>
cassandra.cluster: DEBUG: Refreshing schema in response to schema change. {'keyspace': u'ks_ns2', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'cf_ns2'}
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.connection: DEBUG: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'ks_ns2', 'change_type': u'UPDATED', 'target_type': u'TABLE', u'table': u'cf_ns2'}, stream_id=-1)>
cassandra.connection: DEBUG: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'ks_ns2', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'index_ns2_index'}, stream_id=-1)>
cassandra.cluster: DEBUG: Refreshing schema in response to schema change. {'keyspace': u'ks_ns2', 'change_type': u'UPDATED', 'target_type': u'TABLE', u'table': u'cf_ns2'}
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.connection: DEBUG: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'ks_ns2', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'cf2_ns2'}, stream_id=-1)>
cassandra.cluster: DEBUG: Refreshing schema in response to schema change. {'keyspace': u'ks_ns2', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'cf2_ns2'}
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.connection: DEBUG: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'ks2_ns2', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}, stream_id=-1)>
cassandra.cluster: DEBUG: Refreshing schema in response to schema change. {'keyspace': u'ks2_ns2', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas mismatched, trying again
cassandra.cluster: DEBUG: [control connection] Schemas match
cassandra.cluster: DEBUG: [control connection] Waiting for schema agreement
cassandra.cluster: DEBUG: [control connection] Schemas match
dtest: DEBUG: concurrent_schema_changes_test.TestConcurrentSchemaChanges.changes_while_node_down_testchanges_while_node_down_test - Calling node1.Stop strated
cassandra.connection: DEBUG: Message pushed from server: <EventMessage(event_type=u'STATUS_CHANGE', trace_id=None, event_args={'change_type': u'DOWN', 'address': ('127.0.0.1', 9042)}, stream_id=-1)>
cassandra.io.libevreactor: DEBUG: Connection <LibevConnection(139661795030800) 127.0.0.1:9042> closed by server
cassandra.io.libevreactor: DEBUG: Closing connection (139661795030800) to 127.0.0.1
cassandra.io.libevreactor: DEBUG: Closed socket to 127.0.0.1
dtest: DEBUG: concurrent_schema_changes_test.TestConcurrentSchemaChanges.changes_while_node_down_testchanges_while_node_down_test - Calling node1.stop done
dtest: DEBUG: concurrent_schema_changes_test.TestConcurrentSchemaChanges.changes_while_node_down_testchanges_while_node_down_test - Calling make_schema_changes
dtest: DEBUG: concurrent_schema_changes_test.TestConcurrentSchemaChanges.changes_while_node_down_testchanges_while_node_down_test - make_schema_changes() ns2
cassandra.cluster: ERROR: Unexpected exception while handling result in ResponseFuture:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3746, in cassandra.cluster.ResponseFuture._set_result
    session._set_keyspace_for_all_pools(
  File "cassandra/cluster.py", line 2608, in cassandra.cluster.Session._set_keyspace_for_all_pools
    pool._set_keyspace_for_all_conns(keyspace, pool_finished_setting_keyspace)
  File "cassandra/pool.py", line 436, in cassandra.pool.HostConnection._set_keyspace_for_all_conns
    self._connection.set_keyspace_async(keyspace, connection_finished_setting_keyspace)
  File "cassandra/connection.py", line 879, in cassandra.connection.Connection.set_keyspace_async
    self.send_msg(query, request_id, process_result)
  File "cassandra/connection.py", line 465, in cassandra.connection.Connection.send_msg
    raise ConnectionShutdown("Connection to %s is closed" % self.host)
ConnectionShutdown: Connection to 127.0.0.1 is closed
--------------------- >> end captured logging << ---------------------
```

**Comment by asias** [comment]
[PATCH scylla] storage_service: Stop cql server before gossip

**Comment by slivne** [comment]
Its not a regression ... it should go into 3.1 only
