### ISSUE TITLE
mc format: sstabledump MarshalException: String didn't validate

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4040]
Seen over an sstable generated by database_test.

/tmp/tmpdir_aSZthI/ks/cf-264c03c00e7111e98233000000000000/snapshots/1546421474991-cf/mc-2-big-Data.db:
[
  {
    "partition" : {
      "key" : [ "\u0001\u0000\u0000\u0000" ],
      "position" : 0
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 23,
        "clustering" : [ "ck0000000000" ],
        "cells" : [
          { "name" : "v", "value" }
        ] }
    ] }
]Exception in thread "main" org.apache.cassandra.serializers.MarshalException: String didn't validate.
        at org.apache.cassandra.serializers.UTF8Serializer.validate(UTF8Serializer.java:35)
        at org.apache.cassandra.db.marshal.AbstractType.getString(AbstractType.java:128)
        at org.apache.cassandra.tools.JsonTransformer.serializeCell(JsonTransformer.java:444)
        at org.apache.cassandra.tools.JsonTransformer.serializeColumnData(JsonTransformer.java:378)
        at org.apache.cassandra.tools.JsonTransformer.serializeRow(JsonTransformer.java:282)
        at org.apache.cassandra.tools.JsonTransformer.serializePartition(JsonTransformer.java:217)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.apache.cassandra.tools.JsonTransformer.toJson(JsonTransformer.java:102)
        at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:251)
        at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)

**Comment by bhalevy** [comment]
[mc-2-big.zip](https://github.com/scylladb/scylla/files/2720552/mc-2-big.zip)

**Comment by haaawk** [comment]
Here's an error message obtained using sstabledump from the lastest 3.11 cassandra branch:
```
[haaawk@desktop cassandra]$ ./tools/bin/sstabledump ~/Downloads/mc-2-big/mc-2-big-Data.db 
WARN  10:54:41,518 The option crc_check_chance was deprecated as a compression option. You should specify it as a top-level table option instead
[
  {
    "partition" : {
      "key" : [ "\u0001\u0000\u0000\u0000" ],
      "position" : 0
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 1069,
        "clustering" : [ "ck0000000000" ],
        "cells" : [
          { "name" : "v", "value" }
        ] }
    ] }
]Exception in thread "main" java.lang.AssertionError: UTF-8 value contained non-utf8 characters: 
	at org.apache.cassandra.db.marshal.UTF8Type.toJSONString(UTF8Type.java:70)
	at org.apache.cassandra.tools.JsonTransformer.serializeCell(JsonTransformer.java:463)
	at org.apache.cassandra.tools.JsonTransformer.serializeColumnData(JsonTransformer.java:373)
	at org.apache.cassandra.tools.JsonTransformer.serializeRow(JsonTransformer.java:277)
	at org.apache.cassandra.tools.JsonTransformer.serializePartition(JsonTransformer.java:211)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.apache.cassandra.tools.JsonTransformer.toJson(JsonTransformer.java:101)
	at org.apache.cassandra.tools.SSTableExport.main(SSTableExport.java:240)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816)
	at org.apache.cassandra.utils.ByteBufferUtil.string(ByteBufferUtil.java:156)
	at org.apache.cassandra.db.marshal.UTF8Type.toJSONString(UTF8Type.java:66)
	... 16 more
```

**Comment by slivne** [comment]
@bhalevy / @haaawk we need to understand if this is a regression from 2.3 or not 

if we create the same schema and insert the same values on 2.3 does this reproduce ?

**Comment by haaawk** [comment]
I checked and the tool complains because it gets the following sequence of bytes that should be UTF-8 bytes.
```
00 b7 3c 00 10 60 00 00 00 0c 44 00 10 60 00 00 80 aa 34 06 10 60 00 00 fc 6b ff 6e 01 7f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00 69 a1 00 00 00 00 00 00 01 00 00 00 00 00 00 00 c0 75 49 06 10 60 00 00 01 00 00 00 00 00 00 00 a8 69 19 00 10 60 00 00 f8 44 58 d3 46 5a db 71 95 cf bb 7a 81 28 da 8c 01 00 00 00 00 00 00 80 e2 84 2c 5c ff ff ff 7f 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 e8 94 1e 04 00 00 00 00 40 d6 a3 00 10 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 01 00 00 00 00 00 00 1a 00 00 00 00 00 00 00 1a 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 10 60 00 00 d8 4c 76 bc 10 60 00 00 00 00 00 00 00 04 00 00 00 00 67 06 10 60 00 00 01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 10 60 00 00 d8 4c 76 bc 10 60 00 00 00 00 00 00 00 04 00 00 00 00 67 06 10 60 00 04 01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 10 60 00 00 d8 4c 76 bc 10 60 00 00 00 00 00 00 00 04 00 00 00 00 67 06 10 60 00 04 01 00 00 00 00 00 00 00 60 6d 00 00 00 00 00 00 01 00 00 00 00 00 00 00 d0 07 00 00 00 00 00 00 80 aa 34 06 10 60 00 00 80 aa 34 06 10 60 00 00 80 aa 34 06 10 60 00 00 00 00 00 00 00 00 00 00 10 3e 3c 00 10 60 00 00 10 3e 3c 00 10 60 00 00 00 00 00 00 00 00 00 00 00 00 b8 00 10 60 00 00 00 00 b8 00 10 60 00 00 00 00 00 00 00 00 02 00 08 cb 08 00 10 60 00 00 10 cb 08 00 10 60 00 00 10 cb 08 00 10 60 00 00 a8 ca 08 00 10 60 00 00 b0 ca 08 00 10 60 00 00 b0 ca 08 00 10 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00 00 00 00 80 e2 84 2c 5c 00 00 00 00 1a 00 00 00 00 00 00 00 1a 00 01 00 00 00 00 00 00 0c 63 6b 30 30 30 30 30 30 30 30 30 30 00 0e 04 01 00 0c 63 6b 30 30 30 30 30 30 30 30 30 30 00 0e 04 01 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 00 00 00 00 00 00 00 2a 3f 3c 00 10 60 00 00 ff ff ff ff ff ff ff 7f 00 f5 34 06 10 60 00 00 02 00 00 00 00 00 00 80 ff ff ff 7f 00 7f 00 00 e0 fd 67 06 ff ff ff 7f 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00 00 00 80 38 21 0b d7 41 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 d8 3f 3c 00 10 60 00 00 d8 3f 3c 00 10 60 00 00 00 00 00 00 00 00 00 00
```

**Comment by avikivity** [comment]
Patch is on the lost.
