### ISSUE TITLE
Setup optimization NIC and disk

### ISSUE THREAD

**Issue by fggarcia** [scylladb/scylla#4102]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.0-0.20190117.2d181da65
Cluster size: 14 instances (two datancer, 11-3)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04.5 LTS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= 4 hyperthreading= memory= 8 GB
Disks: (SSD/HDD, count) NVME 80Gb x1 EXT4

```
Do you want to enable Network Interface Card (NIC) and disk(s) optimization?
Yes - optimize the NIC queue and disks settings. Selecting Yes greatly improves performance. No - skip this step.
[YES/no]
ERROR: timed out. Your system can't be tuned until the issue is fixed.
Traceback (most recent call last):
  File "/usr/lib/scylla/scylla_sysconfig_setup", line 75, in <module>
    rps_cpus = out('{} --tune net --nic {} --get-cpu-mask'.format(perftune_base_command(), ifname))
  File "/usr/lib/scylla/scylla_util.py", line 280, in out
    return subprocess.check_output(cmd, shell=shell).strip().decode('utf-8')
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/scylla/perftune.py', '--tune', 'disks', '--dir', '/home/despegar/data/scylla/data', '--dir', '/home/despegar/data/scylla/commitlog', '--dir', '/home/despegar/data/scylla/hints', '--tune', 'net', '--nic', 'ens3', '--get-cpu-mask']' returned non-zero exit status 1
```

**Comment by glommer** [comment]
hello.

What is the output of running that command manually? 
```
/usr/lib/scylla/perftune.py --tune disks --dir /home/despegar/data/scylla/data --dir /home/despegar/data/scylla/commitlog --dir /home/despegar/data/scylla/hints --tune net --nic ens3 --get-cpu-mask
````

**Comment by glommer** [comment]
@vladzcloudius FYI

**Comment by fggarcia** [comment]
@glommer 
I don't know if correct but

/usr/lib/scylla/perftune.py --tune disks --dir /home/despegar/data/scylla/data --dir /home/despegar/data/scylla/commitlog --dir /home/despegar/data/scylla/hints --tune net --nic ens3 --get-cpu-mask
ERROR: timed out. Your system can't be tuned until the issue is fixed.

**Comment by vladzcloudius** [comment]
@fggarcia Could you, please, provide a little more info about the system where you see the issue: is it a VM or bare metal box? If VM - what kind of?
Please, try to see which HW causes the timeout: try to remove `--dir <DIR>` parameters one by one and if the error still persists - remove the `--tune disks` with the last `--dir <DIR>` pair.

**Comment by vladzcloudius** [comment]
@fggarcia Please run the following command and send us the output:
`python3 -m trace --trace /usr/lib/scylla/perftune.py --tune disks --dir /home/despegar/data/scylla/data --dir /home/despegar/data/scylla/commitlog --dir /home/despegar/data/scylla/hints --tune net --nic ens3 --get-cpu-mask`

**Comment by fggarcia** [comment]
@vladzcloudius https://www.dropbox.com/s/rpf5myph1gg7o05/output.txt?dl=0

**Comment by vladzcloudius** [comment]
@fggarcia Thanks. I see the issue.
A quick fix for you is to apply the following patch to perftune.py:
```
diff --git a/scripts/perftune.py b/scripts/perftune.py
index 50016215..554d9568 100755
--- a/scripts/perftune.py
+++ b/scripts/perftune.py
@@ -831,6 +831,8 @@ class DiskPerfTuner(PerfTunerBase):
         except urllib.error.URLError:
             # Non-AWS case
             pass
+        except:
+            pass
 
         # Sort IRQs for easier verification
         nvme_irqs.sort(key=lambda irq_num_str: int(irq_num_str))
```

I'll send a proper fix to 3.0 tree.

**Comment by vladzcloudius** [comment]
@fggarcia Could you, please, clarify what is the platform where you are running this, please?

**Comment by vladzcloudius** [comment]
@fggarcia The proper fix would be close to this:
```
diff --git a/scripts/perftune.py b/scripts/perftune.py
index 50016215..04759eab 100755
--- a/scripts/perftune.py
+++ b/scripts/perftune.py
@@ -831,6 +831,12 @@ class DiskPerfTuner(PerfTunerBase):
         except urllib.error.URLError:
             # Non-AWS case
             pass
+        except ConnectionError:
+            # Non-AWS case (failed to connect to 169.254.169.254)
+            pass
+        except TimeoutError:
+            # Non-AWS case (failed to connect to 169.254.169.254)
+            pass
 
         # Sort IRQs for easier verification
         nvme_irqs.sort(key=lambda irq_num_str: int(irq_num_str))
```

Could you, please, verify that this fixes an issue on your system, please?

**Comment by fggarcia** [comment]
@vladzcloudius 
I don't have root permission in any environment(now). This issue doesn't avoid that scylla start but I report it.

**Comment by vladzcloudius** [comment]
@fggarcia Ok. NP. Could you, please, elaborate about the platform/HW, please?

**Comment by fggarcia** [comment]
@vladzcloudius 
I don't have the exact information about HW.
The machine is a virtualization over openstack.

```
lspci -v
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
	Subsystem: Red Hat, Inc Qemu virtual machine
	Flags: fast devsel

00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
	Subsystem: Red Hat, Inc Qemu virtual machine
	Flags: medium devsel

00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II] (prog-if 80 [Master])
	Subsystem: Red Hat, Inc Qemu virtual machine
	Flags: bus master, medium devsel, latency 0
	[virtual] Memory at 000001f0 (32-bit, non-prefetchable) [size=8]
	[virtual] Memory at 000003f0 (type 3, non-prefetchable)
	[virtual] Memory at 00000170 (32-bit, non-prefetchable) [size=8]
	[virtual] Memory at 00000370 (type 3, non-prefetchable)
	I/O ports at c0a0 [size=16]
	Kernel driver in use: ata_piix

00:01.2 USB controller: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] (rev 01) (prog-if 00 [UHCI])
	Subsystem: Red Hat, Inc QEMU Virtual Machine
	Flags: bus master, fast devsel, latency 0, IRQ 11
	I/O ports at c040 [size=32]
	Kernel driver in use: uhci_hcd

00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
	Subsystem: Red Hat, Inc Qemu virtual machine
	Flags: medium devsel, IRQ 9

00:02.0 VGA compatible controller: Cirrus Logic GD 5446 (prog-if 00 [VGA controller])
	Subsystem: Red Hat, Inc QEMU Virtual Machine
	Flags: fast devsel
	Memory at fc000000 (32-bit, prefetchable) [size=32M]
	Memory at febd0000 (32-bit, non-prefetchable) [size=4K]
	Expansion ROM at febc0000 [disabled] [size=64K]
	Kernel modules: cirrusfb

00:03.0 Ethernet controller: Red Hat, Inc Virtio network device
	Subsystem: Red Hat, Inc Virtio network device
	Physical Slot: 3
	Flags: bus master, fast devsel, latency 0, IRQ 10
	I/O ports at c060 [size=32]
	Memory at febd1000 (32-bit, non-prefetchable) [size=4K]
	Expansion ROM at feb80000 [disabled] [size=256K]
	Capabilities: <access denied>
	Kernel driver in use: virtio-pci

00:04.0 SCSI storage controller: Red Hat, Inc Virtio block device
	Subsystem: Red Hat, Inc Virtio block device
	Physical Slot: 4
	Flags: bus master, fast devsel, latency 0, IRQ 11
	I/O ports at c000 [size=64]
	Memory at febd2000 (32-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: virtio-pci

00:05.0 Unclassified device [00ff]: Red Hat, Inc Virtio memory balloon
	Subsystem: Red Hat, Inc Virtio memory balloon
	Physical Slot: 5
	Flags: bus master, fast devsel, latency 0, IRQ 10
	I/O ports at c080 [size=32]
	Kernel driver in use: virtio-pci
```

**Comment by slivne** [comment]
Patch on ML: "[seastar-dev] [PATCH v1] perftune.py: don't let any exception out when connecting to AWS meta server"

**Comment by fggarcia** [comment]
Hi @vladzcloudius was this patch applied in 3.0.1?

**Comment by vladzcloudius** [comment]
@fggarcia It didn't unfortunately.

**Comment by vladzcloudius** [comment]
@slivne FYI ^^

**Comment by fggarcia** [comment]
@vladzcloudius Okey. Because i upgrade to 3.0.1 and issue still persist. No problem.
