### ISSUE TITLE
dtest mc_sstables_case_sensitive_update_value_test failed: res[0].count != data_amount

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4109]
Scylla version (or git commit hash): 02d88de082d2b2fdfc04c45f5583e7ce68476ad0
Dtest [#1004](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest/1004/label=scylla-dtest,mode=release,smp=2/testReport/)
```
FAIL: mc_sstables_case_sensitive_update_value_test (cql_additional_tests.TestCQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/urchin-dtest/cql_additional_tests.py", line 5106, in mc_sstables_case_sensitive_update_value_test
    dataset=dataset, data_amount=data_amount)
  File "/jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/urchin-dtest/cql_additional_tests.py", line 5049, in mc_prepare_table
    columns=columns, keys_columns_amount=2)
  File "/jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/urchin-dtest/cql_additional_tests.py", line 5207, in mc_validate_data
    self.assertEqual(res[0].count, data_amount)
AssertionError: 8 != 10
```

**Comment by slivne** [comment]
@bhalevy is this still happening - if not lets clsose and reopen wehn we see it

**Comment by bhalevy** [comment]
never reproduced, closing...
