### ISSUE TITLE
dtest offline_tools_test.TestOfflineTools.sstablelevelreset_test failed: Unknown column scylla_cpu_sharding_algorithm during deserialization

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4112]
Scylla version (or git commit hash): since [#965](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest/label=scylla-dtest,mode=release,smp=2/965/testReport/offline_tools_test/TestOfflineTools/sstablelevelreset_test/)
Probably  6a5d8934a61aed264051dfdbe62eef6118043b91 (db: Enable SSTables 'mc' format by default.)

```
Unexpected nodetool stderr: ERROR 04:36:11,571 Error in ThreadPoolExecutor
java.lang.RuntimeException: Unknown column scylla_cpu_sharding_algorithm during deserialization
	at org.apache.cassandra.db.SerializationHeader$Component.toHeader(SerializationHeader.java:321) ~[main/:na]
	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:522) ~[main/:na]
	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:385) ~[main/:na]
	at org.apache.cassandra.io.sstable.format.SSTableReader$3.run(SSTableReader.java:570) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81) [main/:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
ERROR 04:36:11,604 Error in ThreadPoolExecutor
java.lang.RuntimeException: Unknown column supported_features during deserialization
	at org.apache.cassandra.db.SerializationHeader$Component.toHeader(SerializationHeader.java:321) ~[main/:na]
	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:522) ~[main/:na]
	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:385) ~[main/:na]
	at org.apache.cassandra.io.sstable.format.SSTableReader$3.run(SSTableReader.java:570) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81) [main/:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]

-------------------- >> begin captured logging << --------------------
dtest: DEBUG: offline_tools_test.TestOfflineTools.sstablelevelreset_testsstablelevelreset_test - cluster ccm directory: /jenkins/.dtest/dtest-klr64A
--------------------- >> end captured logging << ---------------------

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/urchin-dtest/offline_tools_test.py", line 74, in sstablelevelreset_test
    self.verify_nodetool_stderr(error)
  File "/jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/urchin-dtest/offline_tools_test.py", line 47, in verify_nodetool_stderr
    "Unexpected nodetool stderr: %s" % error)
  File "/usr/lib64/python2.7/unittest/case.py", line 460, in assertTrue
    raise self.failureException(msg)
```

**Comment by slivne** [comment]
@bhalevy - this is urgent we need to understand why we fail - if we have an issue with mc

**Comment by glommer** [comment]
Can't we remove those columns? We added them in  system.local so that our shard-aware driver would work. But we eventually moved that to a message response and the system.local version is not used anymore. We never documented it, so maybe we can just go ahead and remove it.

**Comment by tgrabiec** [comment]
`supported_features` is used also internally (also in the `peers` table). We could move it. But if we don't need our system keyspace sstables to be portable (?), then it's easier to modify the tools.

**Comment by slivne** [comment]
so this is not mc related, or so it seems. 

The issue is that we are trying to be sure that drivers are able  to work with scylla and cassandra. since drivers reads system tables - if we have columns that we added, theoretically drivers (coded in a wrong way) can fail. 

supported features is an old filed (AFAIK) - so it should heva been an issue also in older releases (2.3) - why isn't it ?

**Comment by tgrabiec** [comment]
@slivne The tools open all sstables when initializing. MC-format sstables now have something called a serialization header, which is interpreted when sstable is opened. That's when the failure will happen. With LA-format sstables, we would fail only when trying to actually read from those sstables. That may explain why the dtest started to fail now.

**Comment by bhalevy** [comment]
@tgrabiec is the non-failure #2598 ?

**Comment by tgrabiec** [comment]
@bhalevy I don't understand the question, please elaborate.

**Comment by bhalevy** [comment]
Looking for an explanation why the dtest didn't fail in the past, #2598 calls for erring on unknown columns rather than ignoring them and it's fixed only for the mc format, so I asked if this could explain why the dtest didn't fail on older formats.

**Comment by tgrabiec** [comment]
@bhalevy No, because #2598 is only about changing the scylla server, while here it's the tools from scylla-tools-java which are erroring.

**Comment by bhalevy** [comment]
Discussed with @slivne. As a first step, let's fix the tools for 3.1.
Later on, consider moving these columns to scylla specific tables.

**Comment by slivne** [comment]
lets revert also @glommer patch bdce561ada2bc1deb11604152e1222dcebd47008 adding the three fields scylla_cpu_sharding_algorithm,scylla_nr_shards,scylla_msb_ignore if we do not need them.

**Comment by slivne** [comment]
@haaawk do we need these fields in the system tables for any reason ?

**Comment by haaawk** [comment]
@slivne They are used for shard-awareness support of the driver I believe

**Comment by slivne** [comment]
@haaawk they are not used by the drivers - the drivers are supposed to fetch them using the protocol extensions

https://github.com/scylladb/scylla/blob/master/docs/protocol-extensions.md

https://github.com/scylladb/java-driver/commit/7226d8b64e434669da87232a682dbe8cdc4a5560

**Comment by haaawk** [comment]
@slivne That's correct but isn't scylla taking the values that are returned to the driver from that tables?

**Comment by haaawk** [comment]
Maybe not but then why are those fields still there?

**Comment by haaawk** [comment]
Ok there are not used: https://github.com/scylladb/scylla/blob/master/transport/server.cc#L1124
so probably we can get rid of them.

**Comment by haaawk** [comment]
Should I just remove them?

**Comment by slivne** [comment]
Yep we should revert the patch from glauber ... in my view

**Comment by haaawk** [comment]
@glommer any objections?

**Comment by slivne** [comment]
once we do this we can postpone the fix of moving the left columns to a scylla table.

**Comment by bhalevy** [comment]
According to @haaawk 834bec5cc9e79eca487928e7b9bd77d751e0370a actually fixes this issue.  Closing.
