### ISSUE TITLE
Regression in connection time in Scylla 3 compared to Scylla 2.3.1

### ISSUE THREAD

**Issue by linux-wizard** [scylladb/scylla#4125]
*Installation details*
Scylla version (or git commit hash): 3.0.0-0.20190116.2d181da65
Cluster size: 12
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS Linux release 7.4.1708

*Hardware details (for performance issues)* 
Platform: physical
Hardware: sockets=2 cores=72 hyperthreading=yes memory=512GB
Disks: 3 * 2TB Intel(R) SSD DC P3600 NVMe

After i did a rolling online upgrade of Scylla 2.3.1 to Scylla 3.0, I noticed that some application could no longer connect to the Scylla 3.0 nodes.

We noticed that the application was using 300ms as default connect timeout. Increasing this value to 1000ms allows to fix the issue. However it should be noted this is a regression compared to Scylla 2.3.1 and Cassandra 2.1.19

relevant logs from Cassandra Java driver:
```
2019-01-21 18:21:28,172 DF DEBUG com.datastax.driver.core.Cluster - Starting new cluster with contact points [as-dfcas-3b01/10.46.163.21:9042, as-dfcas-3b02/10.46.163.22:9042, as-dfcas-3b04/10.46.163.24:9042, as-dfcas-3b07/10.46.163.27:9042, as-dfcas-3b08/10.46.163.28:9042]
2019-01-21 18:21:28,214 DF DEBUG com.datastax.driver.core.Host.STATES - [as-dfcas-3b08/10.46.163.28:9042] preparing to open 1 new connections, total = 1
2019-01-21 18:21:28,216 DF DEBUG com.datastax.driver.core.Host.STATES - [as-dfcas-3b08/10.46.163.28:9042] Connection[as-dfcas-3b08/10.46.163.28:9042-1, inFlight=0, closed=false] Transport initialized, connection ready
2019-01-21 18:21:28,217 DF DEBUG com.datastax.driver.core.ControlConnection - [Control connection] Refreshing node list and token map
2019-01-21 18:21:28,268 DF DEBUG com.datastax.driver.core.ControlConnection - [Control connection] Refreshing schema
2019-01-21 18:21:28,577 DF DEBUG com.datastax.driver.core.Host.STATES - [as-dfcas-3b08/10.46.163.28:9042] Connection[as-dfcas-3b08/10.46.163.28:9042-1, inFlight=0, closed=true] closed, remaining = 0
2019-01-21 18:21:28,578 DF DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on as-dfcas-3b08/10.46.163.28:9042 connection, trying next host
com.datastax.driver.core.exceptions.OperationTimedOutException: [as-dfcas-3b08/10.46.163.28:9042] Operation timed out
	at com.datastax.driver.core.DefaultResultSetFuture.onTimeout(DefaultResultSetFuture.java:209)
	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1380)
```

**Comment by linux-wizard** [comment]
No I'm not using authentication or encryption.

**Comment by linux-wizard** [comment]
@slivne Could the payload sent during init is bigger and so takes more time due to shard-awareness support?

**Comment by linux-wizard** [comment]
[as-propp-3y10-01.pcap.gz](https://github.com/scylladb/scylla/files/2782176/as-propp-3y10-01.pcap.gz)

**Comment by avikivity** [comment]
And, only the client->server packets are visible in the dump.

**Comment by linux-wizard** [comment]
@avikivity DataStax driver

I will try to have a new tcpdump tomorrow

**Comment by linux-wizard** [comment]
[as-dfcas-3b02_as-dfcas-3b01.pcap.gz](https://github.com/scylladb/scylla/files/2785847/as-dfcas-3b02_as-dfcas-3b01.pcap.gz)

@avikivity Here is another capture from Scylla cqlsh to 1 node in the cluster. I will try to prove later a capture from our scala application

**Comment by slivne** [comment]
@linux-wizard - 

I have check the first capture - its very partial, it only has packets from 10.146.173.76 to 10.46.163.21 and even that seems a subset - the driver has more queries then that.

We need a complete capture to check the response time of scylla for requests.

Looking at the second capture - there are 400ms between the query from system_schema.columns and the response. 

I am checking on my end if I can detect a change in response to this system level query between versions.

**Comment by slivne** [comment]
I was able to reproduce the issue (I think) on AWS i3.16x 

Using a ScyllaDB 3.0.0 (ami-0436905a94398b3db) / ScyllaDB 3.0.1 (ami-0e408f1b170700dd0) running the following 

```
cqlsh> paging off
cqlsh> tracing on
cqlsh> select * from system_schema.columns ;
.
.
.
Tracing session: 899a6990-1f00-11e9-bd55-000000000005

 activity                                       | timestamp                  | source     | source_elapsed | client
------------------------------------------------+----------------------------+------------+----------------+-----------
                             Execute CQL3 query | 2019-01-23 11:17:58.057000 | 10.0.0.188 |              0 | 127.0.0.1
                  Parsing a statement [shard 1] | 2019-01-23 11:17:58.057433 | 10.0.0.188 |             -- | 127.0.0.1
               Processing a statement [shard 1] | 2019-01-23 11:17:58.057486 | 10.0.0.188 |             53 | 127.0.0.1
          read_data: querying locally [shard 1] | 2019-01-23 11:17:58.057518 | 10.0.0.188 |             86 | 127.0.0.1
 Done processing - preparing a result [shard 1] | 2019-01-23 11:17:58.093488 | 10.0.0.188 |          36056 | 127.0.0.1
                               Request complete | 2019-01-23 11:17:58.093616 | 10.0.0.188 |          36616 | 127.0.0.1
```

and using ScyllaDB 2.3.1 (ami-0990366cdafebaa01) I get

```
cqlsh> paging off
cqlsh> tracing on
cqlsh> select * from system_schema.columns;
.
.
.
Tracing session: 2542d9f0-1f00-11e9-8a93-000000000005

 activity                                       | timestamp                  | source    | source_elapsed
------------------------------------------------+----------------------------+-----------+----------------
                             Execute CQL3 query | 2019-01-23 11:15:09.712000 | 10.0.0.34 |              0
                  Parsing a statement [shard 1] | 2019-01-23 11:15:09.712016 | 10.0.0.34 |             --
               Processing a statement [shard 1] | 2019-01-23 11:15:09.712058 | 10.0.0.34 |             42
          read_data: querying locally [shard 1] | 2019-01-23 11:15:09.712084 | 10.0.0.34 |             68
 Done processing - preparing a result [shard 1] | 2019-01-23 11:15:09.718249 | 10.0.0.34 |           6233
                               Request complete | 2019-01-23 11:15:09.718639 | 10.0.0.34 |           6639
```

working to get additional logs

**Comment by avikivity** [comment]
Maybe a regression in full scans of tiny tables on machines with tons of shards. @denesb ?

**Comment by slivne** [comment]
In an attempt to check if this is an issue with a sparsly populated table beeing queried.

I create a table with c-s and wrote 10 partitions and did a select count(*)

on Scylla 3.0.1
```
cqlsh> select count(*) from keyspace1.standard1 ;

 count
-------
    10

(1 rows)

Tracing session: ded10330-1f08-11e9-920a-000000000008

 activity                                       | timestamp                  | source    | source_elapsed | client
------------------------------------------------+----------------------------+-----------+----------------+-----------
                             Execute CQL3 query | 2019-01-23 12:17:36.995000 | 10.0.0.65 |              0 | 127.0.0.1
                  Parsing a statement [shard 5] | 2019-01-23 12:17:36.995938 | 10.0.0.65 |             -- | 127.0.0.1
               Processing a statement [shard 5] | 2019-01-23 12:17:36.996099 | 10.0.0.65 |            161 | 127.0.0.1
          read_data: querying locally [shard 5] | 2019-01-23 12:17:36.996645 | 10.0.0.65 |            708 | 127.0.0.1
 Done processing - preparing a result [shard 5] | 2019-01-23 12:17:37.009923 | 10.0.0.65 |          13985 | 127.0.0.1
                               Request complete | 2019-01-23 12:17:37.009302 | 10.0.0.65 |          14302 | 127.0.0.1
```

on Scylla 2.3.1
```
cqlsh> select count(*) from keyspace1.standard1 ;

 count
-------
    10

(1 rows)

Tracing session: e8d8c2f0-1f08-11e9-8b6b-000000000004

 activity                                       | timestamp                  | source    | source_elapsed
------------------------------------------------+----------------------------+-----------+----------------
                             Execute CQL3 query | 2019-01-23 12:17:53.823000 | 10.0.0.34 |              0
                  Parsing a statement [shard 1] | 2019-01-23 12:17:53.823024 | 10.0.0.34 |             --
               Processing a statement [shard 1] | 2019-01-23 12:17:53.823075 | 10.0.0.34 |             51
          read_data: querying locally [shard 1] | 2019-01-23 12:17:53.823390 | 10.0.0.34 |            367
 Done processing - preparing a result [shard 1] | 2019-01-23 12:17:53.827344 | 10.0.0.34 |           4320
                               Request complete | 2019-01-23 12:17:53.827331 | 10.0.0.34 |           4331
```

yet doing a multipartition in query on the keys returns results in ~the same latency.

on 2.3.1 
```
cqlsh> select key from keyspace1.standard1 where key in (0x36384b30374f33314c30, 0x37373539364d4f323330,0x50364d4e4d3850394f30,0x4f503030314c35393330) ;

 key
------------------------
 0x36384b30374f33314c30
 0x37373539364d4f323330
 0x4f503030314c35393330
 0x50364d4e4d3850394f30

(4 rows)

Tracing session: 317a0dc0-1f09-11e9-8b6b-000000000004

 activity                                                                                                                         | timestamp                  | source    | source_elapsed
----------------------------------------------------------------------------------------------------------------------------------+----------------------------+-----------+----------------
                                                                                                               Execute CQL3 query | 2019-01-23 12:19:55.676000 | 10.0.0.34 |              0
                                                                                                    Parsing a statement [shard 1] | 2019-01-23 12:19:55.676190 | 10.0.0.34 |             --
                                                                                                 Processing a statement [shard 1] | 2019-01-23 12:19:55.676280 | 10.0.0.34 |             90
 Creating read executor for token -9090087391989406011 with all: {10.0.0.34} targets: {10.0.0.34} repair decision: NONE [shard 1] | 2019-01-23 12:19:55.676344 | 10.0.0.34 |            154
 Creating read executor for token -7643380759630077974 with all: {10.0.0.34} targets: {10.0.0.34} repair decision: NONE [shard 1] | 2019-01-23 12:19:55.676349 | 10.0.0.34 |            159
 Creating read executor for token -2998312467040114775 with all: {10.0.0.34} targets: {10.0.0.34} repair decision: NONE [shard 1] | 2019-01-23 12:19:55.676353 | 10.0.0.34 |            163
 Creating read executor for token -4094339843955376801 with all: {10.0.0.34} targets: {10.0.0.34} repair decision: NONE [shard 1] | 2019-01-23 12:19:55.676356 | 10.0.0.34 |            166
                                                                                            read_data: querying locally [shard 1] | 2019-01-23 12:19:55.676359 | 10.0.0.34 |            169
                                                                                            read_data: querying locally [shard 1] | 2019-01-23 12:19:55.676369 | 10.0.0.34 |            179
                                                                                            read_data: querying locally [shard 1] | 2019-01-23 12:19:55.676373 | 10.0.0.34 |            183
                                                                                            read_data: querying locally [shard 1] | 2019-01-23 12:19:55.676376 | 10.0.0.34 |            186
                                                  Start querying the token range that starts with -2998312467040114775 [shard 14] | 2019-01-23 12:19:55.676402 | 10.0.0.34 |              7
                                                  Start querying the token range that starts with -7643380759630077974 [shard 51] | 2019-01-23 12:19:55.676478 | 10.0.0.34 |             10
                                                  Start querying the token range that starts with -9090087391989406011 [shard 36] | 2019-01-23 12:19:55.676478 | 10.0.0.34 |             10
                                                  Start querying the token range that starts with -4094339843955376801 [shard 54] | 2019-01-23 12:19:55.676480 | 10.0.0.34 |              5
                                                                                                      Querying is done [shard 51] | 2019-01-23 12:19:55.676664 | 10.0.0.34 |            146
                                                                                                      Querying is done [shard 36] | 2019-01-23 12:19:55.676664 | 10.0.0.34 |            148
                                                                                                      Querying is done [shard 54] | 2019-01-23 12:19:55.676674 | 10.0.0.34 |             54
                                                                                                      Querying is done [shard 14] | 2019-01-23 12:19:55.676680 | 10.0.0.34 |            110
                                                                                   Done processing - preparing a result [shard 1] | 2019-01-23 12:19:55.677041 | 10.0.0.34 |            851
                                                                                                                 Request complete | 2019-01-23 12:19:55.676862 | 10.0.0.34 |            862

```

Scylla 3.0.1

```
cqlsh> select key from keyspace1.standard1 where key in (0x36384b30374f33314c30, 0x37373539364d4f323330,0x50364d4e4d3850394f30,0x4f503030314c35393330) ;

 key
------------------------
 0x36384b30374f33314c30
 0x37373539364d4f323330
 0x4f503030314c35393330
 0x50364d4e4d3850394f30

(4 rows)

Tracing session: 3a0f2ab0-1f09-11e9-920a-000000000008

 activity                                                                                                                         | timestamp                  | source    | source_elapsed | client
----------------------------------------------------------------------------------------------------------------------------------+----------------------------+-----------+----------------+-----------
                                                                                                               Execute CQL3 query | 2019-01-23 12:20:10.075000 | 10.0.0.65 |              0 | 127.0.0.1
                                                                                                    Parsing a statement [shard 5] | 2019-01-23 12:20:10.075917 | 10.0.0.65 |             -- | 127.0.0.1
                                                                                                 Processing a statement [shard 5] | 2019-01-23 12:20:10.076006 | 10.0.0.65 |             89 | 127.0.0.1
 Creating read executor for token -9090087391989406011 with all: {10.0.0.65} targets: {10.0.0.65} repair decision: NONE [shard 5] | 2019-01-23 12:20:10.076079 | 10.0.0.65 |            162 | 127.0.0.1
 Creating read executor for token -7643380759630077974 with all: {10.0.0.65} targets: {10.0.0.65} repair decision: NONE [shard 5] | 2019-01-23 12:20:10.076084 | 10.0.0.65 |            167 | 127.0.0.1
 Creating read executor for token -2998312467040114775 with all: {10.0.0.65} targets: {10.0.0.65} repair decision: NONE [shard 5] | 2019-01-23 12:20:10.076087 | 10.0.0.65 |            171 | 127.0.0.1
 Creating read executor for token -4094339843955376801 with all: {10.0.0.65} targets: {10.0.0.65} repair decision: NONE [shard 5] | 2019-01-23 12:20:10.076091 | 10.0.0.65 |            175 | 127.0.0.1
                                                                                            read_data: querying locally [shard 5] | 2019-01-23 12:20:10.076094 | 10.0.0.65 |            178 | 127.0.0.1
                                                                                            read_data: querying locally [shard 5] | 2019-01-23 12:20:10.076106 | 10.0.0.65 |            189 | 127.0.0.1
                                                                                            read_data: querying locally [shard 5] | 2019-01-23 12:20:10.076108 | 10.0.0.65 |            191 | 127.0.0.1
                                                                                            read_data: querying locally [shard 5] | 2019-01-23 12:20:10.076110 | 10.0.0.65 |            194 | 127.0.0.1
                                                  Start querying the token range that starts with -2998312467040114775 [shard 14] | 2019-01-23 12:20:10.076207 | 10.0.0.65 |              6 | 127.0.0.1
                                                  Start querying the token range that starts with -9090087391989406011 [shard 36] | 2019-01-23 12:20:10.076253 | 10.0.0.65 |             23 | 127.0.0.1
                                                  Start querying the token range that starts with -4094339843955376801 [shard 54] | 2019-01-23 12:20:10.076256 | 10.0.0.65 |             11 | 127.0.0.1
                                                  Start querying the token range that starts with -7643380759630077974 [shard 51] | 2019-01-23 12:20:10.076258 | 10.0.0.65 |             11 | 127.0.0.1
                                                                                                      Querying is done [shard 14] | 2019-01-23 12:20:10.076337 | 10.0.0.65 |            136 | 127.0.0.1
                                                                                                      Querying is done [shard 54] | 2019-01-23 12:20:10.076346 | 10.0.0.65 |            101 | 127.0.0.1
                                                                                                      Querying is done [shard 51] | 2019-01-23 12:20:10.076346 | 10.0.0.65 |             99 | 127.0.0.1
                                                                                                      Querying is done [shard 36] | 2019-01-23 12:20:10.076404 | 10.0.0.65 |            173 | 127.0.0.1
                                                                                   Done processing - preparing a result [shard 5] | 2019-01-23 12:20:10.076784 | 10.0.0.65 |            867 | 127.0.0.1
                                                                                                                 Request complete | 2019-01-23 12:20:10.075880 | 10.0.0.65 |            880 | 127.0.0.1
```

**Comment by denesb** [comment]
Multipartition IN queries go through a different code path then range scans.

**Comment by denesb** [comment]
I will have a look at why range-scans take so long.

**Comment by denesb** [comment]
The new range scan code (`multishard_combining_reader()`) uses exponentially increasing parallelism, just like the previous code, with the added advantage that it reads the whole range. Such a sparse table should be read in a single pass, with `O(log2(shard_num))` fill buffer calls. In theory the handling of sparse tables should have improved with 3.0. Off the top of my head I don't know what have gone wrong. I'll have to add some additional tracing to see what is going on.

**Comment by glommer** [comment]
This is in master for a while and users in the field are hitting this. @avikivity @slivne What's the 3.0 backport status of this ?
