### ISSUE TITLE
'cold_reads_to_omit' Size Tiered compaction property causes problems when using java tools.

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#4169]
If we create a table with
```
AND compaction = {'min_threshold': '2', 'cold_reads_to_omit': '0.0', 'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32'}
```

sstableloader fails with:

```
Exception: org.apache.cassandra.exceptions.ConfigurationException: Properties specified [cold_reads_to_omit] are not understood by SizeTieredCompactionStrategy
org.apache.cassandra.exceptions.ConfigurationException: Properties specified [cold_reads_to_omit] are not understood by SizeTieredCompactionStrategy
    at org.apache.cassandra.schema.CompactionParams.validate(CompactionParams.java:148)
    at org.apache.cassandra.schema.TableParams.validate(TableParams.java:139)
    at org.apache.cassandra.cql3.statements.TableAttributes.validate(TableAttributes.java:55)
    at org.apache.cassandra.cql3.statements.CFProperties.validate(CFProperties.java:35)
    at org.apache.cassandra.cql3.statements.CreateTableStatement$RawStatement.prepare(CreateTableStatement.java:216)
    at com.scylladb.tools.BulkLoader$CQLClient.getCFMetaData(BulkLoader.java:664)
    at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1456)
    at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1297)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

Cassandra 3.11 do not support `cold_reads_to_omit` property of Size Tiered compaction. We updated our java tools so they follow behaviour of recent Cassandra version. Cassandra 3.11 refuses to create a table with `AND compaction = {... 'cold_reads_to_omit': '0.0', 'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy' ... }` by signalling exception `ConfigurationException: Properties specified [cold_reads_to_omit] are not understood by SizeTieredCompactionStrategy`. Scylla creates the table with no problem but the tools do not work and customers fail to migrate.

A work around is to tell customer to remove the `cold_reads_to_omit` property but it would be better to make the situation more clear for example by refusing to create a table with such property in Scylla.

**Comment by denesb** [comment]
This issue aged out. We are dropping our java tools.
