### ISSUE TITLE
MultiException stack error when starting up

### ISSUE THREAD

**Issue by edendekker** [scylladb/scylla#4179]
- [✅] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.1-0.20190120.3c4f8cf6e
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): VM VirtualBox

```
Feb 03 00:38:47 host scylla-jmx[2505]: MultiException stack 2 of 2
Feb 03 00:38:47 host scylla-jmx[2505]: java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
Feb 03 00:38:47 host scylla-jmx[2505]:         implementation=org.glassfish.jersey.message.internal.DataSourceProvider
Feb 03 00:38:47 host scylla-jmx[2505]:         contracts={javax.ws.rs.ext.MessageBodyReader,javax.ws.rs.ext.MessageBodyWriter}
Feb 03 00:38:47 host scylla-jmx[2505]:         scope=javax.inject.Singleton
Feb 03 00:38:47 host scylla-jmx[2505]:         qualifiers={}
Feb 03 00:38:47 host scylla-jmx[2505]:         descriptorType=CLASS
Feb 03 00:38:47 host scylla-jmx[2505]:         descriptorVisibility=NORMAL
Feb 03 00:38:47 host scylla-jmx[2505]:         metadata=
Feb 03 00:38:47 host scylla-jmx[2505]:         rank=0
Feb 03 00:38:47 host scylla-jmx[2505]:         loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@150ab4ed
Feb 03 00:38:47 host scylla-jmx[2505]:         proxiable=null
Feb 03 00:38:47 host scylla-jmx[2505]:         proxyForSameScope=null
Feb 03 00:38:47 host scylla-jmx[2505]:         analysisName=null
Feb 03 00:38:47 host scylla-jmx[2505]:         id=12
Feb 03 00:38:47 host scylla-jmx[2505]:         locatorId=2
Feb 03 00:38:47 host scylla-jmx[2505]:         identityHashCode=1011044643
Feb 03 00:38:47 host scylla-jmx[2505]:         reified=false)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:689)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:463)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2187)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:121)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl$10.compute(ServiceLocatorImpl.java:1331)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl$10.compute(ServiceLocatorImpl.java:1326)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture$1.call(LRUHybridCache.java:115)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture$1.call(LRUHybridCache.java:111)
Feb 03 00:38:47 host scylla-jmx[2505]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture.run(LRUHybridCache.java:173)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.hk2.utilities.cache.LRUHybridCache.compute(LRUHybridCache.java:292)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1388)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1313)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1302)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.internal.inject.Providers.getServiceHandles(Providers.java:354)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:187)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.message.internal.MessageBodyFactory.<init>(MessageBodyFactory.java:248)
Feb 03 00:38:47 host scylla-jmx[2505]:         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Feb 03 00:38:47 host scylla-jmx[2505]:         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Feb 03 00:38:47 host scylla-jmx[2505]:         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Feb 03 00:38:47 host scylla-jmx[2505]:         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)

Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
Feb 03 00:38:47 host scylla-jmx[2505]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2072)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:767)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:774)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:97)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:67)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:308)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316)
Feb 03 00:38:47 host scylla-jmx[2505]:         at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:172)
Feb 03 00:38:47 host scylla-jmx[2505]:         at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:192)
Feb 03 00:38:47 host scylla-jmx[2505]:         at com.scylladb.jmx.api.APIClient.getReader(APIClient.java:216)
Feb 03 00:38:47 host scylla-jmx[2505]:         at com.scylladb.jmx.api.APIClient.getJsonArray(APIClient.java:632)
Feb 03 00:38:47 host scylla-jmx[2505]:         at com.scylladb.jmx.api.APIClient.getJsonArray(APIClient.java:639)
Feb 03 00:38:47 host scylla-jmx[2505]:         at org.apache.cassandra.metrics.StreamingMetrics.checkRegistration(StreamingMetrics.java:76)
Feb 03 00:38:47 host scylla-jmx[2505]:         at com.scylladb.jmx.utils.APIMBeanServer.checkRegistrations(APIMBeanServer.java:302)
Feb 03 00:38:47 host scylla-jmx[2505]:         at com.scylladb.jmx.utils.APIMBeanServer.queryNames(APIMBeanServer.java:114)
Feb 03 00:38:47 host scylla-jmx[2505]:         at com.scylladb.jmx.main.Main.main(Main.java:49)
Feb 03 00:38:47 host scylla-jmx[2505]: JMX is enabled to receive remote connections on port: 7199
Feb 03 00:38:58 host scylla[2480]: [shard 0] gossip - No gossip backlog; proceeding
Feb 03 00:38:58 host scylla[2480]: [shard 0] storage_service - Starting listening for CQL clients on 192.168.0.232:9042 (unencrypted)
Feb 03 00:38:58 host systemd[1]: Started Scylla Housekeeping restart mode.
Feb 03 00:38:58 host scylla[2480]: [shard 0] storage_service - Thrift server listening on 192.168.0.232:9160 ...
Feb 03 00:38:59 host scylla-housekeeping[2541]: You current Scylla release is 3.0.1 the latest minor release is 3.0 go to http://www.scylladb.com for upgrade instructions

```

Scylla-server loads successfully. 
It however outputs long stack traces of the above in my journalctl logs.

**Comment by slivne** [comment]
can you check with java version you are using 

scylla currently supports 1.8 only (we are working to fix that).

**Comment by edendekker** [comment]
You are correct. I was using openjdk 10. I have downgraded to openjdk 8. I am happy to close this ticket.
