### ISSUE TITLE
SIGSEGV in cluster read

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#418]
running

commit b2630db514d595d3a19c542af713e18b867d7994
Author: Takuya ASADA <syuu@cloudius-systems.com>
Date:   Thu Sep 24 09:18:06 2015 +0000

    dist: remove rpm dependency to libvirt
    
    This is for testing virtio mode, since we don't officially recommend to use virtio mode we should drop it.
    
    Signed-off-by: Takuya ASADA <syuu@cloudius-systems.com>

creating cluster with
```
pkill -9 scylla
rm -Rf tmp/*

mkdir tmp/1; ./build/release/scylla -c 1 -m 128M --rpc-address 127.0.0.1 --listen-address 127.0.0.1 --seed-provider-parameters seeds=127.0.0.1 --datadir `pwd`/tmp/1 --commitlog-directory `pwd`/tmp/1 --cpuset 0 2>&1 | tee /tmp/out1 &
sleep 1
mkdir tmp/2; ./build/release/scylla -c 1 -m 128M  --rpc-address 127.0.0.2 --listen-address 127.0.0.2 --seed-provider-parameters seeds=127.0.0.1 --datadir `pwd`/tmp/2 --commitlog-directory `pwd`/tmp/2 --cpuset 1 2>&1 | tee /tmp/out2 &
sleep 6
mkdir tmp/3; ./build/release/scylla -c 1 -m 128M  --rpc-address 127.0.0.3 --listen-address 127.0.0.3 --seed-provider-parameters seeds=127.0.0.1 --datadir `pwd`/tmp/3 --commitlog-directory `pwd`/tmp/3 --cpuset 2 2>&1 | tee /tmp/out3 &

```
running the following python application

```
#!/usr/bin/python
from cassandra.cluster import Cluster
import subprocess, tempfile, os, shutil
import time
from cassandra.query import SimpleStatement
from cassandra import Unavailable,ConsistencyLevel

def debug(msg):
    print msg

class TestSimpleCluster:

    def prepare_cluster(self):
        session3 = Cluster(['127.0.0.3']).connect()
        session3.execute("CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'} ;")
        session3.execute("CREATE TABLE ks.test1 ( k int PRIMARY KEY, c int);")
        insert = SimpleStatement("insert into ks.test1  (k,c) values (1,2);", consistency_level=ConsistencyLevel.ALL)
        session3.execute(insert)
        time.sleep(10)

        # Select
        session1 = Cluster(['127.0.0.1']).connect()
        query = SimpleStatement("SELECT * FROM ks.test1 WHERE k=1",consistency_level=ConsistencyLevel.QUORUM)
        session1.execute(query)

        return session1;


x =  TestSimpleCluster()
x.prepare_cluster()
```

I get

```
(gdb) where
#0  get (this=0x8) at /usr/include/c++/4.9.2/bits/unique_ptr.h:305
#1  operator bool (this=0x8) at /usr/include/c++/4.9.2/bits/unique_ptr.h:319
#2  is_linearized (this=0x8) at ./bytes_ostream.hh:220
#3  linearize (this=0x8) at ./bytes_ostream.hh:236
#4  query::result::digest (this=0x8) at ./query-result.hh:137
#5  0x00000000009210f2 in operator()<, void> (__object=..., this=<synthetic pointer>) at /usr/include/c++/4.9.2/functional:556
#6  dereference (this=<synthetic pointer>) at /usr/include/boost/iterator/transform_iterator.hpp:121
#7  dereference<boost::transform_iterator<std::_Mem_fn<query::result_digest (query::result::*)()>, boost::indirect_iterator<__gnu_cxx::__normal_iterator<foreign_ptr<lw_shared_ptr<query::result> > const*, std::vector<foreign_ptr<lw_shared_ptr<query::result> > > >, boost::use_default, boost::use_default, boost::use_default, boost::use_default>, boost::use_default, boost::use_default> > (f=<synthetic pointer>)
    at /usr/include/boost/iterator/iterator_facade.hpp:514
#8  operator* (this=<synthetic pointer>) at /usr/include/boost/iterator/iterator_facade.hpp:639
#9  dereference (selected=1, this=<synthetic pointer>) at /usr/include/boost/range/detail/join_iterator.hpp:74
#10 dereference (this=<synthetic pointer>) at /usr/include/boost/range/detail/join_iterator.hpp:244
#11 dereference<boost::range_detail::join_iterator<__gnu_cxx::__normal_iterator<query::result_digest const*, std::vector<query::result_digest> >, boost::transform_iterator<std::_Mem_fn<query::result_digest (query::result::*)()>, boost::indirect_iterator<__gnu_cxx::__normal_iterator<foreign_ptr<lw_shared_ptr<query::result> > const*, std::vector<foreign_ptr<lw_shared_ptr<query::result> > > >, boost::use_default, boost::use_default, boost::use_default, boost::use_default>, boost::use_default, boost::use_default>, query::result_digest, query::result_digest, boost::random_access_traversal_tag> > (f=<synthetic pointer>)
    at /usr/include/boost/iterator/iterator_facade.hpp:514
#12 operator* (this=<synthetic pointer>) at /usr/include/boost/iterator/iterator_facade.hpp:639
#13 operator()<boost::range_detail::join_iterator<__gnu_cxx::__normal_iterator<const query::result_digest*, std::vector<query::result_digest> >, boost::transform_iterator<std::_Mem_fn<query::result_digest (query::result::*)()>, boost::indirect_iterator<__gnu_cxx::__normal_iterator<const foreign_ptr<lw_shared_ptr<query::result> >*, std::vector<foreign_ptr<lw_shared_ptr<query::result> > > >, boost::use_default, boost::use_default, boost::use_default, boost::use_default>, boost::use_default, boost::use_default>, query::result_digest, query::result_digest, boost::random_access_traversal_tag> > (__it=..., 
    this=<synthetic pointer>) at /usr/include/c++/4.9.2/bits/predefined_ops.h:231
#14 __find_if<boost::range_detail::join_iterator<__gnu_cxx::__normal_iterator<const query::result_digest*, std::vector<query::result_digest> >, boost::transform_iterator<std::_Mem_fn<query::result_digest (query::result::*)()>, boost::indirect_iterator<__gnu_cxx::__normal_iterator<const foreign_ptr<lw_shared_ptr<query::result> >*, std::vector<foreign_ptr<lw_shared_ptr<query::result> > > >, boost::use_default, boost::use_default, boost::use_default, boost::use_default>, boost::use_default, boost::use_default>, query::result_digest, query::result_digest, boost::random_access_traversal_tag>, __gnu_cxx::__ops::_Iter_pred<service::digest_read_resolver::digests_match() const::<lambda(const query::result_digest&)> > > (__pred=..., __last=..., __first=...) at /usr/include/c++/4.9.2/bits/stl_algo.h:104
#15 __find_if<boost::range_detail::join_iterator<__gnu_cxx::__normal_iterator<const query::result_digest*, std::vector<query::result_digest> >, boost::transform_iterator<std::_Mem_fn<query::result_digest (query::result::*)()>, boost::indirect_iterator<__gnu_cxx::__normal_iterator<const foreign_ptr<lw_shared_ptr<query::result> >*, std::vector<foreign_ptr<lw_shared_ptr<query::result> > > >, boost::use_default, boost::use_default, boost::use_default, boost::use_default>, boost::use_default, boost::use_default>, query::result_digest, query::result_digest, boost::random_access_traversal_tag>, __gnu_cxx::__ops::_Iter_pred<service::digest_read_resolver::digests_match() const::<lambda(const query::result_digest&)> > > (__pred=..., __last=..., __first=...) at /usr/include/c++/4.9.2/bits/stl_algo.h:162
#16 find_if<boost::range_detail::join_iterator<__gnu_cxx::__normal_iterator<const query::result_digest*, std::vector<query::result_digest> >, boost::transform_iterator<std::_Mem_fn<query::result_digest (query::result::*)()>, boost::indirect_iterator<__gnu_cxx::__normal_iterator<const foreign_ptr<lw_shared_ptr<query::result> >*, std::vector<foreign_ptr<lw_shared_ptr<query::result> > > >, boost::use_default, boost::use_default, boost::use_default, boost::use_default>, boost::use_default, boost::use_default>, query::result_digest, query::result_digest, boost::random_access_traversal_tag>, service::digest_read_resolver::digests_match() const::<lambda(const query::result_digest&)> > (__pred=..., __last=..., __first=...) at /usr/include/c++/4.9.2/bits/stl_algo.h:3805
#17 service::digest_read_resolver::digests_match (this=<optimized out>) at service/storage_proxy.cc:1305
#18 0x000000000092e885 in resolve (this=0x600000da2150) at service/storage_proxy.cc:1323
#19 operator() (f=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x5d2083f, DIE 0x610b0bf>, __closure=0x7fff2fb3c3c0) at service/storage_proxy.cc:1609
#20 do_void_futurize_apply<service::abstract_read_executor::execute(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(future<>)#2}::operator()(future<>) const::{lambda(future<>&&)#1}, future<> >(is_future&&, future<>) (func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x5d2083f, DIE 0x610b120>)
    at /home/shlomi/scylla/seastar/core/future.hh:1078
#21 0x000000000092ea28 in apply<service::abstract_read_executor::execute(std::chrono::_V2::system_clock::time_point)::<lambda(future<>)>::<lambda(future<>&&)>, future<> > (
    func=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x5d2083f, DIE 0x604373c>) at /home/shlomi/scylla/seastar/core/future.hh:1126
#22 future<>::then_wrapped<service::abstract_read_executor::execute(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(future<>)#2}::operator()(future<>) const::{lambda(future<>&&)#1}, future<> >(service::abstract_read_executor::execute(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(future<>)#2}::operator()(future<>) const::{lambda(future<>&&)#1}&&) (this=this@entry=0x7fff2fb3c3a0, 
    func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x5d2083f, DIE 0x610b5a3>) at /home/shlomi/scylla/seastar/core/future.hh:822
#23 0x00000000009438b4 in service::abstract_read_executor::execute(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(future<>)#2}::operator()(future<>) const (__closure=__closure@entry=0x60000114d420, f=...) at service/storage_proxy.cc:1615
#24 0x0000000000943b62 in do_void_futurize_apply<service::abstract_read_executor::execute(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(future<>)#2}, future<> >(std::result_of&&, future<>&&) (func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x5d2083f, DIE 0x61d54a8>)
    at /home/shlomi/scylla/seastar/core/future.hh:1078
#25 0x0000000000946cb6 in apply<service::abstract_read_executor::execute(std::chrono::_V2::system_clock::time_point)::<lambda(future<>)>, future<> > (
    func=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x5d2083f, DIE 0x60437af>) at /home/shlomi/scylla/seastar/core/future.hh:1126
#26 operator()<future_state<> > (state=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x5d2083f, DIE 0x62170ee>, __closure=0x60000114d400) at /home/shlomi/scylla/seastar/core/future.hh:828
#27 _ZN12continuationIZN6futureIIEE12then_wrappedIZN7service22abstract_read_executor7executeENSt6chrono10time_pointINS5_3_V212system_clockENS5_8durationIlSt5ratioILl1ELl1000000000EEEEEEEUlS1_E0_S1_EET0_OT_EUlOT_---Type <return> to continue, or q <return> to quit--- 
E_IEE3runEv (this=0x60000114d3f0) at /home/shlomi/scylla/seastar/core/future.hh:362
#28 0x0000000000470a0f in reactor::run_tasks (this=this@entry=0x6000003c8000, tasks=...) at core/reactor.cc:1117
#29 0x000000000049c1db in reactor::run (this=0x6000003c8000) at core/reactor.cc:1234
#30 0x00000000004f263b in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fff2fb3cc60, ac=ac@entry=17, av=av@entry=0x7fff2fb3cea8, 
    func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x52f599, DIE 0x5d912e>) at core/app-template.cc:122
#31 0x000000000041eaac in main (ac=17, av=0x7fff2fb3cea8) at main.cc:324
```

**Comment by slivne** [comment]
fixed by 

commit 2998b891f35346cc4d62bf779ab901ae841a7a1c
Author: Gleb Natapov <gleb@scylladb.com>
Date:   Wed Sep 30 13:31:13 2015 +0300

    storage_proxy: fix crash during background read repair
    
    Lazy digest calculation code introduced a bug in background read repair.
    The problem is that digest_read_resolver::resolve() destroys one data
    result (it is moved to a caller to be sent as a reply), so during
    background digest match there is no value to calculate a digest from.
    Copying data to the caller would be most elegant solution, but also
    slowest one, so lets just treat the case where there is only one
    target queried and skip digest calculation in this case since we know
    digest_match() will do nothing.
