### ISSUE TITLE
Scylla crashes on SCYLLA_COUNTER_SHARD_LIST prepared statement

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4209]
Scylla version (or git commit hash): 3.0 (3c4f8cf6ed3e916df127bb61d6a1bda7c2f7454a)

Scylla crashes on counter prepared statements 
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /home/shlomi/scylla/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /home/shlomi/scylla/seastar/core/reactor.cc:410
 (inlined by) print_with_backtrace at /home/shlomi/scylla/seastar/core/reactor.cc:431
seastar::print_with_backtrace(char const*) at /home/shlomi/scylla/seastar/core/reactor.cc:438
sigsegv_action at /home/shlomi/scylla/seastar/core/reactor.cc:4020
 (inlined by) operator() at /home/shlomi/scylla/seastar/core/reactor.cc:4006
 (inlined by) _FUN at /home/shlomi/scylla/seastar/core/reactor.cc:4002
?? ??:0
__find_if<__gnu_cxx::__normal_iterator<const seastar::shared_ptr<cql3::column_specification>*, std::vector<seastar::shared_ptr<cql3::column_specification> > >, __gnu_cxx::__ops::_Iter_negate<cql3::column_specification::all_in_same_table(const std::vector<seastar::shared_ptr<cql3::column_specification> >&)::<lambda(auto:72&&)> > > at /usr/include/c++/8/bits/stl_algo.h:118
 (inlined by) __find_if_not<__gnu_cxx::__normal_iterator<const seastar::shared_ptr<cql3::column_specification>*, std::vector<seastar::shared_ptr<cql3::column_specification> > >, __gnu_cxx::__ops::_Iter_pred<cql3::column_specification::all_in_same_table(const std::vector<seastar::shared_ptr<cql3::column_specification> >&)::<lambda(auto:72&&)> > > at /usr/include/c++/8/bits/stl_algo.h:171
 (inlined by) find_if_not<__gnu_cxx::__normal_iterator<const seastar::shared_ptr<cql3::column_specification>*, std::vector<seastar::shared_ptr<cql3::column_specification> > >, cql3::column_specification::all_in_same_table(const std::vector<seastar::shared_ptr<cql3::column_specification> >&)::<lambda(auto:72&&)> > at /usr/include/c++/8/bits/stl_algo.h:566
 (inlined by) all_of<__gnu_cxx::__normal_iterator<const seastar::shared_ptr<cql3::column_specification>*, std::vector<seastar::shared_ptr<cql3::column_specification> > >, cql3::column_specification::all_in_same_table(const std::vector<seastar::shared_ptr<cql3::column_specification> >&)::<lambda(auto:72&&)> > at /usr/include/c++/8/bits/stl_algo.h:509
 (inlined by) cql3::column_specification::all_in_same_table(std::vector<seastar::shared_ptr<cql3::column_specification>, std::allocator<seastar::shared_ptr<cql3::column_specification> > > const&) at /home/shlomi/scylla/cql3/column_specification.cc:51
cql3::prepared_metadata::prepared_metadata(std::vector<seastar::shared_ptr<cql3::column_specification>, std::allocator<seastar::shared_ptr<cql3::column_specification> > > const&, std::vector<unsigned short, std::allocator<unsigned short> > const&) at /home/shlomi/scylla/cql3/result_set.cc:106 (discriminator 1)
seastar::shared_ptr_count_for<cql3::prepared_metadata>::shared_ptr_count_for<std::vector<seastar::shared_ptr<cql3::column_specification>, std::allocator<seastar::shared_ptr<cql3::column_specification> > > const&, std::vector<unsigned short, std::allocator<unsigned short> >&>(std::vector<seastar::shared_ptr<cql3::column_specification>, std::allocator<seastar::shared_ptr<cql3::column_specification> > > const&, std::vector<unsigned short, std::allocator<unsigned short> >&) at /home/shlomi/scylla/./seastar/core/shared_ptr.hh:466
 (inlined by) seastar::shared_ptr<cql3::prepared_metadata> seastar::shared_ptr_make_helper<cql3::prepared_metadata, false>::make<std::vector<seastar::shared_ptr<cql3::column_specification>, std::allocator<seastar::shared_ptr<cql3::column_specification> > > const&, std::vector<unsigned short, std::allocator<unsigned short> >&>(std::vector<seastar::shared_ptr<cql3::column_specification>, std::allocator<seastar::shared_ptr<cql3::column_specification> > > const&, std::vector<unsigned short, std::allocator<unsigned short> >&) at /home/shlomi/scylla/./seastar/core/shared_ptr.hh:629
 (inlined by) seastar::shared_ptr<cql3::prepared_metadata> seastar::make_shared<cql3::prepared_metadata, std::vector<seastar::shared_ptr<cql3::column_specification>, std::allocator<seastar::shared_ptr<cql3::column_specification> > > const&, std::vector<unsigned short, std::allocator<unsigned short> >&>(std::vector<seastar::shared_ptr<cql3::column_specification>, std::allocator<seastar::shared_ptr<cql3::column_specification> > > const&, std::vector<unsigned short, std::allocator<unsigned short> >&) at /home/shlomi/scylla/./seastar/core/shared_ptr.hh:647
 (inlined by) cql_transport::messages::result_message::prepared::prepared(seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action>) at /home/shlomi/scylla/./transport/messages/result_message.hh:47
 (inlined by) cql_transport::messages::result_message::prepared::cql::cql(seastar::basic_sstring<signed char, unsigned int, 31u, false> const&, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action>) at /home/shlomi/scylla/./transport/messages/result_message.hh:123
 (inlined by) seastar::shared_ptr_count_for<cql_transport::messages::result_message::prepared::cql>::shared_ptr_count_for<seastar::basic_sstring<signed char, unsigned int, 31u, false> const&, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >(seastar::basic_sstring<signed char, unsigned int, 31u, false> const&, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action>&&) at /home/shlomi/scylla/./seastar/core/shared_ptr.hh:466
 (inlined by) seastar::shared_ptr<cql_transport::messages::result_message::prepared::cql> seastar::shared_ptr_make_helper<cql_transport::messages::result_message::prepared::cql, false>::make<seastar::basic_sstring<signed char, unsigned int, 31u, false> const&, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >(seastar::basic_sstring<signed char, unsigned int, 31u, false> const&, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action>&&) at /home/shlomi/scylla/./seastar/core/shared_ptr.hh:629
 (inlined by) seastar::shared_ptr<cql_transport::messages::result_message::prepared::cql> seastar::make_shared<cql_transport::messages::result_message::prepared::cql, seastar::basic_sstring<signed char, unsigned int, 31u, false> const&, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >(seastar::basic_sstring<signed char, unsigned int, 31u, false> const&, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action>&&) at /home/shlomi/scylla/./seastar/core/shared_ptr.hh:647
 (inlined by) seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > cql3::query_processor::prepare_one<cql_transport::messages::result_message::prepared::cql, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&)>(seastar::basic_sstring<char, unsigned int, 15u, true>, service::client_state const&, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&))::{lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}::operator()(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&) const::{lambda(auto:1)#2}::operator()<seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >(auto, {lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}) const at /home/shlomi/scylla/./cql3/query_processor.hh:364
 (inlined by) _ZN7seastar12apply_helperIZZN4cql315query_processor11prepare_oneIN13cql_transport8messages14result_message8prepared3cqlERFNS1_23prepared_cache_key_typeERKNSt12experimental15fundamentals_v117basic_string_viewIcSt11char_traitsIcEEERKNS_13basic_sstringIcjLj15ELb1EEEERFRKNSI_IajLj31ELb0EEERKS9_EEENS_6futureIJNS_10shared_ptrIS7_EEEEESJ_RKN7service12client_stateEOT0_OT1_ENKUlSS_SL_E_clESS_SL_EUlT_E0_OSt5tupleIJNS_11checked_ptrINS_8weak_ptrINS1_10statements18prepared_statementEEENS_25default_null_deref_actionEEEEESt16integer_sequenceImJLm0EEEE5applyEOS19_S1J_ at /home/shlomi/scylla/./seastar/core/apply.hh:35
 (inlined by) auto seastar::apply<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > cql3::query_processor::prepare_one<cql_transport::messages::result_message::prepared::cql, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&)>(seastar::basic_sstring<char, unsigned int, 15u, true>, service::client_state const&, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&))::{lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}::operator()(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&) const::{lambda(auto:1)#2}, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >({lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}&&, std::tuple<seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >&&) at /home/shlomi/scylla/./seastar/core/apply.hh:43
 (inlined by) seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > seastar::futurize<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > >::apply<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > cql3::query_processor::prepare_one<cql_transport::messages::result_message::prepared::cql, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&)>(seastar::basic_sstring<char, unsigned int, 15u, true>, service::client_state const&, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&))::{lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}::operator()(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&) const::{lambda(auto:1)#2}, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >({lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}&&, std::tuple<seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >&&) at /home/shlomi/scylla/./seastar/core/future.hh:1389
 (inlined by) seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > seastar::future<seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >::then<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > cql3::query_processor::prepare_one<cql_transport::messages::result_message::prepared::cql, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&)>(seastar::basic_sstring<char, unsigned int, 15u, true>, service::client_state const&, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&))::{lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}::operator()(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&) const::{lambda(auto:1)#2}, seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > >({lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}&&)::{lambda({lambda(auto:1)#2})#1}::operator()<seastar::future_state<seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> > >(auto, {lambda(auto:1)#2}) at /home/shlomi/scylla/./seastar/core/future.hh:963
 (inlined by) seastar::continuation<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > seastar::future<seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >::then<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > cql3::query_processor::prepare_one<cql_transport::messages::result_message::prepared::cql, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&)>(seastar::basic_sstring<char, unsigned int, 15u, true>, service::client_state const&, cql3::prepared_cache_key_type (&)(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&), seastar::basic_sstring<signed char, unsigned int, 31u, false> const& (&)(cql3::prepared_cache_key_type const&))::{lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}::operator()(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&) const::{lambda(auto:1)#2}, seastar::future<seastar::shared_ptr<cql_transport::messages::result_message::prepared> > >({lambda(cql3::prepared_cache_key_type const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&)#1}&&)::{lambda({lambda(auto:1)#2})#1}, seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> >::run_and_dispose() at /home/shlomi/scylla/./seastar/core/future.hh:414
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /home/shlomi/scylla/seastar/core/reactor.cc:2695
seastar::reactor::run_some_tasks() at /home/shlomi/scylla/seastar/core/reactor.cc:3118
seastar::reactor::run_some_tasks() at /home/shlomi/scylla/seastar/core/reactor.cc:3102
 (inlined by) seastar::reactor::run() at /home/shlomi/scylla/seastar/core/reactor.cc:3265
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /home/shlomi/scylla/seastar/core/app-template.cc:185
main at /home/shlomi/scylla/main.cc:337
?? ??:0
_start at ??:?
?? ??:0
```

reproducer (will be added to dtest prepared_statements_test.py)

```
    def test_counter_1(self):
        self.cluster.populate(1).start()
        node = self.cluster.nodes.values()[0]

        session = self.patient_cql_connection(node)
        session.execute("""
            CREATE KEYSPACE IF NOT EXISTS %s
            WITH replication = { 'class': 'SimpleStrategy', 'replication_factor': '1' }
            """ % KEYSPACE)

        session.set_keyspace(KEYSPACE)
        session.execute("CREATE TABLE IF NOT EXISTS tb (pk bigint, date timestamp, ck text, c1 counter, PRIMARY KEY (pk, date, ck));")

        session.execute("UPDATE tb SET c1 = SCYLLA_COUNTER_SHARD_LIST([(103, d432e37a-a190-4689-8bda-b3ba4973bc2e, 1, 1)])  WHERE pk = 1 AND date = 1549640927943017 AND ck = 'test';")
        update_statement = session.prepare("UPDATE tb SET c1 = SCYLLA_COUNTER_SHARD_LIST([(103,?,1,?)])  WHERE pk = ? AND date = ? AND ck = ?")
        session.execute(update_statement, (0xd432e37aa19046898bdab3ba4973bc2e, 1,  1, 1549640927943018, 'test'));
```

**Comment by slivne** [comment]
The correct way to use prepared_statements with counters is:

```
    def test2(self):
        self.cluster.populate(1).start()
        node = self.cluster.nodes.values()[0]

        session = self.patient_cql_connection(node)
        session.execute("""
            CREATE KEYSPACE IF NOT EXISTS %s
            WITH replication = { 'class': 'SimpleStrategy', 'replication_factor': '1' }
            """ % KEYSPACE)

        session.set_keyspace(KEYSPACE)
        session.execute("CREATE TABLE IF NOT EXISTS tb (pk bigint, date timestamp, ck text, c1 counter, PRIMARY KEY (pk, date, ck));")

        session.execute("UPDATE tb SET c1 = SCYLLA_COUNTER_SHARD_LIST([(103, d432e37a-a190-4689-8bda-b3ba4973bc2e, 1, 1)])  WHERE pk = 1 AND date = 1549640927943017 AND ck = 'test';")
        update_statement = session.prepare("UPDATE tb SET c1 = SCYLLA_COUNTER_SHARD_LIST(?)  WHERE pk = ? AND date = ? AND ck = ?")
        session.execute(update_statement, ([(103,uuid.UUID('d432e37aa19046898bdab3ba4973bc2e'),1, 1)],  1 ,1549640927943018,'test'));
        assert_one(session, 'select count(*) from tb', [2])
```

So the issue in the sample above could be an illegal prepared statement.

**Comment by slivne** [comment]
If the crashing code is changed to the following:

```
        update_statement = session.prepare("UPDATE tb SET c1 = SCYLLA_COUNTER_SHARD_LIST([(?,?,?,?)])  WHERE pk = ? AND date = ? AND ck = ?")
        session.execute(update_statement, (103, 0xd432e37aa19046898bdab3ba4973bc2e, 1, 1, 1,1549640927943018,'test'));

```

we get an error back 

```
Traceback (most recent call last):
  File "/home/shlomi/scylla-dtest/prepared_statements_test.py", line 63, in test1
    update_statement = session.prepare("UPDATE tb SET c1 = SCYLLA_COUNTER_SHARD_LIST([(?,?,?,?)])  WHERE pk = ? AND date = ? AND ck = ?")
  File "cassandra/cluster.py", line 2218, in cassandra.cluster.Session.prepare (cassandra/cluster.c:38461)
    log.exception("Error preparing query:")
  File "cassandra/cluster.py", line 2215, in cassandra.cluster.Session.prepare (cassandra/cluster.c:38317)
    future.send_request()
  File "cassandra/cluster.py", line 3781, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:73073)
    if self._final_result is not _NOT_SET:
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid list literal for c1: bind variables are not supported inside collection literals"
```
