### ISSUE TITLE
Scylla doesn't configure on Ubuntu 18.04

### ISSUE THREAD

**Issue by hakuch** [scylladb/scylla#4218]
Observed with: 85e579171057b9d97c4c4f8d6fd98eae0be89410

```
$ ./configure.y --mode=release
Package seastar was not found in the pkg-config search path.
Perhaps you should add the directory containing `seastar.pc'
to the PKG_CONFIG_PATH environment variable
Package 'seastar', required by '/seastar-testing', not found
Traceback (most recent call last):
  File "./configure.py", line 1233, in <module>
    local_libs += ' ' + pkg_config(pc_path, '--libs', '--static')
  File "./configure.py", line 100, in pkg_config
    output = subprocess.check_output(['pkg-config'] + list(options) + [package])
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pkg-config', '--libs', '--static', 'seastar/build/release/seastar-testing.pc']' returned non-zero exit status 1.
```

**Comment by hakuch** [comment]
The reason for the failure is a difference in the way that the `pkg-config` executable behaves on Fedora and Ubuntu. On Fedora, the executable is provided by the `pkgconf` project. I have a patch ready.
