### ISSUE TITLE
master: fail to install scylla for lack of scylla-python3 dependency

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4252]
*Installation details*
Scylla version (or git commit hash): scylla.x86_64 0:666.development-0.20190217.7b411e30a.el7
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

* Jenkins job: http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/centos-rpm-test/103/label=muninn/artifact/latest/job.log

@glommer Did we push scylla-python to https://copr-be.cloud.fedoraproject.org/results/scylladb/scylla-3rdparty/epel-7-x86_64/?

```
2019-02-18 05:58:39,782 process          L0333 INFO | Running '/bin/yum -y install scylla'
2019-02-18 05:58:39,870 process          L0420 DEBUG| [stdout] Loaded plugins: fastestmirror
2019-02-18 05:58:39,903 process          L0420 DEBUG| [stdout] Loading mirror speeds from cached hostfile
2019-02-18 05:58:39,903 process          L0420 DEBUG| [stdout]  * base: centos.spd.co.il
2019-02-18 05:58:39,903 process          L0420 DEBUG| [stdout]  * epel: ftp.fau.de
2019-02-18 05:58:39,903 process          L0420 DEBUG| [stdout]  * extras: centos.spd.co.il
2019-02-18 05:58:39,903 process          L0420 DEBUG| [stdout]  * updates: centos.spd.co.il
2019-02-18 05:58:40,027 process          L0420 DEBUG| [stdout] Resolving Dependencies
2019-02-18 05:58:40,027 process          L0420 DEBUG| [stdout] --> Running transaction check
2019-02-18 05:58:40,027 process          L0420 DEBUG| [stdout] ---> Package scylla.x86_64 0:666.development-0.20190217.7b411e30a.el7 will be installed
2019-02-18 05:58:40,038 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-tools-core = 666.development for package: scylla-666.development-0.20190217.7b411e30a.el7.x86_64
2019-02-18 05:58:40,173 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-tools = 666.development for package: scylla-666.development-0.20190217.7b411e30a.el7.x86_64
2019-02-18 05:58:40,173 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-server = 666.development for package: scylla-666.development-0.20190217.7b411e30a.el7.x86_64
2019-02-18 05:58:40,173 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-kernel-conf = 666.development for package: scylla-666.development-0.20190217.7b411e30a.el7.x86_64
2019-02-18 05:58:40,173 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-jmx = 666.development for package: scylla-666.development-0.20190217.7b411e30a.el7.x86_64
2019-02-18 05:58:40,174 process          L0420 DEBUG| [stdout] --> Running transaction check
2019-02-18 05:58:40,174 process          L0420 DEBUG| [stdout] ---> Package scylla-jmx.noarch 0:666.development-20190218.27313ee will be installed
2019-02-18 05:58:40,174 process          L0420 DEBUG| [stdout] ---> Package scylla-kernel-conf.x86_64 0:666.development-0.20190217.7b411e30a.el7 will be installed
2019-02-18 05:58:40,174 process          L0420 DEBUG| [stdout] ---> Package scylla-server.x86_64 0:666.development-0.20190217.7b411e30a.el7 will be installed
2019-02-18 05:58:40,634 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-python3 for package: scylla-server-666.development-0.20190217.7b411e30a.el7.x86_64
2019-02-18 05:58:40,634 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-conf for package: scylla-server-666.development-0.20190217.7b411e30a.el7.x86_64
2019-02-18 05:58:40,645 process          L0420 DEBUG| [stdout] ---> Package scylla-tools.noarch 0:666.development-20190218.c908002457 will be installed
2019-02-18 05:58:40,645 process          L0420 DEBUG| [stdout] ---> Package scylla-tools-core.noarch 0:666.development-20190218.c908002457 will be installed
2019-02-18 05:58:40,645 process          L0420 DEBUG| [stdout] --> Running transaction check
2019-02-18 05:58:40,645 process          L0420 DEBUG| [stdout] ---> Package scylla-conf.x86_64 0:666.development-0.20190217.7b411e30a.el7 will be installed
2019-02-18 05:58:40,645 process          L0420 DEBUG| [stdout] ---> Package scylla-server.x86_64 0:666.development-0.20190217.7b411e30a.el7 will be installed
2019-02-18 05:58:40,646 process          L0420 DEBUG| [stdout] --> Processing Dependency: scylla-python3 for package: scylla-server-666.development-0.20190217.7b411e30a.el7.x86_64
2019-02-18 05:58:40,711 process          L0420 DEBUG| [stdout] --> Finished Dependency Resolution
2019-02-18 05:58:40,733 process          L0420 DEBUG| [stderr] Error: Package: scylla-server-666.development-0.20190217.7b411e30a.el7.x86_64 (scylla)
2019-02-18 05:58:40,733 process          L0420 DEBUG| [stderr]            Requires: scylla-python3
2019-02-18 05:58:40,733 process          L0420 DEBUG| [stdout]  You could try using --skip-broken to work around the problem
2019-02-18 05:58:41,111 process          L0420 DEBUG| [stdout]  You could try running: rpm -Va --nofiles --nodigest
2019-02-18 05:58:41,132 stacktrace       L0036 ERROR| 
2019-02-18 05:58:41,132 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
2019-02-18 05:58:41,132 stacktrace       L0042 ERROR| Traceback (most recent call last):
2019-02-18 05:58:41,132 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/centos-rpm-test/label/muninn/scylla-artifacts.py", line 760, in setUp
2019-02-18 05:58:41,133 stacktrace       L0042 ERROR|     self.scylla_setup()
2019-02-18 05:58:41,133 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/centos-rpm-test/label/muninn/scylla-artifacts.py", line 746, in scylla_setup
2019-02-18 05:58:41,133 stacktrace       L0042 ERROR|     installer.run()
2019-02-18 05:58:41,133 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/centos-rpm-test/label/muninn/scylla-artifacts.py", line 339, in run
2019-02-18 05:58:41,133 stacktrace       L0042 ERROR|     raise InstallPackageError(e_msg)
2019-02-18 05:58:41,133 stacktrace       L0042 ERROR| InstallPackageError: Package scylla could not be installed (see logs for details)
```

**Comment by glommer** [comment]
This has to be generated by the build system and it was not a requirement before.

`./reloc/build_python3.sh` can be used for that.

**Comment by slivne** [comment]
@syuu1228 can you try and help its blocking everything

**Comment by slivne** [comment]
probably broken since 367ef8d318abc5b303e66a32372e0d0d318a694d

**Comment by hagitsegev** [comment]
This blocks master as well as enterprise since Feb 15.
Last success build on master was on Jan 22...

**Comment by slivne** [comment]
@syuu1228  / @penberg 
Are there pending patches to fix this ?

Master (3.1) centos rpm's are borken for ~2 weeks now - we need to fix this.

**Comment by syuu1228** [comment]
I was postpone to fix this since I'm trying to change build method of
python rpm on master, but the patchset is still haven't merged yet, so I
changed my mind and trying to fix the jenkins job now.

**Comment by vnnw** [comment]
Any updates?

**Comment by syuu1228** [comment]
Fixed.

**Comment by syuu1228** [comment]
This issue is already fixed, can be close now.

**Comment by amoskong** [comment]
Recent artifact-test jobs are all BLUE (PASS), http://jenkins.scylladb.com/job/scylla-master/job/centos-rpm-test/. Let's close this issue.
