### ISSUE TITLE
repair_multiple_pr_test: Repair session 1 failed

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4267]
scylla version: 0eddf19432d12e68503194852d3183c20e9cf964
scylla-dtest version: 7a15b8f248f2c6ae6d01edc915e379421084d86f

Seen in [dtest-release/40/testReport/repair_additional_test/RepairAdditionalTest/repair_multiple_pr_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/40/testReport/repair_additional_test/RepairAdditionalTest/repair_multiple_pr_test/):
```
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/resources/cassandra/bin/nodetool -h localhost -p 7156 repair ks' failed; exit status: 2; stdout: [2019-02-23 23:27:49,057] Starting repair command #1, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)
[2019-02-23 23:27:51,164] Repair session 1 failed
[2019-02-23 23:27:51,165] Repair session 1 finished
; stderr: error: Repair job has failed with the error message: [2019-02-23 23:27:51,164] Repair session 1 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2019-02-23 23:27:51,164] Repair session 1 failed
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

On [node2.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/40/artifact/logs-release.2/1550964471783_repair_additional_test.RepairAdditionalTest.repair_multiple_pr_test/node2.log):
```
scylla: ../../include/seastar/core/future.hh:511: void seastar::promise<T>::set_value(A&& ...) [with A = {}; T = {}]: Assertion `_state' failed.
Aborting on shard 0.
Backtrace:

$ addr2line -Cfpi -e archive/logs-release.2/scylla 
  0x00000000041bc472
  0x00000000040b50e5
  0x00000000040b53e5
  0x00000000040b5493
  0x00007fb578f3c02f
  /lib64/libc.so.6+0x000000000003853e
  /lib64/libc.so.6+0x0000000000022894
  /lib64/libc.so.6+0x0000000000022768
  /lib64/libc.so.6+0x00000000000309f5
  0x00000000044a13ad
  0x00000000040b24c1
  0x00000000040b26be
  0x000000000418924d
  0x000000000401ea05
  0x00000000009fb5a1
  /lib64/libc.so.6+0x0000000000024412
  0x0000000000a5a39d
...
seastar::continuation<seastar::future<>::then_impl<seastar::rpc::client::client(seastar::rpc::logger const&, void*, seastar::rpc::client_options, seastar::socket, seastar::socket_address const&, seastar::socket_address const&)::{lambda(seastar::connected_socket)#1}::operator()(seastar::connected_socket) const::{lambda()#1}, seastar::future<> >(seastar::rpc::client::client(seastar::rpc::logger const&, void*, seastar::rpc::client_options, seastar::socket, seastar::socket_address const&, seastar::socket_address const&)::{lambda(seastar::connected_socket)#1}::operator()(seastar::connected_socket) const::{lambda()#1}&&)::{lambda(auto:2)#1}>::run_and_dispose() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../include/seastar/core/future.hh:511
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../include/seastar/core/shared_future.hh:259
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/rpc/rpc.cc:652
...
```

**Comment by bhalevy** [comment]
@gleb-cloudius please look into that.
The assert tripped in `negotiate_protocol`

**Comment by slivne** [comment]
seems similar to https://github.com/scylladb/scylla/issues/4316

now you have a core

**Comment by bhalevy** [comment]
Dups #4316
