### ISSUE TITLE
repair_option_pr_dc_host_test timed out

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4292]
scylla version ca288189a9418d15b5beea32c0a4afeb5fd793b7
scylla-dtest version [e6f5a1f1](scylladb/scylla-dtest@e6f5a1f10e618ef3bcbf6d31fcd07be5899d054d)

Seen in [dtest-release/43/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_dc_host_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/43/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_dc_host_test/):
```
Error Message
'repair_option_pr_dc_host_test (repair_additional_test.RepairAdditionalTest)'
Stacktrace
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/.dtest_venv/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 812, in run
    test(orig)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/.dtest_venv/lib/python2.7/site-packages/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/.dtest_venv/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/.dtest_venv/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/usr/lib64/python2.7/unittest/case.py", line 431, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 2459, in repair_option_pr_dc_host_test
    return RepairAdditionalBase._repair_option_pr_dc_host_test(self)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 699, in _repair_option_pr_dc_host_test
    node1_1.repair(['-pr', '-local', 'ks'])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 1213, in repair
    return self.nodetool(cmd, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 703, in nodetool
    stdout, stderr = p.communicate()
  File "/usr/lib64/python2.7/subprocess.py", line 483, in communicate
    return self._communicate(input)
  File "/usr/lib64/python2.7/subprocess.py", line 1124, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib64/python2.7/subprocess.py", line 1178, in _communicate_with_poll
    ready = poller.poll()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/.dtest_venv/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 276, in signalhandler
    raise TimedOutException()
TimedOutException: 'repair_option_pr_dc_host_test (repair_additional_test.RepairAdditionalTest)'
```

There are no logs due to a bug with nosetests timeout exception processing.
Will open a different issue about that.

Keeping this issue for reference in case we hit it again.

**Comment by asias** [comment]
@bhalevy So, this is s dtest issue not scylla, correct?

**Comment by bhalevy** [comment]
Undetermined yet.  We've added facilities in dtest to collect node logs on timeout and cores in case scylla crashed for some reason, so the verdict is still out, until the issue is reproduced.  However we suspect cross-test interference due to stale processes that were left over from previous runs that timed out and weren't cleaned up properly so it's possible this is one of these cases.  If it doesn't reproduce we'll just close it.  Nothing to be actively done at the moment...

**Comment by bhalevy** [comment]
Assuming scylla crashed a-la #4316 so let's close this issues.
