### ISSUE TITLE
scylla-housekeeping causes an error on master/CentOS7

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4345]
Getting backtrace while running housekeeping restart mode.
```
2019-01-23 00:03:11,504 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain systemd[1]: Started Scylla Housekeeping restart mode.
2019-01-23 00:03:11,504 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: Traceback (most recent call last):
2019-01-23 00:03:11,504 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: File "/usr/lib/scylla/scylla-housekeeping", line 183, in <module>
2019-01-23 00:03:11,504 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: args.func(args)
2019-01-23 00:03:11,504 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: File "/usr/lib/scylla/scylla-housekeeping", line 109, in check_version
2019-01-23 00:03:11,504 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
2019-01-23 00:03:11,504 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: File "/usr/lib/scylla/scylla-housekeeping", line 68, in get_api
2019-01-23 00:03:11,505 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: return get_json_from_url("http://" + api_address + path)
2019-01-23 00:03:11,505 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: File "/usr/lib/scylla/scylla-housekeeping", line 64, in get_json_from_url
2019-01-23 00:03:11,505 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: return json.loads(data)
2019-01-23 00:03:11,505 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
2019-01-23 00:03:11,505 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: s.__class__.__name__))
2019-01-23 00:03:11,505 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain scylla-housekeeping[23223]: TypeError: the JSON object must be str, not 'bytes'
2019-01-23 00:03:11,505 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain systemd[1]: scylla-housekeeping-restart.service: main process exited, code=exited, status=1/FAILURE
2019-01-23 00:03:11,505 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain systemd[1]: Unit scylla-housekeeping-restart.service entered failed state.
2019-01-23 00:03:11,505 process          L0420 DEBUG| [stdout] Jan 23 00:03:01 localhost.localdomain systemd[1]: scylla-housekeeping-restart.service failed.
```

**Comment by slivne** [comment]
@amnonh can you please look at this

**Comment by amnonh** [comment]
It's already been solved by: 
https://github.com/scylladb/scylla/commit/750b76b1de9dc3cafb9ce7cc2cbd428c7eb3f374

**Comment by slivne** [comment]
@amnonh - please validate with the nightly the issue is resolved

**Comment by slivne** [comment]
@amnonh ping

**Comment by amnonh** [comment]
I have validated it with the latest runnable AMI ami-02a3d62127f3b7705
