### ISSUE TITLE
AMI login prompt causes 'No module named yaml' error on master

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4355]
```
ECDSA key fingerprint is SHA256:uYWtDDzzzwfsIygGK26ultA4q0yz2aHnF7BXchBOxsc.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'ec2-3-90-150-88.compute-1.amazonaws.com,3.90.150.88' (ECDSA) to the list of known hosts.
Traceback (most recent call last):
  File "/usr/lib/scylla/scylla-ami/scylla_ami_login", line 26, in <module>
    from scylla_util import *
  File "/usr/lib/scylla/scylla_util.py", line 31, in <module>
    import yaml
ImportError: No module named 'yaml'
```

**Comment by syuu1228** [comment]
This is because we moved to relocatable python, but scylla-ami does not follow the change.

**Comment by glommer** [comment]
We should relocate the AMI scripts as well.

**Comment by tzach** [comment]
@syuu1228 what is the next step?

**Comment by slivne** [comment]
tested

AMI: scylla_2019-06-27T08-16-19Z (ami-087bc859c84c1a13e) Internal
version
3.1.0.rc2-0.20190627.acff367ea


and it seems to work ok

```
Last login: Thu Jun 27 09:43:34 2019 from system.cloudius-systems.com

   _____            _ _       _____  ____  
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        


Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at: 
	http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

    ScyllaDB is active.

$ nodetool status

Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  10.0.0.165  0 bytes    256          ?       7df95fee-ca92-4a8c-9b9c-aa740af89a69  1b

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
This EC2 instance is optimized for Scylla.
```

@syuu1228 can we close this ?

I tried to check if we move the ami to relocatable python could not find a patch.

**Comment by slivne** [comment]
@syuu1228 ping
