### ISSUE TITLE
Cqlsh bundled with Scylla (docker image) fails to display DECIMAL column with 0 value.

### ISSUE THREAD

**Issue by Vinigas** [scylladb/scylla#4374]
Table description:
```
CREATE TABLE mkeyspace.mtable (
    p_id uuid,
    c_id uuid,
    budget decimal,
    count int,
    PRIMARY KEY (p_id, c_id)
) WITH CLUSTERING ORDER BY (c_id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```
This table has row with budget column value of zero (value of C# default decimal).
Then trying to SELECT the column with this query:
`SELECT p_id,c_id,budget FROM mtable;`
I get error in CQLSH:
```
Traceback (most recent call last):
  File "/usr/bin/cqlsh.py", line 1053, in perform_simple_statement
    result = future.result()
  File "/usr/share/scylla/cassandra/lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/cluster.py", line 3925, in result
    raise self._final_exception
DriverException: Failed decoding result column "budget" of type decimal: invalid literal for int() with base 16: ''
```

I am using CQLSH **inside** of Scylla container.

*Installation details*
Scylla version (or git commit hash): Official docker image: scylladb/scylla:3.0.4
Cluster size: 3 master nodes, non-production environment
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker / Debian9-host.

**Comment by slivne** [comment]
@Vinigas I tested the following on 3.0.4 and 3.0.8

```
insert into mtable (p_id, c_id, budget) values (11111111-1111-1111-1111-111111111111,11111111-1111-1111-1111-111111111111,1);
```

and select works

```
SELECT p_id,c_id,budget FROM mykeyspace.mtable ;

 p_id                                 | c_id                                 | budget
--------------------------------------+--------------------------------------+--------
 11111111-1111-1111-1111-111111111111 | 11111111-1111-1111-1111-111111111111 |      1

```

can you please share either the sstables or the values you inserted so we can reproduce this.
```

**Comment by slivne** [comment]
closing this issue no update
