### ISSUE TITLE
On master relocatable python3, https access causes URLError

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4396]
On master/centos-rpm-test, we are getting "urllib.error.URLError: <urlopen error unknown url type: https>" with node_exporter_install.
It should be able to run without error, so I guess we are breaking python3 environment for some reason.
@glommer Is the script able to run when you merged relocatable python3 patchset? Maybe I did break something while modifying the build script?

http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/centos-rpm-test/label=muninn/lastCompletedBuild/artifact/latest/job.log

```
2019-04-03 12:34:55,013 process          L0420 DEBUG| [stderr] Traceback (most recent call last):
2019-04-03 12:34:55,013 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/libexec/node_exporter_install", line 58, in <module>
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]     data = curl('https://github.com/prometheus/node_exporter/releases/download/v{version}/node_exporter-{version}.linux-amd64.tar.gz'.format(version=VERSION), byte=True)
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_util.py", line 40, in curl
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]     with urllib.request.urlopen(req) as res:
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 222, in urlopen
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]     return opener.open(url, data, timeout)
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 525, in open
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]     response = self._open(req, data)
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 548, in _open
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]     'unknown_open', req)
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 503, in _call_chain
2019-04-03 12:34:55,014 process          L0420 DEBUG| [stderr]     result = func(*args)
2019-04-03 12:34:55,015 process          L0420 DEBUG| [stderr]   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1387, in unknown_open
2019-04-03 12:34:55,015 process          L0420 DEBUG| [stderr]     raise URLError('unknown url type: %s' % type)
2019-04-03 12:34:55,015 process          L0420 DEBUG| [stderr] urllib.error.URLError: <urlopen error unknown url type: https>
2019-04-03 12:34:55,021 process          L0420 DEBUG| [stdout] Unable to retrieve version information
2019-04-03 12:34:55,021 process          L0420 DEBUG| [stdout] node exporter setup failed.
```

**Comment by avikivity** [comment]
You can try `strace -o /tmp/trace.txt -e trace=file python3 -c "import urllib.request; urllib.request.urlopen('https://google.com')"`, it will show you which file access failed.

**Comment by glommer** [comment]
I've seen this before, and if my memory doesn't trick me it's a python2 vs
python3 issue -> because urrllib is different between them.
I had that issue (or similar) when first trying scyllatop  before avi
converted it.

**Comment by amoskong** [comment]
duplicated with #4391

**Comment by syuu1228** [comment]
@amoskong I think it doesn't seems duplicate issue, #4391 is "ConnectionResetError: [Errno 104] Connection reset by peer" it's another exception, and it's usually network issue. Also we use different version of python3 interpreter now (we haven't switched relocatable python3 on Debian variants yet).

**Comment by amoskong** [comment]
OK.

**Comment by tzach** [comment]
@syuu1228 should move node_exporter_install to Python3 solve the problem?

**Comment by amoskong** [comment]
It had been converted to python3

**Comment by glommer** [comment]
It seems to be referring to local libssl :

```
openat(AT_FDCWD, "/lib64/tls/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib64/tls/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib64/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

Although we do ship libssl in the relocatable interpreter:

```
$ find /opt/scylladb/python3/ | grep libssl
/opt/scylladb/python3/lib64/.libssl.so.1.1.1b.hmac
/opt/scylladb/python3/lib64/.libssl.so.1.1.hmac
/opt/scylladb/python3/lib64/libssl.so.1.1
/opt/scylladb/python3/lib64/libssl.so.1.1.1b
```

I will investigate why

**Comment by glommer** [comment]
The problem is that our code checks for x-sharedlib as a mime type for so to relocate shared libraries, but Fedora29's pymagic is returning application/x-pie-executable.

So libraries don't get relocated. I will send a patch

**Comment by jonmorton** [comment]
how can I get around this error on a release version of scylla?
