### ISSUE TITLE
On Ubuntu 18.04 artifacts test for master fails with "Please upgrade to a newer kernel version"

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4397]
This is strange, since Ubuntu 18.04 should have AIO capable kernel by default.
(Note: we haven't switched to relocatable python on Debian variants, so that's not related with relocatable python)
```
2019-04-03 04:40:24,742 process          L0420 DEBUG| [stdout] Please upgrade to a newer kernel version.
2019-04-03 04:40:24,742 process          L0420 DEBUG| [stdout]  see http://www.scylladb.com/kb/kb-fs-not-qualified-aio/ for details
2019-04-03 04:40:24,755 process          L0420 DEBUG| [stderr] Traceback (most recent call last):
2019-04-03 04:40:24,755 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_setup", line 236, in <module>
2019-04-03 04:40:24,755 process          L0420 DEBUG| [stderr]     run('/usr/lib/scylla/scylla_kernel_check')
2019-04-03 04:40:24,755 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_util.py", line 276, in run
2019-04-03 04:40:24,755 process          L0420 DEBUG| [stderr]     return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
2019-04-03 04:40:24,756 process          L0420 DEBUG| [stderr]   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
2019-04-03 04:40:24,756 process          L0420 DEBUG| [stderr]     raise CalledProcessError(retcode, cmd)
2019-04-03 04:40:24,756 process          L0420 DEBUG| [stderr] subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla_kernel_check']' returned non-zero exit status 252.
2019-04-03 04:40:24,768 stacktrace       L0036 ERROR| 
2019-04-03 04:40:24,768 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:436
2019-04-03 04:40:24,794 stacktrace       L0042 ERROR| Traceback (most recent call last):
2019-04-03 04:40:24,794 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/ubuntu-deb-18.04-test/label/huginn/scylla-artifacts.py", line 765, in setUp
2019-04-03 04:40:24,794 stacktrace       L0042 ERROR|     self.scylla_setup()
2019-04-03 04:40:24,794 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/ubuntu-deb-18.04-test/label/huginn/scylla-artifacts.py", line 751, in scylla_setup
2019-04-03 04:40:24,794 stacktrace       L0042 ERROR|     installer.run()
2019-04-03 04:40:24,795 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/ubuntu-deb-18.04-test/label/huginn/scylla-artifacts.py", line 370, in run
2019-04-03 04:40:24,795 stacktrace       L0042 ERROR|     process.run(setup_cmd, shell=True, verbose=True, timeout=600)
2019-04-03 04:40:24,795 stacktrace       L0042 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 1031, in run
2019-04-03 04:40:24,795 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
2019-04-03 04:40:24,795 stacktrace       L0042 ERROR| CmdError: Command '/usr/lib/scylla/scylla_setup --nic ens2 --disks /dev/sdb --no-cpuscaling-setup' failed (rc=1)
2019-04-03 04:40:24,795 stacktrace       L0043 ERROR| 
```

**Comment by syuu1228** [comment]
Same on Ubuntu 16.04:

http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/ubuntu-deb-16.04-test/label=huginn/80/artifact/latest/job.log
```
2019-04-03 04:30:39,573 process          L0333 INFO | Running '/usr/lib/scylla/scylla_setup --nic ens3 --disks /dev/vdb --no-cpuscaling-setup'
2019-04-03 04:30:42,608 process          L0420 DEBUG| [stdout] Please upgrade to a newer kernel version.
2019-04-03 04:30:42,608 process          L0420 DEBUG| [stdout]  see http://www.scylladb.com/kb/kb-fs-not-qualified-aio/ for details
2019-04-03 04:30:42,682 process          L0420 DEBUG| [stderr] Traceback (most recent call last):
2019-04-03 04:30:42,682 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_setup", line 236, in <module>
2019-04-03 04:30:42,683 process          L0420 DEBUG| [stderr]     run('/usr/lib/scylla/scylla_kernel_check')
2019-04-03 04:30:42,683 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_util.py", line 276, in run
2019-04-03 04:30:42,683 process          L0420 DEBUG| [stderr]     return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
2019-04-03 04:30:42,683 process          L0420 DEBUG| [stderr]   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
2019-04-03 04:30:42,683 process          L0420 DEBUG| [stderr]     raise CalledProcessError(retcode, cmd)
2019-04-03 04:30:42,683 process          L0420 DEBUG| [stderr] subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla_kernel_check']' returned non-zero exit status 252
2019-04-03 04:30:42,712 stacktrace       L0036 ERROR| 
2019-04-03 04:30:42,716 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado-36.3-py2.7.egg/avocado/core/test.py:436
2019-04-03 04:30:42,729 stacktrace       L0042 ERROR| Traceback (most recent call last):
2019-04-03 04:30:42,730 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/ubuntu-deb-16.04-test/label/huginn/scylla-artifacts.py", line 765, in setUp
2019-04-03 04:30:42,730 stacktrace       L0042 ERROR|     self.scylla_setup()
2019-04-03 04:30:42,730 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/ubuntu-deb-16.04-test/label/huginn/scylla-artifacts.py", line 751, in scylla_setup
2019-04-03 04:30:42,730 stacktrace       L0042 ERROR|     installer.run()
2019-04-03 04:30:42,730 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/ubuntu-deb-16.04-test/label/huginn/scylla-artifacts.py", line 370, in run
2019-04-03 04:30:42,730 stacktrace       L0042 ERROR|     process.run(setup_cmd, shell=True, verbose=True, timeout=600)
2019-04-03 04:30:42,730 stacktrace       L0042 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado-36.3-py2.7.egg/avocado/utils/process.py", line 1031, in run
2019-04-03 04:30:42,730 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
2019-04-03 04:30:42,730 stacktrace       L0042 ERROR| CmdError: Command '/usr/lib/scylla/scylla_setup --nic ens3 --disks /dev/vdb --no-cpuscaling-setup' failed (rc=1)
2019-04-03 04:30:42,730 stacktrace       L0043 ERROR| 
2019-04-03 04:30:42,738 test             L0581 ERROR| ERROR 1-/root/avocado/tests/jenkins/slave/workspace/scylla-master/ubuntu-deb-16.04-test/label/huginn/scylla-artifacts.py:ScyllaArtifactSanity.test_after_install -> TestSetupFail: Command '/usr/lib/scylla/scylla_setup --nic ens3 --disks /dev/vdb --no-cpuscaling-setup' failed (rc=1)
2019-04-03 04:30:42,739 test             L0568 INFO | 
```

**Comment by syuu1228** [comment]
@amoskong Any idea?

**Comment by amoskong** [comment]
duplicated with issue #4392

**Comment by amoskong** [comment]
I think it's problem of verify code itself, I will check manually.

**Comment by syuu1228** [comment]
closing since it duplicated with #4392
