### ISSUE TITLE
reloc/python3/build_reloc.sh does not able to build after python3-psutil added

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4415]
It seems like after merged 2305cc88f30fffaf0f7064627e4a4cd111f076ac, create-relocatable-package-python3.py tries to call fix_binary() on non-ELF binary like  /usr/lib64/python3.7/\_\_pycache\_\_/dummy_threading.cpython-37.opt-1.pyc, then causes "not an ELF executable".
@glommer Please take a look.

```
01:24:51 666.development-0.20190407.6191fd770
01:24:51 'build/python3/SCYLLA-RELEASE-FILE' => 'build/SCYLLA-RELEASE-FILE'
01:24:53 not an ELF executable
01:24:53 Traceback (most recent call last):
01:24:53   File "./scripts/create-relocatable-package-python3.py", line 238, in <module>
01:24:53     copy_file_to_python_env(ar, f)
01:24:53   File "./scripts/create-relocatable-package-python3.py", line 161, in copy_file_to_python_env
01:24:53     fix_sharedlib(ar, f, libfile)
01:24:53   File "./scripts/create-relocatable-package-python3.py", line 104, in fix_sharedlib
01:24:53     patched_binary = fix_binary(ar, binpath, '$ORIGIN/' + relpath)
01:24:53   File "./scripts/create-relocatable-package-python3.py", line 85, in fix_binary
01:24:53     patched_elf])
01:24:53   File "/usr/lib64/python3.7/subprocess.py", line 347, in check_call
01:24:53     raise CalledProcessError(retcode, cmd)
01:24:53 subprocess.CalledProcessError: Command '['patchelf', '--set-rpath', '$ORIGIN/../../../../lib64', '/tmp/tmpwgeuktwr']' returned non-zero exit status 1.
```

**Comment by syuu1228** [comment]
@glommer It seems to skip application/octet-stream fixes the problem, sent a patch on ML "[PATCH scylla] reloc: skip running fix_sharedlib() on application/octet-stream files"

**Comment by glommer** [comment]
I wonder how that worked for me? I have .pyc files in my tree as well.
