### ISSUE TITLE
scylla_setup/scylla_prepare does not works on Amazon Linux 2 (master branch)

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4437]
Since we switched relocatable binary we are able to run Scylla on Amazon Linux 2 now, but scylla_setup does not works correctly on the environment.

```
Do you want to verify the ScyllaDB packages are installed?
Yes - runs a script to confirm that ScyllaDB is installed. No - skips the installation check.
[YES/no]
Traceback (most recent call last):
  File "/usr/lib/scylla/libexec/scylla_setup", line 241, in <module>
    do_verify_package('scylla-jmx')
  File "/usr/lib/scylla/libexec/scylla_setup", line 98, in do_verify_package
    if res != 0:
UnboundLocalError: local variable 'res' referenced before assignment
```

```
Do you want to enable Network Interface Card (NIC) and disk(s) optimization?
Yes - optimize the NIC queue and disks settings. Selecting Yes greatly improves performance. No - skip this step.
[yes/NO]
Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 'SET_NIC_AND_DISKS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/scylla/scylla_util.py", line 490, in get_set_nic_and_disks_config_value
    return cfg.get('SET_NIC_AND_DISKS')
  File "/usr/lib/scylla/scylla_util.py", line 557, in get
    return self._cfg.get('global', key).strip('"')
  File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'SET_NIC_AND_DISKS' in section: 'global'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 'SET_NIC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/scylla/libexec/scylla_sysconfig_setup", line 44, in <module>
    set_nic_and_disks = str2bool(get_set_nic_and_disks_config_value(cfg))
  File "/usr/lib/scylla/scylla_util.py", line 493, in get_set_nic_and_disks_config_value
    return cfg.get('SET_NIC')
  File "/usr/lib/scylla/scylla_util.py", line 557, in get
    return self._cfg.get('global', key).strip('"')
  File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'SET_NIC' in section: 'global'
NIC queue setup failed. Press any key to continue...
```

scylla_prepare also causes traceback:
```
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: Traceback (most recent call last):
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 788, in get
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: value = d[option]
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 914, in __getitem__
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: return self.__missing__(key)            # support subclasses that define __missing__
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 906, in __missing__
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: raise KeyError(key)
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: KeyError: 'AMI'
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: During handling of the above exception, another exception occurred:
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: Traceback (most recent call last):
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: File "/usr/lib/scylla/libexec/scylla_prepare", line 36, in <module>
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: ami = cfg.get('AMI')
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: File "/usr/lib/scylla/scylla_util.py", line 557, in get
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: return self._cfg.get('global', key).strip('"')
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 791, in get
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: raise NoOptionError(option, section)
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal scylla_prepare[5440]: configparser.NoOptionError: No option 'AMI' in section: 'global'
Apr 16 12:14:29 ip-172-16-99-138.ec2.internal systemd[1]: scylla-server.service: control process exited, code=exited status=1
```

**Comment by syuu1228** [comment]
Not sure which change causes the difference, but with current master it just able to launch in Amazon Linux 2.
