### ISSUE TITLE
scylla startup failing on master AMI

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4443]
Tested with scylla_2019-04-18T10-11-36Z (ami-065d1da1f1ffae271) on i3.4xlarge

It seems invalid parameter passed to perftune.py in scylla_prepare script.

```
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: usage: perftune.py [-h] [--mode {sq_split,sq,mq}] [--nic NIC] [--get-cpu-mask]
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: [--verbose] [--tune {disks,net}] [--cpu-mask MASK]
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: [--dir DIRS] [--dev DEVS] [--options-file OPTIONS_FILE]
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: [--dump-options-file]
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: perftune.py: error: argument --mode: invalid choice: 'None' (choose from 'sq_split', 'sq', 'mq')
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: Traceback (most recent call last):
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: File "/usr/lib/scylla/libexec/scylla_prepare", line 69, in <module>
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: create_perftune_conf(ifname)
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: File "/usr/lib/scylla/scylla_util.py", line 465, in create_perftune_conf
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: yaml = out('/usr/lib/scylla/perftune.py --tune net --nic "{nic}" --mode {mode} --dump-options-file'.format(nic=nic, mode=mode))
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: File "/usr/lib/scylla/scylla_util.py", line 296, in out
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: return subprocess.check_output(cmd, shell=shell, env=scylla_env).strip().decode('utf-8')
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 395, in check_output
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: **kwargs).stdout
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 487, in run
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: output=stdout, stderr=stderr)
Apr 18 11:46:09 ip-172-16-99-42.ec2.internal scylla_prepare[6130]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/perftune.py', '--tune', 'net', '--nic', 'eth0', '--mode', 'None', '--dump-options-file']' returned non-zero exit status 2.
```

**Comment by syuu1228** [comment]
After added some debug code on setup scripts, I found perftune.py is causing traceback inside of get_mode_cpuset() function, but it was suppressed since we redirected stderr=subprocess.DEVNULL.
The traceback actually says it does not able to find hwloc-calc command, witch is recently become relocatable binary (75a7859).
So the issue is likely PATH problem on perftune.py, because relocatable CLIs are on /opt/scylladb/bin/, we need add it PATH before execute the command.
We did it in other scylla_*_setup scripts, but probably not in perftune.py since it is part of Seastar.

I also think redirecting stderr to /dev/null was mistake, it become harder to find out root cause of a problem.
```
Traceback (most recent call last):
  File "/usr/lib/scylla/libexec/perftune.py", line 1164, in <module>
    args.cpu_mask = run_hwloc_calc(['all'])
  File "/usr/lib/scylla/libexec/perftune.py", line 41, in run_hwloc_calc
    return run_one_command(['hwloc-calc'] + prog_args).rstrip()
  File "/usr/lib/scylla/libexec/perftune.py", line 22, in run_one_command
    proc = subprocess.Popen(prog_args, stdout = subprocess.PIPE, stderr = my_stderr)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hwloc-calc': 'hwloc-calc'
```

**Comment by avikivity** [comment]
3.1 was the first release to use relocatable packages, and this is in 3.1, so no need to backport.
