### ISSUE TITLE
calling `nodetool upgradesstables` without parameters or with specific keyspace is failing 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#4525]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 0.20190604.cbaea172c (master)
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu (relocatable package)

calling like `nodetool upgradesstables -a` works
calling `nodetool upgradesstables ks cf` or  `nodetool upgradesstables` fails like this:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/fruch/Projects/scylla-dtest/migration_test.py", line 52, in migrate_sstable_without_compression_upgradesstable_test
    node1.nodetool("upgradesstables")
  File "/home/fruch/Projects/scylla-dtest/.venv/src/ccm/ccmlib/node.py", line 714, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
NodetoolError: Nodetool command '/home/fruch/.ccm/scylla-repository/unstable/master/265/scylla-java-tools/bin/nodetool -h localhost -p 7100 upgradesstables' failed; exit status: 2; stderr: error: Scylla API server HTTP GET to URL '/storage_service/keyspace_upgrade_sstables/ks' failed: exclude_current_version (true): type error - should be bool
-- StackTrace --
java.lang.IllegalStateException: Scylla API server HTTP GET to URL '/storage_service/keyspace_upgrade_sstables/ks' failed: exclude_current_version (true): type error - should be bool
	at com.scylladb.jmx.api.APIClient.getException(APIClient.java:135)
	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:178)
	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:192)
	at com.scylladb.jmx.api.APIClient.getIntValue(APIClient.java:229)
	at org.apache.cassandra.service.StorageService.upgradeSSTables(StorageService.java:660)
	at org.apache.cassandra.service.StorageService.upgradeSSTables(StorageService.java:1678)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.scylladb.jmx.utils.APIMBeanServer.invoke(APIMBeanServer.java:168)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fruch** [comment]
@slivne @elcallio am I missing something on how this command should it should work ? 

smells  to me a bit like default values aren't configured correctly, couldn't figure out where exactly on scylla's end or jmx/nodetool end...

I'm working on creating a dtest for it, I'll supply a branch with the test that failing.

@roydahan FYI

**Comment by elcallio** [comment]
The problem is in api.hh "req_param". It uses boost::lexical cast, which does _not_ work for "textual" bool (true/false).  Weird this has not been spotted before.
