### ISSUE TITLE
scylla install wrong java version on ubuntu 18.04

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#4548]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1-rc1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI):Ubuntu 18.04

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): GCE

openjdk-11-jre-headless is getting installed insted of openjdk-8-jre-headless

```bash
fruch@fruch-syclla-ubuntu-18:~$ sudo apt-get install scylla                                                                                                                   
Reading package lists... Done                                                                                                                                                 
Building dependency tree                                                                                                                                                      
Reading state information... Done                                                                                                                                             
The following package was automatically installed and is no longer required:                                                                                                  
  grub-pc-bin                                                                                                                                                                 
Use 'sudo apt autoremove' to remove it.                                                                                                                                       
The following additional packages will be installed:                                                                                                                          
  default-jre-headless hwloc-nox libasound2 libasound2-data libhwloc-plugins libhwloc5 libltdl7 libpciaccess0 libpython-stdlib libpython2.7-minimal libpython2.7-stdlib       
  num-utils ocl-icd-libopencl1 openjdk-11-jre-headless python python-minimal python-yaml python2.7 python2.7-minimal scylla-conf scylla-jmx scylla-kernel-conf                
  scylla-python3 scylla-server scylla-tools scylla-tools-core                                                                                                                 
Suggested packages:                                                                                                                                                           
  default-jre libasound2-plugins alsa-utils libhwloc-contrib-plugins opencl-icd libnss-mdns fonts-dejavu-extra fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei   
  | fonts-wqy-zenhei fonts-indic python-doc python-tk python2.7-doc binutils binfmt-support                                                                                   
The following NEW packages will be installed:                                                                                                                                 
  default-jre-headless hwloc-nox libasound2 libasound2-data libhwloc-plugins libhwloc5 libltdl7 libpciaccess0 libpython-stdlib libpython2.7-minimal libpython2.7-stdlib       
  num-utils ocl-icd-libopencl1 openjdk-11-jre-headless python python-minimal python-yaml python2.7 python2.7-minimal scylla scylla-conf scylla-jmx scylla-kernel-conf         
  scylla-python3 scylla-server scylla-tools scylla-tools-core                                                                                                                 
0 upgraded, 27 newly installed, 0 to remove and 0 not upgraded.                
```

this make `nodetool staus` fail like this:
```bash
fruch@fruch-syclla-ubuntu-18:~$ nodetool status
error: null
-- StackTrace --
java.lang.NullPointerException
        at org.apache.cassandra.config.DatabaseDescriptor.getDiskFailurePolicy(DatabaseDescriptor.java:1881)
        at org.apache.cassandra.utils.JVMStabilityInspector.inspectThrowable(JVMStabilityInspector.java:82)
        at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:79)
        at org.apache.cassandra.utils.FBUtilities.getToolsOutputDirectory(FBUtilities.java:824)
        at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:204)
        at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:170)
```

a workaround is running this after scylla install: 
```bash
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install -y openjdk-8-jre-headless
sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
```

**Comment by fruch** [comment]
I guessing `default-jre-headless` was updated on 18.04, we need to be more specific

**Comment by slivne** [comment]
https://github.com/scylladb/scylla/issues/4456#issuecomment-493746263
