### ISSUE TITLE
3.1 upgrade failed to start due to scylla_prepare calling perftune.py with --mode None

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#4553]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):  3.1rc1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

I have a test server where Scylla 2.3 had been installed on the OS and scylla 3.0.4 was running in a docker container.  I tried upgrading the OS version of scylla to 3.1 RC1 and then stopping the docker container and then starting the new 3.1 RC1 version.  I ran scylla_setup with no errors.  However, the service subsequently failed to start.  I found the following error in the journalctl output:

```
Jun 13 12:08:55 services scylla_prepare[13136]: usage: perftune.py [-h] [--mode {sq_split,sq,mq}] [--nic NIC] [--get-cpu-mask]
Jun 13 12:08:55 services scylla_prepare[13136]:                    [--tune {disks,net}] [--cpu-mask MASK] [--dir DIRS]
Jun 13 12:08:55 services scylla_prepare[13136]:                    [--dev DEVS] [--options-file OPTIONS_FILE]
Jun 13 12:08:55 services scylla_prepare[13136]:                    [--dump-options-file]
Jun 13 12:08:55 services scylla_prepare[13136]: perftune.py: error: argument --mode: invalid choice: 'None' (choose from 'sq_split', 'sq', 'mq')
Jun 13 12:08:55 services scylla_prepare[13136]: Traceback (most recent call last):
Jun 13 12:08:55 services scylla_prepare[13136]:   File "/usr/lib/scylla/scylla_prepare", line 68, in <module>
Jun 13 12:08:55 services scylla_prepare[13136]:     create_perftune_conf(ifname)
Jun 13 12:08:55 services scylla_prepare[13136]:   File "/usr/lib/scylla/scylla_util.py", line 389, in create_perftune_conf
Jun 13 12:08:55 services scylla_prepare[13136]:     yaml=out('/usr/lib/scylla/perftune.py --tune net --nic "{nic}" --mode {mode} --dump-options-file'.format(nic=nic, mode=mode))
Jun 13 12:08:55 services scylla_prepare[13136]:   File "/usr/lib/scylla/scylla_util.py", line 272, in out
Jun 13 12:08:55 services scylla_prepare[13136]:     return subprocess.check_output(cmd, shell=shell).strip().decode('utf-8')
Jun 13 12:08:55 services scylla_prepare[13136]:   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
Jun 13 12:08:55 services scylla_prepare[13136]:     **kwargs).stdout
Jun 13 12:08:55 services scylla_prepare[13136]:   File "/usr/lib/python3.5/subprocess.py", line 708, in run
Jun 13 12:08:55 services scylla_prepare[13136]:     output=stdout, stderr=stderr)
Jun 13 12:08:55 services scylla_prepare[13136]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/perftune.py', '--tune', 'net', '--nic', 'eth0', '--mode', 'None', '--dump-options-file']' returned non-zero exit status 2
Jun 13 12:08:55 services systemd[1]: scylla-server.service: Control process exited, code=exited status=1
Jun 13 12:08:55 services systemd[1]: Failed to start Scylla Server.
Jun 13 12:08:55 services systemd[1]: scylla-server.service: Unit entered failed state.
Jun 13 12:08:55 services systemd[1]: scylla-server.service: Failed with result 'exit-code'.
```

I wonder if maybe this is using an old version of scylla_prepare?

```
$ ls -l scylla_prepare
-rwxr-xr-x 1 root root 2689 Sep 17  2018 scylla_prepare
```

Not sure if that is supposed to get updated as part of the apt-get package install or setup...

**Comment by glommer** [comment]
If you are not surprised to see the first user bug in an -rc coming from Veramine like this comment

**Comment by roydahan** [comment]
Not sure I fully understand the setup, but IIUC there is a known issue with 3.1.RC1 docker.
https://github.com/scylladb/scylla/issues/4536

**Comment by glommer** [comment]
doesn't look like the same issue, Roy

**Comment by veramine** [comment]
Nah, I hit that issue as well but chown -R to the rescue.

In this case, I had to change the /etc/defaults/scylla-server SET_NIC="no" to get scylla to start. 

I think the repro is somehow related to a combination of the cpuset and --smp we are using.  I see some conditional usage of the perftune script based on cpuset and in this case we had cpuset=2-4 but I changed it a few times using the script, without success.

**Comment by veramine** [comment]
I figured this out.  It was my problem.  The install never successfully completed.  I used the instructions at https://www.scylladb.com/download/open-source/scylla-ubuntu-16-04/ to apt-get update, apt-get install scylla.  Notice that it even says it is setting up scylla-3.1..

```
ubuntu@ip-172-31-6-38:~$ sudo curl -o /etc/apt/sources.list.d/scylla.list -L http://repositories.scylladb.com/scylla/repo/0f62265227df1b6d6deec36ab4bc5e76/ubuntu/scylladb-3.1-xenial.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   183  100   183    0     0   1292      0 --:--:-- --:--:-- --:--:--  1297
100   221  100   221    0     0    246      0 --:--:-- --:--:-- --:--:--     0

ubuntu@ip-172-31-6-38:~$ sudo apt-get update
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease                         
Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease                       
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                               
Get:5 http://ppa.launchpad.net/scylladb/ppa/ubuntu xenial InRelease [24.3 kB]
Get:6 https://repositories.scylladb.com/scylla/downloads/scylladb/0f62265227df1b6d6deec36ab4bc5e76/scylla/deb/ubuntu/scylladb-3.1 xenial InRelease [928 B]
Fetched 28.0 kB in 1s (23.1 kB/s)  
Reading package lists... Done

ubuntu@ip-172-31-6-38:~$ sudo apt-get install scylla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  scylla
1 upgraded, 0 newly installed, 0 to remove and 117 not upgraded.
Need to get 14.4 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://repositories.scylladb.com/scylla/downloads/scylladb/0f62265227df1b6d6deec36ab4bc5e76/scylla/deb/ubuntu/scylladb-3.1 xenial/multiverse amd64 scylla amd64 3.1.0.rc1-0.20190610.224f9cee7-1 [14.4 kB]
Fetched 14.4 kB in 1s (10.9 kB/s)
(Reading database ... 53912 files and directories currently installed.)
Preparing to unpack .../scylla_3.1.0.rc1-0.20190610.224f9cee7-1_amd64.deb ...
Unpacking scylla (3.1.0.rc1-0.20190610.224f9cee7-1) over (3.0.7-0.20190527.4c16c1fe1-0ubuntu1~xenial) ...
Setting up scylla (3.1.0.rc1-0.20190610.224f9cee7-1) ...
```

But when I actually run it, it is still the old version:

```
ubuntu@ip-172-31-6-38:~$ scylla --version
2.3.5-0.20190417.0e0f9143c
```

The trick is to do apt-get install scylla-server:

```
ubuntu@ip-172-31-6-38:~$ sudo apt-get install scylla-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  hugepages libcrypto++9v5 libgnutlsxx28 libhugetlbfs0 libjsoncpp1 libprotobuf9v5 libsnappy1v5 python-cffi-backend python-chardet python-cryptography python-enum34
  python-idna python-ipaddress python-ndg-httpsclient python-openssl python-pkg-resources python-pyasn1 python-requests python-six python-urllib3 python-urwid
  python3-pyudev scylla-gcc73-libstdc++6
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  num-utils scylla-python3
The following NEW packages will be installed:
  num-utils scylla-python3
The following packages will be upgraded:
  scylla-server
1 upgraded, 2 newly installed, 0 to remove and 116 not upgraded.
Need to get 44.9 MB of archives.
After this operation, 122 MB of additional disk space will be used.
Do you want to continue? [Y/n]  
```

And then it worked.

**Comment by slivne** [comment]
@syuu1228 ? do we have an issue with packaging AFAIL upgrading Scylla should have worked

**Comment by syuu1228** [comment]
@slivne With Debian package manager and our .deb packages, we never able to upgrade packages with "apt-get install scylla".
The command just tries to upgrade scylla metapackage, never upgrade scylla-* packages.
On our upgrade document we suggest to use "apt-get dist-upgrade scylla", I think that is the only way to do upgrade correctly:
https://docs.scylladb.com/upgrade/upgrade-opensource/upgrade-guide-from-2.3-to-3.0/upgrade-guide-from-2.3-to-3.0-ubuntu-16-04/

**Comment by veramine** [comment]
This might be an issue with the state of my particular test server but I prefer upgrading via

```
$ sudo apt-get install scylla-\*
```

I tried that "apt-get dist-upgrade scylla" suggestion and apt-get wants to install and upgrade a ton of packages, as you can see below.  When I upgrade using install scylla with the wildcard, I get just the two updated packages (scylla-server scylla-server-dbg) that I wanted.

![distrupgrade](https://user-images.githubusercontent.com/26036714/59796430-562a3d00-9292-11e9-8e21-b8273993f6a2.jpeg)

**Comment by slivne** [comment]
@veramine - can you validate using the procedure we provided - it works in our testing.

If it does - we will need to stick to that

**Comment by slivne** [comment]
@veramine closing this issue

**Comment by veramine** [comment]
ok thanks
