### ISSUE TITLE
repair_with_down_nodes_2b_test fails assertEqual(len(result), 2000)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4616]
Starting [dtest-release/159/testReport/repair_additional_test/RepairAdditionalTest/repair_with_down_nodes_2b_test](http://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/159/testReport/repair_additional_test/RepairAdditionalTest/repair_with_down_nodes_2b_test/)
Scylla version 94d2194c771dfc2fb260b00f7f525b8089092b41
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 2514, in repair_with_down_nodes_2b_test
    return RepairAdditionalBase._repair_with_down_nodes_2b_test(self,more_options)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 1673, in _repair_with_down_nodes_2b_test
    self.assertEqual(len(result), 2000)
  File "/usr/lib64/python2.7/unittest/case.py", line 551, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 544, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1548 != 2000
```

Nodes logs [here](http://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/159/artifact/logs-release.2/1561510645780_repair_additional_test.RepairAdditionalTest.repair_with_down_nodes_2b_test/)

**Comment by bhalevy** [comment]
@asias can you please into this issue?

**Comment by asias** [comment]
I will take a look tomorrow.  Does this fail consistently?

**Comment by bhalevy** [comment]
> I will take a look tomorrow. Does this fail consistently?

Thanks.  Yes. it failed 2 times consecutively on Jenkins dtest-release, and it fails for me locally the same way.  I used the following command (scylla built with dbuild, otherwise just use `nosetests -s -v`):
```
CASSANDRA_DIR=../scylla/build/dev ./scripts/run_test.sh repair_additional_test:RepairAdditionalTest.repair_with_down_nodes_2b_test
```

**Comment by bhalevy** [comment]
Maybe we need to retry...

**Comment by bhalevy** [comment]
Weird.  With the following patch:
```
diff --git a/repair_additional_test.py b/repair_additional_test.py
index 05abf22..876dbd5 100644
--- a/repair_additional_test.py
+++ b/repair_additional_test.py
@@ -1668,9 +1668,20 @@ class RepairAdditionalBase(Tester):
         # on node 4, and if repair was diligent enough, it could repair the
         # 3 living nodes.
         session = self.patient_cql_connection(node2, 'ks')
-        result = list(session.execute("SELECT * from cf"))
-        debug(len(result))
-        self.assertEqual(len(result), 2000)
+        expected = 2000
+        timeout = 60
+        delay = 6
+        result = []
+        while timeout > 0:
+            result = list(session.execute("SELECT * from cf"))
+            actual = len(result)
+            debug(actual)
+            if actual == expected:
+                break
+            time.sleep(delay)
+            timeout = timeout - delay
+
+        self.assertEqual(len(result), expected)
 
     def _repair_abort_test(self):
         """
```

I got the following results:
```
FAIL: repair_with_down_nodes_2b_test (repair_additional_test.RepairAdditionalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 2525, in repair_with_down_nodes_2b_test
    return RepairAdditionalBase._repair_with_down_nodes_2b_test(self,more_options)
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 1684, in _repair_with_down_nodes_2b_test
    self.assertEqual(len(result), expected)
AssertionError: 1497 != 2000
----------------------------------------------------------------------
Ran 1 test in 222.455s
FAILED (failures=1)
2019-06-27 14:46:46.346530 going to run tests sequentially
2019-06-27 14:46:46.346623 using the SingleClusterIdAllocator
2019-06-27 14:46:46.350451 cluster ccm directory: /local/home/bhalevy/.dtest/dtest-fOf86F
2019-06-27 14:46:46.350549 Starting Scylla cluster from directory ../scylla/build/dev
2019-06-27 14:47:33.187407 CREATE COLUMNFAMILY cf (key varchar PRIMARY KEY, c2 text, c1 text) WITH comment='test cf' AND compression = {} AND read_repair_chance=0.000000
2019-06-27 14:49:22.648847 1330
2019-06-27 14:49:27.647172 1490
2019-06-27 14:49:33.702104 1641
2019-06-27 14:49:39.740362 1589
2019-06-27 14:49:45.775447 1494
2019-06-27 14:49:51.829288 1650
2019-06-27 14:49:57.863766 1589
2019-06-27 14:50:03.911697 1494
2019-06-27 14:50:09.960862 1650
2019-06-27 14:50:16.043005 1558
2019-06-27 14:50:22.090167 1497
2019-06-27 14:50:28.097659 tearDown
2019-06-27 14:50:28.478960 tearDown: looking for errors in logs
2019-06-27 14:50:28.483020 tearDown: copying logs
2019-06-27 14:50:28.485759 _cleanup_cluster
2019-06-27 14:50:28.796228 tearDown: looking for errors in logs
2019-06-27 14:50:28.799900 tearDown: copying logs
2019-06-27 14:50:28.802546 _cleanup_cluster
```

**Comment by asias** [comment]
Reproduced with both partition level and row level repair with scylla master commit 2d3e3640df34df4cc086f976262994c9bf5d563e. It is commit bb5665331cbf7df1eb85b8ca70e44d1dea0e6110 (repair: Sync schema from follower nodes before repair) that has changed the behaviour of handling down node during repair.

**Comment by asias** [comment]
Patch is posted: https://github.com/scylladb/scylla/pull/4635

**Comment by slivne** [comment]
@bhalevy the patch was merged can we close this ?

**Comment by bhalevy** [comment]
> @bhalevy the patch was merged can we close this ?

@slivne fix was dequeued due to incorrect Author header.
@asias please resubmit on mailing list (not sure what happened on github)
