### ISSUE TITLE
TestPushedNotifications/restart_node_test: self.get_ip_from_node(node2) == notification["address"][0]

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4717]
Regression first seen in [dtest-release/173/testReport/junit/pushed_notifications_test/TestPushedNotifications/restart_node_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/173/testReport/junit/pushed_notifications_test/TestPushedNotifications/restart_node_test/):
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/pushed_notifications_test.py", line 181, in restart_node_test
    assert self.get_ip_from_node(node2) == notification["address"][0]
AssertionError
```
[dtest.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/173/artifact/logs-release.2/dtest.log):
```
2019-07-11 22:48:45,277 1262    dtest                          DEBUG    | pushed_notifications_test.TestPushedNotifications.restart_node_testrestart_node_test - Restarting second node...
2019-07-11 22:48:45,291 1262    dtest                          DEBUG    | pushed_notifications_test.TestPushedNotifications.restart_node_testrestart_node_test - Source 127.0.10.1 sent {'change_type': u'DOWN', 'address': ('0.0.0.4', 2130708994)}
2019-07-11 22:48:55,964 1262    dtest                          DEBUG    | pushed_notifications_test.TestPushedNotifications.restart_node_testrestart_node_test - Waiting for notifications from 127.0.10.1
...
2019-07-11 22:49:14,887 1262    dtest                          DEBUG    | pushed_notifications_test.TestPushedNotifications.restart_node_testrestart_node_test - Source 127.0.10.1 sent {'change_type': u'UP', 'address': ('0.0.0.4', 2130708994)}
2019-07-11 22:49:14,990 1262    dtest                          DEBUG    | pushed_notifications_test.TestPushedNotifications.restart_node_testrestart_node_test - Test failed
```

Note bad address `0.0.0.4` above.

Introduced in 405fd517b0ee61279512c966f466a33140d20934 (Merge "IPv6 support" from Calle)

A good run, for example, at b4dc118639a455e223cc348159b36067f7009a06, shows:
```
2019-07-15 19:03:42.733263 Source 127.0.40.1 sent {'change_type': u'UP', 'address': ('127.0.40.2', 9042)}
```

**Comment by slivne** [comment]
@elcallio this commit has the ipv6 work - not sure if that changes anything or not.

**Comment by elcallio** [comment]
Looking at it.

**Comment by elcallio** [comment]
Patch sent.

**Comment by avikivity** [comment]
ipv6 is not in any supported branch, no backports needed.

**Comment by dorlaor** [comment]
I created a new ipv6 label since we'll soon have a branch for it
