### ISSUE TITLE
ALTER MATERIALIZED VIEW timeout in test_stop_node_during_index_build

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4724]
Since [next/988](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/988), scylla 997a146c7fe372f7e8d28dbed395349f6af2957d there is a regression in test_stop_node_during_index_build in the next runs (that are running on relatively weak machines).

[next/994/testReport/secondary_indexes_test/TestSecondaryIndexes/test_stop_node_during_index_build](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/994/testReport/secondary_indexes_test/TestSecondaryIndexes/test_stop_node_during_index_build/):
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/secondary_indexes_test.py", line 856, in test_stop_node_during_index_build
    self._node_action_during_index_build(node_action='stop', nodes=4, rf=3, num_rows=100000)
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/secondary_indexes_test.py", line 897, in _node_action_during_index_build
    self.create_index(session, table_name, index_column, index_name, compaction=self.compaction_strategy)
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/dtest.py", line 853, in create_index
    session.execute('ALTER MATERIALIZED VIEW {}_index WITH compaction={}'.format(index_name, {'class': compaction}))
  File "cassandra/cluster.py", line 2141, in cassandra.cluster.Session.execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
OperationTimedOut: errors={'127.0.46.4': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.46.4
```

It's unclear from the node logs why this timeout happened as it is evident that [node4](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/994/artifact/logs-release.2/1563253704509_secondary_indexes_test.TestSecondaryIndexes.test_stop_node_during_index_build/node4.log) actually performed the action successfully:
```
INFO  2019-07-16 05:07:54,394 [shard 0] migration_manager - Update view 'ks.b_index_index' From org.apache.cassandra.config.CFMetaData@0x600001263880[cfId=a3d6aed0-a787-11e9-b1d7-000000000000,ksName=ks,cfName=b_index_index,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0.1,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.Int32Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=b, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=idx_token, type=org.apache.cassandra.db.marshal.BytesType, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=key, type=org.apache.cassandra.db.marshal.Int32Type, kind=CLUSTERING_COLUMN, componentIndex=1, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=3f786abc-09f3-3eb8-973a-c341cd3eb198,droppedColumns={},collections={},indices={}, viewInfo=ViewInfo{baseTableId=7e420430-a787-11e9-ad38-000000000000, baseTableName=cf, includeAllColumns=false, whereClause=b IS NOT NULL}] To org.apache.cassandra.config.CFMetaData@0x600001264380[cfId=a3d6aed0-a787-11e9-b1d7-000000000000,ksName=ks,cfName=b_index_index,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0.1,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.Int32Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=b, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=idx_token, type=org.apache.cassandra.db.marshal.BytesType, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=key, type=org.apache.cassandra.db.marshal.Int32Type, kind=CLUSTERING_COLUMN, componentIndex=1, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=ab10a890-a787-11e9-bc19-000000000000,droppedColumns={},collections={},indices={}, viewInfo=ViewInfo{baseTableId=7e420430-a787-11e9-ad38-000000000000, baseTableName=cf, includeAllColumns=false, whereClause=b IS NOT NULL}]
INFO  2019-07-16 05:07:54,855 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-9WMj8C/test/node4/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-24-big-Data.db:level=0, /jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-9WMj8C/test/node4/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-22-big-Data.db:level=0, ]
INFO  2019-07-16 05:07:56,344 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-9WMj8C/test/node4/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/mc-4-big-Data.db:level=0, /jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-9WMj8C/test/node4/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/mc-2-big-Data.db:level=0, ]
INFO  2019-07-16 05:07:58,139 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-9WMj8C/test/node4/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-36-big-Data.db:level=0, /jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-9WMj8C/test/node4/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-34-big-Data.db:level=0, ]
INFO  2019-07-16 05:08:00,754 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-9WMj8C/test/node4/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-24-big-Data.db:level=0, /jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-9WMj8C/test/node4/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-22-big-Data.db:level=0, ]
INFO  2019-07-16 05:08:01,233 [shard 0] database - Schema version changed to 46fe136d-4baa-30a1-9219-36d4581deb03
INFO  2019-07-16 05:08:01,234 [shard 0] migration_manager - Schema merge with 127.0.46.1:0 completed
INFO  2019-07-16 05:08:01,234 [shard 0] migration_manager - Pulling schema from 127.0.46.1:0
INFO  2019-07-16 05:08:03,898 [shard 0] view - Finished building view ks.b_index_index
```

See also [next/988](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/988/testReport/secondary_indexes_test/TestSecondaryIndexes/test_stop_node_during_index_build/) [next/989](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/989/testReport/secondary_indexes_test/TestSecondaryIndexes/test_stop_node_during_index_build/)

**Comment by slivne** [comment]
well on dtest runs (non gatting) it has been passing

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/179/testReport/secondary_indexes_test/TestSecondaryIndexes/test_stop_node_during_index_build/history/

**Comment by slivne** [comment]
@bhalevy closing this - it passed on the last 50 runs 

if this still happens please reopen with updated links
