### ISSUE TITLE
concurrent_drain_test: Error running cassandra-stress: Connection has been closed

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4725]
Since [dtest-release/173/testReport/nodetool_additional_test/TestNodetool/concurrent_drain_test] scylla commit 281f3a69f82c3d75a40654cb5e80439d369ee351 concurrent_drain_test has been failing consistently like this:
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1614, in concurrent_drain_test
    self.general_concurrent(tst)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1547, in general_concurrent
    debug("Test call flow:\n" + self.print_time(self.concurrent_part(op)))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1523, in concurrent_part
    self.assertFalse(self.concurrent_test_fail, "Concurrent test failed\n" + self.print_time(res))
  File "/usr/lib64/python2.7/unittest/case.py", line 454, in assertFalse
    raise self.failureException(msg)
AssertionError: Concurrent test failed
|0                                                                                                            |90|91|92                  |112|113           129|
----------------------------------------------------------------------------------------------------------------------------------------------------------------
[concurrent_stress                                                                                                                                             X
Error running cassandra-stress: com.datastax.driver.core.exceptions.TransportException: [127.0.28.2/127.0.28.2:9042] Connection has been closed
com.datastax.driver.core.exceptions.TransportException: [127.0.28.2/127.0.28.2:9042] Connection has been closed
com.datastax.driver.core.exceptions.TransportException: [127.0.28.2/127.0.28.2:9042] Connection has been closed
com.datastax.driver.core.exceptions.TransportException: [127.0.28.2/127.0.28.2:9042] Connection has been closed
com.datastax.driver.core.exceptions.TransportException: [127.0.28.2/127.0.28.2:9042] Connection has been closed
com.datastax.driver.core.exceptions.TransportException: [127.0.28.2/127.0.28.2:9042] Connection has been closed
com.datastax.driver.core.exceptions.TransportException: [127.0.28.2/127.0.28.2:9042] Connection has been closed
com.datastax.driver.core.exceptions.TransportException: [127.0.28.2/127.0.28.2:9042] Connection has been closed
ERROR 22:19:07,922 [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds

                                                                                                               [drain         ]
                                                                                                                [verify_info           ]
                                                                                                                []
                                                                                                     verify_status
                                                                                                                []
                                                                                                   verify_netstats
                                                                                                                []
                                                                                               verify_cfhistograms
                                                                                                                []
                                                                                                    verify_cfstats
                                                                                                                  []
                                                                                                verify_describering
                                                                                                                  []
                                                                                              verify_decribecluster
                                                                                                                                          [verify_info      ]
                                                                                                                                          []
                                                                                                                               verify_status
                                                                                                                                            []
                                                                                                                              verify_netstats
                                                                                                                                            []
                                                                                                                          verify_cfhistograms
                                                                                                                                            []
                                                                                                                                verify_cfstats
                                                                                                                                            []
                                                                                                                           verify_describering
                                                                                                                                            []
                                                                                                                         verify_decribecluster
```

Edit: seen also previously: [dtest-release/167](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/167/testReport/nodetool_additional_test/TestNodetool/concurrent_drain_test/)

**Comment by bhalevy** [comment]
@elcallio could this be related to your ipv6 changes?

**Comment by slivne** [comment]
Fixed in  https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/180/

```
10:10:36  concurrent_drain_test (nodetool_additional_test.TestNodetool) ... ok
```

it may have been related to ipv6 change 


closing
