### ISSUE TITLE
Overriding "listen_address" causes bad_function_call exception

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#473]
scylla HEAD: f1c681de6045d5fb0ae8e60183b72368b31bc00b
configuration: --disable-xen --enable-dpdk
server: c3.8xlarge AWS instance with Fedora21
command line: sudo ./build/release/scylla --options-file conf/scylla.yaml --smp 4 --memory 512M  --default-log-level debug --rpc-address `real IP` --listen-address `real IP, the same as given for --rpc-address`

Result:
```
DEBUG [shard 2] lsa - Registered region @0x60200026ed30 with id=68
DEBUG [shard 3] lsa - Registered region @0x60300026ee10 with id=69
DEBUG [shard 1] lsa - Registered region @0x60100026ed30 with id=70
INFO  [shard 2] database - Row: max_vector_size: 32, internal_count: 5
DEBUG [shard 3] lsa - Registered region @0x60300026ed30 with id=71
INFO  [shard 1] database - Row: max_vector_size: 32, internal_count: 5
INFO  [shard 3] database - Row: max_vector_size: 32, internal_count: 5
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
```

call trace:
```
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call

Program received signal SIGABRT, Aborted.
0x00007ffff40dd8d7 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff40dd8d7 in raise () from /lib64/libc.so.6
#1  0x00007ffff40df53a in abort () from /lib64/libc.so.6
#2  0x00007ffff74b1fdd in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007ffff74afe56 in ?? () from /lib64/libstdc++.so.6
#4  0x00007ffff74aee59 in ?? () from /lib64/libstdc++.so.6
#5  0x00007ffff74af65a in __gxx_personality_v0 () from /lib64/libstdc++.so.6
#6  0x00007ffff4692013 in ?? () from /lib64/libgcc_s.so.1
#7  0x00007ffff469239b in _Unwind_RaiseException () from /lib64/libgcc_s.so.1
#8  0x00007ffff74b00ac in __cxa_throw () from /lib64/libstdc++.so.6
#9  0x00007ffff750a512 in std::__throw_bad_function_call() () from /lib64/libstdc++.so.6
#10 0x00000000004ba053 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/4.9.2/functional:2438
#11 0x0000000000cc104c in seastar::async_sharded_service<net::messaging_service>::~async_sharded_service (this=0x600000574800, __in_chrg=<optimized out>) at /home/fedora/urchin/seastar/core/sharded.hh:42
#12 0x0000000000cb6ccc in net::messaging_service::messaging_service (this=0x600000574800, ip=...) at message/messaging_service.cc:258
#13 0x0000000000ddde7c in future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()() ()
    at /home/fedora/urchin/seastar/core/shared_ptr.hh:491
#14 0x0000000000dea0ed in future<> parallel_for_each<boost::range_detail::integer_iterator<unsigned int>, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}>(boost::range_detail::integer_iterator<unsigned int>, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}&&)::{lambda(parallel_for_each_state&)#1}::operator()(parallel_for_each_state) const () at ./seastar/core/future.hh:1078
#15 0x0000000000df0072 in do_with<parallel_for_each_state, future<> parallel_for_each<boost::range_detail::integer_iterator<unsigned int>, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}>(boost::range_detail::integer_iterator<unsigned int>, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}&&)::{lambda(parallel_for_each_state&)#1}>(future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}&&, future<> parallel_for_each<boost::range_detail::integer_iterator<unsigned int>, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}>(boost::range_detail::integer_iterator<unsigned int>, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}, future<> seastar::sharded<net::messaging_service>::start<gms::inet_address const&>(gms::inet_address const&)::{lambda(unsigned int)#1}&&)::{lambda(parallel_for_each_state&)#1}) (
    rvalue=<unknown type in /home/fedora/urchin/build/release/scylla, CU 0xc68fe3f, DIE 0xc8f7506>, f=<unknown type in /home/fedora/urchin/build/release/scylla, CU 0xc68fe3f, DIE 0xc8f7424>)
    at /home/fedora/urchin/seastar/core/do_with.hh:55
#16 0x0000000000df8068 in parallel_for_each<boost::range_detail::integer_iterator<unsigned int>, seastar::sharded<Service>::start(Args&& ...) [with Args = {const gms::inet_address&}; Service = net::messaging_service]::<lambda(unsigned int)> > (func=<unknown type in /home/fedora/urchin/build/release/scylla, CU 0xc68fe3f, DIE 0xc91d1fb>, end=..., begin=...) at /home/fedora/urchin/seastar/core/future-util.hh:110
#17 parallel_for_each<boost::integer_range<unsigned int>, seastar::sharded<Service>::start(Args&& ...) [with Args = {const gms::inet_address&}; Service = net::messaging_service]::<lambda(unsigned int)> > (
    func=<unknown type in /home/fedora/urchin/build/release/scylla, CU 0xc68fe3f, DIE 0xc88c1de>, range=<optimized out>) at /home/fedora/urchin/seastar/core/future-util.hh:132
#18 seastar::sharded<net::messaging_service>::start<gms::inet_address const&> (this=0x19bebb0 <net::_the_messaging_service>) at ./seastar/core/sharded.hh:349
#19 0x0000000000dd8d14 in init_ms_fd_gossiper (listen_address=..., seed_provider=..., cluster_name=...) at init.cc:74
#20 0x0000000000640f41 in operator() (__closure=0x6000000caed0, __closure@entry=0x6000000caef0) at main.cc:228
#21 apply (args=<optimized out>, func=func@entry=<unknown type in /home/fedora/urchin/build/release/scylla, CU 0x13d813e, DIE 0x17959cc>) at /home/fedora/urchin/seastar/core/apply.hh:34
#22 apply<main(int, char**)::<lambda()>::<lambda()>::<lambda()> > (args=<optimized out>, func=func@entry=<unknown type in /home/fedora/urchin/build/release/scylla, CU 0x13d813e, DIE 0x1795a3a>)
    at /home/fedora/urchin/seastar/core/apply.hh:42
#23 futurize<future<> >::apply<main(int, char**)::<lambda()>::<lambda()>::<lambda()> >(<unknown type in /home/fedora/urchin/build/release/scylla, CU 0x13d813e, DIE 0x1795a7a>, <unknown type in /home/fedora/urchin/build/release/scylla, CU 0x13d813e, DIE 0x1795a8d>) (func=func@entry=<unknown type in /home/fedora/urchin/build/release/scylla, CU 0x13d813e, DIE 0x1795a7a>, args=<optimized out>) at /home/fedora/urchin/seastar/core/future.hh:1133
#24 0x0000000000650aac in operator()<future_state<> > (state=<unknown type in /home/fedora/urchin/build/release/scylla, CU 0x13d813e, DIE 0x18b7d40>, __closure=0x6000000caeb0) at /home/fedora/urchin/seastar/core/future.hh:789
#25 continuation<future<T>::then(Func&&) [with Func = main(int, char**)::<lambda()>::<lambda()>::<lambda()>; Result = future<>; T = {}]::<lambda(auto:3&&)> >::run(void) (this=0x6000000caea0)
    at /home/fedora/urchin/seastar/core/future.hh:362
#26 0x000000000047a8cf in reactor::run_tasks (this=this@entry=0x600000501000, tasks=...) at core/reactor.cc:1222
#27 0x00000000004a7e8b in reactor::run (this=0x600000501000) at core/reactor.cc:1348
#28 0x0000000000501e86 in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffe2e0, ac=ac@entry=13, av=av@entry=0x7fffffffe528, 
    func=func@entry=<unknown type in /home/fedora/urchin/build/release/scylla, CU 0x55f17e, DIE 0x60961a>) at core/app-template.cc:122
#29 0x000000000042722b in main (ac=13, av=0x7fffffffe528) at main.cc:351
```

The same command without --listen-address parameter works just fine.

**Comment by gleb-cloudius** [comment]
I posted a patch to seastar-dev to fix it.

--
			Gleb.

**Comment by tgrabiec** [comment]
Duplicates #353
