### ISSUE TITLE
DTEST consistency_test.py:TestConsistency.short_read_reversed_test fails

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#480]
using 

Merge: 93c1035 02732f1
Author: Avi Kivity <avi@scylladb.com>
Date:   Tue Oct 20 17:36:57 2015 +0300

    Merge "Flusing of CF:s without replay positions" from Calle
    
    "Fixes: #469
    
    We occasionally generate memtables that are not empty, yet have no
    high replay_position set. (Typical case is CL replay, but apparently
    there are others).
    
    Moreover, we can do this repeatedly, and thus get caught in the flush
    queue ordering restrictions.
    
    Solve this by treating a flush without replay_position as a flush at the
    highest running position, i.e. "last" in queue. Note that this will not
    affect the actual flush operation, nor CL callbacks, only anyone waiting
    for the operation(s) to complete.
    
    To do this, the flush_queue had its restrictions eased, and some introspection
    methods added."

```
pkill -9 scylla;  rm -Rf ~/.dtest/*;KEEP_TEST_DIR=true nosetests -v -s consistency_test.py:TestConsistency.short_read_reversed_test
FAIL

======================================================================
FAIL: short_read_reversed_test (consistency_test.TestConsistency)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/consistency_test.py", line 791, in short_read_reversed_test
    assert res[i][1] == 'value%d' % (5-i), 'Expecting value%d, got %s (%s)' % (5-i, res[i][1], str(res))
AssertionError: Expecting value5, got value2 ([Row(c=u'c000002', v=u'value2'), Row(c=u'c000001', v=u'value1'), Row(c=u'c000000', v=u'value0')])
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-KuMZzV
cassandra.cluster: WARNING: Host 127.0.0.1 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.1, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Failed to create connection pool for new host 127.0.0.1:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1831, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool (cassandra/cluster.c:31324)
    new_pool = HostConnection(host, distance, self)
  File "cassandra/pool.py", line 295, in cassandra.pool.HostConnection.__init__ (cassandra/pool.c:6160)
    self._connection = session.cluster.connection_factory(host.address)
  File "cassandra/cluster.py", line 785, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9335)
    return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
  File "cassandra/connection.py", line 304, in cassandra.connection.Connection.factory (cassandra/connection.c:5114)
    conn = cls(host, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cassandra/io/libevreactor.py", line 264, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 338, in cassandra.connection.Connection._connect_socket (cassandra/connection.c:6246)
    raise socket.error(sockerr.errno, "Tried connecting to %s. Last error: %s" % ([a[4] for a in addresses], sockerr.strerror or sockerr))
error: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Host 127.0.0.1 has been marked down
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Failed to create connection pool for new host 127.0.0.2:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1831, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool (cassandra/cluster.c:31324)
    new_pool = HostConnection(host, distance, self)
  File "cassandra/pool.py", line 295, in cassandra.pool.HostConnection.__init__ (cassandra/pool.c:6160)
    self._connection = session.cluster.connection_factory(host.address)
  File "cassandra/cluster.py", line 785, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9335)
    return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
  File "cassandra/connection.py", line 304, in cassandra.connection.Connection.factory (cassandra/connection.c:5114)
    conn = cls(host, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cassandra/io/libevreactor.py", line 264, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 338, in cassandra.connection.Connection._connect_socket (cassandra/connection.c:6246)
    raise socket.error(sockerr.errno, "Tried connecting to %s. Last error: %s" % ([a[4] for a in addresses], sockerr.strerror or sockerr))
error: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
cassandra.cluster: WARNING: [control connection] Error connecting to 127.0.0.3:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 2114, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:37551)
    return self._try_connect(host)
  File "cassandra/cluster.py", line 2134, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:38028)
    connection = self._cluster.connection_factory(host.address, is_control_connection=True)
  File "cassandra/cluster.py", line 785, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9335)
    return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
  File "cassandra/connection.py", line 304, in cassandra.connection.Connection.factory (cassandra/connection.c:5114)
    conn = cls(host, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cassandra/io/libevreactor.py", line 264, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 338, in cassandra.connection.Connection._connect_socket (cassandra/connection.c:6246)
    raise socket.error(sockerr.errno, "Tried connecting to %s. Last error: %s" % ([a[4] for a in addresses], sockerr.strerror or sockerr))
error: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Host 127.0.0.3 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Host 127.0.0.3 has been marked down
cassandra.cluster: WARNING: Host 127.0.0.3 has been marked down
cassandra.cluster: WARNING: [control connection] Error connecting to 127.0.0.3:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 2114, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:37551)
    return self._try_connect(host)
  File "cassandra/cluster.py", line 2134, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:38028)
    connection = self._cluster.connection_factory(host.address, is_control_connection=True)
  File "cassandra/cluster.py", line 785, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9335)
    return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
  File "cassandra/connection.py", line 304, in cassandra.connection.Connection.factory (cassandra/connection.c:5114)
    conn = cls(host, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cassandra/io/libevreactor.py", line 264, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 338, in cassandra.connection.Connection._connect_socket (cassandra/connection.c:6246)
    raise socket.error(sockerr.errno, "Tried connecting to %s. Last error: %s" % ([a[4] for a in addresses], sockerr.strerror or sockerr))
error: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Failed to create connection pool for new host 127.0.0.3:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1831, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool (cassandra/cluster.c:31324)
    new_pool = HostConnection(host, distance, self)
  File "cassandra/pool.py", line 295, in cassandra.pool.HostConnection.__init__ (cassandra/pool.c:6160)
    self._connection = session.cluster.connection_factory(host.address)
  File "cassandra/cluster.py", line 785, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9335)
    return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
  File "cassandra/connection.py", line 304, in cassandra.connection.Connection.factory (cassandra/connection.c:5114)
    conn = cls(host, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cassandra/io/libevreactor.py", line 264, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 338, in cassandra.connection.Connection._connect_socket (cassandra/connection.c:6246)
    raise socket.error(sockerr.errno, "Tried connecting to %s. Last error: %s" % ([a[4] for a in addresses], sockerr.strerror or sockerr))
error: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Host 127.0.0.3 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 110.853s

FAILED (failures=1)

**Comment by gleb-cloudius** [comment]
There is no much useful info here besides that dtest cannot connect to
the cluster. Does the cluster running? If not did it crash? If yes was
core saved and what was bt?

--
			Gleb.

**Comment by penberg** [comment]
I think the reconnect error happens _after_ the following test failure:

```
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/consistency_test.py", line 791, in short_read_reversed_test
    assert res[i][1] == 'value%d' % (5-i), 'Expecting value%d, got %s (%s)' % (5-i, res[i][1], str(res))
AssertionError: Expecting value5, got value2 ([Row(c=u'c000002', v=u'value2'), Row(c=u'c000001', v=u'value1'), Row(c=u'c000000', v=u'value0')])
```

AFAICT, the returned result set is inconsistent with what the test case expects.

**Comment by slivne** [comment]
True, I did not collect all the info

There are additional short_read_tests that do pass, short_read_test,
short_read_delete_test.

Please try running this yourself, it always fails

**Comment by gleb-cloudius** [comment]
On Wed, Oct 21, 2015 at 12:06:00AM -0700, Pekka Enberg wrote:
> I think the reconnect error happens _after_ the following test failure:
> 
> ```
> Traceback (most recent call last):
>   File "/home/shlomi/urchin-dtest/consistency_test.py", line 791, in short_read_reversed_test
>     assert res[i][1] == 'value%d' % (5-i), 'Expecting value%d, got %s (%s)' % (5-i, res[i][1], str(res))
> AssertionError: Expecting value5, got value2 ([Row(c=u'c000002', v=u'value2'), Row(c=u'c000001', v=u'value1'), Row(c=u'c000000', v=u'value0')])
> ```
> 
> AFAICT, the returned result set is inconsistent with what the test case expects.
> 
You are probably right. Why generate all the noise instead of printing
error message? Is there any description what those tests are doing?

--
			Gleb.

**Comment by penberg** [comment]
@gleb-cloudius Scylla has probably crashed and the test harness tries to continue. I don't think there's other information on the test cases beyond the Python source code itself.

**Comment by gleb-cloudius** [comment]
On Wed, Oct 21, 2015 at 12:13:09AM -0700, slivne wrote:
> True, I did not collect all the info
> 
> There are additional short_read_tests that do pass, short_read_test,
> short_read_delete_test.
> 
> Please try running this yourself, it always fails
> 
As I said multiple times running a bunch of tests in uncontrollable
environment will not help me to debug it. The only thing it will
accomplish is that I will confirm your result, but I believe you anyway
;) To debug I need to run the test in my, isolated, environment and
understand what the test is doing, but if I do later I do not need to
run it at all.

--
			Gleb.

**Comment by slivne** [comment]
The code itself of the test is very simple

It create a cluster of 3 nodes with rf=3, inserts 9 values (0-8)
- it stops a node deletes value 8 starts stopped node again
- it stops a node deletes value 7 starts stopped node again
- it stops a node deletes value 6 starts stopped node again
- it does a select order by desc limit 3
- it checks it got back 3 values - it checks the values and we do not adhere to the order by.


```
    def short_read_reversed_test(self):
        cluster = self.cluster

        # Disable hinted handoff and set batch commit log so this doesn't
        # interfer with the test
        cluster.set_configuration_options(values={ 'hinted_handoff_enabled' : False}, batch_commitlog=True)

        cluster.populate(3).start(wait_other_notice=True,jvm_args=['--default-log-level','trace'])
        node1, node2, node3 = cluster.nodelist()

        cursor = self.patient_cql_connection(node1)
        self.create_ks(cursor, 'ks', 3)
        self.create_cf(cursor, 'cf', read_repair=0.0)
        # insert 9 columns in one row
        insert_columns(self, cursor, 0, 9)

        # Deleting 3 last columns with a different node dead each time
        self.stop_delete_and_restart(1, 6)
        self.stop_delete_and_restart(2, 7)
        self.stop_delete_and_restart(3, 8)

        # Query 3 firsts columns
        cursor = self.patient_cql_connection(node1, 'ks')
        query = SimpleStatement('SELECT c, v FROM cf WHERE key=\'k0\' ORDER BY c DESC LIMIT 3', consistency_level=ConsistencyLevel.QUORUM)
        rows = cursor.execute(query)
        res = rows
        assert len(res) == 3, 'Expecting 3 values, got %d (%s)' % (len(res), str(res))
        # value 6, 7 and 8 have been deleted
        for i in xrange(0, 3):
            assert res[i][1] == 'value%d' % (5-i), 'Expecting value%d, got %s (%s)' % (5-i, res[i][1], str(res))
```

there is no failure/core/crash.

the issue is that the short read does not apply the ORDER BY DESC limit

instead of returning values 5,4,3 it returns values 2,1,0 and its not what is expected.

**Comment by gleb-cloudius** [comment]
On Wed, Oct 21, 2015 at 01:28:12AM -0700, slivne wrote:
> The code itself of the test is very simple
> 
> It create a cluster of 3 nodes with rf=3, inserts 9 values (0-8)
> - it stops a node deletes value 8 starts stopped node again
> - it stops a node deletes value 7 starts stopped node again
> - it stops a node deletes value 6 starts stopped node again
> - it does a select order by desc limit 3
> - it checks it got back 3 values - it checks the values and we do not adhere to the order by.
> 
> 
Yes, I already decipher that from the test code. No I need cqlsh that
works.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
@tgrabiec looks like query_mutations() does not handle reversed flag at all, so during reconciliation phase received data is incorrect.

**Comment by tgrabiec** [comment]
@gleb-cloudius yep. reverse ordering was added after mutation queries, but only to data queries. I'm fixing that.
