### ISSUE TITLE
Segfault in set_compaction_manager during compaction_delete_with_smp_change_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4824]
Seen first in [dtest-debug/213/artifact/logs-debug.2/1565253021472_compaction_additional_test.CompactionAdditionalTest.compaction_delete_with_smp_change_test/node1.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/213/artifact/logs-debug.2/1565253021472_compaction_additional_test.CompactionAdditionalTest.compaction_delete_with_smp_change_test/node1.log)
Scylla version 689fc72babaa0f4c914be07513273c8ec1d181ae

Recently seen in [dtest-release/204/artifact/logs-release.2/1565478098968_compaction_additional_test.CompactionAdditionalTest.compaction_delete_with_smp_change_test/node1.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/204/artifact/logs-release.2/1565478098968_compaction_additional_test.CompactionAdditionalTest.compaction_delete_with_smp_change_test/node1.log)
Scylla version 547c072f9306f90267d5dbc3bc49f019d8ac6008
```
(gdb) bt
#0  std::_Hashtable<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> >, std::pair<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > const, unsigned long>, std::allocator<std::pair<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > const, unsigned long> >, std::__detail::_Select1st, std::equal_to<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > >, utils::tuple_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node (
    __code=13808560276525649879, __k=..., __n=0, this=0x7ffc33cec090) at /usr/include/c++/8/bits/hashtable.h:1554
#1  std::_Hashtable<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> >, std::pair<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > const, unsigned long>, std::allocator<std::pair<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > const, unsigned long> >, std::__detail::_Select1st, std::equal_to<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > >, utils::tuple_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_node (
    __c=13808560276525649879, __key=..., __bkt=0, this=0x7ffc33cec090) at /usr/include/c++/8/bits/hashtable.h:654
#2  std::__detail::_Map_base<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> >, std::pair<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > const, unsigned long>, std::allocator<std::pair<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > const, unsigned long> >, std::__detail::_Select1st, std::equal_to<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > >, utils::tuple_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[] (
    __k=..., this=0x7ffc33cec090) at /usr/include/c++/8/bits/hashtable_policy.h:732
#3  std::unordered_map<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> >, unsigned long, utils::tuple_hash, std::equal_to<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > >, std::allocator<std::pair<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> > const, unsigned long> > >::operator[] (__k=..., this=0x7ffc33cec090)
    at /usr/include/c++/8/bits/unordered_map.h:978
#4  api::<lambda(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)>::operator() (__closure=<optimized out>, i=...) at api/compaction_manager.cc:80
#5  seastar::do_void_futurize_helper<seastar::future<> >::apply<api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::<lambda(std::unique_ptr<seastar::httpd::request>)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)>&, std::pair<const utils::UUID, seastar::lw_shared_ptr<table> >&> (func=<synthetic pointer>...) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1381
#6  seastar::futurize<void>::apply<api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::<lambda(std::unique_ptr<seastar::httpd::request>)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)>&, std::pair<const utils::UUID, seastar::lw_shared_ptr<table> >&> (func=<synthetic pointer>...) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1407
#7  seastar::do_for_each<std::__detail::_Node_iterator<std::pair<const utils::UUID, seastar::lw_shared_ptr<table> >, false, true>, api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::<lambda(std::unique_ptr<seastar::httpd::request>)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)> >(std::__detail::_Node_iterator<std::pair<utils::UUID const, seastar::lw_shared_ptr<table> >, false, true>, std::__detail::_Node_iterator<std::pair<utils::UUID const, seastar::lw_shared_ptr<table> >, false, true>, api::<lambda(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)>) (begin=..., end=..., action=...)
    at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future-util.hh:569
#8  0x0000000002ca3959 in seastar::<lambda()>::operator() (this=0x600001233998) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future-util.hh:576
#9  seastar::apply_helper<seastar::do_for_each(Iterator, Iterator, AsyncAction) [with Iterator = std::__detail::_Node_iterator<std::pair<const utils::UUID, seastar::lw_shared_ptr<table> >, false, true>; AsyncAction = api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::<lambda(std::unique_ptr<seastar::httpd::request>)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)>]::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (args=..., func=...)
    at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
#10 seastar::apply<seastar::do_for_each(Iterator, Iterator, AsyncAction) [with Iterator = std::__detail::_Node_iterator<std::pair<const utils::UUID, seastar::lw_shared_ptr<table> >, false, true>; AsyncAction = api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::<lambda(std::unique_ptr<seastar::httpd::request>)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)>]::<lambda()> > (args=..., func=...) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:43
#11 seastar::futurize<seastar::future<> >::apply<seastar::do_for_each(Iterator, Iterator, AsyncAction) [with Iterator = std::__detail::_Node_iterator<std::pair<const utils::UUID, seastar::lw_shared_ptr<table> >, false, true>; AsyncAction = api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::<lambda(std::unique_ptr<seastar::httpd::request>)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)>]::<lambda()> > (args=..., func=...)
    at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1414
#12 seastar::future<>::<lambda()>::<lambda(seastar::future_state<>&&)>::operator() (state=..., this=0x600001233978) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1000
#13 seastar::continuation<seastar::future<T>::then_impl(Func&&) [with Func = seastar::do_for_each(Iterator, Iterator, AsyncAction) [with Iterator = std::__detail::_Node_iterator<std::pair<const utils::UUID, seastar::lw_shared_ptr<table> >, false, true>; AsyncAction = api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::<lambda(std::unique_ptr<seastar::httpd::request>)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)>]::<lambda()>; Result = seastar::future<>; T = {}]::<lambda()>::<lambda(seastar::future_state<>&&)> >::run_and_dispose(void) (this=0x600001233960) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:400
#14 0x0000000002fa6832 in seastar::reactor::run_tasks (this=this@entry=0x600000020000, tq=...) at ../../src/core/reactor.cc:3821
#15 0x0000000002fa6a4f in seastar::reactor::run_some_tasks (this=this@entry=0x600000020000) at ../../src/core/reactor.cc:4248
#16 0x0000000003089ab6 in seastar::reactor::run_some_tasks (this=0x600000020000) at ../../src/core/reactor.cc:4392
#17 seastar::reactor::run (this=0x600000020000) at ../../src/core/reactor.cc:4392
#18 0x0000000002f44997 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=<optimized out>, ac=<optimized out>, av=<optimized out>, func=...) at ../../include/seastar/core/reactor.hh:918
#19 0x0000000002f45913 in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) (this=this@entry=0x7ffc33ced880, ac=ac@entry=24, av=av@entry=0x7ffc33cedbb0, func=...) at /usr/include/c++/8/bits/std_function.h:87
#20 0x0000000000700e20 in main (ac=24, av=0x7ffc33cedbb0) at /usr/include/c++/8/bits/std_function.h:87
```

**Comment by bhalevy** [comment]
Looks like `tasks` in `set_compaction_manager` is allocated on the stack:

https://github.com/scylladb/scylla/blob/547c072f9306f90267d5dbc3bc49f019d8ac6008/api/compaction_manager.cc#L75

**Comment by bhalevy** [comment]
Seen also in [dtest-release/227/artifact/logs-release.2/1567063420537_offline_tools_test.TestOfflineTools.sstablelevelreset_test/node1.log](http://jenkins.scylladb.com/job/scylla-master/job/dtest-release/227/artifact/logs-release.2/1567063420537_offline_tools_test.TestOfflineTools.sstablelevelreset_test/node1.log)
```
Segmentation fault on shard 0.
Backtrace:
  0x0000000002e9f712
  0x0000000002da7545
  0x0000000002da7845
  0x0000000002da7893
  0x00007fa6de30402f
  0x0000000002ab0a00
  0x0000000002ab140d
  0x0000000002da47c1
  0x0000000002da49de
  0x0000000002e7aead
  0x0000000002d4636d
  0x0000000002d471e2
  0x00000000006cedff
  /jenkins/workspace/scylla-master/dtest-release/scylla-dtest/../scylla/dynamic_libs/libc.so.6+0x0000000000024412
  0x000000000072ffdd
```

```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/backtrace.hh:55
seastar::print_with_backtrace(seastar::backtrace_buffer&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:1199
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:1220
seastar::print_with_backtrace(char const*) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:1227
seastar::install_oneshot_signal_handler<11, &seastar::sigsegv_action>()::{lambda(int, siginfo_t*, void*)#1}::_FUN(int, siginfo_t*, void*) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:5264
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:5250
 (inlined by) _FUN at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:5246
?? ??:0
seastar::future<> seastar::do_for_each<std::__detail::_Node_iterator<std::pair<utils::UUID const, seastar::lw_shared_ptr<table> >, false, true>, api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::{lambda(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >)#2}::operator()(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >) const::{lambda(database&)#1}::operator()(database) const::{lambda(std::pair<utils::UUID, seastar::lw_shared_ptr<table> > const&)#1}>(std::__detail::_Node_iterator<std::pair<utils::UUID const, seastar::lw_shared_ptr<table> >, false, true>, api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::{lambda(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >)#2}::operator()(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >) const::{lambda(database&)#1}::operator()(database) const::{lambda(std::pair<utils::UUID, seastar::lw_shared_ptr<table> > const&)#1}, api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::{lambda(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >)#2}::operator()(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >) const::{lambda(database&)#1}::operator()(database) const::{lambda(std::pair<utils::UUID, seastar::lw_shared_ptr<table> > const&)#1}) at /usr/include/c++/8/bits/hashtable_policy.h:434
 (inlined by) ?? at /usr/include/c++/8/bits/hashtable_policy.h:1392
 (inlined by) ?? at /usr/include/c++/8/bits/hashtable.h:643
 (inlined by) ?? at /usr/include/c++/8/bits/hashtable_policy.h:731
 (inlined by) ?? at /usr/include/c++/8/bits/unordered_map.h:978
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/api/compaction_manager.cc:80
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1463
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1489
 (inlined by) do_for_each<std::__detail::_Node_iterator<std::pair<const utils::UUID, seastar::lw_shared_ptr<table> >, false, true>, api::set_compaction_manager(api::http_context&, seastar::httpd::routes&)::<lambda(std::unique_ptr<seastar::httpd::request>)>::<lambda(database&)>::<lambda(const std::pair<utils::UUID, seastar::lw_shared_ptr<table> >&)> > at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future-util.hh:589
operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future-util.hh:597
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1496
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1063
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:414
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:3825
seastar::reactor::run_some_tasks() [clone .part.3076] at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:4252
seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:4235
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:4396
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/app-template.cc:199
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/app-template.cc:115
main at /jenkins/workspace/scylla-master/dtest-release/scylla/main.cc:506
```

**Comment by slivne** [comment]
@bhalevy do we need to backport this - did we hit the issue on 3.1 ?

**Comment by avikivity** [comment]
3.1 doesn't have this API call, so isn't vulnerable.
