### ISSUE TITLE
Add node update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_node_1_test

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#483]
Head 
commit 5453cfbab75d7a9c968c0226020dfcda5277a028
Merge: cf73413 3a95a9c
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Oct 21 08:59:42 2015 +0300

    Merge "snapshots: take + clear" from Glauber
    
    "This is the code for taking a snapshot, and clearing a snapshot."

Test fails every other run
```
======================================================================
ERROR: simple_add_node_1_test (update_cluster_layout_tests.TestUpdateClusterLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/update_cluster_layout_tests.py", line 85, in simple_add_node_1_test
    insert_c1c2(cursor, i, ConsistencyLevel.TWO)
  File "/home/shlomi/urchin-dtest/tools.py", line 21, in insert_c1c2
    session.execute(query)
  File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:27334)
    result = future.result()
  File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:65206)
    raise self._final_exception
Unavailable: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl TWO. Requires 2, alive 1" info={'required_replicas': 2, 'alive_replicas': 1, 'consistency': 'TWO'}
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-JOqqnX
--------------------- >> end captured logging << ---------------------
```

**Comment by slivne** [comment]
with 
commit 23723991ed5bbabce0643a00f40b950df05f3469
Author: Asias He <asias@scylladb.com>
Date:   Wed Nov 18 16:22:35 2015 +0800

    gossip: Fix STATUS field in nodetool gossipinfo
    
    Before:
       === with c* cluster ===
       $ nodetool -p 7100 gossipinfo
    
       STATUS:NORMAL,-1139428872328849340
    
       === with scylla ===
       $ nodetool -p 7100 gossipinfo
    
       0:NORMAL,8251763528961471825;-9147358554612963965;5334343410266177046
    
    After:
       === with scylla ===
       $ nodetool -p 7100 gossipinfo
    
       0:NORMAL,8251763528961471825
    
    To align with c*, print one token in the STATUS field.
    
    Refs #508.

running scylla debug  this test still fails (it sometimes passes)

```
export CASSANDRA_DIR=~/scylla/build/debug
shlomi@localhost~/urchin-dtest (update_tests)$ pkill -9 scylla; rm -Rf ~/.dtest/*; REUSE_CLUSTER=false KEEP_TEST_DIR=true DEBUG=true PRINT_DEBUG=true nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_node_1_test 
simple_add_node_1_test (update_cluster_layout_tests.TestUpdateClusterLayout) ... cluster ccm directory: /home/shlomi/.dtest/dtest-Q9Ua1B
ERROR

======================================================================
ERROR: simple_add_node_1_test (update_cluster_layout_tests.TestUpdateClusterLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/update_cluster_layout_tests.py", line 93, in simple_add_node_1_test
    insert_c1c2(cursor, i, ConsistencyLevel.TWO)
  File "/home/shlomi/urchin-dtest/tools.py", line 21, in insert_c1c2
    session.execute(query)
  File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:27334)
    result = future.result()
  File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:65206)
    raise self._final_exception
OperationTimedOut: errors={}, last_host=127.0.0.1
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-Q9Ua1B
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 90.169s

FAILED (errors=1)
```

**Comment by tzach** [comment]
@slivne can we close this?

**Comment by asias** [comment]
@slivne I think we can close this one now.
