### ISSUE TITLE
AMI build occasionally fails as "File contains no section headers"

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla#4845]
AMI build occasionally fails as "File contains no section headers" after 7-8 minutes.
Happens on about 30-40% of the builds (not only master).
Rebuild usually runs OK.
Log:
```
18:15:56  [0;32m    amazon-ebs: File contains no section headers.[0m
18:15:56  [0;32m    amazon-ebs: file: file:///etc/yum.repos.d/scylla_install.repo, line: 1[0m
18:15:56  [0;32m    amazon-ebs: '<html>\n'[0m
18:15:56  [0;32m    amazon-ebs: Traceback (most recent call last):[0m
18:15:56  [0;32m    amazon-ebs:   File "/home/centos/scylla_install_ami", line 72, in <module>[0m
18:15:56  [0;32m    amazon-ebs:     run('yum install -y {}'.format(' '.join(rpms)))[0m
18:15:56  [0;32m    amazon-ebs:   File "/home/centos/scylla_install_ami", line 36, in run[0m
18:15:56  [0;32m    amazon-ebs:     return subprocess.check_call(cmd, shell=shell)[0m
18:15:56  [0;32m    amazon-ebs:   File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call[0m
18:15:56  [0;32m    amazon-ebs:     raise CalledProcessError(retcode, cmd)[0m
18:15:56  [0;32m    amazon-ebs: subprocess.CalledProcessError: Command '['yum', 'install', '-y', '/home/centos/scylla-conf.x86_64.rpm', '/home/centos/scylla-debuginfo.x86_64.rpm', '/home/centos/scylla-kernel-conf.x86_64.rpm', '/home/centos/scylla-server.x86_64.rpm', '/home/centos/scylla-python3.x86_64.rpm', '/home/centos/scylla.x86_64.rpm', '/home/centos/scylla-jmx.noarch.rpm', '/home/centos/scylla-tools-core.noarch.rpm', '/home/centos/scylla-tools.noarch.rpm', '/home/centos/scylla-ami.noarch.rpm']' returned non-zero exit status 1[0m
18:15:56  [1;32m==> amazon-ebs: Terminating the source AWS instance...[0m
18:16:22  [1;32m==> amazon-ebs: Cleaning up any extra volumes...[0m
18:16:22  [1;32m==> amazon-ebs: No volumes to clean up, skipping[0m
18:16:22  [1;32m==> amazon-ebs: Deleting temporary keypair...[0m
18:16:22  [1;31mBuild 'amazon-ebs' errored: Script exited with non-zero exit status: 1[0m
```

**Comment by hagitsegev** [comment]
Closing here, Open on pkg. Happens on sif only.
