### ISSUE TITLE
Scylla unit tests crash when given an unrecognised option

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4851]
```
bhalevy@localhost scylla$ build/release/tests/sstable_mutation_test_g -- --foo
Running 42 test cases...
error: unrecognised option '--foo'

Try --help.
Segmentation fault (core dumped)
bhalevy@localhost scylla$ ls -l *.core
-rw-------. 1 bhalevy bhalevy 69701632 Aug 14 15:45 sstable_mutatio.28089.1565786707.core
bhalevy@localhost scylla$ gdb -c sstable_mutatio.28089.1565786707.core build/release/tests/sstable_mutation_test_g
GNU gdb (GDB) Fedora 8.2-7.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/release/tests/sstable_mutation_test_g...done.

warning: core file may not match specified executable file.
[New LWP 28090]
[New LWP 28089]

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: generic error

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib64/libthread_db-1.0.so
line to your configuration file "/local/home/bhalevy/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/local/home/bhalevy/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: generic error

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `build/release/tests/sstable_mutation_test_g -- --foo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f65f44821f3 in munmap () from /lib64/libc.so.6
[Current thread is 1 (LWP 28090)]
Missing separate debuginfos, use: dnf debuginfo-install boost-chrono-1.66.0-14.fc29.x86_64 boost-date-time-1.66.0-14.fc29.x86_64 boost-filesystem-1.66.0-14.fc29.x86_64 boost-program-options-1.66.0-14.fc29.x86_64 boost-regex-1.66.0-14.fc29.x86_64 boost-system-1.66.0-14.fc29.x86_64 boost-test-1.66.0-14.fc29.x86_64 boost-thread-1.66.0-14.fc29.x86_64 boost-timer-1.66.0-14.fc29.x86_64 c-ares-1.13.0-5.fc29.x86_64 cryptopp-7.0.0-2.fc29.x86_64 fmt-5.2.1-1.fc29.x86_64 glibc-2.28-33.fc29.x86_64 gmp-6.1.2-9.fc29.x86_64 gnutls-3.6.7-1.fc29.x86_64 hwloc-libs-1.11.12-1.fc29.x86_64 libatomic-8.3.1-2.fc29.x86_64 libblkid-2.32.1-1.fc29.x86_64 libcap-2.25-12.fc29.x86_64 libffi-3.1-18.fc29.x86_64 libgcrypt-1.8.4-1.fc29.x86_64 libgpg-error-1.33-1.fc29.x86_64 libicu-62.2-1.fc29.x86_64 libmount-2.32.1-1.fc29.x86_64 libselinux-2.8-6.fc29.x86_64 libstdc++-8.3.1-2.fc29.x86_64 libtasn1-4.13-5.fc29.x86_64 libtool-ltdl-2.4.6-27.fc29.x86_64 libunistring-0.9.10-4.fc29.x86_64 libuuid-2.32.1-1.fc29.x86_64 libxcrypt-4.4.6-2.fc29.x86_64 lz4-libs-1.8.3-1.fc29.x86_64 nettle-3.4.1rc1-1.fc29.x86_64 numactl-libs-2.0.12-1.fc29.x86_64 openssl-libs-1.1.1c-2.fc29.x86_64 p11-kit-0.23.16.1-1.fc29.x86_64 snappy-1.1.7-8.fc29.x86_64 thrift-0.10.0-15.fc29.x86_64 trousers-lib-0.3.13-11.fc29.x86_64 xz-libs-5.2.4-3.fc29.x86_64 yaml-cpp-0.6.2-1.fc29.x86_64 zlib-1.2.11-14.fc29.x86_64
(gdb) info threads
  Id   Target Id         Frame 
* 1    LWP 28090         0x00007f65f44821f3 in munmap () from /lib64/libc.so.6
  2    LWP 28089         0x00007f65f4f2372c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f65f44821f3 in munmap () from /lib64/libc.so.6
Backtrace stopped: Cannot access memory at address 0x7f65f1de9088
(gdb) thread 2
[Switching to thread 2 (LWP 28089)]
#0  0x00007f65f4f2372c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f65f4f2372c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f65f46286f0 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#2  0x0000000003171643 in std::condition_variable::wait<seastar::testing::exchanger<std::__exception_ptr::exception_ptr>::take()::{lambda()#1}>(std::unique_lock<std::mutex>&, seastar::testing::exchanger<std::__exception_ptr::exception_ptr>::take()::{lambda()#1}) (__p=..., 
    __lock=..., this=0x7ffeaa3a1ff8) at /usr/include/c++/8/bits/exception_ptr.h:145
#3  seastar::testing::exchanger<std::__exception_ptr::exception_ptr>::take (this=0x7ffeaa3a1fd0) at ../../include/seastar/testing/exchanger.hh:69
#4  seastar::testing::test_runner::run_sync(std::function<seastar::future<> ()>) (this=0x3b53060 <seastar::testing::instance>, task=...) at ../../src/testing/test_runner.cc:117
#5  0x00000000031701af in seastar::testing::seastar_test::run (this=0x3b32d30 <nonexistent_key_instance>) at /usr/include/c++/8/new:169
#6  0x00007f65f4992ba2 in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) () from /lib64/libboost_unit_test_framework.so.1.66.0
#7  0x00007f65f499278d in boost::execution_monitor::catch_signals(boost::function<int ()> const&) () from /lib64/libboost_unit_test_framework.so.1.66.0
#8  0x00007f65f4992865 in boost::execution_monitor::execute(boost::function<int ()> const&) () from /lib64/libboost_unit_test_framework.so.1.66.0
#9  0x00007f65f4992941 in boost::execution_monitor::vexecute(boost::function<void ()> const&) () from /lib64/libboost_unit_test_framework.so.1.66.0
#10 0x00007f65f49b8c89 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) () from /lib64/libboost_unit_test_framework.so.1.66.0
#11 0x00007f65f499ea97 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) () from /lib64/libboost_unit_test_framework.so.1.66.0
#12 0x00007f65f499ecc0 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) () from /lib64/libboost_unit_test_framework.so.1.66.0
#13 0x00007f65f49973b9 in boost::unit_test::framework::run(unsigned long, bool) () from /lib64/libboost_unit_test_framework.so.1.66.0
#14 0x00007f65f49b6648 in boost::unit_test::unit_test_main(bool (*)(), int, char**) () from /lib64/libboost_unit_test_framework.so.1.66.0
#15 0x000000000316fda0 in seastar::testing::entry_point (argc=<optimized out>, argv=<optimized out>) at ../../src/testing/entry_point.cc:50
#16 0x00007f65f43ae413 in __libc_start_main () from /lib64/libc.so.6
#17 0x00000000006f583e in _start () at /usr/include/c++/8/system_error:77
```

**Comment by bhalevy** [comment]
That's actually a seastar bug.
Opened scylladb/seastar#673 and closing this one...
