### ISSUE TITLE
db::toppartitions_query doesn't return a hex representation of the partition for views

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#4896]
Scylla 3.1
This is how the call to the API looks like:
$ `curl -X GET --header 'Accept: application/json'`
```
 'http://localhost:10000/column_family/toppartitions/mview%3Ausers?duration=8728'
qW1ead": [{"partition": "5+}cI
~kE?<", "count": 213, "error": 212},{"partition": "tL<6yxT<;isu%t<A", "count": 201, "error": 200},{"partition": "jBHhRO3", "count": 186, "error": 185},{"partition": "QGS
0B]B%", "count": 186, "error": 185},{"partition": "Gkm7frS	p}UNtWN&?$X^", "count": 186, "error": 185},{"partition": ")d&z_
o5PK", "count": 186, "error": 185},{"partition": "gfZ2w[XHo+Gsc~'@es^", "count": 186, "error": 185},{"partition": "<=Ac        np:b", "count": 186, "error": 185},{"partition": "~Vu~BK}5w
                                                                                                                       YOXCP", "count": 185, "error": 184},{"partition": "`[2tx:D={aA!n8%5y>GRM(l", "count": 185, "error": 184}], "write": [{"partition": "
                                                 qBO}h`^ThX|uw"L
", "count": 164, "error": 163},{"partition": "D[71c|
r$/-v

     ount": 163, "error": 162},{"partition": "`@LD(BqHn:"\[N'3 2", "count": 150, "error": 149},{"partition": "Ki
]?o0="0)PPfZQs&4W8", "count": 150, "error": 149},{"partition": "k`dPD/>B$#z~KV", "count": 150, "error": 149},{"partition": "}h", "count": 150, "error": 149},{"partition": ",{,s"Ylu)A;
                                                                                                                                                                                       ", "count": 150, "error": 149},{"partition": "f(k3/o
@lqbIhQw/$S=", "count": 150, "error": 149},{"partition": "&h|3)
tXp_", "count": 150, "error": 149},{"partition": "Z.	?mD	#hF;Jz", "count": 150, "error": 149}]}
```

**Comment by juliayakovlev** [comment]
Installation details
Scylla version (or git commit hash): 3.1.0.rc3-0.20190727.bebfd7b26
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0e90f1a90d8bb3a4e

Create tablespace:
```
CREATE KEYSPACE mview WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};
```
Create table:
```
CREATE TABLE users (
    username text,
    first_name text,
    last_name text,
    password text,
    email text,
    last_access timeuuid,
    PRIMARY KEY(username)
  );
```
Create MV:
```
CREATE MATERIALIZED VIEW mview.users_by_last_name AS SELECT * FROM mview.users WHERE last_name IS NOT NULL and username IS NOT NULL PRIMARY KEY (last_name, username);
```
Start load on the table.

Run nodetool:
```
nodetool  toppartitions mview users_by_last_name 1556 -s 320 -k 19 -a reads
```
or 
```
nodetool   toppartitions mview users 8728 -s 193 -k 13 -a reads
```

Got error:
```
error: org.glassfish.json.JsonLocationImpl
-- StackTrace --
java.io.NotSerializableException: org.glassfish.json.JsonLocationImpl
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
	at java.lang.Throwable.writeObject(Throwable.java:1014)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
	at java.lang.Throwable.writeObject(Throwable.java:1014)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:396)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by roydahan** [comment]
@aleksbykov do you have tests for view in top partitions?

**Comment by aleksbykov** [comment]
@roydahan, yes i added new  tests to cover work with MV, but not submit it yet, because finding the way  how better to run the toppartitions tests, which will not fail them durring run on jenkins and with parallel run

**Comment by slivne** [comment]
@amnonh are you working on a fix ?

**Comment by amnonh** [comment]
@slivne not currently, it's something to do with how MV reports its key, let me know if you want me to get into it

**Comment by nyh** [comment]
@amnonh I don't understand the context of this problem (hex representation? what do you expect to see there?) or how it's related to materialized views - given that a materialized view is just a normal table, which is read normally and has normal partitions which should just be printed normally.
If you can point me to a specific problem regarding MV I can try to fix it, but I don't understand where to look for a problem.

**Comment by amnonh** [comment]
@nyh I'm not sure the problem is with MV, but maybe it's related to the way it creates the partition key.

The issue is a result of running nodetool toppartition on a view
the nodetool command is mapped to:
api/column_family.cc : cf::toppartitions

It uses toppartitions_query that is found in ./db/data_listeners.cc

It should return a key that can be returned to the user as the key for the most used partition.
What is return seems weird (look at the results at the top of the bug).

**Comment by juliayakovlev** [comment]
Got similar problem during MV&SI longevity (show_toppartitions nemesis)
Scylla version: ```3.2.rc2-0.20191207.2ff26d11608```

Error:
```
< t:2019-12-08 13:44:45,925 f:remote.py       l:126  c:sdcm.remote          p:ERROR > RemoteCmdRunner [centos@10.0.136.254]: Error executing command: "nodetool  toppartitions sec_index users_first_name_ind_index 1490 -s 862 -k 5 -a writes"; Exit status: 2
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.136.254]: STDERR: error: org.glassfish.json.JsonLocationImpl
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG > -- StackTrace --
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG > java.io.NotSerializableException: org.glassfish.json.JsonLocationImpl
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.lang.Throwable.writeObject(Throwable.java:1014)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.lang.reflect.Method.invoke(Method.java:498)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.lang.Throwable.writeObject(Throwable.java:1014)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.lang.reflect.Method.invoke(Method.java:498)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:396)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.rmi.transport.Transport$1.run(Transport.java:200)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.rmi.transport.Transport$1.run(Transport.java:197)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.security.AccessController.doPrivileged(Native Method)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.security.AccessController.doPrivileged(Native Method)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
< t:2019-12-08 13:44:45,926 f:remote.py       l:130  c:sdcm.remote          p:DEBUG >   at java.lang.Thread.run(Thread.java:748)
```

**Comment by ShlomiBalalis** [comment]
Though not complete, it seems like I received a similar issue in the 50gb 4days longevity during show_toppartitions nemesis
Scylla version: `3.2.rc2-0.20191207.2ff26d11608`

Error:
```
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > Command: 'nodetool -u cassandra -pw cassandra  toppartitions mview users_by_first_name 8375 -s 894 -k 14 -a writes,reads'
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > 
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > Exit code: 2
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > 
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > 
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > 
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > 
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR > 
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at java.lang.Throwable.writeObject(Throwable.java:1014)
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at java.lang.reflect.Method.invoke(Method.java:498)
< t:2019-12-08 19:12:01,555 f:nemesis.py      l:1189 c:sdcm.nemesis         p:ERROR >   at java.io.ObjectStreamClass.invokeWri
```

**Comment by slivne** [comment]
@ShlomiBalalis - please open a new issue for the issue you found its not related to this issue
