### ISSUE TITLE
C-S write workload failed in upgrading last db node

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4917]
*Installation details*
Scylla version (or git commit hash): from `3.0.10-0.20190815.b3bfd8c08` to `3.1.0.rc4-0.20190826.e4a39ed31`
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

* INFO
  - Test job: http://jenkins.scylladb.com/job/scylla-3.1/job/rolling-upgrade/job/rolling-upgrade-centos7/89/execution/node/41/log/
  - Job log: https://cloudius-jenkins-test.s3.amazonaws.com/15e70527-f6da-4d44-854a-cd7f4a45ee89/job_log.zip
  - Test ID: 15e70527-f6da-4d44-854a-cd7f4a45ee89
  - SCT event log: https://cloudius-jenkins-test.s3.amazonaws.com/15e70527-f6da-4d44-854a-cd7f4a45ee89/job_log.zip

There is a background c-s write workload, which is running for the whole upgrade test. It's started before upgrade first node, and finished after upgraded the last db node.

- cassandra-stress write no-warmup cl=QUORUM n=60000000 -schema 'keyspace=keyspace_entire_test replication(factor=3) compression=LZ4Compressor' -port jmx=6868 -mode cql3 native compression=lz4  user=cassandra password=cassandra -rate threads=1000 -pop seq=1..60000000 -log interval=5 -node 10.142.0.54"

In upgrade test of 3.1 (centos7), the entire write workload failed in upgrading last db node, the other nodes had been upgraded to 3.1 from 3.0. It failed after drained the node and stopped the scylla-server.

The last db node was finally upgraded successfully.

```
< t:2019-08-28 02:31:27,415 f:upgrade_test.py l:439  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-3 begin
< t:2019-08-28 02:37:22,559 f:upgrade_test.py l:441  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-3 ended
< t:2019-08-28 03:00:07,687 f:upgrade_test.py l:464  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-4 begin
< t:2019-08-28 03:06:32,579 f:upgrade_test.py l:466  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-4 ended
< t:2019-08-28 03:09:43,186 f:upgrade_test.py l:478  c:sdcm.tester          p:INFO  > Rollback Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-4 begin
< t:2019-08-28 03:13:41,453 f:upgrade_test.py l:480  c:sdcm.tester          p:INFO  > Rollback Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-4 ended
< t:2019-08-28 03:13:51,294 f:upgrade_test.py l:485  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-4 begin
< t:2019-08-28 03:20:12,421 f:upgrade_test.py l:487  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-4 ended
< t:2019-08-28 03:20:21,485 f:upgrade_test.py l:485  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-2 begin
< t:2019-08-28 03:27:53,437 f:upgrade_test.py l:487  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-2 ended
< t:2019-08-28 03:28:02,973 f:upgrade_test.py l:485  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-1 begin

< t:2019-08-28 03:29:11,404 f:cluster.py      l:2009 c:sdcm.cluster         p:DEBUG > Node rolling-upgrade-upgrade--centos-db-node-15e705
27-0-1 [35.196.47.237 | 10.142.0.54] (seed: False): Command 'nodetool -u cassandra -pw cassandra  drain ' duration -> 7.1717171669 s

< t:2019-08-28 03:29:13,781 f:remote.py       l:117  c:sdcm.remote          p:INFO  > RemoteCmdRunner [scylla-test@10.142.0.54]: Command "sudo systemctl stop scylla-server.service" finished with status 0

: com.datastax.driver.core.exceptions.ConnectionException: [rolling-upgrade-upgrade--centos-db-node-15e70527-0-3.c.skilled-adapter-452.internal/10.142.0.93:9042] Pool is shutdown
:       at com.datastax.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:613) [cassandra-driver-core-3.5.1-shaded.jar:na]
:       at com.datastax.driver.core.SessionManager.removePool(SessionManager.java:400) [cassandra-driver-core-3.5.1-shaded.jar:na]
:       at com.datastax.driver.core.SessionManager.onDown(SessionManager.java:485) [cassandra-driver-core-3.5.1-shaded.jar:na]
:       at com.datastax.driver.core.Cluster$Manager.onDown(Cluster.java:1941) [cassandra-driver-core-3.5.1-shaded.jar:na]
:       at com.datastax.driver.core.Cluster$Manager.access$1200(Cluster.java:1385) [cassandra-driver-core-3.5.1-shaded.jar:na]
:       at com.datastax.driver.core.Cluster$Manager$5.runMayThrow(Cluster.java:1898) [cassandra-driver-core-3.5.1-shaded.jar:na]
:       at com.datastax.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32) [cassandra-driver-core-3.5.1-shaded.jar:na]
:       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
:       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
:       at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [cassandra-driver-core-3.5.1-shaded.jar:na]
:       at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
: com.datastax.driver.core.exceptions.TransportException: [rolling-upgrade-upgrade--centos-db-node-15e70527-0-3.c.skilled-adapter-452.internal/10.142.0.93:9042] Connection has been closed


< t:2019-08-28 03:31:01,113 f:remote.py       l:662  c:sdcm.remote          p:INFO  > RemoteCmdRunner [scylla-test@10.142.0.136]: total,      52918233,   25175,   25175,   25175,    39.7,    32.3,   102.3,   129.1,   160.7,   173.1, 4490.0,  0.01851,      0,      0,       0,       0,       0,       0


< t:2019-08-28 03:35:51,354 f:upgrade_test.py l:487  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-upgrade--centos-db-node-15e70527-0-1 ended
```

```
STDERR: Failed to connect over JMX; not collecting these stats
```

**Comment by amoskong** [comment]
I'm checking if upgraded node will serve c-s entire (write) workload.

I guess only old db nodes serve entire workload (started before upgrade) before the upgrade completed. It switches to upgraded nodes when the last nodes is upgraded.

I only see this issue with CentOS7.

**Comment by amoskong** [comment]
> I'm checking if upgraded node will serve c-s entire (write) workload.
> 
> I guess only old db nodes serve entire workload (started before upgrade) before the upgrade completed. It switches to upgraded nodes when the last nodes is upgraded.

Not really, both old & upgraded nodes serve the requests of entire cs-write workload.

* Note: there is only one kind of workload in the test:
  - http://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-clone-3.1/job/rolling-upgrade-centos7/7/ (PASS)
  - test id: 6a9da6ad-6b24-48ae-8260-ec0bbcb80dae
  - https://cloudius-jenkins-test.s3.amazonaws.com/6a9da6ad-6b24-48ae-8260-ec0bbcb80dae/job_log.zip
  - ![upgrade-3 1-entire-cs-write-workload-snapshot](https://user-images.githubusercontent.com/309708/63904721-92250f80-ca44-11e9-8705-90334bf3ff92.png)


> I only see this issue with CentOS7.

It also occurred on ubuntu 16.04
- http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04/75/execution/node/41/log/
-  Test ID: e7ed3046-2437-4989-b21a-c85eb42f1a49
- 3.1.0.rc4-0.20190828.d70c2db09

**Comment by amoskong** [comment]
It seems not a real scylla issue, the c-s workload would take about 60 - 70 mins, but there is a timeout (65 mins) in sct for upgrade_test.

I had sent a PR to increase the timeout by PR https://github.com/scylladb/scylla-cluster-tests/pull/1273

BTW, I'm executing more test with new timeout, let's see if the problem still exists.

**Comment by amoskong** [comment]
I didn't see this error anymore, let's close this issue.
