### ISSUE TITLE
Too many in flight hints (C-S OverloadedException) during multiple repairs

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#4935]
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc4-0.20190828.d70c2db09
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-05f77d44238bc0bf4

When running 3 nemesis in parallel on different nodes

- 2 nodetool repair
- 1 nodetool cleanup

got
```
WARN  19:58:50,506 Host ip-10-0-148-227.eu-west-1.compute.internal/10.0.java.io.IOException: Operation x10 on key(s) [39364d3039304b353630]: Error executing: (OverloadedException): Queried host (ip-10-0-90-70.eu-west-1.compute.internal/10.0.90.70:9042) was overloaded: Too many in flight hints: 10485900
```
Hints in progress during repairs is large.
![image](https://user-images.githubusercontent.com/5269241/64074136-3c549f80-ccb0-11e9-84f2-1c8e3668627a.png)

**Comment by bhalevy** [comment]
Cc @eliransin

**Comment by slivne** [comment]
lets try to reproduce with full metrics and we will try to analyze

the strange thing is there are many hints without write timeouts according to what was reported

**Comment by gleb-cloudius** [comment]
On Tue, Sep 03, 2019 at 04:07:15AM -0700, Shlomi Livne wrote:
> lets try to reproduce with full metrics and we will try to analyze
> 
> the strange thing is there are many hints without write timeouts according to what was reported
> 
Why is it strange? Hints are written only for writes that succeed.

--
			Gleb.

**Comment by slivne** [comment]
@bentsi / @roydahan I'll need this reproduced - if possible provide the system when this happens - if not provide the metrics (not only a screen shot)

**Comment by fgelcer** [comment]
this is the too many hints while we have repair running in the background (abort_repair_nemesis)
https://snapshot.raintank.io/dashboard/snapshot/VF7V8LkY9PqSt44QZd4bDv64Cj4dWYpd

**Comment by slivne** [comment]
we are accumulating a huge backlog of hints (written - sent - that is only cleared when the load drops)
![4935](https://user-images.githubusercontent.com/3465480/64494474-0c039700-d296-11e9-9fa7-638d4eb610e8.png)

https://snapshot.raintank.io/dashboard/snapshot/VNMP180IVt04vtoypTlwji1WQ5MXZBGp


So we are reaching the numbers we are reporting **... was overloaded: Too many in flight hints: 10485900** or so it seems based on the metrics. 

The peek of the scylla_hints_manager_size_of_hints_in_progress in 14:17 aligns with a nemesis that restarts scylla (multiple times)

![nemesis](https://user-images.githubusercontent.com/3465480/64494573-618c7380-d297-11e9-8507-ce34a93a5c86.png)

I checked we do not have views hints in this case 

The threshold of overload for hints is scylla internal and is set at 10 MB 

in db/hints/resource_manager.hh

```
    static constexpr uint64_t max_size_of_hints_in_progress = 10 * 1024 * 1024; // 10MB
```

**Comment by amoskong** [comment]
I always see the 'Too many in flight hints (C-S OverloadedException)' error in longevity-large-collections-12h job.

I tried to reduce the collection size from 2 * 8M to 1 * 1M, but it still has this problem, and workload failed.

The only Workload: 
- "JVM_OPTION='-Xms8033M -Xmx8033M -Xmn400M' cassandra-stress user profile=/tmp/large_collections.yaml ops'(insert=3,read1=1,update1=1)' cl=QUORUM duration=720m -port         jmx=6868 -mode cql3 native -rate threads=10"

[large_collections.yaml.txt](https://github.com/scylladb/scylla/files/4425849/large_collections.yaml.txt)

----
Test job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/longevity-large-collections-12h-clone/12/
Test id: 7f2165d9-3947-40fa-808a-c90e69f36cc4
logs:
    - db log: https://cloudius-jenkins-test.s3.amazonaws.com/7f2165d9-3947-40fa-808a-c90e69f36cc4/20200402_203323/db-cluster-7f2165d9.zip
    - sct log: https://cloudius-jenkins-test.s3.amazonaws.com/7f2165d9-3947-40fa-808a-c90e69f36cc4/20200402_203323/sct-runner-7f2165d9.zip

```
#### CS workload started
< t:2020-04-02 07:46:39,740 f:remote.py       l:300  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.136.148]: Running command "echo TAG: loader_idx:0-cpu_idx:
0-keyspace_idx:1; STRESS_TEST_MARKER=HN2WHWNGMOO80U0R7S8N; JVM_OPTION='-Xms8033M -Xmx8033M -Xmn400M' cassandra-stress user profile=/tmp/large_collections.yaml ops'(insert=3,
read1=1,update1=1)' cl=QUORUM duration=720m -port jmx=6868 -mode cql3 native -rate threads=20 -node 10.0.18.1"...

....

< t:2020-04-02 16:35:34,715 f:remote.py       l:727  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.136.148]: insert,      6386115,     146,     146,     162,
    69.0,    26.1,    86.6,  1119.9,  1132.5,  1132.5,31724.7,  0.04173,      1,      0,       0,       0,       0,       0
< t:2020-04-02 16:35:34,716 f:remote.py       l:727  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.136.148]: read1,       2122827,      37,      37,      37,
   141.6,    88.5,   472.4,   498.9,   498.9,   498.9,31724.7,  0.04173,      0,      0,       0,       0,       0,       0
< t:2020-04-02 16:35:34,716 f:remote.py       l:727  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.136.148]: update1,     2132602,      93,       0,       0,
    60.7,    29.0,    57.4,   841.5,  1184.9,  1184.9,31724.7,  0.04173,      0,      0,       0,       0,       0,       0
< t:2020-04-02 16:35:34,716 f:remote.py       l:727  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.136.148]: total,      10641544,     277,     184,     200,
    76.0,    28.7,   165.7,  1119.9,  1184.9,  1184.9,31724.7,  0.04173,      1,      0,       0,       0,       0,       0
< t:2020-04-02 16:35:34,716 f:remote.py       l:727  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.136.148]: com.datastax.driver.core.exceptions.OverloadedEx
ception: Queried host (ip-10-0-233-183.eu-west-1.compute.internal/10.0.233.183:9042) was overloaded: Too many in flight hints: 10960471
< t:2020-04-02 16:35:34,771 f:sct_events.py   l:791  c:sdcm.sct_events      p:INFO  > 2020-04-02 16:35:34.759: (CassandraStressLogEvent Severity.ERROR): type=IOException reg
ex=java\.io\.IOException line_number=132962 node=Node longevity-large-collections-12h-lar-loader-node-7f2165d9-1 [34.249.192.80 | 10.0.136.148] (seed: False)
< t:2020-04-02 16:35:34,771 f:sct_events.py   l:791  c:sdcm.sct_events      p:INFO  > java.io.IOException: Operation x10 on key(s) [^Zie:qyHh]: Error executing: (OverloadedE
xception): Queried host (ip-10-0-233-183.eu-west-1.compute.internal/10.0.233.183:9042) was overloaded: Too many in flight hints: 10960471

^^^^^
#### CS workload stuck

....
....

#### CS workload failed
< t:2020-04-02 19:46:52,267 f:remote.py       l:160  c:sdcm.remote          p:DEBUG > total,      10641544,     277,     184,     200,    76.0,    28.7,   165.7,  1119.9,  1
184.9,  1184.9,31724.7,  0.04173,      1,      0,       0,       0,       0,       0
< t:2020-04-02 19:46:52,267 f:remote.py       l:160  c:sdcm.remote          p:DEBUG > FAILURE
```

#### Nemesis in the job:
```
< t:2020-04-02 07:49:31,369 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method network_reject_thrift
< t:2020-04-02 07:51:31,742 f:nemesis.py      l:657  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method network_reject_thrift
< t:2020-04-02 08:07:17,151 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method restart_then_repair_node
< t:2020-04-02 08:11:12,594 f:nemesis.py      l:657  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method restart_then_repair_node
< t:2020-04-02 08:26:57,819 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method restart_then_repair_node
< t:2020-04-02 08:50:02,977 f:nemesis.py      l:657  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method restart_then_repair_node
< t:2020-04-02 09:05:45,825 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method add_drop_column
< t:2020-04-02 09:16:52,592 f:nemesis.py      l:657  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method add_drop_column
< t:2020-04-02 09:32:30,914 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method validate_hh_short_downtime
< t:2020-04-02 09:51:51,287 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method delete_by_rows_range
< t:2020-04-02 09:52:34,441 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method soft_reboot_node
< t:2020-04-02 09:56:11,396 f:nemesis.py      l:657  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method soft_reboot_node
< t:2020-04-02 10:11:50,749 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method network_reject_node_exporter
< t:2020-04-02 10:12:50,894 f:nemesis.py      l:657  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method network_reject_node_exporter
< t:2020-04-02 10:28:28,040 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_decommission

## CS workload failed during decommission nemesis

< t:2020-04-02 20:01:29,727 f:nemesis.py      l:657  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_decommission
```

**Comment by amoskong** [comment]
ping @slivne

**Comment by aleksbykov** [comment]
During rolling-upgrade job ([link](https://jenkins.scylladb.com/job/scylla-4.2/job/rolling-upgrade/job/rolling-upgrade-debian9-test/15/)) from 4.1 to 4.2 when upgrade process started on node4, c-s stress detects 
```
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
WARN  08:24:42,618 Host rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042 is overloaded.
WARN  08:24:42,618 Host rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042 is overloaded.
WARN  08:24:42,618 Host rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042 is overloaded.
WARN  08:24:43,177 Host rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042 is overloaded.
WARN  08:24:43,177 Host rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042 is overloaded.
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
WARN  08:24:43,178 Host rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042 is overloaded.
WARN  08:24:43,178 Host rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042 is overloaded.
overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:java.io.IOException: Operation x10 on key(s) [354b4e4e3034324b3130]: Error executing: (OverloadedException): Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
WARN  08:24:43,204 Host rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042 is overloaded.
com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-4-2-debian-stretch-db-node-0570670b-0-2.c.skilled-adapter-452.internal/10.142.0.63:9042) was overloaded: Too many in flight hints: 10485768
FAILURE
java.lang.RuntimeException: Failed to execute stress action
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:101)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```
link to dashboards with metrics:
https://snapshot.raintank.io/dashboard/snapshot/ZyrYDUEcDrpvM9svJzDHqLV120BDP7Ez
https://snapshot.raintank.io/dashboard/snapshot/J87Ks1ndtct2leHYLZjzhPkVcy2jUJLB
https://snapshot.raintank.io/dashboard/snapshot/bDIENvwdGZnayFqnrBtNXvfxJO2J1bBg

you can restore monitoring on your localhost with command from sct
$ hydra investigate show-monitor 0570670b-ce08-4471-935e-b769476658a2

**Comment by aleksbykov** [comment]
issue reproduced for rolling upgrade from 4.1.3 -. 4.2.rc2 on node where 4.1.3 is running while another node is upgrading.
job link https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/rolling-upgrade/job/rolling-upgrade-debian9-test/29/
db nodes : log link: https://cloudius-jenkins-test.s3.amazonaws.com/670a3a6f-89e7-4d1b-b3e5-5310cffe5ffb/20200804_035645/db-cluster-670a3a6f.zip
you can restore monitoring on your localhost with command from sct
$ hydra investigate show-monitor 670a3a6f-89e7-4d1b-b3e5-5310cffe5ffb
