### ISSUE TITLE
nodetool compactionhistory produces java.io.NotSerializableException

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#4966]
```
# nodetool compactionhistory
Compaction History:
error: org.glassfish.json.JsonLocationImpl
-- StackTrace --
java.io.NotSerializableException: org.glassfish.json.JsonLocationImpl
   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
   at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
   at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
   at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
   at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
   at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
   at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
```

*Installation details*
Scylla version (or git commit hash): 3.0.8-0.20190627.23da53c4f.el7.x86_64
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

**Comment by slivne** [comment]
on 3.0.8 docker it works

```
nodetool compactionhistory

DEBUG 09:07:43,325 Using SLF4J as the default logging framework
DEBUG 09:07:43,328 -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
DEBUG 09:07:43,329 -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
Compaction History: 
id                                   keyspace_name columnfamily_name               compacted_at            bytes_in bytes_out rows_merged
8f516bf0-cfbc-11e9-9459-000000000001 system        local                           2019-09-05T09:07:17.679 23626    12273                
8f377b50-cfbc-11e9-9459-000000000001 system        local                           2019-09-05T09:07:17.509 18132    12413                
8877baa0-cfbc-11e9-91d3-000000000003 system_schema functions                       2019-09-05T09:07:06.186 9974     4991                 
88765b10-cfbc-11e9-91d3-000000000003 system_schema types                           2019-09-05T09:07:06.177 9974     4991                 
887597c0-cfbc-11e9-91d3-000000000003 system_schema views                           2019-09-05T09:07:06.172 9974     4991                 
886f7d40-cfbc-11e9-a066-000000000002 system_schema functions                       2019-09-05T09:07:06.132 10044    5026                 
886bd3c0-cfbc-11e9-a066-000000000002 system_schema types                           2019-09-05T09:07:06.108 10044    5026                 
886bacb0-cfbc-11e9-91d3-000000000003 system_schema indexes                         2019-09-05T09:07:06.107 9974     4991                 
88685150-cfbc-11e9-a066-000000000002 system_schema views                           2019-09-05T09:07:06.084 10044    5026                 
88612560-cfbc-11e9-91d3-000000000003 system_schema dropped_columns                 2019-09-05T09:07:06.038 9974     4991                 
88593620-cfbc-11e9-a066-000000000002 system_schema indexes                         2019-09-05T09:07:05.986 10044    5026                 
884e39a0-cfbc-11e9-a066-000000000002 system_schema dropped_columns                 2019-09-05T09:07:05.914 10044    5026                 
884e1290-cfbc-11e9-91d3-000000000003 system_schema triggers                        2019-09-05T09:07:05.913 9974     4991                 
884734c0-cfbc-11e9-a066-000000000002 system_schema triggers                        2019-09-05T09:07:05.868 10044    5026                 
883e3410-cfbc-11e9-91d3-000000000003 system_schema columns                         2019-09-05T09:07:05.809 64589    52450                
883ad8b1-cfbc-11e9-91d3-000000000003 system_schema aggregates                      2019-09-05T09:07:05.787 9974     4991                 
883ad8b0-cfbc-11e9-91d3-000000000003 system_schema keyspaces                       2019-09-05T09:07:05.786 48973    44044                
882295c0-cfbc-11e9-91d3-000000000003 ks            standard1                       2019-09-05T09:07:05.626 448377   367034               
882247a0-cfbc-11e9-91d3-000000000003 system_schema scylla_tables                   2019-09-05T09:07:05.625 11168    5749                 
88226eb0-cfbc-11e9-91d3-000000000003 system_schema tables                          2019-09-05T09:07:05.625 60997    50701                
880ee6b0-cfbc-11e9-9459-000000000001 system        local                           2019-09-05T09:07:05.498 17054    11882                
87e78892-cfbc-11e9-a066-000000000002 ks            standard1                       2019-09-05T09:07:05.241 467155   381011               
87e78890-cfbc-11e9-a066-000000000002 system_schema columns                         2019-09-05T09:07:05.240 78843    66539                
87e76181-cfbc-11e9-a066-000000000002 system_schema aggregates                      2019-09-05T09:07:05.240 10044    5026                 
87e76182-cfbc-11e9-a066-000000000002 system_schema tables                          2019-09-05T09:07:05.240 70280    61711                
87e78891-cfbc-11e9-a066-000000000002 system_schema keyspaces                       2019-09-05T09:07:05.240 61227    56258                
87e76180-cfbc-11e9-a066-000000000002 system_schema scylla_tables                   2019-09-05T09:07:05.239 10861    5594                 
87c1ff30-cfbc-11e9-9459-000000000001 ks            standard1                       2019-09-05T09:07:04.994 453423   361214               
87b57c10-cfbc-11e9-9459-000000000001 system        local                           2019-09-05T09:07:04.913 33828    12213                
8781c1e0-cfbc-11e9-a1a4-000000000000 ks            standard1                       2019-09-05T09:07:04.574 458010   373165               
87259820-cfbc-11e9-a1a4-000000000000 system        peers                           2019-09-05T09:07:03.970 10569    0                    
872486b0-cfbc-11e9-a1a4-000000000000 system        scylla_views_builds_in_progress 2019-09-05T09:07:03.963 7238     0                    
[root@1b2fbf08cc0b /]# 
```

Please provide a reproducer / access to the system this fails on

**Comment by dyasny** [comment]
@slivne looks like it is specific to the setup, I couldn't reproduce this either. 

@tarzanek is working on it, he might be able to add some more info

**Comment by tarzanek** [comment]
we're waiting for customer to get us output from 
curl http://127.0.0.1:10000/compaction_manager/compaction_history

it seems it is a corner case of some kind with some invalid data/format in above reply

**Comment by slivne** [comment]
Compaction history extracts data from a matching system table

You can ask them to.provide the content of that table via select

That may also help understand why its not working for them

**Comment by tarzanek** [comment]
I asked for the contents of system.compaction_history

**Comment by tarzanek** [comment]
[ch.txt](https://github.com/scylladb/scylla/files/3591056/ch.txt)

**Comment by slivne** [comment]
@tarzanek I checked it looks ok ...

did you get results for this 
```
curl http://127.0.0.1:10000/compaction_manager/compaction_history
```

please make sure they run it on the node that have issues ...

**Comment by tarzanek** [comment]
they didn't provide us with more info, so basically we can now only speculate why they had wrong info in their output :-(
closing as we don't have enough info to proceed here
