### ISSUE TITLE
Detected hint manager drops after Scylla short downtime

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#5002]
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc6-0.20190908.2ec036f50
Cluster size: 5 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0f02b94adb41f1f9c

Materialized view longevity test.

During nemesis named ValidateHintedHandoffShortDowntime hint manager drops were detected.

Hinted handoff is enabled.
Scylla on one node was restarted. Scylla was down about 30 sec. 
After the Scylla was up, reported about hint drops:

![Screenshot from 2019-09-11 08-55-42](https://user-images.githubusercontent.com/34435448/64671719-f64ac900-d471-11e9-8993-0ea438d72460.png)

But no scylla_hints_for_views_manager_size_of_hints_in_progress and scylla_hints_manager_size_of_hints_in_progress:

![Screenshot from 2019-09-11 08-56-48](https://user-images.githubusercontent.com/34435448/64671778-22664a00-d472-11e9-8a2d-bfd506e4ef54.png)

Load is about 40%:
![Screenshot from 2019-09-10 16-35-01](https://user-images.githubusercontent.com/34435448/64670648-86870f00-d46e-11e9-9ce9-cfc28b1084d0.png)

About 1.5K requests:
![Screenshot from 2019-09-10 16-34-13](https://user-images.githubusercontent.com/34435448/64670667-93a3fe00-d46e-11e9-80b2-4bcf02cb8b28.png)

**Comment by juliayakovlev** [comment]
Hint manager drops were found in large partition test (longevity-large-partition-200k-pks-4days)

Installation details:
Scylla version: 3.3.rc2-0.20200305.3bed8063f6c
AMI: ami-01c890a4541178da1
Cluster size: 5 nodes (i3en.3xlarge)

Hinted handoff is enabled.
Scylla on one node was restarted. Scylla was down about 30 sec.
After the Scylla was up, reported about hint drops:

![Screenshot from 2020-03-11 10-51-07](https://user-images.githubusercontent.com/34435448/76399919-25da7f80-6388-11ea-9d1e-085f7fb83b68.png)

![Screenshot from 2020-03-11 10-59-49](https://user-images.githubusercontent.com/34435448/76399954-30951480-6388-11ea-8068-95b8f6783b1e.png)

Get logs:
```hydra investigate  show-logs bc4bab16-67e1-491f-bb10-2de40f16f9cd```

Get Grafana and Prometheus services:
```hydra investigate  show-monitor bc4bab16-67e1-491f-bb10-2de40f16f9cd```

**Comment by aleksbykov** [comment]
Hint manager drops were found during gemini tests
Scylla version 666.development-0.20200424.31ccd3750b6 

Next errors found in logs:
```
< t:2020-04-24 21:51:56,855 f:db_stats.py     l:182  c:sdcm.db_stats        p:DEBUG > Query to PrometheusDB: http://34.252.139.159:9090/api/v1/query_range?query=sum(rate(scylla_hints_manager_sent{}[15s]))&start=1587765056.8549407&end=1587765116.8549407&step=5
< t:2020-04-24 21:51:56,856 f:connectionpool.py l:205  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 34.252.139.159:9090
< t:2020-04-24 21:51:56,859 f:connectionpool.py l:393  c:urllib3.connectionpool p:DEBUG > http://34.252.139.159:9090 "GET /api/v1/query_range?query=sum(rate(scylla_hints_manager_sent%7B%7D[15s]))&start=1587765056.8549407&end=1587765116.8549407&step=5 HTTP/1.1" 200 156
< t:2020-04-24 21:51:56,860 f:db_stats.py     l:150  c:sdcm.db_stats        p:DEBUG > Response from Prometheus server: {'status': 'success', 'data': {'resultType': 'matrix', 'result': [{'metric': {}, 'values': [[1587765056.855, '0'], [1587765061.855, '0'], [1587765066.855, '0'], [1587765071.855, '0'], [1587765076.855,
< t:2020-04-24 21:51:56,860 f:tester.py       l:1612 c:sdcm.tester          p:DEBUG > scylla_hints_manager_sent: [{'metric': {}, 'values': [[1587765056.855, '0'], [1587765061.855, '0'], [1587765066.855, '0'], [1587765071.855, '0'], [1587765076.855, '0'], [1587765081.855, '0'], [1587765086.855, '0'], [1587765091.855, '0'], [1587765096.855, '0'], [1587765101.855, '0'], [1587765106.855, '0'], [1587765111.855, '0'], [1587765116.855, '0']]}]
< t:2020-04-24 21:51:56,860 f:db_stats.py     l:182  c:sdcm.db_stats        p:DEBUG > Query to PrometheusDB: http://34.252.139.159:9090/api/v1/query_range?query=sum(rate(scylla_hints_manager_dropped{}[15s]))&start=1587764842.393117&end=1587765116.860696&step=5
< t:2020-04-24 21:51:56,862 f:connectionpool.py l:205  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 34.252.139.159:9090
< t:2020-04-24 21:51:56,864 f:connectionpool.py l:393  c:urllib3.connectionpool p:DEBUG > http://34.252.139.159:9090 "GET /api/v1/query_range?query=sum(rate(scylla_hints_manager_dropped%7B%7D[15s]))&start=1587764842.393117&end=1587765116.860696&step=5 HTTP/1.1" 200 276
< t:2020-04-24 21:51:56,865 f:db_stats.py     l:150  c:sdcm.db_stats        p:DEBUG > Response from Prometheus server: {'status': 'success', 'data': {'resultType': 'matrix', 'result': [{'metric': {}, 'values': [[1587764842.393, '0'], [1587764847.393, '0'], [1587764852.393, '0'], [1587764857.393, '0'], [1587764862.393,
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:654  c:sdcm.nemesis         p:ERROR > sdcm.nemesis.GeminiChaosMonkey: ('Exception in random_disrupt_method %s: %s', 'validate_hh_short_downtime', AssertionError('There were hint manager drops detected during the test!',))
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.GeminiChaosMonkey: Unhandled exception in method <function GeminiChaosMonkey.disrupt at 0x7f2d2ce56950> < t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.GeminiChaosMonkey: Unhandled exception in method <function GeminiChaosMonkey.disrupt at 0x7f2d2ce56950>
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1950, in wrapper
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 2583, in disrupt
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >     self.call_random_disrupt_method(disrupt_methods=self.disrupt_methods_list)
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 651, in call_random_disrupt_method
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >     disrupt_method()
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1354, in disrupt_validate_hh_short_downtime
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >     self.tester.verify_no_drops_and_errors(starting_from=start_time)
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/tester.py", line 1633, in verify_no_drops_and_errors
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR >     assert any([float(v[1]) for v in results[0]["values"]]) is False, err_msg
< t:2020-04-24 21:51:56,865 f:nemesis.py      l:1960 c:sdcm.nemesis         p:ERROR > AssertionError: There were hint manager drops detected during the test!
```

![Screenshot from 2020-04-27 16-48-54](https://user-images.githubusercontent.com/44991177/80359167-a5280200-88a7-11ea-8db3-ec817b639690.png)
![Screenshot from 2020-04-27 16-52-26](https://user-images.githubusercontent.com/44991177/80359170-a6592f00-88a7-11ea-9069-635c0881366d.png)

db logs: 
https://cloudius-jenkins-test.s3.amazonaws.com/b8197439-3e31-4ce3-8a7e-9ac0b4fdd36b/20200425_010715/db-cluster-b8197439.zip

to restore monitoring stack
hydra investigate show-monitor b8197439-3e31-4ce3-8a7e-9ac0b4fdd36b
and on grafana filter data for 7 days

**Comment by vladzcloudius** [comment]
Note that hints being dropped is a "hints admission control" in action.
By looking at graphs above I'd guess that you've either hit too many outstanding hints limit or the maximum amount of memory allocated to outstanding hints.

There is a gauge metric for outstanding hints.
