### ISSUE TITLE
concurrent_drain_test failed verify_cfhistograms: Write Latency is not monotonic: 11.0(75% load), was 12.0

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5033]
Scylla version 79935df959a7066ab1a61c1c4b350391a23cc2b5
Seen in [dtest-release/245/testReport/nodetool_additional_test/TestNodetool/concurrent_drain_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/245/testReport/nodetool_additional_test/TestNodetool/concurrent_drain_test/):
```
Error Message
Concurrent test failed
|0                                                                                                             |90|91|92                                    128|
----------------------------------------------------------------------------------------------------------------------------------------------------------------
[concurrent_stress                                                                                                                                             ]
                                                                                                                [dra]
                                                                                                                 [verify_info       ]
                                                                                                                 []
                                                                                                      verify_status
                                                                                                                 []
                                                                                                   verify_netstats
                                                                                                                 [X
                                                                                                verify_cfhistograms
                                                           Write Latency is not monotonic: 11.0(75% load), was 12.0
                                                                                                                 []
                                                                                                     verify_cfstats
                                                                                                                   []
                                                                                                 verify_describering
                                                                                                                   []
                                                                                               verify_decribecluster
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1618, in concurrent_drain_test
    self.general_concurrent(tst)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1551, in general_concurrent
    debug("Test call flow:\n" + self.print_time(self.concurrent_part(op)))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1527, in concurrent_part
    self.assertFalse(self.concurrent_test_fail, "Concurrent test failed\n" + self.print_time(res))
  File "/usr/lib64/python2.7/unittest/case.py", line 454, in assertFalse
    raise self.failureException(msg)

Standard Output
('Failed verify_cfhistograms', ' with ', AssertionError('Write Latency is not monotonic: 11.0(75% load), was 12.0',))
```

**Comment by bhalevy** [comment]
@amnonh does that fall in your realm?

**Comment by amnonh** [comment]
@bhalevy @slivne I'm looking into it, but maybe we can remove all the concurrent tests, there were there at a phase that he had little such tests by the QA and now it takes a long time other tests are doing it anyhow.

**Comment by slivne** [comment]
We do run some nodetool command in parallel with SCT (by mere luck) - assuming we are checking this in other places is not complete.

Please try to fix this, we can make the tests "more relaxed" in some sense - we are mainly concerned in seeing that parallel operation is not getting the node to a bad state.

**Comment by amnonh** [comment]
I've looked at it and tried unsuccessfully to reproduce.
There is no reason, I've sent a PR to the dtest to add the entire output of cfstats.

In general, there shouldn't be a situation that this validation should fail, so I prefer to identify the root cause rather than relax the tests.

**Comment by slivne** [comment]
the tests are failing all over for other reason https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/439/testReport/nodetool_additional_test/TestNodetool/concurrent_drain_test/ ... leaving this open till we fix that

it seems this is relate dto other changes done in dtest and ccm

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/353/

and the fact those changes caused a regression in this test - was not taken care off.

@bhalevy - is this known ?

**Comment by bhalevy** [comment]
> @bhalevy - is this known ?

@slivne yes.  It's unclear why stress fails in this test and if it's a scylla bug or not.

**Comment by bhalevy** [comment]
Ref https://github.com/scylladb/scylla/issues/6792
