### ISSUE TITLE
WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM after stop_start_scylla_server nemesis

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#5040]
Installation details
Scylla version (or git commit hash): 3.1.0.rc6
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-09337cd80d5626a43

scenario: 50GB longevity - the was a nemesis of restart with resharding. then, few minutes later there was a nemesis of stop_start_scylla_server and one of the stress loads failed.

failure:
```
< t:2019-09-13 05:08:32,950 f:sct_events.py   l:452  c:sdcm.sct_events      p:INFO  > 2019-09-13 05:08:32.913: (DatabaseLogEvent Severity.NORMAL): type=BOOT regex=Starting Scylla Server line_number=37532 node=Node longevity-tls-50g
b-4d-3-1-db-node-7d2b56ac-4 [34.254.192.76 | 10.0.221.4] (seed: False)
< t:2019-09-13 05:08:32,950 f:sct_events.py   l:452  c:sdcm.sct_events      p:INFO  > 2019-09-13T05:08:30+00:00  ip-10-0-221-4 !INFO    | systemd: Starting Scylla Server...
< t:2019-09-13 05:08:32,951 f:connectionpool.py l:205  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 10.0.42.141:3000
< t:2019-09-13 05:08:32,960 f:connectionpool.py l:393  c:urllib3.connectionpool p:DEBUG > http://10.0.42.141:3000 "POST /api/annotations HTTP/1.1" 200 39
< t:2019-09-13 05:08:32,962 f:sct_events.py   l:509  c:sdcm.sct_events      p:INFO  > {"id":424,"message":"Annotation added"}
< t:2019-09-13 05:08:32,984 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: com.datastax.driver.core.exceptions.OperationTimedOutException: [ip-10-0-195-213.eu-west-1.compute.interna
l/10.0.195.213:9042] Timed out waiting for server response
< t:2019-09-13 05:08:32,994 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.202.223]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at 
consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2019-09-13 05:08:33,046 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: total,     121021933,    2184,    2184,    2184,     4.6,     4.1,     6.9,    24.0,    41.5,    44.5,6783
8.0,  0.00174,      0,      0,       0,       0,       0,       0
< t:2019-09-13 05:08:33,105 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.111.96]: total,     115111582,    1947,    1947,    1947,     5.1,     4.3,    11.0,    29.2,    47.1,    49.8,67809
.0,  0.00414,      0,      0,       0,       0,       0,       0
< t:2019-09-13 05:08:33,110 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: total,     153239224,    1315,    1315,    1315,     6.7,     4.2,    13.0,    31.0,    92.6,  5003.8,6773
0.0,  0.52001,      0,      0,       0,       0,       0,       0
< t:2019-09-13 05:08:33,159 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.202.223]: total,     109752036,    2225,    2225,    2225,     4.0,     3.9,     5.9,    15.7,    46.6,    51.3,6781
2.0,  0.00828,      0,      0,       0,       0,       0,       0
< t:2019-09-13 05:08:33,174 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.111.96]: total,     157033465,    2855,    2855,    2855,     7.3,     4.6,     9.5,    38.3,    77.0, 10007.6,67760
.0,  0.38729,      0,      0,       0,       0,       0,       0
< t:2019-09-13 05:08:33,174 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.111.96]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at c
onsistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2019-09-13 05:08:33,180 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.202.223]: total,     157033477,    2856,    2856,    2856,     7.0,     6.2,     9.6,    38.3,    74.1,   126.4,6776
5.0,  0.10520,      0,      0,       0,       0,       0,       0
< t:2019-09-13 05:08:33,187 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.111.96]: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistenc
y QUORUM (2 responses were required but only 1 replica responded)
< t:2019-09-13 05:08:33,190 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.202.223]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at 
consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2019-09-13 05:08:33,190 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: com.datastax.driver.core.exceptions.OperationTimedOutException: [ip-10-0-195-213.eu-west-1.compute.interna
l/10.0.195.213:9042] Timed out waiting for server response
< t:2019-09-13 05:08:33,191 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at 
consistency QUORUM (2 replica were required but only 1 acknowledged the write)
...
< t:2019-09-13 05:08:34,724 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: java.io.IOException: Operation x10 on key(s) [504e314b393832383631]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2019-09-13 05:08:34,725 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: 
< t:2019-09-13 05:08:34,729 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]:    at org.apache.cassandra.stress.Operation.error(Operation.java:136)
< t:2019-09-13 05:08:34,734 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]:    at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:114)
< t:2019-09-13 05:08:34,735 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
< t:2019-09-13 05:08:34,735 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
< t:2019-09-13 05:08:34,736 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
< t:2019-09-13 05:08:34,736 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: com.datastax.driver.core.exceptions.OperationTimedOutException: [ip-10-0-195-213.eu-west-1.compute.internal/10.0.195.213:9042] Timed out waiting for server response
< t:2019-09-13 05:08:34,736 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]:    at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:468)
< t:2019-09-13 05:08:34,739 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: total,     584879755,       1,       1,       1, 20006.8, 20015.2, 20015.2, 20015.2, 20015.2, 20015.2,67975.7,  0.02504,      1,      0,       0,       0,       0,       0
< t:2019-09-13 05:08:34,756 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.111.96]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2019-09-13 05:08:34,784 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.131.230]: com.datastax.driver.core.exceptions.OperationTimedOutException: [ip-10-0-195-213.eu-west-1.compute.internal/10.0.195.213:9042] Timed out waiting for server response

```
logs:
scratch.scylladb.com/issues/sct_io_exception.log.gz
snapshot:
https://snapshot.raintank.io/dashboard/snapshot/egnyru81WzefQhd56HICkhYVEyNbfv1A
nemesis list:
```
< t:2019-09-12 09:51:43,422 f:nemesis.py      l:584  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_cleanup
< t:2019-09-12 10:09:29,358 f:nemesis.py      l:584  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_refresh
< t:2019-09-12 10:20:01,930 f:nemesis.py      l:584  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_refresh
< t:2019-09-12 10:36:32,626 f:nemesis.py      l:584  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_drain
< t:2019-09-12 10:58:19,530 f:nemesis.py      l:584  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_cleanup
< t:2019-09-12 22:48:23,980 f:nemesis.py      l:584  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method stop_wait_start_scylla_server
< t:2019-09-12 23:13:17,911 f:nemesis.py      l:584  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method restart_with_resharding
< t:2019-09-13 05:08:07,045 f:nemesis.py      l:584  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method stop_start_scylla_server
< t:2019-09-13 05:25:15,347 f:nemesis.py      l:584  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method stop_start_scylla_server

```
longevity stress commands are:
```
prepare_write_cmd: ["cassandra-stress write cl=QUORUM n=100000000 -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native  -rate threads=500 -pop seq=1..100000000",
                    "cassandra-stress counter_write cl=QUORUM n=1000000 -schema 'replication(factor=3) compaction(strategy=DateTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1 -pop seq=1..1000000"]
stress_cmd: ["cassandra-stress mixed cl=QUORUM duration=5760m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native  -rate threads=20 -pop seq=1..100000000 -log interval=5",
             "cassandra-stress counter_write cl=QUORUM duration=5760m -schema 'replication(factor=3) compaction(strategy=DateTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1 -pop seq=1..1000000",
             "cassandra-stress user profile=/tmp/cs_mv_profile.yaml ops'(insert=3,read1=1,read2=1,read3=1)' cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native -rate threads=10",
             "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4 -rate threads=50 -pop seq=1..100000000 -log interval=5",
             "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=SnappyCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=snappy -rate threads=50 -pop seq=1..100000000 -log interval=5",
             "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=DeflateCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none -rate threads=50 -pop seq=1..100000000 -log interval=5"]
stress_read_cmd: ["cassandra-stress read cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native  -rate threads=50 -pop seq=1..100000000 -log interval=5",
                  "cassandra-stress counter_read cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native -rate threads=10 -pop seq=1..1000000",
                  "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4 -rate threads=20 -pop seq=1..100000000 -log interval=5",
                  "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=SnappyCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=snappy -rate threads=20 -pop seq=1..100000000 -log interval=5",
                  "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=DeflateCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none -rate threads=20 -pop seq=1..100000000 -log interval=5"]
```

**Comment by yarongilor** [comment]
more logs could be found here:
< t:2019-09-16 10:47:13,540 f:common.py       l:333  c:utils                p:INFO  > Uploading '/sct/events_log.zip' to https://cloudius-jenkins-test.s3.amazonaws.com/7d2b56ac-9b39-4bc2-a99d-cba76d6a7ee6/events_log.zip
< t:2019-09-16 11:05:04,497 f:common.py       l:333  c:utils                p:INFO  > Uploading '/sct/20190912-093414-446865/job_log.zip' to https://cloudius-jenkins-test.s3.amazonaws.com/7d2b56ac-9b39-4bc2-a99d-cba76d6a7ee6/job_log.zip

**Comment by slivne** [comment]
I expect resharding did not end and as such it restarted (potentially with more todo) after the stop and start.

I am closing this for now as 3.3 is almost out - if it happens on 3.3 and newer releases please create a new issue 

(we are also working on changing the way we handle resharding as part of off compaction strategy)
