### ISSUE TITLE
mutation_test hangs

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5093]
Seen in [next/1196](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1196)
Scylla version d57ab83bc892f7bb562f3860a185197a0f1cfcbe
```
jenkins     56     1 99 16:33 ?        01:40:01 build/dev/tests/mutation_test --report_level=no --logger=HRF,test_suite:XML,test_suite,jenkins_test.release.mutation_test.boost.xml -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0
```

since it's in dev mode we can't get much out of gdb so the info below is just for reference

```
(gdb) info threads
  Id   Target Id                                      Frame 
* 1    Thread 0x7f0970683280 (LWP 56) "mutation_test" 0x00007f09733e44d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  2    Thread 0x7f09703ff700 (LWP 79) "mutation_test" 0x0000000001427e9d in ?? ()
  3    Thread 0x7f096fdff700 (LWP 165) "reactor-1"    0x00007f0972963466 in epoll_pwait () from /lib64/libc.so.6
  4    Thread 0x7f096f7ff700 (LWP 168) "syscall-0"    0x00007f09733e7bec in read () from /lib64/libpthread.so.0
  5    Thread 0x7f096f462700 (LWP 169) "timer-0"      0x00007f09733e7bec in read () from /lib64/libpthread.so.0
  6    Thread 0x7f096e9ff700 (LWP 170) "syscall-1"    0x00007f09733e7bec in read () from /lib64/libpthread.so.0
  7    Thread 0x7f096e650700 (LWP 171) "timer-1"      0x00007f09733e7bec in read () from /lib64/libpthread.so.0

(gdb) bt
#0  0x00007f09733e44d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f0972b19950 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#2  0x000000000188ebd4 in ?? ()
#3  0x000000000188da13 in ?? ()
#4  0x000000000188d27d in ?? ()
#5  0x00007f0972e6f582 in ?? () from /lib64/libboost_unit_test_framework.so.1.69.0
#6  0x00007f0972e6e5ed in boost::execution_monitor::catch_signals(boost::function<int ()> const&) () from /lib64/libboost_unit_test_framework.so.1.69.0
#7  0x00007f0972e6e678 in boost::execution_monitor::execute(boost::function<int ()> const&) () from /lib64/libboost_unit_test_framework.so.1.69.0
#8  0x00007f0972e6e74e in boost::execution_monitor::vexecute(boost::function<void ()> const&) () from /lib64/libboost_unit_test_framework.so.1.69.0
#9  0x00007f0972e9924f in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) () from /lib64/libboost_unit_test_framework.so.1.69.0
#10 0x00007f0972e7e680 in ?? () from /lib64/libboost_unit_test_framework.so.1.69.0
#11 0x00007f0972e7e914 in ?? () from /lib64/libboost_unit_test_framework.so.1.69.0
#12 0x00007f0972e75c74 in boost::unit_test::framework::run(unsigned long, bool) () from /lib64/libboost_unit_test_framework.so.1.69.0
#13 0x00007f0972e980d2 in boost::unit_test::unit_test_main(bool (*)(), int, char**) () from /lib64/libboost_unit_test_framework.so.1.69.0
#14 0x000000000188d69a in ?? ()
#15 0x000000000043ad23 in ?? ()
#16 0x00007f097288bf33 in __libc_start_main () from /lib64/libc.so.6
#17 0x000000000042cafe in ?? ()

(gdb) thread 2
[Switching to thread 2 (Thread 0x7f09703ff700 (LWP 79))]
#0  0x00000000004aeca7 in ?? ()
(gdb) bt
#0  0x00000000004aeca7 in ?? ()
#1  0x0000000001466c2e in ?? ()
#2  0x0000000001454cea in ?? ()
#3  0x00000000014652f2 in ?? ()
#4  0x000000000146533e in ?? ()
#5  0x000000000145b918 in ?? ()
#6  0x000000000145bf75 in ?? ()
#7  0x000000000145c108 in ?? ()
#8  0x000000000145fc39 in ?? ()
#9  0x00000000014606e2 in ?? ()
#10 0x0000000001461ebb in ?? ()
#11 0x000000000048dad8 in ?? ()
#12 0x00000000004ce4b4 in ?? ()
#13 0x00000000017825a7 in ?? ()
```

**Comment by slivne** [comment]
@bhalevy is this still relevant - can we close this ?

**Comment by bhalevy** [comment]
> @bhalevy is this still relevant - can we close this ?

Haven't seen since.  We can close and reopen if hit again.
