### ISSUE TITLE
scylla-docker: c-s read failed after restart

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5096]
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc8-0.20190923.21aec9c7e
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker: scylladb/scylla-nightly:3.1.0.rc8

### Test jobs:
- http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/docker-test/20/
- http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/docker-test/21/

### Description:

We have two subtests in scylla_docker test:

- test_basic_stress: Run nodetool and cassandra stress utilities when cluster is prepared
- test_stress_with_restart: Run cassandra stress write, restart cluster, run stress read

IN above two jobs, the test_basic_stress all PASSed. but test_stress_with_restart failed, c-s read workload failed after cluster restart.

In my manual testing, the c-s read workload after cluster restart didn't failed, but stuck.
It stuck again when I canceled old one and rerun it.

### additional info:

I didn't find any database error in docker logs of node1 & node2

The two nodes are up after restart, confirmed by both 
- `docker exec node1 nodetool status`
- `docker exec node2 nodetool status`

@penberg @hagitsegev @slivne @roydahan

**Comment by amoskong** [comment]
```
2019-09-25 03:21:03 'docker exec node1 cassandra-stress read n=300000 -rate threads=10 -node 172.17.0.2'
2019-09-25 03:21:04] ******************** Stress Settings ********************
2019-09-25 03:21:04] Command:
2019-09-25 03:21:04]   Type: read
2019-09-25 03:21:04]   Count: 300,000
2019-09-25 03:21:04]   No Warmup: false
2019-09-25 03:21:04]   Consistency Level: LOCAL_ONE
2019-09-25 03:21:04]   Target Uncertainty: not applicable
2019-09-25 03:21:04]   Key Size (bytes): 10
2019-09-25 03:21:04]   Counter Increment Distibution: add=fixed(1)
2019-09-25 03:21:04] Rate:
2019-09-25 03:21:04]   Auto: false
2019-09-25 03:21:04]   Thread Count: 10
2019-09-25 03:21:04]   OpsPer Sec: 0
2019-09-25 03:21:04] Population:
2019-09-25 03:21:04]   Distribution: Gaussian:  min=1,max=300000,mean=150000.500000,stdev=49999.833333
2019-09-25 03:21:04]   Order: ARBITRARY
2019-09-25 03:21:04]   Wrap: false
2019-09-25 03:21:04] Insert:
2019-09-25 03:21:04]   Revisits: Uniform:  min=1,max=1000000
2019-09-25 03:21:04]   Visits: Fixed:  key=1
2019-09-25 03:21:04]   Row Population Ratio: Ratio: divisor=1.000000;delegate=Fixed:  key=1
2019-09-25 03:21:04]   Batch Type: not batching
2019-09-25 03:21:04] Columns:
2019-09-25 03:21:04]   Max Columns Per Key: 5
2019-09-25 03:21:04]   Column Names: [C0, C1, C2, C3, C4]
2019-09-25 03:21:04]   Comparator: AsciiType
2019-09-25 03:21:04]   Timestamp: null
2019-09-25 03:21:04]   Variable Column Count: false
2019-09-25 03:21:04]   Slice: false
2019-09-25 03:21:04]   Size Distribution: Fixed:  key=34
2019-09-25 03:21:04]   Count Distribution: Fixed:  key=5
2019-09-25 03:21:04] Errors:
2019-09-25 03:21:04]   Ignore: false
2019-09-25 03:21:04]   Tries: 10
2019-09-25 03:21:04] Log:
2019-09-25 03:21:04]   No Summary: false
2019-09-25 03:21:04]   No Settings: false
2019-09-25 03:21:04]   File: null
2019-09-25 03:21:04]   Interval Millis: 1000
2019-09-25 03:21:04]   Level: NORMAL
2019-09-25 03:21:04] Mode:
2019-09-25 03:21:04]   API: JAVA_DRIVER_NATIVE
2019-09-25 03:21:04]   Connection Style: CQL_PREPARED
2019-09-25 03:21:04]   CQL Version: CQL3
2019-09-25 03:21:04]   Protocol Version: V4
2019-09-25 03:21:04]   Username: null
2019-09-25 03:21:04]   Password: null
2019-09-25 03:21:04]   Auth Provide Class: null
2019-09-25 03:21:04]   Max Pending Per Connection: 128
2019-09-25 03:21:04]   Connections Per Host: 8
2019-09-25 03:21:04]   Compression: NONE
2019-09-25 03:21:04] Node:
2019-09-25 03:21:04]   Nodes: [172.17.0.2]
2019-09-25 03:21:04]   Is White List: false
2019-09-25 03:21:04]   Datacenter: null
2019-09-25 03:21:04] Schema:
2019-09-25 03:21:04]   Keyspace: keyspace1
2019-09-25 03:21:04]   Replication Strategy: org.apache.cassandra.locator.SimpleStrategy
2019-09-25 03:21:04]   Replication Strategy Pptions: {replication_factor=1}
2019-09-25 03:21:04]   Table Compression: null
2019-09-25 03:21:04]   Table Compaction Strategy: null
2019-09-25 03:21:04]   Table Compaction Strategy Options: {}
2019-09-25 03:21:04] Transport:
2019-09-25 03:21:04]   factory=org.apache.cassandra.thrift.TFramedTransportFactory; truststore=null; truststore-password=null; keystore=null; keystore-password=null; ssl-protocol=TLS; ssl-alg=SunX509; store-type=JKS; ssl-ciphers=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA; 
2019-09-25 03:21:04] Port:
2019-09-25 03:21:04]   Native Port: 9042
2019-09-25 03:21:04]   Thrift Port: 9160
2019-09-25 03:21:04]   JMX Port: 7199
2019-09-25 03:21:04] Send To Daemon:
2019-09-25 03:21:04]   *not set*
2019-09-25 03:21:04] Graph:
2019-09-25 03:21:04]   File: null
2019-09-25 03:21:04]   Revision: unknown
2019-09-25 03:21:04]   Title: null
2019-09-25 03:21:04]   Operation: READ
2019-09-25 03:21:04] TokenRange:
2019-09-25 03:21:04]   Wrap: false
2019-09-25 03:21:04]   Split Factor: 1
2019-09-25 03:21:04] 
2019-09-25 03:21:04] Sleeping 2s...
2019-09-25 03:21:06] Warming up READ with 50000 iterations...
2019-09-25 03:21:06] Failed to connect over JMX; not collecting these stats
2019-09-25 03:21:06] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.17.0.2:9042] Cannot connect))
2019-09-25 03:21:06] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.17.0.2:9042] Cannot connect))
2019-09-25 03:21:06] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.17.0.2:9042] Cannot connect))
2019-09-25 03:21:06] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.17.0.2:9042] Cannot connect))
2019-09-25 03:21:06] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.17.0.2:9042] Cannot connect))
2019-09-25 03:21:06] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.17.0.2:9042] Cannot connect))
2019-09-25 03:21:06] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.17.0.2:9042] Cannot connect))
2019-09-25 03:21:06] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.17.0.2:9042] Cannot connect))
2019-09-25 03:21:06] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.17.0.2:9042] Cannot connect))
2019-09-25 03:21:06] Failed to create client too many times
2019-09-25 03:21:06] java.lang.RuntimeException: Failed to execute warmup
2019-09-25 03:21:06] 	at org.apache.cassandra.stress.StressAction.warmup(StressAction.java:123)
2019-09-25 03:21:06] 	at org.apache.cassandra.stress.StressAction.run(StressAction.java:70)
2019-09-25 03:21:06] 	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
2019-09-25 03:21:06] 	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

**Comment by amoskong** [comment]
I can still reproduce this issue with a single node.

**Comment by amoskong** [comment]
The problem doesn't exist in 3.1.0.rc7
- original job: http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/docker-test/12/  PASSed
- rerun: http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/docker-test/label=muninn/22/console  PASSed

**Comment by penberg** [comment]
I don't see how this could be a Docker issue. Instead, it seems more likely that the Scylla server has some issue (ran out of disk space, crashed, or something else).

**Comment by amoskong** [comment]
```
$ git log --oneline scylla-3.1.0.rc7..scylla-3.1.0.rc8
21aec9c7ef (tag: scylla-3.1.0.rc8) release: prepare for 3.1.0.rc8
02ce19e851 storage_service: Replicate and advertise tokens early in the boot up process
37c4be5e74 Storage proxy: protect against infinite recursion in query_partition_key_range_concurrent
d81ac93728 Update seastar submodule
024d1563ad Revert "Simplify db::cql_type_parser::parse"
```

@asias 's change related with token replicate after restart, this issue might be caused by that.
https://github.com/scylladb/scylla/commit/02ce19e851f0cda92f0a88331810f181b9e2e6f6

**Comment by amoskong** [comment]
This issue also exists in scylla master:
- http://jenkins.scylladb.com/job/scylla-master/job/docker-test/40/label=muninn/console
- scylla-nightly:666.development-201909241147

**Comment by asias** [comment]
> I can still reproduce this issue with a single node.

How did you reproduce? Can you share the details?
If you connect to cql port once you see nodetool status shows a node is in UN status, the node might not open cql server yet.

**Comment by asias** [comment]
I saw you mentioned:
```
test_stress_with_restart: Run cassandra stress write, restart cluster, run stress read
```

When do you start to run the stress read workload after the nodes restart? How do you check the CQL port is open and ready?

**Comment by amoskong** [comment]
> > I can still reproduce this issue with a single node.
> 
> How did you reproduce? Can you share the details?

```
docker pull scylladb/scylla-nightly:3.1.0.rc8
docker run --name node1-rc8 -d scylladb/scylla-nightly:3.1.0.rc8

Repeated to check until node is up
- docker exec node1-rc8 nodetool status

docker exec node1-rc8 cassandra-stress write cl=QUORUM n=30000 -schema 'replication(factor=1)' -rate threads=10 -node 172.17.0.2
docker exec node1-rc8 cassandra-stress read cl=QUORUM n=30000 -schema 'replication(factor=1)' -rate threads=10 -node 172.17.0.2

Restart cluster
- docker stop node1-rc8
- docker start node1-rc8

Repeated to check until node is up
- docker exec node1-rc8 nodetool status

docker exec node1-rc8 cassandra-stress read cl=QUORUM n=30000 -schema 'replication(factor=1)' -rate threads=10 -node 172.17.0.2
```

> If you connect to cql port once you see nodetool status shows a node is in UN status, the node might not open cql server yet.

I tested again, after saw db up by 'nodetool status', cqlsh failed to connect server, and c-s failed.


```
[amos@amos-centos7 ~]$ docker exec node1-rc8 nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.2  0 bytes    256          ?       677a180a-bd82-4819-b74d-8321208b967f  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
[amos@amos-centos7 ~]$ cqlsh 172.17.0.2
Connection error: ('Unable to connect to any servers', {'172.17.0.2': error(111, "Tried connecting to [('172.17.0.2', 9042)]. Last error: Connection refused")})
[amos@amos-centos7 ~]$ cqlsh 172.17.0.2
Connection error: ('Unable to connect to any servers', {'172.17.0.2': error(111, "Tried connecting to [('172.17.0.2', 9042)]. Last error: Connection refused")})
```

**Comment by amoskong** [comment]
> I saw you mentioned:
> 
> ```
> test_stress_with_restart: Run cassandra stress write, restart cluster, run stress read
> ```
> 
> When do you start to run the stress read workload after the nodes restart? How do you check the CQL port is open and ready?

Our test isn't check the port, but checking the node status (expected UN) in `nodetool status`.

**Comment by amoskong** [comment]
> > > I can still reproduce this issue with a single node.
> > 
> > 
> > How did you reproduce? Can you share the details?
> 
> ```
> docker pull scylladb/scylla-nightly:3.1.0.rc8
> docker run --name node1-rc8 -d scylladb/scylla-nightly:3.1.0.rc8
> 
> Repeated to check until node is up
> - docker exec node1-rc8 nodetool status
> 
> docker exec node1-rc8 cassandra-stress write cl=QUORUM n=30000 -schema 'replication(factor=1)' -rate threads=10 -node 172.17.0.2
> docker exec node1-rc8 cassandra-stress read cl=QUORUM n=30000 -schema 'replication(factor=1)' -rate threads=10 -node 172.17.0.2
> 
> Restart cluster
> - docker stop node1-rc8
> - docker start node1-rc8
> 
> Repeated to check until node is up
> - docker exec node1-rc8 nodetool status
> 
> docker exec node1-rc8 cassandra-stress read cl=QUORUM n=30000 -schema 'replication(factor=1)' -rate threads=10 -node 172.17.0.2
> ```
> 
> > If you connect to cql port once you see nodetool status shows a node is in UN status, the node might not open cql server yet.
> 
> I tested again, after saw db up by 'nodetool status', cqlsh failed to connect server, and c-s failed.
> 
> ```
> [amos@amos-centos7 ~]$ docker exec node1-rc8 nodetool status
> Datacenter: datacenter1
> =======================
> Status=Up/Down
> |/ State=Normal/Leaving/Joining/Moving
> --  Address     Load       Tokens       Owns    Host ID                               Rack
> UN  172.17.0.2  0 bytes    256          ?       677a180a-bd82-4819-b74d-8321208b967f  rack1
> 
> Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
> [amos@amos-centos7 ~]$ cqlsh 172.17.0.2
> Connection error: ('Unable to connect to any servers', {'172.17.0.2': error(111, "Tried connecting to [('172.17.0.2', 9042)]. Last error: Connection refused")})
> [amos@amos-centos7 ~]$ cqlsh 172.17.0.2
> Connection error: ('Unable to connect to any servers', {'172.17.0.2': error(111, "Tried connecting to [('172.17.0.2', 9042)]. Last error: Connection refused")})
> ```

In the log, we can see, the node state jump to normal first at (08:40:21)
But start to listening cql clients around (08:40:33)

IN this gap (about 12 seconds), cqlsh will fail. And c-s also might fail.

```
INFO  2019-09-25 08:40:21,616 [shard 0] database - Schema version changed to 6d3fe499-11fc-37b2-a6d1-0492a7e8a043

INFO  2019-09-25 08:40:21,722 [shard 0] storage_service - Node 172.17.0.2 state jump to normal

INFO  2019-09-25 08:40:21,788 [shard 0] storage_service - NORMAL: node is now in normal status
INFO  2019-09-25 08:40:21,791 [shard 0] storage_service - SSTable data integrity checker is disabled.
INFO  2019-09-25 08:40:21,792 [shard 0] init - Waiting for gossip to settle before accepting client requests...
...
INFO  2019-09-25 08:40:33,793 [shard 0] gossip - No gossip backlog; proceeding
INFO  2019-09-25 08:40:33,796 [shard 0] storage_service - Starting listening for CQL clients on 172.17.0.2:9042 (unencrypted)
INFO  2019-09-25 08:40:33,797 [shard 0] storage_service - Thrift server listening on 172.17.0.2:9160 ...
INFO  2019-09-25 08:40:33,798 [shard 0] init - Scylla version 3.1.0.rc8-0.20190923.21aec9c7e initialization completed.
```

**Comment by asias** [comment]
I think the problem is the test itself. UN from nodetool status does not guarantee the cql port is open.

**Comment by amoskong** [comment]
> I think the problem is the test itself. UN from nodetool status does not guarantee the cql port is open.

OK, I will fix scylla_docker test.
