### ISSUE TITLE
resharding_by_murmur3_decrease_test: Encountered exception creating schema: Timed out waiting for server response

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5148]
Seen in [dtest-release/268/testReport/resharding_test/ReshardingTest_nodes4_with_DateTieredCompactionStrategy/resharding_by_murmur3_decrease_test](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/testReport/resharding_test/ReshardingTest_nodes4_with_DateTieredCompactionStrategy/resharding_by_murmur3_decrease_test/)
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/resharding_test.py", line 188, in resharding_by_murmur3_decrease_test
    self._resharding_basic(self.smp, rows=1000, murmur3=self.MURMUR3_PARTITIONER_FOR_DECREASE)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/resharding_test.py", line 147, in _resharding_basic
    self._run_stress(op_cnt, stress_cmd)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/resharding_test.py", line 118, in _run_stress
    res = self.node.stress_object(stress_cmd)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 1170, in stress_object
    out, err = self.stress(stress_options, True, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 1137, in stress
    "stderr: {stderr}\n".format(**locals())
AssertionError: Stress command exited with error code: 1
stdout: ******************** Stress Settings ********************
Command:
  Type: write
  Count: 1,000
  No Warmup: true
  Consistency Level: LOCAL_ONE
  Target Uncertainty: not applicable
  Key Size (bytes): 10
  Counter Increment Distibution: add=fixed(1)
Rate:
  Auto: false
  Thread Count: 16
  OpsPer Sec: 0
Population:
  Sequence: 1..1000
  Order: ARBITRARY
  Wrap: true
Insert:
  Revisits: Uniform:  min=1,max=1000000
  Visits: Fixed:  key=1
  Row Population Ratio: Ratio: divisor=1.000000;delegate=Fixed:  key=1
  Batch Type: not batching
Columns:
  Max Columns Per Key: 5
  Column Names: [C0, C1, C2, C3, C4]
  Comparator: AsciiType
  Timestamp: null
  Variable Column Count: false
  Slice: false
  Size Distribution: Fixed:  key=34
  Count Distribution: Fixed:  key=5
Errors:
  Ignore: false
  Tries: 10
Log:
  No Summary: false
  No Settings: false
  File: null
  Interval Millis: 1000
  Level: NORMAL
Mode:
  API: JAVA_DRIVER_NATIVE
  Connection Style: CQL_PREPARED
  CQL Version: CQL3
  Protocol Version: V4
  Username: null
  Password: null
  Auth Provide Class: null
  Max Pending Per Connection: 128
  Connections Per Host: 8
  Compression: NONE
Node:
  Nodes: [127.0.90.1]
  Is White List: false
  Datacenter: null
Schema:
  Keyspace: keyspace1
  Replication Strategy: org.apache.cassandra.locator.SimpleStrategy
  Replication Strategy Pptions: {replication_factor=3}
  Table Compression: null
  Table Compaction Strategy: DateTieredCompactionStrategy
  Table Compaction Strategy Options: {}
Transport:
  factory=org.apache.cassandra.thrift.TFramedTransportFactory; truststore=null; truststore-password=null; keystore=null; keystore-password=null; ssl-protocol=TLS; ssl-alg=SunX509; store-type=JKS; ssl-ciphers=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA; 
Port:
  Native Port: 9042
  Thrift Port: 9160
  JMX Port: 7190
Send To Daemon:
  *not set*
Graph:
  File: null
  Revision: unknown
  Title: null
  Operation: WRITE
TokenRange:
  Wrap: false
  Split Factor: 1

Connected to cluster: test, max pending requests per connection 128, max connections per host 8
Datatacenter: datacenter1; Host: /127.0.90.1; Rack: rack1
Datatacenter: datacenter1; Host: /127.0.90.2; Rack: rack1
Datatacenter: datacenter1; Host: /127.0.90.3; Rack: rack1
Datatacenter: datacenter1; Host: /127.0.90.4; Rack: rack1

stderr: java.lang.RuntimeException: Encountered exception creating schema
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:100)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:228)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:57)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.90.3:9042] Timed out waiting for server response
	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:44)
	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:26)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:188)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:89)
	... 5 more
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.90.3:9042] Timed out waiting for server response
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:825)
	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1392)
	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at com.datastax.shaded.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

[node1.log](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/artifact/logs-release.2/1570099026865_resharding_test.ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_murmur3_decrease_test/node1.log):
```
INFO  2019-10-03 10:36:49,954 [shard 1] migration_manager - Create new Keyspace: KSMetaData{name=keyspace1, strategyClass=org.apache.cassandra.locator.SimpleStrategy, strategyOptions={replication_factor=3}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x6010007f8840}
INFO  2019-10-03 10:36:53,386 [shard 1] schema_tables - Creating keyspace keyspace1
INFO  2019-10-03 10:36:53,397 [shard 1] database - Schema version changed to 454a5e91-ab8c-3fd7-9ce0-10d0a4e2d1a2
INFO  2019-10-03 10:37:03,025 [shard 1] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-VftiCB/test/node1/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-11-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-VftiCB/test/node1/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-6-big-Data.db:level=0, ]
INFO  2019-10-03 10:37:03,577 [shard 0] schema_tables - Creating keyspace1.standard1 id=b7b68490-e5c9-11e9-b08c-000000000002 version=f0793569-c78d-37ec-8d80-2011e9f4f5b6
INFO  2019-10-03 10:37:03,589 [shard 0] database - Schema version changed to a095a0ae-713c-3cdd-8f98-9c8869e4ca72
```

[node2.log](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/artifact/logs-release.2/1570099026865_resharding_test.ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_murmur3_decrease_test/node2.log):
```
INFO  2019-10-03 10:36:52,258 [shard 1] schema_tables - Creating keyspace keyspace1
INFO  2019-10-03 10:36:52,269 [shard 1] database - Schema version changed to 454a5e91-ab8c-3fd7-9ce0-10d0a4e2d1a2
INFO  2019-10-03 10:37:00,847 [shard 1] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-VftiCB/test/node2/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-11-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-VftiCB/test/node2/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-6-big-Data.db:level=0, ]
INFO  2019-10-03 10:37:02,935 [shard 0] schema_tables - Creating keyspace1.standard1 id=b7b68490-e5c9-11e9-b08c-000000000002 version=f0793569-c78d-37ec-8d80-2011e9f4f5b6
INFO  2019-10-03 10:37:02,952 [shard 0] database - Schema version changed to a095a0ae-713c-3cdd-8f98-9c8869e4ca72
```

[node3.log](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/artifact/logs-release.2/1570099026865_resharding_test.ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_murmur3_decrease_test/node3.log)
```
INFO  2019-10-03 10:36:52,114 [shard 1] schema_tables - Creating keyspace keyspace1
INFO  2019-10-03 10:36:52,124 [shard 1] database - Schema version changed to 454a5e91-ab8c-3fd7-9ce0-10d0a4e2d1a2
INFO  2019-10-03 10:36:54,489 [shard 0] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x600001141880[cfId=b7b68490-e5c9-11e9-b08c-000000000002,ksName=keyspace1,cfName=standard1,cfType=Standard,comparator=org.apache.cassandra.db.marshal.UTF8Type,comment=,readRepairChance=0,dcLocalReadRepairChance=0.1,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.BytesType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=key, type=org.apache.cassandra.db.marshal.BytesType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=C0, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C1, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C2, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C3, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C4, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.DateTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=b7b68491-e5c9-11e9-b08c-000000000002,droppedColumns={},collections={},indices={}]
```

[node4.log](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/artifact/logs-release.2/1570099026865_resharding_test.ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_murmur3_decrease_test/node4.log):
```
INFO  2019-10-03 10:37:03,012 [shard 0] migration_manager - Requesting schema pull from 127.0.90.2:0
INFO  2019-10-03 10:37:03,012 [shard 0] migration_manager - Pulling schema from 127.0.90.2:0
INFO  2019-10-03 10:37:03,604 [shard 0] migration_manager - Requesting schema pull from 127.0.90.1:0
INFO  2019-10-03 10:37:03,604 [shard 0] migration_manager - Pulling schema from 127.0.90.1:0
```

This looks similar to #4388

**Comment by bhalevy** [comment]
Scylla version 3b9bf9d448b7561ad4f51896ea3b1de830db547e

Seen also in:
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/testReport/resharding_test/ReshardingTest_nodes4_with_DateTieredCompactionStrategy/resharding_by_murmur3_smp_test/
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/simple_kill_new_node_while_bootstrapping_test/

**Comment by slivne** [comment]
the https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/testReport/junit/resharding_test/history/ have been passing for the last 50 build closing this issue
