### ISSUE TITLE
sstableloader_compression_none_to_none_test: ConnectionException('Host has been marked down or removed',)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5149]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/testReport/sstable_generation_loading_test/TestSSTableGenerationAndLoading/sstableloader_compression_none_to_none_test/
Scylla version 3b9bf9d448b7561ad4f51896ea3b1de830db547e
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/sstable_generation_loading_test.py", line 154, in sstableloader_compression_none_to_none_test
    self.load_sstable_with_configuration(None, None)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/sstable_generation_loading_test.py", line 209, in load_sstable_with_configuration
    create_schema(session, pre_compression)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/sstable_generation_loading_test.py", line 203, in create_schema
    self.create_ks(session, "ks", rf=2)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 799, in create_ks
    session.execute(query % (name, "'class':'SimpleStrategy', 'replication_factor':%d" % rf))
  File "cassandra/cluster.py", line 2141, in cassandra.cluster.Session.execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
OperationTimedOut: errors={<Host: 127.0.80.2 datacenter1>: ConnectionException('Host has been marked down or removed',)}, last_host=127.0.80.1
```

[dtest.log](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/artifact/logs-release.2/dtest.log)
```
$ grep ' 25502 ' dtest.log
2019-10-03 11:23:19,377 25502   dtest                          DEBUG    | sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_testsstableloader_compression_none_to_none_test - cluster ccm directory: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-Vi9Uik
2019-10-03 11:23:19,378 25502   dtest                          DEBUG    | sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_testsstableloader_compression_none_to_none_test - Starting Scylla cluster from directory /jenkins/workspace/scylla-master/dtest-release/scylla-dtest/../scylla/build/release/
2019-10-03 11:23:19,386 25502   dtest                          DEBUG    | sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_testsstableloader_compression_none_to_none_test - Allocated cluster ID 80: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-Vi9Uik
2019-10-03 11:23:24,681 25502   dtest                          DEBUG    | sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_testsstableloader_compression_none_to_none_test - Testing sstableloader with pre_compression=None and post_compression=None
2019-10-03 11:24:01,739 25502   dtest                          DEBUG    | sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_testsstableloader_compression_none_to_none_test - creating keyspace and inserting
2019-10-03 11:24:01,741 25502   cassandra.cluster              WARNING  | Cluster.__init__ called with contact_points specified, but load-balancing policies are not specified in some ExecutionProfiles. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['127.0.80.1'], EPs without explicit LBPs = ('EXEC_PROFILE_DEFAULT',))
2019-10-03 11:24:11,836 25502   dtest                          DEBUG    | sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_testsstableloader_compression_none_to_none_test - Test failed
2019-10-03 11:24:11,838 25502   dtest                          DEBUG    | sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_testsstableloader_compression_none_to_none_test - removing ccm cluster test at: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-Vi9Uik
2019-10-03 11:24:19,628 25502   dtest                          DEBUG    | sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_testsstableloader_compression_none_to_none_test - Freeing cluster ID 80: link /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/80
```

[node1.log](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/artifact/logs-release.2/1570101851836_sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_test/node1.log)
```
INFO  2019-10-03 11:24:01,803 [shard 1] migration_manager - Create new Keyspace: KSMetaData{name=ks, strategyClass=org.apache.cassandra.locator.SimpleStrategy, strategyOptions={replication_factor=2}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x60100334bc80}
INFO  2019-10-03 11:24:06,508 [shard 0] migration_manager - Requesting schema pull from 127.0.80.2:0
INFO  2019-10-03 11:24:06,508 [shard 0] migration_manager - Pulling schema from 127.0.80.2:0
```

[node2.log](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/artifact/logs-release.2/1570101851836_sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_none_to_none_test/node2.log)
```
INFO  2019-10-03 11:24:06,481 [shard 1] schema_tables - Creating keyspace ks
INFO  2019-10-03 11:24:06,488 [shard 1] database - Schema version changed to e4599641-042e-301f-b383-7c09dbc0a8fb
```

**Comment by bhalevy** [comment]
Similar failures in:
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/testReport/sstable_generation_loading_test/TestSSTableGenerationAndLoading/sstableloader_compression_snappy_to_deflate_test/
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/testReport/sstable_generation_loading_test/TestSSTableGenerationAndLoading/sstableloader_compression_snappy_to_none_test/

**Comment by slivne** [comment]
the https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/268/testReport/junit/sstable_generation_loading_test/TestSSTableGenerationAndLoading/history/ have been passing for more then the last 50 builds - closing this
