### ISSUE TITLE
json_test.JsonFullRowInsertSelect.complex_schema_test: Doctest failed!

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5246]
Seen in [dtest-release/291/testReport/json_test/JsonFullRowInsertSelect/complex_schema_test](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/291/testReport/json_test/JsonFullRowInsertSelect/complex_schema_test/)
Scylla version 2a136ba1bc5f67ca5a45556350b071635d8bae84
```
Error Message
Doctest failed! Captured output:
**********************************************************************
Line 59, in complex_schema_test
Failed example:
    cqlsh_print("SELECT JSON * FROM complex_types")
Expected:
    <BLANKLINE>
     [json]
    --------------------------------------------------------------------------------------------------------------------------------------------------------------
     {"key1": "row1", "many_sinks": null, "mylist": null, "mymap": null, "myset": null, "mytodolists": null, "mytuple": null, "myudt": null, "named_sinks": null}
     {"key1": "row2", "many_sinks": null, "mylist": null, "mymap": null, "myset": null, "mytodolists": null, "mytuple": null, "myudt": null, "named_sinks": null}
    <BLANKLINE>
    (2 rows)
    <BLANKLINE>
Got:
    <BLANKLINE>
     [json]
    --------------------------------------------------------------------------------------------------------------------------------------------------------------
     {"key1": "row1", "many_sinks": null, "mylist": null, "mymap": null, "myset": null, "mytodolists": null, "mytuple": null, "myudt": null, "named_sinks": null}
       {"key1": "row2", "many_sinks": null, "mylist": null, "mymap": null, "myset": null, "mytodolists": null, "mytuple": null, "myudt": {}, "named_sinks": null}
    <BLANKLINE>
    (2 rows)
    <BLANKLINE>
**********************************************************************
Line 71, in complex_schema_test
Failed example:
    cqlsh_print('''
    SELECT * FROM complex_types
    ''')
Expected:
    <BLANKLINE>
     key1 | many_sinks | mylist | mymap | myset | mytodolists | mytuple | myudt | named_sinks
    ------+------------+--------+-------+-------+-------------+---------+-------+-------------
     row1 |       null |   null |  null |  null |        null |    null |  null |        null
     row2 |       null |   null |  null |  null |        null |    null |  null |        null
    <BLANKLINE>
    (2 rows)
    <BLANKLINE>
Got:
    <BLANKLINE>
     key1 | many_sinks | mylist | mymap | myset | mytodolists | mytuple | myudt | named_sinks
    ------+------------+--------+-------+-------+-------------+---------+-------+-------------
     row1 |       null |   null |  null |  null |        null |    null |  null |        null
     row2 |       null |   null |  null |  null |        null |    null |       |        null
    <BLANKLINE>
    (2 rows)
    <BLANKLINE>
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/json_test.py", line 1662, in complex_schema_test
    run_func_docstring(tester=self, test_func=self.complex_schema_test)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/json_test.py", line 192, in run_func_docstring
    raise RuntimeError("Doctest failed! Captured output:\n{}".format(test_output_capturer.content))
RuntimeError: Doctest failed! Captured output:
**********************************************************************
Line 59, in complex_schema_test
Failed example:
    cqlsh_print("SELECT JSON * FROM complex_types")
Expected:
    <BLANKLINE>
     [json]
    --------------------------------------------------------------------------------------------------------------------------------------------------------------
     {"key1": "row1", "many_sinks": null, "mylist": null, "mymap": null, "myset": null, "mytodolists": null, "mytuple": null, "myudt": null, "named_sinks": null}
     {"key1": "row2", "many_sinks": null, "mylist": null, "mymap": null, "myset": null, "mytodolists": null, "mytuple": null, "myudt": null, "named_sinks": null}
    <BLANKLINE>
    (2 rows)
    <BLANKLINE>
Got:
    <BLANKLINE>
     [json]
    --------------------------------------------------------------------------------------------------------------------------------------------------------------
     {"key1": "row1", "many_sinks": null, "mylist": null, "mymap": null, "myset": null, "mytodolists": null, "mytuple": null, "myudt": null, "named_sinks": null}
       {"key1": "row2", "many_sinks": null, "mylist": null, "mymap": null, "myset": null, "mytodolists": null, "mytuple": null, "myudt": {}, "named_sinks": null}
    <BLANKLINE>
    (2 rows)
    <BLANKLINE>
**********************************************************************
Line 71, in complex_schema_test
Failed example:
    cqlsh_print('''
    SELECT * FROM complex_types
    ''')
Expected:
    <BLANKLINE>
     key1 | many_sinks | mylist | mymap | myset | mytodolists | mytuple | myudt | named_sinks
    ------+------------+--------+-------+-------+-------------+---------+-------+-------------
     row1 |       null |   null |  null |  null |        null |    null |  null |        null
     row2 |       null |   null |  null |  null |        null |    null |  null |        null
    <BLANKLINE>
    (2 rows)
    <BLANKLINE>
Got:
    <BLANKLINE>
     key1 | many_sinks | mylist | mymap | myset | mytodolists | mytuple | myudt | named_sinks
    ------+------------+--------+-------+-------+-------------+---------+-------+-------------
     row1 |       null |   null |  null |  null |        null |    null |  null |        null
     row2 |       null |   null |  null |  null |        null |    null |       |        null
    <BLANKLINE>
    (2 rows)
    <BLANKLINE>

Standard Output
**********************************************************************
1 items had failures:
   2 of  18 in complex_schema_test
***Test Failed*** 2 failures.
```

**Comment by bhalevy** [comment]
@kbr- any chance this could be related to 49a7461345e5b365a026157379b9f967e83b6bf8 ?

**Comment by kbr-** [comment]
Possible. Will look into it
