### ISSUE TITLE
lightweight_transaction_test fails with experimental support disabled

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5247]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/293/testReport/cql_additional_tests/CQLAdditionalTests/lightweight_transaction_test/
Scylla version 49aa8ab8a0698c3ee939bceedebab0e2556beeb9
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_additional_tests.py", line 5479, in lightweight_transaction_test
    assert(e.message == "Not implemented: LWT")
AssertionError
```

Reproduced locally.
The actual exception is
```
Exception <Error from server: code=0000 [Server error] message="Paxos is currently disabled. Start Scylla with --experimental=on to enable.">
```

The test needs to run scylla with `--experimental=on`

**Comment by bhalevy** [comment]
Sorry, meant to open a bug against scylla-dtest.
See scylladb/scylla-dtest#1129
