### ISSUE TITLE
perftune.py seems to be broken on scylla-3.2.rc1-0.20191119

### ISSUE THREAD

**Issue by flucchese** [scylladb/scylla#5331]
I instantiated the scylla-3.2.rc1-0.20191119 AMI and started experimenting with perftune.py, but It can't find a dependency:

[centos@ip-10-0-0-211 /]$ cd /usr/lib/scylla/
[centos@ip-10-0-0-211 scylla]$ ./perftune.py --dry-run --tune net
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/perftune.py", line 1315, in <module>
    args.cpu_mask = run_hwloc_calc(['all'])
  File "/opt/scylladb/scripts/libexec/perftune.py", line 58, in run_hwloc_calc
    return run_read_only_command(['hwloc-calc'] + prog_args).rstrip()
  File "/opt/scylladb/scripts/libexec/perftune.py", line 46, in run_read_only_command
    return __run_one_command(prog_args, stderr=stderr, check=check)
  File "/opt/scylladb/scripts/libexec/perftune.py", line 30, in __run_one_command
    proc = subprocess.Popen(prog_args, stdout = subprocess.PIPE, stderr = stderr)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hwloc-calc': 'hwloc-calc'

The dependency is located in:

./opt/scylladb/bin/hwloc-calc
./opt/scylladb/libexec/hwloc-calc

**Comment by flucchese** [comment]
Updating the path seems to solve the problem:

$ export PATH=/opt/scylladb/bin:$PATH

**Comment by glommer** [comment]
Ah, good.

Indeed in this case this is not a bug. The relocated version of the script would set the path.
