### ISSUE TITLE
Stress tool error with tables not having non-primary keys

### ISSUE THREAD

**Issue by arunsandu666** [scylladb/scylla#534]
Hi,
I am trying to pass request_trace.yaml as an input to the stress-tool as below:
./cassandra-stress user profile=request_trace.yaml n=1000000 ops(likelyquery0=1,likelyquery1=2,insert=1) -node 10.32.100.16
the script is perfectly working fine for the other tables. But I get the below error for request_trace table. Please check the request_trace.yaml file for the script.

 ```
------------------------------------- request_trace.yaml---------------------------------------------------------
DML ### THIS IS UNDER CONSTRUCTION!!!
Keyspace Name

keyspace: autogeneratedtest
The CQL for creating a keyspace (optional if it already exists)

keyspace_definition: |
CREATE KEYSPACE autogeneratedtest WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
Table name

table: request_trace
The CQL for creating a table you wish to stress (optional if it already exists)

table_definition:
CREATE TABLE request_trace (
service_context_id text,
trace_statement text,
PRIMARY KEY (service_context_id, trace_statement)
)
Column Distribution Specifications

columnspec:

    name: service_context_id
    size: gaussian(10..20)
    population: gaussian(300..500)

    name: trace_statement
    size: gaussian(5..15)
    population: gaussian(800..1000)

Batch Ratio Distribution Specifications

insert:
partitions: fixed(1) # Our partition key is the domain so only insert one per batch

select: fixed(1)/1000 # We have 1000 posts per domain so 1/1000 will allow 1 post per batch

batchtype: UNLOGGED # Unlogged batches
A list of queries you wish to run against the schema

#
queries:
likelyquery0:
cql: SELECT * FROM request_trace WHERE service_context_id = ?
fields: samerow
likelyquery1:
cql: SELECT * FROM request_trace WHERE service_context_id = ? AND trace_statement = ?
fields: samerow
 ```
 ```
ERROR:
Warming up likelyquery0 with 50000 iterations...
Warming up likelyquery1 with 50000 iterations...
Warming up insert with 50000 iterations...
Generating batches with [1..1] partitions and [0..0] rows (of [1..1] total rows in the partitions)
Exception in thread "main" com.datastax.driver.core.exceptions.SyntaxError: line 1:28 no viable alternative at input 'WHERE' (UPDATE "request_trace" SET  [WHERE]...)
    at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:35)
    at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:271)
    at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:82)
    at org.apache.cassandra.stress.util.JavaDriverClient.prepare(JavaDriverClient.java:84)
    at org.apache.cassandra.stress.StressProfile.getInsert(StressProfile.java:396)
    at org.apache.cassandra.stress.settings.SettingsCommandUser$1.get(SettingsCommandUser.java:82)
    at org.apache.cassandra.stress.settings.SettingsCommandUser$1.get(SettingsCommandUser.java:78)
    at org.apache.cassandra.stress.operations.SampledOpDistributionFactory$1.get(SampledOpDistributionFactory.java:80)
    at org.apache.cassandra.stress.StressAction$Consumer.<init>(StressAction.java:269)
    at org.apache.cassandra.stress.StressAction.run(StressAction.java:204)
    at org.apache.cassandra.stress.StressAction.warmup(StressAction.java:105)
    at org.apache.cassandra.stress.StressAction.run(StressAction.java:61)
    at org.apache.cassandra.stress.Stress.main(Stress.java:114)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:28 no viable alternative at input 'WHERE' (UPDATE "request_trace" SET  [WHERE]...)
    at com.datastax.driver.core.Responses$Error.asException(Responses.java:123)
    at com.datastax.driver.core.SessionManager$1.apply(SessionManager.java:167)
    at com.datastax.driver.core.SessionManager$1.apply(SessionManager.java:142)
    at com.google.common.util.concurrent.Futures$1.apply(Futures.java:713)
    at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
 ```
This stress tool command throws error only when the table has single partition key as described above. In all the other cases where the table has non primary keys, am able to run the command and get the results.

**Comment by penberg** [comment]
@arunsandu666 The profile file you posted is corrupted. Can you please send a version that you used for testing?

The bug is in our CQL grammar that has some of the WHERE clause relation grammar subrules unimplemented.

**Comment by tzach** [comment]
@penberg  @arunsandu666 can we close this issue?

**Comment by noamha** [comment]
The yaml that was supplied is corrupted, I tried to rebuild it as best as I can:
```
### DML ###

# Keyspace Name
keyspace: autogeneratedtest

keyspace_definition: |
 CREATE KEYSPACE autogeneratedtest WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

table: request_trace

table_definition: |
 CREATE TABLE request_trace (
 service_context_id text,
 trace_statement text,
 PRIMARY KEY (service_context_id, trace_statement)
 )

columnspec:
 - name: service_context_id
   size: gaussian(10..20)
   population: gaussian(300..500)

 - name: trace_statement
   size: gaussian(5..15)
   population: gaussian(800..1000)

insert:
 partitions: fixed(1)
 select: fixed(1)/1000
 batchtype: UNLOGGED

queries:
 likelyquery0:
  cql: SELECT * FROM request_trace WHERE service_context_id = ?
  fields: samerow

 likelyquery1:
  cql: SELECT * FROM request_trace WHERE service_context_id = ? AND trace_statement = ?
  fields: samerow
```

And tried running it with Cassandra 3.0 and got the exact same error:
```
com.datastax.driver.core.exceptions.SyntaxError: line 1:28 no viable alternative at input 'WHERE' (UPDATE "request_trace" SET  [WHERE]...)
        at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:66)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:98)
        at org.apache.cassandra.stress.util.JavaDriverClient.prepare(JavaDriverClient.java:99)
        at org.apache.cassandra.stress.StressProfile.getInsert(StressProfile.java:419)
        at org.apache.cassandra.stress.settings.SettingsCommandUser$1.get(SettingsCommandUser.java:77)
        at org.apache.cassandra.stress.settings.SettingsCommandUser$1.get(SettingsCommandUser.java:73)
        at org.apache.cassandra.stress.operations.SampledOpDistributionFactory$1.get(SampledOpDistributionFactory.java:80)
        at org.apache.cassandra.stress.StressAction$Consumer.<init>(StressAction.java:269)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:204)
        at org.apache.cassandra.stress.StressAction.warmup(StressAction.java:105)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:61)
        at org.apache.cassandra.stress.Stress.main(Stress.java:117)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:28 no viable alternative at input 'WHERE' (UPDATE "request_trace" SET  [WHERE]...)
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:122)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:209)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:186)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
        at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1178)
        at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1172)
        at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:186)
        at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:44)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:754)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:576)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1008)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:931)
        at com.datastax.shaded.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at com.datastax.shaded.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at com.datastax.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at com.datastax.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
        at com.datastax.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)
```

When trying to insert manually to scylla using the keyspace and table definition everything worked.

We'll need normal copy of the yaml to examine.

**Comment by slivne** [comment]
closing the issue till additional information is provided

**Comment by arunsandu666** [comment]
@penberg 
Versions
Cassandra 2.1.11.969
CQL spec 3.2.1
Please find the actual yaml file attached.
[yaml file.zip](https://github.com/scylladb/scylla/files/169379/yaml.file.zip)
