### ISSUE TITLE
scylla_io_setup fail: ERROR:root:No data directories found. Please check the configuration and run scylla_io_setup again.

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5370]
*Installation details*
Scylla version (or git commit hash):  666.development-0.20191127.91b43f1f06.el7
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

This issue can be reproduced by manually execute scylla_io_setup .

- test job: https://jenkins.scylladb.com/job/scylla-master/job/centos-rpm-test/350/
- test log: https://jenkins.scylladb.com/job/scylla-master/job/centos-rpm-test/350/label=muninn/artifact/latest/job.log

```
| Running '/usr/lib/scylla/scylla_setup --nic eth0 --no-raid-setup'
| [stdout] WARN  2019-11-28 04:03:00,836 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 124 MB: is less than recommended: 10 GB
| [stdout] INFO  2019-11-28 04:03:00,836 [shard 0] iotune - /var/tmp/mnt passed sanity checks
| [stdout] This is a supported kernel version.
| [stdout] Loaded plugins: fastestmirror
| [stdout] Loading mirror speeds from cached hostfile 
| [stdout]  * base: centos.interhost.net.il
| [stdout]  * epel: mirror.nonstop.co.il
| [stdout]  * extras: centos.interhost.net.il
| [stdout]  * updates: centos.interhost.net.il
| [stdout] Package ntp-4.2.6p5-29.el7.centos.x86_64 already installed and latest version
| [stdout] Package ntpdate-4.2.6p5-29.el7.centos.x86_64 already installed and latest version
| [stdout] Nothing to do
| [stdout] 28 Nov 04:03:09 ntpdate[25216]: adjust time server 162.159.200.123 offset -0.000006 sec
| [stdout] kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e"
| [stderr] ERROR:root:No data directories found. Please check the configuration and run scylla_io_setup again.
| [stderr] 
| [stdout] You current Scylla release is 666.development the latest minor release is 3.1.1 go to http://www.scylladb.com for upgrade instructions
| [stdout] IO configuration setup failed.
| 
| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
| Traceback (most recent call last):
|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/centos-rpm-test/label/muninn/scylla-artifacts.py", line 764, in setUp
|     self.scylla_setup()
|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/centos-rpm-test/label/muninn/scylla-artifacts.py", line 750, in scylla_setup
|     installer.run()
|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/centos-rpm-test/label/muninn/scylla-artifacts.py", line 370, in run
|     process.run(setup_cmd, shell=True, verbose=True, timeout=600)
|   File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1031, in run
|     raise CmdError(cmd, sp.result)
| CmdError: Command '/usr/lib/scylla/scylla_setup --nic eth0 --no-raid-setup' failed (rc=1)
```

/CC @syuu1228 @xemul @bhalevy

**Comment by amoskong** [comment]
Fixed by: https://github.com/scylladb/scylla/pull/5368

**Comment by avikivity** [comment]
Aged out, no need to backport.
