### ISSUE TITLE
scylla-docker: scylla_dev_mode_setup failed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5398]
*Installation details*
Scylla version (or git commit hash): docker: scylladb/scylla-nightly:666.development-201911302334
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Failed job: https://jenkins.scylladb.com/job/scylla-master/job/docker-test/label=muninn/82/console

Reproduced locally:
```
# docker run --name node1 -d scylladb/scylla-nightly:666.development-201911302334

# docker ps -a
6bf5f4478541        scylladb/scylla-nightly:666.development-201911302334   "/docker-entrypoint.…"   37 minutes ago      Exited (0) 22 minutes ago                                                                    node1

# docker logs node1 -f
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 17, in <module>
    setup.io()
  File "/scyllasetup.py", line 45, in io
    data_dirs = cfg["data_file_directories"]
KeyError: 'data_file_directories'
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 17, in <module>
    setup.io()
  File "/scyllasetup.py", line 45, in io
    data_dirs = cfg["data_file_directories"]
KeyError: 'data_file_directories'
```

/CC @bentsi

**Comment by avikivity** [comment]
Related to --workdir, which isn't in any branch.
