### ISSUE TITLE
Master - debian and ubuntu installation fails

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#5401]
*Installation details*
Scylla version (or git commit hash): https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/unified/master/201911241926/scylladb-master/scylla.list
Jenkins job: https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/debian-deb-9-test/267/

```
stdout] Err:9 http://downloads.scylladb.com/deb/unstable/unified/master/201911241926 stable/main amd64 Packages
2019-11-24 19:52:11,563 process          L0420 DEBUG| [stdout]   404  Not Found
2019-11-24 19:52:11,727 process          L0420 DEBUG| [stdout] Ign:10 http://downloads.scylladb.com/deb/unstable/unified/master/201911241926 stable/main Translation-en_IL
2019-11-24 19:52:11,891 process          L0420 DEBUG| [stdout] Ign:11 http://downloads.scylladb.com/deb/unstable/unified/master/201911241926 stable/main Translation-en
2019-11-24 19:52:12,533 process          L0420 DEBUG| [stdout] Reading package lists...
2019-11-24 19:52:12,561 process          L0420 DEBUG| [stderr] W: The repository 'http://downloads.scylladb.com/deb/unstable/unified/master/201911241926 stable Release' does not have a Release file.
2019-11-24 19:52:12,561 process          L0420 DEBUG| [stderr] E: Failed to fetch http://downloads.scylladb.com/deb/unstable/unified/master/201911241926/dists/stable/main/binary-amd64/Packages  404  Not Found
2019-11-24 19:52:12,562 process          L0420 DEBUG| [stderr] E: Some index files failed to download. They have been ignored, or old ones used instead.
2019-11-24 19:52:12,563 stacktrace       L0036 ERROR| 
2019-11-24 19:52:12,563 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:436
2019-11-24 19:52:12,566 stacktrace       L0042 ERROR| Traceback (most recent call last):
2019-11-24 19:52:12,566 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/debian-deb-9-test/label/huginn/scylla-artifacts.py", line 764, in setUp
2019-11-24 19:52:12,566 stacktrace       L0042 ERROR|     self.scylla_setup()
2019-11-24 19:52:12,566 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/debian-deb-9-test/label/huginn/scylla-artifacts.py", line 750, in scylla_setup
2019-11-24 19:52:12,566 stacktrace       L0042 ERROR|     installer.run()
2019-11-24 19:52:12,566 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/debian-deb-9-test/label/huginn/scylla-artifacts.py", line 330, in run
2019-11-24 19:52:12,566 stacktrace       L0042 ERROR|     pkgs = self.env_setup()
2019-11-24 19:52:12,567 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/debian-deb-9-test/label/huginn/scylla-artifacts.py", line 527, in env_setup
2019-11-24 19:52:12,567 stacktrace       L0042 ERROR|     process.run('sudo apt-get update')
2019-11-24 19:52:12,567 stacktrace       L0042 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 1031, in run
2019-11-24 19:52:12,567 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
2019-11-24 19:52:12,567 stacktrace       L0042 ERROR| CmdError: Command 'sudo apt-get update' failed (rc=100)
2019-11-24 19:52:12,567 stacktrace       L0043 ERROR| 
```

**Comment by roydahan** [comment]
https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/ubuntu-deb-16.04-test/264/

https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/ubuntu-deb-18.04-test/254/

**Comment by slivne** [comment]
@penberg the date is fishy we do not use dates we use build ids someone broke either the repo file or the path

**Comment by penberg** [comment]
First things first, looks like the package _build_ is failing after Fedora 31 bump in `dbuild` in commit 1164ff5329:

```
02:57:36 Can't exec "diff": No such file or directory at /usr/share/perl5/vendor_perl/Dpkg/IPC.pm line 311.
```

Will send a patch to add `diffutils` to `dbuild`.

**Comment by penberg** [comment]
There were various release engineering and packaging problems in this area, but all the known ones are addressed and `debian-deb-9-test` is passing now.
