### ISSUE TITLE
load of 'int' from misaligned address

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#5413]
Reproduces with

UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1'  build/debug/tests/json_cql_query_test -t test_select_json_collections   -- -c2

backtrace and error:

```
cql3/type_json.cc:236:24: runtime error: load of misaligned address 0x60400027e767 for type 'const int', which requires 4 byte alignment
0x60400027e767: note: pointer points here
 00 00 00 04 00  00 00 02 00 00 00 01 21  00 00 00 04 00 00 00 03  00 00 00 02 64 65 00 00  02 01 00
             ^

Thread 2 "json_cql_query_" received signal SIGABRT, Aborted.
0x00007ffff5179e35 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5179e35 in raise () from /lib64/libc.so.6
#1  0x00007ffff5164895 in abort () from /lib64/libc.so.6
#2  0x00007ffff53401e2 in ?? () from /lib64/libubsan.so.1
#3  0x00007ffff534ad8c in ?? () from /lib64/libubsan.so.1
#4  0x00007ffff532be99 in ?? () from /lib64/libubsan.so.1
#5  0x00007ffff532fb26 in ?? () from /lib64/libubsan.so.1
#6  0x00007ffff532ff05 in __ubsan_handle_type_mismatch_v1 () from /lib64/libubsan.so.1
#7  0x000000000dcb4699 in compose_value<int> (t=..., bv=...) at cql3/type_json.cc:236
#8  0x000000000dcb2880 in (anonymous namespace)::to_json_string_visitor::operator()<int> (this=0x7fffe85e3720, t=...) at cql3/type_json.cc:361
#9  0x000000000dcb334f in visit<(anonymous namespace)::to_json_string_visitor> (t=..., f=...) at ./concrete_types.hh:217
#10 0x000000000dcadb33 in to_json_string (t=..., bv=<error reading variable: Cannot access memory at address 0xffffffffffffffe0>) at cql3/type_json.cc:417
#11 0x000000000dca7df0 in to_json_string_aux (t=..., bv=...) at cql3/type_json.cc:254
#12 0x000000000dcac55c in (anonymous namespace)::to_json_string_visitor::operator() (this=0x7fffe85e3b90, t=...) at cql3/type_json.cc:380
#13 0x000000000dcb3525 in visit<(anonymous namespace)::to_json_string_visitor> (t=..., f=...) at ./concrete_types.hh:223
#14 0x000000000dcadb33 in to_json_string (t=..., bv=<error reading variable: Cannot access memory at address 0xffffffffffffffe0>) at cql3/type_json.cc:417
#15 0x000000000de41e4e in to_json_string (t=..., b=...) at ./cql3/type_json.hh:33
#16 0x000000000de41f55 in to_json_string (t=..., b=...) at ./cql3/type_json.hh:37
#17 0x000000000de46a4e in cql3::functions::as_json_function::execute (this=0x6070001f7238, sf=..., parameters=...) at cql3/functions/as_json_function.hh:96
#18 0x000000000f5a71ad in cql3::selection::scalar_function_selector::get_output (this=0x60b000475668, sf=...) at cql3/selection/scalar_function_selector.hh:78
#19 0x000000000f5fa520 in cql3::selection::selection_with_processing::selectors_with_processing::get_output_row (this=0x606000077960, sf=...) at cql3/selection/selection.cc:207
#20 0x000000000f5e4c1b in cql3::selection::result_set_builder::flush_selectors (this=0x6110003cd268) at cql3/selection/selection.cc:351
#21 0x000000000f5e520a in cql3::selection::result_set_builder::process_current_row (this=0x6110003cd268, more_rows_coming=false) at cql3/selection/selection.cc:367
#22 0x000000000f5e53a3 in cql3::selection::result_set_builder::build (this=0x6110003cd268) at cql3/selection/selection.cc:380
#23 0x000000000e30c14f in cql3::statements::select_statement::<lambda(cql3::selection::result_set_builder&)>::<lambda()>::operator()(void) const (__closure=0x7fffe85e4f20) at cql3/statements/select_statement.cc:685
#24 0x000000000e35314e in seastar::futurize<seastar::shared_ptr<cql_transport::messages::result_message> >::apply<cql3::statements::select_statement::process_results(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, seastar::lw_shared_ptr<query::read_command>, const cql3::query_options&, gc_clock::time_point) const::<lambda(cql3::selection::result_set_builder&)> mutable::<lambda()> >(cql3::statements::select_statement::<lambda(cql3::selection::result_set_builder&)>::<lambda()> &&) (func=...) at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1467
#25 0x000000000e30d3be in seastar::futurize_apply<cql3::statements::select_statement::process_results(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, seastar::lw_shared_ptr<query::read_command>, const cql3::query_options&, gc_clock::time_point) const::<lambda(cql3::selection::result_set_builder&)> mutable::<lambda()> >(cql3::statements::select_statement::<lambda(cql3::selection::result_set_builder&)>::<lambda()> &&) (func=...)
    at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1619
#26 0x000000000e30d701 in cql3::selection::result_set_builder::with_thread_if_needed<cql3::statements::select_statement::process_results(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, seastar::lw_shared_ptr<query::read_command>, const cql3::query_options&, gc_clock::time_point) const::<lambda(cql3::selection::result_set_builder&)> mutable::<lambda()> >(cql3::statements::select_statement::<lambda(cql3::selection::result_set_builder&)>::<lambda()> &&) (
    this=0x6110003cd268, func=...) at ./cql3/selection/selection.hh:266
#27 0x000000000e30db90 in cql3::statements::select_statement::<lambda(cql3::selection::result_set_builder&)>::operator()(cql3::selection::result_set_builder &) (__closure=0x7fffe85e55c0, builder=...)
    at cql3/statements/select_statement.cc:697
#28 0x000000000e30e183 in seastar::do_with<cql3::selection::result_set_builder, cql3::statements::select_statement::process_results(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, seastar::lw_shared_ptr<query::read_command>, const cql3::query_options&, gc_clock::time_point) const::<lambda(cql3::selection::result_set_builder&)> >(cql3::selection::result_set_builder &&, cql3::statements::select_statement::<lambda(cql3::selection::result_set_builder&)> &&) (
    rvalue=..., f=...) at /home/espindola/scylla/scylla/seastar/include/seastar/core/do_with.hh:94
#29 0x000000000e31021d in cql3::statements::select_statement::process_results (this=0x6110003ccfd8, results=..., cmd=..., options=..., now=...) at cql3/statements/select_statement.cc:698
#30 0x000000000e30842b in cql3::statements::select_statement::<lambda(service::storage_proxy::coordinator_query_result)>::operator()(service::storage_proxy::coordinator_query_result) const (__closure=0x60f0000b0c40, qr=...)
    at cql3/statements/select_statement.cc:633
#31 0x000000000e36ae78 in seastar::apply_helper<cql3::statements::select_statement::execute(service::storage_proxy&, seastar::lw_shared_ptr<query::read_command>, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point) const::<lambda(service::storage_proxy::coordinator_query_result)>&, std::tuple<service::storage_proxy::coordinator_query_result&&>&&, std::integer_sequence<long unsigned int, 0> >::apply(cql3::statements::select_statement::<lambda(service::storage_proxy::coordinator_query_result)> &, std::tuple<service::storage_proxy::coordinator_query_result&&> &&) (func=..., args=...) at /home/espindola/scylla/scylla/seastar/include/seastar/core/apply.hh:36
#32 0x000000000e36b043 in seastar::apply<cql3::statements::select_statement::execute(service::storage_proxy&, seastar::lw_shared_ptr<query::read_command>, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point) const::<lambda(service::storage_proxy::coordinator_query_result)>&, service::storage_proxy::coordinator_query_result&&>(cql3::statements::select_statement::<lambda(service::storage_proxy::coordinator_query_result)> &, std::tuple<service::storage_proxy::coordinator_query_result&&> &&) (func=..., args=...) at /home/espindola/scylla/scylla/seastar/include/seastar/core/apply.hh:44
#33 0x000000000e36b1f9 in seastar::futurize<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > >::apply<cql3::statements::select_statement::execute(service::storage_proxy&, seastar::lw_shared_ptr<query::read_command>, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point) const::<lambda(service::storage_proxy::coordinator_query_result)>&, service::storage_proxy::coordinator_query_result&&>(cql3::statements::select_statement::<lambda(service::storage_proxy::coordinator_query_result)> &, std::tuple<service::storage_proxy::coordinator_query_result&&> &&) (func=..., args=...)
    at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1537
#34 0x000000000e3527e0 in seastar::future<service::storage_proxy::coordinator_query_result>::<lambda(service::storage_proxy::coordinator_query_result&&)>::operator()(service::storage_proxy::coordinator_query_result &&) (
    this=0x60f0000b0c40, args#0=...) at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1076
#35 0x000000000e381b35 in seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >(service::storage_proxy::coordinator_query_result&&)>::direct_vtable_for<seastar::future<T>::then(Func&&) [with Func = cql3::statements::select_statement::execute(service::storage_proxy&, seastar::lw_shared_ptr<query::read_command>, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point) const::<lambda(service::storage_proxy::coordinator_query_result)>; Result = seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >; T = {service::storage_proxy::coordinator_query_result}]::<lambda(service::storage_proxy::coordinator_query_result&&)> >::call(const seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >(service::storage_proxy::coordinator_query_result&&)> *, service::storage_proxy::coordinator_query_result &&) (func=0x60f0000b0c40, args#0=...) at /home/espindola/scylla/scylla/seastar/include/seastar/util/noncopyable_function.hh:104
#36 0x000000000e48e5cb in seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>::operator()(service::storage_proxy::coordinator_query_result&&) const (this=0x60f0000b0c40, args#0=...) at /home/espindola/scylla/scylla/seastar/include/seastar/util/noncopyable_function.hh:187
#37 0x000000000e4586c4 in seastar::apply_helper<seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>, std::tuple<service::storage_proxy::coordinator_query_result>&&, std::integer_sequence<unsigned long, 0ul> >::apply(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>&&, std::tuple<service::storage_proxy::coordinator_query_result>&&) (func=..., args=...) at /home/espindola/scylla/scylla/seastar/include/seastar/core/apply.hh:36
#38 0x000000000e458803 in seastar::apply<seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>, service::storage_proxy::coordinator_query_result>(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>&&, std::tuple<service::storage_proxy::coordinator_query_result>&&) (func=..., args=...) at /home/espindola/scylla/scylla/seastar/include/seastar/core/apply.hh:44
#39 0x000000000e4589b9 in seastar::futurize<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > >::apply<seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>, service::storage_proxy::coordinator_query_result>(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>&&, std::tuple<service::storage_proxy::coordinator_query_result>&&) (func=..., args=...) at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1537
#40 0x000000000e40a1ce in seastar::future<service::storage_proxy::coordinator_query_result>::then_impl<seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>, seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > >(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<service::storage_proxy::coordinator_query_result>&&)#1}::operator()(seastar::future_state<service::storage_proxy::coordinator_query_result>) (this=0x60f0000b0c28, state=...) at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1104
#41 0x000000000e4ef659 in seastar::continuation<seastar::future<service::storage_proxy::coordinator_query_result>::then_impl<seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>, seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > >(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (service::storage_proxy::coordinator_query_result&&)>&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<service::storage_proxy::coordinator_query_result>&&)#1}, service::storage_proxy::coordinator_query_result>::run_and_dispose() (this=0x60f0000b0bc0) at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:424
#42 0x00000000142759d9 in seastar::reactor::run_tasks (this=0x633000000800, tq=...) at /home/espindola/scylla/scylla/seastar/src/core/reactor.cc:2075
#43 0x0000000014279b42 in seastar::reactor::run_some_tasks (this=0x633000000800) at /home/espindola/scylla/scylla/seastar/src/core/reactor.cc:2499
#44 0x000000001427ef45 in seastar::reactor::run (this=0x633000000800) at /home/espindola/scylla/scylla/seastar/src/core/reactor.cc:2640
#45 0x0000000014d2cfbd in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=0x7fffe85e7340, ac=2, av=0x7fffffffd748, func=...) at /home/espindola/scylla/scylla/seastar/src/core/app-template.cc:199
#46 0x0000000014d07515 in seastar::testing::test_runner::<lambda()>::operator()(void) (__closure=0x603000018430) at /home/espindola/scylla/scylla/seastar/src/testing/test_runner.cc:67
#47 0x0000000014d1065b in std::_Function_handler<void(), seastar::testing::test_runner::start(int, char**)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/9/bits/std_function.h:300
#48 0x000000000d70b62b in std::function<void ()>::operator()() const (this=0x603000018460) at /usr/include/c++/9/bits/std_function.h:690
#49 0x0000000014581321 in seastar::posix_thread::start_routine (arg=0x603000018460) at /home/espindola/scylla/scylla/seastar/src/core/posix.cc:52
#50 0x00007ffff665d4c0 in start_thread () from /lib64/libpthread.so.0
#51 0x00007ffff523e163 in clone () from /lib64/libc.so.6
```

**Comment by bhalevy** [comment]
@espindola this was introduced in your commit bd3e725605b (then moved to this file in 786b1ec3641), right?

**Comment by espindola** [comment]
looking at this next.

**Comment by avikivity** [comment]
"cosmetic" bug, not backporting.
