### ISSUE TITLE
Use-after-move in make_multishard_streaming_reader() (aarch64)

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#5419]
aarch64 asan detected this:

```
=================================================================
==65398==ERROR: AddressSanitizer: stack-buffer-underflow on address 0xffffc1af2be0 at pc 0xffffa7bf3904 bp 0xffffc1af1a80 sp 0xffffc1af1af8
WRITE of size 1664 at 0xffffc1af2be0 thread T1
    #0 0xffffa7bf3900  (/lib64/libasan.so.5+0x63900)
    #1 0xffffa54fc368  (/lib64/libgcc_s.so.1+0xc368)
    #2 0xffffa54fda3c in _Unwind_RaiseException (/lib64/libgcc_s.so.1+0xda3c)
    #3 0xa321904 in _Unwind_RaiseException /home/avi/scylla/seastar/src/core/exception_hacks.cc:148
    #4 0xffffa5f8e4d4 in __cxa_throw (/lib64/libstdc++.so.6+0x9e4d4)
    #5 0xffffa61e6f90 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) (/lib64/libboost_unit_test_framework.so.1.69.0+0x26f90)
    #6 0xffffa61e7024 in boost::execution_monitor::execute(boost::function<int ()> const&) (/lib64/libboost_unit_test_framework.so.1.69.0+0x27024)
    #7 0xffffa61e793c in boost::execution_monitor::vexecute(boost::function<void ()> const&) (/lib64/libboost_unit_test_framework.so.1.69.0+0x2793c)
    #8 0xffffa620fa4c in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (/lib64/libboost_unit_test_framework.so.1.69.0+0x4fa4c)
    #9 0xffffa61f6f74  (/lib64/libboost_unit_test_framework.so.1.69.0+0x36f74)
    #10 0xffffa61f7128  (/lib64/libboost_unit_test_framework.so.1.69.0+0x37128)
    #11 0xffffa61eea20 in boost::unit_test::framework::run(unsigned long, bool) (/lib64/libboost_unit_test_framework.so.1.69.0+0x2ea20)
    #12 0xffffa620e7b8 in boost::unit_test::unit_test_main(bool (*)(), int, char**) (/lib64/libboost_unit_test_framework.so.1.69.0+0x4e7b8)
    #13 0xb0365ac in seastar::testing::entry_point(int, char**) /home/avi/scylla/seastar/src/testing/entry_point.cc:50
    #14 0x429288 in main /home/avi/scylla/seastar/include/seastar/testing/seastar_test.hh:56
    #15 0xffffa5394368 in __libc_start_main (/lib64/libc.so.6+0x24368)
    #16 0x429188  (/home/avi/scylla/build/debug/tests/mutation_reader_test_g+0x429188)

Address 0xffffc1af2be0 is located in stack of thread T0 at offset 0 in frame
    #0 0xb05f6cc in void std::condition_variable::wait<seastar::testing::exchanger<std::__exception_ptr::exception_ptr>::take()::{lambda()#1}>(std::unique_lock<std::mutex>&, seastar::testing::exchanger<std::__exception_ptr::exception_ptr>::take()::{lambda()#1}) /usr/include/c++/9/condition_variable:98

  This frame has 1 object(s):
    [32, 40) '__p' (line 98) <== Memory access at offset 0 partially underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow (/lib64/libasan.so.5+0x63900) 
Shadow bytes around the buggy address:
  0x200ff835e520: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x200ff835e530: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x200ff835e540: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x200ff835e550: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x200ff835e560: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x200ff835e570: 00 00 00 00 00 00 00 00 00 00 00 00[f1]f1 f1 f1
  0x200ff835e580: 00 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x200ff835e590: f1 f1 f1 f1 00 f2 f2 f2 00 00 f2 f2 00 00 00 00
  0x200ff835e5a0: 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00
  0x200ff835e5b0: 00 f2 00 00 00 00 00 00 00 00 f8 f8 f2 f2 f2 f2
  0x200ff835e5c0: f8 f8 f8 f8 f8 f2 f2 f2 f2 f2 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
Thread T1 created by T0 here:
    #0 0xffffa7bcc9ac in __interceptor_pthread_create (/lib64/libasan.so.5+0x3c9ac)
    #1 0xafee9e4 in seastar::posix_thread::posix_thread(seastar::posix_thread::attr, std::function<void ()>) /home/avi/scylla/seastar/src/core/posix.cc:83
    #2 0xafee2a4 in seastar::posix_thread::posix_thread(std::function<void ()>) /home/avi/scylla/seastar/src/core/posix.cc:57
    #3 0xb0433b0 in make_unique<seastar::posix_thread, seastar::testing::test_runner::start(int, char**)::<lambda()> > /usr/include/c++/9/bits/unique_ptr.h:849
    #4 0xb03f760 in seastar::testing::test_runner::start(int, char**) /home/avi/scylla/seastar/src/testing/test_runner.cc:63
    #5 0xb036468 in init_unit_test_suite /home/avi/scylla/seastar/src/testing/entry_point.cc:45
    #6 0xffffa61e9a58  (/lib64/libboost_unit_test_framework.so.1.69.0+0x29a58)
    #7 0xffffa61e8948  (/lib64/libboost_unit_test_framework.so.1.69.0+0x28948)
    #8 0xffffa61e6f30 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) (/lib64/libboost_unit_test_framework.so.1.69.0+0x26f30)
    #9 0xffffa61e7024 in boost::execution_monitor::execute(boost::function<int ()> const&) (/lib64/libboost_unit_test_framework.so.1.69.0+0x27024)
    #10 0xffffa61e793c in boost::execution_monitor::vexecute(boost::function<void ()> const&) (/lib64/libboost_unit_test_framework.so.1.69.0+0x2793c)
    #11 0xffffa61ed6c0 in boost::unit_test::framework::init(bool (*)(), int, char**) (/lib64/libboost_unit_test_framework.so.1.69.0+0x2d6c0)
    #12 0xffffa620e610 in boost::unit_test::unit_test_main(bool (*)(), int, char**) (/lib64/libboost_unit_test_framework.so.1.69.0+0x4e610)
    #13 0xb0365ac in seastar::testing::entry_point(int, char**) /home/avi/scylla/seastar/src/testing/entry_point.cc:50
    #14 0x429288 in main /home/avi/scylla/seastar/include/seastar/testing/seastar_test.hh:56
    #15 0xffffa5394368 in __libc_start_main (/lib64/libc.so.6+0x24368)
    #16 0x429188  (/home/avi/scylla/build/debug/tests/mutation_reader_test_g+0x429188)

==65398==ABORTING
```

Doesn't happen on x86_64.

**Comment by avikivity** [comment]
Dubious since x86 isn't affected, but backported to 3.1 and 3.2.
