### ISSUE TITLE
Multidc fails on consistency all with 3 DCs each with 3 nodes consistency_test.py:TestAvailability.test_network_topology_strategy test_network_topology_strategy 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#543]
The previous issue #535 was resolved

yet 

with commit d622fe867ee81bb0e65077f0b8802dd3e4e13603
Author: Asias He <asias@scylladb.com>
Date:   Mon Nov 9 18:55:40 2015 +0800

    gossip: Pass const ref if possible
    
    It is clear that we will not change the parameter.

the test fails at a different point.

export CASSANDRA_DIR=~/scylla/build/debug

rm -Rf ~/.dtest/* ; pkill -9 scylla; KEEP_TEST_DIR=true nosetests -v -s consistency_test.py:TestAvailability.test_network_topology_strategy
test_network_topology_strategy (consistency_test.TestAvailability) ... ERROR

```
======================================================================
ERROR: test_network_topology_strategy (consistency_test.TestAvailability)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/consistency_test.py", line 313, in test_network_topology_strategy
    self._test_network_topology_strategy(combinations)
  File "/home/shlomi/urchin-dtest/consistency_test.py", line 223, in _test_network_topology_strategy
    self._test_insert_query_from_node(session, i, rf_factors, nodes_alive, *combination)
  File "/home/shlomi/urchin-dtest/consistency_test.py", line 243, in _test_insert_query_from_node
    self.insert_user(session, n, age, write_cl, serial_cl)
  File "/home/shlomi/urchin-dtest/consistency_test.py", line 126, in insert_user
    session.execute(statement)
  File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:27334)
    result = future.result()
  File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:65206)
    raise self._final_exception
WriteTimeout: code=1100 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out - received only 8 responses." info={'received_responses': 8, 'required_responses': 9, 'consistency': 'ALL'}
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-tveeS8
cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: {UUID('6a39e42c-83c7-3d84-a12a-5598dd916db6'): ['127.0.0.6'], UUID('722a9c81-eeee-3c5d-ba48-50a580cdfe9f'): ['127.0.0.9', '127.0.0.8', '127.0.0.7', '127.0.0.5', '127.0.0.4', '127.0.0.3', '127.0.0.2', '127.0.0.1']}
cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: {UUID('6a39e42c-83c7-3d84-a12a-5598dd916db6'): ['127.0.0.6'], UUID('722a9c81-eeee-3c5d-ba48-50a580cdfe9f'): ['127.0.0.9', '127.0.0.8', '127.0.0.7', '127.0.0.5', '127.0.0.4', '127.0.0.3', '127.0.0.2', '127.0.0.1']}
dtest: DEBUG: Testing dc 0 with rf 3 and [3, 3, 3] nodes alive
dtest: DEBUG: Testing node 0 in dc 0 with [3, 3, 3] nodes alive
cassandra.cluster: WARNING: [control connection] Error connecting to 127.0.0.1:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 2114, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:37551)
    return self._try_connect(host)
  File "cassandra/cluster.py", line 2164, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:38737)
    raise
  File "cassandra/cluster.py", line 2157, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:38597)
    shared_results = connection.wait_for_responses(
  File "cassandra/connection.py", line 478, in cassandra.connection.Connection.wait_for_responses (cassandra/connection.c:10195)
    raise
  File "cassandra/connection.py", line 476, in cassandra.connection.Connection.wait_for_responses (cassandra/connection.c:10137)
    return waiter.deliver(timeout)
  File "cassandra/connection.py", line 878, in cassandra.connection.ResponseWaiter.deliver (cassandra/connection.c:20137)
    raise OperationTimedOut()
OperationTimedOut: errors=None, last_host=None
cassandra.cluster: ERROR: Control connection failed to connect, shutting down Cluster:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 840, in cassandra.cluster.Cluster.connect (cassandra/cluster.c:11146)
    self.control_connection.connect()
  File "cassandra/cluster.py", line 2088, in cassandra.cluster.ControlConnection.connect (cassandra/cluster.c:36955)
    self._set_new_connection(self._reconnect_internal())
  File "cassandra/cluster.py", line 2123, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:37811)
    raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1': OperationTimedOut('errors=None, last_host=None',)})
dtest: DEBUG: Connected to ['127.0.0.1'] for ALL/ALL/-
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 117.483s

FAILED (errors=1)
```

this test passed in the past

**Comment by slivne** [comment]
passes on 6ac54a27dca18e500ca591c936263c18a046e37c
