### ISSUE TITLE
oel7.7: scylla_ntp_setup/scylla_util.py: ValueError: invalid literal for int() with base 10: '7.7'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5433]
*Installation details*
Scylla version (or git commit hash):  scylla-666.development-0.20191207.7b37a700e11.el7.x86_64.rpm
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): `OEL 7.7`

This issue was introduced by commit c9d860678658754937308c08d913bce5e0c37a77  /CC @syuu1228 

Artifact test job: https://jenkins.scylladb.com/job/scylla-master/job/oel7.4-rpm-test/label=muninn/140/artifact/latest/job.log

```
2019-12-07 11:38:13,099 process          L0333 INFO | Running '/usr/lib/scylla/scylla_setup --nic ens2 --disks /dev/sdb'
2019-12-07 11:38:15,998 process          L0420 DEBUG| [stdout] WARN  2019-12-07 11:38:15,988 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 124 MB: is less than recommended: 10 GB
2019-12-07 11:38:15,998 process          L0420 DEBUG| [stdout] INFO  2019-12-07 11:38:15,988 [shard 0] iotune - /var/tmp/mnt passed sanity checks
2019-12-07 11:38:16,074 process          L0420 DEBUG| [stdout] This is a supported kernel version.
2019-12-07 11:38:16,156 process          L0420 DEBUG| [stderr] Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /usr/lib/systemd/system/scylla-server.service.
2019-12-07 11:38:17,647 process          L0420 DEBUG| [stderr] Traceback (most recent call last):
2019-12-07 11:38:17,647 process          L0420 DEBUG| [stderr]   File "/opt/scylladb/scripts/libexec/scylla_ntp_setup", line 81, in <module>
2019-12-07 11:38:17,647 process          L0420 DEBUG| [stderr]     if redhat_version() >= 8:
2019-12-07 11:38:17,647 process          L0420 DEBUG| [stderr]   File "/opt/scylladb/scripts/scylla_util.py", line 370, in redhat_version
2019-12-07 11:38:17,647 process          L0420 DEBUG| [stderr]     return int(os_release['VERSION_ID'])
2019-12-07 11:38:17,647 process          L0420 DEBUG| [stderr] ValueError: invalid literal for int() with base 10: '7.7'
2019-12-07 11:38:17,656 process          L0420 DEBUG| [stdout] You current Scylla release is 666.development the latest minor release is 3.1.2 go to http://www.scylladb.com for upgrade instructions
2019-12-07 11:38:17,657 process          L0420 DEBUG| [stdout] NTP setup failed.
2019-12-07 11:38:17,667 stacktrace       L0036 ERROR| 
2019-12-07 11:38:17,667 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
2019-12-07 11:38:17,670 stacktrace       L0042 ERROR| Traceback (most recent call last):
2019-12-07 11:38:17,670 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/oel7.4-rpm-test/label/muninn/scylla-artifacts.py", line 764, in setUp
2019-12-07 11:38:17,670 stacktrace       L0042 ERROR|     self.scylla_setup()
2019-12-07 11:38:17,671 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/oel7.4-rpm-test/label/muninn/scylla-artifacts.py", line 750, in scylla_setup
2019-12-07 11:38:17,671 stacktrace       L0042 ERROR|     installer.run()
2019-12-07 11:38:17,671 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master/oel7.4-rpm-test/label/muninn/scylla-artifacts.py", line 370, in run
2019-12-07 11:38:17,671 stacktrace       L0042 ERROR|     process.run(setup_cmd, shell=True, verbose=True, timeout=600)
2019-12-07 11:38:17,671 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1031, in run
2019-12-07 11:38:17,671 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
2019-12-07 11:38:17,671 stacktrace       L0042 ERROR| CmdError: Command '/usr/lib/scylla/scylla_setup --nic ens2 --disks /dev/sdb' failed (rc=1)
```

**Comment by amoskong** [comment]
Quote from https://www.linux.org/docs/man5/os-release.html:

```
       VERSION_ID=
           A lower-case string (mostly numeric, no spaces or other characters outside of 0-9, a-z, ".", "_" and "-")
           identifying the operating system version, excluding any OS name information or release code name, and
           suitable for processing by scripts or usage in generated filenames. This field is optional. Example:
           "VERSION_ID=17" or "VERSION_ID=11.04".
```


Real example of /etc/of-release on OEL 7
```
[root@localhost ~]# cat /etc/os-release 
NAME="Oracle Linux Server"
VERSION="7.7"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Oracle Linux Server 7.7"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:7:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.7
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.7
```

Example of centos7
```
[amos@amos-centos7 ~]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
