### ISSUE TITLE
netstats_test: nodetool: Scylla API server HTTP GET to URL '/stream_manager/' failed: _Map_base::at

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5437]
Seen in [dtest-release/339/testReport/nodetool_additional_test/TestNodetool/netstats_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/339/testReport/nodetool_additional_test/TestNodetool/netstats_test/)
Scylla version 7b37a700e11ae298940a2015815e51e1434ede6f
Scylla-dtest version scylladb/scylla-dtest@65a423fc6e6777bbe650ad2218af3c3eb0e8135d
```
Error Message
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/7b37a700e11ae298940a2015815e51e1434ede6f/scylla-java-tools/bin/nodetool -h 127.0.90.1 -p 7190 netstats' failed; exit status: 1; stdout: Mode: NORMAL
nodetool: Scylla API server HTTP GET to URL '/stream_manager/' failed: _Map_base::at
See 'nodetool help' or 'nodetool help <command>'.
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1160, in netstats_test
    stats = self.netstats(node)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1071, in netstats
    out = node.nodetool('netstats', True)[0]
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 724, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
NodetoolError: Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/7b37a700e11ae298940a2015815e51e1434ede6f/scylla-java-tools/bin/nodetool -h 127.0.90.1 -p 7190 netstats' failed; exit status: 1; stdout: Mode: NORMAL
nodetool: Scylla API server HTTP GET to URL '/stream_manager/' failed: _Map_base::at
See 'nodetool help' or 'nodetool help <command>'.
```

In the nodes logs, e.g. https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/339/artifact/logs-release.2/1575722755440_nodetool_additional_test.TestNodetool.netstats_test/node1.log there are the following warnings:
```
INFO  2019-12-07 12:45:54,390 [shard 0] stream_session - [Stream #81e76f61-18ef-11ea-9fdf-000000000000] Executing streaming plan for Bootstrap-system_auth-index-0 with peers=127.0.90.3, slave
INFO  2019-12-07 12:45:54,391 [shard 0] stream_session - [Stream #81e76f61-18ef-11ea-9fdf-000000000000] Skip sending ks=system_auth, cf=role_members, reader contains no data, with new rpc streaming
INFO  2019-12-07 12:45:54,391 [shard 1] stream_session - [Stream #81e76f61-18ef-11ea-9fdf-000000000000] Skip sending ks=system_auth, cf=role_members, reader contains no data, with new rpc streaming
INFO  2019-12-07 12:45:54,391 [shard 0] stream_session - [Stream #81e76f61-18ef-11ea-9fdf-000000000000] Skip sending ks=system_auth, cf=roles, reader contains no data, with new rpc streaming
INFO  2019-12-07 12:45:54,391 [shard 1] stream_session - [Stream #81e76f61-18ef-11ea-9fdf-000000000000] Skip sending ks=system_auth, cf=roles, reader contains no data, with new rpc streaming
INFO  2019-12-07 12:45:54,392 [shard 0] stream_session - [Stream #81e7bd80-18ef-11ea-9fdf-000000000000] Executing streaming plan for Bootstrap-system_auth-index-1 with peers=127.0.90.3, slave
WARN  2019-12-07 12:45:54,392 [shard 0] stream_session - [Stream #81e76f61-18ef-11ea-9fdf-000000000000] Fail to get progess on all shards: std::out_of_range (_Map_base::at)
```

Besides the nodetool error, it seems like:
1. These log messages should be errors rather than warnings.
2. The need to be more informative about what was out of range.
3. There is a typo in the message: s/progess/progress/

**Comment by gleb-cloudius** [comment]
@asias should look at it

**Comment by asias** [comment]
I unassigned gleb and assigned myself.

**Comment by asias** [comment]
Patch is sent: https://github.com/scylladb/scylla/pull/5483
