### ISSUE TITLE
cluster_cleanup_test is flaky: fails with Unable to complete the operation against any hosts

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5439]
Seen 50% of the times since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/331/testReport/cleanup_test/TestCleanup/cluster_cleanup_test (until [339](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/339/testReport/cleanup_test/TestCleanup/cluster_cleanup_test/)
```
Error Message
('Unable to complete the operation against any hosts', {})
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cleanup_test.py", line 41, in cluster_cleanup_test
    rows = session.execute("select count(*) from ks.cf;");
  File "cassandra/cluster.py", line 2141, in cassandra.cluster.Session.execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
NoHostAvailable: ('Unable to complete the operation against any hosts', {})
```

This may be a bug in the test, please open a corresponding issue on scylla-dtest if so.

**Comment by slivne** [comment]
dtest bug ... submitted a patch

**Comment by slivne** [comment]
Passing for the last 100 runs ... the fix works closing
