### ISSUE TITLE
LWT: incorrect number of required participants for queries executed with cl=LOCAL_SERIAL in multi-dc setup

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylla#5477]
*Installation details*
Scylla version (or git commit hash): master

The following tests are consistently failing in scylla-dtest (master), when uncommenting combinations involving `LOCAL_SERIAL` consistency level:

```
consistency_test.py:TestAvailability.test_network_topology_strategy
consistency_test.py:TestAccuracy.test_network_topology_strategy_users
```

These are the affected code fragments, which need to be uncommented in order to exhibit erroneous behavior: https://github.com/scylladb/scylla-dtest/blob/2e3fce05b190aa7bfc5d371403e73ec3c7948902/consistency_test.py#L380 ,  https://github.com/scylladb/scylla-dtest/blob/2e3fce05b190aa7bfc5d371403e73ec3c7948902/consistency_test.py#L655 .

Output of the first dtest:
```
$ TRACE=true CASSANDRA_DIR=${HOME}/work/scylla/build/dev python2 /usr/bin/nosetests --process-timeout=7200 -v -s consistency_test.py:TestAvailability.test_network_topology_strategy
test_network_topology_strategy (consistency_test.TestAvailability) ... ERROR

======================================================================
ERROR: test_network_topology_strategy (consistency_test.TestAvailability)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pa.solodovnikov/work/my-dtest/consistency_test.py", line 388, in test_network_topology_strategy
    self._test_network_topology_strategy(combinations)
  File "/home/pa.solodovnikov/work/my-dtest/consistency_test.py", line 274, in _test_network_topology_strategy
    session, i, rf_factors, nodes_alive, *combination)
  File "/home/pa.solodovnikov/work/my-dtest/consistency_test.py", line 294, in _test_insert_query_from_node
    self.insert_user(session, n, age, write_cl, serial_cl)
  File "/home/pa.solodovnikov/work/my-dtest/consistency_test.py", line 158, in insert_user
    session.execute(statement)
  File "cassandra/cluster.py", line 2345, in cassandra.cluster.Session.execute
    timeout, execution_profile, paging_state, host).result()
  File "cassandra/cluster.py", line 4304, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl LOCAL_SERIAL. Requires 5, alive 3" info={'required_replicas': 5, 'alive_replicas': 3, 'consistency': 'LOCAL_SERIAL'}
-------------------- >> begin captured logging << --------------------
dtest: DEBUG:  - going to run tests sequentially
dtest: DEBUG:  - using the SingleClusterIdAllocator
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - cluster ccm directory: /home/pa.solodovnikov/.dtest/dtest-SLjjB8
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Starting Scylla cluster from directory /home/pa.solodovnikov/work/scylla/build/dev
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Testing dc 0 with rf 3 and [3, 3, 3] nodes alive
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Testing node 0 in dc 0 with [3, 3, 3] nodes alive
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for ALL/ALL/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for QUORUM/QUORUM/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for LOCAL_QUORUM/LOCAL_QUORUM/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - required_nodes equal to 2
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - required_nodes equal to 2
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for EACH_QUORUM/LOCAL_QUORUM/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - required_nodes equal to 2
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for ONE/ONE/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for ONE/ALL/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for ALL/ONE/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for QUORUM/TWO/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for QUORUM/THREE/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for TWO/TWO/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for THREE/ONE/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for ANY/ONE/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for LOCAL_ONE/LOCAL_ONE/-
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - required_nodes equal to 1
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - required_nodes equal to 1
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for QUORUM/SERIAL/SERIAL
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Connected to ['127.0.0.1'] for LOCAL_QUORUM/LOCAL_SERIAL/LOCAL_SERIAL
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - required_nodes equal to 2
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Retrying request after UE. Attempt #0
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Retrying request after UE. Attempt #1
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Retrying request after UE. Attempt #2
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Retrying request after UE. Attempt #3
dtest: DEBUG: consistency_test.TestAvailability.test_network_topology_strategytest_network_topology_strategy - Retrying request after UE. Attempt #4
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 101.230s

FAILED (errors=1)
```

And this is what can be found in the node logs:
```
TRACE 2019-12-13 23:09:02,449 [shard 0] query_processor - process: "INSERT INTO users (userid, firstname, lastname, age) VALUES (0, 'first0', 'last0', 30) IF NOT EXISTS"
[Backtrace #0]
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x1a6436d: seastar::current_backtrace() у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x18eb16a: seastar::log_exception_trace() у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x18eb2c1: _Unwind_RaiseException у ??:?
{/lib64/libstdc++.so.6} 0xaab1b: __cxa_throw у ??:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0xb8ba6e: service::storage_proxy::get_paxos_participants(seastar::basic_sstring<char, unsigned int, 15u, true> const&, dht::token const&, db::consistency_level) у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0xbefb4a: seastar::shared_ptr<service::paxos_response_handler> seastar::shared_ptr_make_helper<service::paxos_response_handler, true>::make<seastar::shared_ptr<service::storage_proxy>, tracing::trace_state_ptr&, service_permit&, dht::decorated_key, seastar::lw_shared_ptr<schema const>&, seastar::lw_shared_ptr<query::read_command>&, db::consistency_level&, db::consistency_level&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >&>(seastar::shared_ptr<service::storage_proxy>&&, tracing::trace_state_ptr&, service_permit&, dht::decorated_key&&, seastar::lw_shared_ptr<schema const>&, seastar::lw_shared_ptr<query::read_command>&, db::consistency_level&, db::consistency_level&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >&) у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0xb8d53c: service::storage_proxy::cas(seastar::lw_shared_ptr<schema const>, seastar::shared_ptr<service::cas_request>, seastar::lw_shared_ptr<query::read_command>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, service::storage_proxy::coordinator_query_options, db::consistency_level, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x9b3ff6: cql3::statements::modification_statement::execute_with_condition(service::storage_proxy&, service::query_state&, cql3::query_options const&) const у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x9b52d2: cql3::statements::modification_statement::do_execute(service::storage_proxy&, service::query_state&, cql3::query_options const&) const у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x9b7d96: seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::modification_statement const*, service::storage_proxy&, service::query_state&, cql3::query_options const&)>::direct_vtable_for<std::_Mem_fn<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::modification_statement::*)(service::storage_proxy&, service::query_state&, cql3::query_options const&) const> >::call(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::modification_statement const*, service::storage_proxy&, service::query_state&, cql3::query_options const&)> const*, cql3::statements::modification_statement const*, service::storage_proxy&, service::query_state&, cql3::query_options const&) у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x9b7da8: seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::modification_statement const*, service::storage_proxy&, service::query_state&, cql3::query_options const&)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >, cql3::statements::modification_statement const*, service::storage_proxy&, service::query_state&, cql3::query_options const&>::make_stage_for_group(seastar::scheduling_group)::{lambda(cql3::statements::modification_statement const*, service::storage_proxy&, service::query_state&, cql3::query_options const&)#1}>::call(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::modification_statement const*, service::storage_proxy&, service::query_state&, cql3::query_options const&)> const*, cql3::statements::modification_statement const*, service::storage_proxy&, service::query_state&, cql3::query_options const&) у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x9ba8cf: seastar::concrete_execution_stage<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >, cql3::statements::modification_statement const*, service::storage_proxy&, service::query_state&, cql3::query_options const&>::do_flush() у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x18eb562: seastar::lambda_task<seastar::execution_stage::flush()::{lambda()#1}>::run_and_dispose() у execution_stage.cc:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x1919611: seastar::reactor::run_tasks(seastar::reactor::task_queue&) у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x191ff9f: seastar::reactor::run_some_tasks() у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x19465dd: seastar::reactor::run() у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x18e96ac: seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x18e9e38: seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) у crtstuff.c:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x43f660: main у crtstuff.c:?
{/lib64/libc.so.6} 0x271a2: __libc_start_main у ??:?
{/home/pa.solodovnikov/work/scylla/build/dev/scylla} 0x4254fd: _start у ??:?
```

`storage_proxy::get_paxos_participants` calculates required participants count as follows:
```c++
    size_t required_participants = db::quorum_for(ks) + pending_endpoints.size();
```
For `cl=SERIAL` the call to `db::quorum_for(ks)` gets translated to 5 (as in the example above), i.e. the regular quorum of 9 nodes. But for `cl=LOCAL_SERIAL` it should be the nodes count for `LOCAL_QUORUM` instead, which equals to 2.

**Comment by ManManson** [comment]
Fixed by https://github.com/scylladb/scylla/commit/c451f6d82ae3d9b466fa332b419d379382e00b3c.
