### ISSUE TITLE
scylla_setup / scylla_sysconfig_setup failed in setting clocksource

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5478]
*Installation details*
Scylla version (or git commit hash): master  27b8b6fe9d0be43f46cbd65682b6245da32c9e05
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

commit 4333b37f9e1087f7f0622a71d44ffeafbf7f6b2a introduced this issue.
- scylla_setup: Support for enforcing optimal Linux clocksource setting (#5379)

###  ERROR 1 in scylla_setup:

```
    scylla_setup error:
    
    | Do you want to enforce the use of fastest available Linux clocksource?
    | Yes - enforce TSC. No - keep current configuration.
    | [YES/no]
    | Traceback (most recent call last):
    |   File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 788, in get
    |     value = d[option]
    |   File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 916, in __getitem__
    |     return self.__missing__(key)            # support subclasses that define __missing__
    |   File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 908, in __missing__
    |     raise KeyError(key)
    | KeyError: 'SET_CLOCKSOURCE'
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 45, in <module>
    |     set_clocksource = str2bool(cfg.get('SET_CLOCKSOURCE'))
    |   File "/opt/scylladb/scripts/scylla_util.py", line 664, in get
    |     return self._cfg.get('global', key).strip('"')
    |   File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 791, in get
    |     raise NoOptionError(option, section)
    | configparser.NoOptionError: No option 'SET_CLOCKSOURCE' in section: 'global'
    | Performance Tuning setup failed. Press any key to continue...
```

### ERROR 2 in upgrade test:

```
    In upgrade test from 3.1 to master, we won't rerun scylla_setup. Scylla-server
    failed to start in scylla_prepare stage. This patch fixed the issue.
    
    sudo: COMMAND=/bin/systemctl start scylla-server.service
    systemd: Starting Scylla Server...
    scylla_prepare: Traceback (most recent call last):
    scylla_prepare: File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 788, in get
    scylla_prepare: value = d[option]
    scylla_prepare: File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 916, in __getitem__
    scylla_prepare: return self.__missing__(key)            # support subclasses that define __missing__
    scylla_prepare: File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 908, in __missing__
    scylla_prepare: raise KeyError(key)
    scylla_prepare: KeyError: 'SET_CLOCKSOURCE'
    scylla_prepare: During handling of the above exception, another exception occurred:
    scylla_prepare: Traceback (most recent call last):
    scylla_prepare: File "/opt/scylladb/scripts/libexec/scylla_prepare", line 77, in <module>
    scylla_prepare: if create_perftune_conf(cfg):
    scylla_prepare: File "/opt/scylladb/scripts/scylla_util.py", line 556, in create_perftune_conf
    scylla_prepare: if cfg.get('SET_CLOCKSOURCE') == 'yes':
    scylla_prepare: File "/opt/scylladb/scripts/scylla_util.py", line 664, in get
    scylla_prepare: return self._cfg.get('global', key).strip('"')
    scylla_prepare: File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 791, in get
    scylla_prepare: raise NoOptionError(option, section)
    scylla_prepare: configparser.NoOptionError: No option 'SET_CLOCKSOURCE' in section: 'global'
    systemd: scylla-server.service: control process exited, code=exited status=1
```

/CC @flucchese

**Comment by amoskong** [comment]
The patch problem patch had been reverted, let's close this issue

**Comment by avikivity** [comment]
Aged out, no need to backport.
