### ISSUE TITLE
lightweight_transaction_test error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5479]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1389/testReport/cql_additional_tests/CQLAdditionalTests/lightweight_transaction_test
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/cql_additional_tests.py", line 5499, in lightweight_transaction_test
    session.execute(c)
  File "cassandra/cluster.py", line 2141, in cassandra.cluster.Session.execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
error: unpack requires a string argument of length 4
```
Scylla version 9ec98324edb29596be9009cf54129d267d08e83a

Not sure this error is reproducible, or if it's related to LWT at all...
Last report of a similar error was in #4304

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1389/artifact/logs-release.2/dtest.log shows the failure from the cassandra driver:
```
2019-12-13 19:42:49,070 8234    dtest                          DEBUG    | cql_additional_tests.CQLAdditionalTests.lightweight_transaction_testlightweight_transaction_test - Restart node with experimental=on and retry...
2019-12-13 19:42:50,400 8234    cassandra.cluster              WARNING  | [control connection] Error connecting to 127.0.50.1:
...
error: [Errno 111] Tried connecting to [('127.0.50.1', 9042)]. Last error: Connection refused
2019-12-13 19:43:19,166 8234    cassandra.cluster              WARNING  | Cluster.__init__ called with contact_points specified, but load-balancing policies are not specified in some ExecutionProfiles. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['127.0.50.1'], EPs without explicit LBPs = ('EXEC_PROFILE_DEFAULT',))
2019-12-13 19:43:19,197 8234    cassandra.connection           ERROR    | Error decoding response from Cassandra. ver(4); flags(0000); stream(1); op(8); offset(9); len(0); buffer: '\x84\x00\x00\x01\x08\x00\x00\x00\x00'
Traceback (most recent call last):
  File "cassandra/connection.py", line 609, in cassandra.connection.Connection.process_msg
    response = decoder(header.version, self.user_type_map, stream_id,
  File "cassandra/protocol.py", line 1149, in cassandra.protocol._ProtocolHandler.decode_message
    msg = msg_class.recv_body(body, protocol_version, user_type_map, result_metadata)
  File "cassandra/protocol.py", line 633, in cassandra.protocol.ResultMessage.recv_body
    kind = read_int(f)
  File "cassandra/protocol.py", line 1230, in cassandra.protocol.read_int
    return int32_unpack(f.read(4))
  File "/usr/lib64/python2.7/site-packages/cassandra/marshal.py", line 22, in <lambda>
    unpack = lambda s: packer.unpack(s)[0]
error: unpack requires a string argument of length 4
2019-12-13 19:43:19,309 8234    dtest                          DEBUG    | cql_additional_tests.CQLAdditionalTests.lightweight_transaction_testlightweight_transaction_test - Test failed
```

Nothing suspicious in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1389/artifact/logs-release.2/1576266199311_cql_additional_tests.CQLAdditionalTests.lightweight_transaction_test/node1.log AFAICT

**Comment by bhalevy** [comment]
Cc @kostja @gleb-cloudius

**Comment by bhalevy** [comment]
Hmm seen also in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/346/testReport/cql_additional_tests/CQLAdditionalTests/lightweight_transaction_test/

**Comment by slivne** [comment]
I vaguely remember that we have decide to return a result always while Cassandra doesn't .... is this related ?

**Comment by kostja** [comment]
No it should be not related. If it was, it would fail consistently.

**Comment by kostja** [comment]
@bhalevy are there any stats as to how frequent this is?

**Comment by slivne** [comment]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/346/testReport/cql_additional_tests/CQLAdditionalTests/lightweight_transaction_test/history/

**Comment by kostja** [comment]
@slivne please help me read this. When did it start to fail for the first time this way? Is it failing consistently or is it flaky?

**Comment by bhalevy** [comment]
> @slivne please help me read this. When did it start to fail for the first time this way? Is it failing consistently or is it flaky?

@kostja we started hitting that in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1388/ using scylla 9ec98324edb29596be9009cf54129d267d08e83a
Right after 64cade15cc6392fb72d7f0f76e25ebcfa3983f58 (Merge "bouncing lwt request to an owning shard" from Gleb)
Looking at https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1403/testReport/cql_additional_tests/CQLAdditionalTests/lightweight_transaction_test/history/
the tests fails about half the times on average.

In dtest-release, it started failing in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/346/testReport/junit/cql_additional_tests/CQLAdditionalTests/lightweight_transaction_test/
Also scylle version 9ec98324edb29596be9009cf54129d267d08e83a
(Taken from https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/346/artifact/00-Build.txt)

**Comment by avikivity** [comment]
"half the time" matches with two shards per node, and picking the wrong shard half the time.

**Comment by avikivity** [comment]
No release branch was vulnerable, so no backports.
