### ISSUE TITLE
cast_varint_test: Sum overflow

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5586]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/367/testReport/cql_cast_test/CQLCastTest/cast_varint_test/
Caused by e97a111f642aff2aa1241a9d4261edfd97e545c1
```
Error Message
'' != 'NaN'
+ NaN : casting from type varint to type float: expected NaN but got 
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_cast_test.py", line 32, in cast_varint_test
    self._test_run(test_from, TestData.POSITIVE_VALUES)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_cast_test.py", line 227, in _test_run
    test_types=test_types, test_to=test_to, compare_error=compare_error)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_cast_test.py", line 272, in _test_one_type
    assert_equal(actual_result, str(exp_result), "casting from type {} to type {}: expected {} but got {}".format(from_type, to_type, exp_result, actual_result))
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 1250, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: '' != 'NaN'
+ NaN : casting from type varint to type float: expected NaN but got 
Standard Output
(EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  (EE)  <stdin>:3:ErrorMessageSub: Sum overflow. Values should be casted to a wider type.(EE)  
```

**Comment by avikivity** [comment]
Aged out.
