### ISSUE TITLE
paging_tests: Requested pages were not delivered before timeout. Requested: 1; retrieved: 0; empty retrieved 0

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5587]
Seen this failure in several paging test cases:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/367/testReport/paging_test/TestPagingWithIndexingAndAggregation/test_filter_indexed_column/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/367/testReport/paging_test/TestPagingWithIndexingAndAggregation/test_filter_non_indexed_column/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/367/testReport/paging_test/TestPagingWithIndexingAndAggregation/test_filter_pk_column/
```
Error Message
Requested pages were not delivered before timeout. Requested: 1; retrieved: 0; empty retrieved 0
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 2870, in test_filter_indexed_column
    self.create_and_verify_mybool_results(session, ['someint', 'somebigint'])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 2858, in create_and_verify_mybool_results
    self._create_and_verify_results(session, cols, filter_func, where_clause, allow_filtering=allow_filtering)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 2853, in _create_and_verify_results
    self._verify_col_results(session, filtered_list, query_fmt, col)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 2842, in _verify_col_results
    self._verify_col_func_results(session, filtered_list, query_fmt, col, 'sum', lambda l: ctypes.c_int(sum(l)).value)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 2833, in _verify_col_func_results
    assert_msg='{}({}) returned wrong value'.format(query_func, col))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 2823, in execute_query_and_compare_results
    pf = PageFetcher(future).request_all()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 64, in __init__
    self.wait(seconds=30)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 138, in wait
    raise RuntimeError(error_message('Requested pages were not delivered before timeout'))
RuntimeError: Requested pages were not delivered before timeout. Requested: 1; retrieved: 0; empty retrieved 0
```

Scylla version 3853594108dc0686aeeeb7eecc9ea340b479fabc
Node logs here: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/367/artifact/logs-release.2/

**Comment by slivne** [comment]
@bhalevy can you please triage this and help point the person (I tried to check what went into 367) and I did not find the immediate suspect.

**Comment by bhalevy** [comment]
@slivne it is my patch fixing sum overflow (0bde5906b3337be7691a8fd62d3dfe98e07437e4) that caused this regression in the test as seen by cassandra stress error messages:
```
cassandra.protocol.ErrorMessageSub: <Error from server: code=1aff [Unknown] message="Sum overflow. Values should be casted to a wider type.">
2020-01-12 00:04:24,302 32341   cassandra.connection           ERROR    | Callback handler errored, ignoring:
Traceback (most recent call last):
  File "cassandra/connection.py", line 628, in cassandra.connection.Connection.process_msg
  File "cassandra/cluster.py", line 3878, in cassandra.cluster.ResponseFuture._set_result
  File "cassandra/cluster.py", line 3976, in cassandra.cluster.ResponseFuture._set_final_exception
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 82, in handle_error
    raise exc
  File "cassandra/cluster.py", line 3840, in cassandra.cluster.ResponseFuture._set_result
  File "cassandra/cluster.py", line 3976, in cassandra.cluster.ResponseFuture._set_final_exception
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/paging_test.py", line 82, in handle_error
    raise exc
```

**Comment by bhalevy** [comment]
The test should be fixed to prevent and/or handle sum overflow errors, so closing this scylla issue.
