### ISSUE TITLE
Queries with CL Quorum are failing in mixed cluster (3.1 and 3.2)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5593]
*Installation details*
Scylla version (or git commit hash):

- Old version: 3.1.2-0.20191127.9d78d848e
- New version: 3.2.0-0.20200113.798357f656

Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Test Job:

- https://jenkins.scylladb.com/job/scylla-3.2/job/rolling-upgrade/job/rolling-upgrade-centos7/57
- test id: c812d899-cd03-4c7f-be99-f90394f6fe43
- Living cluster:  [GCE link](https://console.cloud.google.com/compute/instances?project=skilled-adapter-452&instancessize=50&instancesquery=%255B%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22c812d899_5C_22_22%257D%255D)
   - rolling-upgrade-3-2-centos-db-node-c812d899-0-1 [34.74.0.145 | 10.142.0.36] 
   - rolling-upgrade-3-2-centos-db-node-c812d899-0-2 [34.74.171.217 | 10.142.0.97] 
   - rolling-upgrade-3-2-centos-db-node-c812d899-0-3 [35.196.218.191 | 10.142.0.101] 
   - rolling-upgrade-3-2-centos-db-node-c812d899-0-4 [34.73.169.212 | 10.142.0.103] 
   - rolling-upgrade-3-2-centos-loader-node-c812d899-0-1 [35.237.198.4 | 10.142.0.104] 
   - rolling-upgrade-3-2-centos-monitor-node-c812d899-0-1 [35.196.234.254 | 10.142.0.105] 

### Description

After upgraded one db node (db-node-c812d899-0-2,  [34.74.171.217 | 10.142.0.97]), we run some verify testing (https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/fill_db_data.py), the verify test failed in insert data to collection: `UPDATE collection_and_regular_test SET l[0] = 1, c = 42 WHERE k = 3`.

client error: `ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for keyspace_fill_db_data.collection_and_regular_test - received only 1 responses from 2 CL=QUORUM." info={'received_responses': 1, 'required_responses': 2, 'consistency': 'QUORUM'}`

```
        # collection_and_regular_test
        {
            'create_tables': [
                """CREATE TABLE collection_and_regular_test (
            k int PRIMARY KEY,
            l list<int>,
            c int
          )"""],
            'truncates': ["TRUNCATE collection_and_regular_test"],
            'inserts': [
                "INSERT INTO collection_and_regular_test(k, l, c) VALUES(3, [0, 1, 2], 4)",
                "UPDATE collection_and_regular_test SET l[0] = 1, c = 42 WHERE k = 3"],
            'queries': ["SELECT l, c FROM collection_and_regular_test WHERE k = 3"],
            'results': [[[[1, 1, 2], 42]]],
            'min_version': '',
            'max_version': '',
            'skip': ''},
```

### DB Errors from db-node-c812d899-0-1 & db-node-c812d899-0-4

```
2020-01-14 09:36:33 regex=Exception  line_number=5250 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-4 [34.73.169.212 | 10.142.0.103] (seed: False)
2020-01-14T09:36:33  | scylla: [shard 3] rpc - client 10.142.0.97:59539 msg_id 579006:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:35 regex=Exception  line_number=5251 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-4 [34.73.169.212 | 10.142.0.103] (seed: False)
2020-01-14T09:36:35  | scylla: [shard 3] rpc - client 10.142.0.97:59539 msg_id 579027:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:37 regex=Exception  line_number=5252 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-4 [34.73.169.212 | 10.142.0.103] (seed: False)
2020-01-14T09:36:37  | scylla: [shard 3] rpc - client 10.142.0.97:59539 msg_id 579030:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:39 regex=Exception  line_number=5256 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-4 [34.73.169.212 | 10.142.0.103] (seed: False)
2020-01-14T09:36:39  | scylla: [shard 3] rpc - client 10.142.0.97:59539 msg_id 579051:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:33 regex=Exception  line_number=7756 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-1 [34.74.0.145 | 10.142.0.36] (seed: True)
2020-01-14T09:36:33  | scylla: [shard 3] rpc - client 10.142.0.97:55691 msg_id 564770:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:35 regex=Exception  line_number=7757 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-1 [34.74.0.145 | 10.142.0.36] (seed: True)
2020-01-14T09:36:35  | scylla: [shard 3] rpc - client 10.142.0.97:55691 msg_id 564771:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:37 regex=Exception  line_number=7758 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-1 [34.74.0.145 | 10.142.0.36] (seed: True)
2020-01-14T09:36:37  | scylla: [shard 3] rpc - client 10.142.0.97:55691 msg_id 564772:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:39 regex=Exception  line_number=7759 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-1 [34.74.0.145 | 10.142.0.36] (seed: True)
2020-01-14T09:36:39  | scylla: [shard 3] rpc - client 10.142.0.97:55691 msg_id 564773:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:41 regex=Exception  line_number=7760 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-1 [34.74.0.145 | 10.142.0.36] (seed: True)
2020-01-14T09:36:41  | scylla: [shard 3] rpc - client 10.142.0.97:55691 msg_id 564774:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:43 regex=Exception  line_number=7761 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-1 [34.74.0.145 | 10.142.0.36] (seed: True)
2020-01-14T09:36:43  | scylla: [shard 3] rpc - client 10.142.0.97:55691 msg_id 564775:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
2020-01-14 09:36:43 regex=Exception  line_number=5257 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-4 [34.73.169.212 | 10.142.0.103] (seed: False)
2020-01-14T09:36:43  | scylla: [shard 3] rpc - client 10.142.0.97:59539 msg_id 579077:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
```

### Key SCT Logs with timestamps:

- upgraded one db node (db-node-c812d899-0-2)
- execute verify test
- db error raised from db-node-c812d899-0-1 and db-node-c812d899-0-4 in inserting data to collection. and the insert failed for `ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for       keyspace_fill_db_data.collection_and_regular_test - received only 1 responses from 2 CL=QUORUM." info={'received_responses': 1, 'required_responses': 2, 'consistency':      'QUORUM'}`
```
< t:2020-01-14 09:04:36,148 f:upgrade_test.py l:473  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-3-2-centos-db-node-c812d899-0-2 begin
< t:2020-01-14 09:04:44,896 f:upgrade_test.py l:111  c:sdcm.tester          p:INFO  > Upgrading a Node

2020-01-14 09:36:41,381 > 2020-01-14 09:36:39.000: (DatabaseLogEvent Severity.CRITICAL): type=DATABASE_ERROR regex=Exception  line_number=5256 node=Node rolling-upgrade-3-2-centos-db-node-c812d899-0-4 [34.73.169.212 | 10.142.0.103] (seed: False)
2020-01-14 09:36:41,381 > 2020-01-14T09:36:39+00:00  rolling-upgrade-3-2-centos-db-node-c812d899-0-4 !INFO    | scylla: [shard 3] rpc - client 10.142.0.97:59539 msg_id      579051:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)

2020-01-14 09:36:44,961 > 2020-01-14T09:36:33+00:00  rolling-upgrade-3-2-centos-db-node-c812d899-0-1 !INFO    | scylla: [shard 3] rpc - client 10.142.0.97:55691 msg_id      564770:  got exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)

2020-01-14 09:36:45,194 > failed to insert: UPDATE collection_and_regular_test SET l[0] = 1, c = 42 WHERE k = 3
2020-01-14 09:36:45,194 > failed to insert: UPDATE collection_and_regular_test SET l[0] = 1, c = 42 WHERE k = 3

2020-01-14 09:36:45,194 > Traceback (most recent call last):
2020-01-14 09:36:45,194 >   File "/sct/sdcm/fill_db_data.py", line 2918, in cql_insert_data_to_tables
2020-01-14 09:36:45,194 >     session.execute(insert)
2020-01-14 09:36:45,194 >   File "cassandra/cluster.py", line 2134, in cassandra.cluster.Session.execute
2020-01-14 09:36:45,194 >     return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
2020-01-14 09:36:45,194 >   File "cassandra/cluster.py", line 4026, in cassandra.cluster.ResponseFuture.result
2020-01-14 09:36:45,194 >     raise self._final_exception
2020-01-14 09:36:45,194 > ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for       keyspace_fill_db_data.collection_and_regular_test - received only 1 responses from 2 CL=QUORUM." info={'received_responses': 1, 'required_responses': 2, 'consistency':      'QUORUM'}
```

### Reproduce

The issue can be reproduced easily. 4 / 5 jobs failed for this issue, 1 / 5 failed for env issue.

/CC @roydahan @slivne

**Comment by bhalevy** [comment]
@amoskong 
> Old version: 3.1.2-0.20191127.9d78d848e
> New version: 3.1.2-0.20191127.9d78d848e

These are the same, while the title is about mixed cluster

**Comment by amoskong** [comment]
> @amoskong
> 
> > Old version: 3.1.2-0.20191127.9d78d848e
> > New version: 3.1.2-0.20191127.9d78d848e

3.2.0-0.20200113.798357f656

> 
> These are the same, while the title is about mixed cluster

Fixed, thanks.

**Comment by avikivity** [comment]
@amoskong please kill the cluster, I'll try to reproduce locally

**Comment by avikivity** [comment]
@amoskong what are the queries that fail?

**Comment by avikivity** [comment]
I was able to reproduce it with 3.2. Will now try with master.

**Comment by avikivity** [comment]
Does not reproduce with 3.1->master

**Comment by avikivity** [comment]
master is vulnerable, I probably reproduced incorrectly.

**Comment by avikivity** [comment]
The culprit is likely e0b31dd273cb424be4c061e98a19bdbcd1ba03c7

**Comment by amoskong** [comment]
> @amoskong please kill the cluster, I'll try to reproduce locally

Killed.

> @amoskong what are the queries that fail?

`UPDATE collection_and_regular_test SET l[0] = 1, c = 42 WHERE k = 3`

**Comment by avikivity** [comment]
Backported to 3.2.
