### ISSUE TITLE
nodetool listsnapshots failed during parallel running with create/clear snapshots

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#5603]
*Installation details*
Scylla version (or git commit hash): unstable/branch-3.2:202001152008
Cluster size:1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu/ dtest

Created cluster with one node. Created several keyspaces which contains several tables. Filled with data: partition contains several rows.
After that run snapshot operations in parallel:
create snapshot,
clear snapshot
listsnapshots.

the list snapshot periodically failed with next error:
```
NodetoolError: Nodetool command '/home/abykov/.ccm/scylla-repository/unstable/branch-3.2/202001152008/scylla-java-tools/bin/nodetool -h 127.0.0.1 -p 7100 listsnapshots' failed; exit status: 2; stdout: Snapshot Details: 
; stderr: error: Scylla API server HTTP GET to URL '/storage_service/snapshots/size/true' failed: filesystem error: stat failed: No such file or directory [/home/abykov/.dtest/dtest-GEXxMt/test/node1/data/ks12/table_cf1-fc1c5e50387811ea9011000000000000/snapshots/1579190338768/mc-1-big-Filter.db]
-- StackTrace --
java.lang.IllegalStateException: Scylla API server HTTP GET to URL '/storage_service/snapshots/size/true' failed: filesystem error: stat failed: No such file or directory [/home/abykov/.dtest/dtest-GEXxMt/test/node1/data/ks12/table_cf1-fc1c5e50387811ea9011000000000000/snapshots/1579190338768/mc-1-big-Filter.db]
	at com.scylladb.jmx.api.APIClient.getException(APIClient.java:139)
	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:186)
	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:208)
	at com.scylladb.jmx.api.APIClient.getLongValue(APIClient.java:511)
	at org.apache.cassandra.service.StorageService.trueSnapshotsSize(StorageService.java:592)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.scylladb.jmx.utils.APIMBeanServer.invoke(APIMBeanServer.java:168)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
steps to reproduce
1. create cluster and  node
2. create keyspaces and tables
3. fill data (better large amount of data)
4. run nodetool snapshot ( to create snapshots for all keyspaces and tables
5. run in parallel next operations:
5.1 nodetool snapshot
5.2 nodetool cleansnapshots
5.2 nodetool listsnapshots

**Comment by aleksbykov** [comment]
Related materials:
PR with tests: https://github.com/scylladb/scylla-dtest/pull/1172
PR introduced not permitted parallel snapshot operation: https://github.com/scylladb/scylla/commit/91b71a0b1a5a18b520327e87df52b88b7a715e09
Related issues:
https://github.com/scylladb/scylla/issues/4554
https://github.com/scylladb/scylla/issues/4557

**Comment by avikivity** [comment]
Backported to 4.0.
