### ISSUE TITLE
BATCH statements do not support v2 encoding of requests

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#563]
This was  created based on Raphael's and Tzach's report of an issue with cassandra-stress with user profile

BATCH statements created via the cassandra-stress user profile may be using v2 frames

We currently do not parse them correctly and throw 
```
truncated frame: expected 1 bytes, length is 0
```

which will lead to cassandra-stress to report

```
com.datastax.driver.core.exceptions.DriverInternalError: Anunexpected protocol error occurred. This is a bug in this library,please report: truncated frame: expected 1 bytes, length is 0
```

for example (running our cassandra-stress with scylla)
cassandra-stress user profile=sample.yaml ops\(insert=1\) -rate threads=1

where

```
### DML ###
 
# Keyspace Name
keyspace: keyspace2
 
# The CQL for creating a keyspace (optional if it already exists)
keyspace_definition: |
  CREATE KEYSPACE keyspace2 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

# Table name
table: standard1
 
# The CQL for creating a table you wish to stress (optional if it already exists)
table_definition: |
  CREATE TABLE standard1 (
      key blob PRIMARY KEY,
      c0 blob,
      c1 blob,
      c2 blob,
      c3 blob,
      c4 blob
  );

### Column Distribution Specifications ###
 
columnspec:
  - name: key
    size: fixed(10)

  - name: c0
    size: fixed(34)

  - name: c1
    size: fixed(34)

  - name: c2
    size: fixed(34)

  - name: c3
    size: fixed(34)

  - name: c4
    size: fixed(34)


### Batch Ratio Distribution Specifications ###
 
insert:
  partitions: fixed(2)
  select:    fixed(1)/1000
  batchtype: UNLOGGED

queries:
  single:
    cql: select * from standard1 where key = ? LIMIT 1
```

will generate packets have the following format:

```
02:00:00:0d:00:00:01:c7:01:00:02:01:00:10:e6:c7:90:d7:ee:70:ce:56:e8:0f:5c:1c:ba:27:ef:35:00:06:00:00:00:22:e4:82:82:e4:b5:4a:57:1f:6d:c5:df:05:cb:41:73:48:43:a6:a8:2b:1f:4b:3a:05:e1:0e:4f:76:02:c0:8b:a8:66:2a:00:00:00:22:1b:6a:19:03:ae:fa:24:bf:c0:65:83:6b:c9:46:51:16:4f:db:ad:4e:f4:c6:d4:b3:ae:99:c3:c5:54:6d:04:cf:93:8b:00:00:00:22:ac:65:96:7f:0a:c2:5e:9c:21:7b:58:44:37:a3:34:bf:24:11:49:13:03:98:34:8c:64:aa:0b:66:49:6a:89:91:3f:12:00:00:00:22:04:9c:f3:04:63:bc:ba:81:38:12:40:22:b9:00:ee:57:f8:b6:23:17:25:f2:8e:7e:28:2a:72:5b:77:b1:4a:67:c4:5e:00:00:00:22:b3:8f:b0:3a:fe:73:a5:86:f0:d3:53:8a:6c:2f:50:53:1d:22:71:db:f1:bb:78:c0:98:fa:b7:80:4e:57:0e:f4:5f:e6:00:00:00:0a:73:2c:34:70:fb:51:2f:60:d9:cf:01:00:10:e6:c7:90:d7:ee:70:ce:56:e8:0f:5c:1c:ba:27:ef:35:00:06:00:00:00:22:40:58:ce:f7:f2:19:38:fc:85:4f:ab:c8:42:f4:08:b1:76:5d:84:15:1f:c3:9a:de:07:31:93:65:42:ce:9e:9f:dc:63:00:00:00:22:1c:dc:f9:e2:28:de:bb:66:ef:75:da:c6:a0:90:7f:87:21:0e:c5:f1:1a:7f:d8:da:d4:68:ac:42:3b:bc:cd:1d:5c:be:00:00:00:22:be:5f:bf:d6:c9:e0:b7:19:1e:31:a3:9d:4d:d0:83:04:5a:b0:08:5f:21:c9:96:5c:6d:3e:7b:8c:0f:ae:6a:b5:1a:47:00:00:00:22:d6:9c:5c:77:41:71:80:85:3a:d7:03:02:2e:b8:2a:43:20:aa:1a:b2:0f:e0:64:46:4b:ec:88:f8:33:fb:3d:f5:e4:1d:00:00:00:22:00:95:3c:72:e9:8f:bc:16:c4:b8:8a:01:97:bf:73:8a:01:fd:42:03:74:76:a2:f0:d4:53:f6:0e:bc:4d:bb:64:16:90:00:00:00:0a:1f:0e:13:a4:67:82:77:9d:af:93:00:0a
```

In V2 
```
4.1.7. BATCH

  Allows executing a list of queries (prepared or not) as a batch (note that
  only DML statements are accepted in a batch). The body of the message must
  be:
    <type><n><query_1>...<query_n><consistency>
  where:
```

In V3
```
4.1.7. BATCH

  Allows executing a list of queries (prepared or not) as a batch (note that
  only DML statements are accepted in a batch). The body of the message must
  be:
    <type><n><query_1>...<query_n><consistency><flags>[<serial_consistency>][<timestamp>]
```

running with gdb
```
(gdb) where
#0  0x0000003c1405f05d in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x0000000000827ed8 in transport::cql_server::connection::check_room (this=this@entry=0x6000010b0710, buf=..., n=n@entry=1) at transport/server.cc:862
#2  0x000000000082ab8c in read_byte (buf=..., this=0x6000010b0710) at transport/server.cc:877
#3  transport::cql_server::connection::read_options (this=this@entry=0x6000010b0710, buf=...) at transport/server.cc:1018
#4  0x000000000082e3e6 in transport::cql_server::connection::process_batch (this=0x6000010b0710, stream=<optimized out>, buf=..., client_state=...) at transport/server.cc:647
#5  0x000000000083232e in operator() (__closure=0x7fffffffc560) at transport/server.cc:372
#6  apply (args=<optimized out>, func=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3aadec9>) at /home/shlomi/scylla/seastar/core/apply.hh:34
#7  apply<transport::cql_server::connection::process_request_one(bytes_view, uint8_t, uint16_t, service::client_state)::<lambda()> > (args=<optimized out>, 
    func=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3aadf37>) at /home/shlomi/scylla/seastar/core/apply.hh:42
#8  apply<transport::cql_server::connection::process_request_one(bytes_view, uint8_t, uint16_t, service::client_state)::<lambda()> > (args=<optimized out>, 
    func=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3aadf77>) at /home/shlomi/scylla/seastar/core/future.hh:1145
#9  then<transport::cql_server::connection::process_request_one(bytes_view, uint8_t, uint16_t, service::client_state)::<lambda()>, future<std::pair<shared_ptr<transport::cql_server::response>, service::client_state> > > (func=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3ab4da3>, this=0x7fffffffc500) at /home/shlomi/scylla/seastar/core/future.hh:784
#10 transport::cql_server::connection::process_request_one (this=0x6000010b0710, buf=..., op=<optimized out>, stream=<optimized out>, client_state=...) at transport/server.cc:398
#11 0x0000000000832768 in operator() (__closure=<optimized out>) at transport/server.cc:472
#12 futurize<future<std::pair<foreign_ptr<shared_ptr<transport::cql_server::response> >, service::client_state> > >::apply<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>::<lambda()> mutable::<lambda()>&>(transport::cql_server::connection::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>::<lambda()>::<lambda()> &) (func=...) at /home/shlomi/scylla/seastar/core/future.hh:1155
#13 0x000000000083392d in transport::cql_server::connection::process_request()::{lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)#1}::operator()(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&) const::{lambda(temporary_buffer<char>)#1}::operator()(temporary_buffer) const::{lambda()#1}::operator()() () at /home/shlomi/scylla/seastar/core/reactor.hh:996
#14 0x0000000000834c7c in with_gate<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>::<lambda()> > (func=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7bb00>, g=...) at /home/shlomi/scylla/seastar/core/gate.hh:100
#15 operator() (buf=<error reading variable: access outside bounds of object referenced via synthetic pointer>, __closure=0x7fffffffcd60) at transport/server.cc:480
#16 apply (args=args@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7bad1>, 
    func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7babf>) at /home/shlomi/scylla/seastar/core/apply.hh:34
#17 apply<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>, temporary_buffer<char> > (
    args=args@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3aae1e1>, 
    func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3aae1cd>) at /home/shlomi/scylla/seastar/core/apply.hh:42
#18 futurize<future<> >::apply<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>, temporary_buffer<char> >(<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7bf8c>, <unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7e8e9>) (
    func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7bf8c>, 
    args=args@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7e8e9>) at /home/shlomi/scylla/seastar/core/future.hh:1145
#19 0x0000000000835cd1 in then<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>::<lambda(temporary_buffer<char>)>, future<> > (func=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7e930>, this=0x7fffffffce80) at /home/shlomi/scylla/seastar/core/future.hh:784
#20 operator() (v=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7e8ee>, __closure=0x6000014932e0) at transport/server.cc:483
#21 futurize<future<> >::apply<transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>, future<std::experimental::optional<transport::cql_binary_frame_v3> > >(<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7ebc3>) (
    func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b7ebc3>) at /home/shlomi/scylla/seastar/core/future.hh:1155
#22 0x000000000083619e in operator()<future_state<std::experimental::optional<transport::cql_binary_frame_v3> > > (state=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x384fd6d, DIE 0x3b80847>, 
    __closure=0x6000014932c0) at /home/shlomi/scylla/seastar/core/future.hh:833
#23 continuation<future<T>::then_wrapped(Func&&) [with Func = transport::cql_server::connection::process_request()::<lambda(future<std::experimental::optional<transport::cql_binary_frame_v3> >&&)>; Result = future<>; T = {std::experimental::optional<transport::cql_binary_frame_v3>}]::<lambda(auto:2&&)>, std::experimental::optional<transport::cql_binary_frame_v3> >::run(void) (this=0x6000014932a0)
    at /home/shlomi/scylla/seastar/core/future.hh:362
#24 0x000000000047898f in reactor::run_tasks (this=this@entry=0x600000209000, tasks=...) at core/reactor.cc:1222
#25 0x00000000004a611b in reactor::run (this=0x600000209000) at core/reactor.cc:1348
#26 0x00000000004ffad3 in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffd720, ac=ac@entry=11, av=av@entry=0x7fffffffd968, 
    func=func@entry=<unknown type in /home/shlomi/scylla/build/release/scylla, CU 0x55c881, DIE 0x609632>) at core/app-template.cc:123
#27 0x000000000042058b in main (ac=11, av=0x7fffffffd968) at main.cc:352
(gdb) p _version
$3 = 2 '\002'
```

The code we may be missing is the following from BatchMessage.java

```
        public BatchMessage decode(ByteBuf body, int version)
        {
.
.

            QueryOptions options = version < 3
                                 ? QueryOptions.fromPreV3Batch(CBUtil.readConsistencyLevel(body))
                                 : QueryOptions.codec.decode(body, version);
}
```

@penberg , @elcallio do we need to support V2 or should all of this has been resolved in connection setup when V3 was not enforced ?

**Comment by avikivity** [comment]
Likely also related:

```
bytes_opt
collection_type_impl::reserialize(serialization_format from, serialization_format to, bytes_view_opt v) const {
    if (!v) {
        return std::experimental::nullopt;
    }
    auto val = deserialize(*v, from);
    bytes ret(bytes::initialized_later(), serialized_size(get_value_ptr(val)));  // FIXME: serialized_size want @to
    auto out = ret.begin();
    serialize(get_value_ptr(val), out, to);
    return ret;
}
```

**Comment by slivne** [comment]
Ok found the issue

The cassandra-driver that is packaged is cassandra-java-driver-2.0.9.2 - which supports only CQL Binary Version 2 - surprising as it be.

So we need to apply something like https://github.com/apache/cassandra/commit/b94c87a1816b5fc370d14dbc001eaca5b7c720e8

that will upgrade the driver version to be a 2.1.X version that supports  CQL Binary Version 3.

**Comment by elcallio** [comment]
Question: Do you still want a fix for the cql server message parser?

**Comment by slivne** [comment]
we need ro decide if we are going to support v2 as well if so we need todo
it across the board and mot based om failed tests ....

so for now - no need todo the additions to.support v2

**Comment by penberg** [comment]
@slivne I think we could close this specific issue and open a new one for "CQL v1 and v2 binary protocol support." It's a generic issue and we really only support v3 right now.
