### ISSUE TITLE
Warning: schema version mismatch detected in CqlshSmokeTest.select_all_cl_quorum_test 

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5679]
Starting https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1566/testReport/junit/cqlsh_tests.cqlsh_tests/CqlshSmokeTest/dtest___select_all_cl_quorum_test/
scylla version f2feeb4b10b13fbfbfc5b9c7cd3b8c87bc5bce21
cqlsh_tests/cqlsh_tests.py:CqlshSmokeTest.select_all_cl_quorum_test became flaky and fails like this:
```
Error Message
'<stdin>:2:Warning: schema version mismatc[83 chars]s.\n' != ''
- <stdin>:2:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/cqlsh_tests/cqlsh_tests.py", line 1820, in select_all_cl_quorum_test
    self.assertEqual(ks1_stderr, '')
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 1250, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: '<stdin>:2:Warning: schema version mismatc[83 chars]s.\n' != ''
- <stdin>:2:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.

Standard Output
(EE)  (EE)  <stdin>:2:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.(EE)  
```

I'm not sure why we started getting this warning and if it's benign or not,
and that said, if scylla needs fixing or the test to tolerate it.

Until then the test should be removed from next-gating.

**Comment by espindola** [comment]
Failure at: https://jenkins.scylladb.com/job/scylla-master/job/next/1576/consoleText

**Comment by fruch** [comment]
this failure isn't happening anymore, and cqlsh is doing that only as warning for quite some time.

closing this
