### ISSUE TITLE
Cannot create table after failing to create it with too many columns

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5681]
scylla version d13492485f1772fc2350b09595ca1fc57e783f8a

This was derived from the limits_test.py:TestLimits.max_columns_and_query_parameters_test dtest when trying to reverse the order for cases, i.e. start from the longest one, that fails as expected, and going down to creating tables with fewer columns, that should succeed.

Python reproducer:
```python
    def cannot_find_table_uuid_test(self):
        cluster = self.prepare()
        cluster.populate(1).start(wait_for_binary_proto=True, wait_other_notice=True)
        node = cluster.nodelist()[0]
        session = self.patient_cql_connection(node)
        session.execute("CREATE KEYSPACE ks WITH replication={'class':'SimpleStrategy', 'replication_factor':1}")

        def create_table(session, count, expected_exception):
            keys = ""
            for i in range(count):
                keys += "key{} int, ".format(i)
            try:
                c = "CREATE TABLE ks.test1 ({} blub int PRIMARY KEY,)".format(keys)
                session.execute(c)
                assert expected_exception == None, "Table creation succeeded unexpectedly"
            except Exception as e:
                if expected_exception:
                    print("Table creation failed as expected: {}".format(e))
                else:
                    assert False, "Table creation failed unexpectedly: {}".format(e)

        create_table(session, 65535, expected_exception=NoHostAvailable)
        create_table(session, 32767, expected_exception=None)
```

Test output:
```
$ PRINT_DEBUG=true KEEP_TEST_DIR=true NOSE_PROCESSES=1 CASSANDRA_DIR=$HOME/dev/scylla/build/release SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" python3 -m nose -s -v --process-timeout=7200 limits_test.py:TestLimits.cannot_find_table_uuid_test
2020-01-30 15:46:07.084385 going to run tests in parallel
2020-01-30 15:46:07.084479 using the RandomClusterIdAllocator
2020-01-30 15:46:07.118708 cluster ccm directory: /local/home/bhalevy/.dtest/dtest-5mb8r27i
2020-01-30 15:46:07.118904 Starting Scylla cluster from directory /local/home/bhalevy/dev/scylla/build/release
2020-01-30 15:46:07.123822 Allocated cluster ID 15: /local/home/bhalevy/.dtest/dtest-5mb8r27i
Table creation failed as expected: ('Unable to complete the operation against any hosts', {<Host: 127.0.15.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Mutation of 20621708 bytes is too large for the maximum size of 16777216">})
2020-01-30 15:46:11.351187 Test failed with errors: [(<limits_test.TestLimits testMethod=cannot_find_table_uuid_test>, (<class 'AssertionError'>, AssertionError('Table creation failed unexpectedly: (\'Unable to complete the operation against any hosts\', {<Host: 127.0.15.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Can\'t find a column family with UUID df2301c0-4366-11ea-bf2a-000000000001">})'), <traceback object at 0x7fb1cf975f50>))]
2020-01-30 15:46:11.430406 stopping ccm cluster test at: /local/home/bhalevy/.dtest/dtest-5mb8r27i
2020-01-30 15:46:12.508397 Freeing cluster ID 15: link /local/home/bhalevy/.dtest/15
cannot_find_table_uuid_test (limits_test.TestLimits) ... FAIL

======================================================================
FAIL: cannot_find_table_uuid_test (limits_test.TestLimits)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/limits_test.py", line 213, in cannot_find_table_uuid_test
    create_table(session, 32767, expected_exception=None)
  File "/local/home/bhalevy/dev/scylla-dtest/limits_test.py", line 210, in create_table
    assert False, "Table creation failed unexpectedly: {}".format(e)
AssertionError: Table creation failed unexpectedly: ('Unable to complete the operation against any hosts', {<Host: 127.0.15.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Can't find a column family with UUID df2301c0-4366-11ea-bf2a-000000000001">})
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: limits_test.TestLimits.cannot_find_table_uuid_testcannot_find_table_uuid_test - cluster ccm directory: /local/home/bhalevy/.dtest/dtest-5mb8r27i
dtest: DEBUG: limits_test.TestLimits.cannot_find_table_uuid_testcannot_find_table_uuid_test - Starting Scylla cluster from directory /local/home/bhalevy/dev/scylla/build/release
dtest: DEBUG: limits_test.TestLimits.cannot_find_table_uuid_testcannot_find_table_uuid_test - Allocated cluster ID 15: /local/home/bhalevy/.dtest/dtest-5mb8r27i
cassandra.cluster: WARNING: Cluster.__init__ called with contact_points specified, but load-balancing policies are not specified in some ExecutionProfiles. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['127.0.15.1'], EPs without explicit LBPs = ('EXEC_PROFILE_DEFAULT',))
cassandra.cluster: WARNING: Host 127.0.15.1:9042 error: Server error.
cassandra.cluster: WARNING: Host 127.0.15.1:9042 error: Server error.
dtest: DEBUG: limits_test.TestLimits.cannot_find_table_uuid_testcannot_find_table_uuid_test - Test failed with errors: [(<limits_test.TestLimits testMethod=cannot_find_table_uuid_test>, (<class 'AssertionError'>, AssertionError('Table creation failed unexpectedly: (\'Unable to complete the operation against any hosts\', {<Host: 127.0.15.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Can\'t find a column family with UUID df2301c0-4366-11ea-bf2a-000000000001">})'), <traceback object at 0x7fb1cf975f50>))]
dtest: DEBUG: limits_test.TestLimits.cannot_find_table_uuid_testcannot_find_table_uuid_test - stopping ccm cluster test at: /local/home/bhalevy/.dtest/dtest-5mb8r27i
dtest: DEBUG: limits_test.TestLimits.cannot_find_table_uuid_testcannot_find_table_uuid_test - Freeing cluster ID 15: link /local/home/bhalevy/.dtest/15
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 5.417s

FAILED (failures=1)
```

FWIW, The node log 
[node1.log.gz](https://github.com/scylladb/scylla/files/4134230/node1.log.gz) doesn't seem to indicate any problem.

**Comment by bhalevy** [comment]
I noticed that we don't get the second failure if using a different name for the newly created table.

I speculate that scylla doesn't properly recover from the first error (`Mutation of 20621708 bytes is too large for the maximum size of 16777216`) and leaves bad state around that causes the next table creation with the same name to fail.

**Comment by slivne** [comment]
@bhalevy is this a regression ?

**Comment by slivne** [comment]
@bhalevy ping

**Comment by bhalevy** [comment]
> @bhalevy is this a regression ?

@slivne I don't think it ever passed before.  I'd assume it is not a regression
