### ISSUE TITLE
heat_weighted_load_balancing_cl_QUORUM_test dtest is flaky

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#5690]
This test sometimes (but not always) fails with

```
======================================================================
FAIL: heat_weighted_load_balancing_cl_QUORUM_test (heat_weighted_load_balancing_test.HeatWeightedLB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/haaawk/haaawk/custom_partitioner/remove_partitioners/scylla-dtest/heat_weighted_load_balancing_test.py", line 144, in heat_weighted_load_balancing_cl_QUORUM_test
    self.run_heat_weighted_load_balancing('QUORUM')
  File "/home/haaawk/haaawk/custom_partitioner/remove_partitioners/scylla-dtest/heat_weighted_load_balancing_test.py", line 118, in run_heat_weighted_load_balancing
    self.verify_metrics(metrics)
  File "/home/haaawk/haaawk/custom_partitioner/remove_partitioners/scylla-dtest/heat_weighted_load_balancing_test.py", line 59, in verify_metrics
    self.assertAlmostEqual(metrics[key][node_ind][i]['delta']/metrics[key][2][i]['delta'], 1, delta=0.5)
AssertionError: 2.3796223446105427 != 1 within 0.5 delta (1.3796223446105427 difference)
-------------------- >> begin captured logging << --------------------
dtest: DEBUG:  - going to run tests sequentially
dtest: DEBUG:  - using the SingleClusterIdAllocator
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - cluster ccm directory: /home/haaawk/.dtest/dtest-_ug4rdsq
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - Starting Scylla cluster from directory /home/haaawk/haaawk/custom_partitioner/remove_partitioners/scylla/build/release
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - Run stress write
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - Flush system tables
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - Run stress read
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - Get metrics from all nodes
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - Verify metrics
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - Verify scylla_storage_proxy_coordinator_reads_local_node
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - Verify scylla_storage_proxy_replica_reads
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - Test failed with errors: [(<heat_weighted_load_balancing_test.HeatWeightedLB testMethod=heat_weighted_load_balancing_cl_QUORUM_test>, (<class 'AssertionError'>, AssertionError('2.3796223446105427 != 1 within 0.5 delta (1.3796223446105427 difference)'), <traceback object at 0x7f01105b9aa0>))]
dtest: DEBUG: heat_weighted_load_balancing_test.HeatWeightedLB.heat_weighted_load_balancing_cl_QUORUM_testheat_weighted_load_balancing_cl_QUORUM_test - removing ccm cluster test at: /home/haaawk/.dtest/dtest-_ug4rdsq
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 197.059s

FAILED (failures=1)
```

**Comment by haaawk** [comment]
More info can be found here: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/915/

**Comment by haaawk** [comment]
FYI: @penberg @hagitsegev @avikivity @roydahan @fruch

**Comment by bhalevy** [comment]
Fixed with https://github.com/scylladb/scylla-dtest/pull/1278
