### ISSUE TITLE
secondary_indexes_test.TestLocalIndexes.test_stop_node_during_local_index_build is flaky

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#5691]
The test sometimes fails with:
```
Error Message
errors={'127.0.60.1': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.60.1
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-dtest/secondary_indexes_test.py", line 2078, in test_stop_node_during_local_index_build
    self._node_action_during_index_build(node_action='stop', nodes=4, rf=3, num_rows=100000)
  File "/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-dtest/secondary_indexes_test.py", line 2109, in _node_action_during_index_build
    self.create_cf(session, table_name, key_type='int', columns={'b': 'int'}, compaction={'class': self.compaction_strategy})
  File "/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-dtest/dtest.py", line 862, in create_cf
    session.execute(query)
  File "cassandra/cluster.py", line 2141, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={'127.0.60.1': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.60.1
```

More info can be found here: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/914/testReport/junit/secondary_indexes_test/TestLocalIndexes/dtest_not_Parallel___test_stop_node_during_local_index_build/

**Comment by haaawk** [comment]
FYI: @penberg @hagitsegev @avikivity @roydahan @fruch @nyh @psarna

**Comment by bhalevy** [comment]
Cluster is started in `prepare` with the default flags, and those are unsafe with `NOSE_PROCESSES=1` (as shown in https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/914/consoleText).

Should be fixed with https://github.com/scylladb/scylla-dtest/pull/1284

**Comment by slivne** [comment]
seems to be fixed https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/424/testReport/secondary_indexes_test/TestLocalIndexes/
