### ISSUE TITLE
concurrent_schema_changes_test.TestConcurrentSchemaChanges.changes_to_different_nodes_test  is flaky

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#5692]
The test sometimes fails with:
```
Error Message
errors={'127.0.60.1': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.60.1
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-dtest/concurrent_schema_changes_test.py", line 396, in changes_to_different_nodes_test
    self.make_schema_changes(session, namespace='ns1')
  File "/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-dtest/concurrent_schema_changes_test.py", line 120, in make_schema_changes
    session.execute("CREATE INDEX index2_%s ON cf_%s(col3)" % (namespace, namespace))
  File "cassandra/cluster.py", line 2141, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={'127.0.60.1': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.60.1
```

More info here: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/914/testReport/junit/concurrent_schema_changes_test/TestConcurrentSchemaChanges/dtest_not_Parallel___changes_to_different_nodes_test/

**Comment by haaawk** [comment]
FYI: @penberg @hagitsegev @avikivity @roydahan @fruch

**Comment by bhalevy** [comment]
Cluster is started with the default flags, and those are unsafe with `NOSE_PROCESSES=1` (as shown in https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/914/consoleText).

Should be fixed with https://github.com/scylladb/scylla-dtest/pull/1284

**Comment by slivne** [comment]
seems to be fixed https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/418/testReport/concurrent_schema_changes_test/TestConcurrentSchemaChanges/
