### ISSUE TITLE
concurrent_schema_changes_test.TestConcurrentSchemaChanges.snapshot_test is flaky

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#5693]
The test sometimes fails with:
```
Error Message
Nodetool command '/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla/resources/cassandra/bin/nodetool -h 127.0.31.1 -p 7131 describecluster' failed; exit status: 1; stdout: Cluster Information:
nodetool: Scylla API server HTTP GET to URL '/storage_service/cluster_name' failed: Not found
See 'nodetool help' or 'nodetool help <command>'.
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-dtest/concurrent_schema_changes_test.py", line 536, in snapshot_test
    self.validate_schema_consistent(node1)
  File "/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-dtest/concurrent_schema_changes_test.py", line 129, in validate_schema_consistent
    response = node.nodetool('describecluster', True)[0]
  File "/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-ccm/ccmlib/node.py", line 732, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/jenkins/slave/workspace/scylla-master/byo/byo_build_tests_dtest/scylla/resources/cassandra/bin/nodetool -h 127.0.31.1 -p 7131 describecluster' failed; exit status: 1; stdout: Cluster Information:
nodetool: Scylla API server HTTP GET to URL '/storage_service/cluster_name' failed: Not found
See 'nodetool help' or 'nodetool help <command>'.
```

More info here: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/914/testReport/junit/concurrent_schema_changes_test/TestConcurrentSchemaChanges/dtest_not_Parallel___snapshot_test/

**Comment by haaawk** [comment]
FYI: @penberg @hagitsegev @avikivity @roydahan @fruch

**Comment by bhalevy** [comment]
Fails consistently this way in dtest-release since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/373/testReport/concurrent_schema_changes_test/TestConcurrentSchemaChanges/snapshot_test/

**Comment by bhalevy** [comment]
According to the node logs, the test starts the cluster with the default flags, without  `wait_for_binary_proto=True`.

Will be fixed with https://github.com/scylladb/scylla-dtest/pull/1284

**Comment by slivne** [comment]
seems to be fixed https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/418/

**Comment by espindola** [comment]
Failed again:

https://jenkins.scylladb.com/job/scylla-master/job/next/1790/consoleText

Not sure if the same bug or not.
