### ISSUE TITLE
lwt: bind marker (tuple with NULL value) not working as expected in LWT update query

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylla#5710]
*Installation details*
Scylla version (or git commit hash): a74a82d4d245d75311c19d0d8fba404d5d75937e

The following test case fails for Scylla and executes successfully for the latest available Cassandra (3.11.5):

```py
def null_value_tuple_test(self):
    session = self.prepare(options={'experimental_features': ['lwt']})

    table_name = 'null_value_tuple_test'

    session.execute('''
        CREATE TABLE IF NOT EXISTS {table_name} (
            k int PRIMARY KEY,
            test boolean
        )
    '''.format(table_name=table_name))

    insert_stmt = prepare_statement(session, '''
        INSERT INTO {table_name} (k, test) VALUES(?, ?)
    '''.format(table_name=table_name))
    session.execute(insert_stmt, [0, None])

    update_stmt = prepare_statement(session, '''
        UPDATE {table_name} SET test=:new_value WHERE k=0 IF test in :v
    '''.format(table_name=table_name))

    assert_one_prepared(session, update_stmt, [True, None], {'new_value': False, 'v': (None,)})
    assert_one(session, "SELECT * FROM {table_name}".format(table_name=table_name), [0, False])
```

The test also available [there](https://github.com/scylladb/scylla-dtest/pull/1286/files#diff-f970bd5d59bce8c5c4fc15bbeecd80ecR61).

Failing test output for Scylla:
```
SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" CASSANDRA_DIR=${HOME}/work/scylla/build/release python3 -m nose -v -s --nologcapture --process-timeout 1000 cql_prepared_test.py:TestCQL.null_value_tuple_test
null_value_tuple_test (cql_prepared_test.TestCQL) ... FAIL

======================================================================
FAIL: null_value_tuple_test (cql_prepared_test.TestCQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pa.solodovnikov/work/my-dtest/cql_prepared_test.py", line 82, in null_value_tuple_test
    assert_one_prepared(session, update_stmt, [True, None], {'new_value': False, 'v': (None,)})
  File "/home/pa.solodovnikov/work/my-dtest/dtest.py", line 1244, in inner
    return func(*args, **kwargs)
  File "/home/pa.solodovnikov/work/my-dtest/cql_prepared_test.py", line 19, in assert_one_prepared
    assert list_res == [expected], 'Expected %s from "%s", but got %s' % ([expected], stmt.query_string, list_res)
AssertionError: Expected [[True, None]] from "
            UPDATE null_value_tuple_test SET test=:new_value WHERE k=0 IF test in :v
        ", but got [[False, None]]

----------------------------------------------------------------------
Ran 1 test in 3.533s

FAILED (failures=1)
```

The issue manifests only in case where `IN` condition is evauated against a bind marker of the form `:v` (with the value of `(null)`, i.e. `tuple(None)` in python3).

No errors observed if the literal form `IF test IN (null)` is used instead.

`IF test IN (:v)` with bound parameter value of `None` also works as expected.

**Comment by avikivity** [comment]
Backported to 3.3, 3.2.
