### ISSUE TITLE
test_remove_node_during_index_build may fail with Expected a row count of 100000 in query "SELECT * FROM b_index_index", but got 99984

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5780]
This is reproducible with scylla-dtest eada06e5b92259a61733966b66e5160544bc9a9f
scylladb/scylla@43097854a5e043492cacd19cfced047f35a99a6b
when I run multiple instance of the test, it may fail to validate the right node count.
For example:
```
$ PRINT_DEBUG=true KEEP_TEST_DIR=true NOSE_PROCESSES=4 SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" CASSANDRA_DIR=~/dev/scylla/build/dev nosetests -s -v --process-timeout=1800 secondary_indexes_test:TestSecondaryIndexes.test_remove_node_during_index_build{,,,}

2020-02-10 18:58:30.600683 going to run tests in parallel
2020-02-10 18:58:30.600776 using the RandomClusterIdAllocator
2020-02-10 18:58:30.657261 cluster ccm directory: /local/home/bhalevy/.dtest/dtest-expiq04h
2020-02-10 18:58:30.657410 Starting Scylla cluster from directory /local/home/bhalevy/dev/scylla/build/dev
2020-02-10 18:58:30.661733 Allocated cluster ID 41: /local/home/bhalevy/.dtest/dtest-expiq04h
2020-02-10 18:58:30.670152 cluster ccm directory: /local/home/bhalevy/.dtest/dtest-poayf1bw
2020-02-10 18:58:30.670326 Starting Scylla cluster from directory /local/home/bhalevy/dev/scylla/build/dev
2020-02-10 18:58:30.674983 Allocated cluster ID 12: /local/home/bhalevy/.dtest/dtest-poayf1bw
2020-02-10 18:58:30.680505 cluster ccm directory: /local/home/bhalevy/.dtest/dtest-23tbzt0r
2020-02-10 18:58:30.680652 Starting Scylla cluster from directory /local/home/bhalevy/dev/scylla/build/dev
2020-02-10 18:58:30.685721 Allocated cluster ID 66: /local/home/bhalevy/.dtest/dtest-23tbzt0r
2020-02-10 18:58:30.705851 cluster ccm directory: /local/home/bhalevy/.dtest/dtest-whzqc06x
2020-02-10 18:58:30.706005 Starting Scylla cluster from directory /local/home/bhalevy/dev/scylla/build/dev
2020-02-10 18:58:30.710352 Allocated cluster ID 40: /local/home/bhalevy/.dtest/dtest-whzqc06x
2020-02-10 18:58:30.744171 Randomly selected DateTieredCompactionStrategy as compaction strategy for base table
2020-02-10 18:58:30.744224 Randomly selected SizeTieredCompactionStrategy as compaction strategy for base table
2020-02-10 18:58:30.756744 Randomly selected DateTieredCompactionStrategy as compaction strategy for base table
2020-02-10 18:58:30.779450 Randomly selected DateTieredCompactionStrategy as compaction strategy for base table
2020-02-10 18:59:20.559997 The cluster has been started with SMP 2
2020-02-10 18:59:21.660089 CREATE COLUMNFAMILY cf (key int PRIMARY KEY, b int) WITH comment='test cf' AND compression = {} AND compaction={'class': 'DateTieredCompactionStrategy'}
2020-02-10 18:59:22.263300 The cluster has been started with SMP 2
2020-02-10 18:59:22.812497 CREATE COLUMNFAMILY cf (key int PRIMARY KEY, b int) WITH comment='test cf' AND compression = {} AND compaction={'class': 'DateTieredCompactionStrategy'}
2020-02-10 18:59:22.854421 The cluster has been started with SMP 2
2020-02-10 18:59:23.840132 CREATE COLUMNFAMILY cf (key int PRIMARY KEY, b int) WITH comment='test cf' AND compression = {} AND compaction={'class': 'DateTieredCompactionStrategy'}
2020-02-10 18:59:24.742964 The cluster has been started with SMP 2
2020-02-10 18:59:26.294021 CREATE COLUMNFAMILY cf (key int PRIMARY KEY, b int) WITH comment='test cf' AND compression = {} AND compaction={'class': 'SizeTieredCompactionStrategy'}
2020-02-10 18:59:55.337365 Create index: CREATE INDEX b_index ON cf (b)
2020-02-10 18:59:57.574528 Create index: CREATE INDEX b_index ON cf (b)
2020-02-10 18:59:58.321178 Index b_index has been created
2020-02-10 18:59:58.321321 Ensure view building started.
2020-02-10 18:59:58.323193 START: remove node node2
2020-02-10 18:59:58.430410 Create index: CREATE INDEX b_index ON cf (b)
2020-02-10 19:00:00.948047 Index b_index has been created
2020-02-10 19:00:00.948335 Ensure view building started.
2020-02-10 19:00:00.950910 START: remove node node2
2020-02-10 19:00:01.791984 Index b_index has been created
2020-02-10 19:00:01.792172 Ensure view building started.
2020-02-10 19:00:01.799999 START: remove node node2
2020-02-10 19:00:03.018497 Create index: CREATE INDEX b_index ON cf (b)
2020-02-10 19:00:06.103977 Index b_index has been created
2020-02-10 19:00:06.104169 Ensure view building started.
2020-02-10 19:00:06.108298 START: remove node node2
2020-02-10 19:01:09.299934 FINISH: remove node node2
2020-02-10 19:01:09.300040 Add new node
2020-02-10 19:01:09.371161 Start join at 19:01:09
2020-02-10 19:01:10.404667 FINISH: remove node node2
2020-02-10 19:01:10.404885 Add new node
2020-02-10 19:01:10.487164 Start join at 19:01:10
2020-02-10 19:01:11.381867 FINISH: remove node node2
2020-02-10 19:01:11.382089 Add new node
2020-02-10 19:01:11.459695 FINISH: remove node node2
2020-02-10 19:01:11.459793 Add new node
2020-02-10 19:01:11.462099 Start join at 19:01:11
2020-02-10 19:01:11.522095 Start join at 19:01:11
2020-02-10 19:03:03.124199 Finish join at 19:03:03
2020-02-10 19:03:03.126560 Waiting for view ks.b_index_index to finish building...
2020-02-10 19:03:03.794088 Finish join at 19:03:03
2020-02-10 19:03:03.795672 Waiting for view ks.b_index_index to finish building...
2020-02-10 19:03:04.857341 Finish join at 19:03:04
2020-02-10 19:03:04.859724 Waiting for view ks.b_index_index to finish building...
2020-02-10 19:03:05.443352 Finish join at 19:03:05
2020-02-10 19:03:05.446093 Waiting for view ks.b_index_index to finish building...
2020-02-10 19:03:25.301857 Verify data with ONE consistency level
2020-02-10 19:03:25.914140 Verify data with ONE consistency level
2020-02-10 19:03:26.804711 Verify data with ONE consistency level
2020-02-10 19:03:27.091244 Verify data with ONE consistency level
2020-02-10 19:04:28.400563 stopping ccm cluster test at: /local/home/bhalevy/.dtest/dtest-whzqc06x
2020-02-10 19:04:29.488478 Freeing cluster ID 40: link /local/home/bhalevy/.dtest/40
test_remove_node_during_index_build (secondary_indexes_test.TestSecondaryIndexes) ... ok
2020-02-10 19:04:30.597707 Test failed with errors: [(<secondary_indexes_test.TestSecondaryIndexes testMethod=test_remove_node_during_index_build>, (<class 'AssertionError'>, AssertionError('Expected a row count of 100000 in query "SELECT * FROM b_index_index", but got 99984'), <traceback object at 0x7fe397c28460>))]
2020-02-10 19:04:30.623981 stopping ccm cluster test at: /local/home/bhalevy/.dtest/dtest-expiq04h
2020-02-10 19:04:30.708724 Test failed with errors: [(<secondary_indexes_test.TestSecondaryIndexes testMethod=test_remove_node_during_index_build>, (<class 'AssertionError'>, AssertionError('Expected a row count of 100000 in query "SELECT * FROM b_index_index", but got 99967'), <traceback object at 0x7fe3a6a13eb0>))]
2020-02-10 19:04:30.722432 stopping ccm cluster test at: /local/home/bhalevy/.dtest/dtest-poayf1bw
2020-02-10 19:04:31.292242 Test failed with errors: [(<secondary_indexes_test.TestSecondaryIndexes testMethod=test_remove_node_during_index_build>, (<class 'AssertionError'>, AssertionError('Expected a row count of 100000 in query "SELECT * FROM b_index_index", but got 99961'), <traceback object at 0x7fe38dadcaf0>))]
2020-02-10 19:04:31.306774 stopping ccm cluster test at: /local/home/bhalevy/.dtest/dtest-23tbzt0r
2020-02-10 19:04:31.713986 Freeing cluster ID 41: link /local/home/bhalevy/.dtest/41
test_remove_node_during_index_build (secondary_indexes_test.TestSecondaryIndexes) ... FAIL
FAIL
2020-02-10 19:04:31.788781 Freeing cluster ID 12: link /local/home/bhalevy/.dtest/12
test_remove_node_during_index_build (secondary_indexes_test.TestSecondaryIndexes) ... FAIL
FAIL
2020-02-10 19:04:32.371468 Freeing cluster ID 66: link /local/home/bhalevy/.dtest/66
test_remove_node_during_index_build (secondary_indexes_test.TestSecondaryIndexes) ... FAIL
FAIL

======================================================================
FAIL: test_remove_node_during_index_build (secondary_indexes_test.TestSecondaryIndexes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/secondary_indexes_test.py", line 1036, in test_remove_node_during_index_build
    self._node_action_during_index_build(node_action='remove', nodes=4, rf=3, num_rows=100000)
  File "/local/home/bhalevy/dev/scylla-dtest/secondary_indexes_test.py", line 1098, in _node_action_during_index_build
    num_rows_expected=num_rows, consistency_level=ConsistencyLevel.QUORUM)
  File "/local/home/bhalevy/dev/scylla-dtest/dtest.py", line 1244, in inner
    return func(*args, **kwargs)
  File "/local/home/bhalevy/dev/scylla-dtest/assertions.py", line 126, in assert_row_count_in_select
    num_rows_expected, query, count)
AssertionError: Expected a row count of 100000 in query "SELECT * FROM b_index_index", but got 99984
```

On node1 
[system.log](https://github.com/scylladb/scylla-dtest/files/4182155/system.log)
 I can see this:
```
INFO  2020-02-10 19:00:03,561 [shard 0] schema_tables - Creating ks.b_index_index id=c7a551b1-4c26-11ea-848f-000000000000 version=0a15e36a-abed-3817-8afc-85be42803003
...
INFO  2020-02-10 19:00:26,902 [shard 0] gossip - InetAddress 127.0.41.2 is now DOWN, status = NORMAL
INFO  2020-02-10 19:00:26,902 [shard 0] rpc - client 127.0.41.2:7000: fail to connect: Connection refused
ERROR 2020-02-10 19:00:26,902 [shard 0] view - Error applying view update to 127.0.41.2: exceptions::mutation_write_timeout_exception (Operation timed out for ks.b_index_index - received only 0 responses from 1 CL=ONE.)
...
INFO  2020-02-10 19:00:27,823 [shard 0] storage_service - removenode: endpoint = 127.0.41.2, replicating_nodes = {127.0.41.4, 127.0.41.1, 127.0.41.3}
INFO  2020-02-10 19:00:27,837 [shard 0] gossip - Removing host: 1436d545-c659-43bb-8464-051a3b26cbe4
INFO  2020-02-10 19:00:27,837 [shard 0] gossip - Sleeping for 30000ms to ensure 127.0.41.2 does not change
...
INFO  2020-02-10 19:00:57,837 [shard 0] gossip - Advertising removal for 127.0.41.2
...
INFO  2020-02-10 19:00:58,616 [shard 0] stream_session - [Stream #e87e4901-4c26-11ea-848f-000000000000] Start sending ks=ks, cf=b_index_index, estimated_partitions=0, with new rpc streaming
INFO  2020-02-10 19:00:58,618 [shard 1] stream_session - [Stream #e87e4901-4c26-11ea-848f-000000000000] Start sending ks=ks, cf=b_index_index, estimated_partitions=0, with new rpc streaming
...
INFO  2020-02-10 19:01:08,319 [shard 0] storage_service - Got confirm_replication from 127.0.41.4, removing_node 127.0.41.2
...
INFO  2020-02-10 19:01:09,360 [shard 0] gossip - Completing removal of 127.0.41.2
INFO  2020-02-10 19:01:09,360 [shard 0] gossip - Node 127.0.41.2 will be removed from gossip at [2020-02-13 19:01:09]: (expire = 1581613269352, now = 1581354069352, diff = 259200 seconds)
...
INFO  2020-02-10 19:01:14,939 [shard 0] gossip - InetAddress 127.0.41.5 is now UP, status = UNKNOWN
INFO  2020-02-10 19:01:30,467 [shard 0] view - Finished building view ks.b_index_index
...
INFO  2020-02-10 19:02:43,415 [shard 0] stream_session - [Stream #26f35c21-4c27-11ea-af3a-000000000000] Start sending ks=ks, cf=b_index_index, estimated_partitions=38691, with new rpc streaming
INFO  2020-02-10 19:02:43,415 [shard 1] stream_session - [Stream #26f35c21-4c27-11ea-af3a-000000000000] Start sending ks=ks, cf=b_index_index, estimated_partitions=38271, with new rpc streaming
...
INFO  2020-02-10 19:02:50,892 [shard 0] stream_session - [Stream #2ba06970-4c27-11ea-af3a-000000000000] Start sending ks=ks, cf=b_index_index, estimated_partitions=7126, with new rpc streaming
INFO  2020-02-10 19:02:50,892 [shard 1] stream_session - [Stream #2ba06970-4c27-11ea-af3a-000000000000] Start sending ks=ks, cf=b_index_index, estimated_partitions=7049, with new rpc streaming
INFO  2020-02-10 19:02:50,949 [shard 0] stream_session - [Stream #2ba06970-4c27-11ea-af3a-000000000000] Streaming plan for Bootstrap-ks-index-10 succeeded, peers={127.0.41.5}, tx=87 KiB, 456.56 KiB/s, rx=0 KiB, 0.00 KiB/s
```

This needs to be analyzed and determine if the issue is with scylla or with the test.
FWIW the test does seem to wait for the view to be built before running the select query with CL= QUORUM

```
        index_is_built(self.cluster, session, ks_name=keyspace_name, table_name=table_name, index_name=index_name)

        # Validate the data using filtering by index with cl=ONE
        self.validate_index_data(self, session, cl=ConsistencyLevel.ONE, num_rows=num_rows, table_name=table_name,
                                 index_column=index_column)

        # Validate view rows
        assert_row_count_in_select(session=session, query="SELECT * FROM {}".format(view_name),
                                   num_rows_expected=num_rows, consistency_level=ConsistencyLevel.QUORUM)
```

**Comment by bhalevy** [comment]
cc @eliransin @psarna

**Comment by bhalevy** [comment]
There are similar errors in `materialized_views_test:TestMaterializedViews.interrupt_build_process_with_resharding_*`
not that they are using `eventually` but it show no real progress.  For example, when ran locally:
```
2020-03-17 14:54:33.198067 materialized_views_test.py:TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test - <lambda> [1/7]: Expected a row count of 200000 in table 't_by_v2', but got 173983: will retry in 1 second(s)
2020-03-17 14:54:39.746828 materialized_views_test.py:TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test - <lambda> [2/7]: Expected a row count of 200000 in table 't_by_v2', but got 173983: will retry in 2 second(s)
2020-03-17 14:54:47.796876 materialized_views_test.py:TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test - <lambda> [3/7]: Expected a row count of 200000 in table 't_by_v2', but got 173983: will retry in 4 second(s)
2020-03-17 14:54:55.881217 materialized_views_test.py:TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test - <lambda> [4/7]: Expected a row count of 200000 in table 't_by_v2', but got 173983: will retry in 8 second(s)
2020-03-17 14:55:10.410384 materialized_views_test.py:TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test - <lambda> [5/7]: Expected a row count of 200000 in table 't_by_v2', but got 173983: will retry in 16 second(s)
2020-03-17 14:55:31.983546 materialized_views_test.py:TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test - <lambda> [6/7]: Expected a row count of 200000 in table 't_by_v2', but got 173983: will retry in 32 second(s)
```

**Comment by eliransin** [comment]
@bhalevy does this reproduce every time? any special steps to reproduce?

**Comment by bhalevy** [comment]
> @bhalevy does this reproduce every time? any special steps to reproduce?

@eliransin it seems to be reliably reproduced on jenkins since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/420/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test/
(Scylla version c020b4e5e20e7f3b5e8fe0a12271f3adc5449be2)

I needed no special steps to reproduce locally.  Try this command on a machine with enough cores (mine has 12, not sure if 4, for example, are enough to reproduce)
```
PRINT_DEBUG=true NOSE_PROCESSES=1 SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" CASSANDRA_DIR=<your-path-to>/scylla/build/dev nosetests -s -v --process-timeout=3600 materialized_views_test:TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test
```

**Comment by slivne** [comment]
@bhalevy can we close this

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/420/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test/history/

seems to be green in the last ~25 runs or so

**Comment by bhalevy** [comment]
@slivne the flakiness is still there.  See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/431/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build/history/

Last hit at https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/451/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build/

**Comment by bhalevy** [comment]
Not seen in last ~50 runs.  Closing...
