### ISSUE TITLE
lwt: conditional update for list<T> fails to apply for "IF value[:i]=:v" pattern and null values

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylla#5791]
*Installation details*
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/43097854a5e043492cacd19cfced047f35a99a6b

LWT updates fail to apply under the following circumstances:

```
CREATE TABLE IF NOT EXISTS test_table (
    k int PRIMARY KEY,
    test list<boolean>
)

-- prepared stmt
-- supply [0, [None]] as arguments
INSERT INTO test_table (k, test) VALUES(?, ?)

-- prepared update stmt
-- supply these arguments: {'new_value': [False], 'i': 0, 'v': None}
UPDATE test_table SET test=:new_value WHERE k=0 IF test[:i]=:v
```
The last statement returns `[False, [None]]` row instead of `[True, [None]]`.

This also can be demonstrated by running the following dtest test case: https://github.com/scylladb/scylla-dtest/pull/1286/files#diff-f970bd5d59bce8c5c4fc15bbeecd80ecR553

Console output in this case is as follows:
```
SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" CASSANDRA_DIR=${HOME}/work/scylla/build/debug python3 -m nose -v -s --nologcapture --process-timeout 1000 cql_prepared_test.py:TestCQL.null_value_boolean_list_index_access_test
null_value_boolean_list_index_access_test (cql_prepared_test.TestCQL) ... FAIL

======================================================================
FAIL: null_value_boolean_list_index_access_test (cql_prepared_test.TestCQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pa.solodovnikov/work/my-dtest/cql_prepared_test.py", line 575, in null_value_boolean_list_index_access_test
    assert_one_prepared(session, update_stmt, [True, [None]], {'new_value': [False], 'i': 0, 'v': None})
  File "/home/pa.solodovnikov/work/my-dtest/dtest.py", line 1244, in inner
    return func(*args, **kwargs)
  File "/home/pa.solodovnikov/work/my-dtest/cql_prepared_test.py", line 19, in assert_one_prepared
    assert list_res == [expected], 'Expected %s from "%s", but got %s' % ([expected], stmt.query_string, list_res)
AssertionError: Expected [[True, [None]]] from "
            UPDATE null_value_boolean_list_index_access_test SET test=:new_value WHERE k=0 IF test[:i]=:v
        ", but got [[False, [None]]]

----------------------------------------------------------------------
Ran 1 test in 17.800s

FAILED (failures=1)
```

**Comment by ManManson** [comment]
Closing as "invalid", because we should not even be able to INSERT nulls in a collection column at first place. More detailed description of an underlying problem is given in https://github.com/scylladb/scylla/issues/5825.
