### ISSUE TITLE
Early call to /v2/config while scylla start may crash on "local_is_initialized, class database" assertion

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla#5849]
There's a misordering in registration of API rules vs database.start() call.

https://github.com/scylladb/scylla-enterprise/issues/1234#issuecomment-586969372

**Comment by bhalevy** [comment]
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f29b2fff8db in __GI_abort () at abort.c:100
#2  0x00007f29b2fef39a in __assert_fail_base (fmt=0x7f29b31767d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x55ab8d97dbf3 "local_is_initialized()", file=file@entry=0x55ab8d97dbd9 "./seastar/core/sharded.hh", 
    line=line@entry=540, function=function@entry=0x55ab8da90f40 <seastar::sharded<database>::local()::__PRETTY_FUNCTION__> "Service& seastar::sharded<T>::local() [with Service = database]") at assert.c:92
#3  0x00007f29b2fef412 in __GI___assert_fail (assertion=0x55ab8d97dbf3 "local_is_initialized()", file=0x55ab8d97dbd9 "./seastar/core/sharded.hh", line=540, 
    function=0x55ab8da90f40 <seastar::sharded<database>::local()::__PRETTY_FUNCTION__> "Service& seastar::sharded<T>::local() [with Service = database]") at assert.c:101
#4  0x000055ab89ca2d68 in seastar::sharded<database>::local (this=<optimized out>) at ./seastar/core/sharded.hh:540
#5  0x000055ab8d6590ff in api::<lambda(seastar::httpd::const_req)>::operator()(seastar::httpd::const_req) const (__closure=0x600000610560, r=...) at api/config.cc:106
#6  0x000055ab8d65c299 in std::_Function_handler<seastar::json::json_return_type(const seastar::httpd::request&), api::set_config(std::shared_ptr<seastar::httpd::api_registry_builder20>, api::http_context&, seastar::httpd::routes&)::<lambda(seastar::httpd::const_req)> >::_M_invoke(const std::_Any_data &, const seastar::httpd::request &) (__functor=..., __args#0=...) at /opt/scylladb/include/c++/7/bits/std_function.h:302
#7  0x000055ab898300dd in std::function<seastar::json::json_return_type (seastar::httpd::request const&)>::operator()(seastar::httpd::request const&) const (__args#0=..., this=<optimized out>) at /opt/scylladb/include/c++/7/bits/std_function.h:706
#8  seastar::httpd::function_handler::function_handler(std::function<seastar::json::json_return_type (seastar::httpd::request const&)> const&)::{lambda(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >, std::unique_ptr<seastar::httpd::reply, std::default_delete<seastar::httpd::reply> >)#1}::operator()(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >, std::unique_ptr<seastar::httpd::reply, std::default_delete<seastar::httpd::reply> >) const (rep=..., req=..., __closure=<optimized out>) at http/function_handlers.hh:93
#9  std::_Function_handler<seastar::future<std::unique_ptr<seastar::httpd::reply, std::default_delete<seastar::httpd::reply> > > (std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >, std::unique_ptr<seastar::httpd::reply, std::default_delete<seastar::httpd::reply> >), seastar::httpd::function_handler::function_handler(std::function<seastar::json::json_return_type (seastar::httpd::request const&)> const&)::{lambda(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >, std::unique_ptr<seastar::httpd::reply, std::default_delete<seastar::httpd::reply> >)#1}>::_M_invoke(std::_Any_data const&, std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >&&, std::unique_ptr<seastar::httpd::reply, std::default_delete<seastar::httpd::reply> >&&) (__functor=..., __args#0=..., __args#1=...) at /opt/scylladb/include/c++/7/bits/std_function.h:302
#10 0x000055ab89848674 in std::function<seastar::future<std::unique_ptr<seastar::httpd::reply, std::default_delete<seastar::httpd::reply> > > (std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >, std::unique_ptr<seastar::httpd::reply, std::default_delete<seastar::httpd::reply> >)>::operator()(std::unique_ptr<seastar::httpd::request, std::default_delete<seastar::httpd::request> >, std::unique_ptr<seastar::httpd::reply, std::default_delete<seastar::httpd::reply> >) const (__args#1=..., __args#0=..., this=0x6000003ba520) at /opt/scylladb/include/c++/7/bits/std_function.h:706
#11 seastar::httpd::function_handler::handle (rep=..., req=..., path=..., this=0x6000003ba500) at http/function_handlers.hh:118
#12 seastar::httpd::routes::handle (this=this@entry=0x6000001e1900, path=..., req=..., rep=...) at http/routes.cc:94
#13 0x000055ab89866d46 in seastar::httpd::connection::generate_reply (this=0x6000000e4a00, req=...) at http/httpd.cc:231
#14 0x000055ab89869a14 in seastar::httpd::connection::<lambda()>::<lambda()>::operator() (__closure=<optimized out>) at http/httpd.cc:173
#15 seastar::apply_helper<seastar::httpd::connection::read_one()::<lambda()> mutable::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (args=..., func=...)
    at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/core/apply.hh:35
#16 seastar::apply<seastar::httpd::connection::read_one()::<lambda()> mutable::<lambda()> > (args=..., func=...) at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/core/apply.hh:43
#17 seastar::futurize<seastar::future<bool> >::apply<seastar::httpd::connection::read_one()::<lambda()> mutable::<lambda()> > (args=..., func=...) at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/core/future.hh:1389
#18 seastar::future<>::then<seastar::httpd::connection::read_one()::<lambda()> mutable::<lambda()> > (func=..., this=0x7ffe1dccb760) at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/core/future.hh:952
#19 seastar::httpd::connection::<lambda()>::operator()(void) (__closure=__closure@entry=0x6000007ab138) at http/httpd.cc:171
#20 0x000055ab8986b354 in seastar::apply_helper<seastar::httpd::connection::read_one()::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (args=..., func=...)
    at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/core/apply.hh:35
#21 seastar::apply<seastar::httpd::connection::read_one()::<lambda()> > (args=..., func=...) at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/core/apply.hh:43
#22 seastar::futurize<seastar::future<> >::apply<seastar::httpd::connection::read_one()::<lambda()> > (args=..., func=...) at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/core/future.hh:1389
#23 seastar::future<>::<lambda(auto:1&&)>::operator()<seastar::future_state<> > (state=..., __closure=0x6000007ab118) at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/core/future.hh:963
#24 seastar::continuation<seastar::future<T>::then(Func&&) [with Func = seastar::httpd::connection::read_one()::<lambda()>; Result = seastar::future<>; T = {}]::<lambda(auto:1&&)> >::run_and_dispose(void) (this=0x6000007ab100)
    at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/core/future.hh:414
#25 0x000055ab892c1c8f in seastar::reactor::run_tasks (this=this@entry=0x600000020000, tq=...) at core/reactor.cc:2732
#26 0x000055ab892c1e62 in seastar::reactor::run_some_tasks (this=this@entry=0x600000020000) at core/reactor.cc:3156
#27 0x000055ab893970e0 in seastar::reactor::run_some_tasks (this=0x600000020000) at /build/scylla-enterprise-server-2019.1.4-0.20191217.b59e92dbd/seastar/util/log.hh:313
#28 seastar::reactor::run (this=0x600000020000) at core/reactor.cc:3303
#29 0x000055ab894d142e in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=<optimized out>, ac=<optimized out>, av=<optimized out>, func=...) at core/app-template.cc:185
#30 0x000055ab892421b2 in main (ac=19, av=0x7ffe1dccc608) at main.cc:889
```

**Comment by bhalevy** [comment]
@xemul what versions are vulnerable?

**Comment by xemul** [comment]
@bhalevy , 3.2 and 3.3 only. The call for db.local() inside set_config's lambdas (the one that crashes) was introduced after 3.1 with commit b663cd17

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport to 3.3, 3.2, 2019.1

**Comment by avikivity** [comment]
Aged out.
