### ISSUE TITLE
lwt: comparing NULL collection with empty value in IF condition yields incorrect results

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylla#5855]
*Installation details*
Scylla version (or git commit hash): b01b11c1f3fb245757402e157fca42c51c47362b

Initial data and test table description:
```
CREATE TABLE test (
    k INT PRIMARY KEY,
    lvalue list<boolean>
)

-- intentionally leave lvalue==null
INSERT INTO test (k) VALUES (0)
```
When executing the following LWT update statement via Python driver with args `{'update_val': [], 'v': []}`:
```
UPDATE test SET lvalue=:update_val WHERE k=0 IF lvalue=:v
```
This query is expected to return `True` in `[applied]` column, yet in case of prepared statement this returns `False` instead:
```
======================================================================
FAIL: compare_collection_with_null_test (cql_prepared_test.TestCQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pa.solodovnikov/work/my-dtest/cql_prepared_test.py", line 576, in compare_collection_with_null_test
    assert_one_prepared(session, ti.stmt, [True, None], {'update_val': ti.empty, 'v': ti.empty})
  File "/home/pa.solodovnikov/work/my-dtest/dtest.py", line 1244, in inner
    return func(*args, **kwargs)
  File "/home/pa.solodovnikov/work/my-dtest/assertions.py", line 71, in assert_one_prepared
    assert list_res == [expected], 'Expected %s from "%s", but got %s' % ([expected], stmt.query_string, list_res)
AssertionError: Expected [[True, None]] from "
                    UPDATE test SET lvalue=:update_val WHERE k=0 IF lvalue=:v
                ", but got [[False, None]]

----------------------------------------------------------------------
```

This issue can be reproduced by this test case [(dtest)](https://github.com/ManManson/scylla-dtest/commit/4282e86135f265e2ea46899ae77c896915818e1b#diff-f970bd5d59bce8c5c4fc15bbeecd80ecR495).

Un-prepared variant of the query works as expected.

**Comment by nyh** [comment]
Also reproduced by the translated Cassandra unit test `cassandra_tests/validation/operations/insert_update_if_condition_collections_test.py`::`testNonFrozenEmptyCollection`. That test has a null list value:
```python
    with create_table(cql, test_keyspace, f"(k int PRIMARY KEY, l list<text>)") as table:
        execute(cql, table, "INSERT INTO %s (k, l) VALUES (0, null)")
```
and then attempts an `IF l == []` and expects it to succeed:
```python
        assert list(execute(cql, table, "UPDATE %s SET l = null WHERE k = 0 IF l = ?", []))[0][0] == True
```
but returns False.

Surprisingly, if the bound variable isn't an empty list but a null, it passes (this is the previous line in that test:
```python
        assert list(execute(cql, table, "UPDATE %s SET l = null WHERE k = 0 IF l = ?", None))[0][0] == True
```

So somehow, the comparison code sees an empty list constant in this context not as a null (which is what an empty list usually is) but as something else, not equal to null, but in our present LWT implementation null is equal to null so that second check `IF l = null` does pass.

**Comment by nyh** [comment]
A related bug also exposed in `cassandra_tests/validation/operations/insert_update_if_condition_collections_test.py`::`testNonFrozenEmptyCollection`:

If the list column is an empty list (which is the same as null), the LWT expression `if l < ["a"]`, which should be True, returns False. Again it appears that `l` is treated as a null instead of an empty list.

This isn't exactly the same situation as reported above but they probably need to be fixed together, in roughly the same spot in the code.
