### ISSUE TITLE
Authentication failed after node was set down

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#5878]
Description:
When one of the nodes in the cluster goes down and you are trying to authenticate on another one, there is a chance (more than 50%) that authentication will fail.

Discovered by https://github.com/scylladb/scylla-dtest/pull/1323

Scylla version (or git commit hash):
export SCYLLA_VERSION=unstable/branch-3.3:2020-02-20T01%3A16%3A58Z
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI):
Ubuntu

Repoduction steps:
git clone git@github.com:dkropachev/scylla-dtest.git
cd ./scylla-dtest
git checkout connected_cql_clients
export SCYLLA_VERSION=unstable/branch-3.3:2020-02-20T01%3A16%3A58Z.
/scripts/run_test.sh -v cql_system_clients.py:SystemClientsTest.system_clients_ssl_authentication_test

Result:
======================================================================
ERROR: system_clients_test (cql_system_clients.SystemClientsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/scylladb/scylla-dtest/dkropachev/cql_system_clients.py", line 311, in system_clients_test
    with self.node_session(3, **self._test_users[2]):
  File "/usr/src/scylladb/scylla-dtest/dkropachev/cql_system_clients.py", line 136, in node_session
    ssl_opts=ssl_opts)
  File "/usr/src/scylladb/scylla-dtest/dkropachev/cql_system_clients.py", line 52, in __init__
    protocol_version=protocol_version)
  File "/usr/src/scylladb/scylla-dtest/dkropachev/dtest.py", line 783, in patient_cql_connection
    **kwargs
  File "/usr/src/scylladb/scylla-dtest/dkropachev/dtest.py", line 120, in retry_till_success
    return fun(*args, **kwargs)
  File "/usr/src/scylladb/scylla-dtest/dkropachev/dtest.py", line 706, in cql_connection
    protocol_version, port=port, ssl_opts=ssl_opts, **kwargs)
  File "/usr/src/scylladb/scylla-dtest/dkropachev/dtest.py", line 744, in _create_session
    session = cluster.connect()
  File "cassandra/cluster.py", line 1247, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1283, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1270, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 2773, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 2816, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.4': AuthenticationFailed('Failed to authenticate to 127.0.0.4: Error from server: code=0100 [Bad credentials] message="authentication failed"')})

**Comment by slivne** [comment]
@dkropachev can you please provide

"desc full schema"

and nodetool status

**Comment by eliransin** [comment]
@slivne this is not a regression and it is even a documented behavior.
AFAIK this is a known issue. Our system_auth keyspace is starting with RF=1 which essentially means that after shutting down a node, some of the user credentials for authentication will be unavailable.
Right now what we have in place to overcome that is: https://docs.scylladb.com/operating-scylla/procedures/cluster-management/add_node_to_cluster/#prerequisites (see the NOTE scetion)
And we have an issue which we still didn't close that deals with how to do:  #1796
@roydahan I am not sure how we dealt with it so far but the options I can think of:
1.we add a requires 1796 on the test (which I don't think we should do).
2. we will change the cluster.populate  procedure of ccm to do the replication altering (see link above)
3. We will change the prepare procedure of the test to do the replication altering (see link above)
4. We change the specific test to do the replication altering (link above) 

@slivne / @roydahan what do you think?

**Comment by roydahan** [comment]
I think option 3 is the valid option for the test. (We do the same in SCT).

**Comment by dkropachev** [comment]
Thanks Eliran, Roy.
