### ISSUE TITLE
Wrong count(*) with CL=LOCAL_ONE after repair -pr

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5887]
Regression in the following dtests started in:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/382/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_dc_host_test/
Scylla version bcc464755227898fb67ea77d4b48dd224d3ab5b3

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/383/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_multi_dc_test/
Scylla version 43097854a5e043492cacd19cfced047f35a99a6b

Most recent failure is: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/393/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_dc_host_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/repair_additional_test.py", line 2695, in repair_option_pr_dc_host_test
    return RepairAdditionalBase._repair_option_pr_dc_host_test(self)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/repair_additional_test.py", line 860, in _repair_option_pr_dc_host_test
    self.assert_repair_option_pr_count(count, 1200, 1800)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/repair_additional_test.py", line 675, in assert_repair_option_pr_count
    "expected pr repair to repair between {} to {} rows, but count is {}".format(min_count, max_count, count))
  File "/usr/lib64/python3.7/unittest/case.py", line 722, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : expected pr repair to repair between 1200 to 1800 rows, but count is 795
```

The tests starts a 3-dc cluster, 2 nodes in each dc.
It writes 1000 unique keys on each of node1_1 and node_2 with `ConsistencyLevel.LOCAL_ONE` while all other nodes are stopped.
Then after starting all nodes it runs `nodetool repair -pr -local ks` on node1_1, stops it and checks the number of rows on node1_2 using `SELECT count(*) from cf`.

It expects about 1/6 of the 1000 keys written on node1_1 to reach node1_2 but it fails with a count that is **less than** 1000.  I.e. fewer than the number of keys written to node1_2 initially.

**Comment by bhalevy** [comment]
@asias can you please look into this?

**Comment by asias** [comment]
I will take a look. Thanks.

**Comment by bhalevy** [comment]
Testing with bhalevy/scylla-dtest#1328 at bhalevy/scylla-dtest@0f253ca8bb72743ae2b083bd61dc1ed3a2d0ac0f revealed that there's a discrepancy between the rows returned by `select *` vs. `select count(*)` and the problem is apparently with the `count(*)` query.

I ran the following locally:
```
PRINT_DEBUG=true KEEP_TEST_DIR=true NOSE_PROCESSES=6 SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" CASSANDRA_DIR=~/dev/scylla/build/debug nosetests -s -v --process-timeout=3600 repair_additional_test:RepairAdditionalTest.repair_option_pr{,_{dc_host,multi_dc}}_test
```

And the tests failed as follows:
```
FAIL: repair_option_pr_dc_host_test (repair_additional_test.RepairAdditionalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 2698, in repair_option_pr_dc_host_test
    return RepairAdditionalBase._repair_option_pr_dc_host_test(self)
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 861, in _repair_option_pr_dc_host_test
    self.assert_repair_option_pr_rows(session, 1200, 1800)
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 679, in assert_repair_option_pr_rows
    "count {} must be equal to len(rows)\nrows: {}".format(count, rows))
AssertionError: 740 != 1731 : count 740 must be equal to len(rows)
rows: [Row(key='k2244', c1='value1', c2='value2'), Row(key='k1912', c1='value1', c2='value2'), ...
```

Full output: 
[repair-option-pr.log](https://github.com/scylladb/scylla/files/4243962/repair-option-pr.log)

Cc @eliransin

**Comment by eliransin** [comment]
@dekimir can you please have a look?

**Comment by asias** [comment]
> Testing with [scylladb/scylla-dtest#1328](https://github.com/scylladb/scylla-dtest/pull/1328) at [bhalevy/scylla-dtest@0f253ca](https://github.com/bhalevy/scylla-dtest/commit/0f253ca8bb72743ae2b083bd61dc1ed3a2d0ac0f) revealed that there's a discrepancy between the rows returned by `select *` vs. `select count(*)` and the problem is apparently with the `count(*)` query.

@bhalevy Do you mean select * is correct and as expected but select count(*) is not. The repair itself is fine, we have a problem in the cql query level?

**Comment by bhalevy** [comment]
> > Testing with [scylladb/scylla-dtest#1328](https://github.com/scylladb/scylla-dtest/pull/1328) at [bhalevy/scylla-dtest@0f253ca](https://github.com/bhalevy/scylla-dtest/commit/0f253ca8bb72743ae2b083bd61dc1ed3a2d0ac0f) revealed that there's a discrepancy between the rows returned by `select *` vs. `select count(*)` and the problem is apparently with the `count(*)` query.
> 
> @bhalevy Do you mean select * is correct and as expected but select count(*) is not. The repair itself is fine, we have a problem in the cql query level?

Correct. So it appears.

**Comment by dekimir** [comment]
> Testing with [scylladb/scylla-dtest#1328](https://github.com/scylladb/scylla-dtest/pull/1328) at [bhalevy/scylla-dtest@0f253ca](https://github.com/bhalevy/scylla-dtest/commit/0f253ca8bb72743ae2b083bd61dc1ed3a2d0ac0f) revealed that there's a discrepancy between the rows returned by `select *` vs. `select count(*)` and the problem is apparently with the `count(*)` query.

I cannot reproduce this on my machine:
```
2020-02-28 11:09:01.813488 stopping ccm cluster test at: /home/dejan/.dtest/dtest-3f7tp7js
2020-02-28 11:09:02.863989 Freeing cluster ID 57: link /home/dejan/.dtest/57
repair_option_pr_test (repair_additional_test.RepairAdditionalTest) ... ok
2020-02-28 11:10:28.542616 Checking data on node2
2020-02-28 11:13:01.282564 Checking data on node3
2020-02-28 11:13:25.853948 stopping ccm cluster test at: /home/dejan/.dtest/dtest-o3617ch3
2020-02-28 11:13:26.909823 Freeing cluster ID 2: link /home/dejan/.dtest/2
repair_option_pr_dc_host_test (repair_additional_test.RepairAdditionalTest) ... ok
2020-02-28 11:15:33.710024 Checking data on node4
2020-02-28 11:18:06.364969 Checking data on node5
2020-02-28 11:20:38.930068 Checking data on node6
2020-02-28 11:23:12.039066 stopping ccm cluster test at: /home/dejan/.dtest/dtest-moqc0380
2020-02-28 11:23:13.095430 Freeing cluster ID 27: link /home/dejan/.dtest/27
repair_option_pr_multi_dc_test (repair_additional_test.RepairAdditionalTest) ... ok

----------------------------------------------------------------------
Ran 3 tests in 1082.251s

OK
(env) localhost>cat /tmp/r.sh 
#!/bin/bash
PRINT_DEBUG=true KEEP_TEST_DIR=true NOSE_PROCESSES=6 SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" \
CASSANDRA_DIR=~/src/scylla/build/dev \
           nosetests -s -v --process-timeout=3600 \
           repair_additional_test:RepairAdditionalTest.repair_option_pr{,_{dc_host,multi_dc}}_test
(env) localhost>git log -3 --oneline 
0f253ca8 (HEAD, bhalevy/repair-option-pr) repair_option_pr tests: assert_repair_option_pr_rows: compare count to len(rows)
0bacbced repair_option_pr tests: use cluster.{stop,start}_nodes
a5816052 (origin/manager-2.0) materialized_views_test: _run_node_failure_during_mv_stress_insert: add expected error
(env) localhost>
```

**Comment by dekimir** [comment]
Scratch that, I'm able to reproduce after git pull and rebuild of Scylla.

**Comment by bhalevy** [comment]
> Update: I can reproduce it with the debug Scylla build, though not with the dev build.

@dekimir we see it on Jenkins also only with dtest-debug.
It might be related to yielding in continuations in debug mode.

**Comment by eliransin** [comment]
@dekimir any news?

**Comment by dekimir** [comment]
> @dekimir any news?

Only that it can be reproduced without `repair` and with less than six nodes.  But it still requires three DCs and nodes going up and down.

I'm finding it unexpectedly difficult to make the test pause and let me attach a debugger to a running Scylla.  `nose` does something with stdin that confuses both the `input()` function and `pdb`. :(

**Comment by dekimir** [comment]
Here is the minimum test code that can still reproduce the bug (though not 100% of the time):
```python
self.cluster.set_configuration_options(values={'hinted_handoff_enabled': False})
self.cluster.populate([2,1,1]).start(wait_for_binary_proto=True, wait_other_notice=True)
node1_1, node1_2, node2, node3 = self.cluster.nodelist()
session = self.patient_cql_connection(node1_1)
self.create_ks(session, 'ks', {'dc1': 2, 'dc2': 1, 'dc3': 1})
self.create_cf(session, 'cf', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})

# Insert 1000 keys *only* on node 1, another 1000 keys *only* on node 2
# both in the first data center. The other data centers will be
# completely missing this data:
debug("Adding data only on node 1...")
self.cluster.stop_nodes([node1_2, node2, node3], wait_other_notice=True)
session = self.patient_cql_connection(node1_1, 'ks')
insert_c1c2(session, keys=range(1000, 2000), consistency=ConsistencyLevel.LOCAL_ONE)
self.cluster.flush()
self.assert_count(session)
debug("Adding data only on node 2...")
node1_2.start(wait_other_notice=True, wait_for_binary_proto=True)
node1_1.stop(wait_other_notice=True)
session = self.patient_cql_connection(node1_2, 'ks')
insert_c1c2(session, keys=range(2000, 3000), consistency=ConsistencyLevel.LOCAL_ONE)
self.assert_count(session)

# Bring up all nodes, each node on dc 1 should have different data
# and all the nodes of the two other clusters are empty (but that's
# not important in this case).
debug("Bring back all nodes...")
nn = self.cluster.start_nodes(wait_other_notice=True, wait_for_binary_proto=True)
debug('Started: %r' % [e[1].pid for e in nn])

debug("Stopping node1_2")
node1_2.flush()
node1_2.stop(wait_other_notice=True)

session = self.patient_cql_connection(node1_1, 'ks')
self.assert_count(session)
```

**Comment by dekimir** [comment]
Fascinating: the query response changes over time. :thinking: 

I paused the test right before that last `assert_count()` (the first 2 always pass) and queried node1_1 by hand:

```cql
Connected to test at 127.0.74.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh:ks> SELECT count(*) from cf;

 count
-------
  1000

(1 rows)
cqlsh:ks> SELECT count(*) from cf;

 count
-------
   504

(1 rows)
cqlsh:ks> SELECT count(*) from cf;

 count
-------
   504

(1 rows)
cqlsh:ks> SELECT count(*) from cf;

 count
-------
   504

(1 rows)
cqlsh:ks> SELECT count(*) from cf;

 count
-------
     0

(1 rows)
```

On every run, the first query always returns 1000, regardless of how long I wait before sending it.  The second returns 500+x (for a small value of x) as long as it's sent within a few seconds of the first.  But in time, it always goes down to 0.

**Comment by bhalevy** [comment]
Another data point in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/409/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_dc_host_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/repair_additional_test.py", line 2698, in repair_option_pr_dc_host_test
    return RepairAdditionalBase._repair_option_pr_dc_host_test(self)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/repair_additional_test.py", line 869, in _repair_option_pr_dc_host_test
    self.assert_repair_option_pr_rows(session, 1200, 1800)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/repair_additional_test.py", line 682, in assert_repair_option_pr_rows
    "expected pr repair to repair between {} to {} rows, but count is {}\nrows: {}".format(min_count, max_count, count, rows))
  File "/usr/lib64/python3.7/unittest/case.py", line 722, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : expected pr repair to repair between 1200 to 1800 rows, but count is 732
```

This indicates the count query matches the length of the select query (and both were too low).

**Comment by bhalevy** [comment]
I reproduced locally also with 3.3.rc2-0.20200308.3bed8063f
```
$ rm -rf logs* ~/.dtest/* ; KEEP_LOGS=true PRINT_DEBUG=true KEEP_TEST_DIR=true NOSE_PROCESSES=6 SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" CASSANDRA_DIR=~/dev/scylla-2/build/debug nosetests -s -v --process-timeout=1800 repair_additional_test:RepairAdditionalTest.repair_option_pr_dc_host_test
2020-03-08 09:24:04.107058 going to run tests in parallel
2020-03-08 09:24:04.107157 using the RandomClusterIdAllocator
2020-03-08 09:24:04.145722 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - cluster ccm directory: /local/home/bhalevy/.dtest/dtest-035_y8jn
2020-03-08 09:24:04.145908 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Starting Scylla cluster from directory /local/home/bhalevy/dev/scylla-2/build/debug
2020-03-08 09:24:04.837196 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Allocated cluster ID 60: /local/home/bhalevy/.dtest/dtest-035_y8jn
2020-03-08 09:25:37.611673 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - CREATE COLUMNFAMILY cf (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {} AND read_repair_chance=0.000000
2020-03-08 09:25:55.045765 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Adding data only on node 1...
2020-03-08 09:26:16.818606 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Adding data only on node 2...
2020-03-08 09:27:19.937021 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Bring back all nodes...
2020-03-08 09:30:58.730839 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - [2020-03-08 09:29:42,288] Starting repair command #1, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)
[2020-03-08 09:30:58,399] Repair session 1 
[2020-03-08 09:30:58,400] Repair session 1 finished

2020-03-08 09:30:58.731072 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - 
2020-03-08 09:30:58.731188 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Stopping node1_1
2020-03-08 09:31:27.651903 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Asserting pr repair count: 1556 in [1200..1800]
2020-03-08 09:31:27.653587 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Restarting node1_2
2020-03-08 09:32:17.057144 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Stopping node1_2
2020-03-08 09:32:36.129592 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Asserting pr repair count: 0 in [1200..1800]
2020-03-08 09:32:36.277617 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Test failed with errors: [(<repair_additional_test.RepairAdditionalTest testMethod=repair_option_pr_dc_host_test>, (<class 'AssertionError'>, AssertionError('False is not true : expected pr repair to repair between 1200 to 1800 rows, but count is 0\nrows: []'), <traceback object at 0x7f623869cb90>))]
2020-03-08 09:32:36.295689 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - stopping ccm cluster test at: /local/home/bhalevy/.dtest/dtest-035_y8jn
2020-03-08 09:32:37.370423 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Freeing cluster ID 60: link /local/home/bhalevy/.dtest/60
repair_option_pr_dc_host_test (repair_additional_test.RepairAdditionalTest) ... FAIL

======================================================================
FAIL: repair_option_pr_dc_host_test (repair_additional_test.RepairAdditionalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 2698, in repair_option_pr_dc_host_test
    return RepairAdditionalBase._repair_option_pr_dc_host_test(self)
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 869, in _repair_option_pr_dc_host_test
    self.assert_repair_option_pr_rows(session, 1200, 1800)
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 682, in assert_repair_option_pr_rows
    "expected pr repair to repair between {} to {} rows, but count is {}\nrows: {}".format(min_count, max_count, count, rows))
AssertionError: False is not true : expected pr repair to repair between 1200 to 1800 rows, but count is 0
rows: []
```

**Comment by slivne** [comment]
@bhalevy is this a new failure in 3.3 from when is this nodetool repair test failing

**Comment by slivne** [comment]
@bhalevy please update once you check 3.2 as well

**Comment by bhalevy** [comment]
Reproduced *locally* also with 3.2.3-0.20200308.48253eb18
```
$ rm -rf logs* ~/.dtest/* ; PRINT_DEBUG=true KEEP_TEST_DIR=true NOSE_PROCESSES=6 SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" CASSANDRA_DIR=~/dev/scylla-2/build/debug nosetests -s -v --process-timeout=1800 repair_additional_test:RepairAdditionalTest.repair_option_pr_dc_host_test
2020-03-08 14:30:07.495837 going to run tests in parallel
2020-03-08 14:30:07.495937 using the RandomClusterIdAllocator
2020-03-08 14:30:07.539425 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - cluster ccm directory: /local/home/bhalevy/.dtest/dtest-s9b6l30n
2020-03-08 14:30:07.539631 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Starting Scylla cluster from directory /local/home/bhalevy/dev/scylla-2/build/debug
2020-03-08 14:30:07.544570 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Allocated cluster ID 68: /local/home/bhalevy/.dtest/dtest-s9b6l30n
2020-03-08 14:31:38.885278 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - CREATE COLUMNFAMILY cf (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {} AND read_repair_chance=0.000000
2020-03-08 14:32:09.182100 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Adding data only on node 1...
2020-03-08 14:32:22.575104 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Adding data only on node 2...
2020-03-08 14:33:24.989943 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Bring back all nodes...
2020-03-08 14:36:57.254909 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - [2020-03-08 14:35:46,818] Starting repair command #1, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)
[2020-03-08 14:36:56,928] Repair session 1 
[2020-03-08 14:36:56,928] Repair session 1 finished

2020-03-08 14:36:57.255057 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - 
2020-03-08 14:36:57.255121 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Stopping node1_1
2020-03-08 14:37:19.222918 repair_additional_test.py:RepairAdditionalTest.repair_option_pr_dc_host_test - Test failed with errors: [(<repair_additional_test.RepairAdditionalTest testMethod=repair_option_pr_dc_host_test>, (<class 'AssertionError'>, AssertionError("1513 != 1514 : count 1513 must be equal to len(rows)
```

**Comment by tzach** [comment]
> Reproduced locally also with 3.2.3-0.20200308.48253eb18
So, not a regression of 3.3

**Comment by dekimir** [comment]
The results described below happen with consistency level ONE.  But I noticed that with LOCAL_ONE, the returned count is always 1000, no matter how many times I query.

> Fascinating: the query result changes over time. thinking
> 
> I paused the test right before that last `assert_count()` (the first 2 always pass) and queried node1_1 by hand:
> 
> ```sql
> Connected to test at 127.0.74.1:9042.
> [cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
> Use HELP for help.
> cqlsh:ks> SELECT count(*) from cf;
> 
>  count
> -------
>   1000
> 
> (1 rows)
> cqlsh:ks> SELECT count(*) from cf;
> 
>  count
> -------
>    504
> 
> (1 rows)
> cqlsh:ks> SELECT count(*) from cf;
> 
>  count
> -------
>    504
> 
> (1 rows)
> cqlsh:ks> SELECT count(*) from cf;
> 
>  count
> -------
>    504
> 
> (1 rows)
> cqlsh:ks> SELECT count(*) from cf;
> 
>  count
> -------
>      0
> 
> (1 rows)
> ```
> 
> On every run, the first query always returns 1000, regardless of how long I wait before sending it. The second returns 500+x (for a small value of x) as long as it's sent within a few seconds of the first. But in time, it always goes down to 0.

**Comment by psarna** [comment]
Question: this whole test is based on the idea of repairing a single datacenter and querying with `cl == LOCAL_ONE`, and yet `assert_repair_option_pr_rows()` is called with a default consistency level, i.e. `ONE`. Isn't it a bug? I ran this test 3 times after explicitly changing it to `LOCAL_ONE` by: `self.assert_repair_option_pr_rows(session, 1200, 1800, ConsistencyLevel.LOCAL_ONE)` and it passed each time.

**Comment by bhalevy** [comment]
> Question: this whole test is based on the idea of repairing a single datacenter and querying with `cl == LOCAL_ONE`, and yet `assert_repair_option_pr_rows()` is called with a default consistency level, i.e. `ONE`. Isn't it a bug? I ran this test 3 times after explicitly changing it to `LOCAL_ONE` by: `self.assert_repair_option_pr_rows(session, 1200, 1800, ConsistencyLevel.LOCAL_ONE)` and it passed each time.

It's unintended, it was copied from the original test in scylladb/scylla-dtest@2ffcb2690fdeaff7b73063f37b7b2cac217f4801
but I think you're right and we need to fix the test.

**Comment by eliransin** [comment]
@psarna please push your fix :smile:

**Comment by psarna** [comment]
https://github.com/scylladb/scylla-dtest/pull/1354

**Comment by bhalevy** [comment]
Respective dtest-debug tests now passing with the dtest fix.
Closing this issue.  No need for a fix/backport in scylla.
