### ISSUE TITLE
wide_row_test: AddressSanitizer: negative-size-param: (size=-8) during shutdown

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5888]
Seen in https://jenkins.scylladb.com/view/scylla-3.3/job/scylla-3.3/job/dtest-debug/21/artifact/logs-debug.2/1582502227060_compact_storage_tests.TestCompactStorage.wide_row_test/node1.log
Scylla version 756574d09464b54421f539fac6640313ccbe8189 3.3.rc1-0.20200223.756574d0946 
```
INFO  2020-02-23 23:56:20,563 [shard 0] init - Signal received; shutting down
INFO  2020-02-23 23:56:20,564 [shard 0] init - Shutting down redis service
INFO  2020-02-23 23:56:20,564 [shard 0] init - Shutting down redis service was successful
INFO  2020-02-23 23:56:20,564 [shard 0] init - Shutting down compaction manager
INFO  2020-02-23 23:56:20,564 [shard 0] compaction_manager - Asked to stop
INFO  2020-02-23 23:56:20,565 [shard 0] compaction_manager - Stopped
INFO  2020-02-23 23:56:20,565 [shard 1] compaction_manager - Asked to stop
INFO  2020-02-23 23:56:20,566 [shard 1] compaction_manager - Stopped
INFO  2020-02-23 23:56:20,567 [shard 0] init - Shutting down compaction manager was successful
INFO  2020-02-23 23:56:20,567 [shard 0] init - Shutting down view builder
INFO  2020-02-23 23:56:20,567 [shard 0] view - Stopping view builder
INFO  2020-02-23 23:56:20,567 [shard 1] view - Stopping view builder
INFO  2020-02-23 23:56:20,569 [shard 0] init - Shutting down view builder was successful
INFO  2020-02-23 23:56:20,569 [shard 0] init - Shutting down local storage
INFO  2020-02-23 23:56:20,571 [shard 0] storage_service - Drain on shutdown: starts
INFO  2020-02-23 23:56:20,572 [shard 0] storage_service - Stop transport: starts
INFO  2020-02-23 23:56:20,576 [shard 0] storage_service - Thrift server stopped
INFO  2020-02-23 23:56:20,598 [shard 0] storage_service - CQL server stopped
INFO  2020-02-23 23:56:20,598 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2020-02-23 23:56:20,599 [shard 0] gossip - My status = NORMAL
INFO  2020-02-23 23:56:20,600 [shard 0] gossip - Announcing shutdown
INFO  2020-02-23 23:56:20,610 [shard 0] storage_service - Node 127.0.21.1 state jump to normal
INFO  2020-02-23 23:56:22,724 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2020-02-23 23:56:22,724 [shard 0] gossip - Disable and wait for gossip loop finished
INFO  2020-02-23 23:56:22,726 [shard 0] gossip - Gossip is now stopped
INFO  2020-02-23 23:56:22,726 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2020-02-23 23:56:22,728 [shard 0] storage_service - messaging_service stopped
INFO  2020-02-23 23:56:22,728 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2020-02-23 23:56:22,729 [shard 0] storage_service - stream_manager stopped
INFO  2020-02-23 23:56:22,729 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2020-02-23 23:56:22,732 [shard 0] storage_service - Stop transport: auth shutdown
INFO  2020-02-23 23:56:22,732 [shard 0] storage_service - Stop transport: done
INFO  2020-02-23 23:56:22,732 [shard 0] storage_service - Drain on shutdown: stop_transport done
INFO  2020-02-23 23:56:22,732 [shard 0] tracing - Asked to shut down
INFO  2020-02-23 23:56:22,732 [shard 0] tracing - Tracing is down
INFO  2020-02-23 23:56:22,733 [shard 1] tracing - Asked to shut down
INFO  2020-02-23 23:56:22,733 [shard 1] tracing - Tracing is down
INFO  2020-02-23 23:56:22,737 [shard 0] storage_service - Drain on shutdown: tracing is stopped
INFO  2020-02-23 23:56:22,738 [shard 0] storage_service - Drain on shutdown: system distributed keyspace stopped
INFO  2020-02-23 23:56:22,738 [shard 0] hints_manager - Asked to stop
INFO  2020-02-23 23:56:22,738 [shard 0] hints_manager - Asked to stop
=================================================================
INFO  2020-02-23 23:56:22,739 [shard 0] hints_manager - Stopped
==6935==ERROR: AddressSanitizer: negative-size-param: (size=-8)
INFO  2020-02-23 23:56:22,739 [shard 0] hints_manager - Stopped
    #0 0x7ff4a7a57698 in memmove (/jenkins/workspace/scylla-3.3/dtest-debug/scylla/.ccm/scylla-repository/756574d09464b54421f539fac6640313ccbe8189/scylla//opt/scylladb/libreloc/libasan.so.5+0xa1698)
    #1 0x68a16e1 in service::endpoint_lifecycle_subscriber** std::__copy_move<true, true, std::random_access_iterator_tag>::__copy_m<service::endpoint_lifecycle_subscriber*>(service::endpoint_lifecycle_subscriber* const*, service::endpoint_lifecycle_subscriber* const*, service::endpoint_lifecycle_subscriber**) /usr/include/c++/9/bits/stl_algobase.h:386
    #2 0x685b5b4 in service::endpoint_lifecycle_subscriber** std::__copy_move_a<true, service::endpoint_lifecycle_subscriber**, service::endpoint_lifecycle_subscriber**>(service::endpoint_lifecycle_subscriber**, service::endpoint_lifecycle_subscriber**, service::endpoint_lifecycle_subscriber**) /usr/include/c++/9/bits/stl_algobase.h:404
    #3 0x680e627 in __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > > std::__copy_move_a2<true, __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >, __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > > >(__gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >, __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >, __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >) /usr/include/c++/9/bits/stl_algobase.h:440
    #4 0x67b2b6c in __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > > std::move<__gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >, __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > > >(__gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >, __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >, __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >) /usr/include/c++/9/bits/stl_algobase.h:505
    #5 0x6758ca9 in std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> >::_M_erase(__gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >, __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >) /usr/include/c++/9/bits/vector.tcc:190
    #6 0x6723862 in std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> >::erase(__gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber* const*, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >, __gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber* const*, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >) /usr/include/c++/9/bits/stl_vector.h:1458
    #7 0x64472ac in service::storage_service::unregister_subscriber(service::endpoint_lifecycle_subscriber*) service/storage_service.cc:1383
    #8 0x6448b7a in operator() service/storage_service.cc:1435
    #9 0x657f412 in apply<service::storage_service::drain_on_shutdown()::<lambda(service::storage_service&)>::<lambda()>::<lambda(service::storage_proxy&)>&, service::storage_proxy&> seastar/include/seastar/core/future.hh:1612
    #10 0x653db5d in apply<service::storage_service::drain_on_shutdown()::<lambda(service::storage_service&)>::<lambda()>::<lambda(service::storage_proxy&)>&, service::storage_proxy&> seastar/include/seastar/core/future.hh:1638
    #11 0x64e490d in operator() seastar/include/seastar/core/sharded.hh:688
    #12 0x657f67a in _M_invoke /usr/include/c++/9/bits/std_function.h:286
    #13 0x77dcb6 in std::function<seastar::future<> (service::storage_proxy&)>::operator()(service::storage_proxy&) const /usr/include/c++/9/bits/std_function.h:690
    #14 0x6e73c9 in seastar::sharded<service::storage_proxy>::invoke_on_all(seastar::smp_service_group, std::function<seastar::future<> (service::storage_proxy&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}::operator()() const seastar/include/seastar/core/sharded.hh:654
    #15 0x80156f in seastar::future<> seastar::futurize<seastar::future<> >::apply<seastar::sharded<service::storage_proxy>::invoke_on_all(seastar::smp_service_group, std::function<seastar::future<> (service::storage_proxy&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&>(seastar::sharded<service::storage_proxy>::invoke_on_all(seastar::smp_service_group, std::function<seastar::future<> (service::storage_proxy&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&) seastar/include/seastar/core/future.hh:1655
    #16 0xa246b1 in seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_proxy>::invoke_on_all(seastar::smp_service_group, std::function<seastar::future<> (service::storage_proxy&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::process()::{lambda()#1}::operator()() const seastar/include/seastar/core/smp.hh:194
    #17 0xa95ce3 in seastar::future<> seastar::futurize<seastar::future<> >::apply<seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_proxy>::invoke_on_all(seastar::smp_service_group, std::function<seastar::future<> (service::storage_proxy&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::process()::{lambda()#1}&>(seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_proxy>::invoke_on_all(seastar::smp_service_group, std::function<seastar::future<> (service::storage_proxy&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::process()::{lambda()#1}&) seastar/include/seastar/core/future.hh:1655
    #18 0xa254e4 in auto seastar::with_scheduling_group<seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_proxy>::invoke_on_all(seastar::smp_service_group, std::function<seastar::future<> (service::storage_proxy&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::process()::{lambda()#1}>(seastar::scheduling_group, seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_proxy>::invoke_on_all(seastar::smp_service_group, std::function<seastar::future<> (service::storage_proxy&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::process()::{lambda()#1}) seastar/include/seastar/core/future-util.hh:80
    #19 0xa25bf3 in seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_proxy>::invoke_on_all(seastar::smp_service_group, std::function<seastar::future<> (service::storage_proxy&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::process() seastar/include/seastar/core/smp.hh:186
    #20 0x966ee51 in operator() seastar/src/core/reactor.cc:3083
    #21 0x96b17b3 in process_queue<2, seastar::smp_message_queue::process_incoming()::<lambda(seastar::smp_message_queue::work_item*)> > seastar/src/core/reactor.cc:3054
    #22 0x966eee1 in seastar::smp_message_queue::process_incoming() seastar/src/core/reactor.cc:3082
    #23 0x9681bb8 in seastar::smp::poll_queues() seastar/src/core/reactor.cc:3884
    #24 0x975f87d in seastar::reactor::smp_pollfn::poll() seastar/src/core/reactor.cc:2365
    #25 0x9669406 in seastar::reactor::poll_once() seastar/src/core/reactor.cc:2787
    #26 0x966493d in operator() seastar/src/core/reactor.cc:2680
    #27 0x96ca3e7 in _M_invoke /usr/include/c++/9/bits/std_function.h:285
    #28 0x9797c72 in std::function<bool ()>::operator()() const /usr/include/c++/9/bits/std_function.h:690
    #29 0x9666fad in seastar::reactor::run() seastar/src/core/reactor.cc:2706
    #30 0x967a0d9 in operator() seastar/src/core/reactor.cc:3826
    #31 0x96cb957 in _M_invoke /usr/include/c++/9/bits/std_function.h:300
    #32 0x27aef84 in std::function<void ()>::operator()() const /usr/include/c++/9/bits/std_function.h:690
    #33 0xa260352 in seastar::posix_thread::start_routine(void*) seastar/src/core/posix.cc:52
    #34 0x7ff4a69f24e1 in start_thread (/jenkins/workspace/scylla-3.3/dtest-debug/scylla/.ccm/scylla-repository/756574d09464b54421f539fac6640313ccbe8189/scylla//opt/scylladb/libreloc/libpthread.so.0+0x94e1)
    #35 0x7ff4a5724692 in __GI___clone (/jenkins/workspace/scylla-3.3/dtest-debug/scylla/.ccm/scylla-repository/756574d09464b54421f539fac6640313ccbe8189/scylla//opt/scylladb/libreloc/libc.so.6+0x101692)

0x6030005a89c0 is located 16 bytes inside of 32-byte region [0x6030005a89b0,0x6030005a89d0)
allocated by thread T0 here:
    #0 0x7ff4a7ac59d7 in operator new(unsigned long) (/jenkins/workspace/scylla-3.3/dtest-debug/scylla/.ccm/scylla-repository/756574d09464b54421f539fac6640313ccbe8189/scylla//opt/scylladb/libreloc/libasan.so.5+0x10f9d7)
    #1 0x685b41a in __gnu_cxx::new_allocator<service::endpoint_lifecycle_subscriber*>::allocate(unsigned long, void const*) /usr/include/c++/9/ext/new_allocator.h:114
    #2 0x680e141 in std::allocator_traits<std::allocator<service::endpoint_lifecycle_subscriber*> >::allocate(std::allocator<service::endpoint_lifecycle_subscriber*>&, unsigned long) /usr/include/c++/9/bits/alloc_traits.h:444
    #3 0x67b219b in std::_Vector_base<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> >::_M_allocate(unsigned long) /usr/include/c++/9/bits/stl_vector.h:343
    #4 0x6757804 in void std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> >::_M_realloc_insert<service::endpoint_lifecycle_subscriber*&>(__gnu_cxx::__normal_iterator<service::endpoint_lifecycle_subscriber**, std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> > >, service::endpoint_lifecycle_subscriber*&) /usr/include/c++/9/bits/vector.tcc:440
    #5 0x6723181 in service::endpoint_lifecycle_subscriber*& std::vector<service::endpoint_lifecycle_subscriber*, std::allocator<service::endpoint_lifecycle_subscriber*> >::emplace_back<service::endpoint_lifecycle_subscriber*&>(service::endpoint_lifecycle_subscriber*&) /usr/include/c++/9/bits/vector.tcc:121
    #6 0x6446e56 in service::storage_service::register_subscriber(service::endpoint_lifecycle_subscriber*) service/storage_service.cc:1378
    #7 0x4e14d84 in operator() db/hints/manager.cc:106
    #8 0x4e6ccbe in apply seastar/include/seastar/core/apply.hh:36
    #9 0x4e6cd45 in apply<db::hints::manager::start(seastar::shared_ptr<service::storage_proxy>, seastar::shared_ptr<gms::gossiper>, seastar::shared_ptr<service::storage_service>)::<lambda()>&> seastar/include/seastar/core/apply.hh:44
    #10 0x4e6cdd5 in apply_tuple<db::hints::manager::start(seastar::shared_ptr<service::storage_proxy>, seastar::shared_ptr<gms::gossiper>, seastar::shared_ptr<service::storage_service>)::<lambda()>&> seastar/include/seastar/core/future.hh:1599
    #11 0x4e56a26 in apply<db::hints::manager::start(seastar::shared_ptr<service::storage_proxy>, seastar::shared_ptr<gms::gossiper>, seastar::shared_ptr<service::storage_service>)::<lambda()>&> seastar/include/seastar/core/future.hh:1633
    #12 0x4e4255f in operator() seastar/include/seastar/core/future.hh:1163
    #13 0x4e6d04a in call seastar/include/seastar/util/noncopyable_function.hh:101
    #14 0x70fdbf in seastar::noncopyable_function<seastar::future<> ()>::operator()() const seastar/include/seastar/util/noncopyable_function.hh:184
    #15 0x67a1c6 in seastar::apply_helper<seastar::noncopyable_function<seastar::future<> ()>, std::tuple<>&&, std::integer_sequence<unsigned long> >::apply(seastar::noncopyable_function<seastar::future<> ()>&&, std::tuple<>&&) seastar/include/seastar/core/apply.hh:36
    #16 0x67a2a5 in auto seastar::apply<seastar::noncopyable_function<seastar::future<> ()>>(seastar::noncopyable_function<seastar::future<> ()>&&, std::tuple<>&&) seastar/include/seastar/core/apply.hh:44
    #17 0x67a38c in seastar::future<> seastar::futurize<seastar::future<> >::apply<seastar::noncopyable_function<seastar::future<> ()>>(seastar::noncopyable_function<seastar::future<> ()>&&, std::tuple<>&&) seastar/include/seastar/core/future.hh:1645
    #18 0x5fd0a5 in seastar::future<>::then_impl<seastar::noncopyable_function<seastar::future<> ()>, seastar::future<> >(seastar::noncopyable_function<seastar::future<> ()>&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<>&&)#1}::operator()(seastar::future_state<>) seastar/include/seastar/core/future.hh:1191
    #19 0xa86f1e in seastar::continuation<seastar::future<>::then_impl<seastar::noncopyable_function<seastar::future<> ()>, seastar::future<> >(seastar::noncopyable_function<seastar::future<> ()>&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<>&&)#1}>::run_and_dispose() seastar/include/seastar/core/future.hh:506
    #20 0x965d8fc in seastar::reactor::run_tasks(seastar::reactor::task_queue&) seastar/src/core/reactor.cc:2118
    #21 0x96618ab in seastar::reactor::run_some_tasks() seastar/src/core/reactor.cc:2541
    #22 0x9666a58 in seastar::reactor::run() seastar/src/core/reactor.cc:2686
    #23 0x94cef77 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) seastar/src/core/app-template.cc:199
    #24 0x94ccf9d in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) seastar/src/core/app-template.cc:115
    #25 0x504b89 in main main.cc:476
    #26 0x7ff4a564a1a2 in __libc_start_main (/jenkins/workspace/scylla-3.3/dtest-debug/scylla/.ccm/scylla-repository/756574d09464b54421f539fac6640313ccbe8189/scylla//opt/scylladb/libreloc/libc.so.6+0x271a2)

Thread T1 (reactor-1) created by T0 here:
    #0 0x7ff4a79f0955 in pthread_create (/jenkins/workspace/scylla-3.3/dtest-debug/scylla/.ccm/scylla-repository/756574d09464b54421f539fac6640313ccbe8189/scylla//opt/scylladb/libreloc/libasan.so.5+0x3a955)
    #1 0xa260940 in seastar::posix_thread::posix_thread(seastar::posix_thread::attr, std::function<void ()>) seastar/src/core/posix.cc:87
    #2 0xa2604fa in seastar::posix_thread::posix_thread(std::function<void ()>) seastar/src/core/posix.cc:57
    #3 0x983a929 in void __gnu_cxx::new_allocator<seastar::posix_thread>::construct<seastar::posix_thread, std::function<void ()> >(seastar::posix_thread*, std::function<void ()>&&) /usr/include/c++/9/ext/new_allocator.h:147
    #4 0x97f0afc in void std::allocator_traits<std::allocator<seastar::posix_thread> >::construct<seastar::posix_thread, std::function<void ()> >(std::allocator<seastar::posix_thread>&, seastar::posix_thread*, std::function<void ()>&&) /usr/include/c++/9/bits/alloc_traits.h:484
    #5 0x97f0eed in void std::vector<seastar::posix_thread, std::allocator<seastar::posix_thread> >::_M_realloc_insert<std::function<void ()> >(__gnu_cxx::__normal_iterator<seastar::posix_thread*, std::vector<seastar::posix_thread, std::allocator<seastar::posix_thread> > >, std::function<void ()>&&) /usr/include/c++/9/bits/vector.tcc:449
    #6 0x97a0faf in seastar::posix_thread& std::vector<seastar::posix_thread, std::allocator<seastar::posix_thread> >::emplace_back<std::function<void ()> >(std::function<void ()>&&) /usr/include/c++/9/bits/vector.tcc:121
    #7 0x9677655 in seastar::smp::create_thread(std::function<void ()>) seastar/src/core/reactor.cc:3390
    #8 0x967f804 in seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config) seastar/src/core/reactor.cc:3796
    #9 0x94cea73 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) seastar/src/core/app-template.cc:175
    #10 0x94ccf9d in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) seastar/src/core/app-template.cc:115
    #11 0x504b89 in main main.cc:476
    #12 0x7ff4a564a1a2 in __libc_start_main (/jenkins/workspace/scylla-3.3/dtest-debug/scylla/.ccm/scylla-repository/756574d09464b54421f539fac6640313ccbe8189/scylla//opt/scylladb/libreloc/libc.so.6+0x271a2)

SUMMARY: AddressSanitizer: negative-size-param (/jenkins/workspace/scylla-3.3/dtest-debug/scylla/.ccm/scylla-repository/756574d09464b54421f539fac6640313ccbe8189/scylla//opt/scylladb/libreloc/libasan.so.5+0xa1698) in memmove
==6935==ABORTING
```

Core dump [here](https://jenkins.scylladb.com/view/scylla-3.3/job/scylla-3.3/job/dtest-debug/21/artifact/logs-debug.2/1582502227060_compact_storage_tests.TestCompactStorage.wide_row_test/node1-reactor-1.6935.1582502184.core.gz)
Reloc package on [jenkins](https://jenkins.scylladb.com/view/scylla-3.3/job/scylla-3.3/job/build/33/artifact/scylla/build/debug/scylla-package.tar.gz) or on [s3](http://downloads.scylladb.com/relocatable/unstable/branch-3.3/2020-02-23T20:29:05Z/scylla-debug-package.tar.gz)

**Comment by bhalevy** [comment]
Duplicate of #5385
