### ISSUE TITLE
missing key in test_filtering_MV_new_primary

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5928]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/407/testReport/like_operator_test/TestLikeOperatorForMV/test_filtering_MV_new_primary/
Scylla version 134d5a5f7530861f15ba67aaecdb6e57cd1647ed

```
Error Message
Expected [['ytrewq0', 'qwerty0'], ['ytrewq1', 'qwerty1'], ['ytrewq2', 'qwerty2'], ['ytrewq3', 'qwerty3'], ['ytrewq4', 'qwerty4']] from SELECT * FROM building_by_city WHERE city LIKE 'y%' ALLOW FILTERING, but got [['ytrewq0', 'qwerty0'], ['ytrewq1', 'qwerty1'], ['ytrewq2', 'qwerty2'], ['ytrewq3', 'qwerty3']]
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/like_operator_test.py", line 2096, in test_filtering_MV_new_primary
    ignore_order=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1261, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 89, in assert_all
    assert list_res == expected, "Expected %s from %s, but got %s" % (expected, query, list_res)
AssertionError: Expected [['ytrewq0', 'qwerty0'], ['ytrewq1', 'qwerty1'], ['ytrewq2', 'qwerty2'], ['ytrewq3', 'qwerty3'], ['ytrewq4', 'qwerty4']] from SELECT * FROM building_by_city WHERE city LIKE 'y%' ALLOW FILTERING, but got [['ytrewq0', 'qwerty0'], ['ytrewq1', 'qwerty1'], ['ytrewq2', 'qwerty2'], ['ytrewq3', 'qwerty3']]
```

It's quite rare but reproducible (about 1 out of 20 runs)

**Comment by bhalevy** [comment]
@eliransin fyi

**Comment by psarna** [comment]
@bhalevy, @aleksbykov (I see from git blame you wrote the tests:) ) it's just an issue with a test which reads from materialized views and doesn't take into account that their consistency is eventual. When reading from materialized views and asserting results, one needs to use some kind of a retry mechanism. Materialized view dtests have a bunch of `eventually` functions for that, you can grep for `git grep eventually materialized_views_test.py` for some usage examples.

**Comment by bhalevy** [comment]
Closing scylla issue as the problem is in the test.
