### ISSUE TITLE
add_dc_after_mv_network_replication_test: Startup failed: std::runtime_error (bootstrap_with_repair: keyspace=ks, range=(9203054051880214880, 9220371454731773857], no existing node in local dc)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5929]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/407/testReport/materialized_views_test/TestMaterializedViews/add_dc_after_mv_network_replication_test/
Scylla version 134d5a5f7530861f15ba67aaecdb6e57cd1647ed
(I assume this was introduced in 956b092012c64432b181b3960f5efebad1fbc3be `Merge "Repair based node operation" from Asias`)
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 1311, in add_dc_after_mv_network_replication_test
    self._add_dc_after_mv_test({'dc1': 1, 'dc2': 1})
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 1206, in _add_dc_after_mv_test
    node4.start(wait_other_notice=True, wait_for_binary_proto=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 508, in start
    ext_env)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 253, in _start_scylla
    self.wait_for_binary_interface(from_mark=self.mark, process=self._process_scylla)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 494, in wait_for_binary_interface
    self.watch_log_for("Starting listening for CQL clients", **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 460, in watch_log_for
    raise RuntimeError("The process is dead, returncode={}".format(process.returncode))
RuntimeError: The process is dead, returncode=1
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/407/artifact/logs-release.2/1582993949776_materialized_views_test.TestMaterializedViews.add_dc_after_mv_network_replication_test/node4.log
```
INFO  2020-02-29 16:32:29,607 [shard 0] storage_service - JOINING: Starting to bootstrap...
INFO  2020-02-29 16:32:29,608 [shard 0] repair - bootstrap_with_repair: started with keyspaces={ks, system_auth, system_traces, system_distributed}
INFO  2020-02-29 16:32:29,619 [shard 0] repair - bootstrap_with_repair: started with keyspace=ks, nr_ranges=1025
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down gossiping
INFO  2020-02-29 16:32:29,620 [shard 0] gossip - My status = BOOT
WARN  2020-02-29 16:32:29,620 [shard 0] gossip - No local state or state is in silent shutdown, not announcing shutdown
INFO  2020-02-29 16:32:29,620 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2020-02-29 16:32:29,620 [shard 0] gossip - Disable and wait for gossip loop finished
INFO  2020-02-29 16:32:29,620 [shard 0] gossip - Gossip is now stopped
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down gossiping was successful
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down storage service notifications
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down storage service notifications was successful
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down repair service
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down repair service was successful
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down cdc
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down cdc was successful
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down migration manager
INFO  2020-02-29 16:32:29,620 [shard 0] migration_manager - stopping migration service
INFO  2020-02-29 16:32:29,620 [shard 1] migration_manager - stopping migration service
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down migration manager was successful
INFO  2020-02-29 16:32:29,620 [shard 0] init - Shutting down database
INFO  2020-02-29 16:32:29,620 [shard 0] compaction_manager - Asked to stop
INFO  2020-02-29 16:32:29,621 [shard 0] compaction_manager - Stopped
INFO  2020-02-29 16:32:29,621 [shard 1] compaction_manager - Asked to stop
INFO  2020-02-29 16:32:29,621 [shard 1] compaction_manager - Stopped
INFO  2020-02-29 16:32:29,712 [shard 0] init - Shutting down database: waiting for background jobs...
INFO  2020-02-29 16:32:29,712 [shard 0] init - Shutting down database was successful
INFO  2020-02-29 16:32:29,712 [shard 0] init - Shutting down migration manager notifier
INFO  2020-02-29 16:32:29,712 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2020-02-29 16:32:29,712 [shard 0] init - Shutting down token metadata
INFO  2020-02-29 16:32:29,714 [shard 0] init - Shutting down token metadata was successful
INFO  2020-02-29 16:32:29,714 [shard 0] init - Shutting down prometheus API server
INFO  2020-02-29 16:32:29,715 [shard 0] init - Shutting down prometheus API server was successful
INFO  2020-02-29 16:32:29,715 [shard 0] init - Shutting down sighup
INFO  2020-02-29 16:32:29,715 [shard 0] init - Shutting down sighup was successful
INFO  2020-02-29 16:32:29,715 [shard 0] init - Startup failed: std::runtime_error (bootstrap_with_repair: keyspace=ks, range=(9203054051880214880, 9220371454731773857], no existing node in local dc)
```

**Comment by bhalevy** [comment]
@asias please look into this

**Comment by asias** [comment]
I am able to reproduce. 
The problem is:

n1, n2, n3 added to the cluster in dc1
keyspace ks is created with RF = {dc1:1, dc2:1}
n3 is added to dc2, when n3 bootstraps, n3 can not find any node in the dc2. 

The test is trying to add a new dc not following the supported procedure. https://docs.scylladb.com/operating-scylla/procedures/cluster-management/add_dc_to_exist_dc/

Before repair based node ops, we are not strict about this so the test passed. Now the check is more strict in the code, so the test failed. 

With the following patch, the test passes. I am not 100% sure which is better: to fallback or to reject the bootstrap. If we choose fallback to remote DC(s), should we stream from one of the remote DCs or more of them, which DC(s) to choose? 

```
commit 27372c29bfa18db2d383f5dd9ba9216fd63ac267 (HEAD -> repair_fix_5929)
Author: Asias He <asias@scylladb.com>
Date:   Mon Mar 2 11:06:38 2020 +0800

    repair: Fallback to nodes in remote DCs to bootstrap

diff --git a/repair/repair.cc b/repair/repair.cc
index f7d3f8470..b9cbd2028 100644
--- a/repair/repair.cc
+++ b/repair/repair.cc
@@ -1654,6 +1654,13 @@ future<> bootstrap_with_repair(seastar::sharded<database>& db, locator::token_me
                                 })
                             );
                         };
+                        auto get_old_endpoints_in_remote_dc = [&] () {
+                            return boost::copy_range<std::vector<gms::inet_address>>(old_endpoints |
+                                boost::adaptors::filtered([&] (const gms::inet_address& node) {
+                                    return snitch_ptr->get_datacenter(node) != local_dc;
+                                })
+                            );
+                        };
                         auto old_endpoints_in_local_dc = get_old_endpoints_in_local_dc();
                         auto rf_in_local_dc = get_rf_in_local_dc();
                         if (old_endpoints.size() == strat.get_replication_factor()) {
@@ -1671,10 +1678,16 @@ future<> bootstrap_with_repair(seastar::sharded<database>& db, locator::token_me
                                 mandatory_neighbors = get_node_losing_the_ranges(old_endpoints_in_local_dc, new_endpoints);
                                 neighbors = mandatory_neighbors;
                             } else if (old_endpoints_in_local_dc.size() == 0) {
+                                auto old_endpoints_in_remote_dc = get_old_endpoints_in_remote_dc();
+                                neighbors = old_endpoints_in_remote_dc;
+                                rlogger.warn("bootstrap_with_repair: keyspace={}, range={}, old_endpoints_in_local_dc={}, old_endpoints_in_remote_dc={}, no existing node in local dc, fallback to bootstrap from nodes in other DCs",
+                                        keyspace_name, desired_range, old_endpoints_in_local_dc, old_endpoints_in_remote_dc);
+#if 0
                                 // Local DC has zero replica node.
                                 // Reject the operation
                                 throw std::runtime_error(format("bootstrap_with_repair: keyspace={}, range={}, no existing node in local dc",
                                         keyspace_name, desired_range));
+#endif
                             } else if (old_endpoints_in_local_dc.size() < rf_in_local_dc) {
                                 // Local DC does not have enough replica nodes.
                                 // For example, with RF = 3, 2 nodes n1, n2 in the
```

**Comment by bhalevy** [comment]
> n3 is added to dc2, when n3 bootstraps, n3 can not find any node in the dc2.

@asias, you mean `n4`?

**Comment by asias** [comment]
> > n3 is added to dc2, when n3 bootstraps, n3 can not find any node in the dc2.
> 
> @asias, you mean `n4`?

Yes, I modified the comments to avoid new readers.

**Comment by asias** [comment]
I sent PR: https://github.com/scylladb/scylla-dtest/pull/1338 to fix dtest.
