### ISSUE TITLE
allocation failures with 660M per core.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#596]
When I run scylla on c3.8xlarge instance with 64G memory everything seams to be OK, but if I limit memory to 20G things starts to fail pretty quickly with std::bad_alloc. I am using two loaders with -rate
threads=1000 and CL=ONE.

**Comment by gleb-cloudius** [comment]
I am running 3 node cluster with RF=3

**Comment by slivne** [comment]
will try to reproduce

**Comment by dorlaor** [comment]
Progress?

**Comment by slivne** [comment]
With AMI 0.15 it does not replicate the exact case but it does crash.

start a cluster of 3 nodes using the AMI with reflector (on c3.8xlarge)
stop the services
edit /etc/sysconfig/scylla-server setting args to have --memory 20G
start the scylla-service
to make sure we do not have an issue with c-s and jmx I stopped the jmx prior to running the load

start 2 loaders with 0.15 AMI on c3.8x stop the scylla-server on each loader run the following

```
cassandra-stress write duration=12h cl=one -mode cql3 native -schema replication(factor=3) keyspace=test1 -node XXXX -rate threads=1000
```

after a few minutes I got a core

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fd7ae7509c8 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install boost-filesystem-1.57.0-6.fc22.x86_64 boost-program-options-1.57.0-6.fc22.x86_64 boost-system-1.57.0-6.fc22.x86_64 boost-test-1.57.0-6.fc22.x86_64 boost-thread-1.57.0-6.fc22.x86_64 cryptopp-5.6.2-9.fc22.x86_64 glibc-2.21-8.fc22.x86_64 gmp-6.0.0-9.fc22.x86_64 gnutls-3.3.19-1.fc22.x86_64 gnutls-c++-3.3.19-1.fc22.x86_64 hwloc-libs-1.11.0-4.fc22.x86_64 jsoncpp-0.6.0-0.14.rc2.fc22.x86_64 keyutils-libs-1.5.9-4.fc22.x86_64 krb5-libs-1.13.2-10.fc22.x86_64 libaio-0.3.110-4.fc22.x86_64 libcom_err-1.42.12-4.fc22.x86_64 libffi-3.1-7.fc22.x86_64 libgcc-5.3.1-2.fc22.x86_64 libpciaccess-0.13.3-0.3.fc22.x86_64 libselinux-2.3-10.fc22.x86_64 libstdc++-5.3.1-2.fc22.x86_64 libtasn1-4.5-1.fc22.x86_64 libtool-ltdl-2.4.2-35.fc22.x86_64 libxml2-2.9.3-1.fc22.x86_64 lz4-r131-1.fc22.x86_64 nettle-2.7.1-5.fc22.x86_64 numactl-libs-2.0.10-2.fc22.x86_64 openssl-libs-1.0.1k-13.fc22.x86_64 p11-kit-0.23.1-2.fc22.x86_64 pcre-8.38-1.fc22.x86_64 snappy-1.1.1-3.fc22.x86_64 thrift-0.9.1-13.fc22.3.x86_64 trousers-0.3.13-3.fc22.x86_64 xz-libs-5.2.0-2.fc22.x86_64 yaml-cpp-0.5.1-6.fc22.x86_64 zlib-1.2.8-7.fc22.x86_64
(gdb) where
#0  0x00007fd7ae7509c8 in raise () from /lib64/libc.so.6
#1  0x00007fd7ae75265a in abort () from /lib64/libc.so.6
#2  0x0000000000d4c345 in then_wrapped<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>; StopCondition = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>&]::<lambda(std::result_of_t<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>()>)>, future<> > (func=<optimized out>, this=<optimized out>)
    at /usr/src/debug/scylla-server-0.15/seastar/core/future.hh:887
#3  do_until_continued<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>, rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>&>(rpc::protocol<net::serializer, net::messaging_verb>::server::connection::<lambda(rpc::negotiation_frame)>::<lambda()> &, <unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0xbac2681, DIE 0xbff34ca>, promise<>) (stop_cond=..., 
    action=action@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0xbac2681, DIE 0xbff34ca>, p=...) at /usr/src/debug/scylla-server-0.15/seastar/core/future-util.hh:148
#4  0x0000000000d4ca32 in operator() (fut=..., __closure=<optimized out>) at /usr/src/debug/scylla-server-0.15/seastar/core/future-util.hh:151
#5  do_void_futurize_apply<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>; StopCondition = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>&]::<lambda(std::result_of_t<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>()>)>, future<> >(<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0xbac2681, DIE 0xc2fdaf7>) (
    func=func@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0xbac2681, DIE 0xc2fdaf7>) at /usr/src/debug/scylla-server-0.15/seastar/core/future.hh:1138
#6  0x0000000000d4cbb6 in apply<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>; StopCondition = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>&]::<lambda(std::result_of_t<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>()>)>, future<> > (func=<optimized out>) at /usr/src/debug/scylla-server-0.15/seastar/core/future.hh:1186
#7  operator()<future_state<> > (state=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0xbac2681, DIE 0xbff4612>, __closure=0x613027ff4070)
    at /usr/src/debug/scylla-server-0.15/seastar/core/future.hh:881
#8  continuation<future<T>::then_wrapped(Func&&) [with Func = do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>; StopCondition = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>&]::<lambda(std::result_of_t<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda(rpc::negotiation_frame)> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>()>)>; Result = future<>; T = {}]::<lambda(auto:2&&)> >::run(void) (this=0x613027ff4060)
    at /usr/src/debug/scylla-server-0.15/seastar/core/future.hh:399
#9  0x000000000047793d in reactor::run_tasks (this=this@entry=0x613000111000, tasks=...) at core/reactor.cc:1318
#10 0x00000000004a1d6b in reactor::run (this=0x613000111000) at core/reactor.cc:1622
#11 0x00000000004c206f in smp::<lambda()>::operator()(void) const (__closure=0x6000000ccf00) at core/reactor.cc:2377
#12 0x000000000047470e in operator() (this=<optimized out>) at /usr/include/c++/5.3.1/functional:2271
#13 dpdk_thread_adaptor (f=<optimized out>) at core/reactor.cc:2207
#14 0x000000000067530b in eal_thread_loop ()
#15 0x00007fd7aeae3555 in start_thread () from /lib64/libpthread.so.0
#16 0x00007fd7ae81eb9d in clone () from /lib64/libc.so.6
```

I copied the core on the machine to /core.scylla-2016-01-12-20:11:41-1588 as the coredump volume in 15 is on the ephemeral drives

@avikivity I provided you access to the machine (i-383363b9, sl-0.15-596-cl-3)

**Comment by gleb-cloudius** [comment]
On Tue, Jan 12, 2016 at 12:38:01PM -0800, slivne wrote:
> With AMI 0.15 it does not replicate the exact case but it does crash.
> 
It is the exact case. The crash is due to oom.

--
			Gleb.

**Comment by avikivity** [comment]
Most of the memory is in small objects:

```
   40   4096     901071     36188160   0.0
   48   4096      22233      1073152   0.2
   56   4096    1844456    103493632   0.0
   64   4096      23455      1503232   0.1
   80   4096      22788      1830912   0.0
   96   4096    3622414    353271808   0.0
  112   4096     922425    104960000   0.0
```

Note the 1:2:4:1 pattern for objects of size 40, 56, 96, and 112 bytes.

**Comment by avikivity** [comment]
Here are the vtables of the 96-byte object found in 0x61300335f000 (count symbol):

```
     11 _ZTV12continuationIZN6futureIJEE12then_wrappedIZN3net12send_messageIN3rpc12no_wait_typeEJjmEEEDaPNS3_17messaging_serviceENS3_14messaging_verbENS3_8shard_idEDpOT0_EUlOT_E_S1_EET0_SF_EUlSF_E_JEE + 16 in section .rodata of /usr/bin/scylla
     11 _ZTV12continuationIZN6futureIJEE12then_wrappedIZNS1_7finallyIZZN3rpc11send_helperIN3net10serializerENS6_14messaging_verbENS4_12no_wait_typeEJjmEEEDaT0_NS4_9signatureIFT1_DpT2_EEEEN7shelper4sendERNS4_8protocolIS7_S8_E6clientENSt12experimental15fundamentals_v18optionalINSt6chrono10time_pointINSP_3_V212steady_clockENSP_8durationIlSt5ratioILl1ELl1000000000EEEEEEEERKjRKmEUlvE0_EES1_OT_EUlS1_E_S1_EESA_S15_EUlS15_E_JEE + 16 in section .rodata of /usr/bin/scylla
      9 _ZTV12continuationIZN6futureIJEE4thenIZZN3rpc11send_helperIN3net10serializerENS5_14messaging_verbENS3_12no_wait_typeEJjmEEEDaT0_NS3_9signatureIFT1_DpT2_EEEEN7shelper4sendERNS3_8protocolIS6_S7_E6clientENSt12experimental15fundamentals_v18optionalINSt6chrono10time_pointINSO_3_V212steady_clockENSO_8durationIlSt5ratioILl1ELl1000000000EEEEEEEERKjRKmEUlvE_S1_EES9_OT_EUlS14_E_JEE + 16 in section .rodata of /usr/bin/scylla
     11 _ZTV12continuationIZN6futureIJSt5tupleIJS0_IJEES2_EEEE4thenIZZN3rpc11send_helperIN3net10serializerENS8_14messaging_verbENS6_12no_wait_typeEJjmEEEDaT0_NS6_9signatureIFT1_DpT2_EEEEN7shelper4sendERNS6_8protocolIS9_SA_E6clientENSt12experimental15fundamentals_v18optionalINSt6chrono10time_pointINSR_3_V212steady_clockENSR_8durationIlSt5ratioILl1ELl1000000000EEEEEEEERKjRKmEUlT_E1_S2_EESC_OS15_EUlS17_E_JS3_EE + 16 in section .rodata of /usr/bin/scylla
```

**Comment by avikivity** [comment]
Note 96 byte objects occur 4 times as often as the others, and we have 4 different types.

**Comment by avikivity** [comment]
112-sized objects appear to be some kind of reference-counted payload:

```
0x613003bc6230:	0x0000000000000001	0x0000000000000000
0x613003bc6240:	0x0000000000000002	0x0000613003bcb518
0x613003bc6250:	0x0000000000000001	0x0000000000000000
0x613003bc6260:	0x0000000000000001	0x0000613000000002
0x613003bc6270:	0x0000000000000000	0x0000000000000001
0x613003bc6280:	0x0000000000000000	0x0000613003bcf248
0x613003bc6290:	0x0000613003bcf240	0x0000000000000014

```

**Comment by avikivity** [comment]
56-sized objects @  0x613003bd5000:

```
      1 vtable for continuation<future<> future<>::then_wrapped<future<> future<>::handle_exception<service::storage_proxy::init_messaging_service()::{lambda(frozen_mutation, std::vector<gms::inet_address, std::allocator<gms::inet_address> >, gms::inet_address, unsigned int, unsigned long)#3}::operator()(frozen_mutation, std::vector<gms::inet_address, std::allocator<gms::inet_address> >, gms::inet_address, unsigned int, unsigned long) const::{lambda(frozen_mutation const&, shared_ptr<service::storage_proxy>&)#1}::operator()(frozen_mutation const, shared_ptr<service::storage_proxy>) const::{lambda(std::__exception_ptr::exception_ptr)#3}>(service::storage_proxy::init_messaging_service()::{lambda(frozen_mutation, std::vector<gms::inet_address, std::allocator<gms::inet_address> >, gms::inet_address, unsigned int, unsigned long)#3}::operator()(frozen_mutation, std::vector<gms::inet_address, std::allocator<gms::inet_address> >, gms::inet_address, unsigned int, unsigned long) const::{lambda(frozen_mutation const&, shared_ptr<service::storage_proxy>&)#1}::operator()(frozen_mutation const, shared_ptr<service::storage_proxy>) const::{lambda(std::__exception_ptr::exception_ptr)#3}&&)::{lambda({lambda(std::__exception_ptr::exception_ptr)#3})#1}, future<> >({lambda(std::__exception_ptr::exception_ptr)#3})::{lambda({lambda(std::__exception_ptr::exception_ptr)#3})#1}> + 16 in section .rodata of /usr/bin/scylla
     35 vtable for continuation<future<> future<>::then_wrapped<service::storage_proxy::init_messaging_service()::{lambda(frozen_mutation, std::vector<gms::inet_address, std::allocator<gms::inet_address> >, gms::inet_address, unsigned int, unsigned long)#3}::operator()(frozen_mutation, std::vector<gms::inet_address, std::allocator<gms::inet_address> >, gms::inet_address, unsigned int, unsigned long) const::{lambda(frozen_mutation const&, shared_ptr<service::storage_proxy>&)#1}::operator()(frozen_mutation const, shared_ptr<service::storage_proxy>) const::{lambda()#2}::operator()() const::{lambda(future<>)#1}, future<> >(service::storage_proxy::init_messaging_service()::{lambda(frozen_mutation, std::vector<gms::inet_address, std::allocator<gms::inet_address> >, gms::inet_address, unsigned int, unsigned long)#3}::operator()(frozen_mutation, std::vector<gms::inet_address, std::allocator<gms::inet_address> >, gms::inet_address, unsigned int, unsigned long) const::{lambda(frozen_mutation const&, shared_ptr<service::storage_proxy>&)#1}::operator()(frozen_mutation const, shared_ptr<service::storage_proxy>) const::{lambda()#2}::operator()() const::{lambda(future<>)#1}&&)::{lambda({lambda(future<>)#1})#1}> + 16 in section .rodata of /usr/bin/scylla
     37 _ZTV12continuationIZN6futureIJEE12then_wrappedIZN14when_all_stateIJS1_S1_EE4waitILm0EEEivEUlOT_E_S1_EET0_S7_EUlS7_E_JEE + 16 in section .rodata of /usr/bin/scylla
```

**Comment by avikivity** [comment]
These are all part of:

```
    ms.register_mutation([] (frozen_mutation in, std::vector<gms::inet_address> forward, gms::inet_address reply_to, unsigned shard, storage_proxy::response_id_type response_id) {
        do_with(std::move(in), get_local_shared_storage_proxy(), [forward = std::move(forward), reply_to, shard, response_id] (const frozen_mutation& m, shared_ptr<storage_proxy>& p) {
            return when_all(
                // mutate_locally() may throw, putting it into apply() converts exception to a future.
                futurize<void>::apply([&p, &m] {
                    return p->mutate_locally(m);
                }).then([reply_to, shard, response_id] {
                    auto& ms = net::get_local_messaging_service();
                    ms.send_mutation_done(net::messaging_service::msg_addr{reply_to, shard}, shard, response_id).then_wrapped([] (future<> f) {
                        f.ignore_ready_future();
                    });
                    // return void, no need to wait for send to complete
                }).handle_exception([] (std::exception_ptr eptr) {
                    logger.warn("MUTATION verb handler: {}", eptr);
                }),
                parallel_for_each(forward.begin(), forward.end(), [reply_to, shard, response_id, &m, &p] (gms::inet_address forward) {
                    auto& ms = net::get_local_messaging_service();
                    auto timeout = clock_type::now() + std::chrono::milliseconds(p->_db.local().get_config().write_request_timeout_in_ms());
                    return ms.send_mutation(net::messaging_service::msg_addr{forward, 0}, timeout, m, {}, reply_to, shard, response_id).then_wrapped([] (future<> f) {
                        f.ignore_ready_future();
                    });
                })
            );
        }).discard_result();

        return net::messaging_service::no_wait();
    });
```

**Comment by avikivity** [comment]
We have 3 nodes with 30 shards each.  So 89 shards temporarily overwhelmed 1 shard with MUTATION messages, and it exhausted its memory.  The rpc resource control patches (already posted) should help with this.
