### ISSUE TITLE
very long reactor stalls in logalloc::segment_pool::reclaim_segments in debug mode

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5960]
Seen regularly in the following test:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/81/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test/
```
Error Message
05 Mar 2020 04:47:30 [node1] Missing: ['127.0.20.2.* now UP']:
INFO  2020-03-05 04:45:28,161 [shard 0] rpc - clie.....
See system.log for remainder
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 2004, in interrupt_build_process_with_resharding_half_to_max_test
    self._do_resharding_test(str(cpu_count() // 2), str(cpu_count() - 1))
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 2063, in _do_resharding_test
    wait_for_binary_proto=True)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/scylla_node.py", line 508, in start
    ext_env)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/scylla_node.py", line 250, in _start_scylla
    node.watch_log_for_alive(self, from_mark=mark)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/node.py", line 483, in watch_log_for_alive
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/node.py", line 448, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 05 Mar 2020 04:47:30 [node1] Missing: ['127.0.20.2.* now UP']:
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/81/artifact/logs-debug.2/1583383650492_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test/node2.log
```
Reactor stalled for 95014 ms on shard 28.
Backtrace:
  /jenkins/workspace/scylla-master/dtest-debug-random/scylla/.ccm/scylla-repository/325c3e13ebf1e4b295579b7a9c0dddc01a4e4ec0/scylla//opt/scylladb/libreloc/libasan.so.5+0x000000000006ce7f
  0x000000001573f0b4
  0x000000001571d698
  0x00000000155f5d4f
  0x0000000015608677
  0x0000000015604eb4
  0x000000001560501e
  0x0000000015608108
  0x00007efd92f72b1f
  /jenkins/workspace/scylla-master/dtest-debug-random/scylla/.ccm/scylla-repository/325c3e13ebf1e4b295579b7a9c0dddc01a4e4ec0/scylla//opt/scylladb/libreloc/libasan.so.5+0x000000000012794a
  /jenkins/workspace/scylla-master/dtest-debug-random/scylla/.ccm/scylla-repository/325c3e13ebf1e4b295579b7a9c0dddc01a4e4ec0/scylla//opt/scylladb/libreloc/libasan.so.5+0x0000000000029243
  /jenkins/workspace/scylla-master/dtest-debug-random/scylla/.ccm/scylla-repository/325c3e13ebf1e4b295579b7a9c0dddc01a4e4ec0/scylla//opt/scylladb/libreloc/libasan.so.5+0x000000000002497b
  /jenkins/workspace/scylla-master/dtest-debug-random/scylla/.ccm/scylla-repository/325c3e13ebf1e4b295579b7a9c0dddc01a4e4ec0/scylla//opt/scylladb/libreloc/libasan.so.5+0x000000000002cb4e
  /jenkins/workspace/scylla-master/dtest-debug-random/scylla/.ccm/scylla-repository/325c3e13ebf1e4b295579b7a9c0dddc01a4e4ec0/scylla//opt/scylladb/libreloc/libasan.so.5+0x000000000010d828
  0x000000000d62beb6
  0x000000000d62e602
  0x000000000d640306
  0x000000000d65d5f4
  0x000000000d659460
  0x000000000d6639d3
  0x000000001562f40b
  0x00000000156333b9
  0x00000000156387cc
  0x000000001564c30f
  0x000000001569c4f7
  0x000000000e54e89e
  0x0000000015b04162
  /jenkins/workspace/scylla-master/dtest-debug-random/scylla/.ccm/scylla-repository/325c3e13ebf1e4b295579b7a9c0dddc01a4e4ec0/scylla//opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
  /jenkins/workspace/scylla-master/dtest-debug-random/scylla/.ccm/scylla-repository/325c3e13ebf1e4b295579b7a9c0dddc01a4e4ec0/scylla//opt/scylladb/libreloc/libc.so.6+0x00000000001016d2
INFO  2020-03-05 04:47:23,526 [shard 0] init - Scylla version 666.development-0.20200304.325c3e13ebf with build-id cc71a805ce0a55836e76e7ebb62318f5651a533c starting ...
```

Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/debug/seastar/./seastar/include/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at ./build/debug/seastar/./seastar/src/core/reactor.cc:734
seastar::print_with_backtrace(seastar::backtrace_buffer&) at ./build/debug/seastar/./seastar/src/core/reactor.cc:755
seastar::internal::cpu_stall_detector::generate_trace() at ./build/debug/seastar/./seastar/src/core/reactor.cc:1202 (discriminator 1)
seastar::internal::cpu_stall_detector::maybe_report() at ./build/debug/seastar/./seastar/src/core/reactor.cc:1048
seastar::internal::cpu_stall_detector::on_signal() at ./build/debug/seastar/./seastar/src/core/reactor.cc:1062
seastar::reactor::block_notifier(int) at ./build/debug/seastar/./seastar/src/core/reactor.cc:1185
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
logalloc::segment_pool::reclaim_segments(unsigned long) at ./utils/logalloc.cc:756
logalloc::segment_pool::prime(unsigned long, unsigned long) at ./utils/logalloc.cc:905
logalloc::prime_segment_pool(unsigned long, unsigned long)::{lambda()#1}::operator()() const at ./utils/logalloc.cc:2317
seastar::future<> seastar::do_void_futurize_helper<void>::apply<logalloc::prime_segment_pool(unsigned long, unsigned long)::{lambda()#1}&>(logalloc::prime_segment_pool(unsigned long, unsigned long)::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:1589
seastar::future<> seastar::futurize<void>::apply<logalloc::prime_segment_pool(unsigned long, unsigned long)::{lambda()#1}&>(logalloc::prime_segment_pool(unsigned long, unsigned long)::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:1638
seastar::smp_message_queue::async_work_item<logalloc::prime_segment_pool(unsigned long, unsigned long)::{lambda()#1}>::run_and_dispose() at ././seastar/include/seastar/core/smp.hh:208
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/debug/seastar/./seastar/src/core/reactor.cc:2091
seastar::reactor::run_some_tasks() at ./build/debug/seastar/./seastar/src/core/reactor.cc:2506 (discriminator 2)
seastar::reactor::run() at ./build/debug/seastar/./seastar/src/core/reactor.cc:2666
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at ./build/debug/seastar/./seastar/src/core/reactor.cc:3811 (discriminator 3)
std::_Function_handler<void (), seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}>::_M_invoke(std::_Any_data const&) at /usr/include/c++/9/bits/std_function.h:300
std::function<void ()>::operator()() const at /usr/include/c++/9/bits/std_function.h:690
seastar::posix_thread::start_routine(void*) at ./build/debug/seastar/./seastar/src/core/posix.cc:52
```

The test regularly in debug mode.

**Comment by bhalevy** [comment]
Most recent failure in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/196/artifact/logs-debug.2/1592350008744_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test/node1.log

**Comment by avikivity** [comment]
The test should be relaxed to create less data in debug mode. 

debug mode is not well integrated into lsa, so we can expect problems there.
