### ISSUE TITLE
manually created invalid _scylla_cdc_log table caused segfault

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5966]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200210.43097854a5e
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description:

Currently cdc log is recored in same keyspace with a special suffix `_scylla_cdc_log`.
The `_scylla_cdc_log` table should be created by Scylla internal.

In my test, I want to know if Scylla has limit for creating a table with `_scylla_cdc_log` suffix.
The answer is `no limit`.

If I create a valid _scylla_cdc_log table, it works well.
But the invalid _scylla_cdc_log table will cause crash, the invalid _scylla_cdc_log table has invalid columns.

### Question & Suggestion

Currently the _scylla_cdc_log table is deleted automatically when the user's table is deleted. User isn't suggested to delete the table manually. right?

Suggestion:
- So we should deny user to create table with _scylla_cdc_log suffix, at least giving a WARNING.
- When the test table isn't valid, raise error, not segfault.

### Test scenario:

- create keyspace cdc_test
   - CREATE KEYSPACE cdc_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
- create an invalid table manually
- run a c-s workload which will create cdc_test.test_table, and try to fill data into it
    - cassandra-stress user no-warmup profile=/tmp/cdc_profile.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=2

```
cqlsh> CREATE KEYSPACE cdc_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

cqlsh> CREATE TABLE cdc_test.test_table_scylla_cdc_log (    pkid text PRIMARY KEY,
   ...     boy boolean,
   ...     name text,
   ...     number int,
   ...     starttime timestamp,
   ...     users list<int>,
   ...     vage varint,
   ...     value blob,
   ...     vname text,
   ...     weight decimal
   ... );
cqlsh>
```

```
Mar 06 00:14:35 amos-centos8 scylla[11240]:  [shard 0] schema_tables - Creating cdc_test.test_table_scylla_cdc_log id=75f91d20-5f3f-11ea-b4b2-000000000000 version=85d7ab52-a661-306d-8825-fba859a90d38

Mar 06 00:14:53 amos-centos8 scylla[11240]:  [shard 0] schema_tables - Creating cdc_test.test_table id=80997360-5f3f-11ea-b4b2-000000000000 version=e13d153f-a6c6-319d-918a-f
c5ad8518b62

Mar 06 00:14:57 scylla[11240]: Segmentation fault on shard 0.
scylla[11240]: Backtrace:
scylla[11240]: 0x0000000002d2f862
scylla[11240]: 0x0000000002cd167b
scylla[11240]: 0x0000000002cd1975
scylla[11240]: 0x0000000002cd19c0
scylla[11240]: 0x00007fb6ae316b1f
scylla[11240]: 0x0000000000e41f81
scylla[11240]: 0x00000000013881e6
scylla[11240]: 0x00000000013952a5
scylla[11240]: 0x000000000137e8b1
scylla[11240]: 0x0000000002ccd870
scylla[11240]: 0x0000000002ccda7f
scylla[11240]: 0x0000000002d09425
scylla[11240]: 0x0000000002c6af8f
scylla[11240]: 0x0000000002c6c0be
scylla[11240]: 0x0000000000c70520
scylla[11240]: /opt/scylladb/libreloc/libc.so.6+0x00000000000271a2
scylla[11240]: 0x0000000000b9b02d
systemd[1]: scylla-server.service: main process exited, code=dumped, status=11/SEGV
```

### Decode backtrace

```
$ addr2line -Cfpi -e /usr/lib/debug/opt/scylladb/libexec/scylla-666.development-0.20200210.43097854a5e.x86_64.debug 
0x0000000002d2f862
0x0000000002cd167b
0x0000000002cd1975
0x0000000002cd19c0
0x00007fb6ae316b1f
0x0000000000e41f81
0x00000000013881e6
0x00000000013952a5
0x000000000137e8b1
0x0000000002ccd870
0x0000000002ccda7f
0x0000000002d09425
0x0000000002c6af8f
0x0000000002c6c0be
0x0000000000c70520
/opt/scylladb/libreloc/libc.so.6+0x00000000000271a2
0x0000000000b9b02d
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:743
seastar::print_with_backtrace(char const*) at /usr/include/fmt/format.h:1158
sigsegv_action at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3465
 (inlined by) _FUN at ./build/release/seastar/./seastar/src/core/reactor.cc:3461
?? ??:0
mutation::set_cell(clustering_key_prefix const&, column_definition const&, atomic_cell_or_collection&&) at /usr/include/fmt/format.h:1158
cdc::transformer::set_pk_columns(partition_key const&, long, seastar::basic_sstring<signed char, unsigned int, 31u, false>, int, mutation&) const at ./cdc/log.cc:406
cdc::transformer::transform(mutation const&, cql3::untyped_result_set const*) const at ./cdc/log.cc:506 (discriminator 1)
operator() at /usr/include/fmt/format.h:1158
 (inlined by) apply at ././seastar/include/seastar/core/apply.hh:36
 (inlined by) apply<cdc::cdc_service::impl::augment_mutation_call(seastar::lowres_clock::time_point, std::vector<mutation>&&)::<lambda(std::vector<mutation>&, service::query_state&)>::<lambda(int)>::<lambda(seastar::lw_shared_ptr<cql3::untyped_result_set>)>, seastar::lw_shared_ptr<cql3::untyped_result_set> > at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) apply_tuple<cdc::cdc_service::impl::augment_mutation_call(seastar::lowres_clock::time_point, std::vector<mutation>&&)::<lambda(std::vector<mutation>&, service::query_state&)>::<lambda(int)>::<lambda(seastar::lw_shared_ptr<cql3::untyped_result_set>)>, seastar::lw_shared_ptr<cql3::untyped_result_set> > at ././seastar/include/seastar/core/future.hh:1599
 (inlined by) apply<cdc::cdc_service::impl::augment_mutation_call(seastar::lowres_clock::time_point, std::vector<mutation>&&)::<lambda(std::vector<mutation>&, service::query_state&)>::<lambda(int)>::<lambda(seastar::lw_shared_ptr<cql3::untyped_result_set>)>, seastar::lw_shared_ptr<cql3::untyped_result_set> > at ././seastar/include/seastar/core/future.hh:1633
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1191
 (inlined by) run_and_dispose at ././seastar/include/seastar/core/future.hh:506
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2745
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/include/boost/program_options/variables_map.hpp:146
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at /usr/include/boost/program_options/variables_map.hpp:146
main at ./main.cc:485
?? ??:0
_start at ??:?
```

@haaawk

**Comment by amoskong** [comment]
User profile of cassandra-stress:

`AND cdc = {'enabled': true, 'preimage': false}`

[cdc_profile.yaml.txt](https://github.com/scylladb/scylla/files/4295898/cdc_profile.yaml.txt)

**Comment by piodul** [comment]
This is already fixed in master. It was fixed by https://github.com/scylladb/scylla/pull/5724.

When I ran the c-s workload described in the issue, the master version of Scylla correctly refused to create the CDC log table:
```
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot create CDC log table for table cdc_test.test_table because a table of name cdc_test.test_table_scylla_cdc_log already exists
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:49)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
...
```

**Comment by amoskong** [comment]
Hi @piodul 

How about my first suggestion in https://github.com/scylladb/scylla/issues/5966#issue-576625206 ?
- `So we should deny user to create table with _scylla_cdc_log suffix, at least giving a WARNING.`

With latest scylla (666.development-0.20200308.b4b08be0e10), I can't reproduce this segfault.
But I can still create table with _scylla_cdc_log suffix, and the table can't be dropped.

```
cqlsh> desc cdc_test.test_table_scylla_cdc_log ;

CREATE TABLE cdc_test.test_table_scylla_cdc_log (
    pkid text PRIMARY KEY,
    boy boolean,
    name text,
    number int,
    starttime timestamp,
    users list<int>,
    vage varint,
    value blob,
    vname text,
    weight decimal
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh> drop TABLE cdc_test.test_table_scylla_cdc_log ;
ServerError: Can't find a column family test_table in keyspace cdc_test
cqlsh> desc cdc_test.test_table;

'test_table' not found in keyspace 'cdc_test'
cqlsh> 
```

**Comment by piodul** [comment]
@amoskong 

We wanted to allow users to create tables `X_scylla_cdc_log` suffix  if `X` does not exist. We currently check for conflict if somebody tries to create `X` with cdc, or enable cdc for an existing table `X`.

```cql
cqlsh> create keyspace ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> create table ks.test_scylla_cdc_log (pk int primary key);
cqlsh> create table ks.test (pk int primary key) with cdc = {'enabled': true};
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot create CDC log table for table ks.test because a table of name ks.test_scylla_cdc_log already exists"
cqlsh> create table ks.test (pk int primary key);
cqlsh> alter table ks.test with cdc = {'enabled': true};
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot create CDC log table for table ks.test because a table of name ks.test_scylla_cdc_log already exists"
```

It should be possible, to drop `X_scylla_cdc_log` table when `X` table does not exist - this is a bug. I'll prepare a fix shortly.
