### ISSUE TITLE
scylla_setup: CPU scaling setup failed on Amazon Linux 2

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla#5977]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Installation details**
 - Scylla version (or git commit hash): 3.3.rc2 and 666.development-0.20200302.ba536dbc953
 - OS (RHEL/CentOS/Ubuntu/AWS AMI): Amazon Linux 2

**Description**

`scylla_setup` tries to enable `cpupower` service during CPU scaling setup, but Amazon Linux 2 missed `cpupower.service` file despite `cpupower` binary still there.

```
ERROR > CPU scaling setup failed.
ERROR > 
ERROR > Stderr:
ERROR > 
ERROR > subprocess.CalledProcessError: Command '['systemctl', 'cat', 'cpupower.service']' returned non-zero exit status 1.
ERROR > 
ERROR > During handling of the above exception, another exception occurred:
ERROR > 
ERROR > Traceback (most recent call last):
ERROR >   File "/opt/scylladb/scripts/libexec/scylla_cpuscaling_setup", line 66, in <module>
ERROR >     cpupwr = systemd_unit('cpupower.service')
ERROR >   File "/opt/scylladb/scripts/scylla_util.py", line 619, in __init__
ERROR >     raise SystemdException('unit {} not found'.format(unit))
ERROR > scylla_util.SystemdException: unit cpupower.service not found
ERROR > 
```

```
$ find / -name 'cpupower*' 2> /dev/null
/etc/sysconfig/cpupower
/usr/share/locale/cs/LC_MESSAGES/cpupower.mo
/usr/share/locale/pt/LC_MESSAGES/cpupower.mo
/usr/share/locale/de/LC_MESSAGES/cpupower.mo
/usr/share/locale/it/LC_MESSAGES/cpupower.mo
/usr/share/locale/fr/LC_MESSAGES/cpupower.mo
/usr/share/man/man1/cpupower-frequency-set.1.gz
/usr/share/man/man1/cpupower-idle-set.1.gz
/usr/share/man/man1/cpupower-info.1.gz
/usr/share/man/man1/cpupower-idle-info.1.gz
/usr/share/man/man1/cpupower-monitor.1.gz
/usr/share/man/man1/cpupower-frequency-info.1.gz
/usr/share/man/man1/cpupower-set.1.gz
/usr/share/man/man1/cpupower.1.gz
/usr/bin/cpupower
```

**Workaround**

Use `--no-cpuscaling-setup` option.

**Comment by fruch** [comment]
can you check which version of cpupowerutils was installed ?

**Comment by enaydanov** [comment]
> can you check which version of cpupowerutils was installed ?

Amazon Linux 2:

```
$ rpm -qf /usr/bin/cpupower
kernel-tools-4.14.171-136.231.amzn2.x86_64
```

FYI, CentOS 8:

```
$ rpm -qf /usr/lib/systemd/system/cpupower.service
kernel-tools-4.18.0-147.3.1.el8_1.x86_64
```

Amazon removed .service file from its version of the package.

**Comment by avikivity** [comment]
@syuu1228 let's just detect that it fails and skip it in that case.

**Comment by avikivity** [comment]
Amazon Linux 2 support is new, so not backporting.
