### ISSUE TITLE
Node stuck on shutdown in tracing_shutdown_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5985]
Seen most recently in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/410/testReport/cql_tracing_test/TestCqlTracing/tracing_shutdown_test/

(https://github.com/scylladb/scylla/issues/5697 seen too, for reference)

Scylla debug version b4b08be0e10846c1dbb9719af6511014d387c458
build-id 28e7bf7b3ee69cf43c7fd23c576bbe623d1ca27f
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/dtest.py", line 945, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/dtest.py", line 983, in cleanUpCluster
    raise AssertionError("Core file(s) found.{}".format("" if failed else " Marking test as failed."))
AssertionError: Core file(s) found. Marking test as failed.
Standard Output
node2 is still running. Trying to generate coredump using kill(14176, SIGQUIT)...
```

Core dump: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/410/artifact/logs-debug.2/1583724287757_cql_tracing_test.TestCqlTracing.tracing_shutdown_test/node2-scylla.14176.1583724284.core.gz
Scylla package: https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/500/artifact/scylla/build/debug/scylla-package.tar.gz
Or on S3: http://downloads.scylladb.com/relocatable/unstable/master/2020-03-08T22:25:16Z/scylla-debug-package.tar.gz

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/410/artifact/logs-debug.2/1583724287757_cql_tracing_test.TestCqlTracing.tracing_shutdown_test/node2.log
```
INFO  2020-03-09 03:22:37,586 [shard 0] init - Signal received; shutting down
INFO  2020-03-09 03:22:37,586 [shard 0] init - Shutting down redis service
INFO  2020-03-09 03:22:37,587 [shard 0] init - Shutting down redis service was successful
INFO  2020-03-09 03:22:37,587 [shard 0] init - Shutting down compaction manager
INFO  2020-03-09 03:22:37,587 [shard 0] compaction_manager - Asked to stop
INFO  2020-03-09 03:22:37,588 [shard 1] compaction_manager - Asked to stop
INFO  2020-03-09 03:22:37,588 [shard 0] compaction_manager - Stopped
INFO  2020-03-09 03:22:37,588 [shard 1] compaction_manager - Stopped
INFO  2020-03-09 03:22:37,589 [shard 0] init - Shutting down compaction manager was successful
INFO  2020-03-09 03:22:37,589 [shard 0] init - Shutting down view builder
INFO  2020-03-09 03:22:37,589 [shard 0] view - Stopping view builder
INFO  2020-03-09 03:22:37,589 [shard 1] view - Stopping view builder
INFO  2020-03-09 03:22:37,591 [shard 0] init - Shutting down view builder was successful
INFO  2020-03-09 03:22:37,591 [shard 0] init - Shutting down local storage
INFO  2020-03-09 03:22:37,592 [shard 0] storage_service - Drain on shutdown: starts
INFO  2020-03-09 03:22:37,593 [shard 0] storage_service - Stop transport: starts
INFO  2020-03-09 03:22:37,628 [shard 0] storage_service - Thrift server stopped
INFO  2020-03-09 03:22:40,907 [shard 0] cql_server - exception while processing connection: std::nested_exception
INFO  2020-03-09 03:22:40,926 [shard 0] storage_service - CQL server stopped
INFO  2020-03-09 03:22:40,928 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2020-03-09 03:22:40,928 [shard 0] gossip - My status = NORMAL
INFO  2020-03-09 03:22:40,928 [shard 0] gossip - Announcing shutdown
INFO  2020-03-09 03:22:40,964 [shard 0] storage_service - Node 127.0.23.2 state jump to normal
ERROR 2020-03-09 03:22:42,586 [shard 0] seastar - Timer callback failed: seastar::metrics::double_registration (registering metrics twice for metrics: storage_proxy_coordinator_background_replica_writes_failed_remote_node)
...
```

**Comment by bhalevy** [comment]
Still happening regularly...
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/429/artifact/logs-release.2/1584500532732_cql_tracing_test.TestCqlTracing.tracing_shutdown_test/node2.log
```
INFO  2020-03-18 03:00:04,531 [shard 0] init - Signal received; shutting down
INFO  2020-03-18 03:00:04,531 [shard 0] init - Shutting down redis service
INFO  2020-03-18 03:00:04,531 [shard 0] init - Shutting down redis service was successful
INFO  2020-03-18 03:00:04,531 [shard 0] init - Shutting down compaction manager
INFO  2020-03-18 03:00:04,531 [shard 0] compaction_manager - Asked to stop
INFO  2020-03-18 03:00:04,531 [shard 0] compaction_manager - Stopped
INFO  2020-03-18 03:00:04,531 [shard 1] compaction_manager - Asked to stop
INFO  2020-03-18 03:00:04,531 [shard 1] compaction_manager - Stopped
INFO  2020-03-18 03:00:04,532 [shard 0] init - Shutting down compaction manager was successful
INFO  2020-03-18 03:00:04,532 [shard 0] init - Shutting down view builder
INFO  2020-03-18 03:00:04,532 [shard 0] view - Stopping view builder
INFO  2020-03-18 03:00:04,532 [shard 1] view - Stopping view builder
INFO  2020-03-18 03:00:04,534 [shard 0] init - Shutting down view builder was successful
INFO  2020-03-18 03:00:04,534 [shard 0] init - Shutting down local storage
INFO  2020-03-18 03:00:04,534 [shard 0] storage_service - Drain on shutdown: starts
INFO  2020-03-18 03:00:04,534 [shard 0] storage_service - Stop transport: starts
INFO  2020-03-18 03:00:04,538 [shard 0] storage_service - Thrift server stopped
INFO  2020-03-18 03:00:04,543 [shard 0] cql_server - exception while processing connection: std::nested_exception
INFO  2020-03-18 03:00:04,544 [shard 0] storage_service - CQL server stopped
INFO  2020-03-18 03:00:04,544 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2020-03-18 03:00:04,544 [shard 0] gossip - My status = NORMAL
INFO  2020-03-18 03:00:04,544 [shard 0] gossip - Announcing shutdown
INFO  2020-03-18 03:00:04,545 [shard 0] storage_service - Node 127.0.13.2 state jump to normal
INFO  2020-03-18 03:00:06,610 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2020-03-18 03:00:06,610 [shard 0] gossip - Disable and wait for gossip loop finished
INFO  2020-03-18 03:00:06,610 [shard 0] gossip - Gossip is now stopped
INFO  2020-03-18 03:00:06,610 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2020-03-18 03:00:06,611 [shard 0] storage_service - messaging_service stopped
INFO  2020-03-18 03:00:06,611 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2020-03-18 03:00:06,611 [shard 0] storage_service - stream_manager stopped
INFO  2020-03-18 03:00:06,611 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2020-03-18 03:00:06,611 [shard 0] storage_service - Stop transport: auth shutdown
INFO  2020-03-18 03:00:06,611 [shard 0] storage_service - Stop transport: done
INFO  2020-03-18 03:00:06,611 [shard 0] storage_service - Drain on shutdown: stop_transport done
INFO  2020-03-18 03:00:06,611 [shard 0] tracing - Asked to shut down
INFO  2020-03-18 03:00:06,612 [shard 1] tracing - Asked to shut down
INFO  2020-03-18 03:00:06,612 [shard 1] tracing - Tracing is down
INFO  2020-03-18 03:00:06,615 [shard 0] tracing - Tracing is down
ERROR 2020-03-18 03:00:09,532 [shard 0] seastar - Timer callback failed: seastar::metrics::double_registration (registering metrics twice for metrics: storage_proxy_coordinator_background_replica_writes_failed_remote_node)
(and last line repeated...)
```

**Comment by bhalevy** [comment]
Related to #5697

**Comment by xemul** [comment]
Caused by it. The `service/storage_proxy.cc abstract_write_response_handler::timeout_cb()` needs to call `_proxy->remove_response_handler()` at the end waking up the `mutate_begin()`'s waiting on it, but due to an exception inside `++stats().background_replica_writes_failed.get_ep_stat()` it doesn't.

**Comment by xemul** [comment]
The `get_ep_stat()` throws inside `register_metrics_for()`

**Comment by avikivity** [comment]
Backported to 4.0 (4.1+ have it).
