### ISSUE TITLE
 trace data with python-driver can return the trace query

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#6004]
*Installation details*
Scylla version (or git commit hash): 3.2.0
Cluster size: 1 
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker

## Summary

When using `get_query_trace()` something we'll get the query getting the tracing data, inside the tracing data.

```
prepared = self.session.prepare(
            """
            SELECT * FROM cf0 WHERE a=? AND b=?
            """)

bound = prepared.bind(('a', 'b'))
results = self.session.execute(bound, trace = True)

results.get_query_trace()
```

to avoid this issue, I've queried the events on my own:
```
        trace_id = results.response_future.get_query_trace_ids()[0]
        traces = self.session.execute("SELECT * FROM system_traces.events WHERE session_id = %s", (trace_id, ))
        events = [event for event in traces]
        for event in events:
            print(event.thread, event.activity)
```

**Comment by fruch** [comment]
with `scylladb/scylla:3.2.0` i'm reproducing it easily

with `scylladb/scylla-nightly:666.development-202003110720` (latest master) I can't reproduce this issue.

**Comment by vladzcloudius** [comment]
@fruch Could you, please, attach the full result of `get_query_trace()`?

**Comment by fruch** [comment]
Run it again with 3.2.0
```
[root@80a8dccdabba /]# scylla --version
3.2.0-0.20200115.f9b11c9b30
```

this is the results from the python-driver end (`get_query_trace()`)
```
shard 1 Checking bounds
shard 1 Processing a statement
shard 1 Creating read executor for token -8839064797231613815 with all: {172.17.0.5} targets: {172.17.0.5} repair decision: NONE
shard 1 read_data: querying locally
shard 1 Start querying the token range that starts with -8839064797231613815
shard 1 Querying is done
shard 1 Done processing - preparing a result
shard 1 Parsing a statement
shard 1 Processing a statement
shard 1 Creating read executor for token -341682343253147099 with all: {172.17.0.5} targets: {172.17.0.5} repair decision: NONE
shard 1 read_data: querying locally
shard 0 Start querying the token range that starts with -341682343253147099
shard 0 Querying is done
shard 1 Done processing - preparing a result
```

And this is from scylla end (after enabling traces):
```
TRACE 2020-03-12 07:35:29,650 [shard 1] storage_proxy - query preparedtests.cf0 cmd=read_command{cf_id=0c2f39c0-6434-11ea-bd50-000000000001, version=52aa9f02-3647-399e-9bd7-988a28f07ebb, slice={regular_col
s=[0], static_cols=[], rows=[{ckp{000162}}], options=3, cql_format=4, partition_row_limit=4294967295}, limit=4294967295, timestamp=1583998529}, partition_limit=4294967295}, ranges={{{-8839064797231613815, 
pk{000161}}}}, id=118
TRACE 2020-03-12 07:35:29,650 [shard 1] storage_proxy - creating read executor for token -8839064797231613815 with all: {172.17.0.5} targets: {172.17.0.5} rp decision: NONE
TRACE 2020-03-12 07:35:29,650 [shard 1] storage_proxy - query_result id=118, size=77, rows=1, partitions=1
TRACE 2020-03-12 07:35:29,650 [shard 1] query_result - id=118, { result: c="c" a="a" b="b"
 digest: {}, short_read=false }                                                                                                                                                                              
TRACE 2020-03-12 07:35:29,650 [shard 1] storage_proxy - mutate cl=ANY
TRACE 2020-03-12 07:35:29,650 [shard 1] storage_proxy - creating write handler for token: -341682343253147099 natural: {172.17.0.5} pending: {}
TRACE 2020-03-12 07:35:29,650 [shard 1] storage_proxy - creating write handler with live: {172.17.0.5} dead: {}
TRACE 2020-03-12 07:35:29,651 [shard 1] storage_proxy - mutate cl=ANY
TRACE 2020-03-12 07:35:29,651 [shard 1] storage_proxy - creating write handler for token: -341682343253147099 natural: {172.17.0.5} pending: {}
TRACE 2020-03-12 07:35:29,651 [shard 1] storage_proxy - creating write handler with live: {172.17.0.5} dead: {}                                                                                              TRACE 2020-03-12 07:35:29,651 [shard 1] storage_proxy - mutate cl=ANY
TRACE 2020-03-12 07:35:29,651 [shard 1] storage_proxy - creating write handler for token: 1866179479342559300 natural: {172.17.0.5} pending: {}
TRACE 2020-03-12 07:35:29,651 [shard 1] storage_proxy - creating write handler with live: {172.17.0.5} dead: {}
TRACE 2020-03-12 07:35:29,652 [shard 1] query_processor - process: "SELECT * FROM system_traces.sessions WHERE session_id = 0c59a520-6434-11ea-9834-000000000000"                                            TRACE 2020-03-12 07:35:29,652 [shard 1] storage_proxy - query system_traces.sessions cmd=read_command{cf_id=c5e99f16-8677-3914-b17e-960613512345, version=43fd04e0-c386-39e3-8c47-d674c5a84d8d, slice={regul$
r_cols=[0, 1, 2, 3, 4, 5, 6, 7, 8], static_cols=[], rows=[(-inf, +inf)], options=102, cql_format=4, partition_row_limit=4294967295}, limit=5000, timestamp=1583998529}, partition_limit=4294967295}, ranges={{-341682343253147099, pk{00100c59a520643411ea9834000000000000}}}}, id=119
TRACE 2020-03-12 07:35:29,652 [shard 1] storage_proxy - creating read executor for token -341682343253147099 with all: {172.17.0.5} targets: {172.17.0.5} rp decision: NONE
TRACE 2020-03-12 07:35:29,652 [shard 0] storage_proxy - mutate cl=ANY
TRACE 2020-03-12 07:35:29,652 [shard 0] storage_proxy - creating write handler for token: -341682343253147099 natural: {172.17.0.5} pending: {}
TRACE 2020-03-12 07:35:29,652 [shard 0] storage_proxy - creating write handler with live: {172.17.0.5} dead: {}
TRACE 2020-03-12 07:35:29,652 [shard 1] storage_proxy - query_result id=119, size=474, rows=1, partitions=1                                                                                           
TRACE 2020-03-12 07:35:29,652 [shard 1] query_result - id=119, { result: duration="257" parameters="{consistency_level : LOCAL_ONE}, {page_size : 5000}, {param[0] : a}, {param[1] : b}, {query :
            SELECT * FROM cf0 WHERE a=? AND b=?
            }, {serial_consistency_level : SERIAL}" started_at="2020-03-12T07:35:29.650000" coordinator="172.17.0.5" command="QUERY" client="172.17.0.1" request_size="45" response_size="122" request="Execute CQL3 prepared query [f886a33feaa5fad8ff2bf32624dbbf6b]" session_id="0c59a520-6434-11ea-9834-000000000000" 
```

clearly `SELECT * FROM system_traces.sessions WHERE session_id = 0c59a520-6434-11ea-9834-000000000000` shouldn't be in the trace

**Comment by slivne** [comment]
a tcpdump without having compression will clarify how is the fetch of the
tracing data sent.

If the fetch tracing data has the trace bit set then its a driver issue
(and we may have a scylla bug that both session are somehow attached).

If the fetch tracing data doesn't have the trace bit set then its a scylla
issue for sure.

**Comment by fruch** [comment]
tcpdump clearly shows it's a scylla issue (again, I've seen it only in 3.2.0, and not on master)

### Query 
![image](https://user-images.githubusercontent.com/340979/76506306-a4e8ba00-6453-11ea-8076-c5cbcd0f3aec.png)

### Response
![image](https://user-images.githubusercontent.com/340979/76506339-b5993000-6453-11ea-87f4-55d69fc7764c.png)

full tcpdump:
[scylla.port.9042.debug.txt](https://github.com/scylladb/scylla/files/4323316/scylla.port.9042.debug.txt)

**Comment by vladzcloudius** [comment]
#6014 may also be related

**Comment by vladzcloudius** [comment]
@slivne @eliransin This together with #6014 are very serious issues that require an urgent attention. 
It looks like CQL Tracing is broken in 3.2.

@tzach @eyalgutkind FYI

**Comment by slivne** [comment]
@eliransin removing you

@frucj please test with 3.3.rc3 or with 3.1

**Comment by fruch** [comment]
I think I've narrowed it to a branch-3.2 only issue.
*scylladb/scylla:3.1.4* - Can't reproduce the issue
**scylladb/scylla:3.2.0** - Reproduced
**scylladb/scylla:3.2.3** - Reproduced
*scylladb/scylla:3.3.rc2* - Can't reproduce the issue

**Comment by fruch** [comment]
Reproducer:

```bash
# test assumes running with --smp 4
docker run -d -p 8080:8080 -p 9042:9042 scylladb/scylla:3.2.3 --smp 4
# wait for scylla to be up and ready for CQL
docker logs -f [docker id]

# clone the the repo
git clone --single-branch --branch shared_aware git@github.com:fruch/python-driver.git
cd python-driver
python3 -m venv .venv3
source .venv3/bin/activate
pip install -r requirements.txt -r test-requirements.txt

# run the test
EVENT_LOOP_MANAGER=asyncore  USE_CASS_EXTERNAL=true python -m nose tests/integration/standard/test_shard_aware.py
```

failure looks like that:
```
F                                                                                                                                                                                                            
======================================================================                                                                                                                                       
FAIL: Testing that shard aware driver is sending the requests to the correct shards                                                                                                                          
----------------------------------------------------------------------                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                           
  File "/home/fruch/Projects/python-driver/tests/integration/standard/test_shard_aware.py", line 122, in test_all_tracing_coming_one_shard                                                                   
    self.verify_same_shard_in_tracing(results, "shard 0")                                                                                                                                                    
  File "/home/fruch/Projects/python-driver/tests/integration/standard/test_shard_aware.py", line 48, in verify_same_shard_in_tracing                                                                         
    self.assertEqual(event.thread_name, shard_name)                                                                                                                                                          
AssertionError: 'shard 3' != 'shard 0'                                                                                                                                                                       
- shard 3                                                                                                                                                                                                    
?       ^                                                                                             
+ shard 0                                                                                                                                                                                                    
?       ^  
```

the query on token 8497859890784024364 was is of the trace, hence goes to wrong shard. (i.e. the test expects to be only on shard 0) 
```
shard 0 Checking bounds                                                                                                                                                                                      
shard 0 Processing a statement                                                                                                                                                                               
shard 0 Creating read executor for token 2739050094959918959 with all: {172.17.0.8} targets: {172.17.0.8} repair decision: NONE
shard 0 read_data: querying locally                                                                   
shard 0 Start querying the token range that starts with 2739050094959918959                   
shard 0 Querying is done                                                                                                                                                                                     
shard 0 Done processing - preparing a result                                                                                                                                                                 
shard 0 Parsing a statement                                                                                                                                                                                  
shard 0 Processing a statement                                                                                                                                                                               
shard 0 Creating read executor for token 8497859890784024364 with all: {172.17.0.8} targets: {172.17.0.8} repair decision: NONE                                                                              
shard 0 read_data: querying locally
shard 3 Start querying the token range that starts with 8497859890784024364
shard 3 Querying is done
shard 0 Done processing - preparing a result
```

**Comment by vladzcloudius** [comment]
@fruch FYI: https://github.com/scylladb/scylla/issues/6014#issuecomment-601479903

**Comment by slivne** [comment]
@fruch please move and test with 3.3.0 just released.

Close this issue if it's solved.

We have another issue open for tracing on 3.2 being incorrect.

**Comment by fruch** [comment]
I can confirm `3.3.0-0.20200319.7ae2cdf46c7` doesn't have this issue
