### ISSUE TITLE
node2 doesn't start in ttl_is_respected_on_delayed_replication_test, hits: rpc - connection refused

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6023]
Regression since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/420/testReport/ttl_test/TestDistributedTTL/ttl_is_respected_on_delayed_replication_test/
Scylla version c020b4e5e20e7f3b5e8fe0a12271f3adc5449be2

```
Error Message
12 Mar 2020 23:41:28 [node2] Missing: ['Starting listening for CQL clients|storage_service - JOINING: getting bootstrap token']:
Scylla version 666.development-0.20200312.c020b4e5.....
See system.log for remainder

Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/ttl_test.py", line 677, in ttl_is_respected_on_delayed_replication_test
    self.node2.start(wait_for_binary_proto=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 541, in start
    ext_env)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 283, in _start_scylla
    if not self.wait_for_bootstrap_repair(from_mark=self.mark):
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 218, in wait_for_bootstrap_repair
    if not self.watch_log_for("{}|{}".format(starting_message, bootstrap_message), from_mark=from_mark, timeout=timeout, process=process):
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 448, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 12 Mar 2020 23:41:28 [node2] Missing: ['Starting listening for CQL clients|storage_service - JOINING: getting bootstrap token']:
Scylla version 666.development-0.20200312.c020b4e5.....
See system.log for remainder
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/420/artifact/logs-release.2/1584056488113_ttl_test.TestDistributedTTL.ttl_is_respected_on_delayed_replication_test/node2.log
```
Scylla version 666.development-0.20200312.c020b4e5e20 with build-id 3831e521340491bc985227768a26f62117de60a5 starting ...
command used: "/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/bin/scylla --options-file /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/conf/scylla.yaml --log-to-stdout 1 --api-address 127.0.88.2 --collectd-hostname dea9b946e864.node2 --smp 2 --memory 1024M --abort-on-seastar-bad-alloc --abort-on-lsa-bad-alloc=1 --abort-on-internal-error 1 --developer-mode true --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.88.2 --unsafe-bypass-fsync 1"
parsed command line options: [options-file: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/conf/scylla.yaml, log-to-stdout: 1, api-address: 127.0.88.2, collectd-hostname: dea9b946e864.node2, smp: 2, memory: 1024M, abort-on-seastar-bad-alloc, abort-on-lsa-bad-alloc: 1, abort-on-internal-error: 1, developer-mode: true, default-log-level: info, collectd: 0, overprovisioned, prometheus-address: 127.0.88.2, unsafe-bypass-fsync: 1]
INFO  2020-03-12 23:37:24,439 [shard 0] init - installing SIGHUP handler
INFO  2020-03-12 23:37:24,441 [shard 0] init - Scylla version 666.development-0.20200312.c020b4e5e20 with build-id 3831e521340491bc985227768a26f62117de60a5 starting ...

WARN  2020-03-12 23:37:24,441 [shard 0] init - Only 512 MiB per shard; this is below the recommended minimum of 1 GiB/shard; continuing since running in developer mode
INFO  2020-03-12 23:37:24,442 [shard 0] init - starting prometheus API server
INFO  2020-03-12 23:37:24,443 [shard 0] init - starting tokens manager
INFO  2020-03-12 23:37:24,443 [shard 0] init - starting migration manager notifier
INFO  2020-03-12 23:37:24,443 [shard 0] init - creating tracing
INFO  2020-03-12 23:37:24,443 [shard 0] init - creating snitch
INFO  2020-03-12 23:37:24,443 [shard 0] init - determining DNS name
INFO  2020-03-12 23:37:24,443 [shard 0] init - starting API server
INFO  2020-03-12 23:37:24,443 [shard 0] init - Scylla API server listening on 127.0.88.2:10000 ...
INFO  2020-03-12 23:37:24,443 [shard 0] init - initializing storage service
INFO  2020-03-12 23:37:24,443 [shard 0] init - starting per-shard database core
WARN  2020-03-12 23:37:24,445 [shard 0] init - I/O Scheduler is not properly configured! This is a non-supported setup, and performance is expected to be unpredictably bad.
 Reason found: none of --max-io-requests, --io-properties and --io-properties-file are set.
To properly configure the I/O Scheduler, run the scylla_io_setup utility shipped with Scylla.

INFO  2020-03-12 23:37:24,446 [shard 0] init - creating and verifying directories
INFO  2020-03-12 23:37:24,537 [shard 0] database - Populating Keyspace system_schema
INFO  2020-03-12 23:37:24,537 [shard 0] database - Keyspace system_schema: Reading CF computed_columns id=cc7c7069-3740-33c1-92a4-c3de78dbd2c4 version=2b8c4439-de76-31e0-807f-3b7290a975d7
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF view_virtual_columns id=08843b63-45dc-3be2-9798-a0418295cfaa version=c777531c-15f7-326f-8ebe-39fd0265c8c9
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF dropped_columns id=5e7583b5-f3f4-3af1-9a39-b7e1d6f5f11f version=7426bc6c-4c2f-3200-8ad8-4329610ed59a
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF indexes id=0feb57ac-311f-382f-ba6d-9024d305702f version=99c40462-8687-304e-abe3-2bdbef1f25aa
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF functions id=96489b79-80be-3e14-a701-66a0b9159450 version=329ed804-55b3-3eee-ad61-d85317b96097
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF columns id=24101c25-a2ae-3af7-87c1-b40ee1aca33f version=d33236d4-9bdd-3c09-abf0-a0bc5edc2526
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF scylla_tables id=5d912ff1-f759-3665-b2c8-8042ab5103dd version=16b55508-a81a-3b90-9a0d-f58f5f833864
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF tables id=afddfb9d-bc1e-3068-8056-eed6c302ba09 version=b6240810-eeb7-36d5-9411-43b2d68dddab
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF keyspaces id=abac5682-dea6-31c5-b535-b3d6cffd0fb6 version=e79ca8ba-6556-3f7d-925a-7f20cf57938c
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF triggers id=4df70b66-6b05-3251-95a1-32b54005fd48 version=582d7071-1ef0-37c8-adc6-471a13636139
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF views id=9786ac1c-dd58-3201-a7cd-ad556410c985 version=5b58bb47-96e7-3f57-accf-0bfca4dbbc6e
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF types id=5a8b1ca8-6602-3f77-a045-9273d308917a version=de51b2ce-5e4d-3b7d-a75f-2204332ce8d1
INFO  2020-03-12 23:37:24,538 [shard 0] database - Keyspace system_schema: Reading CF aggregates id=924c5587-2e3a-345b-b10c-12f37c1ba895 version=4b53e92c-0368-3d5c-b959-2ec1bfd1a59f
INFO  2020-03-12 23:37:24,593 [shard 0] database - Populating Keyspace system
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF schema_aggregates id=a5fc57fc-9d6c-3bfd-a3fc-01ad54686fea version=d06c934f-9a69-374c-86f1-523ab26fb05c
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF schema_triggers id=0359bc71-7123-3ee1-9a4a-b9dfb11fc125 version=75e4ec4c-76da-3f59-984e-66810ba0c62b
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF compaction_history id=b4dbb7b4-dc49-3fb5-b3bf-ce6e434832ca version=25cae56a-8d75-39f3-a146-3756ab4981c7
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF compactions_in_progress id=55080ab0-5d9c-3886-90a4-acb25fe1f77b version=540263f1-40db-3869-8a38-3baadedc222d
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF range_xfers id=55d76438-4e55-3f8b-9f6e-676d4af3976d version=dd15a078-409b-350d-9bef-c5f3520832d8
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF scylla_views_builds_in_progress id=a04c7bfd-1e13-36c9-a44d-f22da352281d version=e3fb736c-6956-3990-a31d-9a482279e3fc
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF IndexInfo id=9f5c6374-d485-3229-9a0a-5094af9ad1e3 version=bbb3743b-351f-3023-b4fc-09a9be37d529
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF cdc_local id=0bcaffd4-0c83-3ead-ad13-dc1d5015b77c version=0aa4d3a2-ed95-3ecd-aba0-cd75622ad290
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF schema_columnfamilies id=45f5b360-24bc-3f83-a363-1034ea4fa697 version=7f7a5fea-07b7-304d-a6f8-f7aec72cabdb
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF batchlog id=0290003c-977e-397c-ac3e-fdfdc01d626b version=e2a2e804-49e4-3597-9f16-39fd9475835c
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF schema_functions id=d1b675fe-2b50-3ca4-8e49-c0f81989dcad version=a50959dd-2be0-3e4e-8bb5-cf40796e256a
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF peer_events id=59dfeaea-8db2-3341-91ef-109974d81484 version=7f874a05-72b8-3c21-9acb-baa164fc351a
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF local id=7ad54392-bcdd-35a6-8417-4e047860b377 version=7fa82c2e-5b67-37dd-8e5e-2079e18f1536
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF clients id=ca0f635d-8630-3609-8d93-a1fc06f2a5e5 version=51273ebf-e6f9-3cd5-b455-ea09ad29796f
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF size_estimates id=618f817b-005f-3678-b8a4-53f3930b8e86 version=6d4dbcff-f05b-3dc3-95ad-f79f7b10504d
INFO  2020-03-12 23:37:24,593 [shard 0] database - Keyspace system: Reading CF large_partitions id=8a7fe624-96b0-34b1-b90e-f71bddcdd2d3 version=04fa9920-9369-3a96-be39-6dd9fdc816b6
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF schema_columns id=296e9c04-9bec-3085-827d-c17d3df2122a version=53cfbb66-ee0d-37be-97bb-b2afb3746f85
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF built_views id=4b3c50a9-ea87-3d76-9101-6dbc9c38494a version=a28aa0b3-6def-30a7-9fbe-ce78b3f3c9b9
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF peers id=37f71aca-7dc2-383b-a706-72528af04d4f version=f6f6871f-8c86-3eca-ac0b-2a2e848e395d
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF hints id=2666e205-73ef-38b3-90fe-fecf96e8f0c7 version=0b74fdd1-e96d-309e-a14e-a5bcd7ac885d
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF large_rows id=40550f66-0858-39a0-9430-f27fc08034e9 version=aee3acb0-7926-317b-848e-db7bc3721695
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF large_cells id=ead8bbc5-f146-3ae1-9f71-0b11f9a1d296 version=0d4a6937-a781-3f87-a192-b4e4a4a40acf
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF scylla_local id=2972ec7f-fb20-38dd-aac1-d876f2e3fcbd version=5f0b407d-eedf-3845-a48e-dbb9673d10e1
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF views_builds_in_progress id=b7f2c108-78cd-3c80-9cd5-d609b2bd149c version=b905cce5-1474-3085-819a-7592453e2fb9
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF schema_usertypes id=3aa75225-4f82-350b-8d5c-430fa221fa0a version=3c53e6bb-56d5-3618-a0b2-4ff5f18127d7
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF sstable_activity id=5a1ff267-ace0-3f12-8563-cfae6103c65e version=bdec57a3-b234-334b-be9c-7b1f33113995
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF truncated id=38c19fd0-fb86-3310-a4b7-0d0cc66628aa version=6da9a85c-7ae0-3917-aead-54a2f65a57a8
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF paxos id=b7b7f0c2-fd0a-3410-8c05-3ef614bb7c2d version=6dd372de-72fb-3e1b-9b8c-f97738a67fe9
INFO  2020-03-12 23:37:24,594 [shard 0] database - Keyspace system: Reading CF schema_keyspaces id=b0f22357-4458-3cdb-9631-c43e59ce3676 version=84d28cef-59f9-34a9-9be5-31c684997f03
INFO  2020-03-12 23:37:24,613 [shard 0] init - starting gossip
INFO  2020-03-12 23:37:24,613 [shard 0] init - starting storage proxy
INFO  2020-03-12 23:37:24,616 [shard 0] init - creating hints manager
INFO  2020-03-12 23:37:24,617 [shard 1] init - creating hints manager
INFO  2020-03-12 23:37:24,617 [shard 0] init - starting migration manager
INFO  2020-03-12 23:37:24,617 [shard 0] init - starting query processor
INFO  2020-03-12 23:37:24,617 [shard 0] init - initializing batchlog manager
INFO  2020-03-12 23:37:24,619 [shard 0] legacy_schema_migrator - Moving 0 keyspaces from legacy schema tables to the new schema keyspace (system_schema)
INFO  2020-03-12 23:37:24,619 [shard 0] legacy_schema_migrator - Dropping legacy schema tables
INFO  2020-03-12 23:37:24,720 [shard 0] legacy_schema_migrator - Completed migration of legacy schema tables
INFO  2020-03-12 23:37:24,723 [shard 0] init - loading system sstables
INFO  2020-03-12 23:37:24,727 [shard 0] init - loading non-system sstables
INFO  2020-03-12 23:37:24,750 [shard 0] database - Populating Keyspace ks
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace ks: Reading CF ttl_table id=62229670-64ba-11ea-b64d-000000000001 version=b63c4a5c-1e96-3c6e-a7df-e2c99c97b885
INFO  2020-03-12 23:37:24,750 [shard 0] database - Populating Keyspace system_distributed
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_distributed: Reading CF cdc_description id=a6efd744-ecb1-3bd4-a2d9-de70cd10a136 version=f1e1abad-917c-3699-a936-be885c26446b
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_distributed: Reading CF view_build_status id=5582b59f-8e4e-35e1-b913-3acada51eb04 version=e0b6e628-60e0-39a2-ada0-9b6c13bdd9bc
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_distributed: Reading CF cdc_topology_description id=fe969cf0-bed7-3aea-aa56-3363ccb77b72 version=19f5d4dc-c810-30b1-b136-69585f54ca91
INFO  2020-03-12 23:37:24,750 [shard 0] database - Populating Keyspace system_traces
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_traces: Reading CF sessions id=c5e99f16-8677-3914-b17e-960613512345 version=e72aa0ab-a929-3104-ab4a-063f9263c8aa
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_traces: Reading CF node_slow_log_time_idx id=f9706768-aa1e-3d87-9e5c-51a3927c2870 version=ba8cc209-0c50-38b9-a0c4-2e28b572a569
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_traces: Reading CF sessions_time_idx id=0ebf001c-c1d1-3693-9a63-c3d96ac53318 version=78da6b38-7b99-3764-b9c2-e17adb97cb0f
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_traces: Reading CF events id=8826e8e9-e16a-3728-8753-3bc1fc713c25 version=88d78676-02ea-3080-9db6-c2a7e2fd03a8
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_traces: Reading CF node_slow_log id=bfcc4e62-5b63-3aa1-a1c3-6f5e47f3325c version=98a5e99c-6b35-3835-83d4-9007755107b8
INFO  2020-03-12 23:37:24,750 [shard 0] database - Populating Keyspace system_auth
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_auth: Reading CF roles id=5bc52802-de25-35ed-aeab-188eecebb090 version=99b39a9e-0ff0-39ca-afb1-a506e8af85ef
INFO  2020-03-12 23:37:24,750 [shard 0] database - Keyspace system_auth: Reading CF role_members id=0ecdaa87-f8fb-3e60-88d1-74fb36fe5c0d version=18c846dd-9420-3752-972f-feca8bc32fcf
INFO  2020-03-12 23:37:24,752 [shard 0] init - starting view update generator
INFO  2020-03-12 23:37:24,752 [shard 0] init - discovering staging sstables
INFO  2020-03-12 23:37:24,752 [shard 0] init - setting up system keyspace
INFO  2020-03-12 23:37:24,759 [shard 0] init - starting commit log
INFO  2020-03-12 23:37:24,760 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-10-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-8-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-6-big-Data.db:level=0, ]
INFO  2020-03-12 23:37:24,760 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/local-7ad54392bcdd35a684174e047860b377/mc-28-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/local-7ad54392bcdd35a684174e047860b377/mc-30-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/local-7ad54392bcdd35a684174e047860b377/mc-34-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/local-7ad54392bcdd35a684174e047860b377/mc-32-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/local-7ad54392bcdd35a684174e047860b377/mc-26-big-Data.db:level=0, ]
INFO  2020-03-12 23:37:24,760 [shard 1] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-5-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-7-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/system-truncated-ka-3-Data.db:level=0, ]
INFO  2020-03-12 23:37:24,761 [shard 0] init - initializing migration manager RPC verbs
INFO  2020-03-12 23:37:24,761 [shard 0] init - initializing storage proxy RPC verbs
INFO  2020-03-12 23:37:24,761 [shard 0] init - starting streaming service
INFO  2020-03-12 23:37:24,761 [shard 0] init - starting hinted handoff manager
INFO  2020-03-12 23:37:24,762 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-8-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-6-big-Data.db:level=0, ]
INFO  2020-03-12 23:37:24,776 [shard 0] init - starting messaging service
INFO  2020-03-12 23:37:24,776 [shard 0] repair - Setting max_repair_memory=53687091, max_repair_memory_per_range=33554432, max_repair_ranges_in_parallel=1
INFO  2020-03-12 23:37:24,776 [shard 0] init - starting storage service
INFO  2020-03-12 23:37:24,776 [shard 0] storage_service - Loading persisted ring state
INFO  2020-03-12 23:37:24,779 [shard 0] storage_service - loaded_peer_features: peer_features size=1
INFO  2020-03-12 23:37:24,779 [shard 0] storage_service - loaded_peer_features: peer=127.0.88.1, supported_features=COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,NONFROZEN_UDTS,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
INFO  2020-03-12 23:37:24,779 [shard 0] storage_service - Checking remote features with gossip and system tables
INFO  2020-03-12 23:37:24,779 [shard 0] messaging_service - Starting Messaging Service on port 7000
INFO  2020-03-12 23:37:24,780 [shard 0] rpc - client 127.0.88.1:7000: fail to connect: Connection refused
INFO  2020-03-12 23:37:24,789 [shard 1] compaction - Compacted 3 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-9-big-Data.db:level=0, ]. 221196 bytes to 74280 (~33% of original) in 29ms = 2.44MB/s. ~384 total partitions merged to 6.
INFO  2020-03-12 23:37:24,807 [shard 0] compaction - Compacted 5 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/local-7ad54392bcdd35a684174e047860b377/mc-36-big-Data.db:level=0, ]. 36607 bytes to 12683 (~34% of original) in 47ms = 0.26MB/s. ~640 total partitions merged to 1.
INFO  2020-03-12 23:37:24,807 [shard 0] compaction - Compacted 3 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-12-big-Data.db:level=0, ]. 87207 bytes to 76902 (~88% of original) in 47ms = 1.56MB/s. ~384 total partitions merged to 2.
INFO  2020-03-12 23:37:24,808 [shard 0] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-bug2ercu/test/node2/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-10-big-Data.db:level=0, ]. 97656 bytes to 51738 (~52% of original) in 46ms = 1.07MB/s. ~256 total partitions merged to 2.
INFO  2020-03-12 23:37:25,779 [shard 0] gossip - Connect seeds again ... (1 seconds passed)
INFO  2020-03-12 23:37:25,780 [shard 0] rpc - client 127.0.88.1:7000: fail to connect: Connection refused

... and last 2 messages repeat from here on
```

node1 is shut down at this point

**Comment by bhalevy** [comment]
Last successful run is d895f5e1311118cc93e8c84384914a0a9bde2267
List of scylla changes:
```
scylla$ git log --oneline --reverse d895f5e1311118cc93e8c84384914a0a9bde2267..c020b4e5e20e7f3b5e8fe0a12271f3adc5449be2
e63f5187b2 system_keyspace: Rework migrate_truncation_records feature subscription
0a10e9787e features: Remove future-based when_enabled()
86ca4b83d0 Revert "Revert "features: Stop on shutdown""
899bb230e2 sstable_resharding_test: fix sstable_resharding_strategy_tests with odd smp count
3cc3233281 test/cdc: test that LWT generates CDC logs
3548e85ff7 Merge "features: Properly resolve when_enabled futures on stop" from Pavel E.
cd73f552b9 storage_service, database: do not move sharded services
0cb7182768 Update seastar submodule
3b3659e8cd db,view: drop default parameter for mutate_MV::allow_hints
fd49fd773c db,view: move putting view updates to background to mutate_MV
2061e6a9cc db,view: perform local view updates synchronously
8d2555673f test: add a simple test for synchronous local view updates
8d161cac87 merge: Allow synchronous view updates for local views
0da517ca93 scylla-gdb.py: get_text_range(): make compatible with >=3.0
10944689bc scylla-gdb.py: resolve(): don't attempt to match failed symbols
0909dd3d11 scylla-gdb.py: scylla_sstables: fix copypasta in name passed to argparse
931d2fca45 scylla-gdb.py: std_list: __len__(): support C++11 ABI
c020b4e5e2 logalloc: increase capacity of _regions vector outside reclaim lock
```

**Comment by bhalevy** [comment]
This is a test issue caused by scylladb/scylla-ccm@c1762841eec615ba315be1b4b841aaef5108281d

**Comment by bhalevy** [comment]
Closing since there was no issue with scylla, just with the test, and it is now fixed.
