### ISSUE TITLE
CDC: failed decoding of result column while fetching from cdc log table

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#6050]
The following sequence of cql commands fail with an error:

```cql
cqlsh> create keyspace ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> create table ks.t (pk int, ck int, s int static, c int, c_map map<int, int>, c_list list<int>, primary key(pk, ck)) with cdc = {'enabled': true};
cqlsh> insert into ks.t (pk, ck, s, c, c_map, c_list) values (0, 1, 2, 3, {4:5}, [6]);
cqlsh> select * from ks.t_scylla_cdc_log;
Traceback (most recent call last):
  File "/home/piodul/code/scylla-tools-java/bin/cqlsh.py", line 1053, in perform_simple_statement
    result = future.result()
  File "/home/piodul/code/scylla-tools-java/bin/../lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/cluster.py", line 3925, in result
    raise self._final_exception
DriverException: Failed decoding result column "c_list" of type map<timeuuid, int>: bytes is not a 16-char string
```

**Comment by elcallio** [comment]
Probably means there is an issue in corresponding unit test - i.e. my manual unpacking does not correlate with the python drivers...

**Comment by aleksbykov** [comment]
Got similar error for cassandra driver for frozen collection:
```
ERROR: test_all_operation (cdc_types_test.TestCDCFrozenCollection_frozen<list<text>>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "cassandra/obj_parser.pyx", line 72, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
  File "cassandra/deserializers.pyx", line 307, in cassandra.deserializers.DesMapType.deserialize
  File "cassandra/deserializers.pyx", line 338, in cassandra.deserializers._deserialize_map
  File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
  File "cassandra/deserializers.pyx", line 465, in cassandra.deserializers.GenericDeserializer.deserialize
  File "cassandra/cqltypes.py", line 604, in cassandra.cqltypes.TimeUUIDType.deserialize
  File "/usr/lib64/python3.7/uuid.py", line 169, in __init__
    raise ValueError('bytes is not a 16-char string')
ValueError: bytes is not a 16-char string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cassandra/row_parser.pyx", line 38, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
  File "cassandra/obj_parser.pyx", line 31, in cassandra.obj_parser.ListParser.parse_rows
  File "cassandra/obj_parser.pyx", line 74, in cassandra.obj_parser.TupleRowParser.unpack_row
cassandra.DriverException: Failed decoding result column "value" of type map<timeuuid, varchar>: bytes is not a 16-char string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cassandra/obj_parser.pyx", line 72, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
  File "cassandra/deserializers.pyx", line 307, in cassandra.deserializers.DesMapType.deserialize
  File "cassandra/deserializers.pyx", line 338, in cassandra.deserializers._deserialize_map
  File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
  File "cassandra/deserializers.pyx", line 465, in cassandra.deserializers.GenericDeserializer.deserialize
  File "cassandra/cqltypes.py", line 604, in cassandra.cqltypes.TimeUUIDType.deserialize
  File "/usr/lib64/python3.7/uuid.py", line 169, in __init__
    raise ValueError('bytes is not a 16-char string')
ValueError: bytes is not a 16-char string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abykov/Projects/scylladb-project/scylla-dtest/cdc_types_test.py", line 426, in test_all_operation
    self.all_operation_tmpl()
  File "/home/abykov/Projects/scylladb-project/scylla-dtest/cdc_types_test.py", line 359, in all_operation_tmpl
    cdc_log_data = self.get_all_cdc_log_records(session)
  File "/home/abykov/Projects/scylladb-project/scylla-dtest/cdc_types_test.py", line 131, in get_all_cdc_log_records
    res_cdc_log = list(session.execute(f"SELECT * FROM {self.keyspace}.{self.table_cdc_log}"))
  File "cassandra/cluster.py", line 2141, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
  File "cassandra/connection.py", line 609, in cassandra.connection.Connection.process_msg
  File "cassandra/protocol.py", line 1149, in cassandra.protocol._ProtocolHandler.decode_message
  File "cassandra/protocol.py", line 639, in cassandra.protocol.ResultMessage.recv_body
  File "cassandra/row_parser.pyx", line 46, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
  File "cassandra/obj_parser.pyx", line 57, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/obj_parser.pyx", line 74, in cassandra.obj_parser.TupleRowParser.unpack_row
cassandra.DriverException: Failed decoding result column "value" of type map<timeuuid, varchar>: bytes is not a 16-char string
```

**Comment by elcallio** [comment]
This works fine for me, albeit running on a branch containing my latest changes (pr #6077 and #6078).
I would suggest revisiting with latest master, possibly once those pr:s are merged. 
Note that I remember an error like this from before, so I think you are running a branch before previous collections fixes were merged. 
I'll add a small unit test verification though.

**Comment by haaawk** [comment]
@aleksbykov could you retest on master. It should already be fixed.

**Comment by aleksbykov** [comment]
Yes

**Comment by piodul** [comment]
@aleksbykov Did you re-run the test with a recent Scylla master? Does this error still occur?

**Comment by aleksbykov** [comment]
@piodul sorry for delay with answer. Yes, on latest master the error was not appeared.

**Comment by haaawk** [comment]
It such case, I'm closing the issue.

**Comment by aleksbykov** [comment]
@haaawk @piodul 
The issue again appeared on latest master:

```
Traceback (most recent call last):
  File "cassandra/obj_parser.pyx", line 72, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
  File "cassandra/deserializers.pyx", line 307, in cassandra.deserializers.DesMapType.deserialize
  File "cassandra/deserializers.pyx", line 338, in cassandra.deserializers._deserialize_map
  File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
  File "cassandra/deserializers.pyx", line 465, in cassandra.deserializers.GenericDeserializer.deserialize
  File "cassandra/cqltypes.py", line 677, in cassandra.cqltypes.TimeUUIDType.deserialize
  File "/usr/lib64/python3.7/uuid.py", line 169, in __init__
    raise ValueError('bytes is not a 16-char string')
ValueError: bytes is not a 16-char string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cassandra/row_parser.pyx", line 38, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
  File "cassandra/obj_parser.pyx", line 31, in cassandra.obj_parser.ListParser.parse_rows
  File "cassandra/obj_parser.pyx", line 74, in cassandra.obj_parser.TupleRowParser.unpack_row
cassandra.DriverException: Failed decoding result column "value" of type map<timeuuid, varchar>: bytes is not a 16-char string

During handling of the above exception, another exception occurred:
```

**Comment by piodul** [comment]
@aleksbykov could you provide an instruction on how to reproduce this error? A sequence of CQL statements and schema information would be the best.

**Comment by aleksbykov** [comment]
@piodul 
```
cqlsh> CREATE TABLE ks.cf1 (pkey frozen<list<text>>, ckey frozen<list<text>>, vkey frozen<list<text>>, PRIMARY KEY (pkey, ckey))  WITH cdc={'enabled': true, 'preimage': true}; 
cqlsh> DESC KEYSPACE ks ;

CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE ks.cf1_scylla_cdc_log (
    "cdc$stream_id" blob,
    "cdc$time" timeuuid,
    "cdc$batch_seq_no" int,
    "cdc$deleted_vkey" boolean,
    "cdc$operation" tinyint,
    "cdc$ttl" bigint,
    ckey frozen<list<text>>,
    pkey frozen<list<text>>,
    vkey frozen<map<timeuuid, text>>,
    PRIMARY KEY ("cdc$stream_id", "cdc$time", "cdc$batch_seq_no")
) WITH CLUSTERING ORDER BY ("cdc$time" ASC, "cdc$batch_seq_no" ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'CDC log for ks.cf1'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE ks.cf1 (
    pkey frozen<list<text>>,
    ckey frozen<list<text>>,
    vkey frozen<list<text>>,
    PRIMARY KEY (pkey, ckey)
) WITH CLUSTERING ORDER BY (ckey ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cdc = {'postimage': 'false', 'preimage': 'true', 'enabled': 'true', 'ttl': '86400'}

cqlsh> 
cqlsh> 
cqlsh> 
cqlsh> INSERT INTO ks.cf1 (pkey, ckey, vkey) VALUES (['value1', 'value2'], ['value1', 'value2'], ['value1', 'value2']);
cqlsh> SELECT * from ks.cf1;

 pkey                 | ckey                 | vkey
----------------------+----------------------+----------------------
 ['value1', 'value2'] | ['value1', 'value2'] | ['value1', 'value2']

(1 rows)
cqlsh> select * from ks.cf1_scylla_cdc_log;
Traceback (most recent call last):
  File "/home/abykov/.ccm/scylla-repository/unstable/master/2020-04-08T21%3A01%3A02Z/scylla-tools-java/bin/cqlsh.py", line 1053, in perform_simple_statement
    result = future.result()
  File "/home/abykov/.ccm/scylla-repository/unstable/master/2020-04-08T21%3A01%3A02Z/scylla-tools-java/bin/../lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/cluster.py", line 3925, in result
    raise self._final_exception
DriverException: Failed decoding result column "vkey" of type map<timeuuid, varchar>: bytes is not a 16-char string
```
