### ISSUE TITLE
remove_node_from_gossip_test failed: Missing: ['FatClient .* has been silent for .*ms, removing from gossip']

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6100]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/443/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/remove_node_from_gossip_test/
Scylla version 3159ad4484b26f424d9a4657c58f678d76db70d4
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/update_cluster_layout_tests.py", line 1224, in remove_node_from_gossip_test
    node1.watch_log_for("FatClient .* has been silent for .*ms, removing from gossip")
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 448, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 30 Mar 2020 02:54:55 [node1] Missing: ['FatClient .* has been silent for .*ms, removing from gossip']:
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/443/artifact/logs-release.2/1585536895525_update_cluster_layout_tests.TestUpdateClusterLayout.remove_node_from_gossip_test/node1.log
```
INFO  2020-03-30 02:43:45,853 [shard 0] gossip - InetAddress 127.0.29.4 is now UP, status = UNKNOWN
INFO  2020-03-30 02:44:42,662 [shard 0] gossip - InetAddress 127.0.29.4 is now DOWN, status = shutdown
INFO  2020-03-30 02:44:42,669 [shard 1] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-9-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-7-big-Data.db:level=0, ]
INFO  2020-03-30 02:44:42,670 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-8-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-6-big-Data.db:level=0, ]
WARN  2020-03-30 02:44:42,672 [shard 0] gossip - Skip marking node 127.0.29.4 with status = shutdown as UP
INFO  2020-03-30 02:44:42,688 [shard 0] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-10-big-Data.db:level=0, ]. 28066 bytes to 22703 (~80% of original) in 17ms = 1.27MB/s. ~256 total partitions merged to 2.
INFO  2020-03-30 02:44:42,696 [shard 1] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-11-big-Data.db:level=0, ]. 55330 bytes to 49759 (~89% of original) in 27ms = 1.76MB/s. ~256 total partitions merged to 2.
INFO  2020-03-30 02:44:45,657 [shard 0] rpc - client 127.0.29.4:7000: fail to connect: Connection refused
(repeated ...)
```

A successful run (like one I ran locally) should look like:
```
INFO  2020-03-30 18:06:42,251 [shard 0] gossip - InetAddress 127.0.79.4 is now UP, status = UNKNOWN
INFO  2020-03-30 18:07:45,298 [shard 0] gossip - InetAddress 127.0.79.4 is now DOWN, status = shutdown
INFO  2020-03-30 18:07:50,577 [shard 0] rpc - client 127.0.79.4:7000: fail to connect: Connection refused
INFO  2020-03-30 18:07:52,587 [shard 0] rpc - client 127.0.79.4:7000: fail to connect: Connection refused
INFO  2020-03-30 18:07:53,592 [shard 0] gossip - FatClient 127.0.79.4 has been silent for 10000ms, removing from gossip
```

**Comment by bhalevy** [comment]
@asias please look into this

**Comment by asias** [comment]
Will look into it.

**Comment by asias** [comment]
According to log in [node4](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/443/artifact/logs-release.2/1585536895525_update_cluster_layout_tests.TestUpdateClusterLayout.remove_node_from_gossip_test/node4.log), node4 managed to finish bootstrap, that is the reason node1 failed to see "ccmlib.node.TimeoutError: 30 Mar 2020 02:54:55 [node1] Missing: ['FatClient .* has been silent for .*ms, removing from gossip']:".

```
1210         debug("Start node 4...")
1211         self.ignore_log_patterns += ['Startup failed']
1212         node4 = new_node(cluster)
1213         node4.start(jvm_args=['--logger-log-level','stream_session=debug'], no_wait=True)
1214         node4.watch_log_for("JOINING: Starting to bootstrap")
1215         node4.watch_log_for("Beginning stream session|sync data for keyspace=ks, status=started")
1216 
1217         debug("Stop node 4 ...")
1218         node4.stop()
1219 
1220         debug("Check node 1 removed node4  ...")
1221         node1.watch_log_for("FatClient .* has been silent for .*ms, removing from gossip")

```

The line 1215 and 1218 does not guarantee node4 will not finish bootstrap. The test is not reliable.

**Comment by bhalevy** [comment]
@asias I'll fix the test to do `node4.stop(gently=False)`
since the timing was supposed to work, it just stopped, as you said, after finishing repair.

[node4.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/443/artifact/logs-release.2/1585536895525_update_cluster_layout_tests.TestUpdateClusterLayout.remove_node_from_gossip_test/node4.log):
```
INFO  2020-03-30 02:44:31,975 [shard 0] repair - repair id 1 to sync data for keyspace=ks, status=started
```

[dtest.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/443/artifact/logs-release.2/dtest.log):
```
2020-03-30 02:44:31,985 24110   dtest                          DEBUG    | update_cluster_layout_tests.py:TestUpdateClusterLayout.remove_node_from_gossip_test - Stop node 4 ...
```

[node4.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/443/artifact/logs-release.2/1585536895525_update_cluster_layout_tests.TestUpdateClusterLayout.remove_node_from_gossip_test/node4.log):
```
INFO  2020-03-30 02:44:39,491 [shard 0] repair - repair id 1 to sync data for keyspace=ks, status=succeeded
INFO  2020-03-30 02:44:42,558 [shard 0] storage_service - Bootstrap completed! for the tokens {1819884688215750593, 7157376323408708240, 4653885963564322583, 8315278833445957322, 5335129552199558533, 4094679697449456732, 6099211190536469358, 5809669468331948074, 3684967623046007147, 7274268922043532792, 6618601471094981578, 3315008223738039493, 114956341358767161, 5250123826277993275, 61094515271202722, 7947676472652824685, 59716812125501978, 7770751325638395830, 4637664413014009912, 8177281317622906010, 6076784716601885539, 5989717832630415957, 2068509463659111060, 5503911766193306007, 3521425297272896269, 6661307801133684145, 8024483842862000732, 4026847212674023755, 7427182280223882856, 5982752032655592867, 1265536272138433092, 8031705983523413879, 1093094758175046941, 3390435678876048206, 9102039805305790904, 4577104268870545797, 1303335969519313768, 8377532775621800156, 4643152874412098064, 4627911550443624467, 3020793970047611913, 4905244300924476622, 8046951853750346477, 5307607214309735822, 4374148794266107259, 5686070741182109898, 3389025436803483606, 6656950737464323549, 4699482592987898186, 2414103357185869034, 9208774460507247462, 3372903729991732264, 3440584708610189285, 4004613107535035576, 9168813643225359412, 5884297608768796598, 7009093583947940077, 3154890534117533011, 7761931161169790051, 520337177933320734, 8523992566372929373, 5301139973745113918, 1019266879487058379, 764001019022404752, 8090973963759204339, 8600282264417872534, 4782512822505128837, 8797909704498080638, 4241281029955459985, 7432384548531583798, 8250126064160959395, 5788441733445313791, 2157308553708594879, 6760169708936469870, 5404637029345920115, 667398309613832170, 1775736214985237305, 8165959759659014554, 8792123563029682179, 2654463681147897856, 563899752910209326, 1056670814009438879, 6202182557353851620, 4524972131990447873, 3875882876512423714, 1561058293474809018, 3931499689362807814, 1108509651720150616, 5264419208509376749, 445984888224677772, 9151336103412520678, 1996694885973431717, 5399971618971499161, 5787204062361668624, 848485050511388655, 7009826257415025964, 3759888888704705165, 6905345588624183118, 6712170934898527632, 2559989649350972371, 8093661940683865274, 4963695013355319813, 4241711019676180075, 8167363524870212906, 6650844135240809359, 2883203910223027362, 1250904599926078018, 46855822756777542, 8515464526390978796, 2309206079749595129, 8097929369831818103, 5904369550321574051, 1252081571909435946, 1147360861960424507, 6497981357138628804, 2232393922761909345, 9114925024922126539, 2979098389014670103, 9219327765216547727, 4442032776102403176, 6188684365945680318, 7680094604746940309, 2356480321494668803, 2695304589212985237, 2281938942223621932, 4240698640717558685, 1214366511816392100, 4454925874897900868, 6882527399869436222, 7431412106638903655, 6636647245970202277, 3572645102945493973, 5115557945311539492, 2406382257679170443, 4567463031226206839, 4433206413947506845, 5683511010837001670, 3783499137904065210, 1540418797617276395, 5141175961404541375, 7965902235983546285, 2201711456350278248, 2064016368721055632, 7954646114505958192, 473101808093963619, 6463666677180589525, 1383435797228212061, 6151312328247528227, 5146782655587586701, 7132276670975085109, 8558625014120516321, 6723240067069154850, 7111782412720706135, 1741262538388642006, 9202334484608393652, 1635006369910652443, 4185965865768727, 8120265146232253114, 6757059499062691469, 7751321527523624402, 820692125416953879, 7875213491565335628, 2915776331653448717, 2794217276811482600, 2686809631475513125, 5451941074102280523, 2044012279592607973, 8248680210088365890, 5713265039787718241, 3219450202432403686, 6112646344216343298, 8461563029527529282, 4645825135928460751, 6960229002152311411, 1035586901523159718, 7798059866973102867, 6273498618579338837, 2255641658852283013, 3676410660527955566, 8462612244561420981, 8330054297993644370, 6525619196192832473, 9131416715996940245, 1832642144440118640, 5181317866662145456, 4582841389346103625, 2600649299787824740, 1498279205833156858, 896567997977086681, 4185853562220033701, 6897141230648027772, 4811177272003455927, 1609579107692905544, 6678649810045416790, 2441719467830472443, 510505611618816486, 378981656454220257, 44849206923378512, 495927072862686344, 5915228809420413226, 7465927305156757709, 2203126302663830886, 6563017040403928265, 7543197219046020873, 7628292472113971248, 6332393146338835338, 1051726947988762874, 6416969904749879328, 3487259138446203276, 920735426906513453, 7470373440702407386, 5243308130142350332, 7380084769176122882, 8251420890969161157, 9147364580499503978, 5332905476175271011, 4498969236571241618, 2541050625957260004, 8121197771319050990, 7054220441204886959, 7229909383878480046, 4920935577777915009, 8325875635776933102, 4578965002850672084, 4459958537914824776, 5772483249553009973, 5075264020644351188, 7612279559822686145, 3078845880906797127, 928546367094663299, 7313745913915844495, 2853878294727698379, 6223198497155809231, 8050048712613791771, 4612441030194269927, 4126924979398353526, 2378696574462391193, 3620608737433523772, 5666762137255420331, 530136299810981058, 4381686995454191134, 6047738220330451584, 2467750555635642488, 6071621964450020250, 7596171337166279190, 1944846979368306961, 3740923678690468916, 2187384327619698075, 2105092316415739763, 1749203045869123154, 2898176474509808009, 4755004512088265122, 2271813359474580195, 1962630368343179214, 7904904061877666049, 602948812367218107}
INFO  2020-03-30 02:44:42,572 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node4/data/system/local-7ad54392bcdd35a684174e047860b377/mc-32-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node4/data/system/local-7ad54392bcdd35a684174e047860b377/mc-30-big-Data.db:level=0, ]
INFO  2020-03-30 02:44:42,575 [shard 0] storage_service - Node 127.0.29.4 state jump to normal
INFO  2020-03-30 02:44:42,599 [shard 1] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node4/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-5-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node4/data/system/peers-37f71aca7dc2383ba70672528af04d4f/la-3-big-Data.db:level=0, ]
INFO  2020-03-30 02:44:42,619 [shard 0] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node4/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-8-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yit_ka96/test/node4/data/system/peers-37f71aca7dc2383ba70672528af04d4f/la-6-big-Data.db:level=0, ]
INFO  2020-03-30 02:44:42,620 [shard 0] storage_service - NORMAL: node is now in normal status
INFO  2020-03-30 02:44:42,620 [shard 0] cdc - No generation seen during startup.
INFO  2020-03-30 02:44:42,621 [shard 0] init - starting tracing
INFO  2020-03-30 02:44:42,621 [shard 0] storage_service - SSTable data integrity checker is disabled.
INFO  2020-03-30 02:44:42,621 [shard 0] init - starting batchlog manager
INFO  2020-03-30 02:44:42,621 [shard 0] init - starting load meter
INFO  2020-03-30 02:44:42,621 [shard 0] init - starting cf cache hit rate calculator
INFO  2020-03-30 02:44:42,621 [shard 0] init - starting view update backlog broker
INFO  2020-03-30 02:44:42,621 [shard 0] init - Waiting for gossip to settle before accepting client requests...
INFO  2020-03-30 02:44:42,621 [shard 0] init - Shutting down view update backlog broker
INFO  2020-03-30 02:44:42,622 [shard 0] init - Shutting down view update backlog broker was successful
INFO  2020-03-30 02:44:42,622 [shard 0] init - Shutting down cf cache hit rate calculator
INFO  2020-03-30 02:44:42,622 [shard 0] init - Shutting down cf cache hit rate calculator was successful
INFO  2020-03-30 02:44:42,622 [shard 0] init - Shutting down load meter
INFO  2020-03-30 02:44:42,622 [shard 0] init - Shutting down load meter was successful
INFO  2020-03-30 02:44:42,622 [shard 0] init - Shutting down snapshots
INFO  2020-03-30 02:44:42,622 [shard 0] init - Shutting down snapshots was successful
INFO  2020-03-30 02:44:42,622 [shard 0] init - Shutting down gossiping
INFO  2020-03-30 02:44:42,622 [shard 0] gossip - My status = NORMAL
INFO  2020-03-30 02:44:42,622 [shard 0] gossip - Announcing shutdown
etc.
```
