### ISSUE TITLE
Repair failed with runtime error

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#6120]
*Installation details*
Scylla version (or git commit hash): 4.0.rc0-0.20200325.78f5afec30
Cluster size: 4 nodes (i3.2xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0ee5a732dd840a135 (us-east-1)
Test: longevity-lwt-3h

Repair failed with error:
```
Mar 31 16:25:08 longevity-lwt-3h-4-0-db-node-5cfd2305-2 scylla[3010]:  [shard 0] repair - repair_tracker run for repair id 4 failed: std::runtime_error ({shard 0: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296]), shard 1: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296]), shard 2: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296]), shard 3: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296]), shard 4: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296]), shard 5: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296]), shard 6: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296]), shard 7: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296])})
```

Test scenario:
1. stop scylla-server on the one node
2. remove data files on this node
3. start scylla-server
4. run ```nodetool repair```

One of the repair session failed. Searching in the node log, found that in parallel with repair was run compaction on the same table.

For example, the file ```mc-2387-big-Data.db``` was compacting (reported in the log as "compaction - Compacting"), then repair failed. But I didn't find that compaction on this file was completed (it's reported in the log as "compaction - Compacted"):
```
Mar 31 16:25:00 longevity-lwt-3h-4-0-db-node-5cfd2305-2 scylla[3010]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-d8f22030736111ea8d9f000000000002/mc-4947-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-d8f22030736111ea8d9f000000000002/mc-2387-big-Data.db:level=0, ]
Mar 31 16:25:00 longevity-lwt-3h-4-0-db-node-5cfd2305-2 scylla[3010]:  [shard 0] repair - repair id 4 on shard 0 failed: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296])
```

Another failure example:
```
Mar 31 16:25:07 longevity-lwt-3h-4-0-db-node-5cfd2305-2 scylla[3010]:  [shard 5] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-d8f22030736111ea8d9f000000000002/mc-6733-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-d8f22030736111ea8d9f000000000002/mc-6725-big-Data.db:level=0, ]
Mar 31 16:25:07 longevity-lwt-3h-4-0-db-node-5cfd2305-2 scylla[3010]:  [shard 5] repair - repair id 4 on shard 5 failed: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(-inf, 2511742300002296])
```

Here also I didn't find that compaction of ```mc-6725-big-Data.db``` was completed.

No backtraces/coredumps.

```nodetool repair``` fails. StackTrace:
```
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > Command: 'nodetool  repair '
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > 
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > Exit code: 2
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > 
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > 
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:24:35,241] Repair session 1 
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:24:35,241] Repair session 1 finished
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:24:36,684] Starting repair command #2, repairing 1 ranges for keyspace system_traces (parallelism=SEQUENTIAL, full=true)
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:24:41,015] Repair session 2 
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:24:41,073] Repair session 2 finished
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:24:46,642] Repair session 3 
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:24:46,759] Repair session 3 finished
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:24:47,050] Starting repair command #4, repairing 1 ranges for keyspace keyspace1 (parallelism=SEQUENTIAL, full=true)
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:25:09,123] Repair session 4 failed
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > [2020-03-31 16:25:09,163] Repair session 4 finished
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > 
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > 
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > error: Repair job has failed with the error message: [2020-03-31 16:25:09,123] Repair session 4 failed
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > -- StackTrace --
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR > java.lang.RuntimeException: Repair job has failed with the error message: [2020-03-31 16:25:09,123] Repair session 4 failed
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR >   at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR >   at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR >   at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR >   at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR >   at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
< t:2020-03-31 16:25:09,594 f:nemesis.py      l:1778 c:sdcm.nemesis         p:ERROR >   at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

Test logs: ```https://cloudius-jenkins-test.s3.amazonaws.com/5cfd2305-dfe8-4533-8d03-d2ac74c14bfd/20200331_185328/sct-runner-5cfd2305.zip```

DB cluster log: ``` https://cloudius-jenkins-test.s3.amazonaws.com/5cfd2305-dfe8-4533-8d03-d2ac74c14bfd/20200331_185328/db-cluster-5cfd2305.zip```

Restore Monitor Stack command: ```hydra investigate show-monitor 5cfd2305-dfe8-4533-8d03-d2ac74c14bfd```

**Comment by slivne** [comment]
@asias please note this workload has LWT - we do not think its LWT related but one can never know - please try to have a look.

We have not seen this in other workloads so it maybe LWT related - but still I want you todo the first analysis.

**Comment by juliayakovlev** [comment]
failed repair session was run on the table that LW transactions were not run on it.
And this table has no views

**Comment by asias** [comment]
I will take a look.

**Comment by asias** [comment]
Look the log from node4 belong. The composite iterator error happened already before any repair was performed. Node4 was started with auto_bootstrap = false. It did not stream (using repair), so at line 9588, no repair was run.

```
9575 2020-03-31T16:11:04+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | systemd-logind: Removed session 1164.
9576 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 4] storage_service - Loading new SSTables for keyspace1.standard1...
9577 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 4] table - Reshuffling SSTables in /var/lib/scylla/data/keyspace1/standard1-d8f22030736111ea8d9f000000000002...
9578 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 4] storage_service - CF keyspace1.standard1 at shard 4 had SSTables writes disabled for 10317 usec
9579 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 1] storage_service - CF keyspace1.standard1 at shard 1 had SSTables writes disabled for 7522 usec
9580 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 2] storage_service - CF keyspace1.standard1 at shard 2 had SSTables writes disabled for 7418 usec
9581 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 3] storage_service - CF keyspace1.standard1 at shard 3 had SSTables writes disabled for 7787 usec
9582 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 7] storage_service - CF keyspace1.standard1 at shard 7 had SSTables writes disabled for 8013 usec
9583 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 6] storage_service - CF keyspace1.standard1 at shard 6 had SSTables writes disabled for 7904 usec
9584 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 0] storage_service - CF keyspace1.standard1 at shard 0 had SSTables writes disabled for 7633 usec
9585 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 5] storage_service - CF keyspace1.standard1 at shard 5 had SSTables writes disabled for 8591 usec
9586 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 4] storage_service - Done loading new SSTables for keyspace1.standard1 for all shards
9587 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !INFO    | scylla: [shard 0] compaction - Resharding [/var/lib/scylla/data/keyspace1/standard1-d8f22030736111ea8d9f000000000002/keyspace1-standard1-ka-25-Data.db:level=0, ]
9588 2020-03-31T16:11:05+00:00  longevity-lwt-3h-4-0-db-node-5cfd2305-4 !ERR     | scylla: [shard 0] compaction_manager - resharding failed: seastar::internal::backtraced<marshal_exception> (marshaling error: composite iterator - not enough bytes, expected 17200, got 0 Backtrace:        0x330430d#012  0xe6fcbc#012  0xe6fe63#012  0x1229e7a#012  0x1229fde#012  0x12e47c2#012  0x12e7fad#012  0x12e957f#012  0x12ea554#012  0x2e64c80#012  0x2e64e8f#012  0x2e9ce35#012  0x2e02a37#012  0x2e03b6e#012  0xcfc6b7#012  /opt/scylladb/libreloc/libc.so.6+0x271a2#012  0xc1802d     #012)
```

**Comment by slivne** [comment]
@asias it seems you understand whats going with both issues and why `auto_bootstrap = false` caused both, can you clarify what the issues are.

**Comment by asias** [comment]
> @asias it seems you understand whats going with both issues and why `auto_bootstrap = false` caused both, can you clarify what the issues are.

Just to be clear. I think this error happened before even repair was run during startup. The auto_bootstrap = false might cause the schema sync issue which  botond suspected the composite iterator error was due  wrong schema. https://github.com/scylladb/scylla/issues/6121#issuecomment-608289888

**Comment by slivne** [comment]
@juliayakovlev / @roydahan this also needs to be reproduced on master with #6121 and with auto_bootstrap: true

**Comment by juliayakovlev** [comment]
Once we will have new master ami, I'll check it

**Comment by slivne** [comment]
@fgelcer please report if this happens on 4.0.rc3

**Comment by fgelcer** [comment]
> @fgelcer please report if this happens on 4.0.rc3

on `4.0.rc3-0.20200504.eee4c00e29` lwt 3h job we see a repair succeeded (there is another job running right now):
```
2020-05-04 15:31:01.028: (DisruptionEvent Severity.NORMAL): type=start name=RestartThenRepairNode node=Node longevity-lwt-3h-4-0-db-node-0b84b568-3 [3.250.65.176 | 10.0.2.225] (seed: False) duration=None
2020-05-04 15:34:37.851: (DisruptionEvent Severity.NORMAL): type=end name=RestartThenRepairNode node=Node longevity-lwt-3h-4-0-db-node-0b84b568-3 [3.250.65.176 | 10.0.2.225] (seed: False) duration=216
```

**Comment by slivne** [comment]
so for 4.0 I am closing this issue.

**Comment by slivne** [comment]
so for 4.0 I am closing this issue.
