### ISSUE TITLE
stack-buffer-overflow in service::storage_service::should_bootstrap()

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#613]
Several tests (e.g. `query_processor_test`, `storage_proxy_test`) fail in debug mode:
```
$ build/debug/tests/query_processor_test_g
Running 3 test cases...
WARNING: debug mode. Not for benchmarking or production
==18592==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7fa158bfa200; bottom 0x7fa14c9c7000; size: 0x00000c233200 (203633152)
False positive error reports may follow
For details see http://code.google.com/p/address-sanitizer/issues/detail?id=189
Start Storage service ...
=================================================================
==18592==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fa14c896b80 at pc 0x00000364832a bp 0x7fa14c896b20 sp 0x7fa14c896b10
READ of size 8 at 0x7fa14c896b80 thread T1
    #0 0x3648329 in std::_Rb_tree_const_iterator<gms::inet_address>::operator==(std::_Rb_tree_const_iterator<gms::inet_address> const&) const /usr/include/c++/5.1.1/bits/stl_tree.h:313
    #1 0x3648165 in std::_Rb_tree<gms::inet_address, gms::inet_address, std::_Identity<gms::inet_address>, std::less<gms::inet_address>, std::allocator<gms::inet_address> >::find(gms::inet_address const&) const /usr/include/c++/5.1.1/bits/stl_tree.h:2309
    #2 0x3630061 in std::set<gms::inet_address, std::less<gms::inet_address>, std::allocator<gms::inet_address> >::count(gms::inet_address const&) const /usr/include/c++/5.1.1/bits/stl_set.h:665
    #3 0x4158892 in service::storage_service::should_bootstrap() service/storage_service.cc:136
    #4 0x415adb6 in service::storage_service::prepare_to_join() service/storage_service.cc:164
    #5 0x4183f95 in service::storage_service::init_server(int)::{lambda()#1}::operator()() const (/home/pdziepak/scylla/build/debug/tests/query_processor_test_g+0x4183f95)
    #6 0x436eeb9 in apply /home/pdziepak/scylla/seastar/core/apply.hh:34
    #7 0x436ef64 in apply<service::storage_service::init_server(int)::<lambda()> > /home/pdziepak/scylla/seastar/core/apply.hh:42
    #8 0x436f01a in do_void_futurize_apply_tuple<service::storage_service::init_server(int)::<lambda()> > /home/pdziepak/scylla/seastar/core/future.hh:1113
    #9 0x42a7284 in apply<service::storage_service::init_server(int)::<lambda()> > /home/pdziepak/scylla/seastar/core/future.hh:1133
    #10 0x41ee7b3 in futurize<std::result_of<std::decay<service::storage_service::init_server(int)::{lambda()#1}>::type ()>::type>::type seastar::async<service::storage_service::init_server(int)::{lambda()#1}>(std::decay&&, (std::decay<service::storage_service::init_server(int)::{lambda()#1}>::type&&)...)::{lambda(futurize<std::result_of<std::decay<{lambda()#1}>::type ()>::type> seastar::async<{lambda()#1}>(futurize<std::result_of<std::decay<{lambda()#1}>::type ()>::type>::type, std::decay<{lambda()#1}>::type&&)::work&)#1}::operator()(futurize<std::result_of<std::decay<{lambda()#1}>::type ()>::type> seastar::async<{lambda()#1}>(futurize<std::result_of<std::decay<{lambda()#1}>::type ()>::type>::type, std::decay<{lambda()#1}>::type&&)::work)::{lambda()#1}::operator()() const (/home/pdziepak/scylla/build/debug/tests/query_processor_test_g+0x41ee7b3)
    #11 0x467fdd6 in _M_invoke /usr/include/c++/5.1.1/functional:1871
    #12 0x5d3327 in std::function<void ()>::operator()() const /usr/include/c++/5.1.1/functional:2271
    #13 0x8a21e0 in seastar::thread_context::main() core/thread.cc:139
    #14 0x8a20f9 in seastar::thread_context::s_main(unsigned int, unsigned int) core/thread.cc:130
    #15 0x7fa15fa8af0f  (/lib64/libc.so.6+0x48f0f)

0x7fa14c896b80 is located 127872 bytes inside of 131072-byte region [0x7fa14c877800,0x7fa14c897800)
allocated by thread T1 here:
    #0 0x7fa16435fa92 in operator new[](unsigned long) (/lib64/libasan.so.2+0x99a92)

Thread T1 created by T0 here:
    #0 0x7fa1642fc703 in pthread_create (/lib64/libasan.so.2+0x36703)
    #1 0x809234 in posix_thread::posix_thread(posix_thread::attr, std::function<void ()>) core/posix.cc:87
    #2 0x808d5c in posix_thread::posix_thread(std::function<void ()>) core/posix.cc:60
    #3 0x56313f6 in make_unique<posix_thread, test_runner::start(int, char**)::<lambda()> > /usr/include/c++/5.1.1/bits/unique_ptr.h:765
    #4 0x562f202 in test_runner::start(int, char**) seastar/tests/test_runner.cc:47
    #5 0x562a6f8 in init_unit_test_suite() seastar/tests/test-utils.cc:63
    #6 0x7fa162962ada in boost::unit_test::ut_detail::callback0_impl_t<int, boost::unit_test::ut_detail::test_init_caller>::invoke() (/lib64/libboost_unit_test_framework.so.1.58.0+0x4eada)
    #7 0x60300000c18f  (<unknown module>)

SUMMARY: AddressSanitizer: stack-buffer-overflow /usr/include/c++/5.1.1/bits/stl_tree.h:313 std::_Rb_tree_const_iterator<gms::inet_address>::operator==(std::_Rb_tree_const_iterator<gms::inet_address> const&) const

```

git bisect says that 730abbc421969465b59e1329cd4047978f0931ee is to blame.

**Comment by avikivity** [comment]
I think it's a false positive.  I don't know what to do about it.
