### ISSUE TITLE
scylla crashed during scrub dtest: utils/managed_bytes.cc:37: const value_type* managed_bytes::do_linearize() const: Assertion `lc._nesting' failed.

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6141]
Happened with scylla debug based at 4e6f5436767ef84072af7964b49fe56b0ffbc6c4
during scrub compaction with random data injected into sstable

The updated test is currently at bhalevy/scylla-dtest@0125f478624dde92d4bd06fedc60c5fae4809cfb

```
$ PRINT_DEBUG=true CASSANDRA_DIR=../scylla/build/debug SCYLLA_EXT_OPTS="--smp 2" NOSE_PROCESSES=5 REUSE_CLUSTER=true nosetests -s -v --process-timeout=3600 nodetool_additional_test:TestNodetool.scrub_with_one_node_expect_data_loss_test
2020-04-06 20:39:59.052665 going to run tests in parallel
2020-04-06 20:39:59.052949 using the RandomClusterIdAllocator
2020-04-06 20:39:59.119424 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - cluster ccm directory: /local/home/bhalevy/.dtest/dtest-q8ixb4e_
2020-04-06 20:39:59.119855 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - Starting Scylla cluster from directory ../scylla/build/debug
2020-04-06 20:39:59.126126 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - Allocated cluster ID 68: /local/home/bhalevy/.dtest/dtest-q8ixb4e_
2020-04-06 20:39:59.221748 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - configuring skip_wait_for_gossip_to_settle=0 for single_node test
2020-04-06 20:40:21.283419 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - CREATE COLUMNFAMILY cf (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {}
2020-04-06 20:40:27.057427 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - Will corrupt sstable /local/home/bhalevy/.dtest/dtest-q8ixb4e_/test/node1/data/ks/cf-b02dbb70782d11ea9fff000000000000/mc-2-big-Data.db
2020-04-06 20:40:30.062270 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - Random seed: 1586194830
2020-04-06 20:40:30.062420 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - writing random contents at offset=1597 length=75662
2020-04-06 20:40:56.482524 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - Rebuild sstables by storage_service/keyspace_scrub API
2020-04-06 20:40:56.852933 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - Scrub output: b'0'
2020-04-06 20:40:57.695067 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - stopping ccm cluster test at: /local/home/bhalevy/.dtest/dtest-q8ixb4e_
2020-04-06 20:40:57.766028 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - proc 911343 killed - cluster 127.0.68.
2020-04-06 20:40:57.766850 nodetool_additional_test.py:TestNodetool.scrub_with_one_node_expect_data_loss_test - Freeing cluster ID 68: link /local/home/bhalevy/.dtest/68
scrub_with_one_node_expect_data_loss_test (nodetool_additional_test.TestNodetool) ... FAIL

======================================================================
FAIL: scrub_with_one_node_expect_data_loss_test (nodetool_additional_test.TestNodetool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/dtest.py", line 979, in tearDown
    self.cleanUpCluster()
  File "/local/home/bhalevy/dev/scylla-dtest/dtest.py", line 1012, in cleanUpCluster
    raise AssertionError('Critical errors found: {}\nOther errors: {}'.format(critical_errors, found_errors))
AssertionError: Critical errors found: [('node1', ["scylla: utils/managed_bytes.cc:37: const value_type* managed_bytes::do_linearize() const: Assertion `lc._nesting' failed.", 'Aborting on shard 0.'])]
```

node1.log:
```
INFO  2020-04-06 20:40:56,544 [shard 1] compaction - Scrubbing [/local/home/bhalevy/.dtest/dtest-q8ixb4e_/test/node1/data/ks/cf-b02dbb70782d11ea9fff000000000000/mc-3-big-Data.db:level=0, ]
INFO  2020-04-06 20:40:56,545 [shard 0] compaction - Scrubbing [/local/home/bhalevy/.dtest/dtest-q8ixb4e_/test/node1/data/ks/cf-b02dbb70782d11ea9fff000000000000/mc-2-big-Data.db:level=0, ]
INFO  2020-04-06 20:40:56,601 [shard 0] compaction_manager - compaction info: Compaction for ks/cf was stopped due to: scrub compaction failed due to unrecoverable error: sstables::malformed_sstable_exception (Negative ttl: -9223372036854442414 in sstable /local/home/bhalevy/.dtest/dtest-q8ixb4e_/test/node1/data/ks/cf-b02dbb70782d11ea9fff000000000000/mc-2-big-Data.db): stopping
INFO  2020-04-06 20:40:56,849 [shard 1] compaction - Finished scrubbing 1 sstables to [/local/home/bhalevy/.dtest/dtest-q8ixb4e_/test/node1/data/ks/cf-b02dbb70782d11ea9fff000000000000/mc-5-big-Data.db:level=0, ]. 90005 bytes to 90081 (~100% of original) in 303ms = 0.28MB/s. ~128 total partitions merged to 56.
scylla: utils/managed_bytes.cc:37: const value_type* managed_bytes::do_linearize() const: Assertion `lc._nesting' failed.
Aborting on shard 0.
Backtrace:
  /lib64/libasan.so.5+0x000000000006ce7f
  0x0000000009940e74
  0x000000000991e8d8
  0x00000000097f8668
  0x00000000097f87c1
  0x000000000984e41a
  0x0000000009884fdb
  0x000000000988505c
  0x00007f515b55db1f
  /lib64/libc.so.6+0x000000000003c624
  /lib64/libc.so.6+0x00000000000258d8
  /lib64/libc.so.6+0x00000000000257a8
  /lib64/libc.so.6+0x0000000000034a65
  0x00000000054cf97c
  0x0000000000c408ad
  0x0000000000c4224b
  0x000000000105bdc9
  0x00000000010b7296
  0x00000000057bd53b
  0x00000000057b647d
  0x00000000057b68a6
  0x00000000016d2382
  0x000000000168e86f
  0x0000000001749b9c
  0x000000000173f995
  0x000000000173143a
  0x0000000001711f57
  0x000000000170aacc
  0x00000000016ec20a
  0x00000000016c15d2
  0x00000000016c2816
  0x000000000170b8a5
  0x000000000170b9e4
  0x000000000170bb25
  0x00000000016ed340
  0x00000000016ed1cd
  0x000000000172ae60
  0x000000000173ab34
  0x000000000172b092
  0x000000000172b1d1
  0x000000000172b313
  0x000000000172bb7d
  0x000000000175784d
  0x0000000009833f8b
  0x0000000009837f39
  0x000000000983d181
  0x00000000096a95db
  0x00000000096a7601
  0x00000000004751a1
  /lib64/libc.so.6+0x00000000000271a2
```

Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:735
seastar::print_with_backtrace(seastar::backtrace_buffer&) at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:756
seastar::print_with_backtrace(char const*) at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:763
seastar::sigabrt_action() at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:3445
seastar::install_oneshot_signal_handler<6, &seastar::sigabrt_action>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:3427
seastar::install_oneshot_signal_handler<6, &seastar::sigabrt_action>()::{lambda(int, siginfo_t*, void*)#1}::_FUN(int, siginfo_t*, void*) at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:3423
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
managed_bytes::do_linearize() const at /local/home/bhalevy/dev/scylla/utils/managed_bytes.cc:37 (discriminator 1)
managed_bytes::read_linearize() const at /local/home/bhalevy/dev/scylla/./utils/managed_bytes.hh:147
managed_bytes::data() const at /local/home/bhalevy/dev/scylla/./utils/managed_bytes.hh:400
managed_bytes::operator std::basic_string_view<signed char, std::char_traits<signed char> >() const at /local/home/bhalevy/dev/scylla/./utils/managed_bytes.hh:341
compound_wrapper<partition_key, partition_key_view>::view() const at /local/home/bhalevy/dev/scylla/./keys.hh:230
partition_key::legacy_tri_compare(schema const&, partition_key const&) const at /local/home/bhalevy/dev/scylla/./keys.hh:712
dht::ring_position_tri_compare(schema const&, dht::ring_position_view, dht::ring_position_view) at /local/home/bhalevy/dev/scylla/dht/i_partitioner.cc:300
dht::ring_position_comparator::operator()(dht::ring_position_view, dht::ring_position_view) const at /local/home/bhalevy/dev/scylla/dht/i_partitioner.cc:316
bool dht::ring_position_less_comparator::operator()<dht::ring_position_view, dht::ring_position_view>(dht::ring_position_view const&, dht::ring_position_view const&) const at /local/home/bhalevy/dev/scylla/dht/i_partitioner.hh:599
cache_entry::compare::operator()(cache_entry const&, dht::ring_position_view) const at /local/home/bhalevy/dev/scylla/row_cache.hh:175
bool boost::intrusive::tree_value_compare<cache_entry*, cache_entry::compare, boost::move_detail::identity<cache_entry>, bool, true>::operator()<dht::ring_position>(cache_entry const&, dht::ring_position const&, boost::intrusive::disable_if_smartref_to<dht::ring_position, cache_entry*>::type*) const at /usr/include/boost/intrusive/detail/tree_value_compare.hpp:175
bool boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> >::operator()<boost::intrusive::rbtree_node<void*>*, dht::ring_position>(boost::intrusive::rbtree_node<void*>* const&, dht::ring_position const&, boost::move_detail::enable_if_c<boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> >::is_same_or_nodeptr_convertible<boost::intrusive::rbtree_node<void*>*>::value&&(!boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> >::is_same_or_nodeptr_convertible<dht::ring_position>::value), boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> >::sfinae_type*>::type) const at /usr/include/boost/intrusive/detail/key_nodeptr_comp.hpp:104 (discriminator 2)
boost::intrusive::rbtree_node<void*>* boost::intrusive::bstree_algorithms<boost::intrusive::rbtree_node_traits<void*, false> >::lower_bound_loop<dht::ring_position, boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> > >(boost::intrusive::rbtree_node<void*>*, boost::intrusive::rbtree_node<void*>*, dht::ring_position const&, boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> >) at /usr/include/boost/intrusive/bstree_algorithms.hpp:2028
boost::intrusive::rbtree_node<void*>* boost::intrusive::bstree_algorithms<boost::intrusive::rbtree_node_traits<void*, false> >::lower_bound<dht::ring_position, boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> > >(boost::intrusive::rbtree_node<void*> const* const&, dht::ring_position const&, boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> >) at /usr/include/boost/intrusive/bstree_algorithms.hpp:920 (discriminator 2)
boost::intrusive::rbtree_node<void*>* boost::intrusive::bstree_algorithms<boost::intrusive::rbtree_node_traits<void*, false> >::find<dht::ring_position, boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> > >(boost::intrusive::rbtree_node<void*> const* const&, dht::ring_position const&, boost::intrusive::detail::key_nodeptr_comp<cache_entry::compare, boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, boost::move_detail::identity<cache_entry> >) at /usr/include/boost/intrusive/bstree_algorithms.hpp:754
boost::intrusive::tree_iterator<boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, false> boost::intrusive::bstbase2<boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, void, cache_entry::compare, (boost::intrusive::algo_types)5, void>::find<dht::ring_position, cache_entry::compare>(dht::ring_position const&, cache_entry::compare) at /usr/include/boost/intrusive/bstree.hpp:383 (discriminator 3)
range_populating_reader::handle_end_of_stream() at /local/home/bhalevy/dev/scylla/row_cache.cc:501 (discriminator 2)
auto range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}::operator()<seastar::optimized_optional<mutation_fragment> >(seastar::optimized_optional<mutation_fragment>&&) at /local/home/bhalevy/dev/scylla/row_cache.cc:531
seastar::apply_helper<range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}&, std::tuple<seastar::optimized_optional<mutation_fragment>&&>&&, std::integer_sequence<unsigned long, 0ul> >::apply(range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}, std::tuple<seastar::optimized_optional<mutation_fragment>&&>) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/apply.hh:36
auto seastar::apply<range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}&, seastar::optimized_optional<mutation_fragment>&&>(range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}&, std::tuple<seastar::optimized_optional<mutation_fragment>&&>&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/apply.hh:44
seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > seastar::futurize<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > >::apply<range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}&, seastar::optimized_optional<mutation_fragment>&&>(range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}&, std::tuple<seastar::optimized_optional<mutation_fragment>&&>&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1680
auto seastar::futurize_apply<range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}&, seastar::optimized_optional<mutation_fragment>&&>(range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}&, std::tuple<seastar::optimized_optional<mutation_fragment>&&>&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1786
_ZZN7seastar6futureIJNS_18optimized_optionalI17mutation_fragmentEEEE4thenIZN23range_populating_readerclENSt6chrono10time_pointINS_12lowres_clockENS7_8durationIlSt5ratioILl1ELl1000EEEEEEEUlOT_E_NS0_IJNS1_I20flat_mutation_readerEES3_EEEEET0_SG_ENUlOS3_E_clESM_ at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1211
seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>::direct_vtable_for<seastar::future<seastar::optimized_optional<mutation_fragment> >::then<range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}, seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > >(range_populating_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#1}&&)::{lambda(seastar::optimized_optional<mutation_fragment>&&)#1}>::call(seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)> const*, seastar::optimized_optional<mutation_fragment>&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/util/noncopyable_function.hh:101
seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>::operator()(seastar::optimized_optional<mutation_fragment>&&) const at /local/home/bhalevy/dev/scylla/seastar/include/seastar/util/noncopyable_function.hh:184
seastar::apply_helper<seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>, std::tuple<seastar::optimized_optional<mutation_fragment> >&&, std::integer_sequence<unsigned long, 0ul> >::apply(seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>&&, std::tuple<seastar::optimized_optional<mutation_fragment> >&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/apply.hh:36
auto seastar::apply<seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>, seastar::optimized_optional<mutation_fragment> >(seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>&&, std::tuple<seastar::optimized_optional<mutation_fragment> >&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/apply.hh:44
seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > seastar::futurize<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > >::apply<seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>, seastar::optimized_optional<mutation_fragment> >(seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>&&, std::tuple<seastar::optimized_optional<mutation_fragment> >&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1680
seastar::future<seastar::optimized_optional<mutation_fragment> >::then_impl_nrvo<seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>, seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > >(seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> >&, seastar::future_state<seastar::optimized_optional<mutation_fragment> >&&)#1}::operator()(seastar::internal::promise_base_with_type<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> >, seastar::future_state<seastar::optimized_optional<mutation_fragment> >) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1233
seastar::continuation<seastar::internal::promise_base_with_type<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> >, seastar::future<seastar::optimized_optional<mutation_fragment> >::then_impl_nrvo<seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>, seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > >(seastar::noncopyable_function<seastar::future<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> > (seastar::optimized_optional<mutation_fragment>&&)>&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<seastar::optimized_optional<flat_mutation_reader>, seastar::optimized_optional<mutation_fragment> >&, seastar::future_state<seastar::optimized_optional<mutation_fragment> >&&)#1}, seastar::optimized_optional<mutation_fragment> >::run_and_dispose() at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:513
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:2123
seastar::reactor::run_some_tasks() at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:2538 (discriminator 2)
seastar::reactor::run() at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:2693
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /local/home/bhalevy/dev/scylla/seastar/src/core/app-template.cc:199 (discriminator 1)
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at /local/home/bhalevy/dev/scylla/seastar/src/core/app-template.cc:115 (discriminator 2)
main at /local/home/bhalevy/dev/scylla/main.cc:483 (discriminator 1)
```

**Comment by bhalevy** [comment]
Cc @denesb

**Comment by denesb** [comment]
We are reading a fragmented managed bytes without an enclosing `with_linearized_managed_bytes()`.

**Comment by denesb** [comment]
See https://github.com/scylladb/scylla/issues/6108.

**Comment by slivne** [comment]
Is there a fix ?

which versions are suspect to this bug ?

**Comment by denesb** [comment]
@slivne I think this is not a real bug in the sense that normally we wouldn't even have keys this large. The reason we have a key this large is that the key is coming from a corrupted (by the test) sstable and is likely corrupt. However like I mentioned in https://github.com/scylladb/scylla/issues/6108, this all happens to work incidentally, which serves us fine for now, but we'd be in for a nasty surprise should we increase our key size limitations, and indeed in the case of corrupt keys too.

**Comment by slivne** [comment]
Ok closing this issue

**Comment by denesb** [comment]
@slivne there is new development since I wrote the above commit: https://github.com/scylladb/scylla/issues/6108#issuecomment-619981787. It turns out we *can* have fragmented keys in memtables/cache, so it might be worth looking into this.
