### ISSUE TITLE
scrub prints binary strings when key is corrupted

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6142]
As seen with `nodetool_additional_test:TestNodetool.scrub_with_one_node_expect_data_loss_test` with https://github.com/scylladb/scylla-dtest/pull/1414
`scrub_compaction::on_invalid_partition` and `scrub_compaction::on_invalid_mutation_fragment` may print binary strings to the log when printing `key().with_schema`.
This corrupts the log and causes a failure in the python parser when parsing the logs on bad UTF-8 strings, e.g.:
```
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/dtest.py", line 979, in tearDown
    self.cleanUpCluster()
  File "/local/home/bhalevy/dev/scylla-dtest/dtest.py", line 1003, in cleanUpCluster
    matches = node.grep_log(r'Assertion.*failed|Aborting|AddressSanitizer')
  File "/local/home/bhalevy/dev/scylla-dtest/env/lib/python3.7/site-packages/ccmlib/node.py", line 329, in grep_log
    for line in f:
  File "/local/home/bhalevy/dev/scylla-dtest/env/lib64/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 2880: invalid start byte
```

The following patch suppresses this issue for debugging purposes:
```diff
diff --git a/keys.cc b/keys.cc
index d0fbcae7e5..f844f4b1f7 100644
--- a/keys.cc
+++ b/keys.cc
@@ -48,11 +48,13 @@ static std::ostream& print_key(std::ostream& out, const T& key_with_schema) {
 }
 
 std::ostream& operator<<(std::ostream& out, const partition_key::with_schema_wrapper& pk) {
-    return print_key(out, pk);
+    return out << "pkws{" << to_hex(pk.key.view().representation()) << "}";
+    //return print_key(out, pk);
 }
 
 std::ostream& operator<<(std::ostream& out, const clustering_key_prefix::with_schema_wrapper& ck) {
-    return print_key(out, ck);
+    return out << "ckpws{" << to_hex(ck.key) << "}";
+    //return print_key(out, ck);
 }
 
 std::ostream& operator<<(std::ostream& out, const partition_key_view& pk) {
```

**Comment by bhalevy** [comment]
@denesb please look into this (in low priority)

**Comment by denesb** [comment]
This was fixed since, keys that fail UTF-8 verification are printed as hex binary.
