### ISSUE TITLE
ALTER TYPE row inconsistency

### ISSUE THREAD

**Issue by alecco** [scylladb/scylla#6151]
On a dtest with a thread running SELECT with consistency level ALL, if there's a concurrent ALTER TYPE sometimes there are values returned as None.

Repro:
https://github.com/alecco/scylla-dtest/tree/alter_bug_test
https://github.com/alecco/scylla-dtest/commit/98561bd78b898dcd6f0c7c310f0a3fdb5bd4caba

    $ nosetests -v -I DEBUG --nocapture ./alter_bug_test.py 
    schema_bug_repro_test (alter_bug_test.SchemaBugTester) ... [Row(pk=0, v=0), Row(pk=1, v=1), Row(pk=2, v=2), Row(pk=3, v=None), Row(pk=4, v=4), Row(pk=5, v=5), Row(pk=6, v=None), Row(pk=7, v=None)]
    Exception in thread Thread-19:
    Traceback (most recent call last):
      File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
        self.run()
      File "/usr/lib64/python3.7/threading.py", line 870, in run
        self._target(*self._args, **self._kwargs)
      File "/var/scylla/src/scylla-dtest/alter_bug_test.py", line 40, in _read_rows
        self.assertEqual(lrows, rows_expected)
      File "/usr/lib64/python3.7/unittest/case.py", line 852, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib64/python3.7/unittest/case.py", line 1058, in assertListEqual
        self.assertSequenceEqual(list1, list2, msg, seq_type=list)
      File "/usr/lib64/python3.7/unittest/case.py", line 1040, in assertSequenceEqual
        self.fail(msg)
      File "/usr/lib64/python3.7/unittest/case.py", line 693, in fail
        raise self.failureException(msg)
    AssertionError: Lists differ: [[[0, 0], [1, 1], [2, 2], [3, None], [4, 4], [5, 5], [6, None], [7, None]]] != [[[0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7]]]
    
    First differing element 0:
    [[0, 0], [1, 1], [2, 2], [3, None], [4, 4], [5, 5], [6, None], [7, None]]
    [[0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7]]
    
    - [[[0, 0], [1, 1], [2, 2], [3, None], [4, 4], [5, 5], [6, None], [7, None]]]
    ?                               ^^^^                       ^^^^       ^^^^
    
    + [[[0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7]]]
    ?                               ^                       ^       ^
    
    
    ok
    
    ----------------------------------------------------------------------
    Ran 1 test in 71.321s
    
    OK

**Comment by alecco** [comment]
@kostja

**Comment by slivne** [comment]
Please note we have some other bugs opened on ALTER TYPE.

#4550 - was opened and we did not agree fully on it
#5422 - was opened on ALTERs that may cause a crash 

I would still check whats the issue and if the bug is confined to alter type or may be caused by something else as well.
