### ISSUE TITLE
ALTER DROP/ADD of same column name while LWT DELETE bug/hang

### ISSUE THREAD

**Issue by alecco** [scylladb/scylla#6174]
While doing row LWT DELETEs with prepared statements removes an int column and adds it again as bigint. This brings up a bug and connection to the node is closed.

The same problem happens with other types but this case was picked as it is more  realistic.
    
Also if there's a sleep of 1 second Scylla seems to hang altogether.

Repro:
https://github.com/alecco/scylla-dtest/tree/alter_table_delete_bug_test
https://github.com/alecco/scylla-dtest/commit/5e141c52ac8f868f5a1ec82d917d83b3549f19a8

```
$ nosetests -v -I DEBUG --nocapture ./alter_table_bug_test.py 
bug_test (alter_table_bug_test.TableAlterBugTester) ... DONE PROLOGUE  1586537686.0328913
_delete_Rows start  1586537686.0691018
_alter_table start  1586537686.165845
Exception in thread Thread-6:
Traceback (most recent call last):
  File "cassandra/row_parser.pyx", line 38, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
  File "cassandra/obj_parser.pyx", line 31, in cassandra.obj_parser.ListParser.parse_rows
  File "cassandra/obj_parser.pyx", line 67, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/ioutils.pyx", line 33, in cassandra.obj_parser.get_buf
  File "cassandra/ioutils.pyx", line 45, in cassandra.obj_parser.read_int
  File "cassandra/bytesio.pyx", line 40, in cassandra.bytesio.BytesIOReader.read
EOFError: Cannot read past the end of the file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/scylla/src/scylla-dtest/alter_table_bug_test.py", line 42, in _delete_rows
    session.execute(delete_stmt, (i,))
  File "cassandra/cluster.py", line 2289, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4242, in cassandra.cluster.ResponseFuture.result
  File "cassandra/connection.py", line 762, in cassandra.connection.Connection.process_msg
  File "cassandra/protocol.py", line 1149, in cassandra.protocol._ProtocolHandler.decode_message
  File "cassandra/protocol.py", line 639, in cassandra.protocol.ResultMessage.recv_body
  File "cassandra/row_parser.pyx", line 46, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
  File "cassandra/obj_parser.pyx", line 57, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/obj_parser.pyx", line 67, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/ioutils.pyx", line 33, in cassandra.obj_parser.get_buf
  File "cassandra/ioutils.pyx", line 45, in cassandra.obj_parser.read_int
  File "cassandra/bytesio.pyx", line 40, in cassandra.bytesio.BytesIOReader.read
EOFError: Cannot read past the end of the file

_alter_table done  1586537687.6820407
DONE PROLOGUE  1586537689.9038818
_delete_Rows start  1586537689.9312289
_alter_table start  1586537690.0399754
Exception in thread Thread-8:
Traceback (most recent call last):
  File "cassandra/row_parser.pyx", line 38, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
  File "cassandra/obj_parser.pyx", line 31, in cassandra.obj_parser.ListParser.parse_rows
  File "cassandra/obj_parser.pyx", line 67, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/ioutils.pyx", line 33, in cassandra.obj_parser.get_buf
  File "cassandra/ioutils.pyx", line 45, in cassandra.obj_parser.read_int
  File "cassandra/bytesio.pyx", line 40, in cassandra.bytesio.BytesIOReader.read
EOFError: Cannot read past the end of the file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/scylla/src/scylla-dtest/alter_table_bug_test.py", line 42, in _delete_rows
    session.execute(delete_stmt, (i,))
  File "cassandra/cluster.py", line 2289, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4242, in cassandra.cluster.ResponseFuture.result
  File "cassandra/connection.py", line 762, in cassandra.connection.Connection.process_msg
  File "cassandra/protocol.py", line 1149, in cassandra.protocol._ProtocolHandler.decode_message
  File "cassandra/protocol.py", line 639, in cassandra.protocol.ResultMessage.recv_body
  File "cassandra/row_parser.pyx", line 46, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
  File "cassandra/obj_parser.pyx", line 57, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/obj_parser.pyx", line 67, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/ioutils.pyx", line 33, in cassandra.obj_parser.get_buf
  File "cassandra/ioutils.pyx", line 45, in cassandra.obj_parser.read_int
  File "cassandra/bytesio.pyx", line 40, in cassandra.bytesio.BytesIOReader.read
EOFError: Cannot read past the end of the file

_alter_table done  1586537691.7363684
DONE PROLOGUE  1586537694.1217372
_delete_Rows start  1586537694.1560953
_alter_table start  1586537694.2551668
_alter_table done  1586537695.7424212
_delete_Rows done  1586537695.9966838
DONE PROLOGUE  1586537698.08324
_delete_Rows start  1586537698.1192975
_alter_table start  1586537698.2073715
_alter_table done  1586537699.6957347
_delete_Rows done  1586537700.0854218
ok

----------------------------------------------------------------------
Ran 1 test in 48.908s

OK
```

**Comment by kostja** [comment]
@alecco I believe this is fixed now, could you please retest?

**Comment by alecco** [comment]
Confirmed this is fixed.

Repro branch updated to latest dtest https://github.com/alecco/scylla-dtest/tree/alter_table_delete_bug_test

**Comment by kostja** [comment]
* Alecco ***@***.***> [22/11/18 19:24]:
> Confirmed this is fixed.
> 
> Repro branch updated to latest dtest https://github.com/alecco/scylla-dtest/tree/alter_table_delete_bug_test

Can we move the test case to test.py or it's too heavy?

-- 
Konstantin Osipov, Moscow, Russia

**Comment by alecco** [comment]
> * Alecco ***@***.***> [22/11/18 19:24]:
> Confirmed this is fixed. Repro branch updated to latest dtest https://github.com/alecco/scylla-dtest/tree/alter_table_delete_bug_test
> Can we move the test case to test.py or it's too heavy?
> […](#)
> -- Konstantin Osipov, Moscow, Russia

It can be done with `asyncio` in parallel, sure.
