### ISSUE TITLE
date format breaks YCSB/aws-sdk-java when alternator_enforce_authorization:true

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#6253]
*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Running YCSB (aws-sdk-java 1.10.48) fails to parse date originating from scylla alternator when `alternator_enforce_authorization: true` 

it's 4 years old version of the sdk that YCSB is using there, but I think our data format should be "20 Apr 2020 20:50:09 +0000", we'll need check with dynamodb

```
29664 [Thread-131] WARN  com.amazonaws.http.AmazonHttpClient  -Unable to parse clock skew offset from response: 20 Apr 2020 20:50:09 GMT
java.lang.IllegalArgumentException: Invalid format: "20 Apr 2020 20:50:09 GMT"
        at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
        at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
        at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:193)
        at com.amazonaws.http.AmazonHttpClient.parseClockSkewOffset(AmazonHttpClient.java:1394)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:901)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1820)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.putItem(AmazonDynamoDBClient.java:1353)
        at site.ycsb.db.DynamoDBClient.insert(DynamoDBClient.java:274)
        at site.ycsb.DBWrapper.insert(DBWrapper.java:221)
        at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601)
        at site.ycsb.ClientThread.run(ClientThread.java:135)
        at java.lang.Thread.run(Thread.java:748)
```

this print lot of warnings which render YCSB almost useless for our needs

**Comment by nyh** [comment]
Unfortunately, this is not a problem with authorization but of the Seastar HTTP server. For example, here is the trivial healthcheck request, which also has this GMT timestamp:
```
$ curl -i http://localhost:8000/
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 23
Server: Seastar httpd
Date: 21 Apr 2020 09:41:16 GMT

healthy: localhost:8000        
```

You can see here exactly the same data format in the "Date:" header. Apparently, the client only cares about the "Date:" response header in the case of authentication being enabled, which is why you saw this problem in this case. 

The HTTP date format is explained in this RFC: https://tools.ietf.org/html/rfc7231#section-7.1.1.1 - the date should look like "Sun, 06 Nov 1994 08:49:37 GMT". The day of the week is missing in our output!

**Comment by fruch** [comment]
in theory newer versions of the aws-sdk-java, might be o.k. with it, since they are using a whole different code for it.

but we should still fix it.

python client worked fine... we might consider testing more flavors of the aws-sdk (i.e. in other languages)

**Comment by nyh** [comment]
Opened a Seastar issue: https://github.com/scylladb/seastar/issues/739. I will fix it. I don't know if newer versions of aws-sdk-java will fix this or not - the format of our "Date:" header is definitely wrong. Maybe the new code does its parsing more leniently or maybe it doesn't care about "Date:" at all so it will work, I don't know. It's good you found this - other clients might have problems with this format as well. I'll ask you to re-check this when I submit a new version.

**Comment by nyh** [comment]
I just sent two patches to Seastar, titled `http server: fix "Date" header format` and `http server: fix date function on non-English locales`, fixing the "Date:" header format and should solve this bug. @amnonh can you please review these two patches so they can be included in Seastar and eventually reach Scylla? Thanks.

**Comment by nyh** [comment]
My Seastar fix is already in Seastar (https://github.com/scylladb/seastar/commit/c5cfc5458f74a2f1ad86c940c98a44095cbe1c1c), and would have solved this issue. But unfortunately we can't yet use the newest Seastar in Scylla because of a missing `io_queue::capacity()`, an issue which @glommer is now handling. 

Once that unrelated issue is fixed in Seastar (or Scylla stops using that method) we can update the Seastar submodule, and mark **this** issue fixed.

**Comment by avikivity** [comment]
Fixed by 31ccd3750b6f6739502f1ca004af0dbd03331c9b

**Comment by avikivity** [comment]
Backported to 3.3, 4.0.

**Comment by nyh** [comment]
This issue was fixed by a Seastar commit, which above Avi says is now in master, 4.0 and 3.3. So closing this issue.
