### ISSUE TITLE
Alternator write fails when a node is down with: " Cannot achieve consistency level for cl LOCAL_SERIAL. Requires 1, alive 0 "

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#6268]
*Installation details*
Scylla version (or git commit hash): unstable/master:2020-04-01T01:33:28Z
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Dtest

scenario: taking down one node out of 3 and then trying to run an alternator write query to another node.

the failure's log is:
```
2020-04-21 16:11:24.603290 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Starting Scylla cluster version unstable/master:2020-04-01T01:33:28Z
2020-04-21 16:11:24.613323 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Allocated cluster ID 54: /home/yarongilor/.dtest/dtest-5lbl75fu
2020-04-21 16:11:24.676693 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Populate a cluster with: 3 nodes for single DC
2020-04-21 16:11:25.041841 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Starting cluster..
2020-04-21 16:12:11.110154 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Adding data for all nodes except node2...
2020-04-21 16:12:23.943097 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Stopping node2
2020-04-21 16:12:26.952883 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Creating a table with content, using node1..
2020-04-21 16:12:26.952971 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Getting a resource for node node1 127.0.54.1
2020-04-21 16:12:27.012120 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Creating a table using a resource with node URL: http://127.0.54.1:8080..
2020-04-21 16:12:27.049191 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Generating 100 put request items..
2020-04-21 16:12:53.250166 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Test failed with errors: [(<alternator_tests.AlternatorTest testMethod=test_dynamo_reads_after_repair>, (<class 'botocore.exceptions.ClientError'>, ClientError('An error occurred (Internal Server Error) when calling the BatchWriteItem operation (reached max retries: 9): Internal server error: exceptions::unavailable_exception (Cannot achieve consistency level for cl LOCAL_SERIAL. Requires 1, alive 0)'), <traceback object at 0x7ff7396da2d0>))]
2020-04-21 16:12:53.295819 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - stopping ccm cluster test at: /home/yarongilor/.dtest/dtest-5lbl75fu
2020-04-21 16:12:54.354905 alternator_tests.py:AlternatorTest.test_dynamo_reads_after_repair - Freeing cluster ID 54: link /home/yarongilor/.dtest/54
ERROR

======================================================================
ERROR: test_dynamo_reads_after_repair (alternator_tests.AlternatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yarongilor/git/scylla-dtest/alternator_tests.py", line 215, in test_dynamo_reads_after_repair
    self._prefill_alternator_table(node=node1)
  File "/home/yarongilor/git/scylla-dtest/alternator_tests.py", line 143, in _prefill_alternator_table
    RequestItems={TABLE_NAME: generate_put_request_items(num_of_items=NUM_OF_ITEMS)})
  File "/home/yarongilor/git/scylla-dtest/.dtest_3_7_venv/lib/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/yarongilor/git/scylla-dtest/.dtest_3_7_venv/lib/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/yarongilor/git/scylla-dtest/.dtest_3_7_venv/lib/python3.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/yarongilor/git/scylla-dtest/.dtest_3_7_venv/lib/python3.7/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Internal Server Error) when calling the BatchWriteItem operation (reached max retries: 9): Internal server error: exceptions::unavailable_exception (Cannot achieve consistency level for cl LOCAL_SERIAL. Requires 1, alive 0)
-------------------- >> begin captured logging << --------------------
```

test link: https://github.com/yarongilor/scylla-dtest/blob/cb11731c48f4d4856468b642620df2c6c88c797d/alternator_tests.py#L208

**Comment by yarongilor** [comment]
addressed under https://github.com/scylladb/scylla/issues/6267
