### ISSUE TITLE
fstrim service runtime error

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#6294]
```
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_fstrim", line 60, in <module>
main()
File "/opt/scylladb/scripts/libexec/scylla_fstrim", line 44, in main
cfg = parse_scylla_dirs_with_default(conf=args.config)
File "/opt/scylladb/scripts/scylla_util.py", line 484, in parse_scylla_dirs_with_default
if key not in y or not y[k]:
NameError: name 'k' is not defined
```

**Comment by avikivity** [comment]
Queued as 068bb3a5bf6dce6ee073c262f1c6347313021e40

**Comment by avikivity** [comment]
Backported to 3.3, 4.0.
