### ISSUE TITLE
table_options_test fails with: Error from server: code=0000 [Server error] message="Failed to parse JSON: all"

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6435]
Started in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/480/testReport/cql_additional_tests/TestCQL/table_options_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_additional_tests.py", line 1407, in table_options_test
    """)
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.89.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Failed to parse JSON: all">})
```

and https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/480/testReport/cql_additional_tests/TestCQL/truncate_clean_cache_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_additional_tests.py", line 2882, in truncate_clean_cache_test
    """)
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.99.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Failed to parse JSON: ALL">})
```

Apparently this is caused by 2d727114ed0a029a84828151c7f3acdc7e09fb3f
that tries to parse the string value for caching option (`"all"`) as a map.

**Comment by haaawk** [comment]
It seems that Cassandra has dropped the support for those legacy values.
Value of CACHING property is fetched [using getMap(String)](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/cql3/statements/schema/TableAttributes.java#L92) which [throws an exception](https://github.com/apache/cassandra/blob/01103111ae08b51ccd18bb1c54ac60546546d9df/src/java/org/apache/cassandra/cql3/statements/PropertyDefinitions.java#L78) if the value is not a map.

I think we should just fix those dtests to use only map. What do you think @roydahan and @tzach?

Especially that those are our tests, not inherited from Cassandra. So far, we were totally ignoring CACHING property so the used values weren't changing anything at all anyway. Cassandra converted those dtests to unit tests:

```
commit 3158f8277edc28911a76deb9a74aea38c3d9ef31
Author: Stefania Alborghetti <stefania.alborghetti@datastax.com>
Date:   Wed May 6 11:42:08 2015 +0800

    Migrate CQL dtests to unit tests, CASSANDRA-9160
```

but we brought it back:

```
commit e8245faafdb91b06f6137665195309f4bd20639c
Author: Lucas Meneghel Rodrigues <lmr@scylladb.com>
Date:   Wed Dec 2 02:55:07 2015 -0200

    cql_additional_tests.py: Bring back removed CQL tests
    
    Commit 3158f8277edc28911a76deb9a74aea38c3d9ef31 removes
    a bunch of CQL tests, since those were moved to the
    java unittest suite. They are useful to us, so let's
    bring them back in cql_additional tests, with a bunch
    of cleanups and use of session instead of cursor, which
    is the preferred way of naming the connections with the
    database.
    
    Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>
```

**Comment by slivne** [comment]
this is not supported indeed

```
(.dtest) [shlomi@localhost scylla-ccm]$ ccm node1 cqlsh
Connected to cas-1 at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.4 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cqlsh> create KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> use ks;
cqlsh:ks> CREATE TABLE test (                 k int PRIMARY KEY,                 v1 int,                 v2 int             ) WITH CACHING = ALL;
SyntaxException: Invalid value for property 'caching'. It should be a map.
cqlsh:ks> CREATE TABLE test (                 k int PRIMARY KEY,                 v1 int,                 v2 int             ) WITH CACHING = 'rows_only';
SyntaxException: Invalid value for property 'caching'. It should be a map.
cqlsh:ks> 

```

So I think that we should change the test to the correct syntax supports and we ignore.

**Comment by haaawk** [comment]
Tests are fixed here -> https://github.com/scylladb/scylla-dtest/pull/1482
