### ISSUE TITLE
replace_node_no_hibernate_state_test failed: The process is dead, returncode=1

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6436]
Seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/471/testReport/replace_address_test/TestReplaceAddress/replace_node_no_hibernate_state_test/
Scylla version e44b2826abba0d1c6ae91b7d40f0af112a24517d
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/replace_address_test.py", line 404, in replace_node_no_hibernate_state_test
    node4.start(replace_address=node2_address, wait_for_binary_proto=True, wait_other_notice=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 541, in start
    ext_env)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 281, in _start_scylla
    self.wait_for_binary_interface(from_mark=self.mark, process=self._process_scylla, timeout=420)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 494, in wait_for_binary_interface
    self.watch_log_for("Starting listening for CQL clients", **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 460, in watch_log_for
    raise RuntimeError("The process is dead, returncode={}".format(process.returncode))
RuntimeError: The process is dead, returncode=1
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/471/artifact/logs-release.2/1588473761239_replace_address_test.TestReplaceAddress.replace_node_no_hibernate_state_test/node4.log
```
ERROR 2020-05-03 02:42:41,124 [shard 0] init - Startup failed: std::runtime_error (Cannot replace token 3444658265712363823 which does not exist!)
```

**Comment by asias** [comment]
@bhalevy the commit e44b282 disables repair based ops, the replace operations should fail like `ERROR 2020-05-21 15:49:20,069 [shard 0] init - Startup failed: std::runtime_error (unable to find sufficient sources for streaming range (-9118212697790705053, -9083627894488168363] in keyspace system_auth)`.

Did the test enable repair based ops?

**Comment by bhalevy** [comment]
> @bhalevy the commit [e44b282](https://github.com/scylladb/scylla/commit/e44b2826abba0d1c6ae91b7d40f0af112a24517d) disables repair based ops, the replace operations should fail like `ERROR 2020-05-21 15:49:20,069 [shard 0] init - Startup failed: std::runtime_error (unable to find sufficient sources for streaming range (-9118212697790705053, -9083627894488168363] in keyspace system_auth)`.
> 
> Did the test enable repair based ops?

@asias this was on master with repair-based node ops enabled by default.

**Comment by slivne** [comment]
@asias this test is failing since 471 for 3 weeks on master - it always fails (at least on jenkins) you can try and reproduce locally.

**Comment by slivne** [comment]
It consistently fails on 4.1 as well https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/20/testReport/replace_address_test/TestReplaceAddress/replace_node_no_hibernate_state_test/history/

**Comment by asias** [comment]
> @asias this was on master with repair-based node ops enabled by default.

The code has repair-based node ops disabled by default. Did you enable it in the test explicitly?

**Comment by asias** [comment]
> @asias this test is failing since 471 for 3 weeks on master - it always fails (at least on jenkins) you can try and reproduce locally.

I tried and failed to reproduce

**Comment by bhalevy** [comment]
@asias are you hitting https://github.com/scylladb/scylla/issues/6351, or not even that?

**Comment by asias** [comment]
> @asias are you hitting #6351, or not even that?

Yes, with the commit in this issue, I hit #6351 when I tried to reproduce. I did not see "Cannot replace token 3444658265712363823 which does not exist" issue.

**Comment by bhalevy** [comment]
This test seems to fail either due to this issue or https://github.com/scylladb/scylla/issues/6437

Last time I noticed this particular pattern was in
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/499/artifact/logs-release.2/1590884422224_replace_address_test.TestReplaceAddress.replace_node_no_hibernate_state_test/node4.log
Scylla version c4bbeb80dbd867b565e96e7fdc8a86abc4c90672
```
ERROR 2020-05-31 00:20:22,077 [shard 0] init - Startup failed: std::runtime_error (Cannot replace token -238050287789474168 which does not exist!)
```

**Comment by bhalevy** [comment]
With latest scylla (022d5f6498), I hit a different problem on node4:

```
ERROR 2020-06-01 08:33:45,683 [shard 0] init - Startup failed: std::runtime_error (Cannot replace_address 127.0.45.2 because it doesn't exist in gossip)
```

```
2020-06-01 08:29:22.347771 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - cluster ccm directory: /local/home/bhalevy/.dtest/dtest-m5usa2vn
2020-06-01 08:29:22.347990 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Starting Scylla cluster from directory /local/home/bhalevy/dev/scylla-dtest/../scylla/build/release
2020-06-01 08:29:22.357291 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Allocated cluster ID 45: /local/home/bhalevy/.dtest/dtest-m5usa2vn
2020-06-01 08:29:22.367040 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Cluster *_request_timeout_in_ms=10000, cql request_timeout=30
2020-06-01 08:29:22.425343 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Starting cluster with 2 nodes.
2020-06-01 08:31:00.420761 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Node 1 address is 127.0.45.1
2020-06-01 08:31:00.421230 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Node 2 address is 127.0.45.2
2020-06-01 08:31:00.427024 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Detected number of tokens: 256
2020-06-01 08:31:00.427154 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Inserting Data...
2020-06-01 08:31:18.362011 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Stopping node 2.
2020-06-01 08:31:21.366819 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Starting node 3 to replace node 2, but stop it in the middle of the replace.
2020-06-01 08:32:28.812620 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Node 3 address is 127.0.45.3
2020-06-01 08:32:33.360607 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - gossipinfo:
/127.0.45.3
  generation:1591000348
  heartbeat:2147483647
  HOST_ID:eba14a92-79ae-4981-9302-5efce9ebe0e8
  STATUS:shutdown,true
  RELEASE_VERSION:3.0.8
  X7:12
  X1:COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,NONFROZEN_UDTS,PER_TABLE_CACHING,PER_TABLE_PARTITIONERS,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
  RPC_ADDRESS:127.0.45.3
  X5:
  X4:0
  SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
  X6:2
  DC:datacenter1
  X2:
  RACK:rack1
  X3:3
  NET_VERSION:0
/127.0.45.1
  generation:1591000222
  heartbeat:551
  HOST_ID:b3812aa8-d5be-40e0-b07b-017ce0e3759f
  STATUS:NORMAL,1061769572795439670
  RELEASE_VERSION:3.0.8
  X7:12
  X8:
  X1:COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,NONFROZEN_UDTS,PER_TABLE_CACHING,PER_TABLE_PARTITIONERS,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
  RPC_ADDRESS:127.0.45.1
  X5:0:18446744073709551615:1591000352521
  X4:1
  SCHEMA:a86f9f60-de52-3db4-985b-fb7b5fc54a45
  X6:2
  DC:datacenter1
  X2:system_traces.node_slow_log_time_idx:0.000000;system_traces.sessions_time_idx:0.000000;system_traces.sessions:0.000000;keyspace1.standard1:1.000000;system_traces.node_slow_log:0.000000;system_auth.role_members:0.000000;system_auth.roles:1.000000;system_distributed.cdc_topology_description:0.000000;system_distributed.view_build_status:0.000000;system_distributed.cdc_description:0.000000;system_traces.events:0.000000;
  LOAD:604492
  RACK:rack1
  X3:3
  NET_VERSION:0
/127.0.45.2
  generation:1591000223
  heartbeat:2147483647
  HOST_ID:eba14a92-79ae-4981-9302-5efce9ebe0e8
  STATUS:shutdown,true
  RELEASE_VERSION:3.0.8
  X7:12
  X8:
  X1:COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,NONFROZEN_UDTS,PER_TABLE_CACHING,PER_TABLE_PARTITIONERS,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
  RPC_ADDRESS:127.0.45.2
  X5:0:18446744073709551615:1591000277325
  X4:1
  SCHEMA:a86f9f60-de52-3db4-985b-fb7b5fc54a45
  X6:2
  DC:datacenter1
  X2:system_traces.node_slow_log_time_idx:0.000000;system_traces.sessions_time_idx:0.000000;system_traces.sessions:0.000000;keyspace1.standard1:0.000000;system_traces.node_slow_log:0.000000;system_auth.role_members:0.000000;system_auth.roles:1.000000;system_distributed.cdc_topology_description:0.000000;system_distributed.view_build_status:0.000000;system_distributed.cdc_description:0.000000;system_traces.events:0.000000;
  LOAD:532198
  RACK:rack1
  X3:3
  NET_VERSION:0


2020-06-01 08:32:33.384392 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Starting node 4 to replace node 2.
2020-06-01 08:35:30.613616 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Test failed with errors: [(<replace_address_test.TestReplaceAddress testMethod=replace_node_no_hibernate_state_test>, (<class 'ccmlib.node.TimeoutError'>, TimeoutError("01 Jun 2020 08:35:29 [node1] Missing: ['127.0.45.4.* now UP']:\n.....\nSee system.log for remainder"), <traceback object at 0x7f4f61714dc0>))]
2020-06-01 08:35:30.740421 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - stopping ccm cluster test at: /local/home/bhalevy/.dtest/dtest-m5usa2vn
2020-06-01 08:35:31.749400 replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test - Freeing cluster ID 45: link /local/home/bhalevy/.dtest/45
replace_node_no_hibernate_state_test (replace_address_test.TestReplaceAddress) ... ERROR

======================================================================
ERROR: replace_node_no_hibernate_state_test (replace_address_test.TestReplaceAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/replace_address_test.py", line 407, in replace_node_no_hibernate_state_test
    node4.start(replace_address=node2_address, wait_for_binary_proto=True, wait_other_notice=True)
  File "/local/home/bhalevy/dev/scylla-ccm/ccmlib/scylla_node.py", line 546, in start
    ext_env)
  File "/local/home/bhalevy/dev/scylla-ccm/ccmlib/scylla_node.py", line 279, in _start_scylla
    node.watch_log_for_alive(self, from_mark=mark)
  File "/local/home/bhalevy/dev/scylla-ccm/ccmlib/node.py", line 483, in watch_log_for_alive
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/local/home/bhalevy/dev/scylla-ccm/ccmlib/node.py", line 448, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 01 Jun 2020 08:35:29 [node1] Missing: ['127.0.45.4.* now UP']:
```

**Comment by asias** [comment]
I tried latest maser: eabcb31503eb9896abeeaefe49cd548012dca001. The test passed. I could not reproduce.

**Comment by asias** [comment]
I think I found the root cause. I will work on a fix.

**Comment by asias** [comment]
Patch is sent.

**Comment by avikivity** [comment]
Was already backported everywhere.
