### ISSUE TITLE
CreateTest.testDenseNonCompositeTable fails

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#645]
The ``CreateTest.testDenseNonCompositeTable`` test fails as follows:

```
testDenseNonCompositeTable(org.apache.cassandra.cql3.validation.operations.CreateTest)  Time elapsed: 0.265 sec  <<< FAILURE!
java.lang.AssertionError: Invalid value for row 0 column 0 (url of type varchar), expected <http://bar.bar> but got <http://foo-3>
	at org.junit.Assert.fail(Assert.java:92)
	at org.apache.cassandra.cql3.CQLTester.assertRows(CQLTester.java:395)
	at org.apache.cassandra.cql3.validation.operations.CreateTest.testDenseNonCompositeTable(CreateTest.java:140)
```

The problem is that ``SELECT`` returns result in the wrong order in the test case. You can reproduce the issue with ``cqlsh`` as follows.

Cassandra:

```
[penberg@nero cassandra]$ ./bin/cqlsh 127.0.0.2 --no-color
Connected to Test Cluster at 127.0.0.2:9042.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
cqlsh> CREATE KEYSPACE IF NOT EXISTS cql_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
cqlsh> USE cql_test_keyspace;
cqlsh:cql_test_keyspace> CREATE TABLE foo (userid uuid, url text, time bigint, PRIMARY KEY (userid, url)) WITH COMPACT STORAGE;
cqlsh:cql_test_keyspace> INSERT INTO foo (userid, url, time) VALUES (550e8400-e29b-41d4-a716-446655440000, 'http://foo.bar', 42);
cqlsh:cql_test_keyspace> INSERT INTO foo (userid, url, time) VALUES (550e8400-e29b-41d4-a716-446655440000, 'http://foo-2.bar', 24);
cqlsh:cql_test_keyspace> INSERT INTO foo (userid, url, time) VALUES (550e8400-e29b-41d4-a716-446655440000, 'http://bar.bar', 128);
cqlsh:cql_test_keyspace> SELECT url, time FROM foo WHERE userid = 550e8400-e29b-41d4-a716-446655440000;

 url              | time
------------------+------
   http://bar.bar |  128
 http://foo-2.bar |   24
   http://foo.bar |   42

(3 rows)
cqlsh:cql_test_keyspace> UPDATE foo SET time = 24 WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 and url = 'http://bar.foo';
cqlsh:cql_test_keyspace> UPDATE foo SET time = 12 WHERE userid IN (f47ac10b-58cc-4372-a567-0e02b2c3d479, 550e8400-e29b-41d4-a716-446655440000) and url = 'http://foo-3';
cqlsh:cql_test_keyspace> SELECT url, time FROM foo WHERE userid = 550e8400-e29b-41d4-a716-446655440000;

 url              | time
------------------+------
   http://bar.bar |  128
 http://foo-2.bar |   24
     http://foo-3 |   12
   http://foo.bar |   42

(4 rows)
```

Scylla:

```
[penberg@nero cassandra]$ ./bin/cqlsh --no-color
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
cqlsh> CREATE KEYSPACE IF NOT EXISTS cql_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
cqlsh> USE cql_test_keyspace;
cqlsh:cql_test_keyspace> CREATE TABLE foo (userid uuid, url text, time bigint, PRIMARY KEY (userid, url)) WITH COMPACT STORAGE;
cqlsh:cql_test_keyspace> INSERT INTO foo (userid, url, time) VALUES (550e8400-e29b-41d4-a716-446655440000, 'http://foo.bar', 42);
cqlsh:cql_test_keyspace> INSERT INTO foo (userid, url, time) VALUES (550e8400-e29b-41d4-a716-446655440000, 'http://foo-2.bar', 24);
cqlsh:cql_test_keyspace> INSERT INTO foo (userid, url, time) VALUES (550e8400-e29b-41d4-a716-446655440000, 'http://bar.bar', 128);
cqlsh:cql_test_keyspace> SELECT url, time FROM foo WHERE userid = 550e8400-e29b-41d4-a716-446655440000;

 url              | time
------------------+------
   http://bar.bar |  128
   http://foo.bar |   42
 http://foo-2.bar |   24

(3 rows)
cqlsh:cql_test_keyspace> UPDATE foo SET time = 24 WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 and url = 'http://bar.foo';
cqlsh:cql_test_keyspace> UPDATE foo SET time = 12 WHERE userid IN (f47ac10b-58cc-4372-a567-0e02b2c3d479, 550e8400-e29b-41d4-a716-446655440000) and url = 'http://foo-3';
cqlsh:cql_test_keyspace> SELECT url, time FROM foo WHERE userid = 550e8400-e29b-41d4-a716-446655440000;

 url              | time
------------------+------
     http://foo-3 |   12
   http://bar.bar |  128
   http://foo.bar |   42
 http://foo-2.bar |   24

(4 rows)
```

**Comment by penberg** [comment]
Ping @pdziepak, @tgrabiec

**Comment by pdziepak** [comment]
Looks like compound_type assumes that clustering_keys with a single element are byte comparable which isn't exactly the case as they also have their size prepended, hence the results are incorrectly ordered by their size. I will sent a patch shortly.

**Comment by tgrabiec** [comment]
Perhaps `_byte_order_comparable` condition calculation should also have `&& !is_prefixable`.
