### ISSUE TITLE
cdc_types_test failures

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6466]
Scylla version 96e35f841c6353e17d7190a7078f1f0dbbabd85c
scylladb/scylla-dtest@551539c9fe26c7831ad47d6fd50e879dc7f15c9a
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/483/testReport/cdc_types_test/TestCDCCollectionType_with_list_int_/test_collection_insert_with_postimage/
```
OrderedMapSerializedKey([(UUID('4af26960-[81 chars] 2)]) != [1, 2]
```
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/483/testReport/cdc_types_test/TestCDCCollectionType_with_list_int_/test_collection_insert_with_preimage_postimage/
```
OrderedMapSerializedKey([(UUID('5476ef60-[81 chars] 2)]) != [1, 2]
```

Similar failures in 
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/484/testReport/cdc_types_test/TestCDCCollectionType_with_list_int_/test_collection_insert_with_postimage/
and
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/483/testReport/cdc_types_test/TestCDCCollectionType_with_list_int_/test_collection_insert_with_preimage_postimage/

Scylla version a96087165a92959ff4da74364b681c2906c16745

Plus: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/484/testReport/cdc_types_test/TestCDCCollectionType_with_map_bigint,%20text_/test_collection_insert_with_preimage/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_types_test.py", line 592, in test_collection_insert_with_preimage
    self.insert_operation_tmpl(preimage_enable=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_types_test.py", line 659, in insert_operation_tmpl
    self.verify_cdc_log_rows_after_insert_to_base_table(cdc_log_data, preimage_enable, postimage_enable)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_types_test.py", line 753, in verify_cdc_log_rows_after_insert_to_base_table
    self.check_cdc_log_num_row(cdc_log_data, 6)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_types_test.py", line 132, in check_cdc_log_num_row
    self.assertEqual(len(cdc_log_results), expected_num_rows)
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 4 != 6
```

**Comment by bhalevy** [comment]
Cc @haaawk @aleksbykov

**Comment by elcallio** [comment]
The test is wrong. The "collections" case states its entry for list as: 
'''
{
        "cl_type": "list<int>",
        "ins_dataset": [1, 2],
        "upd_dataset": [3, 4],
        "add_el_dataset": [5],
        "del_el_dataset": [1],
        "result_add_element_dataset": [1, 2, 5],
        "result_delete_element_dataset": [2]
    }
''''
but non-frozen lists are returned as `list<tuple<timeuuid, <value>>>`

**Comment by aleksbykov** [comment]
yes, i found the wrong method for comparing result. Prepare the fix
