### ISSUE TITLE
temporary sstable directories left over after clean node shutdown

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6474]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/486/testReport/sstableloader_test/TestMigration_with_3_0_x/migrate_sstable_with_large_row_number_test/
Scylla version a96087165a92959ff4da74364b681c2906c16745
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/migration_test.py", line 265, in migrate_sstable_with_large_row_number_test
    shutil.copy2(data_file, os.path.join(dir, os.path.basename(data_file)))
  File "/usr/lib64/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yexsvejj/test/node1/data/keyspace1/standard1-ef00725098c311eab6b0000000000000/0000000000000021.sstable'
```

This happened despite the node clean shutdown
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/486/artifact/logs-release.2/1589777964576_sstableloader_test.TestMigration_with_3_0_x.migrate_sstable_with_large_row_number_test/node1.log
```
INFO  2020-05-18 04:59:21,408 [shard 0] init - Signal received; shutting down
INFO  2020-05-18 04:59:21,408 [shard 0] init - Shutting down redis service
INFO  2020-05-18 04:59:21,408 [shard 0] init - Shutting down redis service was successful
INFO  2020-05-18 04:59:21,408 [shard 0] init - Shutting down compaction manager
INFO  2020-05-18 04:59:21,408 [shard 0] compaction_manager - Asked to stop
INFO  2020-05-18 04:59:21,408 [shard 1] compaction_manager - Asked to stop
INFO  2020-05-18 04:59:21,848 [shard 0] compaction_manager - compaction info: Compaction for keyspace1/standard1 was stopped due to: shutdown: stopping
INFO  2020-05-18 04:59:21,848 [shard 0] compaction_manager - Stopped
INFO  2020-05-18 04:59:21,937 [shard 1] compaction_manager - compaction info: Compaction for keyspace1/standard1 was stopped due to: shutdown: stopping
INFO  2020-05-18 04:59:21,938 [shard 1] compaction_manager - Stopped
INFO  2020-05-18 04:59:21,938 [shard 0] init - Shutting down compaction manager was successful
INFO  2020-05-18 04:59:21,938 [shard 0] init - Shutting down view builder
INFO  2020-05-18 04:59:21,938 [shard 0] view - Stopping view builder
INFO  2020-05-18 04:59:21,941 [shard 1] view - Stopping view builder
INFO  2020-05-18 04:59:21,942 [shard 0] init - Shutting down view builder was successful
INFO  2020-05-18 04:59:21,942 [shard 0] init - Shutting down local storage
INFO  2020-05-18 04:59:21,942 [shard 0] storage_service - Drain on shutdown: starts
INFO  2020-05-18 04:59:21,942 [shard 0] storage_service - Stop transport: starts
INFO  2020-05-18 04:59:21,942 [shard 0] storage_service - Thrift server stopped
INFO  2020-05-18 04:59:21,943 [shard 0] storage_service - CQL server stopped
INFO  2020-05-18 04:59:21,943 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2020-05-18 04:59:21,943 [shard 0] gossip - My status = NORMAL
INFO  2020-05-18 04:59:21,943 [shard 0] gossip - Announcing shutdown
INFO  2020-05-18 04:59:21,944 [shard 0] storage_service - Node 127.0.42.1 state jump to normal
INFO  2020-05-18 04:59:21,944 [shard 0] storage_service - Remove node 127.0.42.1 from pending replacing endpoint
INFO  2020-05-18 04:59:24,029 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2020-05-18 04:59:24,029 [shard 0] gossip - Disable and wait for gossip loop finished
INFO  2020-05-18 04:59:24,029 [shard 0] gossip - Gossip is now stopped
INFO  2020-05-18 04:59:24,029 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2020-05-18 04:59:24,030 [shard 0] storage_service - messaging_service stopped
INFO  2020-05-18 04:59:24,030 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2020-05-18 04:59:24,030 [shard 0] storage_service - stream_manager stopped
INFO  2020-05-18 04:59:24,030 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2020-05-18 04:59:24,030 [shard 0] storage_service - Stop transport: auth shutdown
INFO  2020-05-18 04:59:24,030 [shard 0] storage_service - Stop transport: done
INFO  2020-05-18 04:59:24,030 [shard 0] storage_service - Drain on shutdown: stop_transport done
INFO  2020-05-18 04:59:24,030 [shard 0] tracing - Asked to shut down
INFO  2020-05-18 04:59:24,030 [shard 0] tracing - Tracing is down
INFO  2020-05-18 04:59:24,030 [shard 1] tracing - Asked to shut down
INFO  2020-05-18 04:59:24,030 [shard 1] tracing - Tracing is down
INFO  2020-05-18 04:59:24,030 [shard 0] storage_service - Drain on shutdown: tracing is stopped
INFO  2020-05-18 04:59:24,030 [shard 0] storage_service - Drain on shutdown: system distributed keyspace stopped
INFO  2020-05-18 04:59:24,030 [shard 0] hints_manager - Asked to stop
INFO  2020-05-18 04:59:24,030 [shard 0] hints_manager - Stopped
INFO  2020-05-18 04:59:24,030 [shard 0] hints_manager - Asked to stop
INFO  2020-05-18 04:59:24,031 [shard 0] hints_manager - Stopped
INFO  2020-05-18 04:59:24,031 [shard 1] hints_manager - Asked to stop
INFO  2020-05-18 04:59:24,031 [shard 1] hints_manager - Stopped
INFO  2020-05-18 04:59:24,031 [shard 1] hints_manager - Asked to stop
INFO  2020-05-18 04:59:24,031 [shard 1] hints_manager - Stopped
INFO  2020-05-18 04:59:24,031 [shard 0] storage_service - Drain on shutdown: hints manager is stopped
INFO  2020-05-18 04:59:24,069 [shard 0] storage_service - Drain on shutdown: flush column_families done
INFO  2020-05-18 04:59:24,071 [shard 0] storage_service - Drain on shutdown: shutdown commitlog done
INFO  2020-05-18 04:59:24,071 [shard 0] storage_service - Drain on shutdown: done
INFO  2020-05-18 04:59:24,071 [shard 0] init - Shutting down local storage was successful
INFO  2020-05-18 04:59:24,071 [shard 0] init - Shutting down view update generator
INFO  2020-05-18 04:59:24,071 [shard 0] init - Shutting down view update generator was successful
INFO  2020-05-18 04:59:24,071 [shard 0] init - Shutting down repair
INFO  2020-05-18 04:59:24,071 [shard 0] init - Shutting down repair was successful
INFO  2020-05-18 04:59:24,071 [shard 0] init - Shutting down view update backlog broker
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down view update backlog broker was successful
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down cf cache hit rate calculator
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down cf cache hit rate calculator was successful
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down load meter
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down load meter was successful
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down snapshots
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down snapshots was successful
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down gossiping
INFO  2020-05-18 04:59:24,072 [shard 0] gossip - gossip is already stopped
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down gossiping was successful
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down storage service notifications
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down storage service notifications was successful
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down repair service
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down repair service was successful
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down cdc
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down cdc was successful
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down migration manager
INFO  2020-05-18 04:59:24,072 [shard 0] migration_manager - stopping migration service
INFO  2020-05-18 04:59:24,072 [shard 1] migration_manager - stopping migration service
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down migration manager was successful
INFO  2020-05-18 04:59:24,072 [shard 0] init - Shutting down database
INFO  2020-05-18 04:59:24,073 [shard 0] init - Shutting down database: waiting for background jobs...
INFO  2020-05-18 04:59:24,073 [shard 0] init - Shutting down database was successful
INFO  2020-05-18 04:59:24,073 [shard 0] init - Shutting down migration manager notifier
INFO  2020-05-18 04:59:24,073 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2020-05-18 04:59:24,073 [shard 0] init - Shutting down prometheus API server
INFO  2020-05-18 04:59:24,074 [shard 0] init - Shutting down prometheus API server was successful
INFO  2020-05-18 04:59:24,074 [shard 0] init - Shutting down sighup
INFO  2020-05-18 04:59:24,074 [shard 0] init - Shutting down sighup was successful
INFO  2020-05-18 04:59:24,074 [shard 0] init - Scylla version 666.development-0.20200515.a96087165 shutdown complete.
```

I guess that compaction kept running in the background.
If so, b155eef72662363b5ab7badfb5aeed4b4e517767 (Merge "allow early aborts through abort sources." from Glauber) should fix that.

Cc @glommer

**Comment by bhalevy** [comment]
Never reproduced.  Closing with b155eef72662363b5ab7badfb5aeed4b4e517767
