### ISSUE TITLE
Quorum write timeouts and fails when adding column on the stressed table

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#6508]
*Installation details*
Scylla version (or git commit hash): `666.development-0.20200521.c29ccdea7` with build-id 4e3de54c9e8a65011446f42451dd6266212d02e
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-000ea26cf6685813a [eu-west-1]
SCT test id:  5ec552e9-acdb-4362-9098-3a4f7d5f365b
Live monitor: [link](http://99.81.48.181:37296/d/1xC8FDkGk/scylla-per-server-metrics-nemesis-master?orgId=1&from=1590299010320&to=1590301842941&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All)
Grafana snapshot: [link](https://snapshot.raintank.io/dashboard/snapshot/Cm88fYSsLR9sL8lNSaL00i5f4NRrSQQb)
Failed C-S command:
```
cassandra-stress write 
cl=QUORUM duration=2860m  -schema keyspace=keyspace1 'replication(factor=3)
compaction(strategy=LeveledCompactionStrategy)' -port jmx=6868 
-mode cql3 native  user=cassandra password=cassandra -rate threads=250  
-col 'size=FIXED(1024) n=FIXED(1)' -pop seq=400200300..600200300 -log interval=15 
-transport "truststore=/etc/scylla/ssl_conf/client/cacerts.jks 
truststore-password=cassandra"  -node 10.0.88.133  -errors skip-unsupported-columns
```
When adding a columns on the table that was under stress:
```
2020-05-24 05:52:45,072   p:DEBUG > Not starting MonitorReporter thread for Insights; not supported by server version 3.0.8 on ControlConnection host 10.0.27.17:9042
2020-05-24 05:52:45,072   p:DEBUG > Started Session with client_id a9062bb6-5272-449a-8b03-b2da04284243 and session_id a20e82c5-676f-497b-9d9e-58bd4309ba32
2020-05-24 05:52:45,077    p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( TBG7ED3C96 map<frozen<map<frozen<set<varchar>>,frozen<map<varchar,inet>>>>,frozen<list<frozen<list<timestamp>>>>>, RXSKX4BZRL map<frozen<list<frozen<list<varint>>>>,frozen<map<frozen<map<time,boolean>>,frozen<set<float>>>>> );'...
```
Cassndra stress started to get write timeouts: 
```
2020-05-24 05:52:45,153    p:INFO  > RemoteCmdRunner [centos@10.0.226.168]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2020-05-24 05:52:45,153    p:INFO  > RemoteCmdRunner [centos@10.0.226.168]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```
After 10 attempts  writes started to fail and eventually C-S crashed:
```
2020-05-24 05:53:03,199 [centos@10.0.226.168]: java.io.IOException: Operation x10 on key(s) [4f4d304c333235313631]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2020-05-24 05:53:03,199 [centos@10.0.226.168]: 
2020-05-24 05:53:03,199 [centos@10.0.226.168]:    at org.apache.cassandra.stress.Operation.error(Operation.java:141)
2020-05-24 05:53:03,199 [centos@10.0.226.168]:    at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
2020-05-24 05:53:03,199 [centos@10.0.226.168]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
2020-05-24 05:53:03,199 [centos@10.0.226.168]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
2020-05-24 05:53:03,200 [centos@10.0.226.168]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
2020-05-24 05:53:03,200 [centos@10.0.226.168]:    at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
2020-05-24 05:53:03,201 [centos@10.0.226.168]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2020-05-24 05:53:03,236 [centos@10.0.226.168]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 0 acknowledged the write)
2020-05-24 05:53:03,237 [centos@10.0.226.168]: java.io.IOException: Operation x10 on key(s) [4d4e4c3931364b4e4e30]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 0 acknowledged the write)
2020-05-24 05:53:03,238 [centos@10.0.226.168]: 
2020-05-24 05:53:03,238 [centos@10.0.226.168]:    at org.apache.cassandra.stress.Operation.error(Operation.java:141)
2020-05-24 05:53:03,238 [centos@10.0.226.168]:    at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
2020-05-24 05:53:03,238 [centos@10.0.226.168]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
2020-05-24 05:53:03,238 [centos@10.0.226.168]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
2020-05-24 05:53:03,238 [centos@10.0.226.168]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
2020-05-24 05:53:03,238 [centos@10.0.226.168]:    at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
2020-05-24 05:53:03,244 [centos@10.0.226.168]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required 
...
2020-05-24 06:04:04,417 com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2020-05-24 06:04:04,417 com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 0 acknowledged the write)
2020-05-24 06:04:04,417 java.lang.RuntimeException: Failed to execute stress action
2020-05-24 06:04:04,417   at org.apache.cassandra.stress.StressAction.run(StressAction.java:101)
2020-05-24 06:04:04,417   at org.apache.cassandra.stress.Stress.run(Stress.java:143)
2020-05-24 06:04:04,417   at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

On the Grafana dashboard we see write timeouts and failures:
![image](https://user-images.githubusercontent.com/5269241/82838896-4b325080-9ed6-11ea-820f-ff800856c57e.png)

**Comment by bentsi** [comment]
the same issue happened on another run on the same Scylla version but after different Nemesis called `RejectInterNodeNetwork` that blocks internode communication port 7000/7001:
```
sdcm.nemesis.ChaosMonkey: RejectInterNodeNetwork: every packet that belongs to inter node communication connections (port=7000 and 7001) will be rejected with icmp-net-unreachable for 60s
< t:2020-05-22 04:27:08,100 f:nemesis.py      l:1701 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: RejectInterNodeNetwork: executed: sudo iptables -t filter -A INPUT -p tcp --dport 7000  -j REJECT --reject-with icmp-net-unreachable
```

**Comment by juliayakovlev** [comment]
Same problem received with Scylla version ```4.0.1-0.20200524.8d9bc57aca6 with build-id 778b5fddea1d144ace993fe09de0ef6f050bafe6``` (ami-0b5e73fd332621b16, eu-west-1)

Nemesis: RejectInterNodeNetwork

```
< t:2020-05-25 05:00:09,846 f:nemesis.py      l:400  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: RejectInterNodeNetwork: every packet that belongs to inter node communication connections (port=7000 and 7001) will be reject
ed with icmp-proto-unreachable for 120s
< t:2020-05-25 05:00:10,064 f:nemesis.py      l:1698 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: RejectInterNodeNetwork: executed: sudo iptables -t filter -A INPUT -p tcp --dport 7000  -j REJECT --reject-with icmp-proto-un
reachable
```

A lot of WriteTimeoutException:
```
< t:2020-05-25 05:00:12,054 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.231.94]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```

And after 25 sec c-s reported about IOException and after about 2 minutes got a Prometheus error about high latency.

```
< t:2020-05-25 05:00:34,253 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.231.94]: java.io.IOException: Operation x10 on key(s) [31503431364d30304d30]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```
```
< t:2020-05-25 05:02:18,031 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > 2020-05-25 05:02:18.019: (PrometheusAlertManagerEvent Severity.ERROR): alert_name=CassandraStressWriteTooSlow type=start start=2020-05-25T05:02:09.591Z end=2020-05-25T05:05:09.591Z description=Cassandra Stress write latency more than 1000ms updated=2020-05-25T05:02:10.106Z state=active fingerprint=957463dc9da73884 labels={'alertname': 'CassandraStressWriteTooSlow', 'cassandra_stress_write': '0', 'cpu_idx': '0', 'instance': '10.0.231.94', 'job': 'sct_metrics', 'loader_idx': '0', 'monitor': 'scylla-monitor', 'sct_severity': 'ERROR', 'severity': '1', 'type': 'lat_perc_99'}
```

Load on one of loaders failed. 
![Screenshot from 2020-05-26 17-48-01](https://user-images.githubusercontent.com/34435448/82915200-1fb47200-9f79-11ea-97c1-54ae821ec810.png)


Write timeout on the node where the nemesis was run (red) and two other nodes (10.0.186.112 and 10.0.80.179):
![Screenshot from 2020-05-26 17-48-17](https://user-images.githubusercontent.com/34435448/82915373-4e324d00-9f79-11ea-8f1b-4767a1902bb8.png)

**Comment by slivne** [comment]
@bentsi / @juliayakovlev - the schema change and network issue are two different cases - please split them apart.

We need for the 7001 block network port issue
- schema (to check you have speculative retry) ...

**Comment by juliayakovlev** [comment]
> @bentsi / @juliayakovlev - the schema change and network issue are two different cases - please split them apart.
> 
> We need for the 7001 block network port issue
> 
> * schema (to check you have speculative retry) ...
> * Understand which node the network nemesis works on and which node you connect to by default ...
> 
> Can we please rerun this test with only this nemesis on 4.0.0 / 3.3.2 - I expect it may fail also on those versions.

3.3.2 [result](https://github.com/scylladb/scylla/issues/6522#issuecomment-635228616)
4.0.0 [result](https://github.com/scylladb/scylla/issues/6522#issuecomment-634568469)

**Comment by slivne** [comment]
@bentsi / @juliayakovlev - this issue is for the schema change not something else (https://github.com/scylladb/scylla/issues/6508#issue-624459250) 

@bhalevy I need help in looking at the logs and why all the traffic died on the schema change

**Comment by roydahan** [comment]
@juliayakovlev the results you posted aren't relevant to this issue.
This is about adding a new column.
we still not 100% sure that this nemesis is the cause of the issue, we need to run this nemesis alone on both versions and verify.

**Comment by juliayakovlev** [comment]
> @juliayakovlev the results you posted aren't relevant to this issue.
> This is about adding a new column.
> we still not 100% sure that this nemesis is the cause of the issue, we need to run this nemesis alone on both versions and verify.

Yes, I updated the relevant issue #6522  with details. Here I just answered to the question
