### ISSUE TITLE
scylla_setup script broken: scylla_ec2_check

### ISSUE THREAD

**Issue by pankajsoni19** [scylladb/scylla#6540]
*Installation details*
Scylla version (or git commit hash): 4.0.0
Cluster size: 1
OS: Ubuntu 18.04/Debian 10 Buster 64 Bit
AWS instance: t3a.[medium/micro] [ 2 cpu, 1-2 GB RAM]

```
Skip any of the following steps by answering 'no'
Do you want to run Amazon EC2 configuration check?
Yes - runs a script to verify that this instance is optimized for running Scylla. No - skips the configuration check.
[YES/no]YES
t3a doesn't support enhanced networking!
To enable enhanced networking, please use the instance type which supports it.
More documentation available at:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enabling_enhanced_networking
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_setup", line 255, in <module>
    run('{}/scylla_ec2_check --nic {}'.format(scriptsdir(), nic))
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_ec2_check', '--nic', 'ens5']' returned non-zero exit status 1.
```

while I can verify module is present `modinfo ena`

```
filename:       /lib/modules/4.19.0-9-cloud-amd64/kernel/drivers/net/ethernet/amazon/ena/ena.ko
version:        2.1.0K
license:        GPL
description:    Elastic Network Adapter (ENA)
author:         Amazon.com, Inc. or its affiliates
srcversion:     EB69610D42E0F943CEDCC0E
alias:          pci:v00001D0Fd0000EC21sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd0000EC20sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00001EC2sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00000EC2sv*sd*bc*sc*i*
depends:        
retpoline:      Y
intree:         Y
name:           ena
vermagic:       4.19.0-9-cloud-amd64 SMP mod_unload modversions 
sig_id:         PKCS#7
signer:         Debian Secure Boot CA
sig_key:        A7:46:8D:EF
sig_hashalgo:   sha256
signature:      A2:0A:DC:24:93:8B:26:80:43:F3:B8:9D:FE:DC:E3:A5:CD:B8:54:E1:
		BE:D3:38:E3:24:14:F3:2C:7F:6E:AE:24:24:10:EB:7A:54:91:52:84:
		DA:99:FD:1F:D7:D5:CD:2C:1B:FA:92:26:5D:06:45:ED:C6:D1:DC:FD:
		66:2C:5A:78:7D:5F:D0:92:75:C4:B2:D8:88:EA:CA:72:88:F0:49:B8:
		61:EA:19:A3:49:FE:45:BE:5B:D6:B7:98:98:2E:A6:FD:B0:C6:9D:BB:
		A6:25:AB:E0:2E:C4:66:A8:33:FE:C8:F2:C6:6F:A1:F4:95:F4:6A:D6:
		D2:A2:D5:36:48:94:2D:F3:42:A0:A8:AC:91:B6:3A:53:6D:53:D6:46:
		11:3E:B7:F8:8A:E6:19:BF:C9:00:E8:BB:59:78:46:29:EB:7C:C1:14:
		A7:14:62:BC:D4:56:9F:36:84:A0:81:C0:A3:E7:28:72:9D:1A:40:61:
		C4:7B:EC:A5:79:6C:D9:12:D4:59:3E:F3:C1:88:8A:C1:6C:14:33:3A:
		3F:BE:C9:BB:20:54:61:D8:7D:B0:62:59:CB:79:B2:68:5C:2A:E7:AA:
		D3:7F:63:A7:66:C3:76:21:70:AD:8C:E0:B7:12:63:A7:E2:E7:C6:2C:
		72:4B:69:57:12:05:FF:9A:76:25:8A:FA:4D:D2:A4:AD
parm:           debug:Debug level (0=none,...,16=all) (int)
```

and module is enabled on nic ` ethtool -i  ens5`

```
driver: ena
version: 2.1.0K
firmware-version: 
expansion-rom-version: 
bus-info: 0000:00:05.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

```

**Comment by slivne** [comment]
@pankajsoni19 you can run in dev-mode https://docs.scylladb.com/getting-started/install_scylla/dev_mod/

**Comment by avikivity** [comment]
Backported to 3.3, 4.0, 4.1.
