### ISSUE TITLE
scylla-gdb: failed to get coredump by gcore or debug scylla process

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6563]
*Installation details*
Scylla version (or git commit hash): 4.1.rc1-0.20200528.bb8fcbff68f
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): Scylla-branch-4.1-nightly-20200529213950 (ami-00907d577946117dd) (eu-west-1)

### Test info 
- job link: https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/longevity/job/longevity-1tb-7days/3
- test id: df994b68-ef2a-4cd0-9c1c-e32671ea1e8b

### Description

I tried to generate a coredump of scylla process by scylla-gdb, but failed.
Scylla process id is 10176. general gdb works well to get coredup or debug the scylla process, but scylla-gdb always failed.

#### Failed to get coredump of scylla process by `gcore from scylla-gdb`:

```
[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ sudo /opt/scylladb/bin/gcore  10176
BFD: BFD (GNU Binutils) 2.25.51 internal error, aborting at ../../bfd/elf64-x86-64.c line 5770 in elf_x86_64_get_plt_sym_val

BFD: Please report this bug.

gcore: failed to create core.10176
[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ echo $?
1
```

#### Successfully get coredump of scylla process by `gcore from general gdb`:
```
---------------------
[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ sudo /usr/bin/gcore 10176
Missing separate debuginfo for /opt/scylladb/libreloc/libthrift-0.10.0.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/01/497e36f8b0b72f7de5e517360ea43209586b92.debug
Missing separate debuginfo for /opt/scylladb/libreloc/libboost_system.so.1.69.0
...
Missing separate debuginfo for /opt/scylladb/libreloc/libprotobuf.so.17
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/a5/75b3a4a8c6201ed4c3c8166a20ee80968c39f9.debug
warning: File "/opt/scylladb/libreloc/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.
py".
To enable execution of this file add
        add-auto-load-safe-path /opt/scylladb/libreloc/libthread_db.so.1
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Missing separate debuginfo for /opt/scylladb/libreloc/libz.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/15/c953a2400b38f0df43eb838cd9d9fbfba4d379.debug
...
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/d8/e8af51a9cd5fff1353163cefa2fee92675686e.debug
Missing separate debuginfo for /opt/scylladb/libreloc/libgcrypt.so.20
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/18/971d5e2a1099bfe044f2e0485e1ac2827ffc31.debug
Missing separate debuginfo for /opt/scylladb/libreloc/libgpg-error.so.0
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/33/25103ec914b62bc3995fcede46d8369cd83e63.debug
warning: File "/opt/scylladb/libreloc/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
0x0000000002dbc275 in seastar::smp::poll_queues () at ./seastar/src/core/reactor.cc:3133
3133    ./seastar/src/core/reactor.cc: No such file or directory.
warning: target file /proc/10176/cmdline contained unexpected null characters
Saved corefile core.10176
[Inferior 1 (process 10176) detached]
[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ echo $?
0
```

#### Failed to decode the coredump by `gdb from scylla-gdb`:
```
[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ /opt/scylladb/bin/gdb /usr/lib/debug/opt/scylladb/libexec/scylla-4.1.rc1-0.20200528.bb8fcbff68f.x86_64.debug core.10176
GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/debug/opt/scylladb/libexec/scylla-4.1.rc1-0.20200528.bb8fcbff68f.x86_64.debug...done.

warning: core file may not match specified executable file.
[New LWP 10176]
Core was generated by `/usr/bin/scylla'.
#0  0x0000000002dbc275 in seastar::smp::poll_queues () at ./seastar/src/core/reactor.cc:3133
3133    ./seastar/src/core/reactor.cc: No such file or directory.
(gdb) bt
#0  0x0000000002dbc275 in seastar::smp::poll_queues () at ./seastar/src/core/reactor.cc:3133
#1  0x00007fff150f6400 in ?? ()
#2  0x00006000000c8008 in ?? ()
#3  0x00007fff150f6550 in ?? ()
#4  0x0000000000000000 in ?? ()

```

#### Failed to decode the coredump by `gdb from scylla-gdb`:
```
[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ /opt/scylladb/bin/gdb /opt/scylladb/libexec/scylla core.10176
GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/scylladb/libexec/scylla...Reading symbols from /usr/lib/debug/opt/scylladb/libexec/scylla-4.1.rc1-0.20200528.bb8fcbff68f.x86_64.debug...done.
done.
[New LWP 10176]
BFD: BFD (GNU Binutils) 2.25.51 internal error, aborting at ../../bfd/elf64-x86-64.c line 5770 in elf_x86_64_get_plt_sym_val

BFD: Please report this bug.

[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ echo $?
1
```

#### Successfully decode the coredump by `general gdb`:
```
[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ /usr/bin/gdb /opt/scylladb/libexec/scylla core.10176
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-119.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/scylladb/libexec/scylla...Reading symbols from /usr/lib/debug/opt/scylladb/libexec/scylla-4.1.rc1-0.20200528.bb8fcbff68f.x86_64.debug...done.
done.
[New LWP 10176]
Missing separate debuginfo for /opt/scylladb/libreloc/libthrift-0.10.0.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/01/497e36f8b0b72f7de5e517360ea43209586b92.debug
....
warning: File "/opt/scylladb/libreloc/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `/usr/bin/scylla'.
#0  0x0000000002dbc275 in seastar::smp::poll_queues () at ./seastar/src/core/reactor.cc:3133
3133    ./seastar/src/core/reactor.cc: No such file or directory.
(gdb) bt
#0  0x0000000002dbc275 in seastar::smp::poll_queues () at ./seastar/src/core/reactor.cc:3133
#1  0x0000000002e11dc6 in seastar::reactor::smp_pollfn::poll (this=<optimized out>) at ./seastar/src/core/reactor.cc:2410
#2  0x0000000002daabbd in poll_once (this=<optimized out>) at ./seastar/src/core/reactor.cc:2817
#3  operator() (__closure=0x7fff150f6550) at ./seastar/src/core/reactor.cc:2715
#4  std::_Function_handler<bool(), seastar::reactor::run()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/9/bits/std_function.h:285
#5  0x0000000002de7bc9 in operator() (this=0x7fff150f6550) at /usr/include/c++/9/bits/std_function.h:683
#6  seastar::reactor::run (this=0x6000003ae000) at ./seastar/src/core/reactor.cc:2741
#7  0x0000000002d5241a in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fff150f6d00, ac=ac@entry=24,
    av=av@entry=0x7fff150f7048,
    func=func@entry=<unknown type in /usr/lib/debug/opt/scylladb/libexec/scylla-4.1.rc1-0.20200528.bb8fcbff68f.x86_64.debug, CU 0x3f1ed09c, DIE 0x3f2da7f2>)
    at ./seastar/include/seastar/core/reactor.hh:736
#8  0x0000000002d534cf in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) (this=this@entry=0x7fff150f6d00, ac=ac@entry=24,
    av=av@entry=0x7fff150f7048,
    func=func@entry=<unknown type in /usr/lib/debug/opt/scylladb/libexec/scylla-4.1.rc1-0.20200528.bb8fcbff68f.x86_64.debug, CU 0x3f1ed09c, DIE 0x3f2b174f>)
    at /usr/include/c++/9/bits/std_function.h:87
#9  0x0000000000d24ae7 in main () at /usr/include/c++/9/bits/std_function.h:87
#10 0x00007fd96c6381a3 in __libc_start_main () from /opt/scylladb/libreloc/libc.so.6
#11 0x0000000000c4a02e in _start ()
(gdb) info threads
  Id   Target Id         Frame
* 1    LWP 10176         0x0000000002dbc275 in seastar::smp::poll_queues () at ./seastar/src/core/reactor.cc:3133
```

#### Failed to debug running scylla process by `scylla-gdb`:
```
[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ sudo /opt/scylladb/bin/gdb -p 10176
GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 10176
Reading symbols from /opt/scylladb/libexec/scylla...Reading symbols from /usr/lib/debug/opt/scylladb/libexec/scylla-4.1.rc1-0.20200528.bb8fcbff68f.x86_64.debug...done.
done.
Reading symbols from /opt/scylladb/libreloc/libthrift-0.10.0.so...BFD: BFD (GNU Binutils) 2.25.51 internal error, aborting at ../../bfd/elf64-x86-64.c line 5770 in elf_x86_64_get_plt_sym_val

BFD: Please report this bug.

[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ echo $?
1
```

#### Successfully debug running scylla process by `general gdb`:
```
[centos@longevity-tls-1tb-7d-4-1-db-node-df994b68-2 core]$ sudo /usr/bin/gdb -p 10176
Loaded symbols for /opt/scylladb/libreloc/libgpg-error.so.0

warning: File "/opt/scylladb/libreloc/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
0x0000000002e23d53 in operator-= (desc=..., this=0x600000101578) at ./seastar/src/core/fair_queue.cc:158
158     ./seastar/src/core/fair_queue.cc: No such file or directory.
(gdb) bt
#0  0x0000000002e23d53 in operator-= (desc=..., this=0x600000101578) at ./seastar/src/core/fair_queue.cc:158
#1  seastar::fair_queue::notify_requests_finished (this=0x600000101558, desc=...) at ./seastar/src/core/fair_queue.cc:158
#2  0x00000000030720eb in seastar::io_queue::process_completions (this=<optimized out>) at /usr/include/c++/9/bits/move.h:149
#3  0x0000000002e0496c in reap_kernel_completions (this=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:360
#4  seastar::reactor::reap_kernel_completions_pollfn::poll (this=<optimized out>) at ./seastar/src/core/reactor.cc:2315
#5  0x0000000002daabbd in poll_once (this=<optimized out>) at ./seastar/src/core/reactor.cc:2817
#6  operator() (__closure=0x7fff150f6550) at ./seastar/src/core/reactor.cc:2715
#7  std::_Function_handler<bool(), seastar::reactor::run()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/9/bits/std_function.h:285
#8  0x0000000002de7bc9 in operator() (this=0x7fff150f6550) at /usr/include/c++/9/bits/std_function.h:683
#9  seastar::reactor::run (this=0x6000003ae000) at ./seastar/src/core/reactor.cc:2741
#10 0x0000000002d5241a in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fff150f6d00, ac=ac@entry=24,
    av=av@entry=0x7fff150f7048,
    func=func@entry=<unknown type in /usr/lib/debug/opt/scylladb/libexec/scylla-4.1.rc1-0.20200528.bb8fcbff68f.x86_64.debug, CU 0x3f1ed09c, DIE 0x3f2da7f2>)
    at ./seastar/include/seastar/core/reactor.hh:736
#11 0x0000000002d534cf in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) (this=this@entry=0x7fff150f6d00, ac=ac@entry=24,
    av=av@entry=0x7fff150f7048,
    func=func@entry=<unknown type in /usr/lib/debug/opt/scylladb/libexec/scylla-4.1.rc1-0.20200528.bb8fcbff68f.x86_64.debug, CU 0x3f1ed09c, DIE 0x3f2b174f>)
    at /usr/include/c++/9/bits/std_function.h:87
#12 0x0000000000d24ae7 in main () at /usr/include/c++/9/bits/std_function.h:87
#13 0x00007fd96c6381a3 in __libc_start_main () from /opt/scylladb/libreloc/libc.so.6
#14 0x0000000000c4a02e in _start ()
(gdb) info threads
  Id   Target Id         Frame
* 1    process 10176 "scylla" 0x0000000002e23d53 in operator-= (desc=..., this=0x600000101578) at ./seastar/src/core/fair_queue.cc:158
(gdb)
```

/CC @roydahan @slivne

**Comment by slivne** [comment]
@avikivity are we using scylla-gdb anymore ? I think we moved to use the gdb comming from fedora - parallel to the tool-chain

**Comment by avikivity** [comment]
CentOS 7 gdb is too old to be used.

We have two options:
 - not debug codes on nodes
 - package gdb in the relocatable package (@syuu1228 had something for it)

I think we should just avoid using gdb on a node. Things like gcore are too disruptive. If you want a core, send SIGABRT and copy it to another machine for debugging.

**Comment by denesb** [comment]
Doesn't the devtoolset-toolchain bring in a sufficiently recent debugger. I remember in a previous life we used the devtoolset to use more recent gcc and gdb on centos7.

**Comment by avikivity** [comment]
It's not exactly yound but may be good enough.
