### ISSUE TITLE
scylla_setyp on Ubuntu 16 / GCE fails

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6636]
*Installation details*
Scylla version (or git commit hash): 4.0
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):  GCE n1-standard-2 (2 vCPUs, 7.5 GB memory)

RAID step of scylla_setup fails:

```
Please select unmounted disks from the following list: ['/dev/sda14']
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: []
> /dev/sda14
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: ['/dev/sda14']
> done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mdadm is already the newest version (3.3-2ubuntu7.6).
xfsprogs is already the newest version (4.3.0+nmu1ubuntu1.1).
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Creating XFS volume for scylla using 1 disk(s): /dev/sda14
agsize (1024 blocks) too small, need at least 4096 blocks
Usage: mkfs.xfs
/* blocksize */         [-b log=n|size=num]
/* metadata */          [-m crc=0|1,finobt=0|1,uuid=xxx]
/* data subvol */       [-d agcount=n,agsize=n,file,name=xxx,size=num,
                            (sunit=value,swidth=value|su=num,sw=num|noalign),
                            sectlog=n|sectsize=num
/* force overwrite */   [-f]
/* inode size */        [-i log=n|perblock=n|size=num,maxpct=n,attr=0|1|2,
                            projid32bit=0|1,sparse=0|1]
/* no discard */        [-K]
/* log subvol */        [-l agnum=n,internal,size=num,logdev=xxx,version=n
                            sunit=value|su=num,sectlog=n|sectsize=num,
                            lazy-count=0|1]
/* label */             [-L label (maximum 12 characters)]
/* naming */            [-n log=n|size=num,version=2|ci,ftype=0|1]
/* no-op info only */   [-N]
/* prototype file */    [-p fname]
/* quiet */             [-q]
/* realtime subvol */   [-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */        [-s log=n|size=num]
/* version */           [-V]
                        devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 121, in <module>
    run('mkfs.xfs {} -f -K'.format(fsdev))
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mkfs.xfs', '/dev/sda14', '-f', '-K']' returned non-zero exit status 1.
RAID setup failed. Press any key to continue...
```

**Comment by avikivity** [comment]
I'm guessing that /dev/sda14 does not exist (and was misdetected somehow).

**Comment by syuu1228** [comment]
@avikivity I found that they actually created such strange partition number for bios boot region and UEFI boot, I guess why mkfs.xfs fails is because sda14 is too small (looks like it only 4194kb).

It seems has partition type uuid "21686148-6449-6e6f-744e-656564454649" = "BIOS boot partition", we can avoid listing up such partition.
Maybe EFI partition need to skip, too.
 
```
syuu@takuya-ubuntu16-1:~$ sudo parted /dev/sda
GNU Parted 3.2
Using /dev/sda
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) p                                                                
Model: Google PersistentDisk (scsi)
Disk /dev/sda: 10.7GB
Sector size (logical/physical): 512B/4096B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name  Flags
14      1049kB  5243kB  4194kB                     bios_grub
15      5243kB  116MB   111MB   fat32              boot, esp
 1      116MB   10.7GB  10.6GB  ext4

syuu@takuya-ubuntu16-1:~$ lsblk -o NAME,PARTTYPE
NAME    PARTTYPE
sda     
|-sda14 21686148-6449-6e6f-744e-656564454649
|-sda15 c12a7328-f81f-11d2-ba4b-00a0c93ec93b
`-sda1  0fc63daf-8483-4772-8e79-3d69d8477de4
```

referenced: https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs

**Comment by syuu1228** [comment]
We probably also can limit listing by partition size, we cannot use such very small partition anyway.

**Comment by avikivity** [comment]
Agree about filtering by partition types.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
