### ISSUE TITLE
setup fails: scylla fails to identify recognize swap

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#6650]
*Installation details*
Scylla version (or git commit hash): 666.development_20200615.eda80cbb05e
Cluster size:1
Instance type: n1-standard-2

The artifact tests of centos7, debian9, debian10, ubuntu1604, ubuntu1804 failed during setup due to scylla failing to acknowledge the swap disk of the node:
```
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 '

Exit code: 1

Stdout:

tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
node_exporter successfully installed
This computer doesn't supported CPU scaling configuration.
Setting up swapspace version 1, size = 1953120 KiB
no label, UUID=dda66a1c-864c-446b-820a-f61bf58d3129
ESC[1;31mNo swap is configured, it is highly recommended to setup swap on Scylla node.ESC[0m
swap setup failed.
```
Logs:
centos 7:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id e6e1d13a-d223-4342-b760-2a9732ab9393                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200614_234711 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/e6e1d13a-d223-4342-b760-2a9732ab9393/20200614_234711/db-cluster-e6e1d13a.zip |
| 20200614_234711 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/e6e1d13a-d223-4342-b760-2a9732ab9393/20200614_234711/sct-runner-e6e1d13a.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```
debian 9:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id 542f7f3f-931d-454f-8e35-78d6a295668c                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200614_233541 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/542f7f3f-931d-454f-8e35-78d6a295668c/20200614_233541/db-cluster-542f7f3f.zip |
| 20200614_233541 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/542f7f3f-931d-454f-8e35-78d6a295668c/20200614_233541/sct-runner-542f7f3f.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```
debian 10:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id 661360bb-0b7c-4481-b805-bf7ac8560971                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200614_233643 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/661360bb-0b7c-4481-b805-bf7ac8560971/20200614_233643/db-cluster-661360bb.zip |
| 20200614_233643 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/661360bb-0b7c-4481-b805-bf7ac8560971/20200614_233643/sct-runner-661360bb.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```
ubuntu 16:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id d969b580-683c-4bd8-9a15-d007b15abd7b                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200614_233421 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/d969b580-683c-4bd8-9a15-d007b15abd7b/20200614_233421/db-cluster-d969b580.zip |
| 20200614_233421 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/d969b580-683c-4bd8-9a15-d007b15abd7b/20200614_233421/sct-runner-d969b580.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```
ubuntu 18:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id d8aa2707-ca0e-42e0-838b-9912af8b6902                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200614_233539 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/d8aa2707-ca0e-42e0-838b-9912af8b6902/20200614_233539/db-cluster-d8aa2707.zip |
| 20200614_233539 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/d8aa2707-ca0e-42e0-838b-9912af8b6902/20200614_233539/sct-runner-d8aa2707.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```

**Comment by syuu1228** [comment]
Fmm, my local test does not reproduce the issue, I think we need more information to reproduce the issue, something like Dockerfile or shell script or VM image, log, workplace archive... etc

**Comment by roydahan** [comment]
@syuu1228 it happens for us when running on GCE instances, not docker or VM.
We just choose a plain image on GCE running on n1-standard-2 with local_ssd

**Comment by syuu1228** [comment]
It seems like because fallocate created sparse file, XFS does not able to swapon on such file (but ext4 works with same file):
https://bugzilla.redhat.com/show_bug.cgi?id=1129205

Getting a kernel message "swapon: swapfile has holes", which means it's sparse file and cannot use it:
```
[vagrant@localhost ~]$ mount|grep /dev/vda
/dev/vda1 on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
[vagrant@localhost ~]$ sudo systemctl status swapfile.swap
● swapfile.swap - swapfile
   Loaded: loaded (/etc/systemd/system/swapfile.swap; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-06-17 03:40:29 UTC; 31s ago
     What: /swapfile
  Process: 964 ExecActivate=/sbin/swapon /swapfile (code=exited, status=255)

Jun 17 03:40:29 localhost.localdomain systemd[1]: Activating swap swapfile...
Jun 17 03:40:29 localhost.localdomain swapon[964]: swapon: /swapfile: swapon failed: Invalid argument
Jun 17 03:40:29 localhost.localdomain systemd[1]: swapfile.swap swap process exited, code=exited status=255
Jun 17 03:40:29 localhost.localdomain systemd[1]: Failed to activate swap swapfile.
Jun 17 03:40:29 localhost.localdomain systemd[1]: Unit swapfile.swap entered failed state.

[vagrant@localhost ~]$ dmesg|grep "swapon"
[   24.906453] swapon: swapfile has holes
```

But, since it only affects XFS system, the error on Debian & Ubuntu may different problem (CentOS7 is XFS by default).

**Comment by ShlomiBalalis** [comment]
We've experienced the issue again in the debian artifact jobs:
```
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 '

Exit code: 1

Stdout:

tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
node_exporter successfully installed
This computer doesn't supported CPU scaling configuration.
Setting up swapspace version 1, size = 2 GiB (2147479552 bytes)
no label, UUID=a3bc6257-61fc-4ae0-918c-632bd1524d83
ESC[1;31mNo swap is configured, it is highly recommended to setup swap on Scylla node.ESC[0m
swap setup failed.

Stderr:


```
The build the jobs used, for example http://downloads.scylladb.com/deb/unstable/unified/master/2020-06-18T22:18:11Z/, seem to already include #6661 , especially since the centos jobs passed with no issue.

The failed jobs' logs:
artifacts-debian9-test
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id c9970242-16f1-4087-9e7e-066e844a4f82                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200619_225241 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/c9970242-16f1-4087-9e7e-066e844a4f82/20200619_225241/db-cluster-c9970242.zip |
| 20200619_225241 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/c9970242-16f1-4087-9e7e-066e844a4f82/20200619_225241/sct-runner-c9970242.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```
artifacts-debian10-test
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id 8db793cb-b24f-4cfa-8469-af07cf4932ae                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200619_225343 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/8db793cb-b24f-4cfa-8469-af07cf4932ae/20200619_225343/db-cluster-8db793cb.zip |
| 20200619_225343 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/8db793cb-b24f-4cfa-8469-af07cf4932ae/20200619_225343/sct-runner-8db793cb.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```
artifacts-ubuntu1604-test
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id dc8e0781-1088-4fe3-a67e-42d0b82c498d                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200619_225143 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/dc8e0781-1088-4fe3-a67e-42d0b82c498d/20200619_225143/db-cluster-dc8e0781.zip |
| 20200619_225143 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/dc8e0781-1088-4fe3-a67e-42d0b82c498d/20200619_225143/sct-runner-dc8e0781.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```
artifacts-ubuntu1804-test
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id 7a50e649-ac77-46cf-91cc-abb84f57b9ec                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200619_225356 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/7a50e649-ac77-46cf-91cc-abb84f57b9ec/20200619_225356/db-cluster-7a50e649.zip |
| 20200619_225356 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/7a50e649-ac77-46cf-91cc-abb84f57b9ec/20200619_225356/sct-runner-7a50e649.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```

**Comment by syuu1228** [comment]
> We've experienced the issue again in the debian artifact jobs:

Okay, then it's different issue with #6661. I will try to reproduce it on Debian/Ubuntu.

**Comment by syuu1228** [comment]
I think I found it:
```
No swap is configured, it is highly recommended to setup swap on Scylla node.
5+0 records in
5+0 records out
5368709120 bytes (5.4 GB, 5.0 GiB) copied, 7.25803 s, 740 MB/s
Setting up swapspace version 1, size = 5 GiB (5368705024 bytes)
no label, UUID=038bf3c4-9922-4845-bc6b-998db9b17244
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_swap_setup", line 60, in <module>
    swapunit_bn = out('/usr/bin/systemd-escape -p --suffix=swap {}'.format(swapfile))
  File "/opt/scylladb/scripts/scylla_util.py", line 352, in out
    return subprocess.check_output(cmd, shell=shell, env=scylla_env, timeout=timeout).strip().decode('utf-8')
  File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/systemd-escape'
swap setup failed.
vagrant@ubuntu1804:~$ which systemd-escape
/bin/systemd-escape
vagrant@ubuntu1804:~$ ls /usr/bin/systemd-escape
ls: cannot access '/usr/bin/systemd-escape': No such file or directory
vagrant@ubuntu1804:~$ ls /bin/systemd-escape
/bin/systemd-escape
```

**Comment by avikivity** [comment]
I thought /bin was a symlink to /usr/bin.

**Comment by avikivity** [comment]
Minor, not backporting.
