### ISSUE TITLE
alternator test_dynamo_types: items are missing

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6652]
Regression seen in https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/524/testReport/alternator_tests/AlternatorTest/test_dynamo_types/
Scylla version ecc83e83e586c10271f8e08946103cfc10995d62

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/alternator_tests.py", line 396, in test_dynamo_types
    self.assertTrue(expr=not diff, msg=f"The following items are missing:\n{pformat(diff)}")
  File "/usr/lib64/python3.7/unittest/case.py", line 722, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : The following items are missing:
{'iterable_item_removed': {'root[42]': {'binary': {'binary': Binary(b'J\\K"Z%1,9k`oEu80`>E'),
                                                   'hash_key': 'test48'},
                                        'bool': {'bool': False,
                                                 'hash_key': 'test45'},
                                        'hash_key': 'test44',
                                        'list': {'hash_key': 'test49',
                                                 'list': [{'hash_key': 'test49',
                                                           'string': "Z.1ONywkzi'`gs7\\/:"},
                                                          {'binary': Binary(b'3!U/'),
                                                           'hash_key': 'test50'},
                                                          {'hash_key': 'test51',
                                                           'number': Decimal('0')},
                                                          {'bool': True,
                                                           'hash_key': 'test52'},
                                                          {'hash_key': 'test53',
                                                           'none': None},
                                                          {'hash_key': 'test54',
                                                           'string': "+=,nax6oZ.>'/Y~,PjF?TK8:A2E"},
                                                          {'binary': Binary(b'kT.w["Y0v=rvA=lx,'),
                                                           'hash_key': 'test55'},
                                                          {'hash_key': 'test56',
                                                           'number': 710},
                                                          {'bool': True,
                                                           'hash_key': 'test57'},
                                                          {'hash_key': 'test58',
                                                           'none': None},
                                                          {'hash_key': 'test59',
                                                           'string': 't/Ye'},
                                                          {'binary': Binary(b'&O&K'),
                                                           'hash_key': 'test60'},
                                                          {'hash_key': 'test61',
                                                           'number': Decimal('0')},
                                                          {'bool': True,
                                                           'hash_key': 'test62'},
                                                          {'hash_key': 'test63',
                                                           'none': None}]},
                                        'none': {'hash_key': 'test46',
                                                 'none': None},
                                        'number': {'hash_key': 'test44',
                                                   'number': 839},
                                        'string': {'hash_key': 'test47',
                                                   'string': 'bS6m)]%AJDD_=Mu[0'}},
                           'root[43]': {'binary': {'binary': Binary(b'+>6P-8mVg0H^P8q`<(P/+wwN'),
                                                   'hash_key': 'test49'},
                                        'bool': {'bool': True,
                                                 'hash_key': 'test46'},
                                        'hash_key': 'test45',
                                        'list': {'hash_key': 'test50',
                                                 'list': [{'binary': Binary(b'Vk&'),
                                                           'hash_key': 'test50'},
                                                          {'hash_key': 'test51',
                                                           'number': Decimal('0')},
                                                          {'bool': False,
                                                           'hash_key': 'test52'},
                                                          {'hash_key': 'test53',
                                                           'none': None},
                                                          {'hash_key': 'test54',
                                                           'string': 'BA['},
                                                          {'binary': Binary(b'u94qaV<sC!('),
                                                           'hash_key': 'test55'}]},
                                        'none': {'hash_key': 'test47',
                                                 'none': None},
                                        'number': {'hash_key': 'test45',
                                                   'number': Decimal('0')},
                                        'string': {'hash_key': 'test48',
                                                   'string': 'Zm25m4#-mi^;wXJ\\aY7>>7'}},
                           'root[44]': {'binary': {'binary': Binary(b'?m+$'),
                                                   'hash_key': 'test50'},
                                        'bool': {'bool': False,
                                                 'hash_key': 'test47'},
                                        'hash_key': 'test46',
                                        'list': {'hash_key': 'test51',
                                                 'list': [{'hash_key': 'test51',
                                                           'number': Decimal('0')},
                                                          {'bool': True,
                                                           'hash_key': 'test52'},
                                                          {'hash_key': 'test53',
                                                           'none': None},
                                                          {'hash_key': 'test54',
                                                           'string': 'p.k'},
                                                          {'binary': Binary(b'ykY'),
                                                           'hash_key': 'test55'},
                                                          {'hash_key': 'test56',
                                                           'number': 635},
                                                          {'bool': False,
                                                           'hash_key': 'test57'},
                                                          {'hash_key': 'test58',
                                                           'none': None},
                                                          {'hash_key': 'test59',
                                                           'string': '->p}Ty{@'},
                                                          {'binary': Binary(b'PCyvNH+:n{}{=$,f-!POv"Ly'),
                                                           'hash_key': 'test60'},
                                                          {'hash_key': 'test61',
                                                           'number': Decimal('0')},
                                                          {'bool': False,
                                                           'hash_key': 'test62'},
                                                          {'hash_key': 'test63',
                                                           'none': None},
                                                          {'hash_key': 'test64',
                                                           'string': 'W'},
                                                          {'binary': Binary(b'(0k[M5q>k5'),
                                                           'hash_key': 'test65'},
                                                          {'hash_key': 'test66',
                                                           'number': 41},
                                                          {'bool': True,
                                                           'hash_key': 'test67'},
                                                          {'hash_key': 'test68',
                                                           'none': None},
                                                          {'hash_key': 'test69',
                                                           'string': 'BC}QdaJx-.M&(R:'},
                                                          {'binary': Binary(b"lI3pDXr\\@A<>O&n7H{r'<"),
                                                           'hash_key': 'test70'},
                                                          {'hash_key': 'test71',
                                                           'number': Decimal('0')},
                                                          {'bool': True,
                                                           'hash_key': 'test72'},
                                                          {'hash_key': 'test73',
                                                           'none': None},
                                                          {'hash_key': 'test74',
                                                           'string': 'SN#i\\b9yacf4X@-('},
                                                          {'binary': Binary(b"TM:'>"),
                                                           'hash_key': 'test75'},
                                                          {'hash_key': 'test76',
                                                           'number': 298},
                                                          {'bool': True,
                                                           'hash_key': 'test77'}]},
                                        'none': {'hash_key': 'test48',
                                                 'none': None},
                                        'number': {'hash_key': 'test46',
                                                   'number': 733},
                                        'string': {'hash_key': 'test49',
                                                   'string': '{)(RI0i|;!=Iw4<3'}}}}
```

**Comment by bhalevy** [comment]
Cc @psarna could this be related to your latest changes?
45bf039357 alternator: use has_function instead of try-catch
911dee5417 schema: add has_column utility function
b1684cf2e1 alternator: move function handlers to a lookup map
e76fba6f86 alternator: remove outdated TODO for adding timeouts

**Comment by psarna** [comment]
Sounds likely, but I wonder why such an issue wouldn't be caught by unit tests... I'll investigate.

**Comment by psarna** [comment]
Hm, now that I looked at the function it doesn't sound that likely anymore, since the test doesn't seem to use functions at all...

**Comment by psarna** [comment]
At first, this test failed for me for two unrelated reasons.
1. looks like the mypy dynamodb library changed in Python 3.8:
```
  File "/home/sarna/repo/scylla-dtest/alternator_tests.py", line 17, in <module>
    from alternator_utils import TesterAlternator, ALTERNATOR_SNAPSHOT_FOLDER, TABLE_NAME, NUM_OF_ITEMS, random_string, \
  File "/home/sarna/repo/scylla-dtest/alternator_utils.py", line 14, in <module>
    from mypy_boto3_dynamodb.type_defs import AttributeValueTypeDef
ImportError: cannot import name 'AttributeValueTypeDef' from 'mypy_boto3_dynamodb.type_defs' (/home/sarna/.local/lib/python3.8/site-packages/mypy_boto3_dynamodb/type_defs.py)
```
2. It always failed with "address already taken", until I manually changed the number of nodes to 1 and this line:
```diff
- node1, node2, node3 = self.cluster.nodelist()
+ node1 = self.cluster.nodelist()[0]
```
... after which it always passed. (always == 3 times in a row)

This scenario doesn't seem related to using functions for calculating values, so I think it's an unrelated failure - maybe the test is flaky?

**Comment by nyh** [comment]
I think this is a test bug: It writes data and then uses `compare_table_data()` to read it back and expect the same items, but, this function uses `scan_table()` which doesn't seem to use ConsistentRead=True. If it doesn't, it can't expect to be able to immediately read back the data. Sometimes it will (like @psarna saw), sometimes it won't. We should add the consistent read option.
@Orenef11 please look into this (and we should probably close this issue).

**Comment by psarna** [comment]
True, that would also explain why the test always passed for me, since I changed it to use only a single node, otherwise it won't boot locally. `ConsistentRead=True` is definitely needed.

**Comment by nyh** [comment]
By the way, the Alternator unit tests (test/alternator in scylla.git) also forgot ConsistentRead=True in some of the tests, and I just sent two patches to fix them (@psarna please review). We never noticed this in practice, because we rarely run those tests on a multi-node cluster, and even when we do, it is even rarer for the timing and request routing to be such that a read doesn't see what it wrote.

**Comment by Orenef11** [comment]
> ConsistentRead

Thanks, I added it to test :-)

**Comment by Orenef11** [comment]
> By the way, the Alternator unit tests (test/alternator in scylla.git) also forgot ConsistentRead=True in some of the tests, and I just sent two patches to fix them (@psarna please review). We never noticed this in practice, because we rarely run those tests on a multi-node cluster, and even when we do, it is even rarer for the timing and request routing to be such that a read doesn't see what it wrote.

After the tests are fixed, can the bug be closed?

**Comment by nyh** [comment]
Yes, but I don't know how do we conclude if the tests are fixed. Do we wait for one successful dtest run? @bhalevy?
We can always close and reopen if the problem re-appears...

**Comment by Orenef11** [comment]
> Yes, but I don't know how do we conclude if the tests are fixed. Do we wait for one successful dtest run? @bhalevy?
> We can always close and reopen if the problem re-appears...

I would rather close and open the bug that it will stay open and another two months we will ask why it is still open...

**Comment by bhalevy** [comment]
> Yes, but I don't know how do we conclude if the tests are fixed. Do we wait for one successful dtest run? @bhalevy?
> We can always close and reopen if the problem re-appears...

Yes, by convention the bugs are closed as soon as the fix is merged.
Naturally, we can reopen as needed.

It'd be nice to run the test fix against master using  [dtest-byo](https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/build?delay=0sec) to verify it even before merging to next.
