### ISSUE TITLE
remove_node_during_mv_insert_4_nodes_test dtest failed in debug mode: registering metrics twice for metrics: storage_proxy_coordinator_background_replica_writes_failed_remote_node

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6667]
Scylla version 8628ede009b339205e26b680c4e95c601fa38a6a

Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/197/testReport/materialized_views_test/TestMaterializedViews/remove_node_during_mv_insert_4_nodes_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 162, in remove_node_during_mv_insert_4_nodes_test
    self._run_node_failure_during_mv_stress_insert(rf=3, nodes=4, node_action='remove', exclude_errors=['mutation_write_timeout_exception'])
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 240, in _run_node_failure_during_mv_stress_insert
    self.eventually(lambda: self._validate_cs_results(node1, exclude_errors, node_action, double_failure))
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 54, in eventually
    return fun()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 240, in <lambda>
    self.eventually(lambda: self._validate_cs_results(node1, exclude_errors, node_action, double_failure))
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 330, in _validate_cs_results
    self.check_errors(node, exclude_errors)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/dtest.py", line 1226, in check_errors
    assert False, '\n'.join(list(errors))
AssertionError: ERROR 2020-06-17 23:04:09,526 [shard 1] storage_proxy - Failed to obtain stats (seastar::metrics::double_registration (registering metrics twice for metrics: storage_proxy_coordinator_background_replica_writes_failed_remote_node)), fall-back to dummy
ERROR 2020-06-17 23:04:09,520 [shard 1] storage_proxy - Failed to obtain stats (seastar::metrics::double_registration (registering metrics twice for metrics: storage_proxy_coordinator_background_replica_writes_failed_remote_node)), fall-back to dummy
ERROR 2020-06-17 23:04:09,565 [shard 0] storage_proxy - Failed to obtain stats (seastar::metrics::double_registration (registering metrics twice for metrics: storage_proxy_coordinator_background_replica_writes_failed_remote_node)), fall-back to dummy
...
```

**Comment by bhalevy** [comment]
@xemul can you please look into this?

**Comment by xemul** [comment]
@bhalevy , this is dup of #5697 . Last time it crashed (#5985), but it was workarounded with commit 513ce1e6, and the messages about double registration are present in logs.

**Comment by bhalevy** [comment]
Duplicate of #5697
Closing...
