### ISSUE TITLE
scylla_setup: "apt-get install -y hugepages" fails on Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#6673]
Seems like "hugepages" package does not exists on Ubuntu 20.04LTS.
See: https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=hugepages
Related: #6343
```
ScyllaDB setup finished.
scylla_setup accepts command line arguments as well! For easily provisioning in a similar environment than this, type:

    scylla_setup --no-raid-setup

Also, to avoid the time-consuming I/O tuning you can add --no-io-setup and copy the contents of /etc/scylla.d/io*
Only do that if you are moving the files into machines with the exact same hardware
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hugepages
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_setup", line 472, in <module>
    run('apt-get install -y hugepages')
  File "/opt/scylladb/scripts/scylla_util.py", line 342, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'install', '-y', 'hugepages']' returned non-zero exit status 100.

```

**Comment by syuu1228** [comment]
Looks like it renamed to libhugetlbfs-bin:
 https://packages.ubuntu.com/focal/libhugetlbfs-bin

We don't need this for non-dpdk mode, anyway.

**Comment by syuu1228** [comment]
Note: we might able to install it in scylla_prepare instead of scylla_setup, since it only for dpdk mode.

**Comment by avikivity** [comment]
Backported to 4.2. 4.1 and below don't use python3-distro, so not touching them.
