### ISSUE TITLE
test_parallel_operations_create_list_clear_for_all_ks: Assertion `_u.st == state::future' failed.

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6709]
I'm not sure if the bug is in scylla or in seastar.

Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/531/testReport/snapshot_test/TestParallelSnapshotOperations/test_parallel_operations_create_list_clear_for_all_ks/
```
Error Message
Critical errors found: [('node1', ["scylla: /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:445: void seastar::future_state_base::set_exception(std::__exception_ptr::exception_ptr&&): Assertion `_u.st == state::future' failed.", 'Aborting on shard 1.'])]
Other errors: []
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1085, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1127, in cleanUpCluster
    raise AssertionError('Critical errors found: {}\nOther errors: {}'.format(critical_errors, found_errors))
AssertionError: Critical errors found: [('node1', ["scylla: /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:445: void seastar::future_state_base::set_exception(std::__exception_ptr::exception_ptr&&): Assertion `_u.st == state::future' failed.", 'Aborting on shard 1.'])]
Other errors: []
Standard Output
Moving core file /jenkins/workspace/scylla-master/dtest-release/scylla-dtest/reactor-1.4482.1592966720.core to /jenkins/workspace/scylla-master/dtest-release/scylla-dtest/logs-release.2/1592966721133_snapshot_test.TestParallelSnapshotOperations.test_parallel_operations_create_list_clear_for_all_ks/node1-reactor-1.4482.1592966720.core
```

Scylla version 9033fa82d7c968417c5bce208fdabade8e948207
Core dump: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/531/artifact/logs-release.2/1592966721133_snapshot_test.TestParallelSnapshotOperations.test_parallel_operations_create_list_clear_for_all_ks/node1-reactor-1.4482.1592966720.core.gz
scylla-package: https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2138/artifact/scylla/build/release/scylla-package.tar.gz
or http://downloads.scylladb.com.s3.amazonaws.com/relocatable/unstable/master/2020-06-23T09%3A11%3A01Z/scylla-package.tar.gz

Decoded backtrace from https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/531/artifact/logs-release.2/1592966721133_snapshot_test.TestParallelSnapshotOperations.test_parallel_operations_create_list_clear_for_all_ks/node1.log
```
scylla: /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:445: void seastar::future_state_base::set_exception(std::__exception_ptr::exception_ptr&&): Assertion `_u.st == state::future' failed.
Aborting on shard 1.
Backtrace:
  0x0000000002ea3982
  0x0000000002e475f0
  0x0000000002e47895
  0x0000000002e478e0
  0x00007f62398b7a8f
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/9033fa82d7c968417c5bce208fdabade8e948207/scylla//opt/scylladb/libreloc/libc.so.6+0x000000000003ca24
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/9033fa82d7c968417c5bce208fdabade8e948207/scylla//opt/scylladb/libreloc/libc.so.6+0x0000000000025894
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/9033fa82d7c968417c5bce208fdabade8e948207/scylla//opt/scylladb/libreloc/libc.so.6+0x0000000000025768
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/9033fa82d7c968417c5bce208fdabade8e948207/scylla//opt/scylladb/libreloc/libc.so.6+0x0000000000034e85
  0x0000000002defea5
  0x000000000313d623
  0x000000000313dae2
  0x000000000313d531
  0x000000000313e9aa
  0x0000000002e44977
  0x0000000002e44cfe
  0x0000000002e7fa4d
  0x0000000002e8bf1a
  0x0000000002e0f75d
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/9033fa82d7c968417c5bce208fdabade8e948207/scylla//opt/scylladb/libreloc/libpthread.so.0+0x0000000000009431
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/9033fa82d7c968417c5bce208fdabade8e948207/scylla//opt/scylladb/libreloc/libc.so.6+0x00000000001019d2

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/util/backtrace.hh:59
seastar::backtrace_buffer::append_backtrace() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:742
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:763
seastar::print_with_backtrace(char const*) at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:770
seastar::install_oneshot_signal_handler<6, &seastar::sigabrt_action>()::{lambda(int, siginfo_t*, void*)#1}::_FUN(int, siginfo_t*, void*) at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:3478
 (inlined by) operator() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:3460
 (inlined by) _FUN at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:3456
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
seastar::future_state_base::set_exception(std::__exception_ptr::exception_ptr&&) at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:445
 (inlined by) seastar::future_state_base::set_to_broken_promise() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/future.cc:130
seastar::httpd::http_server::do_accepts(int)::{lambda(seastar::future<seastar::accept_result>)#1}::operator()(seastar::future<seastar::accept_result>) at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1331
 (inlined by) operator() at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1514
 (inlined by) then_impl_nrvo<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()>, seastar::future<> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1527
 (inlined by) then_impl<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1542
 (inlined by) run<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1193
 (inlined by) then<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1463
 (inlined by) operator() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/http/httpd.cc:478
seastar::httpd::http_server::do_accepts(int) at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1988
 (inlined by) then_wrapped_common<true, void, seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1627
 (inlined by) then_wrapped_maybe_erase<true, void, seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1581
 (inlined by) then_wrapped<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1572
 (inlined by) seastar::httpd::http_server::do_accepts(int) at /jenkins/workspace/scylla-master/next/scylla/seastar/src/http/httpd.cc:479
seastar::httpd::http_server::do_accepts(int)::{lambda(seastar::future<seastar::accept_result>)#1}::operator()(seastar::future<seastar::accept_result>) at /jenkins/workspace/scylla-master/next/scylla/seastar/src/http/httpd.cc:477
 (inlined by) __invoke_impl<seastar::future<>, seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()> > at /usr/include/c++/10/bits/invoke.h:60
 (inlined by) __invoke<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()> > at /usr/include/c++/10/bits/invoke.h:96
 (inlined by) __apply_impl<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()>, std::tuple<> > at /usr/include/c++/10/tuple:1724
 (inlined by) apply<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()>, std::tuple<> > at /usr/include/c++/10/tuple:1736
 (inlined by) apply<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:2004
 (inlined by) then_impl<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1539
 (inlined by) run<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1193
 (inlined by) then<seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> mutable::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1463
 (inlined by) operator() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/http/httpd.cc:478
seastar::continuation<seastar::internal::promise_base_with_type<>, seastar::httpd::http_server::do_accepts(int)::{lambda(seastar::future<seastar::accept_result>)#1}, seastar::future<seastar::accept_result>::then_wrapped_nrvo<void, {lambda(seastar::future<seastar::accept_result>)#1}>({lambda(seastar::future<seastar::accept_result>)#1}&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<>&, {lambda(seastar::future<seastar::accept_result>)#1}&, seastar::future_state<seastar::accept_result>&&)#1}, seastar::accept_result>::run_and_dispose() at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1606
 (inlined by) satisfy_with_result_of<seastar::future<T>::then_wrapped_nrvo<void, seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)> >::<lambda()>::<lambda(pr_type&, seastar::httpd::http_server::do_accepts(int)::<lambda(seastar::future<seastar::accept_result>)>&, seastar::future_state<seastar::accept_result>&&)> mutable::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1981
 (inlined by) operator() at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1605
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:636
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:2153
seastar::reactor::run_some_tasks() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:2569
seastar::reactor::run_some_tasks() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:2552
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:2724
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:3900
std::function<void ()>::operator()() const at /usr/include/c++/10/bits/std_function.h:622
 (inlined by) seastar::posix_thread::start_routine(void*) at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/posix.cc:60
```

**Comment by bhalevy** [comment]
@espindola can you please do the initial core dump analysis?

**Comment by espindola** [comment]
taking a look now

**Comment by espindola** [comment]
Looks like we try to call 'then' on http's _accepts_done twice. The problem is probably in the recursion:

        _accepts_done = _accepts_done.then([this, which] {
            return do_accepts(which);
        });

if _accepts_done is ready, we call do_accept before then returns.

I will try writing a test to reproduce that and change the code to use one of our loop helpers.

**Comment by espindola** [comment]
Patch sent:
httpd: Avoid calling future::then twice on the same future

**Comment by nyh** [comment]
@espindola thanks for the patch, reviewing it now. Note tha the _accepts_done thing is a very new regression, Seastar commit e67b366bb06d2caed6f1f787a8ce2c07f98061f3 (by @psarna), so probably no backports needed.

**Comment by bhalevy** [comment]
@nyh ping, what's the status of the patch?
It looks like patches 1-2/3 were merged and 3/3 has not yet, right?
Can we merge it too and close this issue once seastar submodule is updated?

**Comment by nyh** [comment]
@bhalevy I have no idea, I'll take a look at the mailinglist...

**Comment by avikivity** [comment]
Backported to 4.2, no other vulnerable versions.
