### ISSUE TITLE
node_graceful_stop_during_stress_and_decommission_test sometimes fails with 'DN' != 'UL'

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6718]
Seen recently in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/521/testReport/nodetool_additional_test/TestNodetool/node_graceful_stop_during_stress_and_decommission_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/532/testReport/nodetool_additional_test/TestNodetool/node_graceful_stop_during_stress_and_decommission_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1938, in node_graceful_stop_during_stress_and_decommission_test
    node_3_status))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 87, in assertEqual
    super(TestNodetool, self).assertEqual(expect, second, msg + " (Expecting " + str(expect) + " got " + str(second) + ")")
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 1250, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: 'DN' != 'UL'
- DN
+ UL
 : Node 3 status is incorrect (should be DN) Instead we got UL (Expecting DN got UL)
```

**Comment by bhalevy** [comment]
@asias can you please do the initial triage and see if this could be a test issue or a scylla issue?

**Comment by asias** [comment]
The status:

```
2020-07-01 10:49:37.796498 nodetool_additional_test.py:TestNodetool.node_graceful_stop_during_stress_and_decommission_test - status={'Datacenter': 'datacenter1', 'nodes': [{'status': 'UN', 'address': '127.0.6.1', 'load': '85.32 KB'
, 'tokens': '256', 'owns': '?', 'host id': 'c6ecadd3-a346-4644-b126-925956e71c93', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.6.2', 'load': '85.62 KB', 'tokens': '256', 'owns': '?', 'host id': '32406f7c-3782-44a4-ab99-417
4a2462ec0', 'rack': 'rack1'}, {'status': 'DN', 'address': '127.0.6.3', 'load': '91.14 KB', 'tokens': '256', 'owns': '?', 'host id': 'a347ae93-b608-4233-873a-05e27e574ac7', 'rack': 'rack1'}]}
```

We should improve the test to get the status by searching the ip address instead of indexing like below:

```
node_3_status = status["nodes"][2]['status']
```

I suspect it got the status of node4 which is in UL in the failed test.

**Comment by asias** [comment]
Dtest change is about to be merged.
