### ISSUE TITLE
lwt_schema_modification_test: materialized_view_test: Cannot drop table when materialized views still depend on it (lwt_load_ks.{table1_top_v_view})

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6738]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/537/testReport/lwt_schema_modification_test/LWTSchemaModificationTester/materialized_view_test/
Scylla version 23ce6864a3535286ca28770f663577e211c71b63
Scylla-dtest version scylladb/scylla-dtest@929b7bda1c1a6e4044487368ace06f979f9ea42c
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/lwt_schema_modification_test.py", line 502, in materialized_view_test
    nrows = 10000, loops = 1, run_s = 10)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/lwt_schema_modification_test.py", line 439, in _test_combine
    self._case_epilogue()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/lwt_schema_modification_test.py", line 384, in _case_epilogue
    session.execute("DROP TABLE table1")
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot drop table when materialized views still depend on it (lwt_load_ks.{table1_top_v_view})"
```

**Comment by bhalevy** [comment]
@alecco can you please see if this could be a bug in the test?
Cc @gleb-cloudius @kostja

**Comment by slivne** [comment]
@kostja need to check if this is relevant for 4.2 as well
