### ISSUE TITLE
nodetool snapshot tests: snapshot missing 

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6739]
a bunch of nodetool snapshot dtests started failing since
scylla version 509442b128f602c596ea5aca3aa5e27f5db14b7e
scylladb/scylla-dtest@929b7bda1c1a6e4044487368ace06f979f9ea42c

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/536/testReport/nodetool_additional_test/TestNodetool/global_snapshot_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 383, in global_snapshot_test
    self.verify_snapshot(node1, "keyspace1", snapshot)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 356, in verify_snapshot
    self.assertTrue(m, "snapshot " + snapshot + " is missing in keyspace " + ks)
  File "/usr/lib64/python3.7/unittest/case.py", line 722, in assertTrue
    raise self.failureException(msg)
AssertionError: [] is not true : snapshot 1593396555402 is missing in keyspace keyspace1
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/536/testReport/nodetool_additional_test/TestNodetool/snapshot_tag_keyspace_cf_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 443, in snapshot_tag_keyspace_cf_test
    self.tst_snapshot("snaptag", keyspace="system_schema", column_family="tables")
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 429, in tst_snapshot
    self.verify_snapshot(node1, keyspace, snapshot)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 356, in verify_snapshot
    self.assertTrue(m, "snapshot " + snapshot + " is missing in keyspace " + ks)
  File "/usr/lib64/python3.7/unittest/case.py", line 722, in assertTrue
    raise self.failureException(msg)
AssertionError: [] is not true : snapshot snaptag is missing in keyspace system_schema
```

And similarly:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/536/testReport/nodetool_additional_test/TestNodetool/snapshot_tag_keyspace_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/536/testReport/nodetool_additional_test/TestNodetool/snapshot_tag_test/

**Comment by bhalevy** [comment]
Last good run at scylla version 2d91e5f6a06586cccc8d2904198ea44192f4a193

**Comment by bhalevy** [comment]
@xemul this could have caused by 509442b128f602c596ea5aca3aa5e27f5db14b7e
Merge "Move snapshot code from storage_service into independent component" from Pavel E

**Comment by xemul** [comment]
[PATCH 0/3] Fix API snapshot details getter  is merged recently, that's the fix

**Comment by bhalevy** [comment]
it was promoted so let's close this issue and reopen if needed.
