### ISSUE TITLE
coredump occurred after modify_table nemesis

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6749]
*Installation details*
Scylla version (or git commit hash): 4.1.0-0.20200618.b443b2574a8
Cluster size:  4 (eu-west-1), 3 (us-west-2),  2 (us-east-1)
OS (RHEL/CentOS/Ubuntu/AWS AMI): 
- ami_id_db_scylla: ami-0ac3864d3eb5997e0 (eu-west-1)    ami-0d711e74dd5293ac0 (us-west-2)  ami-0ed04d673cacf0b3e  (us-east-1)

### Description

In longevity-lwt-24h-multidc job, 5 same coredumps occurred after modify_table nemesis.

ALTER before coredump
  - `ALTER TABLE cqlstress_lwt_example.blogposts_not_updated_lwt_indicator_expect WITH speculat
ive_retry = '659ms';`

Job: https://jenkins.scylladb.com/job/scylla-4.1/view/4.1-test/job/longevity/job/longevity-lwt-24h-multidc/3

### SCT config: 

https://github.com/scylladb/scylla-cluster-tests/blob/branch-4.1/test-cases/longevity/longevity-lwt-24h-multidc.yaml

### Logs
- test id: 2b7e0c96-c603-45de-8237-c8f1a4a5840c
- db logs: https://cloudius-jenkins-test.s3.amazonaws.com/2b7e0c96-c603-45de-8237-c8f1a4a5840c/20200625_040646/db-cluster-2b7e0c96.zip

### Download Coredump 1

```
gsutil cp gs://upload.scylladb.com/core.scylla.996.1dc6cc5e82c1436d990da8fcf1200aff.3754.1593537567000000/core.scylla.996.1dc6cc5e82c1436d990da8fcf1200aff.3754.1593537567000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.996.1dc6cc5e82c1436d990da8fcf1200aff.3754.1593537567000000.gz
```

### Coredump 1

```
2020-06-30T17:19:27+00:00  lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-1
!INFO    | scylla: scylla: ./seastar/include/seastar/core/future.hh:1570: void seastar::future<T>::set_callback(se
astar::continuation_base<T ...>*) [with T = {}]: Assertion `_promise' failed.
2020-06-30T17:19:27+00:00  | scylla: Aborting on shard 2.
2020-06-30T17:19:27+00:00  | scylla: Backtrace:
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002e0ce72
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002db64b4
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002db67b5
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002db6850
2020-06-30T17:19:27+00:00  | scylla: 0x00007f884d25cb1f
2020-06-30T17:19:27+00:00  | scylla: /opt/scylladb/libreloc/libc.so.6+0x000000000003c624
2020-06-30T17:19:27+00:00  | scylla: /opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
2020-06-30T17:19:27+00:00  | scylla: /opt/scylladb/libreloc/libc.so.6+0x00000000000257a8
2020-06-30T17:19:27+00:00  | scylla: /opt/scylladb/libreloc/libc.so.6+0x0000000000034a65
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002d6a0a6
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002d6a161
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002db29e0
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002db2bef
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002de7a05
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002df613c
2020-06-30T17:19:27+00:00  | scylla: 0x0000000002d852dd
2020-06-30T17:19:27+00:00  | scylla: /opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
2020-06-30T17:19:27+00:00  | scylla: /opt/scylladb/libreloc/libc.so.6+0x00000000001016a2

< t:2020-06-30 17:21:00,756 f:cluster.py      l:939  c:sdcm.cluster_aws     p:DEBUG > Node lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-1 [34.250.251.159 | 10.0.3.12] (seed: False): Found coredump file: /var/lib/systemd/coredump/core.scylla.996.1dc6cc5e82c1436d990da8fcf1200aff.3754.1593537567000000

2020-06-30T17:22:46+00:00  | scylla: Scylla version 4.1.0-0.20200618.b443b2574a8 with build-id 650a4b0c03ae680a9fbf7166c992e99e29b37123 starting ...
```

### Nemesis

- ALTER before coredump
  - `ALTER TABLE cqlstress_lwt_example.blogposts_not_updated_lwt_indicator_expect WITH speculat
ive_retry = '659ms';`

```
< t:2020-06-30 11:04:55,352  >>Started random_disrupt_method restart_then_repair_node
< t:2020-06-30 12:04:21,366  >>Started random_disrupt_method toggle_table_ics
< t:2020-06-30 12:33:30,338  >>Started random_disrupt_method no_corrupt_repair
< t:2020-06-30 13:40:12,834  >>Started random_disrupt_method decommission_streaming_err
< t:2020-06-30 14:26:06,343  >>Started random_disrupt_method network_random_interruptions
< t:2020-06-30 14:59:27,274  >>Started random_disrupt_method mgmt_repair_cli
< t:2020-06-30 15:29:28,373  >>Started random_disrupt_method stop_wait_start_scylla_server
< t:2020-06-30 15:36:51,486  <<Finished random_disrupt_method stop_wait_start_scylla_server
< t:2020-06-30 16:14:03,227  >>Started random_disrupt_method toggle_table_ics

< t:2020-06-30 16:14:24,896 f:remote.py       l:160  c:sdcm.remote          p:ERROR > RemoteCmdRunner [centos@54.195.143.234]: Error executing command: "cqlsh --no-color   --request-timeout=1
20 --connect-timeout=60  -e "ALTER MATERIALIZED VIEW  cqlstress_lwt_example.blogposts_deletions WITH compaction = {'class': 'IncrementalCompactionStrategy', 'bucket_high': 1.15, 'bucket_low':
 0.61, 'min_sstable_size': 14, 'min_threshold': 5, 'max_threshold': 4, 'sstable_size_in_mb': 1594};" 54.195.143.234 9042"; Exit status: 2
< t:2020-06-30 16:14:24,896 f:remote.py       l:164  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@54.195.143.234]: STDERR: <stdin>:1:ConfigurationException: Unable to find compact
ion strategy class 'IncrementalCompactionStrategy'

< t:2020-06-30 16:46:47,536  >>Started random_disrupt_method modify_table

< t:2020-06-30 16:46:58,065 f:common.py       l:997  c:utils                p:DEBUG > Executing CQL 'ALTER TABLE cqlstress_lwt_example.blogposts_not_updated_lwt_indicator_expect WITH speculat
ive_retry = '659ms';'...

< t:2020-06-30 16:47:08,337  <<Finished random_disrupt_method modify_table

### 2020-06-30T17:19:27+00:00 <coredump occurred on db-node-1>

< t:2020-06-30 17:25:24,802 f:nemesis.py      l:730  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: _modify_table_property: ALTER TABLE cqlstress_lwt_example.blogposts_update_2_columns_lwt_indicator_expect WITH dclocal_read_repair_chance = 0.9;


Totally 5 same coredump occurred on db nodes.

ca8f9a91-3a6e-478f-b407-4ff0d517cc53]$ grep 'continuation_base' -r db-cluster-ca8f9a91.zip/|grep failed
db-cluster-ca8f9a91.zip/lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-1/messages.log:2020-06-30T17:19:27+00:00  lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-1 !INFO    | scylla: scylla: ./seastar/include/seastar/core/future.hh:1570: void seastar::future<T>::set_callback(seastar::continuation_base<T ...>*) [with T = {}]: Assertion `_promise' failed.
db-cluster-ca8f9a91.zip/lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-2/messages.log:2020-06-30T19:04:52+00:00  lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-2 !INFO    | scylla: scylla: ./seastar/include/seastar/core/future.hh:1570: void seastar::future<T>::set_callback(seastar::continuation_base<T ...>*) [with T = {}]: Assertion `_promise' failed.
db-cluster-ca8f9a91.zip/lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-2/messages.log:2020-06-30T20:02:55+00:00  lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-2 !INFO    | scylla: scylla: ./seastar/include/seastar/core/future.hh:1570: void seastar::future<T>::set_callback(seastar::continuation_base<T ...>*) [with T = {}]: Assertion `_promise' failed.
db-cluster-ca8f9a91.zip/lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-7/messages.log:2020-06-30T17:46:21+00:00  lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-7 !INFO    | scylla: scylla: ./seastar/include/seastar/core/future.hh:1570: void seastar::future<T>::set_callback(seastar::continuation_base<T ...>*) [with T = {}]: Assertion `_promise' failed.
db-cluster-ca8f9a91.zip/lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-4/messages.log:2020-06-30T18:04:24+00:00  lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-4 !INFO    | scylla: scylla: ./seastar/include/seastar/core/future.hh:1570: void seastar::future<T>::set_callback(seastar::continuation_base<T ...>*) [with T = {}]: Assertion `_promise' failed.
db-cluster-ca8f9a91.zip/lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-6/messages.log:2020-06-30T17:41:01+00:00  lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-6 !INFO    | scylla: scylla: ./seastar/include/seastar/core/future.hh:1570: void seastar::future<T>::set_callback(seastar::continuation_base<T ...>*) [with T = {}]: Assertion `_promise' failed.

```

**Comment by amoskong** [comment]
### Coredump 1
```
backtrace=           PID: 3754 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Tue 2020-06-30 17:19:27 UTC (1min 33s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-3 --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /
       Boot ID: 1dc6cc5e82c1436d990da8fcf1200aff
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-1
      Coredump: /var/lib/systemd/coredump/core.scylla.996.1dc6cc5e82c1436d990da8fcf1200aff.3754.1593537567000000
       Message: Process 3754 (scylla) of user 996 dumped core.
                
                Stack trace of thread 3757:
                #0  0x00007f884c81f625 raise (libc.so.6)
                #1  0x00007f884c8089ae abort (libc.so.6)
                #2  0x00007f884c8087a9 __assert_fail_base.cold (libc.so.6)
                #3  0x00007f884c817a66 __assert_fail (libc.so.6)
                #4  0x0000000002d6a0a7 _ZN7seastar6futureIJEE12set_callbackEPNS_17continuation_baseIJEEE (scylla)
                #5  0x0000000002d6a162 _ZN7seastar23parallel_for_each_state15run_and_disposeEv (scylla)
                #6  0x0000000002db29e1 _ZN7seastar7reactor9run_tasksERNS0_10task_queueE (scylla)
                #7  0x0000000002db2bf0 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #8  0x0000000002de7a06 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #9  0x0000000002df613d _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
                #10 0x0000000002d852de _ZNKSt8functionIFvvEEclEv (scylla)
                #11 0x00007f884d2514e2 start_thread (libpthread.so.0)
                #12 0x00007f884c8e46a3 __clone (libc.so.6)
                
                Stack trace of thread 3762:
                #0  0x00007f884d25b87c read (libpthread.so.0)
                #1  0x000000000303d766 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x000000000303da52 operator() (scylla)
                #3  0x0000000002d852de _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f884d2514e2 start_thread (libpthread.so.0)
                #5  0x00007f884c8e46a3 __clone (libc.so.6)
                
                Stack trace of thread 3759:
                #0  0x00007f884d25b87c read (libpthread.so.0)
                #1  0x000000000303d766 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x000000000303da52 operator() (scylla)
                #3  0x0000000002d852de _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f884d2514e2 start_thread (libpthread.so.0)
                #5  0x00007f884c8e46a3 __clone (libc.so.6)
                
                Stack trace of thread 3760:
                #0  0x00007f884d25b87c read (libpthread.so.0)
                #1  0x000000000303d766 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x000000000303da52 operator() (scylla)
                #3  0x0000000002d852de _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f884d2514e2 start_thread (libpthread.so.0)
                #5  0x00007f884c8e46a3 __clone (libc.so.6)
                
                Stack trace of thread 3754:
                #0  0x0000000000fe51c8 XXH64_avalanche (scylla)
                #1  0x000000000103bb98 XXH_INLINE_XXH64_digest (scylla)
                #2  0x000000000103d233 _Z9feed_hashI9xx_hasher3rowJRK6schema11column_kindRKN5utils12small_vectorIjLm8EEER13max_timestampEEvRT_RKT0_DpOT1_ (scylla)
                #3  0x0000000001010bd8 _ZSt10__do_visitILb0ELb1EZN5query8digester9feed_hashI3rowJRK6schema11column_kindRKN5utils12small_vectorIjLm8EEER13max_timestampEEEvRKT_DpOT0_EUlRSF_E_JRSt7variantIJNS0_11noop_hasherE10md5_hasher9xx_hasherEEEEDcOT1_DpOT2_ (scylla)
                #4  0x00000000010572bd _ZZN20flat_mutation_reader4impl16consume_pausableISt17reference_wrapperINS0_16consumer_adapterI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1EN5query27clustering_position_trackerI20query_result_builderEEEEEEEEEN7seastar6futureIJEEET_NSt6chrono10time_pointINSF_12lowres_clockENSJ_8durationIlSt5ratioILl1ELl1000EEEEEEENUlvE0_clEv (scylla)
                #5  0x00000000010583c2 _ZN7seastar8futurizeINS_6futureIJEEEE6invokeIRZN20flat_mutation_reader4impl16consume_pausableISt17reference_wrapperINS6_16consumer_adapterI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1EN5query27clustering_position_trackerI20query_result_builderEEEEEEEEES2_T_NSt6chrono10time_pointINS_12lowres_clockENSM_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE0_JEEES2_OSL_DpOT0_ (scylla)
                #6  0x0000000001052262 _ZZN5query12consume_pageIL19emit_only_live_rows1E20query_result_builderEEDaR20flat_mutation_readerN7seastar13lw_shared_ptrI22compact_mutation_stateIXT_EL20compact_for_sstables0EEEERKNS_15partition_sliceEOT0_jjNSt6chrono10time_pointI8gc_clockNSG_8durationIlSt5ratioILl1ELl1EEEEEENSH_INS5_12lowres_clockENSJ_IlSK_ILl1ELl1000EEEEEEmENUlP17mutation_fragmentE_clEST_ (scylla)
                #7  0x0000000001053e9e _ZN7seastar12apply_helperIZN5query12consume_pageIL19emit_only_live_rows1E20query_result_builderEEDaR20flat_mutation_readerNS_13lw_shared_ptrI22compact_mutation_stateIXT_EL20compact_for_sstables0EEEERKNS1_15partition_sliceEOT0_jjNSt6chrono10time_p
```

**Comment by bhalevy** [comment]
@espindola can you please do the initial analysis to see where this is coming from?

**Comment by espindola** [comment]
The backtrace doesn't say much:
```
#3  0x00007f884c817a66 in __assert_fail () from /home/espindola/scylla/debug-6749/libreloc/libc.so.6
#4  0x0000000002d6a0a7 in seastar::future<>::set_callback(seastar::continuation_base<>*) (callback=0x602001e1bd20, this=0x6020011e69d0) at ./seastar/include/seastar/core/future.hh:302
#5  seastar::internal::set_callback<, seastar::continuation_base<> >(seastar::future<>&, seastar::continuation_base<>*) (callback=0x602001e1bd20, fut=...) at ./seastar/include/seastar/core/future.hh:1854
#6  seastar::parallel_for_each_state::wait_for_one (this=this@entry=0x602001e1bd20) at ./seastar/src/core/future-util.cc:60
#7  0x0000000002d6a162 in seastar::parallel_for_each_state::run_and_dispose (this=0x602001e1bd20) at ./seastar/src/core/future-util.cc:80
#8  0x0000000002db29e1 in seastar::reactor::run_tasks (this=this@entry=0x60200006e000, tq=...) at ./seastar/src/core/reactor.cc:2151
```

Se we have a parallel_for_each trying to wait on a future whose promise has been destroyed, but there is no indication of which parallel_for_each.

With the seastar version in use,  the problem can be reproduced with:

#include <seastar/core/app-template.hh>
#include <seastar/core/future-util.hh>
using namespace seastar;
static future<> foo() {
    std::vector<promise<>> v(2);
    return parallel_for_each(v, [] (promise<>& p){
        return p.get_future();
    });
}
int main(int argc, char** argv) {
    seastar::app_template app;
    app.run(argc, argv, [] {
            return foo();
    });
}

With the current seastar master this correctly produces a seastar::broken_promise. This is because of patch 386f575021e5327155f3f4a5b0d580c80c2bd45e. My suggestion would be to backport that to the seastar being used by 4.1, which would hopefully make this bug easier to track down.

I will still try to track down what is waiting for the broken parallel_for_each in the core.

**Comment by espindola** [comment]
The continuation waiting for this parallel_for_each is the then_wrapped in storage_proxy::mutate_internal.

This means that the parallel_for_each hitting this bug is probably the one in mutate_begin. When it returns a non ready future it is because of storage_proxy::response_wait. It looks like that an entry in _response_handlers was destroyed too soon, destroying the promise abstract_write_response_handler::_ready and clearing the _promise field in a future the parallel_for_each is waiting on.

The logs show a lot of exception futures being ignored. The first one is:

Jun 30 08:32:43 lwt-longevity-multi-dc-24h-4-1-db-node-ca8f9a91-1 scylla[3754]:  [shard 3] seastar - Exceptional future ignored: exceptions::mutation_write_failure_exception (Operation failed for system.paxos - received 0 responses and 1 failures from 1 CL=ONE.)

@gleb-cloudius, @nyh, any suggestions?

**Comment by espindola** [comment]
If anyone else wants to look a the core, the service::storage_proxy is at 0x602000539e00.

**Comment by bhalevy** [comment]
@gleb-cloudius please look into this

**Comment by espindola** [comment]
@avikivity , are you OK with porting seastar's 386f575021e5327155f3f4a5b0d580c80c2bd45e?

**Comment by bhalevy** [comment]
@avikivity ok to backport scylladb/seastar@386f575021e5327155f3f4a5b0d580c80c2bd45e to scylla-seastar branch-4.1?

see https://github.com/scylladb/scylla/issues/6749#issuecomment-653672913

**Comment by gleb-cloudius** [comment]
@espindola The error message about ignored exception is a sign that the abstract_write_response_handler::_ready was not destroyed prematurely because the exception is originated at this promise.  abstract_write_response_handler sets abstract_write_response_handler::_ready in its destructor when it is released from _response_handlers, but not always (because it may be set earlier). If you suspect that the destructor does not set the promise when it should we can add asserts there and retest if the bug is reproducible.

**Comment by avikivity** [comment]
> @avikivity , are you OK with porting seastar's 386f575021e5327155f3f4a5b0d580c80c2bd45e?

I don't understand how a patch that says "no functional changes" is related.

**Comment by espindola** [comment]
> > @avikivity , are you OK with porting seastar's 386f575021e5327155f3f4a5b0d580c80c2bd45e?
> 
> I don't understand how a patch that says "no functional changes" is related.

I was wrong. The "no functional changes"  was under the assumption that we were already setting futures to broken promises in all code paths, but as the test in https://github.com/scylladb/scylla/issues/6749#issuecomment-653672913 shows, that was not the case.

**Comment by avikivity** [comment]
Please resend a backport with an explanation of what it fixed (to scylladb-dev@, since it's no longer seastar master) and which branches are vulnerable. I don't expect to have an objection to the patch, but I do need to understand the situation.

**Comment by espindola** [comment]
I have send email backporting all the way to 3.1. The test crashes with 3.0, but 3.0 doesn't even have broken_promise. Should we try to fix the issues that far back?

**Comment by penberg** [comment]
@espindola We only support two of the latest open source releases at any given time. So backports to 4.1 and 4.0 -- and to 4.2 that's currently in release candidate stage.

**Comment by bhalevy** [comment]
@avikivity can this be closed?

**Comment by bhalevy** [comment]
With all backports done, this is can be closed.
