### ISSUE TITLE
node_exporter_install --force failing

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#6782]
*Installation details*
Scylla version (or git commit hash): 4.1.1-0.20200703.1d9bbbc9577
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): t3.large

```
[centos@ip-10-1-56-33 ~]$ sudo node_exporter_install --force
node_exporter already installed, reinstalling
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/node_exporter_install", line 62, in <module>
    tf.extractall(INSTALL_DIR)
  File "/opt/scylladb/python3/lib64/python3.7/tarfile.py", line 2000, in extractall
    numeric_owner=numeric_owner)
  File "/opt/scylladb/python3/lib64/python3.7/tarfile.py", line 2042, in extract
    numeric_owner=numeric_owner)
  File "/opt/scylladb/python3/lib64/python3.7/tarfile.py", line 2112, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/opt/scylladb/python3/lib64/python3.7/tarfile.py", line 2153, in makefile
    with bltn_open(targetpath, "wb") as target:
OSError: [Errno 26] Text file busy: '/opt/scylladb/Prometheus/node_exporter/node_exporter-0.17.0.linux-amd64/node_exporter'
```

The script should be able to deal with node_exporter already running and holding the file open

**Comment by avikivity** [comment]
Backported to 4.2, 4.1 (already present on 4.3).
