### ISSUE TITLE
test_tuple_indexes failure post 'Rewrite CQL3 restriction representation'

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6825]
The regression started with b0698dfb38afacbd3daf8f64ec83e63ba0ce0cd9
and was seen in jenkins since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/549/testReport/secondary_indexes_test/TestSecondaryIndexesOnCollections/test_tuple_indexes/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 1232, in test_tuple_indexes
    list(session.execute(select_cmd.format(table_name, index_column, template.format(n))))))
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 5 != 0
```

@dekimir said:
> At first glance, the test looks correct to me.  Can you please file a bug?
￼

**Comment by avikivity** [comment]
No vulnerable branches.
