### ISSUE TITLE
test_remove_node_during_index_build times out in 4.1

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6875]
Seen several times in 4.1 dtest-release jobs:

https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/50/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build/
https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/53/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build/
https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/57/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build/
https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/58/testReport/junit/_nose.plugins/multiprocess/NoSharedFixtureContextSuite_context_TestSecondaryIndexes_/
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/plugins/multiprocess.py", line 812, in run
    test(orig)
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 46, in __call__
    return self.run(*arg, **kwarg)
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/lib64/python3.7/unittest/case.py", line 693, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/secondary_indexes_test.py", line 1040, in test_remove_node_during_index_build
    self._node_action_during_index_build(node_action='remove', nodes=4, rf=3, num_rows=100000)
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/secondary_indexes_test.py", line 1087, in _node_action_during_index_build
    self.node_action_with_delay(self, node_action, node2)
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/secondary_indexes_test.py", line 186, in node_action_with_delay
    remove_node(cluster=self.cluster, node=node)
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/scylla_tools.py", line 974, in remove_node
    remove_using_node.nodetool("removenode {}".format(hostid))
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-ccm/ccmlib/node.py", line 729, in nodetool
    stdout, stderr = p.communicate()
  File "/usr/lib64/python3.7/subprocess.py", line 975, in communicate
    self._wait(timeout=sigint_timeout)
  File "/usr/lib64/python3.7/subprocess.py", line 1647, in _wait
    time.sleep(delay)
  File "/usr/local/lib/python3.7/site-packages/nose/plugins/multiprocess.py", line 276, in signalhandler
    raise TimedOutException()
nose.plugins.multiprocess.TimedOutException: 'test_remove_node_during_index_build (secondary_indexes_test.TestSecondaryIndexes)'
```

@asias please look into this to figre out why remove node seems to hang.

**Comment by bhalevy** [comment]
@denesb, considering we're using materialized view here, as @asias noted, might this be a deadlock / leak of the reader semaphore?

**Comment by denesb** [comment]
@bhalevy yes, this is certainly possible and would be my first guess. Out of the three issues contributing for that deadlock (https://github.com/scylladb/scylla/issues/6603, https://github.com/scylladb/scylla/issues/6707 and https://github.com/scylladb/scylla/issues/6774) only https://github.com/scylladb/scylla/issues/6774 was backported to 4.2.

**Comment by bhalevy** [comment]
> @bhalevy yes, this is certainly possible and would be my first guess. Out of the three issues contributing to that deadlock (#6603, #6707 and #6774) only the fix for #6774 was backported to 4.2.

Note that this happens in 4.1

**Comment by denesb** [comment]
> > @bhalevy yes, this is certainly possible and would be my first guess. Out of the three issues contributing to that deadlock (#6603, #6707 and #6774) only the fix for #6774 was backported to 4.2.
> 
> Note that this happens in 4.1

Right, I meant to say 4.1.

**Comment by bhalevy** [comment]
Still happening: https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/63/testReport/

**Comment by bhalevy** [comment]
Let's let the fixes brew in master and 4.2 and then see if we want to backport them to 4.1

**Comment by asias** [comment]
Hello @bhalevy, do we have still have this issue in jenkins? Can we close it now?

**Comment by asias** [comment]
The test passes for me locally.

**Comment by bhalevy** [comment]
> Hello @bhalevy, do we have still have this issue in jenkins? Can we close it now?

Yes.  The test passes reliably since https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/87/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build/
scylla-4.1 version 4ee0b489cffce03a1b3ba5c917b5734aa38c70f2
