### ISSUE TITLE
scylla_raid_setup cause traceback on CentOS7 

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#6954]
Seems like older lsblk does not have PARTTYPE column, scylla_raid_setup fails on get_partition_uuid().
We probably should add lsblk on relocatable binaries, just like other external commands.
```
[vagrant@localhost ~]$ cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
[vagrant@localhost ~]$ sudo /opt/scylladb/scripts/scylla_raid_setup --disks /dev/sdb,/dev/sdc --enable-on-nextboot
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 71, in <module>
    if not is_unused_disk(disk):
  File "/opt/scylladb/scripts/scylla_util.py", line 460, in is_unused_disk
    return not is_system_partition(dev)
  File "/opt/scylladb/scripts/scylla_util.py", line 449, in is_system_partition
    uuid = get_partition_uuid(dev)
  File "/opt/scylladb/scripts/scylla_util.py", line 446, in get_partition_uuid
    return out(f'lsblk -n -oPARTTYPE {dev}')
  File "/opt/scylladb/scripts/scylla_util.py", line 347, in out
    return subprocess.run(cmd, capture_output=True, shell=shell, timeout=timeout, check=exception, encoding='utf-8', env=scylla_env).stdout.strip()
  File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['lsblk', '-n', '-oPARTTYPE', '/dev/sdb']' returned non-zero exit status 1.
[vagrant@localhost ~]$ lsblk --help

Usage:
 lsblk [options] [<device> ...]

Options:
 -a, --all            print all devices
 -b, --bytes          print SIZE in bytes rather than in human readable format
 -d, --nodeps         don't print slaves or holders
 -D, --discard        print discard capabilities
 -e, --exclude <list> exclude devices by major number (default: RAM disks)
 -I, --include <list> show only devices with specified major numbers
 -f, --fs             output info about filesystems
 -h, --help           usage information (this)
 -i, --ascii          use ascii characters only
 -m, --perms          output info about permissions
 -l, --list           use list format output
 -n, --noheadings     don't print headings
 -o, --output <list>  output columns
 -p, --paths          print complate device path
 -P, --pairs          use key="value" output format
 -r, --raw            use raw output format
 -s, --inverse        inverse dependencies
 -t, --topology       output info about topology
 -S, --scsi           output info about SCSI devices

 -h, --help     display this help and exit
 -V, --version  output version information and exit

Available columns (for --output):
        NAME  device name
       KNAME  internal kernel device name
     MAJ:MIN  major:minor device number
      FSTYPE  filesystem type
  MOUNTPOINT  where the device is mounted
       LABEL  filesystem LABEL
        UUID  filesystem UUID
   PARTLABEL  partition LABEL
    PARTUUID  partition UUID
          RA  read-ahead of the device
          RO  read-only device
          RM  removable device
       MODEL  device identifier
      SERIAL  disk serial number
        SIZE  size of the device
       STATE  state of the device
       OWNER  user name
       GROUP  group name
        MODE  device node permissions
   ALIGNMENT  alignment offset
      MIN-IO  minimum I/O size
      OPT-IO  optimal I/O size
     PHY-SEC  physical sector size
     LOG-SEC  logical sector size
        ROTA  rotational device
       SCHED  I/O scheduler name
     RQ-SIZE  request queue size
        TYPE  device type
    DISC-ALN  discard alignment offset
   DISC-GRAN  discard granularity
    DISC-MAX  discard max bytes
   DISC-ZERO  discard zeroes data
       WSAME  write same max bytes
         WWN  unique storage identifier
        RAND  adds randomness
      PKNAME  internal parent kernel device name
        HCTL  Host:Channel:Target:Lun for SCSI
        TRAN  device transport type
         REV  device revision
      VENDOR  device vendor

For more details see lsblk(8).
```

**Comment by aleksbykov** [comment]
Issue reproduced:
for centos7 : repo: https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/branch-4.2/2020-08-01T13:04:56Z/scylla.repo

**Comment by aleksbykov** [comment]
And reproduced for https://jenkins.scylladb.com/job/scylla-4.2/job/artifacts/job/artifacts-oel76-test/31/

**Comment by syuu1228** [comment]
It's on master but not backported to 4.2 yet: 
https://github.com/scylladb/scylla/commit/bb9ad9c90b36dc027010df690eddde0113d21b1d

**Comment by avikivity** [comment]
Backported to 4.2. @syuu1228 do 4.1 and 4.0 also need it? I see they have lsblk too.

**Comment by avikivity** [comment]
Ah, I see it came from d7de9518fedea079599ba6ff5147da1296ff8cfa.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1 as well.
