### ISSUE TITLE
Scylla AMI not starting

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#6973]
AMI: scylla_2020-08-03T23-11-29Z (ami-05b55eb1eb02c4a3a)

```
[scyllaadm@ip-10-99-0-196 ~]$ rpm -qa | grep scylla
scylla-conf-666.development-0.20200803.4edfdfa78da.x86_64
scylla-tools-666.development-20200803.aa7898d7711.noarch
scylla-debuginfo-666.development-0.20200803.4edfdfa78da.x86_64
scylla-python3-3.8.5-0.20200803.4edfdfa78da.x86_64
scylla-kernel-conf-666.development-0.20200803.4edfdfa78da.x86_64
scylla-tools-core-666.development-20200803.aa7898d7711.noarch
scylla-jmx-666.development-20200803.626fd75173f.noarch
scylla-machine-image-666.development-20200804.f2e30f54a6e.noarch
scylla-server-666.development-0.20200803.4edfdfa78da.x86_64
scylla-666.development-0.20200803.4edfdfa78da.x86_64
```

```
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal systemd[1]: Starting Scylla Cloud Image Setup service...
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal systemd[1]: Stopping Dynamically Generate Message Of The Day...
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal systemd[1]: Starting Dynamically Generate Message Of The Day...
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal systemd[1]: Created slice Slice used to run Scylla. Maximum priority for IO and CPU.
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal systemd[1]: Starting Slice used to run Scylla. Maximum priority for IO and CPU.
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal sudo[5254]: pam_unix(sudo:session): session closed for user root
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal sudo[3944]: pam_unix(sudo:session): session closed for user root
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,916 - [scylla_configure] - INFO - Getting 'http://169.254.169.254/l
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Getting 'http://169.254.169.254/latest/meta-data/local-ipv4'...
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,920 - [scylla_configure] - INFO - Going to create scylla.yaml...
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Going to create scylla.yaml...
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,920 - [scylla_configure] - INFO - Getting 'http://169.254.169.254/l
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Getting 'http://169.254.169.254/latest/user-data'...
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,921 - [scylla_configure] - WARNING - Error getting user data: Expec
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Error getting user data: Expecting value: line 1 column 1 (char 0). Will use defaults!
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,922 - [scylla_configure] - INFO - Setting default cluster_name=scyl
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Setting default cluster_name=scylladb-cluster-1596496612
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,951 - [scylla_configure] - INFO - Setting default experimental=Fals
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Setting default experimental=False
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,951 - [scylla_configure] - INFO - Setting default auto_bootstrap=Tr
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Setting default auto_bootstrap=True
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,951 - [scylla_configure] - INFO - Setting default listen_address=17
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Setting default listen_address=172.30.0.81
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,951 - [scylla_configure] - INFO - Setting default broadcast_rpc_add
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Setting default broadcast_rpc_address=172.30.0.81
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,951 - [scylla_configure] - INFO - Setting default endpoint_snitch=o
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Setting default endpoint_snitch=org.apache.cassandra.locator.Ec2Snitch
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,951 - [scylla_configure] - INFO - Setting default rpc_address=0.0.0
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Setting default rpc_address=0.0.0.0
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,951 - [scylla_configure] - INFO - Setting default seed_provider=[{'
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Setting default seed_provider=[{'class_name': 'org.apache.cassandra.locator.SimpleSeedP
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: 2020-08-03 23:16:52,951 - [scylla_configure] - INFO - Saving /etc/scylla/scylla.yaml
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Saving /etc/scylla/scylla.yaml
Aug 03 23:16:53 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: No disks found
Aug 03 23:16:53 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e"
Aug 03 23:16:53 ip-172-30-0-81.ec2.internal systemd-coredump[14182]: Process 14181 (bash) of user 0 dumped core.
                                                                     
Aug 03 23:16:53 ip-172-30-0-81.ec2.internal systemd-coredump[14182]: Process 14181 (bash) of user 0 dumped core.
                                                                     
                                                                     Stack trace of thread 14181:
                                                                     #0  0x00007f31da375d97 kill (libc.so.6)
                                                                     #1  0x000000000043f706 kill_pid (bash)
                                                                     #2  0x000000000046fc8d kill_builtin (bash)
                                                                     #3  0x000000000042ea6b execute_builtin.isra.3 (bash)
                                                                     #4  0x0000000000430cba execute_simple_command (bash)
                                                                     #5  0x0000000000431ab5 execute_command_internal (bash)
                                                                     #6  0x00000000004332fe execute_command (bash)
                                                                     #7  0x000000000041e327 reader_loop (bash)
                                                                     #8  0x000000000041cbc5 main (bash)
                                                                     #9  0x00007f31da36302a __libc_start_main (libc.so.6)
                                                                     #10 0x000000000041d5fa _start (bash)

```

Later we have

```
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: Coredump: /var/lib/systemd/coredump/core.bash.0.6233e0633cc04b72b634a07d7180ab18.5081.15
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: Message: Process 5081 (bash) of user 0 dumped core.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: Stack trace of thread 5081:
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #0  0x00007efea5575d97 kill (libc.so.6)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #1  0x000000000043f706 kill_pid (bash)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #2  0x000000000046fc8d kill_builtin (bash)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #3  0x000000000042ea6b execute_builtin.isra.3 (bash)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #4  0x0000000000430cba execute_simple_command (bash)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #5  0x0000000000431ab5 execute_command_internal (bash)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #6  0x00000000004332fe execute_command (bash)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #7  0x000000000041e327 reader_loop (bash)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #8  0x000000000041cbc5 main (bash)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #9  0x00007efea556302a __libc_start_main (libc.so.6)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: #10 0x000000000041d5fa _start (bash)
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: systemd-coredump is working finely.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: swap already configured, exiting setup
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: Traceback (most recent call last):
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 34, in <modul
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: run('/opt/scylladb/scripts/scylla_swap_setup --swap-directory /')
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: File "/opt/scylladb/scripts/scylla_util.py", line 341, in run
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: return subprocess.run(cmd, stdout=stdout, stderr=stderr, shell=shell, check=exception, e
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 512, in run
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: raise CalledProcessError(retcode, process.args,
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal scylla_image_setup[4509]: subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_swap_setup', '--swap-directory', '/']' returned non-zero exit status 1.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: scylla-image-setup.service: main process exited, code=exited, status=1/FAILURE
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Failed to start Scylla Cloud Image Setup service.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Dependency failed for Scylla Server.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Dependency failed for Scylla JMX.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Dependency failed for Run Scylla fstrim daily.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Job scylla-fstrim.timer/start failed with result 'dependency'.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Job scylla-server.service/start failed with result 'dependency'.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: Unit scylla-image-setup.service entered failed state.
Aug 04 11:13:32 ip-10-99-0-196.ec2.internal systemd[1]: scylla-image-setup.service failed.
```

@fruch / @bentsi are we retrying creating of core file - and maybe this causes us to retry creating swap as well ?

**Comment by slivne** [comment]
@syuu1228 / @penberg should we check if swap is defined and if so not crash with error - but checkl the size is at least what we compute ?

**Comment by amoskong** [comment]
I reproduced this issue, there are two issues:

1. scylla-image-setup service was **Unexpectedly** executed in creating the AMI.

The AMI should be generated on Aug 03, I created the instance on Aug 05.

```
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal systemd[1]: Starting Scylla Cloud Image Setup service...
...
Aug 03 23:16:52 ip-172-30-0-81.ec2.internal scylla_image_setup[14076]: Setting default cluster_name=scylladb-cluster-1596496612


Aug 05 09:40:15 ip-172-30-0-81.ec2.internal systemd[1]: Starting Scylla Cloud Image Setup service...
....
Aug 05 09:40:19 ip-10-99-0-8.ec2.internal scylla_image_setup[3564]: 2020-08-05 09:40:19,495 - [scylla_configure] - INFO - Setting default cluster_name=scylladb-cluster-1596620419
Aug 05 09:40:19 ip-10-99-0-8.ec2.internal scylla_image_setup[3564]: Setting default cluster_name=scylladb-cluster-1596620419
```

2. We run basic scylla_setup in creating AMI, we didn't disable it like coredump, raid, etc.
- aws/ami/files/scylla_install_ami: `run('/opt/scylladb/scripts/scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup --no-ec2-check')`

So when AMI instance is starting, the repeat swap setup will fail for (`swap already configured, exiting setup`).

**Comment by amoskong** [comment]
Just sent a PR to scylla-machine-image to fix this issue.
I built an AMI (ami-067205d8f03ec7b4b (us-east-1)), it works well.

----
But I can still see scylla-machine-image service was started in stopping the SOURCE instance.

#### New Instance log:

```
[scyllaadm@ip-10-99-0-233 ~]$ uptime -s
2020-08-05 12:02:06
[scyllaadm@ip-10-99-0-233 ~]$ sudo journalctl -S 2020-08-04 |grep 'Starting Scylla'
Aug 05 11:50:06 ip-172-30-0-73.ec2.internal systemd[1]: Starting Scylla Cloud Image Setup service...
Aug 05 12:02:25 ip-172-30-0-73.ec2.internal systemd[1]: Starting Scylla Cloud Image Setup service...
Aug 05 12:04:06 ip-10-99-0-233.ec2.internal systemd[1]: Starting Scylla Server...
Aug 05 12:04:13 ip-10-99-0-233.ec2.internal systemd[1]: Starting Scylla JMX...
Aug 05 12:04:25 ip-10-99-0-233.ec2.internal systemd[1]: Starting Scylla Housekeeping restart mode...
```

#### AMI log:
```
2020/08/05 11:50:07 [INFO] (telemetry) ending shell
2020/08/05 11:50:07 ui: ESC[1;32m==> amazon-ebs: Stopping the source instance...ESC[0m
2020/08/05 11:50:07 ui: ESC[0;32m    amazon-ebs: Stopping instanceESC[0m
2020/08/05 11:50:08 ui: ESC[1;32m==> amazon-ebs: Waiting for the instance to stop...ESC[0m
2020/08/05 11:50:25 ui: ESC[1;32m==> amazon-ebs: Enabling Enhanced Networking (SR-IOV)...ESC[0m
2020/08/05 11:50:26 ui: ESC[1;32m==> amazon-ebs: Enabling Enhanced Networking (ENA)...ESC[0m
2020/08/05 11:50:26 ui: ESC[1;32m==> amazon-ebs: Creating AMI scylla_2020-08-05T11-46-48Z from instance i-0ed43714696b0d0b7ESC[0m
2020/08/05 11:50:27 ui: ESC[0;32m    amazon-ebs: AMI: ami-067205d8f03ec7b4bESC[0m
2020/08/05 11:50:27 ui: ESC[1;32m==> amazon-ebs: Waiting for AMI to become ready...ESC[0m
```

**Comment by amoskong** [comment]
Created a new issue for scylla-machine-image:

- scylla-image-setup service is started when stopping the source instance
#49 (https://github.com/scylladb/scylla-machine-image/issues/49)

**Comment by syuu1228** [comment]
@amoskong thanks for fixing the issue.

The PR looks good but scylla_swap_setup proceed creating swap even no disk space available is an another bug, I need fix it.
Also we should have a swap size prompt, as @amoskong pointed out ( #6947 )
Additionally, to avoid out of disk space, we probably limit swap size when disk space is limited, something like limit to 50% of free space or something like that.

**Comment by amoskong** [comment]
This issue had been fixed by https://github.com/scylladb/scylla-machine-image/pull/48

The next-machine-image (job 15) triggered ami and ami-test all PASSed.

- ami: https://jenkins.scylladb.com/job/scylla-master/job/ami/377/
- ami-test: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-test/146/
