### ISSUE TITLE
Node failed to decommission

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#700]
3 node cluster, running for a week with stress tools.
Running nodetool decommisison printed the following error:
```
error: std::bad_alloc
-- StackTrace --
java.lang.RuntimeException: std::bad_alloc
        at com.cloudius.urchin.api.APIClient.getException(APIClient.java:113)
        at com.cloudius.urchin.api.APIClient.post(APIClient.java:100)
        at com.cloudius.urchin.api.APIClient.post(APIClient.java:107)
        at org.apache.cassandra.service.StorageService.decommission(StorageService.java:691)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
        at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1471)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1312)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1404)
        at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:832)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$93(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

When running nodetool status it seems the node status is reported as "leaving", but that is the only difference, there is no action or changes in the node behavior or actions

**Comment by noamha** [comment]
After restart the server goes back to normal status, running the decommission caused the same result, and also causing the stress tool to crash

**Comment by slivne** [comment]
A bit more info

I enabled streaming_seeion trace logging in /etc/sysconfig/scylla-server

SCYLLA_ARGS="--collectd=1 --collectd-address=10.209.32.82:25826 --memory 10G --logger-log-level stream_session=trace"


Streaming does not start - not sure why

this is what I get in the log



```
Dec 24 11:03:26 noam-long-cass-04 scylla[31020]:  [shard 0] storage_service - LEAVING: sleeping 5000 ms for batch processing and pending range setup
Dec 24 11:03:38 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202401-Data.db:l
Dec 24 11:03:56 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacted 10 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202402-Data.db:
Dec 24 11:04:03 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202383-Data.db:level=0, /var/
Dec 24 11:04:14 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202399-Data.db:l
Dec 24 11:04:15 noam-long-cass-04 scylla[31020]:  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202400-Data.db:l
Dec 24 11:04:15 noam-long-cass-04 scylla[31020]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-201828-Data.db:level=0, /var/
Dec 24 11:04:20 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202406-Data.db:level=0, /var/
Dec 24 11:04:33 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202422-Data.db:l
Dec 24 11:04:38 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202405-Data.db:level=0, /var/
Dec 24 11:04:50 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202421-Data.db:l
Dec 24 11:05:13 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202403-Data.db:level=0, /var/
Dec 24 11:05:25 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202419-Data.db:l
Dec 24 11:05:29 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202426-Data.db:level=0, /var/
Dec 24 11:05:30 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202231-Data.db:level=0, /var/
Dec 24 11:05:44 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202442-Data.db:l
Dec 24 11:05:47 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202425-Data.db:level=0, /var/
Dec 24 11:06:06 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202441-Data.db:l
Dec 24 11:06:06 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202381-Data.db:level=0, /var/
Dec 24 11:06:26 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202427-Data.db:l
Dec 24 11:06:26 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202423-Data.db:level=0, /var/
Dec 24 11:06:36 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202446-Data.db:level=0, /var/
Dec 24 11:06:41 noam-long-cass-04 scylla[31020]:  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202412-Data.db:l
Dec 24 11:06:41 noam-long-cass-04 scylla[31020]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202396-Data.db:level=0, /var/
Dec 24 11:06:43 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202443-Data.db:l
Dec 24 11:06:51 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202462-Data.db:l
Dec 24 11:06:54 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202358-Data.db:level=0, /var/
Dec 24 11:07:08 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202449-Data.db:l
Dec 24 11:07:08 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202445-Data.db:level=0, /var/
Dec 24 11:07:21 noam-long-cass-04 scylla[31020]:  [shard 0] compaction - Compacted 12 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202452-Data.db:
Dec 24 11:07:21 noam-long-cass-04 scylla[31020]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-201460-Data.db:level=0, /var/
Dec 24 11:07:24 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202465-Data.db:l
Dec 24 11:07:30 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202447-Data.db:level=0, /var/
Dec 24 11:07:43 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202463-Data.db:l
Dec 24 11:07:49 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202470-Data.db:l
Dec 24 11:07:49 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202466-Data.db:level=0, /var/
Dec 24 11:08:02 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202486-Data.db:l
Dec 24 11:08:02 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-201590-Data.db:level=0, /var/
Dec 24 11:08:04 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202469-Data.db:level=0, /var/
Dec 24 11:08:18 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202485-Data.db:l
Dec 24 11:08:37 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202467-Data.db:level=0, /var/
Dec 24 11:08:52 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202483-Data.db:l
Dec 24 11:09:12 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202489-Data.db:level=0, /var/
Dec 24 11:09:25 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202505-Data.db:l
Dec 24 11:09:48 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202487-Data.db:level=0, /var/
Dec 24 11:10:00 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202503-Data.db:l
Dec 24 11:10:07 noam-long-cass-04 scylla[31020]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202443-Data.db:level=0, /var/
Dec 24 11:10:09 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202494-Data.db:l
Dec 24 11:10:09 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202490-Data.db:level=0, /var/
Dec 24 11:10:24 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202509-Data.db:level=0, /var/
Dec 24 11:10:42 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202525-Data.db:l
Dec 24 11:10:44 noam-long-cass-04 scylla[31020]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202465-Data.db:level=0, /var/
Dec 24 11:10:45 noam-long-cass-04 scylla[31020]:  [shard 2] compaction - Compacted 8 sstables to [/var/lib/scylla/data/keyspace1/standard1-25af8c60a40d11e5bfa5000000000000/keyspace1-standard1-ka-202526-Data.db:l

```

Trying to kill the cassandra-stress driving traffic does not help - it does not start

**Comment by asias** [comment]
Enabling storage_serice debug, I saw
```
Dec 24 13:05:01 noam-long-cass-04 scylla[5436]:  [shard 0] storage_service - LEAVING: sleeping 5000 ms for batch processing and pending range setup
Dec 24 13:05:05 noam-long-cass-04 scylla[5436]:  [shard 0] storage_service - before_change endpoint=10.223.242.18
Dec 24 13:05:05 noam-long-cass-04 scylla[5436]:  [shard 0] storage_service - on_change endpoint=10.223.242.18
Dec 24 13:05:05 noam-long-cass-04 scylla[5436]:  [shard 0] storage_service - Update ep=10.223.242.18, state=LOAD, value=4.67793e+08
Dec 24 13:05:06 noam-long-cass-04 scylla[5436]:  [shard 0] storage_service - Node 10.223.242.18 ranges [{(9201656765677883229, -9092320763719770861], (-9092320763719770861, -9077038405312624534], (-9077038405312624534, -906953
Dec 24 13:05:06 noam-long-cass-04 scylla[5436]:  [shard 0] storage_service - range=(9201656765677883229, -9092320763719770861], current_replica_endpoints={10.223.241.3, 10.208.128.125, 10.223.242.18}, new_replica_endpoints={10.223.241.3, 10.208.128.125}
```
in storage_service::unbootstrap(), scylla hangs somewhere before goes to the step of streaming. That's why you did not see streaming.

**Comment by tzach** [comment]
> 3 node cluster, running for a week with stress tools.

I see the same problem after running a 3 node cluster for a few minutes
nodetool decommisison fail with the same error
nodetool status shows the node as leaving (see below), but select with `CONSISTENCY ALL` of RF=3 keyspace still works.

```
$ nodetool status

Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  172.31.41.169  245.19 KB  256     ?       4b4a7de4-8b5b-435c-bdba-1a32ea2c66c1  2b
UL  172.31.41.168  245.19 KB  256     ?       db6a0358-2c3f-4cf2-b80e-f6fc1a655f18  2b
UN  172.31.44.214  154.28 KB  256     ?       8d697a94-2c20-4633-897f-733659fa7a11  2b

```

**Comment by asias** [comment]
we can close this now.
