### ISSUE TITLE
Semaphore timed out: _read_concurrency_sem) errors on cleanup after node replace with decommission and node status is DN

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#7001]
*Installation details*
Scylla version (or git commit hash): 4.2.rc2-0.20200803.c5ed14bff with build-id 377a88e9234ddae99025e9a5e5f5eeda0cda88cb
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0edbce030f3cb9761

Job [1T-7d-tls](https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/longevity/job/longevity-1tb-7days-test/11/) was failed after 2d running. it failed during Decommission nemessis.
Decommission nemessis logic described in #6531:
```
Description
In decommission nemesis, One node will be decommissioned firstly, the a new node will be added.
Currently we cleanup the test keyspaces (except system keyspaces) of all db nodes in the end of decommission Nemesis.

Scenario:

### Decommission one node
        self.cluster.decommission(self.target_node)

### Add a new node
                new_node = self._add_and_init_new_cluster_node()

### Clean up test keyspaces on all nodes
                test_keyspaces = self.cluster.get_test_keyspaces()
                for node in self.cluster.nodes:
                    for keyspace in test_keyspaces:
                        node.run_nodetool(sub_cmd='cleanup', args=keyspace)
```

After new node6 was removed and node7 was added, cleanup process was started:
```
< t:2020-08-06 17:08:00,470 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.31.181]: Running command "nodetool -u cassandra -pw cassandra  cleanup keyspace_lz4"...
< t:2020-08-06 17:19:36,467 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.31.181]: Command "nodetool -u cassandra -pw cassandra  cleanup keyspace_lz4" finished with status 0
< t:2020-08-06 17:19:36,467 f:cluster.py      l:2495 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-1tb-7d-4-2-db-node-b087b30f-1 [34.242.86.5 | 10.0.31.181] (seed: False): Command 'nodetool -u cassandra -pw cassandra  cleanup keyspace_lz4' duration -> 695.9968547821045 s
< t:2020-08-06 17:19:36,467 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.31.181]: Running command "nodetool -u cassandra -pw cassandra  cleanup keyspace_snappy"...
< t:2020-08-06 17:30:40,758 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.31.181]: Command "nodetool -u cassandra -pw cassandra  cleanup keyspace_snappy" finished with status 0
< t:2020-08-06 17:30:40,758 f:cluster.py      l:2495 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-1tb-7d-4-2-db-node-b087b30f-1 [34.242.86.5 | 10.0.31.181] (seed: False): Command 'nodetool -u cassandra -pw cassandra  cleanup keyspace_snappy' duration -> 664.2901155948639 s
< t:2020-08-06 17:30:40,758 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.31.181]: Running command "nodetool -u cassandra -pw cassandra  cleanup keyspace1"...
< t:2020-08-06 19:27:32,162 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.31.181]: Command "nodetool -u cassandra -pw cassandra  cleanup keyspace1" finished with status 0
< t:2020-08-06 19:27:32,338 f:cluster.py      l:2495 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-1tb-7d-4-2-db-node-b087b30f-1 [34.242.86.5 | 10.0.31.181] (seed: False): Command 'nodetool -u cassandra -pw cassandra  cleanup keyspace1' duration -> 7011.402522802353 s
< t:2020-08-06 19:27:32,339 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.31.181]: Running command "nodetool -u cassandra -pw cassandra  cleanup keyspace_zstd"...
< t:2020-08-06 19:36:27,342 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.31.181]: Command "nodetool -u cassandra -pw cassandra  cleanup keyspace_zstd" finished with status 0
< t:2020-08-06 19:36:27,511 f:cluster.py      l:2495 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-1tb-7d-4-2-db-node-b087b30f-1 [34.242.86.5 | 10.0.31.181] (seed: False): Command 'nodetool -u cassandra -pw cassandra  cleanup keyspace_zstd' duration -> 535.0025005340576 s
< t:2020-08-06 19:36:27,512 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.31.181]: Running command "nodetool -u cassandra -pw cassandra  cleanup keyspace_deflate"...
< t:2020-08-06 19:49:27,918 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.31.181]: Command "nodetool -u cassandra -pw cassandra  cleanup keyspace_deflate" finished with status 0
< t:2020-08-06 19:49:27,918 f:cluster.py      l:2495 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-1tb-7d-4-2-db-node-b087b30f-1 [34.242.86.5 | 10.0.31.181] (seed: False): Command 'nodetool -u cassandra -pw cassandra  cleanup keyspace_deflate' duration -> 780.4044830799103 s
< t:2020-08-06 19:49:27,918 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.31.181]: Running command "nodetool -u cassandra -pw cassandra  cleanup mview"...
< t:2020-08-06 19:50:07,436 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.31.181]: Command "nodetool -u cassandra -pw cassandra  cleanup mview" finished with status 0
< t:2020-08-06 19:50:07,436 f:cluster.py      l:2495 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-1tb-7d-4-2-db-node-b087b30f-1 [34.242.86.5 | 10.0.31.181] (seed: False): Command 'nodetool -u cassandra -pw cassandra  cleanup mview' duration -> 39.51700448989868 s
< t:2020-08-06 19:50:07,436 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.7.227]: Running command "nodetool -u cassandra -pw cassandra  cleanup keyspace_lz4"...
< t:2020-08-06 20:08:11,579 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.7.227]: Command "nodetool -u cassandra -pw cassandra  cleanup keyspace_lz4" finished with status 0
< t:2020-08-06 20:08:11,580 f:cluster.py      l:2495 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 [34.244.176.29 | 10.0.7.227] (seed: False): Command 'nodetool -u cassandra -pw cassandra  cleanup keyspace_lz4' duration -> 1084.1427900791168 s
< t:2020-08-06 20:08:11,580 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.7.227]: Running command "nodetool -u cassandra -pw cassandra  cleanup keyspace_snappy"...
< t:2020-08-06 20:36:39,544 f:remote.py       l:177  c:sdcm.remote          p:ERROR > RemoteCmdRunner [centos@10.0.7.227]: Error executing command: "nodetool -u cassandra -pw cassandra  cleanup keyspace_snappy"; Exit status: 2
< t:2020-08-06 20:36:39,544 f:cluster.py      l:2498 c:sdcm.cluster_aws     p:CRITICAL > Node longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 [34.244.176.29 | 10.0.7.227] (seed: False): Command 'nodetool -u cassandra -pw cassandra  cleanup keyspace_snappy' error: Encountered a bad command exit code!
< t:2020-08-06 20:36:39,544 f:cluster.py      l:2498 c:sdcm.cluster_aws     p:CRITICAL > Command: 'nodetool -u cassandra -pw cassandra  cleanup keyspace_snappy'
< t:2020-08-06 20:36:39,544 f:nemesis.py      l:636  c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: ('Exception in random_disrupt_method %s: %s', 'nodetool_decommission', <UnexpectedExit: cmd='nodetool -u cassandra -pw cassandra  cleanup keyspace_snappy' exited=2>)
```
When cleanup process was running on node2 the command was failed for keyspace keyspace_snappy:
```
 > Command: 'nodetool -u cassandra -pw cassandra  cleanup keyspace_snappy'
 > 
 > Exit code: 2
 > 
 > Stdout:
 > 
 > Cassandra has shutdown.
 > 
 > Stderr:
 > 
 >    at javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
 >    at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1020)
 >    at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:298)
 >    at com.sun.proxy.$Proxy8.forceKeyspaceCleanup(Unknown Source)
 >    at org.apache.cassandra.tools.NodeProbe.forceKeyspaceCleanup(NodeProbe.java:258)
 >    at org.apache.cassandra.tools.NodeProbe.forceKeyspaceCleanup(NodeProbe.java:292)
 >    at org.apache.cassandra.tools.nodetool.Cleanup.execute(Cleanup.java:55)
 >    at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:270)
 >    at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:180)
 > 
 > 
```
During the cleanup process there a lot of next warning and error messages:
```
eastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !WARNING | scylla: [shard 6] storage_proxy - Failed to apply mutation from 10.0.221.179#6: seastar::semaphore_timed_out (Semaphore timedout)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 10] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace_zstd.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace_zstd.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 2] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace_zstd.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 10] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace_snappy.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 9] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace_zstd.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 8] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace_snappy.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 10] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace_snappy.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 1] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace_deflate.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 2] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !WARNING | scylla: [shard 2] storage_proxy - Failed to apply mutation from 10.0.135.227#2: seastar::semaphore_timed_out (Semaphore timedout)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !WARNING | scylla: [shard 2] storage_proxy - Failed to apply mutation from 10.0.135.227#2: seastar::semaphore_timed_out (Semaphore timedout)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !WARNING | scylla: [shard 2] storage_proxy - Failed to apply mutation from 10.0.135.227#2: seastar::semaphore_timed_out (Semaphore timedout)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !WARNING | scylla: [shard 2] storage_proxy - Failed to apply mutation from 10.0.135.227#2: seastar::semaphore_timed_out (Semaphore timedout)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !WARNING | scylla: [shard 2] storage_proxy - Failed to apply mutation from 10.0.135.227#2: seastar::semaphore_timed_out (Semaphore timedout)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !WARNING | scylla: [shard 2] storage_proxy - Failed to apply mutation from 10.0.135.227#2: seastar::semaphore_timed_out (Semaphore timedout)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !WARNING | scylla: [shard 2] storage_proxy - Failed to apply mutation from 10.0.135.227#2: seastar::semaphore_timed_out (Semaphore timedout)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !WARNING | scylla: [shard 2] storage_proxy - Failed to apply mutation from 10.0.135.227#2: seastar::semaphore_timed_out (Semaphore timedout)
2020-08-06T20:33:47+00:00  longevity-tls-1tb-7d-4-2-db-node-b087b30f-2 !ERR     | scylla: [shard 1] storage_proxy - Exception when communicating with 10.0.7.227, to read from keyspace_deflate.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
```
After nemesis was failed, The status of node2 was reported as DN, but no any other critical errors, rebooting, coredump were found.
Db log:
[system.log.tar.gz](https://github.com/scylladb/scylla/files/5049325/system.log.tar.gz)
Monitoring stack is still running:
http://34.243.237.74:3000/d/YLH3J64Gz/scylla-per-server-metrics-nemesis-master?orgId=1&from=1596520228501&to=1596784106208&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All

**Comment by slivne** [comment]
repair was fixed post 4.2.rc2 - I am closing this issue - if it happens again please reopen
