### ISSUE TITLE
Iterative add node / decomission node does not stream all the data

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#701]
the iterative test does a sequence of add node and remove node and checks at the end that all the added keys are returned in select *

head

commit 8f4e90b87a1571533c3b15be4899ad5efe2d7170
Author: Takuya ASADA <syuu@scylladb.com>
Date:   Fri Dec 18 04:18:47 2015 +0900

    dist: use tsc clocksource on AMI
    
    Stop using xen clocksource, use tsc clocksource instead.
    Fixes #462
    
    Signed-off-by: Takuya ASADA <syuu@scylladb.com>

In some runs it fails
```
shlomi@localhost~/urchin-dtest (iterative_add_decomission)$ pkill -9 java ;rm -Rf ~/.dtest/*; export CASSANDRA_DIR=~/scylla; pkill -9 scylla; KEEP_TEST_DIR=true DEBUG=true PRINT_DEBUG=true nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.iterative_add_3_node_decommission_3_node_rf_1_test
iterative_add_3_node_decommission_3_node_rf_1_test (update_cluster_layout_tests.TestUpdateClusterLayout) ... cluster ccm directory: /home/shlomi/.dtest/dtest-WbSpPl
added node2
added node3
added node4
decommissioned node2
decommissioned node3
added node5
added node6
added node7
FAIL

======================================================================
FAIL: iterative_add_3_node_decommission_3_node_rf_1_test (update_cluster_layout_tests.TestUpdateClusterLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/update_cluster_layout_tests.py", line 165, in iterative_add_3_node_decommission_3_node_rf_1_test
    self._iterative_add_decommission(node_count=3,iterations=2,rf=1)
  File "/home/shlomi/urchin-dtest/update_cluster_layout_tests.py", line 134, in _iterative_add_decommission
    self.assertEqual(len(result), iteration*node_count*100+1000, "data loss after increasing size to %d expecting %d rows %d" % (len(cluster.nodelist()),iteration*node_count*100+1000,len(result)))
AssertionError: data loss after increasing size to 7 expecting 1600 rows 1568
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-WbSpPl
dtest: DEBUG: added node2
dtest: DEBUG: added node3
dtest: DEBUG: added node4
dtest: DEBUG: decommissioned node2
dtest: DEBUG: decommissioned node3
dtest: DEBUG: added node5
dtest: DEBUG: added node6
dtest: DEBUG: added node7
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 335.823s

FAILED (failures=1)
```

**Comment by slivne** [comment]
@asias at least a first analysis from your end is needed to figure ut where the issue is ... if you add info next time I'll try todo that :)

**Comment by asias** [comment]
It looks like there is a race between  insert_c1c2(session_i) and result = session.execute(query).
Adding a sleep between them, the test is passing.

I tested with this tag on dev: asias/issue/701/v1

```
--- a/update_cluster_layout_tests.py
+++ b/update_cluster_layout_tests.py
@@ -129,7 +129,7 @@ class TestUpdateClusterLayout(Tester):
                 insert_c1c2(session_i, keys=range(iteration*100000+i*2000,iteration*100000+i*2000+100), consistency=consistency)
                 debug("added %s" % node_i.name)

-
+            time.sleep(1)
             result = session.execute(query)
             self.assertEqual(len(result), iteration*node_count*100+1000, "data loss after increasing size to %d expecting %d rows %d" % (len(cluster.nodelist()),iteration*node_count*100+1000,len(result)))

```

**Comment by asias** [comment]
sometimes sleep 1 is not enough. I tried sleep 5. 

```
==========================
RUN TEST: update_cluster_layout_tests.py:TestUpdateClusterLayout.iterative_add_3_node_decommission_3_node_rf_1_test
iterative_add_3_node_decommission_3_node_rf_1_test (update_cluster_layout_tests.TestUpdateClusterLayout) ... cluster ccm directory: /home/asias/.dtest/dtest-qVorpd
added node2
added node3
added node4
decommissioned node2
decommissioned node3
added node5
added node6
added node7
decommissioned node4
decommissioned node5
decommissioned node6
decommissioned node1
ok

----------------------------------------------------------------------
Ran 1 test in 594.010s

OK
==========================
```

**Comment by asias** [comment]
Running the test against c*. It passes without the sleep.

**Comment by dorlaor** [comment]
On Fri, Dec 25, 2015 at 12:09 PM, Asias He <notifications@github.com> wrote:

> Running the test against c*. It passes without the sleep.
>

Isn't there a better method than these random sleep times? Using state and
re-try for instance?

**Comment by asias** [comment]
On Dec 26, 2015 3:38 AM, "Dor Laor" <notifications@github.com> wrote:
>
> On Fri, Dec 25, 2015 at 12:09 PM, Asias He <notifications@github.com>
wrote:
>
> > Running the test against c*. It passes without the sleep.
> >
>
> Isn't there a better method than these random sleep times? Using state and
> re-try for instance?

We should figure out the root cause. Retry or sleep do not matter.

**Comment by slivne** [comment]
I tried tyo analyze if the issue is from the data being streamed by add node or from new values that have been inserted.

I added a query prior to the insert_c1c2.

```
diff --git a/update_cluster_layout_tests.py b/update_cluster_layout_tests.py
index 213ffa4..a6561e2 100644
--- a/update_cluster_layout_tests.py
+++ b/update_cluster_layout_tests.py
@@ -126,6 +126,8 @@ class TestUpdateClusterLayout(Tester):
                 node_i.start(wait_for_binary_proto=True,wait_other_notice=True)
                 session_i = self.patient_exclusive_cql_connection(node_i)
                 session_i.execute("use ks;");
+                result = session.execute(query)
+                self.assertEqual(len(result), ((iteration-1)*node_count+i-1)*100+1000, "data loss after increasing size to %d expecting %d rows %d" % (len(cluster.nodelist()),iteration*node_count*100+1000,len(result)))
                 insert_c1c2(session_i, keys=range(iteration*100000+i*2000,iteration*100000+i*2000+100), consistency=consistency)
                 debug("added %s" % node_i.name)
```

The additional assert does not fail - so the issue is indeed with the items added by the insert_c1c2.

**Comment by slivne** [comment]
@vladzcloudius take a stab at this ...

**Comment by vladzcloudius** [comment]
The original issue that caused the test to fail seems to be fixed but on the 7-th iteration of the test (I ran it in a loop) it failed with the assert from issue #774 .
