### ISSUE TITLE
Scylla installation in Debian 10 docker container (no)

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#7055]
I have a debian:buster docker container which I'm using to set up Scylla: 

`$ docker run -it debian:buster /bin/bash
`

I follow the official installation procedure as installed [at the website](https://www.scylladb.com/download/?platform=debian-10&version=scylla-4.2):

```
root@d63f32115822:/# apt-get install apt-transport-https wget gnupg2 dirmngr
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'apt' instead of 'apt-transport-https'
Package gnupg2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gpgv

E: Unable to locate package wget
E: Package 'gnupg2' has no installation candidate
E: Unable to locate package dirmngr
```

If I am new to docker I'm lost already, but fortunately I know `apt update` helps. Still it would be a good idea to add it to the official instruction.

```
root@d63f32115822:/# apt-key adv --fetch-keys https://download.opensuse.org/repositories/home:/scylladb:/scylla-3rdparty-stretch/Debian_10.0/Release.key
Executing: /tmp/apt-key-gpghome.PFSL06Z6rV/gpg.1.sh --fetch-keys https://download.opensuse.org/repositories/home:/scylladb:/scylla-3rdparty-stretch/Debian_10.0/Release.key
gpg: requesting key from 'https://download.opensuse.org/repositories/home:/scylladb:/scylla-3rdparty-stretch/Debian_10.0/Release.key'
gpg: WARNING: unable to fetch URI https://download.opensuse.org/repositories/home:/scylladb:/scylla-3rdparty-stretch/Debian_10.0/Release.key: No data
```

**gpg: WARNING: unable to fetch URI https://download.opensuse.org/repositories/home:/scylladb:/scylla-3rdparty-stretch/Debian_10.0/Release.key: No data** doesn't look good to me:

```
% curl -I https://download.opensuse.org/repositories/home:/scylladb:/scylla-3rdparty-stretch/Debian_10.0/Release.key
HTTP/2 404
...
```

I skip over a few steps of the instruction to install scylla:

```
root@d63f32115822:/# apt install scylla
...
The following packages have unmet dependencies:
 scylla : Depends: scylla-jmx but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Let's try to see what happens:

```
root@d63f32115822:/# apt install scylla-jmx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed.
...
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 scylla-jmx : Depends: openjdk-8-jre-headless but it is not installable or
                       openjdk-8-jre but it is not installable or
                       oracle-java8-set-default but it is not installable or
                       adoptopenjdk-8-hotspot-jre but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I use [a freely available port of Java 8 to Debian 10](https://linuxize.com/post/install-java-on-debian-10/) and finally get to `scylla_setup` with no arguments:

```
subprocess.CalledProcessError: Command '['mount', '/var/tmp/kernel-check.img', '/var/tmp/mnt', '-o', 'loop']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_setup", line 276, in <module>
    run('{}/scylla_kernel_check'.format(scriptsdir()))
  File "/opt/scylladb/scripts/scylla_util.py", line 342, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_kernel_check']' returned non-zero exit status 1.
```

Alright, say I, let's have a minimal io properties file:

```
$ scylla_setup --no-ntp-setup --no-ec2-check --no-enable-service --no-sysconfig-setup --no-coredump-setup --no-version-check --no-node-exporter --no-cpuscaling-setup --no-fstrim-setup --no-memory-setup --no-swap-setup --no-kernel-check --no-raid-setup
ERROR 2020-08-17 18:50:16,153 [shard 1] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
ERROR 2020-08-17 18:50:16,153 [shard 5] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
ERROR:root:['/var/lib/scylla/data', '/var/lib/scylla/commitlog', '/var/lib/scylla/hints', '/var/lib/scylla/view_hints'] did not pass validation tests, it may not be on XFS and/or has limited disk space.
This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required.
To override this error, enable developer mode as follow:
sudo /opt/scylladb/scripts/scylla_dev_mode_setup --developer-mode 1
IO configuration setup failed.
```

Alright, I follow the advice:

```
root@d63f32115822:/# scylla_setup --no-ntp-setup --no-ec2-check --no-enable-service --no-sysconfig-setup --no-coredump-setup --no-version-check --no-node-exporter --no-cpuscaling-setup --no-fstrim-setup --no-memory-setup --no-swap-setup --no-kernel-check --no-raid-setup --developer-mode 1
usage: scylla_setup [-h] (--disks DISKS | --no-raid-setup) [--nic NIC] [--ntp-domain NTP_DOMAIN]
                    [--swap-directory SWAP_DIRECTORY] [--ami] [--setup-nic-and-disks] [--developer-mode]
                    [--no-ec2-check] [--no-kernel-check] [--no-verify-package] [--no-enable-service]
                    [--no-bootparam-setup] [--no-ntp-setup] [--no-coredump-setup] [--no-sysconfig-setup]
                    [--no-io-setup] [--no-version-check] [--no-node-exporter] [--no-cpuscaling-setup]
                    [--no-fstrim-setup] [--no-memory-setup] [--no-swap-setup]
scylla_setup: error: unrecognized arguments: 1
```

Uhm, OK, let's try to work around the misleading help message:

```
root@d63f32115822:/# scylla_setup --no-ntp-setup --no-ec2-check --no-enable-service --no-sysconfig-setup --no-coredump-setup --no-version-check --no-node-exporter --no-cpuscaling-setup --no-fstrim-setup --no-memory-setup --no-swap-setup --no-kernel-check --no-raid-setup --developer-mode 1
usage: scylla_setup [-h] (--disks DISKS | --no-raid-setup) [--nic NIC] [--ntp-domain NTP_DOMAIN]
                    [--swap-directory SWAP_DIRECTORY] [--ami] [--setup-nic-and-disks] [--developer-mode]
                    [--no-ec2-check] [--no-kernel-check] [--no-verify-package] [--no-enable-service]
                    [--no-bootparam-setup] [--no-ntp-setup] [--no-coredump-setup] [--no-sysconfig-setup]
                    [--no-io-setup] [--no-version-check] [--no-node-exporter] [--no-cpuscaling-setup]
                    [--no-fstrim-setup] [--no-memory-setup] [--no-swap-setup]
scylla_setup: error: unrecognized arguments: 1
bind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: WARNING: unable to mbind shard memory; performance may suffer: 

WARNING: unable to mbind shard memory; performance may suffer: 
ERROR 2020-08-17 18:52:42,497 [shard 30] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
ERROR:root:['/var/lib/scylla/data', '/var/lib/scylla/commitlog', '/var/lib/scylla/hints', '/var/lib/scylla/view_hints'] did not pass validation tests, it may not be on XFS and/or has limited disk space.
This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required.
To override this error, enable developer mode as follow:
sudo /opt/scylladb/scripts/scylla_dev_mode_setup --developer-mode 1
```

At this point I give up trying to set up Scylla on Debian 10.

**Comment by slivne** [comment]
@penberg can we close this

**Comment by slivne** [comment]
@penberg ping

**Comment by penberg** [comment]
I'm closing this as the specific issue mentioned by @kostja is fixed, and there's a simpler way to install:

```
curl -sSf get.scylladb.com/server | sudo bash
```
