### ISSUE TITLE
scylla-gdb.py: scylla task does not work

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#7058]
Scylla: ee7291aa882d925d3de3dd3db14df443db020034

$ gdb -v
GNU gdb (GDB) Fedora 8.3.50.20190824-30.fc31
The scylla task-queues shows there are tasks in a task queue but scylla tasks command failed to show it.

```
(gdb) scylla task-queues
   id name                             shares  tasks
   00 "main"                           1000.00 0
   01 "atexit"                         1000.00 0
*A 02 "streaming"                       200.00 1
   03 "compaction"                       64.10 0
   04 "mem_compaction"                 1000.00 0
   05 "statement"                      1000.00 0
   06 "memtable"                          1.00 0
   07 "memtable_to_cache"               200.00 0
(gdb) scylla tasks
Traceback (most recent call last):
  File "scylla-gdb.py", line 2486, in invoke
    for ptr in get_local_tasks():
  File "scylla-gdb.py", line 2427, in get_local_tasks
    for t in circular_buffer(tq['_q']):
  File "scylla-gdb.py", line 2375, in __iter__
    yield st[self._mask(i)]
  File "scylla-gdb.py", line 2366, in _mask
    return i & (int(self['_impl']['capacity']) - 1)
  File "scylla-gdb.py", line 2387, in __getitem__
    return (impl['storage'] + self._mask(int(impl['begin']) + item)).dereference()
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Error occurred in Python: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by avikivity** [comment]
Not backporting gdb, though maybe I should.
