### ISSUE TITLE
Nodetool rebuild command failed after scylla up

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#7066]
*Installation details*
Scylla version (or git commit hash): 4.2.rc2-0.20200817.b052f3f5c
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0eadd1bdaace4c843(eu-north-1)

During job https://jenkins.scylladb.com/job/scylla-4.2/job/gemini-/job/gemini-3h-with-nemesis-test/34/ first run of nemesis CorruptThenRebuild failed. Nemesis logic is : Stop scylla, remove several sstables, Start scylla and run command nodetool rebuild.

The command nodetool rebuild right after scylla was up, failed with next error:
```
2020-08-17T09:00:02+00:00  gemini-with-nemesis-3h-normal-4-2-db-node-41cf63a0-2 !INFO    | scylla: [shard 0] init - serving
2020-08-17T09:00:02+00:00  gemini-with-nemesis-3h-normal-4-2-db-node-41cf63a0-2 !INFO    | scylla: [shard 0] init - Scylla version 4.2.rc2-0.20200817.b052f3f5c initialization completed.
2020-08-17T09:00:02+00:00  gemini-with-nemesis-3h-normal-4-2-db-node-41cf63a0-2 !INFO    | scylla: [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-16-big-Data.db:level=0, ]. 82kB to 76kB (~93% of original) in 80ms = 959kB/s. ~256 total partitions merged to 2.
```

```
< t:2020-08-17 09:00:46,223 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > error: org.apache.cassandra.db:type=StorageService
 Error executing command: "nodetool  rebuild "; Exit status: 2
 STDERR: error: org.apache.cassandra.db:type=StorageService
 -- StackTrace --
 javax.management.InstanceNotFoundException: org.apache.cassandra.db:type=StorageService
   at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
   at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getClassLoaderFor(DefaultMBeanServerInterceptor.java:1444)
   at com.sun.jmx.mbeanserver.JmxMBeanServer.getClassLoaderFor(JmxMBeanServer.java:1324)
   at com.scylladb.jmx.utils.APIMBeanServer.getClassLoaderFor(APIMBeanServer.java:275)
   at javax.management.remote.rmi.RMIConnectionImpl$6.run(RMIConnectionImpl.java:1365)
   at java.security.AccessController.doPrivileged(Native Method)
   at javax.management.remote.rmi.RMIConnectionImpl.getClassLoaderFor(RMIConnectionImpl.java:1362)
   at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:813)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
   at sun.rmi.transport.Transport$1.run(Transport.java:200)
   at sun.rmi.transport.Transport$1.run(Transport.java:197)
   at java.security.AccessController.doPrivileged(Native Method)
   at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
   at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
   at java.security.AccessController.doPrivileged(Native Method)
   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:748)
   at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
   at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
   at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
   at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
   at javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
   at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1020)
   at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:298)
   at com.sun.proxy.$Proxy8.rebuild(Unknown Source)
   at org.apache.cassandra.tools.NodeProbe.rebuild(NodeProbe.java:1217)
   at org.apache.cassandra.tools.nodetool.Rebuild.execute(Rebuild.java:58)
   at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:270)
   at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:180)
```

No any errors were found in log. Unfortunately, the log from node were not saved, the output were taken from sct.log(where all messages also logged)
[node2.log](https://github.com/scylladb/scylla/files/5094282/node2.log)

**Comment by roydahan** [comment]
@aleksbykov let's try to run in REPRODUCERS with this nemesis only and see if we can reproduce with more information.

**Comment by slivne** [comment]
@aleksbykov ping

**Comment by aleksbykov** [comment]
2 latest runs didn't reproduce the issue.
Used  only the single nemesis CorruptThenRebuild , which cause an issue, latest 4.2.rc3 ami and gemini command with same seed(generate similar schema)  and different seed.

**Comment by slivne** [comment]
closing - if you hit it again please reopen with more information
