### ISSUE TITLE
killed_wiped_node_cannot_join_test failed

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#7073]
Scylla version 666.development-0.20200817.9aa47122

```
Error Message

18 Aug 2020 10:30:43 [node4] Missing: ['A node with address 127.0.76.4 already exists, cancelling join']:
Scylla version 666.development-0.20200817.9aa47122.....
See system.log for remainder

Stacktrace

Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/bootstrap_test.py", line 390, in killed_wiped_node_cannot_join_test
    self._wiped_node_cannot_join_test(gently=False)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/bootstrap_test.py", line 436, in _wiped_node_cannot_join_test
    node2.watch_log_for(expected_error, from_mark=mark)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 448, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 18 Aug 2020 10:30:43 [node4] Missing: ['A node with address 127.0.76.4 already exists, cancelling join']:
Scylla version 666.development-0.20200817.9aa47122.....
See system.log for remainder
```

**Comment by asias** [comment]
Fixed by: https://github.com/scylladb/scylla/pull/7074

**Comment by avikivity** [comment]
@asias what's your opinion about backporting this? How risky is it? And is the bug likely to happen outside a test scenario?

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
