### ISSUE TITLE
test_nodetool_refresh_main_sstable_directory: Refresh in main directory succeeded unexpectedly!

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7078]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/583/testReport/backup_restore_tests/TestBackupRestore/test_nodetool_refresh_main_sstable_directory/
with scylla version 2e1499ee93f1cca310fb73476d2d781c62a4da8c

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/backup_restore_tests.py", line 699, in test_nodetool_refresh_main_sstable_directory
    self.copy_snapshot_and_verify(node1, snapshot_dir, cf_dir, expect_refresh_fail=True, verify_count=2000)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/backup_restore_tests.py", line 748, in copy_snapshot_and_verify
    raise Exception("Refresh in main directory succeeded unexpectedly! It's no longer supported from 4.1")
Exception: Refresh in main directory succeeded unexpectedly! It's no longer supported from 4.1
```

but it fails also with 4.2 at 6ae6eb97b2a4b33f6ac442dea4e0bc44d19987e4

This is probably a result of off-strategy compaction.

and passed with 4.1 at 79c00d66e587d7a2ddc3f948e9f61261bcb42bc6

**Comment by raphaelsc** [comment]
looks like a dup of https://github.com/scylladb/scylla/issues/7022

**Comment by bhalevy** [comment]
Duplicate of #7022
