### ISSUE TITLE
Node gets overloaded when other node is preparing for upgrade

### ISSUE THREAD

**Issue by nizarh11** [scylladb/scylla#7112]
*Installation details*
Scylla version (or git commit hash): Scylla version 4.1.5-0.20200817.382dcb9d34f with build-id 81e17a64e43d05e201237c9322c225d5f005ab2c 
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI):

**Node was overloaded [Too many in flight hints: 10485768] while another node was preparing for the upgrade on debian9**

Error:

```


2020-08-24 15:10:07.697: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=12733 node=Node rolling-upgrade-master-debian-stret-loader-node-c6a87d83-0-1 [35.227.27.211 | 10.142.0.70] (seed: False)
com.datajava.io.IOException: Operation x10 on key(s) [32383730364c38353630]: Error executing: (OverloadedException): Queried host (rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042) was overloaded: Too many in flight hints: 10485768

```

Node gets overloaded message:

```
< t:2020-08-24 15:10:04,269 f:cluster.py      l:1359 c:sdcm.cluster         p:DEBUG > 2020-08-24T15:09:51+00:00  rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-4 !ERR     | scylla:  [shard 0] rpc - client 10.142.0.20:7001: fail to connect: Connection refused
< t:2020-08-24 15:10:04,269 f:cluster.py      l:1359 c:sdcm.cluster         p:DEBUG > 2020-08-24T15:09:54+00:00  rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-4 !ERR     | scylla:  [shard 0] rpc - client 10.142.0.20:7001: fail to connect: Connection refused
< t:2020-08-24 15:10:04,270 f:cluster.py      l:1359 c:sdcm.cluster         p:DEBUG > 2020-08-24T15:09:57+00:00  rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-4 !ERR     | scylla:  [shard 0] rpc - client 10.142.0.20:7001: fail to connect: Connection refused
< t:2020-08-24 15:10:04,270 f:cluster.py      l:1359 c:sdcm.cluster         p:DEBUG > 2020-08-24T15:10:02+00:00  rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-4 !ERR     | scylla:  [shard 0] rpc - client 10.142.0.20:7001: fail to connect: Connection refused
< t:2020-08-24 15:10:04,271 f:cluster.py      l:1359 c:sdcm.cluster         p:DEBUG > 2020-08-24T15:10:04+00:00  rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-4 !ERR     | scylla:  [shard 0] rpc - client 10.142.0.20:7001: fail to connect: Connection refused
< t:2020-08-24 15:10:04,457 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,451 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,458 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,454 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,458 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,454 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,458 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,454 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,458 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,454 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,458 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,454 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,459 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,455 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,459 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,455 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,460 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042) was overloaded: Too many in flight hints: 10485768
< t:2020-08-24 15:10:04,460 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042) was overloaded: Too many in flight hints: 10485768
< t:2020-08-24 15:10:04,460 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042) was overloaded: Too many in flight hints: 10485768
< t:2020-08-24 15:10:04,460 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042) was overloaded: Too many in flight hints: 10485768
< t:2020-08-24 15:10:04,474 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042) was overloaded: Too many in flight hints: 10485768
< t:2020-08-24 15:10:04,474 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042) was overloaded: Too many in flight hints: 10485768
< t:2020-08-24 15:10:04,474 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042) was overloaded: Too many in flight hints: 10485768
< t:2020-08-24 15:10:04,474 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OverloadedException: Queried host (rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042) was overloaded: Too many in flight hints: 10485768
< t:2020-08-24 15:10:04,500 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,455 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,501 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,498 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,501 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,498 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.
< t:2020-08-24 15:10:04,501 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > WARN  15:10:04,498 Host rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1.c.skilled-adapter-452.internal/10.142.0.13:9042 is overloaded.


```

After this we get Oversized Allocation message:

```

Aug 24 15:10:01 rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1 scylla[18806]:  [shard 0] seastar_memory - oversized allocation: 1310720 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at   0x325397d
                                                                                          0x2d7a724
                                                                                          0x2d7f4eb
                                                                                          0x1caa794
                                                                                          0x1ca0b94
                                                                                          0x1ca109d
                                                                                          0x1934695
                                                                                          0x18f241b
                                                                                          0x18f2748
                                                                                          0x1988a08
                                                                                          0x18ded57
                                                                                          0x194933d
                                                                                          0x194800f
                                                                                          0x194c390
                                                                                          0x2d6150c
                                                                                          0x2dbe6d0
                                                                                          0x2dbe8df
                                                                                          0x2df36f5
                                                                                          0x2d5deb9
                                                                                          0x2d5ef6e
                                                                                          0xd2bb26
                                                                                          /opt/scylladb/libreloc/libc.so.6+0x271a2
                                                                                          0xc5102d
Aug 24 15:10:02 rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1 scylla[18806]:  [shard 0] rpc - client 10.142.0.20:7001: fail to connect: Connection refused
Aug 24 15:10:03 rolling-upgrade-master-debian-stret-db-node-c6a87d83-0-1 scylla[18806]:  [shard 0] rpc - client 10.142.0.20:7001: fail to connect: Connection refused

```

Important to mention that during the run and before the preparation for the upgrade, we had many exceptions during cs runs:

```
< t:2020-08-24 14:31:21,928 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```

or

```
< t:2020-08-24 14:32:39,626 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
< t:2020-08-24 14:32:39,627 f:base.py         l:235  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ALL (3 responses were required but only 2 replica responded, 1 failed)
```

Jenkins Job:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-debian9-test/58/consoleFull

Logs [test id c6a87d83-2eb2-4d20-82f2-7727938268ef ]                                                                                             

| 20190101_010101 | prometheus  | https://cloudius-jenkins-test.s3.amazonaws.com/c6a87d83-2eb2-4d20-82f2-7727938268ef/prometheus_snapshot_20200824_151958.tar.gz                                                                                                             |
| 20200824_151042 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/c6a87d83-2eb2-4d20-82f2-7727938268ef/20200824_151042/grafana-screenshot-overview-20200824_151043-rolling-upgrade-master-debian-stret-monitor-node-c6a87d83-0-1.png                          |
| 20200824_151042 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/c6a87d83-2eb2-4d20-82f2-7727938268ef/20200824_151042/grafana-screenshot-scylla-per-server-metrics-nemesis-20200824_151446-rolling-upgrade-master-debian-stret-monitor-node-c6a87d83-0-1.png |
| 20200824_152008 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/c6a87d83-2eb2-4d20-82f2-7727938268ef/20200824_152008/grafana-screenshot-overview-20200824_152009-rolling-upgrade-master-debian-stret-monitor-node-c6a87d83-0-1.png                          |
| 20200824_152008 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/c6a87d83-2eb2-4d20-82f2-7727938268ef/20200824_152008/grafana-screenshot-scylla-per-server-metrics-nemesis-20200824_152315-rolling-upgrade-master-debian-stret-monitor-node-c6a87d83-0-1.png |
| 20200824_152901 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/c6a87d83-2eb2-4d20-82f2-7727938268ef/20200824_152901/db-cluster-c6a87d83.zip                                                                                                                |
| 20200824_152901 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/c6a87d83-2eb2-4d20-82f2-7727938268ef/20200824_152901/loader-set-c6a87d83.zip                                                                                                                |
| 20200824_152901 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/c6a87d83-2eb2-4d20-82f2-7727938268ef/20200824_152901/monitor-set-c6a87d83.zip                                                                                                               |
| 20200824_152901 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/c6a87d83-2eb2-4d20-82f2-7727938268ef/20200824_152901/sct-runner-c6a87d83.zip                                                                                                                |

**Comment by roydahan** [comment]
This is happening only in debian9, right?

**Comment by nizarh11** [comment]
> This is happening only in debian9, right?

yes

**Comment by ShlomiBalalis** [comment]
Probably related to #6964, maybe even the same issue

**Comment by dkropachev** [comment]
Hello, we have faced exact same problem on **docker/kubernetes**:
Node3 become overloaded right after Node2 was shutdown
test_id: **daaf7498-9fa1-4f4a-980f-2903e44cfefb**
scylla version: **4.1.7-0.20200918.2251a1c577 with build-id 36f8a7b490fb7f7638d7828dfe92eecc2c31cbd9**

db-logs:
https://cloudius-jenkins-test.s3.amazonaws.com/daaf7498-9fa1-4f4a-980f-2903e44cfefb/20201013_152121/db-cluster-daaf7498.zip

sct-logs:
https://cloudius-jenkins-test.s3.amazonaws.com/daaf7498-9fa1-4f4a-980f-2903e44cfefb/20201013_152121/sct-runner-daaf7498.zip

loader-logs:
https://cloudius-jenkins-test.s3.amazonaws.com/daaf7498-9fa1-4f4a-980f-2903e44cfefb/20201013_152121/loader-set-daaf7498.zip

Same log messages there:

```
< t:2020-10-13 12:21:40,513 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > WARN  12:21:40,509 Host 10.123.245.195/10.123.245.195:9042 is overloaded.
< t:2020-10-13 12:21:40,515 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OverloadedException: Queried host (10.123.245.195/10.123.245.195:9042) was overl>
< t:2020-10-13 12:21:40,517 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > WARN  12:21:40,514 Host 10.123.245.195/10.123.245.195:9042 is overloaded.
```

```
WARN  2020-10-13 12:21:39,870 [shard 4] seastar_memory - oversized allocation: 1310720 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at   0x326f94d
  0x2d966d4
  0x2d9b49b
  0x1cb8924
  0x1caed24
  0x1caf22d
  0x1940475
  0x190040b
  0x1900738
  0x1996a08
  0x18ecd47
  0x19551bd
  0x1953e8f
  0x1958210
  0x2d7d4bc
  0x2dda680
  0x2dda88f
  0x2e0f705
  0x2e1de3c
  0x2dacf7d
  /opt/scylladb/libreloc/libpthread.so.0+0x94e1
  /opt/scylladb/libreloc/libc.so.6+0x1016a2

```

```
< t:2020-10-13 12:20:14,977 f:kubernetes_cmd_runner.py l:152  c:KubernetesCmdRunner  p:DEBUG > Running command "supervisorctl stop scylla"...
< t:2020-10-13 12:20:28,453 f:base.py         l:220  c:KubernetesCmdRunner  p:DEBUG > scylla: started
< t:2020-10-13 12:20:28,455 f:base.py         l:140  c:KubernetesCmdRunner  p:DEBUG > Command "supervisorctl start scylla" finished with status 0

```

Nemesis plan:

```
19:06:35 < t:2020-10-13 TruncateMonkeyLargePartition on sct-cluster-us-east1-c-us-east1-1 [10.123.253.223 | 10.123.253.223]
19:20:15 < t:2020-10-13 CorruptThenRebuild on sct-cluster-us-east1-c-us-east1-1 [10.123.253.223 | 10.123.253.223]
```

**Comment by bentsi** [comment]
another strange thing is that c-s stopped any writes after this happened but the command didn't exit till the end of the test
![image](https://user-images.githubusercontent.com/5269241/95974995-50108600-0e1e-11eb-86ed-e3f79d01cf9d.png)
Till the  end of the test C-S printed following errors:

```
< t:2020-10-13 15:04:47,730 > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query a
< t:2020-10-13 15:04:47,730 > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query a
< t:2020-10-13 15:04:47,730 > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query a
< t:2020-10-13 15:04:47,730 > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query a
< t:2020-10-13 15:04:47,730 > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query a
< t:2020-10-13 15:04:47,730 > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query a
< t:2020-10-13 15:04:47,730 > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query a
< t:2020-10-13 15:04:47,730 > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query a
< t:2020-10-13 15:04:47,730 > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query a
< t:2020-10-13 15:04:47,730 > WARN  12:22:22,321 Error creating netty channel to 10.123.253.223/10.123.253.223:9042                   
< t:2020-10-13 15:04:47,730 > com.datastax.shaded.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 10.123.
< t:2020-10-13 15:04:47,730 >  at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_262]                            
< t:2020-10-13 15:04:47,730 >  at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_262]              
< t:2020-10-13 15:04:47,730 >  at com.datastax.shaded.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:
< t:2020-10-13 15:04:47,730 >  at com.datastax.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNio
< t:2020-10-13 15:04:47,730 >  at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634) [scylla
< t:2020-10-13 15:04:47,730 >  at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:58
< t:2020-10-13 15:04:47,730 >  at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [scyll
< t:2020-10-13 15:04:47,730 >  at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) [scylla-driver-core-3.
< t:2020-10-13 15:04:47,730 >  at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.
< t:2020-10-13 15:04:47,730 >  at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:3
< t:2020-10-13 15:04:47,730 >  at java.lang.Thread.run(Thread.java:748) [na:1.8.0_262]                                                
< t:2020-10-13 15:04:47,730 > Caused by: java.net.ConnectException: Connection refused                                                
< t:2020-10-13 15:04:47,730 >  ... 11 common frames omitted                                                                           

```
After truncate Nemesis started, hints started to drop

![image](https://user-images.githubusercontent.com/5269241/95977699-d7132d80-0e21-11eb-9959-945247975034.png)


To restore Scylla Monitoring use: `hydra investigate show-monitor daaf7498-9fa1-4f4a-980f-2903e44cfefb`
