### ISSUE TITLE
getendpoints_test: failed: marshal_exception (marshaling error: Invalid number format 'value')

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7145]
Regression seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/592/testReport/nodetool_additional_test/TestNodetool/getendpoints_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 946, in getendpoints_test
    endpoint = self.getendpoints(node, "ks1", "tbl1", "4")
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 932, in getendpoints
    return node.nodetool('getendpoints ' + ks + ' ' + cf + ' value', True)[0]
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 737, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/f063dc22af7de97d90aefdb33fe174cec80b277b/scylla-tools-java/bin/nodetool -h 127.0.74.1 -p 7174 getendpoints ks1 tbl1 value' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP GET to URL '/storage_service/natural_endpoints/ks1' failed: marshal_exception (marshaling error: Invalid number format 'value')
```

Most likely this was caused by 68b3ed1c9a166c0d315da3cb3621802e02203143
That fixed #7134

@amnonh please take a look

**Comment by amnonh** [comment]
This is, in fact, a problem with the test, I'll send a fix shortly.
