### ISSUE TITLE
cdc_tests: check_preimage: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7148]
Seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/590/testReport/junit/cdc_tests/
scylla-dtest vesion a237e953d796b39f7e743edb2cfdb8ca681377a6
scylla version d18af34205d2e1661ef84ecf7f54dad58184a8e8
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_tests.py", line 291, in add_field_with_cdc_and_preimage_test
    self.schema_change_template("ALTER TABLE ks.cf ADD c int", with_preimage=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_tests.py", line 276, in schema_change_template
    self.check_common_invariants(session, base_rows, log_rows, update_rows, write_count, with_preimage)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_tests.py", line 366, in check_common_invariants
    self.check_preimage(log_rows)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_tests.py", line 377, in check_preimage
    preimage_row, update_row = list(write)
ValueError: not enough values to unpack (expected 2, got 1)
```

I suspect this could be a result of e50911e5b0cc1e2848a67ae8e0c7b73925bbebfd

Cc @haaawk @kbr-

**Comment by bhalevy** [comment]
Also, https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/590/testReport/cdc_types_test/ ssem to be failing preimage validation, for example:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_types_test.py", line 730, in test_insert_udt_preimage
    self.insert_udt_tpl(preimage_enable=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_types_test.py", line 788, in insert_udt_tpl
    postimage_enable)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_types_test.py", line 877, in verify_cdc_log_rows_with_udt
    expected_data=expected_udt_result['preimage'])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cdc_types_test.py", line 165, in check_cdc_log_row_udt
    self.assertEqual(row.cdc_operation, operation)
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
```

**Comment by kbr-** [comment]
@elcallio your change broke it, so maybe you could fix it :P
I'm guessing most of the work would be done by simply reverting 26902586eee4be6ca28039a55fd7b590887b14ba, but that commit was only about preimages, and the change affected postimages too, so additional work may be needed.

**Comment by elcallio** [comment]
Yeah, I am already on it. Will send patch in a minute.

**Comment by elcallio** [comment]
See /scylladb/scylla-dtest#1659

**Comment by bhalevy** [comment]
Fixed with https://github.com/scylladb/scylla-dtest/pull/1660
