### ISSUE TITLE
Scylla throws an out_of_range exception and fails to start up

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#718]
```
[penberg@nero scylla]$ ./build/release/scylla --commitlog-directory node3/commitlog --data-file-directories node3/data --listen-address 127.0.0.3 --rpc-address 127.0.0.3 --seed-provider-parameters seeds=127.0.0.3 --smp 2 
Scylla version development-20151228.561bb79 starting ...
WARN  [shard 0] config - Option partitioner is not (yet) used.
Start Storage service ...
WARN  [shard 0] init - node3/commitlog is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is strongly recommended
WARN  [shard 0] init - node3/data is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is strongly recommended
Start gossiper service ...
Exiting on unhandled exception of type 'std::out_of_range': _Map_base::at
```

```
Catchpoint 1 (exception thrown), 0x00007ffff729805d in __cxa_throw () from /lib64/libstdc++.so.6
(gdb) bt
#0  0x00007ffff729805d in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x00007ffff72f1dc6 in std::__throw_out_of_range(char const*) () from /lib64/libstdc++.so.6
#2  0x0000000000e07c0a in std::__detail::_Map_base<basic_sstring<char, unsigned int, 15u>, std::pair<basic_sstring<char, unsigned int, 15u> const, basic_sstring<char, unsigned int, 15u> >, std::allocator<std::pair<basic_sstring<char, unsigned int, 15u> const, basic_sstring<char, unsigned int, 15u> > >, std::__detail::_Select1st, std::equal_to<basic_sstring<char, unsigned int, 15u> >, std::hash<basic_sstring<char, unsigned int, 15u> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::at (
    this=<optimized out>, __k=...) at /usr/include/c++/4.9.2/bits/hashtable_policy.h:672
#3  0x0000000000dafc2f in service::storage_service::start_native_transport()::{lambda(service::storage_service&)#1}::operator()(service::storage_service&) const::{lambda(dns::hostent)#1}::operator()(dns) const::{lambda()#1}::operator()() const () at /usr/include/c++/4.9.2/bits/unordered_map.h:648
#4  0x0000000000db09dc in apply (args=<optimized out>, func=<unknown type in /home/penberg/scylla/build/release/scylla, CU 0xbee90ed, DIE 0xc404af0>)
    at /home/penberg/scylla/seastar/core/apply.hh:34
#5  apply<service::storage_service::start_native_transport()::<lambda(service::storage_service&)>::<lambda(dns::hostent)>::<lambda()> > (
    args=<optimized out>, func=<unknown type in /home/penberg/scylla/build/release/scylla, CU 0xbee90ed, DIE 0xc404b5e>)
    at /home/penberg/scylla/seastar/core/apply.hh:42
#6  apply<service::storage_service::start_native_transport()::<lambda(service::storage_service&)>::<lambda(dns::hostent)>::<lambda()> > (
    args=<optimized out>, func=<unknown type in /home/penberg/scylla/build/release/scylla, CU 0xbee90ed, DIE 0xc404b9e>)
    at /home/penberg/scylla/seastar/core/future.hh:1193
#7  operator()<future_state<> > (state=<optimized out>, __closure=<optimized out>) at /home/penberg/scylla/seastar/core/future.hh:842
#8  continuation<future<T>::then(Func&&) [with Func = service::storage_service::start_native_transport()::<lambda(service::storage_service&)>::<lambda(dns::hostent)>::<lambda()>; Result = future<>; T = {}]::<lambda(auto:3&&)> >::run(void) (this=<optimized out>) at /home/penberg/scylla/seastar/core/future.hh:399
#9  0x000000000047cf3f in reactor::run_tasks (this=this@entry=0x60000022c000, tasks=...) at core/reactor.cc:1318
#10 0x00000000004aa72b in reactor::run (this=0x60000022c000) at core/reactor.cc:1622
#11 0x000000000051dc76 in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffda30, ac=ac@entry=13, 
    av=av@entry=0x7fffffffdc78, func=func@entry=<unknown type in /home/penberg/scylla/build/release/scylla, CU 0x61f64c, DIE 0x6c64b0>)
    at core/app-template.cc:123
#12 0x0000000000424aab in main (ac=13, av=0x7fffffffdc78) at main.cc:415
```

Reverting the merge 561bb79d22cc177c9f8ae45b0034384b047735ea fixes the issue.

**Comment by penberg** [comment]
Ping @elcallio @avikivity

**Comment by penberg** [comment]
@elcallio @avikivity I sent a patch to fix this up.
