### ISSUE TITLE
disable_autocompaction_nodetool_test failed: std::runtime_error (Too early: storage service not initialized yet)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7199]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/601/testReport/compaction_test/TestCompaction_with_SizeTieredCompactionStrategy/disable_autocompaction_nodetool_test/
Scylla version f76c519c1fc9f511383024b83f3b015833a65736
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/compaction_test.py", line 374, in disable_autocompaction_nodetool_test
    enable_mark = self.enable_autocompaction(node=node, ks=self.primary_ks, table=self.primary_table)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/compaction_test.py", line 541, in enable_autocompaction
    node.nodetool(f'enableautocompaction {ks} {table}')
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 737, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/f76c519c1fc9f511383024b83f3b015833a65736/scylla-tools-java/bin/nodetool -h 127.0.73.1 -p 7173 enableautocompaction ks to_disable' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/auto_compaction/ks' failed: std::runtime_error (Too early: storage service not initialized yet)
See 'nodetool help' or 'nodetool help <command>'.
```

This is very strange since the tests actually creates tables, writes data, and waits for compaction to start before disabling autocompaction.

From https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/601/artifact/logs-release.2/dtest.log:
```
bhalevy@lt tmp$ grep TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test dtest-601.log
2020-09-08 08:15:00,627 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - cluster ccm directory: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-5ffvtcgt
2020-09-08 08:15:00,628 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - Starting Scylla cluster version f76c519c1fc9f511383024b83f3b015833a65736
2020-09-08 08:15:00,643 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - Allocated cluster ID 73: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-5ffvtcgt
2020-09-08 08:15:00,668 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - Cluster *_request_timeout_in_ms=10000, cql request_timeout=30
2020-09-08 08:15:00,677 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - configuring skip_wait_for_gossip_to_settle=0 for single_node test
2020-09-08 08:15:03,378 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - CREATE COLUMNFAMILY to_disable (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {} AND compaction={'class':'SizeTieredCompactionStrategy'}
2020-09-08 08:15:03,687 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - CREATE COLUMNFAMILY std1 (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {} AND compaction={'class':'SizeTieredCompactionStrategy'}
2020-09-08 08:16:53,653 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - Test failed with errors: [(<compaction_test.TestCompaction_with_SizeTieredCompactionStrategy testMethod=disable_autocompaction_nodetool_test>, (<class 'ccmlib.node.NodetoolError'>, NodetoolError("Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/f76c519c1fc9f511383024b83f3b015833a65736/scylla-tools-java/bin/nodetool -h 127.0.73.1 -p 7173 enableautocompaction ks to_disable' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/auto_compaction/ks' failed: std::runtime_error (Too early: storage service not initialized yet)\nSee 'nodetool help' or 'nodetool help <command>'.\n"), <traceback object at 0x7f380cc29f50>))]
2020-09-08 08:16:53,679 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - removing ccm cluster test at: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-5ffvtcgt
2020-09-08 08:16:54,780 9555    dtest                          DEBUG    | compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test - Freeing cluster ID 73: link /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/73
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/601/artifact/logs-release.2/1599553013660_compaction_test.TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test/node1.log
shows no error.

**Comment by bhalevy** [comment]
In https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/601/artifact/logs-release.2/1599553013660_compaction_test.TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_nodetool_test/node1.log there is the following message:
```
INFO  2020-09-08 08:15:02,096 [shard 0] storage_service - Loading persisted ring state
```
that indicates shard 0 passed through `storage_service::init_server`
https://github.com/scylladb/scylla/blob/f76c519c1fc9f511383024b83f3b015833a65736/service/storage_service.cc#L1606

After
https://github.com/scylladb/scylla/blob/f76c519c1fc9f511383024b83f3b015833a65736/service/storage_service.cc#L1598

**Comment by bhalevy** [comment]
[[PATCH v1 0/4] storage_service: set_tables_autocompaction: run_with_api_lock](https://groups.google.com/g/scylladb-dev/c/2IARFnrGuHQ/m/jpvXBN2LAQAJ) is on the ML (Approved by @raphaelsc)
