### ISSUE TITLE
Load failed with java.io.IOException: Operation x10 on key(s) on multidc cluster during adding new node

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#7227]
*Installation details*
Scylla version (or git commit hash): 4.2.rc4-0.20200907.bf0c493c28 with build-id 49cc32b091e40433f7006467b50f2e6722d6074b
Cluster size: 6 nodes in 2 dc
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0c145d7f41255036c ami-0c80384341ee0f4eb (eu-west-1 us-east-1)
instance type: i3.4xlarge

Job https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/longevity/job/longevity-alternator-3h-multidc-test/9 failed because c-s command failed with messages:
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
java.io.IOException: Operation x10 on key(s) [4d363339505035383531]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
FAILURE
java.lang.RuntimeException: Failed to execute stress action
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:101)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

Cluster consists of 2 datacents with 3 nodes in each one. Next stress commands are ran 
```
stress_cmd: [
  "cassandra-stress write cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=20 -pop seq=1..6990500 -col 'n=FIXED(10) size=FIXED(512)' -log interval=5",
  "cassandra-stress read  cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=20 -pop seq=1..6990500 -col 'n=FIXED(10) size=FIXED(512)' -log interval=5",
  # with lwt table
  "bin/ycsb run dynamodb -P workloads/workloadc -threads 20 -p readproportion=0.5 -p updateproportion=0.5 -p recordcount=6990500 -p fieldcount=10 -p fieldlength=512 -p operationcount=200200300 -p dataintegrity=true",
  # no lwt table
  "bin/ycsb run dynamodb -P workloads/workloadc -threads 20 -p readproportion=0.5 -p updateproportion=0.5 -p recordcount=6990500 -p fieldcount=10 -p fieldlength=512 -p operationcount=200200300 -p dataintegrity=true -p table=usertable_no_lwt",
]
```
Nemesis TerminateAndReplaceNode terminate node and then adding new node to cluster.
First run of this nemesis caused error in c-s command during adding new node to cluster, but c-s continue to run:
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
java.io.IOException: Operation x10 on key(s) [4c4c4f4e355030303230]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
total,        970253,      21,      21,      21,  1568.4,    71.4,  6350.2, 20048.8, 20048.8, 20048.8, 2621.6,  0.01311,      1,      0,       0,       0,       0,       0
```

Second run of this nemesis caused c-s command to fail:
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
java.io.IOException: Operation x10 on key(s) [4d363339505035383531]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
FAILURE
java.lang.RuntimeException: Failed to execute stress action
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:101)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

![Screenshot from 2020-09-14 13-22-43](https://user-images.githubusercontent.com/44991177/93050710-8f1bb200-f68d-11ea-8dc4-6d6636897e31.png)
![Screenshot from 2020-09-14 13-22-52](https://user-images.githubusercontent.com/44991177/93050720-92af3900-f68d-11ea-9921-8ce77aa7dd76.png)
![Screenshot from 2020-09-14 13-23-10](https://user-images.githubusercontent.com/44991177/93050728-96db5680-f68d-11ea-8045-001672ef4939.png)
![Screenshot from 2020-09-14 13-23-27](https://user-images.githubusercontent.com/44991177/93050739-9ba00a80-f68d-11ea-90fd-632ee80fcc52.png)

db logs: https://cloudius-jenkins-test.s3.amazonaws.com/268441a5-964d-4bba-8b3d-6245b5abe3f9/20200909_194606/db-cluster-268441a5.zip
loader logs: https://cloudius-jenkins-test.s3.amazonaws.com/268441a5-964d-4bba-8b3d-6245b5abe3f9/20200909_194606/loader-set-268441a5.zip

may similar to issues:
https://github.com/scylladb/scylla/issues/6522
https://github.com/scylladb/scylla/issues/6508

**Comment by aleksbykov** [comment]
Dashboard snapshot: https://snapshot.raintank.io/dashboard/snapshot/M5EhG6kIzct6eBDuNELlyDmmv6FUldGp

**Comment by roydahan** [comment]
Not an issue, the c-s replication startegy (which I don't understand why we even have c-s in this test) is SimpleStrategy (as you can find in the loader logs):
Replication Strategy: org.apache.cassandra.locator.SimpleStrategy
