### ISSUE TITLE
after upgrade from 4.1 to 4.2 scylla doesn't start anymore

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#7305]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.2.rc4-0.20200907.bf0c493c28
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos 7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

```
Sep 30 10:02:25 scylla systemd[1]: Starting Scylla Server...
Sep 30 10:02:25 scylla scylla_prepare[2081]: Traceback (most recent call last):
Sep 30 10:02:25 scylla scylla_prepare[2081]: File "/opt/scylladb/scripts/libexec/scylla_prepare", line 28, in <module>
Sep 30 10:02:25 scylla scylla_prepare[2081]: from scylla_util import *
Sep 30 10:02:25 scylla scylla_prepare[2081]: File "/opt/scylladb/scripts/scylla_util.py", line 35, in <module>
Sep 30 10:02:25 scylla scylla_prepare[2081]: import distro
Sep 30 10:02:25 scylla scylla_prepare[2081]: ModuleNotFoundError: No module named 'distro'
Sep 30 10:02:25 scylla systemd[1]: scylla-server.service: control process exited, code=exited status=1
Sep 30 10:02:25 scylla systemd[1]: Failed to start Scylla Server.
Sep 30 10:02:25 scylla systemd[1]: Unit scylla-server.service entered failed state.
```

I used direct rpm repo

**Comment by tarzanek** [comment]
this seems to be the cause:
https://github.com/scylladb/scylla/commit/eabcb31503eb9896abeeaefe49cd548012dca001

so python3-distro didn't get packaged?

**Comment by tarzanek** [comment]
ok
reruning
```
sudo yum update scylla\* -y
```
