### ISSUE TITLE
debian/debian/debian_files_gen.py: shutil.rmtree() ignores permission error

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#7337]
I mistakenly built deb package root user once, then re-run same build after that, debian_file_gen.py causes following backtrace:
```
[1/6] ./dist/debian/debian_files_gen.py
FAILED: build/debian/debian 
./dist/debian/debian_files_gen.py
Traceback (most recent call last):
  File "./dist/debian/debian_files_gen.py", line 51, in <module>
    shutil.copytree('dist/debian/debian', 'build/debian/debian')
  File "/usr/lib64/python3.8/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.8/shutil.py", line 455, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'build/debian/debian'
```
It because shutil.rmtree() ignores permission error, then mkdir fails since directory already exists.

**Comment by avikivity** [comment]
@syuu1228 I believe this isn't on any release branch, yes?
