### ISSUE TITLE
scylla-4.1.7: Assert failure in data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::fast_forward_to()

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#7404]
Split from https://github.com/scylladb/scylla/issues/7285

Scylla 4.1.7-0.20200918.2251a1c577.x86_64

Coredump UUID: 7ef910ea-1548-43b1-878f-f3eeed470681

Cores:
* core.scylla.996.e90241e6effe492c921b29e6a2b05fbf.42156.1601715298000000
* core.scylla.996.e098d0e88341441dab680daf54301e87.48094.1601723214000000 

Backtrace:
```
(gdb) bt
#0  0x00007f9ac99ab625 in raise () from /opt/scylladb/libreloc/libc.so.6
#1  0x00007f9ac99949ae in abort () from /opt/scylladb/libreloc/libc.so.6
#2  0x00007f9ac99947a9 in __assert_fail_base.cold () from /opt/scylladb/libreloc/libc.so.6
#3  0x00007f9ac99a3a66 in __assert_fail () from /opt/scylladb/libreloc/libc.so.6
#4  0x0000000001321b44 in data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::fast_forward_to (end=4822189730, begin=4822185715, this=<optimized out>) at ./seastar/include/seastar/core/future.hh:1114
#5  sstables::data_consume_context<sstables::data_consume_rows_context_m>::fast_forward_to (end=4822189730, begin=4822185715, this=0x6040d8a7eba8) at sstables/data_consume_context.hh:103
#6  sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}::operator()() const (this=<optimized out>) at sstables/partition.cc:406
#7  seastar::apply_helper<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}, std::tuple<>&&, std::integer_sequence<unsigned long> >::apply({lambda()#1}&&, std::tuple) (args=..., func=...) at ./seastar/include/seastar/core/apply.hh:36
#8  seastar::apply<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}&&, std::tuple<>&&) (args=..., func=...) at ./seastar/include/seastar/core/apply.hh:44
#9  seastar::futurize<seastar::future<> >::apply<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}&&, std::tuple<>&&) (args=..., func=...)
    at ./seastar/include/seastar/core/future.hh:1731
#10 seastar::future<>::then_impl<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}, seastar::future<> >(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}&&) (func=..., this=0x7f9ac61e6300)
    at ./seastar/include/seastar/core/future.hh:1277
#11 seastar::future<>::then<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}, seastar::future<> >(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}&&) (func=..., this=0x7f9ac61e6300)
    at ./seastar/include/seastar/core/future.hh:1231
#12 sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const (this=<optimized out>) at sstables/partition.cc:411
#13 0x0000000001321c05 in seastar::apply_helper<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, std::tuple<>&&, std::integer_sequence<unsigned long> >::apply({lambda()#1}&&, std::tuple<>) (args=..., func=...) at ./seastar/include/seastar/core/apply.hh:42
#14 seastar::apply<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, std::tuple<>&&) (args=..., func=...) at ./seastar/include/seastar/core/apply.hh:44
#15 seastar::futurize<seastar::future<> >::apply<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, std::tuple<>&&) (args=..., func=...) at ./seastar/include/seastar/core/future.hh:1731
#16 seastar::future<>::then_impl<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, seastar::future<> >(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&) (func=..., this=0x7f9ac61e6380) at ./seastar/include/seastar/core/future.hh:1277
#17 seastar::future<>::then<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, seastar::future<> >(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&) (func=..., this=0x7f9ac61e6380) at ./seastar/include/seastar/core/future.hh:1231
#18 sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fast_forward_to (this=0x6040d8a7e800, pr=..., timeout=...) at sstables/partition.cc:413
#19 0x00000000010b3d21 in flat_mutation_reader::fast_forward_to (timeout=..., pr=..., this=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:360
#20 mutation_reader_merger::<lambda(flat_mutation_reader&)>::operator() (__closure=0x7f9ac61e6460, __closure=0x7f9ac61e6460, mr=...) at mutation_reader.cc:554
#21 seastar::futurize<seastar::future<> >::invoke<mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)>, flat_mutation_reader&> (func=...)
    at ./seastar/include/seastar/core/future.hh:1748
#22 seastar::futurize_invoke<mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)>, flat_mutation_reader&> (func=...) at ./seastar/include/seastar/core/future.hh:1832
#23 seastar::parallel_for_each<std::_List_iterator<flat_mutation_reader>, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> > (func=..., end=..., begin=...)
    at ./seastar/include/seastar/core/future-util.hh:158
#24 seastar::internal::parallel_for_each_impl<std::__cxx11::list<flat_mutation_reader>&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> >(std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> > &, mutation_reader_merger::<lambda(flat_mutation_reader&)> &&) (range=..., func=...) at ./seastar/include/seastar/core/future-util.hh:203
#25 0x00000000010d8aae in seastar::futurize<seastar::future<> >::invoke<seastar::future<> (*&)(std::__cxx11::list<flat_mutation_reader>&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)>&&), std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> > (
    func=<synthetic pointer>: <optimized out>) at ./seastar/include/seastar/core/future.hh:1830
#26 seastar::futurize_invoke<seastar::future<> (*&)(std::__cxx11::list<flat_mutation_reader>&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)>&&), std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> > (func=<synthetic pointer>: <optimized out>)
    at ./seastar/include/seastar/core/future.hh:1832
#27 seastar::parallel_for_each<std::__cxx11::list<flat_mutation_reader>&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> > (func=..., range=...)
    at ./seastar/include/seastar/core/future-util.hh:215
#28 mutation_reader_merger::fast_forward_to (this=this@entry=0x604088951558, pr=..., timeout=timeout@entry=...) at mutation_reader.cc:553
#29 0x00000000010d8ea5 in mutation_fragment_merger<mutation_reader_merger>::fast_forward_to (timeout=..., pr=..., this=0x604088951550) at mutation_reader.cc:618
--Type <RET> for more, q to quit, c to continue without paging--
#30 combined_mutation_reader::fast_forward_to (this=0x604088951500, pr=..., timeout=...) at mutation_reader.cc:618
#31 0x000000000110cb3e in flat_mutation_reader::fast_forward_to (timeout=..., pr=..., this=0x60408857f870) at /usr/include/c++/9/bits/unique_ptr.h:360
#32 restricting_mutation_reader::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(flat_mutation_reader&)#1}::operator()(flat_mutation_reader&) const (__closure=<synthetic pointer>, __closure=<synthetic pointer>, reader=...) at mutation_reader.cc:749
#33 restricting_mutation_reader::with_reader<restricting_mutation_reader::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(flat_mutation_reader&)#1}>(restricting_mutation_reader::fast_forward_to(nonwrapping_range<dht::ring_position> const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(flat_mutation_reader&)#1}, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) (timeout=..., fn=..., this=0x60408857f820) at mutation_reader.cc:702
#34 restricting_mutation_reader::fast_forward_to (this=0x60408857f820, pr=..., timeout=...) at mutation_reader.cc:750
#35 0x00000000010b3d21 in flat_mutation_reader::fast_forward_to (timeout=..., pr=..., this=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:360
#36 mutation_reader_merger::<lambda(flat_mutation_reader&)>::operator() (__closure=0x7f9ac61e66d0, __closure=0x7f9ac61e66d0, mr=...) at mutation_reader.cc:554
#37 seastar::futurize<seastar::future<> >::invoke<mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)>, flat_mutation_reader&> (func=...)
    at ./seastar/include/seastar/core/future.hh:1748
#38 seastar::futurize_invoke<mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)>, flat_mutation_reader&> (func=...) at ./seastar/include/seastar/core/future.hh:1832
#39 seastar::parallel_for_each<std::_List_iterator<flat_mutation_reader>, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> > (func=..., end=..., begin=...)
    at ./seastar/include/seastar/core/future-util.hh:158
#40 seastar::internal::parallel_for_each_impl<std::__cxx11::list<flat_mutation_reader>&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> >(std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> > &, mutation_reader_merger::<lambda(flat_mutation_reader&)> &&) (range=..., func=...) at ./seastar/include/seastar/core/future-util.hh:203
#41 0x00000000010d8aae in seastar::futurize<seastar::future<> >::invoke<seastar::future<> (*&)(std::__cxx11::list<flat_mutation_reader>&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)>&&), std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> > (
    func=<synthetic pointer>: <optimized out>) at ./seastar/include/seastar/core/future.hh:1830
#42 seastar::futurize_invoke<seastar::future<> (*&)(std::__cxx11::list<flat_mutation_reader>&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)>&&), std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> > (func=<synthetic pointer>: <optimized out>)
    at ./seastar/include/seastar/core/future.hh:1832
#43 seastar::parallel_for_each<std::__cxx11::list<flat_mutation_reader>&, mutation_reader_merger::fast_forward_to(const partition_range&, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&)> > (func=..., range=...)
    at ./seastar/include/seastar/core/future-util.hh:215
#44 mutation_reader_merger::fast_forward_to (this=this@entry=0x604088950f58, pr=..., timeout=timeout@entry=...) at mutation_reader.cc:553
#45 0x00000000010d8ea5 in mutation_fragment_merger<mutation_reader_merger>::fast_forward_to (timeout=..., pr=..., this=0x604088950f50) at mutation_reader.cc:618
#46 combined_mutation_reader::fast_forward_to (this=0x604088950f00, pr=..., timeout=...) at mutation_reader.cc:618
#47 0x0000000001116028 in flat_mutation_reader::fast_forward_to (timeout=..., pr=..., this=<optimized out>) at flat_mutation_reader.hh:432
#48 flat_multi_range_mutation_reader<make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter>::<lambda()>::<lambda()>::operator()(void) const (this=<optimized out>, this=<optimized out>) at flat_mutation_reader.cc:699
#49 0x0000000001116d7e in seastar::apply_helper<flat_multi_range_mutation_reader<Generator>::fill_buffer(seastar::lowres_clock::time_point) [with Generator = make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter; seastar::lowres_clock::time_point = std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long int, std::ratio<1, 1000> > >]::<lambda()>::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (args=..., func=...) at ./seastar/include/seastar/core/apply.hh:42
#50 seastar::apply<flat_multi_range_mutation_reader<Generator>::fill_buffer(seastar::lowres_clock::time_point) [with Generator = make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter]::<lambda()>::<lambda()> > (args=..., func=...) at ./seastar/include/seastar/core/apply.hh:44
#51 seastar::futurize<seastar::future<> >::apply<flat_multi_range_mutation_reader<Generator>::fill_buffer(seastar::lowres_clock::time_point) [with Generator = make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter]::<lambda()>::<lambda()> > (args=..., func=...) at ./seastar/include/seastar/core/future.hh:1731
#52 seastar::future<>::then_impl<flat_multi_range_mutation_reader<Generator>::fill_buffer(seastar::lowres_clock::time_point) [with Generator = make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter]::<lambda()>::<lambda()> > (func=..., this=0x7f9ac61e6860) at ./seastar/include/seastar/core/future.hh:1277
#53 seastar::future<>::then<flat_multi_range_mutation_reader<Generator>::fill_buffer(seastar::lowres_clock::time_point) [with Generator = make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter]::<lambda()>::<lambda()> > (func=..., this=0x7f9ac61e6860) at ./seastar/include/seastar/core/future.hh:1231
#54 flat_multi_range_mutation_reader<make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter>::<lambda()>::operator() (this=<optimized out>, this=<optimized out>) at flat_mutation_reader.cc:704
#55 seastar::futurize<seastar::future<> >::invoke<flat_multi_range_mutation_reader<Generator>::fill_buffer(seastar::lowres_clock::time_point) [with Generator = make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter]::<lambda()>&> (func=<synthetic pointer>...) at ./seastar/include/seastar/core/future.hh:1748
#56 seastar::futurize_invoke<flat_multi_range_mutation_reader<Generator>::fill_buffer(seastar::lowres_clock::time_point) [with Generator = make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter]::<lambda()>&> (func=<synthetic pointer>...) at ./seastar/include/seastar/core/future.hh:1832
#57 seastar::do_until<flat_multi_range_mutation_reader<Generator>::fill_buffer(seastar::lowres_clock::time_point) [with Generator = make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter]::<lambda()>, flat_multi_range_mutation_reader<Generator>::fill_buffer(seastar::lowres_clock::time_point) [with Generator = make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter]::<lambda()> > (action=..., stop_cond=...)
    at ./seastar/include/seastar/core/future-util.hh:521
#58 flat_multi_range_mutation_reader<make_flat_multi_range_reader(schema_ptr, mutation_source, const partition_range_vector&, const query::partition_slice&, const seastar::io_priority_class&, tracing::trace_state_ptr, mutation_reader::forwarding)::adapter>::fill_buffer(seastar::lowres_clock::time_point) (this=0x60408856a770, timeout=...) at flat_mutation_reader.cc:705
#59 0x0000000000f65e3c in flat_mutation_reader::impl::operator() (this=0x60408856a770, timeout=...) at flat_mutation_reader.hh:145
#60 0x0000000002378ab8 in flat_mutation_reader::operator() (timeout=..., this=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:360
#61 streaming::<lambda(mutation_fragment*)>::<lambda(size_t)>::<lambda(seastar::rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>, seastar::rpc::source<int>)>::<lambda()>::<lambda(seastar::rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>&, mutation_fragment_stream_validator&)>::<lambda()>::operator() (__closure=__closure@entry=0x6040b12d0280) at streaming/stream_transfer_task.cc:210
#62 seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::<lambda(mutation_fragment*)>::<lambda(size_t)>::<lambda(seastar::rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>, seastar::rpc::source<int>)> mutable::<lambda()> mutable::<lambda(seastar::rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>&, mutation_fragment_stream_validator&)>::<lambda()>&>(streaming::<lambda(mutation_fragment*)>::<lambda(size_t)>::<lambda(seastar::rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>, seastar::rpc::source<int>)>::<lambda()>::<lambda(seastar::rpc::sink<frozen_m--Type <RET> for more, q to quit, c to continue without paging--
utation_fragment, streaming::stream_mutation_fragments_cmd>&, mutation_fragment_stream_validator&)>::<lambda()> &) (func=...) at ./seastar/include/seastar/core/future.hh:1748
#63 0x000000000237cd33 in seastar::futurize_invoke<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::<lambda(mutation_fragment*)>::<lambda(size_t)>::<lambda(seastar::rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>, seastar::rpc::source<int>)> mutable::<lambda()> mutable::<lambda(seastar::rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>&, mutation_fragment_stream_validator&)>::<lambda()>&> (func=...)
    at ./seastar/include/seastar/core/future.hh:1830
#64 seastar::internal::repeater<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::<lambda(mutation_fragment*)>::<lambda(size_t)>::<lambda(seastar::rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>, seastar::rpc::source<int>)> mutable::<lambda()> mutable::<lambda(seastar::rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>&, mutation_fragment_stream_validator&)>::<lambda()> >::run_and_dispose(void) (
    this=0x6040b12d0240) at ./seastar/include/seastar/core/future-util.hh:254
#65 0x0000000002dda681 in seastar::reactor::run_tasks (this=this@entry=0x60400010e000, tq=...) at ./seastar/src/core/reactor.cc:2154
#66 0x0000000002dda890 in seastar::reactor::run_some_tasks (this=this@entry=0x60400010e000) at ./seastar/src/core/reactor.cc:2569
#67 0x0000000002e0f706 in seastar::reactor::run_some_tasks (this=0x60400010e000) at ./seastar/src/core/reactor.cc:2724
#68 seastar::reactor::run (this=0x60400010e000) at ./seastar/src/core/reactor.cc:2724
#69 0x0000000002e1de3d in seastar::smp::<lambda()>::operator()(void) const (__closure=<optimized out>) at ./seastar/include/seastar/core/reactor.hh:736
#70 0x0000000002dacf7e in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/9/bits/std_function.h:683
#71 seastar::posix_thread::start_routine (arg=<optimized out>) at ./seastar/src/core/posix.cc:60
#72 0x00007f9aca3dd4e2 in start_thread () from /opt/scylladb/libreloc/libpthread.so.0
#73 0x00007f9ac9a706a3 in clone () from /opt/scylladb/libreloc/libc.so.6
```

We try to fast-forward to a position smaller than the current stream position.

**Comment by denesb** [comment]
I checked and the ranges are sorted.

**Comment by denesb** [comment]
The sstables involved: mc-81930-big-Data.db (later core) and mc-39655-big-Data.db (earlier core). @keef-cognitiv would it be possible to share these with us (all components preferably), or the index and summary ones at least?

**Comment by slivne** [comment]
@bhalevy assign this internally

**Comment by bhalevy** [comment]
Botond let's leave it with you for now until we understand the root cause better (with a good chance that the gap between understanding and a fix would be small :))

**Comment by keef-cognitiv** [comment]
Sorry for some reason I didn't get a notification on this one. I went back and checked the related issue today after someone asked me about it and I saw the reference to this. Neither of these files were part of the set this db was restored from nor still existing in the set that was backed up again later. These issues only happened on repair. Compactions still ran fine as long as they were a part of another process. So I suspect these were compacted away successfully.

**Comment by denesb** [comment]
Possibly another symptom of https://github.com/scylladb/scylla/issues/7552. This issue can generate an index with out-of-order partitions, which might result in an attempt to fast-forward-to to an earlier position in the data file.

**Comment by denesb** [comment]
Closing this, this was opened against a now unsupported version and there is no way to make progress on this issue. We also have a likely suspect in #7552 which was solved and backported to live releases. We'll open a new issue if we see this again.
