### ISSUE TITLE
AMI: got "unit scylla-ami-setup.service not found" error on 4.1.8

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#7455]
*Installation details*
Scylla version (or git commit hash): 4.1.8
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): i3en.2xlarge
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

I got following error when I logged in AMI instance:
```
   _____            _ _       _____  ____  
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        


Nodetool:
        nodetool help
CQL Shell:
        cqlsh
More documentation available at: 
        http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

Traceback (most recent call last):
  File "/opt/scylladb/scripts/scylla_util.py", line 631, in __init__
    run('systemctl {} cat {}'.format(self.ctlparam, unit), silent=True)
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['systemctl', 'cat', 'scylla-ami-setup.service']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/scylla-machine-image/libexec/scylla_login", line 111, in <module>
    setup = systemd_unit('scylla-ami-setup.service')
  File "/opt/scylladb/scripts/scylla_util.py", line 633, in __init__
    raise SystemdException('unit {} not found'.format(unit))
scylla_util.SystemdException: unit scylla-ami-setup.service not found
```

**Comment by slivne** [comment]
```
Oct 22 09:25:52 ip-10-99-0-216.ec2.internal cloud-init[1182]: Cloud-init v. 18.5 finished at Thu, 22 Oct 2020 09:25:52 +0000. Datasource DataSourceEc2Local.  Up 61.42 seconds
Oct 22 09:25:52 ip-10-99-0-216.ec2.internal systemd[1]: Started Execute cloud user/final scripts.
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,304 - [scylla_configure] - INFO - Getting 'http://169.254.169.254/latest/meta-data/local-ipv4'...
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Getting 'http://169.254.169.254/latest/meta-data/local-ipv4'...
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,307 - [scylla_configure] - INFO - Going to create scylla.yaml...
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Going to create scylla.yaml...
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,307 - [scylla_configure] - INFO - Getting 'http://169.254.169.254/latest/user-data'...
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Getting 'http://169.254.169.254/latest/user-data'...
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,308 - [scylla_configure] - WARNING - Error getting user data: HTTP Error 404: Not Found. Will use defaults!
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Error getting user data: HTTP Error 404: Not Found. Will use defaults!
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,308 - [scylla_configure] - INFO - Setting default cluster_name=scylladb-cluster-1603358756
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Setting default cluster_name=scylladb-cluster-1603358756
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,335 - [scylla_configure] - INFO - Setting default experimental=False
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Setting default experimental=False
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,335 - [scylla_configure] - INFO - Setting default auto_bootstrap=True
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Setting default auto_bootstrap=True
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,335 - [scylla_configure] - INFO - Setting default listen_address=10.99.0.216
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Setting default listen_address=10.99.0.216
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,335 - [scylla_configure] - INFO - Setting default broadcast_rpc_address=10.99.0.216
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Setting default broadcast_rpc_address=10.99.0.216
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,335 - [scylla_configure] - INFO - Setting default endpoint_snitch=org.apache.cassandra.locator.Ec2Snitch
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Setting default endpoint_snitch=org.apache.cassandra.locator.Ec2Snitch
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,335 - [scylla_configure] - INFO - Setting default rpc_address=0.0.0.0
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Setting default rpc_address=0.0.0.0
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,335 - [scylla_configure] - INFO - Setting default seed_provider=[{'class_name': 'org.apache.cassandra.locator.SimpleSeedProvider', 'parameters': [{'
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Setting default seed_provider=[{'class_name': 'org.apache.cassandra.locator.SimpleSeedProvider', 'parameters': [{'seeds': '10.99.0.216'}]}]
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,336 - [scylla_configure] - INFO - Saving /etc/scylla/scylla.yaml
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: Saving /etc/scylla/scylla.yaml
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: 2020-10-22 09:25:56,413 - [scylla_create_devices] - INFO - RAID Array containing ['nvme1n1', 'nvme2n1'] not found. Creating...
Oct 22 09:25:56 ip-10-99-0-216.ec2.internal scylla_image_setup[1008]: RAID Array containing ['nvme1n1', 'nvme2n1'] not found. Creating...
Oct 22 09:25:58 ip-10-99-0-216.ec2.internal sshd[1222]: Accepted publickey for centos from 185.32.178.247 port 23937 ssh2: RSA SHA256:f6vyz9U2s79nX6FRr1CkUlTBQ13PmTXLJMWF2qa6sxg
```

**Comment by slivne** [comment]
after waiting a bit the instance is up 

```
Last login: Thu Oct 22 09:25:59 2020 from 185.32.178.247

   _____            _ _       _____  ____  
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        


Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at: 
	http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

    ScyllaDB is active.

$ nodetool status

Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  10.99.0.216  462.55 KB  256          ?       a1166a19-fe98-4ef2-974e-160159a25cbb  1f

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
This EC2 instance is optimized for Scylla.
    
[centos@ip-10-99-0-216 ~]$ 

```

**Comment by slivne** [comment]
4.1 seems to be based on machine image 


```
-bash: greo: command not found
[centos@ip-10-99-0-216 ~]$ sudo rpm -qa | grep scylla
scylla-conf-4.1.8-0.20201002.6c43a0dc29.x86_64
scylla-tools-core-4.1.8-20201002.4e7c17c075.noarch
scylla-machine-image-4.1.8-20201002.e05e8cf72d.noarch
scylla-server-4.1.8-0.20201002.6c43a0dc29.x86_64
scylla-kernel-conf-4.1.8-0.20201002.6c43a0dc29.x86_64
scylla-tools-4.1.8-20201002.4e7c17c075.noarch
scylla-4.1.8-0.20201002.6c43a0dc29.x86_64
scylla-debuginfo-4.1.8-0.20201002.6c43a0dc29.x86_64
scylla-python3-3.7.7-0.20201002.6c43a0dc29.x86_64
scylla-jmx-4.1.8-20201002.398e4bd1db.noarch
```

and

```
sudo systemctl | grep scylla
  var-lib-scylla.mount                                                    loaded active mounted   /var/lib/scylla
  var-lib-systemd-coredump.mount                                          loaded active mounted   Save coredump to scylla data directory
  scylla-image-setup.service                                              loaded active exited    Scylla Cloud Image Setup service
  scylla-jmx.service                                                      loaded active running   Scylla JMX
  scylla-server.service                                                   loaded active running   Scylla Server
  scylla-helper.slice                                                     loaded active active    Slice used to run companion programs to Scylla. Memory, CPU and IO restricted
  scylla-server.slice                                                     loaded active active    Slice used to run Scylla. Maximum priority for IO and CPU
  scylla.slice                                                            loaded active active    scylla.slice
  scylla-fstrim.timer                                                     loaded active waiting   Run Scylla fstrim daily
  scylla-housekeeping-daily.timer                                         loaded active waiting   Run Scylla Housekeeping daily mode
  scylla-housekeeping-restart.timer                                       loaded active elapsed   Run Scylla Housekeeping restart mode
```

**Comment by slivne** [comment]
so it seems we may have a check early on incorrect

**Comment by slivne** [comment]
```
[centos@ip-10-99-0-216 ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         31G     0   31G   0% /dev
tmpfs            32G     0   32G   0% /dev/shm
tmpfs            32G   17M   32G   1% /run
tmpfs            32G     0   32G   0% /sys/fs/cgroup
/dev/nvme0n1p1   10G  5.9G  4.2G  59% /
/dev/md0        4.6T  549M  4.6T   1% /var/lib/scylla
tmpfs           6.3G     0  6.3G   0% /run/user/1000
```

@syuu1228 / @fruch / @bentsi are we missing a backport ?

**Comment by fruch** [comment]
yes we found this during 4.2 testing, and seem like we didn't backported it
```
commit 6e53476ce36822b2406c6bd87bd0cf49811dc149
Author: Amos Kong <amos@scylladb.com>
Date:   Tue Jun 2 18:38:24 2020 +0800

    aws/scylla_login: update rest scylla-ami-setup to new name
    
    We had rename the scylla-ami-setup to scylla-image-setup.
    But the old name is still used in aws scylla_login script.
    
    Error:
    Traceback (most recent call last):
      File "/opt/scylladb/scylla-machine-image/libexec/scylla_login", line 115, in <module>
        setup = systemd_unit('scylla-ami-setup.service')
      File "/opt/scylladb/scripts/scylla_util.py", line 619, in __init__
        raise SystemdException('unit {} not found'.format(unit))
    scylla_util.SystemdException: unit scylla-ami-setup.service not found
    
    Signed-off-by: Amos Kong <amos@scylladb.com>
```

**Comment by fruch** [comment]
backport to `next-4.1` branch
