### ISSUE TITLE
scyllatop fail with "locale.Error: unsupported locale setting" on docker image

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#7487]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20201015.8068272b466
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI):  centos docker

```
Traceback (most recent call last):
  File "/opt/scylladb/scyllatop/libexec/scyllatop.py", line 14, in <module>
    import views.simple
  File "/opt/scylladb/scyllatop/views/simple.py", line 1, in <module>
    from . import base
  File "/opt/scylladb/scyllatop/views/base.py", line 2, in <module>
    import urwid
  File "/opt/scylladb/python3/lib64/python3.8/site-packages/urwid/__init__.py", line 25, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/opt/scylladb/python3/lib64/python3.8/site-packages/urwid/widget.py", line 26, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/opt/scylladb/python3/lib64/python3.8/site-packages/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/opt/scylladb/python3/lib64/python3.8/site-packages/urwid/util.py", line 58, in detect_encoding
    locale.setlocale(locale.LC_ALL, initial[0])
  File "/opt/scylladb/python3/lib64/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

seems like #7414 is hardcoding LC_ALL to something that doesn't match the docker locale

**Comment by fruch** [comment]
We have `urwid==2.1.0` installed coming from fedora, installing manually `urwid==2.1.2` into the relocatable python fixed the issue.

see:
https://github.com/urwid/urwid/issues/437

how can we get an update version with fix, into the fedora upstream ?

**Comment by fruch** [comment]
seem like the new version on it's way
https://bugzilla.redhat.com/show_bug.cgi?id=1860724

**Comment by avikivity** [comment]
It's now in updates-testing, should hit updates in a week.

**Comment by fruch** [comment]
@avikivity can we reconsider using specific packages from pypi for our relocatable python, instead of depending on the distribution (i.e. fedora) ? so we wouldn't get "gifts" like that every time we build ?

**Comment by avikivity** [comment]
no

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
