### ISSUE TITLE
scyllatop: using `metricPattern` fails with "dictionary changed size during iteration"

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#7488]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20201015.8068272b466
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos docker

when using `metricPattern`
```
[root@62edafbd9aed urwid-2.1.2]# scyllatop *cpu*nice*
scyllatop failed connecting to Scylla With an error: dictionary changed size during iteration
```

from my experience, it when trying to change a dict while iterating on it, it changed on python3
and one should iterated over the keys, or a copy of the dict.

```
Traceback (most recent call last):
  File "/opt/scylladb/scyllatop/libexec/scyllatop.py", line 123, in <module>
    fancyUserInterface(arguments.metricPattern, arguments.interval, metric_source, arguments.ttl)
  File "/opt/scylladb/scyllatop/libexec/scyllatop.py", line 37, in fancyUserInterface
    liveData = livedata.LiveData(metricPatterns, interval, metric_source, ttl)
  File "/opt/scylladb/scyllatop/livedata.py", line 23, in __init__
    self._results = self._discoverMetrics()
  File "/opt/scylladb/scyllatop/livedata.py", line 42, in _discoverMetrics
    for symbol in results:
RuntimeError: dictionary changed size during iteration
```

**Comment by avikivity** [comment]
Backported to 4.1, 4.2, 4.3.
