### ISSUE TITLE
Storage proxy exception due count queries 

### ISSUE THREAD

**Issue by MikeGoltsov** [scylladb/scylla#7566]
*Installation details*
Scylla version (or git commit hash): 4.2.0 
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos 7 with  5.9.2-1.el7.elrepo.x86_64 kernel

Due some analytic queries with counting large amount of keys I see in logs  **Attempted to append cell#1 to row already having 30 cells** exception. What does it mean?

```[shard 81] storage_proxy - Exception when communicating with 10.3.0.103, to read from dbsvc.publication: seastar::internal::backtraced<std::runtime_error> (Attempted to append cell#1 to row already having 30 cells 
Backtrace:    0x334961d
                                                 0x3349930
                                                 0x3349db9
                                                 0x2219333
                                                 0x2e5aa8f
                                                 0x2e5a88e
                                                 0x108c5ab
                                                 0x110d454
                                                 0x11144a3
                                                 0x1016a4b
                                                 0x11b32a0
                                                 0x197de15
                                                 0x2e8fab7
                                                 0x2e8fe2e
                                                 0x2ec6f0d
                                                 0x2ed690a
                                                 0x2e5ab8d
                                                 /opt/scylladb/libreloc/libpthread.so.0+0x9431
                                                 /opt/scylladb/libreloc/libc.so.6+0x101912
                                                 --------
                                                 seastar::continuation<seastar::internal::promise_base_with_type<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >, service::storage_proxy::query_result_local(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<query::read_command>, nonwrapping_interval<dht::ring_position> const&, query::result_options, tracing::trace_state_ptr, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, unsigned long)::{lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}, seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature> >::then_impl_nrvo<{lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}, service::storage_proxy::query_result_local(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<query::read_command>, nonwrapping_interval<dht::ring_position> const&, query::result_options, tracing::trace_state_ptr, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, unsigned long)::{lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> > >({lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&, {lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}&, seastar::future_state<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature> >&&)#1}, seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature> >
                                                 --------
                                                 seastar::continuation<seastar::internal::promise_base_with_type<>, service::abstract_read_executor::make_data_requests(seastar::shared_ptr<service::digest_read_resolver>, __gnu_cxx::__normal_iterator<gms::inet_address*, std::vector<gms::inet_address, std::allocator<gms::inet_address> > >, __gnu_cxx::__normal_iterator<gms::inet_address*, std::vector<gms::inet_address, std::allocator<gms::inet_address> > >, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, bool)::{lambda(gms::inet_address)#1}::operator()(gms::inet_address) const::{lambda(seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >)#1}, seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature>::then_wrapped_nrvo<void, seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> > >(seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<>&, seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&, seastar::future_state<cache_temperature>&&)#1}, cache_temperature>
                                                 --------
                                                 seastar::parallel_for_each_state
                                                 --------
                                                 seastar::internal::when_all_state_component<seastar::future<> >
                                                 --------
                                                 N7seastar12continuationINS_8internal22promise_base_with_typeIJEEEZNS_6futureIJSt5tupleIJEEEE14discard_resultEvEUlDpOT_E_ZZNS7_14then_impl_nrvoISB_NS4_IJEEEEET0_OT_ENKUlvE_clEvEUlRS3_RSB_ONS_12future_stateIJS6_EEEE_JS6_EEE
                                                 --------
                                                 seastar::continuation<seastar::internal::promise_base_with_type<>, seastar::future<>::handle_exception<service::abstract_read_executor::make_requests(seastar::shared_ptr<service::digest_read_resolver>, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#3}>(service::abstract_read_executor::make_requests(seastar::shared_ptr<service::digest_read_resolver>, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#3}&&)::{lambda(auto:1&&)#1}, seastar::future<>::then_wrapped_nrvo<seastar::future<>, service::abstract_read_executor::make_requests(seastar::shared_ptr<service::digest_read_resolver>, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#3}>(service::abstract_read_executor::make_requests(seastar::shared_ptr<service::digest_read_resolver>, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#3}&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<>&, service::abstract_read_executor::make_requests(seastar::shared_ptr<service::digest_read_resolver>, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(auto:1&&)#3}&, seastar::future_state<>&&)#1}>
                                                 --------
                                                 seastar::continuation<seastar::internal::promise_base_with_type<>, seastar::future<>::finally_body<service::abstract_read_executor::execute(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, false>, seastar::future<>::then_wrapped_nrvo<seastar::future<>, service::abstract_read_executor::execute(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(service::abstract_read_executor::execute(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<>&, service::abstract_read_executor::execute(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&, seastar::future_state<>&&)#1}>
                                              )```

**Comment by gleb-cloudius** [comment]
Looks like data corruption. @denesb demoted it from an assert to an error in 3164456108618659320ddd65969553f0cceada08.

**Comment by bhalevy** [comment]
@MikeGoltsov can you please provide the exact scylla version and build-id (from the system log)?

**Comment by MikeGoltsov** [comment]
> @MikeGoltsov can you please provide the exact scylla version and build-id (from the system log)?

 Scylla version 4.2.0-0.20201025.94597e38e2 with build-id 9057ccfab8fb951c06b8feaf25ac05ac7e60765e

**Comment by bhalevy** [comment]
Decoded backtrace:
```
seastar::current_backtrace_tasklocal() at backtrace.cc:?
 (inlined by) seastar::current_backtrace_tasklocal() at /jenkins/workspace/scylla-4.2/build/scylla/seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at backtrace.cc:?
seastar::current_backtrace() at backtrace.cc:?
seastar::internal::backtraced<std::runtime_error>::backtraced<seastar::internal::backtraced<std::runtime_error>&>(seastar::internal::backtraced<std::runtime_error>&) at /usr/include/c++/10/bits/stl_vector.h:1759
std::__exception_ptr::exception_ptr std::make_exception_ptr<seastar::internal::backtraced<std::runtime_error> >(seastar::internal::backtraced<std::runtime_error>) at /usr/include/c++/10/bits/exception_ptr.h:195
 (inlined by) std::__exception_ptr::exception_ptr seastar::make_backtraced_exception_ptr<std::runtime_error, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) at /jenkins/workspace/scylla-4.2/build/scylla/seastar/include/seastar/util/backtrace.hh:211
 (inlined by) void seastar::throw_with_backtrace<std::runtime_error, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) at /jenkins/workspace/scylla-4.2/build/scylla/seastar/include/seastar/util/backtrace.hh:227
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at /jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/on_internal_error.cc:41
row::append_cell(unsigned int, atomic_cell_or_collection) at /usr/include/fmt/format.h:2188
partition_builder::accept_row_cell(unsigned int, atomic_cell&&) at /jenkins/workspace/scylla-4.2/build/scylla/partition_builder.hh:78
 (inlined by) void mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const::cell_visitor::accept_atomic_cell(unsigned int, atomic_cell) const at /jenkins/workspace/scylla-4.2/build/scylla/mutation_partition_view.cc:242
 (inlined by) operator() at /jenkins/workspace/scylla-4.2/build/scylla/mutation_partition_view.cc:162
 (inlined by) internal_visit<boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type>&> at /usr/include/boost/variant/variant.hpp:1058
 (inlined by) visitation_impl_invoke_impl<boost::detail::variant::invoke_visitor<const (anonymous namespace)::read_and_visit_row<mutation_partition_view::do_accept<partition_builder>::cell_visitor>::atomic_cell_or_collection_visitor, false>, void*, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type> > at /usr/include/boost/variant/detail/visitation_impl.hpp:112
 (inlined by) visitation_impl_invoke<boost::detail::variant::invoke_visitor<const (anonymous namespace)::read_and_visit_row<mutation_partition_view::do_accept<partition_builder>::cell_visitor>::atomic_cell_or_collection_visitor, false>, void*, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type>, boost::variant<boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type>, ser::collection_cell_view, ser::unknown_variant_type>::has_fallback_type_> at /usr/include/boost/variant/detail/visitation_impl.hpp:154
 (inlined by) visitation_impl<mpl_::int_<0>, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<3>, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type>, boost::mpl::l_item<mpl_::long_<2>, ser::collection_cell_view, boost::mpl::l_item<mpl_::long_<1>, ser::unknown_variant_type, boost::mpl::l_end> > > >, boost::mpl::l_iter<boost::mpl::l_end> >, boost::detail::variant::invoke_visitor<const (anonymous namespace)::read_and_visit_row<mutation_partition_view::do_accept<partition_builder>::cell_visitor>::atomic_cell_or_collection_visitor, false>, void*, boost::variant<boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type>, ser::collection_cell_view, ser::unknown_variant_type>::has_fallback_type_> at /usr/include/boost/variant/detail/visitation_impl.hpp:238
 (inlined by) internal_apply_visitor_impl<boost::detail::variant::invoke_visitor<const (anonymous namespace)::read_and_visit_row<mutation_partition_view::do_accept<partition_builder>::cell_visitor>::atomic_cell_or_collection_visitor, false>, void*> at /usr/include/boost/variant/variant.hpp:2452
 (inlined by) internal_apply_visitor<boost::detail::variant::invoke_visitor<const (anonymous namespace)::read_and_visit_row<mutation_partition_view::do_accept<partition_builder>::cell_visitor>::atomic_cell_or_collection_visitor, false> > at /usr/include/boost/variant/variant.hpp:2466
 (inlined by) apply_visitor<const (anonymous namespace)::read_and_visit_row<mutation_partition_view::do_accept<partition_builder>::cell_visitor>::atomic_cell_or_collection_visitor> at /usr/include/boost/variant/variant.hpp:2518
 (inlined by) apply_visitor<(anonymous namespace)::read_and_visit_row<mutation_partition_view::do_accept<partition_builder>::cell_visitor>::atomic_cell_or_collection_visitor, boost::variant<boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type>, ser::collection_cell_view, ser::unknown_variant_type>&> at /usr/include/boost/variant/detail/apply_visitor_unary.hpp:97
 (inlined by) read_and_visit_row<mutation_partition_view::do_accept<partition_builder>::cell_visitor> at /jenkins/workspace/scylla-4.2/build/scylla/mutation_partition_view.cc:182
void mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const at /jenkins/workspace/scylla-4.2/build/scylla/mutation_partition_view.cc:248
frozen_mutation::unfreeze(seastar::lw_shared_ptr<schema const>) const at /usr/include/boost/intrusive/bstree_algorithms.hpp:1565
to_data_query_result(reconcilable_result const&, seastar::lw_shared_ptr<schema const>, query::partition_slice const&, unsigned int, unsigned int, query::result_options) at /jenkins/workspace/scylla-4.2/build/scylla/mutation_query.cc:67
seastar::continuation<seastar::internal::promise_base_with_type<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >, service::storage_proxy::query_result_local(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<query::read_command>, nonwrapping_interval<dht::ring_position> const&, query::result_options, tracing::trace_state_ptr, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, unsigned long)::{lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}, service::storage_proxy::query_result_local(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<query::read_command>, nonwrapping_interval<dht::ring_position> const&, query::result_options, tracing::trace_state_ptr, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, unsigned long)::{lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> > seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature> >::then_impl_nrvo<{lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}, service::storage_proxy::query_result_local(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<query::read_command>, nonwrapping_interval<dht::ring_position> const&, query::result_options, tracing::trace_state_ptr, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, unsigned long)::{lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> > >({lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&, {lambda(seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature>&&)#2}&, seastar::future_state<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature> >&&)#1}, seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<reconcilable_result> >, cache_temperature> >::run_and_dispose() at /usr/include/fmt/format.h:1316
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:2188
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:2188
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:2188
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:2715
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/fmt/format.h:2188
std::function<void ()>::operator()() const at /usr/include/c++/10/bits/basic_string.h:323
 (inlined by) seastar::posix_thread::start_routine(void*) at /jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/posix.cc:60
```

**Comment by denesb** [comment]
@MikeGoltsov the fastest way to get to the bottom of this would be to get a coredump. Scylla can be instructed to generate a coredump when this error happens (will result in a crash), by starting the node with `--abort-on-internal-error=1`.

**Comment by MikeGoltsov** [comment]
@denesb 
Coredump has 22G zipped size. How I can send it to you? upload.scylladb.com has a http limit 6G I think?

**Comment by slivne** [comment]
@MikeGoltsov split the file into parts using `split` and upload them to the same directory.

**Comment by MikeGoltsov** [comment]
@denesb  @slivne  uuid dfe9e7de-1846-4432-b84f-6e56ea861061

**Comment by bhalevy** [comment]
@denesb were you able to download and open the core dump?

**Comment by denesb** [comment]
I'm getting:
```
Cannot access memory at address 0x7ffff7ffe048
Cannot access memory at address 0x7ffff7ffe040
Failed to read a valid object file image from memory.
--Type <RET> for more, q to quit, c to continue without paging--
Core was generated by `/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ffff65be9e5 in ?? ()
[Current thread is 1 (LWP 350597)]
(gdb) bt
#0  0x00007ffff65be9e5 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffefdd57a0
(gdb) 
```

Just to check if I botched up the decrompression, this is the size and md5sum on the decompressed coredump:
```
$ du -sh *
67G     coredump
4.1G    coredump.gz00
4.1G    coredump.gz01
4.1G    coredump.gz02
4.1G    coredump.gz03
4.1G    coredump.gz04
1.5G    coredump.gz05

$ md5sum ./coredump
0ba495e922f405d933af44086f6a5621  ./coredump
```
Does this match what you uploaded @MikeGoltsov?

**Comment by slivne** [comment]
Benny the file was split it was to big - you need to merge the file and
then load it

**Comment by denesb** [comment]
@slivne I did merge the parts and unzipped the resulting archive, but the resulting coredump is not ok according to gdb.

**Comment by MikeGoltsov** [comment]
@denesb yes, it matched, md5 correct

**Comment by avikivity** [comment]
> I'm getting:
> 
> ```
> Cannot access memory at address 0x7ffff7ffe048
> Cannot access memory at address 0x7ffff7ffe040
> Failed to read a valid object file image from memory.
> --Type <RET> for more, q to quit, c to continue without paging--
> Core was generated by `/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --'.
> Program terminated with signal SIGABRT, Aborted.
> #0  0x00007ffff65be9e5 in ?? ()
> [Current thread is 1 (LWP 350597)]
> (gdb) bt
> #0  0x00007ffff65be9e5 in ?? ()
> Backtrace stopped: Cannot access memory at address 0x7fffefdd57a0

This looks like a shared library, did you open the core in the same toolchain image?

**Comment by denesb** [comment]
I opened it in the toolchain image of the scylla version the coredump was generated with. I can't can't even check shared libraries:
```
(gdb) info sharedlibrary
Cannot access memory at address 0x7ffff7ffe048
Cannot access memory at address 0x7ffff7ffe040
No shared libraries loaded at this time.
```

**Comment by denesb** [comment]
The core is possibly truncated.

**Comment by MikeGoltsov** [comment]
Unfortunately we copy data to new table with truncating old, and now this exception does not appear.

**Comment by bhalevy** [comment]
FWIW, I'm hitting a similar assert when reading in the presence of sstables with out-of-order clustering rows (and out-of-order partitions) with #7552 reproducer.

@MikeGoltsov and chance your cluster had in the past nodes with different number of shards and you ran repair on it?
If so, what version did you run?

**Comment by creker** [comment]
@bhalevy 

> chance your cluster had in the past nodes with different number of shards and you ran repair on it

It did. We migrated whole cluster to different hardware with different number of cores. I don't remember which version we ran at the time.

**Comment by bhalevy** [comment]
> @bhalevy
> 
> > chance your cluster had in the past nodes with different number of shards and you ran repair on it
> 
> It did. We migrated whole cluster to different hardware with different number of cores. I don't remember which version we ran at the time.

Thanks @creker, this can definitely explain the root cause for what you've seen as #7552.

The gist of it is that row-level repair initially had an issue when running on nodes with different number of shards due to repair rpc messages going out of order. This in turn, created SSTables with out-of-order partitions in the data and index files and, more rarely, with out-of-order rows/range-tombstones within the partition.  Queries that stumbled upon those mis-ordered index files may have hit several asserts / checks in the code, like the one you guys reported.
