### ISSUE TITLE
output_stream destructor assertion failure while running cassandra-stress

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#757]
while trying to reproduce #735 

version 0.14.1

running on i2.xlarge with attached drive

loader on c3.xlarge (version 0.1.4.1 - shutdown of scylla)

provision
```
cassandra-stress write no-warmup cl=ONE n=2000000 -mode native cql3 -rate threads=10 -node $SERVERS -pop seq=1..2000000 -col 'size=FIXED(2048) n=FIXED(5)'

```

stress
```
cassandra-stress mixed no-warmup cl=ONE duration=1000h -mode native cql3 -rate threads=1 -node 10.149.117.233 -pop seq=1..2000000 -col 'size=FIXED(2048) n=FIXED(5)'
```

journalctl

```
Jan 06 05:24:53 ip-10-149-117-233 scylla[1370]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1265-Data.db:leve
Jan 06 05:25:53 ip-10-149-117-233 scylla[1370]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1247-Data.db:level=0, /var/lib
Jan 06 05:26:08 ip-10-149-117-233 scylla[1370]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1267-Data.db:leve
Jan 06 05:26:13 ip-10-149-117-233 scylla[1370]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1248-Data.db:level=0, /var/lib
Jan 06 05:26:29 ip-10-149-117-233 scylla[1370]:  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1268-Data.db:leve
Jan 06 05:34:10 ip-10-149-117-233 scylla[1370]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1270-Data.db:level=0, /var/lib
Jan 06 05:34:25 ip-10-149-117-233 scylla[1370]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1286-Data.db:leve
Jan 06 05:35:25 ip-10-149-117-233 scylla[1370]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1269-Data.db:level=0, /var/lib
Jan 06 05:35:40 ip-10-149-117-233 scylla[1370]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1285-Data.db:leve
Jan 06 05:36:43 ip-10-149-117-233 scylla[1370]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1271-Data.db:level=0, /var/lib
Jan 06 05:36:59 ip-10-149-117-233 scylla[1370]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1272-Data.db:level=0, /var/lib
Jan 06 05:36:59 ip-10-149-117-233 scylla[1370]:  [shard 3] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1287-Data.db:leve
Jan 06 05:37:14 ip-10-149-117-233 scylla[1370]:  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1288-Data.db:leve
Jan 06 05:44:57 ip-10-149-117-233 scylla[1370]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1290-Data.db:level=0, /var/lib
Jan 06 05:45:13 ip-10-149-117-233 scylla[1370]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-28a09be0b3f211e5bec2000000000001/keyspace1-standard1-ka-1306-Data.db:leve
Jan 06 05:45:55 ip-10-149-117-233 scylla_run[1362]: Failed with  {"message": "Not found", "code": 404}
Jan 06 05:45:55 ip-10-149-117-233 audit[1374]: <audit-1701> auid=4294967295 uid=995 gid=1001 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 pid=1374 comm="scylla" exe="/usr/bin/scylla" sig=6
Jan 06 05:45:55 ip-10-149-117-233 scylla_run[1362]: scylla: /builddir/build/BUILD/scylla-server-0.14.1/seastar/core/iostream.hh:200: output_stream<CharType>::~output_stream() [with CharType = char]: Assertion `!
Jan 06 06:01:01 ip-10-149-117-233 CROND[7744]: (root) CMD (run-parts /etc/cron.hourly)
```

there is a core in /var/lib/scylla/coredump

based on the name its the same process

core.scylla-2016-01-06-05:45:55-1370

```
Type "apropos word" to search for commands related to "word"...
[New LWP 1374]
[New LWP 1378]
[New LWP 1377]
[New LWP 1372]
[New LWP 1376]
[New LWP 1373]
[New LWP 1371]
[New LWP 1375]
[New LWP 1370]
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...done.
done.

warning: Ignoring non-absolute filename: <linux-vdso.so.1>
Missing separate debuginfo for linux-vdso.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/a8/88257ccc787e9bfe920798db376ed7e8d5beeb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f18a6be49c8 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install boost-filesystem-1.57.0-6.fc22.x86_64 boost-program-options-1.57.0-6.fc22.x86_64 boost-system-1.57.0-6.fc22.x86_64 boost-test-1.57.0-6.fc22.x86_64 boost-thread-1.57.0-6.fc22.x86_64 cryptopp-5.6.2-9.fc22.x86_64 glibc-2.21-8.fc22.x86_64 gmp-6.0.0-9.fc22.x86_64 gnutls-3.3.19-1.fc22.x86_64 gnutls-c++-3.3.19-1.fc22.x86_64 hwloc-libs-1.11.0-4.fc22.x86_64 jsoncpp-0.6.0-0.14.rc2.fc22.x86_64 keyutils-libs-1.5.9-4.fc22.x86_64 krb5-libs-1.13.2-10.fc22.x86_64 libaio-0.3.110-4.fc22.x86_64 libcom_err-1.42.12-4.fc22.x86_64 libffi-3.1-7.fc22.x86_64 libgcc-5.3.1-2.fc22.x86_64 libpciaccess-0.13.3-0.3.fc22.x86_64 libselinux-2.3-10.fc22.x86_64 libstdc++-5.3.1-2.fc22.x86_64 libtasn1-4.5-1.fc22.x86_64 libtool-ltdl-2.4.2-35.fc22.x86_64 libxml2-2.9.3-1.fc22.x86_64 lz4-r131-1.fc22.x86_64 nettle-2.7.1-5.fc22.x86_64 numactl-libs-2.0.10-2.fc22.x86_64 openssl-libs-1.0.1k-13.fc22.x86_64 p11-kit-0.23.1-2.fc22.x86_64 pcre-8.38-1.fc22.x86_64 snappy-1.1.1-3.fc22.x86_64 thrift-0.9.1-13.fc22.3.x86_64 trousers-0.3.13-3.fc22.x86_64 xz-libs-5.2.0-2.fc22.x86_64 yaml-cpp-0.5.1-6.fc22.x86_64 zlib-1.2.8-7.fc22.x86_64
(gdb) where
#0  0x00007f18a6be49c8 in raise () from /lib64/libc.so.6
#1  0x00007f18a6be665a in abort () from /lib64/libc.so.6
#2  0x00007f18a6bdd187 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f18a6bdd232 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000006c3b86 in ~output_stream (this=0x603000c09a48, __in_chrg=<optimized out>) at /usr/src/debug/scylla-server-0.14.1/seastar/core/iostream.hh:200
#5  ~connection (this=0x603000c09a00, __in_chrg=<optimized out>) at /usr/src/debug/scylla-server-0.14.1/seastar/http/httpd.hh:151
#6  operator()<future<> > (f=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x1637d5a, DIE 0x1a4db2d>, __closure=0x603000b2e0f0) at /usr/src/debug/scylla-server-0.14.1/seastar/http/httpd.hh:114
#7  _Z22do_void_futurize_applyIZZN5httpd11http_server10do_acceptsEiENUl6futureIJ16connected_socket14socket_addressEEE_clES5_EUlOT_E_JS2_IJEEEENSt9enable_ifIXntsr9is_futureIJNSt9result_ofIFS7_DpOT0_EE4typeEEE5valueESA_E4typeES8_SG_ (func=func@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x1637d5a, DIE 0x1a4dc7f>) at /usr/src/debug/scylla-server-0.14.1/seastar/core/future.hh:1138
#8  0x00000000006c90c6 in apply<httpd::http_server::do_accepts(int)::<lambda(future<connected_socket, socket_address>)> mutable::<lambda(auto:34&&)>, future<> > (func=<optimized out>)
    at /usr/src/debug/scylla-server-0.14.1/seastar/core/future.hh:1186
#9  operator()<future_state<> > (state=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x1637d5a, DIE 0x1a62733>, __closure=0x603000b2e0d0)
    at /usr/src/debug/scylla-server-0.14.1/seastar/core/future.hh:881
#10 _ZN12continuationIZN6futureIJEE12then_wrappedIZZN5httpd11http_server10do_acceptsEiENUlS0_IJ16connected_socket14socket_addressEEE_clES7_EUlOT_E_S1_EET0_SA_EUlSA_E_JEE3runEv (this=0x603000b2e0c0)
    at /usr/src/debug/scylla-server-0.14.1/seastar/core/future.hh:399
#11 0x00000000004771cd in reactor::run_tasks (this=this@entry=0x6030000c3000, tasks=...) at core/reactor.cc:1318
#12 0x00000000004a15fb in reactor::run (this=0x6030000c3000) at core/reactor.cc:1622
#13 0x00000000004c18ff in smp::<lambda()>::operator()(void) const (__closure=0x6000000cf680) at core/reactor.cc:2377
#14 0x0000000000473f9e in operator() (this=<optimized out>) at /usr/include/c++/5.3.1/functional:2271
#15 dpdk_thread_adaptor (f=<optimized out>) at core/reactor.cc:2207
#16 0x000000000067733b in eal_thread_loop ()
#17 0x00007f18a6f77555 in start_thread () from /lib64/libpthread.so.0
#18 0x00007f18a6cb2b9d in clone () from /lib64/libc.so.6
```

@avikivity  I provided you access to the machine i-05f19084

**Comment by avikivity** [comment]
Cause was httpd not closing the connection properly.  Seastar patch posted.
