### ISSUE TITLE
offline installation: scylla_io_setup failed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7577]
*Installation details*
Scylla version (or git commit hash): scylla-unified-package-4.4.dev.0.20201110.78c598e08e.tar.gz
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS8 instance on GCE

### Description

In nonroot offline installation, the scylla_io_setup failed for `IndexError: list index out of range`

GCE Machine type:  e2-medium (2 vCPUs, 4 GB memory)

````
[scylla-test@amos-offlineinstall-centos7 ~]$ ./scylladb/sbin/scylla_setup 
node exporter setup is disabled by default, since the installation is offline mode.

Skip any of the following steps by answering 'no'
Do you want the Scylla server service to automatically start when the Scylla node boots?
Yes - Scylla server service automatically starts on Scylla node boot. No - skips this step. Note you will have to start the Scylla Server service manually.
[YES/no]
Created symlink /home/scylla-test/.config/systemd/user/multi-user.target.wants/scylla-server.service → /home/scylla-test/.config/systemd/user/scylla-server.service.
Do you want IOTune to study your disks IO profile and adapt Scylla to it? (*WARNING* Saying NO here means the node will not boot in production mode unless you configure the I/O Subsystem manually!)
Yes - let iotune study my disk(s). Note that this action will take a few minutes. No - skip this step.
[YES/no]
Traceback (most recent call last):
  File "/home/scylla-test/scylladb/scripts/libexec/scylla_io_setup", line 239, in <module>
    if idata.is_recommended_instance():
  File "/home/scylla-test/scylladb/scripts/scylla_util.py", line 299, in is_recommended_instance
    if self.is_recommended_instance_size() and not self.is_unsupported_instance_class() and self.is_supported_instance_class():
  File "/home/scylla-test/scylladb/scripts/scylla_util.py", line 267, in is_recommended_instance_size
    if int(self.instance_size()) > 1:
  File "/home/scylla-test/scylladb/scripts/scylla_util.py", line 237, in instance_size
    return self.instancetype.split("-")[2]
IndexError: list index out of range
IO configuration setup failed. Press any key to continue...

Do you want to install node exporter to export Prometheus data from the node? Note that the Scylla monitoring stack uses this data
Yes - install node exporter. No - skip this  step.
[yes/NO]
ScyllaDB setup finished.
[scylla-test@amos-offlineinstall-centos7 ~]$ echo $?
0

````

Failed to start scylla for lack of io setup:

- [shard 0] init - Startup failed: std::runtime_error (Bad I/O Scheduler configuration)

```
[scylla-test@amos-offlineinstall-centos7 ~]$ cat scylladb/etc/scylla.d/io.conf 
# DO NO EDIT
# This file should be automatically configure by scylla_io_setup
#
# SEASTAR_IO="--max-io-requests=1 --num-io-queues=1"
```

CC @penberg @roydahan

**Comment by amoskong** [comment]
Reproduce steps:

```
curl -o scylla.tar.gz http://downloads.scylladb.com.s3.amazonaws.com/relocatable/unstable/master/2020-11-10T00%3A01%3A15Z/scylla-unified-package-4.4.dev.0.20201110.78c598e08e.tar.gz
tar xvfz scylla.tar.gz
sh -x ./install.sh --nonroot
./scylladb/sbin/scylla_setup
```

**Comment by avikivity** [comment]
@tarzanek @fruch I think this is your code

**Comment by fruch** [comment]
> @tarzanek @fruch I think this is your code

I think you meant @bentsi

**Comment by fruch** [comment]
@amoskong, you have this instance still running ?

**Comment by avikivity** [comment]
> > @tarzanek @fruch I think this is your code
> 
> I think you meant @bentsi

To tell the truth, I'm not certain you're two different people

**Comment by tarzanek** [comment]
this is my bug, picking up

**Comment by tarzanek** [comment]
@bentsi can you review https://github.com/scylladb/scylla/pull/7592 ?

**Comment by amoskong** [comment]
> @amoskong, you have this instance still running ?

No, it's easy to reproduce.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
