### ISSUE TITLE
CoreDump during "nodetool toppartitions"  command 

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla#7622]
## Details 

* Test: longevity_test.LongevityTest.test_custom_time
* Build number: 139
* Backend: aws: eu-north-1
* Test-id: edcdb724-c7bb-4e67-b728-363123645c43

## System Infromation
* Scylla version: `4.4.dev-0.20201112.5b1237584 with build-id f17e3c90f234ad4ba1abfc8c9f8d8ca660584161` (`ami-0b69d2b4e4e67abd3`)
* Instance type: `i3.4xlarge`
* Number of scylladb nodes: 6

## Logs
```
2020-11-15 17:13:06.473: (DisruptionEvent Severity.ERROR): type=end name=ShowTopPartitions node=Node longevity-cdc-100gb-4h-master-db-node-edcdb724-5 [13.53.106.224 | 10.0.2.233] (seed: False) duration=45 error=Encountered a bad command exit code!
Command: 'nodetool  toppartitions cdc_test test_table 9494 -s 602 -k 8 -a writes'
Exit code: 2
Stdout:
Using /etc/scylla/scylla.yaml as the config file
Stderr:
at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
at java.security.AccessController.doPrivileged(Native Method)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2464, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2734, in disrupt
self.call_random_disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 817, in call_random_disrupt_method
self.execute_disrupt_method(disrupt_method)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 824, in execute_disrupt_method
disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1807, in disrupt_show_toppartitions
result = self.target_node.run_nodetool(sub_cmd='toppartitions', args=sub_cmd_args)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2417, in run_nodetool
result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 601, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 593, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 536, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.8/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.8/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.8/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'nodetool  toppartitions cdc_test test_table 9494 -s 602 -k 8 -a writes'
Exit code: 2
Stdout:
Using /etc/scylla/scylla.yaml as the config file
Stderr:
at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
at java.security.AccessController.doPrivileged(Native Method)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

```

## CoreDump Information
[URL](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.995.70954fb0108c423099bc2d946281cffb.48696.1605461256000000/core.scylla.995.70954fb0108c423099bc2d946281cffb.48696.1605461256000000.gz)
```
2020-11-15 17:43:24.053: (CoreDumpEvent Severity.ERROR)node=Node longevity-cdc-100gb-4h-master-db-node-edcdb724-5 [13.53.106.224 | 10.0.2.233] (seed: False)
corefile_url=https://storage.cloud.google.com/upload.scylladb.com/core.scylla.995.70954fb0108c423099bc2d946281cffb.48696.1605461256000000/core.scylla.995.70954fb0108c423099bc2d946281cffb.48696.1605461256000000.gz
backtrace=           PID: 48696 (scylla)
UID: 995 (scylla)
GID: 1001 (scylla)
Signal: 6 (ABRT)
Timestamp: Sun 2020-11-15 17:27:36 UTC (4min 27s ago)
Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --experimental-features cdc --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15 --lock-memory=1
Executable: /opt/scylladb/libexec/scylla
Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
Unit: scylla-server.service
Slice: scylla-server.slice
Boot ID: 70954fb0108c423099bc2d946281cffb
Machine ID: ec239da046efe33c7665d4508a7d0a61
Hostname: longevity-cdc-100gb-4h-master-db-node-edcdb724-5
Coredump: /var/lib/systemd/coredump/core.scylla.995.70954fb0108c423099bc2d946281cffb.48696.1605461256000000
Message: Process 48696 (scylla) of user 995 dumped core.
Stack trace of thread 48696:
#0  0x00007f82f0400bc5 raise (libc.so.6)
#1  0x00007f82f03e9954 abort (libc.so.6)
#2  0x00000000037b0bdc _ZN7seastar17on_internal_errorERNS_6loggerESt17basic_string_viewIcSt11char_traitsIcEE (scylla)
#3  0x00000000013bb2c5 _ZN12_GLOBAL__N_119on_validation_errorERN7seastar6loggerERKNS0_13basic_sstringIcjLj15ELb1EEE (scylla)
#4  0x00000000013bbec2 _ZN42mutation_fragment_stream_validating_filter16on_end_of_streamEv (scylla)
#5  0x0000000001569611 _ZN20flat_mutation_reader4impl17consume_in_threadIN8sstables14sstable_writerE42mutation_fragment_stream_validating_filterEEDaT_T0_NSt6chrono10time_pointIN7seastar12lowres_clockENS7_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
#6  0x000000000156860a _ZN7seastar20noncopyable_functionIFvvEE17direct_vtable_forIZNS_5asyncIZN8sstables7sstable16write_componentsE20flat_mutation_readermNS_13lw_shared_ptrIK6schemaEERKNS5_21sstable_writer_configE14encoding_statsRKNS_17io_priority_classEE4$_61JEEENS_8futurizeINSt9result_ofIFNSt5decayIT_E4typeEDpNSM_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSN_DpOSQ_EUlvE_E4callEPKS2_ (scylla)
#7  0x0000000003a61282 _ZN7seastar14thread_context4mainEv (scylla)
Stack trace of thread 48700:
#0  0x00000000010749d2 _ZNK25atomic_cell_or_collection21external_memory_usageERK13abstract_type (scylla)
#1  0x000000000124db6b _ZNK3row21external_memory_usageERK6schema11column_kind (scylla)
#2  0x00000000013205b2 _ZZN24frozen_mutation_fragment8unfreezeERK6schema13reader_permitENK3$_3clEN3ser19clustering_row_viewE (scylla)
#3  0x000000000131d7ab _ZNSt8__detail9__variant17__gen_vtable_implINS0_12_Multi_arrayIPFNS0_21__deduce_visit_resultI17mutation_fragmentEEON7seastar8internal15variant_visitorIJZN24frozen_mutation_fragment8unfreezeERK6schema13reader_permitE3$_3ZNS9_8unfreezeESC_SD_E3$_4ZNS9_8unfreezeESC_SD_E3$_5ZNS9_8unfreezeESC_SD_E3$_6ZNS9_8unfreezeESC_SD_E3$_7ZNS9_8unfreezeESC_SD_E3$_8EEERSt7variantIJN3ser19clustering_row_viewENSN_15static_row_viewENSN_20range_tombstone_viewENSN_20partition_start_viewE13partition_endNSN_20unknown_variant_typeEEEEJEEESt16integer_sequenceImJLm0EEEE14__visit_invokeESL_SV_ (scylla)
#4  0x000000000131bd5e _ZN24frozen_mutation_fragment8unfreezeERK6schema13reader_permit (scylla)
#5  0x0000000002a462d0 _ZNSt17_Function_handlerIFN7seastar6futureINS0_18optimized_optionalI17mutation_fragmentEEEEvEZZZN9streaming14stream_session30init_messaging_service_handlerERN4netw17messaging_serviceEENK3$_0clERKNS0_3rpc11client_infoEN5utils4UUIDESI_SI_mNSD_8optionalINS7_13stream_reasonEEENSD_6sourceIJ24frozen_mutation_fragmentNSJ_INS7_29stream_mutation_fragments_cmdEEEEEEENUlNS0_13lw_shared_ptrIK6schemaEEE_clESU_EUlvE_E9_M_invokeERKSt9_Any_data (scylla)
#6  0x00000000013df3b6 _ZN7seastar8internal14do_until_stateIZN17generating_reader11fill_bufferENSt6chrono10time_pointINS_12lowres_clockENS3_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE_ZNS2_11fill_bufferESA_EUlvE0_E15run_and_disposeEv (scylla)
#7  0x00000000037e45b5 _ZN7seastar7reactor14run_some_tasksEv (scylla)
#8  0x00000000037e5758 _ZN7seastar7reactor3runEv (scylla)
#9  0x00000000038034d5 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_95E9_M_invokeERKSt9_Any_data (scylla)
#10 0x00000000037b149b _ZN7seastar12posix_thread13start_routineEPv (scylla)
#11 0x00007f82f110f3f9 start_thread (libpthread.so.0)
#12 0x00007f82f04c4b03 __clone (libc.so.6)
Stack trace of thread 48699:
#0  0x0000000002f19976 _ZN15mutation_writer41timestamp_based_splitting_mutation_writer11examine_rowERK3row11column_kind (scylla)
#1  0x0000000002f1df10 _ZN15mutation_writer41timestamp_based_splitting_mutation_writer7consumeEO14clustering_row (scylla)
#2  0x0000000002f284e9 _ZZZZN15mutation_writer11feed_writerINS_41timestamp_based_splitting_mutation_writerEEEN7seastar6futureIvEEO20flat_mutation_readerOT_ENKUlRS5_RS1_E_clES9_SA_ENKUlvE_clEvENKUlvE0_clEv (scylla)
#3  0x0000000002f29009 _ZN7seastar8internal14do_until_stateIZZZN15mutation_writer11feed_writerINS2_41timestamp_based_splitting_
download_instructions=gsutil cp gs://upload.scylladb.com/core.scylla.995.70954fb0108c423099bc2d946281cffb.48696.1605461256000000/core.scylla.995.70954fb0108c423099bc2d946281cffb.48696.1605461256000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.995.70954fb0108c423099bc2d946281cffb.48696.1605461256000000.gz```
```

## Links
* **prometheus** - https://cloudius-jenkins-test.s3.amazonaws.com/edcdb724-c7bb-4e67-b728-363123645c43/prometheus_snapshot_20201115_204919.tar.gz
* **grafana** - https://cloudius-jenkins-test.s3.amazonaws.com/edcdb724-c7bb-4e67-b728-363123645c43/20201115_203913/grafana-screenshot-overview-20201115_203913-longevity-cdc-100gb-4h-master-monitor-node-edcdb724-1.png
* **grafana** - https://cloudius-jenkins-test.s3.amazonaws.com/edcdb724-c7bb-4e67-b728-363123645c43/20201115_203913/grafana-screenshot-scylla-per-server-metrics-nemesis-20201115_204255-longevity-cdc-100gb-4h-master-monitor-node-edcdb724-1.png
* **grafana** - https://cloudius-jenkins-test.s3.amazonaws.com/edcdb724-c7bb-4e67-b728-363123645c43/20201115_205030/grafana-screenshot-overview-20201115_205030-longevity-cdc-100gb-4h-master-monitor-node-edcdb724-1.png
* **grafana** - https://cloudius-jenkins-test.s3.amazonaws.com/edcdb724-c7bb-4e67-b728-363123645c43/20201115_205030/grafana-screenshot-scylla-per-server-metrics-nemesis-20201115_205347-longevity-cdc-100gb-4h-master-monitor-node-edcdb724-1.png
* **db-cluster** - https://cloudius-jenkins-test.s3.amazonaws.com/edcdb724-c7bb-4e67-b728-363123645c43/20201115_210020/db-cluster-edcdb724.zip
* **loader-set** - https://cloudius-jenkins-test.s3.amazonaws.com/edcdb724-c7bb-4e67-b728-363123645c43/20201115_210020/loader-set-edcdb724.zip
* **monitor-set** - https://cloudius-jenkins-test.s3.amazonaws.com/edcdb724-c7bb-4e67-b728-363123645c43/20201115_210020/monitor-set-edcdb724.zip
* **sct-runner** - https://cloudius-jenkins-test.s3.amazonaws.com/edcdb724-c7bb-4e67-b728-363123645c43/20201115_210020/sct-runner-edcdb724.zip

**Comment by slivne** [comment]
Lets check this out - after we fix https://github.com/scylladb/scylla/issues/7482

**Comment by raphaelsc** [comment]
On Mon, Nov 16, 2020 at 12:43 PM Oren Efraimov <notifications@github.com>
wrote:

>
> UID: 995 (scylla)
> GID: 1001 (scylla)
> Signal: 6 (ABRT)
> Timestamp: Sun 2020-11-15 17:27:36 UTC (4min 27s ago)
> Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500
>
>
Unrelated suggestion: I don't get why we're running longevity tests with
such a high threshold for reactor stall notifications. 500ms is half a
second, and that's an unacceptable stall. we should lower the threshold to
at least 100ms, as any stall higher than 100ms is already significant for
matters of latency and therefore should be reported.

**Comment by fgelcer** [comment]
this issue seems to be reproducing for 2021.1.20 patch release:
https://jenkins.scylladb.com/view/nexts/job/enterprise-2021.1/job/longevity/job/longevity-cdc-4h-test/116/
