### ISSUE TITLE
Recent changes in `dist/common/scripts` breaks scylla-machine-image

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#7695]
*Installation details*
Scylla version (or git commit hash): master

recently this was merged:
https://github.com/scylladb/scylla/commit/3fefa520bd5862fa0e8d678e67405bcc17387f55#diff-30654fb8378bc60288cf2cbd81c98b597b95b61dd3f8d53ac6cc60bda1ce1816

and now all the image based on scylla-machine-image are failing to boot with the following:
```
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: Traceback (most recent call last):
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 27, in <module>
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: run('/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami')
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 501, in run
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: with Popen(*popenargs, **kwargs) as process:
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 947, in __init__
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: self._execute_child(args, executable, preexec_fn, close_fds,
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 1819, in _execute_child
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: raise child_exception_type(errno_num, err_msg, err_filename)
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal scylla_image_setup[4329]: FileNotFoundError: [Errno 2] No such file or directory: '/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami'
Nov 24 23:54:41 ip-10-0-3-72.ec2.internal systemd[1]: scylla-image-setup.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by bhalevy** [comment]
Caused by 3fefa520bd5862fa0e8d678e67405bcc17387f55?

**Comment by slivne** [comment]
@penberg please help

**Comment by penberg** [comment]
@slivne @fruch Isn't this addressed by https://github.com/scylladb/scylla-machine-image/pull/84, which is merged now?

**Comment by fruch** [comment]
it's now working again:
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-test/231/
