### ISSUE TITLE
Running Scylla on docker using boot2docker results too many start retries, requires sse4.2 and clmul

### ISSUE THREAD

**Issue by lambchamps** [scylladb/scylla#7713]
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
2020-11-27 00:49:38,782 INFO spawned: 'scylla' with pid 74
Scylla requires the sse4.2 and clmul instruction sets, check your processor and hypervisor
Scylla requires a processor with SSE 4.2 and PCLMUL support
2020-11-27 00:49:38,933 INFO exited: scylla (exit status 71; not expected)
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 208, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 134, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 93, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 88, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
2020-11-27 00:49:41,273 INFO spawned: 'scylla' with pid 96
Scylla requires the sse4.2 and clmul instruction sets, check your processor and hypervisor
Scylla requires a processor with SSE 4.2 and PCLMUL support
2020-11-27 00:49:41,445 INFO exited: scylla (exit status 71; not expected)
2020-11-27 00:49:44,451 INFO spawned: 'scylla' with pid 105
Scylla requires the sse4.2 and clmul instruction sets, check your processor and hypervisor
Scylla requires a processor with SSE 4.2 and PCLMUL support
2020-11-27 00:49:44,606 INFO exited: scylla (exit status 71; not expected)
2020-11-27 00:49:45,607 INFO gave up: scylla entered FATAL state, too many start retries too quickly

**Comment by tzach** [comment]
Similar to https://github.com/scylladb/scylla/issues/6528

**Comment by slivne** [comment]
Scylla requires cpu support for sse4.2 (https://en.wikipedia.org/wiki/SSE4) and also PCLMUL (https://en.wikipedia.org/wiki/CLMUL_instruction_set) those should be avail on CPUs for many years.
