### ISSUE TITLE
c-s timed out due to 1 sec delay in IO queue

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#7725]
*Installation details*
Scylla version (or git commit hash): `4.2.1-0.20201108.4fb8ebccff with build-id d19a95fd85a8e7df2928ccd8c729941f263e8adc`
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS (Kernel version 3.10.0-1127.19.1.el7.x86_64.)

```
08:08:42  < t:2020-11-27 05:08:34,498 f:sct_events.py   l:968  c:sdcm.sct_events      p:INFO  > 2020-11-27 05:08:34.485: (CassandraStressEvent Severity.NORMAL): type=start node=Node rolling-upgrade-master-centos-loader-node-202b4c8a-0-1 [35.237.16.1 | 10.142.0.142] (seed: False)
08:08:42  < t:2020-11-27 05:08:34,498 f:sct_events.py   l:968  c:sdcm.sct_events      p:INFO  > stress_cmd=cassandra-stress user no-warmup profile=/tmp/complex_schema.yaml  ops'(insert=1)' cl=ALL n=5000000 -mode cql3 native  user=cassandra password=cassandra -rate threads=1000 -pop seq=1..5000000 -node 10.142.0.33 -errors skip-unsupported-columns
08:09:06  < t:2020-11-27 05:09:04,836 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=MLUVYWVLAWGNT2ZI71KL; cassandra-stress user no-warmup profile=/tmp/complex_schema.yaml  ops'(insert=1)' cl=ALL n=5000000 -mode cql3 native  user=cassandra password=cassandra -rate threads=1000 -pop seq=1..5000000 -node 10.142.0.33 -errors skip-unsupported-columns"; Exit status: 1
```
C-S custom schema can be found [here](https://github.com/scylladb/scylla-cluster-tests/blob/master/data_dir/complex_schema.yaml)
C-s output
```
===== Using optimized driver!!! =====
Connected to cluster: rolling-upgrade-master-centos-db-cluster-202b4c8a, max pending requests per connection 128, max connections per host 8
Datatacenter: datacenter1; Host: /10.142.0.125; Rack: rack1
Datatacenter: datacenter1; Host: /10.142.0.134; Rack: rack1
Datatacenter: datacenter1; Host: /10.142.0.55; Rack: rack1
Datatacenter: datacenter1; Host: /10.142.0.33; Rack: rack1
Created schema. Sleeping 1s for propagation.
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.142.0.55:9042] Timed out waiting for server response
  at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:43)
  at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:25)
  at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
  at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
  at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
  at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:188)
  at org.apache.cassandra.stress.StressProfile.maybeCreateSchema(StressProfile.java:261)
  at org.apache.cassandra.stress.StressProfile.newGenerator(StressProfile.java:694)
  at org.apache.cassandra.stress.StressProfile.printSettings(StressProfile.java:129)
  at org.apache.cassandra.stress.settings.StressSettings.printSettings(StressSettings.java:383)
  at org.apache.cassandra.stress.Stress.run(Stress.java:95)
  at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.142.0.55:9042] Timed out waiting for server response
  at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:979)
  at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1631)
  at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
  at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
```

![image](https://user-images.githubusercontent.com/5269241/100677678-93966380-337c-11eb-9432-fdb5c94abeb7.png)

Logs:

grafana - https://cloudius-jenkins-test.s3.amazonaws.com/202b4c8a-07a0-4a93-9bb2-0ce1306bc260/20201127_050918/grafana-screenshot-overview-20201127_050918-rolling-upgrade-master-centos-monitor-node-202b4c8a-0-1.png
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/202b4c8a-07a0-4a93-9bb2-0ce1306bc260/20201127_050918/grafana-screenshot-scylla-per-server-metrics-nemesis-20201127_051306-rolling-upgrade-master-centos-monitor-node-202b4c8a-0-1.png
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/202b4c8a-07a0-4a93-9bb2-0ce1306bc260/20201127_051838/grafana-screenshot-overview-20201127_051838-rolling-upgrade-master-centos-monitor-node-202b4c8a-0-1.png
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/202b4c8a-07a0-4a93-9bb2-0ce1306bc260/20201127_051838/grafana-screenshot-scylla-per-server-metrics-nemesis-20201127_052154-rolling-upgrade-master-centos-monitor-node-202b4c8a-0-1.png
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/202b4c8a-07a0-4a93-9bb2-0ce1306bc260/20201127_052734/db-cluster-202b4c8a.zip
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/202b4c8a-07a0-4a93-9bb2-0ce1306bc260/20201127_052734/loader-set-202b4c8a.zip
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/202b4c8a-07a0-4a93-9bb2-0ce1306bc260/20201127_052734/monitor-set-202b4c8a.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/202b4c8a-07a0-4a93-9bb2-0ce1306bc260/20201127_052734/sct-runner-202b4c8a.zip

**Comment by roydahan** [comment]
@bentsi there aren't enough details here for someone to look on it.
Please describe the test and in what part it's happening and if it reproduces.
Also, need monitor or hydra investigate command.

**Comment by avikivity** [comment]
The 1 sec delay is fake, see #8166.
