### ISSUE TITLE
storage_service::get_changed_ranges_for_leaving holds token_metadata& across yield point

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7790]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/687/artifact/logs-release.2/1607597186100_update_cluster_layout_tests.TestUpdateClusterLayout.simple_removenode_2_test/node1.log
```
INFO  2020-12-10 10:46:25,721 [shard 0] gossip - Advertising removal for 127.0.87.2
INFO  2020-12-10 10:46:25,722 [shard 0] storage_service - Removing tokens {9217659481637168743, 9041562187457403188, 8909232492270291394, 8579646722108808333, 8502031638324217220, 8165784908024748484, 7648584704263351890, 9119936369702187965, 7550485118318939782, 7529919490034505806, 7471422617081425380, 6521787978074563330, 6272676813106068828, 6003997817283685870, 5733474719872185110, 5541627985936728922, 5506794953056813156, 4767762722085426621, 7115041949038618340, 4537904338916846403, 4430646219742435218, 4424496800654872308, 4278391396871032122, 4201652815396366571, 3983108349385082842, 8320649691276872284, 4319235375861784099, 3539957824600978815, 3363418965673034694, 3189639337734815660, 2971825298905143980, 2844962970219170519, 2386280517410258417, 2311202138470918466, 7121128036190305021, 6724499728557589992, 2308073009118149135, 2307663289654204912, 1994774277533309786, 1905834822559216981, 4030510515584624467, 1812915381372839009, 1736819649863811714, 1678950225003120628, 1650861911221375702, 2793743196759079610, 1615535754254905293, 7172587275278426313, 1511907860041499618, 1450426081718572888, 5658133227029809534, 1431252160430310475, 1374593146282514174, 1371856161249998520, 3636699750021418028, 1161728372289657341, 1150096766800346751, 1135994801344779981, 7790766257496748329, 3509577958183195848, 1041422813462191354, 3592669638425889094, 947557606633743599, 9069611865558498191, 5088639673529308306, 2920230103710843711, 876572198200522051, 845512740231850451, 8619610155046264943, 5944043927550657245, 2388368684573376928, 570323616113298726, 7505706965743066487, 178006997612856050, 173833571002249196, -74932671033486259, -238516862327928372, -275282540388139583, 5271895669059588129, -439079160279908809, 739343418819680661, -491425486707688500, 1410887001313164049, -565598782253573912, 6633366857423160340, -700201293135254516, -839295357049682100, 5760542687468628016, -954858332926448125, -1082976650874947649, 5376010901993328065, -1530910412940844187, 1517394302789161950, -1573040280842912540, 4021094836355382264, -1730923217066879184, 3242262633738553732, -2012241777781261848, 1762837111778607474, -2194813021317047673, -2196734615460011980, 4345402900813234593, 956839148689690516, -106263815726985054, -2238610908656090546, -2413304119794590705, -2626578387763844196, -2729960107557821122, 6579597805502665954, -2775125987045499467, -3009398254597926207, -648670570199571019, -3075517867241940112, 5513405949449259333, -3190951681703960452, 8725451518779237579, -3207090212034260596, -3219723879890016364, -1026947756310121026, -3309212195177420974, 1801873829550512864, -3361377824474583886, -3378333590397324504, 4333313291459777722, -3047664511484774722, -3463849210236465076, -3706989561582589031, -3711034668598627776, 3136693549440533319, 1341949397772046877, -3182013439070446921, -3798348871607284362, -2368660052852001824, -4211781610805817099, 2538838457823118816, -4219565909103330221, 3923773246875116608, -2092626757042827646, -4224935768346400089, -4333018254962256161, -4520247665353434971, -4671685037882369100, -4675091662948690991, -4735175276741583987, 6350990130892997873, 6193519542673546730, -4777813365658391573, -4884666580064857355, 7915993906690313707, -4966819368814447677, 1988404640864293538, -5074155564662828583, -2824916873834092830, -5139981461522368419, -5166017660378616604, 7862649516541915518, -5199300045458833371, 1465691391119622848, -5274918237292093444, 3955522050341751173, 3028053988322132717, -5294964883437018204, -5398068012292194734, -4230499845382938824, -5611924257179262549, 7378537432822256858, 7280996660855756210, -2860431368737791792, -5642403076122918850, 8748593703074829038, -4521810425055688890, -5777257177420187475, 5667627940718240302, -5851042099656614678, -381250877232896297, -5851841732187841911, -5862440297616689604, -5971728663719484631, -5973285693890529946, 2510053155589298698, -5988891766515978299, 70795728308344319, -1868076891914377805, -6043811672519304421, -146246887556067543, -456478208951173587, -6049798575215068844, -6190793756855624574, -439453884076470944, -6265828292425732883, 1005932218091033829, -6276653945289983061, 4026161747709530616, -6352017385586988297, -6434173891659845956, -4902969105799271440, -6597656379480334442, 936548142763202986, -5711584171855415780, -6719529710276111650, -6745200761040317627, -6774664102182198859, -6775030951094616649, 2413830815755995994, -6866977855898294546, 1367735185190455738, -6926826760776660554, -4649630504583777134, -6973046940579303302, -1624737164478680071, -7056352110284547443, 8409193430637458073, -7072847735580191045, -7191067710687600286, -7215422517621569926, 1612966766035344182, -5429557228051554306, -7250710981660072473, -3482866482104200210, -4700408451300634211, -6630916991053458242, -7298747175893408236, -7310374615231856812, -4225653222477792371, -7413729794067718305, 2513926183394021747, -7514335923213535996, -7596956035979221813, 169562969996127286, -993345541839921710, -1779717869805256811, -7623371921505579016, 3616584282929475977, 3422514428607433852, -2075187328920528303, -7722939659019788128, -7817649810639021416, -6380135021339935291, -7930506008224660491, -8132867267306219864, -8325351725123749803, -8331622396381889999, -7821976751319527781, -8357047644244211984, 6681203624026928258, -8562244084964017695, -8663437424486236865, -5692685817825282327, -8710338559502572707, -8785146885964930196, 2438739308436778524, -207929740641409569, -8956614282985266058, -9027839242946536109, -9056248414770980571, -9203326022074967423} for 127.0.87.2
INFO  2020-12-10 10:46:25,750 [shard 1] compaction - [Compact system.peers f37d8760-3ad4-11eb-9aef-000000000001] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-aok9vv5h/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/md-5-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-aok9vv5h/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/md-3-big-Data.db:level=0, ]
Segmentation fault on shard 0.
Backtrace:
  0x00000000038a8cc4
  0x00000000038b3129
  0x00007fa5a0ea61df
  0x00000000025f57ae
  0x000000000261a821
  0x0000000002618803
  0x00000000029fb7d5
  0x0000000002a78998
  0x0000000003b11c91
```

```
(gdb) bt
#0  std::_Hashtable<dht::token, std::pair<dht::token const, gms::inet_address>, std::allocator<std::pair<dht::token const, gms::inet_address> >, std::__detail::_Select1st, std::equal_to<dht::token>, std::hash<dht::token>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::size (this=0x1) at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/hashtable.h:567
#1  std::unordered_map<dht::token, gms::inet_address, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<std::pair<dht::token const, gms::inet_address> > >::size (this=0x1)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/unordered_map.h:310
#2  locator::token_metadata_impl::clone_only_token_map(bool) const::$_1::operator()(locator::token_metadata_impl&) const (this=0x60000069f2d0, ret=...) at locator/token_metadata.cc:992
#3  std::__invoke_impl<seastar::future<locator::token_metadata_impl>, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&, locator::token_metadata_impl&>(std::__invoke_other, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&, locator::token_metadata_impl&) (__f=..., __args=...) at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
#4  std::__invoke<locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&, locator::token_metadata_impl&>(locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&, locator::token_metadata_impl&) (__fn=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
#5  std::__apply_impl<locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&, std::tuple<locator::token_metadata_impl>&, 0ul>(locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&, std::tuple<locator::token_metadata_impl>&, std::integer_sequence<unsigned long, 0ul>) (__f=..., __t=...) at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
#6  std::apply<locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&, std::tuple<locator::token_metadata_impl>&>(locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&, std::tuple<locator::token_metadata_impl>&) (__f=..., __t=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
#7  seastar::internal::do_with_impl<locator::token_metadata_impl, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1>(locator::token_metadata_impl&&, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&&) (rv1=..., rv2=...)
    at ./seastar/include/seastar/core/do_with.hh:96
#8  seastar::futurize<seastar::future<locator::token_metadata_impl> >::invoke<seastar::future<locator::token_metadata_impl> (*&)(locator::token_metadata_impl&&, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&&), locator::token_metadata_impl, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1>(seastar::future<locator::token_metadata_impl> (*&)(locator::token_metadata_impl&&, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&&), locator::token_metadata_impl&&, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&&) (args=..., args=..., func=<optimized out>) at ./seastar/include/seastar/core/future.hh:2135
#9  seastar::futurize_invoke<seastar::future<locator::token_metadata_impl> (*&)(locator::token_metadata_impl&&, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&&), locator::token_metadata_impl, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1>(seastar::future<locator::token_metadata_impl> (*&)(locator::token_metadata_impl&&, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&&), locator::token_metadata_impl&&, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&&) (args=..., args=..., 
    func=<optimized out>) at ./seastar/include/seastar/core/future.hh:2166
#10 seastar::do_with<locator::token_metadata_impl, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1>(locator::token_metadata_impl&&, locator::token_metadata_impl::clone_only_token_map(bool) const::$_1&&) (rv1=..., rv2=...)
    at ./seastar/include/seastar/core/do_with.hh:131
#11 0x000000000261a822 in locator::token_metadata_impl::clone_only_token_map (this=0x1, clone_sorted_tokens=false) at locator/token_metadata.cc:991
#12 locator::token_metadata_impl::clone_after_all_left (this=0x1) at locator/token_metadata.cc:437
#13 0x0000000002618804 in locator::token_metadata::clone_after_all_left (this=<optimized out>) at locator/token_metadata.cc:1863
#14 0x00000000029fb7d6 in service::storage_service::get_changed_ranges_for_leaving (this=this@entry=0x600000243600, keyspace_name=..., endpoint=...) at service/storage_service.cc:2408
#15 0x0000000002a78999 in service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35::operator()() const (this=0x60000306c810) at service/storage_service.cc:2511
#16 std::__invoke_impl<void, service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35>(std::__invoke_other, service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35&&) (__f=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
#17 std::__invoke<service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35>(service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35&&) (__fn=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
#18 std::__apply_impl<service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35, std::tuple<>>(service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35&&, std::tuple<>&&, std::integer_sequence<unsigned long>) (
    __f=..., __t=...) at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
#19 std::apply<service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35, std::tuple<> >(service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35&&, std::tuple<>&&) (__f=..., __t=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
#20 seastar::futurize<void>::apply<service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35>(service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35&&, std::tuple<>&&) (func=..., args=...)
    at ./seastar/include/seastar/core/future.hh:2099
#21 seastar::async<service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35>(seastar::thread_attributes, service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35&&)::{lambda()#1}::operator()() const (
    this=0x60000022f9a0) at ./seastar/include/seastar/core/thread.hh:258
#22 seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35>(seastar::thread_attributes, service::storage_service::restore_replica_count(gms::inet_address, gms::inet_address)::$_35&&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) (func=0x60000022f9a0) at ./seastar/include/seastar/util/noncopyable_function.hh:116
#23 0x0000000003b11c92 in seastar::noncopyable_function<void ()>::operator()() const (this=0x600000376008) at ./seastar/include/seastar/util/noncopyable_function.hh:201
#24 seastar::thread_context::main (this=0x60000022f980) at ./seastar/src/core/thread.cc:297
```

It looks like in https://github.com/scylladb/scylla/blob/18be57a4e5b7c3df6b51d44a68c144e46f74a8f7/service/storage_service.cc#L2492-L2502
we get a reference to the token_metadata and then may yield when calling `tm.clone_only_token_map`.
Instead, we must hold on to a token_metadata_ptr that will ensure the copy we're looking at will remain valid.

**Comment by avikivity** [comment]
I think no release stream is vulnerable. @bhalevy please confirm.

**Comment by bhalevy** [comment]
> I think no release stream is vulnerable. @bhalevy please confirm.

@avikivity confirmed. The root cause is in 4a622c14e13ce1a472fcb3398e9ee70be524dc50 which is not in any release branch.
