### ISSUE TITLE
Nodetool repair failures after node termination

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#7828]
*Installation details*
Scylla version (or git commit hash): 4.3.rc3-0.20201220.5bd52e4db with build-id ec3427545525638e1720aab150d5addd4b625131
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0554c4148bc9549b0 (eu-north-1)
### Scenario: **longevity-mv-si-4days**

At `2020-12-22 20:44:23.087` a TerminateAndRemoveNodeMonkey nemesis has started, with node 9 being the target node. The nemesis shuts down the target node's scylla service and terminates its instance. Afterwards the nemesis executes a full nodetool repair, removes the node from the cluster and adds a new node in its place.

However, the `nodetool repair` stage failed, with 140 of the repair segments failing to be repaired:
```
< t:2020-12-22 20:45:41,984 f:remote_base.py  l:519  c:RemoteCmdRunner      p:DEBUG > Running command "/usr/bin/nodetool  repair "...
...
2020-12-22T20:45:45+00:00  longevity-mv-si-4d-4-3-db-node-866b9e4d-1 !WARNING | scylla: [shard 0] repair - repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] failed: std::runtime_error ({shard 0: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 0 failed to repair 140 sub ranges), shard 1: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 1 failed to repair 140 sub ranges), shard 2: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 2 failed to repair 140 sub ranges), shard 3: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 3 failed to repair 140 sub ranges), shard 4: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 4 failed to repair 140 sub ranges), shard 5: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 5 failed to repair 140 sub ranges), shard 6: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 6 failed to repair 140 sub ranges), shard 7: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 7 failed to repair 140 sub ranges), shard 8: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 8 failed to repair 140 sub ranges), shard 9: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 9 failed to repair 140 sub ranges), shard 10: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 10 failed to repair 140 sub ranges), shard 11: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 11 failed to repair 140 sub ranges), shard 12: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 12 failed to repair 140 sub ranges), shard 13: std::runtime_error (repair id [id=1403, uuid=39cedf27-3bdb-4ef4-a045-0a6debdd351c] on shard 13 failed to repair 140 sub ranges)})
...
Command: '/usr/bin/nodetool  repair '

Exit code: 2

Stdout:

Using /etc/scylla/scylla.yaml as the config file
[2020-12-22 20:45:44,190] Starting repair command #1403, repairing 1 ranges for keyspace system_traces (parallelism=SEQUENTIAL, full=true
[2020-12-22 20:45:46,290] Repair session 1403 failed
[2020-12-22 20:45:46,291] Repair session 1403 finished

Stderr:

error: Repair job has failed with the error message: [2020-12-22 20:45:46,290] Repair session 1403 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2020-12-22 20:45:46,290] Repair session 1403 failed
  at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
  at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
  at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
  at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
  at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
  at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

Monitor:
```
http://13.49.223.117:3000/d/rSoTVHxGz/scylla-per-server-metrics-nemesis-master?orgId=1&from=1608669722550&to=1608671298336
```

Logs:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                           Log links for testrun with test id 866b9e4d-6cb2-4ee4-8bde-831294501a61                                            |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                         |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| 20201223_131123 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/866b9e4d-6cb2-4ee4-8bde-831294501a61/20201223_131123/db-cluster-866b9e4d.zip  |
| 20201223_131123 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/866b9e4d-6cb2-4ee4-8bde-831294501a61/20201223_131123/loader-set-866b9e4d.zip  |
| 20201223_131123 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/866b9e4d-6cb2-4ee4-8bde-831294501a61/20201223_131123/monitor-set-866b9e4d.zip |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by slivne** [comment]
This is expected one of the nodes is not avail so full repair can't be done - we are missing a node - so its a best effort repair that ends with errors - I think we have another issue like that already open

**Comment by slivne** [comment]
https://github.com/scylladb/scylla/issues/7806

**Comment by slivne** [comment]
closing as duplicate
