### ISSUE TITLE
scylla_setup: Performance Tuning setup failed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7895]
*Installation details*
Scylla version (or git commit hash):
```
scylla-server-4.4.dev-0.20210105.e54cc078a.x86_64
scylla-tools-core-4.4.dev-0.20210105.e54cc078a.noarch
scylla-jmx-4.4.dev-0.20210105.e54cc078a.noarch
scylla-4.4.dev-0.20210105.e54cc078a.x86_64
scylla-conf-4.4.dev-0.20210105.e54cc078a.x86_64
scylla-python3-4.4.dev-0.20210105.e54cc078a.x86_64
scylla-kernel-conf-4.4.dev-0.20210105.e54cc078a.x86_64
scylla-tools-4.4.dev-0.20210105.e54cc078a.noarch
scylla-node-exporter-4.4.dev-0.20210105.e54cc078a.x86_64
```
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7
GCE instance type: Instance type: `n1-standard-2`

#### Scylla Setup cmdline:

```
sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory /

07:31:51  Exit code: 1
07:31:51  
07:31:51  Stdout:
07:31:51  
07:31:51                  #5  0x0000000000432353 execute_command_internal (bash)
07:31:51                  #6  0x0000000000433d3e execute_command (bash)
07:31:51                  #7  0x000000000041e375 reader_loop (bash)
07:31:51                  #8  0x000000000041c9de main (bash)
07:31:51                  #9  0x00007ff428f39555 __libc_start_main (libc.so.6)
07:31:51                  #10 0x000000000041d47a _start (bash)
07:31:51  
07:31:51  
07:31:51  systemd-coredump is working finely.
07:31:51  Performance Tuning setup failed.
07:31:51  
07:31:51  Stderr:
07:31:51  
07:31:51  INFO  2021-01-05 23:31:17,564 [shard 0] iotune - /var/tmp/mnt passed sanity checks
07:31:51  Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /usr/lib/systemd/system/scylla-server.service.
07:31:51  Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-scylla.mount to /etc/systemd/system/var-lib-scylla.mount.
07:31:51  Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-systemd-coredump.mount to /etc/systemd/system/var-lib-systemd-coredump.mount.
07:31:51  Traceback (most recent call last):
07:31:51    File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 83, in <module>
07:31:51      rps_cpus = run('{} --tune net --nic {} --get-cpu-mask'.format(perftune_base_command(), ifname), shell=True, check=True, capture_output=True, encoding='utf-8').stdout.strip()
07:31:51    File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
07:31:51      raise CalledProcessError(retcode, process.args,
07:31:51  subprocess.CalledProcessError: Command '/opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic eth0 --get-cpu-mask' returned non-zero exit status 1.
```

#### Test info

- Test-id: 612d22b8-ede1-4527-8ae2-a6bbc6fb810b
- db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/612d22b8-ede1-4527-8ae2-a6bbc6fb810b/20210105_233216/db-cluster-612d22b8.zip
- sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/612d22b8-ede1-4527-8ae2-a6bbc6fb810b/20210105_233216/sct-runner-612d22b8.zip

/CC @hagitsegev @roydahan @syuu1228

**Comment by amoskong** [comment]
The last Passed job is https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos7-test/319/
```
scylla-server-4.4.dev-0.20210104.d5da455d9.x86_64
scylla-node-exporter-4.4.dev-0.20210104.d5da455d9.x86_64
scylla-tools-4.4.dev-0.20210104.d5da455d9.noarch
scylla-4.4.dev-0.20210104.d5da455d9.x86_64
scylla-conf-4.4.dev-0.20210104.d5da455d9.x86_64
scylla-python3-4.4.dev-0.20210104.d5da455d9.x86_64
scylla-kernel-conf-4.4.dev-0.20210104.d5da455d9.x86_64
scylla-tools-core-4.4.dev-0.20210104.d5da455d9.noarch
scylla-jmx-4.4.dev-0.20210104.d5da455d9.noarch
scylla-manager-agent-666.dev-0.20201230.d4b270c9.x86_64
```

So the problem was introduced in following changes:
```
[amos@fedora scylla]$ git log --oneline d5da455d9..e54cc078a
e54cc078a1 Update seastar submodule
43a2636229 Merge "Remove proxy from size-estimates reader" from Pavel E
9632af5d6b schema_tables: Drop unused merge_schema overload
ed31dd1742 cql-pytest: port Cassandra's unit test validation/entities/counters_test
05d6eff850 cql-pytest: add tests for non-support of unicode equivalence`
feb028c97e cql-pytest: add reproducer for issue 7856
3a3ee45488 size_estimate_reader: Use local db reference not global
107dcbfbd6 size_estimate_reader: Keep database reference on mutation reader
48e494fb62 size_estimate_reader: Keep database reference on virtual_reader
```

The following commit related with perftune.py

```
commit e54cc078a14e8adace9789fce4c362222aed88d6
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Tue Jan 5 13:32:21 2021 +0200

    Update seastar submodule
    
    * seastar d1b5d41b...a2fc9d72 (6):
      > perftune.py: support passing multiple --nic options to tune multiple interfaces at once
      > perftune.py recognize and sort IRQs for Mellanox NICs
      > perftune.py: refactor getting of driver name into __get_driver_name()
    Fixes #6266
      > install-dependencies: support Manjaro
      > append_challenged_posix_file_impl: optimize_queue: use max of sloppy_size_hint and speculative_size
      > future: do_until: handle exception in stop condition
```

/CC @penberg @syuu1228

**Comment by amoskong** [comment]
Related seastart commits
```
commit 56cfe17970f3798321a36e73ab212ca2be015d14
Author: Dmitry Kropachev <dmitry.kropachev@gmail.com>
Date:   Wed Jan 6 21:21:38 2021 +0700

    perftune.py: Fix nic_is_bond_iface() and other function signatures
    
    Commit a2fc9d72c31b97840bc75ae49dbd6f4b6d394e25 introduced regression
    causing the script to fail with following error:
    
      ERROR: nic_is_bond_iface() missing 1 required positional argument: 'nic'. Your system can't be tuned until the issue is fixed.
    
    Fix the issue by removing the "@property" annotations, which replace the
    function with a Python getter.
    
    Acked-by: Lubos Kosco <lubos@scylladb.com>
    Closes #852

:100755 100755 52bc44c7 9cab8d91 M	scripts/perftune.py

commit a2fc9d72c31b97840bc75ae49dbd6f4b6d394e25
Author: Lubos Kosco <lubos@scylladb.com>
Date:   Tue Sep 22 10:49:25 2020 +0200

    perftune.py: support passing multiple --nic options to tune multiple interfaces at once
    
    This is needed mainly for Azure, which exposes physical interface
    (enP...) and virtual interface(eth?). Virtual interface is used in OS
    and has IP assigned, physical interface however needs to be tuned, so
    perftune should be able to tune both in one run.

:100755 100755 8f2dfd78 52bc44c7 M	scripts/perftune.py

commit f7ab76107687a282406a6cb1c3da704e2efe5dce
Author: Lubos Kosco <tarzanek@gmail.com>
Date:   Wed Sep 30 15:04:05 2020 +0200

    perftune.py recognize and sort IRQs for Mellanox NICs
    
    comparator for mlx irqs should detect if mlx is not present
    
    set proper message for driver detection
    
    Various cards use different names in interrupts listing output. To have
    proper comparator with proper regex parsing we should add support for
    card names/regexps to be recognized for queues and properly parsed from
    interrupts. They are not always in order and in sync and definitely they
    can vary between machines(so same NIC won't get the same IRQs assigned
    to its queues, even on same cloud)

:100755 100755 4fabd9da 8f2dfd78 M	scripts/perftune.py

commit 2b809ebe29221ebbe89bffe419264ec89bc5edcb
Author: Lubos Kosco <lubos@scylladb.com>
Date:   Wed Sep 30 13:36:44 2020 +0200

    perftune.py: refactor getting of driver name into __get_driver_name()

:100755 100755 516cd3ef 4fabd9da M	scripts/perftune.py
```

**Comment by tarzanek** [comment]
ack, will check and send the fix asap

**Comment by tarzanek** [comment]
cannot repro on my VM from dev checkout:
```
[lubos@gcpdisktoramtest scripts]$ ./perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic eth0 --get-cpu-mask
0x00000003
[lubos@gcpdisktoramtest scripts]$ echo $?
0
```

@amoskong how do I access above VM?

**Comment by tarzanek** [comment]
can repro now
```
[scylla-test@artifacts-centos7-jenkins-db-node-5641df59-0-1 ~]$ /opt/scylladb/scripts/perftune.py --tune net --nic "eth0" --mode mq --dump-options-file
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/perftune.py", line 1403, in <module>
    dump_config(args)
  File "/opt/scylladb/scripts/libexec/perftune.py", line 1354, in dump_config
    if prog_args.nic:
AttributeError: 'Namespace' object has no attribute 'nic'
```
will fix

**Comment by tarzanek** [comment]
https://github.com/scylladb/seastar/pull/853

**Comment by amoskong** [comment]
> cannot repro on my VM from dev checkout (below is n1-standard-2):

The problem in perf tune setup should be fixed by https://github.com/scylladb/seastar/commit/56cfe17970f3798321a36e73ab212ca2be015d14

> ```
> [lubos@gcpdisktoramtest scripts]$ ./perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic eth0 --get-cpu-mask
> 0x00000003
> [lubos@gcpdisktoramtest scripts]$ echo $?
> 0
> ```

There is a new fail in scylla_prepare.
We just reproduced in https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos7-test/324/

```
scylla_prepare[4673]: Exception occurred while creating perftune.yaml: 
Command '/opt/scylladb/scripts/perftune.py --tune net --nic "eth0" --mode mq --dump-options-file' returned non-zero exit 
```

version: scylla-server-4.4.dev-0.20210107.9eed26ca3d8.x86_64
I saw you already sent a fix PR, Thanks.

**Comment by amoskong** [comment]
This issue had been fixed by https://github.com/scylladb/scylla/commit/e5fe0acd155f6fcb3ddb811c74df5b58c3e75a3a, artifact-test of centos7 passed now.

We can close this issue.

**Comment by juliayakovlev** [comment]
Similar failure with "Performance Tuning setup failed."

Test: artifacts-amazon2-test

System under test
```
ScyllaDB repo: https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/master/rpm/centos/2021-01-11T02:13:34Z/scylla.repo
Actual aws image used: ami-099a8245f5daa82bf
AWS region: eu-west-1
Instance type: i3.large
Scylla packages installed:
scylla-tools-core-4.4.dev-0.20210111.3aa80f47fec.noarch
scylla-jmx-4.4.dev-0.20210111.3aa80f47fec.noarch
scylla-conf-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-node-exporter-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-tools-4.4.dev-0.20210111.3aa80f47fec.noarch
scylla-server-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-kernel-conf-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-python3-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-4.4.dev-0.20210111.3aa80f47fec.x86_64
```

[Job](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-amazon2-test/148/)

Error ```ValueError: invalid literal for int() with base 16: 'Driver ena has been detected.\n00000003'```:
```
2021-01-11 09:05:41.047: (TestFrameworkEvent Severity.ERROR), source=ArtifactsTest.SetUp()
exception=[Node artifacts-amazon2-jenkins-db-node-de08233f-1 [34.241.36.180 | 10.0.0.225] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
#5  0x0000000000431ab5 execute_command_internal (bash)
#6  0x00000000004332fe execute_command (bash)
#7  0x000000000041e327 reader_loop (bash)
#8  0x000000000041cbc5 main (bash)
#9  0x00007fe733bff02a __libc_start_main (libc.so.6)
#10 0x000000000041d5fa _start (bash)
systemd-coredump is working finely.
Performance Tuning setup failed.
Stderr:
Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /usr/lib/systemd/system/scylla-server.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-scylla.mount to /etc/systemd/system/var-lib-scylla.mount.
Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-systemd-coredump.mount to /etc/systemd/system/var-lib-systemd-coredump.mount.
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 85, in <module>
cpuset = hex2list(rps_cpus)
File "/opt/scylladb/scripts/scylla_util.py", line 552, in hex2list
hex_int = int(hex_str2, 16)
ValueError: invalid literal for int() with base 16: 'Driver ena has been detected.\n00000003'
Traceback (most recent call last):
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3268, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3894, in node_setup
self._scylla_post_install(node, install_scylla, devname)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 933, in _scylla_post_install
super()._scylla_post_install(node, new_scylla_installed, devname)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3958, in _scylla_post_install
node.scylla_setup(disks, devname)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 110, in inner
res = func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster.py", line 2181, in scylla_setup
self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --setup-nic-and-disks {}'
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
#5  0x0000000000431ab5 execute_command_internal (bash)
#6  0x00000000004332fe execute_command (bash)
#7  0x000000000041e327 reader_loop (bash)
#8  0x000000000041cbc5 main (bash)
#9  0x00007fe733bff02a __libc_start_main (libc.so.6)
#10 0x000000000041d5fa _start (bash)
systemd-coredump is working finely.
Performance Tuning setup failed.
Stderr:
Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /usr/lib/systemd/system/scylla-server.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-scylla.mount to /etc/systemd/system/var-lib-scylla.mount.
Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-systemd-coredump.mount to /etc/systemd/system/var-lib-systemd-coredump.mount.
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 85, in <module>
cpuset = hex2list(rps_cpus)
File "/opt/scylladb/scripts/scylla_util.py", line 552, in hex2list
hex_int = int(hex_str2, 16)
ValueError: invalid literal for int() with base 16: 'Driver ena has been detected.\n00000003'
```

Hydra commands:
```
Restore Monitor Stack command: $ hydra investigate show-monitor de08233f-a417-4a53-b26f-357208ca8736
Show all stored logs command: $ hydra investigate show-logs de08233f-a417-4a53-b26f-357208ca8736
```

Logs:
```
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/de08233f-a417-4a53-b26f-357208ca8736/20210111_090611/db-cluster-de08233f.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/de08233f-a417-4a53-b26f-357208ca8736/20210111_090611/sct-runner-de08233f.zip
```

**Comment by amoskong** [comment]
> Similar failure with "Performance Tuning setup failed."

It's a different error, I had opened a new issue.

----

There are two problems in this issue:

- problem 1: fail to execute perftune.py in scylla_setup (fixed)
- problem 2: fail to execute perftune.py in scylla_prepare ( in start stage)  (fixed)

The above two problem had been fixed.

There is another problem on OEL7 and amazon (as you mentioned).I opened a new issue for it:
- https://github.com/scylladb/scylla/issues/7905


> Test: artifacts-amazon2-test


> [Job](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-amazon2-test/148/)
> 
> Error `ValueError: invalid literal for int() with base 16: 'Driver ena has been detected.\n00000003'`:
> 
> ```
> 2021-01-11 09:05:41.047: (TestFrameworkEvent Severity.ERROR), source=ArtifactsTest.SetUp()
> exception=[Node artifacts-amazon2-jenkins-db-node-de08233f-1 [34.241.36.180 | 10.0.0.225] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
> Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
> Exit code: 1


> Traceback (most recent call last):
> File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 85, in <module>
> cpuset = hex2list(rps_cpus)
> File "/opt/scylladb/scripts/scylla_util.py", line 552, in hex2list
> hex_int = int(hex_str2, 16)
> ValueError: invalid literal for int() with base 16: 'Driver ena has been detected.\n00000003'
> ```

**Comment by penberg** [comment]
@amoskong The issues is fixed in `scylla.git` master branch, right?

**Comment by amoskong** [comment]
> @amoskong The issues is fixed in `scylla.git` master branch, right?

Yes, we can close this issue.
