### ISSUE TITLE
scylla_sysconfig_setup: ValueError: invalid literal for int() with base 16: 'Driver ena has been detected.\n00000003'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7905]
*Installation details*
Scylla version (or git commit hash): 

scylla-tools-core-4.4.dev-0.20210111.3aa80f47fec.noarch
scylla-python3-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-conf-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-kernel-conf-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-tools-4.4.dev-0.20210111.3aa80f47fec.noarch
scylla-jmx-4.4.dev-0.20210111.3aa80f47fec.noarch
scylla-server-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-node-exporter-4.4.dev-0.20210111.3aa80f47fec.x86_64

Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): OEL7

### Description

Artifact test of CentOS7, CentOS8, Debian10, Debian9, Ubuntu 16, Ubuntu 18 and Ubuntu 20 all PASSed.
The problem only exists with artifact-test of OEL 7.

Recently artifact-test of OEL7 all passed except the last one, so it's a regression issue.
- https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/artifacts/job/artifacts-oel76-test/291/

### Problem

`scylla_sysconfig_setup` script will convert the output of  `seastart/scripts/perftune.py` by `scylla_utils.py:hex2list()`

The "Driver xx has been detected" message was added by @tarzanek in commit https://github.com/scylladb/seastar/commit/f7ab76107687a282406a6cb1c3da704e2efe5dce
- the patch was applied to scylla 6 days ago (https://github.com/scylladb/scylla/commit/e54cc078a14e8adace9789fce4c362222aed88d6)

It's clean that the problem was introduced by this change.

### Solution

- option 1: Remove the message to fix the regression
- option 2: only convert the last line of the output from perftune.py   /Cc @syuu1228 

### SCT test logs:

```
2021-01-11 09:18:54.220: (TestFrameworkEvent Severity.ERROR), source=ArtifactsTest.SetUp()
exception=[Node artifacts-oel76-jenkins-db-node-7c4de4c0-1 [54.75.76.14 | 10.0.0.220] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
#5  0x0000000000432233 execute_command_internal (bash)
#6  0x0000000000433c1e execute_command (bash)
#7  0x000000000041e255 reader_loop (bash)
#8  0x000000000041c8be main (bash)
#9  0x00007f47717ad495 __libc_start_main (libc.so.6)
#10 0x000000000041d35a _start (bash)
systemd-coredump is working finely.
Performance Tuning setup failed.
Stderr:
Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /usr/lib/systemd/system/scylla-server.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-scylla.mount to /etc/systemd/system/var-lib-scylla.mount.
Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-systemd-coredump.mount to /etc/systemd/system/var-lib-systemd-coredump.mount.
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 85, in <module>
cpuset = hex2list(rps_cpus)
File "/opt/scylladb/scripts/scylla_util.py", line 552, in hex2list
hex_int = int(hex_str2, 16)
ValueError: invalid literal for int() with base 16: 'Driver ena has been detected.\n00000003'
Traceback (most recent call last):
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3268, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3894, in node_setup
self._scylla_post_install(node, install_scylla, devname)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 933, in _scylla_post_install
super()._scylla_post_install(node, new_scylla_installed, devname)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3958, in _scylla_post_install
node.scylla_setup(disks, devname)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 110, in inner
res = func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/cluster.py", line 2181, in scylla_setup
self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --setup-nic-and-disks {}'
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-oel76-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
#5  0x0000000000432233 execute_command_internal (bash)
#6  0x0000000000433c1e execute_command (bash)
#7  0x000000000041e255 reader_loop (bash)
#8  0x000000000041c8be main (bash)
#9  0x00007f47717ad495 __libc_start_main (libc.so.6)
#10 0x000000000041d35a _start (bash)
systemd-coredump is working finely.
Performance Tuning setup failed.
Stderr:
Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /usr/lib/systemd/system/scylla-server.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-scylla.mount to /etc/systemd/system/var-lib-scylla.mount.
Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-systemd-coredump.mount to /etc/systemd/system/var-lib-systemd-coredump.mount.
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 85, in <module>
cpuset = hex2list(rps_cpus)
File "/opt/scylladb/scripts/scylla_util.py", line 552, in hex2list
hex_int = int(hex_str2, 16)
ValueError: invalid literal for int() with base 16: 'Driver ena has been detected.\n00000003'
```

/Cc @hagitsegev @penberg @roydahan

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
