### ISSUE TITLE
Nodetool cleanup failed because of "DC or rack not found in snitch properties"

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylla#7930]
*Installation details* 
Scylla version (or git commit hash): 4.3.rc3-0.20201217.5bd52e4db
Cluster size: 18
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

When I executed the `nodetool cleanup` command after performing `nodetool repair` on a DC in the cluster, the following error occurred.
```
[root@01 ~]# nodetool cleanup
Using /etc/scylla/scylla.yaml as the config file
WARN  16:42:29,831 Unable to read cassandra-rackdc.properties
error: DC or rack not found in snitch properties, check your configuration in: cassandra-rackdc.properties
-- StackTrace --
org.apache.cassandra.exceptions.ConfigurationException: DC or rack not found in snitch properties, check your configuration in: cassandra-rackdc.properties
	at org.apache.cassandra.locator.GossipingPropertyFileSnitch.loadConfiguration(GossipingPropertyFileSnitch.java:76)
	at org.apache.cassandra.locator.GossipingPropertyFileSnitch.<init>(GossipingPropertyFileSnitch.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:545)
	at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:538)
	at org.apache.cassandra.config.DatabaseDescriptor.createEndpointSnitch(DatabaseDescriptor.java:1018)
	at org.apache.cassandra.config.DatabaseDescriptor.applySnitch(DatabaseDescriptor.java:942)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:192)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:157)
	at org.apache.cassandra.tools.NodeProbe.checkJobs(NodeProbe.java:337)
	at org.apache.cassandra.tools.NodeProbe.forceKeyspaceCleanup(NodeProbe.java:344)
	at org.apache.cassandra.tools.nodetool.Cleanup.execute(Cleanup.java:55)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:270)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:180)

```
The following is the content of my cassandra-rackdc.properties file
```
[root@01 ~]# cat /etc/scylla/cassandra-rackdc.properties 
#
# cassandra-rackdc.properties
#
# The lines may include white spaces at the beginning and the end.
# The rack and data center names may also include white spaces.
# All trailing and leading white spaces will be trimmed.
#  
dc=DC01
rack=DC02_Rack01
# prefer_local=<false | true>
# dc_suffix=<Data Center name suffix, used by EC2SnitchXXX snitches>
#
```

```
[root@01 ~]# nodetool status
Using /etc/scylla/scylla.yaml as the config file
Datacenter: DC01
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  10.195.152.7   5.95 TB    256          ?       ad1b06f3-43c4-4bec-89a8-cc7bdd8cfcc4  DC01_Rack01
UN  10.195.152.11  5.63 TB    256          ?       78be6786-f3a4-4a2e-b1d8-5b1f44f6b86d  DC01_Rack01
UN  10.195.152.10  5.7 TB     256          ?       8a695f2f-6649-47f8-9562-d209ee44301b  DC01_Rack01
UN  10.195.152.9   5.72 TB    256          ?       3d25bfe1-1778-4a6c-bb63-1e02762831a0  DC01_Rack01
UN  10.195.152.8   5.94 TB    256          ?       9cfde9a7-0a5c-4c11-a8f7-2c756b2e40ea  DC01_Rack01
UN  10.195.152.12  5.33 TB    256          ?       6f318f15-e80a-48d9-86bb-37f75aab3adb  DC01_Rack01
Datacenter: DC02
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  10.195.154.7   5.29 TB    256          ?       8e621be8-c7a9-43c3-89be-64232e29b472  DC02_Rack01
UN  10.195.154.11  5.65 TB    256          ?       c98cd032-13bf-4cc0-93a7-2ffa457a3384  DC02_Rack01
UN  10.195.154.10  6.1 TB     256          ?       321fc1ec-4133-4fa6-806c-c232c46b3b46  DC02_Rack01
UN  10.195.154.9   5.65 TB    256          ?       dd834574-e33d-4db7-bc04-3914e0fc9df9  DC02_Rack01
UN  10.195.154.8   5.65 TB    256          ?       05698698-98cf-4b77-bb98-13e25216dda0  DC02_Rack01
UN  10.195.154.12  5.51 TB    256          ?       56483a09-8732-408e-bfa6-bbbd34f22339  DC02_Rack01
Datacenter: DC03
==========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  10.181.159.71  5.16 TB    256          ?       e33dfa28-4cdd-4fc4-a451-b7d438360265  DC03_Rack01
UN  10.181.159.70  5.3 TB     256          ?       3a3aac3c-e8a8-43d2-8100-473c73c0d483  DC03_Rack01
UN  10.181.159.73  5.35 TB    256          ?       c5240d47-f4fd-4272-b106-9b7f8445d9ea  DC03_Rack01
UN  10.181.159.72  5.28 TB    256          ?       12ed5c12-bb2f-469a-9670-8b424602678d  DC03_Rack01
UN  10.181.159.75  5.46 TB    256          ?       3c017acd-0f5a-4907-b3cc-d5b2d985833b  DC03_Rack01
UN  10.181.159.74  5.35 TB    256          ?       2ee2644e-a653-4214-bc2d-fa287b37f085  DC03_Rack01


```

**Comment by slivne** [comment]
was able to reproduce this in docker with 4.3.0

steps


1. start a docker container using 4.3.0
2. change /etc/scylla/cassandra-rackdc.properties 
```
[root@some-scylla /]# cat /etc/scylla/cassandra-rackdc.properties 
#
# cassandra-rackdc.properties
#
# The lines may include white spaces at the beginning and the end.
# The rack and data center names may also include white spaces.
# All trailing and leading white spaces will be trimmed.
#  
# dc=my_data_center
# rack=my_rack
# prefer_local=<false | true>
# dc_suffix=<Data Center name suffix, used by EC2SnitchXXX snitches>
#
dc=DC01
rack=DC02_Rack01
```
3. change /etc/scylla.yaml
```
endpoint_snitch: GossipingPropertyFileSnitch
```
4. restart scylla
```
supervisorctl restart scylla
```
5. check nodetool status
```
nodetool status
Using /etc/scylla/scylla.yaml as the config file
Datacenter: DC01
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.2  1.45 MB    256          ?       252c7231-9ed2-4b9f-baa3-0796778c6f88  DC02_Rack01

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
[root@some-scylla /]# 
```
7. check nodetool describecluster
```
[root@some-scylla /]# nodetool describecluster
Using /etc/scylla/scylla.yaml as the config file
Cluster Information:
	Name: Test Cluster
	Snitch: org.apache.cassandra.locator.GossipingPropertyFileSnitch
	DynamicEndPointSnitch: disabled
	Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
	Schema versions:
		4075d1b6-9187-36b1-bb7a-7fdf6b2a8871: [172.17.0.2]
```
8. run nodetool cleanup
```
nodetool cleanup
Using /etc/scylla/scylla.yaml as the config file
WARN  19:58:26,176 Only 33.197GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
WARN  19:58:26,201 Unable to read cassandra-rackdc.properties
error: DC or rack not found in snitch properties, check your configuration in: cassandra-rackdc.properties
-- StackTrace --
org.apache.cassandra.exceptions.ConfigurationException: DC or rack not found in snitch properties, check your configuration in: cassandra-rackdc.properties
	at org.apache.cassandra.locator.GossipingPropertyFileSnitch.loadConfiguration(GossipingPropertyFileSnitch.java:76)
	at org.apache.cassandra.locator.GossipingPropertyFileSnitch.<init>(GossipingPropertyFileSnitch.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:545)
	at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:538)
	at org.apache.cassandra.config.DatabaseDescriptor.createEndpointSnitch(DatabaseDescriptor.java:1018)
	at org.apache.cassandra.config.DatabaseDescriptor.applySnitch(DatabaseDescriptor.java:942)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:192)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:157)
	at org.apache.cassandra.tools.NodeProbe.checkJobs(NodeProbe.java:337)
	at org.apache.cassandra.tools.NodeProbe.forceKeyspaceCleanup(NodeProbe.java:344)
	at org.apache.cassandra.tools.nodetool.Cleanup.execute(Cleanup.java:55)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:270)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:180)
```
doing the same on 4.2.3 works

```
[root@some-scylla-4 /]# nodetool status
Datacenter: DC01
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.10  0 bytes    256          ?       b5ce43c5-58c4-4757-85ff-1552175eaa9f  DC02_Rack01

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
[root@some-scylla-4 /]# nodetool describecluster
Cluster Information:
	Name: Test Cluster
	Snitch: org.apache.cassandra.locator.GossipingPropertyFileSnitch
	DynamicEndPointSnitch: disabled
	Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
	Schema versions:
		16071240-10bd-3d15-b681-7d80a2dcecfd: [172.17.0.10]

[root@some-scylla-4 /]# nodetool cleanup
WARN  20:13:35,371 Only 30.380GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
[root@some-scylla-4 /]# scylla --version
4.2.3-0.20210104.24346215c2
```

**Comment by amnonh** [comment]
I suspect the issu is with the location of ``cassandra-rackdc.properties``

When I copied it to:
``/etc/scylla/cassandra/cassandra-rackdc.properties``
It works:
```
sh-4.2# nodetool cleanup
Using /etc/scylla/scylla.yaml as the config file
WARN  12:39:49,826 Only 40.396GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
WARN  12:39:49,859 Unable to read cassandra-rackdc.properties
error: DC or rack not found in snitch properties, check your configuration in: cassandra-rackdc.properties
-- StackTrace --
org.apache.cassandra.exceptions.ConfigurationException: DC or rack not found in snitch properties, check your configuration in: cassandra-rackdc.properties
	at org.apache.cassandra.locator.GossipingPropertyFileSnitch.loadConfiguration(GossipingPropertyFileSnitch.java:76)
	at org.apache.cassandra.locator.GossipingPropertyFileSnitch.<init>(GossipingPropertyFileSnitch.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:545)
	at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:538)
	at org.apache.cassandra.config.DatabaseDescriptor.createEndpointSnitch(DatabaseDescriptor.java:1018)
	at org.apache.cassandra.config.DatabaseDescriptor.applySnitch(DatabaseDescriptor.java:942)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:192)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:157)
	at org.apache.cassandra.tools.NodeProbe.checkJobs(NodeProbe.java:337)
	at org.apache.cassandra.tools.NodeProbe.forceKeyspaceCleanup(NodeProbe.java:344)
	at org.apache.cassandra.tools.nodetool.Cleanup.execute(Cleanup.java:55)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:270)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:180)

sh-4.2# cp /etc/scylla/cassandra-rackdc.properties /etc/scylla/cassandra/
sh-4.2# nodetool cleanup
Using /etc/scylla/scylla.yaml as the config file
WARN  12:40:10,415 Only 40.395GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
```

**Comment by amnonh** [comment]
In 4.2: 
CASSANDRA_CONF = /tmp/tmp.AICc1DnTDx
and all files were copied there:
```
$ ls /tmp/tmp.AICc1DnTDx
cassandra-env.sh	     cassandra.yaml	  jvm-server.options	 jvm11-server.options  jvm8-server.options  logback.xml
cassandra-rackdc.properties  jvm-clients.options  jvm11-clients.options  jvm8-clients.options  logback-tools.xml    scylla.yaml
```
in 4.3
CASSANDRA_CONF = /etc/scylla/cassandra
But /etc/scylla is not part of the CLASSPATH
```
/etc/scylla/cassandra:/opt/scylladb/share/cassandra/lib/HdrHistogram-2.1.9.jar:/opt/scylladb/share/cassandra/lib/ST4-4.0.8.jar:/opt/scylladb/share/cassandra/lib/airline-0.6.jar:/opt/scylladb/share/cassandra/lib/antlr-runtime-3.5.2.jar:/opt/scylladb/share/cassandra/lib/apache-cassandra-4.3.0-0.20210110.000585522.jar:/opt/scylladb/share/cassandra/lib/apache-cassandra-thrift-4.3.0-0.20210110.000585522.jar:/opt/scylladb/share/cassandra/lib/apache-cassandra.jar:/opt/scylladb/share/cassandra/lib/asm-6.2.jar:/opt/scylladb/share/cassandra/lib/caffeine-2.2.6.jar:/opt/scylladb/share/cassandra/lib/chronicle-bytes-1.16.3.jar:/opt/scylladb/share/cassandra/lib/chronicle-core-1.16.3-SNAPSHOT.jar:/opt/scylladb/share/cassandra/lib/chronicle-queue-4.16.3.jar:/opt/scylladb/share/cassandra/lib/chronicle-threads-1.16.0.jar:/opt/scylladb/share/cassandra/lib/chronicle-wire-1.16.1.jar:/opt/scylladb/share/cassandra/lib/commons-cli-1.1.jar:/opt/scylladb/share/cassandra/lib/commons-codec-1.9.jar:/opt/scylladb/share/cassandra/lib/commons-lang3-3.1.jar:/opt/scylladb/share/cassandra/lib/commons-math3-3.2.jar:/opt/scylladb/share/cassandra/lib/compress-lzf-0.8.4.jar:/opt/scylladb/share/cassandra/lib/concurrent-trees-2.4.0.jar:/opt/scylladb/share/cassandra/lib/concurrentlinkedhashmap-lru-1.4.jar:/opt/scylladb/share/cassandra/lib/disruptor-3.0.1.jar:/opt/scylladb/share/cassandra/lib/ecj-4.6.1.jar:/opt/scylladb/share/cassandra/lib/guava-18.0.jar:/opt/scylladb/share/cassandra/lib/high-scale-lib-1.0.6.jar:/opt/scylladb/share/cassandra/lib/hppc-0.5.4.jar:/opt/scylladb/share/cassandra/lib/jackson-core-asl-1.9.13.jar:/opt/scylladb/share/cassandra/lib/jackson-mapper-asl-1.9.13.jar:/opt/scylladb/share/cassandra/lib/jamm-0.3.2.jar:/opt/scylladb/share/cassandra/lib/javax.inject.jar:/opt/scylladb/share/cassandra/lib/jbcrypt-0.3m.jar:/opt/scylladb/share/cassandra/lib/jcl-over-slf4j-1.7.7.jar:/opt/scylladb/share/cassandra/lib/jctools-core-1.2.1.jar:/opt/scylladb/share/cassandra/lib/jflex-1.6.0.jar:/opt/scylladb/share/cassandra/lib/jna-4.2.2.jar:/opt/scylladb/share/cassandra/lib/joda-time-2.4.jar:/opt/scylladb/share/cassandra/lib/json-simple-1.1.jar:/opt/scylladb/share/cassandra/lib/jstackjunit-0.0.1.jar:/opt/scylladb/share/cassandra/lib/libthrift-0.9.2.jar:/opt/scylladb/share/cassandra/lib/log4j-over-slf4j-1.7.7.jar:/opt/scylladb/share/cassandra/lib/logback-classic-1.1.3.jar:/opt/scylladb/share/cassandra/lib/logback-core-1.1.3.jar:/opt/scylladb/share/cassandra/lib/lz4-1.3.0.jar:/opt/scylladb/share/cassandra/lib/metrics-core-3.1.5.jar:/opt/scylladb/share/cassandra/lib/metrics-jvm-3.1.5.jar:/opt/scylladb/share/cassandra/lib/metrics-logback-3.1.5.jar:/opt/scylladb/share/cassandra/lib/netty-all-4.0.56.Final.jar:/opt/scylladb/share/cassandra/lib/ohc-core-0.5.1.jar:/opt/scylladb/share/cassandra/lib/ohc-core-j8-0.5.1.jar:/opt/scylladb/share/cassandra/lib/reporter-config-base-3.0.3.jar:/opt/scylladb/share/cassandra/lib/reporter-config3-3.0.3.jar:/opt/scylladb/share/cassandra/lib/scylla-driver-core-3.7.1-scylla-2-shaded.jar:/opt/scylladb/share/cassandra/lib/scylla-tools-4.3.0-0.20210110.000585522.jar:/opt/scylladb/share/cassandra/lib/sigar-1.6.4.jar:/opt/scylladb/share/cassandra/lib/slf4j-api-1.7.7.jar:/opt/scylladb/share/cassandra/lib/snakeyaml-1.11.jar:/opt/scylladb/share/cassandra/lib/snappy-java-1.1.1.7.jar:/opt/scylladb/share/cassandra/lib/snowball-stemmer-1.3.0.581.1.jar:/opt/scylladb/share/cassandra/lib/stream-2.5.2.jar:/opt/scylladb/share/cassandra/lib/stress.jar:/opt/scylladb/share/cassandra/lib/thrift-server-0.3.7.jar:/opt/scylladb/share/cassandra/*.jar:
```

**Comment by slivne** [comment]
Thanks amnon

@penberg moving it to your queue -

I know we had the temp directory and copied files in the past can't recall when/who removed that.

**Comment by slivne** [comment]
I think the offending commit is this one scylladb/scylla-tools-java@3eca0e35111f48629cf5b654dd5212199029f78e

@jul-stas - reassigning this to you - I think you did this change. 

If I'm missing something let me know - I think we simply need to add the additional directory to the path.

**Comment by slivne** [comment]
@penberg / @avikivity backport to 4.3 ,  4.4

**Comment by slivne** [comment]
@penberg / @avikivity ping on backport this is a regression

**Comment by slivne** [comment]
@avikivity / @penberg need this backported to 4.4, 4.3 its a regression

**Comment by avikivity** [comment]
@jul-stas I see it's a regression from 4.2 to 4.3 but I can't figure out how we regressed. Any idea what change triggered the regression?

**Comment by slivne** [comment]
@avikivity I think its this commit scylladb/scylla-tools-java@3eca0e3

**Comment by avikivity** [comment]
Backported to 4.3, 4.4. 4.5 was already safe.
