### ISSUE TITLE
Coredump when using UDF and C-S, TWCS compaction

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla#7977]
*Installation details*
Scylla version (or git commit hash): `4.3.0-0.20210110.000585522 with build-id 7fab6c35a5d403f3416292b37c9a9aa94fe4db1f`
Cluster size: 3 nodes (i3.2xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-09100abf6401dce3a` (aws: eu-west-1)

Test: `longevity-twcs-3h`
Test name: `longevity_twcs_test.TWCSLongevityTest.test_custom_time`
Test config file(s):
- [longevity-twcs-3h.yaml] (https://github.com/scylladb/scylla-cluster-tests/blob/6e9ba43585b8c60ecd0ca3798834a4f50d20d252/test-cases/longevity/longevity-twcs-3h.yaml)

**Issue description**
====================================
Coredump when using UDF and TWCS Compaction.

UDF:
```
            session.execute(f"CREATE KEYSPACE IF NOT EXISTS keyspace1"
                            f" WITH replication={{'class':'SimpleStrategy', 'replication_factor':{rf}}}")
            session.execute(f"USE keyspace1")
            session.execute(f"""CREATE OR REPLACE FUNCTION   minutesAgo(ago int, now bigint)
                            RETURNS NULL ON NULL INPUT
                            RETURNS bigint
                            LANGUAGE Lua
                            AS 'return now - 60000 * ago';""")
```
C-S 
```
table_definition: |

  CREATE TABLE twcstest (
  id text,

  time timestamp,

  metric int,

  value blob,

  PRIMARY KEY((id), time)

  ) WITH CLUSTERING ORDER BY (time DESC)

  AND compaction = { 'class':'TimeWindowCompactionStrategy', 'compaction_window_unit':'MINUTES', 'compaction_window_size':'1' }

  AND comment='A table to see what happens with TWCS & Stress'

columnspec:
  - name: id

    size: fixed(64)

    population: uniform(1..1500M)

  - name: time

    cluster: fixed(288)

  - name: value

    size: fixed(50)


queries:

  insert:

    cql: insert into twcstest (id, time, metric, value) VALUES (?, toTimestamp(now()), ?, ?)

  select5m:

    cql: select * from twcstest where id = ? and time <= toTimestamp(now()) and time >= minutesAgo(5, toTimestamp(now()))

  select10m:

    cql: select * from twcstest where id = ? and time <= toTimestamp(now()) and time >= minutesAgo(10, toTimestamp(now()))
```
BACKTRACE
```
backtrace=           PID: 2934 (scylla)
UID: 997 (scylla)
GID: 1001 (scylla)
Signal: 6 (ABRT)
Timestamp: Wed 2021-01-27 20:51:17 UTC (2min 30s ago)
Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-7 --lock-memory=1
Executable: /opt/scylladb/libexec/scylla
Control Group: /
Boot ID: adbbb8751f7146aabfcc4fd89fcf2adf
Machine ID: cc2c86fe566741e6a2ff6d399c5d5daa
Hostname: longevity-twcs-longevit-db-node-ed2cc02e-1
Coredump: /var/lib/systemd/coredump/core.scylla.997.adbbb8751f7146aabfcc4fd89fcf2adf.2934.1611780677000000
Message: Process 2934 (scylla) of user 997 dumped core.
Stack trace of thread 2939:
#0  0x00007f3e8231e9e5 raise (libc.so.6)
#1  0x00007f3e8230794d abort (libc.so.6)
#2  0x00007f3e82307769 __assert_fail_base.cold (libc.so.6)
#3  0x00007f3e82316e76 __assert_fail (libc.so.6)
#4  0x0000000002b01572 _ZN7seastar8internal11future_base7do_waitEv (scylla)
#5  0x0000000001517520 _ZN7seastar6futureISt8optionalINS_13basic_sstringIajLj31ELb0EEEEE4waitEv (scylla)
#6  0x000000000153a53e _ZN4cql39functions13function_call16execute_internalE24cql_serialization_formatRNS0_15scalar_functionESt6vectorISt8optionalIN7seastar13basic_sstringIajLj31ELb0EEEESaISA_EE (scylla)
#7  0x000000000153a88d _ZN4cql39functions13function_call12bind_and_getERKNS_13query_optionsE (scylla)
#8  0x0000000001513a69 _ZZZN4cql34expr19possible_lhs_valuesEPK17column_definitionRKSt7variantIJbNS0_11conjunctionENS0_15binary_operatorEEERKNS_13query_optionsEENKUlRKS6_E1_clESE_ENKUlRKNS0_12column_valueEE_clESI_ (scylla)
#9  0x0000000001514b3a __invoke_impl<std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const cql3::expr::column_value&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(cql3::expr::token)> >, const cql3::expr::column_value&> (scylla)
#10 0x0000000001500462 __do_visit<std::__detail::__variant::__deduce_visit_result<std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > > >, overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const cql3::expr::column_value&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(cql3::expr::token)> >, const std::variant<cql3::expr::column_value, std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >, cql3::expr::token>&> (scylla)
#11 0x00000000015008f8 __do_visit<std::__detail::__variant::__deduce_visit_result<std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > > >, overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(bool)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::conjunction&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)> >, const std::variant<bool, cql3::expr::conjunction, cql3::expr::binary_operator>&> (scylla)
#12 0x0000000001503243 __do_visit<std::__detail::__variant::__deduce_visit_result<std::variant<std::vector<seastar::
download_instructions=gsutil cp gs://upload.scylladb.com/core.scylla.997.adbbb8751f7146aabfcc4fd89fcf2adf.2934.1611780677000000/core.scylla.997.adbbb8751f7146aabfcc4fd89fcf2adf.2934.1611780677000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.997.adbbb8751f7146aabfcc4fd89fcf2adf.2934.1611780677000000.gz
```
====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor ed2cc02e-c0f8-4e59-955e-945fdaf577f0`
Show all stored logs command: `$ hydra investigate show-logs ed2cc02e-c0f8-4e59-955e-945fdaf577f0`

Test id: `ed2cc02e-c0f8-4e59-955e-945fdaf577f0`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_210940/grafana-screenshot-longevity-twcs-3h-scylla-per-server-metrics-nemesis-20210127_211328-longevity-twcs-longevit-monitor-node-ed2cc02e-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_210940/grafana-screenshot-longevity-twcs-3h-scylla-per-server-metrics-nemesis-20210127_211328-longevity-twcs-longevit-monitor-node-ed2cc02e-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_210940/grafana-screenshot-overview-20210127_210940-longevity-twcs-longevit-monitor-node-ed2cc02e-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_210940/grafana-screenshot-overview-20210127_210940-longevity-twcs-longevit-monitor-node-ed2cc02e-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_211754/grafana-screenshot-longevity-twcs-3h-scylla-per-server-metrics-nemesis-20210127_212110-longevity-twcs-longevit-monitor-node-ed2cc02e-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_211754/grafana-screenshot-longevity-twcs-3h-scylla-per-server-metrics-nemesis-20210127_212110-longevity-twcs-longevit-monitor-node-ed2cc02e-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_211754/grafana-screenshot-overview-20210127_211754-longevity-twcs-longevit-monitor-node-ed2cc02e-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_211754/grafana-screenshot-overview-20210127_211754-longevity-twcs-longevit-monitor-node-ed2cc02e-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_212543/db-cluster-ed2cc02e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_212543/db-cluster-ed2cc02e.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_212543/loader-set-ed2cc02e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_212543/loader-set-ed2cc02e.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_212543/monitor-set-ed2cc02e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_212543/monitor-set-ed2cc02e.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_212543/sct-runner-ed2cc02e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ed2cc02e-c0f8-4e59-955e-945fdaf577f0/20210127_212543/sct-runner-ed2cc02e.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/shoshan/job/longevity-twcs-3h/10/)

**Comment by roydahan** [comment]
@shoshan please find the backtrace, decode it and add it here.
@bhalevy In case you're interested (we haven't started testing UDF, but tried using it).

**Comment by bhalevy** [comment]
Hmm, need to look at the crash.  If you have a coredump it would be even better.

That said, we don't support the use of UDFs in the WHERE clause yet.
This is #5607

Does the above scenario work against Cassandra?

**Comment by shoshan** [comment]
@bhalevy coredump is huge 20GB,  can be accessed via gce console https://storage.cloud.google.com/upload.scylladb.com/core.scylla.997.adbbb8751f7146aabfcc4fd89fcf2adf.2934.1611780677000000/core.scylla.997.adbbb8751f7146aabfcc4fd89fcf2adf.2934.1611780677000000.gz

**Comment by bhalevy** [comment]
> @bhalevy coredump is huge 20GB, can be accessed via gce console https://storage.cloud.google.com/upload.scylladb.com/core.scylla.997.adbbb8751f7146aabfcc4fd89fcf2adf.2934.1611780677000000/core.scylla.997.adbbb8751f7146aabfcc4fd89fcf2adf.2934.1611780677000000.gz

Thanks.  By the way, this isn't huge at all :)
We have core dumps of well over 100GB from the largest AWS machines we use...

**Comment by bhalevy** [comment]
```
(gdb) bt
#0  0x00007f3e8231e9e5 in raise () from /downloads/7977/scylla/libreloc/libc.so.6
#1  0x00007f3e8230794d in abort () from /downloads/7977/scylla/libreloc/libc.so.6
#2  0x00007f3e82307769 in __assert_fail_base.cold () from /downloads/7977/scylla/libreloc/libc.so.6
#3  0x00007f3e82316e76 in __assert_fail () from /downloads/7977/scylla/libreloc/libc.so.6
#4  0x0000000002b01572 in seastar::internal::future_base::do_wait (this=0x7f3e7edd2f00) at ./seastar/src/core/future.cc:246
#5  seastar::internal::future_base::do_wait (this=this@entry=0x7f3e7edd2f00) at ./seastar/src/core/future.cc:246
#6  0x0000000001517520 in seastar::future<std::optional<seastar::basic_sstring<signed char, unsigned int, 31u, false> > >::wait (this=0x7f3e7edd2f00) at /usr/include/c++/10/ext/new_allocator.h:120
#7  seastar::future<std::optional<seastar::basic_sstring<signed char, unsigned int, 31u, false> > >::get (this=0x7f3e7edd2f00) at ./seastar/include/seastar/core/future.hh:1441
#8  seastar::future<std::optional<seastar::basic_sstring<signed char, unsigned int, 31u, false> > >::get0 (this=0x7f3e7edd2f00) at ./seastar/include/seastar/core/future.hh:1463
#9  cql3::functions::user_function::execute (this=0x60400073cc10, sf=..., parameters=...) at cql3/functions/user_function.cc:60
#10 0x000000000153a53e in cql3::functions::function_call::execute_internal (sf=..., fun=..., params=...) at cql3/functions/functions.cc:458
#11 0x000000000153a88d in cql3::functions::function_call::bind_and_get (this=0x604000752e40, options=...) at ./cql3/query_options.hh:215
#12 0x0000000001513a69 in operator() (__closure=0x7f3e7edd32a0, col=...) at ./seastar/include/seastar/core/shared_ptr.hh:579
#13 0x0000000001514b3a in std::__invoke_impl<std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const cql3::expr::column_value&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(cql3::expr::token)> >, const cql3::expr::column_value&> (__f=...) at /usr/include/c++/10/bits/invoke.h:89
#14 std::__invoke<overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const cql3::expr::column_value&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(cql3::expr::token)> >, const cql3::expr::column_value&> (__fn=...) at /usr/include/c++/10/bits/invoke.h:96
#15 std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > > > (*)(overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const cql3::expr::column_value&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(cql3::expr::token)> >&&, const std::variant<cql3::expr::column_value, std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >, cql3::expr::token>&)>, std::integer_sequence<long unsigned int, 0> >::__visit_invoke(overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const cql3::expr::column_value&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(cql3::expr::token)> > &&, const std::variant<cql3::expr::column_value, std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >, cql3::expr::token> &) (__visitor=..., __vars#0=...) at /usr/include/c++/10/variant:1014
#16 0x0000000001500462 in std::__do_visit<std::__detail::__variant::__deduce_visit_result<std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > > >, overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const cql3::expr::column_value&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(cql3::expr::token)> >, const std::variant<cql3::expr::column_value, std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >, cql3::expr::token>&> (__visitor=...) at /usr/include/c++/10/variant:1688
#17 std::visit<overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const cql3::expr::column_value&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(const std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)>::<lambda(cql3::expr::token)> >, const std::variant<cql3::expr::column_value, std::vector<cql3::expr::column_value, std::allocator<cql3::expr::column_value> >, cql3::expr::token>&> (__visitor=...) at /usr/include/c++/10/variant:1711
#18 operator() (oper=..., __closure=<optimized out>) at cql3/expr/expression.cc:750
#19 std::__invoke_impl<std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(bool)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::conjunction&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)> >, const cql3::expr::binary_operator&> (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#20 std::__invoke<overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(bool)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::conjunction&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)> >, const cql3::expr::binary_operator&> (__fn=...) at /usr/include/c++/10/bits/invoke.h:96
#21 std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > > > (*)(overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(bool)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::conjunction&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)> >&&, const std::variant<bool, cql3::expr::conjunction, cql3::expr::binary_operator>&)>, std::integer_sequence<long unsigned int, 2> >::__visit_invoke(overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(bool)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::conjunction&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)> > &&, const std::variant<bool, cql3::expr::conjunction, cql3::expr::binary_operator> &) (__visitor=..., __vars#0=...) at /usr/include/c++/10/variant:1014
#22 0x00000000015008f8 in std::__do_visit<std::__detail::__variant::__deduce_visit_result<std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > > >, overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(bool)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::conjunction&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)> >, const std::variant<bool, cql3::expr::conjunction, cql3::expr::binary_operator>&> (__visitor=...) at /usr/include/c++/10/variant:1688
#23 std::visit<overloaded_functor<cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(bool)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::conjunction&)>, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::binary_operator&)> >, const std::variant<bool, cql3::expr::conjunction, cql3::expr::binary_operator>&> (__visitor=...) at /usr/include/c++/10/variant:1711
#24 cql3::expr::possible_lhs_values (options=..., expr=..., cdef=<optimized out>) at cql3/expr/expression.cc:752
#25 operator() (child=..., acc=..., __closure=<synthetic pointer>) at cql3/expr/expression.cc:672
#26 std::accumulate<__gnu_cxx::__normal_iterator<const std::variant<bool, cql3::expr::conjunction, cql3::expr::binary_operator>*, std::vector<std::variant<bool, cql3::expr::conjunction, cql3::expr::binary_operator> > >, std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::conjunction&)>::<lambda(const value_set&, const expression&)> > (__binary_op=..., __init=..., __last=..., __first=...) at /usr/include/c++/10/bits/stl_numeric.h:169
#27 boost::accumulate<std::vector<std::variant<bool, cql3::expr::conjunction, cql3::expr::binary_operator> >, std::variant<std::vector<seastar::basic_sstring<signed char, unsigned int, 31, false>, std::allocator<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, nonwrapping_interval<seastar::basic_sstring<signed char, unsigned int, 31, false> > >, cql3::expr::possible_lhs_values(const column_definition*, const expression&, const cql3::query_options&)::<lambda(const cql3::expr::conjunction&)>::<lambda(const value_set&, const expression&)> > (op=..., init=..., rng=...) at /usr/include/boost/range/numeric.hpp:54
#28 operator() (conj=..., __closure=<optimized out>) at cql3/expr/expression.cc:673
```

**Comment by bhalevy** [comment]
Ah, apparently this is not called in a seastar thread
```
longevity-twcs-longevit-db-node-ed2cc02e-1/messages.log:2021-01-27T20:51:17+00:00  longevity-twcs-longevit-db-node-ed2cc02e-1 !INFO    | scylla: scylla: ./seastar/src/core/future.cc:248: void seastar::internal::future_base::do_wait(): Assertion `thread' failed.
longevity-twcs-longevit-db-node-ed2cc02e-3/messages.log:2021-01-27T20:51:17+00:00  longevity-twcs-longevit-db-node-ed2cc02e-3 !INFO    | scylla: scylla: ./seastar/src/core/future.cc:248: void seastar::internal::future_base::do_wait(): Assertion `thread' failed.
```

**Comment by avikivity** [comment]
UDF is experimental, so not backporting.

**Comment by avikivity** [comment]
Well, you replaced the core dump with an internal error, but the query still fails.

**Comment by nyh** [comment]
> Well, you replaced the core dump with an internal error, but the query still fails.

Yes, looks like https://github.com/scylladb/scylladb/issues/13746 ?
