### ISSUE TITLE
consistency_test: short_read_reversed_test: Expecting value5, got value4

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8000]
Regression started in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/729/testReport/consistency_test/TestConsistency/short_read_reversed_test/
Scylla version a1f93e42972df729c899c4e6ef3653f101c806dd

```
Error Message

Expecting value5, got value4 ([Row(c='c000004', v='value4'), Row(c='c000005', v='value5'), Row(c='c000004', v='value4')])

Stacktrace

Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/consistency_test.py", line 998, in short_read_reversed_test
    5 - i), 'Expecting value%d, got %s (%s)' % (5 - i, res[i][1], str(res))
AssertionError: Expecting value5, got value4 ([Row(c='c000004', v='value4'), Row(c='c000005', v='value5'), Row(c='c000004', v='value4')])
```

Bisected to aec231ba2eb70ce3eedd4fea0acf1ef9ff833641

**Comment by bhalevy** [comment]
This causes another regression: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/729/testReport/thrift_tests/TestMutations/test_get_range_slice/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/thrift_tests.py", line 1493, in test_get_range_slice
    assert result[0].columns[0].column.name == b'col4'
AssertionError
```

Note that this test is much faster to run, either successfully or not.

**Comment by denesb** [comment]
Investigating...

**Comment by denesb** [comment]
The `mutation::consume()` that I added in https://github.com/scylladb/scylla/commit/aec231ba2eb70ce3eedd4fea0acf1ef9ff833641 doesn't support reverse consumption, so results are sent in the wrong order for reverse queries.

**Comment by avikivity** [comment]
No vulnerable branches, so no backports.
