### ISSUE TITLE
perftune failing on Ubuntu 20.04LTS AMI

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#8041]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 338c190842d52e8da5345c027b3df4f1a66a3a5a
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI, Ubuntu 20.04 LTS  (ami-0885b1f6bd170450c)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):  i3en.2xlarge
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

```
ubuntu@ip-10-0-0-180:~$ sudo /opt/scylladb/scripts/scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup --no-ec2-check --no-swap-setup

(skip output since it's unrelated)

ubuntu@ip-10-0-0-180:~$ sudo /opt/scylladb/scripts/scylla_sysconfig_setup --nic ens5 --setup-nic

ubuntu@ip-10-0-0-180:~$ sudo systemctl start scylla-server.service
Job for scylla-server.service failed because the control process exited with error code.
See "systemctl status scylla-server.service" and "journalctl -xe" for details.

ubuntu@ip-10-0-0-180:~$ journalctl -xe|grep "scylla_prepare\["
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7845]: Traceback (most recent call last):
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7845]:   File "/opt/scylladb/scripts/libexec/perftune.py", line 1389, in <module>
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7845]:     parse_options_file(args)
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7845]:   File "/opt/scylladb/scripts/libexec/perftune.py", line 1334, in parse_options_file
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7845]:     prog_args.nics = extend_and_unique(prog_args.nics, y['nic'])
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7845]:   File "/opt/scylladb/scripts/libexec/perftune.py", line 1312, in extend_and_unique
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7845]:     return list(set(orig_list))
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7845]: TypeError: 'NoneType' object is not iterable
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7827]: Exception occurred while creating perftune.yaml: Command '/opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --options-file /etc/scylla.d/perftune.yaml' returned non-zero exit status 1.
Feb 05 00:57:33 ip-10-0-0-180 scylla_prepare[7827]: To fix the error, please re-run scylla_setup.

ubuntu@ip-10-0-0-180:~$ cat /etc/scylla.d/perftune.yaml 
cpu_mask: '0x000000ff'
mode: mq
nic:
- ens5
tune:
- net

ubuntu@ip-10-0-0-180:~$ sudo cat /etc/default/scylla-server 
# choose following mode: virtio, dpdk, posix
NETWORK_MODE=posix

# tap device name(virtio)
TAP=tap0

# bridge device name (virtio)
BRIDGE=virbr0

# ethernet device name
IFNAME="ens5"

# setup NIC's and disks' interrupts, RPS, XPS, nomerges and I/O scheduler (posix)
SET_NIC_AND_DISKS="yes"

# tune clocksource
SET_CLOCKSOURCE=no

# ethernet device driver (dpdk)
ETHDRV=

# ethernet device PCI ID (dpdk)
ETHPCIID=

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=scylla

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/var/lib/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix"

## scylla arguments (for dpdk mode)
#SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack native --dpdk-pmd"

# setup as AMI instance
AMI=no

```

**Comment by tarzanek** [comment]
@amoskong isn't this the https://github.com/scylladb/scylla/issues/8008
@syuu1228 do you have the fixes from above?

**Comment by tarzanek** [comment]
(I'd close as dup of https://github.com/scylladb/scylla/issues/8008 , but verify first if the patch fixes your prob @syuu1228 Takuya )

**Comment by syuu1228** [comment]
Closing since it looks like duplicate of #8008

**Comment by amoskong** [comment]
> Closing since it looks like duplicate of #8008

Yes, it's duplicated. and had been fixed in master:

https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2004-test/

![Screenshot from 2021-02-07 15-57-43](https://user-images.githubusercontent.com/309708/107140488-41b22100-695d-11eb-80d6-75ac3aad890d.png)
