### ISSUE TITLE
dist: aws_instance.ephemeral_disks() returns rootfs partition 

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#8055]
While testing Ubuntu 20.04 AMI (scylladb/scylla-machine-image#96), I found that scylla_create_devices failed at following error:
```
ubuntu@ip-10-0-0-52:~$ sudo /opt/scylladb/scylla-machine-image/scylla_create_devices
/dev/nvme0n1 is busy
Traceback (most recent call last):
  File "/home/ubuntu/scylla_create_devices", line 76, in <module>
    create_raid(disk_devices)
  File "/home/ubuntu/scylla_create_devices", line 33, in create_raid
    run(["/opt/scylladb/scripts/scylla_raid_setup", "--raiddev", "/dev/md0", "--disks", ",".join(devices),
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_raid_setup', '--raiddev', '/dev/md0', '--disks', '/dev/nvme2n1,/dev/nvme0n1,/dev/nvme4n1,/dev/nvme1n1,/dev/nvme3n1', '--root', '/var/lib/scylla', '--volume-role', 'all', '--update-fstab']' returned non-zero exit status 1.
```

And it looks like because aws_instance.ephemeral_disks() mistakenly includes rootfs partition, so the RAID creation failed.

**Comment by avikivity** [comment]
Backported to 4.2, 4.3, 4.4.
