### ISSUE TITLE
scylla AMI 0.15 fail to boot

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#806]
When launching ami-45c69e2f on us-east, scylla fail to boot, and a core dump was created.

Log
```
$ journalctl _COMM=scylla
-- Logs begin at Thu 2015-09-17 10:42:15 UTC, end at Sun 2016-01-17 08:43:41 UTC. --
Jan 17 08:29:10 ip-10-186-57-10 scylla[990]: EAL: TSC frequency is ~2793268 KHz
Jan 17 08:29:10 ip-10-186-57-10 scylla[990]: EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
Jan 17 08:29:10 ip-10-186-57-10 scylla[990]: EAL: Master lcore 0 is ready (tid=3184b4c0;cpuset=[0])
Jan 17 08:29:10 ip-10-186-57-10 scylla[990]: EAL: lcore 3 is ready (tid=24d1b700;cpuset=[3])
Jan 17 08:29:10 ip-10-186-57-10 scylla[990]: EAL: lcore 2 is ready (tid=2551c700;cpuset=[2])
Jan 17 08:29:10 ip-10-186-57-10 scylla[990]: EAL: lcore 1 is ready (tid=25d1d700;cpuset=[1])
Jan 17 08:29:10 ip-10-186-57-10 scylla[990]:  [shard 0] config - Option partitioner is not (yet) used.
Jan 17 08:29:11 ip-10-186-57-10 scylla[990]:  [shard 0] database - Row: max_vector_size: 32, internal_count: 5
Jan 17 08:29:11 ip-10-186-57-10 scylla[990]:  [shard 2] database - Row: max_vector_size: 32, internal_count: 5
Jan 17 08:29:11 ip-10-186-57-10 scylla[990]:  [shard 1] database - Row: max_vector_size: 32, internal_count: 5
Jan 17 08:29:11 ip-10-186-57-10 audit[1014]: <audit-1701> auid=4294967295 uid=995 gid=1001 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 pid=1014 comm="scylla" exe="/usr
```

coredump
```
#0  shared_ptr (x=..., this=0x7fc225d16380) at /usr/src/debug/scylla-server-0.15/seastar/core/shared_ptr.hh:361
#1  seastar::sharded<streaming::stream_manager>::get_local_service (this=0x1c587f0 <streaming::_the_stream_manager>) at /usr/src/debug/scylla-server-0.15/seastar/core/sharded.hh:317
#2  0x00000000011c849f in operator() (__closure=<optimized out>) at /usr/src/debug/scylla-server-0.15/seastar/core/sharded.hh:222
#3  futurize<std::vector<httpd::stream_manager_json::stream_state, std::allocator<httpd::stream_manager_json::stream_state> > >::apply<seastar::sharded<Service>::map_reduce0(Mapper, Initial, Reduce)::<lambda(unsigned int)> [with Mapper = api::set_stream_manager(api::http_context&, httpd::routes&)::<lambda(std::unique_ptr<httpd::request>)>::<lambda(streaming::stream_manager&)>; Initial = std::vector<httpd::stream_manager_json::stream_state>; Reduce = std::vector<httpd::stream_manager_json::stream_state> (*)(std::vector<httpd::stream_manager_json::stream_state>, std::vector<httpd::stream_manager_json::stream_state>&&); Service = streaming::stream_manager]::<lambda()>&>((anonymous namespace)::sharded<streaming::stream_manager>::<lambda(unsigned int)>::<lambda()> &) (func=...) at /usr/src/debug/scylla-server-0.15/seastar/core/future.hh:1127
#4  0x00000000011c96a8 in submit_to<seastar::sharded<Service>::map_reduce0(Mapper, Initial, Reduce)::<lambda(unsigned int)> [with Mapper = api::set_stream_manager(api::http_context&, httpd::routes&)::<lambda(std::unique_ptr<httpd::request>)>::<lambda(streaming::stream_manager&)>; Initial = std::vector<httpd::stream_manager_json::stream_state>; Reduce = std::vector<httpd::stream_manager_json::stream_state> (*)(std::vector<httpd::stream_manager_json::stream_state>, std::vector<httpd::stream_manager_json::stream_state>&&); Service = streaming::stream_manager]::<lambda()> > (func=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x10d5eb18, DIE 0x10febf29>, t=1) at /usr/src/debug/scylla-server-0.15/seastar/core/reactor.hh:926
#5  operator() (__closure=<synthetic pointer>, c=1) at /usr/src/debug/scylla-server-0.15/seastar/core/sharded.hh:225
#6  map_reduce<boost::range_detail::integer_iterator<unsigned int>, seastar::sharded<Service>::map_reduce0(Mapper, Initial, Reduce) [with Mapper = api::set_stream_manager(api::http_context&, httpd::routes&)::<lambda(std::unique_ptr<httpd::request>)>::<lambda(streaming::stream_manager&)>; Initial = std::vector<httpd::stream_manager_json::stream_state>; Reduce = std::vector<httpd::stream_manager_json::stream_state> (*)(std::vector<httpd::stream_manager_json::stream_state>, std::vector<httpd::stream_manager_json::stream_state>&&); Service = streaming::stream_manager]::<lambda(unsigned int)>, std::vector<httpd::stream_manager_json::stream_state>, std::vector<httpd::stream_manager_json::stream_state> (*)(std::vector<httpd::stream_manager_json::stream_state>, std::vector<httpd::stream_manager_json::stream_state>&&)> (
    reduce=0x11d0e30 <api::concat<httpd::stream_manager_json::stream_state>(std::vector<httpd::stream_manager_json::stream_state, std::allocator<httpd::stream_manager_json::stream_state> >, std::vector<httpd::stream_manager_json::stream_state, std::allocator<httpd::stream_manager_json::stream_state> >&&)>, 
    initial=<error reading variable: access outside bounds of object referenced via synthetic pointer>, mapper=<synthetic pointer>, end=..., begin=...)
    at /usr/src/debug/scylla-server-0.15/seastar/core/future-util.hh:588
#7  map_reduce0<api::set_stream_manager(api::http_context&, httpd::routes&)::<lambda(std::unique_ptr<httpd::request>)>::<lambda(streaming::stream_manager&)>, std::vector<httpd::stream_manager_json::stream_state>, std::vector<httpd::stream_manager_json::stream_state> (*)(std::vector<httpd::stream_manager_json::stream_state>, std::vector<httpd::stream_manager_json::stream_state>&&)> (this=<optimized out>, 
    reduce=0x11d0e30 <api::concat<httpd::stream_manager_json::stream_state>(std::vector<httpd::stream_manager_json::stream_state, std::allocator<httpd::stream_manager_json::stream_state> >, std::vector<httpd::stream_manager_json::stream_state, std::allocator<httpd::stream_manager_json::stream_state> >&&)>, 
    initial=<error reading variable: access outside bounds of object referenced via synthetic pointer>, map=...) at /usr/src/debug/scylla-server-0.15/seastar/core/sharded.hh:229
#8  operator() (__closure=<optimized out>, req=...) at api/stream_manager.cc:88
#9  std::_Function_handler<future<json::json_return_type>(std::unique_ptr<httpd::request, std::default_delete<httpd::request> >), api::set_stream_manager(api::http_context&, httpd::routes&)::<lambda(std::unique_ptr<httpd::request, std::default_delete<httpd::request> >)> >::_M_invoke(const std::_Any_data &, <unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x10d5eb18, DIE 0x10ff1d8b>) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/5.3.1/functional:1857
#10 0x00000000005bbfb5 in operator() (__args#0=std::unique_ptr<httpd::request> containing 0x7fc225d16710, this=<optimized out>) at /usr/include/c++/5.3.1/functional:2271
#11 operator() (rep=..., req=..., __closure=<optimized out>) at http/function_handlers.hh:92
#12 std::_Function_handler<future<std::unique_ptr<httpd::reply, std::default_delete<httpd::reply> > > (std::unique_ptr<httpd::request, std::default_delete<httpd::request> >, std::unique_ptr<httpd::reply, std::default_delete<httpd::reply> >), httpd::function_handler::function_handler(std::function<future<json::json_return_type> (std::unique_ptr<httpd::request, std::default_delete<httpd::request> >)> const&)::{lambda(std::unique_ptr<httpd::request, std::default_delete<httpd::request> >, std::unique_ptr<httpd::reply, std::default_delete<httpd::reply> >)#1}>::_M_invoke(std::_Any_data const&, std::unique_ptr<httpd::request, std::default_delete<httpd::request> >&&, std::unique_ptr<httpd::reply, std::default_delete<httpd::reply> >&&) (
    __functor=..., __args#0=<optimized out>, __args#1=<optimized out>) at /usr/include/c++/5.3.1/functional:1857
#13 0x00000000005be05d in operator() (__args#1=std::unique_ptr<httpd::reply> containing 0x7fc225d16780, __args#0=std::unique_ptr<httpd::request> containing 0x7fc225d16770, 
    this=<optimized out>) at /usr/include/c++/5.3.1/functional:2271
#14 httpd::function_handler::handle (this=<optimized out>, path=..., req=..., rep=...) at http/function_handlers.hh:102
#15 0x00000000005cb866 in httpd::routes::handle (this=0x603000135bf8, path=..., req=std::unique_ptr<httpd::request> containing 0x0, rep=std::unique_ptr<httpd::reply> containing 0x0)
    at http/routes.cc:91
#16 0x00000000006e215f in httpd::http_server::connection::generate_reply (this=0x603000012200, req=std::unique_ptr<httpd::request> containing 0x0)
    at /usr/src/debug/scylla-server-0.15/seastar/http/httpd.hh:355
#17 0x00000000006e2666 in operator() (__closure=<optimized out>) at /usr/src/debug/scylla-server-0.15/seastar/http/httpd.hh:189
#18 apply (args=<optimized out>, func=<optimized out>) at /usr/src/debug/scylla-server-0.15/seastar/core/apply.hh:34
#19 apply<httpd::http_server::connection::read_one()::<lambda()> mutable::<lambda()> > (args=<optimized out>, func=<optimized out>)
```

**Comment by slivne** [comment]
fixed by b1845cddeceaa5a84509b1827243bbf472b669ba
