### ISSUE TITLE
test_dates_type_group may fail because of timeuuid sort order incompatibility

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8107]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release-parallel/32/testReport/cql_group_functions_tests/TestGroupFunctions/Run_Dtest_Parallel_Cloud_Machines___FullDtest___split054___test_dates_type_group/
scylla-dtest version edd1beb936028b98e234153cc6a6d8e644d59235
scylla version scylladb/scylla@495b7b5596ab5f2bd1f1149f5b56c0e550716f79
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release-parallel/scylla-dtest/cql_group_functions_tests.py", line 107, in test_dates_type_group
    single_type=single_type)
  File "/jenkins/workspace/scylla-master/dtest-release-parallel/scylla-dtest/cql_group_functions_tests.py", line 74, in create_tables_and_run_group_functions
    self.check_results(session=session, table_name=table_name, single_type=single_type)
  File "/jenkins/workspace/scylla-master/dtest-release-parallel/scylla-dtest/cql_group_functions_tests.py", line 48, in check_results
    cl=ConsistencyLevel.QUORUM)
  File "/jenkins/workspace/scylla-master/dtest-release-parallel/scylla-dtest/dtest.py", line 1643, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release-parallel/scylla-dtest/assertions.py", line 68, in assert_one
    assert list_res == [expected], "Expected %s from %s, but got %s" % ([expected], query, list_res)
AssertionError: Expected [[UUID('00000100-7024-11eb-9812-0242ac110002')]] from select min(my_timeuuid) from all_types, but got [[UUID('fc2109b2-7023-11eb-9812-0242ac110002')]]
```

Looks like time the timeuuid expected results list is sorted lexicographically, which it shouldn't.
See 5ab6600f53a53a64436fdb89012d89739de99352 / scylladb/scylla#7956

**Comment by bhalevy** [comment]
@fgelcer you're the author of this test, can you please look into it?
/cc @kostja

**Comment by bhalevy** [comment]
sorry, wrong repository.
will open in scylla-dtest...

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylla-dtest/issues/1963
