### ISSUE TITLE
After running "CorruptThenRebuildMonkey" nemesis, Scylla failed to start

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla#8109]
*Installation details*
Scylla version (or git commit hash): `4.5.dev-0.20210211.718976e79`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (gce: eu-west-1)

Test: `longevity-10gb-3h-GCE-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fbdb9b807f3dd592124b00f788f51ccd233df6c6/test-cases/longevity/longevity-10gb-3h.yaml)

**Issue description**

====================================
When running the `CorruptThenRebuildMonkey` nemesis, the node failed to start.

The `CorruptThenRebuildMonkey` steps:
* Stop node
* Select 5 random data files (that non-system files)
* Start Scylla (in this point the test failed)

The following nodes (`node1`, `node2`, `node5`, `node7` and `node8`) are not starting after 

```
2021-02-15 12:40:59.562: (ClusterHealthValidatorEvent Severity.CRITICAL): type=NodeStatus node=longevity-10gb-3h-master-db-node-4ccb00f6-0-1 error=Current node 10.142.0.37. Node with 10.142.0.54 (SisyphusMonkey nemesis target node) status is DN
2021-02-15 12:41:19.245: (ClusterHealthValidatorEvent Severity.CRITICAL): type=NodeStatus node=longevity-10gb-3h-master-db-node-4ccb00f6-0-2 error=Current node 10.142.0.46. Node with 10.142.0.54 (SisyphusMonkey nemesis target node) status is DN
2021-02-15 12:41:38.566: (ClusterHealthValidatorEvent Severity.CRITICAL): type=NodeStatus node=longevity-10gb-3h-master-db-node-4ccb00f6-0-5 error=Current node 10.142.0.53. Node with 10.142.0.54 (SisyphusMonkey nemesis target node) status is DN
2021-02-15 12:43:37.507: (ClusterHealthValidatorEvent Severity.CRITICAL): type=NodeStatus node=longevity-10gb-3h-master-db-node-4ccb00f6-0-7 error=Current node 10.142.0.62. Node with 10.142.0.54 (SisyphusMonkey nemesis target node) status is DN
2021-02-15 12:43:56.230: (ClusterHealthValidatorEvent Severity.CRITICAL): type=NodeStatus node=longevity-10gb-3h-master-db-node-4ccb00f6-0-8 error=Current node 10.142.0.63. Node with 10.142.0.54 (SisyphusMonkey nemesis target node) status is DN
```

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c`
Show all stored logs command: `$ hydra investigate show-logs 4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c`

Test id: `4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c/20210215_125933/db-cluster-4ccb00f6.zip](https://cloudius-jenkins-test.s3.amazonaws.com/4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c/20210215_125933/db-cluster-4ccb00f6.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c/20210215_125933/loader-set-4ccb00f6.zip](https://cloudius-jenkins-test.s3.amazonaws.com/4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c/20210215_125933/loader-set-4ccb00f6.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c/20210215_125933/monitor-set-4ccb00f6.zip](https://cloudius-jenkins-test.s3.amazonaws.com/4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c/20210215_125933/monitor-set-4ccb00f6.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c/20210215_125933/sct-runner-4ccb00f6.zip](https://cloudius-jenkins-test.s3.amazonaws.com/4ccb00f6-0a5c-4f38-97f5-9c6da7ec7e0c/20210215_125933/sct-runner-4ccb00f6.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-GCE-test/9/)

**Comment by slivne** [comment]
We need more info - from the node that did not start - can you extract what was written on that node when it attempted to start (that should clarify why it could not start)

**Comment by Orenef11** [comment]
> We need more info - from the node that did not start - can you extract what was written on that node when it attempted to start (that should clarify why it could not start)

I upgraded the bug description

**Comment by Orenef11** [comment]
@slivne 
My last comment did not exactly explain the source of the problem, I will try to describe what happened during this time period.
The `CorruptThenRebuild` nemesis ran on `node6` at `2021-02-15 12:18:38` until `2021-02-15 12:40:35`.

At `2021-02-15 12:18:38` Scylla execute the following cmd `/bin/systemctl stop` 
```
2021-02-15T12:18:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !NOTICE  | sudo[18847]: scylla-test : TTY=unknown ; PWD=/home/scylla-test ; USER=root ; COMMAND=/bin/systemctl stop│
│2021-02-15T12:18:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !DEBUG   | sudo[18847]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slic│
│2021-02-15T12:18:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | sudo[18847]: pam_unix(sudo:session): session opened for user root by (uid=0)                            │
│2021-02-15T12:18:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | systemd[1]: scylla-housekeeping-restart.timer: Succeeded.                                               │
│2021-02-15T12:18:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | systemd[1]: Stopped Run Scylla Housekeeping restart mode.                                               │
│2021-02-15T12:18:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | systemd[1]: scylla-housekeeping-daily.timer: Succeeded.                                                 │
│2021-02-15T12:18:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | systemd[1]: Stopped Run Scylla Housekeeping daily mode.                                                 │
│2021-02-15T12:18:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | systemd[1]: Stopping Scylla JMX...                                                                      │
│2021-02-15T12:18:39+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !NOTICE  | systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=143/n/a
```

At `2021-02-15T12:33:39` - After exactly 5 minutes, there was a timeout error because Scylla was not stopped
```
│2021-02-15T12:33:39+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !WARNING | systemd[1]: scylla-server.service: State 'stop-sigterm' timed out. Killing.                      │
│2021-02-15T12:33:39+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !NOTICE  | systemd[1]: scylla-server.service: Killing process 3643 (scylla) with signal SIGKILL.            │
│2021-02-15T12:33:55+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !NOTICE  | sudo[20111]: scylla-test : TTY=unknown ; PWD=/home/scylla-test ; USER=root ; COMMAND=/bin/coredum│
│2021-02-15T12:33:55+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !DEBUG   | sudo[20111]: pam_systemd(sudo:session): Cannot create session: Already running in a session or us│
│2021-02-15T12:33:55+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | sudo[20111]: pam_unix(sudo:session): session opened for user root by (uid=0)                     │
│2021-02-15T12:33:55+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | sudo[20111]: pam_unix(sudo:session): session closed for user root                                │
│2021-02-15T12:34:25+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !NOTICE  | sudo[20144]: scylla-test : TTY=unknown ; PWD=/home/scylla-test ; USER=root ; COMMAND=/bin/coredum│
│2021-02-15T12:34:25+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !DEBUG   | sudo[20144]: pam_systemd(sudo:session): Cannot create session: Already running in a session or us│
│2021-02-15T12:34:25+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | sudo[20144]: pam_unix(sudo:session): session opened for user root by (uid=0)                     │
│2021-02-15T12:34:25+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | sudo[20144]: pam_unix(sudo:session): session closed for user root                                │
│2021-02-15T12:34:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !WARNING | systemd[1]: scylla-server.service: Main process exited, code=killed, status=9/KILL               │
│2021-02-15T12:34:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !WARNING | systemd[1]: scylla-server.service: Failed with result 'timeout'.   
```

At `2021-02-15T12:34:38+00:00`: The node starts the Scylla 
```
│2021-02-15T12:34:38+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | systemd[1]: Starting Scylla Server...                                                            │

```

At `2021-02-15T12:35:40+00:00` - One mins and 2 seconds after Scylla start, the following error raised: `init - Startup failed: seastar::rpc::timeout_error (rpc call timed out)`
```
astar::rpc::timeout_error (rpc call timed out)                                            │
2021-02-15T12:35:40+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !ERR     | scylla[20191]: [shard 0]  │
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | sshd[20617]: Invalid user ubuntu from 122.51.83.195 port 49010                                   │
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | systemd[1]: Started Scylla Housekeeping restart mode.                                            │
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]: /opt/scylladb/scripts/libexec/scylla-housekeeping:195: DeprecationWar│
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]:  config = configparser.SafeConfigParser()                            │
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]: Traceback (most recent call last):                                   │
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]:  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 208, │
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]:    args.func(args)                                                   │
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]:  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 134, │
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]:    current_version = sanitize_version(get_api('/storage_service/scyll│
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]:  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 93, i│
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]:    return get_json_from_url("http://" + api_address + path)          │
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]:  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 88, i│
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]:    raise RuntimeError(f'Failed to get "{path}" due to the following e│
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !INFO    | scylla-housekeeping[20619]: RuntimeError: Failed to get "http://localhost:10000/storage_service/s│
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !NOTICE  | systemd[1]: scylla-housekeeping-restart.service: Main process exited, code=exited, status=1/FAILU│
│2021-02-15T12:35:48+00:00  longevity-10gb-3h-master-db-node-4ccb00f6-0-6 !WARNING | systemd[1]: scylla-housekeeping-restart.service: Failed with result 'exit-code'.       
```
