### ISSUE TITLE
segfault due to corrupt _last_status_change map in cql_transport::cql_server::event_notifier::on_down during shutdown

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8143]
Hit in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/751/artifact/logs-release.2/1614055616683_materialized_views_test.TestMaterializedViews.double_node_failure_during_mv_insert_4_nodes_test/node1.log
(and on node4)

Scylla version fb1d3fe2cf41a72190846dde85e3ebd00e6eb4b3
Relocatable packages: http://downloads.scylladb.com/unstable/scylla/master/relocatable/2021-02-22T17%3A54%3A28Z/scylla-package.tar.gz
Coredump: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/751/artifact/logs-release.2/1614055616683_materialized_views_test.TestMaterializedViews.double_node_failure_during_mv_insert_4_nodes_test/node1-reactor-1.1674952.1614055600.core.gz

```
INFO  2021-02-23 04:46:40,658 [shard 0] compaction_manager - Asked to stop
INFO  2021-02-23 04:46:40,659 [shard 0] compaction_manager - Stopping 0 ongoing compactions
INFO  2021-02-23 04:46:40,659 [shard 0] init - Signal received; shutting down
INFO  2021-02-23 04:46:40,659 [shard 0] init - Shutting down redis service
INFO  2021-02-23 04:46:40,659 [shard 0] init - Shutting down redis service was successful
INFO  2021-02-23 04:46:40,659 [shard 0] init - Shutting down view builder
INFO  2021-02-23 04:46:40,659 [shard 0] view - Stopping view builder
INFO  2021-02-23 04:46:40,659 [shard 0] compaction_manager - Stopped
INFO  2021-02-23 04:46:40,659 [shard 1] compaction_manager - Asked to stop
INFO  2021-02-23 04:46:40,659 [shard 1] compaction_manager - Stopping 0 ongoing compactions
INFO  2021-02-23 04:46:40,659 [shard 1] view - Stopping view builder
INFO  2021-02-23 04:46:40,659 [shard 1] compaction_manager - Stopped
INFO  2021-02-23 04:46:40,659 [shard 0] init - Shutting down view builder was successful
INFO  2021-02-23 04:46:40,659 [shard 0] init - Shutting down local storage
INFO  2021-02-23 04:46:40,659 [shard 0] storage_service - Drain on shutdown: starts
INFO  2021-02-23 04:46:40,659 [shard 0] storage_service - Stop transport: starts
INFO  2021-02-23 04:46:40,659 [shard 0] storage_service - Shutting down native transport
INFO  2021-02-23 04:46:40,665 [shard 0] gossip - InetAddress 127.0.60.3 is now DOWN, status = shutdown
INFO  2021-02-23 04:46:40,669 [shard 0] cql_server_controller - CQL server stopped
INFO  2021-02-23 04:46:40,669 [shard 0] storage_service - Shutting down native transport was successful
INFO  2021-02-23 04:46:40,669 [shard 0] storage_service - Shutting down rpc server
Segmentation fault on shard 0.
Backtrace:
  0x3e8e558
  0x3ec0486
  0x7f9a332ea1df
  0x4173fef
  0x19213a9
  0x2ca4c7b
  0x411e0f1
```

```
(gdb) bt
#0  seastar::net::inet_address::operator== (this=0x6010007f0678, o=...) at ./seastar/src/net/inet_address.cc:130
#1  0x00000000019213aa in gms::operator== (x=..., y=...) at ./gms/inet_address.hh:81
#2  std::equal_to<gms::inet_address>::operator() (this=<optimized out>, __x=..., __y=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_function.h:356
#3  std::__detail::_Hashtable_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<false, false, true> >::_M_equals (this=0x60100305efa0, __k=..., __c=<optimized out>, __n=0x2a05d00105ec03ff) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/hashtable_policy.h:1804
#4  std::_Hashtable<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node (this=0x60100305efa0, __bkt=7, __k=..., 
    __code=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/hashtable.h:1580
#5  std::_Hashtable<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_node (this=0x60100305efa0, __bkt=7, __key=..., 
    __c=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/hashtable.h:693
#6  std::_Hashtable<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find (this=0x60100305efa0, __k=...)
    at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/hashtable.h:1470
#7  std::unordered_map<gms::inet_address, cql_transport::event::status_change::status_type, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> > >::contains (
    this=0x60100305efa0, __x=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/unordered_map.h:948
#8  cql_transport::cql_server::event_notifier::on_down (this=0x60100305ef00, endpoint=...) at transport/event_notifier.cc:299
#9  0x0000000002ca4c7c in service::storage_service::notify_down(gms::inet_address)::$_55::operator()<service::storage_service&>(service::storage_service&) const::{lambda()#1}::operator()() const (this=<optimized out>) at service/storage_service.cc:3473
#10 std::__invoke_impl<void, service::storage_service::notify_down(gms::inet_address)::$_55::operator()<service::storage_service&>(service::storage_service&) const::{lambda()#1}>(std::__invoke_other, service::storage_service::notify_down(gms::inet_address)::$_55::operator()<service::storage_service&>(service::storage_service&) const::{lambda()#1}&&) (__f=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
#11 std::__invoke<service::storage_service::notify_down(gms::inet_address)::$_55::operator()<service::storage_service&>(service::storage_service&) const::{lambda()#1}>(service::storage_service&) (__fn=...)
    at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
#12 std::__apply_impl<service::storage_service::notify_down(gms::inet_address)::$_55::operator()<service::storage_service&>(service::storage_service&) const::{lambda()#1}, std::tuple<>>(service::storage_service&, std::tuple<>&&, std::integer_sequence<unsigned long>) (__f=..., __t=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
#13 std::apply<service::storage_service::notify_down(gms::inet_address)::$_55::operator()<service::storage_service&>(service::storage_service&) const::{lambda()#1}, std::tuple<> >(service::storage_service&, std::tuple<>&&) (__f=..., __t=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
#14 seastar::futurize<void>::apply<service::storage_service::notify_down(gms::inet_address)::$_55::operator()<service::storage_service&>(service::storage_service&) const::{lambda()#1}>(service::storage_service&, std::tuple<>&&) (func=..., args=...) at ./seastar/include/seastar/core/future.hh:2099
#15 seastar::async<service::storage_service::notify_down(gms::inet_address)::$_55::operator()<service::storage_service&>(service::storage_service&) const::{lambda()#1}>(seastar::thread_attributes, service::storage_service&)::{lambda()#1}::operator()() const (this=0x60100709b0a0) at ./seastar/include/seastar/core/thread.hh:258
#16 seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<service::storage_service::notify_down(gms::inet_address)::$_55::operator()<service::storage_service&>(service::storage_service&) const::{lambda()#1}>(seastar::thread_attributes, service::storage_service&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) (func=0x60100709b0a0) at ./seastar/include/seastar/util/noncopyable_function.hh:124
#17 0x000000000411e0f2 in seastar::noncopyable_function<void ()>::operator()() const (this=0x6010007f0678) at ./seastar/include/seastar/util/noncopyable_function.hh:209
#18 seastar::thread_context::main (this=0x60100709b080) at ./seastar/src/core/thread.cc:297

(gdb) fr 8
#8  cql_transport::cql_server::event_notifier::on_down (this=0x60100305ef00, endpoint=...) at transport/event_notifier.cc:299
299         bool was_down = _last_status_change.contains(endpoint) && _last_status_change.at(endpoint) == event::status_change::status_type::DOWN;
(gdb) p endpoint
$25 = (const gms::inet_address &) @0x6010007f0678: {
  _addr = {
    _in_family = seastar::net::inet_address::family::INET,
    {
      _in = {
        s_addr = 54263935
      },
      _in6 = {
        __in6_u = {
          __u6_addr8 = "\177\000<\003{\320\350\000\000\000\000\000\225\353,",
          __u6_addr16 = {127, 828, 53371, 232, 0, 0, 60309, 44},
          __u6_addr32 = {54263935, 15257723, 0, 2943893}
        }
      }
    },
    _scope = 4294967295
  }
}
(gdb) p _last_status_change
$26 = {
  _M_h = {
    <std::__detail::_Hashtable_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<false, false, true> >> = {
      <std::__detail::_Hash_code_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::__detail::_Select1st, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, false>> = {
        <std::__detail::_Hashtable_ebo_helper<0, std::__detail::_Select1st, true>> = {
          <std::__detail::_Select1st> = {<No data fields>}, <No data fields>}, 
        <std::__detail::_Hashtable_ebo_helper<1, std::hash<gms::inet_address>, true>> = {
          <std::hash<gms::inet_address>> = {<No data fields>}, <No data fields>}, 
        <std::__detail::_Hashtable_ebo_helper<2, std::__detail::_Mod_range_hashing, true>> = {
          <std::__detail::_Mod_range_hashing> = {<No data fields>}, <No data fields>}, <No data fields>}, 
      <std::__detail::_Hashtable_ebo_helper<0, std::equal_to<gms::inet_address>, true>> = {
        <std::equal_to<gms::inet_address>> = {
          <std::binary_function<gms::inet_address, gms::inet_address, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, 
    <std::__detail::_Map_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>> = {<No data fields>}, 
    <std::__detail::_Insert<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, false>> = {
      <std::__detail::_Insert_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >> = {<No data fields>}, <No data fields>}, 
    <std::__detail::_Rehash_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::--Type <RET> for more, q to quit, c to continue without paging--c
equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, std::integral_constant<bool, true> >> = {<No data fields>}, 
    <std::__detail::_Equality<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>> = {<No data fields>}, 
    <std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, false> > >> = {
      <std::__detail::_Hashtable_ebo_helper<0, std::allocator<std::__detail::_Hash_node<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, false> >, true>> = {
        <std::allocator<std::__detail::_Hash_node<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, false> >> = {
          <__gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, false> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, 
    members of std::_Hashtable<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >:
    _M_buckets = 0x6010038fa850,
    _M_bucket_count = 13,
    _M_before_begin = {
      _M_nxt = 0x0
    },
    _M_element_count = 0,
    _M_rehash_policy = {
      _M_max_load_factor = 1,
      _M_next_resize = 13
    },
    _M_single_bucket = 0x0
  }
}

(gdb) down
#4  std::_Hashtable<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node (this=0x60100305efa0, __bkt=7, __k=..., 
    __code=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/hashtable.h:1580
1580              if (this->_M_equals(__k, __code, __p))
(gdb) p *this
$28 = {
  <std::__detail::_Hashtable_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<false, false, true> >> = {
    <std::__detail::_Hash_code_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::__detail::_Select1st, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, false>> = {
      <std::__detail::_Hashtable_ebo_helper<0, std::__detail::_Select1st, true>> = {
        <std::__detail::_Select1st> = {<No data fields>}, <No data fields>}, 
      <std::__detail::_Hashtable_ebo_helper<1, std::hash<gms::inet_address>, true>> = {
        <std::hash<gms::inet_address>> = {<No data fields>}, <No data fields>}, 
      <std::__detail::_Hashtable_ebo_helper<2, std::__detail::_Mod_range_hashing, true>> = {
        <std::__detail::_Mod_range_hashing> = {<No data fields>}, <No data fields>}, <No data fields>}, 
    <std::__detail::_Hashtable_ebo_helper<0, std::equal_to<gms::inet_address>, true>> = {
      <std::equal_to<gms::inet_address>> = {
        <std::binary_function<gms::inet_address, gms::inet_address, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, 
  <std::__detail::_Map_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>> = {<No data fields>}, 
  <std::__detail::_Insert<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, false>> = {
    <std::__detail::_Insert_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >> = {<No data fields>}, <No data fields>}, 
  <std::__detail::_Rehash_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, std::integral_constant<bool, true> >> = {<No data fie--Type <RET> for more, q to quit, c to continue without paging--c
lds>}, 
  <std::__detail::_Equality<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>> = {<No data fields>}, 
  <std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, false> > >> = {
    <std::__detail::_Hashtable_ebo_helper<0, std::allocator<std::__detail::_Hash_node<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, false> >, true>> = {
      <std::allocator<std::__detail::_Hash_node<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, false> >> = {
        <__gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, false> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, 
  members of std::_Hashtable<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::allocator<std::pair<gms::inet_address const, cql_transport::event::status_change::status_type> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >:
  _M_buckets = 0x6010038fa850,
  _M_bucket_count = 13,
  _M_before_begin = {
    _M_nxt = 0x0
  },
  _M_element_count = 0,
  _M_rehash_policy = {
    _M_max_load_factor = 1,
    _M_next_resize = 13
  },
  _M_single_bucket = 0x0
}
(gdb) down
#3  std::__detail::_Hashtable_base<gms::inet_address, std::pair<gms::inet_address const, cql_transport::event::status_change::status_type>, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<false, false, true> >::_M_equals (this=0x60100305efa0, __k=..., __c=<optimized out>, __n=0x2a05d00105ec03ff) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/hashtable_policy.h:1804
1804            && _M_eq()(__k, this->_M_extract()(__n->_M_v()));
(gdb) down
#2  std::equal_to<gms::inet_address>::operator() (this=<optimized out>, __x=..., __y=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_function.h:356
356           { return __x == __y; }
(gdb) p __x
$29 = (const gms::inet_address &) @0x6010007f0678: {
  _addr = {
    _in_family = seastar::net::inet_address::family::INET,
    {
      _in = {
        s_addr = 54263935
      },
      _in6 = {
        __in6_u = {
          __u6_addr8 = "\177\000<\003{\320\350\000\000\000\000\000\225\353,",
          __u6_addr16 = {127, 828, 53371, 232, 0, 0, 60309, 44},
          __u6_addr32 = {54263935, 15257723, 0, 2943893}
        }
      }
    },
    _scope = 4294967295
  }
}
(gdb) p __y
$30 = (const gms::inet_address &) <error reading variable>
```

**Comment by bhalevy** [comment]
Given this sequence:
```
INFO  2021-02-23 04:46:40,659 [shard 0] storage_service - Shutting down native transport
INFO  2021-02-23 04:46:40,665 [shard 0] gossip - InetAddress 127.0.60.3 is now DOWN, status = shutdown
INFO  2021-02-23 04:46:40,669 [shard 0] cql_server_controller - CQL server stopped
INFO  2021-02-23 04:46:40,669 [shard 0] storage_service - Shutting down native transport was successful
```

It looks like the cql server is stopped in the middle of `storage_service::notify_down`,
possibly due to storage_proxy::on_down yielding.

the `cql_server::event_notifier` subscription is unregistered in `cql_server::event_notifier::~event_notifier`
while the `ss._lifecycle_subscribers` vector is being walked.

**Comment by xemul** [comment]
The solution might be in moving `event_notifier`'s unregister from destructor into `::stop()` method and using `atomic_vector` for `storage_service::_lifecycle_subscribers`

**Comment by bhalevy** [comment]
Yes, this should work, as all of the following can wait on a futurized `unregister_subscriber`:
```
db/hints/manager.cc:124:        _strorage_service_anchor->unregister_subscriber(this);
service/storage_service.cc:1623:                ss.unregister_subscriber(&local_proxy);
transport/event_notifier.cc:40:    service::get_local_storage_service().unregister_subscriber(this);
```

**Comment by bhalevy** [comment]
@avikivity I'm not sure how far back this should be backported. I've seen it in 4.4 so please backport at least there.

**Comment by bhalevy** [comment]
ping @avikivity need backport to 4.4

**Comment by avikivity** [comment]
Is only 4.4 vulnerable? Or other versions too?

**Comment by bhalevy** [comment]
@avikivity inspecting the code shows that storage_proxy::on_down may yield from version 3.1.
But the issue shows up in dtest only since 4.4.  The dtests pass in 4.3 and earlier.
So I consider only 4.4 to be vulnerable.
To have a more accurate answer we'll probably need to bisect the tree and pinpoint the exact patch that exposed this vulnerability.

**Comment by avikivity** [comment]
I'll backport to 4.4 for now. The change is too large to backport further.

**Comment by avikivity** [comment]
Backported to 4.4.

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
