### ISSUE TITLE
Apparent data loss/resurrection with versioned sstable_set

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8197]
There were a dtest regression in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/757
Testing scylla version baf5d05631491792c0809f6ea657f9aa60ad0cd2
That I bisected to the 31909515 Merge 'sstables: add versioning to the sstable_set ' from Wojciech Mitros series.

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/757/testReport/snapshot_test/TestSchemaFileInSnapshot/test_restoring_by_schema_with_mv_use_refresh/
and presumingly also
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/757/testReport/snapshot_test/TestSchemaFileInSnapshot/test_restoring_by_schema_with_mv_use_refresh_multiple_tables/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/757/testReport/snapshot_test/TestSchemaFileInSnapshot/test_restoring_snapshot_with_indexes_use_refresh/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/757/testReport/snapshot_test/TestSchemaFileInSnapshot/test_restoring_snapshot_with_indexes_use_refresh_multiple_tables/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/snapshot_test.py", line 1020, in test_restoring_by_schema_with_mv_use_refresh
    self.create_restore_data_with_snapshot_with_mv(use_sstableloader=False, multiple_tables=False)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/snapshot_test.py", line 1230, in create_restore_data_with_snapshot_with_mv
    self.check_rows_number_in_table(session, "ks", "cf_mv", 100)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/snapshot_test.py", line 1474, in check_rows_number_in_table
    self.assertEqual(rows[0][0], number)
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 100
```

Bisected to aa0cd940d

**Comment by bhalevy** [comment]
Same patch caused regression also with:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/757/testReport/materialized_views_test/TestMaterializedViews/base_replica_repair_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 3045, in base_replica_repair_test
    self._base_replica_repair_test()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 3134, in _base_replica_repair_test
    [i, i, 'a', 3.0]
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1643, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 68, in assert_one
    assert list_res == [expected], "Expected %s from %s, but got %s" % ([expected], query, list_res)
AssertionError: Expected [[0, 0, 'a', 3.0]] from SELECT * FROM t_by_v WHERE v = 0, but got []
```

and https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/757/testReport/materialized_views_test/TestMaterializedViews/really_complex_repair_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 3314, in really_complex_repair_test
    assert_none(session2, "SELECT * FROM ks.t_by_v WHERE v2 = 'a'", cl=ConsistencyLevel.QUORUM)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1643, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 84, in assert_none
    assert list_res == [], "Expected nothing from %s, but got %s" % (query, list_res)
AssertionError: Expected nothing from SELECT * FROM ks.t_by_v WHERE v2 = 'a', but got [['a', 1, 1, Decimal('3.0')], ['a', 2, 2, Decimal('3.0')]]
```

**Comment by avikivity** [comment]
I'll revert it, too many serious regressions. Need a BYO dtest to pass first.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
