### ISSUE TITLE
Regression in thrift_tests.test_get_range_slice dtest: query_data_on_all_shards(): reverse range scans are not supported

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8211]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/758/testReport/thrift_tests/TestMutations/test_get_range_slice_2/

Introduced in 0f0c3be63e4f1bfbcdde988a7bdd7f5fa54d9c2e
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1130, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1184, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node1', ['ERROR 2021-03-03 03:30:39,067 [shard 0] storage_proxy - Exception when communicating with 127.0.14.1, to read from Keyspace1.Standard1: std::runtime_error (query_data_on_all_shards(): reverse range scans are not supported)'])]
```

@denesb, your commit message says:
```
    Refuse reverse queries just like in the new
    `query_data_on_all_shards()`. The reason is the same, reverse range
    scans are not supported on the client API level and hence they are
    underspecified and more importantly: not tested.
```

The question is how to consider thrift?

/cc @tgrabiec

**Comment by denesb** [comment]
Well thrift *is* a client API, so I guess we can't say that all client APIs disallow reverse scans. We need to support it.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
