### ISSUE TITLE
Error running perform after upgrade from 4.4rc1 to 4.4rc2

### ISSUE THREAD

**Issue by fggarcia** [scylladb/scylla#8218]
After upgrade from 4.4rc1 to 4.4rc2 and perform:

```
/usr/sbin/scylla_setup --no-raid-setup --nic $INTERFACE \
                         --no-coredump-setup --no-io-setup --no-ec2-check
```

where 
```
INTERFACE=$(ifconfig | expand | cut -c1-8 | sort | uniq -u | awk -F: '{print $1;}' | grep -v lo | head -1)
```

INTERFACE=ens3

issue:
```
Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/opt/scylladb/python3/lib64/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/opt/scylladb/python3/lib64/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'SET_NIC_AND_DISKS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/scripts/scylla_util.py", line 684, in get_set_nic_and_disks_config_value
    return cfg.get('SET_NIC_AND_DISKS')
  File "/opt/scylladb/scripts/scylla_util.py", line 832, in get
    return self._cfg.get('global', key).strip('"')
  File "/opt/scylladb/python3/lib64/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'SET_NIC_AND_DISKS' in section: 'global'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/opt/scylladb/python3/lib64/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/opt/scylladb/python3/lib64/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'SET_NIC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 42, in <module>
    set_nic_and_disks = str2bool(get_set_nic_and_disks_config_value(cfg))
  File "/opt/scylladb/scripts/scylla_util.py", line 687, in get_set_nic_and_disks_config_value
    return cfg.get('SET_NIC')
  File "/opt/scylladb/scripts/scylla_util.py", line 832, in get
    return self._cfg.get('global', key).strip('"')
  File "/opt/scylladb/python3/lib64/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'SET_NIC' in section: 'global'
done
Job for scylla-server.service failed because of unavailable resources or another system error.
See "systemctl status scylla-server.service" and "journalctl -xe" for details.

```

**Comment by slivne** [comment]
Is it this  9fc582ee8358166c0a1e91c23d1e335440df8dcb are we missing anything ?
