### ISSUE TITLE
Wrong maximum number of cell count

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#822]
rom limit.py test.

```
    ======================================================================
    ERROR: max_cells_test (limits.TestLimits)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/benoit/scylla-dtest/limits.py", line 282, in max_cells_test
        self._do_test_max_cell_count(session, node, cells - 1)
      File "/home/benoit/scylla-dtest/limits.py", line 266, in _do_test_max_cell_count
        session.execute(c)
      File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:27334)
        result = future.result()
      File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:65206)
        raise self._final_exception
    NoHostAvailable: ('Unable to complete the operation against any hosts', {})
    -------------------- >> begin captured logging << --------------------
    dtest: DEBUG: cluster ccm directory: /home/benoit/.dtest/dtest-OyAcP9
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: [control connection] Error connecting to 127.0.0.1:
    Traceback (most recent call last):
      File "cassandra/cluster.py", line 2114, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:37551)
        return self._try_connect(host)
      File "cassandra/cluster.py", line 2134, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:38028)
        connection = self._cluster.connection_factory(host.address, is_control_connection=True)
      File "cassandra/cluster.py", line 785, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9335)
        return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
      File "cassandra/connection.py", line 313, in cassandra.connection.Connection.factory (cassandra/connection.c:5400)
        raise OperationTimedOut("Timed out creating connection (%s seconds)" % timeout)
    OperationTimedOut: errors=Timed out creating connection (10 seconds), last_host=None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
   cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: [control connection] Error connecting to 127.0.0.1:
    Traceback (most recent call last):
      File "cassandra/cluster.py", line 2114, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:37551)
        return self._try_connect(host)
      File "cassandra/cluster.py", line 2134, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:38028)
        connection = self._cluster.connection_factory(host.address, is_control_connection=True)
      File "cassandra/cluster.py", line 785, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9335)
        return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
      File "cassandra/connection.py", line 313, in cassandra.connection.Connection.factory (cassandra/connection.c:5400)
        raise OperationTimedOut("Timed out creating connection (%s seconds)" % timeout)
    OperationTimedOut: errors=Timed out creating connection (10 seconds), last_host=None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: Node 127.0.0.1 is reporting a schema disagreement: None
    cassandra.cluster: WARNING: [control connection] Error connecting to 127.0.0.1:
    Traceback (most recent call last):
      File "cassandra/cluster.py", line 2114, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:37551)
        return self._try_connect(host)
      File "cassandra/cluster.py", line 2134, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:38028)
        connection = self._cluster.connection_factory(host.address, is_control_connection=True)
      File "cassandra/cluster.py", line 785, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9335)
        return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
      File "cassandra/connection.py", line 313, in cassandra.connection.Connection.factory (cassandra/connection.c:5400)
        raise OperationTimedOut("Timed out creating connection (%s seconds)" % timeout)
    OperationTimedOut: errors=Timed out creating connection (10 seconds), last_host=None
    cassandra.cluster: WARNING: Host 127.0.0.1 has been marked down
    --------------------- >> end captured logging << ---------------------

    ----------------------------------------------------------------------
    Ran 1 test in 905.714s
```

current known limit: 16777215 (known power of 2)

should be: 2G

crash: not visible in the log seems to cause python client to timeout

extract of scylla output:

```
/node1/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-64-Data.db:level=0, ]
INFO  [shard 0] compaction - Compacted 4 sstables to [/home/benoit/.dtest/dtest-GPEMdf/test/node1/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-65-Data.db:level=0, ]. 32219 bytes to 30697 (~95% of original) in 588ms = 0.0497807MB/s. ~1024 total partitions merged to 2.
INFO  [shard 0] compaction - Compacting [/home/benoit/.dtest/dtest-GPEMdf/test/node1/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-61-Data.db:level=0, /home/benoit/.dtest/dtest-GPEMdf/test/node1/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-62-Data.db:level=0, /home/benoit/.dtest/dtest-GPEMdf/test/node1/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-63-Data.db:level=0, /home/benoit/.dtest/dtest-GPEMdf/test/node1/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-64-Data.db:level=0, ]
```

**Comment by penberg** [comment]
The operation times out because it takes too long time to process the request. I increased the timeout to 120 seconds but it's still not enough.

``perf top`` points to ``prepare_column_identifier`` taking a lot of time which suggests that we enter an infinite loop in ``update_statement::parsed_insert::prepare_internal``.

```
(gdb) bt
#0  shared_ptr_count_for<cql3::column_identifier>::~shared_ptr_count_for (this=0x60000257a820, __in_chrg=<optimized out>)
    at /home/penberg/scylla/seastar/core/shared_ptr.hh:317
#1  0x000000000094ab7d in shared_ptr<cql3::column_identifier>::~shared_ptr (this=0x7fffffffbf60, __in_chrg=<optimized out>)
    at /home/penberg/scylla/seastar/core/shared_ptr.hh:389
#2  cql3::statements::update_statement::parsed_insert::prepare_internal (this=0x6000136bdbf0, db=..., schema=..., bound_names=..., attrs=...)
    at cql3/statements/update_statement.cc:148
^C#3  0x00000000009375de in cql3::statements::modification_statement::parsed::prepare (Quit
```

**Comment by avikivity** [comment]
Quadratic behavior:

```
::shared_ptr<modification_statement>
update_statement::parsed_insert::prepare_internal(database& db, schema_ptr schema,
    ::shared_ptr<variable_specifications> bound_names, std::unique_ptr<attributes> attrs)
{

...

    for (size_t i = 0; i < _column_names.size(); i++) {
        auto id = _column_names[i]->prepare_column_identifier(schema);
        auto def = get_column_definition(schema, *id);
        if (!def) {
            throw exceptions::invalid_request_exception(sprint("Unknown identifier %s", *id));
        }

        for (size_t j = 0; j < i; j++) {
            auto other_id = _column_names[j]->prepare_column_identifier(schema);
            if (*id == *other_id) {
                throw exceptions::invalid_request_exception(sprint("Multiple definitions found for column %s", *id));
            }
        }

...

}
```

**Comment by avikivity** [comment]
Some magic like

    boost::adjacent_find(boost::irange | transformed(prepare_column_identifier) | sorted)

might do the trick

**Comment by penberg** [comment]
@benoit-canet Cassandra 2.1.8 is not able to deal with higher than 16777215 limit either. Is the test case actually sane?

**Comment by benoit-canet** [comment]
Pekka: I am often confronted to the fact that before scylla limits are
removed I cannot
test my test code. So sorry  if the test is broken. I'll check this on
sunday. I also noticed
some issues in the python casssandra wrapper while writting the tests that
where limiting
blob size for example.

Best regards

Benoît

**Comment by penberg** [comment]
@benoit-canet Oh, don't worry about it. I am just wondering if there's actually anything to fix here on Scylla side as we seem to have the same limits as Cassandra already.

**Comment by benoit-canet** [comment]
Has this code already been rewritten ?

I don't recognize it in Scylla codebase.

**Comment by penberg** [comment]
https://github.com/scylladb/scylla/commit/8e2c924de3077f664c347333884999ee5f725c9c

**Comment by benoit-canet** [comment]
@penberg: The theorical limit is 2 billions. We are way below I will dig this.

**Comment by penberg** [comment]
@benoit-canet It's the *practical* limit (i.e. what C* has) that matters much more here.

**Comment by benoit-canet** [comment]
I wonder if we are hitting a limit of the python driver. Some test have
this problem.

**Comment by benoit-canet** [comment]
The limits are the same as cassandra. closing the bug

**Comment by penberg** [comment]
@benoit-canet Can you please fix the limit in our dtest and re-enable it?
