### ISSUE TITLE
coroutine miscompile: function param seems to be optimized away

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8259]
I hit this when trying to coroutinize `table::query`.

Reproduced with https://github.com/bhalevy/scylla/commit/41454035d1ecb4f527331303a197d10c01fabe86 on top of scylla cf28552357bb19f69d47ed323041aeb525a6a844:
```diff
diff --git a/table.cc b/table.cc
index 416881a65..e61aa5f7f 100644
--- a/table.cc
+++ b/table.cc
@@ -1766,28 +1766,43 @@ table::query(schema_ptr s,
     utils::latency_counter lc;
     _stats.reads.set_latency(lc);
     const auto short_read_allwoed = query::short_read(cmd.slice.options.contains<query::partition_slice::option::allow_short_read>());
-    auto f = opts.request == query::result_request::only_digest
-             ? memory_limiter.new_digest_read(*cmd.max_result_size, short_read_allwoed) : memory_limiter.new_data_read(*cmd.max_result_size, short_read_allwoed);
-    return f.then([this, lc, s = std::move(s), &cmd, class_config, opts, &partition_ranges,
-            trace_state = std::move(trace_state), timeout, cache_ctx = std::move(cache_ctx),
-            leave = std::move(leave)] (query::result_memory_accounter accounter) mutable {
+    auto accounter = co_await (opts.request == query::result_request::only_digest
+             ? memory_limiter.new_digest_read(*cmd.max_result_size, short_read_allwoed) : memory_limiter.new_data_read(*cmd.max_result_size, short_read_allwoed));
         auto qs_ptr = std::make_unique<query_state>(std::move(s), cmd, opts, partition_ranges, std::move(accounter));
         auto& qs = *qs_ptr;
-        return do_until(std::bind(&query_state::done, &qs), [this, &qs, class_config, trace_state = std::move(trace_state), timeout, cache_ctx = std::move(cache_ctx)] {
+        while (!qs.done()) {
             auto&& range = *qs.current_partition_range++;
-            return data_query(qs.schema, as_mutation_source(), range, qs.cmd.slice, qs.remaining_rows(),
+            auto ms = as_mutation_source();
+            co_await data_query(qs.schema, ms, range, qs.cmd.slice, qs.remaining_rows(),
                               qs.remaining_partitions(), qs.cmd.timestamp, qs.builder, timeout, class_config, trace_state, cache_ctx);
-        }).then([qs_ptr = std::move(qs_ptr), &qs] {
-            return make_ready_future<lw_shared_ptr<query::result>>(
-                    make_lw_shared<query::result>(qs.builder.build()));
-        }).finally([lc, this, leave = std::move(leave)]() mutable {
+        }
+        std::exception_ptr ex;
+        lw_shared_ptr<query::result> res;
+        try {
+            res = make_lw_shared<query::result>(qs.builder.build());
+        } catch (...) {
+            ex = std::current_exception();
+        }
+        qs_ptr.reset();
+        auto finally = [lc, this, leave = std::move(leave)]() mutable {
             _stats.reads.mark(lc);
             if (lc.is_start()) {
                 _stats.estimated_read.add(lc.latency());
             }
             // "leave" is destroyed here
-        });
-    });
+        };
+    try {
+        finally();
+    } catch (...) {
+        if (ex) {
+            throw seastar::nested_exception(std::current_exception(), std::move(ex));
+        }
+        throw;
+    }
+    if (ex) {
+        std::rethrow_exception(std::move(ex));
+    }
+    co_return res;
 }
 
 mutation_source
```

$ mode=debug; test=database_test; case=; ninja -j32 build/$mode/test/boost/${test}_g && { UBSAN_OPTIONS="halt_on_error=1:abort_on_error=1:suppressions=`pwd`/ubsan-suppressions.supp" ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1' build/$mode/test/boost/${test}_g -l all $([ -n "$case" ] && echo "-t $case") --catch_system_errors=no --color_output=false -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --default-log-level=info
...
/home/bhalevy/dev/scylla-2/seastar/include/seastar/util/bool_class.hh:84:30: runtime error: load of value 190, which is not a valid value for type 'bool'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/bhalevy/dev/scylla-2/seastar/include/seastar/util/bool_class.hh:84:30 in 
```

```
$ gdb -c database_test_g.230935.1615454531.core build/debug/test/boost/database_test_g
(gdb) bt
#0  0x00007fe94569b9d5 in raise () from /lib64/libc.so.6
#1  0x00007fe9456848a4 in abort () from /lib64/libc.so.6
#2  0x0000000010c3582b in __sanitizer::Abort() ()
#3  0x0000000010c33b68 in __sanitizer::Die() ()
#4  0x0000000010c445c9 in __ubsan::ScopedReport::~ScopedReport() ()
#5  0x0000000010c45b4c in handleLoadInvalidValue(__ubsan::InvalidValueData*, unsigned long, __ubsan::ReportOptions) ()
#6  0x0000000010c49421 in __ubsan_handle_load_invalid_value ()
#7  0x00000000151a51f0 in seastar::operator! (x=...) at ./seastar/include/seastar/util/bool_class.hh:84
#8  0x000000001519f71a in query::querier_cache_context::lookup_data_querier (this=0x7fe93e096060, s=..., range=..., slice=..., trace_state=...) at querier.cc:440
#9  0x00000000116105f0 in data_query (s=..., source=..., range=..., slice=..., row_limit=18446744073709551615, partition_limit=<optimized out>, query_time=..., builder=..., timeout=..., class_config=..., trace_ptr=..., cache_ctx=...) at mutation_partition.cc:1985
#10 0x00000000110c94b8 in table::query (this=<optimized out>, s=..., cmd=..., class_config=..., opts=..., partition_ranges=..., trace_state=..., memory_limiter=..., timeout=..., cache_ctx=...) at table.cc:1776
#11 0x000000001117f3c8 in std::experimental::coroutine_handle<seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<query::result> >::promise_type>::resume (this=this@entry=0x7fe93db99760) at ./seastar/include/seastar/core/std-coroutine.hh:70
#12 0x000000001117f1ab in seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<query::result> >::promise_type::run_and_dispose (this=0x616000063f90) at ./seastar/include/seastar/core/coroutine.hh:69
#13 0x00000000160264d1 in seastar::reactor::run_tasks (this=0x62400002c100, tq=...) at ./seastar/src/core/reactor.cc:2258
#14 0x000000001602cb97 in seastar::reactor::run_some_tasks (this=0x62400002c100) at ./seastar/src/core/reactor.cc:2667
#15 0x00000000160314e8 in seastar::reactor::run (this=0x62400002c100) at ./seastar/src/core/reactor.cc:2826
#16 0x0000000016ea3913 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=0x7fe93defb020, ac=11, av=0x7fff01036ba8, func=...) at ./seastar/src/core/app-template.cc:207
#17 0x0000000016ea1a42 in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) (this=0x7fe93defb020, ac=11, av=0x7fff01036ba8, func=...) at ./seastar/src/core/app-template.cc:115
#18 0x0000000016e7adf9 in seastar::testing::test_runner::start(int, char**)::$_0::operator()() (this=0x604000009550) at ./seastar/src/testing/test_runner.cc:70
#19 0x0000000016e7a678 in std::__invoke_impl<void, seastar::testing::test_runner::start(int, char**)::$_0&>(std::__invoke_other, seastar::testing::test_runner::start(int, char**)::$_0&) (__f=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
#20 0x0000000016e7a508 in std::__invoke_r<void, seastar::testing::test_runner::start(int, char**)::$_0&>(seastar::testing::test_runner::start(int, char**)::$_0&) (__fn=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110
#21 0x0000000016e79f18 in std::_Function_handler<void (), seastar::testing::test_runner::start(int, char**)::$_0>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
#22 0x00000000111e6356 in std::function<void ()>::operator()() const (this=0x6030000159a0) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
#23 0x0000000016395d68 in seastar::posix_thread::start_routine (arg=0x6030000159a0) at ./seastar/src/core/posix.cc:60
#24 0x00007fe9464cb3f9 in start_thread () from /lib64/libpthread.so.0
#25 0x00007fe94575f903 in clone () from /lib64/libc.so.6

(gdb) fr 9
#9  0x00000000116105f0 in data_query (s=..., source=..., range=..., slice=..., row_limit=18446744073709551615, partition_limit=<optimized out>, query_time=..., builder=..., timeout=..., class_config=..., trace_ptr=..., cache_ctx=...) at mutation_partition.cc:1985
1985	    auto querier_opt = cache_ctx.lookup_data_querier(*s, range, slice, trace_ptr);
(gdb) p cache_ctx
$2 = {
  _cache = 0xbebebebebebebebe,
  _key = {
    most_sig_bits = -4702111234474983746,
    least_sig_bits = -4702111234474983746
  },
  _is_first_page = {
    _value = 190
  }
}
```

**Comment by bhalevy** [comment]
cc @psarna @avikivity

**Comment by bhalevy** [comment]
For the record:
```
$ clang++ --version
clang version 11.0.0 (Fedora 11.0.0-2.fc33)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by avikivity** [comment]
There's not much point in opening a bug for code that doesn't exist. How are we supposed to fix it?

Those unclosable bugs end up accumulating.

**Comment by bhalevy** [comment]
Although scylla is not a development platform, can't I consider the issue with the compiler kind and version in the mentioned scylla version?
This would be fixed when the compiler is either fixed or changed to one that works.

If not opening a github issue for this, what would be a better way to keep track of the gory details?

**Comment by avikivity** [comment]
The best way is in a deep well, you have to throw it there at midnight when no one's watching and not tell anyone. Otherwise, there's a clang bug for it: https://bugs.llvm.org/show_bug.cgi?id=48857.
