### ISSUE TITLE
scylla_setup: scylla_setup can cause traceback when scylla-node-exporter package is not installed

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#8276]
Since scylla-node-exporter package required from scylla metapackage not scylla-server package, scylla-server can install scylla-node-exporter.
If we run node exporter setup in such condition, scylla_setup abort the script like this:
```
Do you want to enable node exporter to export Prometheus data from the node? Note that the Scylla monitoring stack uses this data
Yes - enable node exporter. No - skip this  step.
[YES/no]
Traceback (most recent call last):
  File "/opt/scylladb/scripts/scylla_util.py", line 777, in __init__
    run('systemctl {} cat {}'.format(self.ctlparam, unit), shell=True, check=True, stdout=DEVNULL, stderr=DEVNULL)
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'systemctl  cat scylla-node-exporter' returned non-zero exit status 1.
```
We need to run package existence before running the command, or requires it from scylla-server package, not scylla metapackage.

**Comment by syuu1228** [comment]
I think it's better to add dependency to scylla-server package, since it supposed to install with scylla-server.
