### ISSUE TITLE
refresh_and_restart_after_compaction_strategy_change_test: 3 != 0 : Exception occured in subtest

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8353]
Regression seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/768/testReport/compaction_additional_test/CompactionAdditionalTest/refresh_and_restart_after_compaction_strategy_change_test/
Scylla version abab1d906c3490a112a0f7b677364f51ca1e63e2
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/compaction_additional_test.py", line 561, in refresh_and_restart_after_compaction_strategy_change_test
    self.assertEqual(len(subtests_errs), 0, 'Exception occured in subtest')
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 3 != 0 : Exception occured in subtest
Standard Output
2021-03-19 19:42:59.130267 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'LeveledCompactionStrategy', 'sstable_size_in_mb': 1, 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 19:42:59.806363 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 19:43:00.608173 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 19:43:06.157789 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 19:43:17.493578 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 19:45:29.127456 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': 1, 'compaction_window_unit': 'MINUTES', 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 19:45:30.163223 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 19:45:38.335616 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 19:45:43.866046 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 19:45:57.157493 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 19:48:29.337131 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'SizeTieredCompactionStrategy', 'bucket_high': 1.5, 'bucket_low': 0.5, 'min_sstable_size': 1, 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 19:48:30.153700 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 19:48:31.093486 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 19:48:36.723492 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 19:48:43.559203 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 19:50:06.375458 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'DateTieredCompactionStrategy'}
2021-03-19 19:50:07.128959 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 19:50:07.891594 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 19:50:13.520271 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 19:50:20.766213 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 19:51:55.987630 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'LeveledCompactionStrategy', 'sstable_size_in_mb': 1, 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 19:51:56.771959 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 19:51:57.640469 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 19:52:03.383415 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 19:54:25.227123 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': 1, 'compaction_window_unit': 'MINUTES', 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 19:54:26.049721 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 19:54:34.783803 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 19:54:40.453119 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 19:54:52.452473 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 19:57:20.205235 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'SizeTieredCompactionStrategy', 'bucket_high': 1.5, 'bucket_low': 0.5, 'min_sstable_size': 1, 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 19:57:20.863570 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 19:57:21.786585 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 19:57:27.261909 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 19:57:36.411244 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 19:58:57.715314 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'DateTieredCompactionStrategy'}
2021-03-19 19:58:58.377324 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 19:58:59.021494 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 19:59:04.567639 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 19:59:12.420227 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 20:00:41.561535 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'LeveledCompactionStrategy', 'sstable_size_in_mb': 1, 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 20:00:42.238892 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 20:00:42.954040 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 20:00:48.490594 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 20:03:11.084423 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': 1, 'compaction_window_unit': 'MINUTES', 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 20:03:11.862072 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 20:03:22.527534 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 20:03:28.018245 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 20:03:46.870039 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 20:06:14.867903 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'SizeTieredCompactionStrategy', 'bucket_high': 1.5, 'bucket_low': 0.5, 'min_sstable_size': 1, 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 20:06:15.540404 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 20:06:16.415784 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 20:06:21.907010 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 20:06:31.393052 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 20:07:52.400240 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'DateTieredCompactionStrategy'}
2021-03-19 20:07:53.066110 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 20:07:53.721911 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 20:07:59.203193 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 20:08:08.738925 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 20:09:37.920854 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'LeveledCompactionStrategy', 'sstable_size_in_mb': 1, 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 20:09:38.623212 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 20:09:39.335395 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 20:09:44.871947 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 20:12:07.624888 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': 1, 'compaction_window_unit': 'MINUTES', 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 20:12:08.410326 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 20:12:23.489078 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 20:12:28.986849 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 20:12:46.561459 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 20:15:15.338223 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'SizeTieredCompactionStrategy', 'bucket_high': 1.5, 'bucket_low': 0.5, 'min_sstable_size': 1, 'max_threshold': 1, 'min_threshold': 1}
2021-03-19 20:15:16.058943 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 20:15:17.013203 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 20:15:22.490568 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 20:15:33.788598 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
2021-03-19 20:16:54.613901 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Change table compaction strategy to {'class': 'DateTieredCompactionStrategy'}
2021-03-19 20:16:55.365185 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Refresh keyspace1.standard1 .....
2021-03-19 20:16:56.074831 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from upload/ directory
2021-03-19 20:17:01.533220 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Restart the node .....
2021-03-19 20:17:11.026936 compaction_additional_test.py:CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test - Verify data is loaded from staging/ directory
```

**Comment by amoskong** [comment]
Not a scylla issue, I just adjusted the test.

by https://github.com/scylladb/scylla/issues/8353

**Comment by bhalevy** [comment]
Closing with scylladb/scylla-dtest#2135 / https://github.com/scylladb/scylla-dtest/commit/6238d420f73c3319fc7a66e25e4f21bb1ccf1704
