### ISSUE TITLE
test_total_space_limit_of_commitlog: stopping scylla-server hangs

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#8438]
*Installation details*
Scylla version (or git commit hash): 4.6.dev-0.20210406.e991e01f2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

Executing the fixed `test_total_space_limit_of_commitlog`, the test will fail in stop & start the scylla-server.

```
From Benny:

I looked into test_total_space_limit_of_commitlog
and hit a bug in scylla at least when running on machines with lots of memory
causing scylla to cross an internal threshold and get into an 
```

- latest test: https://github.com/scylladb/scylla-dtest/blob/next/commitlog_test.py
- fix: https://github.com/scylladb/scylla-dtest/pull/2085

### Part of DB logs:
```
INFO  2021-04-09 01:35:57,313 [shard 0] database - Keyspace system: Reading CF schema_columns id=296e9c04-9bec-3085-827d-c17d3df2122a version=53cfbb66-ee0d-37be-97bb-b2afb3746f85
INFO  2021-04-09 01:35:57,313 [shard 0] database - Keyspace system: Reading CF schema_triggers id=0359bc71-7123-3ee1-9a4a-b9dfb11fc125 version=75e4ec4c-76da-3f59-984e-66810ba0c62b
INFO  2021-04-09 01:35:57,712 [shard 0] init - starting gossip
INFO  2021-04-09 01:35:57,712 [shard 0] init - seeds={127.0.46.1}, listen_address=127.0.46.1, broadcast_address=127.0.46.1
INFO  2021-04-09 01:35:57,712 [shard 0] seastar - updated: blocked-reactor-notify-ms=200
INFO  2021-04-09 01:35:57,712 [shard 0] init - starting storage proxy
INFO  2021-04-09 01:35:57,735 [shard 0] init - starting migration manager
INFO  2021-04-09 01:35:57,735 [shard 0] init - starting query processor
INFO  2021-04-09 01:35:57,739 [shard 0] init - initializing batchlog manager
INFO  2021-04-09 01:35:57,745 [shard 0] legacy_schema_migrator - Moving 0 keyspaces from legacy schema tables to the new schema keyspace (system_schema)
INFO  2021-04-09 01:35:57,745 [shard 0] legacy_schema_migrator - Dropping legacy schema tables
INFO  2021-04-09 01:36:58,830 [shard 0] compaction_manager - Asked to stop
INFO  2021-04-09 01:36:58,830 [shard 0] compaction_manager - Stopping 0 ongoing compactions
INFO  2021-04-09 01:36:58,830 [shard 0] compaction_manager - Stopped
(END)
```

### Test scenario

- set small/medium/big commitlog_segment_size_in_mb
- start scylla-server
- create test keyspace and table
- fill data to the test table in 200, and try to make the commit log space is well used.
- make sure the well-used-cases are more than or equal to 5 times in 200 seconds
- set commitlog_segment_size_in_mb back to default -1
- stop & start scylla
- verify the filled data count
- insert more data and verify the count is increased

**Comment by slivne** [comment]
@bhalevy please help with additional info - so we can assign this.

**Comment by bhalevy** [comment]
I added some debug logging over next @705f9c4f79293011fedd775187208db170f1326c
```diff
diff --git a/db/commitlog/commitlog.cc b/db/commitlog/commitlog.cc
index aa9d5c643..17b9d4af0 100644
--- a/db/commitlog/commitlog.cc
+++ b/db/commitlog/commitlog.cc
@@ -1674,8 +1674,9 @@ future<> db::commitlog::segment_manager::clear_reserve_segments() {
 }
 
 future<> db::commitlog::segment_manager::sync_all_segments() {
-    clogger.debug("Issuing sync for all segments");
+    clogger.debug("Issuing sync for all {} segments", _segments.size());
     return parallel_for_each(_segments, [] (sseg_ptr s) {
+        clogger.debug("Syncing segment {}", *s);
         return s->sync().then([](sseg_ptr s) {
             clogger.debug("Synced segment {}", *s);
         });
@@ -1683,7 +1684,7 @@ future<> db::commitlog::segment_manager::sync_all_segments() {
 }
 
 future<> db::commitlog::segment_manager::shutdown_all_segments() {
-    clogger.debug("Issuing shutdown for all segments");
+    clogger.debug("Issuing shutdown for all {} segments", _segments.size());
     return parallel_for_each(_segments, [] (sseg_ptr s) {
         return s->shutdown().then([](sseg_ptr s) {
             clogger.debug("Shutdown segment {}", *s);
@@ -1697,6 +1698,7 @@ future<> db::commitlog::segment_manager::shutdown() {
 
         // Wait for all pending requests to finish. Need to sync first because segments that are
         // alive may be holding semaphore permits.
+        clogger.info("Shutting down commitlog");
         auto block_new_requests = get_units(_request_controller, max_request_controller_units());
         return sync_all_segments().then([this, block_new_requests = std::move(block_new_requests)] () mutable {
             return std::move(block_new_requests).then([this] (auto permits) {
@@ -1713,8 +1715,11 @@ future<> db::commitlog::segment_manager::shutdown() {
                 return std::move(_reserve_replenisher).then_wrapped([this] (auto f) {
                     // Could be cleaner with proper seastar support
                     if (f.failed()) {
-                        _shutdown_promise->set_exception(f.get_exception());
+                        auto ex = f.get_exception();
+                        clogger.info("Shutting down commitlog failed: {}", ex);
+                        _shutdown_promise->set_exception(std::move(ex));
                     } else {
+                        clogger.info("Shutting down commitlog completed");
                         _shutdown_promise->set_value();
                     }
                 });
```

This point towards hang in the commitlog shutdown path.

With the following additional change the test still fails but is able to stop the cluster:

```diff
diff --git a/db/commitlog/commitlog.cc b/db/commitlog/commitlog.cc
index aa9d5c643..f0e3367a1 100644
--- a/db/commitlog/commitlog.cc
+++ b/db/commitlog/commitlog.cc
@@ -1511,7 +1511,7 @@ future<db::commitlog::segment_manager::sseg_ptr> db::commitlog::segment_manager:
         });
     }
 
-    if (!cfg.allow_going_over_size_limit && max_disk_size != 0 && totals.total_size_on_disk >= max_disk_size) {
+    if (false && !cfg.allow_going_over_size_limit && max_disk_size != 0 && totals.total_size_on_disk >= max_disk_size) {
         clogger.debug("Disk usage ({} MB) exceeds maximum ({} MB) - allocation will wait...", totals.total_size_on_disk/(1024*1024), max_disk_size/(1024*1024));
         auto f = cfg.reuse_segments ? _recycled_segments.not_empty() :  _disk_deletions.get_shared_future();
         return f.handle_exception([this](auto ep) {
```

```
DEBUG 2021-04-11 12:58:21,536 [shard 0] commitlog - Issuing shutdown for all 1 segments
TRACE 2021-04-11 12:58:21,536 [shard 0] commitlog - Syncing CommitLog-2-241308201.log 1802240 -> 1802240
TRACE 2021-04-11 12:58:21,536 [shard 0] commitlog - CommitLog-2-241308201.log already synced! (1802240 < 1802240)
TRACE 2021-04-11 12:58:21,536 [shard 0] commitlog - Syncing CommitLog-2-241308201.log 1802240 -> 1802240
TRACE 2021-04-11 12:58:21,536 [shard 0] commitlog - CommitLog-2-241308201.log already synced! (1802240 < 1802240)
TRACE 2021-04-11 12:58:21,536 [shard 0] commitlog - CommitLog-2-241308201.log is closed but not terminated.
TRACE 2021-04-11 12:58:21,536 [shard 0] commitlog - Allocated 128 k buffer
TRACE 2021-04-11 12:58:21,536 [shard 0] commitlog - Terminating CommitLog-2-241308201.log at pos 1806336
TRACE 2021-04-11 12:58:21,536 [shard 0] commitlog - Final write of 4096 to CommitLog-2-241308201.log: 4096/4096 bytes at 1802240
TRACE 2021-04-11 12:58:21,536 [shard 0] commitlog - CommitLog-2-241308201.log synced to 1806336
DEBUG 2021-04-11 12:58:21,542 [shard 0] commitlog - Shutdown segment CommitLog-2-241308201.log
TRACE 2021-04-11 12:58:21,542 [shard 0] commitlog - Checking for unused segments (1 active)
DEBUG 2021-04-11 12:58:21,542 [shard 0] commitlog - Segment CommitLog-2-241308201.log is unused

I think that without the change above the segment remains active and we wait for ever (maybe on `gate.close()`?)

DEBUG 2021-04-11 12:58:21,542 [shard 0] commitlog - Segment CommitLog-2-241308201.log is no longer active and will submitted for delete now
DEBUG 2021-04-11 12:58:21,542 [shard 0] commitlog - Segment CommitLog-2-241308202.log is no longer active and will submitted for delete now
DEBUG 2021-04-11 12:58:21,542 [shard 0] commitlog - Delete segments {/home/bhalevy/.dtest/dtest-0okfmbxe/test/node1/commitlogs/CommitLog-2-241308202.log, /home/bhalevy/.dtest/dtest-0okfmbxe/test/node1/commitlogs/CommitLog-2-241308201.log}
DEBUG 2021-04-11 12:58:21,542 [shard 0] commitlog - Deleting segment file /home/bhalevy/.dtest/dtest-0okfmbxe/test/node1/commitlogs/CommitLog-2-241308201.log
TRACE 2021-04-11 12:58:21,542 [shard 0] commitlog - Reclaimed 1 MB
DEBUG 2021-04-11 12:58:21,542 [shard 0] commitlog - Deleting segment file /home/bhalevy/.dtest/dtest-0okfmbxe/test/node1/commitlogs/CommitLog-2-241308202.log
TRACE 2021-04-11 12:58:21,546 [shard 0] commitlog - Reclaimed 4095 MB
INFO  2021-04-11 12:58:21,546 [shard 0] commitlog - Shutting down commitlog completed
```

@elcallio please look into this

**Comment by elcallio** [comment]
I think this a dup of #8363 (?). I can't repro it anyhow. But I sent a patch with a test for shutting down with potentially waiting allocation just in case.

**Comment by slivne** [comment]
closing this is marked a dup of  #8363 that is fixed and merged

**Comment by amoskong** [comment]
@ShlomiBalalis @elcallio 

I touched coredumps in https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/522/artifact/logs-byo.release.2/
But it doesn't occur in my local test (running dtest on a GCE instance)

- 4.6.dev-0.20210418.dbd0b9a3ef

```
07:44:46  ======================================================================
07:44:46  FAIL: test_total_space_limit_of_commitlog (commitlog_test.TestCommitLog)
07:44:46  ----------------------------------------------------------------------
07:44:46  Traceback (most recent call last):
07:44:46    File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/commitlog_test.py", line 42, in tearDown
07:44:46      super(TestCommitLog, self).tearDown()
07:44:46    File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/dtest.py", line 1134, in tearDown
07:44:46      self.cleanUpCluster()
07:44:46    File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/dtest.py", line 1191, in cleanUpCluster
07:44:46      raise AssertionError("Core file(s) found.{}".format("" if failed else " Marking test as failed."))
07:44:46  AssertionError: Core file(s) found. Marking test as failed.
07:44:46  
07:44:46  ======================================================================
07:44:46  FAIL: test_total_space_limit_of_commitlog_with_small_limit (commitlog_test.TestCommitLog)
07:44:46  ----------------------------------------------------------------------
07:44:46  Traceback (most recent call last):
07:44:46    File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/commitlog_test.py", line 42, in tearDown
07:44:46      super(TestCommitLog, self).tearDown()
07:44:46    File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/dtest.py", line 1134, in tearDown
07:44:46      self.cleanUpCluster()
07:44:46    File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/dtest.py", line 1191, in cleanUpCluster
07:44:46      raise AssertionError("Core file(s) found.{}".format("" if failed else " Marking test as failed."))
07:44:46  AssertionError: Core file(s) found. Marking test as failed.
07:44:46  
07:44:46  ======================================================================
07:44:46  FAIL: test_total_space_limit_of_commitlog_with_medium_limit (commitlog_test.TestCommitLog)
07:44:46  ----------------------------------------------------------------------
07:44:46  Traceback (most recent call last):
07:44:46    File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/commitlog_test.py", line 42, in tearDown
07:44:46      super(TestCommitLog, self).tearDown()
07:44:46    File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/dtest.py", line 1134, in tearDown
07:44:46      self.cleanUpCluster()
07:44:46    File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/dtest.py", line 1191, in cleanUpCluster
07:44:46      raise AssertionError("Core file(s) found.{}".format("" if failed else " Marking test as failed."))
07:44:46  AssertionError: Core file(s) found. Marking test as failed.
```

### Failed to decode the coredump

```
$ gdb /usr/lib/debug/opt/scylladb/libexec/scylla-4.6.dev-0.20210418.dbd0b9a3ef.x86_64.debug node1-scylla.2064.1618875879.core 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-119.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/lib/debug/opt/scylladb/libexec/scylla-4.6.dev-0.20210418.dbd0b9a3ef.x86_64.debug...Segmentation fault (core dumped)
```
