### ISSUE TITLE
artifacts-centos7-test: scylla_util.py fails with - ModuleNotFoundError: No module named 'scylla_sysconfdir'

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#8456]
ERROR - 
```
2021-04-12 09:47:27.896: (TestFrameworkEvent Severity.ERROR), source=ArtifactsTest.SetUp()
exception=[Node artifacts-centos7-jenkins-db-node-b27a579d-0-1 [34.75.20.208 | 10.142.0.21] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --help'
Exit code: 1
Stdout:
Stderr:
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_setup", line 31, in <module>
from scylla_util import *
File "/opt/scylladb/scripts/scylla_util.py", line 37, in <module>
from scylla_sysconfdir import SYSCONFDIR
ModuleNotFoundError: No module named 'scylla_sysconfdir'
Traceback (most recent call last):
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos7-test/scylla-cluster-tests/sdcm/cluster.py", line 3426, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos7-test/scylla-cluster-tests/sdcm/cluster.py", line 4081, in node_setup
self._scylla_post_install(node, install_scylla, devname)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos7-test/scylla-cluster-tests/sdcm/cluster.py", line 4149, in _scylla_post_install
node.scylla_setup(disks, devname)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos7-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 110, in inner
res = func(*args, **kwargs)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos7-test/scylla-cluster-tests/sdcm/cluster.py", line 2250, in scylla_setup
result = self.remoter.run('sudo /usr/lib/scylla/scylla_setup --help')
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos7-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos7-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos7-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos7-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --help'
Exit code: 1
Stdout:
Stderr:
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_setup", line 31, in <module>
from scylla_util import *
File "/opt/scylladb/scripts/scylla_util.py", line 37, in <module>
from scylla_sysconfdir import SYSCONFDIR
ModuleNotFoundError: No module named 'scylla_sysconfdir'
```

Test details
Test: artifacts_test.ArtifactsTest.test_scylla_service
Build number: 117
Backend: gce: us-east1
Kernel version: 3.10.0-1160.21.1.el7.x86_64
Test-id: b27a579d-7f67-44b9-8ab5-800812b4cc51
Start time: 2021-04-12 09:40:33
End time: 2021-04-12 09:47:41
Started by user: timer
Private repo: https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-3.3.repo
Test result
FAILED
System under test
ScyllaDB version:
ScyllaDB repo: https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-3.3.repo
Actual gce image used: centos-7-v20210401
AWS region: us-east1
Instance type: n1-standard-2
Scylla packages installed:
No scylla packages are installed. Please check log files.

**Comment by slivne** [comment]
related to https://github.com/scylladb/scylla/issues/8385 that is supposed to be reverted

**Comment by yaronkaikov** [comment]
@avikivity @slivne This patch made it to enterprise as well, it should be reverted also. This is the merge commit: https://github.com/scylladb/scylla-enterprise/commit/901c86c5a5f4e30bf77f5a19d97acd99179c2689

**Comment by mykaul** [comment]
> @avikivity @slivne This patch made it to enterprise as well, it should be reverted also. This is the merge commit: [scylladb/scylla-enterprise@901c86c](https://github.com/scylladb/scylla-enterprise/commit/901c86c5a5f4e30bf77f5a19d97acd99179c2689)

@yaronkaikov :
1. Was the enterprise commit reverted?
2. Should this issue be re-opened?

Regardless, removing the 'backport candidate' label for now.

**Comment by yaronkaikov** [comment]
> > @avikivity @slivne This patch made it to enterprise as well, it should be reverted also. This is the merge commit: [scylladb/scylla-enterprise@901c86c](https://github.com/scylladb/scylla-enterprise/commit/901c86c5a5f4e30bf77f5a19d97acd99179c2689)
> 
> @yaronkaikov :
> 
> 1. Was the enterprise commit reverted?
> 2. Should this issue be re-opened?
> 
> Regardless, removing the 'backport candidate' label for now.

@mykaul This commit was reverted almost 2 years ago
