### ISSUE TITLE
ScyllaDb sometimes fails to start up: INFO gave up: scylla entered FATAL state, too many start retries too quickly

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla#8458]
*Installation details*
Scylla version (or git commit hash): 4.3.1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04.2

*Steps to reproduce*
This issue is not reproducable consistently. I use ScyllaDb in docker-compose for testing with Github Actions. When it fails to start up, I hit the restart workflow button a few times until it works, but it is really annoying to keep doing this. 

I tried to reproduce the problem in a small reproduction repository which can be found here: https://github.com/Jasperav/docker-compose-check/actions. Ignore the green checkmarks, the errors are thrown in a separate executable (because I don't like to write yaml code). 

This is an example of a failed run: https://github.com/Jasperav/docker-compose-check/runs/2312446849?check_suite_focus=true and unfold step 'Start docker compose'. The exectable doesn't do very much, the code can be found here: https://github.com/Jasperav/docker-compose-check/blob/master/src/main.rs. It comes down do this:

- Wait for docker-compose to start up (3 minutes)
- Run docker exec somescylla nodetool status
- Run docker exec somescylla cqlsh -f /project/setup.cql
- Run docker exec somescylla nodetool status

This is my docker-compose file:

```
name: ScyllaDB-tests

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          path: ./server
      - name: Start docker compose
        run: |
          cd ./server
          docker-compose up -d
          ls
          cargo run
```

The logging tells me this:

```
 2021-04-12 11:20:30,370 INFO Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
2021-04-12 11:20:30,370 INFO Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
2021-04-12 11:20:30,370 INFO Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
2021-04-12 11:20:30,370 INFO Included extra file "/etc/supervisord.conf.d/sshd-server.conf" during parsing
2021-04-12 11:20:30,394 INFO RPC interface 'supervisor' initialized
2021-04-12 11:20:30,394 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2021-04-12 11:20:30,394 INFO supervisord started with pid 26
2021-04-12 11:20:31,397 INFO spawned: 'scylla' with pid 29
2021-04-12 11:20:31,399 INFO spawned: 'scylla-housekeeping' with pid 30
2021-04-12 11:20:31,401 INFO spawned: 'sshd' with pid 31
2021-04-12 11:20:31,417 INFO spawned: 'scylla-jmx' with pid 34
2021-04-12 11:20:31,435 INFO spawned: 'rsyslog' with pid 37
2021-04-12 11:20:31,460 INFO spawned: 'node-exporter' with pid 40
Generating public/private ed25519 key pair.
Your identification has been saved in /etc/ssh/ssh_host_ed25519_key.
Your public key has been saved in /etc/ssh/ssh_host_ed25519_key.pub.
The key fingerprint is:
SHA256:q11TFUfHDmY3RXTvWFBVtZ+EsQdhp6ELsex/f4xMjic root@4a629a3de7a6
The key's randomart image is:
+--[ED25519 256]--+
|         .   *+B^|
|        . o o %=B|
|         + . *.B+|
|        . . ..o++|
|        S. .. ..o|
|         ...  .  |
|        . o. * o |
|       o . .E * o|
|      . .    o ..|
+----[SHA256]-----+
2021-04-12 11:20:32,567 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-12 11:20:32,569 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-12 11:20:32,569 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-12 11:20:32,569 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-12 11:20:32,569 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-12 11:20:32,569 INFO success: node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Scylla version 4.3.1-0.20210210.46650adcd with build-id bfaa518f22098de476b961b707925c71441bb81b starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --smp 2 --overprovisioned --listen-address 172.18.0.5 --rpc-address 172.18.0.5 --seed-provider-parameters seeds=172.18.0.5 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, smp: 2, overprovisioned, listen-address: 172.18.0.5, rpc-address: 172.18.0.5, seed-provider-parameters: seeds=172.18.0.5, blocked-reactor-notify-ms: 999999999]
2021-04-12 11:20:33,374 INFO exited: scylla (exit status 1; not expected)
Connecting to http://localhost:10000
Starting the JMX server
2021-04-12 11:20:33,935 INFO spawned: 'scylla' with pid 68
2021-04-12 11:20:35,018 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Scylla version 4.3.1-0.20210210.46650adcd with build-id bfaa518f22098de476b961b707925c71441bb81b starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --smp 2 --overprovisioned --listen-address 172.18.0.5 --rpc-address 172.18.0.5 --seed-provider-parameters seeds=172.18.0.5 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, smp: 2, overprovisioned, listen-address: 172.18.0.5, rpc-address: 172.18.0.5, seed-provider-parameters: seeds=172.18.0.5, blocked-reactor-notify-ms: 999999999]
JMX is enabled to receive remote connections on port: 7199
2021-04-12 11:20:37,120 INFO exited: scylla (exit status 1; not expected)
2021-04-12 11:20:38,124 INFO spawned: 'scylla' with pid 89
Scylla version 4.3.1-0.20210210.46650adcd with build-id bfaa518f22098de476b961b707925c71441bb81b starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --smp 2 --overprovisioned --listen-address 172.18.0.5 --rpc-address 172.18.0.5 --seed-provider-parameters seeds=172.18.0.5 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, smp: 2, overprovisioned, listen-address: 172.18.0.5, rpc-address: 172.18.0.5, seed-provider-parameters: seeds=172.18.0.5, blocked-reactor-notify-ms: 999999999]
2021-04-12 11:20:39,344 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
The key fingerprint is:
SHA256:yUvUkY23KggJmvH41EcZQ+EgMqvs2tpIuxlI7AqVYVY root@4a629a3de7a6
The key's randomart image is:
+---[RSA 4096]----+
|o . E.=+  .+     |
|.+.o oo. .o.o    |
|.*+o o. . .. .   |
|Booo+ .o .  .    |
|.*o  o .S  .     |
|=..   .....      |
|o=      ..       |
|=++              |
|==+              |
+----[SHA256]-----+
2021-04-12 11:20:39,634 INFO exited: scylla (exit status 1; not expected)
2021-04-12 11:20:40,637 INFO spawned: 'scylla' with pid 107
Scylla version 4.3.1-0.20210210.46650adcd with build-id bfaa518f22098de476b961b707925c71441bb81b starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --smp 2 --overprovisioned --listen-address 172.18.0.5 --rpc-address 172.18.0.5 --seed-provider-parameters seeds=172.18.0.5 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, smp: 2, overprovisioned, listen-address: 172.18.0.5, rpc-address: 172.18.0.5, seed-provider-parameters: seeds=172.18.0.5, blocked-reactor-notify-ms: 999999999]
2021-04-12 11:20:41,096 INFO exited: scylla (exit status 1; not expected)
2021-04-12 11:20:42,098 INFO spawned: 'scylla' with pid 119
Scylla version 4.3.1-0.20210210.46650adcd with build-id bfaa518f22098de476b961b707925c71441bb81b starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --smp 2 --overprovisioned --listen-address 172.18.0.5 --rpc-address 172.18.0.5 --seed-provider-parameters seeds=172.18.0.5 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, smp: 2, overprovisioned, listen-address: 172.18.0.5, rpc-address: 172.18.0.5, seed-provider-parameters: seeds=172.18.0.5, blocked-reactor-notify-ms: 999999999]
2021-04-12 11:20:42,532 INFO exited: scylla (exit status 1; not expected)
2021-04-12 11:20:44,535 INFO spawned: 'scylla' with pid 131
Scylla version 4.3.1-0.20210210.46650adcd with build-id bfaa518f22098de476b961b707925c71441bb81b starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --smp 2 --overprovisioned --listen-address 172.18.0.5 --rpc-address 172.18.0.5 --seed-provider-parameters seeds=172.18.0.5 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, smp: 2, overprovisioned, listen-address: 172.18.0.5, rpc-address: 172.18.0.5, seed-provider-parameters: seeds=172.18.0.5, blocked-reactor-notify-ms: 999999999]
2021-04-12 11:20:45,044 INFO exited: scylla (exit status 1; not expected)
2021-04-12 11:20:48,050 INFO spawned: 'scylla' with pid 143
Scylla version 4.3.1-0.20210210.46650adcd with build-id bfaa518f22098de476b961b707925c71441bb81b starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --smp 2 --overprovisioned --listen-address 172.18.0.5 --rpc-address 172.18.0.5 --seed-provider-parameters seeds=172.18.0.5 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, smp: 2, overprovisioned, listen-address: 172.18.0.5, rpc-address: 172.18.0.5, seed-provider-parameters: seeds=172.18.0.5, blocked-reactor-notify-ms: 999999999]
2021-04-12 11:20:48,556 INFO exited: scylla (exit status 1; not expected)
2021-04-12 11:20:49,558 INFO gave up: scylla entered FATAL state, too many start retries too quickly
```

**Comment by slivne** [comment]
@Jasperav I am not sure why this is happening and without additional info on why scylla fails to start its hard to tell.

You can try to limit scylla resources by adding additional limitations, 

here is a sample from scylla university

https://github.com/scylladb/scylla-code-samples/blob/master/mms/docker-compose.yml

**Comment by Jasperav** [comment]
@slivne Thanks I will try it with the provided docker compose file. What additional info do you need? I included the logging. The reproduction path is also simple: 

1. Fork the project
2. Run the action a few times until it fails

**Comment by kylerchin** [comment]
please help i don't understand why i'm bugging out like this
![image](https://user-images.githubusercontent.com/7539174/118224687-86f05e00-b438-11eb-9d93-f3adcb35fa40.png)
![Screenshot from 2021-05-13 21-50-39](https://user-images.githubusercontent.com/7539174/118224726-966fa700-b438-11eb-9f51-a09b64868710.png)

**Comment by jm-ds** [comment]
I have the identical setup and am getting exactly the same error. Mine is not random, it's on every start. This is running on a workstation with a 16core amd CPU with 16gb ram and a 1TB nvme

Installation details
Scylla version (or git commit hash): 4.3.1
Cluster size: 1 (also fails with 3)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04.2

**Comment by JonasHiltl** [comment]
Same here with docker compose
```
version: "3.1"

services:
  scylla:
    container_name: scylla
    image: scylladb/scylla:latest
    command: --smp 2 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9042:9042"
    volumes:
      - ./_data/scylla1:/var/lib/scylla/data
```

**Comment by brianlu-scale** [comment]
Has there been any update on this?

**Comment by mykaul** [comment]
> Has there been any update on this?

@brianlu-scale - have you seen that happening in recent 5.x series?

**Comment by brianlu-scale** [comment]
Yes. Specifically, we had the same error come up in the following situation:

Our Scylla cluster is deployed in a kubernetes cluster on specific instance types (these instance types only have 4 CPUs allotted). We accidentally set the resource limits the Scylla cluster to 6 CPUs. As a result, Scylla tried to startup 6 threads, Seastar saw that there were only 4 cores, and then promptly failed, causing the error we saw above.

**Comment by shreyaskaundinya** [comment]
Here's my docker-compose file 

```yaml
version: '3'

services:
    pn_dn_db:
        container_name: pn_db
        image: scylladb/scylla

        ports:
            - '9042:9042'

        networks:
            - public_node
            - bridge

networks:
    public_node:

    bridge:
        driver: bridge
```

using the command 

`docker-compose up --build`

I'm getting a very similar issue ...

```
pn_db  | running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
pn_db  | running: (['/opt/scylladb/scripts/scylla_io_setup'],)
pn_db  | 2023-05-06 03:32:02,126 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
pn_db  | 2023-05-06 03:32:02,127 INFO Included extra file "/etc/supervisord.conf.d/rsyslog.conf" during parsing
pn_db  | 2023-05-06 03:32:02,127 INFO Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
pn_db  | 2023-05-06 03:32:02,127 INFO Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
pn_db  | 2023-05-06 03:32:02,127 INFO Included extra file "/etc/supervisord.conf.d/scylla-node-exporter.conf" during parsing
pn_db  | 2023-05-06 03:32:02,127 INFO Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
pn_db  | 2023-05-06 03:32:02,127 INFO Included extra file "/etc/supervisord.conf.d/sshd-server.conf" during parsing
pn_db  | 2023-05-06 03:32:02,140 INFO RPC interface 'supervisor' initialized
pn_db  | 2023-05-06 03:32:02,141 CRIT Server 'inet_http_server' running without any HTTP authentication checking
pn_db  | 2023-05-06 03:32:02,141 INFO supervisord started with pid 26
pn_db  | 2023-05-06 03:32:03,146 INFO spawned: 'rsyslog' with pid 28
pn_db  | 2023-05-06 03:32:03,148 INFO spawned: 'scylla' with pid 29
pn_db  | 2023-05-06 03:32:03,151 INFO spawned: 'scylla-housekeeping' with pid 30
pn_db  | 2023-05-06 03:32:03,153 INFO spawned: 'scylla-jmx' with pid 32
pn_db  | 2023-05-06 03:32:03,155 INFO spawned: 'scylla-node-exporter' with pid 35
pn_db  | 2023-05-06 03:32:03,158 INFO spawned: 'sshd' with pid 37
pn_db  | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
pn_db  | rsyslogd: activation of module imklog failed [v8.2001.0 try https://www.rsyslog.com/e/2145 ]
pn_db  | ts=2023-05-06T03:32:03.314Z caller=node_exporter.go:182 level=info msg="Starting node_exporter" version="(version=1.3.1, branch=HEAD, revision=a2321e7b940ddcff26873612bccdf7cd4c42b6b6)"
pn_db  | ts=2023-05-06T03:32:03.316Z caller=node_exporter.go:183 level=info msg="Build context" build_context="(go=go1.17.3, user=root@243aafa5525c, date=20211205-11:09:49)"
pn_db  | ts=2023-05-06T03:32:03.316Z caller=node_exporter.go:185 level=warn msg="Node Exporter is running as root user. This exporter is designed to run as unpriviledged user, root is not required."
pn_db  | ts=2023-05-06T03:32:03.320Z caller=filesystem_common.go:111 level=info collector=filesystem msg="Parsed flag --collector.filesystem.mount-points-exclude" flag=^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+)($|/)
pn_db  | ts=2023-05-06T03:32:03.321Z caller=filesystem_common.go:113 level=info collector=filesystem msg="Parsed flag --collector.filesystem.fs-types-exclude" flag=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:108 level=info msg="Enabled collectors"
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=arp
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=bcache
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=bonding
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=btrfs
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=conntrack
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=cpu
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=cpufreq
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=diskstats
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=dmi
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=edac
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=entropy
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=fibrechannel
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=filefd
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=filesystem
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=hwmon
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=infiniband
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=interrupts
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=ipvs
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=loadavg
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=mdadm
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=meminfo
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=netclass
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=netdev
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=netstat
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=nfs
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=nfsd
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=nvme
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=os
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=powersupplyclass
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=pressure
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=rapl
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=schedstat
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=sockstat
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=softnet
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=stat
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=tapestats
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=textfile
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=thermal_zone
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=time
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=timex
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=udp_queues
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=uname
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=vmstat
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=xfs
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:115 level=info collector=zfs
pn_db  | ts=2023-05-06T03:32:03.322Z caller=node_exporter.go:199 level=info msg="Listening on" address=:9100
pn_db  | ts=2023-05-06T03:32:03.325Z caller=tls_config.go:195 level=info msg="TLS is disabled." http2=false
pn_db  | Scylla version 5.1.8-0.20230319.c90807d29f30 with build-id 470cfa560e66dc8c816a5b45db4349f2d7d91553 starting ...
pn_db  | command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.24.0.2 172.22.0.2 --rpc-address 172.24.0.2 172.22.0.2 --seed-provider-parameters seeds=172.24.0.2 172.22.0.2 --alternator-address 172.24.0.2 172.22.0.2 --blocked-reactor-notify-ms 999999999"
pn_db  | parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.24.0.2, (positional) 172.22.0.2, rpc-address: 172.24.0.2, (positional) 172.22.0.2, seed-provider-parameters: seeds=172.24.0.2, (positional) 172.22.0.2, alternator-address: 172.24.0.2, (positional) 172.22.0.2, blocked-reactor-notify-ms, (positional) 999999999]
pn_db  | error: too many positional options have been specified on the command line
pn_db  |
pn_db  | Try --help.
pn_db  | 2023-05-06 03:32:04,051 INFO exited: scylla (exit status 2; not expected)
pn_db  | Connecting to http://localhost:10000
pn_db  | Starting the JMX server
pn_db  | 2023-05-06 03:32:04,377 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pn_db  | 2023-05-06 03:32:04,377 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pn_db  | 2023-05-06 03:32:04,378 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pn_db  | 2023-05-06 03:32:04,378 INFO success: scylla-node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pn_db  | 2023-05-06 03:32:04,378 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pn_db  | JMX is enabled to receive remote connections on port: 7199
pn_db  | 2023-05-06 03:32:05,784 INFO spawned: 'scylla' with pid 77
pn_db  | Scylla version 5.1.8-0.20230319.c90807d29f30 with build-id 470cfa560e66dc8c816a5b45db4349f2d7d91553 starting ...
pn_db  | command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.24.0.2 172.22.0.2 --rpc-address 172.24.0.2 172.22.0.2 --seed-provider-parameters seeds=172.24.0.2 172.22.0.2 --alternator-address 172.24.0.2 172.22.0.2 --blocked-reactor-notify-ms 999999999"
pn_db  | parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.24.0.2, (positional) 172.22.0.2, rpc-address: 172.24.0.2, (positional) 172.22.0.2, seed-provider-parameters: seeds=172.24.0.2, (positional) 172.22.0.2, alternator-address: 172.24.0.2, (positional) 172.22.0.2, blocked-reactor-notify-ms, (positional) 999999999]
pn_db  | error: too many positional options have been specified on the command line
pn_db  |
pn_db  | Try --help.
pn_db  | 2023-05-06 03:32:06,334 INFO exited: scylla (exit status 2; not expected)
pn_db  | 2023-05-06 03:32:08,338 INFO spawned: 'scylla' with pid 95
pn_db  | Traceback (most recent call last):
pn_db  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
pn_db  |     args.func(args)
pn_db  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
pn_db  |     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
pn_db  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
pn_db  |     return get_json_from_url("http://" + api_address + path)
pn_db  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
pn_db  |     raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
pn_db  | RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
pn_db  | Scylla version 5.1.8-0.20230319.c90807d29f30 with build-id 470cfa560e66dc8c816a5b45db4349f2d7d91553 starting ...
pn_db  | command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.24.0.2 172.22.0.2 --rpc-address 172.24.0.2 172.22.0.2 --seed-provider-parameters seeds=172.24.0.2 172.22.0.2 --alternator-address 172.24.0.2 172.22.0.2 --blocked-reactor-notify-ms 999999999"
pn_db  | parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.24.0.2, (positional) 172.22.0.2, rpc-address: 172.24.0.2, (positional) 172.22.0.2, seed-provider-parameters: seeds=172.24.0.2, (positional) 172.22.0.2, alternator-address: 172.24.0.2, (positional) 172.22.0.2, blocked-reactor-notify-ms, (positional) 999999999]
pn_db  | error: too many positional options have been specified on the command line
pn_db  |
pn_db  | Try --help.
pn_db  | 2023-05-06 03:32:08,905 INFO exited: scylla (exit status 2; not expected)
pn_db  | 2023-05-06 03:32:11,910 INFO spawned: 'scylla' with pid 111
pn_db  | Scylla version 5.1.8-0.20230319.c90807d29f30 with build-id 470cfa560e66dc8c816a5b45db4349f2d7d91553 starting ...
pn_db  | command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.24.0.2 172.22.0.2 --rpc-address 172.24.0.2 172.22.0.2 --seed-provider-parameters seeds=172.24.0.2 172.22.0.2 --alternator-address 172.24.0.2 172.22.0.2 --blocked-reactor-notify-ms 999999999"
pn_db  | parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.24.0.2, (positional) 172.22.0.2, rpc-address: 172.24.0.2, (positional) 172.22.0.2, seed-provider-parameters: seeds=172.24.0.2, (positional) 172.22.0.2, alternator-address: 172.24.0.2, (positional) 172.22.0.2, blocked-reactor-notify-ms, (positional) 999999999]
pn_db  | error: too many positional options have been specified on the command line
pn_db  |
pn_db  | Try --help.
pn_db  | 2023-05-06 03:32:12,485 INFO exited: scylla (exit status 2; not expected)
pn_db  | 2023-05-06 03:32:13,486 INFO gave up: scylla entered FATAL state, too many start retries too quickly
```

**Comment by RinatzZak** [comment]
Hello! There was the same problem when running the test container, Scylla version 4.5.6. It was decided by the command  withCommand("--developer-mode 1 --smp 1").  After that, everything always started successfully and worked
