### ISSUE TITLE
regression in toppartitions dtests

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8459]
Starting in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/781/testReport/toppartitions_test/
Scylla version bb9a109c1aafe9c579b0654f2403df12d7f1d6ac
Several dtest from toppartitions_test.py started failing as follows:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/781/testReport/toppartitions_test/TestTopPartitions/test_any_of_required_parameters_is_missing/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/toppartitions_test.py", line 300, in test_any_of_required_parameters_is_missing
    details = self.run_toppartitions_with_wrong_parameters(node)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/toppartitions_test.py", line 160, in run_toppartitions_with_wrong_parameters
    node.nodetool(self.cmd)
  File "/usr/lib64/python3.7/unittest/case.py", line 220, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/usr/lib64/python3.7/unittest/case.py", line 136, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: NodetoolError not raised
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/781/testReport/toppartitions_test/TestTopPartitions/test_top_5_paritions_write_samplers_and_empty_read_sample/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/toppartitions_test.py", line 418, in test_top_5_paritions_write_samplers_and_empty_read_sample
    expected_results=expected_write_toppartition_key_count)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/toppartitions_test.py", line 258, in verifyTopPartitionCounterForSample
    "Expected results: {}\nActual results: {}.".format(expected_results, actual_results["partitions"]))
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 5 : Expected results: [('k5', '100'), ('k6', '100'), ('k7', '100'), ('k8', '100'), ('k9', '100')]
Actual results: OrderedDict().
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/781/testReport/toppartitions_test/TestTopPartitions/test_write_into_one_paritions_to_different_rows/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/toppartitions_test.py", line 760, in test_write_into_one_paritions_to_different_rows
    expected_results=expected_write_toppartition_results)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/toppartitions_test.py", line 258, in verifyTopPartitionCounterForSample
    "Expected results: {}\nActual results: {}.".format(expected_results, actual_results["partitions"]))
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 10 : Expected results: [('1:1', '150'), ('1:0', '15'), ('1:2', '15'), ('1:3', '15'), ('1:4', '15'), ('1:5', '15'), ('1:6', '15'), ('1:7', '15'), ('1:8', '15'), ('1:9', '15')]
Actual results: OrderedDict().
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/781/testReport/toppartitions_test/TestTopPartitions/test_writes_sample_for_10_partitions_with_100_op_and_empty_reads_sample/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/toppartitions_test.py", line 347, in test_writes_sample_for_10_partitions_with_100_op_and_empty_reads_sample
    expected_results=expected_write_toppartition_key_count)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/toppartitions_test.py", line 258, in verifyTopPartitionCounterForSample
    "Expected results: {}\nActual results: {}.".format(expected_results, actual_results["partitions"]))
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 10 : Expected results: [('k0', '100'), ('k1', '100'), ('k2', '100'), ('k3', '100'), ('k4', '100'), ('k5', '100'), ('k6', '100'), ('k7', '100'), ('k8', '100'), ('k9', '100')]
Actual results: OrderedDict().
```

I reproduced this with latest dtest version to verify that the trigger for the regression is a change in scylla rather than in the test.
See https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/511/
vs. https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/512/

**Comment by raphaelsc** [comment]
given that the run 780 succeeded, the possible guilty commit is in the range: 6a2377a233b6708598777bfb11a18afcab27c1e6..bb9a109c1aafe9c579b0654f2403df12d7f1d6ac

**Comment by raphaelsc** [comment]
```
commit bbec43f9a10598c4f8eb475b218827247dfa8c68
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Mar 31 17:38:03 2021 +0300

    Update tools/java submodule
    
    * tools/java ccc4201ded...fb21784b91 (2):
      > fix: Add dummy implementation of getToppartitions
      > nodetool: Make toppartitions call the generic endpoint
    
    Fixes #4520.

```

**Comment by bhalevy** [comment]
Right, this is caused by https://github.com/scylladb/scylla-tools-java/commit/a8a3f6cb13367ddac06e4fe6c4fccf019f314bfb

**Comment by raphaelsc** [comment]
Looks like a API change broke toppartitions dtest. /CC @StarostaGit, please help us here.

**Comment by bhalevy** [comment]
@StarostaGit, @avikivity I think we should revert the changes from tools-java and sort this out out of tree before re-merging a correct version.

**Comment by bhalevy** [comment]
unless there is an easy fix to the test of course...

**Comment by StarostaGit** [comment]
Looking into it rn

**Comment by avikivity** [comment]
Possibly run_toppartitions_with_wrong_parameters is now a false positive since topppartitions command line is more relaxed. Or perhaps we don't check errors rigorously enough now.

**Comment by bhalevy** [comment]
@avikivity I think you meant test_any_of_required_parameters_is_missing

**Comment by bhalevy** [comment]
`run_toppartitions_with_wrong_parameters` is just the service routine, it's caller decides what parameters to omit.
It's called from `test_any_of_required_parameters_is_missing` which now fails since the missing parameters no longer produce the expected error.

**Comment by bhalevy** [comment]
ping @StarostaGit

**Comment by StarostaGit** [comment]
In the middle of fixing, had to finish something first
