### ISSUE TITLE
Repair -local not using correct dc info

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#851]
export CASSANDRA_DIR=/home/shlomi/scylla; nosetests -v -s repair_additional_test.py:RepairAdditionalTest.repair_option_dc_test

it fails on monster (jenkins)

```

======================================================================
ERROR: repair_option_dc_test (repair_additional_test.RepairAdditionalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/repair_additional_test.py", line 803, in repair_option_dc_test
    info=node1.repair(['-local', 'ks'])
  File "/home/shlomi/urchin-ccm/ccmlib/node.py", line 1171, in repair
    return self.nodetool(cmd, **kwargs)
  File "/home/shlomi/urchin-ccm/ccmlib/node.py", line 693, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
NodetoolError: Nodetool command '/home/shlomi/scylla/resources/cassandra/bin/nodetool -h localhost -p 7100 repair -local ks' failed; exit status: 2; stdout: [2016-01-27 14:57:33,056] Starting repair command #1, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)
[2016-01-27 14:57:33,167] Repair session 1 failed
[2016-01-27 14:57:33,167] Repair session 1 finished
; stderr: error: nodetool failed, check server logs
-- StackTrace --
java.lang.RuntimeException: nodetool failed, check server logs
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:290)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:202)


-------------------- >> begin captured logging << --------------------
```

checking node1 log

```
INFO  [shard 0] rpc - client 127.0.0.4: client connection dropped: Connection refused
INFO  [shard 0] rpc - client 127.0.0.4: client connection dropped: Connection refused
INFO  [shard 0] rpc - client 127.0.0.4: client connection dropped: Connection refused
INFO  [shard 0] rpc - client 127.0.0.4: client connection dropped: Connection refused
INFO  [shard 0] gossip - Node 127.0.0.4 has restarted, now UP
INFO  [shard 0] gossip - InetAddress 127.0.0.4 is now UP
INFO  [shard 0] storage_service - Node 127.0.0.4 state jump to normal
INFO  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 127.0.0.4
INFO  [shard 0] repair - starting user-requested repair for keyspace ks, repair id 1, options {dataCenters=dc2, incremental=false, parallelism=0, primaryRange=false}
INFO  [shard 0] repair - repair 1 failed - std::runtime_error (The current host must be part of the repair)
```

it seems that repair --local did not use the correct dc info of node1 which is dc1 (according to the logs it used dc2)

scylla

commit c4dafe24f5de5ab276906d955d0ffda9c881bb88
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Wed Jan 27 13:29:01 2016 +0200

    Update scylla-ami submodule
    
    * dist/ami/files/scylla-ami 77cde04...e284bcd (2):
      > Run scylla.yaml construction only once
      > Revert "Run scylla.yaml construction only once"

scylla-jmx

commit 3e1a8961a2e05809c221f9473159e87027ff18e3
Author: Amnon Heiman <amnon@scylladb.com>
Date:   Thu Jan 21 11:10:12 2016 +0200

    StorageService: setLoggingLevel
    
    This patch uses the system api to set log level.
    After this patch the nodetool setloglevel would support modifying a log
    level of a log object.
    
    Signed-off-by: Amnon Heiman <amnon@scylladb.com>
    Message-Id: <1453367412-29722-1-git-send-email-amnon@scylladb.com>

**Comment by nyh** [comment]
Thanks for the lead on the "-local" bug. I'll look into it.

**Comment by nyh** [comment]
By the way, the repair code doesn't even know about "-local" option - as you can see in the log you pasted, the JMX ode is passing it "dataCenters=dc2". I'll need to check why.

**Comment by nyh** [comment]
In NodeTool.java, there is
```java
        @Option(title = "local_dc", name = {"-local", "--in-local-dc"}, description = "Use -local to only repair against nodes in the same datacenter")
        private boolean localDC = false;
...
if (localDC)
                        dataCenters = newArrayList(probe.getDataCenter());
```

So apparently NodeProbe.getDataCenter() doesn't return the right thing.
looking at NodeProbe.java, I see
```java
    public String getDataCenter()
    {
        try
        {
            return getEndpointSnitchInfoProxy().getDatacenter(getEndpoint());
```

This looks like gibberish to me. @amnonh , @slivne , do you know if this getDataCenter() supposed to be working? Do we have an independent test for it (unrelated to repair)?

**Comment by nyh** [comment]
Note to self: I need to verify what kind of error message Cassandra provides when repair failed because of a wrong "-dc" option. It's not nice when the error message is "repair failed, check the logs" - it would have been much better to have the actual error ("The current host must be part of the repair") up front. But maybe that's also how things behave in Cassandra?

**Comment by slivne** [comment]
@amnonh you need to answer the above ... I'm reassigning this to you

**Comment by penberg** [comment]
@nyh says that commit https://github.com/scylladb/scylla-jmx/commit/691f86983b22a8a0f27c7d85818804c1c9932152 probably fixes the issue.

**Comment by nyh** [comment]
Indeed. @slivne can you please cause Jenkins to rerun the dtest to verify that the "local_dc_repair_test" and "repair_option_dc_test" should both pass now?

**Comment by slivne** [comment]
works on branch-0.18

**Comment by slivne** [comment]
tried on 1.0.1 it does not work

nodetool repair --in-local-dc <keyspace> <cf>

or

nodetool repair --local <keyspace> <cf> 

do not work

nodetool repair -dc <dc> <keyspace> <cf> does work

**Comment by nyh** [comment]
Really odd, it worked in the past and nothing changed in this area recently as far as I know.
How do you define that "it does not work" - did it fail the repair_option_dc_test dtest which is supposed to test this option (and in the past caught the previous bugs we had there)?

**Comment by slivne** [comment]
I tried to run it and received the following

```

error: Index: 0, Size: 0

-- StackTrace --

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

at java.util.ArrayList.rangeCheck(ArrayList.java:653)

at java.util.ArrayList.get(ArrayList.java:429)

at org.apache.cassandra.tools.NodeProbe.getEndpoint(NodeProbe.java:812)

at org.apache.cassandra.tools.NodeProbe.getDataCenter(NodeProbe.java:830)

at org.apache.cassandra.tools.NodeTool$Repair.execute(NodeTool.java:1890)

at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:288)

at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:202)


```


I'll check if those tests are running or not - thanks

**Comment by nyh** [comment]
@amnonh the error messages quoted by @slivne look like they come from the JMX stuff. Does this ring a bell?

**Comment by slivne** [comment]
@amnonh ping

**Comment by amnonh** [comment]
I can't reproduce, here are some examples:
./bin/nodetool -p 7100 repair -local -- keyspace1 standard1
[2016-05-23 11:08:14,823] Starting repair command #2, repairing 1 ranges for keyspace keyspace1 (parallelism=SEQUENTIAL, full=true)
[2016-05-23 11:08:14,929] Repair session 2 finished
[amnon@localhost cassandra (master)]$ ./bin/nodetool -p 7100 repair -local --
[2016-05-23 11:08:26,883] Starting repair command #3, repairing 1 ranges for keyspace OpsCenter (parallelism=SEQUENTIAL, full=true)
[2016-05-23 11:08:26,989] Repair session 3 finished
[2016-05-23 11:08:27,095] Starting repair command #4, repairing 1 ranges for keyspace keyspace1 (parallelism=SEQUENTIAL, full=true)
[2016-05-23 11:08:27,203] Repair session 4 finished
[2016-05-23 11:08:27,318] Starting repair command #5, repairing 1 ranges for keyspace amnon (parallelism=SEQUENTIAL, full=true)
[2016-05-23 11:08:27,423] Repair session 5 finished
[2016-05-23 11:08:27,621] Repair session 6 finished
[amnon@localhost cassandra (master)]$ ./bin/nodetool -p 7100 repair --in-local-dc --
[2016-05-23 11:09:28,706] Starting repair command #7, repairing 1 ranges for keyspace OpsCenter (parallelism=SEQUENTIAL, full=true)
[2016-05-23 11:09:28,814] Repair session 7 finished
[2016-05-23 11:09:28,908] Starting repair command #8, repairing 1 ranges for keyspace keyspace1 (parallelism=SEQUENTIAL, full=true)
[2016-05-23 11:09:29,014] Repair session 8 finished
[2016-05-23 11:09:29,114] Starting repair command #9, repairing 1 ranges for keyspace amnon (parallelism=SEQUENTIAL, full=true)
[2016-05-23 11:09:29,221] Repair session 9 finished
[2016-05-23 11:09:29,299] Starting repair command #10, repairing 1 ranges for keyspace system (parallelism=SEQUENTIAL, full=true)
[2016-05-23 11:09:29,403] Repair session 10 finished


Can you please add more details on how to reproduce the issue?

**Comment by slivne** [comment]
with 1.1.3 it is working closing this
