### ISSUE TITLE
Repair failed after node restart, connection between the nodes is lost

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#8510]
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.6.dev-0.20210413.163f2be277`
Cluster size: 3 nodes (i3.2xlarge)

Scylla running with shards number (live nodes):
   longevity-twcs-3h-master-db-node-e98195c4-1 (34.241.210.102 | 10.0.3.157): 8 shards
   longevity-twcs-3h-master-db-node-e98195c4-2 (3.250.92.32 | 10.0.0.76): 8 shards
   longevity-twcs-3h-master-db-node-e98195c4-4 (54.72.142.1 | 10.0.1.99): 8 shards

Scylla running with shards number (terminated nodes):
   longevity-twcs-3h-master-db-node-e98195c4-3 (54.194.238.95 | 10.0.0.235): 8 shards

OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0c1ed3bb31743bc1c` (aws: eu-west-1)

Test: `longevity-twcs-3h`
Test name: `longevity_twcs_test.TWCSLongevityTest.test_custom_time`
Test config file(s):
- [longevity-twcs-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/24db50aeb2e9fff62ca533e31a2f827172620e81/test-cases/longevity/longevity-twcs-3h.yaml)

**Issue description**

During RestartThenRepairNode nemesis node 4 (`longevity-twcs-3h-master-db-node-e98195c4-4 [54.72.142.1 | 10.0.1.99]`) has been restarted:
```
instance stop
instance start
```

When node was up and Scylla running, run `nodetool repair` on this node
```
< t:2021-04-18 12:10:20,626 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "/usr/bin/nodetool  repair "...
< t:2021-04-18 12:10:34,479 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > [2021-04-18 12:10:34,458] Starting repair command #1, repairing 1 ranges for keyspace scylla_bench (parallelism=SEQUENTIAL, full=true)
```
After 14 minutes connection between nodes in the cluster was lost despite Scylla on the nodes is running, compaction runs

node 4
```
2021-04-18T12:14:39+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !INFO    | scylla:  [shard 0] gossip - InetAddress 10.0.0.76 is now DOWN, status = NORMAL
2021-04-18T12:15:02+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla:  [shard 1] rpc - client 10.0.0.76:7000: client connection dropped: read: Connection reset by peer
2021-04-18T12:15:10+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla:  [shard 1] rpc - client 10.0.0.76:7000: client stream connection dropped: connection is closed
2021-04-18T12:15:10+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla:  [shard 1] rpc - client 10.0.0.76:7000: client stream connection dropped: connection is closed
2021-04-18T12:15:16+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla:  [shard 5] rpc - client 10.0.0.76:7000: client stream connection dropped: connection is closed
2021-04-18T12:15:25+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !INFO    | scylla:  [shard 0] gossip - InetAddress 10.0.3.157 is now DOWN, status = NORMAL
2021-04-18T12:15:26+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !INFO    | scylla:  [shard 0] gossip - InetAddress 10.0.3.157 is now UP, status = NORMAL
2021-04-18T12:15:42+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla:  [shard 3] rpc - client 10.0.3.157:7000: client stream connection dropped: connection is closed
2021-04-18T12:15:42+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla:  [shard 3] rpc - client 10.0.3.157:7000: client stream connection dropped: connection is closed
2021-04-18T12:15:42+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla: message repeated 20 times: [  [shard 3] rpc - client 10.0.3.157:7000: client stream connection dropped: connection is closed]
2021-04-18T12:15:47+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla:  [shard 2] rpc - client 10.0.3.157:7000: client stream connection dropped: connection is closed
2021-04-18T12:15:47+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla: message repeated 18 times: [  [shard 2] rpc - client 10.0.3.157:7000: client stream connection dropped: connection is closed]
2021-04-18T12:15:49+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !INFO    | scylla:  [shard 0] gossip - InetAddress 10.0.3.157 is now DOWN, status = NORMAL
2021-04-18T12:15:57+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !WARNING | scylla:  [shard 0] gossip - Fail to send EchoMessage to 10.0.3.157: seastar::rpc::closed_error (connection is closed)
2021-04-18T12:16:14+00:00  longevity-twcs-3h-master-db-node-e98195c4-4 !ERR     | scylla:  [shard 4] rpc - client 10.0.3.157:7000: client stream connection dropped: connection is closed
```

node 1:
```
Apr 18 12:15:18 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 0] gossip - InetAddress 10.0.0.76 is now DOWN, status = NORMAL
Apr 18 12:15:42 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 0] gossip - Fail to send EchoMessage to 10.0.0.76: seastar::rpc::closed_error (connection is closed)
Apr 18 12:15:42 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 3] rpc - client 10.0.1.99:50067: server stream connection dropped: Unknown parent connection 1 on shard 3
Apr 18 12:15:42 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 3] rpc - client 10.0.1.99:65331: server stream connection dropped: Unknown parent connection 1 on shard 3
Apr 18 12:15:42 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 3] rpc - client 10.0.1.99:64355: server stream connection dropped: Unknown parent connection 1 on shard 3
Apr 18 12:15:42 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 3] rpc - client 10.0.1.99:60771: server stream connection dropped: Unknown parent connection 1 on shard 3

Apr 18 12:16:22 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 0] gossip - InetAddress 10.0.0.76 is now DOWN, status = NORMAL
Apr 18 12:16:41 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 0] gossip - Fail to send EchoMessage to 10.0.0.76: seastar::rpc::closed_error (connection is closed)
Apr 18 12:17:04 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 0] gossip - InetAddress 10.0.0.76 is now UP, status = NORMAL
Apr 18 12:17:29 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 0] gossip - InetAddress 10.0.1.99 is now DOWN, status = NORMAL
Apr 18 12:18:10 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 0] gossip - InetAddress 10.0.0.76 is now DOWN, status = NORMAL
Apr 18 12:18:12 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 5] rpc - client 10.0.1.99:52245: unexpected eof on a stream while reading data: expected 257521 got 100180
Apr 18 12:18:30 longevity-twcs-3h-master-db-node-e98195c4-1 scylla[10041]:  [shard 0] gossip - Fail to send EchoMessage to 10.0.0.76: seastar::rpc::closed_error (connection is closed)
```

And repair failed:
```
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 2021-04-18 12:21:03.871: (DisruptionEvent Severity.ERROR): type=RestartThenRepairNode subtype=end target_node=Node lon
gevity-twcs-3h-master-db-node-e98195c4-4 [54.72.142.1 | 10.0.1.99] (seed: False) duration=703 error=Encountered a bad command exit code!
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Command: '/usr/bin/nodetool  repair '
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Exit code: 2
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stdout:
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > [2021-04-18 12:10:34,458] Starting repair command #1, repairing 1 ranges for keyspace scylla_bench (parallelism=SEQUEN
TIAL, full=true)
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > [2021-04-18 12:21:02,985] Repair session 1 failed
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > [2021-04-18 12:21:02,991] Repair session 1 finished
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stderr:
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > error: Repair job has failed with the error message: [2021-04-18 12:21:02,985] Repair session 1 failed
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > -- StackTrace --
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > java.lang.RuntimeException: Repair job has failed with the error message: [2021-04-18 12:21:02,985] Repair session 1 f
ailed
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >    at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >    at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgre
ssListener.java:77)
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >    at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583
)
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >    at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >    at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >    at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
< t:2021-04-18 12:21:03,883 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
```

Restore Monitor Stack command: `$ hydra investigate show-monitor e98195c4-f472-4ae1-9f2c-937a47316fd5`
Show all stored logs command: `$ hydra investigate show-logs e98195c4-f472-4ae1-9f2c-937a47316fd5`

Test id: `e98195c4-f472-4ae1-9f2c-937a47316fd5`

Logs:

db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/e98195c4-f472-4ae1-9f2c-937a47316fd5/20210418_124751/db-cluster-e98195c4.zip](https://cloudius-jenkins-test.s3.amazonaws.com/e98195c4-f472-4ae1-9f2c-937a47316fd5/20210418_124751/db-cluster-e98195c4.zip)

sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/e98195c4-f472-4ae1-9f2c-937a47316fd5/20210418_124751/sct-runner-e98195c4.zip](https://cloudius-jenkins-test.s3.amazonaws.com/e98195c4-f472-4ae1-9f2c-937a47316fd5/20210418_124751/sct-runner-e98195c4.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-3h/1/)

**Comment by roydahan** [comment]
Probably same as #7965

**Comment by bhalevy** [comment]
Seems like a non-issue to me.
Why is repair expected to fail when it can't communicate to all nodes?

**Comment by juliayakovlev** [comment]
> Seems like a non-issue to me.
> Why is repair expected to succeed when it can't communicate to all nodes?

It's not clear why the communication between nodes is lost

**Comment by bhalevy** [comment]
So clarify it in the issue title. It's quite misleading as it is.
Something like: "Connection between nodes lost after node restart, causing repair failure"

**Comment by denesb** [comment]
Closing as stale.
