### ISSUE TITLE
scylla_setup: r5b doesn't support enhanced networking!

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla#8544]
*Installation details*
Scylla version 4.4:
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0908bf554a8e333db us-east-2

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): EC2
Instance type: r5b.metal

I'm getting the following error:

```
null_resource.cluster[0] (remote-exec): 2248064
null_resource.cluster[0] (remote-exec): r5b doesn't support enhanced networking!
null_resource.cluster[0] (remote-exec): To enable enhanced networking, please use the instance type which supports it.
null_resource.cluster[0] (remote-exec): More documentation available at:
null_resource.cluster[0] (remote-exec): http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enabling_enhanced_networking
null_resource.cluster[0] (remote-exec): Traceback (most recent call last):
null_resource.cluster[0] (remote-exec):   File "/opt/scylladb/scripts/libexec/scylla_setup", line 341, in <module>
null_resource.cluster[0] (remote-exec):     run('{}/scylla_ec2_check --nic {}'.format(scriptsdir(), args.nic), shell=True, check=True)
null_resource.cluster[0] (remote-exec):   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
null_resource.cluster[0] (remote-exec):     raise CalledProcessError(retcode, process.args,
null_resource.cluster[0] (remote-exec): subprocess.CalledProcessError: Command '/opt/scylladb/scripts/scylla_ec2_check --nic eth0' returned non-zero exit status 1.
null_resource.cluster[0] (remote-exec): cache_enabled: false
null_resource.configure-prometheus (remote-exec): Wait for Prometheus container to start..
null_resource.configure-prometheus: Still creating... [1m0s elapsed]
```
Since this is a super new and powerful instance, I guess there is something wrong with the check. 

This is the call I made to configure scylla:

```
      sudo scylla_setup --disks /dev/nvme1n1,/dev/nvme2n1,/dev/nvme3n1,/dev/nvme4n1   
```

For the time being I have disabled the ec2 check
```
    sudo scylla_setup --disks /dev/nvme1n1,/dev/nvme2n1,/dev/nvme3n1,/dev/nvme4n1 --no-ec2-check
```

**Comment by pveentjer** [comment]
The following is the problem

```
  def get_en_interface_type(self):
        instance_class = self.instance_class()
        instance_size = self.instance_size()
        if instance_class in ['c3', 'c4', 'd2', 'i2', 'r3']:
            return 'ixgbevf'
        if instance_class in ['a1', 'c5', 'c5a', 'c5d', 'c5n', 'c6g', 'c6gd', 'f1', 'g3', 'g4', 'h1', 'i3', 'i3en', 'inf1', 'm5', 'm5a', 'm5ad', 'm5d', 'm5dn', 'm5n', 'm6g', 'm6gd', 'p2', 'p3', 'r4', 'r5', 'r5a', 'r5ad', 'r5d', 'r5dn', 'r5n', 't3', 't3a', 'u-6tb1', 'u-9tb1', 'u-12tb1', 'u-18tn1', 'u-24tb1', 'x1', 'x1e', 'z1d']:
            return 'ena'
        if instance_class == 'm4':
            if instance_size == '16xlarge':
                return 'ena'
            else:
                return 'ixgbevf'
        return None
```

r5b is missing.

**Comment by avelanarius** [comment]
Did your Pull Request (https://github.com/scylladb/scylla/pull/8546) fully fix this issue?

If yes, then you should have written "Fixes #8544" inside a commit message in that PR - that way this issue would be closed automatically.

**Comment by slivne** [comment]
assuming it did  c255903  - closing the issues

**Comment by pveentjer** [comment]
Thanks @slivne
