### ISSUE TITLE
repair_while_table_is_dropped_test dtest fails

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8612]
Regression started in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/805/testReport/repair_additional_test/RepairAdditionalTest/repair_while_table_is_dropped_test/
Scylla version df65d09e089c218bb8b1f53bb18bab38753fb471
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 2909, in repair_while_table_is_dropped_test
    thread1.result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 2898, in <lambda>
    thread1 = executor.submit(lambda: node1.repair())
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 1317, in repair
    return self.nodetool(cmd, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 678, in nodetool
    return super().nodetool(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 777, in nodetool
    raise NodetoolError(" ".join(nodetool), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/df65d09e089c218bb8b1f53bb18bab38753fb471/scylla-tools-java/bin/nodetool -h 127.0.90.1 -p 7190 repair' failed; exit status: 2; stdout: [2021-05-05 00:58:38,065] Starting repair command #1, repairing 1 ranges for keyspace system_traces (parallelism=SEQUENTIAL, full=true)
[2021-05-05 00:58:40,164] Repair session 1 
[2021-05-05 00:58:40,164] Repair session 1 finished
[2021-05-05 00:58:40,172] Starting repair command #2, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)
[2021-05-05 00:58:41,275] Repair session 2 failed
[2021-05-05 00:58:41,275] Repair session 2 finished
; stderr: error: Repair job has failed with the error message: [2021-05-05 00:58:41,275] Repair session 2 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2021-05-05 00:58:41,275] Repair session 2 failed
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/805/artifact/logs-all.release.2/1620176327164_repair_additional_test.RepairAdditionalTest.repair_while_table_is_dropped_test/node1.log
```
INFO  2021-05-05 00:58:40,170 [shard 0] repair - starting user-requested repair for keyspace ks, repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b], options {{ trace -> false}, { jobThreads -> 1}, { incremental -> false}, { parallelism -> parallel}, { primaryRange -> false}}
INFO  2021-05-05 00:58:40,170 [shard 0] repair - repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b]: started replaying hints before repair, source nodes: {127.0.90.2, 127.0.90.1}, target nodes: {127.0.90.2, 127.0.90.1}
...
INFO  2021-05-05 00:58:41,171 [shard 0] repair - repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b]: finished replaying hints (took 1s), continuing with repair
WARN  2021-05-05 00:58:41,171 [shard 0] repair - repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b] failed: std::out_of_range ()
WARN  2021-05-05 00:58:41,171 [shard 0] repair - repair_tracker run for repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b] failed: std::out_of_range ()
```

**Comment by bhalevy** [comment]
I guess this was triggered by 6ffd813b7ba555a972b12b03cb8f7cca2b2f49f9 (Merge 'hints: delay repair until hints are replayed' from Piotr Dulikowski)
@piodul please look into this issue.

**Comment by bhalevy** [comment]
@asias, please verify that https://github.com/scylladb/scylla/pull/8982 fixes this issue.

**Comment by asias** [comment]
> 
> 
> @asias, please verify that #8982 fixes this issue.

Yes, I built https://github.com/scylladb/scylla/pull/8982 and the dtest passed.
