### ISSUE TITLE
nodetool info error for getting "percent repair"

### ISSUE THREAD

**Issue by yangly0815** [scylladb/scylla#8628]
When I execute nodetool info, I got an error as follows:
```
[root@node01 ~]# nodetool info
Using /etc/scylla/scylla.yaml as the config file
ID                     : aa9da3fc-bfb6-48c2-9e45-667177e2222
Gossip active          : true
Thrift active          : true
Native Transport active: true
Load                   : 4.68 TB
Generation No          : 1619678250
Uptime (seconds)       : 431146
Heap Memory (MB)       : 48.82 / 247.50
Off Heap Memory (MB)   : 0.00
Data Center            : dc_01
Rack                   : dc_01_rack01
Exceptions             : 0
Key Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Row Cache              : entries 118040741, size 112.57 MiB, capacity 495.31 GiB, 539903778 hits, 1163635584 requests, 0.464 recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
error: org.apache.cassandra.metrics:type=Table,name=PercentRepaired
-- StackTrace --
javax.management.InstanceNotFoundException: org.apache.cassandra.metrics:type=Table,name=PercentRepaired
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at com.scylladb.jmx.utils.APIMBeanServer.getAttribute(APIMBeanServer.java:160)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
        at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
        at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
        at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
        at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:273)
        at com.sun.proxy.$Proxy23.getValue(Unknown Source)
        at org.apache.cassandra.tools.NodeProbe.getColumnFamilyMetric(NodeProbe.java:1419)
        at org.apache.cassandra.tools.nodetool.Info.execute(Info.java:143)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:270)
        at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:180)

```
But when I execute another env that the scylla version is the same, it work correctly.

**Comment by nyh** [comment]
@amnonh @asias any ideas?

**Comment by amnonh** [comment]
I'm cc @elcallio the error is from the Java-JMX, it means that for some reason, the nodetool does connect to Scylla-JMX but is looking for an object that is not found.
The relevant object (https://github.com/scylladb/scylla-jmx/blob/a7c4c39dd0a06afd20238175d23fd2ddaffd475c/src/main/java/org/apache/cassandra/metrics/TableMetrics.java#L297) have been there for a few years.

It's worth looking for errors in the logs of Scylla-jmx (found on the same machine as scylla)

**Comment by mehmetcanfarsak** [comment]
hi, I have same error. How can we solve this error?

**Comment by d-helios** [comment]
I got the same issue 

```
$ dpkg -l|grep jdk
ii  openjdk-8-jre-headless:amd64       8u382-ga-1~20.04.1                  amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
$ scylla --version
2022.2.13-0.20230824.575d727536c7
```

```
ID                     : 1f8cd140-5303-4808-a93c-46981533f0b9
Gossip active          : true
Thrift active          : false
Native Transport active: true
Load                   : 4.98 MB
Generation No          : 1697535144
Uptime (seconds)       : 271
Heap Memory (MB)       : 11.77 / 247.50
Off Heap Memory (MB)   : 0.00
Data Center            : GCE_EUROPE_WEST_3
Rack                   : europe-west3-c
Exceptions             : 0
Key Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Row Cache              : entries 187, size 187 bytes, capacity 7.9 MiB, 95954 hits, 96962 requests, 0.990 recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
error: org.apache.cassandra.metrics:type=Table,name=PercentRepaired
-- StackTrace --
javax.management.InstanceNotFoundException: org.apache.cassandra.metrics:type=Table,name=PercentRepaired
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at com.scylladb.jmx.utils.APIMBeanServer.getAttribute(APIMBeanServer.java:160)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:273)
	at com.sun.proxy.$Proxy22.getValue(Unknown Source)
	at org.apache.cassandra.tools.NodeProbe.getColumnFamilyMetric(NodeProbe.java:1497)
	at org.apache.cassandra.tools.nodetool.Info.execute(Info.java:146)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.runInternal(NodeTool.java:309)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:294)
	at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:196)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:62)
```
