### ISSUE TITLE
row_cache_test: test_partition_range_population_with_concurrent_memtable_flushes fails with segmentation fault

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#8671]
This test checks populating cache reads parallel to cache updates. Adding a continuation to `fast_forward_to(position_range)`, or more generally speaking, increasing the amount of cache updates that can run in parallel to the reads leads to a segmentation fault in the cache:
```
/home/bdenes/ScyllaDB/scylla/seastar/include/seastar/core/shared_ptr.hh:211:55: runtime error: member access within null pointer of type 'seastar::internal::lw_shared_ptr_accessors_no_esft<std::function<flat_mutation_reader (seastar::lw_shared_ptr<const schema>, reader_permit, const nonwrapping_interval<dht::ring_position> &, const query::partition_slice &, const seastar::io_priority_class &, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<flat_mutation_reader::partition_range_forwarding_tag>)>>::concrete_type' (aka 'shared_ptr_no_esft<std::function<flat_mutation_reader (seastar::lw_shared_ptr<const schema>, reader_permit, const nonwrapping_interval<dht::ring_position> &, const query::partition_slice &, const seastar::io_priority_class &, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<flat_mutation_reader::partition_range_forwarding_tag>)>>')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/bdenes/ScyllaDB/scylla/seastar/include/seastar/core/shared_ptr.hh:211:55 in 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==177871==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x0000118c3847 bp 0x7fc5e91ca630 sp 0x7fc5e91ca530 T1)
==177871==The signal is caused by a READ memory access.
==177871==Hint: address points to the zero page.
    #0 0x118c3847 in std::_Function_base::_M_empty() const /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:248:37
    #1 0x1196e3e6 in std::function<flat_mutation_reader (seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, seastar::io_priority_class const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<flat_mutation_reader::partition_range_forwarding_tag>)>::operator()(seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, seastar::io_priority_class const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<flat_mutation_reader::partition_range_forwarding_tag>) const /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:620:11
    #2 0x1196df6b in mutation_source::make_reader(seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, seastar::io_priority_class const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<flat_mutation_reader::partition_range_forwarding_tag>) const ./mutation_reader.hh:253:16
    #3 0x12071196 in row_cache::create_underlying_reader(cache::read_context&, mutation_source&, nonwrapping_interval<dht::ring_position> const&) row_cache.cc:49:23
    #4 0x12133caf in cache::autoupdating_underlying_reader::move_to_next_partition(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::'lambda0'()::operator()() const ./read_context.hh:75:30
    #5 0x12133ab3 in seastar::future<void> seastar::futurize<void>::invoke<cache::autoupdating_underlying_reader::move_to_next_partition(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::'lambda0'()&>(cache::autoupdating_underlying_reader::move_to_next_partition(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::'lambda0'()&) ./seastar/include/seastar/core/future.hh:2132:13
    #6 0x12133a8e in auto seastar::futurize_invoke<cache::autoupdating_underlying_reader::move_to_next_partition(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::'lambda0'()&>(cache::autoupdating_underlying_reader::move_to_next_partition(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::'lambda0'()&) ./seastar/include/seastar/core/future.hh:2166:12
    #7 0x12133a36 in auto seastar::future<void> seastar::future<void>::then<cache::autoupdating_underlying_reader::move_to_next_partition(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::'lambda0'(), seastar::future<void> >(cache::autoupdating_underlying_reader::move_to_next_partition(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::'lambda0'()&&)::'lambda'(auto&&...)::operator()<>(auto&&...) ./seastar/include/seastar/core/future.hh:1527:24
    #8 0x121339f1 in seastar::noncopyable_function<seastar::future<void> ()>::direct_vtable_for<seastar::future<void> seastar::future<void>::then<cache::autoupdating_underlying_reader::move_to_next_partition(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::'lambda0'(), seastar::future<void> >(cache::autoupdating_underlying_reader::move_to_next_partition(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::'lambda0'()&&)::'lambda'(auto&&...)>::call(seastar::noncopyable_function<seastar::future<void> ()> const*) ./seastar/include/seastar/util/noncopyable_function.hh:124:20
    #9 0x1194ff3e in seastar::noncopyable_function<seastar::future<void> ()>::operator()() const ./seastar/include/seastar/util/noncopyable_function.hh:209:16
    #10 0x1194feae in seastar::future<void> std::__invoke_impl<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> ()>&>(std::__invoke_other, seastar::noncopyable_function<seastar::future<void> ()>&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60:14
    #11 0x1194fe7e in std::__invoke_result<seastar::noncopyable_function<seastar::future<void> ()>&>::type std::__invoke<seastar::noncopyable_function<seastar::future<void> ()>&>(seastar::noncopyable_function<seastar::future<void> ()>&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95:14
    #12 0x1194fe3e in std::invoke_result<seastar::noncopyable_function<seastar::future<void> ()>&>::type std::invoke<seastar::noncopyable_function<seastar::future<void> ()>&>(seastar::noncopyable_function<seastar::future<void> ()>&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/functional:88:14
    #13 0x1194fe0e in auto seastar::internal::future_invoke<seastar::noncopyable_function<seastar::future<void> ()>&, seastar::internal::monostate>(seastar::noncopyable_function<seastar::future<void> ()>&, seastar::internal::monostate&&) ./seastar/include/seastar/core/future.hh:1209:16
    #14 0x1194fda0 in seastar::future<void> seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> ()>&&)::'lambda'(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&)::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&) const::'lambda'()::operator()() const ./seastar/include/seastar/core/future.hh:1582:28
    #15 0x1194fcc2 in void seastar::futurize<seastar::future<void> >::satisfy_with_result_of<seastar::future<void> seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> ()>&&)::'lambda'(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&)::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&) const::'lambda'()>(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&&) ./seastar/include/seastar/core/future.hh:2120:9
    #16 0x1194fb3e in seastar::future<void> seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> ()>&&)::'lambda'(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&)::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&) const ./seastar/include/seastar/core/future.hh:1575:17
    #17 0x1194f8fd in seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void> seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> ()>&&)::'lambda'(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&), void>::run_and_dispose() ./seastar/include/seastar/core/future.hh:767:13
    #18 0x1729e4a0 in seastar::reactor::run_tasks(seastar::reactor::task_queue&) build/debug/seastar/./seastar/src/core/reactor.cc:2228:14
    #19 0x172a52a6 in seastar::reactor::run_some_tasks() build/debug/seastar/./seastar/src/core/reactor.cc:2637:9
    #20 0x172a9edb in seastar::reactor::run() build/debug/seastar/./seastar/src/core/reactor.cc:2796:9
    #21 0x181964aa in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) build/debug/seastar/./seastar/src/core/app-template.cc:207:31
    #22 0x181945bc in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) build/debug/seastar/./seastar/src/core/app-template.cc:115:12
    #23 0x1816c9c6 in seastar::testing::test_runner::start(int, char**)::$_0::operator()() build/debug/seastar/./seastar/src/testing/test_runner.cc:70:26
    #24 0x1816c217 in void std::__invoke_impl<void, seastar::testing::test_runner::start(int, char**)::$_0&>(std::__invoke_other, seastar::testing::test_runner::start(int, char**)::$_0&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60:14
    #25 0x1816c0a7 in std::enable_if<is_invocable_r_v<void, seastar::testing::test_runner::start(int, char**)::$_0&>, void>::type std::__invoke_r<void, seastar::testing::test_runner::start(int, char**)::$_0&>(seastar::testing::test_runner::start(int, char**)::$_0&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110:2
    #26 0x1816bab7 in std::_Function_handler<void (), seastar::testing::test_runner::start(int, char**)::$_0>::_M_invoke(std::_Any_data const&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291:9
    #27 0x11eec038 in std::function<void ()>::operator()() const /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622:14
    #28 0x17627307 in seastar::posix_thread::start_routine(void*) build/debug/seastar/./seastar/src/core/posix.cc:60:5
    #29 0x7fc5efe2a3f8 in start_thread (/lib64/libpthread.so.0+0x93f8)
    #30 0x7fc5ef0b7b52 in clone (/lib64/libc.so.6+0x101b52)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:248:37 in std::_Function_base::_M_empty() const
Thread T1 created by T0 here:
    #0 0x11673652 in pthread_create (/home/bdenes/ScyllaDB/scylla/build/debug/test/boost/row_cache_test_g+0x11673652)
    #1 0x17627b66 in seastar::posix_thread::posix_thread(seastar::posix_thread::attr, std::function<void ()>) build/debug/seastar/./seastar/src/core/posix.cc:95:9
    #2 0x17627581 in seastar::posix_thread::posix_thread(std::function<void ()>) build/debug/seastar/./seastar/src/core/posix.cc:65:7
    #3 0x1816a7e9 in std::_MakeUniq<seastar::posix_thread>::__single_object std::make_unique<seastar::posix_thread, seastar::testing::test_runner::start(int, char**)::$_0>(seastar::testing::test_runner::start(int, char**)::$_0&&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/unique_ptr.h:962:34
    #4 0x1816a291 in seastar::testing::test_runner::start(int, char**) build/debug/seastar/./seastar/src/testing/test_runner.cc:63:15
    #5 0x1815abb2 in seastar::testing::init_unit_test_suite() build/debug/seastar/./seastar/src/testing/entry_point.cc:47:33
    #6 0x7fc5ef43a05c  (/lib64/libboost_unit_test_framework.so.1.73.0+0x2605c)

==177871==ABORTING
```
Although this failure doesn't happen on master, the problem exists there too, it just doesn't happen to manifest. I could reproduce this problem by just adding a `finally()` clause in `flat_mutation_reader::fast_forward_to(position_range)` with 100% reliability.

The underlying problem is that fa43d7680 made `autoupdating_underlying_reader::move_to_next_partition()` non-atomic w.r.t. creating the new underlying reader. This means that a parallelly running cache update fiber can be scheduled between the old reader being closed and the new one being created and change `_prev_snapshot` such that the new reader is attempted to be created with a null mutation source.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
