### ISSUE TITLE
Missing gossip UP notification in restart after kill the node

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#8705]
*Installation details*
Scylla version (or git commit hash): 4.6.dev-0.20210516.5e39cedbe3
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description
When the db node is killed, and restart will fail with `[node2] Missing: ['127.0.56.1.* now UP']:`
It works well if we stop the node by node.stop(gently=True).

### reboot_test.py
```
from dtest import Tester
class RebootTest(Tester):
    def reboot_test(self):
        self.cluster.populate(3).start(wait_for_binary_proto=True, wait_other_notice=True)
        for node in self.cluster.nodelist():
            node.stop(gently=False)
            node.start(wait_for_binary_proto=True, wait_other_notice=True)
```

### Test log
2021-05-25 08:21:07.766700 reboot_test.py:RebootTest.reboot_test - cluster ccm directory: /home/amos/.dtest/dtest-bj777vnb
2021-05-25 08:21:07.767007 reboot_test.py:RebootTest.reboot_test - Starting Scylla cluster version unstable/master:2021-05-16T16:06:02Z
2021-05-25 08:21:08.555795 reboot_test.py:RebootTest.reboot_test - Allocated cluster ID 56: /home/amos/.dtest/dtest-bj777vnb
2021-05-25 08:21:09.251674 reboot_test.py:RebootTest.reboot_test - Scylla mode is 'release'
2021-05-25 08:21:09.251924 reboot_test.py:RebootTest.reboot_test - Cluster *_request_timeout_in_ms=10000, range_request_timeout_in_ms=30000, cql request_timeout=30
2021-05-25 08:25:16.900236 reboot_test.py:RebootTest.reboot_test - Test failed with errors: [(<reboot_test.RebootTest testMethod=reboot_test>, (<class 'ccmlib.node.TimeoutError'>, TimeoutError("25 May 2021 08:25:16 [node2] Missing: ['127.0.56.1.* now UP']:\nERROR 2021-05-25 08:23:15,710 [shard 0] rpc - clie.....\nSee system.log for remainder"), <traceback object at 0x7fabf614c050>))]
2021-05-25 08:25:16.900570 reboot_test.py:RebootTest.reboot_test - Stopping cluster
2021-05-25 08:25:19.948112 reboot_test.py:RebootTest.reboot_test - stopping ccm cluster test at: /home/amos/.dtest/dtest-bj777vnb
2021-05-25 08:25:20.668002 reboot_test.py:RebootTest.reboot_test - Freeing cluster ID 56: link /home/amos/.dtest/56
reboot_test (reboot_test.RebootTest) ... ERROR

======================================================================
ERROR: reboot_test (reboot_test.RebootTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amos/newspace/builddir/scylla-dtest/reboot_test.py", line 9, in reboot_test
    node.start(wait_for_binary_proto=True, wait_other_notice=True)
  File "/home/amos/newspace/builddir/scylla-ccm/ccmlib/scylla_node.py", line 602, in start
    ext_env)
  File "/home/amos/newspace/builddir/scylla-ccm/ccmlib/scylla_node.py", line 310, in _start_scylla
    node.watch_log_for_alive(self, from_mark=mark, timeout=t)
  File "/home/amos/newspace/builddir/scylla-ccm/ccmlib/node.py", line 518, in watch_log_for_alive
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/home/amos/newspace/builddir/scylla-ccm/ccmlib/node.py", line 483, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 25 May 2021 08:25:16 [node2] Missing: ['127.0.56.1.* now UP']:
ERROR 2021-05-25 08:23:15,710 [shard 0] rpc - clie.....
See system.log for remainder

----------------------------------------------------------------------
Ran 1 test in 252.939s

FAILED (errors=1)
Docker exitcode: 1

/Cc @asias @roydahan

**Comment by asias** [comment]
I think this is expected because when a node is killed forcefully and restarted  immediately, it is possible that other nodes will not notice the node is down before the node finishes restart. As a result, other nodes will not mark the down, thus will not print the log xxx is now UP when the node restarts.

**Comment by amoskong** [comment]
> I think this is expected because when a node is killed forcefully and restarted immediately, it is possible that other nodes will not notice the node is down before the node finishes restart. As a result, other nodes will not mark the down, thus will not print the log xxx is now UP when the node restarts.

Ok. Let's close this issue?

**Comment by bhalevy** [comment]
> > I think this is expected because when a node is killed forcefully and restarted immediately, it is possible that other nodes will not notice the node is down before the node finishes restart. As a result, other nodes will not mark the down, thus will not print the log xxx is now UP when the node restarts.
> 
> Ok. Let's close this issue?

Yes. It's the expected behavior.

**Comment by asias** [comment]
> > I think this is expected because when a node is killed forcefully and restarted immediately, it is possible that other nodes will not notice the node is down before the node finishes restart. As a result, other nodes will not mark the down, thus will not print the log xxx is now UP when the node restarts.
> 
> Ok. Let's close this issue?

Amos, yes.
