### ISSUE TITLE
release_version from system tables is incorrect

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8740]
$ scylla --version
4.6.dev-0.20210528.849bec07d

```
cqlsh> SELECT release_version from system.peers ;

 release_version
-----------------
           3.0.8
           3.0.8

(2 rows)
cqlsh> SELECT release_version from system.local  ;

 release_version
-----------------
           3.0.8

(1 rows)
```

**Comment by avelanarius** [comment]
> Isn't it a C* version that is expected for compatibility with Cassandra drivers? \cc @penberg

Scylla Java Driver 4.7.2.0 (forked from DataStax Java Driver 4.7.2) throws an exception if the `release_version` is `4.6.dev-0.20210512.c0dafa75d` (non `3.0.8`). Scylla Java Driver 4.11.1.0 (forked from DataStax Java Driver 4.11.1) works correctly.

Stacktrace of Scylla Java Driver 4.7.2.0:
```
Exception in thread "main" com.datastax.oss.driver.api.core.NoNodeAvailableException: No node was available to execute the query
	at com.datastax.oss.driver.api.core.NoNodeAvailableException.copy(NoNodeAvailableException.java:40)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:237)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:53)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:73)
	at Main.main(Main.java:14)
```

**Comment by asias** [comment]
Thanks for trying it out. It is sad we have to keep using the magic 3.0.8 version ;(

**Comment by tgrabiec** [comment]
We can add scylla_release_version.

**Comment by asias** [comment]
> We can add scylla_release_version.

We definitely can, the question is whether it is worth to do so. We can not throw everything into the system table. I am fixing the version because it is wrong. We can get the scylla version number from REST API.

**Comment by penberg** [comment]
@tgrabiec Yes, exactly. The version is there for Cassandra Driver compatibility.

**Comment by nyh** [comment]
> > We can add scylla_release_version.
> 
> We definitely can, the question is whether it is worth to do so. We can not throw everything into the system table. I am fixing the version because it is wrong. We can get the scylla version number from REST API.

In the duplicate issue #8841 is was mentioned that there is value in making this information available via CQL and not other methods (REST API, logs, etc.) - in installations where only CQL is exposed, including Scylla Cloud.

**Comment by nyh** [comment]
> @tgrabiec Yes, exactly. The version is there for Cassandra Driver compatibility.

Some other projects who faced this problem found a way to print both the "pretend" version that the drivers see, and also the real version for humans to see. For example:
```
$ aspell --version
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
```

I don't know if this technique is relevant to us - we would need to experiment whether we can stick other text after the string "3.0.8" and perhaps if done in the right way, the Cassandra driver will ignore the extra text.

**Comment by bentsi** [comment]
@nyh yep, we need this available via CQL in the Scylla Cloud, since only 9041 is open

**Comment by nyh** [comment]
We already have a way to get the real ScyllaDB version of a node, as described in https://github.com/scylladb/scylla-cqlsh/issues/9#issuecomment-1332234516:
```
cqlsh> SELECT version FROM system.versions WHERE key='local' ;

 version
-----------------------------------
 5.2.0~dev-0.20221130.8bc0af9e34fa
```
This doesn't show you the version of all the peers, but you can contact each node and ask it its ScyllaDB version in this way.

Is this enough and we should close this issue, or do you want this information in the specific tables which you mentioned?

**Comment by mykaul** [comment]
> @nyh yep, we need this available via CQL, to use it in the Scylla Cloud, since only 9041 is open

Scylla cloud knows exactly which version is installed on each node, since it installed it in the 1st place - no mysteries there.

**Comment by mykaul** [comment]
> @mykaul I think the issue is not how "Scylla Cloud" (the service) know what they installed, but how a Scylla Cloud **user** can figure out the exact version of Scylla that is running (in case the user forgot, or in case the user doesn't even know because they asked us to upgrade at will).

They have it in the Scylla Cloud UI (and hopefully, in the API as well). I don't think we absolutely need a CQL interface to it (although we try to have one usually).

**Comment by hulkabob** [comment]
I'm having an issue with Zipkin 2.21-2.23.X (tried all of them), where it looks for Cassandra version when provisioning schema or doing initial health check:
```
java.lang.IllegalStateException: Host b0eeab9a-993d-4f4f-9bb6-d5d952b7e1d0 is running Cassandra 3.0.8, but minimum version is 3.11.3
```

If there was a way to alter this value, so Scylla Administrator could decide the level of compatibility with Cassandra drivers on his own.

**Comment by nyh** [comment]
Another user on stackoverflow who was surprised that release_version is not helpful on recognizing Scylla:
https://stackoverflow.com/questions/79021741/is-it-possible-to-identify-the-cassandra-engine-system-via-cql
