### ISSUE TITLE
truncate_after_restart_test: [node1] Missing: ['127.0.38.2 is now (dead|DOWN)']

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8760]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/804/testReport/cql_tests/TruncateTester/truncate_after_restart_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/cql_tests.py", line 782, in truncate_after_restart_test
    node2.stop(wait_other_notice=True)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-ccm/ccmlib/scylla_node.py", line 844, in stop
    self.wait_until_stopped(wait_seconds, marks, dump_core=gently)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-ccm/ccmlib/scylla_node.py", line 813, in wait_until_stopped
    node.watch_log_for_death(self, from_mark=mark)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-ccm/ccmlib/node.py", line 509, in watch_log_for_death
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-ccm/ccmlib/node.py", line 483, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 31 May 2021 02:20:26 [node1] Missing: ['127.0.38.2 is now (dead|DOWN)']:
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/804/artifact/logs-all.debug.2/dtest.log
```
2021-05-31 02:03:06,316 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - cluster ccm directory: /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-iftc0vml
2021-05-31 02:03:06,317 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - Starting Scylla cluster version 76d7c761d1e490bc5725fa86a3cf64a20daa3102
2021-05-31 02:03:06,325 22444   ccm                            DEBUG    | Started cluster 'test' version 4.6.dev installed in /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/76d7c761d1e490bc5725fa86a3cf64a20daa3102
2021-05-31 02:03:06,332 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - Allocated cluster ID 38: /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-iftc0vml
2021-05-31 02:03:06,354 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - Scylla mode is 'debug'
2021-05-31 02:03:06,354 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - Cluster *_request_timeout_in_ms=30000, range_request_timeout_in_ms=90000, cql request_timeout=90
2021-05-31 02:03:06,364 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - configuring skip_wait_for_gossip_to_settle=0 for single_node test
2021-05-31 02:03:06,505 22444   ccm                            DEBUG    | node1: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-iftc0vml/test/node1/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-iftc0vml/test/node1/conf/scylla.yaml', '--log-to-stdout', '1', '--api-address', '127.0.38.1', '--collectd-hostname', '0e8de5180622.node1', '--smp', '2', '--memory', '1024M', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--developer-mode', 'true', '--default-log-level', 'info', '--blocked-reactor-notify-ms', '5000', '--collectd', '0', '--overprovisioned', '--prometheus-address', '127.0.38.1', '--unsafe-bypass-fsync', '1'] wait_other_notice=False wait_for_binary_proto=False
2021-05-31 02:03:36,139 22444   ccm                            DEBUG    | node2: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-iftc0vml/test/node2/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-iftc0vml/test/node2/conf/scylla.yaml', '--log-to-stdout', '1', '--api-address', '127.0.38.2', '--collectd-hostname', '0e8de5180622.node2', '--smp', '2', '--memory', '1024M', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--developer-mode', 'true', '--default-log-level', 'info', '--blocked-reactor-notify-ms', '5000', '--collectd', '0', '--overprovisioned', '--prometheus-address', '127.0.38.2', '--unsafe-bypass-fsync', '1'] wait_other_notice=True wait_for_binary_proto=True
2021-05-31 02:20:26,082 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - Test failed with errors: [(<cql_tests.TruncateTester testMethod=truncate_after_restart_test>, (<class 'ccmlib.node.TimeoutError'>, TimeoutError("31 May 2021 02:20:26 [node1] Missing: ['127.0.38.2 is now (dead|DOWN)']:\n.....\nSee system.log for remainder"), <traceback object at 0x7f6ae9bf4190>))]
2021-05-31 02:20:26,082 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - Stopping cluster
2021-05-31 02:20:33,118 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - removing ccm cluster test at: /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-iftc0vml
2021-05-31 02:20:33,162 22444   dtest                          DEBUG    | cql_tests.py:TruncateTester.truncate_after_restart_test - Freeing cluster ID 38: link /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/38
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/804/artifact/logs-all.debug.2/1622427633098_cql_tests.TruncateTester.truncate_after_restart_test/node2.log
```
INFO  2021-05-31 02:10:05,212 [shard 0] compaction_manager - Asked to stop
INFO  2021-05-31 02:10:05,213 [shard 0] compaction_manager - Stopping 0 ongoing compactions
WARN  2021-05-31 02:10:05,213 [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[127.0.38.1]: seastar::sleep_aborted (Sleep is aborted)
INFO  2021-05-31 02:10:05,213 [shard 0] gossip - failure_detector_loop: Finished main loop
INFO  2021-05-31 02:10:05,214 [shard 0] compaction_manager - Stopped
INFO  2021-05-31 02:10:05,214 [shard 0] init - Signal received; shutting down
INFO  2021-05-31 02:10:05,214 [shard 0] init - Shutting down redis service
INFO  2021-05-31 02:10:05,214 [shard 0] init - Shutting down redis service was successful
INFO  2021-05-31 02:10:05,214 [shard 1] compaction_manager - Asked to stop
INFO  2021-05-31 02:10:05,214 [shard 0] init - Shutting down view builder
INFO  2021-05-31 02:10:05,214 [shard 0] view - Stopping view builder
INFO  2021-05-31 02:10:05,214 [shard 1] compaction_manager - Stopping 0 ongoing compactions
INFO  2021-05-31 02:10:05,214 [shard 1] view - Stopping view builder
INFO  2021-05-31 02:10:05,214 [shard 1] compaction_manager - Stopped
INFO  2021-05-31 02:10:05,216 [shard 0] init - Shutting down view builder was successful
INFO  2021-05-31 02:10:05,216 [shard 0] init - Shutting down local storage
INFO  2021-05-31 02:10:05,220 [shard 0] storage_service - Stop transport: starts
INFO  2021-05-31 02:10:05,220 [shard 0] storage_service - Shutting down native transport
INFO  2021-05-31 02:10:05,234 [shard 0] cql_server_controller - CQL server stopped
INFO  2021-05-31 02:10:05,234 [shard 0] storage_service - Shutting down native transport was successful
INFO  2021-05-31 02:10:05,234 [shard 0] storage_service - Shutting down rpc server
INFO  2021-05-31 02:10:05,234 [shard 0] storage_service - Shutting down rpc server was successful
INFO  2021-05-31 02:10:05,234 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2021-05-31 02:10:05,236 [shard 0] gossip - My status = NORMAL
INFO  2021-05-31 02:10:05,236 [shard 0] gossip - Announcing shutdown
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO  2021-05-31 02:10:05,253 [shard 0] storage_service - Node 127.0.38.2 state jump to normal
INFO  2021-05-31 02:10:07,344 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2021-05-31 02:10:07,345 [shard 0] gossip - Disable and wait for gossip loop finished
INFO  2021-05-31 02:10:07,347 [shard 0] gossip - Gossip is now stopped
INFO  2021-05-31 02:10:07,347 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2021-05-31 02:10:07,347 [shard 0] messaging_service - Stopping nontls server
INFO  2021-05-31 02:10:07,347 [shard 0] messaging_service - Stopping tls server
INFO  2021-05-31 02:10:07,347 [shard 0] messaging_service - Stopping client for address: 127.0.38.1:0
INFO  2021-05-31 02:10:07,347 [shard 0] messaging_service - Stopping client for address: 127.0.38.1:0
INFO  2021-05-31 02:10:07,347 [shard 0] messaging_service - Stopping client for address: 127.0.38.1:0
INFO  2021-05-31 02:10:07,347 [shard 0] messaging_service - Stopping client for address: 127.0.38.1:0
INFO  2021-05-31 02:10:07,351 [shard 0] messaging_service - Stopping client for address: 127.0.38.1:0 - Done
INFO  2021-05-31 02:10:07,351 [shard 0] messaging_service - Stopping tls server - Done
INFO  2021-05-31 02:10:07,352 [shard 1] messaging_service - Stopping nontls server
INFO  2021-05-31 02:10:07,352 [shard 1] messaging_service - Stopping tls server
INFO  2021-05-31 02:10:07,353 [shard 1] messaging_service - Stopping tls server - Done
INFO  2021-05-31 02:10:07,354 [shard 1] messaging_service - Stopping nontls server - Done
INFO  2021-05-31 02:10:07,354 [shard 0] messaging_service - Stopping client for address: 127.0.38.1:0 - Done
INFO  2021-05-31 02:10:07,354 [shard 0] messaging_service - Stopping client for address: 127.0.38.1:0 - Done
INFO  2021-05-31 02:10:07,354 [shard 0] messaging_service - Stopping client for address: 127.0.38.1:0 - Done
INFO  2021-05-31 02:10:07,355 [shard 0] messaging_service - Stopping nontls server - Done
INFO  2021-05-31 02:10:07,355 [shard 0] storage_service - messaging_service stopped
INFO  2021-05-31 02:10:07,355 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2021-05-31 02:10:07,356 [shard 0] storage_service - stream_manager stopped
INFO  2021-05-31 02:10:07,356 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2021-05-31 02:10:07,356 [shard 0] storage_service - Stop transport: done
INFO  2021-05-31 02:10:07,356 [shard 0] tracing - Asked to shut down
INFO  2021-05-31 02:10:07,356 [shard 0] tracing - Tracing is down
INFO  2021-05-31 02:10:07,357 [shard 1] tracing - Asked to shut down
INFO  2021-05-31 02:10:07,357 [shard 1] tracing - Tracing is down
INFO  2021-05-31 02:10:09,317 [shard 0] migration_manager - stopping migration service
INFO  2021-05-31 02:10:09,317 [shard 1] migration_manager - stopping migration service
INFO  2021-05-31 02:10:09,323 [shard 0] init - Shutting down local storage was successful
INFO  2021-05-31 02:10:09,323 [shard 0] init - Shutting down view update generator
INFO  2021-05-31 02:10:09,323 [shard 0] view_update_generator - leaving 0 unstaged sstables unprocessed
INFO  2021-05-31 02:10:09,324 [shard 1] view_update_generator - leaving 0 unstaged sstables unprocessed
INFO  2021-05-31 02:10:09,325 [shard 0] init - Shutting down view update generator was successful
INFO  2021-05-31 02:10:09,325 [shard 0] init - Shutting down service level controller
INFO  2021-05-31 02:10:18,535 [shard 0] service_level_controller - update_from_distributed_data: configuration polling loop aborted
INFO  2021-05-31 02:10:18,536 [shard 0] init - Shutting down service level controller was successful
INFO  2021-05-31 02:10:18,536 [shard 0] init - Shutting down repair
INFO  2021-05-31 02:10:18,538 [shard 0] init - Shutting down repair was successful
INFO  2021-05-31 02:10:18,538 [shard 0] init - Shutting down rpc controller API
INFO  2021-05-31 02:10:18,539 [shard 0] init - Shutting down rpc controller API was successful
INFO  2021-05-31 02:10:18,539 [shard 0] init - Shutting down transport controller API
INFO  2021-05-31 02:10:18,539 [shard 0] init - Shutting down transport controller API was successful
INFO  2021-05-31 02:10:18,539 [shard 0] init - Shutting down native transport
INFO  2021-05-31 02:10:18,539 [shard 0] init - Shutting down native transport was successful
INFO  2021-05-31 02:10:18,539 [shard 0] init - Shutting down view update backlog broker
INFO  2021-05-31 02:10:18,541 [shard 0] init - Shutting down view update backlog broker was successful
INFO  2021-05-31 02:10:18,541 [shard 0] init - Shutting down cf cache hit rate calculator
INFO  2021-05-31 02:10:18,542 [shard 0] init - Shutting down cf cache hit rate calculator was successful
INFO  2021-05-31 02:10:18,542 [shard 0] init - Shutting down load meter
INFO  2021-05-31 02:10:18,542 [shard 0] init - Shutting down load meter was successful
INFO  2021-05-31 02:10:18,542 [shard 0] init - Shutting down snapshots API
INFO  2021-05-31 02:10:18,542 [shard 0] init - Shutting down snapshots API was successful
INFO  2021-05-31 02:10:18,542 [shard 0] init - Shutting down snapshots
INFO  2021-05-31 02:10:18,544 [shard 0] init - Shutting down snapshots was successful
INFO  2021-05-31 02:10:18,544 [shard 0] init - Shutting down auth service
INFO  2021-05-31 02:10:18,545 [shard 0] init - Shutting down auth service was successful
INFO  2021-05-31 02:10:18,545 [shard 0] init - Shutting down tracing
INFO  2021-05-31 02:10:18,546 [shard 0] init - Shutting down tracing was successful
INFO  2021-05-31 02:10:18,546 [shard 0] init - Shutting down storage service notifications
INFO  2021-05-31 02:10:18,546 [shard 0] init - Shutting down storage service notifications was successful
INFO  2021-05-31 02:10:18,546 [shard 0] init - Shutting down system distributed keyspace
INFO  2021-05-31 02:10:18,546 [shard 0] init - Shutting down system distributed keyspace was successful
INFO  2021-05-31 02:10:18,546 [shard 0] init - Shutting down gossiping
INFO  2021-05-31 02:10:18,547 [shard 0] gossip - gossip is already stopped
INFO  2021-05-31 02:10:18,547 [shard 0] init - Shutting down gossiping was successful
INFO  2021-05-31 02:10:18,547 [shard 0] init - Shutting down storage service notifications
INFO  2021-05-31 02:10:18,547 [shard 0] init - Shutting down storage service notifications was successful
INFO  2021-05-31 02:10:18,547 [shard 0] init - Shutting down repair API
INFO  2021-05-31 02:10:18,547 [shard 0] init - Shutting down repair API was successful
INFO  2021-05-31 02:10:18,547 [shard 0] init - Shutting down messaging service API
INFO  2021-05-31 02:10:18,548 [shard 0] init - Shutting down messaging service API was successful
INFO  2021-05-31 02:10:18,548 [shard 0] init - Shutting down storage service messaging
INFO  2021-05-31 02:10:18,549 [shard 0] init - Shutting down storage service messaging was successful
INFO  2021-05-31 02:10:18,549 [shard 0] init - Shutting down cdc log service
INFO  2021-05-31 02:10:18,550 [shard 0] init - Shutting down cdc log service was successful
INFO  2021-05-31 02:10:18,550 [shard 0] init - Shutting down CDC Generation Management service
INFO  2021-05-31 02:10:18,551 [shard 0] init - Shutting down CDC Generation Management service was successful
INFO  2021-05-31 02:10:18,551 [shard 0] init - Shutting down repair service
INFO  2021-05-31 02:10:18,553 [shard 0] init - Shutting down repair service was successful
INFO  2021-05-31 02:10:18,553 [shard 0] init - Shutting down drain storage proxy
INFO  2021-05-31 02:10:18,556 [shard 0] hints_manager - Asked to stop
INFO  2021-05-31 02:10:18,556 [shard 0] hints_manager - Asked to stop
INFO  2021-05-31 02:10:18,556 [shard 0] hints_manager - Stopped
INFO  2021-05-31 02:10:18,556 [shard 0] hints_manager - Stopped
INFO  2021-05-31 02:10:18,558 [shard 1] hints_manager - Asked to stop
INFO  2021-05-31 02:10:18,558 [shard 1] hints_manager - Asked to stop
INFO  2021-05-31 02:10:18,559 [shard 1] hints_manager - Stopped
INFO  2021-05-31 02:10:18,559 [shard 1] hints_manager - Stopped
INFO  2021-05-31 02:10:18,560 [shard 0] init - Shutting down drain storage proxy was successful
INFO  2021-05-31 02:10:18,560 [shard 0] init - Shutting down streaming service
INFO  2021-05-31 02:10:18,561 [shard 0] init - Shutting down streaming service was successful
INFO  2021-05-31 02:10:18,561 [shard 0] init - Shutting down Raft services
INFO  2021-05-31 02:10:18,562 [shard 0] init - Shutting down Raft services was successful
INFO  2021-05-31 02:10:18,562 [shard 0] init - Shutting down storage proxy RPC verbs
INFO  2021-05-31 02:10:18,563 [shard 0] init - Shutting down storage proxy RPC verbs was successful
INFO  2021-05-31 02:10:18,563 [shard 0] init - Shutting down sstables format selector
INFO  2021-05-31 02:10:18,563 [shard 0] init - Shutting down sstables format selector was successful
INFO  2021-05-31 02:10:18,563 [shard 0] init - Shutting down migration manager
INFO  2021-05-31 02:10:18,564 [shard 0] init - Shutting down migration manager was successful
INFO  2021-05-31 02:10:18,564 [shard 0] init - Shutting down database
INFO  2021-05-31 02:10:18,785 [shard 0] init - Shutting down database was successful
INFO  2021-05-31 02:10:18,785 [shard 0] init - Shutting down service_memory_limiter
INFO  2021-05-31 02:10:18,785 [shard 0] init - Shutting down service_memory_limiter was successful
INFO  2021-05-31 02:10:18,786 [shard 0] init - Shutting down sst_dir_semaphore
INFO  2021-05-31 02:10:18,786 [shard 0] init - Shutting down sst_dir_semaphore was successful
INFO  2021-05-31 02:10:18,787 [shard 0] init - Shutting down messaging service
INFO  2021-05-31 02:10:18,788 [shard 0] init - Shutting down messaging service was successful
INFO  2021-05-31 02:10:18,788 [shard 0] init - Shutting down API server
INFO  2021-05-31 02:10:18,793 [shard 0] init - Shutting down API server was successful
INFO  2021-05-31 02:10:18,793 [shard 0] init - Shutting down tracing instance
INFO  2021-05-31 02:10:18,794 [shard 0] init - Shutting down tracing instance was successful
INFO  2021-05-31 02:10:18,795 [shard 0] init - Shutting down migration manager notifier
INFO  2021-05-31 02:10:18,795 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2021-05-31 02:10:18,795 [shard 0] init - Shutting down prometheus API server
INFO  2021-05-31 02:10:18,798 [shard 0] init - Shutting down prometheus API server was successful
INFO  2021-05-31 02:10:18,799 [shard 0] init - Shutting down sighup
INFO  2021-05-31 02:10:18,801 [shard 0] init - Shutting down sighup was successful
INFO  2021-05-31 02:10:18,802 [shard 0] init - Scylla version 4.6.dev-0.20210530.76d7c761d1 shutdown complete.
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/804/artifact/logs-all.debug.2/1622427633098_cql_tests.TruncateTester.truncate_after_restart_test/node1.log
```
INFO  2021-05-31 02:10:01,041 [shard 0] stream_session - [Stream #4e352840-c1b5-11eb-867c-b36004a77bab] Streaming plan for Bootstrap-ks-index-10 succeeded, peers={127.0.38.2}, tx=0 KiB, 0.00 KiB/s, rx=0 KiB, 0.00 KiB/s
INFO  2021-05-31 02:20:26,083 [shard 0] compaction_manager - Asked to stop
```

**Comment by asias** [comment]
I saw:
 
313 INFO  2021-05-31 02:04:29,579 [shard 0] gossip - FatClient 127.0.38.2 has been silent for 10000ms, removing from gossip


So, the patch https://github.com/scylladb/scylla/pull/8777 will fix this issue.

**Comment by bhalevy** [comment]
Passing since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/811/testReport/cql_tests/TruncateTester/truncate_after_restart_test/ - closing
