### ISSUE TITLE
Cassandra stress mixed fails to achieve consistency during node reboot: 

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#8817]
*Installation details*
Scylla version (or git commit hash): 4.6.dev-0.20210531.b0c22f2e39 with build-id 6a2a6e52891ef3
f81d9a844a9b84d45da27c6cbe
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0c8cdedf851cde9cf (eu-north-1)

At `2021-06-04 09:31:54.392` a SoftRebootNode nemesis started on node 7 (13.48.190.83 | 10.0.0.28). The nemesis restarts the target instance, and wait for it to rejoin the cluster. However, shortly after the target node rose after the reboot, one of the cassandra stress mixed threads started to show Read/Write timeout errors:
```
09:34:56.417 [cluster1-nio-worker-12] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.0.28:9042-51, inFlight=2, closed=false] Keyspace set to keyspace1
READ,      277723413,   10800,   10800,   10800,     5.7,     3.5,    15.7,    28.2,   107.8,   228.5,19010.0,  0.01167,      0,      0,       0,       0,       0,       0
WRITE,     277724888,   10836,   10836,   10836,     3.6,     2.2,    10.9,    16.8,    39.1,   121.1,19010.0,  0.01167,      0,      0,       0,       0,       0,       0
total,     555448301,   21635,   21635,   21635,     4.6,     2.7,    13.8,    21.9,    79.9,   228.5,19010.0,  0.01167,      0,      0,       0,       0,       0,       0
READ,      277778296,   10977,   10977,   10977,     5.4,     3.5,    15.1,    22.1,    46.4,   116.9,19015.0,  0.01167,      0,      0,       0,       0,       0,       0
WRITE,     277780733,   11169,   11169,   11169,     3.6,     2.3,    10.6,    15.1,    36.5,    99.8,19015.0,  0.01167,      0,      0,       0,       0,       0,       0
total,     555559029,   22146,   22146,   22146,     4.5,     2.9,    13.2,    19.3,    41.8,   116.9,19015.0,  0.01167,      0,      0,       0,       0,       0,       0
READ,      277831403,   10621,   10621,   10621,     5.8,     3.3,    15.9,    40.8,    98.8,   186.6,19020.0,  0.01167,      0,      0,       0,       0,       0,       0
WRITE,     277833329,   10519,   10519,   10519,     3.6,     2.0,    11.1,    18.7,    41.8,   142.3,19020.0,  0.01167,      0,      0,       0,       0,       0,       0
total,     555664732,   21141,   21141,   21141,     4.7,     2.6,    13.7,    31.2,    85.7,   186.6,19020.0,  0.01167,      0,      0,       0,       0,       0,       0
READ,      277887646,   11249,   11249,   11249,     5.4,     3.3,    14.9,    31.1,   126.3,   233.8,19025.0,  0.01167,      0,      0,       0,       0,       0,       0
WRITE,     277888479,   11030,   11030,   11030,     3.5,     2.1,    10.2,    17.6,    80.4,   195.8,19025.0,  0.01167,      0,      0,       0,       0,       0,       0
total,     555776125,   22279,   22279,   22279,     4.5,     2.6,    13.0,    24.0,   110.7,   233.8,19025.0,  0.01167,      0,      0,       0,       0,       0,       0
READ,      277950606,   12592,   12592,   12592,     4.8,     3.2,    15.1,    23.8,    45.8,    76.4,19030.0,  0.01166,      0,      0,       0,       0,       0,       0
WRITE,     277951320,   12568,   12568,   12568,     3.1,     2.0,     9.7,    15.8,    23.3,    57.8,19030.0,  0.01166,      0,      0,       0,       0,       0,       0
total,     555901926,   25160,   25160,   25160,     4.0,     2.5,    12.7,    20.5,    37.4,    76.4,19030.0,  0.01166,      0,      0,       0,       0,       0,       0
09:35:25.316 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.20:9042-1, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
09:35:25.317 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.20:9042-1, inFlight=0, closed=false] heartbeat query succeeded
READ,      278008619,   11603,   11603,   11603,     5.4,     2.8,    16.4,    53.5,   145.8,   262.9,19035.0,  0.01166,      0,      0,       0,       0,       0,       0
WRITE,     278007720,   11280,   11280,   11280,     3.3,     1.8,     9.9,    24.8,    90.2,   344.2,19035.0,  0.01166,      0,      0,       0,       0,       0,       0
total,     556016339,   22883,   22883,   22883,     4.4,     2.2,    13.2,    39.8,   129.0,   344.2,19035.0,  0.01166,      0,      0,       0,       0,       0,       0
READ,      278072716,   12819,   12819,   12819,     4.9,     3.0,    15.0,    35.3,    89.5,   196.3,19040.0,  0.01166,      0,      0,       0,       0,       0,       0
WRITE,     278071489,   12754,   12754,   12754,     2.9,     1.9,     8.5,    16.7,    47.1,   129.2,19040.0,  0.01166,      0,      0,       0,       0,       0,       0
total,     556144205,   25573,   25573,   25573,     3.9,     2.4,    12.0,    26.6,    82.5,   196.3,19040.0,  0.01166,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
```

Until eventually the it due to IOException:
```
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [33324f344e36344c3231]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)

        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
READ,      278137982,     912,     912,     912,    95.0,     2.3,    18.9,  2023.8, 16139.7, 20233.3,19063.1,  0.01167,      1,      0,       0,       0,       0,       0
WRITE,     278136932,     952,     952,     952,     2.7,     1.4,     7.5,    21.1,    86.5,    90.3,19063.1,  0.01167,      0,      0,       0,       0,       0,       0
total,     556274914,    1864,    1864,    1864,    47.9,     1.8,    12.2,    53.2, 12138.3, 20233.3,19063.1,  0.01167,      1,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [323637354d3934333630]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)

com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x10 on key(s) [36353639344c36315030]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)

        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
        at org.apache.cassandra.strecom.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
ss.operations.predefined.CqlOperation.run(CqlOperation.java:109)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
java.io.IOException: Operation x10 on key(s) [4d4d38344d504b4d3031]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)

        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
```
Stress command:
`cassandra-stress mixed cl=QUORUM duration=4320m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native  -rate threads=100 -pop seq=1..100000000 -log interval=5`

Rest of the stresses: https://github.com/scylladb/scylla-cluster-tests/blob/master/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml

None of the other stresses seem to have experienced this issue.

From the nodes' logs, I could only find one error at the time of the failure:
In several times in the run, some nodes experienced several semaphore_timed_out errors for a small stretch of time.
Specifically around the time of the stress failure, between `2021-06-04 09:31:15.000` to `2021-06-04 09:35:38.000`, node 6 (13.49.80.254 | 10.0.2.25) suffered from multiple Semaphore timeouts:
```
2021-06-04 09:32:59.000: (DatabaseLogEvent Severity.WARNING): type=SEMAPHORE_TIME_OUT regex=semaphore_timed_out line_number=47982 node=Node longevity-tls-50gb-3d-master-db-node-05e95283-6 [13.49.80.254 | 10.0.2.25] (seed: False)
2021-06-04T09:32:59+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-6 !WARNING | scylla:  [shard 2] storage_proxy - Failed to apply mutation from 10.0.2.20#2: seastar::semaphore_timed_out (Semaphore timedout)
2021-06-04 09:32:59.000: (DatabaseLogEvent Severity.WARNING): type=SEMAPHORE_TIME_OUT regex=semaphore_timed_out line_number=47983 node=Node longevity-tls-50gb-3d-master-db-node-05e95283-6 [13.49.80.254 | 10.0.2.25] (seed: False)
2021-06-04T09:32:59+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-6 !WARNING | scylla:  [shard 3] storage_proxy - Failed to apply mutation from 10.0.3.167#3: seastar::semaphore_timed_out (Semaphore timedout)
2021-06-04 09:32:59.000: (DatabaseLogEvent Severity.WARNING): type=SEMAPHORE_TIME_OUT regex=semaphore_timed_out line_number=47985 node=Node longevity-tls-50gb-3d-master-db-node-05e95283-6 [13.49.80.254 | 10.0.2.25] (seed: False)
2021-06-04T09:32:59+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-6 !WARNING | scylla:  [shard 7] storage_proxy - Failed to apply mutation from 10.0.3.167#7: seastar::semaphore_timed_out (Semaphore timedout)

...

2021-06-04T09:35:38+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-6 !WARNING | scylla:  [shard 7] storage_proxy - Failed to apply mutation from 10.0.0.28#7: seastar::semaphore_timed_out (Semaphore timedout)
2021-06-04 09:35:38.000: (DatabaseLogEvent Severity.WARNING): type=SEMAPHORE_TIME_OUT regex=semaphore_timed_out line_number=48612 node=Node longevity-tls-50gb-3d-master-db-node-05e95283-6 [13.49.80.254 | 10.0.2.25] (seed: False)
2021-06-04T09:35:38+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-6 !WARNING | scylla:  [shard 0] storage_proxy - Failed to apply mutation from 10.0.0.28#0: seastar::semaphore_timed_out (Semaphore timedout)
2021-06-04 09:35:38.000: (DatabaseLogEvent Severity.WARNING): type=SEMAPHORE_TIME_OUT regex=semaphore_timed_out line_number=48613 node=Node longevity-tls-50gb-3d-master-db-node-05e95283-6 [13.49.80.254 | 10.0.2.25] (seed: False)
2021-06-04T09:35:38+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-6 !WARNING | scylla:  [shard 4] storage_proxy - Failed to apply mutation from 10.0.0.28#4: seastar::semaphore_timed_out (Semaphore timedout)
2021-06-04 09:35:38.000: (DatabaseLogEvent Severity.WARNING): type=SEMAPHORE_TIME_OUT regex=semaphore_timed_out line_number=48614 node=Node longevity-tls-50gb-3d-master-db-node-05e95283-6 [13.49.80.254 | 10.0.2.25] (seed: False)
2021-06-04T09:35:38+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-6 !ERR     | scylla:  [shard 8] storage_proxy - exception during mutation write to 10.0.2.25: seastar::semaphore_timed_out (Semaphore timedout)
2021-06-04 09:35:38.000: (DatabaseLogEvent Severity.WARNING): type=SEMAPHORE_TIME_OUT regex=semaphore_timed_out line_number=48615 node=Node longevity-tls-50gb-3d-master-db-node-05e95283-6 [13.49.80.254 | 10.0.2.25] (seed: False)
2021-06-04T09:35:38+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-6 !WARNING | scylla:  [shard 2] storage_proxy - Failed to apply mutation from 10.0.1.147#2: seastar::semaphore_timed_out (Semaphore timedout)
```

Also, right after node 7 was fully initialized, it experienced two Semaphore timeouts as well:
```
2021-06-04T09:34:52+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-7 !INFO    | scylla:  [shard 0] init - Scylla version 4.6.dev-0.20210531.b0c22f2e39 initialization completed.
2021-06-04T09:34:52+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-7 !INFO    | systemd-timesyncd[532]: Initial synchronization to time server [2001:67c:1560:8003::c8]:123 (ntp.ubuntu.com).
2021-06-04T09:34:56+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-7 !INFO    | sshd[1356]: Accepted publickey for scyllaadm from 10.0.3.76 port 49302 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8
2021-06-04T09:34:56+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-7 !INFO    | sshd[1356]: pam_unix(sshd:session): session opened for user scyllaadm by (uid=0)
2021-06-04T09:34:56+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-7 !INFO    | systemd-logind[666]: New session 4 of user scyllaadm.
2021-06-04T09:34:56+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-7 !INFO    | systemd[1]: Started Session 4 of user scyllaadm.
2021-06-04T09:34:57+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-7 !WARNING | scylla:  [shard 4] storage_proxy - Failed to apply mutation from 10.0.2.20#4: seastar::semaphore_timed_out (Semaphore timedout)
2021-06-04T09:34:57+00:00  longevity-tls-50gb-3d-master-db-node-05e95283-7 !WARNING | scylla:  [shard 4] storage_proxy - Failed to apply mutation from 10.0.2.20#4: seastar::semaphore_timed_out (Semaphore timedout)
```
I couldn't find anuthing on node 1's (13.51.69.113 | 10.0.2.20) log to explain the timeouts on node 7's side.

Logs:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                           Log links for testrun with test id 05e95283-ed77-47ba-86e5-94543ebc8334                                            |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                         |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| 20210604_093610 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/05e95283-ed77-47ba-86e5-94543ebc8334/20210604_093610/db-cluster-05e95283.zip  |
| 20210604_093610 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/05e95283-ed77-47ba-86e5-94543ebc8334/20210604_093610/loader-set-05e95283.zip  |
| 20210604_093610 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/05e95283-ed77-47ba-86e5-94543ebc8334/20210604_093610/monitor-set-05e95283.zip |
| 20210604_093610 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/05e95283-ed77-47ba-86e5-94543ebc8334/20210604_093610/sct-runner-05e95283.zip  |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

Monitor: http://13.51.238.247:3000/d/rhHNOt6Mk/longevity-50gb-3days-scylla-per-server-metrics-nemesis-master?orgId=1&from=1622771755813&to=1622808453129

Living nodes:
```
longevity-tls-50gb-3d-master-db-node-05e95283-1
longevity-tls-50gb-3d-master-db-node-05e95283-1
```

**Comment by ShlomiBalalis** [comment]
accidental duplicate of #8818, closing.
