### ISSUE TITLE
scylla_setup failed on debian based OSes with error:  seastar - Could not setup Async I/O: Resource temporarily unavailable. 

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#8845]
Scylla version: ScyllaDB version: 4.3.4-0.20210525.d737d56a0

During rolling upgrade for debian based OS: debian 10, ubuntu-18.04, ubuntu-20.04 with scylla version 4.3.4 `scylla_setup` failed with next errors:
```
15:37:47  Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3 --no-io-setup  --swap-directory / '
15:37:47  Exit code: 1
15:37:47  Stdout:
15:37:47  Unpacking xfsprogs (4.20.0-1) ...
15:37:47  Setting up libreadline5:amd64 (5.2+dfsg-3+b13) ...
15:37:47  Setting up xfsprogs (4.20.0-1) ...
15:37:47  update-initramfs: deferring update (trigger activated)
15:37:47  Processing triggers for man-db (2.8.5-2) ...
15:37:47  Processing triggers for libc-bin (2.28-10) ...
15:37:47  Processing triggers for initramfs-tools (0.133+deb10u1) ...
15:37:47  update-initramfs: Generating /boot/initrd.img-4.19.0-16-cloud-amd64
15:37:47  Please upgrade to a newer kernel version.
15:37:47  see https://docs.scylladb.com/troubleshooting/error_messages/kb_fs_not_qualified_aio/ for details
15:37:47  Stderr:
15:37:47  /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
15:37:47  ERROR 2021-06-10 08:37:30,666 [shard 2] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
15:37:47  Traceback (most recent call last):
15:37:47  File "/opt/scylladb/scripts/libexec/scylla_setup", line 350, in <module>
15:37:47  run('{}/scylla_kernel_check'.format(scriptsdir()))
15:37:47  File "/opt/scylladb/scripts/scylla_util.py", line 512, in run
15:37:47  return subprocess.run(cmd, stdout=stdout, stderr=stderr, shell=shell, check=exception, env=scylla_env).returncode
15:37:47  File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 512, in run
15:37:47  raise CalledProcessError(retcode, process.args,
15:37:47  subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_kernel_check']' returned non-zero exit status 1.
```
Next job failed:
https://jenkins.scylladb.com/view/nexts/job/scylla-4.4/job/rolling-upgrade/job/rolling-upgrade-debian10-test/44
https://jenkins.scylladb.com/job/scylla-4.4/job/rolling-upgrade/job/rolling-upgrade-ubuntu18.04-test/38
https://jenkins.scylladb.com/view/nexts/job/scylla-4.4/job/rolling-upgrade/job/rolling-upgrade-ubuntu20.04-test/41

db logs:
debian-10: https://cloudius-jenkins-test.s3.amazonaws.com/03094117-c659-4fee-9a81-6652b59748ed/20210611_075017/db-cluster-03094117.zip
ubuntu-18.04: https://cloudius-jenkins-test.s3.amazonaws.com/1bf3be1c-2aa9-4743-9677-93ae6d1015fd/20210610_083805/db-cluster-1bf3be1c.zip
ubuntu-20.04: https://cloudius-jenkins-test.s3.amazonaws.com/c0c3e89b-0aa2-4b85-a7fa-cdd086879ad2/20210610_083813/db-cluster-c0c3e89b.zip

**Comment by roydahan** [comment]
dup of #8713
