### ISSUE TITLE
`Semaphore timed out: _read_concurrency_sem` raised after upgrading the first node

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#8886]
*Installation details*
Scylla version (or git commit hash): upgrade 4.5.rc2-0.20210602.d92a26636 to 4.6.dev-0.20210613.846f0bd16e4
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

test job: https://jenkins.scylladb.com/view/master/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/177/

The first node was successfully upgraded from 4.5.rc2-0.20210602.d92a26636 to 4.6.dev-0.20210613.846f0bd16e4, But two kinds of error started to raise after upgrade. And the fill_db_data verify after upgrading the first node failed.

I saw many `storage_proxy - Failed to apply mutation from 10.142.0.65#3: seastar::semaphore_timed_out (Semaphore timedout)`
 and `storage_proxy - Exception when communicating with 10.142.0.60, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)` from the first upgraded node.

### Key logs with timestamp
[amos@amos-centos7 e2668405-c50c-403b-9f13-e6c79f2a1ec2]$ cat sct.log |grep -E '> Step| begin$|ended$'
< t:2021-06-18 04:40:15,371 f:upgrade_test.py l:534  c:UpgradeTest          p:INFO  > Step1 - Upgrade First Node
< t:2021-06-18 04:40:15,371 f:upgrade_test.py l:537  c:UpgradeTest          p:INFO  > Upgrade Node rolling-upgrade-master-centos-db-node-e2668405-0-1 begin

2021-06-18T04:50:49+00:00  rolling-upgrade-master-centos-db-node-e2668405-0-1 !WARNING | scylla: [shard 3] storage_proxy - Failed to apply mutation from 10.142.0.65#3: seastar::semaphore_timed_out (Semaphore timedout)
< t:2021-06-18 06:02:38,239 f:upgrade_test.py l:539  c:UpgradeTest          p:INFO  > Upgrade Node rolling-upgrade-master-centos-db-node-e2668405-0-1 ended

db-node-e2668405-0-1 !ERR | scylla: [shard 6] storage_proxy - Exception when communicating with 10.142.0.60, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)

### Logs

- DB log: https://cloudius-jenkins-test.s3.amazonaws.com/e2668405-c50c-403b-9f13-e6c79f2a1ec2/20210618_065602/db-cluster-e2668405.zip 
- Loader log:  https://cloudius-jenkins-test.s3.amazonaws.com/e2668405-c50c-403b-9f13-e6c79f2a1ec2/20210618_065602/loader-set-e2668405.zip  
- SCT log: https://cloudius-jenkins-test.s3.amazonaws.com/e2668405-c50c-403b-9f13-e6c79f2a1ec2/20210618_065602/sct-runner-e2668405.zip  

### SCT Fail in fill_db_data verify:

```
14:55:51  2021-06-18 06:51:12.840: (TestFrameworkEvent Severity.ERROR) period_type=not-set event_id=737b61bc-6403-4f2a-b205-bef1ad1bbc19, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
14:55:51  File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/upgrade_test.py", line 551, in test_rolling_upgrade
14:55:51  self.fill_and_verify_db_data('after upgraded one node')
14:55:51  File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/upgrade_test.py", line 437, in fill_and_verify_db_data
14:55:51  self.verify_db_data()
14:55:51  File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/fill_db_data.py", line 3287, in verify_db_data
14:55:51  self.run_db_queries(session, session.default_fetch_size)
14:55:51  File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/fill_db_data.py", line 3209, in run_db_queries
14:55:51  raise ex
14:55:51  File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/fill_db_data.py", line 3205, in run_db_queries
14:55:51  res = session.execute(item['queries'][i])
14:55:51  File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/utils/common.py", line 1262, in execute_verbose
14:55:51  return execute_orig(*args, **kwargs)
14:55:51  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
14:55:51  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
14:55:51  cassandra.OperationTimedOut: errors={'10.142.0.77:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.142.0.77:9042
```

**Comment by roydahan** [comment]
@fgelcer & @dkropachev do you see this issue also on this week runs?

**Comment by fgelcer** [comment]
> @fgelcer & @dkropachev do you see this issue also on this week runs?

on last week's build @amoskong reported this issue (build 177)
on build 178 seems not to have failed in that point (ran for 5h 48 min) but timed out

**Comment by dkropachev** [comment]
@roydahan , did not see it on this week

**Comment by slivne** [comment]
need to check that we are not overloading the cluster 

this is a regression according to QA the workload did not change
