### ISSUE TITLE
sstablemetadata: add support to inspect sstable using zstd compression

### ISSUE THREAD

**Issue by fyang13** [scylladb/scylla#8887]
For the sstable using "org.apache.cassandra.io.compress.ZstdCompressor" compression, sstablemetadata can't inspect the sstable files, always getting error:

Exception in thread "main" java.lang.RuntimeException: Cannot create CompressionParams for stored parameters
        at org.apache.cassandra.io.compress.CompressionMetadata.<init>(CompressionMetadata.java:117)
        at org.apache.cassandra.io.compress.CompressionMetadata.create(CompressionMetadata.java:90)
        at org.apache.cassandra.tools.SSTableMetadataViewer.main(SSTableMetadataViewer.java:155)
Caused by: org.apache.cassandra.exceptions.ConfigurationException: Could not create Compression for type org.apache.cassandra.io.compress.ZstdCompressor
        at org.apache.cassandra.schema.CompressionParams.parseCompressorClass(CompressionParams.java:208)
        at org.apache.cassandra.schema.CompressionParams.<init>(CompressionParams.java:153)
        at org.apache.cassandra.io.compress.CompressionMetadata.<init>(CompressionMetadata.java:113)
        ... 2 more
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.io.compress.ZstdCompressor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.cassandra.schema.CompressionParams.parseCompressorClass(CompressionParams.java:204)
        ... 4 more

Same command running against sstable using LZ4Compressor without issue.

*Installation details*
Scylla version (or git commit hash): 4.2.3, 4.2.4
Cluster size: 16 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.6

**Comment by slivne** [comment]
We added zstd to scylla but not to the tools - there are potentially other gotchas / sstabledump / ...

Need to see if upstream added zstd if so great we maybe able to get this "easily"

If not we need to cinsider whats the amount of work for adding this to the tools.

(and next time - to note that adding a compression is more complex then only scylla core)

**Comment by kbr-** [comment]
Zstd was added to Cassandra 4.0 which is not yet released which is why we didn't yet merge the 4.0 branch into scylla-tools-java... see https://github.com/scylladb/scylla-tools-java/issues/140

But we can try backporting the Zstd support change manually.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
