### ISSUE TITLE
database shutdown races with shard_reader

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8933]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/858/artifact/logs-all.release.2/1624849152614_update_cluster_layout_tests.TestUpdateClusterLayout.simple_add_new_node_while_adding_info_2_test/node4.log
```
Scylla version 4.6.dev-0.20210627.121971ec0 with build-id fe3d4be31e54e0b4c318b652015ae65f1d7ba749 starting ...
...
INFO  2021-06-28 02:59:04,596 [shard 0] init - Shutting down database
terminate called after throwing an instance of 'seastar::gate_closed_exception'
  what():  gate closed
Aborting on shard 1.
Backtrace:
  0x406a4c8
  0x409c182
  0x7fc255a7b1df
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libc.so.6+0x3d9d4
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libc.so.6+0x268a3
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libstdc++.so.6+0x9e925
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libstdc++.so.6+0xaa1ab
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libstdc++.so.6+0xaa216
  0xecb8da
  0x367ffc3
  0x150e871
  0x1511761
  0x407d3bf
  0x407e647
  0x409c70e
  0x4047eba
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libpthread.so.0+0x93f8
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libc.so.6+0x101902
```

Decoded from http://downloads.scylladb.com/unstable/scylla/master/relocatable/2021-06-27T17:44:39Z/scylla-package.tar.gz:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:754
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:784
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:796
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3559
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3541
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3537
?? ??:0
/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libc.so.6 0x3d9d4 
/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libc.so.6 0x268a3 
/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libstdc++.so.6 0x9e925 
/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libstdc++.so.6 0xaa1ab 
/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/121971ec0f0a2bdd5135b0e390e8ba15d4547c71/scylla/libreloc/libstdc++.so.6 0xaa216 
__clang_call_terminate at main.cc:?
reader_concurrency_semaphore::on_permit_created(reader_permit::impl&) at ./reader_concurrency_semaphore.cc:609
 (inlined by) impl at ./reader_concurrency_semaphore.cc:91
 (inlined by) shared_ptr_count_for<reader_concurrency_semaphore &, const schema *const &, std::basic_string_view<char, std::char_traits<char> > &> at ././seastar/include/seastar/core/shared_ptr.hh:467
 (inlined by) seastar::shared_ptr<reader_permit::impl> seastar::shared_ptr_make_helper<reader_permit::impl, false>::make<reader_concurrency_semaphore&, schema const* const&, std::basic_string_view<char, std::char_traits<char> >&>(reader_concurrency_semaphore&, schema const* const&, std::basic_string_view<char, std::char_traits<char> >&) at ././seastar/include/seastar/core/shared_ptr.hh:631
 (inlined by) seastar::shared_ptr<reader_permit::impl> seastar::make_shared<reader_permit::impl, reader_concurrency_semaphore&, schema const* const&, std::basic_string_view<char, std::char_traits<char> >&>(reader_concurrency_semaphore&, schema const* const&, std::basic_string_view<char, std::char_traits<char> >&) at ././seastar/include/seastar/core/shared_ptr.hh:649
 (inlined by) reader_permit at ./reader_concurrency_semaphore.cc:174
 (inlined by) reader_concurrency_semaphore::make_permit(schema const*, char const*) at ./reader_concurrency_semaphore.cc:619
operator() at ./mutation_reader.cc:1691
 (inlined by) seastar::future<(anonymous namespace)::shard_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::reader_and_buffer_fill_result> seastar::futurize<seastar::future<(anonymous namespace)::shard_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::reader_and_buffer_fill_result> >::invoke<(anonymous namespace)::shard_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_31&>((anonymous namespace)::shard_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_31&) at ././seastar/include/seastar/core/future.hh:2135
seastar::smp_message_queue::async_work_item<(anonymous namespace)::shard_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_31>::run_and_dispose() at ././seastar/include/seastar/core/smp.hh:231
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2230
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2639
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2798
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3975
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(std::__invoke_other, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>, void>::type std::__invoke_r<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
```

**Comment by bhalevy** [comment]
Botond, please look into this.

Cc @xemul

**Comment by bhalevy** [comment]
Unfortunately there's no coredmp, just this backtrace.

**Comment by denesb** [comment]
> shutdown races with shard_reader

This is normal, the gate **is** the synchronization. The problem is that for some reason I made `on_permit_created()` `noexcept`, when it really isn't. Will send a fix.

**Comment by bhalevy** [comment]
I'd consider entering the gate in `reader_concurrency_semaphore::make_permit` before constructing (and enlisting) a new permit,
and drop `on_permit_created`.

**Comment by denesb** [comment]
I think that would be a step in the wrong direction, best keep this code where all paths creating permits converge: in the permit constructor.

**Comment by bhalevy** [comment]
@avikivity https://github.com/bhalevy/scylla/commit/8ac83fffa9dc25f801b06e6911c914c77173ac90 prevents the errors we currently see in failing dtests like https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/864/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/simple_add_new_node_while_adding_info_1_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1148, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1202, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node4', ['ERROR 2021-07-05 02:43:39,078 [shard 0] storage_proxy - Exception when communicating with 127.0.53.4, to read from system.batchlog: seastar::gate_closed_exception (gate closed)', 'ERROR 2021-07-05 02:43:39,079 [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_failure_exception (Operation failed for system.batchlog - received 0 responses and 1 failures from 1 CL=ONE.)'])]
```

Just note it relies on seastar::gate_holder that is not yet available in scylla/master

**Comment by avikivity** [comment]
fe4002c6c42d9eb1b83b72953e4b929d7dc09fd7
