### ISSUE TITLE
Segfault in counters::_steady_now.load during migrate_sstable_with_large_row_number_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8952]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/860/artifact/logs-all.release.2/1625020982195_sstableloader_test.TestMigration_with_2_1_x.migrate_sstable_with_large_row_number_test/node1.log
```
Scylla version 4.6.dev-0.20210629.edd54a946 with build-id f9892d08b6d63d264d1643385014ff69df6d2a6a starting ...
...
INFO  2021-06-30 02:41:35,078 [shard 0] init - Scylla version 4.6.dev-0.20210629.edd54a946 initialization completed.
INFO  2021-06-30 02:41:35,082 [shard 0] compaction - [Compact system.truncated af8a7240-d94c-11eb-8442-f27218bff0f8] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-23xhzwei/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-14-big-Data.db:level=0, ]. 82kB to 76kB (~93% of original) in 5ms = 15MB/s. ~256 total partitions merged to 2.
INFO  2021-06-30 02:41:49,190 [shard 1] compaction - [Compact keyspace1.standard1 b7f41260-d94c-11eb-b30c-f27318bff0f8] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-23xhzwei/test/node1/data/keyspace1/standard1-8c447290d94c11eb8bffaf26c0db80b1/md-5-big-Data.db:level=0:origin=memtable, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-23xhzwei/test/node1/data/keyspace1/standard1-8c447290d94c11eb8bffaf26c0db80b1/md-3-big-Data.db:level=0:origin=memtable, ]
INFO  2021-06-30 02:41:49,268 [shard 0] compaction - [Compact keyspace1.standard1 b7fff940-d94c-11eb-8442-f27218bff0f8] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-23xhzwei/test/node1/data/keyspace1/standard1-8c447290d94c11eb8bffaf26c0db80b1/md-4-big-Data.db:level=0:origin=memtable, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-23xhzwei/test/node1/data/keyspace1/standard1-8c447290d94c11eb8bffaf26c0db80b1/md-2-big-Data.db:level=0:origin=memtable, ]
Segmentation fault on shard 0.
Backtrace:
  0x4045f88
  0x40777f6
  0x7f9cabd141df
  0x2572584
  0x2572c85
  0x405819b
  0x4076f08
  0x405a135
  0x3ff5114
  0x3ff4516
  0xec9661
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/edd54a946350689a5032395cbdd799d21481ec39/scylla/libreloc/libc.so.6+0x281e1
  0xec67ad
```

Decoded:
```
scylla/libexec/scylla: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=f9892d08b6d63d264d1643385014ff69df6d2a6a, not stripped

  0x4045f88
  0x40777f6
  0x7f9cabd141df
  0x2572584
  0x2572c85
  0x405819b
  0x4076f08
  0x405a135
  0x3ff5114
  0x3ff4516
  0xec9661
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:754
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:784
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:796
 (inlined by) seastar::sigsegv_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3555
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3541
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3537
?? ??:0
std::__atomic_base<long>::load(std::memory_order) const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/atomic_base.h:426
 (inlined by) seastar::lowres_clock_impl::steady_now() at ././seastar/include/seastar/core/lowres_clock.hh:61
 (inlined by) seastar::lowres_clock::now() at ././seastar/include/seastar/core/lowres_clock.hh:119
 (inlined by) db::commitlog::segment::reset_sync_time() at ./db/commitlog/commitlog.cc:642
 (inlined by) db::commitlog::segment::sync() at ./db/commitlog/commitlog.cc:668
 (inlined by) operator() at ./db/commitlog/commitlog.cc:1939
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<db::commitlog::segment_manager::sync()::$_32, seastar::shared_ptr<db::commitlog::segment>&>(db::commitlog::segment_manager::sync()::$_32&&, seastar::shared_ptr<db::commitlog::segment>&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<db::commitlog::segment_manager::sync()::$_32, seastar::shared_ptr<db::commitlog::segment>&>(db::commitlog::segment_manager::sync()::$_32&&, seastar::shared_ptr<db::commitlog::segment>&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) seastar::future<void> seastar::parallel_for_each<__gnu_cxx::__normal_iterator<seastar::shared_ptr<db::commitlog::segment>*, std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > > >, db::commitlog::segment_manager::sync()::$_32>(__gnu_cxx::__normal_iterator<seastar::shared_ptr<db::commitlog::segment>*, std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > > >, __gnu_cxx::__normal_iterator<seastar::shared_ptr<db::commitlog::segment>*, std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > > >, db::commitlog::segment_manager::sync()::$_32&&) at ././seastar/include/seastar/core/loop.hh:554
 (inlined by) seastar::future<void> seastar::internal::parallel_for_each_impl<std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32>(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&) at ././seastar/include/seastar/core/loop.hh:598
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<seastar::future<void> (*&)(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&), std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32>(seastar::future<void> (*&)(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&), std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<seastar::future<void> (*&)(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&), std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32>(seastar::future<void> (*&)(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&), std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) seastar::future<void> seastar::parallel_for_each<std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32>(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&) at ././seastar/include/seastar/core/loop.hh:610
 (inlined by) db::commitlog::segment_manager::sync() at ./db/commitlog/commitlog.cc:1938
operator() at ./db/commitlog/commitlog.cc:1951
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<db::commitlog::segment_manager::on_timer()::$_33>(db::commitlog::segment_manager::on_timer()::$_33&&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<db::commitlog::segment_manager::on_timer()::$_33>(db::commitlog::segment_manager::on_timer()::$_33&&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) auto seastar::internal::invoke_func_with_gate<db::commitlog::segment_manager::on_timer()::$_33>(seastar::gate&, db::commitlog::segment_manager::on_timer()::$_33&&) at ././seastar/include/seastar/core/gate.hh:133
 (inlined by) auto seastar::with_gate<db::commitlog::segment_manager::on_timer()::$_33>(seastar::gate&, db::commitlog::segment_manager::on_timer()::$_33&&) at ././seastar/include/seastar/core/gate.hh:151
 (inlined by) db::commitlog::segment_manager::on_timer() at ./db/commitlog/commitlog.cc:1949
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
 (inlined by) void seastar::reactor::complete_timers<seastar::timer_set<seastar::timer<seastar::lowres_clock>, &seastar::timer<seastar::lowres_clock>::_link>, boost::intrusive::list<seastar::timer<seastar::lowres_clock>, boost::intrusive::member_hook<seastar::timer<seastar::lowres_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::lowres_clock>::_link> >, seastar::reactor::do_expire_lowres_timers()::$_72>(seastar::timer_set<seastar::timer<seastar::lowres_clock>, &seastar::timer<seastar::lowres_clock>::_link>&, boost::intrusive::list<seastar::timer<seastar::lowres_clock>, boost::intrusive::member_hook<seastar::timer<seastar::lowres_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::lowres_clock>::_link> >&, seastar::reactor::do_expire_lowres_timers()::$_72&&) at ./build/release/seastar/./seastar/src/core/reactor.cc:1242
 (inlined by) seastar::reactor::do_expire_lowres_timers() at ./build/release/seastar/./seastar/src/core/reactor.cc:2280
seastar::reactor::poll_once() at ./build/release/seastar/./seastar/src/core/reactor.cc:2894
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:2792
 (inlined by) bool std::__invoke_impl<bool, seastar::reactor::run()::$_79&>(std::__invoke_other, seastar::reactor::run()::$_79&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::enable_if<is_invocable_r_v<bool, seastar::reactor::run()::$_79&>, bool>::type std::__invoke_r<bool, seastar::reactor::run()::$_79&>(seastar::reactor::run()::$_79&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:113
 (inlined by) std::_Function_handler<bool (), seastar::reactor::run()::$_79>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
std::function<bool ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2818
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:216
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:124
main at ./main.cc:507
```

Coredump: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/860/artifact/logs-all.release.2/1625020982195_sstableloader_test.TestMigration_with_2_1_x.migrate_sstable_with_large_row_number_test/node1-scylla.1281396.1625020914.core.gz
Reloc package: http://downloads.scylladb.com.s3.amazonaws.com/unstable/scylla/master/relocatable/2021-06-29T08%3A57%3A43Z/scylla-package.tar.gz

**Comment by bhalevy** [comment]
@xemul / @avikivity can you please look into this?

**Comment by avikivity** [comment]
This can't possibly segfault, it's a load from a static variable.

**Comment by bhalevy** [comment]
Could this be related to #8828?

**Comment by bhalevy** [comment]
Actually, since it is a static variable it's unrelated to seastar memory.

**Comment by raphaelsc** [comment]
On Wed, Jun 30, 2021 at 9:22 AM Benny Halevy ***@***.***> wrote:
>
> Actually, since it is a static variable it's unrelated to seastar memory.

can that be a compiler bug? found that old GCC had a bug when loading
unaligned atomic data, but we do enforce cacheline alignment on
counters struct.

**Comment by avikivity** [comment]
There is no need to cachline align atomics. They would be impossible to use.

They need to be aligned, but the compiler arranges for that (and on x86 even that is unneeded).

**Comment by bhalevy** [comment]
```
#0  db::commitlog::segment::reset_sync_time (this=0x0) at db/commitlog/commitlog.cc:642
#1  db::commitlog::segment::sync (this=0x0) at db/commitlog/commitlog.cc:668
#2  db::commitlog::segment_manager::sync()::$_32::operator()(seastar::shared_ptr<db::commitlog::segment>) const (this=<optimized out>, s=...) at db/commitlog/commitlog.cc:1939
```

**Comment by bhalevy** [comment]
```
(gdb) fr 10
#10 db::commitlog::segment_manager::sync (this=this@entry=0x600000267800) at db/commitlog/commitlog.cc:1938
1938        _background_sync = parallel_for_each(_segments, [](sseg_ptr s) {
(gdb) p _segments
$3 = {
  <std::_Vector_base<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >> = {
    _M_impl = {
      <std::allocator<seastar::shared_ptr<db::commitlog::segment> >> = {
        <__gnu_cxx::new_allocator<seastar::shared_ptr<db::commitlog::segment> >> = {<No data fields>}, <No data fields>}, 
      <std::_Vector_base<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >::_Vector_impl_data> = {
        _M_start = 0x600005067a00,
        _M_finish = 0x600005067a50,
        _M_end_of_storage = 0x600005067a80
      }, <No data fields>}
  }, <No data fields>}
```

@elcallio how can this=0x0 in the call to `db::commitlog::segment::sync`?

**Comment by bhalevy** [comment]
> This can't possibly segfault, it's a load from a static variable.

@avikivity I didn't look at the assembly code but is it possible the segfault occurred on the store part of:
```
    void reset_sync_time() {
        _sync_time = clock_type::now();
    }
```
when this is `nullptr`,
and the backtrace printed by addr2line appears to point to `atomic_base<long>::load` because of inlining?

**Comment by bhalevy** [comment]
Hit again in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/865/artifact/logs-all.release.2/1625524756899_bootstrap_test.TestBootstrap.local_quorum_bootstrap_test/node2.log
```
Segmentation fault on shard 1.
Backtrace:
  0x4060d88
  0x40925f6
  0x7f2c83db91df
  0x2577ec4
  0x25785c5
  0x4072f9b
  0x4091d08
  0x4074f35
  0x4092be5
  0x403e77a
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/27fe3c3aa0478107122c36570894624de75bb0e8/scylla/libreloc/libpthread.so.0+0x93f8
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/27fe3c3aa0478107122c36570894624de75bb0e8/scylla/libreloc/libc.so.6+0x101902
```

```
(gdb) bt
#0  db::commitlog::segment::reset_sync_time (this=0x0) at db/commitlog/commitlog.cc:645
#1  db::commitlog::segment::sync (this=0x0) at db/commitlog/commitlog.cc:671
#2  db::commitlog::segment_manager::sync()::$_32::operator()(seastar::shared_ptr<db::commitlog::segment>) const (this=<optimized out>, s=...) at db/commitlog/commitlog.cc:1950
#3  seastar::futurize<seastar::future<void> >::invoke<db::commitlog::segment_manager::sync()::$_32, seastar::shared_ptr<db::commitlog::segment>&>(db::commitlog::segment_manager::sync()::$_32&&, seastar::shared_ptr<db::commitlog::segment>&) (func=..., args=...) at ./seastar/include/seastar/core/future.hh:2135
#4  seastar::futurize_invoke<db::commitlog::segment_manager::sync()::$_32, seastar::shared_ptr<db::commitlog::segment>&>(db::commitlog::segment_manager::sync()::$_32&&, seastar::shared_ptr<db::commitlog::segment>&) (func=..., args=...) at ./seastar/include/seastar/core/future.hh:2166
#5  seastar::parallel_for_each<__gnu_cxx::__normal_iterator<seastar::shared_ptr<db::commitlog::segment>*, std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > > >, db::commitlog::segment_manager::sync()::$_32>(__gnu_cxx::__normal_iterator<seastar::shared_ptr<db::commitlog::segment>*, std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > > >, __gnu_cxx::__normal_iterator<seastar::shared_ptr<db::commitlog::segment>*, std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > > >, db::commitlog::segment_manager::sync()::$_32&&) (begin=..., end=..., func=...) at ./seastar/include/seastar/core/loop.hh:554
#6  seastar::internal::parallel_for_each_impl<std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32>(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&) (func=..., range=...) at ./seastar/include/seastar/core/loop.hh:598
#7  seastar::futurize<seastar::future<void> >::invoke<seastar::future<void> (*&)(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&), std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32>(seastar::future<void> (*&)(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&), std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&) (args=..., func=<optimized out>, args=...) at ./seastar/include/seastar/core/future.hh:2135
#8  seastar::futurize_invoke<seastar::future<void> (*&)(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&), std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32>(seastar::future<void> (*&)(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&), std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&) (args=..., func=<optimized out>, args=...) at ./seastar/include/seastar/core/future.hh:2166
#9  seastar::parallel_for_each<std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32>(std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >&, db::commitlog::segment_manager::sync()::$_32&&) (func=..., range=...) at ./seastar/include/seastar/core/loop.hh:610
#10 db::commitlog::segment_manager::sync (this=this@entry=0x60100404f800) at db/commitlog/commitlog.cc:1949
#11 0x00000000025785c6 in db::commitlog::segment_manager::on_timer()::$_33::operator()() const (this=<optimized out>) at db/commitlog/commitlog.cc:1962
#12 seastar::futurize<seastar::future<void> >::invoke<db::commitlog::segment_manager::on_timer()::$_33>(db::commitlog::segment_manager::on_timer()::$_33&&) (func=...) at ./seastar/include/seastar/core/future.hh:2135
#13 seastar::futurize_invoke<db::commitlog::segment_manager::on_timer()::$_33>(db::commitlog::segment_manager::on_timer()::$_33&&) (func=...) at ./seastar/include/seastar/core/future.hh:2166
#14 seastar::internal::invoke_func_with_gate<db::commitlog::segment_manager::on_timer()::$_33>(seastar::gate&, db::commitlog::segment_manager::on_timer()::$_33&&) (g=..., func=...) at ./seastar/include/seastar/core/gate.hh:133
#15 seastar::with_gate<db::commitlog::segment_manager::on_timer()::$_33>(seastar::gate&, db::commitlog::segment_manager::on_timer()::$_33&&) (g=..., func=...) at ./seastar/include/seastar/core/gate.hh:151
#16 db::commitlog::segment_manager::on_timer (this=0x60100404f800) at db/commitlog/commitlog.cc:1960
#17 0x0000000004072f9c in seastar::noncopyable_function<void ()>::operator()() const (this=0x60100404fc78) at ./seastar/include/seastar/util/noncopyable_function.hh:209
#18 seastar::reactor::complete_timers<seastar::timer_set<seastar::timer<seastar::lowres_clock>, &seastar::timer<seastar::lowres_clock>::_link>, boost::intrusive::list<seastar::timer<seastar::lowres_clock>, boost::intrusive::member_hook<seastar::timer<seastar::lowres_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::lowres_clock>::_link> >, seastar::reactor::do_expire_lowres_timers()::$_72>(seastar::timer_set<seastar::timer<seastar::lowres_clock>, &seastar::timer<seastar::lowres_clock>::_link>&, boost::intrusive::list<seastar::timer<seastar::lowres_clock>, boost::intrusive::member_hook<seastar::timer<seastar::lowres_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::lowres_clock>::_link> >&, seastar::reactor::do_expire_lowres_timers()::$_72&&) (this=<optimized out>, timers=..., expired_timers=..., enable_fn=...) at ./seastar/src/core/reactor.cc:1242
#19 seastar::reactor::do_expire_lowres_timers (this=0x6010000a6000) at ./seastar/src/core/reactor.cc:2280
#20 0x0000000004091d09 in seastar::reactor::poll_once (this=0x6010000a6000) at ./seastar/src/core/reactor.cc:2894
#21 seastar::reactor::run()::$_79::operator()() const (this=<optimized out>) at ./seastar/src/core/reactor.cc:2792
#22 std::__invoke_impl<bool, seastar::reactor::run()::$_79&>(std::__invoke_other, seastar::reactor::run()::$_79&) (__f=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
#23 std::__invoke_r<bool, seastar::reactor::run()::$_79&>(seastar::reactor::run()::$_79&) (__fn=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:113
#24 std::_Function_handler<bool (), seastar::reactor::run()::$_79>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
#25 0x0000000004074f36 in std::function<bool ()>::operator()() const (this=0x7f2c80bd3aa0) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
#26 seastar::reactor::run (this=0x6010000a6000) at ./seastar/src/core/reactor.cc:2818
#27 0x0000000004092be6 in seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97::operator()() const (this=<optimized out>) at ./seastar/src/core/reactor.cc:3978
#28 std::__invoke_impl<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(std::__invoke_other, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) (__f=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
#29 std::__invoke_r<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) (__fn=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110
#30 std::_Function_handler<void (), seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
#31 0x000000000403e77b in std::function<void ()>::operator()() const (this=0x7f2c80be4300) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
#32 seastar::posix_thread::start_routine (arg=0x7f2c80be4300) at ./seastar/src/core/posix.cc:60
#33 0x00007f2c83dae3f9 in start_thread () from /data/scylla/libreloc/libpthread.so.0
#34 0x00007f2c8315d903 in clone () from /data/scylla/libreloc/libc.so.6
```

```
(gdb) fr 10
#10 db::commitlog::segment_manager::sync (this=this@entry=0x60100404f800) at db/commitlog/commitlog.cc:1949
warning: Source file is more recent than executable.
1949        _background_sync = parallel_for_each(_segments, [](sseg_ptr s) {
(gdb) p _segments
$1 = {
  <std::_Vector_base<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >> = {
    _M_impl = {
      <std::allocator<seastar::shared_ptr<db::commitlog::segment> >> = {
        <__gnu_cxx::new_allocator<seastar::shared_ptr<db::commitlog::segment> >> = {<No data fields>}, <No data fields>}, 
      <std::_Vector_base<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > >::_Vector_impl_data> = {
        _M_start = 0x601000358f00,
        _M_finish = 0x601000358f60,
        _M_end_of_storage = 0x601000358f80
      }, <No data fields>}
  }, <No data fields>}
(gdb) p ((sseg_ptr*)0x601000358f00)[0]
$8 = {
  _b = 0x601000158e00,
  _p = 0x601000158e00
}
(gdb) p ((sseg_ptr*)0x601000358f00)[1]
$9 = {
  _b = 0x601000159000,
  _p = 0x601000159000
}
(gdb) p ((sseg_ptr*)0x601000358f00)[2]
$10 = {
  _b = 0x601000152e00,
  _p = 0x601000152e00
}
(gdb) p ((sseg_ptr*)0x601000358f00)[3]
$11 = {
  _b = 0x601000152800,
  _p = 0x601000152800
}
(gdb) p ((sseg_ptr*)0x601000358f00)[4]
$12 = {
  _b = 0x601000158400,
  _p = 0x601000158400
}
(gdb) p ((sseg_ptr*)0x601000358f00)[5]
$13 = {
  _b = 0x601000153200,
  _p = 0x601000153200
}
(gdb) p ((sseg_ptr*)0x601000358f00)[6]
$14 = {
  _b = 0x0,
  _p = 0x0
}
(gdb) p ((sseg_ptr*)0x601000358f00)[7]
$27 = {
  _b = 0x44f7370 <compact_radix_tree::tree<cell_and_hash, unsigned int>::nil_root>,
  _p = 0x0
}
(gdb) p &((sseg_ptr*)0x601000358f00)[7]
$28 = (db::commitlog::segment_manager::sseg_ptr *) 0x601000358f70
(gdb) fr 5
#5  seastar::parallel_for_each<__gnu_cxx::__normal_iterator<seastar::shared_ptr<db::commitlog::segment>*, std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > > >, db::commitlog::segment_manager::sync()::$_32>(__gnu_cxx::__normal_iterator<seastar::shared_ptr<db::commitlog::segment>*, std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > > >, __gnu_cxx::__normal_iterator<seastar::shared_ptr<db::commitlog::segment>*, std::vector<seastar::shared_ptr<db::commitlog::segment>, std::allocator<seastar::shared_ptr<db::commitlog::segment> > > >, db::commitlog::segment_manager::sync()::$_32&&) (begin=..., end=..., func=...) at ./seastar/include/seastar/core/loop.hh:554
554             auto f = futurize_invoke(std::forward<Func>(func), *begin++);
(gdb) p begin
$29 = {
  _M_current = 0x601000358f70
}
```

So it looks like segments were removed during the `parallel_for_each` loop called from `segment_manager::sync()`.

**Comment by bhalevy** [comment]
Copying `_segments` should keep them around safely, like:
```diff
diff --git a/db/commitlog/commitlog.cc b/db/commitlog/commitlog.cc
index b7339c465..c1705ac0f 100644
--- a/db/commitlog/commitlog.cc
+++ b/db/commitlog/commitlog.cc
@@ -1946,11 +1946,13 @@ future<> db::commitlog::segment_manager::clear() {
  */
 void db::commitlog::segment_manager::sync() {
     auto f = std::exchange(_background_sync, make_ready_future<>());
-    _background_sync = parallel_for_each(_segments, [](sseg_ptr s) {
+    _background_sync = [segments = _segments, f = std::move(f)] () mutable {
+      return parallel_for_each(segments, [](sseg_ptr s) {
         return s->sync().discard_result();
-    }).then([f = std::move(f)]() mutable {
+      }).then([f = std::move(f)]() mutable {
         return std::move(f);
-    });
+      });
+    }();
 }
 
 void db::commitlog::segment_manager::on_timer() {
```

(There should be no need to hold `segments` using `do_with` for `parallel_for_each` since it creates all subordinate futures before it returns)

**Comment by elcallio** [comment]
Again, how can anything be removed from `_segments` before we've read the whole vector? No code called removes anything. At most it can cause a suspension point, but we should not "pre-emptively" task switch out of the `parallel_for_each` loop because of that.  All invocations here should be safely past the initial `reset_sync_time` call and well into `cycle` once we actually return and hand over reins to another execution path.

**Comment by bhalevy** [comment]
Can't a memtable flush happen if we yield from sync()?
It calls `discard_completed_segments`.

**Comment by bhalevy** [comment]
> At most it can cause a suspension point, but we should not "pre-emptively" task switch out of the parallel_for_each loop because of that.

I agree that we're not supposed to preempt `parallel_for_each` while it walks `_segments`.

**Comment by bhalevy** [comment]
@elcallio sync-> cycle -> flush -> do_flush -> end_flush -> 
```
        if (can_delete()) {
            _segment_manager->discard_unused_segments();
        }
```

**Comment by elcallio** [comment]
Ah, crap. We get there by never halting. This call was added to deal with deadlocks in shutdown. Fun side effect.

**Comment by avikivity** [comment]
Is this a recent regression? I assume so. But please confirm that no branch (including 4.5) is vulnerable.

**Comment by bhalevy** [comment]
> Is this a recent regression? I assume so. But please confirm that no branch (including 4.5) is vulnerable.

@avikivity 4.5 is now vulnerable, with f89f4e69a0d209b0646e9804db281166fc679081

**Comment by avikivity** [comment]
Backported to 4.5.
