### ISSUE TITLE
batchlog manager is not stopped if scylla shuts down during startup

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9009]
This issue stems off of #8995.

In addition to storage_proxy::drain_on_shutdown not synchronizing with on-going queries, the reason there is an on-going query after the storage_proxy is drained appears to be that the batchlog manager is not stopped if scylla gets a shutdown signal during startup (e.g. when waiting for gossip to settle).

I'm opening a separate issue for that since I think we should fix the storage_proxy draining synchronization as well, but this issue is orthogonal and fixing it will also fix the failures we see in several dtests, like the following one:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/864/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/simple_add_new_node_while_adding_info_1_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1148, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1202, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node4', ['ERROR 2021-07-05 02:43:39,078 [shard 0] storage_proxy - Exception when communicating with 127.0.53.4, to read from system.batchlog: seastar::gate_closed_exception (gate closed)', 'ERROR 2021-07-05 02:43:39,079 [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_failure_exception (Operation failed for system.batchlog - received 0 responses and 1 failures from 1 CL=ONE.)'])]
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/864/artifact/logs-all.release.2/1625453021390_update_cluster_layout_tests.TestUpdateClusterLayout.simple_add_new_node_while_adding_info_1_test/node4.log
```
INFO  2021-07-05 02:43:33,373 [shard 0] init - Shutting down drain storage proxy
INFO  2021-07-05 02:43:33,373 [shard 0] hints_manager - Asked to stop
INFO  2021-07-05 02:43:33,373 [shard 0] hints_manager - Stopped
INFO  2021-07-05 02:43:33,374 [shard 1] hints_manager - Asked to stop
INFO  2021-07-05 02:43:33,374 [shard 1] hints_manager - Stopped
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down drain storage proxy was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down streaming service
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down streaming service was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down Raft RPC
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down Raft RPC was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down storage proxy RPC verbs
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down storage proxy RPC verbs was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down sstables format selector
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down sstables format selector was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down migration manager
INFO  2021-07-05 02:43:33,374 [shard 0] migration_manager - stopping migration service
INFO  2021-07-05 02:43:33,374 [shard 1] migration_manager - stopping migration service
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down migration manager was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down database
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down database was successful
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down service_memory_limiter
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down service_memory_limiter was successful
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down sst_dir_semaphore
ERROR 2021-07-05 02:43:39,078 [shard 0] storage_proxy - Exception when communicating with 127.0.53.4, to read from system.batchlog: seastar::gate_closed_exception (gate closed)
ERROR 2021-07-05 02:43:39,079 [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_failure_exception (Operation failed for system.batchlog - received 0 responses and 1 failures from 1 CL=ONE.)
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down sst_dir_semaphore was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down Raft
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down Raft was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down messaging service
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down messaging service was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down API server
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down API server was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down tracing instance
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down tracing instance was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down migration manager notifier
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down prometheus API server
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down prometheus API server was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down sighup
INFO  2021-07-05 02:43:39,080 [shard 0] init - Shutting down sighup was successful
ERROR 2021-07-05 02:43:39,080 [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
