### ISSUE TITLE
scylla_cache_reads metrics are not found

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9012]
A bunch of bypass_cache_test dtests started failing in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/868/testReport/

For example, https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/868/testReport/bypass_cache_test/TestBypassCache/test_alter_table_caching_disable/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/bypass_cache_test.py", line 165, in test_alter_table_caching_disable
    self.verify_read_was_from_cache(node=node, query=query, session=session)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/bypass_cache_test.py", line 57, in verify_read_was_from_cache
    assert_false(self.is_read_from_disk(node, query, session, metric=metric),
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/bypass_cache_test.py", line 45, in is_read_from_disk
    cache_read_before_bypass_read = self.get_scylla_cache_reads_metrics(node=node, metrics=metric)[metric[0]]
KeyError: 'scylla_cache_reads'
```

It looks like this could have been caused by 6a6403d19d60204635e40f1247b091317ef9e7e6
where earlier the metric were always set up using `dummy_app_stats` and with this change `setup_metrics()` isn't called anymore.

@tgrabiec please look into this.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
