### ISSUE TITLE
Regression in test_oversize_indexed_values dtest

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9013]
Starting https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/868/testReport/junit/secondary_indexes_test/TestSecondaryIndexes/test_oversize_indexed_values/
Scylla version fe4002c6c42d9eb1b83b72953e4b929d7dc09fd7
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 721, in test_oversize_indexed_values
    self._validate_long_indexed_values(OVERSIZE_LENGTH, expect_message)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 739, in _validate_long_indexed_values
    expect_message=expect_message)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 105, in insert_row_with_long_value
    expect_message)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 114, in assert_request
    session, value_length, expect_message)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 143, in execute_and_assert
    raise e
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 141, in execute_and_assert
    assert assert_success, assert_fail
AssertionError: Expecting query INSERT INTO table_1625882981354 (a, b, c) VALUES (0, 0, ?) to be invalid
```

**Comment by bhalevy** [comment]
@psarna git bisect points at bf0777e97a0abb3bebddf84c82de774ebfd9255d for this regression.

**Comment by psarna** [comment]
Right, this series introduced a regression - if a too large value is inserted to an indexed column, view update generation fails, but it's incorrectly ignored in `generate_and_propagate_view_updates()`. Originally, errors in **propagation** were ignored, but errors during **generation** should be forwarded to the user. That unfortunately changed when this routine was rewritten to coroutines.

**Comment by nyh** [comment]
@bhalevy imagine that this test lived in cql-pytest, and took 10 milliseconds, instead of dtest and taking 5 minutes. Developers would actually run it before submitting patches... :-(

**Comment by bhalevy** [comment]
> @bhalevy imagine that this test lived in cql-pytest, and took 10 milliseconds, instead of dtest and taking 5 minutes. Developers would actually run it before submitting patches... :-(

Sounds good :)

**Comment by psarna** [comment]
Actually, please hold with the review. I'm afk now and I'm not sure if WriteFailure is the right error type to expect. I'll need to double-check tomorrow what was the original error type.

**Comment by psarna** [comment]
> Actually, please hold with the review. I'm afk now and I'm not sure if WriteFailure is the right error type to expect. I'll need to double-check tomorrow what was the original error type.

Ok, false alarm, the error is exactly the same as before, the series (https://github.com/scylladb/scylla/pull/9021) is good for review.

**Comment by psarna** [comment]
> @bhalevy imagine that this test lived in cql-pytest, and took 10 milliseconds, instead of dtest and taking 5 minutes. Developers would actually run it before submitting patches... :-(

Already ported in #9021, coding the test case and running it took less than a single dtest run :)

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
