### ISSUE TITLE
wide_rows_test: View wide_row.user_events_view not built

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9047]
Regression seen since:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/872/testReport/wide_rows_test/TestWideRows_with_LeveledCompactionStrategy/test_large_cell_in_materialized_view/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/872/testReport/wide_rows_test/TestWideRows_with_SizeTieredCompactionStrategy/test_large_cell_in_materialized_view/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/872/testReport/wide_rows_test/TestWideRows_with_TimeWindowCompactionStrategy/test_large_cell_in_materialized_view/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/wide_rows_test.py", line 1205, in test_large_cell_in_materialized_view
    wait_for_view(cluster=self.cluster, session=session, ks=self.KEYSPACE_NAME, view=view_name)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 1025, in wait_for_view
    raise Exception(error_msg)
Exception: View wide_row.user_events_view not built
```

Scylla version c8e7bd9a26a23a5ce0edae9be67eb1a4bb86b48f

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/872/artifact/logs-all.release.2/1626233747736_wide_rows_test.TestWideRows_with_LeveledCompactionStrategy.test_large_cell_in_materialized_view/node1.log
```
WARN  2021-07-14 03:29:14,878 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value0 (1048583 bytes)
INFO  2021-07-14 03:29:14,878 [shard 0] schema_tables - Schema version changed to 400acd35-c16f-304c-bb5b-f816b66f2e00
WARN  2021-07-14 03:29:14,879 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value1 (1048583 bytes)
WARN  2021-07-14 03:29:14,879 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value2 (1048583 bytes)
WARN  2021-07-14 03:29:14,879 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value3 (1048583 bytes)
WARN  2021-07-14 03:29:14,880 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value4 (1048583 bytes)
WARN  2021-07-14 03:29:14,880 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value5 (1048583 bytes)
WARN  2021-07-14 03:29:14,880 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value6 (1048583 bytes)
WARN  2021-07-14 03:29:14,881 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value7 (1048583 bytes)
WARN  2021-07-14 03:29:14,881 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value8 (1048583 bytes)
WARN  2021-07-14 03:29:14,881 [shard 1] large_data - Writing large cell wide_row/user_events: user22021-07-16 value9 (1048583 bytes)
WARN  2021-07-14 03:29:14,882 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value0 (1048584 bytes)
WARN  2021-07-14 03:29:14,883 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value1 (1048584 bytes)
WARN  2021-07-14 03:29:14,883 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value2 (1048584 bytes)
WARN  2021-07-14 03:29:14,884 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value3 (1048584 bytes)
WARN  2021-07-14 03:29:14,884 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value4 (1048584 bytes)
WARN  2021-07-14 03:29:14,884 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value5 (1048584 bytes)
WARN  2021-07-14 03:29:14,884 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value6 (1048584 bytes)
WARN  2021-07-14 03:29:14,885 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value7 (1048584 bytes)
WARN  2021-07-14 03:29:14,885 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value8 (1048584 bytes)
WARN  2021-07-14 03:29:14,885 [shard 0] large_data - Writing large cell wide_row/user_events: user82021-07-22 value9 (1048584 bytes)
WARN  2021-07-14 03:29:14,893 [shard 0] large_data - Writing large row wide_row/user_events: user82021-07-22 (10485858 bytes)
WARN  2021-07-14 03:29:14,902 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value0 (1048584 bytes)
WARN  2021-07-14 03:29:14,902 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value1 (1048584 bytes)
WARN  2021-07-14 03:29:14,903 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value2 (1048584 bytes)
WARN  2021-07-14 03:29:14,903 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value3 (1048584 bytes)
WARN  2021-07-14 03:29:14,903 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value4 (1048584 bytes)
WARN  2021-07-14 03:29:14,903 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value5 (1048584 bytes)
WARN  2021-07-14 03:29:14,903 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value6 (1048584 bytes)
WARN  2021-07-14 03:29:14,903 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value7 (1048584 bytes)
WARN  2021-07-14 03:29:14,904 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value8 (1048584 bytes)
WARN  2021-07-14 03:29:14,904 [shard 0] large_data - Writing large cell wide_row/user_events: user92021-07-23 value9 (1048584 bytes)
WARN  2021-07-14 03:29:14,909 [shard 1] large_data - Writing large row wide_row/user_events: user22021-07-16 (10485848 bytes)
INFO  2021-07-14 03:29:14,914 [shard 0] compaction - [Compact system_schema.indexes a9e381d0-e453-11eb-9b2e-efb17791d519] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/md-44-big-Data.db:level=0]. 11kB to 5kB (~51% of original) in 29ms = 198kB/s. ~256 total partitions merged to 2.
WARN  2021-07-14 03:29:14,916 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value0 (1048583 bytes)
WARN  2021-07-14 03:29:14,916 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value1 (1048583 bytes)
WARN  2021-07-14 03:29:14,917 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value2 (1048583 bytes)
WARN  2021-07-14 03:29:14,917 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value3 (1048583 bytes)
WARN  2021-07-14 03:29:14,917 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value4 (1048583 bytes)
WARN  2021-07-14 03:29:14,917 [shard 0] large_data - Writing large row wide_row/user_events: user92021-07-23 (10485858 bytes)
WARN  2021-07-14 03:29:14,918 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value5 (1048583 bytes)
WARN  2021-07-14 03:29:14,918 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value6 (1048583 bytes)
WARN  2021-07-14 03:29:14,918 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value7 (1048583 bytes)
WARN  2021-07-14 03:29:14,919 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value8 (1048583 bytes)
WARN  2021-07-14 03:29:14,919 [shard 1] large_data - Writing large cell wide_row/user_events: user42021-07-18 value9 (1048583 bytes)
INFO  2021-07-14 03:29:14,924 [shard 0] compaction - [Compact system_schema.columns a9ed1ec0-e453-11eb-9b2e-efb17791d519] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/md-44-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/md-42-big-Data.db:level=0:origin=compaction]
WARN  2021-07-14 03:29:14,928 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value0 (1048581 bytes)
WARN  2021-07-14 03:29:14,928 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value1 (1048582 bytes)
WARN  2021-07-14 03:29:14,929 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value2 (1048583 bytes)
WARN  2021-07-14 03:29:14,929 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value3 (1048583 bytes)
WARN  2021-07-14 03:29:14,929 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value4 (1048583 bytes)
WARN  2021-07-14 03:29:14,929 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value5 (1048583 bytes)
WARN  2021-07-14 03:29:14,930 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value6 (1048583 bytes)
WARN  2021-07-14 03:29:14,930 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value7 (1048583 bytes)
WARN  2021-07-14 03:29:14,930 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value8 (1048583 bytes)
WARN  2021-07-14 03:29:14,930 [shard 0] large_data - Writing large cell wide_row/user_events: user12021-07-15 value9 (1048583 bytes)
WARN  2021-07-14 03:29:14,937 [shard 0] large_data - Writing large row wide_row/user_events: user12021-07-15 (10485845 bytes)
WARN  2021-07-14 03:29:14,938 [shard 1] large_data - Writing large row wide_row/user_events: user42021-07-18 (10485848 bytes)
WARN  2021-07-14 03:29:14,944 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value0 (1048584 bytes)
WARN  2021-07-14 03:29:14,944 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value1 (1048584 bytes)
WARN  2021-07-14 03:29:14,944 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value2 (1048584 bytes)
WARN  2021-07-14 03:29:14,944 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value3 (1048584 bytes)
WARN  2021-07-14 03:29:14,945 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value4 (1048584 bytes)
WARN  2021-07-14 03:29:14,945 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value5 (1048584 bytes)
WARN  2021-07-14 03:29:14,945 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value6 (1048584 bytes)
WARN  2021-07-14 03:29:14,945 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value7 (1048584 bytes)
WARN  2021-07-14 03:29:14,946 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value8 (1048584 bytes)
WARN  2021-07-14 03:29:14,946 [shard 0] large_data - Writing large cell wide_row/user_events: user72021-07-21 value9 (1048584 bytes)
WARN  2021-07-14 03:29:14,946 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value0 (1048581 bytes)
WARN  2021-07-14 03:29:14,946 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value1 (1048583 bytes)
WARN  2021-07-14 03:29:14,946 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value2 (1048583 bytes)
WARN  2021-07-14 03:29:14,947 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value3 (1048583 bytes)
WARN  2021-07-14 03:29:14,947 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value4 (1048583 bytes)
WARN  2021-07-14 03:29:14,947 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value5 (1048583 bytes)
WARN  2021-07-14 03:29:14,947 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value6 (1048583 bytes)
WARN  2021-07-14 03:29:14,947 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value7 (1048583 bytes)
WARN  2021-07-14 03:29:14,948 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value8 (1048583 bytes)
WARN  2021-07-14 03:29:14,948 [shard 1] large_data - Writing large cell wide_row/user_events: user02021-07-14 value9 (1048583 bytes)
WARN  2021-07-14 03:29:14,955 [shard 0] large_data - Writing large row wide_row/user_events: user72021-07-21 (10485858 bytes)
WARN  2021-07-14 03:29:14,963 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value0 (1048583 bytes)
WARN  2021-07-14 03:29:14,963 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value1 (1048583 bytes)
WARN  2021-07-14 03:29:14,964 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value2 (1048583 bytes)
WARN  2021-07-14 03:29:14,964 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value3 (1048583 bytes)
WARN  2021-07-14 03:29:14,964 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value4 (1048583 bytes)
WARN  2021-07-14 03:29:14,964 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value5 (1048583 bytes)
WARN  2021-07-14 03:29:14,965 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value6 (1048583 bytes)
WARN  2021-07-14 03:29:14,965 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value7 (1048583 bytes)
WARN  2021-07-14 03:29:14,965 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value8 (1048583 bytes)
WARN  2021-07-14 03:29:14,965 [shard 0] large_data - Writing large cell wide_row/user_events: user32021-07-17 value9 (1048583 bytes)
WARN  2021-07-14 03:29:14,970 [shard 1] large_data - Writing large row wide_row/user_events: user02021-07-14 (10485846 bytes)
WARN  2021-07-14 03:29:14,972 [shard 0] large_data - Writing large row wide_row/user_events: user32021-07-17 (10485848 bytes)
WARN  2021-07-14 03:29:14,980 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value0 (1048583 bytes)
WARN  2021-07-14 03:29:14,980 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value1 (1048584 bytes)
WARN  2021-07-14 03:29:14,980 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value2 (1048584 bytes)
WARN  2021-07-14 03:29:14,980 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value3 (1048584 bytes)
WARN  2021-07-14 03:29:14,981 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value4 (1048584 bytes)
WARN  2021-07-14 03:29:14,981 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value5 (1048584 bytes)
WARN  2021-07-14 03:29:14,981 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value6 (1048584 bytes)
WARN  2021-07-14 03:29:14,981 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value7 (1048584 bytes)
WARN  2021-07-14 03:29:14,982 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value8 (1048584 bytes)
WARN  2021-07-14 03:29:14,982 [shard 1] large_data - Writing large cell wide_row/user_events: user62021-07-20 value9 (1048584 bytes)
INFO  2021-07-14 03:29:14,991 [shard 0] view - Building view wide_row.user_events_view, starting at token minimum token
WARN  2021-07-14 03:29:15,002 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:15,012 [shard 1] large_data - Writing large row wide_row/user_events: user62021-07-20 (10485857 bytes)
INFO  2021-07-14 03:29:15,015 [shard 0] compaction - [Compact system_schema.columns a9ed1ec0-e453-11eb-9b2e-efb17791d519] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/md-46-big-Data.db:level=0]. 24kB to 18kB (~76% of original) in 85ms = 216kB/s. ~256 total partitions merged to 7.
INFO  2021-07-14 03:29:15,019 [shard 0] compaction - [Compact system_schema.scylla_tables a9fb9db0-e453-11eb-9b2e-efb17791d519] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/md-46-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/md-44-big-Data.db:level=0:origin=compaction]
WARN  2021-07-14 03:29:15,019 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value0 (1048583 bytes)
WARN  2021-07-14 03:29:15,019 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value1 (1048583 bytes)
WARN  2021-07-14 03:29:15,020 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value2 (1048583 bytes)
WARN  2021-07-14 03:29:15,020 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value3 (1048583 bytes)
WARN  2021-07-14 03:29:15,020 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value4 (1048583 bytes)
WARN  2021-07-14 03:29:15,020 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value5 (1048583 bytes)
WARN  2021-07-14 03:29:15,021 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value6 (1048583 bytes)
WARN  2021-07-14 03:29:15,021 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value7 (1048583 bytes)
WARN  2021-07-14 03:29:15,021 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value8 (1048583 bytes)
WARN  2021-07-14 03:29:15,021 [shard 1] large_data - Writing large cell wide_row/user_events: user52021-07-19 value9 (1048583 bytes)
WARN  2021-07-14 03:29:15,050 [shard 1] large_data - Writing large row wide_row/user_events: user52021-07-19 (10485848 bytes)
INFO  2021-07-14 03:29:15,065 [shard 0] compaction - [Compact system_schema.scylla_tables a9fb9db0-e453-11eb-9b2e-efb17791d519] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/md-48-big-Data.db:level=0]. 13kB to 7kB (~58% of original) in 41ms = 191kB/s. ~256 total partitions merged to 7.
INFO  2021-07-14 03:29:15,071 [shard 0] compaction - [Compact system_schema.dropped_columns aa038cf0-e453-11eb-9b2e-efb17791d519] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/md-46-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/md-44-big-Data.db:level=0:origin=compaction]
INFO  2021-07-14 03:29:15,089 [shard 0] compaction - [Compact system_schema.dropped_columns aa038cf0-e453-11eb-9b2e-efb17791d519] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/md-48-big-Data.db:level=0]. 11kB to 5kB (~52% of original) in 15ms = 383kB/s. ~256 total partitions merged to 2.
WARN  2021-07-14 03:29:15,095 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
INFO  2021-07-14 03:29:15,095 [shard 0] compaction - [Compact system_schema.keyspaces aa073670-e453-11eb-9b2e-efb17791d519] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-62-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-60-big-Data.db:level=0:origin=compaction]
INFO  2021-07-14 03:29:15,117 [shard 0] compaction - [Compact system_schema.keyspaces aa073670-e453-11eb-9b2e-efb17791d519] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-64-big-Data.db:level=0]. 11kB to 6kB (~52% of original) in 18ms = 338kB/s. ~256 total partitions merged to 7.
INFO  2021-07-14 03:29:15,118 [shard 0] compaction - [Compact system_schema.tables aa0ab8e0-e453-11eb-9b2e-efb17791d519] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/md-42-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/md-40-big-Data.db:level=0:origin=compaction]
INFO  2021-07-14 03:29:15,130 [shard 0] compaction - [Compact system_schema.tables aa0ab8e0-e453-11eb-9b2e-efb17791d519] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/md-44-big-Data.db:level=0]. 20kB to 13kB (~66% of original) in 9ms = 1MB/s. ~256 total partitions merged to 7.
INFO  2021-07-14 03:29:15,130 [shard 0] compaction - [Compact system_schema.computed_columns aa0c8da0-e453-11eb-9b2e-efb17791d519] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/md-42-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/md-40-big-Data.db:level=0:origin=compaction]
INFO  2021-07-14 03:29:15,141 [shard 0] compaction - [Compact system_schema.computed_columns aa0c8da0-e453-11eb-9b2e-efb17791d519] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-agfhk769/test/node1/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/md-44-big-Data.db:level=0]. 10kB to 5kB (~51% of original) in 8ms = 697kB/s. ~256 total partitions merged to 2.
WARN  2021-07-14 03:29:16,013 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:16,105 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:18,023 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:18,116 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:22,035 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:22,127 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:30,046 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:30,138 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:46,055 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:29:46,151 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:30:18,065 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:30:18,161 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:31:18,085 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:31:18,170 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:32:18,095 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:32:18,180 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:33:18,103 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:33:18,190 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:34:18,113 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:34:18,201 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:35:18,121 [shard 0] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
WARN  2021-07-14 03:35:18,211 [shard 1] view - Error executing build step for base wide_row.user_events: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 10485760 (configured via max_memory_for_unlimited_query_hard_limit))
```

@psarna is it a duplicate of https://github.com/scylladb/scylla/issues/9013?
The tested version does not include 8bdff97d8da126666a4237886dc995594a51a9a0

**Comment by psarna** [comment]
Ouch, no, it's yet another subtle regression. By mistake I left a hardcoded 10MB limit in the view path... it should either be taken from `max_memory_for_unlimited_query_hard_limit` or just set to an infinitely high value (the second one is simpler and better, since it's a view update so it already comes from a validated column value.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
