### ISSUE TITLE
cassandra-harry fail: harry.model.Model$ValidationException

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#9050]
*Installation details*
Scylla version (or git commit hash):  4.5.rc5-0.20210711.7f96719c5
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

cassandra-harry failed with scylla-4.5.rc5

Caused by: harry.model.Model$ValidationException: While validating 6489722821256964062, expected row not to be visible: a deletion, followed by no overwrites or all incomplete writes, but found [Operation{pd=-451118590066856979, cd=6489722821256964062, lts=13, opId=93, op=WRITE}, Operation{pd=-451118590066856979, cd=6489722821256964062, lts=3, opId=3, op=WRITE}].
Range tombstones: [Range{minBound=-9223372036854775808, maxBound=3434404112152657919, minInclusive=true, maxInclusive=true, timestamp=13}(lts=13, opId=36)]

##### Building
```
            git clone -b scylla-branch https://github.com/amoskong/cassandra-harry
            cd cassandra-harry
            make mvn
```

##### Run the test
```
./scripts/cassandra-harry -run-time 1 -run-time-unit MINUTES
```

### Error Detail

- FULL log: 
[scylla-4.5rc5-cassandra-harry-fail.txt](https://github.com/scylladb/scylla/files/6829888/scylla-4.5rc5-cassandra-harry-fail.txt)

```
ERROR [main] instance_id_IS_UNDEFINED 2021-07-16 09:52:29,830 HarryRunner.java:69 - Execution failed
harry.model.Model$ValidationException: Caught exception while validating the resultset harry.runner.Query$SingleClusteringQuery@4c0b54b7.
checker.tracker().forceLts(19L, 16L)
run.validator.validatePartition(3L)
Row Iter Peek: null
Validated no rows:
[]
Validated rows:

Rows:

        at harry.model.ExhaustiveChecker.validatePartitionState(ExhaustiveChecker.java:232)
        at harry.model.ExhaustiveChecker.validatePartitionState(ExhaustiveChecker.java:98)
        at harry.runner.Validator.validateRecentPartitions(Validator.java:76)
        at harry.runner.Runner$ConcurrentRunner.lambda$initAndStartAll$4(Runner.java:274)
        at harry.runner.Runner.lambda$reportThrowable$0(Runner.java:128)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: harry.model.Model$ValidationException: While validating 6489722821256964062, expected row not to be visible: a deletion, followed by no overwrites or all incomplete writes, but found [Operation{pd=-451118590066856979, cd=6489722821256964062, lts=13, opId=93, op=WRITE}, Operation{pd=-451118590066856979, cd=6489722821256964062, lts=3, opId=3, op=WRITE}].
Range tombstones: [Range{minBound=-9223372036854775808, maxBound=3434404112152657919, minInclusive=true, maxInclusive=true, timestamp=13}(lts=13, opId=36)]
        at harry.model.ExhaustiveChecker.validateNoRow(ExhaustiveChecker.java:307)
        at harry.model.ExhaustiveChecker.validatePartitionState(ExhaustiveChecker.java:216)
        ... 11 common frames omitted
INFO  [main] instance_id_IS_UNDEFINED 2021-07-16 09:52:29,830 HarryRunner.java:80 - Shutting down executor..
INFO  [main] instance_id_IS_UNDEFINED 2021-07-16 09:52:29,834 HarryRunner.java:86 - Shutting down runner..
INFO  [main] instance_id_IS_UNDEFINED 2021-07-16 09:52:29,845 Runner.java:314 - Shutting down...
INFO  [main] instance_id_IS_UNDEFINED 2021-07-16 09:52:29,975 Runner.java:95 - Tearing down setup...
INFO  [main] instance_id_IS_UNDEFINED 2021-07-16 09:52:29,976 HarryRunner.java:94 - Exiting...
```

**Comment by amoskong** [comment]
[scylla-4.4.3-fail-with-latest-cassandra-harry.txt](https://github.com/scylladb/scylla/files/6829934/scylla-4.4.3-fail-with-latest-cassandra-harry.txt)

Scylla 4.4.3 failed for another error

Caused by: harry.model.Model$ValidationException: Error caught while validating column 1. Expected value: 2147483648. Modification should have been visible but was not.
Operation: Operation{pd=-3529805905209414768, cd=8779104218115833902, lts=11, opId=71, op=WRITE}
Row: resultSetRow(-3529805905209414768L, 8779104218115833902L, values(-1L,2147483648L,-1L,-9223372036854775808L,-1L,-1L,-1L,-9223372036854775808L,-1L), lts(-9223372036854775808L,1L,-9223372036854775808L,1L,-9223372036854775808L,-9223372036854775808L,-9223372036854775808L,1L,-9223372036854775808L))
Row ID: 81
Column States: [UNOBSERVED, UNOBSERVED, UNOBSERVED, UNOBSERVED, UNOBSERVED, UNOBSERVED, UNOBSERVED, UNOBSERVED, UNOBSERVED] 
Range tombstones: Ranges{sortedByMin=[]}

**Comment by slivne** [comment]
Is cassandra-harry (https://github.com/apache/cassandra-harry) a new tool
we added - did it pass on old revisions - if not we will to check this out
- but its not a regression.

**Comment by amoskong** [comment]
The original unstable scylla works, version: 4.5.dev-0.20210118.faf71c6f7

I will try to test with 4.4.0

**Comment by fruch** [comment]
this isn't relevant anymore, harry is running o.k. on recent releases
