### ISSUE TITLE
gdb test: scylla fiber $task: Provided pointer 0x0000600003b9cf10 is not an object managed by seastar or not a task pointer

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9214]
Failure seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3871/artifact/output_test_release.txt
Scylla version 9c7bcd1d85a9ba5127d26a46d0e546e4b746fad4

```
*** CMD: scylla fiber $task

Provided pointer 0x0000600003b9cf10 is not an object managed by seastar or not a task pointer
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/next/scylla/scylla-gdb.py", line 3254, in invoke
    tptr, vptr, name = this_task
TypeError: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/next/scylla/test/scylla-gdb/test.py", line 67, in <module>
    dos('fiber $task')
  File "/jenkins/workspace/scylla-master/next/scylla/test/scylla-gdb/test.py", line 19, in dos
    return do('scylla ' + cmd, known_broken, loudly=True)
  File "/jenkins/workspace/scylla-master/next/scylla/test/scylla-gdb/test.py", line 9, in do
    ret = gdb.execute(cmd)
gdb.error: Error occurred in Python: cannot unpack non-iterable NoneType object
```

**Comment by bhalevy** [comment]
@denesb mind looking into this while @cmm is on vacation?

**Comment by bhalevy** [comment]
Duplicate of #9860
