### ISSUE TITLE
nodetool repair failed for table with TWCS on new added node with replace with a lot of errors and warnings with semaphore timeout

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#9237]
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.5.rc6-0.20210817.88314fedf`
Cluster size: 3 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-twcs-48h-4-5-db-node-899f0e32-1 (34.237.223.2 | 10.0.2.29): 8 shards
   longevity-twcs-48h-4-5-db-node-899f0e32-2 (3.94.150.125 | 10.0.1.15): 8 shards
   longevity-twcs-48h-4-5-db-node-899f0e32-4 (34.201.27.67 | 10.0.2.227): 8 shards
Scylla running with shards number (terminated nodes):
   longevity-twcs-48h-4-5-db-node-899f0e32-3 (3.234.220.106 | 10.0.1.233): 8 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0739a655c1d250571` (aws: us-east-1)

Test: `longevity-twcs-48h-test`
Test name: `longevity_twcs_test.TWCSLongevityTest.test_custom_time`
Test config file(s):
- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/baa234208dc154fdc3ecb9055dd7a33f44238bc0/test-cases/longevity/longevity-twcs-48h.yaml)

**Issue description**
Next scylla-bench commands was used to run time-series payload:
- scylla-bench -workload=timeseries -mode=write -replication-factor=3 -partition-count=20000 -clustering-row-count=9999999000000 -clustering-row-size=200 -concurrency=30 -max-rate=60000 -rows-per-request=5000 -duration=2880m
- scylla-bench -workload=timeseries -mode=read -partition-count=20000 -concurrency=48 -replication-factor=3 -write-rate=3 -clustering-row-count=9999999000000 -clustering-row-size=200  -rows-per-request=300 -provide-upper-bound -start-timestamp=SCT_TIME -duration=2880m

this commands generate next schema:
```
CREATE KEYSPACE scylla_bench WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE scylla_bench.test (
    pk bigint,
    ck bigint,
    v blob,
    PRIMARY KEY (pk, ck)
) WITH CLUSTERING ORDER BY (ck ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'MINUTES'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 900
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE scylla_bench.test_counters (
    pk bigint,
    ck bigint,
    c1 counter,
    c2 counter,
    c3 counter,
    c4 counter,
    c5 counter,
    PRIMARY KEY (pk, ck)
) WITH CLUSTERING ORDER BY (ck ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

```

at time 13:18:35.279 test terminated node3 and add new node 4 with replace node3. After scylla was up on node4, nodetool repair manually started. During that repair a lot of next warnings and errors are logged on node4:
```
2021-08-22T16:12:57+00:00  longevity-twcs-48h-4-5-db-node-899f0e32-4 !WARNING | scylla:  [shard 2] storage_proxy - Failed to apply mutation from 10.0.2.29#2: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->2 semaphore)
2021-08-22T16:12:57+00:00  longevity-twcs-48h-4-5-db-node-899f0e32-4 !ERR     | scylla:  [shard 5] storage_proxy - exception during mutation write to 10.0.2.227: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
2021-08-22T16:12:57+00:00  longevity-twcs-48h-4-5-db-node-899f0e32-4 !WARNING | scylla:  [shard 5] storage_proxy - Failed to apply mutation from 10.0.2.29#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
2021-08-22T16:12:57+00:00  longevity-twcs-48h-4-5-db-node-899f0e32-4 !ERR     | scylla:  [shard 5] storage_proxy - exception during mutation write to 10.0.2.227: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
2021-08-22T16:12:57+00:00  longevity-twcs-48h-4-5-db-node-899f0e32-4 !WARNING | scylla:  [shard 0] storage_proxy - Failed to apply mutation from 10.0.1.15#0: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->0 semaphore)
2021-08-22T16:12:57+00:00  longevity-twcs-48h-4-5-db-node-899f0e32-4 !WARNING | scylla:  [shard 1] storage_proxy - Failed to apply mutation from 10.0.1.15#1: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->1 semaphore)
```
command  `nodetool repair` failed with next error:
```
Command: '/usr/bin/nodetool  repair '

Exit code: 2

Stdout:

[2021-08-22 16:32:30,996] Repair session 1 failed
[2021-08-22 16:32:30,998] Repair session 1 finished

Stderr:

error: Repair job has failed with the error message: [2021-08-22 16:32:30,996] Repair session 1 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2021-08-22 16:32:30,996] Repair session 1 failed
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)

```

at some time, node 4 has status DN and this state terminate the test.
```
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
DN  10.0.2.227  1.78 GB    256          ?       0af3779a-0d04-4329-8e93-7d0c1a6be444  1a
UN  10.0.2.29   1.47 GB    256          ?       8c04463e-1738-4d66-ab7d-ee79334f114f  1a
UN  10.0.1.15   1.7 GB     256          ?       b65339b2-83b5-43e3-9750-ed1584006414  1a
```

cluster is available:
```
| longevity-twcs-48h-4-5-db-node-899f0e32-1      | us-east-1a | 34.237.223.2  |
| longevity-twcs-48h-4-5-db-node-899f0e32-2      | us-east-1a | 3.94.150.125  |
| longevity-twcs-48h-4-5-monitor-node-899f0e32-1 | us-east-1a | 3.234.139.229 |
| longevity-twcs-48h-4-5-db-node-899f0e32-4      | us-east-1a | 34.201.27.67  |
```
db logs: 
https://cloudius-jenkins-test.s3.amazonaws.com/899f0e32-96f2-4eb2-9542-9dc745e228ad/20210822_170301/db-cluster-899f0e32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/899f0e32-96f2-4eb2-9542-9dc745e228ad/20210822_170301/db-cluster-899f0e32.tar.gz)

Monitoring:
http://3.234.139.229:3000

**Comment by aleksbykov** [comment]
The issue could be simialr to https://github.com/scylladb/scylla/issues/9199

**Comment by slivne** [comment]
a new test on 4.4 this test did not pass

**Comment by slivne** [comment]
this is not a regression pushing out

**Comment by denesb** [comment]
Closing as stale.
