### ISSUE TITLE
error: too many positional options have been specified on the command line when trying alternator

### ISSUE THREAD

**Issue by dimaqq** [scylladb/scylla#9240]
I've tried running Scylla with Alternator the way the docs tell me to: `docker run -it --name scylla -d -p 8000:8000 scylladb/scylla-nightly:latest --alternator-port=8000 --alternator-write-isolation=always` and the container keeps hitting this error:

```
2021-08-24 04:58:26,974 INFO spawned: 'scylla-server' with pid 78
2021-08-24 04:58:28,022 INFO success: scylla-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Scylla version 4.6.dev-0.20210822.f98cb9650 with build-id 6a65da570b62b9708745e9eb39019a3a46d0a1b1 starting ...
command used: "/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 2001:db8:1::242:ac11:2 172.17.0.2 --rpc-address 2001:db8:1::242:ac11:2 172.17.0.2 --seed-provider-parameters seeds=2001:db8:1::242:ac11:2 172.17.0.2 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 1, log-to-stdout: 0, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 2001:db8:1::242:ac11:2, (positional) 172.17.0.2, rpc-address: 2001:db8:1::242:ac11:2, (positional) 172.17.0.2, seed-provider-parameters: seeds=2001:db8:1::242:ac11:2, (positional) 172.17.0.2, blocked-reactor-notify-ms: 999999999]
error: too many positional options have been specified on the command line

Try --help.
```

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (docker hash): `scylladb/scylla-nightly:latest       a7e0767c63ab`
Cluster size: 1

Full container log:

```
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
2021-08-24 04:58:14,760 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-08-24 04:58:14,764 INFO Included extra file "/etc/supervisord.conf.d/rsyslog.conf" during parsing
2021-08-24 04:58:14,769 INFO Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
2021-08-24 04:58:14,769 INFO Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
2021-08-24 04:58:14,770 INFO Included extra file "/etc/supervisord.conf.d/scylla-node-exporter.conf" during parsing
2021-08-24 04:58:14,770 INFO Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
2021-08-24 04:58:14,773 INFO Included extra file "/etc/supervisord.conf.d/sshd-server.conf" during parsing
2021-08-24 04:58:14,910 INFO RPC interface 'supervisor' initialized
2021-08-24 04:58:14,917 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2021-08-24 04:58:14,926 INFO supervisord started with pid 27
2021-08-24 04:58:15,941 INFO spawned: 'rsyslog' with pid 29
2021-08-24 04:58:16,031 INFO spawned: 'scylla-housekeeping' with pid 30
2021-08-24 04:58:16,114 INFO spawned: 'scylla-jmx' with pid 31
2021-08-24 04:58:16,252 INFO spawned: 'scylla-node-exporter' with pid 32
2021-08-24 04:58:16,406 INFO spawned: 'scylla-server' with pid 36
2021-08-24 04:58:16,535 INFO spawned: 'sshd' with pid 38
rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
rsyslogd: activation of module imklog failed [v8.2001.0 try https://www.rsyslog.com/e/2145 ]
level=info ts=2021-08-24T04:58:17.107Z caller=node_exporter.go:177 msg="Starting node_exporter" version="(version=1.0.1, branch=HEAD, revision=3715be6ae899f2a9b9dbfd9c39f3e09a7bd4559f)"
2021-08-24 04:58:17,131 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-08-24 04:58:17,132 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-08-24 04:58:17,150 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-08-24 04:58:17,172 INFO success: scylla-node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
level=info ts=2021-08-24T04:58:17.124Z caller=node_exporter.go:178 msg="Build context" build_context="(go=go1.14.4, user=root@1f76dbbcfa55, date=20200616-12:44:12)"
level=info ts=2021-08-24T04:58:17.236Z caller=node_exporter.go:105 msg="Enabled collectors"
level=info ts=2021-08-24T04:58:17.249Z caller=node_exporter.go:112 collector=arp
level=info ts=2021-08-24T04:58:17.263Z caller=node_exporter.go:112 collector=bcache
level=info ts=2021-08-24T04:58:17.263Z caller=node_exporter.go:112 collector=bonding
level=info ts=2021-08-24T04:58:17.263Z caller=node_exporter.go:112 collector=btrfs
level=info ts=2021-08-24T04:58:17.263Z caller=node_exporter.go:112 collector=conntrack
level=info ts=2021-08-24T04:58:17.263Z caller=node_exporter.go:112 collector=cpu
2021-08-24 04:58:17,284 INFO success: scylla-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
level=info ts=2021-08-24T04:58:17.264Z caller=node_exporter.go:112 collector=cpufreq
level=info ts=2021-08-24T04:58:17.274Z caller=node_exporter.go:112 collector=diskstats
level=info ts=2021-08-24T04:58:17.275Z caller=node_exporter.go:112 collector=edac
level=info ts=2021-08-24T04:58:17.275Z caller=node_exporter.go:112 collector=entropy
level=info ts=2021-08-24T04:58:17.275Z caller=node_exporter.go:112 collector=filefd
level=info ts=2021-08-24T04:58:17.296Z caller=node_exporter.go:112 collector=filesystem
level=info ts=2021-08-24T04:58:17.296Z caller=node_exporter.go:112 collector=hwmon
level=info ts=2021-08-24T04:58:17.296Z caller=node_exporter.go:112 collector=infiniband
level=info ts=2021-08-24T04:58:17.296Z caller=node_exporter.go:112 collector=interrupts
level=info ts=2021-08-24T04:58:17.296Z caller=node_exporter.go:112 collector=ipvs
level=info ts=2021-08-24T04:58:17.297Z caller=node_exporter.go:112 collector=loadavg
level=info ts=2021-08-24T04:58:17.297Z caller=node_exporter.go:112 collector=mdadm
level=info ts=2021-08-24T04:58:17.306Z caller=node_exporter.go:112 collector=meminfo
level=info ts=2021-08-24T04:58:17.306Z caller=node_exporter.go:112 collector=netclass
level=info ts=2021-08-24T04:58:17.306Z caller=node_exporter.go:112 collector=netdev
level=info ts=2021-08-24T04:58:17.307Z caller=node_exporter.go:112 collector=netstat
level=info ts=2021-08-24T04:58:17.307Z caller=node_exporter.go:112 collector=nfs
level=info ts=2021-08-24T04:58:17.307Z caller=node_exporter.go:112 collector=nfsd
level=info ts=2021-08-24T04:58:17.307Z caller=node_exporter.go:112 collector=powersupplyclass
level=info ts=2021-08-24T04:58:17.329Z caller=node_exporter.go:112 collector=pressure
level=info ts=2021-08-24T04:58:17.336Z caller=node_exporter.go:112 collector=rapl
level=info ts=2021-08-24T04:58:17.336Z caller=node_exporter.go:112 collector=schedstat
level=info ts=2021-08-24T04:58:17.347Z caller=node_exporter.go:112 collector=sockstat
level=info ts=2021-08-24T04:58:17.347Z caller=node_exporter.go:112 collector=softnet
level=info ts=2021-08-24T04:58:17.347Z caller=node_exporter.go:112 collector=stat
level=info ts=2021-08-24T04:58:17.347Z caller=node_exporter.go:112 collector=textfile
level=info ts=2021-08-24T04:58:17.347Z caller=node_exporter.go:112 collector=thermal_zone
level=info ts=2021-08-24T04:58:17.348Z caller=node_exporter.go:112 collector=time
level=info ts=2021-08-24T04:58:17.348Z caller=node_exporter.go:112 collector=timex
level=info ts=2021-08-24T04:58:17.348Z caller=node_exporter.go:112 collector=udp_queues
level=info ts=2021-08-24T04:58:17.348Z caller=node_exporter.go:112 collector=uname
level=info ts=2021-08-24T04:58:17.348Z caller=node_exporter.go:112 collector=vmstat
level=info ts=2021-08-24T04:58:17.348Z caller=node_exporter.go:112 collector=xfs
level=info ts=2021-08-24T04:58:17.349Z caller=node_exporter.go:112 collector=zfs
level=info ts=2021-08-24T04:58:17.362Z caller=node_exporter.go:191 msg="Listening on" address=:9100
level=info ts=2021-08-24T04:58:17.380Z caller=tls_config.go:170 msg="TLS is disabled and it cannot be enabled on the fly." http2=false
2021-08-24 04:58:18,420 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Scylla version 4.6.dev-0.20210822.f98cb9650 with build-id 6a65da570b62b9708745e9eb39019a3a46d0a1b1 starting ...
command used: "/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 2001:db8:1::242:ac11:2 172.17.0.2 --rpc-address 2001:db8:1::242:ac11:2 172.17.0.2 --seed-provider-parameters seeds=2001:db8:1::242:ac11:2 172.17.0.2 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 1, log-to-stdout: 0, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 2001:db8:1::242:ac11:2, (positional) 172.17.0.2, rpc-address: 2001:db8:1::242:ac11:2, (positional) 172.17.0.2, seed-provider-parameters: seeds=2001:db8:1::242:ac11:2, (positional) 172.17.0.2, blocked-reactor-notify-ms: 999999999]
error: too many positional options have been specified on the command line

Try --help.
2021-08-24 04:58:25,869 INFO exited: scylla-server (exit status 2; not expected)
2021-08-24 04:58:26,974 INFO spawned: 'scylla-server' with pid 78
2021-08-24 04:58:28,022 INFO success: scylla-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Scylla version 4.6.dev-0.20210822.f98cb9650 with build-id 6a65da570b62b9708745e9eb39019a3a46d0a1b1 starting ...
command used: "/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 2001:db8:1::242:ac11:2 172.17.0.2 --rpc-address 2001:db8:1::242:ac11:2 172.17.0.2 --seed-provider-parameters seeds=2001:db8:1::242:ac11:2 172.17.0.2 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 1, log-to-stdout: 0, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 2001:db8:1::242:ac11:2, (positional) 172.17.0.2, rpc-address: 2001:db8:1::242:ac11:2, (positional) 172.17.0.2, seed-provider-parameters: seeds=2001:db8:1::242:ac11:2, (positional) 172.17.0.2, blocked-reactor-notify-ms: 999999999]
error: too many positional options have been specified on the command line

Try --help.
2021-08-24 04:58:36,937 INFO exited: scylla-server (exit status 2; not expected)
2021-08-24 04:58:38,019 INFO spawned: 'scylla-server' with pid 91
2021-08-24 04:58:39,073 INFO success: scylla-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 208, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 134, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 93, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 88, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 111] Connection refused>
```

The traceback at the very end happens when container is killed.

**Comment by gleb-cloudius** [comment]
On Mon, Aug 23, 2021 at 10:18:35PM -0700, Dima Tisnek wrote:
> ```
> 2021-08-24 04:58:26,974 INFO spawned: 'scylla-server' with pid 78
> 2021-08-24 04:58:28,022 INFO success: scylla-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> Scylla version 4.6.dev-0.20210822.f98cb9650 with build-id 6a65da570b62b9708745e9eb39019a3a46d0a1b1 starting ...
> command used: "/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 2001:db8:1::242:ac11:2 172.17.0.2 --rpc-address 2001:db8:1::242:ac11:2 172.17.0.2 --seed-provider-parameters seeds=2001:db8:1::242:ac11:2 172.17.0.2 --blocked-reactor-notify-ms 999999999"
Those address configurations do not look right.

> parsed command line options: [log-to-syslog: 1, log-to-stdout: 0, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 2001:db8:1::242:ac11:2, (positional) 172.17.0.2, rpc-address: 2001:db8:1::242:ac11:2, (positional) 172.17.0.2, seed-provider-parameters: seeds=2001:db8:1::242:ac11:2, (positional) 172.17.0.2, blocked-reactor-notify-ms: 999999999]
> error: too many positional options have been specified on the command line
> 
> Try --help.
> ```

**Comment by dimaqq** [comment]
🤔  maybe alternator example expects a setup where several Scylla instances a ran at predefined ip addresses? 🤔

**Comment by gleb-cloudius** [comment]
On Mon, Aug 23, 2021 at 10:59:15PM -0700, Dima Tisnek wrote:
> 🤔  maybe alternator example expects a setup where several Scylla instances a ran at predefined ip addresses? 🤔 
> 
What I mean is that you specify each address twice once as ipv6 and
another as ipv4 with a space in the middle. This is not valid command
line.

--
			Gleb.

**Comment by dimaqq** [comment]
Well I did not specify **any** ip addresses.
(the command I used is at the top of the ticket).

**Comment by dimaqq** [comment]
@nyh re: https://github.com/HENNGE/aiodynamo/issues/27#issuecomment-907713291 is there a simple way to get a developer (free, temporary) access to production (cloud) Scylla Alternator?

**Comment by nyh** [comment]
@dimaqq I believe we do have some sort of very-short-term free trial of Scylla on the cloud in https://cloud.scylladb.com/user/signup but I don't know any details about it. As a Scylla developer, I'm more interested in getting docker (back?) to work, I'll look into that next.

**Comment by dimaqq** [comment]
Ugh, am I hitting [almost] the same issue again:
`'--alternator-address' cannot be specified more than once`

**Comment by ultperf** [comment]
root@cldxs-1:/home/ubuntu# docker run -v /var/lib/scylla:/var/lib/scylla -h cldxs-1 --name cldxs-1 -p 7000:7000 -p 7001:7001 -p 9042:9042 -p 9160:9160 -p 10000:10000 -it scylladb/scylla /bin/bash
```
INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-15 08:45:23,851 INFO exited: scylla (exit status 2; not expected)
2023-03-15 08:45:24,854 INFO spawned: 'scylla' with pid 119
2023-03-15 08:45:24,855 WARN received SIGINT indicating exit request
2023-03-15 08:45:24,857 INFO waiting for rsyslog, scylla, scylla-housekeeping, scylla-jmx, scylla-node-exporter, sshd to die
Scylla version 5.1.6-0.20230223.530600a64674 with build-id c38178ef635d4ac7f67a8a3ce666056c81f5afb9 starting ...
2023-03-15 08:45:25,092 INFO stopped: sshd (terminated by SIGTERM)
2023-03-15 08:45:25,094 INFO stopped: scylla-node-exporter (terminated by SIGTERM)
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --alternator-address 172.17.0.2 --blocked-reactor-notify-ms 999999999 /bin/bash"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.2, rpc-address: 172.17.0.2, seed-provider-parameters: seeds=172.17.0.2, alternator-address: 172.17.0.2, blocked-reactor-notify-ms, (positional) 999999999, (positional) /bin/bash]
error: too many positional options have been specified on the command line
```

running on ubuntu 22.04
how to resolve? what's the issue?
