### ISSUE TITLE
backup_restore_tests.py:TestBackupRestore.failure_durring_snapshot_no_corrupt_data_test fails

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#932]
head commit 4ff1692248a8c7fdbba6d76cd7a755c0daa8000a
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Mon Feb 22 15:45:19 2016 +0200

    cql3: Make 'CREATE TYPE' error message human readable
    
    We don't support the 'CREATE TYPE' statement for now. The user-visible
    error message, however, is unreadable because our CQL parser doesn't
    even recognize the statement.
    
      cqlsh:ks1> CREATE TYPE config (url text);
      SyntaxException: <ErrorMessage code=2000 [Syntax error in CQL query] message=" : cannot match to any predicted input...
    
    Implement just enough of 'CREATE TYPE' parsing to be able to report a
    human readable error message if someone tries to execute such
    statements:
    
      cqlsh:ks1> CREATE TYPE config (url text);
      ServerError: <ErrorMessage code=0000 [Server error] message="User-defined types are not supported yet">
    Message-Id: <1456148719-9473-2-git-send-email-penberg@scylladb.com>

```
shlomi@localhost~/urchin-dtest (master)$ export CASSANDRA_DIR=~/scylla/build/release; pkill -9 scylla; pkill -9 java; rm -Rf core.*; KEEP_TEST_DIR=true  REUSE_CLUSTER=false DEBUG=true PRINT_DEBUG=true nosetests -v -s backup_restore_tests.py:TestBackupRestore.failure_durring_snapshot_no_corrupt_data_test
failure_durring_snapshot_no_corrupt_data_test (backup_restore_tests.TestBackupRestore) ... cluster ccm directory: /home/shlomi/.dtest/dtest-nQ7kn2
Starting a cluster of one node...
Creating a CQL connection...
Creating a keyspace 'ks'...
Creating a column family 'cf'...
Inserting concurrently 1000 keys...
Taking a snapshot...
Starting nodetool snapshot -t testsnapshot...
Wait for 0.909814740791 seconds
Killing a node...
nodetool snapshot -t testsnapshot killed
Restarting node1...
Checking rows on node1...
FAIL

======================================================================
FAIL: failure_durring_snapshot_no_corrupt_data_test (backup_restore_tests.TestBackupRestore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/backup_restore_tests.py", line 63, in failure_durring_snapshot_no_corrupt_data_test
    self.check_rows_on_node(node1, num_keys, found=keys, c1_values=c1_values, c2_values=c2_values)
  File "/home/shlomi/urchin-dtest/backup_restore_tests.py", line 757, in check_rows_on_node
    self.assertEqual(result[0].count, rows, len(result))
AssertionError: 1
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-nQ7kn2
dtest: DEBUG: Starting a cluster of one node...
dtest: DEBUG: Creating a CQL connection...
dtest: DEBUG: Creating a keyspace 'ks'...
dtest: DEBUG: Creating a column family 'cf'...
dtest: DEBUG: Inserting concurrently 1000 keys...
dtest: DEBUG: Taking a snapshot...
dtest: DEBUG: Starting nodetool snapshot -t testsnapshot...
dtest: DEBUG: Wait for 0.909814740791 seconds
dtest: DEBUG: Killing a node...
dtest: DEBUG: nodetool snapshot -t testsnapshot killed
dtest: DEBUG: Restarting node1...
dtest: DEBUG: Checking rows on node1...
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 24.007s

FAILED (failures=1)
```

**Comment by vladzcloudius** [comment]
@penberg @slivne  What happens is that `nodetool snapshot` does not manage to flush the tables' data to disk before node is being killed. However in this case the data expected to be restored from a commit log when the node is restarted. @elcallio could take a look, pls.?

**Comment by slivne** [comment]
Does not reproduce

Tested 5 times on head e194835d8a4e6a2126c599ed95e5b04114e5ce09

We had multiple fixes in commitlog - it was probably resolved by one (or more)
