### ISSUE TITLE
hintedhandoff_sync_point_api_test fails: AssertionError: 'DONE' != 'IN_PROGRESS'

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9320]
This dtest was recently introduced in scylladb/scylla-dtest@770aa863d5e5b4ccc7ea7057d72a6a1f86fa9a45
but failed in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/927/testReport/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_sync_point_api_test/
against scylla 83113d866136cd291368140ca39536e4e7511c4f
(that includes 1b618921becdaa9c7a9ffa8f59c7471cc954332e)
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/hintedhandoff_additional_test.py", line 691, in hintedhandoff_sync_point_api_test
    wait_for_sync_point(sync_point_id, 0, expect="IN_PROGRESS")
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/hintedhandoff_additional_test.py", line 652, in wait_for_sync_point
    self.assertEqual(status.json(), expect)
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 1250, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: 'DONE' != 'IN_PROGRESS'
- DONE
+ IN_PROGRESS
```

@piodul please look into this.

**Comment by slivne** [comment]
@piodul is this fixed ?

**Comment by bhalevy** [comment]
Test passed in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/920/testReport/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_sync_point_api_test/

Looks like we can close the issue.
@piodul please confirm.

**Comment by piodul** [comment]
@slivne @bhalevy 

I looked at previous run of the Jenkins job and found another run which had the fix but didn't pass: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/914/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_sync_point_api_test/ . I managed to reproduce it locally.

Sent another PR which fixes that issue: https://github.com/scylladb/scylla/pull/9426. I ran the dtest with the fix on my machine 30 times and it passed every time.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
