### ISSUE TITLE
nodetool cleanup fails

### ISSUE THREAD

**Issue by christian-lefty** [scylladb/scylla#9396]
nodetool cleanup fails with the given message:

lefty@hetzner-scylla-c:~$ nodetool cleanup 
error: Missing directive: partitioner
-- StackTrace --
org.apache.cassandra.exceptions.ConfigurationException: Missing directive: partitioner
	at org.apache.cassandra.config.DatabaseDescriptor.applyPartitioner(DatabaseDescriptor.java:967)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:190)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:157)
	at org.apache.cassandra.tools.NodeProbe.checkJobs(NodeProbe.java:337)
	at org.apache.cassandra.tools.NodeProbe.forceKeyspaceCleanup(NodeProbe.java:344)
	at org.apache.cassandra.tools.nodetool.Cleanup.execute(Cleanup.java:55)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:270)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:180)

lefty@hetzner-scylla-c:~$ nodetool version 
ReleaseVersion: 3.0.8

lefty@hetzner-scylla-c:~$ curl -X GET "http://localhost:10000/storage_service/scylla_release_version"
"4.5.rc7-0.20210906.edead1caf"

**Comment by slivne** [comment]
@christian-lefty hi 

can you please share your scylla.yaml and some info on the env

I am not able to reproduce this on the docker image

```
[root@some-scylla /]# scylla --version
4.5.rc7-0.20210906.edead1caf
[root@some-scylla /]# nodetool cleanup
WARN  09:55:12,788 Only 7.893GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
[root@some-scylla /]# 

```

**Comment by christian-lefty** [comment]
reading the code a bit I assume the error is referring to this line:

partitioner: org.apache.cassandra.dht.Murmur3Partitioner

indeed our conf does not have it.

I assume it used to work on earlier versions of nodetool but this line is now mandatory. Do you happen to know if it's safe to add it ?

**Comment by slivne** [comment]
Yes its fine to add this its set by default

 - did you upgrade from an older release - if so can you provide the version of the earliest release that you started from ?
 - if you did not upgrade - can you please provide the distribution you are using and the package you installed and how you installed
 
something seems broken and we would like to fix that

**Comment by slivne** [comment]
@christian-lefty  - if you have additional info please post and we can reopen

closing this issue as its stale
