### ISSUE TITLE
got trackback on scyllatop

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#945]
Not sure how reproduce this, but seems related to screen rendering since it is curses error.

```
Traceback (most recent call last):
  File "./scyllatop.py", line 76, in <module>
    curses.wrapper(main, arguments.metricPattern, arguments.interval, collectd)
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./scyllatop.py", line 30, in main
    liveData.go()
  File "/ssd/scylla.1/tools/scyllatop/livedata.py", line 52, in go
    view.update(self)
  File "/ssd/scylla.1/tools/scyllatop/views/means.py", line 17, in update
    self.writeLine(line, index + 1)
  File "/ssd/scylla.1/tools/scyllatop/views/base.py", line 37, in writeLine
    self._window.addstr(line, 0, str(thing))
_curses.error: addstr() returned ERR
```

**Comment by penberg** [comment]
@syuu1228 I think the error means that ``addstr()`` attempted to write beyond window boundaries.

@haarcuba, I guess we need to truncate the output to fit the screen?

**Comment by haarcuba** [comment]
I did truncate it. Perhaps I did it incorrectly. I'll have a look at it. thanks.

**Comment by slivne** [comment]
@syuu1228 did you get this again ?, if not can you close this

**Comment by slivne** [comment]
@syuu1228 ping
