### ISSUE TITLE
scylla_io_setup on GKE: fails with workload identity enabled, since 4.3.x

### ISSUE THREAD

**Issue by kri5** [scylladb/scylla#9471]
*Installation details*
Scylla version (or git commit hash): 4.4.5
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): GKE (over GCE) with scylla-operator through Helm

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): GKE 
Hardware: n2-highmem-8 (8cpus/64GB RAM)
Disks: 1 local-ssd

When running a Scylla cluster on a GKE cluster with workload identity enabled, it fails due to the scylla_io_setup
script, trying to autodetect machine-type of the node, in order to configure it, but it is not supported.

```running: (['/opt/scylladb/scripts/scylla_io_setup'],)
E1012 14:58:42.218721       1 sidecar/probes.go:172] "healthz probe: can't connect to JMX" err="dial tcp 10.133.4.30:10001: connect: connection refused" Service="databases/scylla-X-Y-0"
E1012 14:58:52.218525       1 sidecar/probes.go:172] "healthz probe: can't connect to JMX" err="dial tcp 10.133.4.30:10001: connect: connection refused" Service="databases/scylla-X-Y-0"
E1012 14:59:02.218469       1 sidecar/probes.go:172] "healthz probe: can't connect to JMX" err="dial tcp 10.133.4.30:10001: connect: connection refused" Service="databases/scylla-X-Y-0"
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_io_setup", line 239, in <module>
    if idata.is_recommended_instance():
  File "/opt/scylladb/scripts/scylla_util.py", line 309, in is_recommended_instance
    if not self.is_unsupported_instance_class() and self.is_supported_instance_class() and self.is_recommended_instance_size():
  File "/opt/scylladb/scripts/scylla_util.py", line 261, in is_unsupported_instance_class
    if self.instancetype == self.m1supported:
  File "/opt/scylladb/scripts/scylla_util.py", line 227, in instancetype
    self.__type = self.__instance_metadata("machine-type").split("/")[-1]
  File "/opt/scylladb/scripts/scylla_util.py", line 154, in __instance_metadata
    return curl(self.META_DATA_BASE_URL + path + "?recursive=%s" % str(recursive).lower(),
  File "/opt/scylladb/scripts/scylla_util.py", line 108, in curl
    with urllib.request.urlopen(req, timeout=timeout) as res:
  File "/opt/scylladb/python3/lib64/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/scylladb/python3/lib64/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/scylladb/python3/lib64/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/scylladb/python3/lib64/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/scylladb/python3/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/scylladb/python3/lib64/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 27, in <module>
    setup.io()
  File "/scyllasetup.py", line 67, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 37, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_io_setup']' returned non-zero exit status 1.
```

The way workload identity works on GKE is by replacing the standard metadata service by a GKE metadata server, running inside the cluster, that will intercept all queries to the regular metadata server, in order to be able to map GCE service account permissions to a Kubernetes service account.

The endpoint `http://metadata.google.internal/computeMetadata/v1/instance/machine-type` is not served by this metadata server.

https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#gke_mds

Is there any way of disabling auto detection?

**Comment by avikivity** [comment]
Backported to 4.4, 4.5. 4.6 had it.
