### ISSUE TITLE
Unclear error message on parsing scylla.yaml seeds with space

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#958]
starting scylla with scylla.yaml with seeds with space

- seeds : "127.0.0.1, 127.0.0.2"

causes scylla not to start with

Exits on unhanded exception of type 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >': Invalid argument

```
#0  0x00007ffff7255b3d in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x0000000000537974 in boost::throw_exception<boost::system::system_error> (e=...) at /usr/include/boost/throw_exception.hpp:69
#2  0x0000000000537a4a in boost::asio::detail::do_throw_error (err=...) at /usr/include/boost/asio/detail/impl/throw_error.ipp:32
#3  0x00000000005fafc6 in boost::asio::detail::throw_error (err=...) at /usr/include/boost/asio/detail/throw_error.hpp:35
#4  boost::asio::ip::address_v4::from_string (str=<optimized out>) at /usr/include/boost/asio/ip/impl/address_v4.ipp:103
#5  boost::asio::ip::address_v4::from_string (str=" 10.10.122.127") at /usr/include/boost/asio/ip/impl/address_v4.ipp:119
#6  net::ipv4_address::ipv4_address (addr=" 10.10.122.127", this=<optimized out>) at /home/shlomi/scylla/seastar/net/ip.hh:58
#7  gms::inet_address::inet_address (this=0x7fffffffbee0, addr=...) at ./gms/inet_address.hh:54
#8  0x0000000000f7edbb in <lambda()>::operator()(void) const (__closure=__closure@entry=0x7fffffffc200) at init.cc:107
#9  0x0000000000f80f21 in apply_helper<init_ms_fd_gossiper(sstring, uint16_t, uint16_t, sstring, sstring, sstring, sstring, db::seed_provider_type, sstring, double)::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (args=<optimized out>, func=<optimized out>) at ./seastar/core/apply.hh:34
#10 apply<init_ms_fd_gossiper(sstring, uint16_t, uint16_t, sstring, sstring, sstring, sstring, db::seed_provider_type, sstring, double)::<lambda()> > (args=<optimized out>, func=<optimized out>)
    at ./seastar/core/apply.hh:42
#11 futurize<future<> >::apply<init_ms_fd_gossiper(sstring, uint16_t, uint16_t, sstring, sstring, sstring, sstring, db::seed_provider_type, sstring, double)::<lambda()> > (args=<optimized out>, 
    func=<unknown type in /home/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0xfa2c1f4, DIE 0xfcaec38>) at ./seastar/core/future.hh:1197
#12 future<>::then<init_ms_fd_gossiper(sstring, uint16_t, uint16_t, sstring, sstring, sstring, sstring, db::seed_provider_type, sstring, double)::<lambda()>, future<> > (
    func=<unknown type in /home/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0xfa2c1f4, DIE 0xfcb83db>, this=0x7fffffffc1a0) at ./seastar/core/future.hh:836
#13 init_ms_fd_gossiper (listen_address=..., storage_port=storage_port@entry=7010, ssl_storage_port=ssl_storage_port@entry=7001, ms_encrypt_what=..., ms_trust_store=..., ms_cert=..., ms_key=..., 
    seed_provider=..., cluster_name=..., phi=phi@entry=8) at init.cc:130
#14 0x00000000005ed0f6 in <lambda()>::<lambda()>::<lambda()>::operator() (__closure=0x7fffffffca40) at main.cc:395
#15 apply_helper<main(int, char**)::<lambda()>::<lambda()>::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (args=<optimized out>, func=<optimized out>)
    at /home/shlomi/scylla/seastar/core/apply.hh:34
#16 apply<main(int, char**)::<lambda()>::<lambda()>::<lambda()> > (args=<optimized out>, func=<optimized out>) at /home/shlomi/scylla/seastar/core/apply.hh:42
#17 futurize<future<> >::apply<main(int, char**)::<lambda()>::<lambda()>::<lambda()> > (args=<optimized out>, func=<unknown type in /home/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x15fdf32, DIE 0x19d95e4>)
    at /home/shlomi/scylla/seastar/core/future.hh:1197
#18 future<>::then<main(int, char**)::<lambda()>::<lambda()>::<lambda()>, future<> >(<unknown type in /home/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x15fdf32, DIE 0x1c373f6>) (this=this@entry=0x7fffffffc850, 
    func=func@entry=<unknown type in /home/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x15fdf32, DIE 0x1c373f6>) at /home/shlomi/scylla/seastar/core/future.hh:836
#19 0x00000000005f3e72 in <lambda()>::<lambda()>::operator()(void) const (__closure=__closure@entry=0x6000001315e0) at main.cc:370
#20 0x00000000005f6cfc in apply_helper<main(int, char**)::<lambda()>::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (args=<optimized out>, func=<optimized out>)
    at /home/shlomi/scylla/seastar/core/apply.hh:34
#21 apply<main(int, char**)::<lambda()>::<lambda()> > (args=<optimized out>, func=<optimized out>) at /home/shlomi/scylla/seastar/core/apply.hh:42
#22 futurize<future<> >::apply<main(int, char**)::<lambda()>::<lambda()> > (args=<optimized out>, func=<unknown type in /home/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x15fdf32, DIE 0x19dbbcd>)
    at /home/shlomi/scylla/seastar/core/future.hh:1197
#23 future<>::<lambda(auto:3&&)>::operator()<future_state<> > (state=<unknown type in /home/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x15fdf32, DIE 0x19f23ee>, __closure=0x6000001315c0)
    at /home/shlomi/scylla/seastar/core/future.hh:846
#24 continuation<future<T>::then(Func&&) [with Func = main(int, char**)::<lambda()>::<lambda()>; Result = future<>; T = {}]::<lambda(auto:3&&)> >::run(void) (this=0x6000001315b0)
    at /home/shlomi/scylla/seastar/core/future.hh:400
#25 0x000000000047126d in reactor::run_tasks (this=this@entry=0x600000283000, tasks=...) at core/reactor.cc:1417
#26 0x000000000049c68b in reactor::run (this=0x600000283000) at core/reactor.cc:1721
#27 0x0000000000512bbe in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffd660, ac=ac@entry=19, av=av@entry=0x7fffffffd8d8, 
    func=func@entry=<unknown type in /home/shlomi/.ccm/scylla-1/node1/bin/scylla, CU 0x66f19d, DIE 0x72c2fe>) at core/app-template.cc:127
#28 0x0000000000417c7e in main (ac=19, av=0x7fffffffd8d8) at main.cc:551
```

**Comment by duarten** [comment]
Submitted a patch for scylla to trim ipv4 addresses in the seeds list and submitted another
 to seastar to be more explicit when failing to parse ipv4 addresses.
