### ISSUE TITLE
Replay after schema change dtest failure

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#963]
The ``replay_after_schema_change_test`` dtest fails as follows:

```
[penberg@nero scylla-dtest]$ KEEP_TEST_DIR=true PRINT_DEBUG=true DEBUG=true nosetests -v -s batch_test.py:TestBatch.replay_after_schema_change_test
replay_after_schema_change_test (batch_test.TestBatch) ... cluster ccm directory: /home/penberg/.dtest/dtest-TZq3lt
Creating schema...
Killing node2 so that batch fails
Executing the batch
Execute failed
Altering schema
Killing all other nodes so that they won't remember old schema during replay
Retrying write after timeout. Attempt #0
Starting all nodes
Waiting for batch replay
FAIL

======================================================================
FAIL: replay_after_schema_change_test (batch_test.TestBatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/penberg/scylla-dtest/batch_test.py", line 130, in replay_after_schema_change_test
    assert list(res[i]) == expected, "Expected %s, got %s" % (expected, res[i])
AssertionError: Expected [3, None, 'k3', 'k3'], got Row(id=4, aa=None, firstname=u'k4', lastname=u'k4')
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/penberg/.dtest/dtest-TZq3lt
dtest: DEBUG: Creating schema...
dtest: DEBUG: Killing node2 so that batch fails
dtest: DEBUG: Executing the batch
dtest: DEBUG: Execute failed
dtest: DEBUG: Altering schema
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
dtest: DEBUG: Killing all other nodes so that they won't remember old schema during replay
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
dtest: DEBUG: Retrying write after timeout. Attempt #0
dtest: DEBUG: Starting all nodes
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 8.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 16.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
dtest: DEBUG: Waiting for batch replay
cassandra.connection: WARNING: Heartbeat failed for connection (140043426641872) to 127.0.0.3
Traceback (most recent call last):
  File "cassandra/connection.py", line 963, in cassandra.connection.ConnectionHeartbeat.run (cassandra/connection.c:21641)
    f.wait(self._interval)
  File "cassandra/connection.py", line 903, in cassandra.connection.HeartbeatFuture.wait (cassandra/connection.c:20115)
    raise self._exception
ConnectionShutdown: Connection to 127.0.0.3 was closed
cassandra.connection: WARNING: Heartbeat failed for connection (140043426624784) to 127.0.0.1
Traceback (most recent call last):
  File "cassandra/connection.py", line 963, in cassandra.connection.ConnectionHeartbeat.run (cassandra/connection.c:21641)
    f.wait(self._interval)
  File "cassandra/connection.py", line 903, in cassandra.connection.HeartbeatFuture.wait (cassandra/connection.c:20115)
    raise self._exception
ConnectionShutdown: Connection to 127.0.0.1 was closed
cassandra.cluster: WARNING: Host 127.0.0.1 has been marked down
cassandra.cluster: WARNING: Host 127.0.0.3 has been marked down
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 139.837s

FAILED (failures=1)
```

No errors are present in the Scylla logs.

Tested with the following HEAD:

```
commit 34ed930aa4d1b5aeb7f89939e79d2a671b938b2d
Author: Raphael S. Carvalho <raphaelsc@scylladb.com>
Date:   Mon Feb 29 13:15:14 2016 -0300

    sstables: fix lack of accuracy in disk usage report
```

**Comment by penberg** [comment]
The test passes with a commit that's just before the commitlog IDLification merge commit:

```
commit 995b638d9642fbfe3b19bb0dae14285a5141ec1e
Author: Tomasz Grabiec <tgrabiec@scylladb.com>
Date:   Tue Feb 23 14:27:44 2016 +0100

    mutation_partition_visitor: Fix crash for large blobs
    
    Fixes #927.
    
    The new visiting code builds cell instances using
    atomic_cell::make_*() factory methods, which won't work in LSA context
    because they depend on managed_bytes storage to be linearized. It may
    not be since large blob support. This worked before because we created
    cells from views before which works in all contexts.
    
    Fix by constructing them in standard allocator context.
    
    Message-Id: <1456234064-13608-2-git-send-email-tgrabiec@scylladb.com>
```

@tgrabiec, @pdziepak, @elcallio

**Comment by penberg** [comment]
@slivne No, please don't assign anybody yet! I am in the middle of "git bisect" and we'll know what broke it soon.

**Comment by penberg** [comment]
```
6cec13143262eb0067e3ee38622bdf29493f1b69 is the first bad commit
commit 6cec13143262eb0067e3ee38622bdf29493f1b69
Author: Tomasz Grabiec <tgrabiec@scylladb.com>
Date:   Thu Feb 25 12:59:10 2016 +0100

    query: Switch to IDL-generated views and writers
    
    The query result footprint for cassandra-stress mutation as reported
    by tests/memory-footprint increased by 18% from 285 B to 337 B.
    
    perf_simple_query shows slight regression in throughput (-8%):
    
      build/release/tests/perf/perf_simple_query -c4 -m1G --partitions 100000
    
    Before: ~433k tps
    After:  ~400k tps

:100755 100755 3efd020dcd550a46557888221e8beb088156273c 3930e6075fb43a90592ab28745881ec46a693c97 M	configure.py
:100644 100644 635c24e388a48e3cb6d7bdafd26af33b0b5918ce 139fab87f6b483ecee3760db1cc83718c209cf7c M	database.cc
:040000 040000 ee7bb0f2d2cfdf520fe137ef0e216380d358def8 509ef5dba5c3d96eac31a2e11ee2929587e7ff7f M	idl
:100644 100644 4b3b13d89a24218c2f1ca2deaed9eb18e13d47ba 22ee1737e15ec3c683e7a1bbfd0c632152177631 M	mutation_partition.cc
:100644 100644 1262602c2af1ea708bba3612151112349c5bc312 c2f2f64f146d92de765547ac122894d5717a9c3d M	mutation_partition.hh
:100644 100644 c66efcef571a0054a33511b731eae2687e7cc59f fa6016c209773dd40e182e4f8bca35a5ba2b8fe2 M	mutation_query.cc
:100644 100644 45d010667e135912eedbff49d8d5f1066928a56f 8fa4a923f46a929ae9573cd14d4db8787e5bfffb M	query-result-reader.hh
:100644 100644 ca071e48d408584d6c35a1037b9dd147e01c1ba5 a605a3ccc79e23e93141d3e18503422b8133af5a M	query-result-writer.hh
:100644 100644 64372404ebe2b3b4d814c683b8ff855498978cc8 b647a6b125e574ca7afb0ce21c304a223ce3d871 M	query-result.hh
:100644 100644 94a151b2978c63d16ba520f53daa7cf723bf5356 9fcb237f8c11e91f47d6d67a7393a9e1b94aa9a9 M	query.cc
:100644 100644 d25d2700afffb86ba343c648d938802037af6621 2f83a91e9d27a16749127829d47ba62ff240eb85 M	query_result_merger.hh
```

Ping @tgrabiec
