### ISSUE TITLE
unable to run scylla_rsyslog_setup on Centos7 instance

### ISSUE THREAD

**Issue by aliasgar-dream11** [scylladb/scylla#9674]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2020.1.6-0.20210202.c6a70535c
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=i3.large AWS EC2
Disks: (SSD/HDD, count) SSD, 1 *100G

I ran the following commands to install scylla rsyslog
sudo ./scylla_rsyslog_setup
sudo yum install python3 -y
sudo ./scylla_rsyslog_setup 
sudo pip3 install pyyaml
sudo ./scylla_rsyslog_setup 
sudo yum install python3-devel -y
sudo ./scylla_rsyslog_setup 
sudo pip3 install psutil
sudo ./scylla_rsyslog_setup 
sudo pip3 install distro
sudo ./scylla_rsyslog_setup

Facing this error:
Traceback (most recent call last):
  File "./dist/common/scripts/scylla_rsyslog_setup", line 25, in <module>
    from scylla_util import *
  File "/home/centos/scylla/dist/common/scripts/scylla_util.py", line 41, in <module>
    from scylla_product import PRODUCT
ModuleNotFoundError: No module named 'scylla_product'

need help to resolve this

Thanks

**Comment by avikivity** [comment]
If you're running scylla-enterprise, please file an issue via zendesk so it can be prioritized.

**Comment by avikivity** [comment]
Also, 2020.1.6 is very old (Jan 2021).
