### ISSUE TITLE
crash on alternator ttl test, on aarch64, mode=debug

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#9735]
HEAD: db5678bb7f92e5e128e1edc80ec2d1465e8662b9

```
(gdb) bt
#0  0x0000ffff9f639750 in raise () from /lib64/libc.so.6
#1  0x0000ffff9f6257dc in abort () from /lib64/libc.so.6
#2  0x000000000b636ad8 in __sanitizer::Abort() ()
#3  0x000000000b634cf8 in __sanitizer::Die() ()
#4  0x000000000b61bc6c in __asan::ScopedInErrorReport::~ScopedInErrorReport() ()
#5  0x000000000b61b684 in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) ()
#6  0x000000000b61c1f8 in __asan_report_load1 ()
#7  0x000000000bd0d2f0 in std::_Optional_base<interval_bound<dht::ring_position>, false, false>::_Optional_base (this=<optimized out>, __other=...) at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/optional:501
#8  0x000000000bd0d254 in std::optional<interval_bound<dht::ring_position> >::optional (this=<optimized out>, this@entry=0xfffe4c938bc0) at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/optional:663
#9  0x000000000bd0d1a4 in wrapping_interval<dht::ring_position>::wrapping_interval (this=0xfffe4c938bc0) at ./interval.hh:87
#10 0x000000000bd0d0fc in nonwrapping_interval<dht::ring_position>::nonwrapping_interval (this=<optimized out>) at ./interval.hh:457
#11 0x000000000c1e4e38 in std::_Construct<nonwrapping_interval<dht::ring_position>, nonwrapping_interval<dht::ring_position> const&> (__p=0xfffe4c938bc0, __args=...)
    at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/stl_construct.h:109
#12 0x000000000c1e4d28 in std::__uninitialized_copy<false>::__uninit_copy<nonwrapping_interval<dht::ring_position> const*, nonwrapping_interval<dht::ring_position>*> (__first=<optimized out>, __first@entry=0xffff9348b690, __last=<optimized out>, 
    __last@entry=0xffff9348b708, __result=__result@entry=0xfffe4c938bc0) at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/stl_uninitialized.h:92
#13 0x000000000c1e4c9c in std::uninitialized_copy<nonwrapping_interval<dht::ring_position> const*, nonwrapping_interval<dht::ring_position>*> (__first=0x0, __first@entry=0xffff9348b690, __last=0xffff943ced08, __last@entry=0xffff9348b708, 
    __result=0x0, __result@entry=0xfffe4c938bc0) at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/stl_uninitialized.h:148
#14 0x000000000c1e4a4c in std::__uninitialized_copy_a<nonwrapping_interval<dht::ring_position> const*, nonwrapping_interval<dht::ring_position>*, nonwrapping_interval<dht::ring_position> > (__first=0x0, __first@entry=0xffff9348b690, 
    __last=0xffff943ced08, __last@entry=0xffff9348b708, __result=0x0, __result@entry=0xfffe4c938bc0) at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/stl_uninitialized.h:333
#15 0x000000000c1e4348 in std::vector<nonwrapping_interval<dht::ring_position>, std::allocator<nonwrapping_interval<dht::ring_position> > >::_M_range_initialize<nonwrapping_interval<dht::ring_position> const*> (this=this@entry=0xfffe649ca220, 
    __first=__first@entry=0xffff9348b690, __last=0xffff9348b708) at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/stl_vector.h:1585
#16 0x000000000c138ac4 in std::vector<nonwrapping_interval<dht::ring_position>, std::allocator<nonwrapping_interval<dht::ring_position> > >::vector (this=0xfffe649ca220, __l=..., __a=...)
    at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/stl_vector.h:629
#17 0x0000000010e9da5c in alternator::scan_table (proxy=..., db=..., s=..., abort_source=...) at alternator/ttl.cc:582
#18 0x000000000c9d6614 in std::experimental::coroutine_handle<seastar::internal::coroutine_traits_base<bool>::promise_type>::resume (this=<optimized out>, this@entry=0xffff9315a6a0) at ./seastar/include/seastar/core/std-coroutine.hh:70
#19 0x000000000c9d6398 in seastar::internal::coroutine_traits_base<bool>::promise_type::run_and_dispose (this=0xfffe649c9e90) at ./seastar/include/seastar/core/coroutine.hh:74
#20 0x00000000116c426c in seastar::reactor::run_tasks (this=0xffff98a98100, tq=...) at ./seastar/src/core/reactor.cc:2378
#21 0x00000000116c9a30 in seastar::reactor::run_some_tasks (this=0xffff98a98100) at ./seastar/src/core/reactor.cc:2787
#22 0x00000000116cd660 in seastar::reactor::do_run (this=0xffff98a98100) at ./seastar/src/core/reactor.cc:2956
#23 0x00000000117917fc in seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97::operator()() const (this=0xffff96e01540) at ./seastar/src/core/reactor.cc:4171
#24 0x0000000011790538 in std::__invoke_impl<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(std::__invoke_other, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) (__f=...) at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#25 0x00000000117902b4 in std::__invoke_r<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) (__fn=...)
    at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
#26 0x000000001178f6a8 in std::_Function_handler<void (), seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
#27 0x000000000bf58a3c in std::function<void ()>::operator()() const (this=0xffff94a7f330) at /usr/lib/gcc/aarch64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
#28 0x0000000011613388 in seastar::posix_thread::start_routine (arg=0xffff94a7f330) at ./seastar/src/core/posix.cc:60
#29 0x0000ffffa02b4008 in start_thread () from /lib64/libpthread.so.0
#30 0x0000ffff9f6db59c in thread_start () from /lib64/libc.so.6
(gdb) 
```

**Comment by avikivity** [comment]
This is here:

```c++
static future<bool> scan_table(
    service::storage_proxy& proxy,
    database& db,
    schema_ptr s,
    abort_source& abort_source)
{
    // Check if an expiration-time attribute is enabled for this table.
    // If not, just return false immediately.
    std::optional<std::string> attribute_name = find_tag(*s, TTL_TAG_KEY);
    if (!attribute_name) {
        co_return false;
    }
    // attribute_name may be one of the schema's columns (in Alternator, this
    // means it's a key column), or an element in Alternator's attrs map
    // encoded in Alternator's JSON encoding.
    // FIXME: To make this less Alternators-specific, we should encode in the
    // single key's value three things:
    // 1. The name of a column
    // 2. Optionally if column is a map, a member in the map
    // 3. The deserializer for the value: CQL or Alternator (JSON).
    // The deserializer can be guessed: If the given column or map item is
    // numeric, it can be used directly. If it is a "bytes" type, it needs to
    // be deserialized using Alternator's deserializer.
    bytes column_name = to_bytes(*attribute_name);
    const column_definition *cd = s->get_column_definition(column_name);
    std::optional<std::string> member;
    if (!cd) {
        member = std::move(attribute_name);
        column_name = bytes(executor::ATTRS_COLUMN_NAME);
        cd = s->get_column_definition(column_name);
        tlogger.info("table {} TTL enabled with attribute {} in {}", s->cf_name(), *member, executor::ATTRS_COLUMN_NAME);
    } else {
        tlogger.info("table {} TTL enabled with attribute {}", s->cf_name(), *attribute_name);
    }
    if (!cd) {
        tlogger.info("table {} TTL column is missing, not scanning", s->cf_name());
        co_return false;
    }
    data_type column_type = cd->type;
    // Verify that the column has the right type: If "member" exists
    // the column must be a map, and if it doesn't, the column must
    // (currently) be a decimal_type. If the column has the wrong type
    // nothing can get expired in this table, and it's pointless to
    // scan it.
    if ((member && column_type->get_kind() != abstract_type::kind::map) ||
        (!member && column_type->get_kind() != abstract_type::kind::decimal)) {
        tlogger.info("table {} TTL column has unsupported type, not scanning", s->cf_name());
        co_return false;
    }
    // FIXME: need to persist position in the scan, and start from it instead
    // of the beginning. Alternatively/additionally, can scan from a random
    // position.
    // FIXME: need to pace the scan, not do it all at once.
    // FIXME: consider if we should ask the scan without caching?
    // can we use cache but not fill it?
    scan_ranges_context scan_ctx{s, proxy, std::move(column_name), std::move(member)};
    token_ranges_owned_by_this_shard my_ranges(db, s);
    while (std::optional<dht::partition_range> range = my_ranges.next_partition_range()) {
        // Note that because of issue #9167 we need to run a separate
        // query on each partition range, and can't pass several of
        // them into one partition_range_vector.
        dht::partition_range_vector partition_ranges = {*range};
        // FIXME: if scanning a single range fails, including network errors,
        // we fail the entire scan (and rescan from the beginning). Need to
        // reconsider this. Saving the scan position might be a good enough
        // solution for this problem.
        co_await scan_table_ranges(proxy, scan_ctx, std::move(partition_ranges), abort_source);
    }
    co_return true;
}
```

in the line 

```c++
        dht::partition_range_vector partition_ranges = {*range};
```

**Comment by avikivity** [comment]
/cc @nyh @kbr- 

smells like a coroutine miscompile, but in debug mode?

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
