### ISSUE TITLE
CREATE TABLE with duplicate columns succeeds sometimes

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#975]
The invalid ``CREATE TABLE`` scenario in ``table_test`` fails in CI run at times as follows:

```
====================================================================== 
FAIL: table_test (cql_additional_tests.TestCQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/penberg/scylla-dtest/cql_additional_tests.py", line 1191, in table_test
    matching="code=2200")
  File "/home/penberg/scylla-dtest/assertions.py", line 26, in assert_invalid        
    raise e
AssertionError: Expecting query to be invalid: got None
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/penberg/.dtest/dtest-R0MvBZ
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 312 tests in 11631.933s
```

I created a simplified test case:

```
#!/usr/bin/env python

from cassandra.cluster import Cluster
from cassandra import InvalidRequest

cluster = Cluster(['127.0.0.1'])
session = cluster.connect()

session.execute("CREATE KEYSPACE IF NOT EXISTS ks WITH replication = {'class':'SimpleStrategy', 'replication_factor':1}")
session.set_keyspace("ks")

try:
    session.execute("CREATE TABLE test4 (k int PRIMARY KEY, c int, k text)")
except InvalidRequest as e:
    print(e)
```

which shows that we indeed pass validation some of the time:

```
[penberg@nero scylla]$ ./doit.py 
code=2200 [Invalid query] message="Multiple definition of identifier k"
[penberg@nero scylla]$ ./doit.py 
code=2200 [Invalid query] message="Multiple definition of identifier k"
[penberg@nero scylla]$ ./doit.py 
[penberg@nero scylla]$ ./doit.py 
code=2200 [Invalid query] message="Multiple definition of identifier k"
[penberg@nero scylla]$ ./doit.py 
Traceback (most recent call last):
  File "./doit.py", line 13, in <module>
    session.execute("CREATE TABLE test4 (k int PRIMARY KEY, c int, k text)")
  File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:26565)
  File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:62845)
cassandra.AlreadyExists: Table 'ks.test4' already exists
```

**Comment by penberg** [comment]
@tgrabiec reverting your optimization d376167bd40b2090db83e723c6a4ed8eece49da5 fixes the problem. Can you take a look at this, please?

**Comment by tgrabiec** [comment]
Hmm, my bet is that `_defined_names` is not actually sorted by names but by pointer address
