### ISSUE TITLE
ubuntu 14.04 scylla 0.18 crash 

### ISSUE THREAD

**Issue by rachlenko** [scylladb/scylla#977]
```
root@XXXX:/var/lib/scylla/coredump# gdb /usr/bin/scylla core.scylla-2016-03-02-08\:49\:40-32115 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/.build-id/b2/f525ef023dcc5017d41ab039d40a54a06d5a8d.debug...done.
done.
[New LWP 32122]
[New LWP 32145]
[New LWP 32140]
[New LWP 32161]
[New LWP 32148]
[New LWP 32157]
[New LWP 32149]
[New LWP 32163]
[New LWP 32116]
[New LWP 32147]
[New LWP 32146]
[New LWP 32156]
[New LWP 32158]
[New LWP 32155]
[New LWP 32141]
[New LWP 32162]
[New LWP 32142]
[New LWP 32151]
[New LWP 32153]
[New LWP 32154]
[New LWP 32143]
[New LWP 32159]
[New LWP 32150]
[New LWP 32152]
[New LWP 32160]
[New LWP 32126]
[New LWP 32118]
[New LWP 32115]
[New LWP 32124]
[New LWP 32144]
[New LWP 32127]
[New LWP 32121]
[New LWP 32123]
[New LWP 32125]
[New LWP 32133]
[New LWP 32128]
[New LWP 32132]
[New LWP 32130]
[New LWP 32120]
[New LWP 32117]
[New LWP 32135]
[New LWP 32134]
[New LWP 32129]
[New LWP 32138]
[New LWP 32136]
[New LWP 32131]
[New LWP 32139]
[New LWP 32137]
[New LWP 32119]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f0cb2405cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x00007f0cb2405cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f0cb24090d8 in __GI_abort () at abort.c:89
#2  0x00007f0cb23feb86 in __assert_fail_base (fmt=0x7f0cb254f830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x156a157 "_data_results.size()", 
    file=file@entry=0x156a11f "service/storage_proxy.cc", line=line@entry=1486, 
    function=function@entry=0x157ee80 <service::digest_read_resolver::resolve()::__PRETTY_FUNCTION__> "foreign_ptr<lw_shared_ptr<query::result> > service::digest_read_resolver::resolve()") at assert.c:92
#3  0x00007f0cb23fec32 in __GI___assert_fail (assertion=0x156a157 "_data_results.size()", 
    file=0x156a11f "service/storage_proxy.cc", line=1486, 
    function=0x157ee80 <service::digest_read_resolver::resolve()::__PRETTY_FUNCTION__> "foreign_ptr<lw_shared_ptr<query::result> > service::digest_read_resolver::resolve()") at assert.c:101
#4  0x0000000000450f9e in service::digest_read_resolver::resolve (this=0x609000a3c410)
    at service/storage_proxy.cc:1486
#5  0x0000000000b11284 in service::digest_read_resolver::resolve (this=0x609000a3c410)
    at service/storage_proxy.cc:1462
#6  0x0000000000b2a217 in service::abstract_read_executor::execute(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(future<>)#2}::operator()(future<>) const (__closure=0x609000a51d50, f=...) at service/storage_proxy.cc:1810
#7  0x0000000000b2a5c2 in do_void_futurize_apply<service::abstract_read_executor::execute(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(future<>)#2}, future<> >(std::result_of&&, future<>&&) (
    func=func@entry=<unknown type in /usr/lib/debug/.build-id/b2/f525ef023dcc5017d41ab039d40a54a06d5a8d.debug, CU 0x77dceb6, DIE 0x7cf8dfa>) at /home/ubuntu/workspace/scylla-ubuntu-deb/scylla/seastar/core/future.hh:1139
#8  0x0000000000b2d636 in apply<service::abstract_read_executor::execute(std::chrono::_V2::steady_clock::time_point)::<lambda(future<>)>, future<> > (
    func=<unknown type in /usr/lib/debug/.build-id/b2/f525ef023dcc5017d41ab039d40a54a06d5a8d.debug, CU 0x77dceb6, DIE 0x7b5087d>) at /home/ubuntu/workspace/scylla-ubuntu-deb/scylla/seastar/core/future.hh:1187
#9  operator()<future_state<> > (
---Type <return> to continue, or q <return> to quit---
    state=<unknown type in /usr/lib/debug/.build-id/b2/f525ef023dcc5017d41ab039d40a54a06d5a8d.debug, CU 0x77dceb6, DIE 0x7d3db9a>, __closure=0x609000a51d30)
    at /home/ubuntu/workspace/scylla-ubuntu-deb/scylla/seastar/core/future.hh:882
#10 _ZN12continuationIZN6futureIIEE12then_wrappedIZN7service22abstract_read_executor7executeENSt6chrono10time_pointINS5_3_V212steady_clockENS5_8durationIlSt5ratioILl1ELl1000000000EEEEEEEUlS1_E0_S1_EET0_OT_EUlOT_E_IEE3runEv (
    this=0x609000a51d20) at /home/ubuntu/workspace/scylla-ubuntu-deb/scylla/seastar/core/future.hh:400
#11 0x00000000004ba71f in reactor::run_tasks (this=this@entry=0x609000111000, tasks=...) at core/reactor.cc:1415
#12 0x00000000004e9703 in reactor::run (this=0x609000111000) at core/reactor.cc:1719
#13 0x0000000000506ecc in smp::<lambda()>::operator()(void) const (__closure=0x6000000dad40)
    at core/reactor.cc:2504
#14 0x00000000004bbef9 in dpdk_thread_adaptor (f=<optimized out>) at core/reactor.cc:2312
#15 0x00000000006a1575 in eal_thread_loop ()
#16 0x00007f0cb279c182 in start_thread (arg=0x7f0ca9719700) at pthread_create.c:312
#17 0x00007f0cb24c947d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by penberg** [comment]
Ping @gleb-cloudius

**Comment by avikivity** [comment]
Please upload the core if possible.

**Comment by penberg** [comment]
Backported to 0.18 branch.
