### ISSUE TITLE
disable_autocompaction_alter_and_nodetool_test: compaction sometimes isn't triggered after flush

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9784]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1018/testReport/compaction_test/TestCompaction_with_SizeTieredCompactionStrategy/disable_autocompaction_alter_and_nodetool_test/
Scylla version e032f92c5cf400c6bdc253c0dbba735ce4aafe84
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/compaction_test.py", line 487, in disable_autocompaction_alter_and_nodetool_test
    f'Found no log items for {self.strategy}')
  File "/usr/lib64/python3.7/unittest/case.py", line 722, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Found no log items for SizeTieredCompactionStrategy
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1018/artifact/logs-all.release.2/1639108969192_compaction_test.TestCompaction_with_SizeTieredCompactionStrategy.disable_autocompaction_alter_and_nodetool_test/node1.log
```
Scylla version 4.7.dev-0.20211208.e032f92c5 with build-id dea43123d3ea55e4e3099ea27e039b4914a9f0c0 starting ...

INFO  2021-12-10 04:01:59,916 [shard 0] api - set_tables_autocompaction: enabled=true keyspace=ks tables={to_disable}
INFO  2021-12-10 04:02:46,185 [shard 0] compaction_manager - Asked to stop
```

The test re-enables auto compaction, then writes to the table, flushes and then examines the log to verify that compaction happened.

See https://github.com/scylladb/scylla-dtest/blob/f13ff886ef83b3223f2370f95eb129dae0443c1e/compaction_test.py#L483-L487

And https://github.com/scylladb/scylla-dtest/blob/f13ff886ef83b3223f2370f95eb129dae0443c1e/compaction_test.py#L574-L580

I reproduced this locally, but it took running the test multiple times.

I also hit a similar issue with the reference table that the test doesn't disable/enable auto-compaction for it:
```
FAIL: disable_autocompaction_alter_and_nodetool_test (compaction_test.TestCompaction_with_SizeTieredCompactionStrategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bhalevy/dev/scylla-dtest/compaction_test.py", line 482, in disable_autocompaction_alter_and_nodetool_test
    f'{self.secondary_ks}.{self.secondary_table} should have continued with regular compactions')
AssertionError: False is not true : ks2.std1 should have continued with regular compactions
```

It looks like this could be a genuine problem where compaction is triggered after flush.

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1043/testReport/compaction_test/TestCompaction/test_disable_autocompaction_schema_LeveledCompactionStrategy_/ is still flaky.
```
Error Message
AssertionError: ks2.std1 should have continued with regular compactions
assert 0 > 0
 +  where 0 = len([])
 +    where [] = <bound method Node.grep_log of <ccmlib.scylla_node.ScyllaNode object at 0x7f6a304de910>>('Compacting.+std1', from_mark=199300)
 +      where <bound method Node.grep_log of <ccmlib.scylla_node.ScyllaNode object at 0x7f6a304de910>> = <ccmlib.scylla_node.ScyllaNode object at 0x7f6a304de910>.grep_log
Stacktrace
self = <compaction_test.TestCompaction object at 0x7f6a3044e6d0>

    def test_disable_autocompaction_schema(self):
        """
        Make sure we can disable compaction via the schema compaction parameter 'enabled' = false
        """
        node = self.prepate_testbed(with_compaction=f'{{\'class\':\'{self.strategy}\', '
                                    f'\'enabled\':\'false\'}}')
        disable_mark = self.disable_autocompaction(node=node, ks=self.primary_ks, table=self.primary_table)
        self.fill_table_with_data(node=node, ks=self.primary_ks, table=self.primary_table, keys=1000)
        self.fill_table_with_data(node=node, ks=self.secondary_ks, table=self.secondary_table, keys=1000)
        assert len(node.grep_log(f'Compacting.+{self.primary_table}', from_mark=disable_mark)) == 0, \
            f'Found compaction log items for {self.strategy}'
        assert len(node.grep_log(f'Compacting.+{self.secondary_table}', from_mark=disable_mark)) > 0, \
            f'{self.secondary_ks}.{self.secondary_table} should have continued with regular compactions'
        # should still be disabled after restart:
        node.stop()
        node.start(wait_for_binary_proto=True)
        session = self.patient_cql_connection(node)
        session.execute('use ks')
        assert len(node.grep_log(f'Compacting.+{self.primary_table}', from_mark=disable_mark)) == 0, \
            f'Found compaction log items for {self.strategy}'
        assert len(node.grep_log(f'Compacting.+{self.secondary_table}', from_mark=disable_mark)) > 0, \
            f'{self.secondary_ks}.{self.secondary_table} should have continued with regular compactions'
        # TODO: in Scylla it doesn't work, so i shall run here alter table and update with the `enabled: true`
        # in Scylla 'nodetool enableautocompaction' doesn't work if compaction disabled in schema,
        # so here alter table and update with the `enabled: true`
        session.execute(f"ALTER TABLE {self.primary_table} "
                        f"with compaction = {{'class': '{self.strategy}', 'enabled': 'true'}}")
        self.disable_autocompaction(node=node, ks=self.primary_ks, table=self.primary_table)
    
        enable_mark = self.enable_autocompaction(node=node, ks=self.primary_ks, table=self.primary_table)
        self.fill_table_with_data(node=node, ks=self.primary_ks, table=self.primary_table, keys=1000)
        self.fill_table_with_data(node=node, ks=self.secondary_ks, table=self.secondary_table, keys=1000)
        assert len(node.grep_log(f'Compacting.+{self.primary_table}', from_mark=enable_mark)) > 0, \
            f'Found no log items for {self.strategy}'
>       assert len(node.grep_log(f'Compacting.+{self.secondary_table}', from_mark=enable_mark)) > 0, \
            f'{self.secondary_ks}.{self.secondary_table} should have continued with regular compactions'
E       AssertionError: ks2.std1 should have continued with regular compactions
E       assert 0 > 0
E        +  where 0 = len([])
E        +    where [] = <bound method Node.grep_log of <ccmlib.scylla_node.ScyllaNode object at 0x7f6a304de910>>('Compacting.+std1', from_mark=199300)
E        +      where <bound method Node.grep_log of <ccmlib.scylla_node.ScyllaNode object at 0x7f6a304de910>> = <ccmlib.scylla_node.ScyllaNode object at 0x7f6a304de910>.grep_log

compaction_test.py:432: AssertionError
```

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylla/blob/755cec1199edbb50b81b03c97f5578bd0595e293/compaction/compaction_manager.cc#L678-L684

could be causing this, we should see it with `--logger-log-level compaction_manager=debug`.

**Comment by raphaelsc** [comment]
the test test_disable_autocompaction_schema should probably be changed to watch the log for compaction on ks2, instead of assuming that compaction happened for ks2 by the time we're done filling both keyspaces.

**Comment by bhalevy** [comment]
> the test test_disable_autocompaction_schema should probably be changed to watch the log for compaction on ks2, instead of assuming that compaction happened for ks2 by the time we're done filling both keyspaces.

@raphaelsc , that's right, but I understand from @mikolajsieluzycki that it doesn't solve the problem.
I think that compaction gets postponed and it isn't resumed.

**Comment by bhalevy** [comment]
Apparently, the missing log messages are due to a combination of https://github.com/scylladb/seastar/issues/1012
And https://github.com/scylladb/scylla/blob/23da2b587965d161a763e6c4a81d4ba4fdaa7b65/compaction/compaction.cc#L797
where a log call on one shard may inhibit log messages on other shards.

**Comment by nyh** [comment]
I added a backport candidate tag manually because for some reason it wasn't automatically added when the Seastar issue marked this issue fixed.

The Seastar in branch-5.0 has the broken Seastar commit (63afb6fb0de3317ef6c9fd9d372407eb6c98015c) so the Seastar fix will need to be backported to it.

Older branches (branch-4.6 and older) do not get the broken Seastar commit, so don't need a backport.

**Comment by avikivity** [comment]
Backported to 5.0, only vulnerable branch.
