### ISSUE TITLE
"sctool cluster list" command fails with "gocql: no response received from cassandra within timeout period" error

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla#9811]
_Installation details_ 
Kernel version: `5.11.0-1023-gcp` 
Scylla version (or git commit hash): `4.7.dev-0.20211215.3ac622bdd with build-id c19c7740f10f82f554c1b67da69f82fc48f9386f` 
Cluster size: 6 nodes (i3.4xlarge) 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos-7 `7091148157460162159` (gcp: us-east1)

Scylla running with shards number (live nodes): 
longevity-10gb-3h-master-db-node-e79c455f-0-1 (104.196.189.45 | 10.142.0.7): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-3 (34.75.56.162 | 10.142.0.35): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-4 (34.139.143.201 | 10.142.0.55): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-5 (34.139.25.79 | 10.142.0.153): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-8 (34.138.206.244 | 10.142.0.30): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-9 (34.75.229.123 | 10.142.0.107): 16 shards

Terminated nodes:
longevity-10gb-3h-master-db-node-e79c455f-0-2	(34.139.75.117 | 10.142.0.16): 16 shards, terminated at 2021-12-15 10:37:17.942850
longevity-10gb-3h-master-db-node-e79c455f-0-6	(34.138.78.99 | 10.142.0.156): 16 shards, terminated at 2021-12-15 11:28:20.562269
longevity-10gb-3h-master-db-node-e79c455f-0-7	(34.73.16.92 | 10.142.0.76): 16 shards, terminated at 2021-12-15 11:45:35.004150

Test: `longevity-10gb-3h-gce-test` Test name: `longevity_test.LongevityTest.test_custom_time` Test config file(s):

* [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c5564161c573430b1ee2042445a66c775f8ce483/test-cases/longevity/longevity-10gb-3h.yaml)

**Issue description** 
One single run twice failed (MgmtRepairCli and MgmtBackup nemesis) to run `sudo sctool cluster list` command with the following error:
```
021-12-15 11:37:22.533: (DisruptionEvent Severity.ERROR) period_type=end event_id=09f03605-f7f8-4ecc-9f82-599727c8978e duration=49s: nemesis_name=MgmtBackup target_node=Node longevity-10gb-3h-master-db-node-e79c455f-0-8 [34.138.206.244 | 10.142.0.30] (seed: False) errors=Encountered a bad command exit code!
Command: 'sudo sctool cluster list'
Exit code: 1
Stdout:
Stderr:
Error: list clusters: gocql: no response received from cassandra within timeout period
Trace ID: Ei4lBZz0TECMXV6ftAW0pg (grep in scylla-manager logs)
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3022, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1808, in disrupt_mgmt_backup
self._mgmt_backup(backup_specific_tables=False)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1813, in _mgmt_backup
mgr_cluster = self.cluster.get_cluster_manager()
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4364, in get_cluster_manager
mgr_cluster = manager_tool.get_cluster(cluster_name)
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 793, in get_cluster
cluster_id = cluster.get_cluster_id_by_name(cluster_name)
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 378, in get_cluster_id_by_name
cluster_list = self.sctool.run(cmd="cluster list", is_verify_errorless_result=True)
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1004, in run
res = self.manager_node.remoter.sudo(f"sctool {cmd}")
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
return self.run(cmd=cmd,
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo sctool cluster list'
Exit code: 1
Stdout:
Stderr:
Error: list clusters: gocql: no response received from cassandra within timeout period
Trace ID: Ei4lBZz0TECMXV6ftAW0pg (grep in scylla-manager logs)
```

```
2021-12-15 12:35:10.125: (DisruptionEvent Severity.ERROR) period_type=end event_id=6849818a-ec68-491c-94da-36fc5a2689c7 duration=1m4s: nemesis_name=MgmtRepairCli target_node=Node longevity-10gb-3h-master-db-node-e79c455f-0-8 [34.138.206.244 | 10.142.0.30] (seed: False) errors=Encountered a bad command exit code!
Command: 'sudo sctool cluster list'
Exit code: 1
Stdout:
Stderr:
Error: list clusters: gocql: no response received from cassandra within timeout period
Trace ID: wnLnTqcsTCaWy1YAJ5Ck6A (grep in scylla-manager logs)
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3022, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 166, in wrapped
res = func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1850, in disrupt_mgmt_repair_cli
mgr_cluster = self.cluster.get_cluster_manager()
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4364, in get_cluster_manager
mgr_cluster = manager_tool.get_cluster(cluster_name)
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 793, in get_cluster
cluster_id = cluster.get_cluster_id_by_name(cluster_name)
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 378, in get_cluster_id_by_name
cluster_list = self.sctool.run(cmd="cluster list", is_verify_errorless_result=True)
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1004, in run
res = self.manager_node.remoter.sudo(f"sctool {cmd}")
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
return self.run(cmd=cmd,
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo sctool cluster list'
Exit code: 1
Stdout:
Stderr:
Error: list clusters: gocql: no response received from cassandra within timeout period
Trace ID: wnLnTqcsTCaWy1YAJ5Ck6A (grep in scylla-manager logs)
```

Manager version: `3.0-dev-0.20211214.d2dce13a92c-SNAPSHOT-d2dce13a92c`
Agent version: `3.0-dev-0.20211214.d2dce13a92c-SNAPSHOT-d2dce13a92c`

Restore Monitor Stack command: `$ hydra investigate show-monitor e79c455f-5ba7-4d17-a163-72c141f2c9c0` 
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e79c455f-5ba7-4d17-a163-72c141f2c9c0) 
Show all stored logs command: `$ hydra investigate show-logs e79c455f-5ba7-4d17-a163-72c141f2c9c0`

Test id: `e79c455f-5ba7-4d17-a163-72c141f2c9c0`

Logs: 
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/e79c455f-5ba7-4d17-a163-72c141f2c9c0/20211215_131604/db-cluster-e79c455f.tar.gz 
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/e79c455f-5ba7-4d17-a163-72c141f2c9c0/20211215_131604/loader-set-e79c455f.tar.gz 
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/e79c455f-5ba7-4d17-a163-72c141f2c9c0/20211215_131604/monitor-set-e79c455f.tar.gz 
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/e79c455f-5ba7-4d17-a163-72c141f2c9c0/20211215_131604/sct-runner-e79c455f.tar.gz

[Jenkins job URL](https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/105)

**Comment by vponomaryov** [comment]
Closing this one in favor of this one -> https://github.com/scylladb/scylla-manager/issues/2978
Reason: wrong project for issue.
