### ISSUE TITLE
scylla-gdb: scylla fiber is flaky

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9860]
We hit this quite frequently in next gating tests, e.g.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4360/artifact/testlog/x86_64_release/run.6588.log
```
*** CMD: scylla fiber $task

Provided pointer 0x00006000000af1f0 is not an object managed by seastar or not a task pointer
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/next/scylla/scylla-gdb.py", line 3355, in invoke
    tptr, vptr, name = this_task
TypeError: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/next/scylla/test/scylla-gdb/test.py", line 68, in <module>
    dos('fiber $task')
  File "/jenkins/workspace/scylla-master/next/scylla/test/scylla-gdb/test.py", line 19, in dos
    return do('scylla ' + cmd, known_broken, loudly=True)
  File "/jenkins/workspace/scylla-master/next/scylla/test/scylla-gdb/test.py", line 9, in do
    ret = gdb.execute(cmd)
gdb.error: Error occurred in Python: cannot unpack non-iterable NoneType object
=== TEST.PY SUMMARY START ===
Test exited with code 255
```

@xemul can you please take a look at this?

**Comment by avikivity** [comment]
scylla-gdb problem, not affecting production, not worth the effort to backport.
