### ISSUE TITLE
scylla-gdb test fails on aarch64

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9892]
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/879/artifact/testlog/aarch64_release/run.280.log
```
=== TEST.PY STARTING TEST #280 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/scylla-master/build/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
test/scylla-gdb/run --junit-xml=/jenkins/workspace/scylla-master/build/scylla/testlog/release/xml/run.280.xunit.xml
=== TEST.PY TEST OUTPUT ===
Scylla is: /jenkins/workspace/scylla-master/build/scylla/build/release/scylla.
Booting Scylla on 127.1.5.191 in /jenkins/workspace/scylla-master/build/scylla/testlog/release/scylla-test-1471...
Boot successful (1.6 seconds).
Starting gdb /jenkins/workspace/scylla-master/build/scylla/build/release/scylla
Starting pytest -o junit_family=xunit2 --scylla-pid=1471 --scylla-tmp-dir=/jenkins/workspace/scylla-master/build/scylla/testlog/release/scylla-test-1471 --junit-xml=/jenkins/workspace/scylla-master/build/scylla/testlog/release/xml/run.280.xunit.xml
============================= test session starts ==============================
platform linux -- Python 3.9.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb, configfile: pytest.ini
collected 33 items

test_misc.py ......F..F.F..FFFFFFF.F.F.F..FFFx                           [100%]

=================================== FAILURES ===================================
_____________________________ test_active_sstables _____________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_active_sstables(gdb):
>       scylla(gdb, 'active-sstables')

test_misc.py:36: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'active-sstables'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 1411, in invoke
    for sst in find_active_sstables():
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 1366, in find_active_sstables
    for reader in find_single_sstable_readers():
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 1358, in find_single_sstable_readers
    for obj_addr, vtable_addr in find_vptrs():
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 1283, in find_vptrs
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
_________________________________ test_repairs _________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_repairs(gdb):
>       scylla(gdb, 'repairs')

test_misc.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'repairs'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: No symbol "repair_meta_for_masters" in namespace "debug".

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 4668, in invoke
    for rm in intrusive_list(gdb.parse_and_eval('debug::repair_meta_for_masters._repair_metas'), link='_tracker_link'):
gdb.error: No symbol "repair_meta_for_masters" in namespace "debug".
________________________________ test_heapprof _________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_heapprof(gdb):
>       scylla(gdb, 'heapprof')

test_misc.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'heapprof'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2040, in invoke
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
________________________________ test_mem_range ________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_mem_range(gdb):
>       scylla(gdb, 'mem-range')

test_misc.py:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'mem-range'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2663, in invoke
    gdb.write('0x%x +%d\n' % get_seastar_memory_start_and_size())
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2107, in get_seastar_memory_start_and_size
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
_______________________________ test_mem_ranges ________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_mem_ranges(gdb):
>       scylla(gdb, 'mem-ranges')

test_misc.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'mem-ranges'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2651, in invoke
    for t, start, total_mem in seastar_memory_layout():
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2117, in seastar_memory_layout
    start, total_mem = get_seastar_memory_start_and_size()
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2107, in get_seastar_memory_start_and_size
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
_________________________________ test_memory __________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_memory(gdb):
>       scylla(gdb, 'memory')

test_misc.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'memory'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 1805, in invoke
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
______________________________ test_segment_descs ______________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_segment_descs(gdb):
>       scylla(gdb, 'segment-descs')

test_misc.py:69: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'segment-descs'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: value has been optimized out

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2335, in invoke
    segs = std_vector(gdb.parse_and_eval('\'logalloc\'::shard_segment_pool._store._segments'))
gdb.error: value has been optimized out
_____________________________ test_small_object_1 ______________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_small_object_1(gdb):
>       scylla(gdb, 'small-object -o 32 --random-page')

test_misc.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'small-object -o 32 --random-page'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 4203, in invoke
    self.init_parser()
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 4165, in init_parser
    help="Object size, valid sizes are: {}".format(scylla_small_objects.get_object_sizes()))
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 4145, in get_object_sizes
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
_____________________________ test_small_object_2 ______________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_small_object_2(gdb):
>       scylla(gdb, 'small-object -o 64 --summarize')

test_misc.py:75: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'small-object -o 64 --summarize'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 4203, in invoke
    self.init_parser()
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 4165, in init_parser
    help="Object size, valid sizes are: {}".format(scylla_small_objects.get_object_sizes()))
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 4145, in get_object_sizes
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
___________________________________ test_lsa ___________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_lsa(gdb):
>       scylla(gdb, 'lsa')

test_misc.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>, cmd = 'lsa'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: value has been optimized out

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2415, in invoke
    lsa_mem = int(lsa['_segments_in_use']) * segment_size
gdb.error: value has been optimized out
_______________________________ test_smp_queues ________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_smp_queues(gdb):
>       scylla(gdb, 'smp-queues')

test_misc.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'smp-queues'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 3982, in invoke
    for obj, vptr in find_vptrs():
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 1283, in find_vptrs
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
_____________________________ test_task_histogram ______________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_task_histogram(gdb):
>       scylla(gdb, 'task_histogram')

test_misc.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'task_histogram'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 1239, in invoke
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
_________________________________ test_threads _________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>

    def test_threads(gdb):
>       scylla(gdb, 'threads')

test_misc.py:96: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'threads'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::thread_context::_all_threads' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2860, in invoke
    for t in seastar_threads_on_current_shard():
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2766, in seastar_threads_on_current_shard
    return intrusive_list(gdb.parse_and_eval('\'seastar::thread_context::_all_threads\''), link='_all_link')
gdb.error: 'seastar::thread_context::_all_threads' has unknown type; cast it to its declared type
__________________________________ test_find ___________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
schema = '$schema'

    def test_find(gdb, schema):
>       scylla(gdb, f'find -r {schema}')

test_misc.py:116: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'find -r $schema'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 3474, in invoke
    for ptr_meta, offset in scylla_find.find(int(gdb.parse_and_eval(args.value)), size_char, args.value_range, find_all=args.find_all,
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 3415, in find
    mem_start, mem_size = get_seastar_memory_start_and_size()
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2107, in get_seastar_memory_start_and_size
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
___________________________________ test_ptr ___________________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
schema = '$schema'

    def test_ptr(gdb, schema):
>       scylla(gdb, f'ptr {schema}')

test_misc.py:119: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'ptr $schema'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2288, in invoke
    ptr_meta = self.analyze(ptr)
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2219, in analyze
    for t, start, size in seastar_memory_layout():
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2117, in seastar_memory_layout
    start, total_mem = get_seastar_memory_start_and_size()
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2107, in get_seastar_memory_start_and_size
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
__________________________ test_generate_object_graph __________________________

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
schema = '$schema'
request = <FixtureRequest for <Function test_generate_object_graph>>

    def test_generate_object_graph(gdb, schema, request):
        tmpdir = request.config.getoption('scylla_tmp_dir')
>       scylla(gdb, f'generate-object-graph -o {tmpdir}/og.dot -d 2 -t 10 {schema}')

test_misc.py:123: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

gdb = <module 'gdb' from '/usr/share/gdb/python/gdb/__init__.py'>
cmd = 'generate-object-graph -o /jenkins/workspace/scylla-master/build/scylla/testlog/release/scylla-test-1471/og.dot -d 2 -t 10 $schema'

    def scylla(gdb, cmd):
>       gdb.execute('scylla ' + cmd, from_tty=False, to_string=True)
E       gdb.error: Error occurred in Python: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type

test_misc.py:6: error
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 3916, in invoke
    scylla_generate_object_graph.generate_object_graph(int(gdb.parse_and_eval(args.object)), dot_file,
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 3872, in generate_object_graph
    scylla_generate_object_graph._do_generate_object_graph(address, f, max_depth, max_vertices, timeout_seconds, value_range_override)
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 3844, in _do_generate_object_graph
    edges, vertices = scylla_generate_object_graph._traverse_object_graph_breadth_first(address, max_depth,
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 3796, in _traverse_object_graph_breadth_first
    vertices[address] = (scylla_ptr.analyze(address), resolve(gdb.Value(address).reinterpret_cast(vptr_type).dereference(), cache=False))
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2219, in analyze
    for t, start, size in seastar_memory_layout():
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2117, in seastar_memory_layout
    start, total_mem = get_seastar_memory_start_and_size()
  File "/jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py", line 2107, in get_seastar_memory_start_and_size
    cpu_mem = gdb.parse_and_eval('\'seastar::memory::cpu_mem\'')
gdb.error: 'seastar::memory::cpu_mem' has unknown type; cast it to its declared type
=============================== warnings summary ===============================
test_misc.py::test_nonexistent_scylla_command
  /jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py:1990: DeprecationWarning: invalid escape sequence \-
    branches = (" |-- ", " \-- ")

test_misc.py::test_nonexistent_scylla_command
  /jenkins/workspace/scylla-master/build/scylla/test/scylla-gdb/../../scylla-gdb.py:4558: DeprecationWarning: invalid escape sequence \+
    self._symbol_pattern = re.compile('vtable for (.*) \+ 16.*')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated xml file: /jenkins/workspace/scylla-master/build/scylla/testlog/release/xml/run.280.xunit.xml -
=========================== short test summary info ============================
FAILED test_misc.py::test_active_sstables - gdb.error: Error occurred in Pyth...
FAILED test_misc.py::test_repairs - gdb.error: Error occurred in Python: No s...
FAILED test_misc.py::test_heapprof - gdb.error: Error occurred in Python: 'se...
FAILED test_misc.py::test_mem_range - gdb.error: Error occurred in Python: 's...
FAILED test_misc.py::test_mem_ranges - gdb.error: Error occurred in Python: '...
FAILED test_misc.py::test_memory - gdb.error: Error occurred in Python: 'seas...
FAILED test_misc.py::test_segment_descs - gdb.error: Error occurred in Python...
FAILED test_misc.py::test_small_object_1 - gdb.error: Error occurred in Pytho...
FAILED test_misc.py::test_small_object_2 - gdb.error: Error occurred in Pytho...
FAILED test_misc.py::test_lsa - gdb.error: Error occurred in Python: value ha...
FAILED test_misc.py::test_smp_queues - gdb.error: Error occurred in Python: '...
FAILED test_misc.py::test_task_histogram - gdb.error: Error occurred in Pytho...
FAILED test_misc.py::test_threads - gdb.error: Error occurred in Python: 'sea...
FAILED test_misc.py::test_find - gdb.error: Error occurred in Python: 'seasta...
FAILED test_misc.py::test_ptr - gdb.error: Error occurred in Python: 'seastar...
FAILED test_misc.py::test_generate_object_graph - gdb.error: Error occurred i...
============ 16 failed, 16 passed, 1 xfailed, 2 warnings in 26.11s =============
```

@yaronkaikov 
If this can't be fixed quickly, you should be able skip this test from the arm build job (in release build) using `./test.py --mode release --skip scylla-gdb`

**Comment by nyh** [comment]
Sorry about that. I rewrote the scylla-gdb test framework, but didn't think to test it on arm (and still don't know how... can you run it in qemu?).

But what I don't understand - it seems that most of these errors are real-looking gdb errors (most of them the same error - about `seastar::memory::cpu_mem`), not something that my code reogranization would have caused....  So how did the old scylla-gdb test pass on arm? Did it pass on arm?

**Comment by avikivity** [comment]
I guess you broke eac6fb8d79fca27f43d7bd233b5b8325d682c38a in your rewrite.

**Comment by nyh** [comment]
> I guess you broke [eac6fb8](https://github.com/scylladb/scylla/commit/eac6fb8d79fca27f43d7bd233b5b8325d682c38a) in your rewrite.

How could I have missed this beauty :-)
I can do something similar, unless there is a way to do this in test.py or jenkins?

**Comment by bhalevy** [comment]
I guess there is a way to do this on Jenkins as I mentioned above, using `test.py --skip scylla-gdb`
but it makes sense to disable it test.py or below since it doesn't pass on aarch64 and if someone runs test.py on such a server and expects no regressions, it shouldn't be run.

**Comment by nyh** [comment]
Sent a patch to the mailing list: "test/scylla-gdb: skip tests on aarch64"

**Comment by nyh** [comment]
No need to backport, this fixes a new patch that didn't reach any branch.
