### ISSUE TITLE
nodetool flush timed out after 60 seconds when starting the test's c-s workload

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#9925]
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.6.rc2-0.20220102.e8a1cfb6f with build-id 5d7b96e39c909424e8224207a162fc2c82b67214`
Cluster size: 6 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-1 (63.35.146.122 | 10.0.3.69): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 (18.203.86.153 | 10.0.3.235): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 (52.51.152.223 | 10.0.1.158): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 (52.208.176.176 | 10.0.0.55): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 (63.35.77.2 | 10.0.2.121): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 (18.200.192.236 | 10.0.1.129): 8 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-07d92096e7ab05aae` (aws: eu-west-1)

Test: `longevity-200gb-48h-network-monkey-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-200GB-48h-network-monkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2c3e4506cee8b75c0f4e89b0aefb9f335c52d6dd/test-cases/longevity/longevity-200GB-48h-network-monkey.yaml)

**Issue description**

during the test, once the nodes were all `UN`, we started running stress:
```
2022-01-13 15:30:39.343: (CassandraStressEvent Severity.NORMAL) period_type=begin event_id=b042bb2f-3896-4195-b567-12bd0c86406c: node=Node longevity-200gb-48h-network-4-6-loader-node-2a9bb634-1 [54.155.48.191 | 10.0.3.232] (seed: False)
stress_cmd=cassandra-stress write cl=ALL n=200200300  -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1000 -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=1..200200300 -log interval=15
```

and it finished with success:
```
2022-01-13 16:16:06.545: (CassandraStressEvent Severity.NORMAL) period_type=end event_id=b042bb2f-3896-4195-b567-12bd0c86406c duration=45m27s: node=Node longevity-200gb-48h-network-4-6-loader-node-2a9bb634-1 [54.155.48.191 | 10.0.3.232] (seed: False)
stress_cmd=cassandra-stress write cl=ALL n=200200300  -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1000 -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=1..200200300 -log interval=15
```

after that, we start the test's workload (that will run for the entire test:
```
2022-01-13 16:16:07.447: (CassandraStressEvent Severity.NORMAL) period_type=begin event_id=20f983f6-da45-46ab-be1f-0b811714d56f: node=Node longevity-200gb-48h-network-4-6-loader-node-2a9bb634-1 [54.155.48.191 | 10.0.3.232] (seed: False)
stress_cmd=cassandra-stress write cl=QUORUM duration=2780m  -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=250  -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=400200300..600200300 -log interval=15
```

and a little moment after that, we had a `nodetool flush` that didn't finish within 60 seconds:
```
2022-01-13 16:16:17.807: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=6aa93299-3a77-416b-856a-87cc98b57b5b: nodetool_command=flush node=longevity-200gb-48h-network-4-6-db-node-2a9bb634-1
```

```
2022-01-13 16:17:17.826: (NodetoolEvent Severity.ERROR) period_type=end event_id=6aa93299-3a77-416b-856a-87cc98b57b5b duration=1m0s: nodetool_command=flush node=longevity-200gb-48h-network-4-6-db-node-2a9bb634-1 errors=['Command did not complete within 60 seconds!\n\nCommand: "/usr/bin/nodetool -u cassandra -pw \'cassandra\'  flush "\n\nStdout:\n\n\n\nStderr:\n\n\n\n', 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2569, in run_nodetool\n    result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run\n    result = _run()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner\n    return func(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run\n    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute\n    result = connection.run(**command_kwargs)\n  File "<decorator-gen-3>", line 2, in run\n  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 30, in opens\n    return method(self, *args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 723, in run\n    return self._run(self._remote_runner(), command, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/invoke/context.py", line 102, in _run\n    return runner.run(command, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 380, in run\n    return self._run_body(command, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 442, in _run_body\n    return self.make_promise() if self._asynchronous else self._finish()\n  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 507, in _finish\n    raise CommandTimedOut(result, timeout=timeout)\ninvoke.exceptions.CommandTimedOut: Command did not complete within 60 seconds!\n\nCommand: "/usr/bin/nodetool -u cassandra -pw \'cassandra\'  flush "\n\nStdout:\n\n\n\nStderr:\n\n\n\n\n']
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2569, in run_nodetool
    result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 723, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/context.py", line 102, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 507, in _finish
    raise CommandTimedOut(result, timeout=timeout)
invoke.exceptions.CommandTimedOut: Command did not complete within 60 seconds!

Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  flush "

Stdout:



Stderr:
```

the strange thing in here is that there is any logging info in the node where it ran, so i'm not sure to understand why it took more than 60 seconds, but during the whole time, there were multiple compaction tasks running in the background (could they be delaying the flush?)

Restore Monitor Stack command: `$ hydra investigate show-monitor 2a9bb634-ee64-41dc-a9fb-0d3b4e942466`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2a9bb634-ee64-41dc-a9fb-0d3b4e942466)
Show all stored logs command: `$ hydra investigate show-logs 2a9bb634-ee64-41dc-a9fb-0d3b4e942466`

Test id: `2a9bb634-ee64-41dc-a9fb-0d3b4e942466`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_144009/grafana-screenshot-longevity-200gb-48h-network-monkey-test-scylla-per-server-metrics-nemesis-20220115_144240-longevity-200gb-48h-network-4-6-monitor-node-2a9bb634-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_144009/grafana-screenshot-longevity-200gb-48h-network-monkey-test-scylla-per-server-metrics-nemesis-20220115_144240-longevity-200gb-48h-network-4-6-monitor-node-2a9bb634-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_144009/grafana-screenshot-overview-20220115_144009-longevity-200gb-48h-network-4-6-monitor-node-2a9bb634-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_144009/grafana-screenshot-overview-20220115_144009-longevity-200gb-48h-network-4-6-monitor-node-2a9bb634-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/db-cluster-2a9bb634.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/db-cluster-2a9bb634.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/loader-set-2a9bb634.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/loader-set-2a9bb634.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/monitor-set-2a9bb634.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/monitor-set-2a9bb634.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/sct-runner-2a9bb634.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/sct-runner-2a9bb634.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.6/job/longevity/job/longevity-200gb-48h-network-monkey-test/3/)

**Comment by roydahan** [comment]
It's not a new issue, I can see it at least since October 2021.

**Comment by fgelcer** [comment]
> It's not a new issue, I can see it at least since October 2021.

i'm sure it is not, but i just didn't find any issue specific with `flush` reported...
if you do have one, please refer it to me, and then we will close this one

**Comment by roydahan** [comment]
I didn't find an issue, but I saw results with this error.
