### ISSUE TITLE
Node aborted with coredump during simple nodetool repair

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#9961]
*Installation details*
Scylla version (or git commit hash): 4.7.dev-0.20220118.985403ab9 with build-id d48bc5d3676f53140f58fae39086e98f17a58534
Cluster size:5
OS (RHEL/CentOS/Ubuntu/AWS AMI):ami-057906d0f869ccd53 (eu-west-1)
Scenario: 
* https://github.com/scylladb/scylla-cluster-tests/blob/master/test-cases/longevity/longevity-large-partition-3h.yaml
* https://github.com/scylladb/scylla-cluster-tests/blob/master/configurations/db-nodes-shards-random.yaml

At `04:27:51,949` a regular repair has started:
`/usr/bin/nodetool  repair -- system_auth`

At `2022-01-23T04:27:53` node 4's shard 4 was aborted, right after the repair has started:
```
2022-01-23T04:27:50+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |  [shard 1] schema_tables - Schema version changed to e1891850-f71e-3308-a574-cea6b32ff03c
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |  [shard 3] repair - repair[cf962924-d72e-414e-8321-4b7ea3f22631]: Started to process repair_flush_hints_batchlog_request from node=10.0.2.34, target_nodes=[10.0.3.102, 10.0.3.245, 10.0.0.100, 10.0.2.12, 10.0.2.34], hints_timeout=300s, batchlog_timeout=300s
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |  [shard 3] repair - repair[cf962924-d72e-414e-8321-4b7ea3f22631]: Started to flush hints for repair_flush_hints_batchlog_request from node=10.0.2.34, target_nodes=[10.0.3.102, 10.0.3.245, 10.0.0.100, 10.0.2.12, 10.0.2.34]
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |  [shard 3] repair - repair[cf962924-d72e-414e-8321-4b7ea3f22631]: Started to flush batchlog for repair_flush_hints_batchlog_request from node=10.0.2.34, target_nodes=[10.0.3.102, 10.0.3.245, 10.0.0.100, 10.0.2.12, 10.0.2.34]
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |  [shard 3] repair - repair[cf962924-d72e-414e-8321-4b7ea3f22631]: Finished to flush hints for repair_flush_hints_batchlog_request from node=10.0.2.34, target_hosts=[10.0.3.102, 10.0.3.245, 10.0.0.100, 10.0.2.12, 10.0.2.34]
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |  [shard 3] repair - repair[cf962924-d72e-414e-8321-4b7ea3f22631]: Finished to flush batchlog for repair_flush_hints_batchlog_request from node=10.0.2.34, target_nodes=[10.0.3.102, 10.0.3.245, 10.0.0.100, 10.0.2.12, 10.0.2.34]
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |  [shard 3] repair - repair[cf962924-d72e-414e-8321-4b7ea3f22631]: Finished to process repair_flush_hints_batchlog_request from node=10.0.2.34, target_nodes=[10.0.3.102, 10.0.3.245, 10.0.0.100, 10.0.2.12, 10.0.2.34]
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO | Aborting on shard 4.
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO | Backtrace:
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x424fef8
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x4280802
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x7fdf1d8efa1f
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   /opt/scylladb/libreloc/libc.so.6+0x3d2a1
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   /opt/scylladb/libreloc/libc.so.6+0x268a3
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x42337e1
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x375773d
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x3757ff8
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x3458155
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x358cfb8
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x4260e54
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x4262227
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x4280d05
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   0x42341ba
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   /opt/scylladb/libreloc/libpthread.so.0+0x9298
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !    INFO |   /opt/scylladb/libreloc/libc.so.6+0x100352
2022-01-23T04:27:53+00:00 longevity-large-partitions-3h-maste-db-node-f5ae3df0-4 !     ERR |  [shard 2] reader_concurrency_semaphore - reader_permit::impl::~impl(): permit system_auth.role_members:repair-meta detected a leak of {count=1, memory=16384} resources, at: 0x45ee67e 0x45eeb70 0x45eee78 0x4233763 0x375773d 0x3757ff8 0x3458155 0x358cfb8 0x4260e54 0x4262227 0x4280d05 0x42341ba /opt/scylladb/libreloc/libpthread.so.0+0x9298 /opt/scylladb/libreloc/libc.so.6+0x100352
```
Coredump:
```
backtrace=           PID: 14015 (scylla)
           UID: 113 (scylla)
           GID: 119 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Sun 2022-01-23 04:27:53 UTC (2min 37s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 100 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --smp 5 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-7 --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: scylla-server.slice
       Boot ID: 75aa826c2772440199a936920e0387c1
    Machine ID: 122c2e3e25124b2dbcf5ddb2c894c926
      Hostname: longevity-large-partitions-3h-maste-db-node-f5ae3df0-4
       Storage: /var/lib/systemd/coredump/core.scylla.113.75aa826c2772440199a936920e0387c1.14015.1642912073000000000000
       Message: Process 14015 (scylla) of user 113 dumped core.
                
                Stack trace of thread 14019:
                #0  0x00007fdf1cd342a2 raise (libc.so.6 + 0x3d2a2)
                #1  0x00007fdf1cd1d950 abort (libc.so.6 + 0x26950)
                #2  0x00000000042337e2 _ZN7seastar26on_internal_error_noexceptERNS_6loggerESt17basic_string_viewIcSt11char_traitsIcEE (scylla + 0x40337e2)
                #3  0x000000000375773e _ZN13reader_permit4implD2Ev (scylla + 0x355773e)
                #4  0x0000000003757ff9 _ZN13reader_permit4implD0Ev (scylla + 0x3557ff9)
                #5  0x0000000003458156 _ZN11repair_metaD2Ev (scylla + 0x3258156)
                #6  0x000000000358cfb9 _ZN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZN11repair_meta29repair_row_level_stop_handlerEN3gms12inet_addressEjNS_13basic_sstringIcjLj15ELb1EEES8_20nonwrapping_intervalIN3dht5tokenEEEUlvE_ZNS_6futureIvE14then_impl_nrvoISD_SF_EET0_OT_EUlOS3_RSD_ONS_12future_stateINS1_9monostateEEEE_vE15run_and_disposeEv (scylla + 0x338cfb9)
                #7  0x0000000004260e55 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x4060e55)
                #8  0x0000000004262228 _ZN7seastar7reactor6do_runEv (scylla + 0x4062228)
                #9  0x0000000004280d06 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE5$_100E9_M_invokeERKSt9_Any_data (scylla + 0x4080d06)
                #10 0x00000000042341bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x40341bb)
                #11 0x00007fdf1d8e5299 start_thread (libpthread.so.0 + 0x9299)
                #12 0x00007fdf1cdf7353 __clone (libc.so.6 + 0x100353)
...
download_instructions=gsutil cp gs://upload.scylladb.com/core.scylla.113.75aa826c2772440199a936920e0387c1.14015.1642912073000000000000/core.scylla.113.75aa826c2772440199a936920e0387c1.14015.1642912073000000000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.113.75aa826c2772440199a936920e0387c1.14015.1642912073000000000000.gz
```

The repair process ended up failing with the following:
```
Command: '/usr/bin/nodetool  repair -- system_auth'

Exit code: 2

Stdout:

[2022-01-23 04:27:53,085] Starting repair command #1, repairing 1 ranges for keyspace system_auth (parallelism=SEQUENTIAL, full=true)
[2022-01-23 04:30:09,192] Repair session 1 failed
[2022-01-23 04:30:09,193] Repair session 1 finished

Stderr:

error: Repair job has failed with the error message: [2022-01-23 04:30:09,192] Repair session 1 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2022-01-23 04:30:09,192] Repair session 1 failed
        at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
        at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

Logs:
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                             Log links for testrun with test id f5ae3df0-e9a6-4a9c-95ec-16642dce903a                                             |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                            |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------+
| 20220123_043250 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/f5ae3df0-e9a6-4a9c-95ec-16642dce903a/20220123_043250/db-cluster-f5ae3df0.tar.gz  |
| 20220123_043250 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/f5ae3df0-e9a6-4a9c-95ec-16642dce903a/20220123_043250/loader-set-f5ae3df0.tar.gz  |
| 20220123_043250 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/f5ae3df0-e9a6-4a9c-95ec-16642dce903a/20220123_043250/monitor-set-f5ae3df0.tar.gz |
| 20220123_043250 | sct         | https://cloudius-jenkins-test.s3.amazonaws.com/f5ae3df0-e9a6-4a9c-95ec-16642dce903a/20220123_043250/sct-runner-f5ae3df0.tar.gz  |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by slivne** [comment]
reader permit crash

**Comment by bhalevy** [comment]
Should be fixed by a65b38a9f72dcd5060ecd7a1614d58e820598e2c

**Comment by denesb** [comment]
> @denesb is this fixed by [a65b38a](https://github.com/scylladb/scylla/commit/a65b38a9f72dcd5060ecd7a1614d58e820598e2c) ?

yes

**Comment by slivne** [comment]
closing

**Comment by avikivity** [comment]
@denesb any branches need backport? I think not but please verify.

**Comment by denesb** [comment]
> @denesb any branches need backport? I think not but please verify.

Only 4.6 and it already has it.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
