### ISSUE TITLE
Support for IMDSv2

### ISSUE THREAD

**Issue by qtheya** [scylladb/scylla#9987]
Please add support for [IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) to scylla util script.

```
Failed to grab http://169.254.169.254/latest/meta-data/block-device-mapping/...
Failed to grab http://169.254.169.254/latest/meta-data/block-device-mapping/...
Failed to grab http://169.254.169.254/latest/meta-data/block-device-mapping/...
Failed to grab http://169.254.169.254/latest/meta-data/block-device-mapping/...
Failed to grab http://169.254.169.254/latest/meta-data/block-device-mapping/...
Traceback (most recent call last):
  File "/opt/scylladb/scylla-machine-image/scylla_create_devices", line 194, in <module>
    get_disk_bundles()
  File "/opt/scylladb/scylla-machine-image/scylla_create_devices", line 133, in get_disk_bundles
    devmap = curl_instance_data('http://169.254.169.254/latest/meta-data/block-device-mapping/')
  File "/opt/scylladb/scylla-machine-image/scylla_create_devices", line 45, in curl_instance_data
    return urllib.request.urlopen(req).read().decode("utf-8")
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/opt/scylladb/scylla-machine-image/scylla_k8s_node_setup", line 65, in <module>
    run('/opt/scylladb/scylla-machine-image/scylla_create_devices --scylla-data-root {}'.format(root_disk))
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scylla-machine-image/scylla_create_devices', '--scylla-data-root', '/mnt/hostfs/mnt/raid-disks/disk0']' returned non-zero exit status 1
```
Here is example in [aws-node-termination-handler](https://github.com/aws/aws-node-termination-handler/blob/main/pkg/ec2metadata/ec2metadata.go#L213) (go) from AWS guys that you can be inspired by

Scylla version (4.5.3)
OS (AWS AMI/EKS default)
Platform (AWS)

**Comment by tzach** [comment]
@yaronkaikov FYI

**Comment by tchaikov** [comment]
per @mykaul , 

> We do not fully support IMDSv2.
> we need to create a meta-issue describe all places we need to fix. perftune.py for example, snitches I believe, etc. Don't  recall Monitoring AMI, Manager was fixed,
